### ISSUE TITLE
Change default module to commonjs

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript#6807]
As noted in https://github.com/Microsoft/TypeScript/issues/6735, the default `--module` flag should be `commonJs` and not `none`.

**Comment by mikekidder** [comment]
Hey, just wanted to say.... you guys are awesome!!  Really enjoying all the new functionality in VSCode and Typescript.  Thanks!

**Comment by billti** [comment]
Fixed in #7016
