### ISSUE TITLE
JsDoc optional params with [] syntax breaks JSDoc comments in signature help

### ISSUE THREAD

**Issue by billti** [Microsoft/TypeScript#6810]
The last two parameters below don't show the description in the signature help for that parameter, the first two do. It appears to be the `[name]` syntax that breaks this.

```javascript
/**
 * @param {string} p1 - A string param
 * @param {string?} p2 - An optional param 
 * @param {string} [p3] - Another optional param
 * @param {string} [p4="test"] - An optional param with a default value
 */
function f1(p1, p2, p3, p4){}
```

**Comment by RyanCavanaugh** [comment]
Moving to TS2.0 milestone since this involves a lot more work than we anticipated

**Comment by Elarcis** [comment]
Has this fix been implemented in TS 2.0.3? Because I'm using this version in VSCode (and I'm certain I'm overriding the TS version via my workspace settings), and this issue's still there.

It also breaks the syntax highlighting of jsdoc, I think I'm going to submit a separate issue on the grammar repo for that.

**Comment by sandersn** [comment]
No, it's going to ship in 2.1. If you `npm install typescript@next` and then point your VSCode there you should see the fix.

**Comment by mhegazy** [comment]
VSCode ships with an older version of TypeScript. Please see [Using Newer TypeScript Versions](https://code.visualstudio.com/docs/languages/typescript#_using-newer-typescript-versions) documentation for more details on updating your VSCode to use a different version of TypeScript.

**Comment by Elarcis** [comment]
Thanks, indeed I installed the latest build and it works.

@mhegazy : "and I'm certain I'm overriding the TS version via my workspace settings"
