### ISSUE TITLE
Default/rest arguments should be disallowed on functions containing "use strict" prologue

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#6815]
As per [14.1.2 Function Definitions - Static Semantics: Early Errors](http://tc39.github.io/ecma262/#sec-function-definitions-static-semantics-early-errors) pointed out by @bterlson's [tweet](https://twitter.com/bterlson/status/694326315160203264) :smile:.

This should error:

``` ts
function f(a = 10) {
    "use strict";
}
```

This should continue not to error:

``` ts
export var foo = 10;

function f(a = 10) {
}
```

This should also continue not to error:

``` ts
function container() {
    "use strict";

    function f(a = 10) {
    }
}
```

**Comment by bterlson** [comment]
Note that this also applies to method definitions (both object literal and class kinds)!

**Comment by RyanCavanaugh** [comment]
What makes the first example an error?

**Comment by RyanCavanaugh** [comment]
OK, I read the tweet.

I don't think we can definitively say that any code is necessarily is *not* in strict mode. It could be bundled in to a single file that has a strict mode declaration at the top.

Also, if we downlevel the default, it doesn't matter if the code is in strict mode or not.

**Comment by DanielRosenwasser** [comment]
As per #25616, it sounds like this should also cover destructuring assignments. I'm not sure why though offhandedly.
