### ISSUE TITLE
allowJs: cannot find file abc.js

### ISSUE THREAD

**Issue by d180cf** [Microsoft/TypeScript#6817]
I gave this feature a try and got a curious error: the language service claims that the js file doesn't exist, while tsc doesn't see any problems. I simply included a js file with `var abc = 123;` into a ts file:

```ts
///<references path="abc.js" />
```

In procmon I see that devenv.exe discovers and reads `abc.js`.

**Comment by mhegazy** [comment]
The visual studio plugin does not track .js files, when it sees one in the context it ignores it.

**Comment by billti** [comment]
Hmmm, this is going to be interesting. Until Salsa is on by default in VS, then your TypeScript context will see it, but when you open it it will be the old JSLS that handles the editing experience. Need to think on this one...

**Comment by mhegazy** [comment]
it is not just editing.. it is the just ignoring it even it was closed.

**Comment by ulrichb** [comment]
It seems that as of TS 1.8.6 the VS addin doesn't support `--allowJs` at all.

* There is no UI to configure `--allowJs` (had to add a `<TypeScriptAllowJS>True</TypeScriptAllowJS>` MSBuild property in the .csproj).

* I get the following errors in VS, although this code compiles fine in MSBuild with `tsc.exe`.

MyJavaScript.js:
```JavaScript
function insideMyJavaScript() {
    console.log('insideMyJavaScript');
}
```
```TypeScript
/// <reference path="./MyJavaScript.js"/>
//  ^__ VS shows "File '..../MyJavaScript.js' not found."

function insideReferenceJavascriptTs(): void {
    // VS shows "Cannot find name 'insideMyJavaScript'."
    insideMyJavaScript();
}
```

**Comment by mhegazy** [comment]
This should be addressed in the next version of VS 15 preview build.
