### ISSUE TITLE
Add a compiler option to turn off "use strict" emit in modules

### ISSUE THREAD

**Issue by dasa** [Microsoft/TypeScript#6819]
This 1.8 breaking change prevents integration with legacy libraries. See discussion at:
https://github.com/Microsoft/TypeScript/issues/3576#issuecomment-176746752

**Comment by mhegazy** [comment]
new flag is `--noImplicitUseStrict`.

**Comment by dasa** [comment]
Thanks! This should probably be mentioned at:
https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes#modules-are-now-emitted-with-a-use-strict-prologue

**Comment by mhegazy** [comment]
thanks. done.
