### ISSUE TITLE
New Website Logo: Aurelia

### ISSUE THREAD

**Issue by behzad888** [Microsoft/TypeScript#6820]
Please fill the following out:

- Name: Aurelia
- Homepage url: http://aurelia.io/
- Brand Guidelines/Licensing: null
- Logo: http://aurelia.io/images/main-logo.svg

> Example:
>
> Name: Microsoft
> Homepage url: https://microsoft.com
> Brand Guidelines/Licensing: https://www.microsoft.com/en-us/legal/intellectualproperty/trademarks/usage/logo.aspx
> Logo: https://news.microsoft.com/microsoft-news-center-photos/msft_logo_rgb_c-gray/

**Comment by mhegazy** [comment]
Logo uploaded, should be out in the next site refresh.
