### ISSUE TITLE
New Website Logo: Dorsa

### ISSUE THREAD

**Issue by behzad888** [Microsoft/TypeScript#6821]
Please fill the following out:

- Name: Dorsa
- Homepage url: http://dorsaportal.com/
- Brand Guidelines/Licensing: null
- Logo:  http://dorsaportal.com/dorsapax/data/sub_0/template/template2/img/logo.png

> Example:
>
> Name: Microsoft
> Homepage url: https://microsoft.com
> Brand Guidelines/Licensing: https://www.microsoft.com/en-us/legal/intellectualproperty/trademarks/usage/logo.aspx
> Logo: https://news.microsoft.com/microsoft-news-center-photos/msft_logo_rgb_c-gray/

**Comment by mhegazy** [comment]
Logo uploaded, should be out in the next site refresh.
