### ISSUE TITLE
Required parameter allows after initializable optional parameter

### ISSUE THREAD

**Issue by falsandtru** [microsoft/TypeScript#6823]
Invalid TypeScript syntax.

https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#a-grammar

``` ts
function f(a?, b) {} // error
function g(a = 0, b) {} // should be an error
```

**Comment by Arnavion** [comment]
It's valid ES6 syntax.

```javascript
g(); // 0, undefined
g(5); // 5, undefined
g(5, 6); // 5, 6
g(undefined, 6); // 0, 6
```

**Comment by falsandtru** [comment]
Is this valid TypeScript syntax?

**Comment by Arnavion** [comment]
All valid ES6 syntax needs to be valid TS syntax.

**Comment by RyanCavanaugh** [comment]
@falsandtru Just because the *grammar* allows it doesn't mean it's legal.  This case is covered at https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#3922-parameter-list

> A signature's parameter list consists of zero or more required parameters, followed by zero or more optional parameters, finally followed by an optional rest parameter.

**Comment by falsandtru** [comment]
It spec explains about optional parameters(includes initializer), but it does not explain about the difference of optional parameters between `?` modifier and initializer in this case.

>  OptionalParameter:
   AccessibilityModifieropt BindingIdentifierOrPattern ? TypeAnnotationopt
   AccessibilityModifieropt BindingIdentifierOrPattern TypeAnnotationopt Initializer
   BindingIdentifier ? : StringLiteral

**Comment by RyanCavanaugh** [comment]
Oh, I see what you mean now. We just need to update the spec

**Comment by falsandtru** [comment]
Thanks.

**Comment by RyanCavanaugh** [comment]
This behaves as expected now
