### ISSUE TITLE
';' is missing after return statement for a non-simple converted loop

### ISSUE THREAD

**Issue by T18970237136** [Microsoft/TypeScript#6824]
Hi,

when using current LKG [typescriptService.js](https://github.com/Microsoft/TypeScript/blob/4b284abd5199b22e21d4770325759235ec523447/lib/typescriptServices.js), when transpiling the following code to ES5:
```typescript
(function(): number {
    for (let i = 0; i < 10; i++) {
        (() => i)();
        if (i == 5)
            return i;
        else if (i == 6)
            break;
    }
    return null;
})();
```
it will be transpiled to this JS:
```javascript
(function () {
    var _loop_1 = function(i) {
        (function () { return i; })();
        if (i == 5)
            return { value: i };
        else if (i == 6)
            return "break";
    };
    for (var i = 0; i < 10; i++) {
        var state_1 = _loop_1(i);
        if (typeof state_1 === "object") return state_1.value
        if (state_1 === "break") break;
    }
    return null;
})();
```

Note that the semicolon (;) after `return state_1.value` is missing.
ATM this doesn't cause a problem (with "if" or "}" in the next line), but I think the semicolon should be emitted to avoid issues when the next line contains e.g. something like `+4;`, as this would be interpreted as part of the return statement.

The cause is in [emitter.ts, line 3165](https://github.com/Microsoft/TypeScript/blob/085593375723006b81d6c0278df98206c389c82b/src/compiler/emitter.ts#L3165):
```typescript
write(`return ${loopResult}.value`);
```

Thanks!

**Comment by mhegazy** [comment]
PRs are welcomed.

**Comment by DanielRosenwasser** [comment]
Thanks @T18970237136!
