### ISSUE TITLE
qualified types in function header only with named parameter

### ISSUE THREAD

**Issue by fphh** [Microsoft/TypeScript#6830]
This gives a compile error:
```

module b {
  interface t {}
}

abstract class A {
  abstract f(b.t) : void;
}

```
This compiles:
```

module b {
  interface t {}
}

abstract class A {
  abstract f(x : b.t) : void;
}

```
Qualifying the type t makes it necessary to name the parameter of the function although this should not be necessary.

This again works:
```

module b {
  interface t {}
}

abstract class A {
  type t = b.t;
  abstract f(t) : void;
}

```

**Comment by fphh** [comment]
I use compiler version 1.7.5.

**Comment by Arnavion** [comment]
That last example doesn't do what you think it does. `abstract f(t): void` doesn't define a method which takes one parameter of type `t`, it defines a method which takes one parameter of type `any`.

In general, signatures in TS (function signatures, indexer signatures, etc.) have parameter name required and type optional. So reversing this for abstract method signatures will just cause confusion.

Also having parameter names is descriptive. Also, if you want to attach JSDoc you need to have a parameter name.

**Comment by fphh** [comment]
Yes, I see my mistake. However it is strange that parameter names are mandatory and parameter types are optional. Note that we define already the arity of the function, and, thus, a partial type for it. Why not defining the whole type and making the parameter names optional? I think, that's a design question and I consider this issue closed.

**Comment by Arnavion** [comment]
As I said, everywhere else parameter names are required and types optional.

Defining a function - `function foo(a, b) { }` or `function foo(a: number, b: string) { }`
Defining a method - `class Foo { bar(a, b) { } }` or `class Foo { bar(a: number, b: string) { } }`

So as I said it would be confusing to change the rules only for abstract methods and make it that `abstract bar(a, b)` means a and b are types.

**Comment by RyanCavanaugh** [comment]
Please read the FAQ.
