### ISSUE TITLE
Type alias is not possible when defining abstract method.

### ISSUE THREAD

**Issue by fphh** [Microsoft/TypeScript#6832]
This gives an compile error:
```

type t = () => void;

abstract class A {
   abstract f : t
}

```
This compiles:
```

abstract class A {
  abstract f () : void; 
}

```
Shouldn't both be possible if we support type aliases?

I used Typescript 1.7.5.

**Comment by mhegazy** [comment]
looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/4669

**Comment by fphh** [comment]
I don't see that #4669 has to do with type aliases. Actually, I think that, if my first example does not compile, this means type aliasing is not fully implemented or broken.

**Comment by cvsguimaraes** [comment]
Please reopen this one.

**Comment by mhegazy** [comment]
abstract properties are not  legal in TS today. #4669 tracks enabling it. This has nothing to do with type aliases..  `abstract class  C { abstract c: number; }` still does not compiler.

**Comment by fphh** [comment]
If we had abstract properties, then my first example would compile? Note, that by type _f_ is still a method, not an property (even if it looks syntactically like a property).

**Comment by mhegazy** [comment]
> If we had abstract properties, then my first example would compile?

yes. this is #4669
