### ISSUE TITLE
Enable/disable implicit TS files references in Visual Studio

### ISSUE THREAD

**Issue by usarskyy** [Microsoft/TypeScript#6834]
As a developer I'd like to be able to enable/disable implicit referencing of TS files in Visual Studio.

I described [my issue on SO](http://stackoverflow.com/questions/35137446/disable-typescript-files-auto-discovery-in-visual-studio) in more details.
Long story short: references are still required to generate correctly concatenated JS result file but because of implicit TS files referencing it is pretty hard to track whether references are correct.

**Comment by mhegazy** [comment]
StackOverflow seems like the right place for questions. this repo is mainly for compiler/language bugs.

**Comment by mhegazy** [comment]
My recommendation would be to add a tsconfig.json to your folder. see https://github.com/Microsoft/TypeScript/wiki/tsconfig.json

**Comment by usarskyy** [comment]
@mhegazy Thank you for a quick answer! 
I didn't ask the question, I wanted to request a feature for VS plugin. SO link was just FYI.

I read about tsconfig.json and "Virtual Projects" but nobody mentioned that it alters TS files reference behavior in Visual Studio. 
The link that you provided describes how TS compiler will behave but VS plugin with InterlliSense is a separate story (if I understand it correctly). Anyway, I will check how tsconfig.json influences VS behavior and let you know soon.

**Comment by mhegazy** [comment]
Please give [TS 1.8-beta](https://blogs.msdn.microsoft.com/typescript/2016/01/28/announcing-typescript-1-8-beta/) a try. we have added [support for tsconfig.json as main driver for project information](https://github.com/Microsoft/TypeScript/wiki/What%27s-new-in-TypeScript#improved-support-for-tsconfigjson-in-visual-studio-2015), so things should be much more intuitive.

**Comment by usarskyy** [comment]
So, I tested tsconfig.json with TS 1.8-beta Visual Studio plugin and it worked as expected. Implicit references are not used anymore and each file must contain "reference" tags to required files. VS shows errors as expected.
