### ISSUE TITLE
Colourisation fails occasionally

### ISSUE THREAD

**Issue by NoelAbrahams** [Microsoft/TypeScript#6836]
Hi,

**Version:**  TS 1.8/VS 2015

The problem started off as a sticky red squiggly that was underlining an error that was already corrected and refusing to go away. I tried closing the file to get rid of the red squiggly. Re-opening the file resulted in the red squiggly disappearing but caused the IDE to display the faulty colouring as depicted below. Closing and re-opening the file did not initially correct the problem, but appears to have corrected itself while I was writing this.

![image](https://cloud.githubusercontent.com/assets/1106823/12747927/df3c8e42-c99e-11e5-97fa-bf40375b9e35.png)

I have not seen this occur in previous versions.

**Comment by mhegazy** [comment]
is there a way we can reproduce this locally?

**Comment by NoelAbrahams** [comment]
Not at the moment. There's also nothing in the event log. I will see if this occurs again.

**Comment by mhegazy** [comment]
this is not really actionable at the moment. please reopen if you run into it again, a project or consistent repro would help a lot.
