### ISSUE TITLE
Go to Definition is not working for simple js object

### ISSUE THREAD

**Issue by egamma** [Microsoft/TypeScript#6839]
_From @yboukhata on February 2, 2016 13:16_

Hi,

The **Go to Definition** seems not working for object methods.

In this example, clicking on **Go to Definition** in **obj.method** does anything.

```
var obj = {};

obj.method = function() {
    return true;
};

obj.method();
```

I think that it is a bug in **Go to Definition**.

_Copied from original issue: Microsoft/vscode#2641_

**Comment by egamma** [comment]
This is also not supported in 0.10.7 with Salsa enabled. Moving to Salsa for comment.

**Comment by RyanCavanaugh** [comment]
We don't support this pattern.

**Comment by mhegazy** [comment]
thanks @RyanCavanaugh.

**Comment by sandersn** [comment]
#20198 or a subsequent PR should handle this pattern. It currently handles it when `var obj = {}` is in another file, but not when it's in the same file, so it's probably just a small tweak needed.

**Comment by mhegazy** [comment]
Fixed by https://github.com/Microsoft/TypeScript/pull/21974
