### ISSUE TITLE
Error message with public class inside namespace

### ISSUE THREAD

**Issue by drake7707** [Microsoft/TypeScript#6844]
```
namespace Test {
    public class A {
        
    }
}
```

The error message on the class line is: 'public' modifier cannot appear on a module element.

Shouldn't that be 'on a namespace element'? Or is namespace still a semantic alias for module?

**Comment by RyanCavanaugh** [comment]
`namespace` and `module` are identical.

We should update the error message to say `namespace`, though.

**Comment by ahejlsberg** [comment]
No sure about that. We use the same error for a top-level element in a module. If anything we should say `'public' modifier cannot appear on a module or namespace element."`

**Comment by RyanCavanaugh** [comment]
Good point

**Comment by mhegazy** [comment]
thanks @plantain-00!

**Comment by mihailik** [comment]
Still not right, it reads as if something is wrong with the `namespace` declaration (or namespace statement? element? definition? node? — whatever you call that lexical construction).

Best to say ` 'public' modifier cannot appear on an element in a module or namespace. Did you mean 'external'?`
