### ISSUE TITLE
Suggestion: Add support for incremental builds with --incremental

### ISSUE THREAD

**Issue by nojvek** [Microsoft/TypeScript#6845]
For simple tsc projects, I just want to use tsc as my build command. Since tsc supports most options in tsconfig.json, it would be awesome if tsc could take --incremental as an argument, check if any of the sources are newer than the outputs and early exist if no sources are newer.

Currently in source depo and nmake land, we have to duplicate a lot of the tsconfig.json options in nmake just to support incremental builds.

**Comment by mhegazy** [comment]
Given the language semantics, a change in one file can impact other files that has not change. e.g. const enums, and namespaces. Moreover, build tools have the ability to detect changes on a project level, and should be able to support this scenario.
