### ISSUE TITLE
Invalid TS2339 error with union types

### ISSUE THREAD

**Issue by cyberalien** [Microsoft/TypeScript#6847]
Sample code:

```typescript
export class Foo {
    _value:boolean|Array<number> = false;
    foo() {
        this._value = [1,2,3];
    }
    bar() {
        return this._value.slice(0);
    }
}
```

Compiler incorrectly throws error for slice(0) function:

    test.ts(7,28): error TS2339: Property 'slice' does not exist on type 'boolean | number[]'.

Error happens only when _value has 2 possible types.

**Comment by RyanCavanaugh** [comment]
You said it could be a boolean or an array, then used a method that only exists on *one* of those types.
