### ISSUE TITLE
Incorrect formatting of interface declaration when readonly modifier present on properties

### ISSUE THREAD

**Issue by myitcv** [Microsoft/TypeScript#6856]
Per [this comment](https://github.com/Microsoft/TypeScript/pull/6532#issuecomment-178460890):

```typescript
interface ExampleInt {
	readonly FirstVal: number;
	readonly SecondVal: number;
	readonly ThirdVal: number;
	Resolve(n: number): number;
}
```

gets reformatted (via `tsfmt`) as:

```typescript
interface ExampleInt {
	readonly FirstVal: number;
readonly SecondVal: number;
readonly ThirdVal: number;
Resolve(n: number): number;
}
```

**Comment by mhegazy** [comment]
//CC: @SaschaNaz

**Comment by mhegazy** [comment]
PRs are welcomed.

**Comment by ahejlsberg** [comment]
I can't reproduce this in VS Code (which uses the same formatting service provided by TypeScript). I think the issue is that `tsfmt` isn't using `typescript@next`, so it is trying to format with a language service that doesn't understand `readonly`.

**Comment by basarat** [comment]
Just tried atom-ts and it worked fine as well :rose: 

![readonly](https://cloud.githubusercontent.com/assets/874898/12769262/812db99e-ca6a-11e5-9f1c-0e14b6492b1e.gif)

**Comment by myitcv** [comment]
Apologies, @ahejlsberg you're quite right, had totally slipped my mind. This issue is still outstanding and being tracked https://github.com/vvakame/typescript-formatter/issues/30
