### ISSUE TITLE
Get undefined in Visual Studio language service when calling super inside inner class declaration

### ISSUE THREAD

**Issue by yuit** [Microsoft/TypeScript#6859]
```ts
class Base {
    constructor() {
    }
}
class s extends Base {
    constructor() {
        class D {
            [super( /*p1*/
        }
    }
}
```
![errorwhenusingsuperincomputedproperty](https://cloud.githubusercontent.com/assets/489742/12768809/4dd0873c-c9c7-11e5-81f6-6be5de06bcc7.PNG)
![errorwhenusingsuperincomputedproperty2](https://cloud.githubusercontent.com/assets/489742/12768810/4dd3f098-c9c7-11e5-96e5-8be21f5a97e0.PNG)

**Comment by sandersn** [comment]
Fixed by #7144
