### ISSUE TITLE
Allow specifing implements for automatic types

### ISSUE THREAD

**Issue by lee-elenbaas** [microsoft/TypeScript#686]
If you have the following code:

```
interface Api {
     a: string;
     o?: string;
}
var v = { a:'s', i: 5 };
var u : Api = { a:'s', i: 5 };
```

v will be automatically types based on its structure, while u will be typed according to the specified interface Api. As a result the compiler will give the following responses to the following expressions:

   v.a // string typed
   v.i // number typed
   v.o // compiler error not in the automatic type
   u.a // string typed
   u.i // compiler error not in the interface
   u.o // string typed

I would like support for something that gives me the benefit of both, an automatic type, that i can give it a list of implements, perhaps using a syntax like this:

```
var s : <G implements Api> = { a:'s', i: 5 };
```

that will give me the following responses from the compiler:

```
s.a // string typed
s.i // number typed
s.o // string typed
```

The advantage is that i want to specify the interface so that the compiler can indeed check that i follow whatever is defined in the interface, but still allow me to use things that are not mentioned in the interface.
This is especially useful when i am using an interface with indexer like this:

```
interface IMap<T> {
    [name:string]:T;
}
interface IPolicy {
  dealWithXXX: () => void;
  // more complex policy options
}
var policies : <G implements IMap<IPolicy>> = {
  policy1 : { dealWithXXX: () => {
    // To one thing
  } },
  policy1 : { dealWithXXX: () => {
    // To other thing
  } }
}
```

Here i want the interface to guard me so if i add some additional requirement to IPolicy it will be checked for all the different policies by the compiler, I also want to use the indexer as an getter for selecting the correct policy by name, last i also want to select specific policies as attributes for example for selecting a default policy

```
var currentPolicy = policies[policyName] || policies.policy1;
```

Currently the only cumbersome way to get that is using the following code (that IMHO is not maintainable):

```
interface ICurrentPolicies: extends IMap<IPolicy> {
  policy1: IPolicy;
  policy2: IPolicy;
  // continue list here all diffeerent policy names
}

var policies2 : ICurrentPolicies = {
  policy1 : { dealWithXXX: () => {
    // To one thing
  } },
  policy1 : { dealWithXXX: () => {
    // To other thing
  } }
}
```

**Comment by blakeembrey** [comment]
I actually just run into this and it would fit my requirements. I'd suggest something like:

```ts
var var = {} implements Type
```

I want to make sure a type implements another type, but I want to expand on that type without having to implement a whole other interface just to do it.

**Comment by blakeembrey** [comment]
This is actually super useful for the type of objects I'm typing which are used for validation. So I need the types to be consistent, but I'd like to just say "implements" or "extends" rather than having to type a duplicate interface that can periodically end up out of sync and inflexible. Imagine something like:

```ts
interface X {
  [key: string]: {
    id (arg: string, userId?: string): string
    authorize (arg: string, userId: string): Promise<boolean>
  }
}

const topics = {
  message: {
    id (arg: string, userId: string) { return true }
    async authorize () { return true }
  }
} extends X
```

Notice that I made a tiny change in that `userId` is required in only this object key, but it still implements/extends `X`.

**Comment by RyanCavanaugh** [comment]
I think we're tracking this at #7481
