### ISSUE TITLE
Implicit Enum Duplicate Values

### ISSUE THREAD

**Issue by omeid** [Microsoft/TypeScript#6864]
Enum value incrementation does not consider previously defined values, nor does the compiler throws an error on duplicate values.

Which means you can end up with potential bugs:

```typescript
enum Color {Red = 3, Green = 2, Blue};

Color.Red == Color.Blue; //true
```

**Comment by Arnavion** [comment]
I understand it may be surprising, but it's also how enums work in C / C++ / C# so there is precedent for it. If someone wrote that enum specifically with the intention to have Blue === 3, they would not want TS to warn or error about it.

**Comment by RyanCavanaugh** [comment]
I'm not sure which would be more surprising. I'll bring it up.

**Comment by omeid** [comment]
I understand the precedent argument but is that the better option?

I would argue that if for:
```typescript
enum Color {Red = 3, Green = 2, Blue, Ultraviolet};

Color.Red == Color.Blue; //true
```

The compile complained about _implicit_ duplicate values and the fix was this:
```typescript
enum Color {Red = 3, Green = 2, Blue = 3, Ultraviolet};
Color.Red == Color.Blue; //true
```

Or better yet,

```typescript
enum Color {Red = 3, Green = 2, Blue = Color.Red, Ultraviolet};
Color.Red == Color.Blue; //true
```

Or maybe
```typescript
enum Color {Red = 3, Green = 2, Blue = Red, Ultraviolet};
Color.Red == Color.Blue; //true
```

It would be more clear and hard to miss any likely bug.

**Comment by RyanCavanaugh** [comment]
Finally got to this. Combination of too expensive (every member has to check every other member, basically), too rare an error to make, and too precedented in other languages with implicitly-numbered enums.
