### ISSUE TITLE
Cannot debug typescript using VS2015

### ISSUE THREAD

**Issue by pantonis** [Microsoft/TypeScript#6871]
I'm trying to debug Typescript using VS2015 but breakpoints are not hit.

You can find a sample of what I'm trying to debug from here:

https://github.com/IEvangelist/MvcAngular2

**Comment by billti** [comment]
Does this work with the basic HTML Application template? If you try my VS2015/Angular2 project at https://github.com/billti/ASPNET5-with-Angular2 does debugging work?

Generally it can be a pain to get source maps and module configuration to all line up. Let me know if the basics are working first. If they are, it's likely project config. If not, it may be a product issue.

**Comment by pantonis** [comment]
Downloaded your project. Added breakpoint into app.ts but again the same problem. Can see that the source maps are generated:

![image](https://cloud.githubusercontent.com/assets/3295086/12825546/8661787c-cb7f-11e5-8f46-55ea9b6a93d9.png)

**Comment by squadwuschel** [comment]
I''ve the same problems, can't hit the breakpoints in VS with Angular 2

https://github.com/squadwuschel/Angular2Introduction

**Comment by mhegazy** [comment]
Is this still an issue?

**Comment by squadwuschel** [comment]
no its working now, tested it today on Vs 2015 Community Edition newest update and TypeScript 1.8

**Comment by mhegazy** [comment]
thanks. closing
