### ISSUE TITLE
Salsa - incorrect error message when using ES7 decorators in a .js file

### ISSUE THREAD

**Issue by egamma** [Microsoft/TypeScript#6872]
See the error message in the screen shot below. It is from a .js project that is using ES7 features using bable to downlevel compile it. 

If I'm a bable user I consider the error message as wrong. I've tried to enable 'experimentalDecorators' in the jsconfig.json, but this didn't have any effect.

![decorators](https://cloud.githubusercontent.com/assets/172399/12777478/8dc375fc-ca5d-11e5-96f3-d175c39eeef0.png)

**Comment by egamma** [comment]
@billti This project is actually an interesting test case for Salsa, it uses webpack, bable, react, ES7 decorators, ES7 spread operator,  and many other technologies (it is the one from the crash bug microsoft/vscode#2054)

To use it as a test case:
- git clone https://github.com/DelvarWorld/some-game.git
- npm install   - not only install but also produces webpacks etc.

**Comment by billti** [comment]
Looks like we explicitly check for and error on decorators in a JavaScript file (at https://github.com/Microsoft/TypeScript/blob/master/src/compiler/program.ts#L1171 ). Not sure why. I'll get this removed and experiment with the project provided a little also. Thanks!

**Comment by egamma** [comment]
@billti thank you!

**Comment by JakeGinnivan** [comment]
@billti @egamma you mentioned spread operator. Is there any way to get salsa to recognise that syntax and not give me errors?

**Comment by billti** [comment]
@JakeGinnivan It's a much requested feature and on the radar, but not support yet. It's covered by #2103 (and please don't add more +1s to it... we have enough, we know you guys want it :wink: ).

**Comment by mikekidder** [comment]
Sorry to piggyback on the Issue, but on testing latest version of VSCode/Typescript/Salsa: Does a project require a jsconfig.json for it to recognize `import { someExport } from 'whatever';` in your JS files?  

If not, still getting _Parsing error: The keyword 'import' is reserved (null)_ message.  I can open separate issue.

**Comment by egamma** [comment]
@mikekidder 
>If not, still getting Parsing error: The keyword 'import' is reserved (null) message. I can open separate issue.

I think you have eslint enabled and this error message comes from eslint. To enable imports in eslint you need to enable `sourcetype`: `module` in the .eslintrc.json, pls see this gist for an example: https://gist.github.com/egamma/65c0e2a832393e3b625a

**Comment by mikekidder** [comment]
@egamma Thanks!.  This project didn't have an .eslintrc.* file. Keep forgetting that plugin extension sets `eslint.enable = true` in VSCode **User Settings**.

Going to do workaround mentioned in Microsoft/vscode-eslint#26, and just enable at **Workspace Settings** when I do want it.  

Perhaps we need labeled helper tags that show the message origin, _Ext: ESLint_, _Typescript_, _VSCode_, etc.

**Comment by egamma** [comment]
>Perhaps we need labeled helper tags that show the message origin, Ext: ESLint, Typescript, VSCode

Support for this is in place, see Microsoft/vscode-eslint#22.

**Comment by waderyan** [comment]
I'm still seeing this issue in a later version of TypeScript

Error message on hover: 'decorators' can only be used in a .ts file. 

![image](https://cloud.githubusercontent.com/assets/2449568/13370900/9857e148-dccc-11e5-954f-acc843e472f8.png)

```
tsc -v
Version 1.9.0-dev.20160130
```

Could it have been reintroduced in 1.9?

**Comment by billti** [comment]
@waderyan Looks like you are using the Sublime plugin - is that right? We've not yet released the update to that containing 1.8, but it is pending (see https://github.com/Microsoft/TypeScript-Sublime-Plugin/pull/446#issuecomment-190103761 ). Unless you are pointing to a custom TypeScript build in the plugin, you are not yet on 1.8.

**Comment by waderyan** [comment]
I'm actually using VS Code Alpha build which uses the latest version of Salsa if I understand correctly.

**Comment by billti** [comment]
Did you follow the steps at https://code.visualstudio.com/Updates to enable Salsa (i.e. do you see the Salsa indicator in the status bar as shown)?

**Comment by waderyan** [comment]
I'm on the latest Alpha build of VS Code which enables Salsa by default. I have confirmed that Salsa is enabled.

**Comment by billti** [comment]
I just installed the latest Alpha build on my desktop (didn't have VSCode installed previously), and got the expected warning as shown below.

![decorators](https://cloud.githubusercontent.com/assets/993909/13401876/b7157288-dec2-11e5-9cbe-cebfbf8f51cb.png)

When I set the compiler option as indicated, the warning went away.

```json
{
    "compilerOptions": {
        "experimentalDecorators": true
    }
}
```

Not sure what is up with your install of VSCode, but it seems to be working as expected.

**Comment by waderyan** [comment]
Excellent. Do you have a link to the list of compiler options? I was not aware of that option.

**Comment by billti** [comment]
See https://github.com/Microsoft/TypeScript/wiki/tsconfig.json for the general file contents (jsconfig.json is the same). There is a link on that page to the full list of compilerOptions also.

**Comment by EisenbergEffect** [comment]
I've got the same issue. Even with a jsconfig.json with the above settings, decorators are detected as errors.

**Comment by pflannery** [comment]
I saw this issue a little while ago but seems to be working for me now. thanks

jsconfig
```json
{
  "compilerOptions": {
    "experimentalDecorators": true
  }
}
```

![image](https://cloud.githubusercontent.com/assets/1727302/13767738/d41d4d0c-ea65-11e5-883a-16d764b56448.png)


```shell
tsc -v
Version 1.8.7
```
