### ISSUE TITLE
Generated js not published to filesystem w/ 1.8.0

### ISSUE THREAD

**Issue by twhitbeck** [Microsoft/TypeScript#6873]
Using 1.8.0, when publishing to filesystem, generated .js files aren't published. Reverting to 1.7.6 fixes issue.

**Comment by billti** [comment]
Can you be more specific. What do you mean 'publishing'? Is this a Visual Studio scenario?

Project details and repro steps would be helpful.

**Comment by twhitbeck** [comment]
Sorry for being vague.

Yes, I mean publishing in Visual Studio 2015. I'll see if I can repro

**Comment by mhegazy** [comment]
the build log file will be helpful with  `/verbosity:diagnostic`

**Comment by paulvanbrenk** [comment]
This may be related to this issue #6721

**Comment by mhegazy** [comment]
this does not seem actionable at the moment. a sample project or a set of steps to reproduce would be appreciated. closing now. please reopen if there additional information.
