### ISSUE TITLE
spread operator and iterable

### ISSUE THREAD

**Issue by yukulele** [Microsoft/TypeScript#6874]
spread operator don't works on iterable
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_operator

**Comment by ahejlsberg** [comment]
Support for spread with iterators is available only on ES6 and later. Are you compiling with `--target es6`?

**Comment by mykohsu** [comment]
@yukulele If you are using babel es2015-loose it will not work. You have to set loose = false for babel-plugin-transform-es2015-spread.
