### ISSUE TITLE
possible problem with `-outFile` in 1.8

### ISSUE THREAD

**Issue by dlebedynskyi** [Microsoft/TypeScript#6875]
I was using 1.7.5 and had following gulp build using browserify/watchify.
```
var bro = browserify('src/bootstrap.tsx', {
    cache: {}, packageCache: {},
    debug: !!debug
  })
.plugin(tsify, {
    "target": "es6", //!!
    "module": "commonjs",
    "sourceMap": true,
    "noImplicitAny": false,
    "jsx": "react", //!!
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true
    typescript: require('typescript')})
.plugin(watchify)  .... 
```
that was producing full bundle on my src files including files that are imported in bootstrap.tsx that are relative to bootstrap.tsx  like 
```
import * as React from 'react';
import configureStore from './store/configureStore';
```
now all external dependencies are imported file - react in bundled - as example. 
But in for relative files  I'm getting 
```
235:[function(require,module,exports){
/// <reference path='../typings/browser.d.ts'/>
/// <reference path='../typings/custom.d.ts'/>
"use strict";
var React = require('react');
var configureStore_1 = require('./store/configureStore');
var routes_1 = require('./routes');
...
`},{"./routes":236,"./store/configureStore":237,"react":223,"react-dom":52,"react-redux":55,"react-router":88,"react-router-redux":60}],236:[function(require,module,exports){

},{}],237:[function(require,module,exports){
``` 
none on './routes' or './store/configureStore' are bundled. 

Does anyone have idea what is going on? 
I feel like it may be realted to Concatenate AMD and System modules with --outFile  that now breaks since only bootstrap.tsx is compiled. 

Note: if you compile all files before into js and then run bundle without tsify and typescript all fine

**Comment by mhegazy** [comment]
I am not sure i understand the issue. I do not see where --outFile is used. in TS 1.8 --outFile will concatenate all modules, in the past it was silently ignored. but --outFile is not allowed with --m commonjs, as it does not make sense. can you elaborate on issue and what is the compiler output, and what you expect?

**Comment by dlebedynskyi** [comment]
@mhegazy, 
 my assumption for `output` as one of the reasons comes from part that tsif + ts 1.7.5 work fine. It may problem with something else. 

What I can state - if you run 
`>tsc src/bootstrap.tsx --jsx react -outDir testDir --target ES5 --experimentalDecorators --module commonjs`
 you are going to get all files. 

and if you run 
`>tsc src/bootstrap.tsx --jsx react --target ES5 --experimentalDecorators --module commonjs` you are going to get all files in same dir. 
and you sad earlier you does not allow commonjs now. I guess part that it was silently ignored allowed tsify to work with commonjs modules. 

I'm not saying that this is your bug, guys. I just want to note that change in `output` will break seamless ingratiation with with browserify thought tsify as example.

**Comment by mhegazy** [comment]
> What I can state - if you run 
>tsc src/bootstrap.tsx --jsx react -outDir testDir --target ES5 --experimentalDecorators --module commonjs
you are going to get all files.

this sounds right. all files should be created in the outDir: `testDir`


> and if you run 
>tsc src/bootstrap.tsx --jsx react --target ES5 --experimentalDecorators --module commonjs you are going to get all files in same dir. 

this is correct too. as you did not specify an outDir

>and you sad earlier you does not allow commonjs now. I guess part that it was silently ignored allowed tsify to work with commonjs modules.

this is not applicable here as you are not specifying `--outFile` anyways.
