### ISSUE TITLE
type inference bug/limitation: union return types vs. multiple overloads.

### ISSUE THREAD

**Issue by brandf** [Microsoft/TypeScript#6876]
The DefinatelyTyped definitions for bluebird have an overload that looks like this:

    attempt<T>(fn: () => PromiseLike<T>, args?: any[], ctx?: any): Promise<T>;
    attempt<T>(fn: () => T, args?: any[], ctx?: any): Promise<T>;

If I try to call it with a function that has the following signature:

    type MaybePromise<T> = () => T | Promise<T>

(note: Promise<T> implements PromiseLike<T>)
The type inference doesn't seem to be considering both overloads.  It seems like it should, which is why I'm filing this issue.

As a temporary fix I've made a pull request to use a union type for the fn return value, but this feels like I'm working around a compiler bug.
  
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/7958

For a min-repro, see the PR above.  The test cases I added fail if I don't make the non-test changes in that PR (switching to a union type).

**Comment by RyanCavanaugh** [comment]
See #6735 and #1805

**Comment by brandf** [comment]
Thanks Ryan.  Sounds like given that this is a known issue and it's the mutli-argument case it is unlikely to be supported.  I will try to get the bluebird definitions updated on DefinatelyTyped.
