### ISSUE TITLE
"Compile On Save" is disabled VS2015 TypeScript Build options when tsconfig.json is present

### ISSUE THREAD

**Issue by jslew** [Microsoft/TypeScript#6879]
I'm trying to achieve both "allowJs" and "Compile On Save" at the same time.  "allowJs" exists in tsconfig.json, but not the IDE's TypeScript Build options.  "Compile On Save" exists in the IDE (which makes sense, since it is really an editor concern), but is disabled if tsconfig.json is present.  What I think would be ideal is to allow "Compile On Save" to be lit up and active in the IDE regardless of whether tsconfig is present or not, even if the other options (which are passed through to to the compiler) are not available.

**Comment by jslew** [comment]
I rewrote the description of this to avoid duplicating issue https://github.com/Microsoft/TypeScript/issues/6879.

**Comment by mhegazy** [comment]
please see my comment in https://github.com/Microsoft/TypeScript/issues/6767#issuecomment-179483696

this should be handled by  #2326
