### ISSUE TITLE
TypeScript 1.8 Beta in VS2015 - allowSyntheticDefaultImports appears not to work

### ISSUE THREAD

**Issue by snerks** [Microsoft/TypeScript#6880]
Following the suggestions in [this article on using Typescript with SystemJs](https://github.com/ServiceStackApps/typescript-redux), I attempted to try the new Typescript 1.8 "**allowSyntheticDefaultImports**" feature, described here: ["Support for default import interop with SystemJS"](https://github.com/Microsoft/TypeScript/wiki/What%27s-new-in-TypeScript).

#### Environment ####
- VS2015 Update 1
- Typescript 1.8 Beta tooling
- Typescript Html App
- **System** Modules (with which **allowSyntheticDefaultImports** is on by default)
- Add the [classnames](https://github.com/JedWatson/classnames) NPM module, using JSPM
- `tsd install classnames --save`
- `import * as classNames from "classnames";`
- Attempt to invoke the `classNames` function directly:
- `this.classNamesResult = classNames(["allowSyntheticDefaultImports", "is", "here"]);`

#### Expected result ####
this.classNamesResult = "allowSyntheticDefaultImports is here"

#### Actual result ####
Exception: "classNames is not a function"

#### Workaround ####
    this.classNamesResult = (classNames as any).default(["works", "but", "explicit", "default", "reference", "required"]);

Repro is here: [https://github.com/snerks/ClassNamesApp](https://github.com/snerks/ClassNamesApp)

**Comment by mhegazy** [comment]
you should be importing it as a default import.. i.e.:
`import classNames from "classnames";`

this used to be an error in the past. with --allowSyntheticDefaultImports, it is "allowed"

**Comment by snerks** [comment]
That fixed it - thanks!

So, to be clear on the pattern with `system` modules, if the `export` section of a definition (*.d.ts) file looks like this:

    declare module "abcmodule" {
    	export = xyzExport
    }

The import syntax with `system` modules (and TypeScript 1.8) should be:


    import xyzExport from "abcmodule";

Is that correct?

**Comment by mhegazy** [comment]
I would say, if you want to use the import as a function or a class, import it using the default import pattern `import d from "mod"`. if you just need to do that, it really does not matter how you write it, it should always work.

**Comment by snerks** [comment]
OK - thanks for the clarification.
