### ISSUE TITLE
Typos in Specification

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#6883]
Found by @pra85 on #6868.
- `emiting` > `emitting`
- `exponentation` > `exponentiation`
- `exended` > `extended`

**Comment by SaschaNaz** [comment]
Can we use some other open converter libraries? A quick search shows [word-to-markdown](https://github.com/benbalter/word-to-markdown) and [Pandoc](https://github.com/jgm/pandoc)

**Comment by RyanCavanaugh** [comment]
The spec is now an "archived" artifact and we won't be tracking defects against it anymore.
