### ISSUE TITLE
Add support for spaces in file paths on Windows systems

### ISSUE THREAD

**Issue by SetTrend** [microsoft/TypeScript#6891]
The TypeScript jake file currently fails when the path to the TypeScript project contains spaces.

As suggested by @mhegazy I am creating this issue instead of a pull request on the fix I implemented for `jakefile.js`.

The fix is mainly based on adding an [undocumented, yet required Node option](https://github.com/nodejs/node/issues/5060) which has already been used in the existing `jakefile.js`, yet only for one single call. I have amended the other calls to utilize this option.

Please refer to [SetTrend/TypeScript](/SetTrend/TypeScript) for changes.

**Comment by jakebailey** [comment]
Just looking at old issues; the build doesn't use jake anymore, nor gulp, and the new build never constructs shell commands, so this one should definitely be fixed now.
