### ISSUE TITLE
__extends is not compatible with ES6 classes

### ISSUE THREAD

**Issue by mykohsu** [Microsoft/TypeScript#6893]
This means you cannot mix Typescript emitted ES5 with ES6 (or babel'd ES5).

For example, in base.es6
```
class Base {
    static Hello {
        console.log('I'm here!);
    }
}
```
And then in derived.es5

```
var __extends = (this && this.__extends) || function (d, b) {
    for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];
    function __() { this.constructor = d; }
    d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
};

var Derived = (function (_super) {
    __extends(Alarm, _super);
    function Derived() {
        _super.apply(this, arguments);
    }
    return Alarm;
})(Base);
```
Hello would not be defined on Derived because methods are not enumerable in ES6.

**Comment by mhegazy** [comment]
the `__extends` is designed to be overrides. you can use `--noEmitHelpers` and provide your own implementation.
the default implementation attempts to balance spec conformance and performance..
