### ISSUE TITLE
outFile compiler option prevents msbuild incremental compilation

### ISSUE THREAD

**Issue by julioct** [Microsoft/TypeScript#6896]
Is the use of the **outFile** compiler option expected to prevent msbuild incremental compilation? For a simple repro I created a new TypeScript HTML App, added a tsconfig.json file and specified only this in that file:
`{
    "compilerOptions": {
        "outFile": "built/myapp.js"
    }
}
`
Then I started calling msbuild with this project. Doesn't matter how many times I call msbuild, it always recompiles the one .ts file I have there. However as soon as I remove the outFile option it starts skipping the CompileTypeScriptWithTSConfig target (which is what I was expecting from the start):

> Skipping target "CompileTypeScriptWithTSConfig" because all output files are up-to-date with respect to the input files

I am using VS 2015 Update 1 and TypeScript 1.8 beta.

**Comment by paulvanbrenk** [comment]
@julioct Yes, this is a current limitation... we have a plan for a fix, but it's a pretty large change, so we're targeting that for 2.0

**Comment by mhegazy** [comment]
same root cause as https://github.com/Microsoft/TypeScript/issues/6934
