### ISSUE TITLE
Type guard can be broken by function call

### ISSUE THREAD

**Issue by jesseschalken** [Microsoft/TypeScript#6900]
This code currently type checks:

```ts
function foo(x:number|string) {
    function blah() {
        x = 'hello';
    }
    if (typeof x === 'number') {
        blah();
        needs_number(x);
    }
}

function needs_number(x:number) {
    console.log(typeof x); // string
}
```

The assignment to `x` in `blah()` bypasses the "... provided no part of the 'if' statement contains assignments to the variable or parameter." condition for type guards (section 4.24).

This may be deliberate, but it could be fixed by changing the condition to "... provided no part of the 'if' statement _nor any other function body_ contains assignments to the variable or parameter." and similarly for `?:`, `&&` and `||`. This would require that the variable not be global.

Examples:
```ts
function foo(x:string|number) {
    if (typeof x === 'number') {
        needs_number(x); // safe
    }
    blah(x);
}
```

```ts
function foo(x:string|number) {
    if (typeof x === 'number') {
        needs_number(x); // unsafe because of assignment in bar()
    }
    function bar() {
        x = ...;
    }
}
```

```ts
function foo(x:string|number) {
    function boo() {
        if (typeof x === 'number') {
            needs_number(x); // unsafe because of assignment in foo()
        }
    }
    x = ...;
}
```

**Comment by ahejlsberg** [comment]
This is a known limitation. Without being overly conservative it is practically impossible to detect all assignments to a variable. For example, your mutating `blah` method might not be called directly, but rather through a number of indirections through calls to other methods, some of which might be conditional and depend on flow of your program. Plus you might alias functions using function objects. We could potentially spend an inordinate amount of time doing this analysis and still get it wrong. I think the currently rules are best we can do.

**Comment by jesseschalken** [comment]
> Without being overly conservative (and thus overly restrictive) it is practically impossible to detect all assignments to a variable. For example, your mutating blah method might not be called directly, but rather through a number of indirections through calls to other methods, some of which might be conditional and depend on flow of your program. Plus you might alias functions using function objects. We could potentially spend an inordinate amount of time doing this analysis and still get it wrong.

Changing the condition to "... provided no part of the 'if' statement nor any other function body contains assignments to the variable or parameter." requires no flow analysis whatsoever. It simply applies the existing "is the variable assigned in the 'if' body?" check to the other scopes/function bodies which have access to the variable, nothing more.

The question is: Is this too conservative/restrictive? Would it break any common JS patterns?

**Comment by ahejlsberg** [comment]
Rewriting your example slightly:

```typescript
function foo(x:number|string) {
    function blah() {
        x = 'hello';
    }
    if (typeof x === 'number') {
        // No mutations of x in this block
        needs_number(x);
    }
    blah();
}
```

If I understand your proposal correctly, this would now be an error. I definitely think that is too restrictive.

**Comment by jesseschalken** [comment]
Thanks @ahejlsberg. If that sort of thing is sufficiently common then it may indeed be too restrictive.
