### ISSUE TITLE
Support for inline function type declaration.

### ISSUE THREAD

**Issue by yazla** [Microsoft/TypeScript#6903]
Hi,

I have just started investigating TypeScript and consider using it for the next big project. So far I have one question:
Why the following
```
var MyAddFn: (x : Number, y : Number) => Number;
var g = (fn : MyAddFn) : Number => fn(5); // produces error "Cannot find name MyAddFn"
```
is not supported for defining a type of the function, even though here: 
```
var myAdd: (x : Number, y : Number) => Number  = 
    function(x : Number, y : Number) : Number { return x+y; };
```
it is perfectly fine but is basically the same as first example and uses the same type notation but with implementation following after that?

It looks like it should work, and is actually very handy I believe, especially for people with fp background. I know that there is "interface" syntax for that, but imho it feels very verbose and redundant.

And of course another question is, is there any plans to support this?

Thanks.

**Comment by mhegazy** [comment]
`MyAddFn` is a value and not a type. in the exampke above you are using it as a type annotation in `fn: MyAddFn`. 

if you want to declare a type name, use:
```ts
type MyAddFn = (x : Number, y : Number) => Number;
```

if you want to to have a value called `MyAddFn`, and refere to its type, use `typeof` operator

```ts
var g = (fn : typeof MyAddFn) : Number => fn(5);
```

**Comment by mhegazy** [comment]
Also for future references, StackOverflow/the TS gitter chat room is a good place for questions. this repo is mainly for the language and compiler bugs.

**Comment by mhegazy** [comment]
you can find more information about types vs values at https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Declaration%20Merging.md#basic-concepts

**Comment by yazla** [comment]
Thanks a lot @mhegazy, got it.
