### ISSUE TITLE
Missing type for Math.sign

### ISSUE THREAD

**Issue by elbarzil** [Microsoft/TypeScript#6907]
There's no type for `Math.sign`, which, AFAICT, is supported by everything except IE (surprisingly).

**Comment by billti** [comment]
This is defined in our ES2015 typing that ships with TypeScript (see https://github.com/Microsoft/TypeScript/blob/master/lib/lib.core.es6.d.ts#L4439 ). Please be sure your project configuration is set to target ES2015. (Note this does mean ALL ES2015 features such as classes, modules, arrow functions, etc… will NOT be converted to ES5).

If you want to continue targeting ES5 but also use this ES2015 API, you can reopen the interface and just add it yourself, e.g.

interface Math {
    sign(x: number): number;
}

Let me know if this help.

**Comment by elbarzil** [comment]
OK, that makes sense -- thanks!  FWIW, I searched for `"Math.sign"` (both issues and code) and found nothing, so hopefully having this would be useful for future searches.

(Thanks also for the workaround, though I can't really use it due to IE anyway.)
