### ISSUE TITLE
Fix super in async method is not included in 1.8 installer for VS2015

### ISSUE THREAD

**Issue by mykohsu** [Microsoft/TypeScript#6912]
The fix https://github.com/Microsoft/TypeScript/pull/5870 is included in node TypeScript 1.8 beta package, but not included in TypeScript_Dev14Full.exe.

There may be other differences as tsc.js is different, but both have version set to 1.8.0.

**Comment by mhegazy** [comment]
sorry about that. looks like the snap for the two packages did not match. the final 1.8 should have matching versions and bits.

**Comment by mykohsu** [comment]
@mhegazy Is there a way to fix this in VS? I replaced the file in Microsoft SDK which works when building from the menu, but compile on save is still using the incorrect version.

**Comment by mhegazy** [comment]
You can use dev mode as in: https://github.com/Microsoft/TypeScript/wiki/Nightly-drops#visual-studio-2013-and-2015

1.8.2 (1.8 final), should be available in the next couple of weeks.
