### ISSUE TITLE
Issue with --outFile module 1.8

### ISSUE THREAD

**Issue by stephenlautier** [Microsoft/TypeScript#6914]
Hi,

I'm not sure if I'm doing something wrong however I'm trying to use Concatenate amd (or system) modules when using ES6 modules as per https://github.com/Microsoft/TypeScript/wiki/What%27s-new-in-TypeScript#concatenate-amd-and-system-modules-with---outfile
What I'm trying to do is to be able to create a library, publish it, installed with JSPM and used as following:

```typescript
import {StringService, MathService} from "ssv-core";

new MathService().add(1, 3); // for sake of example
```

However I have 2 issues, one with bundled d.ts files and another with amd/system at runtime not working.

#### DTS

All d.ts are bundled within 1 file, however they have different modules e.g.

##### What is generated
```typescript
declare module "string.svc" {
    export class StringService {
        interpolateUrl(url: string, data: any): string;
    }
}
declare module "math.svc" {
     export class MathService {
        add(value: number, valueB: number): number;
    }
}
```

##### What is expected
```typescript
declare module "ssv-core" {
    export class StringService {
        interpolateUrl(url: string, data: any): string;
    }
export class MathService {
        add(value: number, valueB: number): number;
    }
}
```

#### bundled js file
They are within one file however they seem to be still as different modules which is causing me issues when loading them from SystemJS.

Within systemjs this is what I expect to do
```javascript
map: {
    "ssv-core": "libs/ssv-core",
}
```
However as it is, I have to create one for `string.svc` e.g.
```javascript
map: {
    "string-svc": "libs/ssv-core",
}
```
On top of that if I do the same for `math.svc` it won't load unless I comment the `string-svc` map.

Using typescript 1.8.0
- target es5
- module amd (tried also system)
SystemJS 0.19.9

Am I doing something wrong or? its not working correctly? Is there a very small example in order to create a library e.g. compiled with d.ts file and js bundled?

if needed the project I have is on github: https://github.com/sketch7/ssv-core/tree/develop its quite small and simple.

**Comment by weswigham** [comment]
Judging by your output, your input must look somewhat like this:
string.svc.ts:
```ts
    export class StringService {
        interpolateUrl(url: string, data: any): string { /*implementation*/ };
    }
```
math.svc.ts
```ts
     export class MathService {
        add(value: number, valueB: number): number { /*implementation*/ };
    }
```

To get the shape it looks like you want, add another file which looks like this:
ssv-core.ts:
```ts
export * from "./string.svc.ts"
export * from "./math.svc.ts"
```

Which is simply collecting the exports you've made into a top-level public API. Additionally, you shouldn't need to use the `map` field of the systemjs configuration, as we output named modules into the bundle (unless you want to rename them, ofc).

**Comment by stephenlautier** [comment]
Thanks @weswigham, its quite similar how I have it (or had it at a point) I will try this out again. Thanks.
