### ISSUE TITLE
[Version 1.8] Can't include the js file to compile file with --allowJs

### ISSUE THREAD

**Issue by lovedota** [Microsoft/TypeScript#6916]
Does anyone try Typescript 1.8, it said from this blog https://blogs.msdn.microsoft.com/typescript/2016/01/28/announcing-typescript-1-8-beta/ that we can compile js module file without needing any tool like webpack or browserify. So my file is

```ts
/// <reference path="../interfaces/react.d.ts"/>

import React from "react";

React.render(<div />, document.getElementById("app-content"));
```

with *tsc test.tsx --allowJs --jsx react --target ES6 --module es2015 --outDir out*

but it compiled to:
```js
/// <reference path="../interfaces/react.d.ts"/>
import React from "react";
React.render(React.createElement("div", null), document.getElementById("app-content"));
```

it does not include the React code to this file
_

**Comment by mhegazy** [comment]
> it does not include the React code to this file

not sure i understand what you mean by "React code".


The output looks right to me.

**Comment by mhegazy** [comment]
`--allowJS` allows the compiler to process .js files, something that the compiler will flag as an unsupported extension in the past.
it does not bundle your react in your output, nor will it resolve references to .js files by providing .d,ts files. in your scenario, looks like you should be using webpack to bundle your output instead.

**Comment by lovedota** [comment]
@mhegazy 
Sorry but in this blog https://blogs.msdn.microsoft.com/typescript/2016/01/28/announcing-typescript-1-8-beta/

>Using 3rd party JavaScript libraries is easier

In order to utilize JavaScript libraries in your TypeScript projects, developers have to include a type definition (.d.ts) file so that the TypeScript compiler knows what you’re doing at compile time and the JavaScript engine knows what to use at runtime. Typically, this is fine unless you want to bundle your external JavaScript libraries with the JavaScript emitted by your TypeScript compilation. Until now, to address this problem, developers needed a third party bundler such as webpack or browserify. With TypeScript 1.8, you can simply include these 3rd party JavaScript libraries in your compilation and they will follow your emitted JavaScript wherever it goes. Source maps included!

**Comment by mhegazy** [comment]
You can pass react.js to the compiler; note this will increase your build time. I would use this feature for migrating js files into TS rather than bundelling. Bundlers like webpack and browserify have better support for bundelling.

**Comment by lovedota** [comment]
@mhegazy 
from here https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#including-js-files-with---allowjs

```
Often there are external source files in your project that may not be authored in TypeScript. Alternatively, you might be in the middle of converting a JS code base into TS, but still want to bundle all your JS code into a single file with the output of your new TS code.

.js files are now allowed as input to tsc. The TypeScript compiler checks the input .js files for syntax errors, and emits valid output based on the --target and --module flags. The output can be combined with other .ts files as well. Source maps are still generated for .js files just like with .ts files.
```

Sorry how can i use this feature. I do exactly like this in my first comment https://github.com/Microsoft/TypeScript/issues/6916#issue-131570713

But it does not work.

**Comment by mhegazy** [comment]
include react.js in your compilation along with react.d.ts

**Comment by lovedota** [comment]
@mhegazy  so it won't work with React in node_modules ?

**Comment by mhegazy** [comment]
in the snippet above, i only see a `/// <reference>` to react.d.ts. i do not see any reference to your react.js. include that in the compilation, and it should be bundled.
