### ISSUE TITLE
Visual Studio compiles TypeScript diffs files incorrect

### ISSUE THREAD

**Issue by DibranMulder** [microsoft/TypeScript#6918]
When developing an ASP.net web application with use of TypeScript I often get compile errors in my Error list when I look at files from my Pending Changes list using the Visual Studio Diff window. The compile errors aren't valid and disappear when I (re)build the project or the solution.

I don't know why Visual Studio is compiling this diff files, it probably has something to do with the syntax highlighting and on the fly compiling. To be clear, I don't have any compile errors in my history nor in my local code, so that isn't the problem.

![image](https://cloud.githubusercontent.com/assets/5592416/12844299/ce2cd690-cbfe-11e5-93a8-c5ec42f9d009.png)

I'm running the following configuration:

Microsoft Visual Studio Professional 2015
Version 14.0.24720.00 Update 1
Microsoft .NET Framework
Version 4.6.01055

TypeScript   1.7.4.0
TypeScript for Microsoft Visual Studio

**Comment by IanYates** [comment]
This has been an issue for many versions.  What improved several versions ago (maybe v1.5?) however was that the errors at least went away when the diff window was closed.  
I assume it's that some "virtual TypeScript project" is created on the fly for the diff window and that project doesn't have any definition files linked to it.

**Comment by paulvanbrenk** [comment]
@IanYates yes, you are correct... we should not be checking for errors in the diff window, I'll see what changed here.

**Comment by Nimrodxx** [comment]
For what its worth, it also occurs with C# files.
![image](https://cloud.githubusercontent.com/assets/5592416/16725949/0aaddda4-475a-11e6-8fbd-493318c0ff83.png)
Microsoft Visual Studio Professional 2015
Version 14.0.25123.00 Update 2
Microsoft .NET Framework
Version 4.6.01038

**Comment by andrewkittredge** [comment]
This is still a problem.

**Comment by sheetalkamat** [comment]
@amcasey @uniqueiniquity Can one of you please take a look. Thanks.

**Comment by uniqueiniquity** [comment]
@andrewkittredge This problem is tracked and has been fixed in an upcoming release of Visual Studio. Thank you for your feedback!

**Comment by amcasey** [comment]
There have been several releases since the last comment, so I assume the latest from https://visualstudio.microsoft.com/ contains the fix.
