### ISSUE TITLE
New Website Logo: Gainsight

### ISSUE THREAD

**Issue by gs-akhan** [Microsoft/TypeScript#6920]
Please fill the following out:

- Name: Gainsight
- Homepage url: http://www.gainsight.com/
- Brand Guidelines/Licensing: None
- Logo: http://www.gainsight.com/wp-content/uploads/2015/09/logo.png

> Example:
>
> Name: Microsoft
> Homepage url: https://microsoft.com
> Brand Guidelines/Licensing: https://www.microsoft.com/en-us/legal/intellectualproperty/trademarks/usage/logo.aspx
> Logo: https://news.microsoft.com/microsoft-news-center-photos/msft_logo_rgb_c-gray/

**Comment by mhegazy** [comment]
Logo uploaded, should be out in the next site refresh.

**Comment by gs-akhan** [comment]
hi, any idea when we will be seeing our logo.. :))

thanks

**Comment by mhegazy** [comment]
We are revamping the site, so should be out in the next few weeks.
