### ISSUE TITLE
Format code strips space after anonymous function

### ISSUE THREAD

**Issue by jrieken** [Microsoft/TypeScript#6923]
_From @milenkovic on February 5, 2016 9:51_

There is no option in settings to disable striping space after function declaration (before opening brace).

_Copied from original issue: Microsoft/vscode#2730_

**Comment by jrieken** [comment]
@milenkovic Can you share in what language that happens?

**Comment by jrieken** [comment]
_From @milenkovic on February 5, 2016 14:31_

Javascript

**Comment by mhegazy** [comment]
I do not see this on latest. please reopen with more details.

![animation](https://cloud.githubusercontent.com/assets/8000722/13192656/45d87af8-d723-11e5-8564-0224f8c17c44.gif)

**Comment by milenkovic** [comment]
This is the problem with insiders version. Not with regular.

**Comment by mhegazy** [comment]
still can not reproduce that, can you provide more details?

**Comment by milenkovic** [comment]
I use VS Code Insiders v 0.10.7, on Windows. Also, I have Salsa activated. When I try to format code:
`var p=function(){
};`
I get 
`var p = function() {
};`
As you can see, there is not space after function keyword like in regular version of VS Code when I format code. This is causing my linting to break every time I format code.

**Comment by mhegazy** [comment]
thanks for the infromation. the option (InsertSpaceAfterFunctionKeywordForAnonymousFunctions) is set by default to false in the server configuration. 

@dbaeumer, how can I set the parameters to the configure command for the server?

**Comment by mhegazy** [comment]
@zhengbli, we should consider loading the formatting options from the tsconfig.

**Comment by fiacc** [comment]
@mhegazy is there a way to set this, I've hit the same issue in VSCode Version 0.10.10-insider (0.10.10-insider

**Comment by evollu** [comment]
I'm using Beautify plugin to do the formatting and binding it to format short cut
https://github.com/HookyQR/VSCodeBeautify

**Comment by zhengbli** [comment]
Related to the more general issue https://github.com/Microsoft/TypeScript/issues/6039

I agree putting the editor options in tsconfig would be a good option / first step. Options from other common config files like the editorconfig file or vscode settings file may be next step, which can be implemented via opening an API to let the editor to parse the file and send commands to apply these settings.

**Comment by fiacc** [comment]
@evollu :+1:

**Comment by zhengbli** [comment]
On latest VSCode, it seems the `InsertSpaceAfterFunctionKeywordForAnonymousFunctions` is already added to the default typescript format settings. This issue doesn't repro anymore.

**Comment by mhegazy** [comment]
@zhengbli how can users set this in VSCode?

**Comment by zhengbli** [comment]
The option is exposed in `settings.json`:
![capture](https://cloud.githubusercontent.com/assets/1171301/14801232/a05b8328-0afc-11e6-8eaa-2ad02884a9d9.PNG)

So users can just change that in there own `settings.json` files.

**Comment by mhegazy** [comment]
thanks!

**Comment by pundoo** [comment]
For JS set this : 

`"javascript.format.insertSpaceAfterFunctionKeywordForAnonymousFunctions": false`
