### ISSUE TITLE
Format code unindents multi-line import statement

### ISSUE THREAD

**Issue by aeisenberg** [Microsoft/TypeScript#6924]
Take this code snippet:
```
import {Obj1, Obj2, Ob3, SomeVeryLongObjName, etc} as SomeVeryLong
    from 'some/file/with/a/very/very/very/very/long/path';
```
When the TS formatter is run on it, the second line is unindented and becomes this:

```
import {Obj1, Obj2, Ob3, SomeVeryLongObjName, etc} as SomeVeryLong
from 'some/file/with/a/very/very/very/very/long/path';
```

That seems incorrect behavior to me. I would have expected the formatter to ensure that multi-line imports are indented. 

Originally reported here: https://github.com/vvakame/typescript-formatter/issues/33

**Comment by mhegazy** [comment]
note: the syntax above is illegal, and should be:
```ts
import { Obj1, Obj2, Ob3, SomeVeryLongObjName, etc}
    from 'some/file/with/a/very/very/very/very/long/path';
```

**Comment by aeisenberg** [comment]
@mhegazy oops. You're right. Thanks for correcting.

**Comment by SaschaNaz** [comment]
It looks certainly better with an indent, but what should be done on this code?

```typescript
import {
    homu,
    mado
}
from 'magica'; // indent or not?
```

Should the formatter forcibly remove the newlines?

```typescript
import {
} from 'magica';
```

**Comment by mhegazy** [comment]
@SaschaNaz you bring good points. i do really not know :)..

I think an intuition here would be from destructring assignments:

```ts
var {a, b} : number;
```

today we format this as:
```ts
var {
    homu,
    mado
}
    : number;
```

though i can see the argument of treating it like `do .. while` instead, and this case the current behavior is correct.

```ts
do {
    x
}
while (true);
```

**Comment by SaschaNaz** [comment]
I would also remove the newline on the destructuring example as I don't see a good reason to keep it.

```typescript
var {
    homu,
    mado
} = something; // okay.
= something; // this looks bad (fixed by #5018)
    = something; // this also looks bad.
```

**Comment by aeisenberg** [comment]
My opinion is that I generally don't like formatters adding and removing newlines. Typically, I put them there for a reason. I generally assume that my formatters apply indentation and spacing changes only.

So, something like this:

```
import {
    homu,
    mado
}
    from 'magica'; // indent or not?
``` 
Would still be indented.

In this situation, if you wanted to avoid indentation, you just change your code to this:

```
import {
    homu,
    mado
} from 'magica'; // indent or not?
``` 
At least, that is how I would structure my code.

**Comment by SaschaNaz** [comment]
@aeisenberg Good opinion, that sounds reasonable.

**Comment by aeisenberg** [comment]
So, if the formatter is working on an import statement and the 'from' token is the first token on a new line, then it should have an indent level of 1?

If I get some time over the next few days, I may take a crack at this, unless someone else is dying to.

**Comment by SaschaNaz** [comment]
I already have a pending PR #4609 but it intentionally prevents `from` keyword from being indented. It seems I have to remove such behavior.
