### ISSUE TITLE
is x6 times slower compiling time a normal thing when migrating from 1.6 to 1.8?

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#6925]
Compile time went from 10 seconds to over a minute after upgrading from 1.6 to 1.8. Is this normal?

**Comment by vladima** [comment]
what version of node do you use?

**Comment by aleksey-bykov** [comment]
v0.12.7

**Comment by vladima** [comment]
It looks like a known perf regression with node v0.12. Can you try to upgrade to node v5 and check if it improves the situation?

**Comment by aleksey-bykov** [comment]
ok

**Comment by aleksey-bykov** [comment]
version 5.x made it better, now it's about 30 secs which is only x3 slower, doesn't it look normal now?

**Comment by vladima** [comment]
it is better but still not good enough. Can you share a repro so we can look into this more closely?

**Comment by aleksey-bykov** [comment]
I am afraid I can't, is there another way to get the data you need?

**Comment by vladima** [comment]
can you try to add `--diagnostics` to compiler options to see what compilation stage takes the majority of time? Ideally if you can do this for TS 1.7 and 1.8 and paste results here.

**Comment by aleksey-bykov** [comment]
version 1.7.5
```
Files:            1040
Lines:          216063
Nodes:          996205
Identifiers:    365978
Symbols:        413474
Types:          136178
Memory used:   507589K
I/O read:        0.16s
I/O write:       0.45s
Parse time:      4.87s
Bind time:       1.52s
Check time:     64.69s
Emit time:       2.68s
Total time:     73.76s
```


version 1.8

```
Files:            1040
Lines:          216063
Nodes:         1010583
Identifiers:    380352
Symbols:      72631648
Types:          135632
Memory used:   586952K
I/O read:        0.31s
I/O write:       0.33s
Parse time:      5.36s
Bind time:       2.58s
Check time:     17.45s
Emit time:       1.81s
Total time:     27.21s
```

**Comment by vladima** [comment]
can you also put results for 1.6 for comparison?

**Comment by aleksey-bykov** [comment]
version 1.6.2

```
Files:            1040
Lines:          216063
Nodes:          996161
Identifiers:    365961
Symbols:        146503
Types:          110017
Memory used:   501672K
I/O read:        0.16s
I/O write:       0.52s
Parse time:      4.97s
Bind time:       1.49s
Check time:     11.22s
Emit time:       3.14s
Total time:     20.82s
```

turns out 10 sec for 1.6 has never been a thing unless v0.12.7 did some magic to it

guess, the case is closed
thanks!

**Comment by aleksey-bykov** [comment]
interestingly the nightly 1.9.0-dev from last night is the fastest

```
Files:            1040
Lines:          216063
Nodes:         1010599
Identifiers:    380359
Symbols:      72631437
Types:          135560
Memory used:   570245K
I/O read:        0.19s
I/O write:       0.36s
Parse time:      3.20s
Bind time:       1.25s
Check time:     11.90s
Emit time:       1.84s
Total time:     18.19s
```


gonna keep that

**Comment by mhegazy** [comment]
@aleksey-bykov, where the perf numbers look good, the number of symbols seem intriguing, we would love to take a look. is there a way we can get access to this code base? we would be open to singing relevant NDA.

**Comment by aleksey-bykov** [comment]
let me see what i can do

**Comment by baio** [comment]
Hi guys, same problem here.
1.6 twice as fast as later ones.

Ubuntu 14.04
Node v 5.5.0
npm 2.5.1

1.6
```
Files:             581
Lines:           72366
Nodes:          277997
Identifiers:     90330
Symbols:         60198
Types:          237089
Memory used:   492525K
I/O read:        0.02s
I/O write:       0.10s
Parse time:      0.75s
Bind time:       0.35s
Check time:      5.46s
Emit time:       0.95s
Total time:      7.50s
``

1.8
```
Files:             581
Lines:           72372
Nodes:          286345
Identifiers:     98412
Symbols:      27327413
Types:          575237
Memory used:   728993K
I/O read:        0.02s
I/O write:       0.16s
Parse time:      0.69s
Bind time:       0.38s
Check time:     10.62s
Emit time:       1.67s
Total time:     13.36s
```

1.9

```
Files:             581
Lines:           72461
Nodes:          286858
Identifiers:     98586
Symbols:      27388515
Types:          575043
Memory used:   717166K
I/O read:        0.02s
I/O write:       0.12s
Parse time:      0.68s
Bind time:       0.35s
Check time:     10.74s
Emit time:       1.43s
Total time:     13.21s
```

**Comment by vladima** [comment]
is it possible to share the code that reproduces the problem (we can sign the NDA if necessary)?

**Comment by baio** [comment]
@vladima  Will ask our stakeholder, soon.

**Comment by baio** [comment]
@vladima sorry guys, no permition

**Comment by aleksey-bykov** [comment]
neither can I, sorry

**Comment by adamcarr** [comment]
I am having this problem as well. Build went from 32 sec to 70 seconds when upgrading from 1.7.3 to 1.8.10. Here is the diagnostic output for 1.8.10

Files:            1285
Lines:          294119
Nodes:         1483138
Identifiers:    465048
Symbols:     140768300
Types:           90686
Memory used:   542756K
I/O read:        0.14s
I/O write:       0.39s
Parse time:      2.40s
Bind time:       1.79s
Check time:     63.54s
Emit time:       2.65s
Total time:     70.39s

FWIW - I work @ Microsoft, so you should be able to view my code pretty easily if that would help.

**Comment by adamcarr** [comment]
I should also mention I am on node 0.12.13. I will attempt to upgrade to node v5, but that will likely cause more issues than it is worth.

**Comment by adamcarr** [comment]
Using node v5.11 just for tsc builds now in 16s. Much faster!!! Not sure the rest of my build will work on node v5 but will check

**Comment by mhegazy** [comment]
it does not have to be V5. anything that is not v0.12.* would be better.
