### ISSUE TITLE
Should warn/flag against ANYTHING !== null

### ISSUE THREAD

**Issue by derekmooney** [Microsoft/TypeScript#6926]
I like that typescript/tslint encourages !==, but I slipped and ended up doing !== null, and neither called me on it. Shouldn't this be flagged?

**Comment by RyanCavanaugh** [comment]
Some things *do* use `null`; it would be odd to tell those people they can't test for it. If you don't want any `null` at all in your code base, feel free to grab our `noNullRule.ts` and add it to your linter.

**Comment by adidahiya** [comment]
two things here:

1. if you want to disallow `null` altogether, TSLint has a `no-null-keyword` rule built in
2. if you want to specifically disallow triple equals against null (still allowing double equals), that's an open suggestion here https://github.com/palantir/tslint/issues/923
