### ISSUE TITLE
VS 2015 Navigate To (Ctrl+,) duplicated results. 

### ISSUE THREAD

**Issue by olmobrutall** [Microsoft/TypeScript#6939]
There are a few issues when using `Ctrl+,` functionality.

### Massive duplicated results:

It happens in .ts and .tsx files for any kind of symbol (class, variable, method,...) 

![image](https://cloud.githubusercontent.com/assets/720953/12866146/4094762e-ccc3-11e5-898b-535262da0af2.png)

### Imported Symbols
Imported symbols should not be shown, or at least shown at the end of the list. 

Current results:
![image](https://cloud.githubusercontent.com/assets/720953/12866148/8476f88a-ccc3-11e5-93ec-a7d304e4a0cb.png)

Expected results:
![image](https://cloud.githubusercontent.com/assets/720953/12866163/09b909f2-ccc4-11e5-88c7-eae14fadf42c.png)

**Comment by drake7707** [comment]
Maybe related to #6566

**Comment by mhegazy** [comment]
PRs welcomed.

**Comment by andy-ms** [comment]
There's a chance that #8756 didn't fully resolve this. Let me know if you can get another repro of duplicated navTo items without imports being involved.
