### ISSUE TITLE
Support AMD modules in Salsa

### ISSUE THREAD

**Issue by egamma** [microsoft/TypeScript#6942]
_From @justin-romano on February 3, 2016 21:56_

It just does nothing unless its a local variable.
I would have suspected this would present a list of all possible matching items in the source.
Its almost as if its not even indexing the code. I am working in a source base of millions of lines of JS so it would be nice.
Products like resharper and visual assist do this better.

_Copied from original issue: Microsoft/vscode#2683_

**Comment by egamma** [comment]
_From @dresoy on February 4, 2016 1:17_

I agree, it should search it for JavaScript.

**Comment by egamma** [comment]
Please give Salsa our new JS infrastructure a try. Here is how:
get the insider channel: https://blogs.msdn.microsoft.com/vscode/2016/02/01/introducing-insiders-builds/
enable salsa: https://github.com/Microsoft/vscode-docs/blob/master/release-notes/latest.md#javascript---salsa-preview

**Comment by egamma** [comment]
_From @justin-romano on February 5, 2016 20:53_

Thanks egamma but i could not see it make a difference. Is there some think like lucene indexing the code when you load a folder?
It does not seem very busy when it starts and noticed that the search is really slow which implies its just trawling the files rather then indexing the source.

**Comment by egamma** [comment]
@justin-romano Then I assume your code isn't using the `commonjs` module system? Are you using another JS module system?

**Comment by egamma** [comment]
_From @justin-romano on February 6, 2016 16:50_

No actually anguar and requirejs.

On Sun, Feb 7, 2016 at 4:52 AM, Erich Gamma <notifications@github.com>
wrote:

> @justin-romano <https://github.com/justin-romano> Then I assume your code
> isn't using the commonjs module system? Are you using another JS module
> system?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Microsoft/vscode/issues/2683#issuecomment-180796779>.
>



-- 
Justin Romaine
Senior Systems Architect
Spark Dental Technology
justin.romaine@gmail.com
ph 021 764 506
hm 09 445 9166

**Comment by egamma** [comment]
Thanks, got it. Salsa doesn't support AMD yet. I'll move it as a feature request to Salsa component.

**Comment by mhegazy** [comment]
When we looked into this, AMD seemed to be fairly complicated to get right statically, at least compared to CommonJS modules.

**Comment by mhegazy** [comment]
@egamma can you weigh in on the priority of AMD module support? given that ES6 is now ubiquitous, as well as other bundling technologies like browserify and webpack that use CommonJS.

**Comment by justin-romano** [comment]
Why dont you just have a grab everything from everywhere mode. So you don't
need a dependency change. Just scan the folders.
Goto definition then should just give you a choice rather that you can
scroll based on most likely candidates. Also remembers your previous
choices and places them at the top of the list. kind of like the ctrl+P
works

On Sun, Feb 7, 2016 at 9:57 AM, Mohamed Hegazy <notifications@github.com>
wrote:

> @egamma <https://github.com/egamma> can you weigh in on the priority of
> AMD module support? given that ES6 is now ubiquitous, as well as other
> bundling technologies like browserify and webpack that use CommonJS.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Microsoft/TypeScript/issues/6942#issuecomment-180863287>
> .
>



-- 
Justin Romaine
Senior Systems Architect
Spark Dental Technology
justin.romaine@gmail.com
ph 021 764 506
hm 09 445 9166

**Comment by egamma** [comment]
>given that ES6 is now ubiquitous, as well as other bundling technologies like browserify and webpack that use CommonJS.

@mhegazy I fully agree that this is correct for more recent JS code bases, but there are also code bases with more mileage. I'll try to find out whether there is some data on this.

**Comment by kitsonk** [comment]
> given that ES6 is now ubiquitous

Syntax yes, but there is yet to be any real loader or agreement on module resolution! :smile: Which is largely what is holding a lot of things back in my opinion.

There are significant issues with CommonJS in the browser, which is exactly why AMD came about to deal with those challenges (and had to split from CommonJS because there couldn't be agreement), to allow asynchronous lazy loading, two pass instantiation, etc. etc. and those advantages and AMD builders like [r.js](http://requirejs.org/docs/optimization.html) are heavily used by many real life projects in lieu alternatives like Browserify and WebPack.  In face, though popularity contests aren't always an indicator, [RequireJS out strips Browserify and WebPack](https://www.google.co.uk/trends/explore#q=RequireJS%2C%20Browserify%2C%20Webpack&cmpt=q&tz=Etc%2FGMT) and only recently has WebPack overtaken RequireJS.

I do agree though, static analysis is challenging for AMD modules, as there are several valid scenarios and because AMD by its nature is two pass instantiation, with circular references and potentially complex configuration information being available to the loader that makes mapping of the MID to the actual file challenging, it wouldn't be a trivial task to accomplish.

**Comment by regrettably** [comment]
The lack of AMD support makes me unable to use VSCode, unfortunately.  I don't really _want_ to use IntelliJ, but it's able to do analysis of my code far more trivially than VSCode is able to...

**Comment by MystK** [comment]
I'd like to add that AMD support would be super helpful in VSCode.

I'm a Netsuite developer, and it uses AMD syntax. It makes it harder when I can't easily click a definition and go to it when other IDEs like WebStorm can. Instead, I have to do a search all manually.

**Comment by MankalMR** [comment]
I would definitely love to have to this feature. I think there are several legacy codebases out there which would benefit from this feature.

**Comment by prantlf** [comment]
If you are looking for the support of AMD/CJS JavaScript modules for the "Go to Definition" command (custom definition provider), you can have a look at the VS Code extension "Require Module Support":

* https://marketplace.visualstudio.com/items?itemName=lici.require-js
* https://github.com/anacierdem/vscode-requirejs

It supports RequireJS configuration (paths) to look up and jump to the original location of the selected identifier's definition.

**Comment by mjbvz** [comment]
I'm closing this since the JS ecosystem has largely moved on writing AMD. This is not an area we plan to invest engineering effort in supporting
