### ISSUE TITLE
Quick Fix support

### ISSUE THREAD

**Issue by angelozerr** [Microsoft/TypeScript#6943]
It should b every cool if tsserver could support quickfix like https://github.com/TypeStrong/atom-typescript/blob/master/docs/quickfix.md

Quick fix could be returned when `geterr` is called like ESLint fix does.

**Comment by mhegazy** [comment]
thanks @angelozerr for filing this issue. We actually have Quick Fix support on our [roadmap for 2.0](https://github.com/Microsoft/TypeScript/wiki/Roadmap#20); we just did not have an issue to track it, but now we do :)

**Comment by angelozerr** [comment]
> but now we do :)

Thanks @mhegazy for your answer. I'm very enthousiasm with this cool feature.

**Comment by geekdenz** [comment]
This would be a great feature to add! As you can see nbts is waiting for it as well.

**Comment by kisstkondoros** [comment]
Hi,

I've worked a bit on @basarat 's implementation and tried to move it into the core.
In https://github.com/kisstkondoros/TypeScript/commit/0c414a57de86c1de1b4d8521ee1b53b64898641f one can find the initial implementation.

Any thoughts?

**Comment by paulvanbrenk** [comment]
@kisstkondoros Thanks for that, it shows there is certainly demand for this feature. I see a couple of issues with integrating with VS (and possibly VSCode), e.g. you can't depend on the error message, since we ship in 14 languages. Can you take a look at my PR, #9304, and if you have suggestions to make the API more useful that's very much appreciated. Note, I didn't do any work yet to integrate this with tsserver yet, I need to discuss that with the VS Code team first.

**Comment by kisstkondoros** [comment]
@paulvanbrenk Yes I also thought it is not the best practice to get the context information from an error message 😄 perhaps extending the Diagnostic class with some context information could help for the more complicated use cases, e.g. adding missing methods / members to a class.
For me it seems that adding those could be done quite easily in core.ts.

**Comment by vvakame** [comment]
Is this issue done by #10185 ?

**Comment by paulvanbrenk** [comment]
Yes, this is completed with #10185

**Comment by olmobrutall** [comment]
Great work! Adding imports will be really awesome. 

BTW: Any plans to allow library-specific quick issues?

**Comment by paulvanbrenk** [comment]
@olmobrutall Not sure what you mean by that.
The current API allows you to register a quickfix to an error... and we'll show combine all available fixes in the UI for that error. There is no planned work to limit fixes based on imports/libraries that are used in the project.

**Comment by olmobrutall** [comment]
I mean an equivalent to C# Code Analyzers. Something like distribuiting codefixes together with .d.ts files.

The compiler will need to somehow load the codefix code at compile time.

Of course it requires TS compiler to do some `eval()` at some point, on code that may need to explore TS internal (inmutable?) data structures.

**Comment by paulvanbrenk** [comment]
Ah, thanks.

**Comment by marcinnajder** [comment]
Sorry for stupid question, how to enable/execute quick fix action inside vs code ? I see no light bulb.    Do I have to use tslint ? thanks in advance

**Comment by marcinnajder** [comment]
quick fixes don't work on Mac, works on Windows

**Comment by mhegazy** [comment]
Seems like a VSCode specific issue, @mjbvz any ideas?

**Comment by mjbvz** [comment]
@marcinnajder If you are on VSCode 1.10 (current insiders builds) and don't see the expected quick fixes, please open a bug: https://github.com/Microsoft/vscode/issues/new

**Comment by marcinnajder** [comment]
works fine on VSCode 1.10, thanks for help!
