### ISSUE TITLE
Should forbid static property named 'name'

### ISSUE THREAD

**Issue by JMS-1** [Microsoft/TypeScript#6946]
class Test { static name = "what"; } will report "what" for Test.name in IE11 but "Test" in FF and Chrome. This seems to be by design (https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Function/name). Either the use of 'name' should be not allowed at all or the compiler should do some name mangling - although according to the specs the first option seems to be more appropriate.

**Comment by basarat** [comment]
Duplicate of https://github.com/Microsoft/TypeScript/issues/442#issuecomment-169521416

**Comment by JMS-1** [comment]
Sorry - did't go back that far when looking it up.
