### ISSUE TITLE
Regression in TS1.8 beta - refreshes all *.map files in VS 2015 too often

### ISSUE THREAD

**Issue by IanYates** [Microsoft/TypeScript#6951]
Hi,

I've installed the downloadable TS 1.8 beta on top of VS 2015 update 1 plus the servicing update (KB3110221) from January 2016.  Just trying to give all the facts  :)

I use VSTS in TFS mode for source control.  I have hundreds of TypeScript files in my ASP.Net *.csproj project.  The Javascript and map output files are also a part of the project and I use Mads Kristensen's file nesting plugin to nest the generated Javascript and map files beneath each TypeScript file so things are not too messy.  There's no grunt or gulp task runner - I just rely on TypeScript to generate new files when I save and when I build.

I have ReSharper 10 installed but have always had its TypeScript support disabled.

I do not have a tsconfig.json file.

Since installing TS 1.8 beta I've found that I can accidentally trigger, usually by mistyping and having intellisense try to be invoked on something that couldn't work, the TypeScript compiler to touch every single *.map file (and sometimes every *.js file) in my project.  It's very frustrating.  The files are identical except for the very last character in the map file (it looks like it's part of a hash maybe?).

I then visit the "TypeScript Build" page in my csproj's properties window and untick "Generate source maps" since they're causing me plenty of grief and I don't use them anyway.  However I save and close that window, reopen it and the tickbox is ticked again.  So I can't even disable them.  

I can turn on some additional logs or something in VS if it would help.  It's a little sporadic as to when it will regenerate all the maps but I feel that it's often when I'm triggering some intellisense to appear.

I might roll back to 1.7 if I can't get the source maps generation disabled (I'm off to manually edit the csproj).

**Comment by IanYates** [comment]
I managed to get source map generation disabled by editing the csproj by hand.  So far so good :)

**Comment by mhegazy** [comment]
it sounds to me that you have Compiler on Save enabled. every time you save a file, the compiler will regenerate your outputs. if this is something you do not want, you can disable it form your project properties, Typescript Build, then check off "Compile on Save".

![snapshot](https://cloud.githubusercontent.com/assets/8000722/12875926/c8141096-cda9-11e5-9814-5e3edf60aed3.jpg)

**Comment by IanYates** [comment]
Thanks @mhegazy - I have that enabled, but have always had that enabled since using TypeScript 9.x.  This "touch every single map file" behaviour is new in 1.8 beta (as far as I can tell) and the touch is very minor - only the last couple characters in the *really* long single-line map file change.  And it's every single map file in the project at once rather than just the map file of the TypeScript file I'm editing.

Disabling map file generation has at least stopped the problem for the moment.  I'm getting a new dev on the team shortly and I'd like for him to be able to use map files in the browser if that's his preference.  I'll enable it again later today or tomorrow and see if the problem resumes.

**Comment by mhegazy** [comment]
The only part of the system that writes to files is compile-on-save. if you have that disabled, i do not think this is the TypeScript language service that is doing this. can you share a project that exhibits the symptoms? i can not get it to repro locally.

**Comment by mhegazy** [comment]
@IanYates do you still see an issue here with TS 1.8.4?

**Comment by mhegazy** [comment]
closing for now. please reopen if it is still an issue.
