### ISSUE TITLE
New Website Logo: Playing

### ISSUE THREAD

**Issue by MadSpindel** [Microsoft/TypeScript#6953]
Please fill the following out:

- Name: Playing
- Homepage url: https://playing.se/
- Brand Guidelines/Licensing: None
- Logo: https://playing.se/media/images/forum/icons/playing-01.svg

> Example:
>
> Name: Microsoft
> Homepage url: https://microsoft.com
> Brand Guidelines/Licensing: https://www.microsoft.com/en-us/legal/intellectualproperty/trademarks/usage/logo.aspx
> Logo: https://news.microsoft.com/microsoft-news-center-photos/msft_logo_rgb_c-gray/

**Comment by mhegazy** [comment]
Logo uploaded, should be out in the next site refresh.
