### ISSUE TITLE
problem recompiling with asp.net 5 project

### ISSUE THREAD

**Issue by lucamorelli** [Microsoft/TypeScript#6954]
Hi, 
 I filed this bug #6841 but in the end I haven't solved the problem: I repaired the vs installation, added (theorically) the **Microsoft.Typescript.MsBuil**d package, tried with several combination of ts sdk installed but I'm not able to recompile ts projects inside asp.net 5: with **angular** and **aurelia (via jspm)** I receive the error message that is not able to find the packages, while an **angular 2 project (via npm )** gives me this error : 

> Build: Cannot re-export name that is not defined in the module.	Angular2Npm	G:\Sorgenti\TestDrive\src\Angular2Npm\node_modules\angular2\src\facade\promise.d.ts

	

  This beta is working fine with other asp.net 4 project and angular 1: I have the double that vs is actually running the nuget version of the compiler. How can I check this?

**Comment by lucamorelli** [comment]
this is the content of the xproj file

```
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="14.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <VisualStudioVersion Condition="'$(VisualStudioVersion)' == ''">14.0</VisualStudioVersion>
    <VSToolsPath Condition="'$(VSToolsPath)' == ''">$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)</VSToolsPath>
  </PropertyGroup>
  <Import Project="$(VSToolsPath)\DNX\Microsoft.DNX.Props" Condition="'$(VSToolsPath)' != ''" />
  <PropertyGroup Label="Globals">
    <ProjectGuid>a9ace5a4-c145-44d9-81c2-3ce702fd3fd1</ProjectGuid>
    <RootNamespace>Trace</RootNamespace>
    <BaseIntermediateOutputPath Condition="'$(BaseIntermediateOutputPath)'=='' ">..\artifacts\obj\$(MSBuildProjectName)</BaseIntermediateOutputPath>
    <OutputPath Condition="'$(OutputPath)'=='' ">..\artifacts\bin\$(MSBuildProjectName)\</OutputPath>
    <SccProjectName>SAK</SccProjectName>
    <SccProvider>SAK</SccProvider>
    <SccAuxPath>SAK</SccAuxPath>
    <SccLocalPath>SAK</SccLocalPath>
  </PropertyGroup>
  <PropertyGroup>
    <SchemaVersion>2.0</SchemaVersion>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <ProduceOutputsOnBuild>True</ProduceOutputsOnBuild>
  </PropertyGroup>
  <ItemGroup>
    <DnxInvisibleContent Include="bower.json" />
    <DnxInvisibleContent Include=".bowerrc" />
    <DnxInvisibleContent Include="package.json" />
  </ItemGroup>
  <ItemGroup>
    <DnxInvisibleCompile Include="Controllers\AccountsController.cs" />
  </ItemGroup>
  <ItemGroup>
    <DnxInvisibleFolder Include="App\Utenti\" />
    <DnxInvisibleFolder Include="wwwroot\uploads\" />
  </ItemGroup>
  <Import Project="$(VSToolsPath)\DNX\Microsoft.DNX.targets" Condition="'$(VSToolsPath)' != ''" />
</Project>

```

the Microsoft.TypeScript.MsBuild package is added to the project: I changed the log error level of msbuild to check what happens and I see this

```
2>Target "FindConfigFiles" in file "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\TypeScript\Microsoft.TypeScript.targets" from project "G:\Sorgenti\Tecnosanimed\src\Trace\Trace.xproj" (target "Compile" depends on it):
2>       Using "FindConfigFiles" task from assembly "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\TypeScript\TypeScript.tasks.dll".
2>       Task "FindConfigFiles"
2>       Done executing task "FindConfigFiles".
2>     1>
2>Done building target "FindConfigFiles" in project "Trace.xproj".
2>       Target "CompileTypeScript" skipped, due to false condition; ('$(BuildingProject)' != 'false' AND '@(ConfigFiles)' == '') was evaluated as ('true' != 'false' AND 'G:\Sorgenti\Tecnosanimed\src\Trace\tsconfig.json' == '').
2>       Target "PreComputeCompileTypeScript" skipped, due to false condition; ('@(ConfigFiles)' == '') was evaluated as ('G:\Sorgenti\Tecnosanimed\src\Trace\tsconfig.json' == '').
2>     1>
2>Target "PreComputeCompileTypeScriptWithTSConfig" in file "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\TypeScript\Microsoft.TypeScript.targets" from project "G:\Sorgenti\Tecnosanimed\src\Trace\Trace.xproj" (target "CompileTypeScriptWithTSConfig" depends on it):
2>       Using "VsTsc" task from assembly "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\TypeScript\TypeScript.tasks.dll".
2>       Task "VsTsc"
2>         C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.8\tsc.exe --project "G:\Sorgenti\Tecnosanimed\src\Trace\tsconfig.json"
2>       Done executing task "VsTsc".
2>     1>
2>Done building target "PreComputeCompileTypeScriptWithTSConfig" in project "Trace.xproj".
2>     1>
2>Target "CompileTypeScriptWithTSConfig" in file "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\TypeScript\Microsoft.TypeScript.targets" from project "G:\Sorgenti\Tecnosanimed\src\Trace\Trace.xproj" (target "Compile" depends on it):
2>       Building target "CompileTypeScriptWithTSConfig" completely.
2>       Output file "G:\Sorgenti\Tecnosanimed\src\Trace\App\app.js" does not exist.
2>       Task "VsTsc"
2>         C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.8\tsc.exe --project "G:\Sorgenti\Tecnosanimed\src\Trace\tsconfig.json"
2>     1>
2>App\Account\accountController.ts(17,37): error TS2503: Build: Cannot find namespace 'ng'.
2>
```

Looks like Visual Studio is not using the nuget package. Am I missing something?

**Comment by lucamorelli** [comment]
If could be of help I have a little update. As explained in the previous issues, after I've seen the problems with 1.8 I tried to uninstall it and reinstall 1.7 to continue to work to my projects, but even the installation was ok I had different problems compiling these asp.net 5 apps. I tried repairing vs, uninstalling and reinstalling 1.7 and 1.8 in any order without any changes. 
In the end I checked the directory **C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\TypeScript** and I found that at the end of the uninstall of every version of typescript I have this

![untitled](https://cloud.githubusercontent.com/assets/127777/12949674/5fb01ff6-d009-11e5-857a-a729697c3ba5.png)

At this point I tried to remove this directory completely and retried to uninstall typescript 1.7.6. and now it works fine.
I tried doing this cleaning up and installing 1.8 beta, but I continue to have the same problem, but at least now I can work on asp.net 5 projects.
I think that the problem rolling back to previous version was unable to overwrite at least the **TypeScript.Tasks.dll** generating an inconsistent behavior.
Could be possibile that to make work nightly builds of 1.8 I have to cleanup something else I wasn't able to find?

**Comment by jordimontana82** [comment]
Hi @lucamorelli 

I was having the same issue. I was running a aspnet5 rc1 app fine from a VS 2015 Community edition (without Update 1 nor Update 2) and it was broken after upgrading to VS 2015 Update 2.  Issue doesn't happen when I compile the project using `dnu build`, so it is VS / MSBuild specific.

After struggling for a couple of hours, I ended up editing the C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\TypeScript\Microsoft.TypeScript.targets file and commenting out all references to FindConfigFiles as a workaround:

`    <CompileDependsOn>
      ****
    <CleanDependsOn>
      $(CleanDependsOn);
      ****
      TypeScriptClean;
      TypeScriptCleanWithTSConfig;
    </CleanDependsOn>
    <BuiltProjectOutputGroupDependsOn>
      ****
`

This is ok as a workaround cause in the end I was using a Grunt task to watch, compile, and deploy ts files to wwwroot anyway, so compiling on Build it is not something I really needed, but at least I can run & debug C#.

**Comment by mhegazy** [comment]
@jordimontana82 if you are using grunt task, set `<TypeScriptCompileBlocked>true</TypeScriptCompileBlocked>` in your project. see http://www.typescriptlang.org/docs/handbook/compiler-options-in-msbuild.html#TypeScriptCompileBlocked

**Comment by mhegazy** [comment]
This should be addressed in the latest version of TS in VS2015 Update3 (https://www.visualstudio.com/en-us/news/releasenotes/vs2015-update3-vs). Please reopen if the issue still persists.
