### ISSUE TITLE
New Website Logo: Puzzlepart AS

### ISSUE THREAD

**Issue by olemp** [Microsoft/TypeScript#6956]
- Name: Puzzlepart AS
- Homepage url: http://www.puzzlepart.com/
- Brand Guidelines/Licensing: (or anything we need to know before using your logo)
- Logo: https://www.dropbox.com/s/9rgl5sl53w26ba2/Puzzlepart-Logo-Digital-800.jpg?dl=0

**Comment by mhegazy** [comment]
Logo uploaded, should be out in the next site refresh.
