### ISSUE TITLE
jsx:"preserve" + allowJs converts js to jsx

### ISSUE THREAD

**Issue by testerez** [Microsoft/TypeScript#6957]
When transpiling `js` files with the new `allowJs` param and `jsx:"preserve"`, all `js` files are output with `jsx` extention. Here is my tsconfig.json:

```json
{
    "compilerOptions": {
        "module": "es2015",
        "allowJs": true,
        "target": "es2015",
        "jsx": "preserve"
    }
}
```

**Comment by billti** [comment]
Duplicate of #6948 . (And fixed with #6949)
