### ISSUE TITLE
Typescript: Pass an extra parameter

### ISSUE THREAD

**Issue by nirus** [Microsoft/TypeScript#6963]
I was trying the below code from the [documentation](https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#14-structural-subtyping)

```
interface Point {  
    x: number;  
    y: number;  
}

function getX(p: Point) {  
    return p.x;  
}

class CPoint {  
    x: number;  
    y: number;  
    constructor(x: number,  y: number) {  
        this.x = x;  
        this.y = y;  
    }  
}

getX(new CPoint(0, 0));  // Ok, fields match

getX({ x: 0, y: 0, color: "red" });  // Extra fields Ok

getX({ x: 0 });  // Error: supplied parameter does not match
```

**As per the code comment says below line should be ok.**

`getX({ x: 0, y: 0, color: "red" });  // Extra fields Ok`

**But i am getting error as below:**

> error TS2345: Argument of type '{ x: number; y: number; color: string; }' is not assignable to parameter of type 'Point'. Object literal may only specify known properties, and 'color' does not exist in type 'Point'

**But the below code works well which i re-wrote in which i made params as optional:**

```
interface Point {  
    x: number;  
    y?: number; 
    color?: string; 
}

function getX(p: Point) {  
    return p.x;  
}

class CPoint {  
    x: number;  
    y: number;  
    constructor(x: number,  y: number) {  
        this.x = x;  
        this.y = y;  
    }  
}

getX(new CPoint(0, 0));  // Ok, fields match

getX({ x: 0, y: 0, color: "red" });  // Extra fields Ok

getX({ x: 0 });  // Error: supplied parameter does not match
```

Please can somebody help me out if the documentation is wrong or am i missing something here

**FYI i am using:**
- Typescript v1.7.5
- Visual studio code

Same is been asked in [stackoverflow](http://stackoverflow.com/questions/35267467/typescript-pass-an-extra-parameter): 

I have attached the screenshot FYI.
![capture](https://cloud.githubusercontent.com/assets/2213751/12885110/39bf9fa0-ce89-11e5-9e49-55b549bdaa38.PNG)

**Comment by yortus** [comment]
I'd say the documentation wrong / out of date. The error you are seeing is an example of #3823. It would have worked before that PR, which landed in v1.6.

**Comment by DanielRosenwasser** [comment]
This is in the spec, not the docs.

**Comment by nirus** [comment]
As pointed by the [Stackoverflow ](http://stackoverflow.com/questions/35267467/typescript-pass-an-extra-parameter)answer below code fixes the problem

` getX({ x: 0, y: 0, color: "red" } as Point); // no error`

This is not given in spec.

**Comment by weswigham** [comment]
It's a cast - casting is in the spec, and it's a feature. Just remember that a cast is basically you overriding the compiler and saying "this is the type of this thing at this position", and so its mostly your responsibility to make sure it's valid to cast in a given situation.

**Comment by weswigham** [comment]
A "nicer" way to "fix" the types and allow passing an argument with extra members would be modifying the signature of `getX` like so:
```ts
function getX<T extends Point>(p: T) {  
    return p.x;  
}
```
Though it may not be immediately obvious how this is any different.

**Comment by mhegazy** [comment]
for future references, more information about strict object literal checking can be found at https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes#strict-object-literal-assignment-checking
