### ISSUE TITLE
Language services debug assertion when switching compiler options

### ISSUE THREAD

**Issue by martine** [Microsoft/TypeScript#6965]
Suppose you are writing a client of the LanguageService that provides a LanguageServiceHost that implements getCompilationSettings to return CompilerOptions that target ScriptTarget.ES5.

If you compile once, then change getCompilationSettings to instead target ScriptTarget.ES6 -- that is, if you dynamically switch the targeted language -- you'll eventually fall into the below code path and hit the debug assertion seen in the snippet.

However, it appears the below code after the debug assertion is attempting to correctly handle the case where the settings have changed.  So I think that the debug assertion is unnecessary and should be removed.

This issue can also be worked around by recreating the whole stack of LanguageServiceHost from scratch when the compilation target changes, but that seems like it might be slow.  It's potentially the case that clients should expect to recreate this object in that scenario, but then it's not clear why the below code handles the missing entry.

Feel free to tell me I'm using the API wrong, or whether a reproduction test case would be useful (I pulled this out of a much larger program so reducing it will be a bit painful).

```javascript
        function acquireOrUpdateDocument(fileName, compilationSettings, scriptSnapshot, version, acquiring) {
            var bucket = getBucketForCompilationSettings(compilationSettings, /*createIfMissing*/ true);
            var path = ts.toPath(fileName, currentDirectory, getCanonicalFileName);
            var entry = bucket.get(path);
            if (!entry) {
                ts.Debug.assert(acquiring, "How could we be trying to update a document that the registry doesn't have?");
                // Have never seen this file with these settings.  Create a new source file for it.
                var sourceFile = createLanguageServiceSourceFile(fileName, scriptSnapshot, compilationSettings.target, version, /*setNodeParents*/ false);
                entry = {
                    sourceFile: sourceFile,
                    languageServiceRefCount: 0,
                    owners: []
                };
                bucket.set(path, entry);
            }
 ```

**Comment by mhegazy** [comment]
The system assumes that files and compilation settings are not mutable. there are places that are built on this assumption. creating a new LS object is the correct way to go. the system is wired to make this a cheap operation, by caching SourceFile objects, and reusing them.
