### ISSUE TITLE
Class Declaration Extends Null Can't have super-call

### ISSUE THREAD

**Issue by yuit** [microsoft/TypeScript#6968]
As pointed out by @DanielRosenwasser in the PR #6860, our spec is not up-to-date regarding class extends null [here](https://github.com/Microsoft/TypeScript/blob/116bce37ea71a5b4422dbba72454f640b944c4b2/doc/spec.md#832-super-calls) Also we should update the comment in lin Checker.ts line in `checkConstructorDeclaration`

**Comment by RyanCavanaugh** [comment]
@yuit is this a spec bug or an implementation bug?

**Comment by e-cloud** [comment]
@RyanCavanaugh yes, it's a spec bug before. But the spec has been fixed for months.

See https://github.com/tc39/ecma262/issues/543

And now Typescript is violating the spec.

**Comment by mhegazy** [comment]
this issue is tracking updating the [TypeScript spec](https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md) and not the ECMAScript spec. I am not sure how the compiler is violating the spec, the compiler gives you an [error](http://www.typescriptlang.org/play/index.html#src=class%20C%20extends%20null%20%7B%20%0D%0A%20%20a%3A%20number%3B%0D%0A%20%20constructor()%20%7B%20%0D%0A%20%20%20%20this.a%20%3D%200%3B%0D%0A%20%20%20%20super()%3B%0D%0A%20%20%7D%0D%0A%7D) if you try to access `super` in a class that extends `null`.

**Comment by e-cloud** [comment]
But the Typescript spec is "old" as v1.8. now the source have been v2.1.

As the sologan says:
![image](https://cloud.githubusercontent.com/assets/5255354/20821537/4608a0e2-b87e-11e6-9090-dac1aff36ef1.png)

Shouldn't the spec of Typescript be the superset of ECMAScript spec?

**Comment by mhegazy** [comment]
The spec is a super set of ECMAScript. As a matter of fact, the TypeScript spec clearly states it is an [augmentation](https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#2-basic-concepts) to the ECMAScript 2015 spec (emphasis mine):

>The remainder of this document is the formal specification of the TypeScript programming language and is **intended to be read as an adjunct to the ECMAScript 2015 Language Specification (specifically, the ECMA-262 Standard, 6th Edition)**. This document describes the syntactic grammar added by TypeScript along with the compile-time processing and type checking performed by the TypeScript compiler, but it only minimally discusses the run-time behavior of programs since that is covered by the ECMAScript specification.

So any ES2015 feature or spec change is implicitly included in the TS spec. 

As for the spec not being updated. yes, this is an issue, we are working on updating the spec. but we are small team, and we have been busy at work getting some [awesome new features](https://github.com/Microsoft/TypeScript/wiki/What%27s-new-in-TypeScript) out. bear with us for a little bit and the spec should be updated to reflect these features.

**Comment by e-cloud** [comment]
I really appreciate the effort your team have made for a greater Typescript.

If my words offend you, **I apologize for it**.

What i commmented is just for reminding. It may has low priority.

**Comment by mhegazy** [comment]
No offense taken, and no apologies required. The spec is out of date, and we need to update it. Your feedback is important to us, so keep it coming!

**Comment by saschanaz** [comment]
One year later: The tc39/ecma262#543 is reverted by https://github.com/tc39/ecma262/pull/781.
