### ISSUE TITLE
why this code provides no error?

### ISSUE THREAD

**Issue by sagifogel** [Microsoft/TypeScript#6969]
```javascript
module M {
     class A {
		c(a: number): A {
			return new B();
		}
	}
}

function B() {
}

**Comment by RyanCavanaugh** [comment]
https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#414-the-new-operator

For compat reasons, void-returning functions invoked with `new` return a value of type `any`.

You can cause this to be an error by running with the `--noImplicitAny` switch.
