### ISSUE TITLE
allow type functions/algebras for operators

### ISSUE THREAD

**Issue by zpdDG4gta8XKpMCd** [microsoft/TypeScript#6970]
``` typescript
interface In<a> = { __in: a };
interface Ratio<a, b> = { __ratio: [a, b]; }
let value : number & In<MHz>;
let scale : number & Ratio<Px, MHz>;
declare *<a, b>(left: number & In<a>, right: number & Ratio<b, a>): number & In<b>;
let width = value * scale; // <-- expected number & In<Px>;
```

**Comment by aleksey-bykov** [comment]
related: #4372, #4895, #5599, #6947, #6735

**Comment by DanielRosenwasser** [comment]
In what way is this distinct from #364?

**Comment by aleksey-bykov** [comment]
Units of measure are governed by the rules of arithmetics. Here you define
rules as you like.

**Comment by aleksey-bykov** [comment]
Which is still 95% of arithmetics when it comes to numbers, but numbers are only a special case

**Comment by aleksey-bykov** [comment]
more to that, a special case in form of units of measure isn't even in the
agenda of tge future development, whereas a more general solution might
make them worthless and unnecessary

**Comment by RyanCavanaugh** [comment]
Closing due to lack of additional feedback
