### ISSUE TITLE
tsd integration in tsserver/language service API

### ISSUE THREAD

**Issue by angelozerr** [Microsoft/TypeScript#6971]
RoadMap 2.0 contains "tsd integration in tsserver/language service API" but the issue doesn't eixts. That's why I create it.

If I understand well, tsserver will able to send event (like semantic/syntax diagnostic) when a tsd file changed and must be compiled to js and *.js.map. The benefit with this feature is that we can use compiled file from tsserver in memory to transform it to js and source map.

**Comment by mhegazy** [comment]
related to https://github.com/Microsoft/TypeScript/pull/6448

**Comment by glen-84** [comment]
Did you consider using [Typings](https://github.com/typings/typings)?

**Comment by angelozerr** [comment]
@mhegazy is https://github.com/Microsoft/TypeScript/pull/6448 will support throw of events (like semantic/syntax diagnostic) with JSON response with ts files which are compiled (with or without errors?)

**Comment by mhegazy** [comment]
The current design, is it is run when the server thinks something changed, i.e. a new file added or removed, or a watched folder/file changed. no other events are raised at that point, as it it is akin of adding a `/// <reference` to your code, and the server picking up the new file.

**Comment by mhegazy** [comment]
This is obsolete now as we have moved to npm for acquiring type declaration packages.
