### ISSUE TITLE
Consider removing usage of 'fs.existsSync'

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#6972]
`exists` and `existsSync` are [deprecated](https://nodejs.org/api/fs.html#fs_fs_exists_path_callback) (see https://github.com/nodejs/node/issues/103 and https://github.com/nodejs/node/issues/1592) and it seems that the "right" thing to do is a `try`/`catch` with a call to `stat`/`statSync` or `access`/`accessSync`.

In `sys.ts`, we use `fs.existsSync` for `fileExists`, `directoryExists` (and thus `createDirectory`), and `readFile`.

**Comment by RyanCavanaugh** [comment]
Based on the discussion in 1592 I don't think `existsSync` is going anywhere

**Comment by DanielRosenwasser** [comment]
I think we're going to need an [`fsExistsSyncExistsSync`](https://github.com/nodejs/node/issues/1592#issuecomment-147138268).

**Comment by RyanCavanaugh** [comment]
It's still there!
