### ISSUE TITLE
IntelliSense for Object Literal Properties

### ISSUE THREAD

**Issue by chase-moskal** [microsoft/TypeScript#6975]
In both the [**TypeScript Playground**](http://www.typescriptlang.org/Playground) as well as VS Code, code hints don't appear complete for properties of object literals, and the goto definition doesn't seem to work:

``` typescript
interface Item {

    /** Doc-comment. */
    alpha: number;
}

let item: Item = {

    alpha: 10
//    ^
//     \---- Goto definition not working?
//      ---- Code hint doesn't display doc-comment?
};

item.alpha = 10;
//     ^
//      \---- Goto definition works :)
//       ---- Code hint shows doc-comment :)

// Since `alpha` is a required property,
// I am obliged to declare it upfront in object literal form..
//  ..I am forced to miss out on intellisense features?
```

Note, the property's type _is_ displayed in the code hint, and the refactor/rename function _does_ work -- so it's not all missing.

I was hoping to fully leverage intellisense features in TS files that I am using like JSON files to declare data structured in accordance with TS interfaces. Am I going about this the wrong way, or is this currently a lacking TypeScript/IntelliSense capability?

_Loving TypeScript with VS Code,
Thanks!_

**Comment by RyanCavanaugh** [comment]
It'd be nice if this worked.

For anyone looking to implement this, the fix would be (in services.ts) to use the contextual type of the object literal (the same way we do to establish the completion list for the property names) to remap the property names inside the literal to their corresponding symbols in the contextual type. Once that's hooked up, everything should just work.

**Comment by DanielRosenwasser** [comment]
Anyone should make sure that the following case works correctly, in that go-to-definition at `/*use*/` jumps to `/*declaration*/`

```ts
interface I {
    xyz: number;
}

/*declaration*/let xyz = 10;
let obj: I = {
    xyz/*use*/
}

**Comment by MgSam** [comment]
Would be really nice if this worked. It makes object literals much harder to use without it.

**Comment by timothyallan** [comment]
I've just run into this as well on a conversion from js -> ts with property heavy objects. I'm almost wondering if using simple classes is the way to go, that way the intellisense works and makes life much easier...

**Comment by RyanCavanaugh** [comment]
This works now
