### ISSUE TITLE
Salsa: jsdoc intellisense not support custom class and @typedef

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/TypeScript#6976]
Moved from microsoft/vscode#2817
From @Thaina

I was upgrade to use salsa and most of thing work fine. which is really great

Except custom type and `@typedef` which cannot registered in intellisense

As the image shown. type of pos0 parameter is not Point object I was created. While pos1 is correct

![screen shot 2559-02-09 at 12 40 30 pm](https://cloud.githubusercontent.com/assets/1042507/12908467/66b2836e-cf2a-11e5-8a92-0da34e786f9c.png)

**Comment by billti** [comment]
Currently `@constructor` or `@typedef` are not supported, and won't be in the upcoming 1.8 release. We'll consider for 2.0.

**Comment by Thaina** [comment]
@billti So without `@constructor` or `@typedef` it cannot register custom type at all?

**Comment by billti** [comment]
You can currently reference a TypeScript "*.d.ts" file in the project, and those types will be useable in the JavaScript file's JsDoc comments. Long term we hope to add more support for specifying the types in JsDoc annotations (such as those mentioned), but this is an option to unblock you currently.
