### ISSUE TITLE
Salsa: jsdoc intellisense not support @type tag

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/TypeScript#6977]
Moved from microsoft/vscode#2819
From @Thaina 

Marking local variable with `@type` not support in salsa

![screen shot 2559-02-09 at 1 10 25 pm](https://cloud.githubusercontent.com/assets/1042507/12908960/8d81bab0-cf2e-11e5-81a6-e06110095a86.png)

**Comment by billti** [comment]
It supports the `@type` tag, but the above type is invalid. There should be no "." after `number`, and there is no `null` type (you can use `void`, but as types are nullable by default, not sure what value either gets you). See below for example of how it looks on my machine.

<img width="392" alt="screen shot 2016-02-09 at 7 57 21 am" src="https://cloud.githubusercontent.com/assets/993909/12921668/28252524-cf03-11e5-9430-b28615cc4163.png">

**Comment by weswigham** [comment]
For the record: The closure compiler actually exposes JSDoc types for `null` and `undefined` - additionally, the type [`T|null`](https://developers.google.com/closure/compiler/docs/js-for-compiler#tag-param) is roughly `T?` and [`T|undefined` = `T=`](https://developers.google.com/closure/compiler/docs/js-for-compiler#variable-parameters).  This is a case where TS presently differs from the closure compiler in its understanding of types, as TS doesn't expose an `undefined` or `null` type (TS exposes `void`).
