### ISSUE TITLE
Add compiler flag to list output files

### ISSUE THREAD

**Issue by angelozerr** [Microsoft/TypeScript#6978]
I would like to implement compilation of ts files to generate source map + js files inside Eclipse by using `tsc`. I have 2 means to do that:

 1) observe changes (with Eclipse IResource API) of typescript files and call `tsc` with the given file
 2) call `tsc --watch` for my Eclipse project

I would prefer to do the 2) because`tsc --watch`  if I have understood stores in memory the other compiled ts files, so I think performance will be better with 2). My main problem is about refresh generated files:

 * when there is an error,`tsc --watch` displays in the console errors for files. So it's easy to catch those logs and display errors in Eclipse Problem View.
 * but when there are none errors, `tsc --watch` doesn't display in the console the generated files in order I refresh it inside Workspace Eclipse. I would like to avoid refreshing the full project directory as soon as  `tsc --watch` done a job. If `tsc --watch` could log generated files, it will help me a lot.

Many thanks for your suggestion!

**Comment by mhegazy** [comment]
so to be clear, what you are looking for is something like --listOutFiles (https://github.com/Microsoft/TypeScript/pull/5476) but for --watch, correct?

**Comment by angelozerr** [comment]
> so to be clear, what you are looking for is something like --listOutFiles (#5476) but for --watch, correct?

Yes exactly! A JSON format should be welcome too for the message, to avoid using some regexp to extract info (lke error line, etc). 

An other idea, tsserver could provide a new command "tsc"?

**Comment by mhegazy** [comment]
> An other idea, tsserver could provide a new command "tsc"?

the language service already provides a similar feature (getEmitOutput), but we would like to keep tsc --watch as the main entry point here.

**Comment by paulvanbrenk** [comment]
This looks like the same request as #3650

**Comment by mhegazy** [comment]
thanks. indeed a duplicate.
