### ISSUE TITLE
Types in HTMLCollection

### ISSUE THREAD

**Issue by elbarzil** [Microsoft/TypeScript#6985]
I ran into a problem where

    someElement.children[0].children[0]

doesn't work because the result of `someElement.children[0]` is an `Element` rather than an `HTMLElement`.  I'm not sure whether there is any situation of dealing with DOM elements in which you'd get something that is an `Element` but not an `HTMLElement`.  I also see in Issue #4689 that there are some operations where `HTMLElement` is used for convenience -- maybe this should be included too?

(Apologies if this is a FAQ.)

**Comment by RyanCavanaugh** [comment]
SVG elements are not HTMLElements, e.g. http://codepen.io/anon/pen/ZQmPjx

**Comment by elbarzil** [comment]
Bah.  Thanks!
