### ISSUE TITLE
Copy value and debug console only output 10000 characters

### ISSUE THREAD

**Issue by jjmartin** [Microsoft/TypeScript#6989]
I understand that you might want to only preview 10000 chars in a string, but if i ask for the value in debug i kinda feel like it shouldn't limit it and certainly not modify the string - i have a string I am trying to get and it gets modified in debug like: its only the left 10000 + "... (length: 16384)"    

it looks like this might be coming from the V8 Debugger this way but is there a way to adjust it in VS Code? 
https://github.com/node-inspector/node-inspector/issues/29

**Comment by mhegazy** [comment]
how is this related to TypeScript?

**Comment by mhegazy** [comment]
I would say this should go to [node-inspector](https://github.com/node-inspector/node-inspector) / [VSCode](https://github.com/Microsoft/vscode). closing as external.
please reactivate if this is not the case, and provide more information on how the TS compiler is causing this issue.

**Comment by jjmartin** [comment]
sorry about that i thought i was in the code repo...
