### ISSUE TITLE
Allow type declaration on constructors

### ISSUE THREAD

**Issue by Jameskmonger** [Microsoft/TypeScript#6999]
At present, constructors in a class can only be typeless. This can be a stark contrast to the other members in classes, which all have explicitly declared types.

This is how a current class looks:

    class Foo {
        private _bool: boolean;

        constructor() {
            this._bool = true;
        }

        public doSomething(): void {
            // TODO: implement code
        }

        public getBool(): boolean {
            return this._bool;
        }
    }

I think there would be more consistency in classes if type declarations were permitted as long as they were the same type. They would effectively be redundant, but would make the class more readable, in my opinion. The above class would then be written like so:

    class Foo {
        private _bool: boolean;

        constructor(): Foo {
            this._bool = true;
        }

        public doSomething(): void {
            // TODO: implement code
        }

        public getBool(): boolean {
            return this._bool;
        }
    }

**Comment by RyanCavanaugh** [comment]
This doesn't seem to be a common problem in terms of readability in a way that outweighs the possible user confusion of what this would mean. 90%+ of the time, you can see the enclosing class name a few lines higher; if not, there's always comments.
