### ISSUE TITLE
Suggestion: 'for..of'

### ISSUE THREAD

**Issue by RyanCavanaugh** [Microsoft/TypeScript#7]
Implement TypeScript support for the `for-of` loop as described in the ES6 proposal

Reference: https://github.com/dherman/tc39-codex-wiki/blob/master/data/es6/for-of/index.md

To be determined: What cases can we support code generation for when targeting pre-ES6 targets?

**Comment by DickvdBrink** [comment]
I guess this is #2207 and #2164 (the latter ins't merged yet)

**Comment by danquirk** [comment]
Yep, thanks, we'll close this when we finish adding the type check work for downlevel.
