### ISSUE TITLE
TypeError: Cannot read property 'type' of undefined at getJSDocTypeForVariableLikeDeclarationFromJSDocComment

### ISSUE THREAD

**Issue by magnushiie** [Microsoft/TypeScript#7002]
With the current master, the compiler crashes when the `@type` JSDoc annotation of a variable is malformed, e.g. in the following (shortened) example from [lodash](https://github.com/lodash/lodash/blob/4.3.0/lodash.js#L9452):
```javascript
/**
 * Checks if `value` is classified as an `Array` object.
 *
 * @type Function
 */
var isArray = Array.isArray;
```

This is in the statement `return annotation.typeExpression.type;`;

This compiles fine if `Function` above is replaced with `{Function}`.

It seems this is similar to #6709 and `annotation.typeExpression` needs checking too.

I could submit a PR, but I understand from CONTRIBUTING.md that the issue needs approval first?

**Comment by billti** [comment]
@RyanCavanaugh Seems like possibly the same root cause as #6984 .

**Comment by RyanCavanaugh** [comment]
Thanks for the report!

FWIW in the future if you find a crashing bug, we'll pretty much always accept PRs on those -- no need to wait for any action. But hopefully that doesn't happen again :wink:
