### ISSUE TITLE
Support json files

### ISSUE THREAD

**Issue by testerez** [Microsoft/TypeScript#7005]
The 1.8 version supports `js` files as input. Is it possible to support also `json` files ?

**Comment by mhegazy** [comment]
The compiler extracts declarations for JS files, and transpiles ES6 constructs down to ES5/ES3. JSON is a data format, and neither of the two actions apply here.

**Comment by testerez** [comment]
So they could be output as is. It is common to include json files in js projects. Converting such a project with typescript leads to an invalid output making migration to typescript harder.

**Comment by testerez** [comment]
And json data structure could be used for type checking.

**Comment by mhegazy** [comment]
> So they could be output as is. It is common to include json files in js projects. Converting such a project with typescript leads to an invalid output making migration to typescript harder.

so why not copy the files in a build step. why do you need the compiler to read them and write them again, saves your build time. also that applies to other resouces, e.g. html, css, img, etc..

>And json data structure could be used for type checking.
 
it is not clear how this works. the syntax of the json files does not lend itself to typings the way TS does it. Moreover, interfaces in TS does that already, and for json, you have JSONSchema to do that. so not sure i see much crossover here.

**Comment by tp** [comment]
A use case I would have for this is a project with many independent modules, which need a package.json for the "main" entry point mapping.

But since TS does not copy them, module loading currently fails for those packages.

**Comment by kitsonk** [comment]
TypeScript isn't a build tool... it a compiler... Using something like `grunt` or `gulp` is really useful part of a full build toolchain, because it can deal with non-transpiled resources effectively (or resources that are transpiled by other compilers).
