### ISSUE TITLE
allowJs + target + outDir do not work as expected if we change target.

### ISSUE THREAD

**Issue by xLama** [Microsoft/TypeScript#7013]
Example class:

![image](https://cloud.githubusercontent.com/assets/8139881/12966167/344fba4e-d05c-11e5-89d8-350feb09d478.png)

tsconfig.json

![image](https://cloud.githubusercontent.com/assets/8139881/12966177/40c3f628-d05c-11e5-9147-4a84b6924f58.png)

If we transpile it, it works nice:

![image](https://cloud.githubusercontent.com/assets/8139881/12966181/4c0f1080-d05c-11e5-969f-6a8e298025fc.png)

Now we change target from es5 to es6. It make another folder inside previous one but new foo.js is es5 yet

![image](https://cloud.githubusercontent.com/assets/8139881/12966186/5361bfae-d05c-11e5-9c76-9e8cb59de328.png)

![image](https://cloud.githubusercontent.com/assets/8139881/12966194/60b6ba24-d05c-11e5-9bc4-943564bdca77.png)

If we transpile again...

![image](https://cloud.githubusercontent.com/assets/8139881/12966198/6eae67b2-d05c-11e5-906d-bd27a6739600.png)

But if we do the same in revert order, from es6 to es5, It works nice.

![image](https://cloud.githubusercontent.com/assets/8139881/12966210/880b008a-d05c-11e5-9376-0e893b430472.png)

![image](https://cloud.githubusercontent.com/assets/8139881/12966220/919f458e-d05c-11e5-8c64-265eb914f152.png)

![image](https://cloud.githubusercontent.com/assets/8139881/12966231/9ff65e1a-d05c-11e5-91b0-12a9b9d7edd0.png)

![image](https://cloud.githubusercontent.com/assets/8139881/12966235/a542ea82-d05c-11e5-82be-6a3a5c22d270.png)

It occurs with following versions: 1.8.0 and 1.9.0-dev.20160210

**Comment by mhegazy** [comment]
Two things going on here. 1. if you use `--allowJs` all .js files in your folder will be automatically picked up (use `--listFiles` to see what files the compiler is picking up); that means `foo.ts` and `otherDir\foo.js` are now part of your compilation.

2. use "rootDir" to identify your root of the input directory structure you want to replicate in your output. If not specified, the rootDir is computed to be the longest path prefix of all input files (in your case, `foo.ts` and `otherDir\foo.js`, and thus the extra `otherDir` created in the output.

I assume what you need is to add "exclude" : "otherDir" to your tsconfig.

**Comment by makc** [comment]
@mhegazy can you comment why 
```
    "allowJs": true,
    "outDir": "./dist/out-tsc",
```
could still produce `TS5055: Cannot write file ... because it would overwrite input file` in src folder? sc --version is 2.6.2. as if the outDir does not have any effect.

**Comment by makc** [comment]
@mhegazy ok, it seems to be not just typescript config issue, as `tsc` does not produce any errors at all, only `ng build` does.
