### ISSUE TITLE
Suggestion regarding --noCustomAsyncPromise

### ISSUE THREAD

**Issue by yortus** [Microsoft/TypeScript#7018]
The `--noCustomAsyncPromise` switch was just introduced #6967.

ES7 async functions cannot return custom promises, but their TypeScript counterparts can. This switch makes it so that TypeScript's non-compliant async function behaviour is the default, and anyone wanting to maintain ES-compliant code has to provide this switch.

Why not have an `--allowCustomAsyncPromise` instead? Then anybody can opt in to TypeScript's custom async function behaviour, but is made more aware they are doing something special/non-standard because they need to provide the flag.

The current polarity of the flag may encourage a great deal more inadvertent use of this non-standard behaviour, causing greater pain down the line when async functions gain better runtime support and adoption. I think it would be prudent to put the non-standard behaviour behind a flag, and make standard behaviour the default.

**Comment by mhegazy** [comment]
Please note this is a 1.8-only flag, and will not exist after that. it is not documented. you are welcome to use it for now if you would like your project to be checked more stricktelly.
The change was a breaking change that broke multiple customers. there is no easy way now to use it async/await with ES5 nor to redefine Promise if you are using ES6. we are working on these for the next release. once that is done the breaking change should be easily avoided by either switching to ES5 or redefining the Promise value.

**Comment by yortus** [comment]
Cool, thanks for clarifying.
