### ISSUE TITLE
"Go to Definition" can't run when method declarations

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#7023]
_From @lv7777 on February 9, 2016 13:47_

```javascript
let foo= function(){
}
foo;
```
above code can right,but

```javascript
let obj;
obj.foo= function(){
}
foo;
```
can't f12

_Copied from original issue: Microsoft/vscode#2842_

**Comment by dbaeumer** [comment]
IMO foo can't be f12 since foo is unknown in the second example. foo only exists as a property of obj. Moving to TS repository for final closing.

**Comment by RyanCavanaugh** [comment]
Go To Definition doesn't work on string matching (nor should it IMO)
