### ISSUE TITLE
MSBuild task for Typesccript uses file creation time in FindConfigFiles

### ISSUE THREAD

**Issue by mykohsu** [Microsoft/TypeScript#7035]
Depending on the source control system, if the file creation time is not set to the actual development file creation time, the ordering of tsconfig builds can be changed resulting in build failure.

Can we use alphabetical ordering or some other option to ensure ordering is repeatable?

**Comment by mhegazy** [comment]
you should use multiple projects if you have this sort of dependency. Project is the build unit for MSBuild, and you can declare dependencies on each other etc..

**Comment by mykohsu** [comment]
MSBuild tasks for other project types generally use alphabetical ordering. Is there a scenario where creation time ordering makes sense?

**Comment by mhegazy** [comment]
i do not think you should take a dependency on this, and name your projects based on their position in the dependency graph. this breaks parallel build. Instead use ProjectReference entries to declare dependencies. this works all the time, regardless of whether the targets file sorts the files before it calls tsc on them or not.

**Comment by paulvanbrenk** [comment]
@mykohsu we don't do any sorting, but process the files in the order we encounter them, either in the project file or on disk... if you need explicit ordering use separate projects as @mhegazy suggested.

**Comment by mykohsu** [comment]
@mhegazy I agree. I am going to pitch this internally.

@paulvanbrenk  That's interesting, because I have tested and can confirm the order is based on file creation timestamp. Making a copy of the tsconfig puts it last. I suppose this is down to the file system API.

**Comment by paulvanbrenk** [comment]
@mykohsu Well... making a copy will also put it last in the project file, if you switch the order in the project file that'll be the new order they are built in.

**Comment by mykohsu** [comment]
@paulvanbrenk I am not making a copy in the project file - just a copy on the file system and replacing the existing file.

**Comment by paulvanbrenk** [comment]
What kind of project are you using?

**Comment by mykohsu** [comment]
HTML Project with Typescript.
