### ISSUE TITLE
'big.js': EISDIR: illegal operation on a directory, read

### ISSUE THREAD

**Issue by magnushiie** [Microsoft/TypeScript#7037]
When trying to import [big.js](https://github.com/MikeMcl/big.js/) package, TypeScript attempts to read it as file, resulting in EISDIR error.

For repro, create the following tsconfig.json:
```json
{
  "compilerOptions": {
    "allowJs": true,
    "outDir": "lib",
    "module": "commonjs",
    "target": "es5",
    "baseUrl": ".",
    "paths": {
      "*": [
        "*", 
        "node_modules/*"
      ]
    }
  },
  "files": ["test.js"]
}
```

and source file:
```javascript
import 'big.js';
```

And execute:
```sh
npm install big.js
tsc
```

The result:
```log
test.js(1,8): error TS5012: Cannot read file 'C:/Test/ts-eisdir/node_modules/big.js': EISDIR: illegal operation on a directory, read
```

The [npm package name rules](https://docs.npmjs.com/files/package.json) say the name can't start with a period, but it seems it's allowed to contain a period. And although it's recommended not to have "js" in the name, it's not disallowed.

**Comment by mhegazy** [comment]
//cc: @vladima

**Comment by vladima** [comment]
@magnushiie thanks for reporting this issue, it is fixed in master and should be available in todays nightly build (`typescript@next` on npm)

**Comment by magnushiie** [comment]
Thank you for the quick fix!
