### ISSUE TITLE
Please allow require to work with json file

### ISSUE THREAD

**Issue by Thaina** [Microsoft/TypeScript#7043]
require should able to parse json file

**Comment by RyanCavanaugh** [comment]
Please include enough information in your issue report so that we can understand what you're referring to and what you'd like to happen. Half a sentence plus a title is not enough.

**Comment by Thaina** [comment]
@RyanCavanaugh If you need more information why you close issue?

**Comment by Thaina** [comment]
And this is what I mean

![image](https://cloud.githubusercontent.com/assets/1042507/11888354/0f4732d0-a56f-11e5-810c-557adcec94b4.png)
