### ISSUE TITLE
Set prototype directly does not register in intellisense

### ISSUE THREAD

**Issue by Thaina** [Microsoft/TypeScript#7046]
Salsa intellisense could register member of function from prototype

![screen shot 2559-02-12 at 2 40 01 pm](https://cloud.githubusercontent.com/assets/1042507/13001315/2f025718-d197-11e5-9ba7-0c3f98db7ea7.png)

But it does not account the setting to prototype

![screen shot 2559-02-12 at 2 40 18 pm](https://cloud.githubusercontent.com/assets/1042507/13001319/37380a4a-d197-11e5-8d1d-7238ec86cecb.png)

**Comment by sandersn** [comment]
This works now and should be available in Typescript 2.9.
