### ISSUE TITLE
Importing amd i18n plugin file

### ISSUE THREAD

**Issue by sercangurbuz** [Microsoft/TypeScript#7050]
To Import the amd plugin [i18n ](http://requirejs.org/docs/api.html#i18n)file,
1)I defined localization file in nls folder style for en-US (./app-resources/nls/resources) 
`define({
    todo: {
        todolist: 'Todo List',
        todo: 'Task',
        done: 'Done',
        state: 'State'
    }
});` 
2) for TS resolution,defined module with extract path as following in a.ts
`declare module "i18n!app-resources/nls/resources" {
    let json: any;
    export default json;
}`
3) Import the module like below in b.ts 
`import appresource from "i18n!app-resources/nls/resources";`

i18n file succesfully loaded as dependency.problem is here when you use the appresource in b.ts,it appears as **appresource.default**  which is null because todo object is assigned to appresource obj itself.

What would be the way of doing this binding correctly ?

using vs 2015 ,ts ver 1.8

**Comment by sercangurbuz** [comment]
using 'require' fixed the case.
`import appresource = require('i18n!app-resources/nls/resources');`

Is there any solution for es6 way?

**Comment by mhegazy** [comment]
`import appresource from "i18n!app-resources/nls/resources";` => import the `default` property of the module. if the module does not have one, you get undefined.

what you need is `import * as appresource from "i18n!app-resources/nls/resources";` instead.

**Comment by mhegazy** [comment]
here is more documentation about modules: https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Modules.md

**Comment by sercangurbuz** [comment]
Thanks :thumbsup:
