### ISSUE TITLE
VS - Typescript compile does not execute during build (for CONSOLE application)

### ISSUE THREAD

**Issue by golfguy0082** [Microsoft/TypeScript#7052]
I have a git repository stored in Visual Studio Online (or whatever the new name is).  In that repository is a *csproj that was configured for typescript.  If I clone that repository onto a new machine and do a build from within visual studio, the typescript compiler does not run.  If I open a *.ts file, make an arbitrary change and save, all *js files are generated as expected (when I save the file).  I checked the *.csproj file and see this (which I think is correct):

<Import Project="$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\TypeScript\Microsoft.TypeScript.targets" Condition="Exists('$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\TypeScript\Microsoft.TypeScript.targets')" />
  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />

Anyone have any idea why the typescript compiler does not seem to be triggered during the build?  Any suggestions for diagnostics I can put in to get more info?

**Comment by mhegazy** [comment]
I will need the build log to be able to help you out. Run `msbuild /v:detailed project.csproj`.

Looks like you have compile-on-save enabled, that is why saving a file causes the generation of outputs.

**Comment by golfguy0082** [comment]
It appears I jumped the gun.  I created a new project to try to reproduce this issue, and I was unable to reproduce it in a new WEB app.  I then realized that my current project is actually a **CONSOLE** app (I'm self-hosting a Nancy application that also uses typescript).  When comparing the two *.csproj files, it finally came down to this line that got things working:

<Import Project="$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v10.0\WebApplications\Microsoft.WebApplication.targets" Condition="false" />

Is this the RECOMMENDED way to get the typescript build working in a Console application?  Is building typescript in a console application a supported scenario?

**Comment by golfguy0082** [comment]
Looks like it didn't like the XML formatting.....it was an import of $(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v10.0\WebApplications\Microsoft.WebApplication.targets

**Comment by mhegazy** [comment]
you need the .props file (for defaults) and the .targets file: https://github.com/Microsoft/TypeScript/wiki/Integrating-with-Build-Tools#msbuild

you can also use NuGet: https://github.com/Microsoft/TypeScript/wiki/Integrating-with-Build-Tools#nuget
