### ISSUE TITLE
Optionally resolved external types

### ISSUE THREAD

**Issue by saschanaz** [microsoft/TypeScript#7056]
``` typescript
let stream: MSStream;
const inputStream = stream.msDetachStream(); // any in lib.d.ts

// const inputStream = stream.msDetachStream() as Windows.Storage.Streams.IInputStream; from winrt.d.ts
```

Can we have a potential-any type information that resolves only when we have correct d.ts file? Some small type definitions in DefinitelyTyped refers much bigger ones e.g. node.d.ts that is not always required. (Imagine a library that supports standard types and Node.js types together.) I hope I can just include a small file without node.d.ts or any other unneeded large files.

Maybe somewhat related to old #1402.

**Comment by RyanCavanaugh** [comment]
If people are using just a very small portion of another library, would they be better served by using structural typing to stub out the useful portion of the consumed type? Just thinking out loud.

**Comment by SaschaNaz** [comment]
@RyanCavanaugh I'm not sure I understand. Can you give me an example?

**Comment by RyanCavanaugh** [comment]
Like instead of

```ts
function fn(): SomeOtherLibrary.Point;
```
you could write
```ts
function fn(): { x: number; y: number; }
```

Assuming that the type is small enough to do this reasonably, of course.

**Comment by SaschaNaz** [comment]
That will be great, but the type of IInputStream in my example has a reference to Buffer, Buffer has one to MemoryBuffer, MemoryBuffer has one to IMemoryBufferReference, etc... Maybe one will not need all of them but maybe others will.

**Comment by RyanCavanaugh** [comment]
Tracking at #31894 now
