### ISSUE TITLE
Control flow analysis could affect the scope of a type guard

### ISSUE THREAD

**Issue by chuckjaz** [Microsoft/TypeScript#7064]
Consider,

```ts
function isString(obj: any): obj is string {
	return typeof typeof obj === "string"; 
}

function foo(value: (string|number)): number {
	if (isString(value)) {
		return value.indexOf('foo')
	} else
		return value;
}

function bar(value: (string|number)): number {
	if (isString(value)) {
		return value.indexOf('foo')
	}
	return value;
}
```

Expected: Both `foo` and `bar` type-check correctly.
Received: `bar` reports that `value` is not assignable to `number`.

Flow analysis could be used here to determine `value` can only be `number` in all the code paths that arrive at the final `return`.

**Comment by mhegazy** [comment]
looks like a duplicate of  #2388

**Comment by chuckjaz** [comment]
Search fail. Sorry about that.
