### ISSUE TITLE
System module format emits incorrect ES6 object destructuring code

### ISSUE THREAD

**Issue by RReverser** [Microsoft/TypeScript#7074]
Hello,

I'm using typescript@next: 1.9.0-dev.20160213

When using `target: "es6"` and `module: "system"` configs together, variable object destructuring code like:

```typescript
export var { toString } = 1;
```

or

```typescript
import stuff from 'stuff';
var { toString } = 1;
```

is converted into an incorrect ES6 code:

```javascript
System.register([], function(exports_1, context_1) {
    "use strict";
    var __moduleName = context_1 && context_1.id;
    var toString;
    return {
        setters:[],
        execute: function() {
            { toString } = 1; // <-- needs to be wrapped into parentheses to avoid syntax error
        }
    }
});
```

**UPD:** For the case with exported destructured variable

```typescript
export var { toString } = 1;
```

incorrect code is also emitted in all the other module modes due to the same common problem (`var` being dropped, but assignment not wrapped into parentheses to prevent conflict with block syntax):

* `commonjs`:

```javascript
"use strict";
{ exports.toString } = 1;
```

* `amd`:
```javascript
define(["require", "exports"], function (require, exports) {
    "use strict";
    { exports.toString } = 1;
});
```

* `umd`:
```javascript
(function (factory) {
    if (typeof module === 'object' && typeof module.exports === 'object') {
        var v = factory(require, exports); if (v !== undefined) module.exports = v;
    }
    else if (typeof define === 'function' && define.amd) {
        define(["require", "exports"], factory);
    }
})(function (require, exports) {
    "use strict";
    { exports.toString } = 1;
});
```

**Comment by vladima** [comment]
another incorrect bit in emit for `amd` / `umd` / `commonjs`: name part in destructuring assignment should be either `Identifier` or `PropertyName` which means that dotted names are not permitted so `{ export.toString }` is illegal

**Comment by RReverser** [comment]
@vladima Oh right, didn't even notice.
