### ISSUE TITLE
module.exports assignment in a JavaScript file cannot be imported with ES6 syntax

### ISSUE THREAD

**Issue by billti** [Microsoft/TypeScript#7076]
See commented out failing test in [this pull request](https://github.com/Microsoft/TypeScript/pull/7075/files#diff-d65b772ede53bcf63c7c599a3f13b82bR15).

I've spent a while in the debugger on this, and the root cause appears to be how the `export=` SymbolObject is constructed in the source file's `symbol.exports` property in a JavaScript module source file versus a TypeScript module source file. This causes `resolveESModuleSymbol` to return `undefined`.

Being it applies only to this specific construct (i.e. assignments to `exports.` work with es6 imports, or importing with `var <id> = require(...)` syntax works), its not a total blocker. But would be good to fix ASAP, especially as the error is rather unattractive.

<img width="1025" alt="screen shot 2016-02-13 at 5 32 44 pm" src="https://cloud.githubusercontent.com/assets/993909/13031177/e170950a-d277-11e5-920c-20a5092059a8.png">

**Comment by Arnavion** [comment]
If you do do this, please consider stripping the `()` and `new()` members from the import binding to be compliant with ES6 (option 2 in #6809)

**Comment by billti** [comment]
Verified this is working in the current bits in 'master'.
