### ISSUE TITLE
"duplicate identifier" error in js files produced by tsc

### ISSUE THREAD

**Issue by d180cf** [microsoft/TypeScript#7077]
Let's say we have the following ts file:

``` ts
function abc() {
  // ...
}

module abc {
  export const def = 123;
}
```

tsc converts this into the following js file:

``` js
function abc() {
  // ...
}

var abc;
abc.def = 123; // well, there is actually a function (abc) { ... } wrapper here
```

Now if I try to include this js file into another ts file, tsc will scan the js file it's just generated and will report an error: "duplicate identifier abc". Once the "var abc" part is removed, the error goes away. Tried with the latest typescript@next (which was 1.9.0-dev.20160214).

The good news is that this is the only error I'm getting from a exceptionally sophisticated js file.

**Comment by RyanCavanaugh** [comment]
We could do the work to not emit the `var` when we know we've already emitted the function. Note that this isn't going to solve *every* case since you might have these declarations in separate files.

**Comment by d180cf** [comment]
I'm actually thinking that emitting the error isn't correct in this case: an empty "var" should be a noop if the var was already declared.

**Comment by mhegazy** [comment]
@d180cf as per the JS semantics, the additional var is a no-op. the typescript compiler imposes a bit stricter semantics here; the assumption here is that you did that be mistake and you did not mean to re-declare the variable, and that might point you to an actual bug, either related to scoping or incorrect use. 
I agree with @RyanCavanaugh that the compiler output should hold up to its own check.

**Comment by basarat** [comment]
If one uses outDir and exclude options wouldn't this be avoided altogether 🌹

**Comment by mhegazy** [comment]
PRs welcomed!

**Comment by RyanCavanaugh** [comment]
@mhegazy we should probably hold off on PRs for this until after the tree transforms work comes in? Don't want to solicit throwaway work

**Comment by mhegazy** [comment]
that is correct. here is the issue to look out for: https://github.com/Microsoft/TypeScript/issues/5595

**Comment by RyanCavanaugh** [comment]
This is fixed
