### ISSUE TITLE
[Proposition] Overloading interfaces with varying constraints

### ISSUE THREAD

**Issue by niieani** [Microsoft/TypeScript#7083]
It's currently possible to do this:
```ts
  method<A extends Array<number>>(one):number;
  method<A extends Array<string>>(two):string;
```

But not possible to do this:
```ts
interface Example<T extends Array<number>> {
  method(one):number;
}
interface Example<T extends Array<string>> {
  method(two):string;
}
```

This means we cannot have different typings depending on the generic type constraint of the interface.
I've even tried a hack like this:

```ts
interface Example<T extends Array<any>> {
  method<A extends T & Array<number>>(one):number;
  method<A extends T & Array<string>>(two):string;
}
```
I was hoping that TS will infer the type of the T array from the intersect, unfortunately that does not happen (it offers both methods, regardless of whether Example is an instance of `Example<Array<number>>` or of `Example<Array<string>>`).

Among other uses, this feature would be useful for a variety of database libraries that return internal types that can have their own operations done on them. For example, when I `map` an `DbArray<DbNumber>`, I should get a different set of methods than when operating on `DbArray<DbString>`.

The current workaround is to ask the user to explicitly declare both - the outer and the inner type, e.g.:

```ts
interface Example<TOuter, TInner> {
  map<TOut>((item: TInner) => TOut): TOut;
  // ...TOuter used in another method
}
```

However, this `TInner` is redundant (it's already inside of TOuter) and sometimes not relevant at all. 
With more complex types this can cause the introduction of even more generic types, that grow like cancer in the declarations (`interface Example<A, B, C, D, ...>`) - the more possibilities there are, the more explicit declarations need to be done at the interface level. This has been an obstacle to creating proper type definitions for RethinkDB https://github.com/DefinitelyTyped/DefinitelyTyped/issues/4551.

Last example: an interface `DbValue` can be a generic of any primitive type in the database: an `array`, a `string` or a `number`. 
For an instance of an `array`, you'd need to pass in `DbValue<Array<number>, number>`, yet for an instance of string, the second parameter is irrelevant: `DbValue<string, void>`.

What we'd need is to be able to constrain not only by method's own generics, but by the containing interfaces generics, for method signatures themselves, something like:

```ts
interface Example<T> {
  // here the constraint is not of the method, but of the type
  method(one):number where T extends Array<number>;
  method(two):string where T extends Array<string>;
}
```

**Comment by DanielRosenwasser** [comment]
Is this a duplicate of #1290?

**Comment by niieani** [comment]
@DanielRosenwasser Yes! I did a search before posting but nothing came up. Thanks. Brilliant that there's already an issue for that. I'll merge the conversation.
