### ISSUE TITLE
Suggestion: Typing module values

### ISSUE THREAD

**Issue by pdhborges** [Microsoft/TypeScript#7084]
I don't know if this was considered yet but since we can pass around modules as values why not offer the ability to specify module types in variables/function signatures?

```typescript
module Foo {	
	export function bar(a: number, b: number): number {
		return a + b;
	}
}

function foo2(moduleFoo: <ModuleType>) {
	...
}
```

Kind regards.

**Comment by ivogabe** [comment]
You can already use `typeof Foo`. Is that what you're looking for?

**Comment by pdhborges** [comment]
@ivogabe Ah! That's enough to cover my use cases.

Thanks!
