### ISSUE TITLE
New Website Logo: iPushPull

### ISSUE THREAD

**Issue by Tomino2112** [Microsoft/TypeScript#7086]
Please fill the following out:
- Name: iPushPull
- Homepage url: https://www.ipushpull.com
- Brand Guidelines/Licensing: Nothing special
- Logo: https://ipp-eu-prod-1-4.s3.amazonaws.com/static/folder_assets/1/ipushpull-logo-xxl-transparent.png

Hi, we are using TypeScript for new version of our API as well as with Angular front-end. Would love to be mentioned.

**Comment by mhegazy** [comment]
Logo uploaded, should be out in the next site refresh.

**Comment by Tomino2112** [comment]
@mhegazy Thank  you, and we will keep reporting issues and suggestions and try to improve TS more and more :)

**Comment by Tomino2112** [comment]
@mhegazy Hi there, not sure if this the best place, we have just had re-branding recently and would be great if logo could be updated to: https://ipushpull.s3.amazonaws.com/static/prd/ipp-logo.png
