### ISSUE TITLE
Occurrence typing for array element

### ISSUE THREAD

**Issue by elbarzil** [Microsoft/TypeScript#7095]
[Sorry about the title, "occurrence typing" is the Typed Racket term for this feature, and I haven't seen a name for it in the TypeScript docs.]

This doesn't work:

    function foo(...xs: (number | (()=>number))[]): number {
        if (typeof xs[0] === "number") return xs[0];
        else return xs[0]();
    }

but this does:

    function foo(...xs: (number | (()=>number))[]): number {
        var x = xs[0];
        if (typeof x === "number") return x;
        else return x();
    }

This might be intentional if it's because `xs[0]` might return different value for things that are kind of like arrays but aren't, though it still surprised me since a rest argument should always be a plain array, so `xs[0]` should always be the same...?

**Comment by RyanCavanaugh** [comment]
Combination of intentional and simply not implemented (see issues mentioning type guards for property access).

In general we can't make very many safe assumptions about the content of a reference type. For example, this is basically equivalent, but we have no idea what `somethingSpecialHappens` might be doing to the array.
```ts
function foo(...xs: (number | (()=>number))[]): number {
    if (typeof xs[0] === "number") {
      somethingSpecialHappens(xs);
      return xs[0];
    } else {
      return xs[0]();
    }
}
```

**Comment by elbarzil** [comment]
Yeah, obviously handing out `xs` to someone else between the type testing and the use could break it; it's just that IME that happens much less frequently than referencing lists, so I was hoping that TS would check for such things and will work if there aren't any...
