### ISSUE TITLE
Bad type error

### ISSUE THREAD

**Issue by elbarzil** [Microsoft/TypeScript#7099]
The following fails to typecheck, complaining that `type 'number' is not assignable to type '() => void'`.

    function nop(): void { return void 0; }
    function foo(xs: (number | (()=>void))[]): (() => void) {
        return xs.reduce(((acc, x) => nop), nop);
    }

But the code never actually looks at the contents, so it should work (and it does, if I change the argument type to something other than a function).

**Comment by RyanCavanaugh** [comment]
Duplicate of #7014
