### ISSUE TITLE
New Website Logo: Coveo

### ISSUE THREAD

**Issue by wfortin** [Microsoft/TypeScript#7100]
- Name: Coveo
- Homepage url: http://www.coveo.com/
- Brand Guidelines/Licensing: http://styleguide.coveo.com/d/GthysWU8RY0Q/brand-guidelines
- Logo: http://styleguide.coveo.com/api/attachment/download/47506

We :heart: typescript at Coveo!

**Comment by malaporte** [comment]
Can confirm, we started using Typescript the day it was out (we were actively looking for exactly this at the moment, the timing was *perfect*).

**Comment by mhegazy** [comment]
Logo uploaded, should be out in the next site refresh.
