### ISSUE TITLE
Visual Studio locates systemjs modules, but cannot locate them on compile

### ISSUE THREAD

**Issue by davismj** [Microsoft/TypeScript#7102]
I have a TypeScript project in Visual Studio, with modules installed via systemjs. I have the following code:

**app.ts**
```
import { Aurelia } from 'aurelia-framework';
```

For example, hovering Aurelia and pressing F12 (Go to Definition) opens up the correct `aurelia-framework.d.ts` file installed by systemjs. However, when I click Build, I get the following output:

```
error TS2307: Build: Cannot find module 'aurelia-router'.
```

Here is my tsconfig for reference.

**tsconfig.json**
```
{
  "version": "1.8.0",
  "compilerOptions": {
    "rootDir": "src/",
    "outDir": "dist/",
    "target": "es5",
    "module": "system",
    "declaration": false,
    "noImplicitAny": false,
    "removeComments": true,
    "noLib": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true
  }
}
```

**Comment by mhegazy** [comment]
what version of TS are you using? and how are you building? can you share your build log?

**Comment by davismj** [comment]
Version, as noted, is 1.8, installed via Visual Studio:

![image](https://cloud.githubusercontent.com/assets/3845823/13093412/24b01dc4-d4d3-11e5-8efe-1ea65f5680a4.png)

I am building via Visual Studio, like standard.

![image](https://cloud.githubusercontent.com/assets/3845823/13093448/64eda9d8-d4d3-11e5-83bb-05058b3368bb.png)

**Comment by mhegazy** [comment]
sorry about that, I meant do you have a custom build setup, and i am guessing no.

can you share your build log?  `msbuild /v:diagnostic`.

A sample repro project would be great too.

also can you confirm that running `tsc --p <path to tsconfig.json>` results in the same issue?

**Comment by davismj** [comment]
Same thing as above from the command line. 

C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.8>tsc.exe --project "\path\to\project\tsconfig.json"

> /path/to/project/src/app.ts(1,45): error TS2307: Cannot find module 'aurelia-router'.
> /path/to/project/src/main.ts(1,25): error TS2307: Cannot find module 'aurelia-framework'.
> 
> Files:               3
> Lines:           17330
> Nodes:           77451
> Identifiers:     29833
> Symbols:         66360
> Types:            4347
> I/O read:        0.00s
> I/O write:       0.00s
> Parse time:      0.15s
> Bind time:       0.07s
> Check time:      0.32s
> Emit time:       0.02s
> Total time:      0.57s

Try this repo to reproduce: [https://github.com/Foursails/visual-aurelia](https://github.com/Foursails/visual-aurelia)

**Comment by vladima** [comment]
I've reproduced the issue - this is a known one and it should already be fixed in our internal bits (tsc.exe does not pick up `.d.ts` files when enumerating directory content)

**Comment by mhegazy** [comment]
the nightly NuGet package should have the fix. see https://github.com/Microsoft/TypeScript/wiki/Nightly-drops#using-nuget-with-msbuild for more details on using the nighly NuGet drop.

**Comment by davismj** [comment]
Is there any workaround?

**Comment by mhegazy** [comment]
1. list "files" property in your tsconfig
2. use NuGet, 
3. use node to build
4. downgrade to 1.7.6
5. wait for TS 1.8.2 (should be out soon)

**Comment by davismj** [comment]
This didn't work.

**Comment by mhegazy** [comment]
can you share a repro, the one you shared earlier did not reproduce the issue for me.

**Comment by davismj** [comment]
I was able to fix this by reformatting my computer.

**Comment by MarcosMeli** [comment]
I got same error with 1.8.4 and 2.0

The workaround was to to remove spaces from the project directory "Online Devoo Tools" => "OnlineDevooTools" make the build success
