### ISSUE TITLE
Visual Studio switches over to intellisense window during rebuild

### ISSUE THREAD

**Issue by NoelAbrahams** [Microsoft/TypeScript#7110]
Hi,

**Version**: VS 2015/TS 1.8

We have a project system in a VS solution whereby the projects reference the output of other projects via `<reference>` tags.

In the VS settings I have the option `Show Output window when build starts` checked and I have the option `Always show Error List if build finishes with errors` unchecked.

As of 1.8 when I carry out a rebuild of the solution, VS switches to the output window as expected, but halfway through it switches over to the `IntelliSense` window and prints a bunch of lines similar to the following:

```
[Failure] Could not find file 'C:\foo\bar\abc.d.ts'.
[Failure] Could not find file 'C:\foo\bar\abc.d.ts'.
[Failure] Could not find a part of the path 'C:\foo\baz\xyz.d.ts'.
[Failure] Could not find file 'C:\foo\bazz\aaaaa.d.ts'.
[Failure] Could not find a part of the path 'C:\foo\baz\capture\bbbbbbbbbb.d.ts'.
[Failure] Could not find a part of the path 'C:\foo\bz\ccccccccc.d.ts'.
```

I'm assuming these errors are occurring because as the full solution rebuild progresses, certain directories are cleaned out, causing the projects that reference files in those directories to print these errors.

There is no problem with the temporary errors, but prior to 1.8 there was no switching over to the intellisense window. I am not really interested in the intellisense errors: I want to observe the build output window.

Thanks.

**Edit**: I should say 'IntelliSense' view on the Output tab: there is no separate tab as such.

**Comment by billti** [comment]
@paulvanbrenk Any ideas what's going on here?

**Comment by mhegazy** [comment]
Roslyn controls that, we should port this to the roslyn forum

**Comment by paulvanbrenk** [comment]
@CyrusNajmabadi Do you have any insights here?

**Comment by CyrusNajmabadi** [comment]
Yup.  roslyn is trying to read the files when this happens, and clearly the files are no longer available or are locked.  We're printing something into the output window so people know this so they're not confused as to why things like intellisense aren't showing full information about their project.
