### ISSUE TITLE
Can't run tsc.exe for TypeScript 1.8 Beta. " Faulting module name: ChakraCore.dll"

### ISSUE THREAD

**Issue by mpawelski** [Microsoft/TypeScript#7111]
I just installed Visual Studio 2015 ultimate and TypeScript 1.8 Beta and I can't compile any project with .ts file. I figured out that when I run "C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.8\tsc.exe" it immediately crash with this message box info:

> [Window Title]
> TypeScript Compiler
> 
> [Main Instruction]
> TypeScript Compiler has stopped working
> 
> [Content]
> A problem caused the program to stop working correctly. Please close the program.
> 
> [Close the program] [Debug the program]

in event log I have this info

> Faulting application name: tsc.exe, version: 1.8.1.0, time stamp: 0x56a6fd71
> Faulting module name: ChakraCore.dll, version: 1.1.0.1, time stamp: 0x56993736
> Exception code: 0xc0000005
> Fault offset: 0x0016a449
> Faulting process id: 0x2bfc
> Faulting application start time: 0x01d169756e95a5df
> Faulting application path: C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.8\tsc.exe
> Faulting module path: C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.8\ChakraCore.dll
> Report Id: ac4ca0cf-d568-11e5-bcb9-34e6d715db95

As I said I did it on "clean" computer with Windows 7. Justs installed VS2015 and TypeScript 1.8 Beta.
Does anyone how to fix it?

**Comment by vladima** [comment]
// cc @paulvanbrenk

**Comment by paulvanbrenk** [comment]
Workaround is to install IE 11. This will be fixed in the 1.8 Final

**Comment by mpawelski** [comment]
thanks for quick answer with workaround, it works :)
