### ISSUE TITLE
React.d.ts `type` does not exist in ReactElement<any>

### ISSUE THREAD

**Issue by nippur72** [Microsoft/TypeScript#7113]
I cross post [this issue](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/8131) from DefinitelyTyped because I'm no longer sure it's something caused by the definitions.

So I have this React code 
```typescript
      return React.Children.map(this.props.children, child => {
         console.log(child.type);
         return child;
      });     
```
that won't compile, resulting in
```
Property 'type' does not exist on type 'ReactElement<any> | string | number'.
```

But I don't understand why that happens, if I backtrace with "go to definition", I find that `child` is defined as:

```typescript
    interface ReactElement<P extends Props<any>> {
        type: string | ComponentClass<P> | StatelessComponent<P>;
        props: P;
        key: string | number;
        ref: string | ((component: Component<P, any> | Element) => any);
    }
```
What I am missing, or is it a bug?

**Comment by RyanCavanaugh** [comment]
You can't access `type` because it might be also be a `string` or `number`, and those types don't have a `type` property.

**Comment by nippur72** [comment]
that's true, thanks! Children can be text elements too, so you need to make sure first they are `React.ReactElement<any>` and then access `type`.
