### ISSUE TITLE
"Casting to method" issue

### ISSUE THREAD

**Issue by Xample** [Microsoft/TypeScript#7114]
Hi, I faced a problem unable to cast an object as a method. While this is handled automatically using an if / else block (and congratulation to the guys who implemented this), this is not working yet into a switch case nor manually. Here is [my code](http://www.typescriptlang.org/Playground#src=%0Ainterface%20MethodInterface%7B%0A%20%20()%3A%20string%3B%0A%7D%0A%0Ainterface%20FocusRule%0A%7B%0A%09surprise%3F%3AMethodInterface%7Cstring%0A%7D%0A%0Afunction%20test(anObject%3AFocusRule)%0A%7B%0A%09var%20actionOrString%3AMethodInterface%7Cstring%20%3D%20anObject.surprise%3B%0A%09%0A%09%20%20%20%20%20%20%20%20%20%20switch(typeof%20actionOrString)%0A%20%20%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2F**%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20*%20There%20is%20no%20way%20to%20prevent%20the%20compilation%20error%20here%20(even%20casting%20the%20actionOrString)%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20*%2F%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20case%20%22function%22%20%3A%20%3CMethodInterface%3EactionOrString()%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2F**%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20*%20If%20a%20string%2C%20maybe%20we%20are%20using%20a%20helper%20or%20a%20query%20selector%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20*%2F%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20case%20%22string%22%20%20%20%3A%20return%3B%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%09%0A%09%0A%09%2F%2F%20Using%20a%20if%20%2F%20else%20is%20however%20ok%0A%09%0A%09if%20(typeof%20actionOrString%20%3D%3D%3D%20%22function%22)%0A%09%7B%0A%09%09actionOrString()%3B%0A%09%7D%0A%09else%0A%09%7B%0A%09%09%2F%2F%20Here%20this%20is%20normal%20to%20fail%E2%80%A6%0A%09%09actionOrString()%3B%0A%09%7D%0A%7D%0A%0A%0A) to reproduce the error:

**Comment by RyanCavanaugh** [comment]
You can use parentheses to make the type assertion work (what you had was changing the type of the result, not the thing being invoked):
```ts
case "function" : (<MethodInterface>actionOrString)();
```
Otherwise this is a duplicate of #2214

**Comment by Xample** [comment]
Thank you @RyanCavanaugh !
