### ISSUE TITLE
tsconfig.json: es5 ignore exclude dir and not es6

### ISSUE THREAD

**Issue by bourdeau** [Microsoft/TypeScript#7116]
Hi all,

I'm discovering the whole JS world atm (node, angular 2, typescript, etc.) so I hope what I'm reporting might not be a bug but my lack of knowledge.

In a Angular 2 project ([jdhm-bo](https://github.com/bourdeau/jdhm-bo)) I got the following tsconfig.json:

```
{
  "compilerOptions": {
    "target": "es5",
    "module": "system",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": false
  },
  "exclude": [
    "node_modules"
  ]
}
```
When I run tsc it look into my app folder and generate the appropriate *.js but it also look into the node_modules folder and generate some errors like:

```
node_modules/angular2/src/core/change_detection/parser/locals.d.ts(3,14): error TS2304: Cannot find name 'Map'.
```
According to the configuration it shouldn't compile anything in the node_modules folder as I excluded it.

If I change `"target": "es5",` to `    "target": "es6",` then it works just fine...

Am I doing something wrong or is it a bug?

Thanks in advance for your help.

**Comment by billti** [comment]
If you target ES5, then you'll need to include the types for the ES6 shims that Angular uses. See the info under the **TypeScript Typings** header at https://angular.io/docs/ts/latest/quickstart.html .

Note that excluding 'node_modules' only stops the compiler from automatically crawling for files to include by default from this location. It will still try to resolve included modules (such as `angular2/core`) from under here per Node's lookup resolution logic.
