### ISSUE TITLE
Optional index signature

### ISSUE THREAD

**Issue by Pajn** [Microsoft/TypeScript#7118]
It should be possible to make the index signature optional like this:
`export type Actions  = {[type: string]?: Action}`

If the index signature is not optional (as I'm required to type right now) I get errors when passing parameters with the Actions type as the index signature is missing in the passed object.

**Comment by mhegazy** [comment]
An index signature is a "constraint" on a type; i do not understand what an optional constraint means.. 

Can you elaborate on your case, and what you are trying to achieve here.

In your example, all properties should be `Action`; and if not, what should they be? why not define the index signature in a more permissive fashion, i.e `[type:string]: any` or `[type:string]:Action|Person|Entity`?

**Comment by Pajn** [comment]
I currently get the error "Index signature is missing in type", what I want to constrain is that all values are `Action`, not that the passed object allows setting additional keys

**Comment by RyanCavanaugh** [comment]
If your use case isn't solved by #7029, please post some code so we can understand the scenario. Thanks!

**Comment by Pajn** [comment]
Oh, sorry. Didn't look for already fixed issues, just open :/
