### ISSUE TITLE
Expecting `index.js` to be resolved when `require` a directory

### ISSUE THREAD

**Issue by vilic** [Microsoft/TypeScript#7129]
**TypeScript Version:** 
nightly (1.9.0-dev.20160217)

**Comment by billti** [comment]
This is the same issue as https://github.com/Microsoft/TypeScript/issues/6670 , so I'll close this one as a duplicate.

Note: I have a pull request out for this currently. (https://github.com/Microsoft/TypeScript/pull/7075).

**Comment by vilic** [comment]
@billti Great to know, thanks!
