### ISSUE TITLE
Why does this not typecheck/compile?

### ISSUE THREAD

**Issue by Ziriax** [Microsoft/TypeScript#7131]
I was trying to write some code where URLs for fetching JSON are 'strongly typed', in the sense that the URL is associated with the type of data.

But I encountered a strange compilation error while doing so. Stripped down example follows:

```
interface IUrl<T> {
}

class Url<T> implements IUrl<T> {
	
}

function test<T>(url: IUrl<T>): T {
	return undefined; // Stub, should be replaced by real code
}

// res1 does *not* compile, type of test(url1) is {}, not number, why?
const url1 = new Url<number>();
const res1 = test(url1) + 1;

// res2 does compile, type of test(url2) is number, why do I have to downcast to IUrl<number>?
const url2: IUrl<number> = new Url<number>();
const res2 = test(url2) + 1;
```

Is this the correct behavior? It seems strange that I have to cast the class to the interface explicitly

**Comment by ivogabe** [comment]
`IUrl` does't have any properties and doesn't use `T` anywhere. Thus `IUrl<number>` is structurally equal to `IUrl<{}>`. Because of that, the return type of `test` will be `{}`. When you add some propety to `IUrl` that uses the type argument, you will get your expected behavior.

**Comment by RyanCavanaugh** [comment]
Need to add this to the FAQ

**Comment by RyanCavanaugh** [comment]
https://github.com/Microsoft/TypeScript/wiki/FAQ#why-doesnt-type-inference-work-on-this-interface-interface-foot---
