### ISSUE TITLE
Salsa: symbols not found (ES5)

### ISSUE THREAD

**Issue by egamma** [Microsoft/TypeScript#7134]
_From @warpdesign on February 17, 2016 11:21_

I have activated salsa and when activated, some symbols cannot be found anymore in ES5 files.

For example, if I have a a file with only:

    function toto() {
    }

Typing `@toto`will work and highlight the toto function.

But if I wrap the code into a closure, it doesn't work anymore:

![salsa](https://cloud.githubusercontent.com/assets/199648/13107988/b5b09720-d570-11e5-8e1a-9a00e8c5984b.jpg)

Without salsa, it works as expected, highlighting the toto function even if it is wrapped into a closure.

Code 0.10.8
Windows 10

_Copied from original issue: Microsoft/vscode#3079_

**Comment by egamma** [comment]
Moving to TypeScript

**Comment by billti** [comment]
This is interesting, as the nested function lives within an expression, not nested function declarations. Need to discuss how we would display these (if desired). for example, currently we show the parent declaration to disambiguate, but in this case, it lives within an anonymous function expression.

**Comment by warpdesign** [comment]
What is the status of this particular problem ?

The fact that Code doesn't detect symbol in this case means it cannot be used with any code wrapped into closure.

A lot of ES5 source code has been written like this.

**Comment by kuechlerm** [comment]
As the update is due today, is it possible to not use Salsa?

I really like to use folding but this issue is a huge step back! My current project uses IIFEs everywhere ...

**Comment by egamma** [comment]
>As the update is due today, is it possible to not use Salsa?

@kuechlerm  this update supports only Salsa and this is not possible, sorry.

**Comment by egamma** [comment]
Related to #6644

**Comment by billti** [comment]
Pull request #7504 is out to address this.

**Comment by warpdesign** [comment]
:+1:

**Comment by warpdesign** [comment]
@mhegazy is it fixed un the just released march preview update ? I tried it and still had the problem.

**Comment by mhegazy** [comment]
the fix went in yesterday. so not sure if it is in the preview. @egamma when would this change be in a public release?

**Comment by egamma** [comment]
We have integrated TS 1.8.9 with the fix today. We plan to push an update on the insiders channel next Monday.

**Comment by con-ssc** [comment]
I used the output of a ts class to build an IIFE structure and this is not working in the Insider version with ts 1.8.10 there are still no symbols found.

**Comment by con-ssc** [comment]
Quick example
`var person;
(function (person) {
    var grades = (function () {
        function grades() { }
        function _processGrades(){}
        grades.getGrades = function(id){};
        return grades;
    })();
    return person.grades = grades;
} (person || (person = {})));`
