### ISSUE TITLE
Intelisense for "import" statements

### ISSUE THREAD

**Issue by egamma** [Microsoft/TypeScript#7135]
_From @tomitrescak on February 17, 2016 9:57_

Hello, is it possible to add intellisense for import statements? Either disaply all files in the project that match the pattern relative to the current file, or display whatever is in the path.

E.g. 

"../" + ctr+space  will pop whatever is in the parent directory 
"my" + ctrl + space will pop up all files that contain "my" showing path relative to the currrent file     

_Copied from original issue: Microsoft/vscode#3076_

**Comment by egamma** [comment]
Moving to typescript

**Comment by billti** [comment]
This is a long-standing request, and is covered in #188.
