### ISSUE TITLE
Construct generic type using new

### ISSUE THREAD

**Issue by masbicudo** [Microsoft/TypeScript#7137]
I know that generic types are only hints to the compiler at present, but what if they can be compiled to real code. This could make it possible to use new operator with generic types.

For example, the following code:

```
function fn<expand T extends {new()}>() { return new T(); }
var a = fn<MyClass1>();
var b = fn<MyClass2>();
```

could be compiled to this:

```
function fn(T) {
  return function() { return new T(); }
}
var a = fn(MyClass1)();
var b = fn(MyClass2)();
```

or something more in the line of templates:

```
function fn_MyClass1() { return new T(); }
function fn_MyClass2() { return new T(); }
var a = fn_MyClass1();
var b = fn_MyClass2();
```

I have a slightly more complex scenario that I wanted to implement, that motivated this proposal:

```
export function form<T>(model: I<T>): FormMeta<T> {
    return new FormMeta<T>(model, new T());
}
```

I have a `model` object that extends `I<MyClass>`. `MyClass` is the metadata class of that specific model object. What I wanted is to make a call to `form` return a `FormMeta` class containing both the `model` object and it's metadata.

If that was possible I could make this code work:

```
interface IMyModel extends I<MyModelMeta> {
    name: string;
}
var model: IMyModel = { name: "Miguel" };
var a = form(model);
```

For instance, the `FormMeta` object will help in the construction of HTML form elements, given a model object.

**Comment by RyanCavanaugh** [comment]
Not doing type-based-emit is a primary design goal (https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals)

There are already good ways of accomplishing 95% of what's being requested here, with the advantage that they're shorter!
```ts
function fn<T>(x: { new(): T }) { return new x(); }
var a = fn(MyClass1);
```
