### ISSUE TITLE
Repeat of #3649 Conflict with Object.prototype.watch in FireFox/Gecko

### ISSUE THREAD

**Issue by mihailik** [Microsoft/TypeScript#7141]
See #3649 Conflict with Object.prototype.watch in FireFox/Gecko
Corresponding PR for that was #3648
Resolved in June 2015, but more appeared

**Comment by saneyuki** [comment]
It will be removed in the future https://www.fxsitecompat.com/en-CA/docs/2015/object-prototype-watch-will-be-removed/

**Comment by mihailik** [comment]
Why is it closed? Was it really fixed?

**Comment by mihailik** [comment]
Sorry, didn't notice your other comment. Thanks a lot @mhegazy :+1:
