### ISSUE TITLE
New Website Logo: Velocity

### ISSUE THREAD

**Issue by Quasso** [Microsoft/TypeScript#7155]
Name: Velocity
Homepage url: https://velocityapp.com
Brand guidelines/licensing: just a generous bit of padding around the logo
Logo: https://uat.velocityapp.com/wp-content/themes/velocity-seventh-release/library/images/velocity-logo-latest.svg

**Comment by mhegazy** [comment]
Logo uploaded, should be out in the next site refresh.

**Comment by Quasso** [comment]
Wonderful, thanks @mhegazy
