### ISSUE TITLE
Report relevant semantic errors for JS files

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript#7162]
Today semantic errors are ignored for JS files. That include errors for labels, some strict mode checks, invalid call expressions, unknown modules, etc.. We will need to go through all the semantic errors and expose ones that are applicable to JS. we can also consider changing the diagnostic message level to be warning instead of an error.

**Comment by billti** [comment]
Isn't this covered by #6802?

**Comment by mhegazy** [comment]
my bad. closing.
