### ISSUE TITLE
Intellisense not working

### ISSUE THREAD

**Issue by egamma** [Microsoft/TypeScript#7166]
_From @hellopao on February 15, 2016 3:15_

I've upgraded the `vs code` to the latest version ,and the `Salsa` was enabled. 
Now, the code intellisense does not work without an `jsconfig.json` file. but version `0.10.6` worked well.

![withoutjsconfig](https://cloud.githubusercontent.com/assets/5064875/13038969/c759c192-d3d4-11e5-886b-416eca15dfb6.png)
![withjsconfig](https://cloud.githubusercontent.com/assets/5064875/13038976/e14ab20a-d3d4-11e5-837b-319fbe02638b.png)

_Copied from original issue: Microsoft/vscode#3017_

**Comment by egamma** [comment]
_From @meritozh on February 15, 2016 3:41_

Same issues. I hope `Salsa` can works without a `jsconfig.json`. How about contain a default `jsconfig.json` without manual creating one?

**Comment by egamma** [comment]
_From @nilshartmann on February 18, 2016 13:15_

In my case Intellisense (even with a `jsconfig.json`) only works for modules that have been `require`d but not for modules that have been imported using ES6 `import`:

![intellisense-es6](https://cloud.githubusercontent.com/assets/435073/13144149/1e3db11e-d649-11e5-923e-377606ce7017.gif)

You can find my sample project here: https://github.com/nilshartmann/vsctest
My environment:
- Visual Studio Code Version 0.10.8 with Salsa preview enabled
- No extensions
- MacOS
- TypeScript installed locally (1.9.0-dev.20160218)
- jsconfig.json (tried several more variants all without success):
```
{    
    "compilerOptions": {
        "target": "ES6"
    },
    "exclude": [
        "node_modules"
    ]
}
```

Just noticed: Importing a module from my own project that uses ES6 `export` seems to work.

I'm not sure if this is the same problem or to better open a new Issue?

**Comment by billti** [comment]
If you open a loose file, then we have no project context, so we're not pulling in the node.d.ts. That would explain the `require("fs'");` not working in the loose file scenario above.

For the ES6 import case, this may be similar/related to #7076. I'll take a look at these together.

**Comment by billti** [comment]
Verified the behavior is as expected in 'master' currently. Note that above for the statement `import http from "http"`, this is a default import, you'll need to set `"allowSyntheticDefaultImports": true` for this to work, else instead use `import * as http from "http"` to import the CommonJS module as a namespace.

**Comment by Hosar** [comment]
Still not working.  I have the following. And even if I set `"allowSyntheticDefaultImports": true` still doesn't show any Intellisense.

Version 1.9.1
Commit f9d0c687ff2ea7aabd85fb9a43129117c0ecf519
Date 2017-02-08T23:44:55.542Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0

**Comment by mhegazy** [comment]
@Hosar this is an old issue. please file a new issue and provide enough information for us to be able to reproduce it.

**Comment by grandsilence** [comment]
So, whan that shit will be fixed? I've got same annoying issue. Hate this. ver 1.10.2
