### ISSUE TITLE
Require url intellisense gone?

### ISSUE THREAD

**Issue by egamma** [Microsoft/TypeScript#7167]
_From @mathiasdose on February 11, 2016 8:20_

One of the features that I really liked with vscode was the folder path intellisense inside require('path') while doing NodeJs development. Now I just see a list of global variables. I don't use the new salsa, and I'm targeting ES5. 

Something that might be worth mentioning is that the intellisense of the required modules is working as before.

_Copied from original issue: Microsoft/vscode#2923_

**Comment by egamma** [comment]
_From @codyrigney92 on February 17, 2016 20:16_

I'm having the same issue. But mine doesn't work in Salsa or pre-Salsa.

**Comment by egamma** [comment]
We are migrating to Salsa and Salsa doesn't provide this support. Moving to TypeScript/Salsa for consideration.

**Comment by billti** [comment]
One of our most long-standing bugs/requests has been for path completion in references and imports ( #188 ), this is another variation on that (as we just added `require` module support). I'll close this as a duplicate and add this extra scenario to that bug.
