### ISSUE TITLE
404 NotFound when using TypeScript Pallax Sample

### ISSUE THREAD

**Issue by veleek** [Microsoft/TypeScript#7171]
Attempting to load the Parallax Starfield typescrypt sample fails in Chrome.

Sample: http://www.typescriptlang.org/Sample/jquery/parallax.html gives a 404 when loading /Sample/jquery/starfield2.png.

On Chrome this appears to break the sample, but the same 404 appears on other browsers, so maybe it's a read herring.

**Comment by DanielRosenwasser** [comment]
This issue was moved to Microsoft/TypeScriptSamples#74
