### ISSUE TITLE
VS release build does not generated content for `_references.js`

### ISSUE THREAD

**Issue by NoelAbrahams** [Microsoft/TypeScript#7175]
Hi,

**Version:**  1.8.0-beta / VS 2015
**Attachments:** [test.zip](https://github.com/Microsoft/TypeScript/files/139582/test.zip)

To reproduce,

* Open up `test.sln` in the attached folder.
* Ensure the development mode is "Debug"
* Rebuild the solution.
* Open up `TypeScriptHTMLApp1\bin\_references.js` and observe that is populated.
* Change the development mode to "Release".
* Rebuild the solution.
* Open up `TypeScriptHTMLApp1\bin\_references.js` and observe that it is now empty.

We have systems in place that depend on `_references.js` in release mode for bundling and deployment. There should be no difference in the treatment of this file in the development and release modes.

**Comment by billti** [comment]
I just opened the project and looked at the diagnostics log for both Debug and Release. The difference is that in 'Release' builds the default is to pass `--removeComments`, and `/// <reference...` directives (which is what `_references.ts` consists of) are comments.

If you want to keep this, then in the Project Properties, go the TypeScript page and select the `Release` configuration, and select the check box to `Keep comments in JavaScript output`.

Being that /// directives are specific to TypeScript, in the final JavaScript output they are just comments, so generally folks do want them removed along with all other comments in their final **release** builds.

**Comment by NoelAbrahams** [comment]
I see. It could be argued that triple slashes are not the same as comments. We wanted to remove comments in the release build in order to help the minifier along.
