### ISSUE TITLE
error TS2495: Type 'FileList' is not an array type or a string type

### ISSUE THREAD

**Issue by Maks3w** [Microsoft/TypeScript#7181]
**TypeScript Version:** 

1.8.0-beta

**Code**

```ts
setFilesFromFileList(fileList: FileList) {
    for (let file of fileList) { }
}
```

**Expected behavior:**
No errors

**Actual behavior:** 
> error TS2495: Type 'FileList' is not an array type or a string type

**Comment by yortus** [comment]
Are you targeting ES5? If so it's probably the problem described in #4031

**Comment by SaschaNaz** [comment]
It seems [`FileList`](https://w3c.github.io/FileAPI/#dfn-filelist) does not support iterator yet, so it won't work even on ES6 mode [as of now](https://github.com/Microsoft/TypeScript/blob/4b284abd5199b22e21d4770325759235ec523447/lib/lib.es6.d.ts#L8477).

```webidl
[Exposed=Window,Worker] interface FileList {
  getter File? item(unsigned long index);
  readonly attribute unsigned long length;
};
```
