### ISSUE TITLE
Microsoft.TypeScript.MSBuild doesn't work on VS2013

### ISSUE THREAD

**Issue by mnivet** [Microsoft/TypeScript#7183]
**TypeScript Version:** 

1.7.5 / 1.8.0-beta

**Expected behavior:**
The package Microsoft.TypeScript.MSBuild must follow Nuget package conventions to be fully compatible with Nuget 2.x and 3.x
In particular props and targets files must be place in the build folder

see https://docs.nuget.org/Create/Creating-and-Publishing-a-Package#import-msbuild-targets-and-props-files-into-project

**Actual behavior:** 
Those files are added into projects using Powershell code
The package as nor content, nor lib, nor build folder and is recognized as a solution package under VS2013 which makes it impossible to be installed on a project.

**Comment by paulvanbrenk** [comment]
This only works when the targets and props file have the same name as the package. They don't, so we have to use the powershell scripts to install the targets/props files. Further the scripts remove any old targets/props from the project, which makes moving to NuGet from targets props installed on the machine much cleaner.
