### ISSUE TITLE
Transpiled ES5 has _invalid left-hand side of assignment expression

### ISSUE THREAD

**Issue by specimen151** [Microsoft/TypeScript#7189]
**TypeScript Version:** 

1.7.3

**Code**

```ts
import { bindable, customElement } from 'aurelia-framework';

@customElement('my-element')
export class MyElement {
  @bindable heading = "Default heading";
}
```

Let me first say that I have discussed this with the creator of Aurelia, who is a very competent programmer, and he has looked at it and suggested I post it here, as there is something strange with the compilation (perhaps).

What I observe is that the generated ES5 JavaScript has an error, at least that's what VSCode tells me:

```javascript
var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
    var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
    else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
    return c > 3 && r && Object.defineProperty(target, key, r), r;
};
var __metadata = (this && this.__metadata) || function (k, v) {
    if (typeof Reflect === "object" && typeof Reflect.metadata === "function") return Reflect.metadata(k, v);
};
define(["require", "exports", 'aurelia-framework'], function (require, exports, aurelia_framework_1) {
    var MyElement = (function () {
        function MyElement() {
            this.heading = "Default heading";
        }
        __decorate([
            aurelia_framework_1.bindable, 
            __metadata('design:type', Object)
        ], MyElement.prototype, "heading", void 0);
        MyElement = __decorate([
            aurelia_framework_1.customElement('my-element'), 
            __metadata('design:paramtypes', [])
        ], MyElement);
        return MyElement;
    })();
    exports.MyElement = MyElement;
});
```

The error is on the line: `MyElement = __decorate([` 7 lines from the end there.
and reads: _invalid left-hand side of assignment expression.`

**Comment by mhegazy** [comment]
The code is correct. it should run correctly, and will do what you expect.

VSCode is showing you an error here, because it is considered as bad practice to override a function declaration because of [TDZ](http://jsrocks.org/2015/01/temporal-dead-zone-tdz-demystified/) issues.

I agree that the TS emitted code should be held to the same standard, that we flag our users for doing.

having said that, the decorator proposal is undergoing a large change in the near future, and any change here will be undone by that.
