### ISSUE TITLE
lib.dom.d.ts - HTMLTextAreaElement, HTMLInputElement do not have "minLength" property

### ISSUE THREAD

**Issue by michaelbromley** [Microsoft/TypeScript#7197]
**TypeScript 1.7.5, but also in master:** 

**Code**

```ts
let nativeTextarea: HTMLTextAreaElement;
nativeTextarea.minLength;

let nativeInput: HTMLInputElement;
nativeInput.minLength;
```

**Expected behavior:**
No compiler error.

**Actual behavior:** 
Compiler error: `Property 'minLength' does not exist on type 'HTMLTextAreaElement'`, `Property 'minLength' does not exist on type 'HTMLInputElement'`

HTML5 spec: https://www.w3.org/TR/html5/forms.html#the-maxlength-and-minlength-attributes

**Comment by mhegazy** [comment]
PRs are welcomed. here is some details on contributing lib.d.ts fixes:https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes

**Comment by YuichiNukiyama** [comment]
HTMLTextAreaElement should impliment `selectionDirection `, too.
spec:[4.10.11 The textarea element
Categories](https://www.w3.org/TR/html5/forms.html#the-textarea-element)
