### ISSUE TITLE
Updating VS2015 Typescript tools to 1.8 causes unexpected build failure

### ISSUE THREAD

**Issue by stanhuff** [Microsoft/TypeScript#7200]
After installing the 1.8.4.0 VS 2015 Typescript tools I'm getting an unexpected build error:

Build: File 'COMPUTE_PATHS_ONLY.ts' not found.  

After perusing other issues with this error I dug into 

C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\Typescript

And also found

C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v15.0\Typescript

I don't know if it's related but for giggles I replaced the Microsoft.TypeScript.targets in v14.0 with the same file I found in v15.0 and the issue went away.  Is this v15 stuff mis-installed?  I don't have a VS v15.

**Comment by mhegazy** [comment]
`C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v15.0\Typescript` is an exact copy of `C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\Typescript`. from the discription you provide, looks like `C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\Typescript\Microsoft.TypeScript.targets` did not install correctly. what version did you have installed before upgrading to 1.8.4? do you have VS2013 installed on the same machine? what version of VS do you have installed? does a repair on the 1.8.4 installer solve the issue (Add/Remove Program, search for TypeScript , repair)?

**Comment by stanhuff** [comment]
The most recent version I had was the 1.7.6 version but I had tried the 1.8.1 beta with odd issues  that both repair and re-install didn't fix, so I uninstalled 1.8.1 and re-installed 1.7.6.  Maybe this left things in a semi-corrupt state.  I do have 2013 Professional installed on the same machine although I haven't been using it.  Other than that only 2015 Enterprise is present.  Regrettably I had not tried to do a repair of the 1.8 install prior to logging the issue.

The targets file was not the only difference but it was the only relevant difference I think.  The other difference was that my 14.0 had an 'en' folder in it. The targets file was dated 11/17/2015 6:11pm.

I reverted my 14.0 to the post-1.8 installed state using a stashed copy and tried doing a repair by re-running the installer and clicking repair.  It has forced me to reboot this time and the targets file seems to have been properly installed but it has left that 'en' folder around.  The build works now as expected without having to mess with anything so it's good enough for me.

Thanks!

**Comment by dpmartin990** [comment]
I had this exact same problem and I found if I did a repair install of Typescript 1.7 followed by a repair install of Typescript 1.8 it was fixed.  Thanks for posting this.  I suspect I earlier installed the Typescript versions IN THE WRONG ORDER which created my problem.

**Comment by Kriskit** [comment]
This has happened for us, copying 
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v15.0\Typescript to C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\Typescript
fixed the problem. Suggests to me there's a typo in the installer?

I noticed the same seemed to happen for the VS 2013 installer but it installed into the v14 folder!

**Comment by paulvanbrenk** [comment]
This is a duplicate of #7445

**Comment by mrcrowl** [comment]
I encountered this problem as well today.  

The solution that worked for me was to copy the _TypeScript_ folder from:
`C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v15.0`
into:
`C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0`

HT to @stanhuff

**Comment by mrugeshparekh** [comment]
This error comes after installing TypeScript version 2.0.3 for me. I fixed it as per the @mhegazy suggestion by copying exact TypeScript folder from v15.0 to v14.0.

**Comment by rajeshghaywat** [comment]
The part of the problem started for me after installing Visual studio 2017. I tried @mrcrowl solution and it worked for me.

**Comment by TrevorScrews** [comment]
Ditto to what @rajeshghaywat posted.  I also tried @mrcrowl solution, restarted visual studio, and my problem was solved.
