### ISSUE TITLE
Typescript warning about experimentalDecorators make the compile fail ???

### ISSUE THREAD

**Issue by bastienJS** [Microsoft/TypeScript#7201]
**TypeScript Version:** 

1.8.2

**Visual Studio Version:** 

2015 with asp.net core project

**Code**

```ts
 import {Component} from 'angular2/core';

@Component({
    selector: 'my-app',
    template: '<h1>My First Angular 2 App</h1>'
})
export class AppComponent { }
```

**Expected behavior:**

As my scripts folder has a tsconfig.json I expect that the set property:

    "experimentalDecorators": true,

Is used by the ts compiler. But it seems not?!!

**Actual behavior:** 

Because I get this error message:

![image](https://cloud.githubusercontent.com/assets/5945955/13266037/64ba0332-da76-11e5-8733-52311070fdac.png)

There are 2 things that make me think:

1) Why is a warning make the compile fail?
2) Why is the tsconfig.json not used by tsc?

**Comment by mhegazy** [comment]
can you share your build log, or the project?

**Comment by bastienJS** [comment]
Getting more into TS/Gulp etc... it seems it was a picnic ;-) 

As I use gulp-typescript, I had to tell this guy to use the tsconfig.json!

**Comment by PushpalathaNagam** [comment]
Hi bastienJS,

i'm also getting the same issue any solution for this and i'm not using the gulf file and all.

Error:
[msbuild] app\app.component.ts(11,14): error TS1219: Build: Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option to remove this warning. 

your reply can helps me a lot . i'm struggling this from month back please help me.
