### ISSUE TITLE
Error after updating to 1.8 final from 1.8 beta using VS2015.2 CTP

### ISSUE THREAD

**Issue by IanYates** [Microsoft/TypeScript#7207]
Hi,

I have VS 2015 update 2 CTP installed on Windows 8.1 with all current Windows Update patches applied.  I *had* the TypeScript 1.8 beta installed.

This morning I downloaded and installed TypeScript 1.8 final.

Now I cannot open any TypeScript files.  I closed VS and reran the TypeScript 1.8 final installer choosing to do a repair.

Same problem opening the files.

Before repairing I got the usual message from VS about checking the activity log.  After repairing I just get this in the status bar

```
The location assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040) The tab has been closed.
```

```
Note: See activity log contents attached to this post (renamed to *.txt)
```

My `c:\program files (x86)\Microsoft SDKs\TypeScript\1.8` folder (there's also a 1.7 one there) seems to be pretty complete.  

I've found `Microsoft.VisualStudio.LanguageServices.Typescript.dll`, `Microsoft.CodeAnalysis.TypeScript.EditorFeatures.dll` and `Microsoft.VisualStudio.TypeScript.Internal.dll` in `C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TypeScript`

Interestingly, the `Microsoft.VisualStudio.TypeScript.Internal.dll` is dated back to 5th January whereas the others are dated this morning when I did the install.  It's also 52016 bytes in size and was signed by Microsoft on 18th December 2015 with version 14.17.60.24818.  The version of the other two files in the folder are 14.1840.40222.1.

So I guess I have an old `Microsoft.VisualStudio.TypeScript.Internal.dll` file.  Another machine on which I've run the 1.8 installer (and it never had the 1.8 beta) has the same file though :(  On that other machine, which admittedly does *not* have the VS 2015 CTP, TypeScript works just fine.

Using Telerik JustDecompile on the DLL in question shows its assembly name is `Microsoft.VisualStudio.TypeScript.Internal, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a`, which is what VS is itself trying to load according to the `ActivityLog.xml`.

I've checked security access rights on the file and they're the same as the other TypeScript files but I think they're equally "faulty" too :(

[ActivityLog.txt](https://github.com/Microsoft/TypeScript/files/143865/ActivityLog.txt)

**Comment by djarekg** [comment]
I believe this is the same issue as [#7204](https://github.com/Microsoft/TypeScript/issues/7204). If you select open with on the TS file from the context menu the TypeScriptEditor is not available. If you have the Clear MEF cache extension installed and run that, after VS restarts you can open a TS file, but cannot edit.

**Comment by IanYates** [comment]
I haven't got that extension (are you suggesting I try it, or are you saying running that extension breaks things?)

I've uninstalled both TS 1.7 and 1.8 from "Programs and Features" in control panel.  I then found Visual Studio 2015 with Update 1 and asked it to repair.  A while later and presto - I have a working VS.

I haven't been game to run the TS installer again :)  However in Help->About the installed products list includes TypeScript 1.8.4.0.  I guess that's a win.

**Comment by djarekg** [comment]
These steps will only get to the point where the TS file can open but is still uneditable just like in the issue I referenced

**Comment by IanYates** [comment]
Thank @djarekg - I stopped and started writing this issue over the space of a few hours so I guess I started writing before that one came up and then posted mine afterwards.

I'm back up and running at least after repairing VS.  So far so good.

**Comment by IanYates** [comment]
Oh good grief - you're right.  I can't edit the TS files!?  I didn't get around to checking that.  Lots of incoming calls & email today distracting me.

Awful :(

**Comment by mhegazy** [comment]
Update 2 CTP does not support TS 1.8.4. We are looking into why the setup did not show the correct blocking message. 
TS has dependency on internal APIs that changed in Update 2, trying to install TS 1.8.4 (targeting Update1) will cause the language service to be broken.
Update 2 CTP has TS 1.8.1-beta in box, the next public release of Update2 should have the TS 1.8.4. sorry for the inconvenience.

**Comment by mhegazy** [comment]
this is the same issue as https://github.com/Microsoft/TypeScript/issues/5386
