### ISSUE TITLE
Async/Await generated code doesn't rethorw the error caught

### ISSUE THREAD

**Issue by pranaydutta89** [Microsoft/TypeScript#7214]
I am using async/await functionality in my nodejs app, when i see the the _awaiter generated code its like

```js
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator.throw(value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : new P(function (resolve) { resolve(result.value); }).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments)).next());
    });
}
```

the problem arises when i throw an error from inside an async function then according to the genreated code the fulfilled and rejected function catches and the same and doesn't rethrows it back ,so my application could catch the required error which i had thrown from the particular async function, is this being made by design ??

**Comment by Arnavion** [comment]
The exception thrown from the async function is used to reject the Promise returned by the async function (as you already noticed). That's how async functions work - they return a Promise that will be resolved to the final value or rejected with any error that happened.

If your calling code uses `await func()` then `await` will either return the final value or rethrow the exception. If your calling code uses `then()` with callbacks then you would have something like `func().then(result => /* result is the final value */, err => /* err is the exception */)`

**Comment by samvv** [comment]
> If your calling code uses await func() then await will either return the final value or rethrow the exception.

I just stumbled on the same issue as @pranaydutta89. Are you sure the exception gets rethrown? Because I just tried out the following snippet of code:

```
async function panic () { throw new Error('aaargghh') }

(async function () {
  panic()
})()

// nothing happens
```

Is the behavior described above correct? If not, is it possible to patch it?
