### ISSUE TITLE
Rest paramters causing error in node 4.2.6

### ISSUE THREAD

**Issue by pranaydutta89** [Microsoft/TypeScript#7215]
I am using typescript for my nodejs app, in es6 compilation mode, in some of my classes the generated js code looks like 

`
class mediasController extends lib.baseClasses.apiControllerAsyncBase().apiControllerAsync {
    constructor(...args) {
        super(...args);
        this.xyz = {};
    }
`

it has the es6 rest parameters which nodejs says as "unexpected token...", 
please provide me with an alternative or solution of the same .

**Comment by RyanCavanaugh** [comment]
If you target ES6, TypeScript is going to emit ES6 code (which includes rest args).

If your runtime doesn't support all ES6 features, you can target ES5, or choose not to use the unsupported ES6 features.

**Comment by pranaydutta89** [comment]
i cannot use es5 since i am using async/await and  typescript is automatically generating the rest params how to stop compiler to generate the rest params??

**Comment by mhegazy** [comment]
here is the issue tracking more granular transformations: https://github.com/Microsoft/TypeScript/issues/4692

**Comment by pranaydutta89** [comment]
@mhegazy  great ,in which version it is being targeted ??

**Comment by mhegazy** [comment]
We are starting with breaking up the lib in the next release, see https://github.com/Microsoft/TypeScript/issues/6974, the emit transformations comes next.

**Comment by bennyyip** [comment]
@pranaydutta89 I came across the same problem as yours.
Adding flag ```--harmony_rest_parameters``` to launch the app could solve it.
see [ECMAScript 2015 (ES6) in Node.js](https://nodejs.org/en/docs/es6/)
