### ISSUE TITLE
Fix IDBIndex interface for openCursor/openKeyCursor

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#7218]
**TypeScript Version:** 

master

**Expected:**

https://www.w3.org/TR/IndexedDB/

```ts
    openCursor(range?: any, direction?: string): IDBRequest;
    openKeyCursor(range?: any, direction?: string): IDBRequest;
```
**Actual:** 

```ts
    openCursor(range?: IDBKeyRange, direction?: string): IDBRequest;
    openKeyCursor(range?: IDBKeyRange, direction?: string): IDBRequest;
```

**Comment by DanielRosenwasser** [comment]
I don't think this is the appropriate fix. From the spec:

> If the range parameter is a key range then the cursor's range must be set to that range. Otherwise, if the range parameter is a valid key then the cursor's range is set to key range containing only that key value. If the range parameter is not specified, the cursor's key range is left as undefined.

Elsewhere:

> A value is said to be a valid key if it is one of the following ECMAScript [ECMA-262] types: Number primitive value, String primitive value, Date object, or Array object. An Array is only a valid key if every item in the array is defined and is a valid key (i.e. sparse arrays can not be valid keys) and if the Array doesn't directly or indirectly contain itself.

So based on that (as well as https://github.com/Microsoft/TypeScript/issues/3496#issuecomment-128553540 and https://github.com/Microsoft/TypeScript/issues/3988#issuecomment-124185555) it sounds like you want a

```ts
type IDBValidKey = number | string | Date | IDBArrayKey;
interface IDBArrayKey extends Array<IDBValidKey>{
}
```

```ts
    openCursor(range?: IDBKeyRange | IDBValidKey, direction?: string): IDBRequest;
    openKeyCursor(range?: IDBKeyRange | IDBValidKey, direction?: string): IDBRequest;
```

**Comment by falsandtru** [comment]
It should be an additional(another) pr because IDBValidKey is not defined by WebIDL. At least, we needs to unify the declaration. IDBObjectStore interface has a same method, different signature.

```ts
interface IDBObjectStore {
    ...
    openCursor(range?: any, direction?: string): IDBRequest;
}
```

And `range?: any` is valid, `range?: IDBKeyRange` is invalid in the spec. So firstly, we should fix to `range?: any`.

**Comment by zhengbli** [comment]
@DanielRosenwasser  Why not just
`type IDBValidKey = number | string | Date | Array<IDBValidKey>;`

**Comment by falsandtru** [comment]
This issue is fixed.
