### ISSUE TITLE
Installing 1.8.4 through Nuget does not update all the needed configuration reliably (targets) in the csproj files

### ISSUE THREAD

**Issue by OClement** [Microsoft/TypeScript#7219]
_Typescript version: 1.8.4 installed via Nuget (both MSBuild and Compiler packages)_

We're an issue where some projects in our solution will compile correctly on our development environment, but not the the Build Server; We're using TSF and MSbuild

The solution consists of multiple Projects defining the presentation layer, written in Typescript and when compiled outputs a single SystemJS Module Bundle. The compilation step is done by Visual Studio / MSbuild

For some reasons, when running the build on TFS, it searches for some JS files, only in some projects
I have no ideas where it references those files, as they don't exist anyways (and they're not meant to)

To be clearer, think of project A that has multiple TS files: 
```
    /projectA.export.ts                <- export/imports from the other files
    /folder1/someService.ts        <- exports a class
    /folder2/somethingElse.ts     <- exports a class
   /and so on
```

The output for this project is going to be a single file called say `projectA.bundle.js` that expeses all modules, so we can later do `import {someService} from 'projectA'`

So we never compile discrete TS to JS (these is no `projectA.export.js` or `someService.js`), and yet, TFS tries to locate them and wants to copy the somewhere

Anyone has ideas of what could be going on?

This is the relevant part of the ouput we get from the TFS build:

```
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v11.0\WebApplications\Microsoft.WebApplication.targets (182, 0)
Could not copy the file "infrastructure.export.js" because it was not found.
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v11.0\WebApplications\Microsoft.WebApplication.targets (182, 0)
Could not copy the file "_references.js" because it was not found.
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v11.0\WebApplications\Microsoft.WebApplication.targets (182, 0)
Could not copy the file "database\issueTrakDatabase.service.js" because it was not found.
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v11.0\WebApplications\Microsoft.WebApplication.targets (182, 0)
Could not copy the file "masterData.webmodel.export.js" because it was not found.
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v11.0\WebApplications\Microsoft.WebApplication.targets (182, 0)
Could not copy the file "masterData.webmodels.js" because it was not found.
Exception Message: MSBuild error 1 has ended this build. You can find more specific information about the cause of this error in above messages. (type BuildProcessTerminateException)
Exception Stack Trace: at System.Activities.Statements.Throw.Execute(CodeActivityContext context)
at System.Activities.CodeActivity.InternalExecute(ActivityInstance instance, ActivityExecutor executor, BookmarkManager bookmarkManager)
at System.Activities.Runtime.ActivityExecutor.ExecuteActivityWorkItem.ExecuteBody(ActivityExecutor executor, BookmarkManager bookmarkManager, Location resultLocation)
```

**Comment by OClement** [comment]
Update:
Seems that the issue was caused by conflicting `<import>` statements in the CSPROJ files
For some reasons, installing the Nuget packages didn't update/override all the needed configuration in there, for most projects (a few were fine). The strange thing is that beside the names, those projects are almost identical in term of configuration

I'll update the title to reflect this

**Comment by mhegazy** [comment]
The install script will only remove the imports that were added by default (e.g. in the default template). it literllay looks for the string:
```XML 
<Import Project="$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\TypeScript\Microsoft.TypeScript.targets" Condition="Exists('$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\TypeScript\Microsoft.TypeScript.targets')" />
```
if you have changed that, or added it manually, or are using a custom import to inject all your targets in your projects, then it will not be removed; and you will need to remove it manually. 

I will update the docs to reflect that: https://github.com/Microsoft/TypeScript/wiki/Configuring-MSBuild-projects-to-use-NuGet

**Comment by mhegazy** [comment]
@paulvanbrenk is there anything we can do here to make the experience better?

**Comment by paulvanbrenk** [comment]
@OClement can you send me one of the project files where the NuGet install doesn't work as expected? (Preferably on a gist).

**Comment by OClement** [comment]
Sure
I just won't be able to do this now though
But I'll keep that in mind and post one as soon as I can

Thanks for the update

O.

**Comment by darrengillis** [comment]
We are having the same issue on the build machine; however, NuGet isn't a factor - we didn't install via the Nuget packages.  

We are using a tsconfig.json file in the project and compiling to one output file.  When building on the server, we get the same behaviour where the build is attempting to copy .js files that don't exist.  Build seems to work when the tsconfig file is absent and the project settings are used.

**Comment by OClement** [comment]
@darrengillis 
In our case, when we had those errors, it looked as if Typescript wasn't running at all
You might want to look in your csproj files and check the configuration you have in there

What I did to help isolate the problem is to remove all VS Typescript Tools, rename the `typescript` folder under `Microsoft SDKs1 folder in program files, to make sure that it couldn't find any TSC.exe in there, and kind of force MSbuild to use the one installed by Nuget

If you haven't installed TSC from nuget, then you must have installed it some other way; If you're using the VS Tools, you must make sure you have them on your build server as well. If you don't plan on using that, then either the nuget version or the npm version (ran through other build script) is what you need

Hope this help


@paulvanbrenk 
Unfortunately I won't be able to provide a csproj anytime soon, sorry about that!

**Comment by darrengillis** [comment]
We are using VS Tools locally and on the server.  I can reproduce this locally running the similar build command that exists on the server: 

"C:\Program Files (x86)\MSBuild\14.0\bin\MSBuild.exe" ".\Solution.sln" /nr:False /fl /p:SkipInvalidConfigurations=true /p:VisualStudioVersion=14.0 /m /p:OutDir="..\..\..\bin\\" /p:Configuration="Release" /p:Platform="Any CPU"

This fails with the same output complaining about the .js files not being found.  

Removing the "OutDir" resolves the TS issue but then any relevant assemblies are not copied (expected behaviour).  We need the assemblies copied and we don't need the build looking for the .js files.  

This did work when using the project config settings and not tsconfig.  Removing the "out" attribute from tsconfig allows the build to succeed but this is most likely only because the .js files do now exist for the build to find/copy

**Comment by paulvanbrenk** [comment]
@darrengillis  you're probably seeing #7322
