### ISSUE TITLE
Incorrect .d.ts generated for destructuring arrow function with default

### ISSUE THREAD

**Issue by JKillian** [Microsoft/TypeScript#7222]
**TypeScript Version:** 
1.8.2 / nightly (1.9.0-dev.20160224)

#### Code ####
**main.tsx:**

```ts
import React = __React;
namespace A {
    export const Greeter = ({name = 'world'}) => <div>Hello, {name}!</div>;
}
```

**module1.tsx:**

```ts
const B = <A.Greeter/>;
```

**react.d.ts**
```ts
// latest version from the DT repo
```

#### Action ####
I run the following commands:

```
> tsc -d --jsx react react.d.ts main.tsx
> tsc --jsx react react.d.ts main.d.ts module1.tsx
```

#### Expected behavior ####
Both commands successfully complete.

#### Actual behavior ####
On TS 1.9.x:
```
> tsc --jsx react react.d.ts main.d.ts module1.tsx
main.d.ts(3,22): error TS2371: A parameter initializer is only allowed in a function or constructor implementation.
```

On TS 1.8.2:
```
> tsc --jsx react react.d.ts main.d.ts module1.tsx
main.d.ts(3,22): error TS1131: Property or signature expected.
main.d.ts(3,37): error TS1128: Declaration or statement expected.
main.d.ts(4,14): error TS1109: Expression expected.
main.d.ts(5,6): error TS1128: Declaration or statement expected.
main.d.ts(5,8): error TS1128: Declaration or statement expected.
main.d.ts(6,1): error TS1128: Declaration or statement expected.
```

##### Notes #####
It seems that the generated typings file, `main.d.ts`, is invalid:

```
import React = __React;
declare namespace A {
    const Greeter: ({name = 'world'}: {
        name?: string;
    }) => JSX.Element;
}
```

**Comment by RyanCavanaugh** [comment]
Minimal repro (run with `--d`)
```ts
const k = ({x = 'y'}) => { }
```

**Comment by JKillian** [comment]
Good call @RyanCavanaugh, all the React stuff above is not relevant to this bug. I happened to stumble across this when trying to use stateless functional components introduced in 1.8, so I'd guess that others might come across it soon as well :)

**Comment by mhegazy** [comment]
sorry @JKillian for the delay. fix should be in `typescript@next` later tonight.

**Comment by joewood** [comment]
I'm seeing this in the 1.8.10 official release. Was it ever patched or do I need to switch to the nightlies to get the fix?

**Comment by mhegazy** [comment]
@joewood, this was fixed after TS 1.8 was forked and release (note the milestone is `"TypeScript 2.0"`). there is no intention to back port the fix to 1.8.

**Comment by joewood** [comment]
OK, thanks. Any ETA on a dev release of 1.9 or 2.0? (i.e. should I change my code to remove default values on de-structured parameters)

**Comment by mhegazy** [comment]
Adding an explicit type annotation should circumvent the issue. e.g. `const k = ({x = 'y'} : { x: string }) => { }`

**Comment by joewood** [comment]
that didn't work for me...
```typescript
const k = ({x = 'y'}:{x:string}) => { }
```
still produces:
```typescript
declare const k: ({x = 'y'}: {
    x: string;
}) => void;
```

**Comment by joewood** [comment]
And with typescript@next it's:
```typescript
declare const k: ({x}: {
    x: string;
}) => void;
```

**Comment by mhegazy** [comment]
apologies for this, should have tried it before recommending it as a workaround. you are right. it does not work..

that leaves us with either not using the default, or changing the meaning  to make the initialization on the whole parameter (i.e. `const k = ({x} = {x: 'y'} ) => { }`);

**Comment by joewood** [comment]
yes, right - or doing a beta release soon 😄
