### ISSUE TITLE
type guards strangeness

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#7224]
**TypeScript Version:** 

1.8.0

**Code**

```ts
const enum AsNonBlank {}
export function isNonBlank(value: string) : value is string & AsNonBlank {
    return !/^\s*$/g.test(value);
}
let value: string;
if (isNonBlank(value)) {
    doThis(value); // expected value to be string & AsNonBlank, actual: string
} else {
    doThat(value);
}
function doThis(value: string & AsNonBlank): void {
}
function doThat(value: string) : void {
}
```

**Expected behavior:**
value should either be `string & AsNonBlank`
or there must be a message saying that the type guard is invalid or something
**Actual behavior:** 
value is a `string`

**Comment by yortus** [comment]
@aleksey-bykov I'm also finding that user-defined type guards often don't work the way I intuitively expect. Your example makes intuitive sense to me and I would have expected it to work.

However, since you haven't started with a union type, I suspect you are working outside the bounds of what tsc can currently do with type guards. I got your example to work by changing the declaration of `value` to:

```ts
let value: string | (string & AsNonBlank);
```

This seems to satisfy the compiler, and the narrowing happens as expected in both the `if` and `else` branches.

**Comment by yortus** [comment]
Interestingly, the following version of your code *does work* as you would expect without needing a union type:

```ts
const enum AsUnaryFunc {}
export function isUnaryFunc(value: Function) : value is Function & AsUnaryFunc {
    return value.length === 1;
}
let value: Function;
if (isUnaryFunc(value)) {
    doThis(value); // expected value to be Function & AsUnaryFunc, AND IT IS
} else {
    doThat(value);
}
function doThis(value: Function & AsUnaryFunc): void {
}
function doThat(value: Function) : void {
}

```

It's the same code as yours, just with `Function/AsUnaryFunction` instead of `string/AsNonBlank`.

**Comment by aleksey-bykov** [comment]
@yortus thanks!

**Comment by aleksey-bykov** [comment]
@yortus just checked with the union, it [doesn't work](http://www.typescriptlang.org/playground#src=const%20enum%20AsNonBlank%20%7B%7D%0D%0Aexport%20function%20isNonBlank(value%3A%20string%20%7C%20string%20%26%20AsNonBlank)%20%3A%20value%20is%20string%20%26%20AsNonBlank%20%7B%0D%0A%20%20%20%20return%20!%2F%5E%5Cs*%24%2Fg.test(value)%3B%0D%0A%7D%0D%0Alet%20value%3A%20string%3B%0D%0Aif%20(isNonBlank(value))%20%7B%0D%0A%20%20%20%20doThis(value)%3B%20%2F%2F%20expected%20value%20to%20be%20string%20%26%20AsNonBlank%2C%20actual%3A%20string%0D%0A%7D%20else%20%7B%0D%0A%20%20%20%20doThat(value)%3B%0D%0A%7D%0D%0Afunction%20doThis(value%3A%20string%20%26%20AsNonBlank)%3A%20void%20%7B%0D%0A%7D%0D%0Afunction%20doThat(value%3A%20string)%20%3A%20void%20%7B%0D%0A%7D%0D%0A) either

```typescript
const enum AsNonBlank {}
export function isNonBlank(value: string | string & AsNonBlank) : value is string & AsNonBlank {
    return !/^\s*$/g.test(value);
}
let value: string;
if (isNonBlank(value)) {
    doThis(value); // expected value to be string & AsNonBlank, actual is *STILL* a string
} else {
    doThat(value);
}
function doThis(value: string & AsNonBlank): void {
}
function doThat(value: string) : void {
}
```

**Comment by yortus** [comment]
Sorry I wasn't clear - this one works for me:

```ts
const enum AsNonBlank {}
export function isNonBlank(value: string) : value is string & AsNonBlank {
    return !/^\s*$/g.test(value);
}
let value: string | (string & AsNonBlank);    // <-- union here
if (isNonBlank(value)) {
    doThis(value); // expected value to be string & AsNonBlank
} else {
    doThat(value);
}
function doThis(value: string & AsNonBlank): void {
}
function doThat(value: string) : void {
}
```

**Comment by aleksey-bykov** [comment]
Thanks! That's a great help!
