### ISSUE TITLE
Allow overloads to be specified in interface

### ISSUE THREAD

**Issue by masaeedu** [Microsoft/TypeScript#7230]
**TypeScript Version:** 

nightly (1.9.0-dev.20160217)

**Code**
A contrived example:

```ts
interface Convert {
  (arg: string): number;
  (arg: number): string;
}

function convert(arg: number | string): number | string {
  return typeof arg === 'number' ? arg.toString() : parseFloat(arg);
}

let foo: Convert = convert;
```

**Expected behavior:**
Code above compiles, and the following compiles and runs without errors:

```ts
let result1: string = foo(10);
let result2: number = foo(result1);
assert(result2 === 10);
```

**Actual behavior:** 
Compilation error:

> ...(10,5): error TS2322: Type '<T>(arg: number | string) => number | string' is not assignable to type 'Convert'.
  Type 'number | string' is not assignable to type 'number'.
    Type 'string' is not assignable to type 'number'.

**Current approach:**
Specify all overloads again above function:

```ts
interface Convert {
  (arg: string): number;
  (arg: number): string;
}

function convert(arg: string): number;
function convert(arg: number): string;
function convert(arg: number | string): number | string {
  return typeof arg === 'number' ? arg.toString() : parseFloat(arg);
}

let foo: Convert = convert;
```

**Comment by RyanCavanaugh** [comment]
This is intentional. The signature `convert(arg: number | string): number | string` does not have the same contract as `Convert`. For example, you could have written:

```ts
function convert(arg: number | string): number | string {
  return Math.random() > 0.5 ? 42 : 'foo';
}
```
which doesn't maintain the `number -> number` / `string -> string` input/output relationship.

**Comment by masaeedu** [comment]
@RyanCavanaugh Yes, but regular overloads don't do this either, so I don't see how this case is any different. You can just as easily write:

```ts
function convert(arg: string): number;
function convert(arg: number): string;
function convert(arg: number | string): number | string {
  return Math.random() > 0.5 ? 42 : 'foo';
}
```

And when you request parameter completion at the following position:

```ts
foo(|
```

You will get `number -> string` and `string -> number`. Could this please be reconsidered?

**Comment by DanielRosenwasser** [comment]
The difference is that the implementation is free to delegate how users should call the function. Flexibility in authoring overloads, on the other hand, is strictly necessary.

Linking to #1805.

**Comment by masaeedu** [comment]
Shouldn't the interface be authoritative as to how users should call the function? That is the point of an interface after all. 

The discussion in #1805 suggests this is difficult to implement (or that the implementation would be computationally expensive). Couldn't the existing logic for ensuring that the bottom overload in an overload list satisfies all prior overloads be reused, in order to ensure that the function can be called with all signatures specified in the interface?

**Comment by RyanCavanaugh** [comment]
> Couldn't the existing logic for ensuring that the bottom overload in an overload list satisfies all prior overloads be reused, in order to ensure that the function can be called with all signatures specified in the interface?

It certainly could, but that logic would reject the assignment anyway. It's legal to invoke your function with a `number` and it's legal to invoke it with a `string`, but the return type of the function is invariantly `number|string` which is not assignable to `number` and is not assignable to `string`.

**Comment by masaeedu** [comment]
@DanielRosenwasser I should mention that what I'm suggesting is for a function that *already* accepts union types to be assignable to an interface with multiple overloads, not vice versa. The example given by @danquirk in that issue:

```ts
function foo(x: string, y: string) {}
function foo(x: number, y: number) {}

var arg: string|number;
foo(arg, arg); // should be an error
```

Is not relevant, since you're trying to pass a union type to an overloaded function.

**Comment by RyanCavanaugh** [comment]
@masaeedu the assignability rules *do* work that way. For example:

```ts
declare function fn(x: string): HTMLElement;
declare function fn(x: number): Element;

function myFn(x: string|number): HTMLDivElement { return undefined };

// OK
var x: typeof fn = myFn;
```

**Comment by masaeedu** [comment]
@RyanCavanaugh I hope I haven't been blathering on about something that already works :scream: Are you saying the last snippet in my previous comment should work?

**Comment by RyanCavanaugh** [comment]
It *shouldn't* work because it's **not** "exactly as type safe.".

Just to break it down:

  1. When invoked with `string`, `Convert` returns `string`
  2. When invoked with `string`, `convert` returns `number | string`
  3. It's not valid to assign a `number | string` to a `number`
  4. Therefore, it is not valid to use `convert` as a `Convert`

Each of these should be uncontroversial, I hope? Which of these do you consider to not be correct?

**Comment by masaeedu** [comment]
Okay, thanks. That helps. Let's start with 1. An instance of `Convert`, when invoked with `string`, returns `number`, not `string`.

**Comment by RyanCavanaugh** [comment]
Typo fixed

**Comment by masaeedu** [comment]
2 is fine. 3 is also true, but is not relevant, since we ignore this problem when creating overloads as well. When I do:

```ts
function convert(arg: string): number;
function convert(arg: number): string;
function convert(arg: number | string): number | string {
  return typeof arg === 'number' ? arg.toString() : parseFloat(arg);
}
```

there's no flow analysis being done to ensure that the function actually returns `number` when passed `string` and `string` when passed `number`. We just kind of close our eyes and hope the implementation does the right thing. 

In other words, we don't enforce the covariance of the function in its return type. We assume a function returning `number | string` is acceptable wherever a function that returns `number` is required, *and* wherever a function that returns `string` is required. We only enforce contravariance in its arguments.

**Comment by RyanCavanaugh** [comment]
I understand what you're suggesting, but don't see why it's at all desirable. What makes function return types special here compared to any other type system position? This line of reasoning works equally well anywhere -- we could just as well make all assignability relations completely bidirectional.

It seems like working backward from an example to produce a rule that doesn't generalize well.

**Comment by masaeedu** [comment]
@RyanCavanaugh It is true this doesn't work as a general principle. This would be a special case with respect to *overload* assignability only.

**Comment by masaeedu** [comment]
Please revisit this. My function implementations are starting to look like this, which is a total nightmare from a readability and DRY perspective:

```ts
  presignedGetObject(bucketName: string, objectName: string, callback: Callback<string>): void
  presignedGetObject(bucketName: string, objectName: string, expires: number, callback: Callback<string>): void
  presignedGetObject(bucketName: string, objectName: string, expires: number, respHeaders: ResponseHeaders, callback: Callback<string>): void
  presignedGetObject(bucketName: string, objectName: string, arg3: number | Callback<string>, arg4?: ResponseHeaders | Callback<string>, arg5?: Callback<string>) {
```

I can construct type signatures much more conveniently in `type ...` expressions using intersection types, and I really don't want to clutter up the implementation with all this noise.

I am able to do `type F = /* complicated function signature */; const f: F = (a, b, c) => { /* use a, b, c, with full type inference */ }`, **except** when the function signature is overloaded, so the special case is the behavior that's already baked in, not the behavior I'm proposing.

**Comment by kitsonk** [comment]
Just to comment, from a readability and DRY perspective, it is much better to author APIs that take an options bag, or even a tagged union option bag instead of creating overloads with complex signatures.

**Comment by masaeedu** [comment]
I'm not authoring these APIs; I'm converting a project to TypeScript. We
can't get rid of the problem of difficult to use overloads by saying "don't
use overloads", since the reason we have overloads is because nothing else
will suffice to describe certain JS code.

Neither unions nor destructured object params are capable of describing
functions with heterogeneous return types. Additionally, for functions
where the return type doesn't matter, you still can't get around using
overloads using unions: TypeScript does not support spread parameters
consisting of a union of tuples: `(...params: [A] | [A, B] | [C, B, A]):
void`.
