### ISSUE TITLE
finally clause with noImplicitReturns yields "Not all code paths return a value."

### ISSUE THREAD

**Issue by Deathspike** [Microsoft/TypeScript#7239]
In Visual Studio Tools 2015 1.8.4, an error occurs on:

```ts
function theAnswerToLifeTheUniverseAndEverything(): number {
  try {
    return 42;
  } finally {
    console.log('Returned the answer to life the universe and everything.');
  }
}
```

When `noImplicitReturns: true` is set. Error is `Not all code paths return a value.`. 

A `finally` clause is not capable of returning anything anyway, this code should be correct.

**Comment by mhegazy** [comment]
Fix should be in tonight `typescript@next`
