### ISSUE TITLE
Bug For ... in  with dictionary type

### ISSUE THREAD

**Issue by GiedriusGrabauskas** [Microsoft/TypeScript#7241]
In Microsoft Visual Studio 2015 with Typescript 1.8.4, an error occurs on:

```ts
let dictionary: {[key: number]: boolean } = {...};

for(let key in dictionary) {
  let num: number = key; // ERROR: Type 'string' is not assignable to type 'number'
}
```

Key in for loop is only string.

**Comment by RyanCavanaugh** [comment]
This is a correct error. `key` is of type `string` at runtime.

**Comment by GiedriusGrabauskas** [comment]
Then bug in dictionary key type.

_An index signature parameter type must be 'string' or 'number'._

**Comment by GiedriusGrabauskas** [comment]
In language spec it's called Index Signatures.
https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#394-index-signatures

It allows both string and number.

**Comment by DovydasNavickas** [comment]
This should not be correct error OR there are inconsistencies in language spec and tooling:

As it is written here:
thttps://github.com/Microsoft/TypeScript/wiki/What%27s-new-in-TypeScript#improved-checking-for-forin-statements
for..in loop implicitly

**Comment by DovydasNavickas** [comment]
This should not be correct error OR there are inconsistencies in language spec, tooling and "What's new" changelog:

As it is written here:
https://github.com/Microsoft/TypeScript/wiki/What%27s-new-in-TypeScript#improved-checking-for-forin-statements
```TypeScript
var a: MyObject[];
for (var x in a) {   // Type of x is implicitly string
    var obj = a[x];  // Type of obj is MyObject
}
```

Compiler implicitly assumes that index `var x` is of type `string`.

But as it is written here:
https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#394-index-signatures

>### <a name="3.9.4"/>3.9.4 Index Signatures
>
>An index signature defines a type constraint for properties in the containing type.
>
>&emsp;&emsp;*IndexSignature:*  
>&emsp;&emsp;&emsp;`[`&emsp;*BindingIdentifier*&emsp;`:`&emsp;`string`&emsp;`]`&emsp;*TypeAnnotation*  
>&emsp;&emsp;&emsp;`[`&emsp;*BindingIdentifier*&emsp;`:`&emsp;`number`&emsp;`]`&emsp;*TypeAnnotation*
>
>There are two kinds of index signatures:
>
>* ***String index signatures***, specified using index type `string`, define type constraints for all properties and numeric index signatures in the containing type. Specifically, in a type with a string index signature of type *T*, all properties and numeric index signatures must have types that are assignable to *T*.
>* ***Numeric index signatures***, specified using index type `number`, define type constraints for all numerically named properties in the containing type. Specifically, in a type with a numeric index signature of type *T*, all numerically named properties must have types that are assignable to *T*.
>
>A ***numerically named property*** is a property whose name is a valid numeric literal. Specifically, a property with a name *N* for which ToString(ToNumber(*N*)) is identical to *N*, where ToString and ToNumber are the abstract operations defined in ECMAScript specification.

A numeric index can be used while declaring object type and then `for..in` should take it implicitly as a numeric also.

Which begs the question: are you deprecating numeric index declaration for objects OR there is an actual bug in a compiler and tooling?

**Comment by ivogabe** [comment]
At runtime, all keys are stored as strings. Numeric keys are stored as strings. In a for-in loop you will thus always get a string. That's one of the strange things of JavaScript. You can see it yourself by adding `console.log(typeof key)` inside the loop.

**Comment by DovydasNavickas** [comment]
I've seen that, but isn't TypeScript actually solving this problem by enforcing specific type usage during compilation time?
And also, it doesn't really answer my question.

**Comment by RyanCavanaugh** [comment]
> Then bug is in a dictionary key type.

Can you clarify? I don't see what you're trying to do.

When you actually use the key inside the loop, you still get its numeric behavior:
```ts
let dictionary: {[key: number]: boolean } = {...};

for(let key in dictionary) {
  let x = dictionary[key]; // x: boolean
}
```

> Are you making a breaking change and deprecating numeric index declaration for objects?

 No

> There is an actual bug in a compiler and tooling?

I'm not seeing one based on what's been posted here.

I logged #7259 to cover updating the spec for the new imporved behavior.

**Comment by DovydasNavickas** [comment]
```TypeScript
let dictionary : { [key: number]: string} = {};

for(let key in dictionary){
	// key is implicitly string, should be number
	let item = dictionary[key];
}
```
You can simply go to http://www.typescriptlang.org/Playground and copy/paste this code.
Then hover on `dictionary` and you will see this:
![image](https://cloud.githubusercontent.com/assets/7989797/13359640/02a21b36-dcbe-11e5-89a6-8a8f2b467442.png)

Then hover on `key` and you will see the same thing that compiler says to us: the `key` is `string`
![image](https://cloud.githubusercontent.com/assets/7989797/13359659/155a9d20-dcbe-11e5-9655-d9ce4947263b.png)

**Comment by RyanCavanaugh** [comment]
`key` is a `string`. It should not be `number`; this would be simply wrong. It doesn't matter what the dictionary kind is, because the key is always a string.

You can't call `toFixed` on the `key`. You *can* call `substr` on it. It's a string. It's not a number. I'm not sure how to say it more plainly.

Why do you think we should take a value we *know* is a `string` and call it a `number` ?

**Comment by DovydasNavickas** [comment]
Hmm.... I don't like to say that I'm wrong, but yes. You are right about key in `for..in` always being `string` and that it should not be treated as `number` :+1:

And only now I actually understand what the spec says:
You can define type constraint on what string OR numeric keyed properties types will be.

Maybe documentation could use a sample for this?

Because it is acting a bit interestingly, when you use it with string or number types for properties:
```TypeScript
let dictionary1 : { [key: string] : string } = {};
let dictionary2 : { [key: number] : number } = {};

dictionary1[0] = 1; // Type 'number' is not assignable to type 'string'.
dictionary1[0] = "1";
dictionary1["1"] = 1; // Type 'number' is not assignable to type 'string'.
dictionary1["1"] = "1";

dictionary2[0] = 2;
dictionary2[0] = "2"; // Type 'string' is not assignable to type 'number'.
dictionary2["1"] = 2;
dictionary2["1"] = "2";
```

But even more interestingly, when you use it with a specific class/interface:
```TypeScript
interface MyObj { value: string }

let dictionary1 : { [key: string] : MyObj } = {};
let dictionary2 : { [key: number]: MyObj } = {};

dictionary1[0] = 1; // Type 'number' is not assignable to type 'MyObj'.
dictionary1[0] = "1"; // Type 'string' is not assignable to type 'MyObj'.
dictionary1["1"] = 1; // Type 'number' is not assignable to type 'MyObj'.
dictionary1["1"] = "1"; // Type 'string' is not assignable to type 'MyObj'.

dictionary2[0] = 1; // Type 'number' is not assignable to type 'MyObj'.
dictionary2[0] = "1"; // Type 'string' is not assignable to type 'MyObj'.
// But no errors for these two:
dictionary2["1"] = 1; 
dictionary2["1"] = "1";
```

Am I the only one who finds this misleading from spec perspective?

**Comment by RyanCavanaugh** [comment]
The last two aren't errors because it's hitting the implicit `any` indexer of all objects. They're flagged as errors under `--noImplicitAny`, though.

Arguably we could say that indexing by a *numeric string* should hit the numeric indexer, but it's not clear why anyone would ever write that code.

**Comment by DovydasNavickas** [comment]
Well, I think this is a quite probable situation:

```TypeScript
interface Calculation { calculate: (arg:number) => number }

class Squarer implements Calculation {
	calculate(arg: number) {
		return arg * arg;
	}
}

class Imposter {
	calculate() {
		return "I calculate";
	}
}

let calculations : { [key: number]: Calculation } = {};

calculations[0] = new Squarer();
calculations["1"] = new Imposter();

for(let key in calculations) {
    let calculation = calculations[key];

    // interface would still be implemented, if we set calculate to null or undefined
    if(calculation.calculate != null) {
        // this results in runtime error for second item, but compiler is fine with it:
        // Uncaught TypeError: calculation.calculate(...).toFixed is not a function
        console.log(calculation.calculate(2).toFixed(2));
    }
}
```

We have interface `Calculation` and one class implementing it, and one accidentally "kind of" complying with it (as of, we call the function `calculate(arg: number)` and there is no error as long as we do not use result as a `number`).
The whole example compiles fine and compiler says nothing about line `dictionary["1"] = new Imposter();`, because as you said:
>it's hitting the implicit `any` indexer of all objects


But when we iterate with `for..in` loop, it gives us a string key, which should result in `let calculation = calculations[key];` evaluating to `any`, because again, `key` is of type `string` and if we are out of `for..in` bounds, and have this code:
```TypeScript
let numericKey = 0;
let stringKey = "0";
let item1 = calculations[numericKey];
let item2 = calculations[stringKey];
```
`item1` is being treated as calculation (numeric key), but `item2` is treated as `any` (string key).

What is more, even if we use the same key supplied by `for..in` loop for us, which is a string, but call `.toString()` on it like this:
```TypeScript
for (let key in calculations) {
    let item = calculations[key]; // Calculation
    item.hello(); // error TS2339: Property 'hello' does not exist on type 'Calculation'.
    let itemWithStringKey = calculations[key.toString()]; // any
    itemWithStringKey.hello(); // no error, because itemWithStringKey is treated as any
}
```

It should at least behave the same as without `.toString()` being called, because both of indexes used are strings and have identical values. Now, it does fallback to saying "I have no idea what is this, it's gonna be `any`" with `key.toString()` index being used, but this is not how compiler should behave, should it?

**Comment by NN---** [comment]
@RyanCavanaugh I have a following code which breaks in 1.8:

```ts
export class State {
   subStates: SubStates = {};
}

export interface SubStates {
   [subStateId: number]: State;
}

interface States{
  [stateId: string]: FrameState;
}

class A {
  states: States = {};

  function remove(stateId: number, subStateId: number) {
    var subStates = this.states[stateId];
    if (subStates) {
     for (var subState in subStates) {
        this.remove(stateId, subState );
      }
    }
  }
}
```

This worked since I used numeric key to add and to remove.
The workaround is to call

**Comment by RyanCavanaugh** [comment]
I don't mean to be dismissive, but we've tried many, many different approaches of how to represent `for..in`, and all of them are problematic for normal JavaScript code in one way or another. The current approach (indexing by the iteration variable on a `number`-indexed type produces the index signature type, but the iteration variable is still correctly `string`) is by far the best available option we've seen. The behavior right now isn't perfect, but works for the vast majority of idiomatic loops.

What do you propose it do instead?
