### ISSUE TITLE
Duplicate identifier when using `export import ... = ...` with interfaces only

### ISSUE THREAD

**Issue by louy** [Microsoft/TypeScript#7242]
In a `.d.ts` file, I have the following:

```ts
import * as interfaces from './interfaces';

declare module sequelize {
  export import Promise = interfaces.Promise;
}
declare var sequelize: interfaces.Static;

export = sequelize;
```

I'm getting an error saying "duplicate identifier 'sequelize'". 
I think this might not be the best way of doing things, but I couldn't find any other way.
What I want to achieve is exporting the `sequelize` variable using `export =` syntax while also exporting some interfaces using `declare module`.

If I do this instead it works fine:

```ts
import * as interfaces from './interfaces';

declare module sequelize {
  type Promise<T> = interfaces.Promise<T>;
}
declare var sequelize: interfaces.Static;

export = sequelize;
```

but I don't want to use types because you cannot extend a type. another option is:

```ts
import * as interfaces from './interfaces';

declare module sequelize {
  interface Promise<T> extends interfaces.Promise<T> {}
}
declare var sequelize: interfaces.Static;

export = sequelize;
```

which works fine but is very confusing. Is there a better way to achieve this?
On a side note, it's very confusing to me how there are two types of modules. The one with `export`s and the one that's a namespace.
A better title for this issue is probably *cannot re-export interfaces in `declare module` without switching its type to object*

**Comment by louy** [comment]
Also this works fine, which means the issue only affects using `export import ...`, not `export ...` by itself.

```ts
import * as interfaces from './interfaces';

declare module sequelize {
  export type Promise<R> = interfaces.Promise<R>;
  // or
  // export interface Promise<R> extends interfaces.Promise<R> {}
}
declare var sequelize: interfaces.Static;

export = sequelize;
```

**Comment by RyanCavanaugh** [comment]
What is the content of the `./interfaces` module?

**Comment by mhegazy** [comment]
imports make a module instantiated. this is why it conflicts with your var.

**Comment by mhegazy** [comment]
This is done in a binding phase early on. and at that time we have no idea what the import will resolve to.

**Comment by louy** [comment]
**interfaces.d.ts** has something like this:
```ts
export interface Promise<T> {/*...*/}
export interface Static {/*...*/}
```

**Comment by louy** [comment]
so this behaviour of instantiated vs non-instantiated modules is really confusing. I also don't think it's documented, but anyway...
in my opinion there should be a way to re-export interfaces/types easily. something like this:

```ts
import Promise = interfaces.Promise;
declare module sequelize {
  export {Promise}; // can be a type or an interface
}
```

my problem with using `export import ...` vs `export interface Promise extends interfaces.Promise` is that I always have to specify type params in both places, and that it's much longer and isn't clear that I'm only re-exporting, not creating something new.

**Comment by mhegazy** [comment]
My only comment is i think the use of `export=` is what is complicating things.. if all what you want to do is reexport, then `export { Promise } from './interfaces';` should do the trick.
