### ISSUE TITLE
Typescript 1.8.4 installation breaks Visual Studio 2015 Community Edition

### ISSUE THREAD

**Issue by smoses2** [Microsoft/TypeScript#7245]
Installed Typescript 1.8.4 today.  On opening Visual Studio 2015 solution, had several error dialogs (see below).   Updating Typescript was intended to hopefully, magically fix some last remaining typescript errors in dt.ts files on setting up a project, but lead to an unusable IDE.

**From the activityLog.xml for VS2015**
>Could not load file or assembly 'Microsoft.VisualStudio.LanguageServices.TypeScript, Version=14.1800.40203.2, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

**From the project properties: Typescript window:**
Could not load file or assembly 'Microsoft.CodeAnalysis.TypeScript.EditorFeatures, Version=14.1800.40203.2, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

**Comment by mhegazy** [comment]
Is this Update2 CTP?

**Comment by smoses2** [comment]
Yes - VS 2015 Update 2 CTP;  Version 14.0.25008.00


Here are installed products on Win 10 machine with VS2015 Installed on C Drive:

Microsoft Visual Studio Community 2015 CTP
Version 14.0.25008.00 Update 2 CTP
Microsoft .NET Framework
Version 4.6.01038

Installed Version: Community

Visual Basic 2015 CTP   00322-20000-00000-AA880
Microsoft Visual Basic 2015 CTP

Visual C# 2015 CTP   00322-20000-00000-AA880
Microsoft Visual C# 2015 CTP

Visual C++ 2015 CTP   00322-20000-00000-AA880
Microsoft Visual C++ 2015 CTP

Visual F# 2015   00322-20000-00000-AA880
Microsoft Visual F# 2015

ASP.NET and Web Tools 2015 (RC1 Update 1)   14.1.20203.0
ASP.NET and Web Tools 2015 (RC1 Update 1)

ASP.NET Web Frameworks and Tools 2012.2   4.1.41102.0
For additional information, visit http://go.microsoft.com/fwlink/?LinkID=309563

ASP.NET Web Frameworks and Tools 2013   5.2.30624.0
For additional information, visit http://www.asp.net/

Azure App Service Tools v2.7.1   14.0.11112.0
Azure App Service Tools v2.7.1

Bundler & Minifier   1.8.147
Adds support for bundling and minifying JavaScript, CSS and HTML files in any project.

Common Azure Tools   1.7
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

CommonEditorPackage Extension   1.0
CommonEditorPackage Visual Stuido Extension Detailed Info

File Nesting   1.0
Automatically nest files based on file name and enables developers to nest and unnest any file manually

Image Optimizer   3.5.80
Uses industry standard tools to optimize any JPEG, PNG and Gifs - including animated Gifs. Can do both lossy and lossless optimization.

JavaScript Project System   2.0
JavaScript Project System

Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Mobile Services Tools

NuGet Package Manager   3.4.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

Open Command Line   2.0.168
Opens a command line at the root of the project. Support for all consoles such as CMD, PowerShell, Bash etc. Provides syntax highlighting, Intellisense and execution of .cmd and .bat files.

Open in Visual Studio Code   1.1.13
Adds a menu command that lets you open any solution, project, folder and file in Visual Studio Code.

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

Python Tools for Visual Studio   2.2.31124.00
Python Tools for Visual Studio provides IntelliSense, projects, templates, Interactive windows, and other support for Python developers.

Python Tools for Visual Studio - Django Integration   2.2.31124.00
Provides templates and integration for the Django web framework.

Python Tools for Visual Studio - Profiling Support   2.2.31124.00
Profiling support for Python projects.

SQL Server Data Tools   14.0.60127.0
Microsoft SQL Server Data Tools

TypeScript   1.8.4.0
TypeScript tools for Visual Studio

Visual Studio Tools for Universal Windows Apps   14.0.25008.00
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

Web Analyzer   1.7.75
Provides static analysis directly in Visual Studio for JavaScript, TypeScript, JSX, CSS and more

Web Compiler   1.10.306
Compiler for LESS, Sass and CoffeeScript files

Web Essentials 2015.1   1.0.207
Adds many useful features to Visual Studio for web developers. Requires Visual Studio 2015

**Comment by mhegazy** [comment]
this is the same as https://github.com/Microsoft/TypeScript/issues/7204

as mentioned in https://github.com/Microsoft/TypeScript/issues/7204#issuecomment-188094372:
> Update 2 CTP does not support TS 1.8.4. We are looking into why the setup did not show the correct blocking message. 
TS has dependency on internal APIs that changed in Update 2, trying to install TS 1.8.4 (targeting Update1) will cause the language service to be broken.
Update 2 CTP has TS 1.8.1-beta in box, the next public release of Update2 should have the TS 1.8.4. sorry for the inconvenience.

**Comment by smoses2** [comment]
Mohamed - what is the best way to revert to prior Typescript version.  ?fresh reinstall of VS and then install prior version of Typescript?
