### ISSUE TITLE
TypeScript 1.8 thinks no .ts files have changed when using a tsconfig.json file

### ISSUE THREAD

**Issue by DavidKDeutsch** [Microsoft/TypeScript#7247]
**TypeScript Version:** 

1.8.2

When building a Visual Studio solution using a tsconfig.json file, the CompileTypeScriptWithTSConfig task reports "Skipping target "CompileTypeScriptWithTSConfig" because all output files are up-to-date with respect to the input files.", even though I have indeed modified my .ts files since the last build. I see this behavior both building from the command line and from within the IDE. If I select "Rebuild Solution" from within the IDE, the files get compiled correctly. Also, if I remove the tsconfig.json file (thus using the properties in the .csproj file), the files also get compiled correctly.

FWIW, I would actually prefer to use the .csproj file rather than a tsconfig.json file, but as it stands now I cannot specify certain options (such as --noImplicitReturns and --noFallthroughCasesInSwitch) in the .csproj file.

**Comment by DavidKDeutsch** [comment]
Actually, after looking through the Microsoft.TypeScript.Targets file, I realized I can indeed specify those flags in my .csproj file; they just are not available in the IDE UI.

**Comment by mhegazy** [comment]
here is the full mapping for compiler options -> MSBuild proeperties: https://github.com/Microsoft/TypeScript/wiki/Setting-Compiler-Options-in-MSBuild-projects

**Comment by DavidKDeutsch** [comment]
...and after further investigation into the targets file, I see the problem: the CompileTypeScriptWithTSConfig target has "@(ConfigFiles)" as its Inputs attribute. So as long as the generated JavaScript files are newer than the tsconfig.json file, it will think it is up to date.

**Comment by mhegazy** [comment]
this is tracked by #6934.

The issue that the way the tasks work today is by "guessing" what the output will look like based on input. this is not feasible when using tsconfig.json. any more. we have a plan to make this work, but as noted in #6934 it is not a rather big change and will touch different parts of the system. so we will be doing this for the next release.

**Comment by DavidKDeutsch** [comment]
@mhegazy - I do not believe this is a duplicate of [#6934](https://github.com/Microsoft/TypeScript/issues/6934), which is a bug regarding how the list of _generated_ JavaScript files are calculated. This bug concerns the fact that the config file is listed as the sole _input_ to the CompileTypeScriptWithTSConfig target:

```xml
 <Target Name="CompileTypeScriptWithTSConfig"
    Condition="'$(BuildingProject)' != 'false' AND '@(ConfigFiles)' != ''"
    DependsOnTargets="$(CompileTypeScriptDependsOn)"
    Inputs="@(ConfigFiles)"
    Outputs="@(GeneratedJavascript)"> 
```

This tells msbuild to skip the target unless the _config_ file has changed since the last build, whereas the intention is to skip it unless one of the _TypeScript_ files has changed. Now it very well may be that you need to fix [#6934](https://github.com/Microsoft/TypeScript/issues/6934) to get incremental building working correctly, but in the meantime all you have to do to fix this issue is disable incremental building in the CompileTypeScriptWithTSConfig target by removing the `Inputs` and `Outputs` attributes. Otherwise, you will never be able to compile changed TypeScript files without either a) changing the tsconfig.json file or b) doing a rebuild solution, which seems like a pretty severe (yet easy to fix) bug.

**Comment by paulvanbrenk** [comment]
The fix for #6934 will actually fix this bug.

**Comment by mhegazy** [comment]
@paulvanbrenk, until #6934, i agree with @DavidKDeutsch that we should remove inputs and outputs and let the task run on every build. no incremental builds is better than stale output.

**Comment by DavidKDeutsch** [comment]
@paulvanbrenk - even when that bug is fixed, won't the `Inputs` attribute have to be changed to reflect the list of TypeScript files to be compiled, rather than just the config file?

**Comment by paulvanbrenk** [comment]
Yes, and I expect a couple of more changes to the targets file.

**Comment by gxclarke** [comment]
I'm using TypeScript 1.8.6 for VS 2015 and unable to compile typescript except by doing a rebuild.

I'm also using ASP.NET 5 / Core and so I don't have a .csproj file to edit for the suggested temporary fix. The .xproj file is bare bones and includes no typescript related details.

Is there a way to remove the inputs and outputs from the CompileTypeScriptWithTSConfig section in an ASP.NET 5 scenario?

Alternatively, will reverting to an earlier version of Typescript work for now, or is that likely to create new problems? Do I need 1.7.6 or is 1.8.4 sufficient?

**Comment by gxclarke** [comment]
I tried reverting to earlier versions of Typescript, but it was not a viable course of action:

- 1.7.6 - generates malformed tsc command line arguments that include both the project argument as well as files, which results in build failure.
- 1.8.4 - does not honor my tsconfig exclude settings that are needed for angular 2, which results in many ts compile errors.

So, re-installed 1.8.6 and I'm back to being able to compile but only via project rebuild.

**Comment by mhegazy** [comment]
What is wrong with compile on save? do you have `"compileOnSave": true` in your tsconfig.json?

**Comment by gxclarke** [comment]
Thank you, @mhegazy. I didn't realize this had been added in 1.8.4. You have resolved my issue.

**Comment by mhegazy** [comment]
For future references, here is the compileOnSave documentation: https://github.com/Microsoft/TypeScript/wiki/tsconfig.json#compileonsave

**Comment by oising** [comment]
is compileOnSave broken again in update 2? I can't get it to work at all. I have to rebuild the project to get the compiler to invoke.

**Comment by paulvanbrenk** [comment]
@oising not that we're aware off, can you file a new bug with a repro project.

**Comment by dtaalbers** [comment]
9aasw9
Eki9
9adsh

**Comment by paulvanbrenk** [comment]
This is fixed in the [nightly NuGet packages](https://www.myget.org/feed/typescript-preview/package/nuget/Microsoft.TypeScript.MSBuild) after 1.9.0-beta-20160411-1
