### ISSUE TITLE
Modules exporting literal objects with computed properties emit non-strict code (and so are unrunnable in 1.8)

### ISSUE THREAD

**Issue by pimterry** [Microsoft/TypeScript#7250]
**TypeScript Version:** 1.8.

**Code**:

```ts
export = { ["hi"]: "there" };
```

This (I assert) is valid and reasonable ES6 code, and isn't violating strict mode as written. I think TypeScript should be able to happily compile this to runnable code, without disabling strict mode.

**Compiled output**:

```js
define(["require", "exports"], function (require, exports) {
    "use strict";
    return (_a = {}, _a["hi"] = "there", _a);
});
```

The resulting compiled code though will not run in strict mode at all; it throws `_a is not defined`, because no variable declaration for _a has been emitted.

You can play with this to see the compiled output yourself in [the playground](http://www.typescriptlang.org/Playground#src=export%20%3D%20%7B%20%5B%22hi%22%5D%3A%20%22there%22%20%7D%3B) (although it won't run there, since it needs define to be defined).

Interestingly, this only seems to happen if the object with computed properties is used in the export statement. If you use such an object as an expression somewhere else than an extra `var _a;` line is also emitted to ensure it's strict, as in [this playground](http://www.typescriptlang.org/Playground#src=var%20x%20%3D%20(%7B%5B%22hi%22%5D%3A%20%22there%22%7D%20%3D%3D%3D%20%7B%7D)%3B%0Aexport%20%3D%20%7B%7D%3B).

**Expected output:**

This should compile to a strict-mode-compliant equivalent, perhaps something along the lines of:

```js
define(["require", "exports"], function (require, exports) {
    "use strict";
    var _a;
    return (_a = {}, _a["hi"] = "there", _a);
});
```

**Comment by vladima** [comment]
oops, have not noticed that it was already assigned to @yuit, sorry.
