### ISSUE TITLE
Multi await support

### ISSUE THREAD

**Issue by smcreator** [Microsoft/TypeScript#7253]
Dear, TypeScript team,

Could it be more efficient and convenient way to use multi await support. I wrote an example below:

```ts
 let sums = await Promise.all(result.map(item=> this.get<number>(`/api/values/${item}`)));
```
may it be better to use more smart syntax here:

```ts
 let sums = await result.map(item=> this.get<number>(`/api/values/${item}`));
```

so compiler here should use overloaded version of await: first with one promise parameter, and second with array of promises.
So this is just my offer for simplify this. Thank you in advance!

**Expected behavior:**
 let sums = await result.map(item=> this.get<number>(`/api/values/${item}`));

**Actual behavior:** 
 let sums = await result.map(item=> this.get<number>(`/api/values/${item}`));

Regards,
Serik

**Comment by DanielRosenwasser** [comment]
Changing the emit of `await` based on the type of its awaited expression goes against certain principles of our language - mainly that we avoid type-informed emit.
