### ISSUE TITLE
[question] produce definitions for both commonjs and globals?

### ISSUE THREAD

**Issue by nippur72** [Microsoft/TypeScript#7255]
I have a commonjs project that I would like to make it consumable from globals too (after webpacking and publishing it to `window`).

The problem is, how do I generate the `.d.ts` definitions for globals? Is that possible without modifying the code? Or do I have to rewrite them "by hand" ?

**Comment by RyanCavanaugh** [comment]
I believe you're looking for #7125 ?

**Comment by nippur72** [comment]
yes, thank you!
