### ISSUE TITLE
Reverse the order of `__param` metadata decorators emitted

### ISSUE THREAD

**Issue by vilic** [microsoft/TypeScript#7258]
Currently it's like:

``` js
__decorate([
    __param(0, _1.param({
        description: 'yo yo yo~'
    })),
    __param(1, _1.param({
        default: 456
    })),
    __param(2, _1.params({
        type: Number,
        required: true
    })),
    __metadata('design:type', Function),
    __metadata('design:paramtypes', [String, Number, Array, SystemOptions, Object]),
    __metadata('design:returntype', void 0)
], default_1.prototype, "execute", null);
```

And as the decorators are applied from the bottom to top, the invoking order of `__param` is somewhat weird. It would be great to have this reversed.

**Comment by mhegazy** [comment]
this is by design. decorators has to be evaluated (a decorator can be an expression and not just an identifier) in order they are defined, but executed in reverse order, to ensure they are cumulative.

**Comment by vilic** [comment]
@mhegazy I see, but I think **parameter** decorators should be evaluated in order they are defined by executed in reserve order. It's reasonable to have class, method and property decorator executed in reserve order as those decorators are decorating the same target. But this should not apply to parameter decorators in my opinion.

**Comment by RyanCavanaugh** [comment]
This doesn't seem to have affected anyone else
