### ISSUE TITLE
1.8: empty enums with same local name incorrectly considered same type

### ISSUE THREAD

**Issue by jeffreymorlan** [microsoft/TypeScript#7267]
In 1.8, if you declare two empty enums with the same local name in different modules, they are assignable, in violation of the spec (["different enum types are not assignable to each other"](https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#3.2.8)):

``` ts
module A { export declare enum Id {} }
module B { export declare enum Id {} }
var a: A.Id;
var b: B.Id;
a = b; // TypeScript 1.7 caught the error here, 1.8 does not.
```

This bug will not occur (i.e. the error will be correctly reported) if
- the enums have different local names,
- one or both of the enums are `const`, or
- the enums have named values with different names.

**Comment by RyanCavanaugh** [comment]
This is intentional (see #1748) but we need to update the spec

**Comment by jeffreymorlan** [comment]
Can I rely on them being unassignable if I make them `const`?

**Comment by RyanCavanaugh** [comment]
No. You could add some arbitrarily-named member to them, though.

**Comment by aleksey-bykov** [comment]
does it mean enums are no longer nominal?

**Comment by RyanCavanaugh** [comment]
No. For example:
```ts
enum A {
	x
}
enum B {
	x
}

// Still an error
var q: A = B.x;
```

**Comment by RyanCavanaugh** [comment]
The spec is now an "archived" artifact and we won't be tracking defects against it anymore.
