### ISSUE TITLE
Feature: type alternatives (to facilitate traits/mixins/type decorators)

### ISSUE THREAD

**Issue by mindplay-dk** [Microsoft/TypeScript#727]
The type system does a great job at mirroring most type patterns in JS, all except mixins/traits, anything that decorates types - which unfortunately is very common in JS.

Without it the type system remains incomplete - that is, we're still one step short of being able to describe JavaScript mixin type patterns.

[Duplication and interfaces](https://typescript.codeplex.com/wikipage?title=Mixins%20in%20TypeScript) are not the answer, because this does not reflect what's actually happening in JavaScript - e.g. not duplication, but type decoration of sorts. Not sure if I'm using the correct terminology here.

[This small library](https://github.com/muut/riotjs/blob/master/lib/observable.js) is an example of a real-world decorator - duplicating all of it's method declarations in every single model type in a view-model hierarchy would be extremely impractical.

The following is a simplified example:

	class User {
		public name: string;
	}
	
	interface Events {
		on(event: string, callback: {():void});
		// other methods here...
	}
	
	function addEvents<T>(object: T): T {
		// decorate the object:
		object['on'] = function() {
			// ...
		}
		return <T> {};
	}
	
	var user = addEvents(new User());

The drawback here is you have to choose which is more important - that `User` is still a `User` after being decorated by `addEvents()`, or that it is now also `Events`. There is no direct way to document this type pattern - your only option currently is to document the shape of the resulting type fully, duplicating all the member declarations contributed by the decorator.

I propose syntax along the lines of the following, to support type alternatives:

	function addEvents<T>(object: T): T|Events {
		// decorate the object:
		object['on'] = function() {
			// ...
		}
		return <T|Events> {};
	}

	var user = addEvents(new User());

The return type of the call is now `User|Events` which is a distinct composite type composed members of `User` and `Events`.

The resulting composite type extends `User` and implements `Events`, and should pass type-checks for both.

This should facilitate type-safe traits/mixins and probably other arbitrary type-patterns possible in JS.

Static type-hints with composite types are implemented in this way in e.g. PhpStorm using php-doc annotations, and it works well.

I think this may be a simpler and more flexible way to support mixins/traits, without explicitly adding support for those patterns specifically.

Thoughts?

**Comment by benliddicott** [comment]
@joewood, they don't need to be `extends`, only `implements`.

    function addEvents<T>(o: T): implements T, Events {
      o["on"] = function(){}
      return <implements T, Events>o;
    }

If an interface could be extend a type parameter, this would provide an alternative solution, more verbose, but also possible to be more type-safe:

    class C { c(){}}

    interface HasEvents<T> extends T { on(name, fn: (o: T, n:number);}

    function addEvents<T>(object: T) {
      object["on"]=function(){};
      return <HasEvents<T>>object;
    }

**Comment by benliddicott** [comment]
OK this is not like #14 or #805, it's kind of the opposite. Here we need to say, in a generic way, "if you give me any object I will give you back the same object but now supporting a new interface", i.e. of both types so it is an intersection type not a union type.

If interfaces could extend a type parameter this would solve the issue and enable expressing the traits pattern properly, as above.

In the a real-world example we would want something like this (standard `Emitter` pattern):

    interface Emitter{ 
      on(event, fn);
      once(event, fn);
      off(event, fn);
      emit(event);
    }
    interface EmitterTrait<T> extends T, Emitter{}

    function MakeEmitter<T> : EmitterTrait<T>(t: T){
      // add the functions to the object
      require('emitter-library').mixin(t);
      return <Observable<T>>t;
    }

Presumably it would also allow writing a type-safe .d.ts which did the same.

**Comment by benliddicott** [comment]
@mindplay-dk , I think this is resolved by Intersection types #3622 committed to master 21 days ago.

**Comment by mhegazy** [comment]
@benliddicott is correct. closing..
