### ISSUE TITLE
Type parameter inferred incorrectly when intersected with another type

### ISSUE THREAD

**Issue by vsiao** [Microsoft/TypeScript#7272]
**TypeScript Version:** 

1.8.0

**Code**

```ts
declare function foo1<T extends U, U>(target: T, source: U);
declare function foo2<T extends U, U>(target: T, source: U & { key?: string });
let x = { a: 1, b: 2 };

foo1(x, { c: 3 }); // Error as expected
foo2(x, { c: 3 }); // OK (Should be Error)
```

**Expected behavior:**
call to `foo2` should error with the same error as the call to `foo1`.

**Actual behavior:** 
call to `foo2` infers type parameter `U` as `{}`, to which `{ c: number }` is assignable.

cf. #7234

**Comment by mhegazy** [comment]
not sure what is the proposal here, `{}` for `U` seems like a correct inference.

**Comment by mhegazy** [comment]
please reopen if there is additional information.
