### ISSUE TITLE
Any plans to refactor typescript to modular structure ?

### ISSUE THREAD

**Issue by casser** [Microsoft/TypeScript#7273]
Guys do you have any plans to refactor TypeScript to modular structure ? 

Currently very hard to review and contribute the files with 15K lines. 

PS: thanks for such a great tool.

**Comment by mhegazy** [comment]
Well.. these are two different things. refactoring to modules does not necessary mean that checker.ts will be smaller :).

for the modular side, yes, we would like to do that at some point; if we were to start writing TS today we would definitely have everything as a module. @weswigham did an experiment to split up the code base into modules and there were a couple of pieces we need in place to make the change happen, namely declaration flattening.

for the size, this is something we talk about a lot. there are pieces that we can split up from the checker to make it smaller, and we have plans to do that, but id not think it is going to shrink much in the long run.

**Comment by casser** [comment]
So this will not come in near Roadmap :) 

Thanks for answer

**Comment by mhegazy** [comment]
Both issues are on our minds, but no concrete plans at the time being.
