### ISSUE TITLE
IntelliSense Doesn't Understand Type Annotations

### ISSUE THREAD

**Issue by egamma** [Microsoft/TypeScript#7275]
_From @joshuaskelton on February 26, 2016 19:31_

Salsa intellisense doesn't correctly handle JSX type annotations.

`'property declarations' can only be used in a .ts file.`

![screen shot 2016-02-26 at 11 27 16 am](https://cloud.githubusercontent.com/assets/14099985/13362982/1f2105ca-dc7c-11e5-8917-56b0d0df4741.png)

_Copied from original issue: Microsoft/vscode-react-native#85_

**Comment by billti** [comment]
Correct. We do not understand type annotations (other than JsDoc) in JavaScript files. The above is invalid JavaScript. 

We understand TypeScript type annotations in TypeScript files. We have no plans to understand flow type annotations.

**Comment by elkebirmed** [comment]
Is this an opensource repo?!!! @billti :-1:

**Comment by rattrayalex-stripe** [comment]
For others who run into this, I found I had to change this setting (Code > Preferences > Settings):

```
"javascript.validate.enable": false
```

This was mentioned at the bottom of the readme in the Flow extension: 
https://marketplace.visualstudio.com/items?itemName=flowtype.flow-for-vscode
