### ISSUE TITLE
Redundant `continue` in emit for loops that capture block-scoped bindings can trigger warnings in linters / minifiers

### ISSUE THREAD

**Issue by Arnavion** [Microsoft/TypeScript#7278]
1.8.2 / 1.9.0-dev.20160227

```typescript
function foo() {
	for (const i of [0, 1]) {
		if (i === 0) {
			continue;
		}

		// Trigger non-simple-loop emit
		(() => {
			console.log(i);
		})();
	}
}
```

is compiled in ES5 mode as

```javascript
function foo() {
    var _loop_1 = function(i) {
        if (i === 0) {
            return "continue";
        }
        // Trigger non-simple-loop emit
        (function () {
            console.log(i);
        })();
    };
    for (var _i = 0, _a = [0, 1]; _i < _a.length; _i++) {
        var i = _a[_i];
        var state_1 = _loop_1(i);
        if (state_1 === "continue") continue;
    }
}
```

`if (state_1 === "continue") continue;` triggers warnings in tools like UglifyJS in two ways:

1. `WARN: Dropping side-effect-free statement` - The `continue;` is redundant since it's the last statement of the loop when the if-branch is taken. It's eliminated, along with the now-empty if-block.
1. `WARN: Side effects in initialization of unused variable state_1` - `state_1` is now an unused variable but with side effects in its initialization. The variable is eliminated and the assignment converted to just the function call.

---

If a loop is simple but for one or more `continue`s (i.e. it has none of `break` / `return` / `break label` / `continue label`), then the loop body emit can be the same as for simple loops:

```javascript
        var i = _a[_i];
        _loop_1(i);
```

(and optionally, the closure emit can also have just `return;` instead of `return "continue";`)

**Comment by vladima** [comment]
fair enough, we can do this. Note: It will be difficult to switch `return "continue"` to `return` since we'll need a separate pass  to know all ways to exit the loop before emitting the converted loop body (probably switching to transformation-based emitted will allow this.)
