### ISSUE TITLE
Trailing Commas in Function Param Lists

### ISSUE THREAD

**Issue by ewinslow** [Microsoft/TypeScript#7279]
https://jeffmo.github.io/es-trailing-function-commas/

This proposal is Stage 3 according to https://github.com/tc39/ecma262, so seems like its at an appropriate stability for TypeScript team to implement it.

This would allow function definitions and calls in the following style: 

```ts
function foo(
  bar: Bar, // Comment about bar
  baz: Baz, // Comment about baz
) {
  // Implementation...
}

foo(
  bar,
  baz,
);
```

Benefits: https://github.com/jeffmo/es-trailing-function-commas/blob/master/proposal_presentation_slides.pdf

 * Helps with VCS authorship attribution in case of added/removed parameters
 * Consistency with object and array literals
 * Lintable (if you don't like the style, can ban it in your codebase with a linter)
 * Supported by other languages

In addition to all of the above, I suspect the extra "verbosity" of TypeScript's inline types makes this feature even more attractive in TypeScript than in vanilla JS. I feel this particularly in class constructors, which can also have `private` annotations, and possibly a `readonly` annotation coming down the pipe.

```ts
class Foo {
  constructor(
    private bar: Bar = new BasicBar(),
    private baz: Baz = new BasicBaz(),
  ) {}
}
```

**Comment by RyanCavanaugh** [comment]
Approved for whatever the Stage 3 proposal says

**Comment by mhegazy** [comment]
PRs are welcomed of course. the change should be limited to the parser, so would be a rather easy change to make.

**Comment by DanielRosenwasser** [comment]
Actually, signature help and overload resolution could potentially be affected by this.

**Comment by nojvek** [comment]
Is anyone taking on this? If not I can. I spent almost my entire weekend playing with the parser and scanner. 

@DanielRosenwasser, what do you mean by signature help and overload resolution?

**Comment by mhegazy** [comment]
@nojvek there is a PR for this already in https://github.com/Microsoft/TypeScript/issues/7747. if you want to take that over and respond to code review comments we can get it in.

**Comment by DanielRosenwasser** [comment]
@nojvek signature help is the little tooltip that shows up to show the parameters & their types when you call a function.

![image](https://cloud.githubusercontent.com/assets/972891/15480596/3f3c84e4-20db-11e6-98b0-4fac0e312b0e.png)


I mean that we specifically check if you have a trailing comma to see if there is a "better" overload in some cases.

For instance, here's a call to `localeCompare` with one argument:

![image](https://cloud.githubusercontent.com/assets/972891/15480627/71b304ac-20db-11e6-9245-367c59ec957d.png)

Here's a call with one argument and a trailing comma:

![image](https://cloud.githubusercontent.com/assets/972891/15480640/7eafddec-20db-11e6-962e-ccfb13127d5d.png)

**Comment by DanielRosenwasser** [comment]
So in general, my warning is that we can't do that anymore if we support trailing commas in argument lists. If we do that, you impair the experience of anyone who wants to use trailing commas in calls.

**Comment by mhegazy** [comment]
do not think this is an issue we should change the design of signature help for. you will get the pop up, you could decide to dismiss it an keep the comma.

**Comment by ewinslow** [comment]
Woohoo!

**Comment by basarat** [comment]
Personal opinion to any users : If you are thinking about adding a trailing comma to a function you might want to reconsider and change the function parameters to a single object https://basarat.gitbooks.io/typescript/content/docs/tips/functionParameters.html :rose:
