### ISSUE TITLE
" 1" with a space is treated like numeric property name

### ISSUE THREAD

**Issue by osdm** [Microsoft/TypeScript#728]
Quoted literal property names with leading or trailing spaces are treated as numeric property names, although they are not treated as numbers by JS.

    class A {
      [i: number]: number;
      public "1": string = "no space"; // Error here - OK
      public " 1": string = "space"; // Error here - Not expected?
    }
    var aaa = new A();
    window.alert(aaa[1]); // Shows "no space" to confirm JS behaviour

**Comment by DanielRosenwasser** [comment]
Any reason this has the milestone of 2.0? This is a relatively minor spec change.

**Comment by JsonFreeman** [comment]
Agreed

**Comment by jasonwilliams200OK** [comment]
@ahejlsberg, @osdm,
this bug is not reproducible in Version 1.5.0-beta (`npm install typescript@1.5.0-beta`), fixed by #860.

**Comment by DanielRosenwasser** [comment]
Thanks @jasonwilliams200OK, right now this tracks the need to update the spec.

**Comment by ahejlsberg** [comment]
Fixed in #4033.
