### ISSUE TITLE
Cannot use 'this' type in type argument on base types

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#7289]
``` ts
interface Foo<T> {
    thing: T;
}

interface Bar extends Foo<this> {
    thing: this;
}
```

``` ts
class Foo<T> {
    thing: T;
}

class Bar extends Foo<this> {
    thing: this;
}
```

``` ts
interface Foo<T> {
    thing: T;
}

class Bar implements Foo<this> {
    thing: this;
}
```

These examples have an error on the 'this' type argument of `Foo`:

```
TS2526  A 'this' type is available only in a non-static member of a class or interface.
```

Since an object type cannot reference a type parameter directly within a heritage clause, we shouldn't be giving this error.

**Comment by mhegazy** [comment]
The class is by design, as the type parameter could be used in the constructor. but the interface seems reasonable.

**Comment by DanielRosenwasser** [comment]
> as the type parameter could be used in the constructor

Can you elaborate what you mean? I'm not necessarily seeing the issue in that case.

**Comment by kitsonk** [comment]
Related to #6223.  While subtly different, I suspect they are in the same problem space.

**Comment by isiahmeadows** [comment]
Well...we could use it for Mithril.js types, where we were looking to add class support. We could avoid creating an entire boilerplate type by just allowing `this` as a generic parameter in the `implements` clause. Just thought I'd bring that up.

*(Oh, and [this](https://github.com/Microsoft/TypeScript/issues/9889#issuecomment-272629886) would also help quite a bit from the other end.)*

**Comment by RyanCavanaugh** [comment]
Seems to not be a very popular scenario
