### ISSUE TITLE
Salsa - no support to treat files without a suffix as .js files, they are always treated as .ts files

### ISSUE THREAD

**Issue by egamma** [Microsoft/TypeScript#7291]
extracted and summarized from Microsoft/vscode#3508

Applications generated with the express generator have a file `www` without suffix but with the shebang 
```
#!/usr/bin/env node
```

Code detects the file as a JS file and passes it to the tsserver. However, the tsserver treats this file as a .ts file and this results in type errors in a JS file.

To reproduce:
- git clone https://github.com/Microsoft/vscode-samples.git
- open the folder `node-express-javascript` in code
- open the file `bin/www`

Notice that there are errors from TS reported in this file,

**Comment by zhengbli** [comment]
This may require a tsserver API change to support opening a file as a specified `ScriptKind`, which will solve a more general category of issues.

**Comment by zhengbli** [comment]
With #7954, opening a file as a specific script kind is now supported.
