### ISSUE TITLE
No commonjs module resolution when there is no jsconfig.json

### ISSUE THREAD

**Issue by egamma** [Microsoft/TypeScript#7292]
Extracted from Microsoft/vscode#3509.

According to #6807 the default for module type is `commonjs`. However, in this example without a jsconfig.json then there are no completion proposals:

* no `jsconfig.json`
* add a file bar.js:
```
exports.foo = 3;
```
* add app.js add the following:
```
var bar = require('./bar');
bar.
```
There a no completions on `bar.`

The work around is to add a `jsconfig.json` that defines the module type to commonjs:

`jsconfig.json`
```json
{
    "compilerOptions": {
        "module": "commonjs"
    }
}
```

**Comment by billti** [comment]
Pull request https://github.com/Microsoft/TypeScript/pull/7466 is out for this issue.
