### ISSUE TITLE
treat some regexp as a comment start

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#7295]
_From @174255317 on February 24, 2016 10:28_

In jsx, expression like /^\/*$/ is treated as a comment start

_Copied from original issue: Microsoft/vscode#3392_

**Comment by RyanCavanaugh** [comment]
Presumably the repro for this is one line, but instead I have to guess where to put that string to repro the bug?

**Comment by DanielRosenwasser** [comment]
@174255317 can you elaborate what you meant? What exactly is the issue?

**Comment by DanielRosenwasser** [comment]
@174255317 I'm going to close this. Feel free to reopen with a solid repro.
