### ISSUE TITLE
Unintuitive compiled output when using array destructuring to swap variables

### ISSUE THREAD

**Issue by joshuacc** [Microsoft/TypeScript#7297]
**TypeScript Version:** 

1.8.2

**Code**

```ts
function whatever (idA, idB) {
	[idA, idB] = [idB, idA];
		
	return true; 
}
```

**Expected behavior:**

```js
function whatever(idA, idB) {
    var _a;
    _a = [idB, idA], idA = _a[0], idB = _a[1];
    return true;
}
```

**Actual behavior:** 

```js
function whatever(idA, idB) {
    _a = [idB, idA], idA = _a[0], idB = _a[1];
    return true;
    var _a;
}
```

Thanks to variable hoisting, there is no functional problem here. However, I consider the compiled code unintuitive.

In addition, using Istanbul for code coverage highlights the `var _a;` declaration as not covered.

**Comment by DanielRosenwasser** [comment]
Like you said, there's no problem here, and aggregating temporaries to emit at the end of a scope makes things a lot simpler during the emit phase. Perhaps when tree rewriting becomes our emit mechanism, this will be easier, so we can revisit this issue in the future. In the mean time, I'd consider filing a bug on Istanbul.
