### ISSUE TITLE
Document 'export *' elision as breaking change

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#7300]
From @JKillian [on Gitter](https://gitter.im/Microsoft/TypeScript?at=56d48bddb0c932986954cce8):

> We had some files that created an Angular directive or something, and they were "imported" in an `index.ts` file using `export * from "./path/to/file"`. The actual files though exported nothing. When we upgraded to 1.8.2, because there was nothing to import/export, those files never actually got required, and thus their side-effects - creating the angular directive - never happened

**Comment by RyanCavanaugh** [comment]
Probably too late now
