### ISSUE TITLE
Output folder in project settings is not respected in 1.8.+

### ISSUE THREAD

**Issue by dziedrius** [Microsoft/TypeScript#7312]
I've updated typescript from 1.8.0-beta to 1.8.4, then to 1.9.20160301.1-beta and typescript output is produced in same folder as is typescript file, not using output folder set in project settings.

**Comment by DanielRosenwasser** [comment]
Could you be more specific on your compiler settings? Are you using a `tsconfig.json`? What are the contents of it?

**Comment by mhegazy** [comment]
@dziedrius can you share a sample we can look at. we definitely want to make sure upgrading is not a wast of time to you.

**Comment by dziedrius** [comment]
I'm using project settings, not tsconfig.json and in project settings there's possibility to set javascript output directory, so I set it and it is ignored.
Anyway, I've investigated more and looks like this is related to this issue: https://github.com/Microsoft/TypeScript/issues/7257

I've moved import line below typescript properties manually and that fixed the issue.

**Comment by mhegazy** [comment]
thanks @dziedrius for digging into this. we are still investigating why #7257 is happening. please do let us know if you run into other issues.
