### ISSUE TITLE
Feature request: TypedClassDescriptor

### ISSUE THREAD

**Issue by sondreb** [Microsoft/TypeScript#7314]
Could it be possible to implement TypedClassDescriptor which works similar to TypedPropertyDescriptor, which could give access to e.g. class type name?

**Comment by mhegazy** [comment]
I would be interested to know how you will be using the instance type in the decorator.. but this should give you access to the type:

```ts
declare type Class<T> = {
    new (...args: any[]): T;
    prototype: T;
};

function dec<T>(target: Class<T>) {
    var instance: T;
    return target
}

@dec
class C {
}
```

**Comment by mhegazy** [comment]
please reopen if the issue has not been addressed.
