### ISSUE TITLE
foreignObject inside an SVG element is not recognized as valid attribute in TSX

### ISSUE THREAD

**Issue by Dynalon** [Microsoft/TypeScript#7315]
**TypeScript Version:** 

1.8.2

**Code**

```ts
// A self-contained demonstration of the problem follows...
class TestComponent extends React.Component<any, any> {
    render() {
        return <svg><foreignObject><p>Test</p></foreignObject></svg>;
    }
}
```

**Expected behavior:**

Compilation should succeed without an error.

**Actual behavior:** 

The compiler throws an error message:
`error TS2339: Property 'foreignObject' does not exist on type 'JSX.IntrinsicElements'.`

Even though the compiler throws an error, the code is still compiled and works as expected in browsers that support the `foreignObject` element inside SVG: https://developer.mozilla.org/en/docs/Web/SVG/Element/foreignObject

**Comment by RyanCavanaugh** [comment]
This needs to be added to react.d.ts, which is managed on DefinitelyTyped
