### ISSUE TITLE
New Website Logo: [Das Keyboard]

### ISSUE THREAD

**Issue by supercobra** [Microsoft/TypeScript#7320]
Please fill the following out:

- Name: Das Keyboard
- Homepage url: http://www.daskeyboard.com/
- Brand Guidelines/Licensing: nothing special
- Logo: http://www.daskeyboard.com/images/press-kit/daskeyboard-logo.png

**Comment by RyanCavanaugh** [comment]
Neat! What are you using TypeScript for?

**Comment by supercobra** [comment]
We are using it to develop our desktop application that configures
keyboards and mice. We are using Electron (http://electron.atom.io/),
Angular 2, and Typescript. The development teams love Typescript by the way.


-- Daniel

**Comment by mhegazy** [comment]
Should be in the next site update in the next few days.
