### ISSUE TITLE
Need a more defined story for TS + ASP.NET Core 1 (was ASP.NET 5)

### ISSUE THREAD

**Issue by sayedihashimi** [Microsoft/TypeScript#7321]
We are receiving a lot of questions about how to use ASP.NET Core 1 (formerly ASP.NET 5) and TypeScript.

Specifically @toresenneseth posted an issue ["What is the Typescript story with ASP.NET 5"](https://github.com/aspnet/Tooling/issues/38) where he asks

>What is the Typescript story with ASP.NET 5? At the moment (VS 2015 CTP6) it doesn't seem to work very well at all. Since it's still pre-release software I don't expect everything to work smoothly, but I need to know if you're planning on making them work well together for the final release or not.

He is not the only one with questions about how TS should be used with ASP.NET Core 1. We have had several [issues logged in the tooling repo](https://github.com/aspnet/Tooling/search?q=typescript&type=Issues&utf8=%E2%9C%93).

I think that some users are going down the MSBuild route, and others gulp/grunt but it seems like both sets of users are running into issues and there are no resources for them to unblock themselves. We need a more well defined usage of TS + ASP.NET Core 1. We may just have a documentation gap here which could be easily fixed. If we need to make updates to the ASP.NET Core 1 project system in Visual Studio please let me know how we can help.

cc @shanselman @DamianEdwards @danroth27

**Comment by billti** [comment]
We have the wiki page at https://github.com/Microsoft/TypeScript/wiki/Using-TypeScript-With-ASP.NET-5 to cover this specific topic, but it's not super discoverable and could do with some clean-up. I'll see if there might be a better location with our site redesign (cc @DanielRosenwasser who is working on docs).

p.s. I notice the issue in the ASP.NET forum you link to for you "*specifically...*" example is nearly a year old (the questions were posted in Mar 2015), which was before the wiki page was created. Do you have more recent examples of continuing questions here we can reference?

**Comment by billti** [comment]
@danroth27 @sayedihashimi I'll look into updating our walkthrough docs to go from "File / New Project" to working TypeScript & ASP.NET5 project (probably using Angular2 as the framework, as that's also a common request). What is the starter template/configuration you think this would be best based off? (Feel free to ping me internally if easier for links or attachments, etc., my alias is `billti`).

**Comment by danroth27** [comment]
@billti It would be good show folks how to setup typescript in the default web app project. If you want to show Angular as well it might make more sense to start from Empty.

**Comment by lucamorelli** [comment]
Hi, I finally fixed all the issues updating to the latest bits of angular 2 and aurelia, and if it can help I can I can upload simple projects using these frameworks working and exchanging data back and forth with a web api controller

**Comment by mhegazy** [comment]
@lucamorelli, @danroth27, and @sayedihashimi can you take a look at https://github.com/Microsoft/TypeScript-Handbook/pull/203

**Comment by sandersn** [comment]
#203 is merged now.
