### ISSUE TITLE
JSDoc autocomplete should not apply to classes

### ISSUE THREAD

**Issue by NoelAbrahams** [Microsoft/TypeScript#7325]
**Version**: TS 1.8.2 / VS 2015

I find the following JSDoc autocomplete terribly annoying:

![sample](https://cloud.githubusercontent.com/assets/1106823/13439313/d8937414-dfe4-11e5-8eb4-3078de224084.gif)

My JSDoc for classes is almost always a one-liner:

```typescript
/** This is the documentation for this class */
export class Position {
}
```

Please consider removing this autocomplete feature for classes, or at least provide an option for turning it off.

Thanks!

**Comment by RyanCavanaugh** [comment]
I don't think we'd have construct-level options or behavior for this, but an option to turn it off entirely seems reasonable.

**Comment by NoelAbrahams** [comment]
The autocomplete for methods and functions is certainly useful, as it can save having to type out parameters, e.g.

```typescript
/**
    * 
    * @param instance
    * @param startPosition
    * @param endPosition
    * @param durationMS
    */
public top(instance: {}, startPosition: string, endPosition: string, durationMS: number) 
```

It just doesn't make sense at the class-level.

**Comment by NoelAbrahams** [comment]
Another case that I think interferes with the normal flow is then a function or method has no parameters:


![sample](https://cloud.githubusercontent.com/assets/1106823/13500928/82a06c50-e15c-11e5-9b80-e4cfd4ab3101.gif)

My JSDoc for this case is, again, typically a single line:

```typescript
/** Gets a short description for each rating type. */
public getDescriptions() {

    return this.descriptions;
}
```

**Comment by Arnavion** [comment]
Just want to point out that parameter-less functions can still have `@return`, `@template`, etc annotations, so unless globally turned off with an LS option it should still be emitted.

**Comment by NoelAbrahams** [comment]
In my case I find that the return is already normally in the description, e.g "Adds an item to persistent storage and returns the id".

**Comment by Arnavion** [comment]
Yes, I understand. I'm just saying that it shouldn't be disabled completely, but only if the new option that Ryan mentioned proposed is enabled.

**Comment by RyanCavanaugh** [comment]
Discussed and several people felt that having multi-line comments here made sense too. So without a consensus that one is better than the other and a desire to not have tons of skeletoning options, the current behavior is what we'd like to continue with

**Comment by NoelAbrahams** [comment]
Oh dear. I have disliked JSDoc from day one, and it only gets worse with use with its intrusive and awkward  style. This is bad news.

Sent from my iPhone

On 17 May 2016, at 00:02, Ryan Cavanaugh <notifications@github.com<mailto:notifications@github.com>> wrote:


Discussed and several people felt that having multi-line comments here made sense too. So without a consensus that one is better than the other and a desire to not have tons of skeletoning options, the current behavior is what we'd like to continue with

-
