### ISSUE TITLE
forceConsistentCasingInFileNames error message doesn't contain enough information

### ISSUE THREAD

**Issue by prabirshrestha** [microsoft/TypeScript#7327]
**TypeScript Version:** 

1.9.0-dev.20160301

**Code**

a.ts

``` ts
import B from './b';
console.log(B);
```

B.ts (note the casing here)

``` ts
export default function B() {
}
```

**Expected behavior:**
a.ts is never referred in the the error so it is impossible to know which file and line number is actually trying to import it.

**Actual behavior:** 

``` cmd
tsc a.ts B.ts --forceConsistentCasingInFileNames
error TS1149: File name 'B.ts' differs from already included file name 'C:/dev/sample/a/b.ts' only in casing
```

Doesn't work with `--pretty` flag enabled too.

**Comment by bleiddyn** [comment]
This issue is also problematic to me. I cannot seem to find where visual studio is storing the lower-case version of the files. Until this bug is fixed, could we get a work-around set of steps or something?

**Comment by mhegazy** [comment]
PRs are always welcomed :)

the work around is global search in your project for the file name, with "match case" flag set.

**Comment by bleiddyn** [comment]
I was just testing that fix myself before posting it. Is there a reason I'm not thinking of to make that check in the first place?

**Comment by bleiddyn** [comment]
I believe the check is used to make sure the key matches in the map? I'm digging through the commit https://github.com/Microsoft/TypeScript/commit/b8a3564d284fb2344dcedcc603fcc23cd5a0f1f6 to get an idea.

So, would an acceptable fix be to update the key when running into this instead of throwing the error?

**Comment by mhegazy** [comment]
I am not sure i understand what you mean by "updating the key". the issue here is that the error does not include the other reference file name. so in the OP, `B.ts` (referenced on the commandline), the other file name `b.ts` (from the import of `./b`), but not where the import came from (i.e. `a.ts`). to do this we need to remember where a file came from when we add it to the list, so we can use this to report errors.

**Comment by bleiddyn** [comment]
Is there a reason for the error though, if we can just update the file map so it is case sensitive when we run into a difference between how the file is represented in the file map and how the file is capitalized on disk?

We have a list of paths keyed by the references to them in other files created by a call to createFileMap at https://github.com/Microsoft/TypeScript/blob/512c6719ae78c14de7e227979df3655a5a69158f/src/compiler/core.ts#L20 . So per the example, the path to b.ts is stored with the key 'b.ts'. When the code gets to where it throws the error, it's looking for 'b.ts' on disk, but only finds 'B.ts'. This throws the error.

My question is why would we not then update the key to match the casing of the name on disk? Change the key in the variable 'filesByName' to be 'B.ts'. No need for an error, it just corrects the reference when it finds it.

**Comment by mhegazy** [comment]
cause we do not know what the path on disk is. Most of the file path operations are done on strings to avoid hitting the disk for stats for every file.

**Comment by mhegazy** [comment]
hence the flag name. the flag does not ensure that you reference the file with the same case as on disk, it just ensures you do not reference it twice with two different cases.

**Comment by Delagen** [comment]
In my case paths on windows come with uppercase drive letter, but typescript complain with this error with the same path but with lowercase drive letter

**Comment by mhegazy** [comment]
@Delagen can you share a self-contained repro.

**Comment by Delagen** [comment]
#13728 the case of problem. I think lowercasing of paths must be disabled. So user must understand what to use in case of path or var naming. I prefer lowercasing filenames in all times separating words with dash or underscore.

**Comment by Delagen** [comment]
Sad but cannot provide repro. I receive this error in private project using typeRoots, types and paths settings of tsconfig.json.

**Comment by bitjson** [comment]
@Delagen – not sure, but maybe this is the issue you were facing? #16875

It happens reliably when using the `extends` property in `tsconfig.json`.

**Comment by Delagen** [comment]
@bitjson may be. I also using extends

**Comment by kemsky** [comment]
It happens when `extends` is used with `forceConsistentCasingInFileNames` set to `true`. I think it is different bug.

**Comment by briefguo** [comment]
I have met a problem. When the folder "config" is renamed  as "Config", after that, I 
renamed it back.It throw a error like
```shell
error TS1149: File name '/Users/gyj/.www/tool/app/src/routes/config/apis/index.ts' differs
from already included file name '/Users/gyj/.www/tool/app/src/routes/Config/apis/index.ts' only in casing.
```
Wheather is there a cache?(I have restarted TS server)

**Comment by zelein** [comment]
I've been able to accurately reproduce this bug (in a single project) by using `forceConsistentCasingInFileNames` set to `true` and using the `extends` keyword. By removing the extends, the bug goes away. However, I'm not always seeing this in every project that utilizes this schema. I have randomly hit this bug.

**Comment by sophistifunk** [comment]
I've been wrestling with this for a few hours, turns out it was `tsify` lowercasing the names passed to TSC. Reverting `tsify` to `3.0.2` fixed the issue for me, but it would've been a lot easier to find if TSC would remember *why* it has a specific casing and report that as part of the error, for example something like "first imported from /foo/bar/baz.ts" or "set as root build filename".

**Comment by RyanCavanaugh** [comment]
Not seeing any reproducible reports here lately. The new(ish) `--explainFiles` can tell you how/why a file got into your compilation, which I think is the root cause of any remaining confusion.
