### ISSUE TITLE
Release 1.8.5 has been updated on npm, but the file does not exist.

### ISSUE THREAD

**Issue by NickH-nz** [Microsoft/TypeScript#7330]
Working release:
https://registry.npmjs.org/typescript/-/typescript-1.8.2.tgz

Not working release:
https://registry.npmjs.org/typescript/-/typescript-1.8.5.tgz

Typescript "latest" points to 1.8.5.

npm install, npm update and accessing the files directly all hang and eventually return with a 504.

**Comment by blakeembrey** [comment]
:+1: Noticed this too. Automated updates with Greenkeeper have died on about a dozen of my repos :smile:

**Comment by sparecycles** [comment]
Blocks up ```scripts/npm.sh install``` when trying to build Microsoft/vscode, too. :cake:

**Comment by jaylegere** [comment]
:toilet:

**Comment by blakeembrey** [comment]
1.8.6 is loading.

**Comment by DanielRosenwasser** [comment]
I have no idea what caused this. Republishing seemed to work.

I present everyone with TypeScript 1.8.7, now hopefully with the ability to download from npm properly. :rainbow: :sparkles: 

Can everyone here give it a try?

**Comment by NickH-nz** [comment]
1.8.7 seems to work fine.

https://registry.npmjs.org/typescript/-/typescript-1.8.7.tgz

**Comment by jaylegere** [comment]
1.8.7 worked for me - thanks!

**Comment by DanielRosenwasser** [comment]
Awesome, glad to hear it everyone!
