### ISSUE TITLE
Types get confused in module with mixed promises and async functions

### ISSUE THREAD

**Issue by yortus** [Microsoft/TypeScript#7333]
**TypeScript Version:** 

1.9.0-dev.20160301

**Code**

![async-bluebird-promise-1](https://cloud.githubusercontent.com/assets/1252361/13448334/315e701c-e05d-11e5-9ab4-0b8f29e40be8.png)

![async-bluebird-promise-2](https://cloud.githubusercontent.com/assets/1252361/13448337/38ee3a38-e05d-11e5-85c7-eb885b0832f8.png)

This is using the [`bluebird.d.ts` file from DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/bluebird/bluebird.d.ts). That file ambiently declares `Promise` globally, even though it is imported as `BluebirdPromise`, which I guess is why the compiler gets mixed up.

The problem is that things like `bar().finally(...)` will compile without error, but crash at runtime.

**Comment by RyanCavanaugh** [comment]
The .d.ts file *said* there was something called `Promise` in global scope. What can the compiler do here (and how)?

**Comment by yortus** [comment]
The compiler probably can't do *much* since it's a case of global declaration merging. `bluebird.d.ts` declares `Promise` as a var, a namespace, and an interface. I think `lib.es6.d.ts` does too. These all merge without a hitch.

It is a bit weird to see it use the `BluebirdPromise` identifier in the return type of `bar`, but I suppose it thinks it can because it points to the same type that `Promise` points to, from the compiler's viewpoint (but it's not that way at runtime, of course).

Will #7125 offer a solution to this?

**Comment by RyanCavanaugh** [comment]
Yes, definitely. If bluebird.d.ts is written as a UMD module and `import`ed, its global `Promise` won't show up and you'll get an error on the `async` line (because there's no `Promise` in scope at that location)
