### ISSUE TITLE
Compiler allows async function expressions in ES3/ES5

### ISSUE THREAD

**Issue by yortus** [Microsoft/TypeScript#7334]
**TypeScript Version:** 

1.8

**Code**

```ts
// file: index.ts
declare class Promise<T> {/***/}
async function foo() { return 42; } // ERROR: Async functions are only available in ES6+
let bar = async function () { return 42; } // OK, but should be an error
let baz = async () => 42; // OK, but should be an error

// file: tsconfig.json
{
    "compilerOptions": {
        "target": "es5"
    }
}
```

**Expected behavior:**
The `bar` and `baz` lines should also get error TS1311 'Async functions are only available in ES6 or higher'.

**Actual behavior:** 
The `bar` and `baz` lines compile without errors.

**Comment by aleksey-bykov** [comment]
#8581 might me related

**Comment by aleksey-bykov** [comment]
also might relate: https://github.com/Microsoft/TypeScript/issues/8584
