### ISSUE TITLE
 msvcp140.dll is missing error in Nuget MsBuild Package "Microsoft.TypeScript.MSBuild.1.8.6"

### ISSUE THREAD

**Issue by mariusfilipowski** [Microsoft/TypeScript#7335]
**TypeScript Version:** 

Microsoft.TypeScript.MSBuild.1.8.6

**Code**
When I add this Nuget Package in a C#-Library Project or a C# ASP.NET Web-Project, nothing happens with the solution file. When I start the tsc.exe in the packages folder I get an error dialog box:

> The program cannot be started, since MSVCP140.dll is missing.

VS 2015 is not installed.Only VS2013 Ultimate Update 5

**Expected behavior:**
I would expect that the csproj would contain the props and target of the typescript compiler from the Microsoft.TypeScript.MSBuild.1.8.6-packages folder. And I would expect that I can start tsc.exe successfully from the commandline without this error.

**Actual behavior:** 
After applying the nuget package, the solution wide package.config has been changed. But the csproj is not changed and the typescript msbuild steps are not configured.

**Comment by mhegazy** [comment]
what versionof Nuget do you have installed? can you upgrade to Nuget v3?

**Comment by paulvanbrenk** [comment]
You'll need to install the [Visual C++ Redistributable](https://www.microsoft.com/en-us/download/details.aspx?id=48145).

**Comment by mariusfilipowski** [comment]
Thanks. Installing the C++ runtime (2015) helped to start tsc.exe without the msvcp*dll-error.

But the msbuild steps are still not included in the VS 2013 Project.
I have the latest NuGet for VS 2013 installed: 2.8.60723.765 and I am not offered any updates in VS. Is there a official VS Extension for nuget 3 for vs 2013?

**Comment by billti** [comment]
How much bigger is our package if we statically link? Seems unfortunate to ship a NuGet package to allow folks to build TypeScript without VS installed, and then also (possibly) require a 14MB install of the C++ runtime (and give a not-very-helpful message if it's missing).

**Comment by mhegazy** [comment]
The automatic injection is broken on VS 2013, only VS 2015; this issue is tracking fixing that. but as a workaround:

* Right-Click -> Unload Project
* Edit project file
* Replace references:

 * prop file:
 
  ```XML
<Import 
Project="$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\TypeScript\Microsoft.TypeScript.Default.props"
Condition="Exists('$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\TypeScript\Microsoft.TypeScript.Default.props')" />
  ```

  with 
  
  ```XML
<Import 
    Project="..\packages\Microsoft.TypeScript.MSBuild.1.8.6\tools\Microsoft.TypeScript.Default.props" 
    Condition="Exists('..\packages\Microsoft.TypeScript.MSBuild.1.8.6\tools\Microsoft.TypeScript.Default.props')" />
<Import 
    Project="..\packages\Microsoft.TypeScript.MSBuild.1.8.6\tools\Microsoft.TypeScript.NuGet.props" 
    Condition="Exists('..\packages\Microsoft.TypeScript.MSBuild.1.8.6\tools\Microsoft.TypeScript.NuGet.props')" />
  ```

 * and targets:


  ```XML
<Import 
    Project="$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\TypeScript\Microsoft.TypeScript.targets"
    Condition="Exists('$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\TypeScript\Microsoft.TypeScript.targets')" />
  ```


  with

  ```XML
<Import 
    Project="..\packages\Microsoft.TypeScript.MSBuild.1.8.6\tools\Microsoft.TypeScript.targets" 
    Condition="Exists('..\packages\Microsoft.TypeScript.MSBuild.1.8.6\tools\Microsoft.TypeScript.targets')" />
  ```

**Comment by paulvanbrenk** [comment]
This is fixed in the nightly NuGet pkgs

**Comment by mihailik** [comment]
Should this be reopened? It seems to be happening in [nuget Microsoft.TypeScript.MSBuild 2.0.3](https://www.nuget.org/packages/Microsoft.TypeScript.MSBuild/) released 22 September.

Original issue filed in March, so the next release must have been out by now?

I am getting this on CI server:
```
Project "PATH-TO-PROJECT\PROJECT-NAME.sln" (1) is building "PATH-TO-PROJECT\PROJECT-NAME.sln" (8) on node 1 (default targets).
PrepareForBuild:
  Creating directory "obj\Release\".
PreComputeCompileTypeScriptWithTSConfig:
  PATH-TO-PROJECT\packages\Microsoft.TypeScript.MSBuild.2.0.3\tools\tsc\tsc.exe --project "PATH-TO-PROJECT\tsconfig.json" --listEmittedFiles
CompileTypeScriptWithTSConfig:
  PATH-TO-PROJECT\packages\Microsoft.TypeScript.MSBuild.2.0.3\tools\tsc\tsc.exe --project "PATH-TO-PROJECT\tsconfig.json" --listEmittedFiles
PATH-TO-PROJECT\packages\Microsoft.TypeScript.MSBuild.2.0.3\tools\microsoft.TypeScript.targets(222,5): error MSB6006: "tsc.exe" exited with code 1. [PATH-TO-PROJECT\PROJECT-NAME.csproj]
Done Building Project "PATH-TO-PROJECT\PROJECT-NAME.csproj" (default targets) -- FAILED.
Done Building Project "PATH-TO-PROJECT\PROJECT-NAME.sln" (default targets) -- FAILED.
```

Note that whilst the title of this issue is about a DLL missing, the discussion above concerns itself with something completely different.

The problem I am referring to is the one from the title of the issue: a DLL is missing and with that build fails. As @mhegazy (mentioned in a comment)[https://github.com/Microsoft/TypeScript/issues/7557#issuecomment-197994208] the fix for missing DLL is coming — which seems it didn't in fact.

**Comment by mihailik** [comment]
@paulvanbrenk should this be reopened?

**Comment by mihailik** [comment]
If any extra logging-enabled runs would help, I'll be glad to run and pass more (sans physical paths).

**Comment by mihailik** [comment]
Running the nuget-generated command as part of pre-build step explicitly generates a bit more details:
```
"PATH-TO-PROJECT\PROJECT-NAMEcsproj" (default target) (8) ->
(PreBuildEvent target) -> 
  EXEC : Script failed with error : 'JsErrorScriptException (0x30001)'. [PATH-TO-PROJECT\PROJECT-NAME.csproj]
  C:\WINDOWS\Microsoft.NET\Framework64\v4.0.30319\Microsoft.Common.targets(1063,5): error MSB3073: The command "echo prebuild test? [PATH-TO-PROJECT\PROJECT-NAME.csproj]
```

**Comment by mhegazy** [comment]
@mihailik do you mind logging a new issue for this.

**Comment by mihailik** [comment]
As mentioned at https://github.com/Microsoft/TypeScript/issues/9720#issuecomment-250362769 , it looks like a duplication.

My workaround is to switch ON 'save on compile' and switch 'OFF' the actual build in CSPROJ — does the job, can get it better when the Chakra fix comes.

Thanks for investigation!
