### ISSUE TITLE
Remove numeric index signatures of Storage interface

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#7336]
Storage interface does not seem to have numeric index signatures.

https://www.w3.org/TR/webstorage/

**TypeScript Version:** 

master

**Diff**

```diff
interface Storage {
   [key: string]: any;
--    [index: number]: string;
}
```

**Comment by mhegazy** [comment]
From the spec:
> Each Storage object provides access to a list of key/value pairs, which are sometimes called items. Keys are strings. Any string (including the empty string) is a valid key. Values are similarly strings.

and
> The supported property names on a Storage object are the keys of each key/value pair currently present in the list associated with the object.

so if you ever use a number it should result in string and nothing else. strings indexer however is a bit tricky, as some strings could be property/method names, e.g. `storage["length"]`.

**Comment by falsandtru** [comment]
Numeric indexer works fine as a result because numeric indexer works as a string, but it is probably not explicit behavior on the spec. What do you think about that?

**Comment by mhegazy** [comment]
ideally you would have only a string indexer. but that is not possible (`length` is of type number). so numeric indexer seems like the next best thing. we can remove it, but that means that even this sub domain of possible values is not going to work.

**Comment by falsandtru** [comment]
I understood(I don't use any index signatures).

**Comment by mhegazy** [comment]
thanks. closing.
