### ISSUE TITLE
Multiple tsconfig.json's in a project causes invalid import intellisense in Visual Studio

### ISSUE THREAD

**Issue by johnnyreilly** [Microsoft/TypeScript#7338]
When you have a project in Visual Studio which has a number of `tsconfig.json`s the intellisense in VS appears to get mixed up between them.  I have a `tsconfig.json` for the main app source (my `src` directory) and another for my tests (`test`).  I noticed in my tests that if I copied and pasted an `import` statement from an `src` directory file to a `test` directory file the import lookup would still resolve.  But it would then fail when actually running the tests.

**TypeScript Version:** 

1.8.7

**Code**

```ts
import { loggerName, loggerService } from '../../../../src/angular/common/services/logger';
import { toolbarServiceName, toolbarService } from '../src/angular/secondaries/shell/toolbarService';
```

**Expected behavior:**
`loggerName` and `loggerService` should resolve; the exports from the `logger.ts` should be picked up successfully.
`toolbarServiceName` and `toolbarService` should not resolve; the path to the file is wrong.

**Actual behavior:** 
`loggerName` and `loggerService` resolve correctly.
`toolbarServiceName` and `toolbarService` resolve at compile time even thought the path to the file is wrong.  This means you find out that the path is wrong at run time rather than compile time.

**Comment by mhegazy** [comment]
is there a self contained repro we can look at?

**Comment by johnnyreilly** [comment]
I'm afraid not; I experienced it as I was adding unit testing to a large project which is not shareable.  I'll see if I can create a repro for you; it probably won't be very soon though.

**Comment by mhegazy** [comment]
this is not actionable at the moment. please reopen if you have a sample we can look at.
