### ISSUE TITLE
Extending Array breaks constructor

### ISSUE THREAD

**Issue by LongHairedHacker** [Microsoft/TypeScript#7340]
While playing around with the [extending expressions](https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#extending-expressions) feature added in 1.6, I noticed that extending
Array will somehow break the constructor.

**TypeScript Version:** 

1.8.7

**Code**

```ts
class ExtArray<U> extends Array<U> {

   // Doesn't matter if this constructor is present or simply omitted
    constructor(...args : U[]) {
        super(...args);
    }

    public contains(element : U) : boolean {
        var i = this.indexOf(element);
        return i !== -1;
    }
}

var test : ExtArray<string> = new ExtArray("a", "b", "c");

test.push("y");

console.log(test.length); // 1

console.log(test[0]);  // y
console.log(test[1]);  // undefined
console.log("Has a: " + test.contains("a"));  // Has a: false
console.log("Has y: " + test.contains("y"));  // Has y : true
```
There is also a [Typescript Playground version](http://www.typescriptlang.org/Playground#src=class%20ExtArray%3CU%3E%20extends%20Array%3CU%3E%20%7B%0A%0A%20%20%20%20constructor(...args%20%3A%20U%5B%5D)%20%7B%0A%20%20%20%20%20%20%20%20super(...args)%3B%0A%20%20%20%20%7D%0A%09%0A%09public%20contains(element%20%3A%20U)%20%3A%20boolean%20%7B%0A%20%20%20%20%20%20%20%20var%20i%20%3D%20this.indexOf(element)%3B%0A%20%20%20%20%20%20%20%20return%20i%20!%3D%3D%20-1%3B%0A%20%20%20%20%7D%0A%7D%0A%0A%0Avar%20test%20%3A%20ExtArray%3Cstring%3E%20%3D%20new%20ExtArray(%22a%22%2C%20%22b%22%2C%20%22c%22)%3B%0A%0Atest.push(%22y%22)%3B%0A%0Adocument.writeln(test.length%20%2B%20%22%3Cbr%2F%3E%22)%3B%0A%0Adocument.writeln(test%5B0%5D%20%2B%20%22%3Cbr%2F%3E%22)%3B%0Adocument.writeln(test%5B1%5D%20%2B%20%22%3Cbr%2F%3E%22)%3B%0A%0Adocument.writeln(%22Has%20a%3A%20%22%20%2B%20test.contains(%22a%22)%20%2B%20%22%3Cbr%2F%3E%22)%3B%0Adocument.writeln(%22Has%20y%3A%20%22%20%2B%20test.contains(%22y%22)%20%2B%20%22%3Cbr%2F%3E%22)%3B) of this example.

**Expected behavior:**
The normal array constructor adds any parameters passed to it as elements to the array.
I would expect that the ExtArray constructor, given above, does the same.
Especially since I could not find anything contradicting this assumption in the documentation. 

**Actual behavior:** 
The elements passed to the constructor are not added to the array, but the push method still seems to works.

**Additional Information:**

I've already asked a [question](https://stackoverflow.com/questions/35726630/extending-array-in-typscript-breaks-constructor) regarding this problem on stackoverflow.
As Nathan Friend points out in his [answer](http://stackoverflow.com/a/35727875/6003117) there, 
extending Array will also break JSON.stringify and it will lead to inconsistent result when checking if something is an array.
These problems might be related to the constructor issue in some way.

**Comment by RyanCavanaugh** [comment]
There isn't anything TypeScript can do about this -- it's just how Array's weird runtime behavior works.

See also http://perfectionkills.com/how-ecmascript-5-still-does-not-allow-to-subclass-an-array/

**Comment by LongHairedHacker** [comment]
Okay I was afraid this would be the case, thanks for the confirmation anyway.

In that case you should consider adding a warning somewhere in the documentation,
since I used code similar to above in a project and if you only initialize empty things,
everything looks fine.
Then I needed to initialize the array with a default value and everything broke.
Took me quite a few moments to figure out what goes actually wrong.
