### ISSUE TITLE
[Suggestion] pass method's property descriptor to parameter decorators

### ISSUE THREAD

**Issue by DavidKDeutsch** [Microsoft/TypeScript#7341]
It would be very convenient if a parameter decorator could modify the implementation of the function the parameter is declared in. Currently, the suggested way to do this is to have two decorators: a parameter decorator to add metadata to the function, and a method decorator to modify the function based on that metadata (see [this example](https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Decorators.md#parameter-decorators) in the TypeScript Handbook, which requires the use of both a "validate" and "required" decorator to implement parameter checking). Not only does this require the inclusion of the reflect-metadata library, it is also quite unwieldy when just a single decorator should suffice. 

I originally tried to accomplish this by altering the prototype of the target in the parameter decorator:

```ts
function myParamAttribute(target: Object, propertyKey: string | symbol, parameterIndex: number) {
    let method: Function = target[propertyKey];

    target[propertyKey] = function () {
        arguments[parameterIndex] = convert(arguments[parameterIndex]);
        return method.apply(this, arguments);
    }
 }
```

Unfortunately, the __decorate method that TypeScript emits restores the method's property descriptor after calling the decorators, so my changes were undone. I have found a workaround that works well by redefining the __param function...

```ts
var __param = function (paramIndex, decorator) {
    return function (target, key, descriptor) { decorator(target, key, paramIndex, descriptor); }
};
```

... and then implementing my decorator as such:

```ts
function myParamAttribute(target: Object, propertyKey: string | symbol, parameterIndex: number, descriptor?: TypedPropertyDescriptor<Function>) {
    let method = descriptor.value;
    descriptor.value = function () {
        arguments[parameterIndex] = convert(arguments[parameterIndex]);
        return method.apply(this, arguments);
    }
}
```

This is obviously sub-optimal, as it mucks with TypeScript's internals and is hardly future-proof. So it would be great if the property descriptor were passed to parameter attributes officially.

**Comment by mhegazy** [comment]
The decorator proposal is undergoing some changes now. we will not be chaining the TS implementation until the proposal has stabilized and then we can revisit this proposal.
