### ISSUE TITLE
Leading underscores in __extends etc prevent Closure minification

### ISSUE THREAD

**Issue by martine** [Microsoft/TypeScript#7345]
TypeScript helpers (__extends, __decorate, __param, etc.) currently all have leading underscores in their names in the generated code.  Unfortunately the Closure compiler treats names with a preceding underscore as special names that shouldn't be dead-code eliminated or renamed.

It would be nice if these builtins had some other name, e.g. `TypeScript__extends` or some such.  It's not really TypeScript's problem but Closure is currently the best minifier so working together is nice.

This would be fixed by issue #3364 as well, but I thought I'd capture the Closure-specific issue separately because it's not the same problem.

Example code to make it clearer: this input code
```js
function _foo() {
  return 3;
}
function bar() {
  return 3;
}
function baz() {
  return 3;
}
console.log(_foo(), bar());
```

in Closure produces

```js
function _foo() {
  return 3;
}
console.log(_foo(), function a() {
  return 3;
}());
```
where baz was eliminated and bar was renamed and inlined, but _foo was kept due to the underscore.

**Comment by mhegazy** [comment]
Please note that `--noEmitHelpers` will not emit any of these helpers and you can specify them once in your project.

**Comment by martine** [comment]
@mhegazy yes, I believe we use that.  But that one specification is redundant for helpers that are unused, and it'd be nice to be able to minify the function names (`__extends` => `a`) as well.

**Comment by mhegazy** [comment]
https://github.com/Microsoft/TypeScript/issues/3364 is on the road map. so we should have that working soon.
