### ISSUE TITLE
tsconfig "outDir" functionality

### ISSUE THREAD

**Issue by MCKRUZ** [Microsoft/TypeScript#7346]
So I currently have my project setup exactly the way it is setup in this tutorial
[https://github.com/Microsoft/TypeScript/wiki/Using-TypeScript-With-ASP.NET-5]

however in my scripts folder I now want to put another level so it would look like

scripts
----app
--------foo.ts

and have it ultimately export out to my wwwroot directory like this

wwwroot
----app
---------foo.js

however I'm finding that all scripts regardless of directory structure end up sitting at the top of the wwwroot directory.  Meaning that the outDir: "../wwwroot" does not take folder structure into account.

In addition I have noticed that when I delete typescript files it doesn't delete the same javascript files within my transpiled folder.

Are these known issues or am I doing something wrong?

**Comment by mhegazy** [comment]
use --rootDir to point to your `scripts` folder. if not set, it will be inferred to `app`.

**Comment by mhegazy** [comment]
need to add this to the FAQ page.

**Comment by MCKRUZ** [comment]
I don't understand.  Putting that setting in will perpetuate the sub level folders?

**Comment by mhegazy** [comment]
from my reply in https://github.com/Microsoft/TypeScript/issues/6435#issuecomment-175753092

> For outDir computation, if you only specify `--outDir` the output structure generated by the compiler is mapped to the input, this is based on a common path calculation, which is the longest common prefix of all your input files. Obviously this changes with the input files, so to tell the compiler what is the root of your source tree that you want mapped in the output, use `--rootDir`.

**Comment by MCKRUZ** [comment]
Ok that worked.  Now what about the deletion of files?  If I delete something from my rootDir, it will not subsequently delete it from my outDir.  Do I need to create a gulp task for this?

**Comment by mhegazy** [comment]
the compiler does not delete anything. so i would suggest that your clean task would blow away your output directory, this way you can always go back to a clean state.

**Comment by mhegazy** [comment]
Added documentation to https://github.com/Microsoft/TypeScript/wiki/FAQ#why-does---outdir-moves-output-after-adding-a-new-file
