### ISSUE TITLE
Allow inference of some type parameters

### ISSUE THREAD

**Issue by chadaustin** [Microsoft/TypeScript#7351]
**TypeScript Version:** 1.8.7

**Code**

```ts
function make_component<A, B extends A>(arg: () => B) {
}

h<{x: string}>(() => {
	return {
		x: "hello",
		y: 10,
	};
});
```

I have a function that produces a higher-order react component by taking a function that knows how to take a set of "external props", run a function taking the external props returning "computed props".  The union of the external props and the computed props is a set of "internal props", which the internal React component can rely on.

I want the caller to specify just one of these property sets, and have everything else be inferred by the function argument passed in.  The code above is a simplified example of this.

Note that only one type parameter is specified -- I would hope the second could be inferred by the function argument (like C++).

However, instead I get a "Supplied parameters do not match any signature of call target." error.

**Comment by RyanCavanaugh** [comment]
I believe this is just #7234 ?

**Comment by chadaustin** [comment]
Ah, that looks the same.  We could close as a duplicate of #7234 and test again once it's fixed.

**Comment by RyanCavanaugh** [comment]
Sounds good, thanks!
