### ISSUE TITLE
Overloaded array type

### ISSUE THREAD

**Issue by Ptival** [Microsoft/TypeScript#7357]
I was unable to find this in the documentation or among the existing issues.

Is there any way to have overloaded array types? Something that would look like:

````
interface I {
    [s: string]<T extends Bar>: T;
    method<T extends Bar>(): T;   // this is allowed
}
````

I guess it would also need a syntax at call-sites, which would look weird:

````
declare var array: I

// and in client code:
class Foo extends Bar { foo(); }
array["field"]<Foo>.foo();
````

(As an aside, I'm not sure how to use the array type syntax)

My apologies if this is already do-able, I couldn't find a way...

**Comment by RyanCavanaugh** [comment]
There isn't a direct way to do this, but really all you're doing is writing a type assertion at the indexing site. You could equivalently write:

```ts
declare var array: { [s: string]: Bar; };
(<Foo>array["field"]).foo();
```

**Comment by Ptival** [comment]
It would indeed defer type assertions to the indexing site, but it could at least guarantee the subtyping condition.

My use case is for a JS library which registers multiple kinds of objects into an array.
If I just make it:

````
interface W2UI {
    [s: string]: any;
}
declare var w2ui : W2UI
````

Then I don't get any documentation/type-checking out of what comes out of the array.
Since the main mode of interaction with the library is with:

````
w2ui["layout"].layoutMethod();
w2ui["tab"].tabMethod();
````

It becomes pretty much useless to even give type to anything.

Is there a way to describe a type that is one of 7 classes, but is allowed to be any of them? (even when they are not compatible)

**Comment by RyanCavanaugh** [comment]
You could use a union type:
```ts
interface W2UI {
  [s: string]: TabControl | InputControl | LabelControl;
}
var arr: W2UI;
// Just type assert
(<InputControl>arr["input"]).setValue();
// N.B. still typesafeish
(<HTMLDivElement>arr["nope"]).blur(); // Error, can't convert HTMLDivElement to ...

// Use some actual sanity checking
const x = arr['layout'];
if(x instanceof TabControl) {
  x.tabMethod();
}
```

**Comment by Ptival** [comment]
Ok, that's what I though of initially but was annoyed to have to cast every time. I can't think of a better way to do it though. Thanks for the quick feedback!

**Comment by Ptival** [comment]
Actually since there is often need for multiple calls, it works ok with:

````
let layout: W2UI.W2Layout = w2ui["layout"];
layout.call1();
layout.call2();
...
````
