### ISSUE TITLE
Expose ts.isExternalModule as public API

### ISSUE THREAD

**Issue by mattmccutchen** [Microsoft/TypeScript#7359]
[Work is in progress](https://github.com/Urigo/angular2-meteor/issues/102) on an official TypeScript plugin for the [Meteor](https://www.meteor.com/) web application framework.  The plan is to set the `module` option to `commonjs` and support both external modules and files that are not external modules.  But the plugin needs to know whether each source file is an external module so it can tell Meteor to either register the output file as a commonjs module or simply run it in the global scope.  Would you be willing to expose the [ts.isExternalModule](https://github.com/Microsoft/TypeScript/blob/0f6dbd02506eb61f18e7317693b1598bcf294a24/src/compiler/utilities.ts#L410) function for this purpose?

**Comment by mhegazy** [comment]
Seems like a reasonable request. we would accept a PR for it.

**Comment by DanielRosenwasser** [comment]
Thanks @mattmccutchen!
