### ISSUE TITLE
Upgrading Visual Studio projects to use multiple tsconfig.json files [VS Typescript 1.8]

### ISSUE THREAD

**Issue by tolemac** [Microsoft/TypeScript#7361]
**TypeScript Version: 1.8**

The complete explanation: http://stackoverflow.com/questions/35755272/multiple-tsconfig-on-a-visual-studio-2015-project-typescript-1-8

I have upgrading my ASP.NET MVC 4 project to use multiple `tsconfig.json` files.
When I have create the `tsconfig` files, the project properties sections is disabled saying `One or more tsconfig.json files detected. Project properties are disabled.` but when compile it the comiler get compiler options from project file and not from `tsconfig.json` files.

I have to manually clear typescript project settings from `.csproj` file to make it works.

**Expected behavior:**
When `tsconfig.json` file is present, the compiler have to ignore project settings.

**Actual behavior:** 
The compiler get options from project file.

**Comment by tolemac** [comment]
I was wrong ... sorry.

The real problem is that `tsconfig.json` files are included on prject as:

    <None Include="typescript\tsconfig.json" />

I have change it by;

    <Content Include="typescript\tsconfig.json" />

And all it's ok

**Comment by zapping** [comment]
This will also help:
1. Open Solution Explorer
1. Right click on the tsconfig.json file and choose 'Exclude From Project'.
2. You might see the tsconfig.json disappear from the Solution Explorer. In that case choose 'Show All Files' option from the top of the Solution Explorer toolbar.
3. Right click on the tsconfig.json and choose 'Include In Project'.
