### ISSUE TITLE
VS2015 returns JsErrorScriptException when compilerOptions.watch is true

### ISSUE THREAD

**Issue by Liero** [Microsoft/TypeScript#7362]
In Visual Studio 2015 create TypeScript HTML app.
Add .ts file to the project
Add tsconfig.json to the project and set `"watch": true`

```javascript
{
  "compileOnSave" : true,
  "compilerOptions": {
    "watch": true,
    "noImplicitAny": false,
    "noEmitOnError": true,
    "removeComments": false,
    "sourceMap": true,
    "target": "es5"
  },
  "exclude": [
    "node_modules",
    "wwwroot"
  ]
}
````
Build the project. Build should fail with an error:
> VSTSC : Script failed with error : 'JsErrorScriptException (0x30001)'.

I'm using:
VS2015 Enterprise Version 14.0.24720.00 Update 1
Typescript 1.8.6.0
WebEssentials 2015.1, build 1.0.209
Resharper 2015.2, build 103.0.20150818.200216 (I've tried to suspend it in order to eliminate influence)

**Comment by shanalikhan** [comment]
im getting the same error all things updated though

**Comment by mwallnberger** [comment]
I also still have this error with
VS2015 Enterprise Version 14.0.24720.00 Update 1
Typescript 1.8.6.0

**Comment by mhegazy** [comment]
The issue has been fixed in master. it is available in the nightly nuget package, and will be available in the nextrelease. TS 1.8.* does not have that.

Either way, the fix is to show a valid error message instead of crashing. but `--watch` is still an invalid argument to pass to tsc.exe.

**Comment by mwallnberger** [comment]
@mhegazy Thank you very much for quick answer. I understand the first part of your answer, that this bug is only fixed in the upcomming 2.0 version.  But how can I compile the *.ts sources to *.js sources (in Visual Studio 2015) by saving the *.ts?

**Comment by mhegazy** [comment]
set `"compileOnSave": true` but note this is not in the `"compilerOptions"`. i.e

```json
{
  "compileOnSave": true,
  "compilerOptions": { ...}
  "exclude": [] 
}
```

see https://github.com/Microsoft/TypeScript/wiki/tsconfig.json#compileonsave for more details.

**Comment by mwallnberger** [comment]
@mhegazy 
Thank you! It works <3

**Comment by DeeZeeThreezy** [comment]
Using `compileOnSave` worked for me when using Visual Studio w/ Update 2. But i've recently installed Update 3 and it will no longer compile on save. My setup is as follows...

VS TypeScript Extension: 1.8.36.0
Environment Variable Path: `C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.8`
`tsc -v`: 1.8.34

I've also made the manual fix for compiling RxJs extensions, https://github.com/Microsoft/TypeScript/issues/8518#issuecomment-223156931.

**Comment by dudih** [comment]
I have the same error on my VS2015 update 3, RC1.
Adding "compileOnSave" didn't work for me.

I also have the "Web-Essentials 2015.3" extension.

In my folder path: "C:\Program Files (x86)\Microsoft SDKs\TypeScript"
I have 2 folders: "1.0", "1.8".

However, when checking for version from cmd in the project foder I got:
 >tsc -v
Version 1.0.3.0

**Comment by dudih** [comment]
[THIS](http://stackoverflow.com/a/35258446/4572425) post solved my problem:
Updating the PATH variable of Win10 to be "1.8" instead of "1.0",
and using "compileOnSave" instead of "watch".

Now it's works.

**Comment by elemental21** [comment]
I have VS 2015 Update 3 on Win10, fixed the 1.0/1.8 issue in the PATH variable. I've tried compileOnSave, the settings in options for compile on save, and watch gives me a build error as well as not compiling on save either.

Works fine when I build

**Comment by elemental21** [comment]
Turns out when I added a Gulp task to delete all .js and .js.map files in the Typescript outDir folder it causes Typescript to generate the refreshed .js and .js.map files automatically. These files have been added to the .tfignore file so they are not in TFS.  Not sure why this is happening.

**Comment by Serjster** [comment]
If you are getting a **JsErrorScriptException (0x30001)** in VS then almost certainly you missed mhegazy's point that "compileOnSave": true, does NOT go inside the "compilerOptions": {}, but on the same level as it.

This is mine:
```
{
  "compileOnSave": true,
  "compilerOptions": {
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "inlineSourceMap": true,
    "inlineSources": true,
    "module": "system",
    "moduleResolution": "node",
    "noEmitOnError": true,
    "noImplicitAny": false,
    "outDir": "./wwwroot/js",
    "removeComments": false,
    "target": "es5"
  },
  "exclude": [
    "node_modules",
    "wwwroot"
  ]
}
```
