### ISSUE TITLE
"Go to symbol..." does not work in JS IIFE

### ISSUE THREAD

**Issue by egamma** [Microsoft/TypeScript#7365]
_From @kuechlerm on March 2, 2016 9:27_

In 0.10.10-insider the following code causes the "Go to symbol..."-box to state "No symbols found".

`(function() {
    function foo() { }
})();`

I would expect to see 'foo' listed as a symbol, which is the case without the IIFE.

_Copied from original issue: Microsoft/vscode#3618_

**Comment by RyanCavanaugh** [comment]
Duplicate of #7134
