### ISSUE TITLE
Incorrect parsing

### ISSUE THREAD

**Issue by lazutkin** [Microsoft/TypeScript#7366]
**TypeScript Version:** 

1.8.7

**Code**

```ts
let s
let a
let b

s = "" // <-- Syntax error iff there is no ';' here
[a, b] = [1, 2]

```

**Comment by s-panferov** [comment]
Babel does the same https://babeljs.io/repl/#?experimental=true&evaluate=false&loose=false&spec=false&playground=false&code=let%20s%0Alet%20a%0Alet%20b%0A%0As%20%3D%20%22%22%0A%5Ba%2C%20b%5D%20%3D%20%5B1%2C%202%5D

I believe this is by design.

**Comment by RyanCavanaugh** [comment]
I'm very confused. I don't see a syntax error in TypeScript (@ `master`) *or* in Babel in the Playground.

TypeScript issues the correct type error "error TS2450: Left-hand side of assignment expression cannot be a constant or a read-only property."

**Comment by Arnavion** [comment]
Yes, @s-panferov is correct. String literals don't allow automatic semi-colon insertion.

@RyanCavanaugh - Babel repl's output is malformed due to the same issue (notice the `[(a, b)]`. I believe that's what the OP meant.

**Comment by mhegazy** [comment]
looking at the [spec](http://www.ecma-international.org/ecma-262/6.0/#sec-automatic-semicolon-insertion), I do not see why a semicolon is required. 

>When, as a Script or Module is parsed from left to right, a token (called the offending token) is encountered that is **not allowed by any production of the grammar**, then a semicolon is automatically inserted before the offending token if one or more of the following conditions is true:
* The offending token is separated from the previous token by at least one LineTerminator.
* The offending token is }.
* The previous token is ) and the inserted semicolon would then be parsed as the terminating semicolon of a do-while statement (13.7.2).

in the example above, this is a valid production, the string literal followed by `[` is a `MemberExpression`, `a, b` is a comma expression, followed by an assignment. so i do not see why ASI would kick in here.

This is more or less the same as :

```ts
var x = ""
["toString"]; 

typeof x === "function"; // true
```

**Comment by RyanCavanaugh** [comment]
To clarify: Babel's output is correct, as is TypeScript's warning about an invalid assignment LHS
