### ISSUE TITLE
Export default abstract class not allowed in class declaration

### ISSUE THREAD

**Issue by xLama** [Microsoft/TypeScript#7375]
**TypeScript Version:** 

1.8.2

**Code**

```ts

export default abstract class A  {} // Error
```

```ts

// Ok
abstract class A  {}
export default A;
````

I have not red anything about this in docs.

Thanks.

**Comment by mhegazy** [comment]
duplicate of https://github.com/Microsoft/TypeScript/issues/3792

**Comment by RyanCavanaugh** [comment]
Please search before logging new issues :cry:

![image](https://cloud.githubusercontent.com/assets/6685088/13507347/0ed6a6f6-e137-11e5-9601-6c56931dcf1e.png)
