### ISSUE TITLE
Create infrastructure to test command line execution

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#7379]
We sometimes see issues with the command line itself, such as specific errors not getting reported, different return codes being used, etc.

The reason these bugs are missed is because the way our testing infrastructure works is by consuming our internal APIs separately from how `tsc.ts` consumes it. As a result, the two may fall out of sync and we may not notice.

We should expand our testing infrastructure to actually test `tsc.ts` itself and track the behavior of how the compiler will behave on the command line.

**Comment by yuit** [comment]
In additional to command-line flag, we should add an infrastructure to test parsing for tsconfig. We currently only have unit-test for testing parsing tsconfig to json object. But we don't have unittest for testing json object to full compiler-options or typing-options.

**Comment by danquirk** [comment]
Just as a historical note, this is roughly what the projects tests were for.

**Comment by weswigham** [comment]
The `user` and now `docker` test suites use `tsc.js` and the whole `typescript` package, respectively. While not unit tests, these integration tests have got this covered from a basic harness-needs perspective. Should we desire, we are currently more than capable of writing custom tests into either suite that use `typescript` and its bundled utilities in any arbitrary esoteric way.
