### ISSUE TITLE
Union types don't match function signatures

### ISSUE THREAD

**Issue by errorx666** [Microsoft/TypeScript#7380]
**TypeScript Version:** 

nightly (1.9.0-dev.20160303)

**Code**

```ts
interface Foo {
	foo( key: string ): string;
	foo( keys: string[] ): string[];
}

declare var foo: Foo;
declare const bar: string|string[];

const baz = foo.foo( bar );
```

**Expected behavior:**
The code is valid and compiles without warning, because interface `Foo` contains a signature for a method `foo` corresponding to each type in the union `string|string[]`.  The `foo` method can accept a parameter list of `string`, and it can also accept a parameter list of `string[]`, therefore an argument list of `string|string[]` is satisfiable.

I would expect the return type for `foo.foo` invoked in this faction to be the type union of the return types of all matching signatures (so `string|string[]`).  This code produces the same error even if all matching signatures have the same return type.

**Actual behavior:** 
`Argument of type 'string | string[]' is not assignable to parameter of type 'string[]'  Type 'string' is not assignable to type 'string[]'.`

**Comment by RyanCavanaugh** [comment]
Duplicate #1805

**Comment by mhegazy** [comment]
you can also find a long discussion on why `{ foo(string|string[]):string|string[] }` is not the same as `{ foo (string): string;  foo (string[]): string[]; }` at https://github.com/Microsoft/TypeScript/issues/7230. This should help shedding some light on how the API should be authored.

**Comment by errorx666** [comment]
Maybe this is a degenerate case, but I feel like this instance should be satisfiable.
I feel like defining the interface this way is preferrable, because we can preserve the mapping for `string`->`string` and `string[]`->`string[]`.  Passing in a parameter that matches both should simply result in `string|string[]`->`string|string[]`.  Being less specific in what is passed in results in a result that is less specific, and vice versa.
In my actual code, both methods return `void`, so there really is no ambiguity; still, this is unsupported.
