### ISSUE TITLE
'this' type in augment function is any

### ISSUE THREAD

**Issue by todoubaba** [Microsoft/TypeScript#7381]
**TypeScript Version:** 

1.8.7

**Code**

```ts
/* foo.ts*/
export class Foo {
    name: string;
}

/*bar.ts*/
import {Foo} from './foo'
declare module './foo' {
    interface Foo {
        bar(): string;
    }
}

Foo.prototype.bar = function() {
    return this.name; // this's type is any
}
```

**Expected behavior:**
The type of `this` in augment function `bar` is `any`.
**Actual behavior:** 
The type of `this` is `Foo`.

**Comment by mhegazy** [comment]
this is currently by design. `this` is of type any outside the body of a class. issue https://github.com/Microsoft/TypeScript/issues/6018 tracks adding the ability to declare it.
