### ISSUE TITLE
Proposal: Constants in interfaces for inlining primitive datatype values

### ISSUE THREAD

**Issue by pederwagner** [Microsoft/TypeScript#7385]
I am often in the need of many constant strings or integer values.
This can for example be schema names of attributes, which will typically be auto generated into TS classes or modules from a separate datasource.

When generating string constants in TypeScript, the output can be very large, while the only use is for IntelliSense. For this reason, it creates an unnecessary bulk of JS data that needs to be loaded in the final application.

It would be nice to be able to declare constants in an interface, that would be compiled away in the JavaScript output. Usages should be replaced by the constant value (Only primitive datatypes).

Sample interface:
```
declare module dbScema {
    export interface IMyTableColumnNames {
        const Column1Name: string = "COLUMN_1";
        const Column2Name: string = "COLUMN_2";
    }
}
```

Sample usage (TS):
```
alert(dbScema.IMyTableColumnNames.Column1Name);
```

Sample output (JS):
```
alert("COLUMN_1");
```

What do you think?

**Comment by mhegazy** [comment]
looks like another scenario for https://github.com/Microsoft/TypeScript/issues/3964 to cover.
