### ISSUE TITLE
Typescript cannot detect parameter types on generic methods in index signatures

### ISSUE THREAD

**Issue by JohnWhiteTB** [Microsoft/TypeScript#7391]
If I create an interface with an index signature that has generic functions as values, the compiler can no longer detect the parameter types on these methods. I've also opened a [question](http://stackoverflow.com/questions/35800958/typescript-cannot-detect-parameter-types-on-generic-methods-in-index-signatures/) on StackOverflow.

**TypeScript Version:** 

1.8.5 and below

**Code**

```ts
interface MethodCollection {
    [methodName: string]: <T>(id: number, text: string, options: T) => boolean | void;
}

var myMethods: MethodCollection = {
    methodA: (id, text, options) => {
        // id: any
        // text: any
        // options: any
    }
}
```

> Error: Parameter 'text' implicitly has 'any' type. (Line 6)
> Error: Parameter 'options' implicitly has 'any' type. (Line 6)
> Error: Parameter 'id' implicitly has 'any' type. (Line 6)

**Expected behavior:**

The compiler should correctly detect the types of `id`, `text`, and `options` parameters.

**Actual behavior:** 

The compiler is unable to detect the types of  `id`, `text`, and `options` parameters, and resorts to implicit `any` for all of them.

**Comment by RyanCavanaugh** [comment]
Why is `MethodCollection` generic? It doesn't do anything with `T`. You should just write `options: {}` or `options: any` and this will work as expected.

**Comment by RyanCavanaugh** [comment]
More specifically, what type do you *expect* `options` to have in this line?

```ts
var myMethods: MethodCollection = {
    methodA: (id, text, options) => {
        // id: number
        // text: string
        // options: ???
    }
}
```

**Comment by JohnWhiteTB** [comment]
This is a significantly dumbed down example, obviously it wouldn't have much use in its present form.

**Comment by RyanCavanaugh** [comment]
This is behaving according to spec. When a signature is generic, we don't use it to contextually type the function expression, because doing so would cause a naked type parameter to leak out. In other words, we don't assign types to `(id, text, options)` because there's not a type we can give to `options`.

**Comment by JohnWhiteTB** [comment]
Also, if I strip parameter `options` from the function signature, the problem still persists. And it's not an issue of not being able to infer generic types - all type detection seems to disable when I add a type parameter.

Please consider the below snippet, in which the issue still persists:

    interface MethodCollection {
        [methodName: string]: <T>(id: number, text: string) => void;
    }

    var myMethods: MethodCollection = {
        methodA: (id, text) => {
            // id: any
            // text: any
        }
    }

I understand there is currently zero use for the type parameter `T` in this example, but please remember that this is a significantly dumbed down snippet, the minimum required to reproduce the problem.

**Comment by RyanCavanaugh** [comment]
Correct. We don't go looking to see if you *use* the type parameter or not -- *any* generic signature is not used for contextual typing. The nonsense case where you have a type parameter but don't use it isn't worth the extra cycles to support.

**Comment by JohnWhiteTB** [comment]
I see this is an intentional limitation. I made a workaround to my problem, the code was a bit hackish anyways. I greatly appreciate your time and help.
