### ISSUE TITLE
QuickInfo classification of symbol kinds does not account for overlapping categories

### ISSUE THREAD

**Issue by JsonFreeman** [Microsoft/TypeScript#740]
The function displayPartKind in the checker does not account for things like a function merging with a module. It always classifies such entities as functions because Function is given higher priority than Module. The correct thing to do here is to pass the intended meaning based on the syntactic position of the quick info request, and base the kind hierarchy on that.

**Comment by mhegazy** [comment]
I do not think this is applicable any longer.
