### ISSUE TITLE
Bluebird Promise.join and typescript

### ISSUE THREAD

**Issue by dmiorandi** [Microsoft/TypeScript#7401]
**TypeScript Version:** 
v1.8.0 and also v1.9.0-dev.20160305

**Code**

```ts
 getList(filter):Promise<IModelResponse> {
      return Promise.join<IModelResponse>(
          this.client.resources.companies.registry.get(),
          this.client.resources.companies.get(super.cleanEntityFilter(filter)),
          (registry:popsicle.Response,  entity:popsicle.Response) =>{
            return <IModelResponse> { registry:registry, entity:entity };
          }
        );
    }

///from d.ts...
join<T>(...values: PromiseLike<T>[]): Promise<T[]>;
join<T>(...values: T[]): Promise<T[]>;


///and the interface is just 
export interface IModelResponse {
    registry: popsicle.Response;
    entity: popsicle.Response;
}

```

**Expected behavior:**
not typed code compile and works. I've just added some typings and it doesn't compile. I want to know how to compile it. At lest the error seems to be wrong. It have no sense to me. I suppose it can't convert
IModelResponse into popsicle.Response[] maybe?

**Actual behavior:** 
error TS2345: Argument of type '(registry: Response, entity: Response) => IModelResponse' is not assignable to parameter of type 'IModelResponse'.
  Property 'registry' is missing in type '(registry: Response, entity: Response) => IModelResponse'.

Typescript

**Comment by RyanCavanaugh** [comment]
Looks like this
```ts
///from d.ts...
join<T>(...values: PromiseLike<T>[]): Promise<T[]>;
join<T>(...values: T[]): Promise<T[]>;
```
should be this:
```ts
join<T>(...values: Array<T | PromiseLike<T>>): Promise<T[]>;
```

**Comment by dmiorandi** [comment]
I think in my case the second join is used. I'm going to try something like this, probably a modified d.ts like you propose could solve. I need to try it more to give you a more detailed informations.

Anyway I suspect the error message returned from compiler is wrong. Probably it should be 
something like:


error TS2345: Argument of type '(registry: Response, entity: Response) => IModelResponse' is not assignable to parameter of type **'any[]'.**

**Comment by mhegazy** [comment]
Does not look like a compiler issue. closing.
