### ISSUE TITLE
Improve readability of default exports

### ISSUE THREAD

**Issue by onreachable** [Microsoft/TypeScript#7407]
I'm unable to `export default` modules/namespaces like this:
```ts
export default namespace Utils { // throws  error TS1005: ';' expected
...
```

Not sure if its related to #3792, but that isn't actually my issue...
Since I can't `export default` the namespace directly, I would like to convention that default exports should be placed in a separate statement and always put in the first lines of the file:
```ts
export default Utils

import * as Foo from "foo"
// ...
import {Bar, Baz} from "bar"

let fooIt = Foo.Factory.SpecialFoo.Create
// ...

namespace Utils {
  // ...
}
```

IMO it would improve readability and make it easier to understand how to consume that file/module.

Despite the fact that the compiler seems to understand that I'm exporting the `Utils` namespace, the transpiled code does not associate the export statement and my internal module, [causing the default export to be undefined at run time](http://www.typescriptlang.org/Playground#src=%2F%2F%20'var%20Utils'%20could%20be%20transpiled%20over%20here%0Aexport%20default%20Utils%20%0A%0Anamespace%20Utils%20%7B%0A%20%20export%20function%20test()%20%7B%0A%09%20%20console.log('TEST')%0A%20%20%7D%0A%7D).

Would be nice to get `export default` transpiled to the of the file or declare the module container earlier, so I can export it wherever I want. 

If #3792 gets fixed I can just convention that the default module should always come first, and keep my default export always on sight. So this is issue is more like a suggestion I suppose...

<sub>Typescript Version 1.9.0-dev.20160220</sub>

**Comment by RyanCavanaugh** [comment]
> Would be nice to get export default transpiled to the of the file 

I'm not 100% clear on what's being reported. I've added `export default namespace Utils {` to #3792; is there another bug here assuming that one gets fixed?

**Comment by onreachable** [comment]
@RyanCavanaugh More an improvement than a bug fix, please disregard my request unless is it any good (yes).

For example, the compiler allows me to reference **Foo** on `export default Foo` and declare it afterwards, which is [nice](http://i.imgur.com/FVam8ER.jpg?1)!

However the transpiled code uses **Foo** before `var Foo;` is declared as [**shown here**](http://www.typescriptlang.org/Playground#src=%2F%2F%20'var%20Utils'%20could%20be%20transpiled%20over%20here%0Aexport%20default%20Utils%20%0A%0Anamespace%20Utils%20%7B%0A%20%20export%20function%20test()%20%7B%0A%09%20%20console.log('TEST')%0A%20%20%7D%0A%7D)

What I'm asking is, since the compiler is already capable of recognizing **Foo** ahead of time, it should also declare `var Foo;` accordingly. This would be

**Comment by mhegazy** [comment]
this looks like a duplicate of #4101

**Comment by onreachable** [comment]
Indeed @mhegazy, thank you!
