### ISSUE TITLE
Language Service not following symlinks or hard links

### ISSUE THREAD

**Issue by paul-go** [Microsoft/TypeScript#7412]
`tsc` seems to have no issue following symlinks and hard links, but the Language Service does not appear to be following them, because I'm getting underlines in VS Code / Sublime, but compilation still works. I would expect the two systems to have the same behavior. Hardlinks on OS X are a bit of an esoteric hack, but I would at least expect symlinks to work.

Using:
OS X
TypeScript: 1.9.0-dev.20160226
Hardlink creator tool for OS X: https://github.com/selkhateeb/hardlink

**Comment by mhegazy** [comment]
@zhengbli  can you take a look.

**Comment by paul-go** [comment]
Sorry about this ... it seems to be happening intermittently now, I can't reliable reproduce it.

**Comment by zhengbli** [comment]
@paul-go Does the underlines still exist if you close and reopen your editor? It could be that the language service was lagging somehow.

**Comment by mhegazy** [comment]
@paul-go is this still an issue? can you share more information?

**Comment by paul-go** [comment]
I'm now not actually not sure if this is a Visual Studio Code problem, or a TS language service problem. It seems that folders that I've symlinked in aren't found in the VS code Cmd+P list. I'll close this issue for now and reopen (possibly under the VS code repo) if I figure out what's going on.
