### ISSUE TITLE
anonymous classes lose type information

### ISSUE THREAD

**Issue by kenhahn85** [Microsoft/TypeScript#7413]
**TypeScript Version:** 

nightly (1.9.0-dev.20160217)

**Code**

```ts
abstract class TestCaseClass extends CaseClass {
  static A = <typeof CaseClass> class extends TestCaseClass {
    v: number;
    constructor(v: number) {
      super();
      this.v = v;
    }
  };
  static B = <typeof CaseClass> class extends TestCaseClass {
    v: string;
    constructor(v: string) {
      super();
      this.v = v;
    }
  };
}
```

**Expected behavior:**
I expect this to compile.

**Actual behavior:** 
`\u001b[39merror TS2352: Neither type \'typeof (Anonymous class)\' nor type \'typeof CaseClass\' is assignable to the other.' }`

**Comment by falsandtru** [comment]
no problem on the latest.

```ts
class CaseClass {
	constructor(v: number | string) {}
}
abstract class TestCaseClass extends CaseClass {
  static A = <typeof CaseClass> class extends TestCaseClass {
    v: number;
    constructor(v: number) {
      super(v);
      this.v = v;
    }
  };
  static B = <typeof CaseClass> class extends TestCaseClass {
    v: string;
    constructor(v: string) {
      super(v);
      this.v = v;
    }
  };
}
```

**Comment by RyanCavanaugh** [comment]
I'm assuming @falsandtru's repro is a correct fill-in for what you meant, which indeed compiles without error in master.

If that's not the case please log a new issue with a self-contained repro.

**Comment by kenhahn85** [comment]
Thanks. It turns out that the real issue was that the parent constructor did not accept any parameters. The compiler error message misled me.
