### ISSUE TITLE
Augmentet methods not available in Visual Studio intellisense unless something is exported from the augmentation module

### ISSUE THREAD

**Issue by MortenHoustonLudvigsen** [Microsoft/TypeScript#7415]
I have a class called Webpack, which I augment to add a new method `addLess` like so:

```typescript
// addLess.ts
import { Webpack } from '../webpack';

declare module '../webpack' {
    interface Webpack {
        addLess(): Webpack;
    }
}

const lessConfiguration = {
    module: {
        loaders: [
            { test: /\.less$/, loader: "style!css!less" }
        ]
    }
};

class Implementation extends Webpack {
    addLess(): Webpack {
        return this.mergeModule('less', lessConfiguration);
    }
}

Webpack.prototype.addLess = Implementation.prototype.addLess;
```

This works great in the current typescript project, but if I compile (with declarations), and try to use the compiled project in another project, the new method is not shown in intellisense in Visual Studio, and it is shown as an error if I try to use it anyway.
However, if I make sure something is exported from the module above it works as expected. For example, I can work around the issue by exporting the class `Implementation` like so:

```typescript
// addLess.ts
import { Webpack } from '../webpack';

declare module '../webpack' {
    interface Webpack {
        addLess(): Webpack;
    }
}

const lessConfiguration = {
    module: {
        loaders: [
            { test: /\.less$/, loader: "style!css!less" }
        ]
    }
};

export class Implementation extends Webpack {
    addLess(): Webpack {
        return this.mergeModule('less', lessConfiguration);
    }
}

Webpack.prototype.addLess = Implementation.prototype.addLess;
```

However, this means that I am exporting something, that should be private to the module.

This issue is only in Visual Studio. When compiling with `gulp-typescript` using typescript 1.8.2, 1.8.5, 1.8.6 or 1.8.7 I get no errors - with or without the extra export.

I am using Visual Studio 2015 update 1 with the extension for Typescript 1.8.4.

**Comment by vladima** [comment]
Can you please elaborate, when your say ` if I compile (with declarations), and try to use the compiled project in another project` - do you use `.d.ts` file from the compiled project in another project?

**Comment by MortenHoustonLudvigsen** [comment]
Sorry if I wasn't entirely clear.

The first project (`project1`) contains the following files (after compiling to the `lib` directory):

````
|-- package.json
|
|-- src
|   |-- index.ts
|   |-- webpack.ts
|   \-- webpack
|       \-- addLess.ts
|	
\-- lib	
    |-- index.js
    |-- index.d.ts
    |-- webpack.js
    |-- webpack.d.ts
    \-- webpack
        |-- addLess.js
        \-- addLess.d.ts
````

In `package.json` main and typings point to the compiled version of `src/index.ts`:

````json
...
"main": "lib/index.js",
"typings": "lib/index",
...
````

`src/index.ts` exports class `Webpack` from `src/webpack.ts`:

````typescript
export { Webpack } from './webpack';
````

`src/webpack.ts` defines class `Webpack` (which is the class that is augmented in `src/webpack/addLess.ts`):

````typescript
export class Webpack {
   ...
}
````

The second project has a symbolic link to the first project in the `node_modules` directory of the second project, and references `addLess.d.ts` using node module resolution.

````typescript
import { Webpack } from 'project1';
import 'project1/lib/webpack/addLess';

let webpack = new WebPack();

// This line is shown as an error in Visual Studio if the class 'Implementation'
// in src/webpack/addLess.ts is not exported:
webpack.addLess();
````

I hope this makes it clearer. :smile:

**Comment by vladima** [comment]
can you please paste the content of `addLess.d.ts` if it does not contain anything sensitive ?

**Comment by MortenHoustonLudvigsen** [comment]
If there was anything sensitive, it's a bit late now :smile: 

`addLess.d.ts` _without_ export of class `Implementation`:

````typescript
declare module '../webpack' {
    interface Webpack {
        addLess(): Webpack;
    }
}
export {};
````

`addLess.d.ts` _with_ export of class `Implementation`:

````typescript
import { Webpack } from '../webpack';
declare module '../webpack' {
    interface Webpack {
        addLess(): Webpack;
    }
}
export declare class Implementation extends Webpack {
    addLess(): Webpack;
}
````

**Comment by david-driscoll** [comment]
I'm seeing a similar issue, everything works correctly with `atom-typescript` or `vscode` but if I switch to `VS2013` or `VS2015` I get the following errors.

![image](https://cloud.githubusercontent.com/assets/1269157/13731427/b25a2f32-e93e-11e5-80f9-094fbd87f4ac.png)

I've got a copy made zip copy available below, it's simply a clone of https://github.com/johnpapa/angular2-go with no extra work done to it.

[Asap2.Web.zip](https://files.zenhub.io/56e5d7f37fb5c739428e954e)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)

**Comment by vladima** [comment]
I can repro this - issue is that our VS specific preprocessing logic does not include module augmentations in the list of module names in file.

**Comment by david-driscoll** [comment]
Cool, thanks for the update (on a sunday no less! :scream: )

Any idea if there will be a tooling release to fix it before 2.0 drops? :pray: (You may not be in the position to say yes or no :smile: )

**Comment by vladima** [comment]
I'm fairly certain that we can fix it entirely on the script side which means that after fix it checked in you can grab and use `typescriptServices.js` from the nightly build.

**Comment by david-driscoll** [comment]
@vladima @mhegazy FYI running `master` in dev mode appears broken with VS2015 Update 2 at the moment.   Any idea when `release-1.8` will be merged back into master?

**Comment by mhegazy** [comment]
sorry for the late reply. i suspect it was fixed by https://github.com/Microsoft/TypeScript/pull/8149. if not let us know what you are seeing.
