### ISSUE TITLE
Add keyword for the typed constructor of this

### ISSUE THREAD

**Issue by trkjgrdg** [Microsoft/TypeScript#7418]
Consider the following classes:

    class Animal {
        static verb = "moved";
        move() { alert("Animal " + Animal.verb); }
    }

    class Snake extends Animal {
        static verb = "slithered"; 
    }

    (new Snake()).move();

The above prints "Animal moved" because we hardcoded `Animal.name` in `move`.  To make subclasses work properly, we should instead define `move` as:

    move() { alert("Animal " + (<typeof Animal>this.constructor).verb); }

But using `(<typeof Animal>this.constructor).verb` everywhere is very verbose.  It would be nice if there were a keyword (e.g. reuse `class`) that stood for `<typeof Animal>this.constructor`, so we could write just `class.verb`.

**Comment by trkjgrdg** [comment]
Related stackoverflow questions:
http://stackoverflow.com/questions/33387318/access-to-static-properties-via-this-constructor-in-typescript
http://stackoverflow.com/questions/29244119/how-to-access-static-members-from-instance-methods-in-typescript
http://stackoverflow.com/questions/34502195/using-static-property-in-inherited-class-method

**Comment by RyanCavanaugh** [comment]
See #3841/ #4356.
