### ISSUE TITLE
TypeScript treating imported namespace as variable with the same name

### ISSUE THREAD

**Issue by DavidKDeutsch** [Microsoft/TypeScript#7419]
This _may_ be a duplicate of #7368, but since that bug involves (external) modules and this one just involves namespaces (or internal modules), I figured I would report it. 

Given a namespace `X`, if you have `import Y = X` and also declare a variable `X`, TypeScript thinks that `Y` is the variable `X`. For example, my angular.d.ts has:

```ts
declare var angular: angular.IAngularStatic;
import ng = angular;
declare namespace angular {
...
```

Now when I call a member of IAngularStatic on `ng`, I get no compile error, e.g.

```ts
let copy = ng.copy(item);
```

compiles fine, but of course I get an error at runtime because `ng` does not exist.

This is with TypeScript 1.8

**Comment by RyanCavanaugh** [comment]
This is working as intended. The line `import ng = angular` emits the code `var ng = angular`, so unless `angular` isn't defined (in which case it's not valid to have `declare var angular`), everything should just work.

**Comment by DavidKDeutsch** [comment]
Hi @RyanCavanaugh,
 
 I'm not sure I understand; as far as I know, no code is emitted when compiling a `.d.ts` file, which is where the `import` statement is.

**Comment by RyanCavanaugh** [comment]
Ah, yes. In this case the angular.d.ts file is incorrect -- it shouldn't write that if there isn't an `ng` variable present at runtime
