### ISSUE TITLE
File watcher not working on network file system

### ISSUE THREAD

**Issue by zhengbli** [Microsoft/TypeScript#7420]
Currently the file watcher cannot work properly on network file systems, or file systems that doesn't support the underlying change notification mechanism that node's `fs.watch` relies on. This could lead to the language service crashing (#6726). 

The alternative solution is to consider third party file watcher libraries. As suggested by Daniel (https://github.com/Microsoft/TypeScript/issues/7376#issuecomment-193072296), [Watchman](https://facebook.github.io/watchman/) or similar product can be used for the purpose. It may worth some research.

**Comment by DanielRosenwasser** [comment]
For the record, there's a few things we should note about Watchman as a solution. From their [Installation](https://facebook.github.io/watchman/docs/install.html) page:

> Watchman relies on the operating system facilities for file notification,
which means that you will likely have very poor results using it on any
kind of remote or distributed filesystem.

Which sounds to me like you'll have sub-optimal results, but at least it won't crash. :smile: 

Additionally, their Windows support is in alpha stages (see https://github.com/facebook/watchman/issues/19).

**Comment by zhengbli** [comment]
Actually the "operating system facilities for file notification" is the very thing that is lacking here, so that may be an issue too. 
I wonder what VSCode uses for their own file watching, which may have considered this case already.

**Comment by zhengbli** [comment]
So I was trying to use a simple try/ catch to detect if `fs.watch` is available for the file, and if so use `fs.watch`, if not use time-stamp comparison. However, turns out sometimes node would simply crash (instead of throwing exceptions) why try to call `fs.watch` on a UNC path. Therefore this solution wouldn't work, and the support for network file system would be a non-trivial work item.

**Comment by wez** [comment]
You probably want to track this open item for watchman: https://github.com/facebook/watchman/issues/201 if you're interested in better support for network shares.

**Comment by DanielRosenwasser** [comment]
@wez thanks for the heads up!

**Comment by mhegazy** [comment]
@zhengbli should this be closed now after #8196?

**Comment by zhengbli** [comment]
Yes I think so.
