### ISSUE TITLE
Module augmentations being applied when their containing modules are not imported

### ISSUE THREAD

**Issue by masaeedu** [Microsoft/TypeScript#7427]
**TypeScript Version:** 

1.8.7 / nightly (1.9.0-dev.20160217)

**Code**

Consider the following three files:

a.ts
```ts
export class A { }
```

foo.ts

```ts
import {A} from './a';

declare module './a' {
    interface A {
        foo(): number;
    }
}

A.prototype.foo = () => 42;
```

main.ts

```ts
import {A} from './a';
// import './foo';

var a = new A();
console.log(a.foo()); // Shouldn't the second import be necessary in order for this code to compile?
```

**Expected behavior:**
The `foo` member should not be suggested in autocomplete, and main.ts should not compile. That should only happen if `foo` is imported (i.e. the second import is uncommented). 

**Actual behavior:** 
The code compiles, but will fail at runtime with:

> TypeError: a.foo is not a function

**Additional info:**
I think this was working correctly as of early Feb, so this might be a regression introduced by something else.

**Comment by RyanCavanaugh** [comment]
How are you compiling this? It looks like you're running with a tsconfig.json with no files list, which means the compiler picks up all .ts files in the current directory.

**Comment by masaeedu** [comment]
@RyanCavanaugh I have all three files in my tsconfig.json files list. Do I need to exclude `foo.ts`?

**Comment by RyanCavanaugh** [comment]
Right, the compiler basically assumes that someone somewhere is going to import `foo` and cause its global side effects to occur (otherwise why would it be in the compilation in the first place).
