### ISSUE TITLE
IntelliSense with types of JSDoc

### ISSUE THREAD

**Issue by egamma** [Microsoft/TypeScript#7428]
_From @anseki on March 8, 2016 4:25_

I tried this:

``` js

/**
 * @param {string} param1 - Normal
 * @param {string|number|boolean} param2 - Multiple types
 * @param {null} param3 - (I know this is strange param.)
 * @param {string|number|null} param4 - Multiple types includes `null`
 * @param {Object} param5 - Object type
 * @param {Array} param6 - Array type
 * @param {jQuery} param7 - Another type
 * @param {MyClass} param8 - Another type
 * @param {string|number|Array} param9 - Multiple types includes `Array`
 * @param {?string} param10 - Nullable type
 * @param {string} [param11] - Optional
 * @returns {?string} result
 */
function fnc(param1, param2, param3, param4, param5, param6,
    param7, param8, param9, param10, param11) {
  return param11;
}

fnc();
```
- param3: any, param4: any, param6: any, param7: any, param8: any, param9: any
- param10: string

It seems that:
- The type of `@param` that includes `null`, `Array`, and other classes other than `Object` are shown as `any`.
- The optional params are shown with `?`, but nullable params and returns are shown with nothing.

I hope that the specified types are shown even if that is `null`, `Array`, or unknown type such as `jQuery` or `MyClass`. And nullable params are shown like optional params.

_Copied from original issue: Microsoft/vscode#3802_

**Comment by egamma** [comment]
moving to TypeScript

**Comment by RyanCavanaugh** [comment]
As for nullability, this is by design. Nullable parameters aren't the same as optional, and `T | null` won't be valid syntax until nullable types become available in TypeScript.

For `Array` we need to special-case this (we expected to see `Array<T>`)

**Comment by DanielRosenwasser** [comment]
@RyanCavanaugh I think the special case should be general enough for all generic types - perhaps instantiating with with `any` for all type arguments.

**Comment by Thaina** [comment]
I too think `null` is not type. It is value. You need to set type as {boolean | number} not {true | number}. Same go for `null`, you could set it as string or any

As for nullable it is `{?any}`

For `{Array}` is should be just like `{[]}`

**Comment by anseki** [comment]
Yes I know `null` or `undefined` are value.
But some style guide such as [Google JavaScript Style Guide](http://google.github.io/styleguide/javascriptguide.xml?showone=Comments#tag-param) specifies `null` in JSDoc to indicate the param that might be multiple type and `null`.
If the param accepts something type and `null`, it can be `{?somethingType}`. But if it accepts more types and `null`, no notation for "multiple  && nullable".

**Comment by anseki** [comment]
Sorry, I don't understand the mechanism of IntelliSense. Is showing specified text as type difficult? even if that is unknown type such as `jQuery` or DOM element or `MyClass`.

**Comment by anseki** [comment]
I think that this issue is solved if IntelliSense parses `@typedef` or `@class`. Those tags might be able to deceive IntelliSense. (It make also a source code dirty.)
Or, as I said, it is solved if IntelliSense shows specified text as type.

I think that `null` is needed by current version of JSDoc to indicate an optional param that is not positioned at the end of params list because It don't have syntax to indicate that now. http://usejsdoc.org/tags-type.html
Then, some style guides such as Google specify `null`.
Also, types such as `Array`, `jQuery` or `MyClass` are typically used in JS.
Those should be shown. Because JSDoc is used for documentation or some guide, JSDoc is not a tool to check syntax like debugger.
We don't want to write `@class` and something for `jQuery` in to all source code.

**Comment by mhegazy** [comment]
With nullable types in, we should add logic to handle `?T` and `!T`.

**Comment by Kovensky** [comment]
`null` and `undefined` are now supported when `"strictNullChecks": true` is enabled in the `jsconfig.json`. jsdoc nullable syntax isn't, though.

**Comment by epicgirl1998** [comment]
i hope i'm in the right place

is there no support for typing callbacks this way or am i doing it all wrong?

![fun1](https://cloud.githubusercontent.com/assets/25940153/23550761/50c4e150-001b-11e7-9619-595ee45697bc.png)
![fun2](https://cloud.githubusercontent.com/assets/25940153/23550760/50c36f00-001b-11e7-8485-2b0433abd989.png)

i'm using the latest version of vs code

**Comment by Kovensky** [comment]
You can, but at least for simple cases (no union types, not inside another type) you have to use closure compiler syntax. Something like `{function(string, string): void}` (note: no parameter names possible)

**Comment by mhegazy** [comment]
These should be working now as described in the OP.
