### ISSUE TITLE
Javascript Parameters with properties and dotted names

### ISSUE THREAD

**Issue by egamma** [Microsoft/TypeScript#7429]
_From @Beng89 on March 8, 2016 2:39_

Currently intellisense does not detect parameter properties see [http://usejsdoc.org/tags-param.html](http://usejsdoc.org/tags-param.html) for details.

![not-working](https://cloud.githubusercontent.com/assets/5748243/13590266/014821a2-e4a4-11e5-9d75-d75d00b6b639.PNG)

Is this something that support will be added for?

_Copied from original issue: Microsoft/vscode#3798_

**Comment by egamma** [comment]
This is a valide feature request, moving to TypeScript.

**Comment by mhegazy** [comment]
Seems working in latest.
