### ISSUE TITLE
Error TS17009 (must call super() first in ES6) issued for ES5 target

### ISSUE THREAD

**Issue by markboyall** [Microsoft/TypeScript#7431]
The motivation for this breaking change talks about the ES6 spec. However, we are only targetting ES5 as we have a bunch of legacy code which it would be risky to change. Now we're stuck on TS 1.7 because TS 1.8 breaks our code to conform to a spec it's not even targetting.

This error should not be issued when the compiler is targetting ES5 or below.

**Comment by mhegazy** [comment]
The main reason here, is that the super object is not completely "formed" until the `super` call is completed. any changes to the object before that might be overridden unexpectedly. consider this:

```ts
class Base {
    constructor(public name: string) { }
}

class Derived extends Base {
    constructor(name: string) {
		this.name = "something"; // this is going to be overwritten by the supper call
		super(name); 
	}
}
```

If your `super` constructor is making any decisions based on some values set on the `this` object, i would argue that it should be a constructor argument instead. 

As for ES6, the aim is to make your code 1. compatible with ES6 code, and 2. easily migrate-able to ES6 when you are ready to make the switch.

**Comment by markboyall** [comment]
It doesn't make any decisions or even read the values- they're private to the deriving class and completely unobservable to the base class. That's what makes the break so inconvenient- there's no funny stuff going on and the assignment completely works as expected.

**Comment by mhegazy** [comment]
if they are private to the class, and do not change the logic in the super constructor, so what is the harm in moving it after the super call?

**Comment by markboyall** [comment]
I have misspoken. That's simply the annoying case. The breaking case is when the super is written in legacy Javascript where nobody knows what it does, so moving the property accesses to after the super call is risky.

**Comment by mhegazy** [comment]
it is not clear that the original code was doing the correct thing either. it is possible that the legacy constructor was overwriting your value from the start any ways.

**Comment by markboyall** [comment]
It's possible, but also immaterial, since if that's what it's doing, it's my full intention to leave it doing that. And if the super constructor does something super dodgy about reading properties from the derived class, I intend to leave it doing that too. 

The problem is supporting my legacy Javascript written a decade ago whilst upgrading Typescript for use in newer areas. It's all very well to be compatible with ES6, but now I'm not compatible with ES5, since ES5 JS can express more than ES6-compatible TS can do.

Ultimately, the problem is that you have one set of source semantics for two different lowerings, which have different requirements. No matter what you do, one of them won't be correct. You need to have different source semantics for different lowerings.

**Comment by mhegazy** [comment]
I am arguing that the ES6 conformance is not the only reason. the code is *possibly* wrong. which is similar to a lot of other cases that TS flags as errors today. e.g. redefining a variable with different types. you can argue that it works, and that it is legacy, but it is still flagged. TS tried to keep the semantics common across targets, unless it is not possible because of runtime limitations.

**Comment by jeffreymorlan** [comment]
How did this "legacy code" from 10 years ago that everyone's afraid to touch become a TypeScript class in the first place?

**Comment by mpetkov** [comment]
Can this check be turned off from tsconfig.json?
