### ISSUE TITLE
Bug: emit of shorthand property is wrong with non-ES6 ModuleKind

### ISSUE THREAD

**Issue by Victorystick** [Microsoft/TypeScript#7434]
**TypeScript Version:** 
1.8.7 / nightly (1.9.0-dev.20160217)

I believe there is a logical error in `emitShorthandPropertyAssignment` in `emitter.ts`. When determining whether to emit a `: name` after a shorthand property, the code checks what the current `ModuleKind` is rather than what `ScriptTarget` we have.

I believe the following change is required

```diff
// A self-contained demonstration of the problem follows...
function emitShorthandPropertyAssignment(node: ShorthandPropertyAssignment) {
    // The name property of a short-hand property assignment is considered an expression position, so here
    // we manually emit the identifier to avoid rewriting.
    writeTextOfNode(currentText, node.name);
    // If emitting pre-ES6 code, or if the name requires rewriting when resolved as an expression identifier,
    // we emit a normal property assignment. For example:
    //   module m {
    //       export let y;
    //   }
    //   module m {
    //       let obj = { y };
    //   }
    // Here we need to emit obj = { y : m.y } regardless of the output target.
-    if (modulekind !== ModuleKind.ES6 || isNamespaceExportReference(node.name)) {
+    if (languageVersion < ScriptTarget.ES6 || isNamespaceExportReference(node.name)) {
        // Emit identifier as an identifier
        write(": ");
        emit(node.name);
    }

    if (languageVersion >= ScriptTarget.ES6 && node.objectAssignmentInitializer) {
        write(" = ");
        emit(node.objectAssignmentInitializer);
    }
}
```

For example, when transpiling this with `tsc --module commonjs --target es6`
```ts
export const foo = { a, b };
```

**Expected behavior:**
```js
"use strict";
exports.foo = { a, b };
```

**Actual behavior:** 
```js
"use strict";
exports.foo = { a: a, b: b };
```

The same example with `tsc --module amd --target es6`
**Expected behavior:**
```js
define(["require", "exports"], function (require, exports) {
    "use strict";
    exports.foo = { a, b };
});
```

**Actual behavior:** 
```js
define(["require", "exports"], function (require, exports) {
    "use strict";
    exports.foo = { a: a, b: b };
});
```

Specifically, I'm encountering this issue when using `transpileModule` with `ModuleKind.ES6` and `SourceTarget.ES5`. The suggested change should address both use-cases.

**Expected behavior:**
```js
export var foo = { a: a, b: b };
```

**Actual behavior:** 
```js
export var foo = { a, b };
```

**Comment by Victorystick** [comment]
I've tried to implement the changes, but I haven't been able to update the baseline tests successfully. I don't get any clear indication of why they're failing, nor can I try using `transpileModule` manually to verify that it works.

```
Debug Failure. False expression: Output generation failed
Error: Debug Failure. False expression: Output generation failed
    at Object.assert (/Users/oskar/github/typescript/built/local/typescript.js:1612:23)
    at Object.transpileModule (/Users/oskar/github/typescript/built/local/typescript.js:45683:18)
    ...
```

I'll extend the necessary changes to this:
```diff
-    if (modulekind !== ModuleKind.ES6 || isNamespaceExportReference(node.name)) {
+    if (languageVersion < ScriptTarget.ES6 || (modulekind === ModuleKind.ES6 && isNamespaceExportReference(node.name))) {
```

We ought to verify that `modulekind` is ES6 before checking whether the name is a namespace export reference.

**Comment by mhegazy** [comment]
i do not see the same error. making the change and running all tests for me produce one change in baselines in `tests/baselines/reference/shorthandPropertyAssignmentInES6Module.js` which is actually the correct output. how can i get the error you are seeing?

**Comment by Victorystick** [comment]
@mhegazy Sorry about the confusing comment. I encountered the `Debug Failure` when I tried to use the locally generated `typescript.js` programatically. But never mind that.

Yes, I get the same error as you do. The baseline fails. I'd submit a PR for this myself, but I just don't know how to update/add new tests for this.

**Comment by mhegazy** [comment]
thanks @Victorystick!
