### ISSUE TITLE
Proposal: Pass SourceFile being emitted to Program.emit's callback

### ISSUE THREAD

**Issue by chuckjaz** [Microsoft/TypeScript#7438]
I propose including the SourceFile being emitted in the emit callback. 

**TypeScript Version:** 

1.7.5 / 1.8.0-beta / nightly (1.9.0-dev.20160217)

**Code**

```ts
import * as ts from 'typescript';
import * as fs from 'fs';
import * as fse from 'fse';

const fileName = 'index.ts';
const fileNames = [fileName];

class LocalHost implements ts.LanguageServiceHost {
  getCompilationSettings(): ts.CompilerOptions {
    return {
      experimentalDecorators: true,
      modules:  ts.ModuleKind.CommonJS,
      target: ts.ScriptTarget.ES5
    };
  }
  
  getProjectVersion(): string { return "1";}
  getScriptFileNames(): string[] { return fileNames; }
  getScriptVersion(fileName: string): string { return "1"; }
  getCurrentDirectory(): string { return dir; }
  
  getScriptSnapshot(fileName: string): ts.IScriptSnapshot {
    const filteredName = nameFilter(fileName);
    if (fs.existsSync(filteredName))
      return ts.ScriptSnapshot.fromString(fs.readFileSync(filteredName, 'utf8'));
  }
  
  getDefaultLibFileName(options: ts.CompilerOptions): string {
    return './node_modules/typescript/lib/lib.es7.d.ts';  
  }
}

const host = new LocalHost();
const ls = ts.createLanguageService(host);
const program = ls.getProgram();

const emitResult = program.emit(undefined, (absoluteFilePath, fileContent, sourceFile) => {
    console.log('emitting', absoluteFilePath, 'for', sourceFile.fileName);
    fse.mkdirsSync(path.dirname(absoluteFilePath));
    fs.writeFileSync(absoluteFilePath, this.fixSourceMapSources(fileContent), { encoding: 'utf-8' });
});
```

**Expected behavior:**
If this proposal is taken then the `sourceFile` parameter above will contain the `SourceFile` instance emit currently emitting the file `absoluteFilePath` on behalf of.

**Justification:**
`.d.ts` files do not contain information about the decorators used in the `.ts` files, nor can it. However, these decorators often contain valuable information that other processors might need, such as, in our case, the Angular 2 offline compiler and the Angular 2 language service. To preserve this information we emit a `.metadata.json` file for each `.d.ts` file emitted if the corresponding module contains classes with decorators.

We use `program.emit()` in our build process and use the callback to trigger the emit of the `.metadata.json` file but we must make an educated guess as to which `SourceFile` the `.d.ts` file is being emitted for. It would be more straight forward for the `SourceFile` to passed into the callback to `emit`.

**Comment by mhegazy** [comment]
if you have --out, there is not a single `SourceFile` to pass. If you are not using `--out`/`--outFile` consider calling emit on each file at a time*, i.e.:

```ts
program.getSourceFiles().forEach(f => {
   program.emit(f, ...);
});
```

`*` if you end up following this approach, i would not `--noEmitOnError`, as that will add some unnecessary overhead.

**Comment by chuckjaz** [comment]
I tried that first but am seeing a huge difference in performance between calling `program.emit(undefined, ...)` and `program.getSourceFiles().forEach(f => program.emit(f, ...))`. In my case the first takes consistently around 6 seconds and the second takes 40 seconds.

As for `--out/--outFile` it seems reasonable to pass `null` or `undefined` in this case.

**Comment by mhegazy** [comment]
> I tried that first but am seeing a huge difference in performance between calling

i think this is because you have `--noEmitOnError` along with `--declaration`. The declaration diagnostics are not cached. We could cache them.

**Comment by chuckjaz** [comment]
Caching would be useful but it seems innocuous and useful to pass the `SourceFile` into the callback. This means it would work and perform well without having to rely on caching. Is there a technical reason I am missing that prevents this?

**Comment by mhegazy** [comment]
i do not think there is a specific reason. my main concern was consistency with the --out case.

**Comment by chuckjaz** [comment]
Do you me to create a pull request?

**Comment by mhegazy** [comment]
sure.

**Comment by alexeagle** [comment]
When the declaration file is emitted, the sourceFiles are not present. This breaks our primary purpose in adding this feature, which is to write an extra file next to the .d.ts outputs.
cc @chuckjaz

**Comment by mhegazy** [comment]
Thanks @alexeagle!
