### ISSUE TITLE
Typescript overriding accessors not understood

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#7443]
_From @JonathanMEdwards on March 8, 2016 15:7_

```
class Foo {
  x: any;
  get y(): any { return undefined; }
}
class Bar extends Foo {
  x: number;
  get y(): number { return undefined; }
}
```

The two variables named x are related: Shift-F12 will find them both, and renaming one will rename the other. But the two getters named y are treated as distinct: Shift-F12 won't show both, and renaming one doesn't rename the other

_Copied from original issue: Microsoft/vscode#3856_

**Comment by mhegazy** [comment]
should be fixed in latest.
