### ISSUE TITLE
noImplicitReturns disallows empty return statement in an async function that does not explicitly return Promise<void>

### ISSUE THREAD

**Issue by FranklinWhale** [Microsoft/TypeScript#7446]
**TypeScript Version:** 
1.8.5 /1.8.7

**Code**
```ts
async function test(isError: boolean = false) {
	if (isError === true) {
		return;
	}
	console.log(await Promise.resolve("The test is passed without an error."));
}

test();
```

**Expected behavior:**
There should be no error when compiling the above code with noImplicitReturns.

**Actual behavior:** 
"error TS7030: Not all code paths return a value." is returned.

**Comment by mhegazy** [comment]
This is by design i would say. the whole point of noImplicitReturns is to make sure you do not "fall through" the function end unnoticed.  

```ts
function foo(isError: boolean = false): SomeType {
    if (isError === true) {
        return undefined;
    }
}
```

so for the non async function `foo` above, `--noImplicitReturns` forces you to return a value in the other branch.

it is true that an async function would always return a value (a Promise object), but the motivation of this feature is not nullablity as much, but rather style consistency, and in that sense, i think the error you are getting is in line with the motivation.

**Comment by RyanCavanaugh** [comment]
The non-async version of this code doesn't have an error under `noImplicitReturns`, so I don't see what the relevant difference between an async an non-async function is when considering `return` expressions.

**Comment by mhegazy** [comment]
that is because the return type annotation is not there. and in that case it goes to `any`. in the case of the async function it is known it is always `Promise`.

**Comment by FranklinWhale** [comment]
@mhegazy Thanks for your tip. The following code can compile:

```ts
async function test(isError: boolean = true): Promise<void> {
	if (isError === true) {
		return;
	}
	console.log(await Promise.resolve("The test is passed without an error."));
}
```
However, why is "Promise<void>" required?

**Comment by mhegazy** [comment]
Well, i think that is a bug :D (at least from my point of view). looks like we have an inconsistent behavior here regardless of how you look at it.

**Comment by mhegazy** [comment]
OK discussed this with @vladima  offline. looks like a bug.


```ts
// Should be an error, Promise<number>, currently retorted correctly 
async function test3(isError: boolean = true) {
    if (isError === true) {
        return 6;
    }
}

// Should not be an error, Promise<any>, currently **not** working
async function test4(isError: boolean = true) {  
    if (isError === true) {
        return undefined;
    }
}

// should not be error, Promise<any> currently working correctly 
async function test5(isError: boolean = true): Promise<any> { //should not be error
    if (isError === true) {
        return undefined;
    }
}


// should be error, currently reported correctly 
async function test6(isError: boolean = true): Promise<number> { 
    if (isError === true) {
        return undefined;
    }
}

// infered to be Promise<void>, should not be an error, currently reported correctly 
async function test7(isError: boolean = true) { 
    if (isError === true) {
        return;
    }
}
```
