### ISSUE TITLE
Update "export = <expr>" to use same logic as for "module.exports" in JavaScript files

### ISSUE THREAD

**Issue by billti** [microsoft/TypeScript#7454]
Per discussion with @mhegazy . See #7249 for the targeted change for the "module.exports = <expr>" in JavaScript files case. Currently doing a namespace import (e.g. `import * as ns from "./mod"`) fails if "./mod" uses the `export = <expr>` syntax.

**Comment by RyanCavanaugh** [comment]
This was fixed with `esModuleInterop`. Miss ya Bill!
