### ISSUE TITLE
JavaScript code formatting not working properly after v0.10.10

### ISSUE THREAD

**Issue by egamma** [Microsoft/TypeScript#7459]
_From @mlakmal on March 8, 2016 0:47_

We are extensively using javascript auto format code feature in vs code to reduce js lint errors.
Ex: spaces after function and function name etc ...

after updating to v0.10.10 above formatting is not working any more and it reset all the formatted functions without spaces.

Can someone help or give information how to override this rule ?

var test = function() { }; //this is what new version format js code to.

but we are expecting and previously worked before like below.
var test = function () { };

_Copied from original issue: Microsoft/vscode#3796_

**Comment by egamma** [comment]
This is a duplicate of Microsoft/TypeScript#6700.

**Comment by egamma** [comment]
Moving to Salsa

**Comment by billti** [comment]
@egamma This doesn't look like a dupe of #6700, which was a bug where it was removing indentation at the start of the line as you type (and is now fixed). This looks like a preference to have a space between the keyword `function` and the opening paren in a function expression (which is only reformatted when "Format code" is specifically executed, I don't see this happen as I type).

**Comment by egamma** [comment]
@billti you are correct, sorry about that. 

For the March update we will expose the TS formatter settings to the user as user settings https://github.com/Microsoft/vscode/issues/3721 so this should cover this request and we will use this issue as a test case.
