### ISSUE TITLE
Suggestion: Let derived classes redeclare private fields

### ISSUE THREAD

**Issue by Elephant-Vessel** [Microsoft/TypeScript#7461]
Consider [this](http://www.typescriptlang.org/Playground#src=class%20BaseClass%20%7B%0D%0A%09private%20_val%20%3D%20%22fofofofo%22%3B%0D%0A%09public%20Value()%7B%0D%0A%09%09return%20this._val%3B%0D%0A%09%7D%0D%0A%7D%0D%0A%0D%0Aclass%20DerivedClass1%20extends%20BaseClass%20%7B%0D%0A%09protected%20_val%20%3D%20%22babababab%22%3B%0D%0A%09public%20SomeMethod()%7B%0D%0A%09%09return%20this._val%3B%0D%0A%09%7D%0D%0A%7D%0D%0A%0D%0Aclass%20DerivedClass2%20extends%20BaseClass%20%7B%0D%0A%09private%20_val%20%3D%203434%3B%0D%0A%09public%20AnotherMethod()%7B%0D%0A%09%09return%20this._val%3B%0D%0A%09%7D%0D%0A%7D):

```
class BaseClass {
	private _val = "fofofofo";
	public Value(){
		return this._val;
	}
}

class DerivedClass1 extends BaseClass {
	protected _val = "babababab";
	public SomeMethod(){
		return this._val;
	}
}

class DerivedClass2 extends BaseClass {
	private _val = 3434;
	public AnotherMethod(){
		return this._val;
	}
}
```

I find it odd that the derived classes errors on that it does not extend BaseClass correctly since the private field _val is defined differently. I can not see why a private field in a base class should impose any kind of restrictions like this, constraining consumers to avoid conflicts with their own private implementations. Is this implementation details leaking out or just a bug?

**Comment by sandersn** [comment]
The fields _val are the same in the base and derived classes because of the way they are defined. That means the derived _vals override the base one, so they should have the same type.

```ts
let d2 = new DerivedClass2();
let s: string = d2.Value();
console.log(s); // 3434? That doesn't look like a string to me.
```

**Comment by Elephant-Vessel** [comment]
Ok, so it's implementation details then. I'd love to see this changed :)

**Comment by sandersn** [comment]
Creating privates via closure uses lots of memory, so this design decision is unlikely to ever change. Sorry.

**Comment by Elephant-Vessel** [comment]
Is that the only way to fix this? Couldn't you just do some compile-time prefixes or something? Because this is darn ugly.

**Comment by sandersn** [comment]
This issue has been discussed quite a bit. Here's [a thread from a few years ago](https://typescript.codeplex.com/discussions/397651), which addresses name mangling about halfway down.

**Comment by Elephant-Vessel** [comment]
Maybe private properties should not have been implemented at all before there was agreement on how to solve this obnoxious behavior of base classes privates leaking out and constraining derived classes. 

I don't care squat about if you still can access private variables if you really want to hack your way around it or not, as long as I have a higher-level language with a coherent and solid conceptual model of how stuff like this works.

You don't have to mangle names, just prefix them with __myDerivedClassPrivates.myValue or something like that. Then it won't be overridden and anyone who would like to work directly with the compiled code can still find them easily.

**Comment by Elephant-Vessel** [comment]
And I guess all this stuff can be made a simple compilation setting if people really care so much about disagreeing about this. Everyone get happiness in their own flavor.

```
{
    "privates" : "inherited", "noleak", "obfuscated"
}
```

**Comment by Elephant-Vessel** [comment]
I'm sure this is not as much "By Design" as it is "Unfortunate Consequence". Is this tracked anywhere here on github?

**Comment by RyanCavanaugh** [comment]
@Elephant-Vessel This has been discussed a lot and we're satisfied with the design as it is, relative to the complexity of possible other options.

**Comment by Elephant-Vessel** [comment]
If I understand the history correctly, the stakeholders in this issue can be categorized as:

 - 1: Wants to prevent that consumers of the compiled code implement against privates that might change and break code...
     - A: ... by hiding them by mangling the names.
     - B: ... by hiding them using closures.
     - C: ... by relying on the convention of prefixing privates with an underscore to clearly communicate what is private and should not be implemented against.

 - 2: Are opposed to having typescript hiding private properties because the implementation would:
     - In the case of A: ... make debugging harder.
     - In the case of B: ... degrade memory management.
     - Generally: ... limit the free will of developers to under their own responsibility make an informed decision to implement against privates.

- 3: Wants to avoid structural conflicts in inheritance, where privates in a base class constrains the super classes. This includes me.

Is that correct?

If we just focus on object oriented sanity, couldn't this be solved in a way that is agnostic to the other issue?

Like prefixing the name of the privates, or rather postfix to improve discoverability: `private _prop:string;` => `this._prop_$$MyClass = "";`

This does not mangle the names, and does not make debugging harder.
This does not affect memory.
This does not prevent consumers of compiled code to exert their free will in implementing against privates.
It does solve, in terms of general idiomatic object oriented patterns, the conceptual insanity of the current solution. It is a simple solution to implement and could be a simple compiler flag if people want to hate it.
