### ISSUE TITLE
Union type casting based on index type

### ISSUE THREAD

**Issue by christyharagan** [Microsoft/TypeScript#7462]
Hi all,

I'm using TypeScript 1.8.2, and I have the following situation:

```ts
const a: MyType[] | {[key: string]: MyType}

// type is any
const b = a[2]
```

I would expect the type of ```b``` to be ```MyType```.

More generically, we could imagine the following:

```ts
const a: MyTypeA[] | {[key:string]: MyTypeB}
```

Scenario 1:
```ts
// should be MyTypeA
const b = a[2]
```

Scenario 2:
```ts
// should be MyTypeB
const c = a['hello']
```

Scenario 3:
```ts
const k: string | number
// should be MyTypeA | MyTypeB
const d = a[k]
```

What do you think? The nice thing about JS syntax is that the property access notation is consistent across arrays and objects, but without strong typing it becomes an obvious source of bugs. I think by supporting this kind of type casting, it would allow us to retain the neat syntax *and* have strong typing.

**Comment by christyharagan** [comment]
I should also add, this is more than just a "nice to have" since if you set "noImplicitAny": true in tsconfig, then there's no neat way of actually performing the above assignment (well, you can force cast the value to either an array or object, but I wouldn't call that neat)

**Comment by RyanCavanaugh** [comment]
```ts
const a: MyTypeA[] | {[key:string]: MyTypeB}

// should be MyTypeA
const b = a[2]

// should be MyTypeB
const c = a['hello']
```
What you've said is that `a` is *either* a `MyTypeA[]` *or* a `{[key:string]: MyTypeB}`. It's impossible to index by `2` on one line and `hello` on the next and expect `MyTypeA` / `MyTypeB` to both come out -- only one of those would actually happen.

The behavior you're describing is appropriate for the *intersection* type `MyTypeA[] & {[key:string]: MyTypeB}`, and indeed all the examples except for `a[k]` work as you'd expect in that case.

**Comment by christyharagan** [comment]
I'm sorry, I should have clarified. Lines 2 and 3 are meant to be separate scenarios.

To give you a better insight into my scenario, I have an abstract class with a property whose type is equal to ```a```.

I then have subclasses which then specialise the type to either an Array or an Object. However, there are methods on the super-class that leverages the fact the syntax is common across the two types.

I have worked around the problem by creating abstract methods for getting and setting the specific property, but if TypeScript could do this kind of cast, it would create much neater - yet equally type-safe - code.

**Comment by RyanCavanaugh** [comment]
What kinds of codepaths access the base abstract property?

**Comment by christyharagan** [comment]
I'm sorry, I'm not sure I understand the question.

But maybe the following code will help:

```ts
abstract class A {
  protected a:MyType[]|{[key:string]:MyType}

  protected doSomeWork(index:string|number) {
    // Some work
    this.a[index] = someValue
  }

}

class B extends A {
  protected a:MyType[] = []

  myMethod(index:number) {
    this.doSomeWork(index)
  }
}
```

Apologises if there's any syntax errors in there :/

**Comment by RyanCavanaugh** [comment]
What you're showing really isn't typesafe at all. What happens when someone invokes `this.doSomeWork('push')` or `this.doSomeWork('indexOf')` when `a` happens to be an `Array` ?

The type-guarded version of `doSomeWork` which stops this from happening behaves as expected:
```ts
  protected doSomeWork(index:string | number) {
	  const a = this.a;
	  if (typeof index === 'number') {
		  if(a instanceof Array) {
			  a[index] = { t: 3 }; // Not 'any' 
		  } else {
			  // throw
		  }		  
	  } else {
		  if(!(a instanceof Array)) {
			  a[index] = { t: 3 }; // Also not 'any'
		  } else {
			  // throw
		  }
	  }
  }
```

**Comment by christyharagan** [comment]
Ok, I understand what you're saying: The correct way to solve this problem is type guards. They ensure type correctness **and** perform the appropriate cast preventing the ```any``` type problem. It's a slightly more verbose syntax than I was proposing, but it does provide a sane solution.

I'm happy to close this if you feel my proposal is superfluous, which I think it is at this point. Let me know.
