### ISSUE TITLE
Feature request: synchronization primitives for async functions

### ISSUE THREAD

**Issue by errorx666** [Microsoft/TypeScript#7465]
Problem: when an asynchronous function is called and accesses shared or global state, race conditions arise.

Solution: provide some mechanism to prevent reentrance into asynchronous function (or section of function), so that only one invocation may run at a time.  This can be done by waiting for the previous function to finish, or by aborting the previous invocation with a Promise rejection.  I see this working similarly to the C# `lock` keyword.

Problem:
```ts
function wait() {
	return new Promise( resolve => { setTimeout( resolve, Math.random() * 10 ); } );
}

let shared: number;
async function foo() {
	shared = 0;
	for( let i = 0; i < 100; i++ ) {	
		shared += 5;
		await wait();
	}
	return shared;
}
foo().then( c => { console.log( c ); } ); // unpredictable output
foo().then( c => { console.log( c ); } ); // race condition
```

Strawman:
```ts
symbol foolock = Symbol();
@lock( foolock, /* block */ false )
async function foo() {
	// ...
}
foo().then( c => { console.log( c ); } ); // rejects, doesn't output
foo().then( c => { console.log( c ); } ); // predictable output, pre-empts last invocation
```

This could be at the function level, or at the block level:

```ts
async function foo() {
	lock( foolock ) { // statement causes rejection in other functions currently holding foolock
	}
	await lock( barlock ) { // statement blocks until barlock becomes available
	}
}
```

Challenge:
I see three possible behaviors for a lock block:
1. Block
2. Reject others
3. Reject self

I'm not sure how to express which one is desirable.  1 and 3 might be possible to implement from an external library, but 2 would require integration into `__awaiter`.

**Comment by errorx666** [comment]
For real-world scenarios running into this problem, consider:
- a function executing a sequence of animation steps (reentrance causes irratic interleaved animation)
- a function loading the components of a scene through AJAX (reentrance causes mix of SceneA and SceneB elements being loaded)

**Comment by mhegazy** [comment]
This is an area of possible conflict with the future of JavaScript. I would say this should go as a proposal for TC39 (https://github.com/tc39/ecma262#ecmascript). We have avoided areas of possible conflict with the committee to ensure that TypeScript is a super set of JavaScript. This issue is thus out of scope for the typescript project at the time being.

I would recommend @rbuckton's prex library for some of these concepts (see https://github.com/rbuckton/prex),

**Comment by rbuckton** [comment]
@errorx666 to expand on @mhegazy's comment above, I wrote [prex](https://github.com/rbuckton/prex) for just this purpose. Using [Semaphore](https://github.com/rbuckton/prex/blob/master/docs/coordination.md#class-semaphore), your example above would read something like this:

```ts
import { Semaphore } from "prex";
const foolock = new Semaphore(1);
async function foo() {
    await foolock.wait(); // statement suspends until foolock becomes available
    try {
      // code inside of block goes here...
    }
    finally {
      foolock.release();
    }
}
```

**Comment by rbuckton** [comment]
> <span>1</span>. Block

This is feasible using the Semaphore example I provided, above.

> <span>2</span>. Reject others

This is likely difficult to accomplish or does not do what you would expect, as you cannot implicitly stop execution of another function without some mechanism for that other function to check whether it should reject. One option for that scenario is to use a [CancellationToken](https://github.com/rbuckton/prex/blob/master/docs/cancellation.md#class-cancellationtoken) and have the other callees invoke `token.throwIfCancellationRequested()`.

> <span>3</span>. Reject self

This is somewhat possible by pairing a `Semaphore` with a `CancellationToken`, and having the token reject after a short delay:

```ts
import { Semaphore, CancellationTokenSource } from "prex";
const foolock = new Semaphore(1);

async function foo () {
  const cts = new CancellationTokenSource();
  setTimeout(() => cts.cancel(), 0); // cancel the source immediately

  await foolock.wait(cts.token); // throws if foolock is not available immediately
  try { 
  }
  finally {
    foolock.release();
  }
}
```
