### ISSUE TITLE
Feature Request: Max Line Length for Typescript Compiler

### ISSUE THREAD

**Issue by btesser-r7** [Microsoft/TypeScript#7467]
One of typescript's key advantages over Babel (at least as far as I'm concerned), is the readability of its compiled javascript.  It is so readable, in fact, that I often use typescript for non-typescript projects, and just submit the compiled javascript.  One issue that often arises, however, is that the compiled javascript will go over the maximum line length allowed by style rules in these javascript projects (especially when using destructuring).  It would be extremely valuable to be able to specify a compiler option for maximumLineLength which could add line breaks when the number of characters in a line goes over the specified value.

For example, the following typescript code:
```typescript
const aVeryLargeObject = {
	firstValue: 1,
	secondValue: 2,
	thirdValue: 3,
	fourthValue: 4
};
const {firstValue, secondValue, thirdValue, fourthValue} = aVeryLargeObject;
```

Produces the following javascript:
```javascript
var aVeryLargeObject = {
    firstValue: 1,
    secondValue: 2,
    thirdValue: 3,
    fourthValue: 4
};
var firstValue = aVeryLargeObject.firstValue, secondValue = aVeryLargeObject.secondValue, thirdValue = aVeryLargeObject.thirdValue, fourthValue = aVeryLargeObject.fourthValue;
```

If this feature was implemented and maximumLineLength was set to 120 in compiler options it should produce the following javascript:
```javascript
var aVeryLargeObject = {
    firstValue: 1,
    secondValue: 2,
    thirdValue: 3,
    fourthValue: 4
};
var firstValue = aVeryLargeObject.firstValue, secondValue = aVeryLargeObject.secondValue,
    thirdValue = aVeryLargeObject.thirdValue, fourthValue = aVeryLargeObject.fourthValue;
```

**Comment by DanielRosenwasser** [comment]
I think that TypeScript's attempt to give canonical and readable output is definitely one of our virtues and strengths, but I think there exist many other tools that can pick up the slack and are specialized to this. You can take easily run TypeScript's emit through a pretty printer after your build, so I think this is out of the scope of our project.
