### ISSUE TITLE
'constructor' should be allowed as the name of a static member

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#7475]
The following should be allowed:

``` ts
class C {
    static constructor() {

    }
}
```

However, we report an error that a `static` modifier can't precede a constructor.

After reading through the spec a bit, I think we should reconsider how we wire up `constructor` in the compiler. It seems as if `constructor` is not special in any way, and that it simply places a member named `constructor` on the prototype. See [here for more details](https://tc39.github.io/ecma262/2016/#sec-runtime-semantics-classdefinitionevaluation).

**Comment by RyanCavanaugh** [comment]
You just have to write
```ts
class Foo {
	static 'constructor'() {
		
	}
}
```
This seems preferable to the world of "Why isn't TypeScript invoking my static constructor?"

**Comment by mhegazy** [comment]
related to https://github.com/Microsoft/TypeScript/issues/442

**Comment by bterlson** [comment]
This is maybe understood but while `constructor` isn't special syntactically, it is special semantically. Eg. Foo.prototype.constructor is just a reference back to Foo, whereas other members are actually installed on Foo.prototype.
