### ISSUE TITLE
New Website Logo: LiveBet

### ISSUE THREAD

**Issue by michalas** [Microsoft/TypeScript#7482]
Please fill the following out:

- Name: LiveBet
- Homepage url: http://www.livebet.com/
- Brand Guidelines/Licensing: Feel free to use the logo in white or black background
- Logo: http://www.livebet.com/a/img/LiveBet_600x220.png

> Example:
>
> Name: Microsoft
> Homepage url: https://microsoft.com
> Brand Guidelines/Licensing: https://www.microsoft.com/en-us/legal/intellectualproperty/trademarks/usage/logo.aspx
> Logo: https://news.microsoft.com/microsoft-news-center-photos/msft_logo_rgb_c-gray/

**Comment by mhegazy** [comment]
Should be in the next site update in the next few days.
