### ISSUE TITLE
Documentation for typescript.d.ts?

### ISSUE THREAD

**Issue by DavidKDeutsch** [Microsoft/TypeScript#7484]
I am writing some custom rules for TsLint, which makes use of the typescript.d.ts file installed with the typescript npm package. Unfortunately, there are no comments in that file; are the interaces/classes/etc. that are declared in that file documented anywhere?

**Comment by mhegazy** [comment]
The documentation is lacking for the API. We have tried to document "entry points", but most of the APIs there remain undocumented. Off course help is appreciated here.

If there is a specific API you need help with, we should be able to add some documentation. also see:
- https://github.com/Microsoft/TypeScript/wiki/Architectural-Overview
- https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API
- https://github.com/Microsoft/TypeScript/wiki/Using-the-Language-Service-API

**Comment by mhegazy** [comment]
Please reopen with any specific documentation requests.
