### ISSUE TITLE
tsc trying to compile typings

### ISSUE THREAD

**Issue by Jameskmonger** [Microsoft/TypeScript#7499]
**TypeScript Version:** 

1.7.5 / 1.8.0-beta / nightly (1.9.0-dev.20160217)

**Code**

Here is my `test/tsconfig.json` content:

```
{
    "compilerOptions": {
        "target": "es5",
        "module": "commonjs",
        "moduleResolution": "node",
        "isolatedModules": false,
        "jsx": "react",
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "declaration": false,
        "noImplicitAny": false,
        "removeComments": true,
        "noLib": false,
        "preserveConstEnums": true,
        "suppressImplicitAnyIndexErrors": true
    },
    "filesGlob": [
        "**/*.ts",
        "**/*.tsx",
        "!node_modules/**"
    ],
    "files": [
        "simple-organizer.test.ts"
    ],
    "atom": {
        "rewriteTsconfig": true
    }
}
```

**Expected behavior:**

When running `tsc -p test`, the file `simple-organizer.test.ts` should be compiled.

**Actual behavior:** 

The script fails with this error:

```
james@JM-LAPTOP:~/Development/tidyfolders$ tsc -p test
typings/main/definitions/tape/index.d.ts(9,26): error TS2307: Cannot find module 'stream'.
```

**Comment by blakeembrey** [comment]
@Jameskmonger do you have a reference from the `test.ts` file to the tape definitions?

**Comment by plantain-00** [comment]
I think you should fix the error in typings, typings will be compiled, but no js file generated.

**Comment by DanielRosenwasser** [comment]
> `"**/*.ts"`

Doesn't this map to `.d.ts` files in `typings`?

**Comment by Jameskmonger** [comment]
@blakeembrey Yes I have a reference to the `tape` definitions from the `test.ts` file.

@plantain-00 The typings file is downloaded from the `typings` project.

@DanielRosenwasser My project layout is like this:

```
-test
-- test.ts
-- tsconfig.json
-typings
```

That glob shouldn't affect the typings files @DanielRosenwasser

**Comment by blakeembrey** [comment]
You need a reference to `node.d.ts`

**Comment by Jameskmonger** [comment]
Right you are @blakeembrey! Issue solved :smile:
