### ISSUE TITLE
New Website Logo: Egret Engine

### ISSUE THREAD

**Issue by zcxp** [Microsoft/TypeScript#7501]
Name: Egret Engine
Homepage url: https://github.com/egret-labs/egret-core
Brand Guidelines/Licensing: https://github.com/egret-labs/egret-core
Logo: http://tool.egret-labs.org/EgretEngine/media/logo/512.png

**Comment by mhegazy** [comment]
Should be in the next site update in the next few days.

**Comment by zcxp** [comment]
@mhegazy Thank you.
