### ISSUE TITLE
String literal overload strange behaviour

### ISSUE THREAD

**Issue by tinganho** [Microsoft/TypeScript#7502]
I was expecting I could write my overloaded string literal functions as:
```ts
class C {
    foo(p1: 'p1' | 'p2'): void;
    foo(p1: string): void {
		
	}
}
```
And then call it as:
```ts
let c:C;
c.foo('none'); // error
```
As you can see it generates an error.

Though this works as expected:
```ts
class C {
    foo(p1: 'p1' | 'p2'): void;
    foo(p1: string): void;
    foo(p1: string): void {
		
	}
}
```
Though it seems redundant that I have to declare two ` foo(p1: string): void;` ?

**Comment by DanielRosenwasser** [comment]
Implementation signatures never contribute to the available overloads. This is the same thing as the following:

```ts
function pet(animal: Cat | Dog);
function pet(animal: Animal) {
    // ...
}

pet(new Squirrel());
```

**Comment by mhegazy** [comment]
see https://github.com/Microsoft/TypeScript/wiki/FAQ#why-am-i-getting-supplied-parameters-do-not-match-any-signature-error
