### ISSUE TITLE
Add ability to see what the compiler thinks a variable's type is

### ISSUE THREAD

**Issue by bcherny** [Microsoft/TypeScript#7506]
Currently, the only way to do this is to deliberately mis-type something as read through the generated error message. It would be nice to have a hook for this, maybe something along the lines of `debugtype foo`.

**Comment by mhegazy** [comment]
I am not sure i understand the suggestion. The compiler comes with a set of language service APIs that are used in many [popular editors and IDEs](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Editor-Support), and these all support some sort of "hover over" or go to type/go to definition features.

**Comment by bcherny** [comment]
If I have the following code:

```ts
let a = b.c
```

I want to know what typescript thinks `a`'s type is. Is that possible? Or are you saying this is already implemented, and if I don't see the type in my IDE it's an issue with the IDE?

**Comment by mhegazy** [comment]
![hover](https://cloud.githubusercontent.com/assets/8000722/13756758/ab8bd1ce-e9de-11e5-9303-d8c23c2c7b80.gif)

**Comment by mhegazy** [comment]
what IDE are you using?

**Comment by bcherny** [comment]
Sublime Text.

You made me second guess myself, and I just noticed that the types do indeed show up in the footer! Thanks for the help!

**Comment by mhegazy** [comment]
Ctrl+T+Q gives you the same experience in sublime text,

![hover2](https://cloud.githubusercontent.com/assets/8000722/13757341/3b57fb28-e9e1-11e5-9d62-51faa70e1f83.gif)
