### ISSUE TITLE
After Last Update Mar-07 tsd Is Not Working

### ISSUE THREAD

**Issue by dleeq8** [Microsoft/TypeScript#7511]
i have tsd files at: 
%userprofile%\typings\node\node.d.ts
and
${workspaceRoot}\typings\node\node.d.ts

still nothing like __dirname in ctrl+space

and also all vars of plugins are shown as any not detected
process: any
fs: any

so is there a way to fix this? just updated my vscode when i see New Update Available

thanks

**Comment by mhegazy** [comment]
I can not understand what is the issue. is this tsd? vscode? typescript compilation? language service issue? please reopen and provide more information.
