### ISSUE TITLE
Daily nightly build publishing was stopped

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#7512]
Have problems?

```
'1.9.0-dev.20160313': '2016-03-13T07:06:24.435Z' },
```

**Comment by RyanCavanaugh** [comment]
I think this is the first issue we can safely attribute to a windstorm in the Seattle area. Yui's getting the machine back online

:dash: :umbrella:

**Comment by falsandtru** [comment]
Oh, it is a weather bug. Thanks.

**Comment by yuit** [comment]
@falsandtru I ran the publishing; it should be out soon. :)

**Comment by falsandtru** [comment]
I found today's build. Thanks @yuit .
