### ISSUE TITLE
{"watch":true} in tsconfig.json gives only partially functional watch mode

### ISSUE THREAD

**Issue by jeffreymorlan** [Microsoft/TypeScript#7514]
If you put `{"watch": true}` in tsconfig.json's compilerOptions, and run tsc without the --watch switch, you get a kind of half-functional watch mode, where changes to existing .ts files are detected, but new files and changes to tsconfig.json itself are not.

**Comment by zhengbli** [comment]
@jeffreymorlan this issue should be fixed by #8318. You can try using the nightly build by `npm install typescript@next -g` tomorrow to test it out. Thanks.
