### ISSUE TITLE
Duplicate identifier error after moving a typescript file

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#7516]
_From @voxking on March 14, 2016 23:12_

- VSCode Version: 0.10.10
- OS Version: Windows 10

Typescript says things are duplicate when i move a file around.
My guess is that the location of the file is not updated in the typescript service properly because when i restart VSCode it fixes itself but still its annoying to have to restart the editor.

Steps to Reproduce:

1. get a large typescript code base like react.d.ts or something similar
2. move it
3. watch it happen

_Copied from original issue: Microsoft/vscode#4211_

**Comment by dbaeumer** [comment]
_From @voxking on March 14, 2016 23:16_

![screen](https://cloud.githubusercontent.com/assets/15142474/13762990/c38b848e-ea3a-11e5-88c9-24f75903bdc1.png)

**Comment by dbaeumer** [comment]
Moving to TS. 

What we do in this case is we send a close request of the file in its old location and then an open at the new location. There is now API to signal a move right now. If there is something VSCode can do different to solve the problem, please move back.

**Comment by zhengbli** [comment]
This should be fixed by #8371 . Please reopen it if the issue still exists.
