### ISSUE TITLE
sourceMappingURL does not end with a carriage return / line feed

### ISSUE THREAD

**Issue by MarcoMiltenburg** [Microsoft/TypeScript#7526]
TypeScript Version: 1.7.5

The outputted javascript ends with a comment line like:

`//# sourceMappingURL=somefilename.js.map`

This line does not end with a carriage return / line feed. When concatenating multiple compiled javascript files together (e.g. in build / minification script) this causes the first line of the next file to be added to the comment and thus be ignored.

I would like to suggest that the last line is also ended with a carriage return / line feed to fix this.

**Comment by RyanCavanaugh** [comment]
@mhegazy seems like a good idea to me, thoughts?

**Comment by mhegazy** [comment]
concatenation ruins source maps. if you are concatenating the output, emit without --sourceMap

**Comment by MarcoMiltenburg** [comment]
That Stackoverflow question is mine and hence this suggestion. I later figured out to turn off the sourcemap that also fixed it (and increased compile time massively as a bonus).

**Comment by mhegazy** [comment]
> and increased compile time massively as a bonus

I would not expect that. i would expect a minor increase as we are writing less files. can you run the compiler with `--diagnostics` with and without source maps and share the output?
