### ISSUE TITLE
ParentNode interface missing from dom.d.ts

### ISSUE THREAD

**Issue by mindplay-dk** [Microsoft/TypeScript#7528]
The [ParentNode](https://developer.mozilla.org/en-US/docs/Web/API/ParentNode) interface (implemented by `Element`, `Document` and `DocumentFragment`) appears to be missing from the `dom.d.ts` declaration file?

**Comment by mhegazy** [comment]
addressed by https://github.com/Microsoft/TSJS-lib-generator/pull/66
