### ISSUE TITLE
Please allow jsdoc at function parameter

### ISSUE THREAD

**Issue by Thaina** [Microsoft/TypeScript#7533]
Some function take complicate type such as function callback. I want to document it inline at the parameter but it seem salsa don't parse jsdoc there

![image](https://cloud.githubusercontent.com/assets/1042507/13800773/e5043bea-eb5e-11e5-96aa-fb7e538bacb3.png)

**Comment by billti** [comment]
We don't support inline block comments currently. For now, you can always write multi-line block comments before the callback function, e.g.
<img width="465" alt="screen shot 2016-03-15 at 9 02 45 pm" src="https://cloud.githubusercontent.com/assets/993909/13801665/5c03b824-eaf1-11e5-98d2-f634a363f32c.png">

**Comment by billti** [comment]
Note that placing an inline comment where you have it poses challenges if you have more than one parameter, as JsDoc @ tags are separated by newlines. The Google closure compiler does support just adding a type immediately before the parameter (e.g. `function(/** number */ index){...}`). We could consider that at a later point

**Comment by Thaina** [comment]
I see thank you

Confirmed I can do this

![image](https://cloud.githubusercontent.com/assets/1042507/13801814/2b01d8c4-eb68-11e5-9af2-b24e26eaf94b.png)

And this

![image](https://cloud.githubusercontent.com/assets/1042507/13801836/62b37eb2-eb68-11e5-9fad-73f76ade0c17.png)

**Comment by billti** [comment]
Great! Thanks. Interesting that I notice using the second form you show only works with a line break before the param. We should probably **not** require this (i.e. just allow it inline).

**Comment by martine** [comment]
Note: Closure supports inline types as you mention, but in Closure, functions have other non-type "stuff" they worry about.  For example optional params are written `@param {number=} opt_foo` and as far as I understand it you cannot use `=` in an inline type, it's specific to function params.

Another way of saying this is that `/** X */` in Closure allows a type X, but `@param {Y}` is the parameter syntax Y which includes types but also optionality.  I imagine (but haven't verified) that rest arguments (with `...`) work similarly.

**Comment by aluanhaddad** [comment]
@martine I believe that optionality is indeed a type level concern.

**Comment by mhegazy** [comment]
Should be fixed in the next release of TypeScript TS 2.1.
