### ISSUE TITLE
Can't set values in dictionaries using dot notation

### ISSUE THREAD

**Issue by FayneAldan** [Microsoft/TypeScript#7537]
**TypeScript Version:** 

1.8.7

**Code**

```ts
var foo: { [index: string]: string; } = {};
foo.bar = 'test';
foo['hello'] = 'world';

```

**Expected behavior:**
The code would compile and run without any errors.

**Actual behavior:** 
Line 3 works while line 2 throws an error when compiling:
`test.ts(2,5): error TS2339: Property 'bar' does not exist on type '{ [index: string]: string; }'.`

**Comment by mhegazy** [comment]
https://github.com/Microsoft/TypeScript/issues/4345#issuecomment-131990102
