### ISSUE TITLE
IntelliSense ECMAScript Version does not match Project Settings

### ISSUE THREAD

**Issue by AndreasGB** [Microsoft/TypeScript#7539]
**TypeScript Version:** 
1.8.6

**Visual Studio Version:**
2015 Enterprise Update 1

**Code**
```ts
"use strict";

function giveString(): Promise<string> {
    return new Promise((resolve, reject) => {
        resolve("Yay");
    });
}

async function main() {
    let awaited = await giveString();
    console.log(awaited);
}

main();
```

**Expected behavior:**
No IntelliSense Errors, since I think this is valid for ECMAScript 6 (which is set as target version in the Project Properties), and when I choose start, it compiles and runs fine, too.

**Actual behavior:** 
Instead, I get multiple IntelliSense errors including

> TS1311	Async functions are only available when targeting ECMAScript 6 and higher.	

>TS2304	Cannot find name 'Promise'.

**Comment by mhegazy** [comment]
Seems like there is an issue picking up the project properties. Do you see the same error when you build? do you have a tsconfig.json file in your project? can you hare your project file?

**Comment by AndreasGB** [comment]
When I choose "Build Only" in the error list, there are none shown, if I choose IntelliSense only, I get them shown.
There is no tsconfig.json file, since I read somewhere that Visual Studio does not play nice with them.
Link to the test project: https://transfer.sh/haxog/promisetest.zip

**Comment by mhegazy** [comment]
Looks like a bug.

To work around it for now, First unload your project, right click unload. edit the protect file.
Then replace:

`<PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|AnyCPU'">`

with:

`<PropertyGroup Condition="'$(Configuration)' == 'Debug">`

and reload.

**Comment by AndreasGB** [comment]
You forgot a closing ', but other than that, the workaround seems to work. Thank you very much!

**Comment by mhegazy** [comment]
I have a fix ready for this, but the change is in the VS Plugin side. the fix should be available in the next public release of TypeScript.
