### ISSUE TITLE
Report an error if a class is inherited from before it is defined

### ISSUE THREAD

**Issue by bsr203** [microsoft/TypeScript#754]
Hello,

I am having the same issue, which had lot of activity on  codeplex.  
https://typescript.codeplex.com/workitem/627

``` ts
class A extends B {
  // ...
}

class B {
  // ...
}
```

Compiles without error but obviously fails at runtime.

**Comment by mhegazy** [comment]
more details can be found at: #21

**Comment by RyanCavanaugh** [comment]
We do this now
