### ISSUE TITLE
insertSpaceAfterOpeningAndBeforeClosingNonemptyBrackets not behaving correctly

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#7540]
_From @SofianHn on March 15, 2016 21:7_

- VSCode Version: 0.10.12
- OS Version: OSX

 #4022
Steps to Reproduce:

1. add `"typescript.format.insertSpaceAfterOpeningAndBeforeClosingNonemptyBrackets": true` to the workspace settings.  
2. open a TS file and copy `if (x) {var x = 1;}`
3. select the line and format
4. expected==Actual => `if (x) { var x = 1; }`
5. change the option to false. 
6. format again 
7. Actual == `if (x) { var x = 1; }` but expected  `if (x) {var x = 1;}`

_Copied from original issue: Microsoft/vscode#4279_

**Comment by dbaeumer** [comment]
Moving to TS. We pass the right option to the tsserver.

**Comment by zhengbli** [comment]
This is because the tsserver considers only `[` and `]` as *brackets*. Therefore this rule is not meant to do the described scenario. We could open up new API for `{` and `}` (namely *braces*), but that should be a separate issue.

**Comment by bcherny** [comment]
@zhengbli What is the correct option to use for `{}`? Did you guys end up reusing `insertSpaceAfterOpeningAndBeforeClosingNonemptyBrackets`, or is there a separate flag?

**Comment by zhengbli** [comment]
@bcherny no corresponding rule has been provided. But that should be easy to add, I'll send a PR soon.
