### ISSUE TITLE
Unclear on how to use allowJS with untyped modules installed with npm

### ISSUE THREAD

**Issue by raybooysen** [Microsoft/TypeScript#7542]
**TypeScript Version:** 

1.8.7

**Code**

```ts
import classnames from 'classnames';

```

If I write the following code with a tsconfig that has `allowJs = true`, I receive the error below.
```
ERROR in ./src/ts-loader-example/headerBar.tsx
(3,24): error TS2307: Cannot find module 'classnames'.
```

I expect this to work as per the documentation for 1.8.  I have found the following [stackoverflow question](https://stackoverflow.com/questions/35201358/how-to-include-untyped-node-modules-with-typescript-1-8) which shows that there is some other that are unsure on how to accomplish this.

As a developer moving from JS to TS, how do I consume untyped modules with the allowJs flag?

**Comment by billti** [comment]
We don't load JavaScript modules from `node_modules` in response to imports in TypeScript files currently. There is a pull request out to get this done (https://github.com/Microsoft/TypeScript/pull/7075) but it is not in yet.

**Comment by raybooysen** [comment]
@billti thank you

**Comment by tamird** [comment]
#7075 is merged, so I guess this is good to close.
