### ISSUE TITLE
[js] should not remove whitespace after 'function'  

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#7543]
_From @slawkacz on March 15, 2016 12:11_

- VSCode Version: 0.10.11
- OS Version: 10.11.3

Formatting JavaScript code causes whitespace remove after 'function' word. This is inappropriate behaviour considering previous versions of IDE. Should be some flag which allow user to set proper formatting for such situation.  

`
Before (0.10.6):
var foo = function () {};

Now: 
var foo = function() {};
`

_Copied from original issue: Microsoft/vscode#4246_

**Comment by dbaeumer** [comment]
Moving to TS. They own the formatter settings for Salsa which we now use.

**Comment by mhegazy** [comment]
looks like the same issue as #6923. and the same underlying issue in https://github.com/Microsoft/TypeScript/issues/6039. the option does exist to add a space after the function keyword, the problem is that there is no way to surface that to the user.
