### ISSUE TITLE
Unable to augment `export = function/namespace`

### ISSUE THREAD

**Issue by blakeembrey** [Microsoft/TypeScript#7545]
Possible duplicate of https://github.com/Microsoft/TypeScript/issues/7148, but it seems like it should be working according to https://github.com/Microsoft/TypeScript/pull/6742.

**TypeScript Version:** 

1.8.7

**Code**

File: `1.d.ts`

```ts
declare module 'm1' {
  function x (): x.Test;

  namespace x {
    export interface Test {
      prop1: boolean;
    }
  }

  export = x;
}
```

File: `2.ts`

```ts
/// <reference path="./1.d.ts" />

import m1 = require('m1');

declare module 'm1' {
  interface Test {
    prop2: boolean;
  }
}

m1().prop2 // `prop2` does not exist on type `Test`.
```

**Expected behavior:**

Interfaces should merge, giving me access to `prop2`.

**Actual behavior:** 

No `prop2` on interface `Test`.

**Comment by vladima** [comment]
I can repro this in 1.8 and it seems to be fixed in `@next`.

**Comment by blakeembrey** [comment]
@vladima Thanks for the confirmation, will it be ported to 1.8?

**Comment by mhegazy** [comment]
i would use `typesctipt@next` for this one. there are a couple of other related fixes as well.

**Comment by blakeembrey** [comment]
@Guria If you want to type moment plugins, looks like you'll need to be using `typescript@next`. (Ref: https://github.com/Microsoft/TypeScript/issues/7148#issuecomment-197347289).

**Comment by Guria** [comment]
@blakeembrey thanks, will try it :)

**Comment by Guria** [comment]
Seems working. Thanks.
