### ISSUE TITLE
Single quote in JSX breaks vscode code formatting

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#7548]
_From @hamiltonia on March 16, 2016 15:55_

- VSCode Version: 0.10.11
- OS Version: Win 7, Mac OS 10.11.3

Steps to Reproduce:

If there is a single quote inside JSX, code formatting does not work for the entire file. Furthermore, if such a file is opened and tried code formatting, it breaks for all other files until a vscode restart.

Sample:

```
class Sample extends Component {
    render() {
        <View style={styles.container}>
            <Text style={styles.title}>Don't</Text>
        </View>
    }
}
``` 

First reported by @taypo: https://github.com/Microsoft/vscode-react-native/issues/156

_Copied from original issue: Microsoft/vscode#4324_

**Comment by dbaeumer** [comment]
_From @egamma on March 16, 2016 18:48_

@dbaeumer is this our edit infrastructure or the TS formatter?

**Comment by dbaeumer** [comment]
Salsa formatter. Moving.

**Comment by mhegazy** [comment]
running into an exception as well.

```txt
Error executing script:

Description:

getFormattingEditsAfterKeystroke('C:\test\file1.tsx', 171, '
')

StackTrace:

Error: Debug Failure. False expression: 
   at assert (:1704:17)
   at getFormattingScanner (:45649:13)
   at formatSpan (:47229:13)
   at formatOnEnter (:47028:13)
   at getFormattingEditsAfterKeystroke (:54045:17)
   at Anonymous function (:55961:17)
   at simpleForwardCall (:55694:9)
   at forwardJSONCall (:55710:13)
   at forwardJSONCall (:55756:13)
   at getFormattingEditsAfterKeystroke (:55959:13)

```

**Comment by mhegazy** [comment]
looks fixed in latest.
