### ISSUE TITLE
Switching to NuGet MsBuild Typescript requires relative paths.

### ISSUE THREAD

**Issue by Vaccano** [Microsoft/TypeScript#7550]
I am running in Visual Studio 2015.  I have the latest Typescript tools installed (1.8).

My project has the options I want embedded in the project file.  When I compile it works.  js files are generated from my ts files.

I then install the Microsoft.TypeScript.MSBuild nuget package.  And then I start getting errors like this:

`Build: Cannot find module 'src/setup/initialize-app'.	 C:\MyPath\main.ts`

main.ts has this at the top of it:
`import {InitializeApp} from 'src/setup/initialize-app';`

If I change that to:
`import {InitializeApp} from './src/setup/initialize-app';`

Then the build error goes away.

I would expect that if I am able to compile without the relative path using the installed version of the msbuild tools, then the Nuget Version would work the same.

Update: Files that are not on the root of my project are not able to work even with a relative path.

On a related note, while this works:
`import {InitializeApp} from './src/setup/initialize-app';`

But this does not:
`import {InitializeApp} from './src/../src/setup/initialize-app';`

From what I see, those should be the same path, but Typescript build is not seeing it that way.

**Comment by mhegazy** [comment]
This is moduleResolution issue. do you have a tsconfig.json file? if you do what is your "module" property value?

compiling with `--module AMD` or `--moduleResolution classic` should make it work.

**Comment by Vaccano** [comment]
@mhegazy I do not have a tsconfig.js.  I am using a typescript project.  I think this is the same property from my project file:

    <TypeScriptModuleKind>System</TypeScriptModuleKind>

I tried adding `<TypescriptModuleResolution>classic</TypescriptModuleResolution>` and I still got the same errors.

Also I tried switching to `<TypeScriptModuleKind>System</TypeScriptModuleKind>` to be `<TypeScriptModuleKind>AMD</TypeScriptModuleKind>` (without TypescriptModuleResolution) and I still got the same error.

**Comment by mhegazy** [comment]
Can you share your build log?

i am interested in the line it calls `tsc.exe`

**Comment by Vaccano** [comment]
Incase it is relevent, these are my typescript settings:

    <TypeScriptTarget>ES5</TypeScriptTarget>
    <TypeScriptModuleKind>System</TypeScriptModuleKind>
    <TypeScriptModuleResolution>Classic</TypeScriptModuleResolution>
    <TypeScriptRemoveComments>false</TypeScriptRemoveComments>
    <TypeScriptSourceMap>true</TypeScriptSourceMap>
    <TypeScriptEmitDecoratorMetadata>True</TypeScriptEmitDecoratorMetadata>
    <TypeScriptExperimentalDecorators>True</TypeScriptExperimentalDecorators>
    <TypeScriptCompileOnSaveEnabled>True</TypeScriptCompileOnSaveEnabled>
    <TypeScriptNoImplicitAny>False</TypeScriptNoImplicitAny>
    <TypeScriptGeneratesDeclarations>False</TypeScriptGeneratesDeclarations>
    <TypeScriptNoEmitOnError>True</TypeScriptNoEmitOnError>

**Comment by Vaccano** [comment]
This is the line that calls tsc:

D:\myProjectPath\PackagesMicrosoft.TypeScript.MSBuild.1.8.6\tools\tsc\tsc.exe  --sourcemap --target ES5 --noEmitOnError --locale en-US "C:\myProjectPath\myProject\jspm_packages\npm\aurelia-animator-css@1.0.0-beta.1.1.0\aurelia-animator-css.d.ts" ... (A ton more of my project files).

It does seem odd that --module (and others) are missing...

**Comment by mhegazy** [comment]
yup. as i suspected. can you share the project file.. i am intrested in the relative location between the targets and the configuration properties
.

**Comment by Vaccano** [comment]
Here is a slimmed down version of my project file.  I just removed a bunch of the content tags so it was not too big.  I was experementing with the `TypeScriptAdditionalFlags` and that is shown below.  (It seemed to have no effect.)

    <?xml version="1.0" encoding="utf-8"?>
    <Project ToolsVersion="4.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
      <Import Project="..\packages\Microsoft.TypeScript.MSBuild.1.8.6\tools\Microsoft.TypeScript.Default.props" Condition="Exists('..\packages\Microsoft.TypeScript.MSBuild.1.8.6\tools\Microsoft.TypeScript.Default.props')" />
      <Import Project="..\packages\Microsoft.TypeScript.MSBuild.1.8.6\tools\Microsoft.TypeScript.NuGet.props" Condition="Exists('..\packages\Microsoft.TypeScript.MSBuild.1.8.6\tools\Microsoft.TypeScript.NuGet.props')" />
      <PropertyGroup>
        <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
        <ProjectGuid>{13C96FD3-823B-46BC-B542-86A39C964FFF}</ProjectGuid>
        <ProjectTypeGuids>{349c5851-65df-11da-9384-00065bff6f21};{fae04ec0-301f-11d3-bf4b-00c04f79fffc}</ProjectTypeGuids>
        <OutputType>Library</OutputType>
        <OutputPath>bin</OutputPath>
        <TargetFrameworkVersion>v4.5.2</TargetFrameworkVersion>
        <DebugType>full</DebugType>
        <DebugSymbols>true</DebugSymbols>
        <TypeScriptToolsVersion>1.8</TypeScriptToolsVersion>
        <UseIISExpress>false</UseIISExpress>
        <IISExpressSSLPort />
        <IISExpressAnonymousAuthentication />
        <IISExpressWindowsAuthentication />
        <IISExpressUseClassicPipelineMode />
        <UseGlobalApplicationHostFile />
        <SccProjectName>SAK</SccProjectName>
        <SccLocalPath>SAK</SccLocalPath>
        <SccAuxPath>SAK</SccAuxPath>
        <SccProvider>SAK</SccProvider>
      </PropertyGroup>
      <ItemGroup>
        <Service Include="{4A0DDDB5-7A95-4FBF-97CC-616D07737A77}" />
      </ItemGroup>
      <ItemGroup>
        <Content Include="jspm_packages\npm\aurelia-pal-browser%401.0.0-beta.1.1.4\aurelia-pal-browser.js" />
        <Content Include="jspm_packages\npm\aurelia-path%401.0.0-beta.1.1.0.js" />
        <Content Include="jspm_packages\npm\aurelia-path%401.0.0-beta.1.1.0\aurelia-path.js" />
        
        <Content Include="setVersion.js" />
        <Content Include="src\views\app\app.html" />
        <TypeScriptCompile Include="jspm_packages\npm\aurelia-animator-css%401.0.0-beta.1.1.0\aurelia-animator-css.d.ts" />
        <TypeScriptCompile Include="jspm_packages\npm\aurelia-binding%401.0.0-beta.1.1.1\aurelia-binding.d.ts" />
        
        <TypeScriptCompile Include="src\version1-stuff\version1-inbound-conversions.ts" />
        <Content Include="styles\arup-styles.css" />
        <Content Include="styles\styles.css" />
        <Content Include="web.config" />
      </ItemGroup>
      <ItemGroup>
        <Content Include="plugins\canvas-sdk\docs\symbols\src\SalesforceCanvasJavascriptSDK_js_client.js.html.orig" />
        <Content Include="plugins\canvas-sdk\README.md" />
        <Content Include="jspm_packages\.dependencies.json" />
        <Content Include="jspm_packages\.loaderversions" />
        <Content Include="jspm_packages\github\jspm\nodelibs-assert%400.1.0\.jspm-hash" />
        
        <Content Include="package.json" />
        <Content Include="packages.config">
          <SubType>Designer</SubType>
        </Content>
        <Content Include="ShipmentTracking.nuspec" />
        <Content Include="plugins\ggpopover\assets\js\ggpopover.min.js.map" />
        
        <Content Include="jspm_packages\npm\jquery%402.2.1\src\.jshintrc" />
        <None Include="web.Debug.config">
          <DependentUpon>web.config</DependentUpon>
        </None>
        <None Include="web.Release.config">
          <DependentUpon>web.config</DependentUpon>
        </None>
      </ItemGroup>
      <ItemGroup>
        <TypeScriptCompile Include="Scripts\typings\es6\es6.d.ts" />
        <TypeScriptCompile Include="Scripts\typings\aurelia-breeze\aurelia-breeze.d.ts" />
        <TypeScriptCompile Include="Scripts\typings\breeze\breeze.d.ts" />
        <TypeScriptCompile Include="Scripts\typings\jquery\jquery.d.ts" />
        <TypeScriptCompile Include="Scripts\typings\log4javascript\log4javascript.d.ts" />
      </ItemGroup>
      <ItemGroup />
      <PropertyGroup>
        <VisualStudioVersion Condition="'$(VisualStudioVersion)' == ''">12.0</VisualStudioVersion>
      </PropertyGroup>
      <PropertyGroup>
        <RootNamespace>ShipmentTracking</RootNamespace>
      </PropertyGroup>
      <Import Project="$(MSBuildBinPath)\Microsoft.CSharp.targets" />
      <Import Project="..\packages\Microsoft.TypeScript.MSBuild.1.8.6\tools\Microsoft.TypeScript.targets" Condition="Exists('..\packages\Microsoft.TypeScript.MSBuild.1.8.6\tools\Microsoft.TypeScript.targets')" />
      <Import Project="$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\WebApplications\Microsoft.WebApplication.targets" Condition="Exists('$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\WebApplications\Microsoft.WebApplication.targets')" />
      <ProjectExtensions>
        <VisualStudio>
          <FlavorProperties GUID="{349c5851-65df-11da-9384-00065b846f21}">
            <WebProjectProperties>
              <UseIIS>False</UseIIS>
              <AutoAssignPort>True</AutoAssignPort>
              <DevelopmentServerPort>29544</DevelopmentServerPort>
              <DevelopmentServerVPath>/</DevelopmentServerVPath>
              <IISUrl>http://221-schaffs.aruplab.net/ShipmentTracking/</IISUrl>
              <NTLMAuthentication>False</NTLMAuthentication>
              <UseCustomServer>False</UseCustomServer>
              <CustomServerUrl>
              </CustomServerUrl>
              <SaveServerSettingsInUserFile>False</SaveServerSettingsInUserFile>
            </WebProjectProperties>
          </FlavorProperties>
        </VisualStudio>
      </ProjectExtensions>
      <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
        <TypeScriptTarget>ES5</TypeScriptTarget>
        <TypeScriptModuleKind>System</TypeScriptModuleKind>
        <TypeScriptModuleResolution>Classic</TypeScriptModuleResolution>
        <TypeScriptRemoveComments>false</TypeScriptRemoveComments>
        <TypeScriptSourceMap>true</TypeScriptSourceMap>
        <TypeScriptEmitDecoratorMetadata>True</TypeScriptEmitDecoratorMetadata>
        <TypeScriptExperimentalDecorators>True</TypeScriptExperimentalDecorators>
        <TypeScriptCompileOnSaveEnabled>True</TypeScriptCompileOnSaveEnabled>
        <TypeScriptNoImplicitAny>False</TypeScriptNoImplicitAny>
        <TypeScriptGeneratesDeclarations>False</TypeScriptGeneratesDeclarations>
        <TypeScriptNoEmitOnError>True</TypeScriptNoEmitOnError>
        <TypeScriptAdditionalFlags> $(TypeScriptAdditionalFlags) --module System </TypeScriptAdditionalFlags>
      </PropertyGroup>
      <PropertyGroup Condition="'$(Configuration)' == 'Release'">
        <TypeScriptTarget>ES5</TypeScriptTarget>
        <TypeScriptModuleKind>System</TypeScriptModuleKind>
        <TypeScriptModuleResolution>Classic</TypeScriptModuleResolution>
        <TypeScriptRemoveComments>false</TypeScriptRemoveComments>
        <TypeScriptSourceMap>true</TypeScriptSourceMap>
        <TypeScriptEmitDecoratorMetadata>True</TypeScriptEmitDecoratorMetadata>
        <TypeScriptExperimentalDecorators>True</TypeScriptExperimentalDecorators>
        <TypeScriptCompileOnSaveEnabled>True</TypeScriptCompileOnSaveEnabled>
        <TypeScriptNoImplicitAny>False</TypeScriptNoImplicitAny>
        <TypeScriptGeneratesDeclarations>False</TypeScriptGeneratesDeclarations>
        <TypeScriptNoEmitOnError>True</TypeScriptNoEmitOnError>
        <TypeScriptAdditionalFlags> $(TypeScriptAdditionalFlags) --module System </TypeScriptAdditionalFlags>
      </PropertyGroup>
    </Project>

**Comment by Vaccano** [comment]
Just to be sure that the `Condition` was not getting in the way, I removed both of the property groups that had the typescript options in them and replaced them with one that had no conditions. Like this:

    <PropertyGroup>
      <TypeScriptTarget>ES5</TypeScriptTarget>
      <TypeScriptModuleKind>System</TypeScriptModuleKind>
      <TypeScriptModuleResolution>Classic</TypeScriptModuleResolution>
      <TypeScriptRemoveComments>false</TypeScriptRemoveComments>
      <TypeScriptSourceMap>true</TypeScriptSourceMap>
      <TypeScriptEmitDecoratorMetadata>True</TypeScriptEmitDecoratorMetadata>
      <TypeScriptExperimentalDecorators>True</TypeScriptExperimentalDecorators>
      <TypeScriptCompileOnSaveEnabled>True</TypeScriptCompileOnSaveEnabled>
      <TypeScriptNoImplicitAny>False</TypeScriptNoImplicitAny>
      <TypeScriptGeneratesDeclarations>False</TypeScriptGeneratesDeclarations>
      <TypeScriptNoEmitOnError>True</TypeScriptNoEmitOnError>
      <TypeScriptAdditionalFlags> $(TypeScriptAdditionalFlags) --module System </TypeScriptAdditionalFlags>
    </PropertyGroup>

It did not have any effect on the compile errors.

**Comment by Vaccano** [comment]
So I think this is an issue with the Typescript MsBuild Nuget.

I created a new project and added `  <TypeScriptModuleKind>System</TypeScriptModuleKind>` to the project file.

When I built this is what I got:

`C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.8\tsc.exe  --module System --sourcemap --target ES5 --noEmitOnError --locale en-US "c:\users\18773\documents\visual studio 2015\Projects\TestNewProjectStructure\TestNewProjectStructure\app.ts"`

I then ran this from the package manager console: `Install-Package Microsoft.TypeScript.MSBuild`

I then built again and got this:
`c:\my\solution\location\packages\Microsoft.TypeScript.MSBuild.1.8.6\tools\tsc\tsc.exe  --sourcemap --target ES5 --noEmitOnError --locale en-US "c:\users\18773\documents\visual studio 2015\Projects\TestNewProjectStructure\TestNewProjectStructure\app.ts"`

Notice that the `--module System` is missing from the second one.  

Since I did this with a empty Typescript HTML project, it seems less likely that it is a config error on my part.  (Unless my tools install is messed up..)

**Comment by mhegazy** [comment]
The issue is the import is before the properties. MSBuild evaluates these in order, so by the time the targets are loaded the properties are not set.

so move the target imports to the bottom of your file. specifically:
```XML
<Import Project="..\packages\Microsoft.TypeScript.MSBuild.1.8.6\tools\Microsoft.TypeScript.targets" Condition="Exists('..\packages\Microsoft.TypeScript.MSBuild.1.8.6\tools\Microsoft.TypeScript.targets')" />
```

**Comment by mhegazy** [comment]
this seems to be the same issue as #7257

**Comment by Vaccano** [comment]
@mhegazy That did it!

Thank you very much for helping me get this fixed.  

I am sorry I did not see that there was already an issue filed for this (I did do some searching, but did not know quite what to search for.)

Thanks again!

**Comment by mhegazy** [comment]
no worries. glad we got to the bottom of it.
