### ISSUE TITLE
error importing default function from ambient module

### ISSUE THREAD

**Issue by bcherny** [Microsoft/TypeScript#7554]
lib:

https://www.npmjs.com/package/textarea-caret

typing (in textarea-caret.d.ts):

```ts
declare module "textarea-caret" {
  export default function getCaretCoordinates(
    element: HTMLElement,
    position: number,
    options?: {debug?: boolean}
  ): {left: number, top: number}
}
```

consuming it (in app.ts):

```ts
import * as getCaretCoordinates from 'textarea-caret'
getCaretCoordinates(element, 42)
```

the function call fails to compile, throwing `Error TS2349: Cannot invoke an expression whose type lacks a call signature`.

changing the import to `import getCaretCoordinates from 'textarea-caret'` fixes the issue.

per the es6 module syntax, it seems that the original version is the correct one, right?

**Comment by blakeembrey** [comment]
@bcherny That type definition is incorrect according to the source code, it should be `export = getCaretCoordinates`. Also, `import * as <name>` imports the exports from the module, not the default. For importing the default, the syntax is `import x from '...'`. 

Once you're using `export =` syntax, you need to import with the equivalent import statement of `import x = require('...')`.

**Comment by bcherny** [comment]
> Also, import * as <name> imports the exports from the module, not the default. For importing the default, the syntax is import x from '...'.

thanks for clarifying - this makes sense!

> Once you're using export = syntax, you need to import with the equivalent import statement of import x = require('...').

this syntax is a bit awkward, since it's using the same keywords as es6, but with different meaning.

**Comment by blakeembrey** [comment]
Yes, I know :smile: But there's no equivalent for `module.exports =` in ES6 syntax, so the ES5 `export`/`import` can still be used in situations like these. You could, of course, use the raw `require` APIs in Node, Webpack, etc. but then TypeScript doesn't know to _also_ import type information. So while `const x = require('...')` would fallback onto your module loader, `import x = require('...')` works with TypeScript to emit the correct import _and_ import type information.

**Comment by bcherny** [comment]
actually, with the `import a from 'b'` syntax, i'm having an issue that typescript compiles `import a from 'b'` to `b.default.a`. to problem is, `b` doesn't have a property called `default` (`a` is assigned to `b` directly).

it's a 3rd party module - what do you suggest?

**Comment by blakeembrey** [comment]
Use `import x = require('...')`, it's the issue I mentioned above. `import x from '...'` is for importing the ES6 default, but for `module.exports` parity you should use `export =` and `import =`.

**Comment by bcherny** [comment]
the import compiles, but the export fails to compile. i also can't seem to find a relevant example anywhere.

new import:

```ts
import getCaretCoordinates = require('textarea-caret')
```

new export:

```ts
declare module 'textarea-caret' {
  export = function getCaretCoordinates( // syntax appears to be wrong
    element: HTMLElement,
    position: number,
    options?: {debug?: boolean}
  ): {left: number, top: number}
}
```

**Comment by PAStheLoD** [comment]
I know this is an old issue, and probably solved, but if maybe the following is helpful to others.

```
declare module 'textarea-caret' {
    function getCaretCoordinates(...): { left: number, top: number }

    export = getCaretCoordinates;
}
```

**Comment by mrdulin** [comment]
@blakeembrey Thanks. I have this issue too. It works. 

Is there some documents about `How to write a typescript definition file`. You know, for all situations. I read the `typescript` official documents. But I think the doc is not easy to understand. 
Because there is no examples to explain it.

I am confused about when to use `export = `, `export as namespace xxx`, `declare namespace xxx`. And, sometimes, there is no `declare` keyword. Just some signatures of function and interface.

If there is a `repo` which has every situation definition file demos, it will be nice. I will star it.
