### ISSUE TITLE
Unable type hint extended Error class

### ISSUE THREAD

**Issue by whitneyit** [Microsoft/TypeScript#7556]
**TypeScript Version:**

nightly (1.9.0-dev.20160313)

**Code**

```ts
class CustomError extends Error {
    constructor(public message?: string) {
        super(message);
    }
}

function example(err: ErrorConstructor): void {
}

example(Error); // OK
example(RangeError); // OK
example(CustomError); // Error
```

**Expected behavior:**
No error is thrown

**Actual behavior:**
> Argument of type 'typeof CustomError' is not assignable to parameter of type
> 'ErrorConstructor'. Type 'typeof CustomError' provides no match for the
> signature '(message?: string): Error'

**Notes:**

The `interface ErrorConstructor {}` declartion in [lib.core.d.ts](https://github.com/Microsoft/TypeScript/blob/7ae6fcd65ef48ef33f62883e7bd64a3634c15333/lib/lib.core.d.ts#L883-L887)
gives off the appearance that you cannot extend `Error` class. This is due to
ES2015 classes not being callable as functions and therefore having no
way to satisfy the `(message?: string): Error;` requirement.

Is this the intended behaviour?

**Comment by mhegazy** [comment]
You can not implemented a callable class in TS. you can in JS however by writing a function and checking the this argument and either treating them as a call or a constructor.

I think what you want is just a "constructor for `Error`"; if this is correct, then this should work:

```ts
function example(err: {new (message?: string): Error}): void {
}
```

**Comment by whitneyit** [comment]
Thanks! That works a treat.

Still on par with the original question though, should there be a standard `interface` for that shape?

Would it be worthwhile to add that interface to `lib.core.d.ts` or something similar?

**Comment by mhegazy** [comment]
> Still on par with the original question though, should there be a standard interface for that shape?

```ts
interface ErrorConstrctor {
    new (message?: string): Error;
}
```

> Would it be worthwhile to add that interface to lib.core.d.ts or something similar?

The one in lib.d.ts describes the shape of the built in `Error`constructor. this one you can call as a function, and you can new as a constructor. do not see why you need another one. TypeScript has a structural type system, so if something looks like a it constructs and `Error` object, it should work everywhere where you need something that constructs an `Error` object.
