### ISSUE TITLE
Running MSBuild for typescript gives error MSB6006

### ISSUE THREAD

**Issue by Vaccano** [Microsoft/TypeScript#7557]
This is related to https://github.com/Microsoft/TypeScript/issues/7335 

When I installed the Typescript MsBuild NuGet it had the updated `Import` that @mhegazy showed.  But I still got the msvcp140.dll is missing error.

I tried installing the VS 2015 C++ runtime (both x64 and x86) and the error changed to:

>D:\bld\1d1f9d1790f3d862\packages\Microsoft.TypeScript.MSBuild.1.8.6\tools\Microsoft.TypeScript.targets(243,5): error MSB6006: "tsc.exe" exited with code 1. 

Not sure what this means or how to get around it.  This only happens on my build machine that only has Visual Studio 2012 on it.  (I was hopping the MsBuild nuget would make it so I did not need to install VS 2015 on the server.)

**Comment by Vaccano** [comment]
I seem to be able to work around this by setting `    <TypeScriptNoEmitOnError>False</TypeScriptNoEmitOnError>`

With that I don't get the error (or at least it does not surface in the console).

**Comment by mhegazy** [comment]
As @paulvanbrenk mentioned in https://github.com/Microsoft/TypeScript/issues/7335#issuecomment-191357294

you need  [Visual C++ Redistributable](https://www.microsoft.com/en-us/download/details.aspx?id=48145) on your server for now. we have a fix for this in the next release though.

**Comment by Vaccano** [comment]
@mhegazy I had the Visual C++ Redistributable on my build server.

This is the error I got after I installed it.

As I said, the error went away after I changed NoEmitOnError to false.

**Comment by mhegazy** [comment]
I do not see how NoEmitOnError changes anything here. it just tells the compiler not to emit anything if at least one error was found. may be i am missing something..

**Comment by Vaccano** [comment]
@mhegazy I agree.  It was a total puzzler to me.  I switched it back and forth several times just to be sure.

With NoEmitOnError set to true, I get the above error.  When false it finishes fine.  

I assumed that the NoEMitOnError setting was causing the error to be hidden in the pipeline somewhere.  I would also have trouble believing it if I had not seen it.

I would suggest not worrying about it much.  My build machine old.  It is running TFS 2010 Build, with Visual Studio 2012.  I am sure when I get a new build machine (hopefully in a week or two) this will go away.  And I have an acceptable workaround until then.

**Comment by JasonKleban** [comment]
I can confirm that unchecking the `Project Properties >> TypeScript Build >> Do not emit outputs if any errors are reported` in this "legacy" typescript project (without the tsconfig.json) makes it build correctly and it doesn't have any errors and the missing output files are actually generated.
