### ISSUE TITLE
Autocompletion does not work with destructured callback parameters

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#7558]
VS2015

**TypeScript Version:** 

1.8.6

**Code**

```ts
[<Event>null].reduce(({type}, b) => b); // should suggest properties
```

**Comment by DanielRosenwasser** [comment]
Thanks for filing an issue, but we should suggest properties for ***what***? You haven't told us where you're requesting completion. Please give more details in your bug reports in the future.

I don't see an issue with anything I'm guessing you're running into.

![image](https://cloud.githubusercontent.com/assets/972891/13836609/699926a2-ebc0-11e5-9dd8-0c4905278689.png)

![image](https://cloud.githubusercontent.com/assets/972891/13836646/b20493c2-ebc0-11e5-95fa-753373584018.png)

![image](https://cloud.githubusercontent.com/assets/972891/13836647/b690825c-ebc0-11e5-82b6-eb80a276fa17.png)

**Comment by falsandtru** [comment]
For example:

```ts
[<Event>null].reduce(({ty}, b) => b);
                         ^ should suggest the `type` property of the callback parameter
```

**Comment by DanielRosenwasser** [comment]
Got it, thanks!

I think this is due to the overload, though I could be wrong. #6405 might be related.

**Comment by falsandtru** [comment]
Thanks for the accepting. This problem occurs whether using overloads or not.

```ts
function f(cb: (ev: Event) => any) {}
f(({ty}) => 0);
      ^
```
