### ISSUE TITLE
Waiting for Anders Hejlsberg to give another unbeatable talk on Typescript!

### ISSUE THREAD

**Issue by HansS** [Microsoft/TypeScript#7560]
**TypeScript Version:** 

1.7.5 / 1.8.0-beta / nightly (1.9.0-dev.20160217)

**Code**

```ts
// A self-contained demonstration of the problem follows...

```

**Expected behavior:**

**Actual behavior:**

**Comment by FranklinWhale** [comment]
@HansS: it appears that @ahejlsberg is going to give a talk on TypeScript in Build 2016: https://channel9.msdn.com/Events/Build/2016/B881

**Comment by ahejlsberg** [comment]
That's right, I'm closing this issue at 3:30 PM PDT. The talk will be live on https://channel9.msdn.com/.

**Comment by HansS** [comment]
Thank' s a lot for solving my issue!:-)
I will certainly watch Anders!Kind regards
Hans

Date: Wed, 30 Mar 2016 08:27:09 -0700

**Comment by FranklinWhale** [comment]
The video of the talk is now available on https://channel9.msdn.com/Events/Build/2016/B881

**Comment by HansS** [comment]
Hi Tse,
thank's for the message!I have seen the talk. Typescript has now established as a big player within the modern javascript frameworks likeAngular or Aurelia.It is fortunate for Microsoft to have such a genius Language Architect, helping Microsoft to get back some of the lost reputation!



Date: Fri, 1 Apr 2016 08:05:58 -0700
