### ISSUE TITLE
selectionDirection missing from HTMLInputElement

### ISSUE THREAD

**Issue by FayneAldan** [Microsoft/TypeScript#7561]
**TypeScript Version:** 

1.8.7

**Code**

```ts
var input = document.createElement('input');
var dir = input.selectionDirection;
input.setSelectionRange(0, 0, 'none');
```

**Expected behavior:**
selectionDirection property would be accessible for HTMLInputElements and I would be able to set selectionDirection propety using setSelectionRange.
**Actual behavior:** 
Lines 2 and 3 of the above code give the errors:
- `Property 'selectionDirection' does not exist on type 'HTMLInputElement'.`
- `Supplied parameters do not match any signature of call target.`

**Comment by kitsonk** [comment]
These are handled through the lib generator for TypeScript: [Microsoft/TSJS-lib-generator](https://github.com/Microsoft/TSJS-lib-generator).

**Comment by FayneAldan** [comment]
I tried to create a PR on there, but I couldn't find what files to edit.

**Comment by mhegazy** [comment]
From https://github.com/Microsoft/TSJS-lib-generator#contribution-guidelines

> For common changes, it is sufficient to change the json files. There are three json files that are used to alter the file generation: `addedTypes.json`, `overridingTypes.json`, and `removedTypes.json`. The format of each file can be inferred from their existing content.

you will need to update `overridingTypes.json`

**Comment by YuichiNukiyama** [comment]
The selectionDirection property had already been implemented in [TSJS-Repo](https://github.com/Microsoft/TSJS-lib-generator/blob/master/baselines/dom.generated.d.ts#L5712).
Maybe, This change will adopt to TS later.
