### ISSUE TITLE
variable with value 0:  strange behavior in if

### ISSUE THREAD

**Issue by mathewmeconry** [Microsoft/TypeScript#7564]
**TypeScript Version:** 

1.7.5 (TS6029)

**Code**

```ts
// var t = 0; if(t) { document.write('defined'); } else { document.write('undefined'); }

```

**Expected behavior:**

the variable is defined

**Actual behavior:** 

the variable is undefined

**Prove at Playground:**
http://goo.gl/UI4ymi

**Comment by sandersn** [comment]
This is expected JavaScript behaviour. Please see [MDN's explanation of truthy](https://developer.mozilla.org/en-US/docs/Glossary/Truthy).
