### ISSUE TITLE
IntelliSense error ("Cannot fine module angular2/core") with TypeScriptModuleResolution of node.

### ISSUE THREAD

**Issue by busbina** [Microsoft/TypeScript#7568]
**TypeScript Version:** 

1.8.6

**Code**

```ts
import {Component} from 'angular2/core';

@Component({
	selector: 'igx-test',
	directives: [Test],
    templateUrl: 'app/ngTest/Templates/Test.html'
})

export class Test {
	//test
	constructor() {
		console.log("ng2 is working");
	}
}
```

```xml
  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <TypeScriptNoImplicitAny>False</TypeScriptNoImplicitAny>
    <TypeScriptGeneratesDeclarations>False</TypeScriptGeneratesDeclarations>
    <TypeScriptModuleKind>none</TypeScriptModuleKind>
    <TypeScriptTarget>ES5</TypeScriptTarget>
    <TypeScriptRemoveComments>False</TypeScriptRemoveComments>
    <TypeScriptCompileOnSaveEnabled>True</TypeScriptCompileOnSaveEnabled>
    <TypeScriptSourceMap>False</TypeScriptSourceMap>
    <TypeScriptModuleResolution>node</TypeScriptModuleResolution>
    <TypeScriptOutFile />
    <TypeScriptOutDir />
    <TypeScriptNoEmitOnError>False</TypeScriptNoEmitOnError>
    <TypeScriptMapRoot />
    <TypeScriptSourceRoot />
    <TypeScriptExperimentalDecorators>true</TypeScriptExperimentalDecorators>
  </PropertyGroup>
```

**Expected behavior:**
Visual studio finds the module ''angular2/core' with:
```xml
<TypeScriptModuleResolution>node</TypeScriptModuleResolution>
```

has full IntelliSense and no build errors.
**Actual behavior:** 
There is a IntelliSense error ("Cannot fine module angular2/core") and no auto completion; the msbuild and build on save both work fine however. The IntelliSense works fine when I put:
```xml
<TypeScriptModuleResolution>NodeJs</TypeScriptModuleResolution>
```
in the proj xml. If I do this I get the must be 'node' or 'classic' error when I use msbuild. Build on save works fine still.

**Comment by busbina** [comment]
I used the vs2015 installer and that didn't change anything. But I installed the nuget typescript msbuild package and that fixed my issue. Thank you.

**Comment by paulvanbrenk** [comment]
Does `Node` work for you...

**Comment by busbina** [comment]
It compiles, lots of duplicate def errors because of the promise d.ts files. No intellisense though, I get intellisense when I set it to NodeJs, but no compiling.

**Comment by cjwainwright** [comment]
I have a similar issue. Setting (in my tsconfig.json file)
```json
"moduleResolution": "node",
"module": "system"
```
I get errors with visual studio intellisense such as above ("Cannot find module angular2/core"). Yet the build (etiher in VS or MSBuild works fine).

Note, if I change the module type to amd, i.e.
```json
"moduleResolution": "node",
"module": "amd"
```
Then both intellisense and the build work!

Is this the same bug?

**Comment by mhegazy** [comment]
@cjwainwright this looks like a different issue. do you mind opening a new issue and sharing a sample project we can look at.

**Comment by cjwainwright** [comment]
@mhegazy Seems I can't reproduce it any more. Possibly a restart of VS resolves it? Though I'm sure I tried that. Will file an issue if I can reproduce it.
