### ISSUE TITLE
tsconfig.json broke msbuild /t:pipelinePreDeployCopyAllFilesToOneFolder

### ISSUE THREAD

**Issue by hcapp01** [Microsoft/TypeScript#7570]
tsconfig.json broke msbuild /t:pipelinePreDeployCopyAllFilesToOneFolder

It looks like -out in tsconfig.json cannot be understood by pipelinePreDeployCopyAllFilesToOneFolder

------------------------------Repro steps--------------------------
msbuild repro.csproj /t:pipelinePreDeployCopyAllFilesToOneFolder /p:_PackageTempDir=".\output"

C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\Web\Microsoft.Web.Publishing.targets(2991,5): error : Copying file lib\a.js to .\output\lib\a.js failed. Could not find file 'lib\a.js'. [d:\code\tsrepro\repro.csproj]

typescript 1.8.6 vs2015
minimium repro project

https://github.com/hcapp01/tsrepro

**Comment by mhegazy** [comment]
this is a known issue, the targets file does not extract the info from the tsconfig.json at the moment. see https://github.com/Microsoft/TypeScript/issues/6934.
