### ISSUE TITLE
option to control allowed source version with newer TS version

### ISSUE THREAD

**Issue by alexeagle** [Microsoft/TypeScript#7573]
javac has the `-source` option. from https://docs.oracle.com/javase/8/docs/technotes/tools/windows/javac.html:

```
source release
Specifies the version of source code accepted. The following values for release are allowed:

1.3
The compiler does not support assertions, generics, or other language features introduced after Java SE 1.3.

1.4
The compiler accepts code containing assertions, which were introduced in Java SE 1.4.

...
```

The use case is when a team wants to take advantage of bugfixes or features in the compiler, without committing to upgrade all their other tooling to understand new syntax or semantics.

For example, if I want to use @vladima pathMapping semantics, my users can start using the `readonly` modifier because it's also in the same version of TypeScript, now my other tooling fails because it uses TS 1.8

**Comment by alexeagle** [comment]
javac also has a `-target` option, which controls the language level of the emitted bytecode, allowing library authors to avoid breaking their users who are not on the latest version of the language.

**Comment by mhegazy** [comment]
Where as limiting the syntax to a certain set is doable, the semantics are not. Freezing the syntax but adopting new semantics still does not guarantee that the code (or generated declarations) will behave the same way on older tool sets. for instance a change to the overload resolution or inference rules can change types of variables, generate/not generate errors, and generate different definition files. moreover, the same syntax in TS 1.7 (specialized signatures) was used in TS 1.8 to mean a different construct, (string literal types) with different semantics and slightly different overload resolution logic.
Having said that, we do not think we are at a point where we can make a commitment about freezing semantics, nor can we afford to keep trigger different semantic paths based on a flag. 
As noted in https://github.com/Microsoft/TypeScript/pull/6702#issuecomment-213627081, we will be cognisant in the future about what changes that can pop up in the definition files even if the source did not include them, to give users an easier migration path.
