### ISSUE TITLE
strange behaviors using exclude in tsconfig.json

### ISSUE THREAD

**Issue by lucamorelli** [Microsoft/TypeScript#7579]
Hi,
  working to a few projects I've noticed some strange behaviors, because I found a few times ts compilation errors in ts for files inside the wwwroot, that by default is excluded.
  I workied a bit on it and seems that the root causes were:
1.  if I have a .d.ts  that reference a ts file inside the excluded zone, it's evalutated anyway bypassing the exclude, with potential problems. This happened to me using typings: I excluded the **typings/main** folder, but I continued to receive errors. After this I noticed that in the **typings/main.d.ts** the files are referenced. excluding the main.d.ts too I solved the problem.
2. if inside the excluded zone I have another **tsconfig.json** file with a valid "files" section, the files are evalutated anyway, bypassing the exclude. This happened to me with angular2: to deploy an asp.net 5 app with angular, Currently I copy all the content of the angular 2 npm package from node_modules to wwwroot, but after this compiling I started having compilation problems for duplicate symbols. 
I solved the problem, excluding in the copy task all the .ts and tsconfig.json.

Is this by design? At the beginning is a bit confusing, though solve the problem is not hard.

**Comment by mhegazy** [comment]
yes, and yes.

"files" take precedence over "exclude". and as explained in https://github.com/Microsoft/TypeScript/wiki/FAQ#why-does-a-file-in-exclude-list-is-still-picked-up-by-the-compiler, to remove a file from the compilation, you need to remove all other files that import/triple-slash reference it.
