### ISSUE TITLE
Resharper code inspections break with TypeScript MsBuild NuGet

### ISSUE THREAD

**Issue by Vaccano** [Microsoft/TypeScript#7582]
When I had TypeScript 1.7 installed (what ever comes with Visual Studio 2015 Update 1) this code showed in the editor with no errors and intellisense worked:

    export class Box implements EntityInterfaces.IBox {
        @computedFrom('isSystemAssigned')
        get mask(): string {
            if (this.isSystemAssigned)
                return '7-000000';
            else
                return '1-00000';
        }

        entityAspect: breeze.EntityAspect;
        entityType: breeze.EntityType;
    }

After I installed the TypeScript 1.8 Tools and upgraded to use the TypeScript MsBuild NuGet the `computedFrom` in `@computedFrom('isSystemAssigned')` is red and `breeze` (in both spots) has red squiggles under it.  (But it builds just fine.)

These are both done by ReSharper (I disabled ReSharper code inspections and they both change to normal highlighting).  Normally, I would consider this a ReSharper bug (and it well may be).  But I thought I would report it here because this worked fine with 1.7

**Expected behavior:**
After upgrading to 1.8, ReSharper syntax highlighting would function the same for code that is legal in 1.7 and 1.8.  (Meaning that if it worked in 1.7 it should work in 1.8.)

**Actual behavior:** 
After upgrading to 1.8, Resharper syntax highlighting for decorators and non-exported module definitions is broken (shows as error when it is not).

NOTE: I do not have a tsconfig.json file.  I am using the Visual Studio Project setup.  In case it is relevant, here is the part of my project file with the typescript settings:

    <PropertyGroup>
      <TypeScriptTarget>ES5</TypeScriptTarget>
      <TypeScriptModuleKind>System</TypeScriptModuleKind>
      <TypeScriptModuleResolution>Classic</TypeScriptModuleResolution>
      <TypeScriptRemoveComments>false</TypeScriptRemoveComments>
      <TypeScriptSourceMap>true</TypeScriptSourceMap>
      <TypeScriptEmitDecoratorMetadata>True</TypeScriptEmitDecoratorMetadata>
      <TypeScriptExperimentalDecorators>True</TypeScriptExperimentalDecorators>
      <TypeScriptCompileOnSaveEnabled>True</TypeScriptCompileOnSaveEnabled>
      <TypeScriptNoImplicitAny>False</TypeScriptNoImplicitAny>
      <TypeScriptGeneratesDeclarations>False</TypeScriptGeneratesDeclarations>
      <TypeScriptNoEmitOnError>False</TypeScriptNoEmitOnError>
    </PropertyGroup>

**Comment by mhegazy** [comment]
Resharper uses a property analysis engine to understand the TS code. they do not use the TypeScript services API. there is nothing that we can do about that. this issue should go to the Resharper issue tracker.

**Comment by Vaccano** [comment]
@mhegazy  OK.  I thought they used the typescript code and the integration may have broken somehow with the upgrade.  (Sorry for the extra noise)
