### ISSUE TITLE
IntelliSense / JSDoc - function declaration not same as function expression

### ISSUE THREAD

**Issue by LittleBrainz** [Microsoft/TypeScript#7586]
In the recent February release of VS Code 0.10.11 (with TypeScript 1.8.2), IntelliSense with JSDoc works as expected when referencing a function defined by a declaration, but displays limited information when referencing a function defined by an expression.

This was [raised](https://github.com/Microsoft/vscode/issues/3842#issuecomment-194428430) in Microsoft/vscode#3842. After consideration, @egamma [declared](https://github.com/Microsoft/vscode/issues/3842#issuecomment-198448374) this to be a TypeScript issue.

**TypeScript Version:** 

1.8.2 or 1.8.9

**Code**

```js
/**
 * Transform a string to upper-case.
 * @param {string} value The string to be transformed.
 * @returns {string} The upper-cased string.
 */
function upper1(value) {
    return value.toUpperCase();
}


/**
 * Transform a string to upper-case.
 * @param {string} value The string to be transformed.
 * @returns {string} The upper-cased string.
 */
const upper2 = function(value) {
    return value.toUpperCase();
};


const v1 = upper1('hey');

const v2 = upper2('ho');
```

**Expected behavior:**

IntelliSense with JSDoc works as expected when referencing a function defined by a declaration:
![fd completion](https://cloud.githubusercontent.com/assets/5047398/13824703/193ed274-eba7-11e5-9280-4025f6200803.PNG)
And hover:
![fd hover](https://cloud.githubusercontent.com/assets/5047398/13824714/21e2a75c-eba7-11e5-9057-7bcaa24a2b15.PNG)

**Actual behavior:** 

IntelliSense displays limited information when referencing a function defined by an expression:
![fe completion](https://cloud.githubusercontent.com/assets/5047398/13824735/32638c18-eba7-11e5-8c56-7d4a6e50f6d1.PNG)
And hover:
![fe hover](https://cloud.githubusercontent.com/assets/5047398/13824737/35c07cae-eba7-11e5-82b8-d6cc972c5623.PNG)

**Comment by DanielRosenwasser** [comment]
Not necessarily Salsa-specific. Ideally this should be fixed for TS as well.

**Comment by sandersn** [comment]
Yes, this repros the same in TypeScript and JavaScript. Not Salsa-specific.
