### ISSUE TITLE
Empty for loop emit

### ISSUE THREAD

**Issue by pierogitus** [Microsoft/TypeScript#7589]
**TypeScript Version:** 

1.8.7

**Code**

```
for
```

**Expected behavior:**
Emit something that's not an infinite loop. It's a syntax error so it should probably stay a syntax error in the output js.
**Actual behavior:** 
A for loop with no parameters or body emits this:
```
for (; ; )
    ;
```

**Comment by mhegazy** [comment]
if i may ask, how are you consuming the output?

**Comment by pierogitus** [comment]
It's a code playground type of scenario where it transpiles and runs the output on every keystroke in an editor. So when I begin a valid for loop by typing 'f'... 'o'... 'r'... it should fail gracefully with a syntax error instead of taking down the browser tab with an infinite loop.

**Comment by mhegazy** [comment]
you probably should have a more generalized solution. the `for` is an easy one to ask the compiler to change, but in a playground scenario, you can have no guarantees that the code you are running is correct. as a matter of fact, most of the time the code will be wrong while the user is editing. exceptions, invalid access to DOM elements, infinite loops, stack over flow, infinite recursion are things that are guaranteed to happen. i would say this code should not run on the UI thread.

**Comment by pierogitus** [comment]
I disagree that this is a matter of application architecture. exceptions, invalid access to DOM elements, stack over flow, infinite recursion are all recoverable with try/catch. Infinite loop is the only one that is not recoverable. Typescript should never emit an infinite loop as some kind of default.

As an alternative it could emit a loop that does nothing like:
```
for(var x in {}){
}
```

**Comment by DanielRosenwasser** [comment]
> it should fail gracefully with a syntax error instead of taking down the browser tab with an infinite loop.

Ideally you'd be able to check the `ExitStatus`, but we don't have a distinction between syntactic and semantic errors.

**Comment by pierogitus** [comment]
I don't think I should have to check the results of the transpile either. My point is that "for" is not an infinite loop in javascript. Typescript is creating one out of thin air.

I don't see any reason why it has to emit what it does. It's just a default value and the default should be less harmful.

**Comment by mhegazy** [comment]
The compiler can not grantee the otuput is infinit-loop-free. where the `for` case is easy to ask the compiler to change, other cases are not. 

If you are expecting live user input, you should expect the input to be invalid 99% of the time. infinit loops, inifinit recursion, and the user writing code that deletes all DOM elements (invlaid DOM access), are not cuagut by exceptions at runtime, and will kill your app. 

consider this:

```ts
var x = 0;

while (!x) // I am in the  middle of typing a loop, but has not got to a break statement
```

```ts
function visit(node) {
if (node.left) visit(node // have not written `.left` yet, and now it is an infinite recursion
}
visit({left: 0});
```

```ts
document.getElementsByTagName("div").forEach(e => document.removeChild(e));
```

I do not think we possibly catch any of these cases, and thus do not see the reason of adding complexity to handle such invalid user input.

**Comment by pierogitus** [comment]
This is not too complex. I'm not asking you to try and detect all possible code problems. I just want you to change the behavior of this one single situation when the input text is "for".

**Comment by mhegazy** [comment]
Why is emitting an empty `for` loop an error any more than any of the above?

**Comment by johnfn** [comment]
To me, `for` on a line by itself seems like a clear user error and should have no output. It is also incorrect as per the spec.

**Comment by RyanCavanaugh** [comment]
"Too Complex" here is about the scalability trade-off: The effect of a thousand people asking us for one-off single-line fixes for their niche scenarios is that we'd have thousands of one-off cases in the compiler codebase, drastically increasing the complexity, maintenance burden, loading time, etc..

Whereas if the consumer of the API who wants to unconditionally execute the code but still handle this case, they can write
`output = output.replace(/for \(; ; \)/g, "for( ; false; )");`
which has the effect of one line of code in their codebase.

**Comment by pierogitus** [comment]
@mhegazy because it deviates from javascript. Your examples above are infinite loops in javascript. If the user does something that explicitly dumb its their own fault. But `for` is not an infinite loop in javascript. Typescript is injecting one out of nowhere.

@RyanCavanaugh I doubt this would add any complexity. The input `for` is ambiguous (you can't tell if it was meant to be a `for`, `for in` or `for of` loop) so its already making a one-off choice to inject `(; ; );` as a default value. I'm just saying we should change the default.

**Comment by mhegazy** [comment]
All what we are saying, TypeScript does not make any guarantees on output correctness if the input is syntactically invalid. Do not see the point of starting to sprinkle in some checks on output correctness for some statements like `for`, but not for property access, missing function arguments, incomplete generic arguments list,  etc.. From the compiler perspective, that is all invalid. `--noEmitOnError` will ensure that no output is generated unless the input is *correct*.
