### ISSUE TITLE
ts.createProgram/ts.transpile producing incorrect output

### ISSUE THREAD

**Issue by timothysoehnlin** [Microsoft/TypeScript#7592]
**TypeScript Version:** 

1.9.0-dev.20160319

**Code**

```ts
// A self-contained demonstration of the problem follows...
let ts = require('typescript');
let res = ts.transpile("let hello='hello'; let world='world'; let out = `${hello} ${world}`", { target : "es6" });
console.log(res);
```

**Expected behavior:**
"use strict";
var hello = 'hello';
var world = 'world';
var out = `${hello} ${world}`;

**Actual behavior:** 
"use strict";
var hello = 'hello';
var world = 'world';
var out = hello + } ${ + world;

---------------------

Using ts.createProgram results in the same issue.

running tsc from the command line does not produce this issue (tsconfig.json indicates target is es6 as well).  I get the expected behavior at that point.

**Comment by timothysoehnlin** [comment]
I'm also seeing another issue with fat arrow functions:

`let ts = require('typescript');`
`let res = ts.transpile("() => console.log('Hello world');", { target : "es6" });`
`console.log(res)`
`"use strict";`
`(function () console.log('Hello world'));`

The output is missing the curly braces and is producing bad javascript.

**Comment by vladima** [comment]
`target` should be set as `{ target: ts.ScriptTarget.ES6 }`

**Comment by timothysoehnlin** [comment]
Thanks, that did it.  This is a little unexpected as I've required my tsconfig.json, and passed in the compilerOptions object into the transpile/createProgram operation.  

Is there a reason those objects aren't compatible? It looks enums may be the only field that needs to be manually converted.  Are there any other conversions that have to happen to make the tsconfig.json's compilerOptions compatible?

**Comment by vladima** [comment]
`ts.convertCompilerOptionsFromJson` should do the trick. First argument of this function is a JSON object that correspond to `compilerOptions` section in `tsconfig.json`, second argument is a basePath that is used to resolve relative paths in compiler options.
```javascript
var ts = require('typescript');
var config = require('./tsconfig.json');
var options = ts.convertCompilerOptionsFromJson(config["compilerOptions"], process.cwd());
if (!options) {
	// TODO: check options.errors
}
var res = ts.transpile("let hello='hello'; let world='world'; let out = `${hello} ${world}`", options.options);
console.log(res);
```
NOTE: `convertCompilerOptionsFromJson` works fine in 1.8 release however there was an unintended breakage in the recent nightly buillds - https://github.com/Microsoft/TypeScript/pull/7595 should revert it to the 1.8 behavior

**Comment by timothysoehnlin** [comment]
Fantastic.  I didn't see that documented in https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API, and was unaware it existed.  

I'm also wondering if there is a need to at least indicate the compilerOptions are being ignored, or are invalid.  I'm not sure what target value was generating the above code, but I'm guessing even the default should generate valid Javascript and not the broken output I was getting.

**Comment by vladima** [comment]
Yes, we need to update documentation page. 
Also if you try to consume the API from the TypeScript client your original example will not typecheck since type of `target` property is not `string`.
![image](https://cloud.githubusercontent.com/assets/8052307/13905949/98de7468-ee8a-11e5-91f3-8c49dd3dc9c7.png)

**Comment by timothysoehnlin** [comment]
Generally I would want to do everything in typescript, but this piece of code is a bootstrap for loading typescript into a non-typescript execution.  This is why I'm attempting to transipile at runtime.  I would have to assume that until ts-node (or something similar) becomes a stable, this will generally be the case for transpile/createProgram.

**Comment by basarat** [comment]
@vladima just reading the code in I think its wrong. https://github.com/Microsoft/TypeScript/issues/7592#issuecomment-198961967

```ts
if (!options) {
    // TODO: check options.errors
}
```
If `!options` then there can't be `options.errors`

**Comment by vladima** [comment]
my mistake, meant to be
```ts
if (!options.options) {
     // TODO:...
}
```
