### ISSUE TITLE
Instance member not in navigation bar items if it has the same name as a static member

### ISSUE THREAD

**Issue by tinganho** [microsoft/TypeScript#7600]
Given the following code:

``` ts
class A {
  static A() {};
  A() {};
}
```

I cannot get a navigation bar item of the instance member, only the static member.

**Comment by Andarist** [comment]
I think this has been already fixed unless I mistake the "navigation bar item" for something else. I can see both in:
- the outline in VS Code (might be called a navigation tree on the TS side)
- the breadcrumbs above the source file in VS Code (might be called a navigation bar on the TS side)
- the symbols search (cmd+R in VS Code)

cc @jakebailey

**Comment by jakebailey** [comment]
Given the age of the issue, it's possible that this was actually a problem in VS. Not sure, though. I also am not sure what "navigation bar" is.

**Comment by RyanCavanaugh** [comment]
In VS parlance, the "Navigation bar" is the 3-combo-box bar shown here. 
![image](https://github.com/microsoft/TypeScript/assets/6685088/d3c77cf5-5bba-4e2e-aa11-7941730811f5)

Unfortunate that there isn't a different icon here but I think that's out of our control, so is "working"
