### ISSUE TITLE
IIFEs' arguments are not inferred

### ISSUE THREAD

**Issue by 2426021684** [Microsoft/TypeScript#7601]
Version: 1.9.0
Code:
`(function (x){
	return x.thisPropertyDoesNotExist
})("Hi")`
Expected Result:
Error type String does not have property thisPropertyDoesNotExist.

Actual Result:
No error

**Comment by DanielRosenwasser** [comment]
IIFEs are type checked, the problem is that `x` implicitly got the type `any`, so you can do anything. You can fix this with a type annotation.

What you probably expected is for the type of `x` to be inferred, but there are certain issues with that as outlined at #4142.

**Comment by 2426021684** [comment]
Flow can catch the error so it is possible.

**Comment by 2426021684** [comment]
Since this issue was closed, does that mean the Typescript team has no plans of adding this feature?

**Comment by RyanCavanaugh** [comment]
Correct; see comments in #4142
