### ISSUE TITLE
Better support for type declarations and tuples

### ISSUE THREAD

**Issue by ianbytchek** [Microsoft/TypeScript#7606]
Tuples are nice, but they feel like second class citizens. Construct for declaring variables and assigning tuple values all in one statement is great, but it doesn't allow to specify types.

```ts
type Tuple = [string, number];
var tuple:Tuple = ['str', 10];

// Works, but `a` and `b` are `any` type.
var [a, b] = tuple;

// Looks great. Doesn't work.
var [c:string, d:number] = tuple;

// Works great. Doesn't look.
var e:string;
var f:number;
[e, f] = tuple;
```

Please consider providing support for `var [c:string, d:number] = tuple` syntax, where variable type is defined right in the "tupled" declaration.

**Comment by Arnavion** [comment]
Why do you think `a` and `b` are of `any` type? They're inferred correctly as `string` and `number` respectively.

Even if we're talking about the situation where you want to provide explicit types, that's supported by

```typescript
var [c, d]: [number, string] = ...;
```

[Playground](http://www.typescriptlang.org/Playground/#src=type%20Tuple%20%3D%20%5Bstring%2C%20number%5D%3B%0D%0Avar%20tuple%3A%20Tuple%20%3D%20%5B'str'%2C%2010%5D%3B%0D%0Avar%20%5Ba%2C%20b%5D%20%3D%20tuple%3B%0D%0Avar%20%5Bc%2C%20d%5D%3A%20%5Bnumber%2C%20string%5D%20%3D%20null%0D%0A)

**Comment by ianbytchek** [comment]
I did try `var [c, d]: [number, string]` or better `var [c, d]: Tuple`, but didn't explicitly check their types, hence assumed they are `any`. You're absolutely correct, doing `var x:boolean = c` results in the error.

I'm using WebStorm, it's really good with TS, but doesn't pick up the type from tuple assignment, made me think there's a problem with it.
