### ISSUE TITLE
tsc with outDir option is not copying the JS import node_modules to outDir

### ISSUE THREAD

**Issue by a8775** [Microsoft/TypeScript#7608]
I have the tsconfig.json as follow:

```
{
    "compilerOptions": {
        "sourceMap": true,
        "module": "commonjs",
        "target": "es6",
        "declaration": true,
        "outDir": "./bin"
    },
    "files": [
        "app.ts" // and some other files...
    ]
}
```
The project has some dependencies in node_modules like firebase that I import like that:

```
import Firebase = require('firebase');
```

The problem is that the TS modules imported in similar way:
```
import {myType} from 'myModule/myModule';
```

are copied (in fact they are compiled) to outDir but not JS modules.

I think it's not intuitive/consistent that I have to copy in separated task JS modules to outDir. I checked wiki page and github issues and I do not see any reference to my scenario.

**Comment by billti** [comment]
JavaScript files are never compiled/copied unless you set `allowJs`. That said, I'm pretty sure that's not what you really want. Code in NPM packages installed under `node_modules` should stay there. Your deployed app should also install the NPM package as part of deployment, and the modules will be resolved at runtime by Node.
