### ISSUE TITLE
Peek definition shows import line with typescript and es6 style modules

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#7612]
_From @mtrivolli on March 19, 2016 11:50_

- VSCode Version: 0.10.10
- OS Version: Debian Jessie

Steps to Reproduce:

- Create a simple typescript file using es6 style imports. For instance:
```typescript
import {Promise} from "es6-promise";

let a = new Promise<string>((resolve, reject) => {
    resolve("test");
});
```
- Right click on "Promise<string>" => peek definition. It shows `import {Promise}`

_Copied from original issue: Microsoft/vscode#4454_

**Comment by martine** [comment]
In Emacs+tsserver the "go to definition" key jumps to that place as well, but then hitting it again (once your cursor is on the `Promise` in `import {Promise}`) it jumps to the file where it's actually defined.  It was a surprise at first, but I can imagine hypotetical scenarios where you'd want to see either the file-local alias or the actual definition...

**Comment by mhegazy** [comment]
should be fixed by https://github.com/Microsoft/TypeScript/pull/6952
