### ISSUE TITLE
Feature request : add in code 'debugger;' to tsserver for .ts and .js files

### ISSUE THREAD

**Issue by Alphapage** [Microsoft/TypeScript#7613]
Hello,

I don't think tsserver provides a way to list all the `debugger;` written in ts or js files.
This feature is related to vscode: https://github.com/Microsoft/vscode/issues/4492

I hope you will take my request into consideration and this could help to enhance tsserver.

Thank you in advance for your feedback.

**Comment by mhegazy** [comment]
This looks like a linter rule rather than a part of the core pipeline. [tslint](https://github.com/palantir/tslint) already has a `no-debugger` rule that does this.

**Comment by RyanCavanaugh** [comment]
@mhegazy I believe the intent here is that a host could ask tsserver what all the `debugger`; statements are so it could use that information to populate a breakpoint list, not to disallow them

**Comment by mhegazy** [comment]
ooh. i see. sorry did not read the linked item. my bad.

**Comment by RyanCavanaugh** [comment]
Linked issue closed out of scope
