### ISSUE TITLE
Support `libraries` field in tsconfig.json

### ISSUE THREAD

**Issue by RyanCavanaugh** [Microsoft/TypeScript#7623]
Today (once the PR goes in) you can write
```ts
/// <reference library="jquery" />
```
but there is no equivalent in tsconfig.json. We should support e.g.
```js
{
  "files": ["myFile.ts"],
  "libraries": ["jquery"], <---
  ...
}
```

**Comment by mhegazy** [comment]
The property name is `"types"` and not `"libraries"`. see https://github.com/Microsoft/TypeScript/pull/7775
