### ISSUE TITLE
what are the preferred apis for writing an ast to .d.ts (or .ts) files?

### ISSUE THREAD

**Issue by bcherny** [Microsoft/TypeScript#7625]

**Comment by RyanCavanaugh** [comment]
We currently don't have support for creating and emitting a synthetic AST. @rbuckton's tree transform work may change this, but I'm not sure.

**Comment by bcherny** [comment]
How would you recommend going about compiling to Typescript then? Eg. For a Scala => Typescript compiler.

**Comment by RyanCavanaugh** [comment]
Producing a CodeDOM-like data structure should be reasonably straightforward. @CyrusNajmabadi might have some more concrete suggestions

**Comment by mhegazy** [comment]
here is the issue @RyanCavanaugh mentioned: https://github.com/Microsoft/TypeScript/issues/5595
