### ISSUE TITLE
strictNullChecks thinks ambient declarations are unassigned and complains when they're used

### ISSUE THREAD

**Issue by Arnavion** [Microsoft/TypeScript#7626]
**TypeScript Version:** 

https://github.com/Microsoft/TypeScript/commit/3853bb86d0f26e150666ab736092824eb781babc (master after merging #7140 )

**Code**

```ts
declare const foo: string;
console.log(foo);
```

`tsc -t es5 --strictNullChecks ./foo.ts`

**Expected behavior:**

Compiles.

**Actual behavior:** 

`foo.ts(2,13): error TS2454: Variable 'foo' is used before being assigned.`

---

Allowing `foo` to be undefined makes it compile, but this shouldn't be required of course.

```typescript
declare const foo: string | undefined;
console.log(foo);
```

**Comment by ahejlsberg** [comment]
This is already fixed in the control flow branch I'm working on, but it is obviously rather irritating so I will put up a fix shortly.
