### ISSUE TITLE
strictNullChecks thinks a value may be null if null is assigned to it in its non-null branch

### ISSUE THREAD

**Issue by Arnavion** [Microsoft/TypeScript#7630]
**TypeScript Version:** 

https://github.com/Microsoft/TypeScript/commit/3853bb86d0f26e150666ab736092824eb781babc (master after merging #7140 )

**Code**

```ts
class Prop {
	value: any;
}

var x: Prop | null = null;
if (x === null) {
	;
}
else if (x.value === null) { // Line 9
	x = null;
}
```

`tsc -t es5 --strictNullChecks ./foo.ts`

**Expected behavior:**

Compiles.

**Actual behavior:** 

`foo.ts(9,10): error TS2531: Object is possibly 'null' or 'undefined'.`

---

If the `x = null;` assignment (line 10) is removed, it does compile, and `x` is correctly inferred to be non-null in the condition and body of the else-if block. But this assignment should not have any effect on the nullability of x in the else-if condition.

**Comment by weswigham** [comment]
Im pretty sure the reason is this: Assignment within a block disabled narrowing within it. If so, the solution is likely already in the works: Control flow based type guards (See PR #6959)

**Comment by Arnavion** [comment]
Disabling narrowing *within* the block is one thing, but line 9 is before the block.

**Comment by RyanCavanaugh** [comment]
Assignments anywhere within the scope of a variable disable type guards.

As you've noticed, this makes null checks extremely cumbersome, which is why control flow analysis was bumped up in priority.
