### ISSUE TITLE
can't navigate javascript with manual namespaces

### ISSUE THREAD

**Issue by jrieken** [Microsoft/TypeScript#7632]
_From @chadbr on March 22, 2016 0:18_

I have large legacy codebase with "manual" style namespacing like this:

```
//namespaces
var my = my || {};
my.app = my.app || {};
```

and "classes" declared like this:

my.app.Application` = (function () {
    var Application = function () {
...
    };
    return Application;
})();

I've tried several combinations of jsconfig.json parameters and none allow me to navigate this style of code. Should this work?
- VSCode Version: 0.10.11, 0.10.12-insider
- OS Version: OSX 10.11.3

Steps to Reproduce:
1. Open attached project or github repo https://github.com/chadbr/vscodeTestJS

[vscodeTestJS.zip](https://github.com/Microsoft/vscode/files/183295/vscodeTestJS.zip)
1. Open folder in vscode
2. open src/app/application.js 
3. try to go to declaration of my.app.SomeView() -- nothing happens.

_Copied from original issue: Microsoft/vscode#4533_

**Comment by jrieken** [comment]
_From @chadbr on March 22, 2016 0:21_

oh - and FWIW, WebStorm allows me to navigate these files...

**Comment by unional** [comment]
This is a major road block for our team to adapt VSCode and TypeScript because our main product is still using global namespace.

**Comment by chadbr** [comment]
I'm assuming this won't be supported any time soon (if ever...)

**Comment by aluanhaddad** [comment]
This seems easily as reasonable as tracking prototype assignments.

**Comment by Cristy94** [comment]
Any news? It's very annoying that by simply namespacing objects you no longer get IntelliSense.

**Comment by mhegazy** [comment]
@sandersn this should be addressed with your fix for https://github.com/Microsoft/TypeScript/issues/16489 with a small modification to recognize the pattern `var x = x || {}`.

**Comment by mhegazy** [comment]
Another pattern referenced in https://github.com/Microsoft/vscode/issues/27246 is `var x = window.x || {}`

**Comment by errorx666** [comment]
If https://github.com/tc39/proposal-nullish-coalescing advances, you may want to revisit this issue.
