### ISSUE TITLE
Index signature not inherited from interface to class

### ISSUE THREAD

**Issue by ianbytchek** [Microsoft/TypeScript#7633]
```ts
interface Foo {
    [key:string]:any;
}

interface Bar extends Foo {
}

class Baz implements Foo {
    [key:string]:any;
}

class Qux implements Foo {
}

console.log((<Foo>{})['x']);
console.log((<Bar>{})['x']);
console.log((<Baz>{})['x']);
console.log((<Qux>{})['x']);
```

On `(<Qux>{})['x']` compiler fails with `Index signature of object type implicitly has an 'any' type.` message. When it's explicitly added to a class, like with `Baz`, everything works ok. With interfaces it seems to work fine, for example, `Bar` interface behaves as expected.

**Comment by mhegazy** [comment]
There is a distinction between `extends` and `implements` clauses for classes. `extends` means the current class inherits the shape of the parent; this includes index signatures, properties, and methods. `implements` on the other hand, is just a constraint. it says to the compiler, "please check that this class incorrectly implements this interface". there is nothing that is "inherited" by implementing the interface.

TypeScript's type system is a structural one. so the implements clause is not required for an instance of this class to be assignable to an instance of the interface it implements. the only requirements, is that their structures match. As a matter of fact, removing the implement clause, should not change the semantics of your program.

**Comment by ianbytchek** [comment]
Very well then. Thanks for the detailed explain.
