### ISSUE TITLE
Unable to get intellisense from jquery IIFE functions

### ISSUE THREAD

**Issue by jrieken** [Microsoft/TypeScript#7634]
_From @Umamaheswaran1990 on March 22, 2016 11:21_

- VSCode Version: 0.10.11
- OS Version: Windows 7

Steps to Reproduce:

1. Create two files one with a.js and one with b.js
2. Create jsconfig.json with below content 

   ```json
    {
        "compilerOptions": {
            "module": "commonjs"
        }
    }
    ```   
3. In **a.js** add below code and install tsd jquery

    ```javascript
    (function() {
        
        function SomeMethod(){
            return "Im SomeMethod()";
        }
    })();
    ```

4. Now if you go to **b.js** and try typing Some... you will not see the intellisense.

Is it possible to get intellisense for the objects inside jquery IIFE?

_Copied from original issue: Microsoft/vscode#4553_

**Comment by sandersn** [comment]
IIFE's don't let definitions escape their scope. Even if your code is in one file, you'll get an error:

```ts
(function() {

    function SomeMethod(){
        return "Im SomeMethod()";
    }
})();
SomeMethod(); <-- "Cannot find name 'SomeMethod'"
```
