### ISSUE TITLE
Incomplete module path emitted when using the 'node' module resolution strategy

### ISSUE THREAD

**Issue by thomas-darling** [Microsoft/TypeScript#7636]
Ok, so here we go... we're building a large app, and we *really, really* need this.

**Background**

Say I'm building a single page app structured like this, compiled using the `node` module resolution strategy and the `AMD` module format:
```
 app
 ├── module1
 │   ├── service1.ts
 │   ├── service1-helper.ts
 │   └── index.ts
 ├──  home.ts
 └──  home.html
```
Where `home.ts` represents a page in the app - it contains this:
```typescript
import {Service1} from "./module1";
...
```
Where `index.ts` represents the interface of a complex module used by the page - it contains this:
```typescript
export {Service1} from "./service1";
...
```
The compiler allows this, as the `node` strategy knows it should look for an `index.ts` file. This is a *really* nice way to structure things, as it allows us to keep things structured within `module1` while at the same time ensuring that the rest of the app only needs a single import statement to use that module, without having to know anything about its internal structure.

**The problem**

Now, while this looks all fine in the editor, the generated javascript files will not actually load in the browser, as a loader like SystemJS *does not* know it should look for the `index.js` file. This is what the above `home.ts` compiles to:
```typescript
define(["require", "exports", "./module1"], function (require, exports, module1_1) {
    ...
```
Here we see that even though the compiler resolved the import path to the `index.ts` file correctly, the emitted javascript *does not* actually reference that file - it still only references `./module1`, which is obviously not a valid file path when the loader tries to load it.

Of course, I could just change all my imports to explicitly reference the `index.ts` file, but that is not just really annoying, it is also quite dangerous to rely on, as the compiler *will not* complain if I forget it - I will only see that error *at runtime*, when the app crashes because it can't find some module.

**The solution**

I believe this can be fixed very easily, by simply having the compiler emit the path *including* the `/index` part it resolved itself, thus resulting in this javascript:
```typescript
define(["require", "exports", "./module1/index"], function (require, exports, module1_1) {
    ...
```
Now the module loader in the browser has a valid file path to load, and everything works beautifully. I see absolutely no reason not to do this, and it would make structuring large apps *so* much easier.

Is this something you could *please* consider for your next release?

**Comment by thomas-darling** [comment]
@vladima You seem to be involved in all the module resolution stuff - could you please take a look at this really quick? It's something I feel is really important and it would help us a lot :-)

**Comment by mhegazy** [comment]
[Module Resolution]() just allows the compiler to find declarations for your modules. the node resolution is mainly to allow you to use node-like systems just like how you would if you wrote directly in JavaScript. so node.js looks for `index.js`, so the ts compiler looks for `index.ts`/`index.d.ts`.

The compiler does not rewrite module names. module names have module-loader-specific semantics, any write the compiler does will break part of the population, e.g. loader plugins, loader configurations, post build scripts that are moving files around, module bundelers etc..

options, you can import the index directly, e.g. `import m from "./module1/index"`, or you can just not use node module resolution.

**Comment by thomas-darling** [comment]
I understand that, and maybe this issue is more complex than it appears, but if the compiler resolves the path to an `index.ts` file, then how much would it really hurt to simply rewrite the path to point to that file? - I mean, if the loader were to resolve that path any different than the compiler, then I wouldn't expect things to work correctly anyway... am I missing something?

It seems there are more and more people using `node` resolution for SPA's, and even the getting started guide for Angular 2 suggests it. There's clearly also a lot of people who find it's concept of an `index.ts` file / folder-as-module to be extremely helpful when structuring large projects, and I don't believe there is a similar concept of a default index file in the `classic` resolution mode, right? Would you consider adding such a feature?

Also, please note the problem with using `node` resolution and at the same time having to reference the `index.ts` file directly, is that the compiler would still be happy if it forgot it and only referenced the folder - but then at runtime, the loader will fail, and that's a nasty surprise. I'm sure that is confusing more than a few developers...

Finally, this issue aside, there seem to be so many changes going on with how path resolution works that I really miss some clear guidance and documentation on this whole thing - is the `classic` resolution even recommended anymore? it seems like all the talk is centered around node these days, and honestly I started getting the feeling that `classic` was more like legacy, and that you wanted to align more with the ES6 and node specifications going forward... So just to be clear, are you saying that `classic` is the officially recommended resolution strategy for new SPA projects? and if so, can you shed some light on why Angular 2 is going against that recommendation?

**Comment by thomas-darling** [comment]
Actually, this quote is an example of why I'm confused about what is recommended:
https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Module%20Resolution.md

> Module Resolution Strategies

> There are two possible module resolution strategies: Node and Classic. You can use the --moduleResolution flag to specify the module resolution strategy. The default if not specified is Node.

> Classic

> This used to be TypeScript's default resolution strategy. Nowadays, this strategy is mainly present for backward compatibility.

This very clearly states that `classic` is legacy and `node` is recommended, so it's a little strange that you guys so often point to that as the solution - honestly, it sometimes feel a little bit like you're focusing too much on server-side node apps, and that people writing for the browser are second-class citizens. From my point of view, it is a pretty big problem that the compiler is happy about code that will never actually work in the browser - such as an import statement pointing to a folder path.

I still strongly believe this needs to work - you absolutely need to do something about this.

**Comment by mhegazy** [comment]
> This very clearly states that classic is legacy and node is recommended, so it's a little strange that you guys so often point to that as the solution - honestly, it sometimes feel a little bit like you're focusing too much on server-side node apps, and that people writing for the browser are second-class citizens.

The browser case is much simpler, it was working since 0.8.* time using classic module resolution. do not see this going away anytime soon. so do not see an issue using it. 
The text in the documentation needs to be less harsh, and do not make it come out as a bad option. we have users with millions of lines of code using this option, and it is not going any where.

Node on the other hand was not working. you import a module from node_modules, and the compiler did not find it. so we added the node module resolution to support that. 

The reason why it is recommended, is more library authors use npm as a mean of package distribution, e.g. angular, rxjs, react, etc.. these libraries, can bundle their definition files with them instead of their users having to go to definitely typed separately. node resolution makes this all work nicely.

> I still strongly believe this needs to work - you absolutely need to do something about this.

not sure i understand the request here.

**Comment by thomas-darling** [comment]
Fair enough - and yeah, the docs definitely need an update then :-)

But still, that means, that if I were to write an Angular 2 app, then I would still like to use `node`, as that would allow it to find the typings. But then the compiler will happily let me to import a folder path, without the `/index` part, even though this is guaranteed to fail at runtime when the browser tries to load it. That's a problem, and that's something that *will* confuse a lot of people - I know I was at first.

I fully understand that it is up to the loader to interpret module names, and that's fine for a loader running on the server - it can look at the file system and determine that a folder import should actually resolve to the `index.js` file. But in the browser, those import statements are always supposed to reference *files* - the loader in the browser can't possibly know whether an import is a file or folder, as it does not have access to the file system - so it always expects a file.

Therefore my request still stands:
In my opinion, the emitted path should include the `/index` part. Maybe what's really missing here is an option or a `node-for-the-browser` resolution strategy that enables this behavior?

If you won't do that, then at least an option to disallow import statements referencing folder paths, as those will fail in the browser anyway...

**Comment by mhegazy** [comment]
I would recommend then using `classic` as a module resolution technique, with `baseUrl` to point to your module root base URL.
For typings for used packages, e.g. angular2, i would use paths to specify where to locate them.

see https://github.com/Microsoft/TypeScript-Handbook/blob/release-2.0/pages/Module%20Resolution.md#path-mapping for more details.
