### ISSUE TITLE
Find References and Dotted JSX Tags

### ISSUE THREAD

**Issue by JKillian** [Microsoft/TypeScript#7637]
**TypeScript Version:** 
1.9.0-dev.20160322

**Code**
```ts
/// <reference path='fourslash.ts'/>

// @Filename: index.tsx
////const /*1*/obj = {Component: () => <div/>};
////const element = </*2*/obj.Component/>;

goTo.marker("1");
verify.referencesCountIs(2);

goTo.marker("2");
verify.referencesCountIs(2);
```

**Expected behavior:**
Test passes

**Actual behavior:** 
Test fails: reference count is 1 at marker 1 and is 0 at marker 2.

**Notes:**
#7622 was great and seemed to fix a lot of bugs! It seems that this one still persists though, as found by @dallonf in https://github.com/palantir/tslint/issues/1010

**Comment by mhegazy** [comment]
@JKillian can you give tomorrow's nightly a try.

**Comment by JKillian** [comment]
@mhegazy Thanks! This seems to have fixed things, sorry for the delay in response.
