### ISSUE TITLE
Possible to add a static method on a union type?

### ISSUE THREAD

**Issue by bcherny** [Microsoft/TypeScript#7641]
I'm using C like a companion object in Scala:

```ts
interface A {
  a: number
}
interface B {
  b: number
}
class C {
  a: number
  b: number
  static c(d: number): number {...}
}
```

How do I express that `C = A|B`? I can do

```ts
interface A {...}
interface B {...}
type C = A|B
```

But then I lose the static method

**Comment by jeffreymorlan** [comment]
Just use a variable, not a class:
```ts
type C = A|B;
var C = {
    c(d: number): number {...}
};
```

**Comment by bcherny** [comment]
Fantastic, that works great! Thanks @jeffreymorlan!
Also, will move these sorts of questions to stackoverflow from now on.
