### ISSUE TITLE
Abstract classes as the default export

### ISSUE THREAD

**Issue by gamedev8** [Microsoft/TypeScript#7647]
Are abstract classes allowed to be the default export in a typescript file? I get a compilation error.

export default abstract class Service {
   ...
}

**Comment by RyanCavanaugh** [comment]
#3792, please search for duplicates before logging new issues.

![image](https://cloud.githubusercontent.com/assets/6685088/13972797/2280ea64-f059-11e5-925a-aee1b3c31c6a.png)
