### ISSUE TITLE
Define Intersection Types that include object literal

### ISSUE THREAD

**Issue by syuilo** [Microsoft/TypeScript#7649]
Nested Intersection Types are supported?

**Code:**
```typescript
interface A {
	nested: {
		kyoppie: string;
	}
}

interface B {
	nested: {
		yuppie: string;
	}
}

const ab: A & B = {
	nested: {
		kyoppie: 'aaa',
		yuppie: 'bbb' // <- Error
	}
};
```

**Got:**
> ```
error TS2322:
Type '{ nested: { kyoppie: string; yuppie: string; }; }' is not assignable to type 'A & B'
  Type '{ nested: { kyoppie: string; yuppie: string; }; }' is not assignable to type 'A'.
    Types of property 'nested' are incompatible.
      Type '{ kyoppie: string; yuppie: string; }' is not assignable to type '{ kyoppie: string; }'.
        Object literal may only specify known properties, and 'yuppie' does not exist in type '{ kyoppie: string; }'.
```

My **TypeScript Version:** 1.8.9

---

Sorry my bad English. Thanks!

**Comment by amir-arad** [comment]
:+1:

**Comment by sandersn** [comment]
It looks like the excess object properties error should not fire when you're checking assignability to a member of an intersection type.

**Comment by sandersn** [comment]
`getRegularTypeOfObjectLiteral` is supposed to mark nested object literals as not-fresh to avoid this error, but it's not recursive. I'll see about making it mark nested object literals as well.

**Comment by sandersn** [comment]
#8605 has the fix -- it makes `getRegularTypeOfObjectLiteral` recursive.

I should change the name `getRegularTypeOfObjectLiteral` but I'm not sure what name is better -- maybe `getNonFreshTypeOfObjectLiteral` ?
