### ISSUE TITLE
Rough estimation dates in roadmap/Release policy

### ISSUE THREAD

**Issue by donaldpipowitch** [Microsoft/TypeScript#7651]
Hi, this is a documentation feature request: Could we add a rough estimation date on the roadmap? No fixed date. Maybe the estimated month or at least the season? It would be nice to know if `2.0` means "summer 2016" or "by the end of 2017".

**Comment by raybooysen** [comment]
Would love to see this.  We're looking at features in 2.1 and would like a general ballpark idea of when these versions will appear.

**Comment by mhegazy** [comment]
We try to keep releases 6-8 weeks apart. last 1.8 went out a week ago. 
Will look into adding dates on the roadmap as well.

**Comment by donaldpipowitch** [comment]
Thank you!

**Comment by NoelAbrahams** [comment]
@mhegazy, I would like to see a pre-release of `--strictNullChecks` if possible. At present it's only available in the nightlies. A pre-release would get you input from a wider audience.

**Comment by mhegazy** [comment]
We are definitely planning a pre-release. we just need to land the emitter work as well (https://github.com/Microsoft/TypeScript/issues/5595). 

and 1.8.9 is the last one actually.

**Comment by NoelAbrahams** [comment]
@mhegazy, okay, thank for the update.

My question was: "Is there a VS plugin for 1.8.9?"


This is all I see:

![image](https://cloud.githubusercontent.com/assets/1106823/14024353/979f07f8-f1e0-11e5-9ae8-277b6ad1ed9a.png)

**Comment by mhegazy** [comment]
yes. :D once it is available, I will update the release page.

**Comment by mhegazy** [comment]
the trick here is synchronizing multiple things at the same time, VSCode releases, VS releases, new language features, etc.. so it is not always easy to give concrete information/dates all the time.

**Comment by mrmckeb** [comment]
@mhegazy I've noted that 1.9 is missing, does that mean that 2.0 will take a little longer? Like @raybooysen, I'm also working on a project that could benefit greatly from some of the 2.1 features.

**Comment by mhegazy** [comment]
> I've noted that 2.0 is the next release, and there's nothing between that and 1.8. Does that mean we should expect 2.0 in the coming weeks?

TS 2.0 is the next release. I do not believe it is ready to be out in the next few weeks. i would expect 4-6 weeks for a public release (likely TS 2.0-beta). 
We are currently looking into TS 2.1 planning and i should have more information to share soon.

> I'm also working on a project that could benefit greatly from some of the 2.1 features.

what features are you specifically looking for?

**Comment by mrmckeb** [comment]
Hi @mhegazy, understood. It looks like there's a lot going in to 2.0!

The absolute biggest feature I'm after is "Support [ES8 object property spread and rest](https://github.com/Microsoft/TypeScript/issues/2103)". It will increase readability of apps greatly, especially when using Redux (which we are). Babel supports this already, but I understand they don't have types to worry about.

I followed the link (issue #2103) and can see that I'm not the only person seeking this feature, but I understand it may be too late to get it into 2.0.

**Comment by mhegazy** [comment]
We might be able to get this done in 2.0.

**Comment by mrmckeb** [comment]
That would be great, as it's a killer feature. Thanks for your time @mhegazy!

**Comment by jaime-olivares** [comment]
The Asp.Net Core project had a clear roadmap with release dates (see https://github.com/aspnet/Home/wiki/Roadmap). I think you should have something similar instead of few rumors in the Issues section.

**Comment by donaldpipowitch** [comment]
I'd love the see a different release policy for TypeScript in the future. I'm a little bit unhappy about how `2.0` will be released.

Maybe TypeScript could adopt Embers pattern:
- Say the current version is `1.x.y`.
- Release new features as `1.(x + 1).y`. If they are very experimental make them only available behind a feature flag.
- Release bug fixes as `1.x.(y + 1)`.
- Deprecate old features (warn about usage).
- Use a major version bump to `2.0.0` only to remove deprecated features. If you have no deprecation warnings in the latest `1.x` version, you should upgrade to `2.0.0` without an error. Don't introduce new features.

What TypeScript currently does with `2.0`:
- Bug fixes are not released separately in patch versions, but as major versions (see https://github.com/Microsoft/TypeScript/issues/7566#issuecomment-217971515).
- New features are released in one big bang. This makes upgrading harder and slows down adoption of new features, which are already finished.
- No clear deprecations (?)

// cc @otbe

**Comment by donaldpipowitch** [comment]
@mhegazy Will there be a new release policy in the post-2.0-era?

**Comment by mhegazy** [comment]
yes. I should be updating the roadmap with tentative release dates in the next few days. so stay tuned.

**Comment by donaldpipowitch** [comment]
Nice, thank you!

**Comment by mhegazy** [comment]
Thanks for the feedback. [Road map](https://github.com/Microsoft/TypeScript/wiki/Roadmap) should be updated now to reflect the plan for TypeScript 2.1, also including planned release dates. we are currently targeting November 2016 for this release. moving forward we will include planned release dates for milestones as they appear.
