### ISSUE TITLE
Allow making string literal / type interaction DRY-er

### ISSUE THREAD

**Issue by johnnyreilly** [Microsoft/TypeScript#7653]
I have a module which exports a const which represents css classes.  It also exports a type which is a string literal restricting usage to just those types.

Presently I have to do this:

```
export const validationCssClasses = {
    warning: "input-validation-warning",
    error: "input-validation-error"
}

export type validationCssClass = "input-validation-warning" | "input-validation-error";
```

It would be quite nice to be able to do this:

```
export const validationCssClasses = {
    warning: "input-validation-warning",
    error: "input-validation-error"
}

export type validationCssClass = validationCssClasses.warning | validationCssClasses.warning;
```

Which would hopefully avoid the possibilities of typos etc sneaking in.  

Are there any plans in this area?

**Comment by johnnyreilly** [comment]
I'm aware that there is something of a "chicken and egg" issue in terms of usage already in that `validationCssClasses.error` and `validationCssClasses.warning` have to be cast to `validationCssClass` when being used.  So this may be a more complex feature than I'd originally thought....

**Comment by mhegazy** [comment]
looks like a string-based enum (https://github.com/Microsoft/TypeScript/issues/3192)
