### ISSUE TITLE
Type guards in Array.prototype.filter

### ISSUE THREAD

**Issue by calebegg** [Microsoft/TypeScript#7657]
**TypeScript Version:** 

nightly (1.9.0-dev.20160323)

**Code**

``` ts
let numbers: number[] =
    [1, '2', 3, '4'].filter(x => typeof x !== 'string');

declare function isNumber(arg: any): arg is number;
let numbers2: number[] = [1, '2', 3, '4'].filter(isNumber);
```

[Playground](http://www.typescriptlang.org/Playground#src=let%20numbers%3A%20number%5B%5D%20%3D%0A%20%20%20%20%5B1%2C%20'2'%2C%203%2C%20'4'%5D.filter%28x%20%3D%3E%20typeof%20x%20!%3D%3D%20'string'%29%3B%0A%0Adeclare%20function%20isNumber%28arg%3A%20any%29%3A%20arg%20is%20number%3B%0Alet%20numbers2%3A%20number%5B%5D%20%3D%20%5B1%2C%20'2'%2C%203%2C%20'4'%5D.filter%28isNumber%29%3B)

**Expected behavior:**
.filter with a type guard returns an array of the specified type. This would be especially useful with `--strictNullChecks`, so we could do something like `foo.map(maybeReturnsNull).filter(x => x != null)....`

**Actual behavior:** 
.filter returns an array of the same type, and the two `let`s above are errors.

**Comment by RyanCavanaugh** [comment]
The required overload is
```ts
interface Array<T> {
	filter<U extends T>(pred: (a: T) => a is U): U[];
}
```

**Comment by calebegg** [comment]
Wow, I didn't realize it would be that easy. It doesn't fix the first case (presumably because the function is not getting recognized as a type guard function), but it does work with a cast:

```ts
let numbers: number[] =
    [1, '2', 3, '4']
	    .filter(<(x) => x is number>(x => typeof x == 'number'));
```

Would inferring that `x => typeof x == 'number'` is a type guard be a good candidate for a separate suggestion? Or is it too specific? (I didn't see anything in the tracker already).

**Comment by DanielRosenwasser** [comment]
The problem I ran into with adding the overload into `lib.d.ts` was that it doesn't work with `Array.isArray`, and I don't entirely recall why. We could investigate this a bit.

**Comment by NoelAbrahams** [comment]
Looks to be the same as #2835

**Comment by RyanCavanaugh** [comment]
(context: #2835 was long before we had type guards)

**Comment by bcherny** [comment]
if someone can patch this to lib.d.ts, i could get rid of so many asserts in my code.

**Comment by Loilo** [comment]
Is there some place to read up about the "is" in @RyanCavanaugh's [overloading code](https://github.com/Microsoft/TypeScript/issues/7657#issuecomment-200447063) above? Couldn't find it anywhere, neither in [this issue about reserved keywords](https://github.com/Microsoft/TypeScript/issues/2536) nor on the pages linked from there.
Also Google wasn't helpful this time.

**Comment by RyanCavanaugh** [comment]
@Loilo see #1007

**Comment by Loilo** [comment]
Thank you!

**Comment by mhegazy** [comment]
Documentation for user defined type guards is available in the language handbook at: http://www.typescriptlang.org/docs/handbook/advanced-types.html#user-defined-type-guards

**Comment by Loilo** [comment]
Yes, now that I know the name of the feature I was already able to find information about it. Thanks anyway. :)

**Comment by PanayotCankov** [comment]
Wow :+1: to add @RyanCavanaugh 's suggestion in the lib.d.ts. I was having something like:
```
interface Node {
	astType: "node" | "rule";
}
interface Rule extends Node {
	ruleSomething: string;
}
function isRule(node: Node): node is Rule {
	return node.astType === "rule";
}
let nodes: Node[] = [];
nodes.filter(isRule).forEach(rule => console.log(rule.ruleSomething));
```
It is magical. :heart:

**Comment by jesseschalken** [comment]
@calebegg You can just add `:x is number` to the signature rather than using a cast:

```ts
let numbers: number[] =
    [1, '2', 3, '4']
        .filter((x):x is number => typeof x == 'number');
```

In principle this would allow the compiler to check that `x is number` does in fact follow from `typeof x == 'number'`, but I don't think it bothers checking that (TS 1.8).

**Comment by bcherny** [comment]
A few more cases (using TS2.0):

```ts
// setup
class A { type = 'A' }
class B { type = 'B' }
type C = A | B
function isA(_): _ is A { return _.type === 'A' }
const cs: C[] = [new A(), new B(), new B()]

// (1) - OK
let as = cs.filter(isA)

// (2) - Not OK - type is still C[]
let as = cs.filter(_ => isA(_))

// (3) - Not OK - type is still C[]
let bs = cs.filter(_ => !isA(_))
```

**Comment by bcherny** [comment]
@mhegazy I don't think https://github.com/Microsoft/TypeScript/pull/10027 fixed this. The issue in (2) and (3) is that the type guard seems to be generalized to a boolean when called by an outer function.

**Comment by Arnavion** [comment]
@bcherny See #5951 and #5101 for that.

**Comment by mhegazy** [comment]
The issue for 2  is that the type guards are not inferred as return type of the second function, and for 3 it is even more advanced, you are expecting type operations to happen on the guard and "deduce" a new guard. the two are things that are not happening right now. the change to filter is really orthogonal here. feel free to log a new issue for that.

**Comment by bcherny** [comment]
@mhegazy Is this the same as #5101, or would you prefer a new issue?

**Comment by mhegazy** [comment]
do not think the case listed in `let bs = cs.filter(_ => !isA(_))` is covered by  #5101. nor does it cover the general case of aliasing:

```ts
function isNumber(a): a is number {
....
}

function myIsNumber(a) {
    return isNumber(a);
}

var x: number | string;
if (myIsNumber(x)) {
    x.toExponential..
}
```

**Comment by bcherny** [comment]
Filed https://github.com/Microsoft/TypeScript/issues/10734

**Comment by Arnavion** [comment]
#10027 also didn't add the overload to `Array#filter`, only to `ReadOnlyArray#filter`. @mhegazy could you reopen this issue?

**Comment by mhegazy** [comment]
Thanks @Arnavion. A PR would be appreciated.

**Comment by OliverJAsh** [comment]
Does this work with discriminated unions? My understanding is that, with @RyanCavanaugh's [overload](https://github.com/Microsoft/TypeScript/issues/7657#issuecomment-200447063), you still need user defined type guards. E.g:

``` ts
    const numbers: number[] = [1, '2', 3, '4']
        .filter((x):x is number => typeof x == 'number')
        .map(y => y)
```

Surely with TypeScript 2's discriminated union types, we can drop the type guard here somehow? I'm not sure how, though!

``` ts
    const numbers: number[] = [1, '2', 3, '4']
        .filter(x => typeof x == 'number')
        .map(y => y)
```

**Comment by OliverJAsh** [comment]
@RyanCavanaugh I'm also curious how this will help when you're filtering on properties, e.g.:

```
// https://github.com/Microsoft/TypeScript/issues/8123
// Will be fixed in TS 2.1
declare global {
    interface Array<T> {
        filter<U extends T>(pred: (a: T) => a is U): U[];
    }
}

const numbers: number[] = [1, '1']
    .filter((x): x is number => typeof x == 'number')
    .map(y => y) // y is number, good!

const numbers2: number[] = [{ foo: 1 }, { foo: '1' }]
    .filter(x => typeof x.foo == 'number')
    .map(y => y.foo) // y.foo is number | string, not good!
```

**Comment by Arnavion** [comment]
`.filter(x => typeof x.foo == 'number')` fails for the same reason that `.filter(x => typeof x == 'number')` would fail - missing return type on the predicate means it's inferred as returning Boolean and not a type guard.

You want `.filter((x): x is { foo: number } => typeof x.foo == 'number')`

**Comment by OliverJAsh** [comment]
Thank you!

Any ideas where discriminated unions will/can help here, or do we have to provide user defined type guards?

**Comment by rob3c** [comment]
I'm trying to get something similar working in `rxjs`, and I'm not sure if it's failing because of a current TypeScript limitation, or if the rxjs type definition for `filter` just needs updating. Here's the rxjs definition as of `rxjs@5.0.0-rc.1`:
```typescript
// definition 1
export declare function filter<T>(
    this: Observable<T>, 
    predicate: (value: T, index: number) => boolean, 
    thisArg?: any
): Observable<T>;

// definition 2
export declare function filter<T, S extends T>(
    this: Observable<T>, 
    predicate: (value: T, index: number) => value is S, 
    thisArg?: any
): Observable<S>;
```
Definition 2 looks like it's trying to implement the `U extends T` strategy mentioned above for `Array<T>`, but it doesn't seem to work due to a clash with definition 1.

Here's a contrived example of using a type guard with `filter` in addition to a regular boolean expression, but the two clashing definitions prevent both from working correctly (see comments):
```typescript
interface Action { type: string; }
class FooAction implements Action { type = 'FOO'; name = 'Bob'; }

function isFooAction(action: Action): action is FooAction {
    return action && action.type === 'FOO';
}

var bob$: Observable<Action> = someActionObservable
    .filter(isFooAction) // I'd like this to cause map to see a FooAction instead of just Action below
    .map(foo => foo.name) // foo is FooAction with definition 1 commented-out, Action otherwise
    .filter(foo => foo.name === 'Bob'); // fails to compile without definition 1
```

Is there a magic type definition tweak I can make to avoid cluttering the method chain with unnecessary casts? It seems like there should be some way to flow the type info through method chains like this without a conflict.

**Comment by josundt** [comment]
Please add the overload but not to lib.es5.d.ts in addition to lib.d.ts.
It seems it does not work with my compilerOptions.lib = ["dom", "es5", "es2015.promise"]

**Comment by Arnavion** [comment]
@josundt See #10916

**Comment by OliverJAsh** [comment]
How can you use type predicates to negate a type? For example:

``` ts
[1, 'foo', true].filter((x): x is not number => typeof x !== 'number')
```

**Comment by janslow** [comment]
Not ideal, but this works for primitives. Although, it might be easier to leave that unguarded.
```typescript
type NotNumber = Object | string | symbol | undefined | null | boolean | Function;
function notNumber(x: any): x is NotNumber {
    return typeof x !== 'number';
}
```

**Comment by bcherny** [comment]
> Any ideas where discriminated unions will/can help here, or do we have to provide user defined type guards?

@mhegazy @RyanCavanaugh Possible for one of you guys to chime in here? It's a lot of friction to have to (a) explicitly parametrize or (b) explicitly type guard every `.filter` call.

**Comment by gasi** [comment]
I tried the type guard [as follows](http://www.typescriptlang.org/play/#src=type%20FooBar%20%3D%20Foo%20%7C%20Bar%0A%0Ainterface%20Foo%20%7B%0A%20%20%20%20type%3A%20%27Foo%27%0A%7D%0A%0Ainterface%20Bar%20%7B%0A%20%20%20%20type%3A%20%27Bar%27%0A%7D%0A%0Aconst%20fooBars%3A%20Array%3CFooBar%3E%20%3D%20%5B%0A%20%20%20%20%7B%20type%3A%20%27Foo%27%20%7D%2C%0A%20%20%20%20%7B%20type%3A%20%27Bar%27%20%7D%2C%0A%5D%0A%0Aconst%20foos%3A%20Array%3CFoo%3E%20%3D%20fooBars.filter(%0A%20%20%20%20(item)%3A%20item%20is%20Foo%20%3D%3E%20item.type%20%3D%3D%3D%20%27Foo%27%0A)) with no luck:

```typescript
type FooBar = Foo | Bar

interface Foo {
    type: 'Foo'
}

interface Bar {
    type: 'Bar'
}

const fooBars: Array<FooBar> = [
    { type: 'Foo' },
    { type: 'Bar' },
]

const foos: Array<Foo> = fooBars.filter(
    (item): item is Foo => item.type === 'Foo'
)
```

**Comment by mvestergaard** [comment]
Is this related to [this problem](http://www.typescriptlang.org/play/index.html#src=const%20foo%20%3D%20%5B1%2C%202%2C%20undefined%2C%203%5D%3B%0D%0Afoo%0D%0A%20%20%20%20.filter(n%20%3D%3E%20n)%0D%0A%20%20%20%20.map(n%20%3D%3E%20n.toString())%3B)? Make sure to enable strictNullChecks.

I would expect the control flow here to know that in the .map, the value is number and not undefined.
I find that this problem forces me to write much less readable code, because I have to jump through hoops to get around the type system tripping up.

If this is the same issue, is there any plans to make this scenario work in the near-ish future?

**Comment by maiermic** [comment]
This issue has been fixed by #16223 and can be closed. You can try it out in `typescript@2.5.0-dev.20170712` for example.

**Comment by calebegg** [comment]
@maiermic: Are you sure? I still get an error on this code:

```typescript
['a', undefined].filter((e): e is string => !!e)[0].substring(0, 10);
```

```
test.ts(1,1): error TS2532: Object is possibly 'undefined'.
```

[Playground](http://www.typescriptlang.org/play/#src=%5B'a'%2C%20undefined%5D.filter((e)%3A%20e%20is%20string%20%3D%3E%20!!e)%5B0%5D.substring(0%2C%2010)%3B%0D%0A) (be sure to check "strictNullChecks" in options to see the error)

**Comment by maiermic** [comment]
@calebegg That looks like a bug to me. Your example works if you use a function declaration instead of the lambda:

```ts
['a', undefined].filter(isString)[0].substring(0, 10);

function isString(e): e is string {
    return !!e
}
```

**Comment by NaridaL** [comment]
@calebegg I opened an issue... in the meantime, specifying the type of e explicitly is a workaround:

```ts
['a', undefined].filter((e: any): e is string => !!e)[0].substring(0, 10);
                          ^^^^^
```

**Comment by calebegg** [comment]
@NaridaL Interesting, thanks for identifying the issue!
