### ISSUE TITLE
[Question] - Is there a syntax for defining interface properties of the same type on the same line?

### ISSUE THREAD

**Issue by dsifford** [Microsoft/TypeScript#7659]
Hello, 

Sorry if this has been asked before. The issue history is massive and I couldn't locate it if it has. I also checked SO but didn't find anything.

I'm coming from Golang and one thing that I like from there is the ability to declare properties of the same type on the same line (It reads cleaner IMO). 

Is this possible with Typescript?

Here's how I'd define an interface (struct type) in Go
```go
type person struct {
        firstName, lastName string
        age int
}
```

Here's how I do the same thing currently in TypeScript
```ts
interface person {
  firstName : string
  lastName : string
  age : number
}
```

Here's how I'd like to do it
```ts
interface person {
  firstName, lastName : string
  age : number
}
```

Thanks for the clarification! :smile:

**Comment by mhegazy** [comment]
It is not allowed to define multiple member declarations in the same declaration statements for interfaces, or classes. nor is it allowed for variable declarations.

to get this behavior you will need to specify the type for each member. If no type is specified, the type is `any`.

this also applies for variable declarations.

```ts
var x, y : number;  // x : any, y: number
```

**Comment by dsifford** [comment]
Understood! Thanks for the quick reply! :+1:
