### ISSUE TITLE
Index signature arguments are not type checked based on the specialized key type they are constrained to

### ISSUE THREAD

**Issue by malibuzios** [Microsoft/TypeScript#7660]
**TypeScript Version:** 

1.8.7

**Code**

```ts
type OnlyNumberKeys = {[key: number]: any};
let a: OnlyNumberKeys = {};

a["abcd"] = 1; // No error?
let x = a["abcd"]; // No error?
```
```ts
type OnlyStringKeys = {[key: string]: any};
let b: OnlyStringKeys = {};

b[1234] = 1; // No error?
let y = b[1234]; // No error?
```
**Expected behavior:**
Should error

**Actual behavior:** 
Doesn't error

_(Sorry if this is a duplicate but a search did not yield anything on this)_

**Comment by RyanCavanaugh** [comment]
The first example is an error under `noImplicitAny`.

The second is by design -- indexing by a number is a subset of indexing by a string, so indexing by a number when a string would have been valid is also valid.

**Comment by malibuzios** [comment]
@RyanCavanaugh 
I'm not sure exactly what the logic is on why the first one errors on `noImplicitAny`?

I renamed the title to a more accurate one, as the keys are of course checked, but not to the specialized key type. 

I also tested in ES6 mode for `Symbol`, and it also did not error on both cases:

```ts
type OnlyNumberKeys = { [key: number]: any };
let a: OnlyNumberKeys = {};

a[Symbol("abcd")] = 1; // No error?
let x = a[Symbol("abcd")]; // No error?
```
```ts
type OnlyStringKeys = { [key: string]: any };
let b: OnlyStringKeys = {};

b[Symbol("abcd")] = 1; // No error?
let y = b[Symbol("abcd")]; // No error?
```

**Comment by jods4** [comment]
Indexing is special because it's the built-in JS way to perform "reflection", i.e. to access a field dynamically at runtime.
```typescript
type X = { length: number; [key: number]: string };
let some: X;
let len = some['length']; // equivalent to some.length;
let dynamic = "length";
len = some[dynamic]; // works at runtime, treated as any at compile time
```

And because the result of dynamic access has to be `any`, doing so is an error under `--noImplicitAny`. _But_ it turned out to be an important enough scenario to be allowed even in no implicit any code, with its sibling option `--suppressImplicitAnyIndexErrors`.

I think a similar argument can be made for `Symbol`.

**Comment by malibuzios** [comment]
@jods4 @RyanCavanaugh 

I'm aware that square bracket notation was designed to become a "back door" where anything can be accessed. I do use it myself occasionally, however I don't remember a case I needed it when an object had an explicit index signature. The reason is very simple:

Since an index signature was designed to "open up" access to what is usually a large amount of key space, such as "all the strings", "all the numbers" and even "all the symbols" (though that is not supported yet, I will open an issue for that later if needed) or a combination of them. One can always write something like:
```ts
type OnlyStringOrNumberKeys = { [key: string | number]: any };
type OnlyStringOrSymbolKeys = { [key: string | Symbol]: any };
type OnlyNumberOrSymbolKeys = { [key: number | Symbol]: any };
```
I mean what really is the benefit of allowing the programmer to specify a parameter type if it is not actually enforced?

There's a very good reason I'm mentioning this at this particular time. The reason is that in light of a proposal like #5683 (also see the duplicate #7656) which is currently in discussion, where the key would be constrained to a finite set of string literal or possibly numbers (with numeric literals), there's not much point of implementing it of keys types are not checked at all. E.g. you had something like:

```ts
type OnlySomeStringLiteralKeys = { [key: "A" | "B" | "C"]: any };
x: OnlySomeStringLiteralKeys = {};

x["D"] = 1; // Error, key is not assignable to "A" | "B" | "C"
```
What benefit would that give if you can "by design" still do things like:
```ts
x[4385] = "a";
x[Symbol("abcd") = 12;
```
?

**Comment by jods4** [comment]
> I mean what really is the benefit of allowing the programmer to specify a parameter type if it is not actually enforced?

You make a good point. 

But I think disallowing dynamic access completely on those objects is too much collateral damage.

In `noImplicitAny` code, but with `suppressImplicitAnyIndexErrors`, I have seen this done:
```typescript
let arr: number[];

let x = arr[4]; // array indexer -> x: number
// dynamically augment the array with metadata or additional infos
x['priority'] = 'high';  // ok...
```

This is certainly not the best code, and you probably should use an intersection type to describe your array `number[] & Metadata` but just sayin' I've seen things like that.

Not sure what the best approach is here.
Some thoughts:
- If an indexed access is specific (with upcoming string or symbol literals support), then it should be OK and properly typed.
- Otherwise, if you run without `noImplicitAny` or with `suppressImplicitAnyIndexErrors` I don't think you really can forbid a dynamic access?

Perhaps some real-world examples could help better define a solution?

**Comment by malibuzios** [comment]
@jods4 

I'm not sure if internally `Array` type is bound by the rules of the `{ [x: number]: any }` interface. I think it is a type that is handled separately. I can understand that in other types like Node's `Buffer` that may actually be the case. So you're right that for something like:
```ts
interface NodeBuffer {
	[index: number]: number;
        ... Lots of properties follow ...
}
```
It would break the ability to "back door" into, say, undocumented properties. The simplest workaround that one would need to either cast it to `any`:
```ts
let buf: Buffer;
(<any> buf)["undocumentedProperty"] = 12;
```
Or use some sort of a intersection type (though I don't think that would be something that would appeal or even be understood by beginners).

But I can see this becoming a bit tedious when it is frequently used, and it would break some existing code, so I agree this would be a major problem if key checking was stricter. Unfortunately I don't really have a good alternative solution for this at this point.

Anyway, as for a real-world example (other the ones described in #7656 for the string literal keys). In the case of "symbols keys only" signatures I could see an example where I have a function that _only_ cares about the metadata hidden inside some object so ideally it would be nice to have a type the basically sees anything thrown at it as just a bunch of symbols, and no more:

```ts
function iOnlyCareAboutTheSymbolsInWhateverYouGiveMe(x: any) {
  let symbolsOnlyHere: { [key: symbol]: any } = x;
  // ... do something with the hidden metadata ...
}
```

**Comment by jods4** [comment]
Nitpicking maybe, but it's not just a "backdoor". It's how you can access members _dynamically at runtime_.
There are good use cases for that. E.g. try to write a serializer, a string format or an ORM without it.
It's like saying Reflection in .net is a "backdoor", although it's the backbone of many frameworks and features.

Regarding examples:
- `symbolsOnlyHere` is not very compelling. The value over using `x: any` is quite low.
- From #7656 I feel like some examples over there would be better served with properly typed members or using a real `Map`, now that they are commonplace.

Probably the most compelling example so far is this one of yours:
```typescript
type RequestMethod = "GET" | "SET" | "PUT" | "UPDATE" | "DELETE";
type HandlerObject = { [key: RequestMethod]: (requestObject: RequestObject) => boolean; };
```
I think this is desirable but I'm not sure what the best way to proceed here is.

Another thing I haven't seen mentionned yet: how should it work with generics?
```typescript
function dump<T>(obj: T) {
  for (let prop in obj)
    console.log(obj[prop]);  // <-- trouble spot
}

let hi = { greetings: "hello world" };
dump(hi);  // sure.

interface SymbolsOnly { [key: symbol]: any };
dump<SymbolsOnly>(hi);  // ok or not? there's indexed access in dump, which may not be a symbol.
```

**Comment by malibuzios** [comment]
@jods4 

I'm trying to figure out what is the actual effect of having index signature key types at the first place, also considering what would happen string literals are allowed. E.g:

```ts
let x: { [key: number] : Array<number> };
```
There seem to be two different interpretations of what this should mean:

1. You can only index `x` using a `number` when using square brackets, which would give you a value of type `Array<number>`.
2. If you index `x` using using a `number` key using square brackets, you get a value of type `Array<number>`, but if you index something else you get `any` (this is how this works today).

Now let's take this to string literals:
```ts
let x: { [key: "A" | "B" | "C" ]: Array<number> };
```
1. You can only index `x` using a "A", "B" or "C" using square brackets, which would give you a value of type `Array<number>`.
2. If you index `x` using using "A", "B" or "C" using square brackets, you get a value of type `Array<number>`, but if you index something else you get `any`.

The second option here wouldn't seem to be be very useful in this case as I feel it is not strict enough, so I'm afraid that if the semantics of indexer key types were generally intended to be this way then I would personally recommend against implementing #5683 at this point. I'm also considering the fact that `{ [key: "A" | "B" | "C" ]: Array<number> }` seem like it [may be assigned from anything](https://github.com/Microsoft/TypeScript/issues/7656#issuecomment-200493231) if interpreted as an [all-optional type](https://github.com/Microsoft/TypeScript/pull/3842).

**Comment by jods4** [comment]
@malibuzios 
2. seems obvious.
1. I don't know. On one hand it makes sense to restrict to the type def. On the other, you break all dynamic access on the object (could get it back by explicit casting to `any`).

Another aspect of indexers is that JS does not allow you to define your own indexer (like say C#). So using an indexer is in fact _always_ going through the JS _associative array_ design.
In that context, defining specific indexer keys and types seems to only make sense for "collections" objects.
_Maybe_ that's an argument for 1. Not sure, though <_<

**Comment by malibuzios** [comment]
I'm assuming the behavior described for key type checking is by design. Essentially - there is no type checking and any indexer would take `string`, `number` or `symbol` regardless of the key type. This was a very important investigation that lead me to recommend not to implement string literal as key types, as strictness of the type checking they would receive would be too weak to catch important errors.

E.g:
```ts
let x: { ["A", "B", "C"]: number } = {};

x["A"] = 1; // OK
x["D"] = 1; // No error
x[12] = 1; // No error
x[Symbol("abc")] = 1; // No error;
```
The alternative - the all optional interface:
```ts
let x: { A?: number, B?: number, C?: number} = {};
```
Would have a sufficient level of checking when using the dot notation (e.g. `x.A = 1`), but would be limited to names that can be used as property identifiers, and the set of possible property names would not be possible to reference as an external type.

It seems very unlikely the `[]` notation would get stricter type notation any time soon so I have decided to close this issue.
