### ISSUE TITLE
Narrowing breaking changes

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript#7662]
This is a place holder for changes to the type narrowing behavior in TypeScript 2.0:

* Type aliases are now narrowed
```ts
function g<T>(obj: T) {
    var t: T;
    if (obj instanceof RegExp) {
         t = obj; // RegExp is not assignable to T
    }
}
```

* Type narrowing does not work for catprued variables in functions and class expressions

```ts
export class Class {
    constructor(public p) { }
}

var c: Class | string;
var x: Class;

if (c instanceof Class) {
    function inner() {
        x = c; // Error, type of c is not narrowed, c is Class | string
    }
    x = c; // OK, c is Class
}
```

**Comment by ivogabe** [comment]
In the first example `obj` should be narrowed to `T & RegExp`, that seems more correct. Is that doable?

**Comment by mhegazy** [comment]
narrowing makes the type more "specific", this seems like expanding the domain of the type.

**Comment by ivogabe** [comment]
I thought that "more specific than" means "subtype of". That would mean that narrowed types are always a subtype of their original type and also always assignable to the original type. `RegExp` is not a subtype of all possible types for `T`, since it is a type argument, but `T & RegExp` is a subtype of it. Or is there something that I missed?

**Comment by mhegazy** [comment]
Type parameter narrowing is tracked by https://github.com/Microsoft/TypeScript/issues/8563

**Comment by Strate** [comment]
Can typescript track that variable isn't changed after bypassing to callback and keep that narrow inside callback?
i.e:
```typescript
{
  let aOrB: A|B = getAOrB()
  if (isA(aOrB)) {
    performOperationA(() => aOrB /* is A here */)
  } else {
    performOperationB(() => aOrB /* is B here */)
  }
  // there is no write-aware operations on aOrB after this point, seems that typescript may be able to catch this case and keep var narrow inside callbacks.
}

```

**Comment by mhegazy** [comment]
> Can typescript track that variable isn't changed after bypassing to callback and keep that narrow inside callback?

it can be done, but that is not trivial amount of computing, and would impact compilation times for all projects.

**Comment by Arnavion** [comment]
@Strate In that case you can yourself use `const` instead of `let` and get that behavior.
