### ISSUE TITLE
How I  get the Class Name in  TypeScript ?

### ISSUE THREAD

**Issue by lusess123** [Microsoft/TypeScript#7665]
var a: Greeter = new Greeter();
alert(typeof(a));

why   is  "Object" , rather than  "Greeter" ?

**TypeScript Version:** 

1.7.5 / 1.8.0-beta / nightly (1.9.0-dev.20160217)

**Code**

```ts
// A self-contained demonstration of the problem follows...

```

**Expected behavior:**

**Actual behavior:**

**Comment by yortus** [comment]
This is really a question about JavaScript semantics, not TypeScript specifically.

[Here's](http://stackoverflow.com/questions/10314338/get-name-of-object-or-class-in-javascript) a relevant StackOverflow page which answers this question and, as with all things JavaScript, points out some of the gotchas.
