### ISSUE TITLE
Typescript not merging interfaces from lib.d.ts

### ISSUE THREAD

**Issue by kuza55** [Microsoft/TypeScript#7669]
**TypeScript Version:** 

1.8.9
**Code**

```ts
interface Window {
    URL;
}
```

**Actual behavior:** 

When upgrading typescript versions, new definitions were added to lib.d.ts, and these new definitions cause conflicts with definitions we had in our project.

This makes it annoying to upgrade typescript since we have to introduce a change to the code that breaks anyone using an old compiler.

**Expected behavior:** 
Typescript would merge the types in my project definitions with lib.d.ts without complaint.

**Comment by oising** [comment]
TypeScript _does_ merge interfaces without complaint, but you have a merge *conflict* for identically named members. I'm not sure I would want typescript to automatically choose a side for a merge conflict. What if it's got the same member name and different parameters? Which definition should win? And what is the logic behind it?

**Comment by mhegazy** [comment]
As @oising explained, a duplicate definition is not something that will be merged, it is assumed to be an error.

one thing to note, using `--noLib`, you can specify your own version of the library, be it an older version of lib.d.ts or a custom one.
