### ISSUE TITLE
Crash when formatting template strings

### ISSUE THREAD

**Issue by SaschaNaz** [Microsoft/TypeScript#7686]
**TypeScript Version:** 1.8.4

IDE: VS2015

```ts
`${""}`;
`
    ${""}
}`;//Put cursor here and tap enter to see crash
```

**Expected behavior:** No crash

**Actual behavior:**

```
Error executing script:

Description:
getFormattingEditsAfterKeystroke('...', 29, '
')

Message:


StackTrace:
Error: Debug Failure. False expression:
  at assert(:1676:17)
  at consumeTokenAndAdvanceScanner(:45618:21)
  at processChildNode (:45554:25)
  at processChildNodes (:45601:25)
  at Anonymous function (:45515:21)
...
```

**Comment by billti** [comment]
Which editor/where are you seeing this? I just tried in VSCode using the latest from `release-1.8` as well as the `master` branch and don't see any issue.

**Comment by SaschaNaz** [comment]
VS2015. Copy-pasting the code to `test.ts`, opening the file on a separate instance of VS, and tapping enter on the specified position reproes this on my environment.
