### ISSUE TITLE
Importing scoped npm modules without scope name

### ISSUE THREAD

**Issue by sasidhar** [Microsoft/TypeScript#7695]
This is a question.

We have some private NPM packages using npmjs' private repository. Assume

- scope name : `@scope`
- private package name as : `private-package`

When we install this NPM package using 
```npm install @scope/private-package``` 

It is installed to : ```./node_modules/@scope/private-package```

In VSCode, to import some thing from this package, we need to do
```import {SomeThing} from '@scope/private-package'```

Is there anything in TypeScript configuration that we can re-map
```@scope/private-package``` to ```private-package``` 
so that we can use like 
```import {SomeThing} from 'private-package'``` instead of adding`@scope`?

**Comment by Arnavion** [comment]
See `paths` tsconfig.json option - https://github.com/Microsoft/TypeScript/issues/5039#pathMappings and https://github.com/Microsoft/TypeScript/pull/5728

**Comment by sasidhar** [comment]
@Arnavion Thanks for the references.
I tried `paths` with 1.8.9 and found it is not yet out.
Seems it is planned for 1.9.0.
