### ISSUE TITLE
Arrays using an array type interface don't have the array library

### ISSUE THREAD

**Issue by FayneAldan** [Microsoft/TypeScript#7696]
**TypeScript Version:** 

1.8.9

**Code**

```ts
var array: {[str: number]: string} = [];
array.push('test');
```

**Expected behavior:**
I would be able to add elements to the empty array by using `push` or `unshift`.

**Actual behavior:**
`test.ts(2,7): error TS2339: Property 'push' does not exist on type '{ [str: number]: string; }'.`

**Comment by Arnavion** [comment]
Why do you expect that? In `var foo: Base = new Derived();` do you also expect that `foo` should have members of `Derived` that are not members of `Base` ?

Also, if your intent is to have a string array, then you can just say `var array: string[] = []`

**Comment by DanielRosenwasser** [comment]
I think @FayneAldan may have a misunderstanding of how to specify the type of an array.

The type annotation you probably wanted was `string[]`:

```ts
let array: string[] = [];
array.push("test"); // works!
```

If not, then @Arnavion's correction is the issue at hand.
