### ISSUE TITLE
void type variables should be able to be passed to a function's optional params

### ISSUE THREAD

**Issue by FayneAldan** [Microsoft/TypeScript#7697]
**TypeScript Version:** 

1.8.9

**Code**

```ts
interface Callback { (result?: string): void; }

function printError(msg: string): void {
	// Print the error to the user.
}

function checkAsyncThing(cb: Callback): void {
	// If we can't do the check, we want to print the error and run the cb.
	// This is done in one line for convenience, but this practice upsets TS...
	if (/* condition */ true) return cb(printError("We can't check this. :("));
	// Here, we would do the check.
}
```

**Expected behavior:**
I would be able to chain functions like I have done in `checkAsyncThing`, which is a semi-common practice in regular JavaScript.

**Actual behavior:** 
I would receive the error:
`test.ts(10,38): error TS2345: Argument of type 'void' is not assignable to parameter of type 'String'.`

To fix the problem, I would have to change `result`'s type in `Callback` to `string | void` or change the `if` statement in `checkAsyncThing` to:
```ts
if (/* condition */ true) {
	printError("We can't check this. :(");
	return cb();
}
```
This shouldn't be necessary, however, since printError doesn't even return anything.

**Comment by jeffreymorlan** [comment]
Using a `void` value as an argument almost always means the programmer incorrectly thought the `void`-returning function actually returned something useful.

If you really want to cram two unrelated function calls into one expression to avoid braces, you can do it much less confusingly with the comma operator:
```ts
if (true) return cb(printError("foo"));     // Error
if (true) return (printError("foo"), cb()); // OK
```

**Comment by DanielRosenwasser** [comment]
I have to agree with @jeffreymorlan on this. This sort of thing is error-prone, has an easy workaround, and doesn't really have a way to play nicely with non-nullable types.

**Comment by FayneAldan** [comment]
I did not actually know about the comma operator. Thanks!
