### ISSUE TITLE
Unable to rename re-exported identifiers

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#7708]
VS2015

**TypeScript Version:** 

1.8.6

**Code**

Rename `var a` to `var c` in `a.ts`.

```ts
// a.ts
export var a;
// b.ts
import {a} from './a';
export {a}
```

**Expected behavior:**

```ts
import {c} from './a';
export {c}
```

**Actual behavior:** 

```ts
import {c} from './a';
export {a}
```

**Comment by RyanCavanaugh** [comment]
I believe this is the same root cause as #6312. Moving the repro over there.

**Comment by sheetalkamat** [comment]
Opening this to make sure this gets covered. This is little bit different from #6312
