### ISSUE TITLE
Super constructor return ignored

### ISSUE THREAD

**Issue by whitneyit** [Microsoft/TypeScript#7710]
**TypeScript Version:** 

nightly (1.9.0-dev.20160313)

**Code**

```ts
class Collection extends Array {

    constructor(...args) {
        const first = arguments[0];
        if (args.length === 1 && typeof first === 'number') {
            super(first, null);
            this.pop();
        } else {
            super(...args);
        }
    }

}

const a = new Collection(3, 2, 1);
const b = new Collection(3);
console.log(a, b);
```

**Expected behavior:**
The `Array` is correctly subclassed and the instances are created correctly.

**Actual behavior:** 
The instances are not created correctly.

**Notes:**
 * This code works in the [babel repl](https://babeljs.io/repl/#?evaluate=true&presets=es2015%2Cstage-3&experimental=false&loose=false&spec=false&code=class%20Collection%20extends%20Array%20%7B%0A%0A%20%20%20%20constructor(...args)%20%7B%0A%20%20%20%20%20%20%20%20const%20first%20%3D%20arguments%5B0%5D%3B%0A%20%20%20%20%20%20%20%20if%20(args.length%20%3D%3D%3D%201%20%26%26%20typeof%20first%20%3D%3D%3D%20'number')%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20super(first%2C%20null)%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20this.pop()%3B%0A%20%20%20%20%20%20%20%20%7D%20else%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20super(...args)%3B%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%0A%7D%0A%0Aconst%20a%20%3D%20new%20Collection(3%2C%202%2C%201)%3B%0Aconst%20b%20%3D%20new%20Collection(3)%3B%0Aconsole.log(a%2C%20b)%3B).
 * Not only does the above code not work in the [playground](http://www.typescriptlang.org/play/#src=class%20Collection%20extends%20Array%20%7B%0D%0A%0D%0A%20%20%20%20constructor(...args)%20%7B%0D%0A%20%20%20%20%20%20%20%20const%20first%20%3D%20arguments%5B0%5D%3B%0D%0A%20%20%20%20%20%20%20%20if%20(args.length%20%3D%3D%3D%201%20%26%26%20typeof%20first%20%3D%3D%3D%20'number')%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20super(first%2C%20null)%3B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20this.pop()%3B%0D%0A%20%20%20%20%20%20%20%20%7D%20else%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20super(...args)%3B%0D%0A%20%20%20%20%20%20%20%20%7D%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%7D%0D%0A%0D%0Aconst%20a%20%3D%20new%20Collection(3%2C%202%2C%201)%3B%0D%0Aconst%20b%20%3D%20new%20Collection(3)%3B%0D%0Aconsole.log(a%2C%20b)%3B), it needs to following [addition](http://www.typescriptlang.org/play/#src=interface%20ArrayConstructor%20%7B%0D%0A%09new%20(...items%3A%20any%5B%5D)%3A%20any%5B%5D%3B%0D%0A%7D%0D%0A%0D%0Aclass%20Collection%20extends%20Array%20%7B%0D%0A%0D%0A%20%20%20%20constructor(...args)%20%7B%0D%0A%20%20%20%20%20%20%20%20const%20first%20%3D%20arguments%5B0%5D%3B%0D%0A%20%20%20%20%20%20%20%20if%20(args.length%20%3D%3D%3D%201%20%26%26%20typeof%20first%20%3D%3D%3D%20'number')%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20super(first%2C%20null)%3B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20this.pop()%3B%0D%0A%20%20%20%20%20%20%20%20%7D%20else%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20super(...args)%3B%0D%0A%20%20%20%20%20%20%20%20%7D%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%7D%0D%0A%0D%0Aconst%20a%20%3D%20new%20Collection(3%2C%202%2C%201)%3B%0D%0Aconst%20b%20%3D%20new%20Collection(3)%3B%0D%0Aconsole.log(a%2C%20b)%3B) to `IArrayConstructor` to get it to not squark.
 * This seems related to #7574.

**Questions:**
* Should this be part of [core](https://github.com/Microsoft/TypeScript/blob/7ae6fcd65ef48ef33f62883e7bd64a3634c15333/lib/lib.core.d.ts#L1244)?
```ts
interface ArrayConstructor {
	new (...items: any[]): any[];
}
```

**Comment by whitneyit** [comment]
The following can be used as a workaround:

```ts
class Collection extends Array {

    constructor(...args) {
        const first = arguments[0];
        if (args.length === 1 && typeof first === 'number') {
            super();
			super.push.call(this, first);
        } else {
			super();
			super.push.apply(this, args);
        }
    }

}

const a = new Collection(3, 2, 1);
const b = new Collection(3);
console.log(a, b);
```

**Comment by jeffreymorlan** [comment]
>This code works in the babel repl.

Actually, it doesn't - it's impossible to subclass builtin classes like `Array` in ES5, because there's no way to tell the `Array` constructor to use your subclass's prototype.

If you transpile this with Babel, `new Collection` creates a plain array which does not inherit from `Collection.prototype`, defeating the whole purpose of subclassing.

**Comment by Arnavion** [comment]
(Since it wasn't explicitly answered) The reason the compiler complains about the two `super()` calls is that `Collection` extends `Array` and not `Array<T>`. The construct signature that takes in array elements [only exists in the generic form](https://github.com/Microsoft/TypeScript/blob/7ae6fcd/lib/lib.core.d.ts#L1250) `new<T>(...items: T[]): T[]` .

So `Collection` should either be `class Collection<T> extends Array<T>` or `class Collection extends Array<any>` depending on what the intented use is.
