### ISSUE TITLE
ChocolateChip-UI

### ISSUE THREAD

**Issue by rbiggs** [Microsoft/TypeScript#7716]
Please fill the following out:

We have updated our logo and website url as below for ChocolateChip-UI:

- Name: ChocolateChip-UI
- Homepage url: http://chocolatechip-ui.github.io
- Brand Guidelines/Licensing: MIT

[Logo-On-Light.svg.zip](https://github.com/Microsoft/TypeScript/files/192572/Logo-On-Light.svg.zip)

- Logo: (svg if possible, pngs over 500x200px with transparent backgrounds are also acceptable)

> Example:
>
> Name: Microsoft
> Homepage url: https://microsoft.com
> Brand Guidelines/Licensing: https://www.microsoft.com/en-us/legal/intellectualproperty/trademarks/usage/logo.aspx
> Logo: https://news.microsoft.com/microsoft-news-center-photos/msft_logo_rgb_c-gray/

**Comment by mhegazy** [comment]
@rbiggs is this an update request for the logo in #3271?

**Comment by rbiggs** [comment]
Yes, we have a new logo and a new url for the framework.

**Comment by mhegazy** [comment]
thanks for confirming.
