### ISSUE TITLE
Javascript language mode on file which is not js cause error

### ISSUE THREAD

**Issue by Thaina** [Microsoft/TypeScript#7720]
I was create file .jslib (js file format for unity3D project) And select language mode as js

Then it cause error unlike normal js file. It try to check existence of all variable and cause error. It seem like it not use the same engine. When I change this file tobe .js it just work properly

![image](https://cloud.githubusercontent.com/assets/1042507/14097155/92645e94-f598-11e5-82b4-6304b58a6702.png)

**Comment by mhegazy** [comment]
The file extension has to be one of the supported ones, i.e.: `.ts`, `.js`, `.jsx`, `.tsx`, and `.d.ts`. 

The general request should be supported as part of https://github.com/Microsoft/TypeScript/issues/7291

**Comment by mhegazy** [comment]
@dbaeumer and @jrieken this issue adds support to open a buffer as a specific language regardless of the file extension. VSCode will need to send the kind as needed.
