### ISSUE TITLE
Add Netbeans to other editor 

### ISSUE THREAD

**Issue by idarous** [Microsoft/TypeScript#7723]
Hello,

I don't know if it's the good place to post this suggestion.

In the web site of TypeScript, there is a section with the other editors that support TypeScript.
I think it would be nice if you add Netbeans because Netbeans is a good IDE for web and its plugin for TypeScript is very good.

More information about the Netbeans' TypeScript plugin https://github.com/Everlaw/nbts

**Comment by angelozerr** [comment]
Hi @idarous I think you should create a PR for https://github.com/Microsoft/TypeScript-wiki/blob/master/TypeScript-Editor-Support.md

**Comment by mhegazy** [comment]
We will publish the editor support page pointed out by @angelozerr to the handbook as well.

**Comment by idarous** [comment]
I mean is it possible to add Netbeans in this section of the main page of the web site of typescript ? http://www.typescriptlang.org

![image](https://cloud.githubusercontent.com/assets/15747854/14141982/094873c0-f683-11e5-9b9c-e73834f4826d.png)

Maybe you can also add Intellij and Notepad++ (https://github.com/sorskoot/npp-typescript-vs) in order to have a new full column of editors displayed.

**Comment by mhegazy** [comment]
For maintainability, i would like to add a link to a page with all editor/IDE support.  https://github.com/Microsoft/TypeScript-wiki/blob/master/TypeScript-Editor-Support.md seems like a good starting place. feel free to send a PR for notepad++
