### ISSUE TITLE
Add function to Date prototype and keep other methods

### ISSUE THREAD

**Issue by mbakker96** [Microsoft/TypeScript#7726]
Hello,

I want to add a function to the Date prototype. I want to add a weekNumber function to it that returns the number of the week.

I wan to create make it on the typescript way so much as posible. 

This is the prototype function: 
```javascript
Date.prototype.getWeekNumber()
    var d: Date = new Date(+this);
    d.setHours(0, 0, 0);
    d.setDate(d.getDate() + 4 - (d.getDay() || 7));
    return Math.ceil((((d - new Date(d.getFullYear(), 0, 1)) / 8.64e7) + 1) / 7);
};
```

I created a interface but the problem was that he removed all the functions of the Date and becease of that my IDE was giving an error that the functions are not existing. 

Does someknow how to do it by the right way?`

**Comment by mhegazy** [comment]
```ts

// Extend the type, and declare the new function
interface Date {
    getWeekNumber(): number;
}

// Add the implementation
Date.prototype.getWeekNumber = function () {
....
};

var x = new Date();


x.getWeekNumber();
```

**Comment by mbakker96** [comment]
The problem with this is that all the methods of the Date not available anymore

**Comment by RyanCavanaugh** [comment]
See https://github.com/Microsoft/TypeScript/wiki/FAQ#why-did-adding-an-import-or-export-modifier-break-my-program . The `interface Date {` declaration needs to not be an a module file.

**Comment by mbakker96** [comment]
What is the right way to do it? @RyanCavanaugh

**Comment by RyanCavanaugh** [comment]
Take the `interface Date {` declaration and put it in a .d.ts file that doesn't have any top-level `import` or `export` statements in it, then reference that .d.ts file in your compilation (either through a `/// <reference` or by adding it to the list of files on the commandline or tsconfig.json)

**Comment by mhegazy** [comment]
if you are using TS 1.8.5 or higher, consider using:

```ts
declare global {
    interface Date {
        myMethod(): number;
    }
}
```

see https://github.com/Microsoft/TypeScript/wiki/What%27s-new-in-TypeScript#augmenting-globalmodule-scope-from-modules for more details.

**Comment by gfrSE** [comment]
How to access the "date object" ?
Or whatever object i am extending..

Using `this` will return the first exported object in that file?!

```javascript
... some angular2 stuff here ...


// DATE EXTENSIONS
// ================

declare global {
  interface Date {
    isToday(): boolean;
  }
}

Date.prototype.isToday = (): boolean => {
  let today = new Date();
  console.log(this); // WILL RETURN FIRST EXPORTED ANGULAR2 OBJECT IN THIS FILE
  return today.getFullYear() === this.getFullYear() && today.getMonth() === this.getMonth() && today.getDate() === this.getDate();
};

```

**Comment by mhegazy** [comment]
Lambda explressions do not have a `this` binding. they inherit the one from the containing scope. in this case, it is the module. This is the ES2015 semantics of lambdas.

use a function expression instead. e.g.:

```ts
Date.prototype.isToday = function (): boolean {
 ... 
};
```

**Comment by mxii** [comment]
@mhegazy Thanks alot!!

Took me many hours to play around but no success..
Thanks, works like a charm!

**Comment by amsakanna** [comment]
I figured the lambda issue already. Still didn't work. But thank you gfrSE. Adding export {} on top resolved my issue.

**Comment by xtianus79** [comment]
@mhegazy do you have documentation on that... it is great informaiton and would like to read more up on it. 

> Lambda expressions do not have a this binding. they inherit the one from the containing scope. in this case, it is the module. This is the ES2015 semantics of lambdas.

use a function expression instead. e.g.:

Date.prototype.isToday = function (): boolean {
 ... 
};
