### ISSUE TITLE
Extra casting not necessary

### ISSUE THREAD

**Issue by Alphapage** [Microsoft/TypeScript#7727]
Hello,

Actual:
```interface ITest{test:string}; let test:ITest=<ITest>{}```
Expected
```interface ITest{test:string}; let test:ITest={}```

I think ```{}``` should be considered as ```ITest``` by default instead of any.

Thanks in advance for your feedback.

**Comment by mhegazy** [comment]
```ts
interface ITest{test?:string}; let test:ITest={}
```

**Comment by mhegazy** [comment]
Sorry hit comment too soon.

`ITest` requires one member `test`. the empty object does not have that. they are not assignable.

you can make `test` optional in `ITest`:
```ts
interface ITest{test?:string}; let test:ITest={}
```
