### ISSUE TITLE
Rename Stateless function variable doesn't update JSX usages

### ISSUE THREAD

**Issue by basarat** [Microsoft/TypeScript#7732]
**TypeScript Version:** 

Just tested in Atom-Typescript which currently has `master` as of `2016-02-23` https://github.com/TypeStrong/atom-typescript/blob/8d43dd1b930a6df0ce62454a1560acfb7eee24c9/package.json#L64

**Code**

```ts
import * as React from "react";
import * as ReactDOM from "react-dom";

const Hello = (props: { compiler: string, framework: string }) => {
    return (
        <div>
            <div>{props.compiler}</div>
            <div>{props.framework}</div>
        </div>
    );
}

ReactDOM.render(
    <Hello compiler="TypeScript" framework="React" />,
    document.getElementById("root")
);
```

**Expected behavior:**
Rename `Hello` in `const Hello` to `Hellos` and `<Hello` should update to `<Hellos`. 

**Actual behavior:** 
Rename `Hello` in `const Hello` to `Hellos` and `<Hello` will not update. 

# More 
I was using this as a sample for https://github.com/basarat/react-typescript  :rose:

**Comment by RyanCavanaugh** [comment]
I think we recently fixed this. Can you try again with a more recent build from master?

**Comment by basarat** [comment]
> I think we recently fixed this. Can you try again with a more recent build from master?

Indeed fixed. Thanks! :rose: 

@RyanCavanaugh I like the highlight on your display pic. I guess TypeScript should standardize https://github.com/remojansen/logo.ts by @remojansen :rose:
