### ISSUE TITLE
Incorrect declarations for clipboard events

### ISSUE THREAD

**Issue by mindplay-dk** [Microsoft/TypeScript#7737]
The DOM declaration files declare clipboard events as `DragEvent` - for example [here](https://github.com/Microsoft/TypeScript/blob/master/lib/lib.d.ts#L7756):

    addEventListener(type: "paste", listener: (ev: DragEvent) => any, useCapture?: boolean): void;

I'm pretty sure these should have been declared with `listener` as `ClipboardEvent` - it's defined, but doesn't appear to be used in the actual event overloads?

This blocks me from accessing e.g. `event.clipboardData`...

**Comment by mhegazy** [comment]
PRs welcomed. more information about contributing lib fixes available in https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes

**Comment by YuichiNukiyama** [comment]
This already had been fixed in [TSJS-Repo](https://github.com/Microsoft/TSJS-lib-generator/blob/master/baselines/dom.generated.d.ts#L4301).

**Comment by mhegazy** [comment]
indeed. thanks @YuichiNukiyama!

**Comment by mindplay-dk** [comment]
Soooo, wait for the next release or...?

Maybe time to think about making the DOM declaration files explicitly versionable/installable (e.g. via `typings`) since these seem to get more frequent updates than the Typescript package itself?

**Comment by DanielRosenwasser** [comment]
@mindplay-dk perhaps, but that's for another issue - for now, you can fetch the current versions of our `lib.d.ts` manually or you can use nightly versions of TypeScript by running `npm install -g typescript@next`.
