### ISSUE TITLE
Double definitions not recognized

### ISSUE THREAD

**Issue by olivierandriessen** [Microsoft/TypeScript#7743]
**TypeScript Version:** 

1.8.9

**Code**

```ts

import Item from "./Models/Item";
import ModelCollection from "ts-core/lib/Data/ModelCollection";

var modelCollection = new ModelCollection<Item>(Item, []);

```

**Expected behavior:**

Compilation without errors.

**Actual behavior:** 

<img width="673" alt="screen shot 2016-03-31 at 09 18 08" src="https://cloud.githubusercontent.com/assets/3968358/14169729/d6f0c84e-f729-11e5-94e8-a60e8c035aeb.png">

In order to replicate:

```bash
clone https://github.com/redound/exp-typings.git
cd exp-typings
typings install
tsc
```

NOTE: I'm not sure if this is a TypeScript or Typings problem so I've also issued it here:
https://github.com/typings/typings/issues/380

**Comment by mhegazy** [comment]
The first `EventEmitter`, referred to in the definition of `Item` is in `exp-typings\typings\main\definitions\ts-data\index.d.ts` line 109. The other `EventEmitter` used in `Model` comes from `exp-typings\typings\main\definitions\ts-core\index.d.ts` line 477.

the two classes seem identical, but they have a private member. from the compiler perspective these are different files. 

Are the files `ts-core\index.d.ts` and `ts-data\index.d.ts` auto generated by typings?

**Comment by olivierandriessen** [comment]
@mhegazy Thanks for your reply.

the definition files inside https://github.com/redound/ts-core/tree/dev-package/lib get generated after the `tsc` executes:
https://github.com/redound/ts-core/blob/dev-package/tsconfig.json

the definition files inside https://github.com/redound/ts-data/tree/dev-package/lib get generated after the `tsc` executes:
https://github.com/redound/ts-data/blob/dev-package/tsconfig.json

Typings then goes ahead and alters them resulting in the `index.d.ts` files inside the typings folder. I think the reason the `EventEmitter` referred to in the definition `Item` is caused by Typings actually including the typings of `ts-core` also in the definition of `ts-data` itself. That's because `ts-data` has `ts-core` as a dependency. I believe I don't have any control whatsoever over the way typings does this. What do you think?

**Comment by mhegazy** [comment]
If there is a shared dependency, it should be factored out to a different component. `ts-core-eventemitter`. the other option, is make the contract of these declaration safe to use across different versions of your library, i.e. do not use private properties.

**Comment by unional** [comment]
How about protected properties? Should they be shared? Sounds like a touchy subject. :smirk:
