### ISSUE TITLE
Users cannot rename/delete directories because tsserver locks them

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#7762]
**TypeScript Version:** 

1.8.9

To reproduce use VSCode from Insider Channel (https://code.visualstudio.com/Download#insiders)

- create workspace
- create tsconfig.json with content
```json
{
	"compilerOptions": {
		"module": "commonjs"
	}
}
```
- create test.ts with content
```ts
class A {	
}
```
- create folder libs
- create folder libs\superLib
- create file libs\superLib\lib.d.ts with content
```ts
export function foo();
```
- start VSCode
- open test.ts
- try to rename libs to libs2

Observer: you can't the directory is locked.

- Use for example handle.exe from SysInternals or a process explorer to check who is holding a lock on the .\libs directory. It is the tsserver.

![capture](https://cloud.githubusercontent.com/assets/1931590/14202545/db08ec70-f7f8-11e5-83dc-d40104f63efc.png)

**Comment by dbaeumer** [comment]
The problem already existed in 1.8.2 which shipped in in 0.10.11. It was not in the release before which shipped with 1.7.x of TS.

**Comment by zhengbli** [comment]
#8196 was just merged, which should solve the problem for now. Can you give it a try?

**Comment by zhengbli** [comment]
I tested using the latest `typescript@next` nightly, and this issue was fixed. Please reopen the issue if you  still see it. Thank.
