### ISSUE TITLE
is the ID of a Symbol unique across a Program?

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#7773]
I am working on a linter rule for eliminating unused identifiers in the code of my application. I am going through all files in the program and count the number of each identifier (thorugh the ID of it's symbol) was seen. It looks like an identifier with the same ID of its symbol can be *declared* in more than one place of the program. Is this true?

**Comment by mhegazy** [comment]
yes. keep in mind that a symbol can be merged though.

**Comment by mhegazy** [comment]
We could consider adding an Id property on Symbol similar to https://github.com/Microsoft/TypeScript/issues/5687
