### ISSUE TITLE
Having *.ts in multiple folders doesnt generate folders if you leave out the root *.ts file

### ISSUE THREAD

**Issue by fletchsod-developer** [Microsoft/TypeScript#7774]
**TypeScript Version:** 

1.8.29

**Code**

tsconfig.json

```JSON
{
  "compilerOptions": {
    "target": "es5",
    "module": "system",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": true,
    "noEmitOnError": true,
    "outDir": "wwwroot/scripts"
    },
    "exclude": [
      "node_modules",
      "typings/main",
      "typings/main.d.ts",
      "wwwroot"
    ]
  }
```
**Expected behavior:**

Sorry if it this is a duplicate but I couldn't find one when searching for it.

Using VS-2015 Update 2, If I create this typescript files in folder (or multiple folders)

![image](https://cloud.githubusercontent.com/assets/5113337/14217997/834aacb8-f81f-11e5-8b51-14eab8b5fe67.png)

When compiling, it should produce this.

![image](https://cloud.githubusercontent.com/assets/5113337/14218014/a0bb81f0-f81f-11e5-98d8-97dc1b3b78b7.png)

**Actual behavior:** 

Instead it produce this

![image](https://cloud.githubusercontent.com/assets/5113337/14218041/c92f5cce-f81f-11e5-922d-4c9aa77fb89e.png)

But the expected behavior would work if you add a root file instead.   (The missing root file shouldn't cause this bug to begin with).

![image](https://cloud.githubusercontent.com/assets/5113337/14218075/f86e9da6-f81f-11e5-9c11-ddaa7a043c41.png)

![image](https://cloud.githubusercontent.com/assets/5113337/14218086/09ba2e22-f820-11e5-9276-63c27a642f5f.png)

**Comment by mhegazy** [comment]
Please see documentation in https://github.com/Microsoft/TypeScript/wiki/FAQ#why-does---outdir-moves-output-after-adding-a-new-file

also see my reply in https://github.com/Microsoft/TypeScript/issues/7346#issuecomment-191432669
