### ISSUE TITLE
All non-initalized Property Member Declarations aren't created in JavaScript

### ISSUE THREAD

**Issue by kabua** [Microsoft/TypeScript#7777]
**TypeScript Version:** 

1.8.6.0

**Code**

The [ Property Member Declarations Spec] (https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#84-property-member-declarations) shows the following ts example:

**TypeScript Code:**
```ts
class Employee {  
    public name: string;  
    public address: string;  
    public retired = false;  
    public manager: Employee = null;  
    public reports: Employee[] = [];  
}
```
However, when the ts file is compiled, **all** the non-initialized properties are missing from JavaScript. 

**Compiled code:**
```js
    var Employee = (function () {
        function Employee() {
            this.retired = false;
            this.manager = null;
            this.reports = [];
        }
        return Employee;
    }());
```

Notices that ```name``` and ```address``` are missing.

We discovered this the hard way. Our code declared a simple 'structure' with 2 of the 7 properties being initialized through the ctor() and the rest was initialized/set later in the code. The TS compiler gave no errors or warnings. But our applications crashed when it tried to set a non-initialized properties. For example:

```ts
var e = new Employee();
e.Name = "bob"; // Error: "Name is not a method on [object Object]"
```
**Expected behavior:**
That **all** properties that are defined (regardless of their initial state) be compiled to JS. We don't expect things to 'just' disappear.

**Actual behavior:** 
**All** uninitialized properties are removed from JavaScript which then leads to run-time errors; and unexpected behavior.

**Comment by RyanCavanaugh** [comment]
Setting a property that doesn't exist yet doesn't generate a "Name is not a method on [object Object]" error. I'm not sure how you're getting that to appear (especially since `Name` isn't `name`...).

Class properties are not initialized by default because some people explicitly don't want that to happen, and some people do. If you want the properties to be initialized, provide an initializer.

**Comment by kabua** [comment]
Thanks for pointing out the typo, but the fact still remains.  If someone defines a class field/variable; then that filed should be reflected in the Javascript code.  Or at the vary lest, display a warning.  But to do nothing and let my application crash then what good is using a compile time code analysis if the code it generates isn't valid? We currently get this type of runtime checking from Javascript. The whole purpose for moving to TypeScript is to get something better,  not worse.
