### ISSUE TITLE
Feature request: Incremental compilation

### ISSUE THREAD

**Issue by digeff** [Microsoft/TypeScript#7778]
I'd be great if there was an easy way for the typescript to detect and only recompile and re-parse the files that were changed since the last run.

**Comment by mquandalle** [comment]
I think it’s already supported—https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API#incremental-build-support-using-the-language-services

**Comment by DanielRosenwasser** [comment]
We also have a `--watch` flag built into the compiler that does this. We also have some outstanding work on #6937 to shave off emit time and avoid updating timestamps when a file's emit isn't actually different.
