### ISSUE TITLE
[Salsa] Union types in JSDoc @type tag are given intellisense for all subtypes

### ISSUE THREAD

**Issue by zhengbli** [Microsoft/TypeScript#7789]
**TypeScript Version:** 

nightly (1.9.0-dev.20160402)

![capture](https://cloud.githubusercontent.com/assets/1171301/14229239/67f42c40-f8e3-11e5-9d16-398a4bd61d46.PNG)

**Comment by DanielRosenwasser** [comment]
This was actually an intentional decision. [Check out the relevant code](https://github.com/Microsoft/TypeScript/blob/68bdbe04e73fc4eb66d744a1a89bbd3baf162a87/src/services/services.ts#L3261-L3272).

**Comment by zhengbli** [comment]
Makes sense.
Quote the comments here just for the record:
> In JavaScript files, for union types, we don't just get the members that
the individual types have in common, we also include all the members that
each individual type has.  This is because we're going to add all identifiers
anyways.  So we might as well elevate the members that were at least part
of the individual types to a higher status since we know what they are.
