### ISSUE TITLE
[Question] - Is it possible to cast a type to an entire block?

### ISSUE THREAD

**Issue by dsifford** [Microsoft/TypeScript#7790]
Hi there,

Quick question (or suggestion if this isn't possible):

What I'm interested in doing is casting a type to an entire block (or to the rest of the current block). I do pretty explicit error handling, and I've found that I have to do this overly verbose `as <type>` statement each time. 

Here's a very pointless, but descriptive example:

```ts
interface Person {
  firstname: string
  lastname: string
  age: number
}

function myFunc(x: boolean): Person|Error {
  if (!x) {
     return new Error('My error message');
  }
  return {
    firstname: 'John',
    lastname: 'Doe',
    age: 45,
  }
}

let output = myFunc(true);

// Handle the error
if ((output as Error).name === 'Error') {
  throw output;
} 

console.log(
  (output as Person).firstname + ' ' + (output as Person).lastname
);

```

I'd like to assume that the `output` variable is of type Person after the if block that checks for an error. Is there any way to re-declare that it is type `Person` so that I don't have to do `(output as Person)` for everything thereafter?

I hope that makes sense. Thanks a lot for the clarification! :smile:

**Comment by RyanCavanaugh** [comment]
This will be possible once type guards are rewritten to use flow control analysis (this work is currently in progress), assuming you add one helper function that creates an explicit type predicate.

The working version of the code (simplified) would look like this:
```ts
function isError(p: any): p is Error {
  return (p as Error).name === 'Error';
}

let x: Person | Error = /* ... */;

if (isError(x)) {
  throw x;
}

// Because we know we can't get here if 'x' is 'Error',
// all future uses of 'x' in this block are seen as type 'Person'
let n = x.firstname; // OK
``

**Comment by dsifford** [comment]
Excellent! Thanks for the clarification.
