### ISSUE TITLE
Msbuild appears to Ignore output dir

### ISSUE THREAD

**Issue by tbertenshaw** [Microsoft/TypeScript#7791]
Using typescript 1.8 in vs2015 update 2, I have a tsconfig.json which outputs to a different folder. This works on save and when running tsc with the -p argument but webpublish appears to Ignore it and expect to see .js files alongside their .ts files

Full diagnostic output below
http://stackoverflow.com/questions/36376126/webpublish-failing-to-respect-typescript-configuration#

**Comment by Drol** [comment]
I have the same problem when using the "outFile" option in tsconfig.json.

**Comment by mhegazy** [comment]
this is the same issue as https://github.com/Microsoft/TypeScript/issues/6934. We are working on a fix for it.
