### ISSUE TITLE
Proposal: Registries

### ISSUE THREAD

**Issue by Gaelan** [Microsoft/TypeScript#7795]
Problem
======
Many JavaScript libraries allow you to call a function to "register" something using a string, then call another function with that same string to do something. For example, apps written with Meteor (a web development framework) use a "publish/subscribe" system where REST-based apps would use GET endpoints. Server calls `Meteor.publish` with a string and a function that returns a database cursor. The client can then call `Meteor.subscribe` with the same string (any remaining arguments are passed to the function on the server), which makes the data returned by the publish function available to the client. Currently, there is no way to ensure that the string or arguments passed to `Meteor.subscribe` are valid. This proposal aims to change that.

Solution
======
I propose a concept of "registries," which store mappings of strings (or possibly other values, but we already have a concept of strings as compile-time constants, so I am sticking with them for now) to objects. Proposed syntax: (I fully expect this to change)

```typescript
declare namespace Meteor {
  registry Publications: any[];

  function publish<N extends string, A extends any[], register N: A to Publications>(name: N, func: (...args: A) => Mongo.Cursor): void;

  function subscribe<N extends string, A is Publications[N]>(name: N, ...args: A);
}
```

Possible Additions
------------------------
- Instance-level registries for classes
- Optionally only making registrations available if the code that uses them is explicitly imported
  - To work for the original use case, this needs to be optional (although Meteor shares a codebase between client and server, `Meteor.publish()` is only defined on the server, so importing the file which calls it is a bad idea)

**Comment by mhegazy** [comment]
I am not familiar with Meteor workflow; can you provide some more information about how this is used today, what are the issues you are trying to address, and how the new proposal would be used.
i am not also sure i understand the scope of these "registry" type mutations, is it that you have ever called `publish` with that string or am i wrong. why is not using an interface augmentation sufficient? what about regular strings, i.e. non-string literal types?

**Comment by Gaelan** [comment]
I forgot about interface augmentation. It's a bit less convenient (I have to declare the publication twice, once for Meteor at runtime and once for TypeScript at compile-time), but not inconvenient enough to justify adding a big feature. Whoops!

If you would like more detailed explanation anyway, it is below. (I typed it before I got to the interface augmentation part, and didn't want to delete that much text.)

* * *

Meteor provides the illusion of database access on the client. Because, for security and performance reasons, we can't send the entire database to the client, database records the client will use are "published" by the server, then "subscribed to" by the client. After a call to `Meteor.subscribe`, the data shows up in the client's emulated database. Here is what it looks like in use now:

```typescript
// On server
Meteor.publish('posts.byAuthor', (authorId: string) =>  Posts.find({author: authorId}) );

// On client, presumably when clicking on an author's name
Meteor.subscribe('posts.byAuthor', authorId); // Runs correctly, compiles
Meteor.subscribe('posts.byAuther', authorId); // ** Fails at runtime (typo), compiles
Meteor.subscribe('posts.byAuthor'); // ** Fails at runtime (incorrect arguments), compiles

// Some logic to wait for the data to load

const posts = Posts.find({author: authorId}).fetch();
```

My goal here is to make those lines that fail at runtime fail to compile.

**Comment by basarat** [comment]
> My goal here is to make those lines that fail at runtime fail to compile.

Why not just have a common `constants.ts` file that contains: 

```ts
export const subscribtionIds = {
   postsByAuthor: 'posts.byAuthor'
} 
```
And just use this instead of magic strings :rose:

**Comment by Gaelan** [comment]
@basarat That doesn't verify that the arguments are in sync.

**Comment by basarat** [comment]
@Gaelan 

```ts

export const subscribtionIds = {
   postsByAuthor: 'posts.byAuthor'
}

// On server
Meteor.publish(subscriptionIds.postsByAuthor, (authorId: string) =>  Posts.find({author: authorId}) );

// On client, presumably when clicking on an author's name
Meteor.subscribe(subscriptionIds.postsByAuthor, authorId); // Runs correctly, compiles
Meteor.subscribe(subscriptionIds.postsByAthor, authorId); // ** Fails at compile runtime (typo)
Meteor.subscribe(subscriptionIds.postsByAthor); // ** Fails at runtime (incorrect arguments), compiles
```

However I might be missing the point. :rose: 

I like my APIs to be type safe. At work I have C# => TypeScript code generation. For OSS NodeJS I have a workerlib and socketlib that shares the idea that an async API (promise or observable) can be easily split across an exectution boundry with simple message passing  : https://github.com/alm-tools/alm/blob/master/docs/contributing/ASYNC.md

**Comment by basarat** [comment]
This ASYNC idea was used by atom-typescript and I've cleaned up further and documented with http://alm.tools/ :rose:

**Comment by Gaelan** [comment]
@basarat Clever!
