### ISSUE TITLE
Feature Request: Declare variables as immutable

### ISSUE THREAD

**Issue by 2426021684** [Microsoft/TypeScript#7796]
Immutable would make a properties on an object immutable recursively.
Example:
```
immutable const a = ["1", "2", "3"]
a.push("4") // Error function mutates immutable variable
```

The would be useful with pure functions #7770

**Comment by RyanCavanaugh** [comment]
This is close enough to what's in #6532 that I don't think we would do a new feature for it.

**Comment by 2426021684** [comment]
How do I declare a variable as readonly? The issue you linked to was taking about making a property readonly. There was a comment mentioning readonly variables but that was not implemented.

**Comment by lastmjs** [comment]
Yes, what about a variable that is just a variable, not part of an interface? Do we have any solution for checking the immutability of one-off variables?
