### ISSUE TITLE
No referencing/intellisense fo nested properties/functions within class

### ISSUE THREAD

**Issue by zalow517** [Microsoft/TypeScript#7801]
I have the following structure where I have a class that contains functions nested inside properties and vice versa. Intellisense and therefore referencing is not working when inside a function that resides inside a property of the class. Is there a way to solve this sort of issue so that I can reference `myThirdProp` inside `mySecondFunc`?

```
export class a {
    
    myProperty = 'hello';
    myFunc() {
        
        this.myProperty; //referencing and intellisense available
    }
    
    mySecondProp: Object = {
        
        myThirdProp: 'hello2',
        mySecondFunc() {
            
            this. //no intellisense/reference here
        }
    }
}
```

**Comment by RyanCavanaugh** [comment]
Currently, we don't really know how `mySecondProp.mySecondFunc` is going to be invoked, so its `this` type is `any`. #6739 should solve this for you by allowing you to specify the type of `this` inside `mySecondFunc`.

**Comment by sandersn** [comment]
`this` inside of an object literal now has Intellisense. @zalow517 can you try `typescript@next`? It will be available April 8, after the nightly build picks it up.

**Comment by sandersn** [comment]
#8389 reverts this fix for now.

**Comment by mhegazy** [comment]
Cross positing from https://github.com/Microsoft/TypeScript/issues/8110#issuecomment-215988532

We have tried different ways of addressing this issue, and the current behavior (this in an object literal is of type any) seems to be the most reasonable.

Classes present stronger assumptions about how the functions will be called. object literals on the other hand can be used as a property bag often with no assumptions about the relationship of the methods and properties on them. we have seen common JS patterns where methods are added, removed, or called with a different this target at runtime (see #8133 for an example). 

the recommendation is to specify an explicit `this` type in methods:

```ts
interface FooBar {
    foo(): void;
    bar(): void;
}

let o = {
    foo: function (this: FooBar) { this /* FooBar */ },
    bar(this: FooBar) { this /* FooBar */ }
}
````

**Comment by ahejlsberg** [comment]
See #14141.
