### ISSUE TITLE
Import element order in csproj file affects save/build behavior

### ISSUE THREAD

**Issue by AndersSahlin** [Microsoft/TypeScript#7802]
I've stumbled on to an issue where I was experiencing a strange behavior with the `outdir` compiler flag. I'm using the latest Typescript compiler Nuget package (1.8.6).

The output files were rendered next to the source files when I built my project, but when I opened and saved a Typescript file, all the files were rendered in the correct directory. After some troubleshooting it turns out that if you don't place the `<Import Project="...Microsoft.TypeScript.targets" />` line _after_ the `<PropertyGroup>...</PropertyGroup>` (with all the Ts build settings) this issue occurs.

I think it's strange that "Compile on Save" could figure out the correct settings but not the normal project build.

I have created a test repo with the above order reversed so that it's easy to see the difference in behavior: https://github.com/AndersSahlin/TypescriptIssueRepo1/ (See `TsExampleProject.csproj` line 122.)

So... I guess I'm just wondering if it's expected behavior or something for you to look closer at.

**Comment by mhegazy** [comment]
These are the MSBuild semantics. the XML tags, either `import`s or `property` declarations are evaluated in the order they appear in the file. 

The `Microsoft.TypeScript.targets` has logic to build the configuration to pass on the commandline, something like:

```XML
   <TypeScriptBuildConfigurations Condition="'$(TypeScriptOutDir)' != ''">$(TypeScriptBuildConfigurations) --outDir &quot;$(TypeScriptOutDir)&quot;</TypeScriptBuildConfigurations>
```

if by the time the import is evaluated, `TypeScriptOutDir` is not defined, i.e. `$(TypeScriptOutDir)==""`, then the condition above will fail.

Compile-On-Save uses VS MSBuild interfaces to get the same information from the project file. you can think of these as what is the value of `TypeScriptOutDir` at the end of the project file. in your case, it does in deed have a value, it is just different from the one that the build sees.

I do not think there is much we can do here.
