### ISSUE TITLE
Generated js doesn't adjust this properly when referencing array

### ISSUE THREAD

**Issue by user414** [Microsoft/TypeScript#7804]
**TypeScript Version:** 

1.8.7

**Code**

```ts
computeFunctionFromDBFieldName = (): any => {
if (this.dbFieldName) {
                return function(object: any): string {
                    return argJsonObject[this.dbFieldName];
...
}
```

**Expected behavior:**
```
 this.computeFunctionFromDBFieldName = function () {
	            if (_this.dbFieldName) {             
	                    return function (argJsonObject) {
	                        return argJsonObject[_this.dbFieldName];
	                    };
```
**Actual behavior:** 
Generated js
```
 this.computeFunctionFromDBFieldName = function () {
	            if (_this.dbFieldName) {             
	                    return function (argJsonObject) {
	                        return argJsonObject[this.dbFieldName];
	                    };
```

The expected difference would be that the _this would also be in the array referencing.

**Comment by user414** [comment]
Sorry when I posted this I hadn't realized that function within function. This makes this issue a little different... Nonetheless, I can't see why one would want the generated js instead of the expected js since in any case in the generated js the this is undefined which is certainly not what the original code was intended to do.

**Comment by Arnavion** [comment]
It follows the semantics of JS. Regular functions don't capture lexical this and arrow functions do:

```typescript
computeFunctionFromDBFieldName = (): any => {
if (this.dbFieldName) {
    return (object: any): string => {
        return argJsonObject[this.dbFieldName];
    }
}
```

**Comment by user414** [comment]
Yeah will close this, even though here I can't hardly think of any other meaning compiler are not in the business of guessing intent.

**Comment by Arnavion** [comment]
I haven't tested, but I think `--strictThis` will give you an error for that once #6018 is merged.

**Comment by user414** [comment]
@RyanCavanaugh @Arnavion Would you rather I keep this open?
