### ISSUE TITLE
'HTMLDialogElement' doesn't exist in 'lib.d.ts'

### ISSUE THREAD

**Issue by RandallFlagg** [Microsoft/TypeScript#7805]
**TypeScript Version:** **_[Taken from the verbose output in VS2015]_**

TypeScriptTarget = ES5
TypeScriptToolsVersion = 1.8
UnitTestPlatformVersion = 14.0

**Code**

```ts
const dialog = document.querySelector('dialog') as HTMLDialogElement;

dialog.show();
//...
dialog.showModal();
//...
const value:string = {result:true};
dialog.close(value);

```

**Expected behavior:**
As described [here](https://w3c.github.io/html/interactive-elements.html#the-dialog-element) the element exists but not showing in lib.d.ts.
**Actual behavior:** 
Error when compiling.

**Possible Solution**
**_Add this to lib.d.ts:_**
**Code**

```ts
interface HTMLDialogElement extends HTMLElement {
    open: Boolean;
    //returnValue: String;
    returnValue: string;
    show(): void;
    close(result?): void;
    showModal(): void;
}
```

**Comment by FranklinWhale** [comment]
The `dialog` element is quite new. It is not in HTML 5.0. It is defined in HTML 5.1 which is still a working draft. I am not sure if it is good to add it at the moment.

**Comment by mhegazy** [comment]
We take a regular updates to lib.d.ts from the edge team definitions, so it should appear there once implemented. until then i agree with @FranklinWhale, no need to include it. 

please note that you can include the definition above and use it meanwhile.

**Comment by RandallFlagg** [comment]
That is what I am doing. Hoping to see it in official typescript lib.
Will wait for the release. Thank you all in the meantime.
