### ISSUE TITLE
Default export creates invalid declaration file

### ISSUE THREAD

**Issue by hammy55** [Microsoft/TypeScript#7807]
ES6 'export default _expression_' syntax creates an invalid declaration file when compiled with --outFile.

Compiling the below code:
```ts
// pi.ts
export default 3.14159;
```
With the following config:
```js
// tsconfig.json
{
    "compilerOptions": {
        "module": "system",
        "outFile": "app.js",
        "declaration": true
    },
    "files": [
        "pi.ts"
    ]
}
```
Results in the following invalid d.ts file:
```ts
// app.d.ts
declare module "pi" {
    // TS1038: A 'declare' modifier cannot be used in an already ambient context.
    declare var _default: number;
    export default _default;
}
```

The issue only occurs when the _expression_ is a literal or return value.

The work around in both cases is to declare a name for the default export:
```ts
const PI = 3.14159;
export default PI;
```

Typescript Version 1.8.5

**Comment by mhegazy** [comment]
@hammy55 can you give `typescript@next` a try later some time after 12:00 am PST.

**Comment by hammy55** [comment]
Sure thing. I will give it a try tomorrow morning.

**Comment by hammy55** [comment]
Verified below in `typescript@next` (Version 1.9.0-dev.20160405).
```ts
export default 3.14159;

function pi(): number { return 3.14159; }
export default pi();

export default (function() { return 3.14159; })();
```

All worked as expected. Thanks for the quick fix.

**Comment by mindplay-dk** [comment]
Will this be in the next minor release, or not available until release 2.0?

My entire project is on hold because of this.

**Comment by RyanCavanaugh** [comment]
I don't think we're going to backport this one unless there's more feedback on it. Is anything blocking you from using the nightly build?

**Comment by mindplay-dk** [comment]
Right on, I'll grab the nightly for now, tx :-)
