### ISSUE TITLE
typescript --allowJs too slow

### ISSUE THREAD

**Issue by Veikedo** [Microsoft/TypeScript#7808]
**TypeScript Version:** 

1.8.9

**tsconfig.json**

```ts
{
  "compilerOptions": {
    "target": "es5",
    "module": "amd",
    "noEmitOnError": true,
    "allowJs": true
  },
  "exclude": [
    "node_modules",
    "bower_components"
  ]
}

```
**gulp task**

```js

var  ts = require("gulp-typescript"),

var tsProject = ts.createProject("tsconfig.json", {
    noExternalResolve: true,
    typescript: require("typescript")
});

gulp.task("scripts", function() {
    return gulp.src(paths.devroot.ts)
        .pipe(ts(tsProject))
        .pipe(gulp.dest(paths.webroot.app));
});

gulp.task("watch", ["scripts"], function() {
    gulp.watch(paths.devroot.ts, ["scripts"]);
})

```

When I run the task with --allowJs set to true, it takes about 10seconds to build my project. Moreover it takes 10 seconds after any change in my files, ie it is not incrementaly.

When --allowJs is disabled, it takes about 1 second to build the whole project, and 100ms to build incrementally.

**Comment by mhegazy** [comment]
can you run `tsc --diagnistics --listFiles` with and without `--allowJs` and share the output?

**Comment by Veikedo** [comment]
@mhegazy , i ran it in a working pc, that a bit faster. 
Actually, the main problem is with "-watch".

[diag.allowJs.txt](https://github.com/Microsoft/TypeScript/files/204566/diag.allowJs.txt)
[diag.disallowJs.txt](https://github.com/Microsoft/TypeScript/files/204567/diag.disallowJs.txt)

[diag.allowJs.watch.txt](https://github.com/Microsoft/TypeScript/files/204596/diag.allowJs.watch.txt)
[diag.disallowJs.watch.txt](https://github.com/Microsoft/TypeScript/files/204597/diag.disallowJs.watch.txt)

**Comment by mhegazy** [comment]
in the allowJS case, you are pulling in many more files (244 vs. 50). we are spending 2 more seconds in additional IO (reading the extra files, and writing their output) and 2 more seconds in type checking them see below.

without `--allowJs`

```txt
Files:             244
Lines:           54431
Nodes:          260098
Identifiers:     88870
Symbols:       7629718
Types:           11834
Memory used:   143379K
I/O read:        0.06s
I/O write:       1.99s
Parse time:      0.86s
Bind time:       0.40s
Check time:      2.17s
Emit time:       2.63s
Total time:      6.07s

```

No `--allowJs`

```txt
Files:              50
Lines:           24110
Nodes:           97627
Identifiers:     37579
Symbols:       1158822
Types:            6640
Memory used:    69853K
I/O read:        0.01s
I/O write:       0.07s
Parse time:      0.32s
Bind time:       0.26s
Check time:      0.78s
Emit time:       0.21s
Total time:      1.57s
```

The question is do you intend to include these files in your compilation? if no, then you should add `App_Scripts` to your `exclude` in tsconfig.json.
