### ISSUE TITLE
Modularization reverted adding nullability annotations to es6.d.ts

### ISSUE THREAD

**Issue by Arnavion** [Microsoft/TypeScript#7810]
#7715 reverted the ES6 part of #7650

Eg: Array.findIndex:

Before: https://github.com/Microsoft/TypeScript/blob/9705c89/src/lib/es6.d.ts#L334

After: https://github.com/Microsoft/TypeScript/blob/68bdbe0/src/lib/es2015.array.d.ts#L22

cc @yuit

**Comment by mhegazy** [comment]
@yuit can you put back the nullablility changes please.
