### ISSUE TITLE
Duplicate declaration for core-js `PropertyKey` type alias 

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript#7812]
Core-js definition file defines a `PropertyKey` like the one in lib.es6.d.ts, now that this is in the main library, this is breaking the core-js compilation.
See https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/core-js/core-js.d.ts#L21

Possible fix, rename the type declaration to something else now, to avoid breaking changes with the next TS release.

**Comment by myitcv** [comment]
Worth noting this also breaks with `lib.es5.d.ts` when using [`DefinitelyTyped/es6-shim`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/7de6c3dd94feaeb21f20054b9f30d5dabc5efabd/es6-shim/es6-shim.d.ts#L6), which I guess is a common pattern?

**Comment by yuit** [comment]
The fix is in; by moving the `PropertyKey` into es2015.core instead of having it in es5

**Comment by myitcv** [comment]
@yuit @mhegazy thanks both. Confirmed fixed in `1.9.0-dev.20160406`
