### ISSUE TITLE
Major issues with class aliasing

### ISSUE THREAD

**Issue by bcherny** [Microsoft/TypeScript#7816]
```ts
class A {}

const B:A = A

new A
new B // Error: Cannot use 'new' with an expression whose type lacks a call or construct signature.

class C extends A {}
class D extends B {} // Error: Type 'A' is not a constructor function type.
```

This breaks the angular 1.x injector pattern:

```ts
angular.module('a').service('b', function(
  myClass: MyClass
){
  new myClass {} // Error!
}
```

**Comment by mhegazy** [comment]
`const B: typeof A = A`

see https://github.com/Microsoft/TypeScript/wiki/FAQ#whats-the-difference-between-bar-and-typeof-bar-when-bar-is-a-class- for more details

**Comment by mhegazy** [comment]
checking the FAQ: https://github.com/Microsoft/TypeScript/wiki/FAQ is usually a good idea before filing a new issue.
