### ISSUE TITLE
Way to catch accidental references to 'this' in contexts where its type is 'any'

### ISSUE THREAD

**Issue by mattmccutchen** [Microsoft/TypeScript#7819]
Suggestion:

I just tracked down a bug in my application where I had copied and pasted a chunk of code containing references to `this` from a class method to an ordinary function declaration and neglected to replace the `this` references.  Normally TypeScript is pretty good at catching everything I need to change, but this time the code compiled without error because `this` had type `any` and then failed at runtime.  I'd like a way to catch such accidental references.

One obvious proposal would be a flag, in the same spirit as `--noImplicitAny`, that reports an error whenever `this` is used in a context in which its type is `any` (see the [spec](https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#4.2)).  The only other idea I had was to completely avoid function declarations and function expressions in favor of static methods of a dummy class, but I feel like that would be ugly.  #3694 would offer a slightly better solution of setting the `this` type to `{}`, but the developer could forget to do so on a particular function.  The flag would be the most foolproof.

With the flag and in the absence of #3694, there needs to be a way to explicitly convert `this` to another type at the beginning of a function body without triggering the error.  Two possible forms that could be allowed:
```
let self = <T>this;
let self: T = this;
```
I'm thinking any more complicated use of `this` should trigger the error.

What would be the rationale for applying a restriction to `this` and not other values of type `any`?  When the developer explicitly declares a value of type `any`, they have intentionally opted out of checking (of intentionally and accidentally introduced references!) based on their judgment that the overall cost outweighs the benefit.  The same cannot be said of `this` in function declarations and function expressions.  Maybe there are other constructs that TypeScript assigns type `any` by default for which developers should be able to opt in to stricter checking; I just haven't run into them yet.

Thanks for reading!  I would be surprised if this hadn't been proposed before, but I wasn't able to find it using either an issue search or a web search.

**Comment by RyanCavanaugh** [comment]
Is there anything you're looking for that isn't covered at #6018?

**Comment by mattmccutchen** [comment]
No.  I was dimly aware of #6018 but didn't read it carefully before filing this. :(

**Comment by RyanCavanaugh** [comment]
Once the PR's in it'd be great to get some feedback on how it worked for you. Thanks!
