### ISSUE TITLE
Prototype properties non enumerable

### ISSUE THREAD

**Issue by jpolo** [microsoft/TypeScript#782]
To make Typescript Class more like default ES classes it could be interesting to make every prototype property non enumerable.

I've made a little snippet that do simply the work and could be added to the `__extend`, etc. :

```
__proto = this.__proto || function (proto) {
      if (Object.getOwnPropertyNames) {//only when ES5
        var keys = Object.getOwnPropertyNames(proto);
        var key;
        for (var i = 0, l = keys.length; i < l; ++i) {
          key = keys[i];
          desc = Object.getOwnPropertyDescriptor(proto, key);
          desc.enumerable = false;
          Object.defineProperty(proto, key, desc);
        }
      }
    }

//generated code
var Greeter = (function () {
  function Greeter() {}
  Greeter.prototype.foo = function () {};
  __proto(Greeter.prototype);
  return Greeter;
}())
```

**Comment by coreybutler** [comment]
I'm not sure I agree with setting every prototype property to be non-enumerable, but I do think it would be useful to do this for all private properties/methods.

In my use case, I'm developing node modules that are designed to be extended. I used to get a lot of support requests from people who would run a `console.log(obj)` to see all of the available properties/methods... and the natural next step is to... use them. This caused a lot of headaches when people would use properties/methods that were supposed to be private. In some cases they'd delete the property unintentionally, typically causing a train wreck in the support forums. I started creating all of the private properties/methods using `object.defineProperties` so I could explicitly define `enumerable`, `writable`, and `configurable` values and these support headaches went away.

While I understand it would be nicer to only maintain 2 runtime class constructs.... well, you are supporting 3 versions of ES, each of which evolved for a reason. While I'm sure it might be a bit more of a pain in the ass, it doesn't seem outlandish (to me) to maintain a construct for each version of ES. After all, isn't that kind of the point behind the TS awesome sauce?

**Comment by NoelAbrahams** [comment]
> I'm developing node modules that are designed to be extended. I used to get a lot of support requests from people who would run a console.log(obj) to see all of the available properties/methods...

That sounds rather old school. Why not publish a `.d.ts` together with the library?

In my opinion, `Object.defineProperties` is somewhat obsolete. It's one of those ES5 features that we never touched.

**Comment by coreybutler** [comment]
@NoelAbrahams 

> "Why not publish a .d.ts together with the library?"

It's not safe to assume all end users are using TypeScript... in fact, none of mine are. My library (which is more of a framework) is basically a collection of classes to build upon, primarily infrastructure components. For example, I have a hot-switch proxy that's updated in realtime via a REST API... most people who are using the `Proxy` class are just adding minor customizations, and they don't need/want to setup TypeScript to do it. For me, the move to TypeScript (which is still in progress) is more about aligning _contributors_ to my projects than it is about the end user who will consume the code. I certainly won't stop them from using TypeScript (I'll encourage it), but I can't assume they'll use it.

I think `Object.defineProperties` was never given enough credit, and it's used more often than most people realize. I personally don't care about the syntax... the point is about setting the enumerability of a property/method. That is something I have not been able to cleanly replicate with TypeScript.

I'm still learning the ins and outs of TypeScript, but I have yet to replicate `configurable` and `writable` properties as well. I'd love to see something like `private static myvar:string` or something along those lines. I can do all of this with native JS, but that somewhat defeats one of the value-adds I see in TS, which is simplicity and readability of more complex structures. If I set a property to `private`, I expect it to be private, not pseudo-private.

**Comment by jpolo** [comment]
> It's not safe to assume all end users are using TypeScript
Totally agree with that. 
In fact that was the main purpose of this issue when I posted it. As private values are properly shadowed by the TS compiler, the idea of making prototype value not enumerable is clearly at _runtime_.

As the ES6 is becoming a reality, what is the spec saying for the prototype properties? TS classes would ideally look like as much as possible like the future standard.

**Comment by coreybutler** [comment]
To the best of my understanding, prototype properties are still in the ES6 spec, and it does not appear the [current draft](http://people.mozilla.org/~jorendorff/es6-draft.html#sec-class-definitions) supports a native `private` option... not in the context of this discussion (though `static` appears). Community suggested workarounds use the somewhat convoluted `Symbol` pattern. There's speculation that ES7 will remove prototype properties, but it's just speculation at this point.

**Comment by jpolo** [comment]
There's a confusion here: I never referred about _privacy_ of properties but about their _enumerability_ .
It's more a runtime matter than a dev safe encapsulation for example : 
```javascript
var obj = new TypeScriptGeneratedClass();
for (var prop in obj) { /*...*/ }
```
Depending on the ```TypeScriptGeneratedClass.prototype``` properties enumerability you will have significant differences between results (and performance too).

**Comment by coreybutler** [comment]
@jpolo - yeah, I realized that after posting. That's really what I'm after as well, at least for now. I suppose I'm piggybacking on your request with an additional "ask" around truer privacy. However; that's more of a "nice to have", and there is still obvious debate around the spec itself... the enumerability is more of a hack for privacy that works effectively today, and combining with the `configurable` and `writable` prototype properties makes it a decent mimic of true privacy.

I think the ES specs and the consortium's take on privacy will effect the decision to maintain prototype properties to some degree though.

**Comment by Rycochet** [comment]
Just came across a major use-case for this - sending a class instance via jQuery.ajax - it uses the `for(...in...)` style of enumeration for the data to send (via POST at least), and while that could in some circumstances be taken as "bad" by not using `.hasOwnProperty()`, there's just as many cases when it is needed - and as the longstanding behaviour, it isn't something that should easily be changed (unless they do so for jQuery3)...

I've got a single function that I can call with a classname and have it set everything in the prototype chain to non-enumerable, but would prefer not to have to (sadly it's not possible in everything).

**Comment by mgol** [comment]
Babel does this correctly. Amongst other problems, this may introduce bugs to projects migrating from Babel to TypeScript.

As for the original argument, I think ES3 vs ES5 parity is now much less important than four years ago and especially less important than ES5 vs ES6+ parity or parity between Babel & TypeScript.

Can this be revisited?
