### ISSUE TITLE
intellisense does not work when using `module.exports.fnName`

### ISSUE THREAD

**Issue by egamma** [Microsoft/TypeScript#7824]
_From @SamVerschueren on April 5, 2016 6:53_

- VSCode Version: 0.10.14 (insiders) and below
- OS Version: Mac OS X 10.11.3

Steps to Reproduce:

1. Create a file called `cfx.js` with the following content

```js
'use strict';
module.exports.generateCanvas = function (fileOrUrl) {
	console.log(fileOrUrl);
};
```

2. Create a file `index.js`

```js
'use strict';
var cfx = require('./file1');
```

3. When you type `cfx.` in `index.js`, it will not suggest `generateCanvas`. If you change `cfx.js` to `exports.generateCanvas` instead of `module.exports.generateCanvas`, it works.

This seems to be a bug because both notations are equivalent.

_Copied from original issue: Microsoft/vscode#4943_

**Comment by NickGrease** [comment]
I just wanted to add that this issue happens on Windows 10 / VSCode-Insider as well.

**Comment by danielo515** [comment]
Why is this closed? it still happening:

OS X El Capitán
VSCode Versión 1.5.2 (1.5.2)

I have to attach the exports directly to the exports object instead of module.exports which I prefer.

Regards

**Comment by kitsonk** [comment]
This is part of TypeScript 2.0, which isn't quite yet GA.  Have you manually updated your VSCode to use TypeScript 2.0?

**Comment by danielo515** [comment]
Hello @kitsonk , no I did not. Is there any manual somewhere?

**Comment by SamVerschueren** [comment]
https://code.visualstudio.com/docs/languages/typescript#_using-newer-typescript-versions

**Comment by Gektorian** [comment]
Still reproducing on VSC 2.2.1

**Comment by mhegazy** [comment]
@Gektorian can you file a new issue and share more details.

**Comment by zhengbli** [comment]
@Gektorian can you share your version of TS as well in the new issue. I could not repro with the latest:
![image](https://cloud.githubusercontent.com/assets/1171301/24370909/f1d92fb8-12dd-11e7-9b85-555c01c29ca3.png)

**Comment by Gektorian** [comment]
I have 2 files. On is -> node_modules\dw\order\OrderMgr.js.

`var OrderMgr = function(){};`
`OrderMgr.getOrder = function(){};`
`module.exports = OrderMgr;`

 Another one doing require on this one -> 
`var OrderMgr = require('dw/order/OrderMgr'); `
When I try to type OrderMgr.(ctrl+space) - I see only this https://puu.sh/v0xZY/5d2a81cedd.png

**Comment by zhengbli** [comment]
Can you elaborate where do these things in the webstorm screenshot come from? Since it is not from your sample code. And the VSCode screenshot shows that we know the `OrderMgr` is a function, hence the `apply` etc. methods, that's what we mean by saying this issue is fixed.

**Comment by Gektorian** [comment]
@zhengbli it is from my sample code, I just didn't add rest of the methods, full version will be - 

```
var OrderMgr = function(){};

OrderMgr.getOrder = function(){};
OrderMgr.queryOrders = function(){};
OrderMgr.searchOrder = function(){};
OrderMgr.failOrder = function(){};
OrderMgr.cancelOrder = function(){};
OrderMgr.placeOrder = function(){};
OrderMgr.searchOrders = function(){};
OrderMgr.createOrder = function(){};
OrderMgr.undoFailOrder = function(){};
OrderMgr.processOrders = function(){};
OrderMgr.describeOrder = function(){};
OrderMgr.queryOrder = function(){};
OrderMgr.createShippingOrders = function(){};

OrderMgr.order=null;

module.exports = OrderMgr;
```

**Comment by zhengbli** [comment]
Still not reproing this. Is my setup correct?
![untitled](https://cloud.githubusercontent.com/assets/1171301/24469817/a8140a5c-1471-11e7-90af-80d9dd396c7d.png)

I guess there may be some else bugs that messed up your intellisense. If you can create a minimum repro project that would be helpful.

**Comment by Vaccano** [comment]
Not sure if I should make an new issue for this, but this does not work with classes.

Here is an example:

**File: UsefulStuffFileName.js**

```
class UsefulStuff {
    constructor(initValue) {
        this.initValue = initValue;
    }

    get someValue(){
        return this.initValue + " someValue";
    }

    doStuff(input) {
        return input + " stuff done";
    }
}

module.exports.UsefullStuff = UsefullStuff;
```

**File: WorkingHere.js**

```
var useful = require('UsefulStuffFileName');

class WorkingHere {
    constructor() {
        this.usefulStuff = new useful.UsefulStuff("Hello");
    }

    doCoolStuff() {
        // I want intellisense options when I type the period after this.usefulStuff
        // The options would be someValue, doStuff() and initValue.
        //                                |
        //                                |
        //                                V
        let myVariable = this.usefullStuff.someValue;                
    }
}
```
Let me know if I should post this as a separate issue, or if I am just doing it wrong...
