### ISSUE TITLE
error in chainable piping with event emitters

### ISSUE THREAD

**Issue by hbakhtiyor** [Microsoft/TypeScript#7825]
**TypeScript Version:** 

1.8.7

**Code**

```ts
private streamProcess(stream: NodeJS.ReadableStream): Promise<void> {
    return new Promise<void>((ok, fail) => {
        stream
            .pipe(this.parser.createStream()) // returning type is `NodeJS.ReadWriteStream`
            .on("error", fail)
            .pipe(this.transformer.createStream()) // returning type is `NodeJS.ReadWriteStream` and error appears in the line
            // error TS2339: Property 'pipe' does not exist on type 'EventEmitter'.
            .on("error", fail)
            .pipe(this.persister.createStream()) // returning type is `NodeJS.WritableStream`
            .on("error", fail)
            .once("finish", () => {
            });
    });
}
```

**Expected behavior:**

**Actual behavior:** 
i got error if only set event emitters, what's the wrong of the code?

**Comment by DanielRosenwasser** [comment]
What version of `node.d.ts` are you using? Can you make sure it's completely up to date?

The version I'm looking at seems to use `this` typing so that your chained calls should maintain the type. [See here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/d969b903d1fce89a5e43828ec68458b4f852db4d/node/node.d.ts#L1790).

**Comment by DanielRosenwasser** [comment]
Also, as a general rule, these sorts of questions really belong on StackOverflow since the team gets so many issues a day. I am curious as to whether there's a bug on our end though.

**Comment by hbakhtiyor** [comment]
i use `"github:DefinitelyTyped/DefinitelyTyped/node/node.d.ts#2d64e0d9450e084b30f5c0e39e88a5a861a6d7c1"`
https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/2d64e0d9450e084b30f5c0e39e88a5a861a6d7c1/node/node.d.ts

**Comment by DanielRosenwasser** [comment]
Update your `.d.ts` file to the latest and it should work.
