### ISSUE TITLE
Compiler Options Documentation, output file order documentation ?

### ISSUE THREAD

**Issue by daslicht** [Microsoft/TypeScript#7826]
The compiler Option Documentation which can be found here : 
**https://www.typescriptlang.org/docs/handbook/compiler-options.html**
Refers to the ```output file order documentation```

Where to find it ?
```
--outFile		Concatenate and emit output to single file. The order of concatenation is determined by the list of files passed to the compiler on the command line along with triple-slash references and imports. See output file order documentation for more details.
```

**Comment by mhegazy** [comment]
I do not think this ever existed. we have a [todo to fill](https://github.com/Microsoft/TypeScript/wiki/FAQ#how-do-i-control-file-ordering-in-combined-output---out-).

the closest thing we have is: https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Triple-Slash%20Directives.md#preprocessing-input-files

**Comment by daslicht** [comment]
Thank you !

**Comment by mhegazy** [comment]
if you do not mind, i would like to keep this open. we should fix this.

**Comment by daslicht** [comment]
You are welcome ! Thank you !

**Comment by mhegazy** [comment]
i have added the documentation here: https://github.com/Microsoft/TypeScript/wiki/FAQ#how-do-i-control-file-ordering-in-combined-output---out-

**Comment by ulrichb** [comment]
Could you please update the FAQ section for the TS 2.0 "include" option (especially what happens with wild card includes)?
