### ISSUE TITLE
Union types behave differently depending whether the variable is direct argument of the function

### ISSUE THREAD

**Issue by zuzusik** [Microsoft/TypeScript#7830]
**TypeScript Version:** 

1.8.5

**Code**

```ts
type Result = boolean | string;
type GetResult = () => Result;
type ResultParam = GetResult | Result;

function getResult(result : ResultParam) {
  return result instanceof Function 
  	? result() 
	: result;
}

function getResultFromParams(params : {result : ResultParam}) {
  return params.result instanceof Function 
  	? params.result() 
	: params.result;
}
```
[Code in Playground](http://www.typescriptlang.org/play/index.html#src=type%20Result%20%3D%20boolean%20%7C%20string%3B%0Atype%20ResultParam%20%3D%20GetResult%20%7C%20Result%3B%0Atype%20GetResult%20%3D%20()%20%3D%3E%20Result%3B%0A%0Afunction%20getResult(result%20%3A%20ResultParam)%20%7B%0A%20%20return%20result%20instanceof%20Function%20%0A%20%20%09%3F%20result()%20%0A%09%3A%20result%3B%0A%7D%0A%0Afunction%20getResultFromParams(params%20%3A%20%7Bresult%20%3A%20ResultParam%7D)%20%7B%0A%20%20return%20params.result%20instanceof%20Function%20%0A%20%20%09%3F%20params.result()%20%0A%09%3A%20params.result%3B%0A%7D%0A)

**Expected behavior:**
script is compiled

**Actual behavior:** 
compilation error is thrown on function `getResultFromParams`: 
(13,7): error TS2349: Cannot invoke an expression whose type lacks a call signature.

**Comment by Arnavion** [comment]
Type guards don't narrow types of property expressions. See #3812
