### ISSUE TITLE
Code example error in Enums section in the Handbook

### ISSUE THREAD

**Issue by gburdeti** [Microsoft/TypeScript#7833]
I know it's minor but just to let you know there's an error in a code example in the Handbook's [Enums section](https://www.typescriptlang.org/docs/handbook/enums.html).

```typescript
enum FileAccess {
    // constant members
    None,
    Read    = 1 << 1,
    Write   = 1 << 2,
    ReadWrite  = Read | Write
    // computed member
    G = "123".length
}
```

should be 
```typescript
enum FileAccess {
    // constant members
    None,
    Read    = 1 << 1,
    Write   = 1 << 2,
    ReadWrite  = Read | Write,
    // computed member
    G = "123".length
}
```

**Comment by mhegazy** [comment]
The handbook sources are in https://github.com/Microsoft/TypeScript-Handbook. feel free to file issues and/or send PRs to that repo.

**Comment by gburdeti** [comment]
Thanks for the info.
