### ISSUE TITLE
pathMapping doesn't use `rootDirs` for absolute or mapped paths

### ISSUE THREAD

**Issue by alexeagle** [Microsoft/TypeScript#7837]
Here's a mockup of our directory structure:
```
$ cat binary/some/other/project/bin-a.ts
export let a;
$ cat generated/path/to/my/project/gen-b.ts
export let b;
$ cat generated/spot/for/node/modules/angular2/core.d.ts
export let bootstrap;
$ cat path/to/my/project/c.ts
// NOTE: we don't use a relative path here because it's a walk up to the top of the source tree and back
import {a} from 'some/other/project/bin-a';
import {b} from './gen-b';
import {bootstrap} from 'angular2/core';
```

And tried to compile with
```
"compilerOptions": {
        "module": "commonjs",
        "target": "es5",
        "noImplicitAny": false,
        "sourceMap": false,
        "baseUrl": ".",
        "rootDirs": [
          "generated",
          "binary",
          "."
        ],
        "paths": {
          // NOTE: this assumes we'll resolve it under the "generated" root, to find the generated .d.ts file
          "angular2/*": ["spot/for/node/modules/angular2/*"]
        },
        "noEmit": true
    },
```

and I get
```
$ ./node_modules/.bin/tsc
path/to/my/project/c.ts(1,17): error TS2307: Cannot find module 'some/other/project/bin-a'.
path/to/my/project/c.ts(3,25): error TS2307: Cannot find module 'angular2/core'.
```

In Vlad's comment we see why:
https://github.com/Microsoft/TypeScript/issues/5039#issuecomment-191821779

> `baseUrl` / `paths` are used to resolve non-relative module names and `rootDirs` are applied only for relative names

Sorry we didn't notice this earlier. I believe @mprobst had verified our use cases against https://github.com/Microsoft/TypeScript/issues/2338 and then maybe the design changes before merge made this no longer work. I'm just now working to update google-internal to use this (we are also blocked on https://github.com/Microsoft/TypeScript/issues/7573 )

@mprobst please check if I've accurately represented the shape of imports that we want. @vladima I know this is close to release, so I wonder what our options are now. Could rootDirs be consulted for all resolutions, or did you eliminate that option in the design process?

**Comment by mhegazy** [comment]
so why not specify these in path as well:

```json
"compilerOptions": {
        "baseUrl": ".",
        "rootDirs": [
          "generated",
          "binary",
          "."
        ],
        "paths": {
            "*" : [ "generated/*", "binary/*", "./*" ],
           "angular2/*": ["spot/for/node/modules/angular2/*"]
        }
    },
```

**Comment by alexeagle** [comment]
Ah, thanks Mohamed, that's a good point. It gets verbose since I also need
```
"paths": {
          "angular2/*": ["spot/for/node/modules/angular2/*",
          "generated/spot/for/node/modules/angular2/*"]
        },
```

but we codegen the tsconfig.json so I don't really care how it looks.

**Comment by mhegazy** [comment]
The idea is that rootDirs are for relative imports, as you have no other way of changing how these are resolved. but for non-relative names you have paths and baseUrl. We have more documentation on using baseUrl, paths and rootDirs at https://github.com/Microsoft/TypeScript-Handbook/blob/release-2.0/pages/Module%20Resolution.md#additional-module-resolution-flags
