### ISSUE TITLE
error TS5001: The current host does not support the '--watch' option.

### ISSUE THREAD

**Issue by oising** [Microsoft/TypeScript#7838]
TypeScript 1.8.9, Visual Studio 2015 Update 2 RTM

```ts
c:\myproject> tsc --w
error TS5001: The current host does not support the '--watch' option.
```

I would expect this to work on the Windows platform? I'm running Window 10 th2.

**Comment by mhegazy** [comment]
`tsc.exe` does not support watch option. `node tsc.js` does, it should work on windows, and on other platforms as well.

see https://github.com/Microsoft/TypeScript/issues/2375

**Comment by DanielRosenwasser** [comment]
Linking to Gitter response as well: [April 5, 2016 1:38 PM](https://gitter.im/Microsoft/TypeScript?at=57042263ad40c3877fa98e6f)
