### ISSUE TITLE
Should be able to declare dotted name with `debugger`

### ISSUE THREAD

**Issue by RyanCavanaugh** [microsoft/TypeScript#7840]
e.g. https://developer.chrome.com/extensions/debugger

This seems to be impossible to write a definition file for, since you can't write

``` ts
declare module chrome.debugger {

}
```

**Comment by mhegazy** [comment]
feel free to send a PR for it. 
the main reason for the restriction is to make sure the emitted code is valid, since we are not emitting anything in this case, we can relax the limitation.

but jsut to be clear. `declare module debugger {}` is still not allowed.

**Comment by RyanCavanaugh** [comment]
We could emit this correctly if we wanted to -- we already have the machinery in place to rename the local name of a module (e.g. `module M.X { export var X  = 10; }`)

**Comment by DanielRosenwasser** [comment]
An easy workaround is to just use interfaces as a heads up. So it's not impossible to write that declaration file.

**Comment by mcdirmid** [comment]
Trying to use the chrome.debugger extension point in Typescript, is there a work around for this yet?

**Comment by evmar** [comment]
@DanielRosenwasser can you give an example of just using interfaces to work around this problem?

**Comment by evmar** [comment]
Here's my lame attempt.  I keep trying to module-augment the namespace and failing.

```
declare namespace chrome {
  function someChromeFunc(): void;
}

declare namespace chromeDebuggerNS {
  interface debuggerInterface { a: string; }
  function someDebuggerFunc(): void;
}
interface chromeWithDebugger {
  "debugger": typeof chromeDebuggerNS;
}


chrome.someChromeFunc();
const chromeDebugger = (chrome as any)['debugger'];

chromeDebugger.someDebuggerFunc();
```

**Comment by dzou** [comment]
Any update on a workaround for this issue? For myself, I've copied and pasted the commented out stuff in my own externs file and do a 'chrome as any as ChromeWithDebugger'. Doesn't seem like a particularly elegant solution.

**Comment by mhegazy** [comment]
you can write this today using `export {.. as debugger};`:

```ts
declare module chrome {
    namespace _debugger {
        export function debug(a: number): void;
    }
    export { _debugger as debugger };
}
```
