### ISSUE TITLE
Add moduleIds as compiler option similar to babel

### ISSUE THREAD

**Issue by jonricaurte** [Microsoft/TypeScript#7847]
Hi,

This is a feature request for adding moduleIds as a compiler option. This is useful for doing something similar to what babel has and what outFile currently does(but on a file by file basis, and not into one file):

https://babeljs.io/docs/usage/options/

This is useful because sometimes you want to have control on a file by file basis and only recompile files that changed while doing some overhead work. I know typescript already has a watch feature, but I have other things than just recompiling files in my workflow and would like to have the option myself to compile files on a file by file basis.

Thanks.

**Comment by mhegazy** [comment]
The TS API supports passing a name to the transform function

The basic definition is in https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API#a-simple-transform-function
the module name is an extra parameter you can pass in https://github.com/Microsoft/TypeScript/blob/b0584b58fa07ee8c06e6d6f0f1bce2d4c37c7640/lib/typescript.d.ts#L2404

Also if you are using AMD you can use `/// <amd-module name="..." />` see http://www.typescriptlang.org/docs/handbook/triple-slash-directives.html#amd-module-
