### ISSUE TITLE
[Transforms] initialization of static members done after class is exported 

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript#7853]
Expected:
```js
    var C1 = (function () {
        function C1() {
            this.m1 = 42;
        }
        return C1;
    }());
    C1.s1 = true;
    exports.C1 = C1;
```

Actual:
```js
    var C1 = (function () {
        function C1() {
            this.m1 = 42;
        }
        return C1;
    }());
    exports.C1 = C1;
    C1.s1 = true;
```

Failed tests:

* es3defaultAliasIsQuoted.ts
* amdImportNotAsPrimaryExpression.ts
* tests\cases\compiler\systemModuleTargetES6.ts

Also in RWC:

* Azure_ContactsExtension

Here the statics are private. Maybe this makes a difference?

```ts
export class Class {
  private static idParameter = "id";
  // ...
}
```

Baseline:
```js
  // ...
  Class.idParameter = "id";
  return Class;
}());
exports.Class = Class;
```

Actual:

```js
  return Class;
}());
exports.Class = Class;
Class.idParameter = "id";
```

**Comment by yuit** [comment]
Fix in latest commit

**Comment by sandersn** [comment]
Still repros in RWC: Azure_ContactsExtension.

**Comment by mhegazy** [comment]
this is currently by design. since the ts transforms run before both module and es6 transforms.
there should not be any functional differences though. if you see instances where the code is functionally different please reopen.
