### ISSUE TITLE
Salsa Feedback

### ISSUE THREAD

**Issue by bowdenk7** [Microsoft/TypeScript#7854]
This issue can be used for general feedback on the new JavaScript language service Salsa. If you feel like something is a bug, file a separate issue, but for general discussion and feedback just comment below. We will spin off new topic or feature request issues as needed.

**Comment by iwaldman** [comment]
emmet support withing JSX

**Comment by mhegazy** [comment]
> emmet support within JSX

@iwaldman can you elaborate?

**Comment by DanielRosenwasser** [comment]
Because nobody explains it on the first try (see https://github.com/Microsoft/TypeScript/issues/4835#issuecomment-166167477 and https://github.com/Microsoft/TypeScript/issues/6508#issuecomment-208433259), Emmet is a macro system for HTML-like languages that works as you type. VS Code has support for it as far as I know.

**Comment by mhegazy** [comment]
> Emmet (see #4835 (comment) and #6508 (comment)), is a macro system for HTML-like languages that works as you type. VS Code has support for it as far as I know (Microsoft/vscode#732).

I understand, i was more interested in what the request was, is it to develop an emmet like system for TS? just JSX? why not just use emmet?

**Comment by aersamkull** [comment]
In TypeScript we do have namespaces. In JavaScript there are idioms for this. I sometimes write something like this:
```JavaScript
// Create a namespace "memDb.controllers"
window.memDb = window.memDb || {};
memDb.controllers = memDb.controllers || {};

memDb.controllers.AClass = class { 
 // ...
};
```

Should something like this be supported by Salsa? How to do namespaces in Salsa?

**Comment by mhegazy** [comment]
@aersamkull this is tracked by https://github.com/Microsoft/TypeScript/issues/7632

**Comment by chicoxyzzy** [comment]
Are language extensions (analogues to babel plugins) planned in Salsa? It'll be cool if we'll be able to throw out Babel which is used mainly for React optimisations ([1](http://babeljs.io/docs/plugins/transform-react-constant-elements/), [2](http://babeljs.io/docs/plugins/transform-react-inline-elements/)) (BTW this might be in core of TS isn't it?) and code instrumentation.

**Comment by AbraaoAlves** [comment]
Salsa could be used to generate definition files from js, like Typescirpt does from ts. There are any plans for this?

**Comment by aluanhaddad** [comment]
@AbraaoAlves #7546 tracks that. It would be super useful.

**Comment by MystK** [comment]
Would be great to have AMD module support! 👍 :)

**Comment by mhegazy** [comment]
Looks like we have issues tracking most of the suggestions here. Please file new issues as needed. Closing this issue for housekeeping purposes.
