### ISSUE TITLE
[Transforms] Unnecessary parentheses around YieldExpression

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript#7855]
**Expected**:

```js
o.a = yield p;
```

**Actual**:
```js
o.a = (yield p);
```

Failed tests:
 
* tests/cases/conformance/async/es6/awaitBinaryExpression/awaitBinaryExpression5_es6.ts

**Comment by DanielRosenwasser** [comment]
With which target? ES5 or ES6?

**Comment by vladima** [comment]
@mhegazy can you please add a name of test file that uncovers the issue?

**Comment by mhegazy** [comment]
> tests/cases/conformance/async/es6/awaitBinaryExpression/awaitBinaryExpression5_es6.ts

**Comment by rbuckton** [comment]
Fixed in #7904.
