### ISSUE TITLE
[Transforms] Incorrect emit for ShorthandPropertyAssignment for an exported value

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript#7862]
**Expected**:

```js
  var aa;
    (_a = { a: a, b: b }, a = _a.a, b = _a.b, _a);
    (_b = { b: b, a: a }, a = _b.a, b = _b.b, _b);
```

**Actual**:

```js
  var aa;
    (_a = { a, b }, a = _a.a, b = _a.b, _a);
    (_b = { b, a }, a = _b.a, b = _b.b, _b);
```

Failed tests:
*  tests/cases/conformance/es6/destructuring/declarationsAndAssignments.ts
* objectLiteralShorthandPropertiesWithModuleES6.js
* giant.js

The last two are failures from namespace exports, not module exports.

**Comment by sandersn** [comment]
This doesn't repro any more. Looks like it's fixed.
