### ISSUE TITLE
NPM packaging guidance for converting comilper d.ts files to external modules

### ISSUE THREAD

**Issue by patrick-rodgers** [Microsoft/TypeScript#7872]
**TypeScript Version:** 

1.8.2

**Code**

On [this page](https://www.typescriptlang.org/docs/handbook/typings-for-npm-packages.html) the statement is made that the modules should "**be written as external modules**" when using with the typings entry.

I am using declarations option with outFile to produce a single *.d.ts file which I want to include in my NPM package. This produces ambient module declarations, which is not compatible with using the typings entry in package.json.

Does guidance exist to convert these compiler produced *.d.ts files to an acceptable format for use with the typings entry in package.json?

**Comment by DanielRosenwasser** [comment]
The problem here is that by using `--outFile`, you're creating modules that can be consumed only in an AMD/SystemJS setting, and in turn, you can't consume it in vanilla Node.js. The same thing applies to your `.d.ts` file if you're using the Node strategy. At that point, you've basically made it problematic for your users to consume your library. So I'm wondering how you're currently intending for users to consume the library over npm.

**Comment by patrick-rodgers** [comment]
Working on that, and looking for the best way. I am only using outFile to build the single d.ts file in my build flow. When I create the .js file I compile into separate files and then combine using browserify. It is that .js file I would like to distribute with the d.ts file along side so that case would be:

npm install blah

thing = require(blah)

and thing has intellisense in my new typescript project thanks to included d.ts file.

Perhaps I am going about this entirely wrongly, which would be good to know and I can go in another direction.

**Comment by DanielRosenwasser** [comment]
I think I see what you mean - but my feeling is that you should have non-bundled `.js`/`.d.ts` files in your package for regular npm users (sometimes in a folder called `lib`), and Browserify should be doing the custom concatenation steps for anyone who wants to bundle (often into a folder called `dist`).

**Comment by patrick-rodgers** [comment]
Not sure if I am closer or not. Rebuilt the NPM package and included a lib folder that includes my raw compiled js files with the d.ts files along side. So file.js and file.d.ts site side by side. I updated the main to point to file.js and typings to point to both the entire lib folder as well as the specific file.d.ts but now get the error "Module '' resolves to a non-module entity and cannot be imported using this construct."

Honestly not sure if that is the js or d.ts file that is causing the issue. I am using UMD for build type for the js files, the d.ts files are just included as they are output. I am using the "import { name } from "npm-module-name";" syntax. I'll keep plugging away and see what I can find.

**Comment by DanielRosenwasser** [comment]
> but now get the error "Module '' resolves to a non-module entity and cannot be imported using this construct."

Where exactly are you getting this error?

**Comment by patrick-rodgers** [comment]
I get that error when I hover over the Import statement in the TypeScript file in the test project.

Now, interestingly (at least to me), if I change the file extension of my test file from .ts to .js and I change the include style to: var thing = require("npm-module-name");

Everything works as expected. I get intellisense support and all the various components resolve as expected off my root entity "thing".

So I guess my question has become how to mimic this behavior in a .ts file? I am using vs code, so perhaps the limitation is there. Seems to be really close to what I want to end up with.

**Comment by patrick-rodgers** [comment]
And solved. I changed the import to: import thing= require("npm-module-name"); in the .ts file and everything works as expected. So the final solution was:

- Include an uncompressed build in the npm package with the d.ts files along side the js files
- Use the main and typings values in the package.json to point to the root js and d.ts files.
- Use the import thing= require("npm-module-name"); include syntax (maybe unique to how my code is structured)

Thanks Daniel for the help on this, going to go ahead and close the issue.
