### ISSUE TITLE
Fourslash facilities for testing script lexical structure are lacking

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#789]
Right now when doing a fourslash test for a file's lexical structure, the idea is to set up markers which represent portions of the lexical tree, and do something like 

```TypeScript
test.markers().forEach((marker) => {
    verify.getScriptLexicalStructureListContains(marker.data.itemName, marker.data.kind, marker.fileName, marker.data.parentName);
});

verify.getScriptLexicalStructureListCount(N);
```

every time.

This is highly undesirable because it allows us to be implicit about the relations between different lexical items. It would be *much* more desirable if we simply had a function that took the lexical structure as a JS object, and confirmed that the expected structure matches the actual structure.

**Comment by mhegazy** [comment]
@DanielRosenwasser this should be fixed now, correct?

**Comment by DanielRosenwasser** [comment]
Not really, this is part of an ongoing concern over the way fourslash itself tests, and is the original issue that caused us to consider baselining API results, and as @RyanCavanaugh suggested

**Comment by mhegazy** [comment]
We have no intimidate plans for changing how fourslash works today. Closing for now, marking it as revisit.
