### ISSUE TITLE
Quick info on object literal destructuring assignment of "for of" statement shows incorrect quick info

### ISSUE THREAD

**Issue by sheetalkamat** [Microsoft/TypeScript#7901]
**TypeScript Version:** 

1.7.5 / 1.8.0-beta / nightly (1.9.0-dev.20160217)

**Code**

```ts
interface I {
    property1: number;
    property2: string;
}
var elems: I[];

var p2: number;
for ({ /**/property1: p2 } of elems) {
}

```

**Expected behavior:**
Quick info shows:
(property) I.property1: number

**Actual behavior:** 
(property) property1: I

**Comment by mhegazy** [comment]
> (property) property1: I

`I` is not correct. it is a `number` is not it?
