### ISSUE TITLE
[tsserver] Support for "definitions" command (several definition)

### ISSUE THREAD

**Issue by angelozerr** [microsoft/TypeScript#7905]
Take a sample:

```
import {IFoldingRange} from 'vs/editor/contrib/folding/common/foldingRange';

export function computeRanges(): IFoldingRange[]
```

I would like when I do a Ctrl+Click on the last IFoldingRange that IDE provides 2 definitions:
- a definition with import {} (like today). Here Ctrl+Click on IFoldingRange[] select {IFoldingRange}
- a definition where IFoldingRange is exported. Here Ctrl+Click on IFoldingRange[] open "vs/editor/contrib/folding/common/foldingRange" file and select where IFoldingRange is exported.

So it should be cool if tsserver could provide "definitions" command to return this array of definition.

**Comment by RyanCavanaugh** [comment]
We now skip through `import`s and that seems to be broadly preferred
