### ISSUE TITLE
Intellisense doesn't work with constant function parameters

### ISSUE THREAD

**Issue by egamma** [Microsoft/TypeScript#7928]
_From @startrekdude on April 5, 2016 23:49_

- VSCode Version: 0.10.11
- OS Version: Windows 10

Steps to Reproduce:

[files.zip](https://github.com/Microsoft/vscode/files/205553/issue.zip)

1. Create a file called SomeAPI.js with the following content:
```javascript
var SomeAPI = (function () {
   "use strict";  
    var exports = {};
    
    exports.sayHello = function (name) {
        alert("Hello, " + name);
    }

    return exports;
})();
```
2. Create a file called SomeAPI.d.ts with the following content:
```typescript
declare namespace SomeAPI {
    function sayHello (name: string) => void;
}
```
3. Create a file called app.js with the following content:
```javascript
/// <reference path="./SomeAPI.d.ts"/>
(function (SomeAPI) {
    "use strict";

    var hello = function () {
        SomeAPI.sayHello(document.body); // Oops! No Intellisense!
    }

    document.addEventListener("DOMContentLoaded", hello);
})(SomeAPI); // This one works
```
4. Mouse over the line where it says "SomeAPI.sayHello" (in app.js). 

Observed Behaviour:
Visual Studio Code's Intellisense informs the user that SomeAPI is of the any type, as is it's child sayHello.

Expected Behaviour:
Visual Studio Code informs the user that SomeAPI is a namespace and that sayHello is a function that takes a string.

Why this bug is important to fix:
Immediately-Invoked Function Expressions were a common way of doing modules and scoping before ES6's (awesome) import statements. There is a lot of legacy code that still uses them.

_Copied from original issue: Microsoft/vscode#4990_

**Comment by egamma** [comment]
Moving to TypeScript for investigation

**Comment by DanielRosenwasser** [comment]
@startrekdude your `.d.ts` file seems incorreclty authored. Did you mean the following?

```ts
declare namespace SomeAPI {
    function sayHello(name: string): void;
}
```

**Comment by startrekdude** [comment]
Indeed. :smile:
Here's an updated zip file: [files.zip](https://github.com/Microsoft/TypeScript/files/209139/issue.zip)

**Comment by 2426021684** [comment]
Sadly the TS team has decided not to add this feature. See #4142 and #7601.

**Comment by DanielRosenwasser** [comment]
Reopened #4142.
