### ISSUE TITLE
How to extend javascript code completion and other features

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#7929]
_From @minggo on April 5, 2016 9:9_

Now i create `cocos.d.ts` for my javascript library code completion. It works perfectly. But i have some special requirements. In my library, the inheritances looks like:

```javascript
cc.Class({
    extends: cc.Component,  // the base class is cc.Component
    myfunc: function() {
        var s = this.myFunc();   // myFunc is a property of cc.Component, want completion for properties of cc.Component, want type checking and all other features that are available
         s.   // want code completion, type checking and all other features that are available
        ...
    },
    ...
});
```

As the codes shows, the inheritance is runtime related. How can i extend javascript code completion to let VSCode know `this` is an instance of `cc.Component`'s subclass?

_Copied from original issue: Microsoft/vscode#4946_

**Comment by dbaeumer** [comment]
_From @minggo on April 5, 2016 9:12_

@isidorn @weinand Any idea? Thanks.

**Comment by dbaeumer** [comment]
_From @minggo on April 6, 2016 2:0_

@dbaeumer Any idea?

**Comment by dbaeumer** [comment]
@minggo to my knowledge you can't right now. But moving to TS. May be they have an idea.

**Comment by mhegazy** [comment]
That is correct. There is now way of doing this, the recommendation would be to use ES6 class pattern.
