### ISSUE TITLE
Generics inference of type (static) intersection on instance shape

### ISSUE THREAD

**Issue by shlomiassaf** [Microsoft/TypeScript#7934]
I'v build a nice library for composition of types (mixin) in a dynamic way so the bookkeeping overhead of having to write stand-in members is not needed. (the lib also has some other features and customisation for composition).

It works great but I have one last bookkeeping overhead that bothers me, The lib requires to explicitly set the Type parameters since I can't get it to work when I let typescript infer the types.

Here's an example of what i'm facing:
**TypeScript Version:** 
1.8.9

**Code**
`A` and `B` are "example" classes, we will use them for demonstration.
Each have one `static` member and one `instance` member, we will use them verify the output when mixin them together.
```ts
class A {
    static STATIC_A: string = 'A';
    instanceA: string = 'A';
    constructor() { }
}
class B {
    static STATIC_B: string = 'B';
    instanceB: string = 'B';
}
```

### A "naive" approach using a simple function:
```ts
    function mergeTypes<T, Z>(type1: T, type2: Z): T & Z {
        // Do some work to mixin the types.
        return <any>{};
    }
    let AB = mergeTypes(A, B);  // Inferred AB: typeof A & typeof B
    let ab = new AB();          // Inferred ab: A

    AB.STATIC_A;    // Compiler OK 
    AB.STATIC_B;    // Compiler OK
    ab.instanceA;   // Compiler OK
    ab.instanceB;   // Compiler ERR: Property 'instanceB' does not exist on type 'A'
```

> Conclusion: Intersection of static types will not propagate to the instance shape.

### A more explicit approach with a control unit and state.
```ts
// Define a contract to bind an instance type param (T/Z) to its static "parent" (TType/ZType)
interface ConcreteTypeOf<T> extends Function { new (...args): T; }

// Explicitly say what we are dealing with:
class MergeTypes<T, TType extends ConcreteTypeOf<T>, Z, ZType extends ConcreteTypeOf<Z>> {
    constructor(private type1: TType, private type2: ZType) {}

    // We return a constructor for T & Z and intersect static members.
    merge(): ConcreteTypeOf<T & Z> & TType & ZType {
        // Do some work to mixin the types.
        return <any>{};
    }
}
```

**An implicit attempt first, let the compiler infer for us**
```ts
let AB = new MergeTypes(A, B).merge();  // Inferred AB: ConcreteTypeOf<{}> & typeof A & typeof B
let ab = new AB();                      // Inferred ab: {}

AB.STATIC_A;    // Compiler OK 
AB.STATIC_B;    // Compiler OK
ab.instanceA;   // Compiler ERR: Property 'instanceA' does not exist on type '{}'
ab.instanceB;   // Compiler ERR: Property 'instanceB' does not exist on type '{}'
```

>**It turns out that the compiler infers `ConcreteTypeOf<T & Z>`  to be `ConcreteTypeOf<{}>`, WHY?**

**Finally, a working version, but we need to explicitly express what we want:**
```ts
let AB = new MergeTypes<A, typeof A, B, typeof B>(A, B).merge();    // Inferred AB: ConcreteTypeOf<A & B> & typeof A & typeof B
let ab = new AB();                                                  // Inferred ab: A & B

AB.STATIC_A;    // Compiler OK 
AB.STATIC_B;    // Compiler OK
ab.instanceA;   // Compiler OK 
ab.instanceB;   // Compiler OK 
```

If i'll be able to remove the need to explicitly express the type I will be able to have an easy API for composition/mixin what ever, that can create type's on the fly and save a reference for them (compile time type reference) as if they were defined expressively.

**Comment by shlomiassaf** [comment]
BTW, I know that I'm sending the `static` type to the constructor so the compiler only "knows" about TType since T is not part of the constructor.

This is probably why T&Z = {}

I just don't know how to "extract" the instance shape from a `static` type in a generic form.
i.e: If I have `class A{}` I know that `A` is the instance shape and `typeof A` is the anonymous static type but when 'typeof A` is a type parameter (T) the compiler doesn't have an explicit contract to infer instance shape from it's static type.

**Comment by shlomiassaf** [comment]
@RyanCavanaugh I'v love to hear your insights on this.

**Comment by DanielRosenwasser** [comment]
It sounds like you potentially want to pass in the prototypes of each constructor, or you want to write

```ts
function mergeTypes<T, Z>(type1: { prototype: T }, type2: { prototype: Z }): new () => T & Z {
    // Do some work to mixin the types.
    return <any>{};
}
```

Also see some of the discussion that went on over at #4559.

**Comment by shlomiassaf** [comment]
@DanielRosenwasser 
In your example, T and Z are the instance type.
When you return `new () => T&Z` you actually return a "blank" type that only "knows" to creates an instance of the mixed in T&Z however all static metadata about this type is lost.

**This is a complex issue, so I will try to simplify a bit, I will only address the core issue I see:**

```ts
// Simple class that holds a Type.
// Has 2 type param's that are bound and represent both "types" of a class.
class TypeWrapper<T, TType extends new () => T> {
    constructor(private _type: TType) {}
    getType(): TType {
        return this._type;
    }
}

// A factory of TypeWrapper
// this trick enables return the typeof type dynamically 
function make<T, TType extends new () => T>(type: TType) {
    return new TypeWrapper<T, typeof type>(type);
}

let typeWrapper = make(class A {}); 
const Clazz = typeWrapper.getType();
let cls = new Clazz();
```

Now, what did the compiler inferred as type for `Clazz`? 
![image](https://cloud.githubusercontent.com/assets/5377501/14366393/3c4401a6-fd1b-11e5-81ed-4e635a32622a.png)
`typeof A`, Looks legit :)

But what does the compiler think about `timeWrapper`?
![image](https://cloud.githubusercontent.com/assets/5377501/14366201/56d5d77a-fd1a-11e5-8bde-75246a16716f.png)
`TypeWrapper<{}, typeof A>` notice the {} and not A.
Well, it knows about the TType param but nothing about T so it makes it {}.

The compiler knows that `TType` is a constructor for T but It only get TType in the signature.
Why can't it infer T from TType, or in other words, given `typeof X` can the compiler infer X?

**Comment by Arnavion** [comment]
btw in the playground atleast, hovering over `AB` in `new AB()` from the "naive" code sample in the OP throws an error `Cannot read property 'flags' of undefined`. I didn't see if it's fixed in master.

![image](https://cloud.githubusercontent.com/assets/1096010/14380885/0cd86c6a-fd37-11e5-93c5-fb10ae1b2d61.png)

```
editor.main.js:6 Uncaught Error: TypeError: Cannot read property 'flags' of undefined

TypeError: Cannot read property 'flags' of undefined
    at Object.t [as buildSymbolDisplay] (https://www.typescriptlang.org/play/Script/vs/languages/typescript/common/lib/typescriptServices.js:22:3918)
    at https://www.typescriptlang.org/play/Script/vs/languages/typescript/common/lib/typescriptServices.js:32:21522
    at p (https://www.typescriptlang.org/play/Script/vs/languages/typescript/common/lib/typescriptServices.js:32:21307)
    at Object.f [as symbolToDisplayParts] (https://www.typescriptlang.org/play/Script/vs/languages/typescript/common/lib/typescriptServices.js:32:21480)
    at H (https://www.typescriptlang.org/play/Script/vs/languages/typescript/common/lib/typescriptServices.js:35:11607)
    at Object.j [as getQuickInfoAtPosition] (https://www.typescriptlang.org/play/Script/vs/languages/typescript/common/lib/typescriptServices.js:35:14991)
    at Object.i [as compute] (https://www.typescriptlang.org/play/Script/vs/languages/typescript/common/typescriptWorker2.js:1:6652)
    at t.computeInfo (https://www.typescriptlang.org/play/Script/vs/languages/typescript/common/typescriptWorker2.js:2:26137)
    at https://www.typescriptlang.org/play/Script/vs/languages/typescript/common/typescriptMode.js:1:19518
    at then (https://www.typescriptlang.org/play/Script/vs/base/common/worker/workerServer.js:1:24735)(anonymous function) @ editor.main.js:6
editor.main.js:11 Main Thread sent to worker the following message:e._onError @ editor.main.js:11e._onmessage @ editor.main.js:11e._onSerializedMessage @ editor.main.js:11(anonymous function) @ editor.main.js:11worker.onmessage @ editor.main.js:14
```

**Comment by RyanCavanaugh** [comment]
One solution would be #7234. That would make the "simplified" example work as expected. This is sort of an abuse of generics since you don't *really* want two type parameters there, but would work.

The alternative is #6606 (assuming it supported `new`), since then you would be able to write out the return type as ` { new(): (typeof new A()) & (typeof new B()) } & A & B }`.

**Comment by mhegazy** [comment]
filed https://github.com/Microsoft/TypeScript/issues/7966 to track the crash in quick info

**Comment by shlomiassaf** [comment]
@RyanCavanaugh #7234 and #6606 are spot on! 

### Here's the interesting thing about your suggestion with #6606:

As I said, I'm working on a lib for mixin's and type composition with realtime type composition.
So the core of it is in the following class, which is similar to my "simplified" exapmle:
```ts
export interface ConcreteTypeOf<T> extends Function { new (...args): T; }

class TypeWrapper<T, TType extends ConcreteTypeOf<T>> {

    constructor(private _type: new () => T, dupe: TType = undefined) {}

    get asType(): T {  return <any>this._type;  }
    get asStaticType(): TType { return <any>this._type; }

    mixType<Z, ZType extends new () => Z> (t: ConcreteTypeOf<Z>, dupe: ZType = undefined) 
						: TypeWrapper<T & Z, ConcreteTypeOf<T & Z> & TType & ZType>  {
         return <any>this;
    }
}
```
Here are some notable changes from the "simplified" example:
 * Added a "dupe" param to the constructor, this is the workaround to get static type meta. if a user supply it he we will have "static" type meta, so `new TypeWrapper(A, A)` will have static & instance types of A and the compiler knows about T and TType.
 * Added to `getter` to get both instance type and static type of the dynamic class.
 * Add a `mixType` method, gets a type and returned the mixed type (no implementation), same logic as constructor regarding dupe type.

**Note** the return type `TypeWrapper<T & Z, ConcreteTypeOf<T & Z> & TType & ZType>` same as your suggestion with #6066 but with a redundant parameter.

Here's an example of what we get from it:

```ts
export class A{
	static IM_STATIC_A: string;
	imInstanceA: string;
}

class B_{
	static IM_STATIC_B: string;
	imInstanceB: string;
}
class C_{
	static IM_STATIC_C: string;
	imInstanceC: string;
}
```

```ts
let tw = new TypeWrapper(A, A)
	.mixType(B_, B_)
	.mixType(C_, C_);
	
// let's expose out our new type to the world:
export const Composed = tw.asStaticType; 
export type Composed = typeof tw.asType;
```
![image](https://cloud.githubusercontent.com/assets/5377501/14399396/f88903d2-fdf4-11e5-8d08-793d5bf3af43.png)
![image](https://cloud.githubusercontent.com/assets/5377501/14399423/427749d6-fdf5-11e5-97b1-b1baa773b351.png)

Quite Cool!

However I had to remove the intersection of `TType & ZType` from the return type of `mixinType` in `TypeWrapper` which means the static type is gone.
```ts
    mixType<Z, ZType extends new () => Z> (t: ConcreteTypeOf<Z>, dupe: ZType = undefined) 
						: TypeWrapper<T & Z, ConcreteTypeOf<T & Z>>  {
         return <any>this;
    }
```


Here's why...
**Lets mixin with, the output of a previous mixin, `Composed` as base:**
```ts
class D {
	static IM_STATIC_D: string;
	imInstanceD: string;
}

let twD = new TypeWrapper(Composed,Composed)
	.mixType(D, D);
	
export const DComposed = twD.asStaticType; 
export type DComposed = typeof twD.asType;
```

If we don't remove the `TType & ZType` intersection from the return type of `mixType`:
![image](https://cloud.githubusercontent.com/assets/5377501/14399620/1701f5b0-fdf7-11e5-93b5-4a7f70e7cd0e.png)
> Note the error and the instance shape is only D now.

If we remove it, we loose static type meta but have full instance shape.
![image](https://cloud.githubusercontent.com/assets/5377501/14399641/4cbd7148-fdf7-11e5-9d06-2a14b63d5e8e.png)

Also worth noting, both with `TType & ZType` and without it, the new type is not "extendable"
With it:
![image](https://cloud.githubusercontent.com/assets/5377501/14399687/da44a0d6-fdf7-11e5-947c-ac56b9e8f50e.png)


Without it:
![image](https://cloud.githubusercontent.com/assets/5377501/14399706/057c4a42-fdf8-11e5-8fda-e06c62643e2e.png)

I really like the outcome, even without static meta tough its an issue.
Beside's mixing in 2 types I manages to mixing single members which make composition really cool.

If these issues are solved it will make the type system super super flexible.

Thanks!

**Comment by shlomiassaf** [comment]
@RyanCavanaugh 
After playing with `typeof expressions` using the compiler built for #6066 I'm quite positive now that 
#7234 will actually solve the problem.

Now matter what you do, if the compiler cant infer an instance type from it's static type you can't fill the missing gap.

**Comment by mhegazy** [comment]
Closing in favor of #7234
