### ISSUE TITLE
No compilation error on a weird line

### ISSUE THREAD

**Issue by Rouche** [Microsoft/TypeScript#7937]
Hi,

I have this line wich i took from a javascript code but forgot to add "=" when converting.
```ts
public require: "ngModel";
```
It compiles ok. Im pretty sure it should not because the line is not in the corresponding .js!

Tryed to search for duplicate but its a bit hard to find the right search terms.

Is it normal?

Thanks.

**TypeScript Version:** 

1.8.9

**Expected behavior:**
Compilation error. (I wish)

**Actual behavior:** 
Compiles with no errors, but the code is not inside the generated .js

**Comment by DanielRosenwasser** [comment]
Unfortunately this declares a property that uses a [string literal type](http://www.typescriptlang.org/docs/release-notes/typescript-1.8.html#string-literal-types). I'm not really sure specifically what we could do here. If you tried *using* the property, you'd get an error eventually though.

**Comment by Rouche** [comment]
Ack, it was introduced in 1.8. So its a property empty of type "ngModel".

I guess its too late for string litterals types to be defined like a generic?
```ts
public require: type<myStringType>
```

For some cases, (Angular require), its not simple to detect the error. Since its not the direct code that uses it.

Gotta be more carefull then!

Thanks.

**Comment by DanielRosenwasser** [comment]
Yeah, unfortunately it is. The other thing is that this is a pretty valid use-case since you might want to tag each of your classes with a property, and then use a union type between them as a discriminator.

**Comment by DanielRosenwasser** [comment]
On the up-side, I think we might be able to do some definite-assignment checking down the line with strict nullability checks. If you had that on, you'd get an error in that case because you never initialized the `require` property.

**Comment by Rouche** [comment]
That would be a nice workaround.
