### ISSUE TITLE
Trailing commas are not removed from arrays when target is ES3

### ISSUE THREAD

**Issue by mhegazy** [microsoft/TypeScript#7938]
**TypeScript Version:** 

this is a regression from TS 1.0

**Code**

``` ts
var x = [1,]
console.log(x.length);
```

**Expected behavior:**
length is 1

**Actual behavior:** 
On ES3 engine length is 2, on an ES5 one length is 1.

**Comment by RobertoMalatesta** [comment]
+1

**Comment by Emeryao** [comment]
+1
