### ISSUE TITLE
let variable shadowing let variable of same name cannot reference outer variable in initialiser

### ISSUE THREAD

**Issue by myitcv** [Microsoft/TypeScript#7939]
Tested with `1.8` and `1.9.0-dev.20160406`

Is it intentional that the following fails to compile?

```ts
let x = 5;

{
	console.log(x); // Block-scoped variable 'x' used before its declaration
	let x = x;      // Block-scoped variable 'x' used before its declaration
	console.log(x);
}
```

The inner `x` is effectively shadowing the outer `x`, but only at and after the point it is redefined (i.e. the inner `let x`)

I couldn't find any specific mention of this in https://github.com/Microsoft/TypeScript/pull/904 which appears to be the documentation for `let` right now (via [the spec](https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#53-let-and-const-declarations))

Thanks

**Comment by DanielRosenwasser** [comment]
It's actually part of the ECMAScript standard. [Every block introduces its own environment record](https://tc39.github.io/ecma262/2016/index.html#sec-blockdeclarationinstantiation) and creates a local binding for each lexical declaration (i.e. each `let`, `const`, etc.). That means that even if you shadow an outer variable later in your block, **any prior uses will refer to the one declared within the block**. In an ES2015+ runtime, that would cause a `ReferenceError` to get thrown. In TypeScript, we give you a compile-time error.

**Comment by myitcv** [comment]
@DanielRosenwasser thanks very much, I should have thought to check the ECMAScript standard too. Totally clear from the spec.
