### ISSUE TITLE
React 15.0 support

### ISSUE THREAD

**Issue by kuon** [Microsoft/TypeScript#7947]
As I guess many people will hit this one, I think it's good that it has its own issue for reference.

React 15.0 cannot be used with typescript 1.8.9 because of `__spread` removal.

Details: https://github.com/Microsoft/TypeScript/issues/7270

**Comment by DanielRosenwasser** [comment]
This doesn

**Comment by DanielRosenwasser** [comment]
Good call, though it's easier for us to track the change here.

**Comment by kuon** [comment]
Yeah, it was just for the SEO side of thing.

**Comment by buzinas** [comment]
@DanielRosenwasser there where?

**Comment by RyanCavanaugh** [comment]
@buzinas #7270
