### ISSUE TITLE
type inference with if-return

### ISSUE THREAD

**Issue by unional** [Microsoft/TypeScript#7949]
TS (1.9.0-dev.20160407)

Don't know if this is possible :rose: : 
```ts
function working(param: string | string[]) {
  if (typeof param === "string") {
    // param is string
  }
  else {
    // param is string[]
  }
}

function notWorking(param: string | string[]) {
  if (typeof param === "string") {
    // param is string
    return;
   }
   
   // param is string | string[]
   // Can it be detected and inferred as string[] here?
}
```

**Comment by basarat** [comment]
This is already done as a part of the code flow analysis that Anders is doing (not on master yet) :rose:

**Comment by RyanCavanaugh** [comment]
See #2388

**Comment by basarat** [comment]
@unional PR is up if you want to watch for the moment it getting merged : https://github.com/Microsoft/TypeScript/pull/8010#issue-147490616 :rose:

![image](https://cloud.githubusercontent.com/assets/874898/14485410/3728be68-019a-11e6-9b51-fd486c42e994.png)
