### ISSUE TITLE
Inheritance with different constructor signatures and a 'typeof' function parameter: not assignable.

### ISSUE THREAD

**Issue by SineOfLight** [Microsoft/TypeScript#7955]
I'm having an issue that foces me to rewrite the type of a function parameter to 'any' instead of 'typeof SomeSuperClass' because a subclass that extends that superclass, but has _another constructor signature_ cannot be passed into that function anymore. Is this expected behavior? My intuition says no. I've read that it has to do with some Javascript function type check conflict because of the use of 'typeof', but currently I don't see another clean way to pass a class type as an argument in a function. without resolving to strings. And the use of 'typeof' seems to break when a subclass has another constructor signature.

See code, where function foo(..) accepts the subclass with equal constructor signature, but rejects the other subclass which has another constructor signature:

**TypeScript Version:** 

1.7.5 

**Code**

```ts
class Super {
    private a: number;
    constructor(a : number) {
        this.a = a;
    }
}

class SubSameConstructor extends Super {
    private b: number;
    constructor(a : number) {
        super(a);
        this.b = a;
    }
}

class SubDifferentConstructor extends Super {
    private b: number;
    constructor(a : number, b: number) {
        super(a);
        this.b = b;
    }
}

function foo(classParam: typeof Super) {
    console.log(classParam);
}

foo(SubSameConstructor); // works
foo(SubDifferentConstructor); // TS2345: Argument of type 'typeof SubDifferentConstructor' is not assignable to parameter of type 'typeof Base'.
```

**Expected behavior:**
Being able to pass a subclass with different constructor signature into a function that accepts an argument of type 'typeof Super' to pass class types.

**Actual behavior:** 
The last function call does not compile.

**Comment by Arnavion** [comment]
If it were allowed, how would you reconcile this?

```typescript
function foo(classParam: typeof Super) {
    return new classParam(5); // classParam is `{ new(a: number): Super }`
}

foo(SubDifferentConstructor); // Calls `new SubDifferentConstructor(5)`
```

**Comment by SineOfLight** [comment]
Ok thank you. I haven't realised you could do new classParam(..) with a typeof argument.

The solution, then, seems to be constructor overloading, as per:

```ts
class SubDifferentConstructor extends Super {
    private b: number;
    constructor(a: number);
    constructor(a: number, b: number);
    constructor(a?: number, b?: number) {
        super(a);
        this.b = b;
    }
}
```


But in my real application, the base class needs injected services which are not on the super class. I suppose this solution is worth the 'risk', because we would never call new classParam() anyway. If we do, we can throw an error in the baseclasses generic constructor implementation if the optional parameters are undefined.

**Comment by Arnavion** [comment]
If you don't want to do `new classParam` then you don't need the construct signature in whatever type you *do* accept, so instead of `typeof Super` accept a wider type that `typeof Super` as well as `typeof` all its subclasses are assignable to.

**Comment by alienriver49** [comment]
I just ran into this exact issue and was expecting it work how @SineOfLight laid it out in his first example. In my case I was going to have different constructor signatures because I was using Aurelia's dependency injection to inject required services, etc. into the class, as well as create the class, not manually. But I still wanted to be able to pass the constructors of a base class to a function and have the type checking with typeof.

My workaround was to create a generic Constructor type and use that:
`type Constructor<T = {}> = new (...args: any[]) => T;`

Then in SineOfLight's example, the foo function would be this:
`function foo(classParam: Constructor<Super>) {
    console.log(classParam);
}`
