### ISSUE TITLE
NodeFlags Needs Expansion

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#7956]
As per https://github.com/Microsoft/TypeScript/pull/7952#discussion_r58987334, we have almost exhausted all possible node flags. While I believe @rbuckton is shifting them around for transforms, I don't know the extent to which using/reusing would be a breaking change.

**Comment by DickvdBrink** [comment]
Is this still an issue? It looks like the NodeFlags enum is changed and the largest is `1 << 18`.
So I think this one can be closed?

**Comment by RyanCavanaugh** [comment]
Yep, Anders refactored these out a while ago. Thanks for pointing it out - one fewer open issue 😄
