### ISSUE TITLE
--outDir and existing definition files

### ISSUE THREAD

**Issue by farfromrefug** [Microsoft/TypeScript#7957]
**TypeScript Version:** 
1.8.9

Hi i am using ```outDir:"dist"``` option for my compiler.

Now my ```src``` is like this:
```
- test.d.ts
- test.ts
```
I handle the ```.d.ts``` myself because i want to force the definitions

Now the issue is that in the outDir i end up with a ```test.d.ts``` generated based on the ```test.ts``` and not the one i implicitely create. Which is also the one i get auto complete from.

I think that if the compiler see an alreading existing definition file, it should copy it and not even generate one.
Don't you think?

**Comment by mhegazy** [comment]
The compiler sees an input file `test.ts` and a declaration flag `--d`, it generates a declaration file for `test.ts` in `test.d.ts`. if you want to override it, add a post build step to copy your pre-canned `test.d.ts` to the output location.

**Comment by farfromrefug** [comment]
that's what i do. Thanks
