### ISSUE TITLE
--outDir and --rootDir

### ISSUE THREAD

**Issue by farfromrefug** [Microsoft/TypeScript#7958]
**TypeScript Version:** 
1.8.9

I am generating a library using the ```outDir``` option. The idea is mostly not to pollute my ```src``` dir.
But the issue is that i still want reference relative path to be relative as if the files where in ```src```
The problem mostly happens with existing definition files in ```src```
I think the problem is related to [this one](https://github.com/Microsoft/TypeScript/issues/7957)

let's say src is ```assets```
and ```outDir``` is ```build/assets```

my src :
```
test.d.ts
test.ts
test2.ts
```
```test2.ts``` reference ```./test.d.ts```

my ouptut dir (```build/assets```) looks like this
```
test.js
test.js.map
test2.js
test2.js.map
test.d.ts
test2.d.ts
```
the problem appears in ```test2.d.ts``` and ```test2.js.map``` and ```test.js.map```
in ```test2.d.ts``` it references ```../../assets/test.d.ts``` when i want ```./test.d.ts```
in ```test2.js.map``` it references its ```sources```  ```../../assets/test2.ts``` when i want ```test2.ts```
same in ```test.js.map```

I tried the option ```rootDir``` and set it to ```assets``` as i thought that was what it was for : to force all relative output path to be related to it. But it doesn't work.

Is there any way to do this? I need this because even if i build inside a different dir i still want to package it as if it was in the source dir.

**Comment by mhegazy** [comment]
The compiler does not copy files around. it generates outputs for sources (i.e `.ts` files) in the desired location. A triple slash reference directive in a source file needs to be maintained in the output file. but since the relative location of files may change, the compiler will update it to reflect the location in the output. 
looks like you have a custom locaiton for some of your .d.ts files; there is no way for the compiler to know that. not rewriting the triple-slash references would result in an error in the output. 

options:
1. do not use triple-slash references, as you move things around, possible add a static index.d.ts that would be the entry point to your library, and has a triple slash reference to all your other .d.ts with the correct locations, and 
2. consider using the new flag `--declarationDir`, this allows you to specify where your declarations would go, and would be different from `--outDir` in this workflow, you could have a setup like:

```tree
src
|- test1.ts
|- test2.ts
definitions
|- test.d.ts
```

```cmd
tsc --declaration --declarationDir .\definitions --outDir .\out src\test1.ts src\test2.ts definitions\test.d.ts
```

the result would be

```tree
src
|- test1.ts
|- test2.ts
definitions
|- test.d.ts
|- test1.d.ts
|- test2.d.ts
out
|- test1.js
|- test2.js
```

hope that helps.

**Comment by farfromrefug** [comment]
I understand your point. But when compiling libraries that might be moved around or packaged as a zip file it would be nice to be able to set a "rootDir" to be used also for source map and reference finding.
It would be the directory where the compiler would suppose the find the original ts/definition files.
In my case i would put the output dir itself to "simulate" my packaged folder.

**Comment by mhegazy** [comment]
The `.d.ts` files do not impact source maps in any shape or form. so do not think the source map discussion is relevant here.

the question is about why does the compiler not copy .d.ts input files to output. the rational is, these files could be acquired from some third party, and you do not want to copy `mocha.d.ts`,` jasmin.d.ts`, `jquery.d.ts`, etc.. for every file you compile. if this is really the intention, a post build script that copies the files should do the job.

**Comment by farfromrefug** [comment]
Well actually the copying was the point of [another ticket] (https://github.com/Microsoft/TypeScript/issues/7957)
Here my point really is about relative paths in definitions files after compilation.
And i talk about sourcemap because tsc generates source map which have the exact same relative paths.

Now about your point on external .d.ts files you are totally right!
But shouldn't we make a difference in the compilation between definitions from the project and definitions from externals? My project definitions are supposed to be "compiled" and thus packaged. External definitions are there only for reference for the compiler. I think it would make sense.
Anyway i solved this copying problem as you said by copying the file afterwards.

**Comment by mhegazy** [comment]
> But shouldn't we make a difference in the compilation between definitions from the project and definitions from externals?

From the compiler perspective there is no distinction. they are all `.d.ts` files. the only difference here is that all are not "transformed" or "compiled". only source (`.ts`) files are.

> And i talk about sourcemap because tsc generates source map which have the exact same relative paths.

consider using `--mapRoot` to tell the compiler where your root will be at runtime,

**Comment by farfromrefug** [comment]
Wow thanks i did not see the mapRoot option.

i get your point about definitions files. But for me the ones coming from an external library are not be considered as the ones i am implementing. Especially if i am actually writing myself an library.

For example if i were to rewrite lodash in typescript, i might separate my lib into multiple ts files but still maintain only one definition file. Does it make sense?
If so i would want to "publish" my definition and so i would expect it to be part of the compilation product. 
It's kind of like if was to write a c++ lib. If i write a header file that i want to be published with the compiled lib i would ask my compiler env to copy it at product location. As an example XCode offers to do this and deliver any header i want (might it be generated or not) with the lib.

Anyway i don't want to take too much of your time on this. I already have a solution to fix this on my side.
Just felt really weird to me to see my own definition being overwritten in the sense that another generated definition was generated with the same name but not the content i expected.

Thanks for your time

**Comment by jombie** [comment]
@mhegazy  I am using typescript 
```sh
tsc --version
Version 1.9.0-dev.20160412
```
My tsconfig.json is as below:
```sh
{
  "compileOnSave": false,
  "buildOnSave": false,
  "compilerOptions": {
    "module": "commonjs",
    "target": "es6",
    "moduleResolution": "node",
    "preserveConstEnums": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "noImplicitAny": false,
    "noEmitOnError": false,
    "forceConsistentCasingInFileNames": true,
    "removeComments": false,
    "sourceMap": true,
    "jsx": "react",
    "outDir": "./lib",
    "declaration": true
  },
  "exclude": [
    "node_modules",
    "dist",
    "typings/browser",
    "typings/browser.d.ts"
  ]
}
```
My project folder structure is as below:
```sh
work/
`-- projects
    `-- projectx
        |-- dist
        |-- src
        `-- tsconfig.json
```
I am trying to compile and generate .d.ts files inside the 'lib' dir but this creates the .d.ts file inside folder with parent attached to lib i.e
```sh
work/
`-- projects
    `-- projectx
        |-- src
        |-- dist
        |   `-- work
        |       `-- projects
        |           `-- projectx
        |               `-- dist
        |                   `-- lib
        |                       `-- src
        |                           `-- index.d.ts
        `-- tsconfig.json
```

I was expecting it to be as :
```sh
work/
`-- projects
    `-- projectx
        |-- dist
        |   `-- lib
        |       `-- src
        |           `-- index.d.ts
        |-- src
        `-- tsconfig.json 
```
**dist** dir above is given in the webpack.config.js as  below:
```sh
output: {
    path: path.join(__dirname, '/dist'),
    filename: outputFile,
    library: libraryName,
    libraryTarget: 'umd',
    umdNamedDefine: true
  }
```

Is this by design or am I missing some config option.
I also tried with declarationDir option but the same result.

**Comment by mhegazy** [comment]
@jombie this does not look right. can you share a sample project that reproduces the issue?

**Comment by jombie** [comment]
@mhegazy  Hi please find a sample project with the above mentioned error.
[Sample Project](https://github.com/jombie/projectx).

**Comment by mhegazy** [comment]
looks like ts-loader /webpack issue.

building from the commandline, i.e. `tsc --p tsconfig.json`, i see the output generated in `./lib/Components/TestComponent.js`. specifying `"rootDir": "./"` in `tsconfig.json` does the right thing as well, and creates the output in `./lib/src/Components/TestComponent.js` which again what i expect.

so leads me to conclude that ts-loader is doing something else. @jbrantly -- any thoughts?

**Comment by jbrantly** [comment]
Currently ts-loader uses the raw `.name` that is returned from TS to figure out where to put the declaration file. This was a recent addition and didn't really take into account outDir or webpack configuration or anything like that. Feel free to open an issue on ts-loader though.
