### ISSUE TITLE
"TS2349: Cannot invoke an expression whose type lacks a call signature." when using union type containing a function

### ISSUE THREAD

**Issue by fzzzt** [Microsoft/TypeScript#7960]
**TypeScript Version:** 

This is with TypeScript version 1.8.4.0 working in a TSX file in VS2015.

**Code**

The actual code is a big React component, so here is a sample with just the guts:

```ts
interface BarProps {
  failedContent?: string | Array<string> | JSX.Element | (() => JSX.Element);
}
class Bar extends React.Component<BarProps> {
  render() {
    let content = this.props.failedContent(); // TS2349
    //let content = (this.props.failedContent as () => JSX.Element)(); // Workaround
  }
}
```

**Expected behavior:**

I would expect it to "just work" in a "native" fashion, meaning the compiler recognizes that the property can be a function, so a function call isn't necessarily an incorrect usage, and that explicit casting isn't necessary. Is this syntax/functionality not supported, or am I writing it incorrectly maybe?

**Actual behavior:** 

It generates a compiler error.

**Comment by Arnavion** [comment]
>so a function call isn't necessarily an incorrect usage

But it is *potentially* an incorrect usage. The compiler only allows functions to be called, and you haven't convinced it that it's a function. If you run this code at runtime and the caller passes in a string for that prop, then this is going to blow up with a type error, which is exactly what TS is intended to prevent.

So the correct thing to do is to check whether the prop is a function or not and handle both cases accordingly.

```typescript
interface BarProps {
  failedContent?: string | string[] | (() => string);
}
class Bar {
	props: BarProps;

	render() {
		const { failedContent } = this.props;
		if (typeof failedContent === "function" && !(failedContent instanceof Array) {
			let content = failedContent();
		}
		else {
			throw new Error("Expected failedContent prop to be a function.");
		}
	}
}
```

Note:

- Type guards only function with simple bindings (variables, function parameters), not expressions, so you can't use `this.props.failedContent` directly.

- The `typeof === "function"` type guard should be sufficient on its own, but for some reason TS doesn't remove the array type with just that.

- In the current 1.8 release the `throw` does not prevent the rest of the `render` function from also getting the narrowed type. This is being fixed (among other things) in the new type guards implementation.

**Comment by fzzzt** [comment]
That is almost exactly what I have, but my call is within a `switch (typeof failedContent)`, which evidently the compiler doesn't pick up for stripping off the other types.

**Comment by Arnavion** [comment]
`switch` for type guards is #2214

---

Your second point is the same as my second note, i.e. that `typeof === "function"` doesn't strip the object type. For `Array` I could get it to work by doing `instanceof Array` but since `JSX.Element` is an interface that doesn't work for it.

One way is to check `typeof === "object"` and assert that as a test for whether it's a `JSX.Element` or not using [user-defined type guards.](https://www.typescriptlang.org/docs/handbook/advanced-types.html#user-defined-type-guards)

```typescript
		if (((arg): arg is JSX.Element => typeof arg === "object")(failedContent)) {
			let content = failedContent; // JSX.Element
		}
```

Perhaps open a separate issue for why `typeof === "function"` doesn't strip object types and vice versa.

**Comment by cawa-93** [comment]
The following code also results in an error TS2349:
```typescript
if (typeof this.method === 'function') {
	let method = this.method(); // TS2349
} else {
	let method = this.method; // Work
}

let method = typeof this.method === 'function' ? this.method() : this.method; // TS2349
let params = typeof this.method === 'string' ? this.params : this.params(); // TS2349
```
The method has been declared in the class:

```typescript
export class DeamonService {
    private method: string | (() => string);
    // ... other code
}
```

**Comment by mhegazy** [comment]
@cawa-93 this should be working as intended in TS 2.0 and later. please give it a try.

**Comment by cawa-93** [comment]
@mhegazy, Yes. With tsc@2.0 there are no error.

**Comment by nexbit** [comment]
Using TS 2.0, this doesn't work either:

```
getFromRepo(ids: string | number | string[] | number[]): Promise<any> {
        if (Array.isArray(ids)) {
            const promises: Promise<any>[] = [];
            (ids as string[] | number[]).forEach((id: string | number) => {  // TS2349
                promises.push(this.repository.find(id));
            });
            return Promise.resolve(Promise.all(promises));
        }
        else {
            return this.repository.find(ids as string | number);
        }
}
```

I can't find any way to have that `forEach` call working, even  `ids instanceof Array` isn't recognized as a type guard. This is very annoying..

**Comment by RyanCavanaugh** [comment]
@nexbit see #7294

**Comment by nexbit** [comment]
@RyanCavanaugh Ok, refactored as `(ids as any[]).forEach(id: string | number) => {})` works fine and gives type safety where it's needed..
But as a side question, is the `Array.isArray()` call supported as type guard by the compiler? Thx..

**Comment by RyanCavanaugh** [comment]
Yes
![image](https://cloud.githubusercontent.com/assets/6685088/19534170/9e834686-95f7-11e6-9ef5-fc0c0e1bc152.png)

**Comment by Arnavion** [comment]
You can get better type safety with `(ids as (string | number)[]).forEach(id => {})`. No need to drop down to `any`

**Comment by nexbit** [comment]
@Arnavion you're right indeed, thanks! tried everything, and missed this..

**Comment by scniro** [comment]
I hate TypeScript with every ounce of my being

**Comment by samuelmtimbo** [comment]
Sorry to bring this back.

```
import { Readable, Transform, Writable } from 'stream'

function unpipe(output: Readable | Transform, input: Writable): void {
  output.unpipe<Writable>(input)
}
```
error TS2349: Cannot invoke an expression whose type lacks a call signature. Type '(<T extends WritableStream>(destination?: T) => Readable) | (<T extends WritableStream>(destinati...' has no compatible call signatures.

I can't understand why I am getting this error, since both `Readable` and `Transform` have the `unpipe` method.
