### ISSUE TITLE
API createProgram won't find definition files

### ISSUE THREAD

**Issue by farfromrefug** [Microsoft/TypeScript#7961]
**TypeScript Version:** 
1.8.9

I have a src dir like this:
```
- test.ts
- test.d.ts
```
```test.ts``` references ```test.d.ts``` like this
```
/// <reference path="./test.d.ts" />
```

It works well under vscode and ```test.ts``` see my declares and such from ```test.d.ts```
Now i want to compile those files using the ```ts.createProgram``` API
So i call something like this:
```javascript
var program = ts.createProgram([path.join(srcDir, 'test.ts')],options, host);
var emitResult = program.emit();
```
i get  errors from ```test.ts``` mentioning it can't find the definitions from ```test.d.ts```
Though i don't get any error about not finding ```test.d.ts```

I also get the same result if i add ```test.d.ts``` in the list of compiled files provided to ```createProgram```

I have tried to use ```rootDir``` without success.

Am i missing something?

**Comment by mhegazy** [comment]
I am not getting the same behaviour. here is my test:

```ts
/// <reference path="typings/node/node.d.ts" />
import * as ts from "typescript";

function compile(fileNames: string[], options: ts.CompilerOptions): void {
    let program = ts.createProgram(fileNames, options);
    let emitResult = program.emit();

    let allDiagnostics = ts.getPreEmitDiagnostics(program).concat(emitResult.diagnostics);

    allDiagnostics.forEach(diagnostic => {
        let { line, character } = diagnostic.file.getLineAndCharacterOfPosition(diagnostic.start);
        let message = ts.flattenDiagnosticMessageText(diagnostic.messageText, '\n');
        console.log(`${diagnostic.file.fileName} (${line + 1},${character + 1}): ${message}`);
    });

    program.getSourceFiles().forEach(f => console.log(f.fileName));
    let exitCode = emitResult.emitSkipped ? 1 : 0;
    console.log(`Process exiting with code '${exitCode}'.`);
    process.exit(exitCode);
}

compile(process.argv.slice(2), {
    noEmitOnError: true, noImplicitAny: true, listFiles: true,
    target: ts.ScriptTarget.ES5, module: ts.ModuleKind.CommonJS
});
```

compile this sample with:

```cmd
tsc compiler.ts
```

and run it as:

```cmd
node compiler.js c:\test\file1.ts
```
with `file1.ts`:

```ts
/// <reference path="./file1.d.ts" />
```

I get:

```cmd
c:/sandbox/node_modules/typescript/lib/lib.d.ts
c:/test/file1.d.ts
c:/test/file1.ts
Process exiting with code '0'.
```

**Comment by farfromrefug** [comment]
Thanks @mhegazy for testing this. I realized the error was with "\ " in the reference path. For some reason vscode was seeing this while the compiler wasn't.
Maybe it would be good to report not found definition files during compilation?

Tahnks
