### ISSUE TITLE
Feature request: Export named default class

### ISSUE THREAD

**Issue by zwhitchcox** [Microsoft/TypeScript#7963]
Right now, you can either export a default class or export that named class. I would like to be able to export a default class. Example:

```ts
export default class MyClass() {  }
```

if i export this class, I can import it in another file:

```ts
import MyClass from './myclass.ts'
```

But I can't import it by name like this

```ts
import { MyClass } from './myclass.ts'
```

On the other hand, if I export the class with no `default` keyword:

```ts
export class MyClass() {  }
```

I can import it by name:

```ts
import { MyClass } from './myclass'
```

But I can't import it as a default

```ts
import MyClass from './myclass'
```

I would like the best of both worlds, where I could import the default class by default and also import it by name if I so choose. I have done this with ES'15, but for some reason, this isn't working with typescript.

**Comment by vladima** [comment]
will this work for you?
```ts
export class MyClass {  }
export default MyClass;
```

Per [ES6 spec](https://tc39.github.io/ecma262/#sec-exports-static-semantics-exportentries):
```
ExportDeclaration: export default ClassDeclaration
    Let names be BoundNames of ClassDeclaration.
    Let localName be the sole element of names.
    Return a new List containing the Record {[[ModuleRequest]]: null, [[ImportName]]: null, [[LocalName]]: localName, [[ExportName]]: "default"}.
```

where `[[ExportName]]` (in this case `default`) - name used to export this binding by this module.

**Comment by mhegazy** [comment]
As @vladima mentioned, this is the correct behavior as per ES6/ES2015 spec. 
Loaders like Systemjs do copy your exports to  `default` which makes `import MyClass from "./myclass"` even though the module does not have a `default` export. this is however is wrong, and a native ES6 module implementation would not support that. see ES6 spec: https://tc39.github.io/ecma262/#sec-exports-static-semantics-exportentries

See more documentation about modules and importing and exporting default at: http://www.typescriptlang.org/docs/handbook/modules.html#default-exports
