### ISSUE TITLE
Typings package.json tag is not working for es6 target?

### ISSUE THREAD

**Issue by Ciantic** [Microsoft/TypeScript#7984]
If I have a node_modules/something/package.json with typings defined, they won't work if the target is es6 but suddenly works if change to es5, is there a reason for this?

I made a test repo for to try: https://github.com/Ciantic/typescript-test-module-with-typings

If this is intended behavior it should be documented in here: http://www.typescriptlang.org/docs/handbook/typings-for-npm-packages.html that the typings tag can't be used if target is es6.

**Edit** Tried also with ntsc, same problem, with es5 it works, but not with es6.

**Comment by Ciantic** [comment]
Got an answer from @BigDataSamuli on gitter:

It works if one adds module: commonjs

e.g. tsconfig.json
```
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es6"
    }
}
```

But it doesn't work if you use:
```
{
    "compilerOptions": {
        "target": "es6"
    }
}
```

This information, and reasoning should be explained clearly in the http://www.typescriptlang.org/docs/handbook/typings-for-npm-packages.html not all of us are in touch with the ever changing module system.

**Comment by vladima** [comment]
try setting `moduleResolution` option to `node`

**Comment by Ciantic** [comment]
@vladima thanks, it works now perfectly with es6. This should be added to the docs above.

**Comment by mhegazy** [comment]
for future searches here is the documentation for module resolution: http://www.typescriptlang.org/docs/handbook/module-resolution.html
