### ISSUE TITLE
Infer Type of Array after Filter

### ISSUE THREAD

**Issue by 2426021684** [Microsoft/TypeScript#7985]
**TypeScript Version:** 

Lastest Commit

**Code**

```ts
const a = [5, 6, "7", "8"]
const b = a.filter(x => typeof x === "number")

```

**Expected behavior:**
b is `number[]`
**Actual behavior:** 
b is `(number|string)[]`

**Comment by DanielRosenwasser** [comment]
Looks like a duplicate of #7657.
