### ISSUE TITLE
[Transforms] ES2015 Module to AMD module: Unused dependency not added to define. 

### ISSUE THREAD

**Issue by anwalkers** [Microsoft/TypeScript#7986]
We have an Angular 1.x project that uses RequireJS for DI. We load angular modules wrapped in defines but don't use the dependency directly. We load the dependency with RequireJS then load the angular module. Is there a way to configure ES2016 modules to always get transformed, even if they are not used directly as a dependency?

<pre><code>define("main", ["dependency"], function(dependency) {
        // Angular application definition loading angular module defined in dependency...
        var app = angular.module("angularApp", ["angularModuleFromDependency"])
        app.run();
});</code></pre>

**TypeScript Version:** 

1.8.9

**Code**

main.ts

<pre><code>import module1 from './module1';
import module2 from './module2';

let v = module1;

export default v;</code></pre>

module1.ts

<pre><code>let x, y, module1;

x = 1;
y = 1;

module1 = x + y;

export default module1;</code></pre>

module2.ts

<pre><code>let x, y, module2;

x = 1;
y = 1;

module2 = x + y;

export default module2;</code></pre>

**Expected behavior:**

<pre><code>define(["require", "exports", "./module1", "./module2"], function (require, exports, module1_1, module2_1) {
    "use strict";
    var v = module1_1.default;
    Object.defineProperty(exports, "__esModule", { value: true });
    exports.default = v;
});</code></pre>

**Actual behavior:** 

<pre><code>define(["require", "exports", "./module1"], function (require, exports, module1_1) {
    "use strict";
    var v = module1_1.default;
    Object.defineProperty(exports, "__esModule", { value: true });
    exports.default = v;
});</code></pre>

**Comment by vladima** [comment]
you can use `<amd-dependency path="dependency"/>` to force adding some dependency.
```ts
/// <amd-dependency path="./module2"/>
import module1 from './module1';
import module2 from './module2';

let v = module1;

export default v;
```
produces
```js
define(["require", "exports", './module1', "./module2"], function (require, exports, module1_1) {
    "use strict";
    var v = module1_1["default"];
    exports.__esModule = true;
    exports["default"] = v;
});
```

Also we use `[Transforms]` prefix to distinguish items that were filed to track rewrite of the emitter so having it on this issue is a bit misleading.

**Comment by jeffreymorlan** [comment]
You can also use `import` without a name:
```ts
import './module2';
```
There are several advantages of this over \<amd-dependency\>:
* Syntax is checked (if you get the syntax of \<amd-dependency\> wrong, it silently does nothing)
* Existence of module is checked
* Can be anywhere in the source (if you put any non-comment code before \<amd-dependency\>, including `import`s, it silently does nothing)
* Works with all kinds of modules, not just AMD

**Comment by vladima** [comment]
+100 to @jeffreymorlan advise - this kind of ES6 import is exactly what you need. Was recently fixing something related to amd-dependency so it popped up in my head

**Comment by mhegazy** [comment]
Please see FAQ entry at: https://github.com/Microsoft/TypeScript/wiki/FAQ#why-are-imports-being-elided-in-my-emit
