### ISSUE TITLE
Duplicate identifier 'Node', how to let Typescript know my file is a module

### ISSUE THREAD

**Issue by carlosdubus** [Microsoft/TypeScript#7990]
I'm building a module and I want to name a class 'Node'. Looks like 'Node' already exists in the global scope. A module file has an isolated scope, so it will not replace the global 'Node' class. How can I tell typescript that a file is a module so it does not complain about duplicates?

models.ts:
`class Node {} `

If I add export to the Node class, the warning is gone.

tsc --version
`Version 1.8.9`

**Comment by carlosdubus** [comment]
I just realized Typescript needs a single export to know that a file is a module. My bad.

**Comment by jesseschalken** [comment]
(at least one export or import)
