### ISSUE TITLE
import only definition of a class

### ISSUE THREAD

**Issue by farfromrefug** [Microsoft/TypeScript#7995]
**TypeScript Version:** 
1.8.9

I should first mention that i using Typescript inside [Titanium Mobile Framework](https://github.com/appcelerator/titanium_mobile). Which means no browser environment.

It also means that sometimes ([compiled library modules](http://docs.appcelerator.com/titanium/3.0/#!/guide/CommonJS_Modules_in_Titanium)) to do ```require('test')``` i actually have to write ```require('mymodule/test')```

Now my issue is not about the actual require but about the "imported definition" that goes with it.
For example if i have this
``` typescript
//test.ts
class A {
   toString(){return "test";}
}
export = A
```

Now i want to use that class in another ts file. If i do this
``` typescript
import A = require('test');
```
it won't work because i actually have to write
``` typescript
import A = require('mymodule/test');
```
but then the compiler wont find ```A``` declaration because it wont find the ```test.ts``` file

Another use case is when we actually hide the ```require```. For example i have that class
``` typescript
class Loader {
   __creators = {}
   __constructors = {}
   registerCreator(name: string) {
      this.__creators[name] = (...args) => {
          if (!this.__constructors[name]) {
               this.__constructors[name] = require(name);
          }
          return this.__constructors[name].call(this, args);
      }
   }
   create(name:string, ...args) {
       return this.__creators[name](args);
   }
}
```
I am using that class to only ```require```(which means load the js file) when needed.
But because of that when i use ```Loader.create``` there is no way for me to cast the resulting object to ```A``` for example because i did not use ```import```

Right now i solve that by creating an interface in a declaration file and then make my class implement that interface. But that's a real pain because i have to duplicate all my classes definitions (which are already generated for example in ```test.d.ts```

So what i would need is a way to only import declaration. I am not sure of the form it could take.
Maybe something like 
``` typescript
import declaration A from 'test';
```
or 
``` typescript
/// <reference path="test.d.ts" />  // i actually can't do this right now because test.d.ts is generated by the compiler
```

Or may be there is already a way to do this?

Thanks a lot, love Typescript!

**Comment by vladima** [comment]
Re: customization of module name - will [path mappings](https://github.com/Microsoft/TypeScript/issues/5039) work for you?

**Comment by vladima** [comment]
Re second issue, compiler elides imports that are not used in value position so i.e for this case
```ts
// m1.ts
export class Cls {x}
```
```ts
// factory.ts
import {Cls} from "./m1";
export function factory() {
    return new Cls();
}
```
```ts
// main.ts
import {Cls} from "./m1";
import {factory} from "./factory";
let x = <Cls>factory();
```

result `main.js` will have import only for `./factory` since `Cls` is used only in type position.
```js
define(["require", "exports", "./factory"], function (require, exports, factory_1) {
    "use strict";
    var x = factory_1.factory();
});

```

**Comment by farfromrefug** [comment]
@vladima In a sense path mapping would solve the first case issue where my ```require``` path is actually not the path to the file.
But it would not solve the second case, where the require is done with a variable. So no way for the compiler to find the file.
For that second case we really need a way to only import the declaration.
``` typescript
import declaration A from 'test';

let a: A = myLoader.create('test);
```
this for example would only be used by the compiler to find ```A``` and would not even appear in the transformed javascript file.

**Comment by vladima** [comment]
It should currently work with the code below:
```ts
import {A} from 'test'; 
let a = <A>myLoader.create('test);
```

Lets assume that module denoted by module name `test` exports type `A`. Since A is not used in a value position - result `.js` file won't include import for `A` (as I've shown [here](https://github.com/Microsoft/TypeScript/issues/7995#issuecomment-208068664))

**Comment by farfromrefug** [comment]
@vladima you lost me there.
If i write 
```
import {A} from 'test';
```
it wont get transformed into this ?
```
const A_1 = require('./test');
```
Well actually i run some test and sometimes it does sometimes it doesnt... 
Can you explain a bit?
thanks

**Comment by mhegazy** [comment]
It will only generate the `require` statement if the import is used in a value position. so

```ts
import {A} from "./test";
var x: A; // used only as a type
```
emits:
```ts
    "use strict";
    var x;
```

where as, 

```ts
import {A} from "./test";
var x = new A(); // used as a value
```
emits:

```js
    "use strict";
    var test_1 = require('./test');
    var x = new test_1.A();
```

**Comment by mhegazy** [comment]
Please see the FAQ entry at https://github.com/Microsoft/TypeScript/wiki/FAQ#why-are-imports-being-elided-in-my-emit

**Comment by farfromrefug** [comment]
ok i think i understand when it does and when it does not.
And the when it does is the reason why i can't work in our environment.
if i do this
``` typescript
import {MicroEvent} from './MicroEvent'; 
export class AKApp extends MicroEvent {
}
```
then the ```import ...``` get transformed into 
``` javascript
const MicroEvent_1 = require('./MicroEvent');
...
```
Which won't work because this is actually not the path to ```MicroEvent``` when the app is built.
Plus i actually don't want the import because ```MicroEvent``` is support to already be defined in the global scope.
So what i want is really only to import the definition so that the typescript compiler knows about ```MicroEvent```

**Comment by mhegazy** [comment]
so how can you extend from `MicroEvent`, when it does not exist yet?

**Comment by farfromrefug** [comment]
It exist in the global scope.
For example it could be done through my loader
```typescript
this['MicroEvent'] = loader.create('MicroEvent');
```
that way we can do ```new MicroEvent()``` or extend it whenever needed without having to to do a require every time.
I know it s not a usual commonjs use. But we are in different environment (JavascriptCore or V8).  It does not even really have a commonjs context structure (even when using a commonjs structure, you still get the same global context)

But our environment is not really the case. The fact is that you might be using a class "knowing" it as already been required in that scope, and you only want the definition of it.

**Comment by mhegazy** [comment]
i understand. I am asking about extending. if you are not importing the value `MicroEvent`, what should output JS be for this :
```ts
class C extends MicroEvent {
}
```

**Comment by farfromrefug** [comment]
If i do it today, and it works (except that to get the definition i have to define an interface in a global .d.ts file) i get this after ts compilation
```javascript
class C extends MicroEvent {
}
```
and after babel for es 5
```javascript
var C = function (_MicroEvent) {
    _inherits(C, _MicroEvent);

    function C(context, _args) {
        _classCallCheck(this, C);
        var _this = _possibleConstructorReturn(this, Object.getPrototypeOf(C).call(this, {
        }));

    return C;
}(MicroEvent);
```

The same way it only supposes that ```MicroEvent``` already exists.

**Comment by mhegazy** [comment]
so `MicroEvent` is a global variable? or is it an export from another module? and if so, what is the point of a module system then, if everything is in the global namespace?

**Comment by farfromrefug** [comment]
Yes it is. But you are right this might not be the best example. I don't require ```MicroEvent``` in all my files mostly because it means accessing a file (or a compiled encrypted string) in our app environment. And reading a file (especially an asset on android) might cost a lot.

our JS environment is based on creating UI widgets. I like for the creator "creator" of those UI widget to be global because i use them everywhere, loading the file might be long, and because that way i can mimic for custom JS based UI widget the behavior of our native API. In The Titanium native API, wherever you are you can create a view using ```Ti.UI.createView```.  So i wrapped native API and custom JS API around the same type of constructor ```new View();``` or ```new CustomView();``` without always having to require ```CustomView.js```.
Plus as i mentionned it would be useless as we don't really have a modular global scope.

But anyway if we take this example:
``` typescript
class Loader {
   __creators = {}
   __constructors = {}
   registerCreator(name: string) {
      this.__creators[name] = (...args) => {
          if (!this.__constructors[name]) {
               this.__constructors[name] = require(name);
          }
          return this.__constructors[name].call(this, args);
      }
   }
   create(name:string, ...args) {
       return this.__creators[name](args);
   }
}
```
As the require is made using a variable. There is no way for the compiler to know or keep trace of the "required" classes.
However i might still want to do (i know what i am doing ;)) 
``` typescript
let a:A = myLoader.create('A');
```
Which in this case would mean importing the definition without having the actual require.
If you want to understand the why of this loader.
we(or i should say I) [use it for styling] (https://github.com/dawsontoth/Appcelerator-Titanium-Redux)

**Comment by mhegazy** [comment]
So for this example, why does the solution proposed by @vladima earlier does not work:

```ts
import {A} from "./another";

class Loader {
   __creators: Map<A> = {}; // only use it as a type here
   __constructors = {}
   registerCreator(name: string) {
      this.__creators[name] = (...args) => {
          if (!this.__constructors[name]) {
               this.__constructors[name] = require(name); // keep using require explicitly here.
          }
          return this.__constructors[name].call(this, args);
      }
   }
   create(name:string, ...args) {
       return this.__creators[name](args);
   }
}

```

**Comment by farfromrefug** [comment]
First they might not be all of class A. Plus the problem is not in this file. But more of when i use the Loader somewhere else. But i understand why it would work here.
If you look at the library (redux) i linked the idea is to be able to do this:
``` typescript
//toto.js
myLoader.registerCreator('CustomView')
```
And somewhere else
``` typescript
let a: CustomView = new CustomView();
```
You are right that i forgot to add a few lines in my creator example (i didn't want to make it too big and i didn't think it was necessary). Here is the full needed Loader class to understand the example.
```typescript
class Loader {
   __creators = {}; 
   __constructors = {}
   registerCreator(context, name: string) {
      this.__creators[name] = (...args) => {
          if (!this.__constructors[name]) {
               this.__constructors[name] = require(name); // keep using require explicitly here.
          }
          return this.__constructors[name].call(this, args);
      }
      context[name] = this.__creators[name];
   }
   create(name:string, ...args) {
       return this.__creators[name](args);
   }
}
```
That way somewhere in my global context i can do this
```typescript
myLoader.registerCreator(this, 'CustomView');
```

And later on in that same context (but it might be in another file )
```typescript
let a:CustomView = new CustomView(myArgs);
```
I already do this. My only problem is that when i define a i cant use ```import``` because it will add the require.

Sorry i should have put the full example before. I wanted to keep it short and thought it was enough.

**Comment by mhegazy** [comment]
that looks like an emit time transformation for me. there are some assumptions about your loader, and you want to leverage that in your class creation process.. does this sound about right?

**Comment by farfromrefug** [comment]
well bear with me as English is not my natural language and i actually come from the C++ world ;). I am not sure i understand the "emit" word.
But if i understand correctly yes i assume my loader class knows about "CustomView". So i expect that could do 
```typescript
let a:CustomView = new CustomView(myArgs);
```
without an import.
But then how to get vscode or the compiler not to complain about not knowing the class "CustomView"
Thus it makes sense to try and import only the definition at that moment.

**Comment by mhegazy** [comment]
by emit, i meant code generation. i.e. that you want to generate a class in a different way.

There is no easy way to convey this infromation to the compiler. the compiler sees a use of a value called   `CustomView`, and it will make sure it exists. 

the only way i can think of is a bit convoluted:

#### CustomViewImplementation.ts
```ts
declare class CustomView {
...
}
```

#### CustomView.ts
```ts
export const CustomViewImplementation = CutomView;
type CustomViewType = CustomView;
export {CustomViewType as CutomType} 
```

#### app.ts
```ts
/// <reference path="CustomView.d.ts" />
import {CustomView} from "./CustomView";
let a: CustomView/*impoted type for CustomView*/ = new CustomView /*the global variable CustomView*/("ss", 0);
```


We proposal can make this better using `declare global`:

#### CustomView.ts
```ts
class CustomViewImplementation {
    ....
}

type CustomViewType = CustomView;
export {CustomViewType as CutomType};

declare global {
    var CutomType: typeof CustomViewImplementation;
}
```

#### app.ts
```ts
import {CustomView} from "./CustomView";
let a: CustomView/*impoted type for CustomView*/ = new CustomView /*the global variable CustomView*/("ss", 0);
```

**Comment by farfromrefug** [comment]
No i don't really want the generated code to look different at all!
I just want the compiler to know about ```CustomView``` from where i do. Kind of like the forward declaration in Objective-C
```typescript
let a:CustomView = new CustomView(myArgs);
```
So i am ok with doing
```
import {CustomView} from "./CustomView";
```
But then yes this one will be transformed into a ```require``` in the generated js file.

That's why i was talking about something like 
```typescript
import definition {CustomView} from "./CustomView";
```
or
```typescript
def {CustomView} from "./CustomView";
```
which would still have the same purpose in the compiler, getting the definition of ```CustomView```
But we are sure it will NOT be present in the js file.

I am even ok with the ```/// <reference path="..." />``` way but it does not work

now about your implemention, it just seems really "heavy" for what we are just trying to do. Plus if you look at ```Loader``` it hads the constructor to a context/scope which might just not be the global one.

**Comment by mhegazy** [comment]
> I just want the compiler to know about CustomView from where i do. Kind of like the forward declaration in Objective-C

it is not a forward declaration, you want to say, i want the type from a module, and the for the value trust me, i am going to get that from somewhere else. 


> now about your implemention, it just seems really "heavy" for what we are just trying to do. Plus if you look at Loader it hads the constructor to a context/scope which might just not be the global one.

There is part that the loader knows and the compiler does not know. There seems to be two options, 1`  have an import to the name, but you tell the compiler to hold off on writing it because the loader does that (there is no way to do this currentlly), 2. or you want to import the type but still use the value. the later is what i have tried to do.

```ts
class CustomViewImplementation {
    ....
}

// Just the time to import
type CustomViewType = CustomView;
export {CustomViewType as CutomType};

// the value to use will come from the loader, this creates no value at runtime, it just tells the compiler there is a global to use.
declare global {
    var CutomType: typeof CustomViewImplementation;
}
```
