### ISSUE TITLE
how to set experimentalDecorators in tsconfig.json?

### ISSUE THREAD

**Issue by yinso** [Microsoft/TypeScript#7997]
**TypeScript Version:** 

typescript 1.8.9
OSX Yosemite
node 5.5.0
ts-node 0.7.1

**Code**

I have `experimentalDecorators` set in `tsconfig.json` as follows:

 ```json
// tsconfig.json
{
  "CompilerOptions": {
    "experimentalDecorators": true
  }
}
```
with the following sample code.

```ts 
// ast.js
import 'reflect-metadata';

function contract(target : any, key : string) {
  let types = Reflect.getMetadata("param.types", target, key)
  console.log('contract.types', types)
}

export abstract class AST {
  @contract // experimental decorator
  equal(other : AST) : boolean {
    return false;
  }
}
```

**Expected behavior:**

I expect that when I run `tsc ./ast.js`, the warning will be suppressed.

**Actual behavior:** 

It turns out `error TS1219` still shows up, though the code compiles.

The error can get suppresed if I call tsc as `tsc --experimentalDecorators ./ast.js`. However, I want to be able to import the code into `ts-node`, but the warnings cause the import to fail.

**Comment by DanielRosenwasser** [comment]
`tsc` doesn't pick up your `tsconfig.json` if it has any file arguments. Feel free to reopen if that doesn't fix the issue.
