### ISSUE TITLE
Overloading function signatures with mutiple optional arguments.

### ISSUE THREAD

**Issue by sebald** [Microsoft/TypeScript#8000]
I am trying to define a function overload with mulitple optinal arguments, but can not seems to get the syntax right (see below example). Currently I am using the following signature:

```ts
function test (a:()=>void, b?:(Object|boolean), c?:boolean)
```

But this is misleading, because `test(noop, true, true)` is *not*  a valid call signature.
Is there a way to achieve this in TS? I am having a tough time to get this to work and couldn't find a solution on SO/Google.

**TypeScript Version:** 

1.8.9

**Code**

```ts
function test (a:()=>void, b?:boolean);
function test (a:()=>void, b?:Object);
function test (a:()=>void, b:Object, c?:boolean) {   
  /.../
}

const noop = () => {};

test( noop );
test( noop, {} );
test( noop, false );
test( noop, {}, false ); // Supplied parameters do not match any signature of call target.
```

**Expected behavior:**

All function calls are valid. 

**Actual behavior:** 

Function with 3 arguments is not callable.

**Comment by Arnavion** [comment]
The function declaration that contains the body is not part of the overloads. If you put your example in the playground and hover over one of the calls to `test` you'll see the popup tell you there are only two overloads of `test`, not three.

See [the handbook,](https://www.typescriptlang.org/docs/handbook/functions.html#overloads) especially the last line.

The correct code would be something like this:

```typescript
function test (a:()=>void, b?:boolean);
function test (a:()=>void, b?:Object);
function test (a:()=>void, b:Object, c?:boolean);
function test (a:()=>void, b?:boolean|Object, c?:boolean) {
  //...
}
```

**Comment by sebald** [comment]
Thanks for the clarification.

**Comment by RyanCavanaugh** [comment]
FWIW this is also in the FAQ: https://github.com/Microsoft/TypeScript/wiki/FAQ#why-am-i-getting-supplied-parameters-do-not-match-any-signature-error

**Comment by sebald** [comment]
Thx, will make sure to check the FAQ next time :)
