### ISSUE TITLE
Incorrect Type inference when re-assignment variable

### ISSUE THREAD

**Issue by syuilo** [Microsoft/TypeScript#8001]
**TypeScript Version:** 
latest

---

**Codes:**
**Function definition:**
```ts
// It returns what was to add the 'kyoppie' property
function addKyoppie<T>(x: T): T & { kyoppie: string } {
	return Object.assign({}, x, {
		kyoppie: 'cute'
	});
}
```

**OK case:**
```ts

const x = addKyoppie({
	yuppie: 'cool'
});

console.log(x.kyoppie);
//            ^^^^^^^ OK
```

**Error case:**
```ts
let x = {
	yuppie: 'cool'
};

x = addKyoppie(x);

console.log(x.kyoppie);
//            ^^^^^^^ Error!

```

---

**Expected behavior:**
Type of `x` is changed to `{ yuppie: string; kyoppie: string; }`

**Actual behavior:** 
`x` of the type remains of `{ yuppie: string }`

Got:
```
Property 'kyoppie' does not exist on type '{ yuppie: string; }'.
```

---

Sorry my bad English. Thanks.

**Screen shot**
![image](https://cloud.githubusercontent.com/assets/4439005/14419777/0d8e7ebe-0003-11e6-84f0-dccbbda98e00.png)

**Comment by RyanCavanaugh** [comment]
Assuming this was resolved -- please re-open otherwise. Thanks!

**Comment by syuilo** [comment]
I thought I was mistaken.

**Comment by syuilo** [comment]
Because only the interface has been extended, this may be normal behavior.

**Comment by ahejlsberg** [comment]
This is by design. In the `let` statement we infer the type of `x` to be `{ yuppie: string }`. Subsequent assignments to `x` don't modify the type of `x` (if they did, we wouldn't catch type mismatch errors).
