### ISSUE TITLE
Compile error if the project imports d.ts which contains a public class that has a privare member uses destructuring assignment in arguments.

### ISSUE THREAD

**Issue by saneyuki** [Microsoft/TypeScript#8002]
## Sceneario

- Project A
  - This uses `typeScript@1.9.0-dev.20160409` with `--noImplicitAny`.
  - This import the below project B via npm.
- Project B
  - This uses `typeScript@1.9.0-dev.20160409` or before with `--noImplicitAny`.
  - This is published as a npm packages `project-b`  with compiled code (`*.js` & `*.d.ts`).

### Project A

```typescript
import {Bar} from 'project-b';

const b = new Bar();
```

### Project B

```typescript
// index.ts

type Arg = {
    a: number;
};
export class Bar {
    private bar({ a, }: Arg): number {
        return a;
    }
}
```

is compiled:

```typescript
// index.d.ts
export declare class Bar {
    private bar({a});
}
```

```javascript
export class Bar {
    bar({ a, }) {
        return a;
    }
}
```

## What happens (Actual Results)

Project A will be a compile error. The error log is here:

```sh
2     private bar({a});
                   ~

project-b/index.d.ts(2,18): error TS7031: Binding element 'a' implicitly has an 'any' type.
```

## Expected behavior

- TypeScript should emit a type signature of private members arguments of a exported object which uses destructuring assignment.
  - I think this is most clear way.
  - But this might have a compatibility risk with libraries compiled wirh ~TypeScript 1.8.
- ...or ignore a type signature of private members...
  - As my personal opinion, I dont like it.

**Comment by saneyuki** [comment]
Relate?: https://github.com/Microsoft/TypeScript/pull/7969

**Comment by mhegazy** [comment]
@sheetalkamat, binding patterns in a private in an ambient context should be exempt of the no-implicit-any check

**Comment by mhegazy** [comment]
@saneyuki please give `typescript@next` a try later tonight and let us know if the issue still persists.

**Comment by saneyuki** [comment]
@mhegazy 

I tried with `typescript@1.9.0-dev.20160412` and `--noImplicitAny` flag, but this problem is still reproducible. Should I wait the `typescript@1.9.0-dev.20160413` or later?

**Comment by saneyuki** [comment]
I confirm these:

- `typescript@1.9.0-dev.20160413` && `--noImplicitAny` is still not fixed.
- But the latest master (which is built with cloning this and `jake LKG`) has been fixed.

Thank you!

**Comment by JKillian** [comment]
In the meantime before TS 2.0, is avoiding destructuring in private method parameters the best way to avoid this issue?

**Comment by mhegazy** [comment]
seems like the only way.
