### ISSUE TITLE
NodeList interface lost iterator on master branch

### ISSUE THREAD

**Issue by SaschaNaz** [Microsoft/TypeScript#8008]
The built lib.es6.d.ts on the master branch (as of April 12) does not contain iterator symbol while Set, Array, Map, etc have it. This is a regression as NodeList on 1.8.x contains it.

**Comment by mhegazy** [comment]
@yuit  looks like your recent changes broke the dom.es6.d.ts integration. can you take a look.

**Comment by yuit** [comment]
Thanks @SaschaNaz I get the PR up
