### ISSUE TITLE
typings ERR! message Unable to read typings for "jasmine"

### ISSUE THREAD

**Issue by agkavish** [Microsoft/TypeScript#8009]
I am trying to work on 5 Minute quick start tutorial for Angular 2. (https://angular.io/docs/ts/latest/quickstart.html). While executing npm install I am getting following errors with typings. I was getting similar errors for es6-shim, but got that resolved after setting http and https_proxy variables. 

Any pointer to resolve this issue?

typings ERR! message Unable to read typings for "jasmine". You should check the entry paths in "jasmine.d.ts" are up to date
typings ERR! caused by Unable to connect to "https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/7de6c3dd94feaeb21f20054b9f30d5dabc5efabd/jasmine/jasmine.d.ts"
typings ERR! caused by self signed certificate in certificate chain

typings ERR! cwd C:\Learning\Angular\a2\angular2-quickstart
typings ERR! system Windows_NT 6.1.7601
typings ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Learning\\Angular\\a2\\angular2-quickstart\\node_modules\\typings\\dist\\bin.js" "install"
typings ERR! node -v v4.4.0
typings ERR! typings -v 0.7.12

typings ERR! If you need help, you may report this error at:
typings ERR!   <https://github.com/typings/typings/issues>

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.4.0
npm ERR! npm  v2.14.20
npm ERR! code ELIFECYCLE
npm ERR! angular2-quickstart@1.0.0 postinstall: `typings install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular2-quickstart@1.0.0 postinstall script 'typings install'.
npm ERR! This is most likely a problem with the angular2-quickstart package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     typings install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-quickstart
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls angular2-quickstart
npm ERR! There is likely additional logging output above.

**TypeScript Version:** 

1.7.5 / 1.8.0-beta / nightly (1.9.0-dev.20160217)

**Code**

```ts
// A self-contained demonstration of the problem follows...

```

**Expected behavior:**

**Actual behavior:**

**Comment by mhegazy** [comment]
> typings ERR! If you need help, you may report this error at:
> typings ERR! https://github.com/typings/typings/issues

looks like an issue to be filed on https://github.com/typings/typings/issues
