### ISSUE TITLE
VS2015 strange sourcemaps after webpack

### ISSUE THREAD

**Issue by nippur72** [Microsoft/TypeScript#8011]
I have a strange behavior in VS2015 with source maps and webpack: 

If I bundle with webpack, the breakpoints are picked correctly, but they are highlighted oddly, as if there is a +1 offset or similar. Furthermore, I can no longer hover the mouse over the variable and get the inspection tooltip.

Compare the two images below, the first is webpacked, the second is a plain TypeScript HTML app project created in Visual Studio. See how the red and yellow areas are shifted +1 to the right. But what bother most is the missing tooltip.

![webpack](https://cloud.githubusercontent.com/assets/2598443/14435353/d70d6890-0017-11e6-9dbc-7c72a775e644.png)
webpack

![nowebpack](https://cloud.githubusercontent.com/assets/2598443/14435360/dabec7a4-0017-11e6-9c81-6d35076def4d.png)
no webpack

I guess this is a VS problem because the source maps looks correct when inspected with something like [source-map-visualization](http://sokra.github.io/source-map-visualization/).

Any idea what is going wrong?

**Comment by sheetalkamat** [comment]
@nippur72 , I have observed similar behavior yesterday, and I am looking into it. Will keep you updated.

**Comment by nippur72** [comment]
for completeness, I should add that I don't use any typescript specific loaders in webpack, I just bundle the `.js` files (and their source maps) compiled via VS2015.

Snippet of my `webpack.config.js`
```js
module.exports = {
    module: {
        preLoaders: [ {
                test: /\.js$/,
                loader: "source-map-loader"
            }
        ]
    },
    devtool: "source-map",
    output: {
        libraryTarget: "this",
        path: "./bundle",
        filename: "app.js",
        sourceMapFilename: "[name].js.map",
        devtoolModuleFilenameTemplate: "[resource-path]"
    }
}
```

**Comment by nippur72** [comment]
An additional remark about this issue: when debugging in Chrome I've noticed there's a "red dot" at position 0 in the sourcemap file. When hovering the mouse over such red dot the tooltip reveals it to be an `\ufeff` character, suggesting something is wrong with UTF encoding. 

I suspect this might be related to the +1 offset, but have no clue why this is happening.

See the attached image:

![image](https://cloud.githubusercontent.com/assets/2598443/15327136/b473e660-1c50-11e6-9d09-0c808bb66280.png)

**Comment by nippur72** [comment]
Update: the UTF BOM character is not the problem, I converted my source files to UTF8 without marker and the issue it's still there.

Anyway I switched to using `ts-loader` in webpack (before I just loaded the compiled .js along with their .map files) and the problem seems to be (mostly) fixed as it does occur only in just few files.

What hasn't gone is the mouse tooltip when hovering over variable names.

**Comment by sheetalkamat** [comment]
I have investigated this and understood the issue and looking into possible ways to fix this. Will keep you updated.

**Comment by sheetalkamat** [comment]
I have just made changes in debugger to fix this issue. Next release that ships this fix should work for your solution correctly. please re-open if you still run into issues.

**Comment by nippur72** [comment]
@sheetalkamat I've found another similar issue which I think might be related to this one, see #9770.
