### ISSUE TITLE
enum with bigger integer than available is allowed

### ISSUE THREAD

**Issue by donaldpipowitch** [Microsoft/TypeScript#8020]
**Code**

```ts
export enum ModelType {
  Repositories,
  Gists
};

function test(modelType: ModelType) {
	
}

test(2);
```

[Example](https://www.typescriptlang.org/play/#src=export%20enum%20ModelType%20%7B%0D%0A%20%20Repositories%2C%0D%0A%20%20Gists%0D%0A%7D%3B%0D%0A%0D%0Afunction%20test(modelType%3A%20ModelType)%20%7B%0D%0A%09%0D%0A%7D%0D%0A%0D%0Atest(2)%3B)
**Expected behavior:**

Throw error, because `2` shouldn't be available in `ModelType`.

**Actual behavior:** 

No error is thrown.

**Comment by RyanCavanaugh** [comment]
We don't distinguish between flag and non-flag enums, so a number that is above any given enum member isn't necessarily invalid. For example
```ts
enum Flags {
  Neat = 1,
  Cool = 2,
  Great = 4
}
// like saying Neat | Cool | Great
var x: Flags = 7;
```

**Comment by donaldpipowitch** [comment]
Can I opt-out from that? This is unexpected for me and for my use cases not useful.

**Comment by RyanCavanaugh** [comment]
There's no opt-out setting. Can you show an example of what you mean about using strings?

**Comment by donaldpipowitch** [comment]
Say the function `test` only accepts `'foo'` or `'bar'` as possible types. I could do it that way:

````
type Value = 'foo' | 'bar';

function test(value: Value) {
	
}

test('foo');
````

However I need to pass `'foo'`` directly which can be troublesome for refactoring. I'd rather pass something like `Value.foo` as a reference to `'foo'` (which also reads nicer in my opinion). Is this possible somehow? The best thing I can come up with is this beast:

````
type Value = 'foo' | 'bar';

type IValueMap = {
  foo: 'foo',
  bar: 'bar'
};

const ValueMap: IValueMap = {
  foo: 'foo',
  bar: 'bar'
};

function test(value: Value) {
	
}

test(ValueMap.foo);
````

**Comment by Elephant-Vessel** [comment]
I also think that the flag-behavior of enums would have been nice to have separated into another keyword like `flag` since that behavior is really different from the common usage of enums as a a simple set of named constant values.

However I'm unsure and curious about what you want to achieve here, why don't you just reference the enum value on the ModelType directly like `test(ModelType.Gists)` instead of sending in wild integers?

**Comment by donaldpipowitch** [comment]
> However I'm unsure and curious about what you want to achieve here, why don't you just reference the enum value on the ModelType directly like test(ModelType.Gists) instead of sending in wild integers if you want more safety and improving refactoring?

Oh, I don't want the send integers directly. I _do_ use the reference like `ModelType.Gists`. I found that by accident and thought it was a bug.

**Comment by Elephant-Vessel** [comment]
@donaldpipowitch So that stuff about strings, how would that improve the language?

**Comment by donaldpipowitch** [comment]
You could reference the string instead of passing it directly. Or what do you mean?

**Comment by Elephant-Vessel** [comment]
I mean, this is still about how to work with enums right? Or have this issue changed to be about the general possibility to reference values in string literal types like we do with enums?

**Comment by donaldpipowitch** [comment]
> I mean, this is still about how to work with enums right?

Yeah. I'd definitely like to see a enum alternative to not allow things like that:

````
export enum ModelType {
  Repositories,
  Gists
};

function test(modelType: ModelType) {

}

test(2);
````

> Or have this issue changed to be about the general possibility to reference values in string literal types like we do with enums?

That would probably a second issue. _However_ this could both be solved with the same feature, if I could define an `enum` with limited custom values (which could be just `0` and `1` or `'gists'` and `'repos'`).

**Comment by mhegazy** [comment]
The issue referenced in OP is by design as noted in https://github.com/Microsoft/TypeScript/issues/8020#issuecomment-208717449

The rest of the discussion is about non-number based enums, and this is already tracked by https://github.com/Microsoft/TypeScript/issues/1206.

**Comment by andremarcondesteixeira** [comment]
maybe:

`   
export class MyClass {
    public teste(bla : foo) : void {
        console.log(bla);
    }

    public teste2() : void {
        this.teste(weekDay.Sábado);
    }
}

enum weekDay {
    Domingo,
    Segunda,
    Terça,
    Quarta,
    Quinta,
    Sexta,
    Sábado
}

export type foo = weekDay.Sábado | weekDay.Domingo;`
