### ISSUE TITLE
whole file "use strict" not working anymore

### ISSUE THREAD

**Issue by Ziriax** [microsoft/TypeScript#8021]
Our code that works fine with TS 1.7

`_references.ts` contains:

```
/// <reference path="useStrict.ts"/>
/// <reference path="file1.ts"/>
/// <reference path="file2.ts"/>
...
```

The `useStrict.ts` file just contains `"use strict"`

The other files just use namespaces, no modules.

All these typescript files are compiled into a single large javascript file, we're not using a module system.

Typescript 1.8.5 breaks the generated JS:

**Expected JS**

```
"use strict";
var __extends = (this && this.__extends) || function (d, b) {
    for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];
    function __() { this.constructor = d; }
    d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
};
//... code from file1
//... code from file2
```

**Actual JS**

```
var __extends = (this && this.__extends) || function (d, b) {
    for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];
    function __() { this.constructor = d; }
    d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
};
"use strict";
//... code from file1
//... code from file2
```

Since now `"use strict"` is not the very first statement anymore, it is completely ignored by the JS runtime.

**Comment by mhegazy** [comment]
This is not a supported scenario. the fact that it worked as described was caused by a bug in the implementation of emitting `__extends` helpers. your files are not parsed in strict mode because the first file in the list had a "use strict".

having said that, we should figure out a way to make this scenario work.

**Comment by Ziriax** [comment]
Interestingly, pasting the following code in the Typescript playground does result in the ```"use strict"``` to be moved above the ```__extends``` declaration...

```
"use strict";

namespace Foo {
	export class Animal {
		
	}
}

namespace Foo {
	export class Horse extends Animal {
	
	}
}
```

Compiling this code placed in a single file with ```tsc.exe``` also results in the correct output code.

However, when the ```--out``` compiler option is passed, incorrect code is generated.

**Comment by Ziriax** [comment]
It seems that passing ```-module none``` does work correctly for the example above  (TSC v1.8.1)

In the compiler's ```emitter.ts``` source code, indeed the following code is present:

```
                // Emit helpers from all the files
                if (isBundledEmit && modulekind) {
                    forEach(sourceFiles, emitEmitHelpers);
                }
```

However it does not work in our large code base, compiled from visual studio. Investigating this further

**Comment by Ziriax** [comment]
Turns out this is a bug in the ```Microsoft.TypeScript.targets```, it contains the following line:

```
    <TypeScriptBuildConfigurations Condition="'$(TypeScriptModuleKind)' != '' and '$(TypeScriptModuleKind)' != 'none'">$(TypeScriptBuildConfigurations) --module $(TypeScriptModuleKind)</TypeScriptBuildConfigurations>
```

but the default module-kind of TSC is ``ModuleKind.CommonJS```.

So 'none' was never passed to TSC at all!

Just removing the check for none fixes the problem:

```
    <TypeScriptBuildConfigurations Condition="'$(TypeScriptModuleKind)' != ''">$(TypeScriptBuildConfigurations) --module $(TypeScriptModuleKind)</TypeScriptBuildConfigurations>
```

**Comment by RyanCavanaugh** [comment]
@Ziriax thanks for tracking that down! Logged #8062

**Comment by RyanCavanaugh** [comment]
Declining due to lack of demand.
