### ISSUE TITLE
"Writing Definition (.d.ts) Files" link in the Wiki is broken (404)

### ISSUE THREAD

**Issue by simonsarris** [Microsoft/TypeScript#8029]
[The wiki](https://github.com/Microsoft/TypeScript/wiki) has a link for:

> [Writing Definition (.d.ts) Files](https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Writing%20Definition%20Files.md)

That link 404s. I don't see a similar page in the Wiki's list of pages.

**Comment by sandersn** [comment]
It's now [Writing Declaration Files](https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Writing%20Declaration%20Files.md). I'll update the wiki link.
