### ISSUE TITLE
Type intersections between `{}` and types with only optional members are not type-checked.

### ISSUE THREAD

**Issue by JabX** [Microsoft/TypeScript#8050]
**TypeScript Version:** 
* typescript@next (1.9.0-20160412)
* 1.8.9
* and probably all the way down to the initial type intersection release.

**Code**

```ts
let test: {} & {foo?} & {bar?};
test = 'hello'; // Valid.
```

**Expected behavior:**
Well I'd like to have an error for that! 

I get autocompletion for `foo` and `bar` while typing `test = {}`, but it's not enforced.

My use case is when I use a type in functions or classes like `T & {foo?}` with `T = {}`.

**Comment by Arnavion** [comment]
Same as #7485 ?

**Comment by basarat** [comment]
Nothing special about `intersection` here. Any type with `all optional members` is considered compatible: 

```ts
let test: {foo?:any;bar?:any;};
test = 'hello'; // Valid.
```

**Comment by DanielRosenwasser** [comment]
I think @Arnavion is correct (thanks a ton for digging that up!). Closing as a duplicate.
