### ISSUE TITLE
Any idea on "type mapping"?

### ISSUE THREAD

**Issue by techird** [Microsoft/TypeScript#8054]
I got confused when using redux-form. I have to define two interface for the fields.

```ts
interface FormFields {
    fieldA: FieldProp;
    fieldB: FieldProp;
    ...
    fieldX: FieldProp;
}

interface FormValues {
    fieldA: string;
    fieldB: string;
    ...
    fieldX: string;
}
```

I thought these work is too verbose and I wonder if there is a way to do the type mapping automaticly.

For example,

```ts
interface FormValues {
    [key: keyof FormFields]: string;
}
```

I am not sure if this is possible.

PS. I am not a native english user and I have no idea how to express this issue to search for duplication. If there is duplicated please tell. Thanks a lot.

**Comment by SaschaNaz** [comment]
#394 and #1295 discusses about this with a new 'memberof' keyword.

**Comment by techird** [comment]
@SaschaNaz Thanks a lot, I will track them and close this.
