### ISSUE TITLE
Iterating array with for .. in, why is iterator forced as string?

### ISSUE THREAD

**Issue by griii2** [Microsoft/TypeScript#8059]
**TypeScript Version:** 

1.8.10-beta

**Code**
https://www.typescriptlang.org/play/#src=var%20myArr%20%3A%20string%5B%5D%20%3D%20%5B%22a%22%2C%20%22b%22%5D%3B%0D%0Avar%20myNumber%20%3A%20number%3B%0D%0A%0D%0Afor%20(var%20i%20in%20myArr)%20%7B%0D%0A%09console.log(myArr%5Bi%5D)%3B%0D%0A%09myNumber%20%3D%20i%3B%0D%0A%7D

**Expected behavior:**

I am clearly iterating an array, not an object, iterator should be number or at least any;

**Actual behavior:** 

Iterator is string.

**Comment by griii2** [comment]
Ok, for in is not for arrays, I get it

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...in

**Comment by RyanCavanaugh** [comment]
You can use `for .. in` with arrays, but the key is always a string even though the key values appear to be numberlike
