### ISSUE TITLE
Incorrect assumed default in .targets file

### ISSUE THREAD

**Issue by RyanCavanaugh** [Microsoft/TypeScript#8062]
Courtesy @Ziriax in #8021:

-------
Turns out this is a bug in the ```Microsoft.TypeScript.targets```, it contains the following line:

```
    <TypeScriptBuildConfigurations Condition="'$(TypeScriptModuleKind)' != '' and '$(TypeScriptModuleKind)' != 'none'">$(TypeScriptBuildConfigurations) --module $(TypeScriptModuleKind)</TypeScriptBuildConfigurations>
```

but the default module-kind of TSC is ``ModuleKind.CommonJS```.

So 'none' was never passed to TSC at all!

Just removing the check for none fixes the problem:

```
    <TypeScriptBuildConfigurations Condition="'$(TypeScriptModuleKind)' != ''">$(TypeScriptBuildConfigurations) --module $(TypeScriptModuleKind)</TypeScriptBuildConfigurations>
```

**Comment by paulvanbrenk** [comment]
I have a fix, which should be in tonights NuGet package.

**Comment by Ziriax** [comment]
Thanks, that was really fast!

**Comment by paulvanbrenk** [comment]
It didn't make tonights drop.
