### ISSUE TITLE
reference search run from a method of a class doesn't find a corresponding method of an interface

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#8066]
```typescript

interface I { boom(): void; }
class C implements I {
   boom/* <-- search for all references here */(){} // expected to find I.boom, actual nothing
}

**Comment by mhegazy** [comment]
mmm, seems to work fine for me on latest:

![image](https://cloud.githubusercontent.com/assets/8000722/14509806/171de9ac-0183-11e6-9364-50395207073d.png)

**Comment by aleksey-bykov** [comment]
mmm... maybe importing an interface from the external module is the problem?


![image](https://cloud.githubusercontent.com/assets/937933/14512510/ab49f114-01ad-11e6-9621-e2cb3522a74c.png)

**Comment by aleksey-bykov** [comment]
![image](https://cloud.githubusercontent.com/assets/937933/14527207/4da8e894-0216-11e6-9bff-79b12cef39b1.png)

**Comment by mhegazy** [comment]
actually it is the class expression, not the module..


```ts
interface I { boom(): void; }
new class C implements I {
   boom/* <-- search for all references here */(){} // expected to find I.boom, actual nothing
}
```
