### ISSUE TITLE
[Transforms] Comments on export declarations not emitted

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript#8076]
**Expected**:

```js
// named export
var variable_2 = require("variable");
```

**Actual**:

```js
var variable_2 = require("variable");
```

Failed tests:
*  es6ExportEqualsInterop.ts

**Comment by sandersn** [comment]
This happens because a named export that is associated with the comment is not emitted. It would be `var variable_1 = require("interface")`, but interfaces have no value side, so the export is omitted.

**Comment by sandersn** [comment]
@rbuckton said he is looking at comment emit right now, so I'll transfer this bug to him.

**Comment by rbuckton** [comment]
In the old emitter we would first emit the comment before emitting (and eliding) the export declaration. In the new emitter we elide the declaration before we ever get to this point.

I think the new baseline is acceptable.
