### ISSUE TITLE
typeof === "object" is insufficient

### ISSUE THREAD

**Issue by sgbeal** [Microsoft/TypeScript#8081]
**TypeScript Version:** 

If the version number were in the sources, i could answer this. bower says it's 1.8.x

**Code**

```ts
// this is compiled JS code from some random bit of ts...
    var __metadata = (this && this.__metadata) || function (k, v) {
        if (typeof Reflect === "object" && typeof Reflect.metadata === "function") return Reflect.metadata(k, v);
    };
```

**Expected behavior:**

typeof ... === "object" is insufficient for such checks because of this JS quirk:

(typeof null === "object")

**Actual behavior:** 

Such uses should include a null/falsy check:

if(Reflect && typeof Reflect==="object" && ...)

Update: as Daniel points out, the typeof check needs to come first:

if(typeof Reflect==="object" && Reflect && ...)

because typeof special-cases the handling of undefined symbols (as opposed to those when the undefined value).

**Comment by DanielRosenwasser** [comment]
> If the version number were in the sources 

[But it is!](https://github.com/Microsoft/TypeScript/blob/794c57478ec2a44ee15fb3e245a4c5d2d1612375/src/compiler/program.ts#L16). You can also write `tsc --version`.

If this is going to be changed, it should be `typeof Reflect === "object" && Reflect && ...` since you need to avoid the initial reference error.

@rbuckton might have some thoughts.

**Comment by sgbeal** [comment]
My installation has no program.ts. It's installed by whichever component manages packages.js, which is configured for:

    "typescript": "^1.8.9",

**Comment by Arnavion** [comment]
program.ts is compiled into tsc.js. Search for `ts.version = ` and in 1.8.9 you should find it at line 32531: `ts.version = "1.8.9";`

**Comment by sgbeal** [comment]
LOL - okay, that explains it. i stopped looking for one around line 5k, assuming that such information would have been "somewhere near the top." i won't have access to my copy until tomorrow but will try to remember to grep it for ts.version and post that here.

**Comment by mhegazy** [comment]
Going back to the original issue. so if i am getting it right, you have set `Reflect` to `null` deliberately? can you not do that? 

the check here is meant to check for a polyfill for `Reflect`, which is an [ES6 native Object](http://www.ecma-international.org/ecma-262/6.0/#sec-reflect), so either it sis there or undefined. `null` is a very interesting situation.

also please note that `--noEmitHelpers` will suppress the emitted helpers and you can implement them differently.

**Comment by sgbeal** [comment]
@mhegazy the problem is a general one - that was only one instance of it i randomly say. It's the _pattern_ i'm reporting a problem with, not the specific case (i should have been explicit about that). i did not trigger this error, i just noticed that the JS code has a corner case.

version 1.8.10, btw.

    [stephan@host:~/consol/proj/nms/nms-web/nms-gui]$ grep -n ts.version ./node_modules/typescript/lib/tsc.js
    32545:    ts.version = "1.8.10";

**Comment by mhegazy** [comment]
thanks @sgbeal for the explanation. I believe checking for `undefined` should be sufficient as we are locating a polyfill/native implementation. setting a standard js object to `null` is not a common practice, and not sure there is much value in guarding against these cases.

**Comment by sgbeal** [comment]
FWIW, it seems to me that this would take less time to fix once (now), when the problem and solution are both obvious, rather than try to figure out why it breaks later in some obscure use case. The currently generated code has an obvious corner case. My _guess_ is that this pattern is more prevalent than this one case, but i haven't examined the any generated code other than the 10 lines or so i just accidentally laid eyes on when i came across this. If i spotted this in a couple seconds in a random code sample, it's likely a wider-spread problem ("problem" in that it demonstrates a lack of understanding of potential corner cases involved with (typeof Blah)). If it were me i'd fix it, but i'm just pedantic that way.
