### ISSUE TITLE
[Suggestion] Provide a way to opt-out strict object literal check for a specific property

### ISSUE THREAD

**Issue by duanyao** [Microsoft/TypeScript#8085]
**TypeScript Version:** 

1.8.10

## Problem

Sometimes we want to opt-out strict object literal check for a specific property. Some types have large amount or even unlimited number of properties, and we only want to model the most frequently used ones. However when we do use an unmodeled property in an object literal, the compiler  complains. E.g.:

```ts
interface AttrBag {
  id?: string;
  style?: string;
  title?: string;
  'class'?: string;
}

function setAttrs(el: Element, attrs: AttrBag) {
  //...
}

setAttrs(document.createElement('a'), {
  title: 'foo', 
  href: 'bar', // error
  'data-x': 'y', //error
});
```

## Existing solutions
Existing solutions have some limitations:

* Add a type assertion for the object literal. This turns off object literal check entirely, which is undesirable, e.g.:

```ts
setAttrs(document.createElement('a'), {
  titile: 'foo', // typo, but no error
  href: 'bar',
  'data-x': 'y',
} as AttrBag);
```

* Augument the interface for all used properties. This is heavy weight for infrequently used properties; and more importantly, the effect is usually global and can't be undone in a specific source file.

## Proposed solution: "additional property" modifier
If a property name in a object literal is modified with `+` ("additional property" modifier), and it doesn't exist in the target type, compiler should skip strict object literal check for this property, and treat this property as optional. E.g.:

```ts
setAttrs(document.createElement('a'), {
  title: 'foo', 
  +href: 'bar', // OK
  +'data-x': 'y', // OK
});

// The type of attrs is { title: string, href?: string, 'data-x'?: string }
var attrs = {
  title: 'foo', 
  +href: 'bar',
  +'data-x': 'y',
};

attrs = {  // OK
  title: 'bar',
};
```

**Comment by DanielRosenwasser** [comment]
Why not add an index signature to the original type?

Details:

* http://www.typescriptlang.org/docs/release-notes/typescript-1.6.html#stricter-object-literal-assignment-checks
* https://github.com/Microsoft/TypeScript-Handbook/pull/211

**Comment by duanyao** [comment]
Because index signature effectively turns off strict object literal check, much like type assertion:
```ts
interface AttrBag {
  id?: string;
  style?: string;
  title?: string;
  'class'?: string;
  [index: string]: any;
};
function setAttrs(el: Element, attrs: AttrBag) {
  //...
}
setAttrs(document.createElement('a'), {
  titile: 'foo', // typo, but no error
});
```

**Comment by RyanCavanaugh** [comment]
How do you feel about this?
```ts
function setAttrs<T extends AttrBag>(el: Element, attrs: T) {
  //...
}

setAttrs<AttrBag & { href; 'data-x'; }>(document.createElement('a'), {
  title: 'foo', 
  href: 'bar',
  'data-x': 'y',
});
```

**Comment by duanyao** [comment]
Yeah, it's a clever solution for passing arguments (the `<AttrBag & { href; 'data-x'; }>` part can be omitted actually). But for variable assignment, it is a bit verbose:
```ts
var attrs: AttrBag & { href?; 'data-x'?; } = {
  title: 'foo', 
  href: 'bar',
  'data-x': 'y',
};
```
And I have no idea what to do with nested object literal:
```ts
interface ElementDescription {
  tagName: string;
  attrs: AttrBag;
}

var el: ElementDescription = {
  tagName: 'a',
  attrs: {
    title: 'foo', 
    href: 'bar', //error
    'data-x': 'y', //error
  }
};
```

**Comment by duanyao** [comment]
Well, the type parameter in the function call of the solution @RyanCavanaugh proposed actually should not be omitted, or strict object literal check is also turned off:
```ts
function setAttrs<T extends AttrBag>(el: Element, attrs: T) {
  //...
}
setAttrs(document.createElement('a'), {
  titile: 'foo', // typo, but no error
  href: 'bar',
  'data-x': 'y',
});
```
I suspect developers too easily forget the type parameter when calling the function because of its verboseness.

**Comment by duanyao** [comment]
I think another use case of "additional property modifier" is guiding type inference for optional properties.

Current behavior:
```ts
// can't write "var colorList = [{ r: 0, g: 255, b: 0, a: 0.5 }]",
// or the third line has error
var colorList: { r: number; g: number; b: number, a?: number }[]
  = [{ r: 0, g: 255, b: 0, a: 0.5 }];
colorList.push({ r: 255, g: 0, b: 0 });
```
With additional property modifier, it is a lot cleaner:
```ts
// type of colorList is infered as { r: number; g: number; b: number, a?: number }[]
var colorList = [{ r: 0, g: 255, b: 0, +a: 0.5 }];
colorList.push({ r: 255, g: 0, b: 0 });
```

**Comment by mhegazy** [comment]
The language already has support for disabling the excess properties for a whole compilation (`--suppressExcessPropertyErrors`), for a specific target (adding index signature), for a specific expression (casting to an intersection type). where as i see how these all do not fit this specific scenario, I do not believe that the added complexity (new syntax and concepts for language users to learn, and implementation complexity in the compiler) does not justify the value.
