### ISSUE TITLE
UTF-8 byte-order mark and source mapping in Visual Studio

### ISSUE THREAD

**Issue by MizardX** [Microsoft/TypeScript#8087]
**TypeScript Version:** 

TypeScript 1.8.9 that came with Visual Studio Professional 2015 14.0.25123.00 Update 2

**Code**

```ts
var x;
```

File saved as "Unicode (UTF-8 with signature) - Codepage 65001"

**Expected behavior:**

Saving the file (using compile-on-save) and building the project generates source-mapping files with the same content.

**Actual behavior:** 

Building the project treats the BOM (U+FEFF) as whitespace, and increments the column count for the first line.

```javascript
{"version":3,"file":"file1.js","sourceRoot":"","sources":["file1.ts"],"names":[],"mappings":"AAAC,IAAI,CAAC,CAAC"}
```

Saving the file ignores the BOM (U+FEFF), and does not increment the column count for the first line.

```javascript
{"version":3,"file":"file1.js","sourceRoot":"","sources":["file1.ts"],"names":[],"mappings":"AAAA,IAAI,CAAC,CAAC"}
```

**Comment by mhegazy** [comment]
@sheetalkamat can you take a look.

**Comment by mhegazy** [comment]
I have just submitted a fix for this. this will be in the next public release. it will also be in the nightly nuget package (https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Nightly%20Builds.md#using-nuget-with-msbuild)
