### ISSUE TITLE
make `exports` referable 

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#8088]
Exports (a parameter on the right part of the picture) is a way to refer to the module itself from within the module. I would be nice if it was exposed in TypeScript the same way as `this` is exposed inside an instance of a current class.

![image](https://cloud.githubusercontent.com/assets/937933/14527577/f3e8f54e-0218-11e6-94b3-5c1bdab9e221.png)

### Problem

Not being able to reference module level identifiers if they are shadowed in a local scope.
    
```typescript

    export function f() {
    }

    export function g(f:() => void) {
        // unable to access f declared at the module level
    }
```

### Workarounds

- Just use slightly different names. *Problem*: Clarity is hurt. Solid consistent naming is important, giving up on it for the sake of making the code work is a burden.  
- Export a single namespace, use its name for referencing the module level exports. *Problem*: reexports are not allowed in namespaces.
    ```typescript

        namespace blah {
           export { meh }; // <-- noway
        }
        export = blah;
    ```
- Use default exports. *Problem*: Inconsistent importing compared to the rest of the modules.

    ```typescript

        export { meh }
        namespace blah {
        }
        export default blah;

        // ... later when importing

        import m1 from 'default-exports';
        import * as m2 from 'traditional-exports';
    ```

### Solution

Expose the `exports` variable to TypeScript so it can be referenced.

**Comment by RyanCavanaugh** [comment]
What would we do when `--module es6` ?

**Comment by mhegazy** [comment]
and why not just alias, or rename the export:

```ts
    function local_f() {
    }
    export {local_f as f};
    export function g(f:() => void) {
        // unable to access f declared at the module level
    }
```

or 

    export function f() {
    }

   var local_f = f;
    export function g(f:() => void) {
        // unable to access f declared at the module level
    }

**Comment by aleksey-bykov** [comment]
@RyanCavanaugh, you are right
@mhegazy, thanks, guess this is the best way around
