### ISSUE TITLE
`new` cannot be applied to a call-site

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#8093]
![image](https://cloud.githubusercontent.com/assets/937933/14538385/8da147ba-0249-11e6-9be3-690659f995ca.png)

```typescript

export function toClass() {
	return class { };
}

const ouch = new toClass(); // <-- expected to work
const yeah = new (toClass()); // works but ugly

```

**Comment by RyanCavanaugh** [comment]
I don't understand why the fact that a function returns a class means you should be able to arbitrarily add a meaningless `new` to an invocation of it. We also prevent you from writing this code and that seems like the right thing to do
```ts
function f() {
	return 3;
}
var x = new f(); // ?
```

**Comment by aleksey-bykov** [comment]
well because it returns a class that I want to instantiate immediately, why not?

as for `3` why would you allow `new` on numbers?

**Comment by RyanCavanaugh** [comment]
I'm really confused. Are you saying we should transform
```ts
const ouch = new toClass();
```
into
```js
const ouch = new (toClass())();
```
during emit?

**Comment by aleksey-bykov** [comment]
got it, thanks
