### ISSUE TITLE
TypeChecker::getTypeAtLocation(Identifier) does not Return Narrowed Type Inside an Array.isArray()-Based Type Guard

### ISSUE THREAD

**Issue by SlurpTheo** [Microsoft/TypeScript#8094]
1.8.10 / next (1.9.0-dev.20160414)

**Code**

```ts
export function X() {
    let x: number | number[] = 0;
    
    if (typeof x === "number") {
        x;              // ts.createProgram(...).getTypeChecker().getTypeAtLocation(Identifier::x).getFlags() --> number
        const y = x;    // ts.createProgram(...).getTypeChecker().getTypeAtLocation(Identifier::y).getFlags() --> number
    }
    if (typeof x !== "object") {
        x;              // ts.createProgram(...).getTypeChecker().getTypeAtLocation(Identifier::x).getFlags() --> number
        const y = x;    // ts.createProgram(...).getTypeChecker().getTypeAtLocation(Identifier::y).getFlags() --> number
    }
    if (!Array.isArray(x)) {
        x;              // ts.createProgram(...).getTypeChecker().getTypeAtLocation(Identifier::x).getFlags() --> Union
        const y = x;    // ts.createProgram(...).getTypeChecker().getTypeAtLocation(Identifier::y).getFlags() --> number
    }
```

**Behavior:**
Why does `TypeChecker::getTypeAtLocation(Identifier::x)` correctly report `number` after the first (`typeof x === "number"`) & second (`typeof x !== "object"`) type guards, but report the (un-narrowed) `Union` type after the third (`!Array.isArray(x)`) type guard? All three block's `const c` is correctly typed as `number`. Is there something besides `TypeChecker::getTypeAtLocation(Identifier)` to use here?

**Comment by mhegazy** [comment]
how about `getSymbolAtLocation(), getTypeOfSymbolAtLocation(symbol, node)` ? do you see any difference?

**Comment by SlurpTheo** [comment]
Doing `getTypeOfSymbolAtLocation(getSymbolAtLocation(Identifier::x), Identifier::x)` gives me the same (`Union`) type, yes (that also correctly reports `number` in the first two type guard blocks).

**Comment by SlurpTheo** [comment]
This appears fixed in typescript@next (1.9.0-dev.20160426) -- probably by https://github.com/Microsoft/TypeScript/pull/8010

**Comment by mhegazy** [comment]
i believe this should be addressed by https://github.com/Microsoft/TypeScript/pull/8324.

**Comment by SlurpTheo** [comment]
OK, tried typescript@next (1.9.0-dev.20160428) and now I get `number` reported in both branches for `TypeChecker::getTypeAtLocation(Identifier::x)`, but `TypeChecker::getTypeAtLocation(VariableDeclaration::z)` is returning `ts.TypeFlags.Anonymous`.

**Comment by mhegazy** [comment]
this is control flow analysis in action :D

```ts
let x: number | number[] = 0;

// x here can only be a number, you assigned it to 0

if (!Array.isArray(x)) {
   // it is a number not an array alright
   const y = x;
} else {
   // it was a number, now we can only be in this branch if it is an array, but it ain't. so it is nothing.
    const z = x;
}
```

this should do what you expect:

```ts
let x: number | number[]; // notice, no initialization

if (!Array.isArray(x)) {
    const y = x; // number
} else {
    const z = x; // number[]
}
```

**Comment by mhegazy** [comment]
looks like this was fixed. closing.

**Comment by SlurpTheo** [comment]
@mhegazy That... is... holy!!!

I think I'm in love with this :+1:
