### ISSUE TITLE
Only consider function parameter types for generic type inference as a last resort

### ISSUE THREAD

**Issue by RyanCavanaugh** [Microsoft/TypeScript#810]
This is a rough sketch so I have something to refer to.

Currently, we treat the two instances of `T` in the parameter list here equally:

``` ts
declare function containsAny<T>(arr: T[], predicate: (x: T) => boolean): boolean;
```

This means that when we make a call like this:

``` ts
var x = containsAny([1, 2, 3], 'hello');
```

we infer `T` to be `{}`. The first argument is assignable to `{}[]` and the second argument is assignable to `{}`, so the call succeeds. This is unexpected and basically wrong.

If instead we only used the type parameters from function arguments when there were _no other candidates_ for a given type parameter, we would infer `T` to be `number` and the call would be correctly rejected.

Not done yet: Actual spec work, thinking it through all the way, testing against existing code.

**Comment by mhegazy** [comment]
looks to be the same issue as https://github.com/Microsoft/TypeScript/issues/1729 or at least related.

**Comment by RyanCavanaugh** [comment]
We did this!
