### ISSUE TITLE
member types, e.g. Tree<T>.Node

### ISSUE THREAD

**Issue by d180cf** [Microsoft/TypeScript#8106]
Sometimes it's useful to declare new types within a class/interface, especially when it's a generic:

```ts
class Tree<T> {
  private type Node = { data: T, subnodes: Node[] };
  public root: Node = { data: null, subnodes: [] };
  ...
}
```

Such member types could be referred to as `Tree<T>.Node`.

**Comment by Arnavion** [comment]
Previous discussion at #7061

**Comment by mhegazy** [comment]
Duplicate of #7061 as noted by @Arnavion
