### ISSUE TITLE
Functions with a declared this type should return that type when called with 'new'

### ISSUE THREAD

**Issue by sandersn** [Microsoft/TypeScript#8109]
Given

```ts
interface FooType {
  x: number;
}
function Foo(this: FooType, x: number) {
  this.x = x;
}
let foo/**/ = new Foo(12);
```

Expected:
`foo` should be of type `FooType`

Actual:
`foo` is of type `any`.

Note: If you name the interface and the function the same thing, then the type of `foo` is structurally correct.

**Comment by mhegazy** [comment]
As per the discussion in the design meeting today, we should log a new issue for supporting new syntax for defining a function that can be called as a constructor.
