### ISSUE TITLE
`this` in function declarations inside object literals should be typed

### ISSUE THREAD

**Issue by sandersn** [Microsoft/TypeScript#8110]
```ts
let o = {
  f: function () { this./**/ }
}
```
Expected: Intellisense shows 'f' in the list
Actual: Intellisense shows nothing because `this: any`.

Note that this similar code already works:

```ts
let o = {
  f() { this./**/ }
}
```

**Comment by sandersn** [comment]
#8389 reverts this fix for now.

**Comment by mhegazy** [comment]
Just to clarify, both patterns will result in a this of type `any`.

We have tried different ways of addressing this issue, and the current behavior (this in an object literal is of type any) seems to be the most reasonable.

Classes present stronger assumptions about how the functions will be called. object literals on the other hand can be used as a property bag often with no assumptions about the relationship of the methods and properties on them. we have seen common JS patterns where methods are added, removed, or called with a different this target at runtime (see #8133 for an example). 

the recommendation is to specify an explicit `this` type in methods:

```ts
interface FooBar {
    foo(): void;
    bar(): void;
}

let o = {
    foo: function (this: FooBar) { this /* FooBar */ },
    bar(this: FooBar) { this /* FooBar */ }
}
````

**Comment by FranklinWhale** [comment]
@sandersn, @mhegazy, @DanielRosenwasser

I have read the the suggestion of adding `this: this` in #9583. Could `: this` be applied to an object literal (not interface) and a method of an object literal to explicitly mark `this` in all methods of that object or that method be the type of the surrounding object? It is not convenient to define `this: this` for each method of an interface. Also, even when the object implements an interface, it may contain additional properties that are used in the interface methods but not exposed via the interface.

Example 1--`this` being the surrounding object in all methods of an object literal:
```ts
var o: this = {
	prop: 12,
	bar() {
		this.prop = 3; // `this` is inferred
	},
	foo() {
		this.bar(); // `this` is inferred
	}
};
```

Example 2--`this` being the surrounding object in a method of an object literal:
```ts
var o = {
	prop: 12,
	bar(this: this) {
		this.prop = 3; // `this` is inferred
	},
	foo() {
		this.bar(); // `this` is any here
	}
};
```

Example 3--`this` being the surrounding object in all methods of an object literal that implements other interfaces:
```ts
interface I {
	bar(); //`this: this` not required
	foo(); //`this: this` not required
}
var o: I & this = {
	prop: 12,
	bar() {
		this.prop = 3; // `this` is inferred
	},
	foo() {
		this.bar(); // `this` is inferred
	}
} as I;
```

**Comment by ahejlsberg** [comment]
See #14141.
