### ISSUE TITLE
querySelector return type could be more specific for single-element selectors

### ISSUE THREAD

**Issue by jelbourn** [Microsoft/TypeScript#8114]
The return types for `querySelector` and `querySelectorAll` (in the [lib.es6.d.ts](https://github.com/Microsoft/TypeScript/blob/79a3e77dd8777ae2f9789844a9432e647ce7013a/lib/lib.es6.d.ts#L19066)) could provide more specific return type information when the selector a single element selector for a known element type.

I.e., right now the types are
```ts
interface NodeSelector {
    querySelector(selectors: string): Element;
    querySelectorAll(selectors: string): NodeListOf<Element>;
}
```

But it could be expanded in [the style of `getElementsByTagName`](https://github.com/Microsoft/TypeScript/blob/79a3e77dd8777ae2f9789844a9432e647ce7013a/lib/lib.es6.d.ts#L8565):
```ts
interface NodeSelector {
    querySelector(selectors: "a"): HTMLAnchorElement;
    querySelector(selectors: "abbr"): HTMLPhraseElement;
    ...
    querySelector(selectors: string): Element;
}
```

It's a minor convenience, but does eliminate the occasional typecast.

**Comment by DanielRosenwasser** [comment]
I don't think this is totally unreasonable. @mhegazy @zhengbli any thoughts on this?

**Comment by mhegazy** [comment]
PRs welcomed. here is some instructions on submitting lib.d.ts PRs: https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes

**Comment by thw0rted** [comment]
I'm a vanilla Javascript user but I benefit from this in VS Intellisense. So, I don't know TS well enough to answer my question: would it be possible to implement this with regex or partial-string matching, such that `querySelector("a.someClass")` also returns a more specific class (i.e. `HTMLAnchorElement`)?  It's the same operating theory, right?  I don't think it's possible for querySelector to return a non-Anchor for the selector example I gave, is it?

**Comment by kitsonk** [comment]
Pattern matching of overloads is #165 and it being applied to `querySelector()` would be different than this closed issue, which has been resolved.

**Comment by thw0rted** [comment]
OK, I think that fills in the blanks of the Typescript syntax I was missing.  I [asked on StackOverflow](https://stackoverflow.com/q/45353770/26286) about good ways to handle this in the short term, and I'm happy enough with the answer, but returning a more specific type (eventually) would make for better code.
