### ISSUE TITLE
Invalid JavaScript for arrow functions with comments

### ISSUE THREAD

**Issue by vitaly-t** [Microsoft/TypeScript#8117]
I've been converting a lot of ES6 JavaScript into TypeScript, and noticed a lot of places got broken where there is a comment between an arrow function opening and implementation.

The code below is supposed to be convertible from ES6 to TypeScript as 1-to-1, without any changes needed:
```ts
function test(){
    return ()=>
    // some comments here;
    123;
}
```
Calling such a function within ES6 returns the expected `()=>123`.

When compiling such TypeScript into ES5 JavaScript we are expecting something like this:

```js
function test(){
    return function () {
        // some comments here;
        return 123;
    };
}
// returns: ()=>123
```

But instead, we are getting this:

```js
function test() {
    return function () {
        // some comments here;
        return
        // some comments here;
        123;
    };
}
// returns: ()=>undefined
```

Which produces a different output result: `()=>undefined`.

**Comment by DanielRosenwasser** [comment]
Hi @vitaly-t I'm not sure where you're getting that emit from. [Here is exactly what I'm getting in the TypeScript Playground](http://www.typescriptlang.org/play/#src=function%20test()%7B%0D%0A%20%20%20%20return%20()%3D%3E%0D%0A%20%20%20%20%2F%2F%20some%20comments%20here%3B%0D%0A%20%20%20%20123%3B%0D%0A%7D) which runs TypeScript 1.8.

```js
function test() {
    return function () {
        // some comments here;
        return 123;
    };
}
```

**Comment by DanielRosenwasser** [comment]
What version of TypeScript are you running? You can run `tsc --version` to find out.

**Comment by vitaly-t** [comment]
@DanielRosenwasser 

```
D:\NodeJS\tests\ts>tsc --version
Version 1.8.10
```
Now running `tsc test`, using input:
```ts
function test(){
    return ()=>
        // some comments here;
        123;
}
```
getting output:
```js
function test() {
    return function () {
        // some comments here;
        return 
        // some comments here;
        123;
    };
}
```

So I don't know what's the difference from your setup...

**Comment by vitaly-t** [comment]
@DanielRosenwasser looks like one shouldn't rely on that Playground for this test. If you run it locally yourself, you will get the same result as me.

**Comment by YuichiNukiyama** [comment]
Mybe, This is effected by `target` option. When I compile tsfile with `tsc test.ts`
output:

```
function test() {
    return function () {
        // some comments here;
        return 
        // some comments here;
        123;
    };
}
```

But, with `tsc test.ts --target "es5"`

```
function test() {
    return function () {
        // some comments here;
        return 123;
    };
}
```

**Comment by vitaly-t** [comment]
@YuichiNukiyama I can confirm that is indeed the case.

**Comment by YuichiNukiyama** [comment]
@vitaly-t  default target vaule is `es3`. see [Compiler Options wiki](https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Compiler%20Options.md).

@DanielRosenwasser 
This must be bug. I found suspicious code in [Emmiter.ts L7882](https://github.com/Microsoft/TypeScript/blob/master/src/compiler/emitter.ts#L7882)(compilerOptions.target is worng. This variable should be languageVersion). If you also think so, I run tests and send PR.

**Comment by DanielRosenwasser** [comment]
The target is ES3 by default. Thank you for finding this, and @YuichiNukiyama, thank you for investigating! We'd definitely appreciate a PR!

**Comment by DanielRosenwasser** [comment]
A simple test case to add would be

`tests/cases/compiler/singleLineCommentInConciseArrowFunctionES3.ts`

```ts
function test(){
    return ()=>
    // some comments here;
    123;
}
```

**Comment by mhegazy** [comment]
thanks @YuichiNukiyama !
