### ISSUE TITLE
Documentation section on website is broken on mobile

### ISSUE THREAD

**Issue by agentfransis** [Microsoft/TypeScript#8119]
The navigation dropdown only has a link to the quick start page.

**Comment by jackqq** [comment]
Confirmed on Android with Firefox and Chrome.

I just discovered that you can read the Handbook from its Github repository. https://github.com/Microsoft/TypeScript-Handbook

![s60421-074312](https://cloud.githubusercontent.com/assets/7012225/14693793/d2f864be-0727-11e6-9eeb-593c105683e1.jpg)

**Comment by jackqq** [comment]
Just discovered another workaround: Set the browser to ask for the Desktop Version of the page, and switch this setting back after navigation.

**Comment by agentfransis** [comment]
In what browser does that work for you? In chrome on android it doesn't
since the resolution stays the same and the mobile version is activated
with a media query.

**Comment by jackqq** [comment]
I found the workaround in **Firefox** 43 on Android 4.4.2.
Just confirmed that it doesn't work in Chrome 47 on Android 4.4.2.

**Comment by mhegazy** [comment]
should be fixed now, can you give http://www.typescriptlang.org/docs/tutorial.html another try.

**Comment by jackqq** [comment]
Confirm, fixed on Android with Firefox and Chrome. Thanks!
