### ISSUE TITLE
Compiler should rewrite namespaced types found in JSDoc

### ISSUE THREAD

**Issue by martine** [Microsoft/TypeScript#8120]
Consider input code like:
```js
import {Foo} from './foo';

/**
 * @type {Foo}
 */
var foo = new Foo();
```

TypeScript imports the module under a generated name (`foo_1` when I tried it), producing code like:

```js
    /**
     * @type {Foo}
     */
    var foo = new foo_1.Foo();
```

But now the JSDoc refers to a type that doesn't exist -- it should instead say `@type {foo_1.Foo}`.  (Another way they could match is if the import created a new variable `Foo` instead of using `foo_1.Foo` everywhere.)

**Comment by mhegazy** [comment]
The compiler should not be messing up with comments it did not create. The correct solution here is to ask the compiler to emit the JSDoc comments for you, including the type information, and it should emit valid names that will match the emitted JS code. that is tracked by https://github.com/Microsoft/TypeScript/issues/10.
