### ISSUE TITLE
Formatting : add new line before brace in function

### ISSUE THREAD

**Issue by Alphapage** [Microsoft/TypeScript#8121]
Hello,

I'm playing with: https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API#pretty-printer-using-the-ls-formatter
The default formatting prints:
```
function test():void {
//something
}
```
But I want:
```
function test():void
{
// something
}
```

Is there any option to add a new line before the code block in a function (I tried ```PlaceOpenBraceOnNewLineForFunctions: true ``` without success) ?

Thanks in advance for your help.

**Comment by DanielRosenwasser** [comment]
@vladima @mhegazy any clues? I would think that would work.

**Comment by vladima** [comment]
works for me, [this snippet](https://gist.github.com/vladima/d8c7755c5ae16897101bf156fc0d506b) produces the expected output

**Comment by Alphapage** [comment]
I'm so sorry: I was overriding the value somewhere else. My big mistake. -1
