### ISSUE TITLE
Support Progressive Transpilation

### ISSUE THREAD

**Issue by kasajian** [Microsoft/TypeScript#8122]
**TypeScript Version:** 
1.7.5 / 1.8.0-beta / nightly (1.9.0-dev.20160217)

**Expected behavior:**
Would like a mechanism that allows one to progressively select which JavaScript features should be transpiled, and which do not need it.  The concept is described here: https://medium.com/@kasajian/progressive-transpilation-def5da34282e#.l38ztasjl

This will allow the creation of custom builds for the specific targeted browser versions.

**Actual behavior:**

**Comment by DanielRosenwasser** [comment]
Thanks for filing, we're tracking granular feature compilation at #4692.
