### ISSUE TITLE
How to generated typed ast?

### ISSUE THREAD

**Issue by yinso** [Microsoft/TypeScript#8127]
**TypeScript Version:** 

1.8.9

**Code**

Based on [Using the Compiler API](https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API), to generate an AST, use `createSourceFile` like this:
```ts
// A self-contained demonstration of the problem follows...
ts.createSourceFile(<filename>, <file content>, ts.ScriptTarget.ES6, true)
```
What gets generated appears to be an untyped AST, i.e. the `.type` field only gets filled if it's declared explicitly in the source code.

What I'm looking for is to generated the typed AST, i.e. having the sources being loaded and typed-checked.

How can I do that? Thanks.

**Comment by mhegazy** [comment]
`.type` on an AST node represents the type declaration. i.e. `T` in ` var x: T`.

What you are looking for is the type of a symbol, and to get to these you need to ask the [`TypeChecker`](https://github.com/Microsoft/TypeScript/blob/b0584b58fa07ee8c06e6d6f0f1bce2d4c37c7640/lib/typescript.d.ts#L1123) using something like [`TypeChecker.getTypeAtLocation(node)`](https://github.com/Microsoft/TypeScript/blob/b0584b58fa07ee8c06e6d6f0f1bce2d4c37c7640/lib/typescript.d.ts#L1177).

you can find more examples for these in the services file like https://github.com/Microsoft/TypeScript/blob/b0584b58fa07ee8c06e6d6f0f1bce2d4c37c7640/src/services/services.ts#L4183
