### ISSUE TITLE
Interface type guard not working on extended classes

### ISSUE THREAD

**Issue by jonatan-alama** [Microsoft/TypeScript#8128]
**TypeScript Version:** 

1.8.9

**Code**

```ts
interface CanDevelop {
	developSomethingAmazing();
}
class Person {
	age: number;
	name: string;
}

class Developer extends Person implements CanDevelop {	
	developSomethingAmazing() {}
}

function canDevelop(arg: any): arg is CanDevelop {
	return arg.developSomethingAmazing !== undefined;
}

let john: Object = new Developer();

if (canDevelop(john)) {
	john.developSomethingAmazing();  // OK
}

let peter: Person = new Developer();

if (canDevelop(peter)) {
	peter.developSomethingAmazing(); // ERROR
}

```

**Expected behaviour:**
It should allow to use the CanDevelop interface methods.

**Actual behaviour:** 
Error "Property 'developSomethingAmazing' does not exist on type 'Person'".

**Comment by kitsonk** [comment]
Because it doesn't.  You can't narrow something that doesn't exist.  You asserted a type which is a class that does not implement `CanDevelop`.  Because `Developer` is a superset of `Person` it can be narrowed to `Person` but can't be expanded to `Developer` once narrowed (and then further narrowed to `CanDevelop`.

**Comment by jonatan-alama** [comment]
I did some more testing. 

It works if the parent class (Person) has no properties:

```ts
interface canDevelop {
	develop();
}

class Person {
}

class Developer extends Person implements canDevelop {
	develop() {}
}

function canDevelop(arg: any): arg is canDevelop {
	return arg.develop !== undefined;
}

let john: Person = new Developer();

if (canDevelop(john)) {
	john.develop(); //OK
}
```

It also works with classes instead of interfaces:

```ts
class Person {
	name: string;
}

class Developer extends Person {
	develop() {}
}

function canDevelop(arg: any): arg is Developer {
	return arg instanceof Developer;
}

let john: Person = new Developer();

if (canDevelop(john)) {
	john.develop(); //OK
}
```

**Comment by RyanCavanaugh** [comment]
This is generally the expected behavior.

Narrowing can only produce a *more specific* type, not a completely-different type. Narrowing "across" a type hierarchy would allow all sorts of very suspect coercions.

**Comment by jonatan-alama** [comment]
Thank you Ryan, I understand the current behaviour now.

I found two ways of solving the problem:

1) Asserting to `any` and then narrowing inside the `if` statement:

```ts
if (canDevelop(john)) {
    <canDevelop>(<any>john).develop();
}
```
The output JavaScript is the same. I think it would be nice if we could do one step assertions in safe situations, but that is a different topic.

2) Creating a parent `IPerson ` interface that `canDevelop` extends and `Person` implements.
