### ISSUE TITLE
intelisense won't work for require with template strings

### ISSUE THREAD

**Issue by egamma** [Microsoft/TypeScript#8135]
_From @NikosEfthias on April 14, 2016 19:9_
- VSCode Version:1.8.2
- OS Version:ubuntu 15.10

Steps to Reproduce:

``` javascript
const a=require("something") //autocomplete works great
const b=require('something') //autocomplete works great
const c=require(`something`) //will not autocomplete
```

_Copied from original issue: Microsoft/vscode#5273_

**Comment by egamma** [comment]
Moving to the TypeScript repository for investigation.

**Comment by NikosEfthias** [comment]
@egamma  i dont think this shpuld be closed before actially it is solved

**Comment by RyanCavanaugh** [comment]
This issue is not closed

**Comment by mhegazy** [comment]
Fixed by https://github.com/Microsoft/TypeScript/pull/19204
