### ISSUE TITLE
TSServer shouldn't assume that OSX file system in case insensitive

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#8139]
**TypeScript Version:** 

1.8.9

The tsserver code assumes that OSX file systems are always run case insensitive. However this is not the case. When the tsserver is used on a case sensitive file system code assist and other features stop working do to file lookup misses. For all the details please see:

https://github.com/Microsoft/vscode/issues/5161#issuecomment-210490841

**Comment by billti** [comment]
@zhengbli aren't you already looking into this for other issues related to watchers?

**Comment by zhengbli** [comment]
This should be fixed by https://github.com/Microsoft/TypeScript/pull/7658, which was merged in master.

**Comment by otbe** [comment]
Mh ```master``` did not work for me. 
Same problem like before.

**Comment by otbe** [comment]
Tried to use ```1.9.0-dev.20160419``` with vscode and in my test project, but got ```TypeError: service.getSourceFile is not a function``` from gulp-tsb.

Is it possible to test your fix?

**Comment by vladima** [comment]
it seems that `gulp-tsb` was not updated to work with the latest bits: outstanding PR to fix it https://github.com/jrieken/gulp-tsb/pull/40

**Comment by zhengbli** [comment]
@otbe currently you can test by editing your test project directly in vscode, with the nightly build of typescript.

**Comment by otbe** [comment]
@zhengbli 
Should I install ```1.9.0-dev.20160419``` as my project dependency?

**Comment by zhengbli** [comment]
If you mean using it with VSCode, you could edit your settings file via `File -> Preferences -> User Settings`, and add
```
"typescript.tsdk": "<the folder where tsserver.js lives>"
```
for example
```
"typescript.tsdk": "C:/Program Files/nodejs/node_modules/typescript/lib",
```

**Comment by otbe** [comment]
Works as expected.
Thank you 👍
