### ISSUE TITLE
Cannot find name 'Fluxxor' && 'Import Fluxxor' - multiple conflicting Intellisense detections

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#8140]
_From @jwulf on November 24, 2015 12:49_

![screen shot 2015-11-24 at 10 43 58 pm](https://cloud.githubusercontent.com/assets/406975/11367128/6a53fb2e-92fd-11e5-911c-752e64b96a2f.png)

_Copied from original issue: Microsoft/vscode#544_

**Comment by dbaeumer** [comment]
_From @jwulf on November 24, 2015 12:51_

This is on a Mac.

**Comment by dbaeumer** [comment]
_From @jwulf on November 24, 2015 13:5_

Perhaps it is the `* as Fluxxor`?

`import * as Fluxxor from 'fluxxor'`

Nope. It's still there with:

`import Fluxxor = require('fluxxor');`

**Comment by dbaeumer** [comment]
@jwulf would you be able to share a folder with me that shows the behavior.

**Comment by dbaeumer** [comment]
_From @unional on April 15, 2016 20:51_

Just encountered this also.
The code runs fine on `tsc` but error on vscode (`ts language service`). Here is how to reproduce:

```ts
// s.ts
export class Foo {}

// m.ts
import { Foo } from './s';
declare namespace Foo { };
export = Foo;

// c.ts
import * as Foo from './m';

console.log(Foo);
```
![image](https://cloud.githubusercontent.com/assets/3254987/14574542/1a0e1bca-0311-11e6-9dc9-27838f267675.png)

**Comment by dbaeumer** [comment]
_From @unional on April 15, 2016 20:51_

Reference: 
https://github.com/typed-typings/npm-any-promise/pull/1

**Comment by dbaeumer** [comment]
_From @unional on April 15, 2016 20:57_

I tested this on Windows.

Code: 1.0  :tada: 
Also tested with TypeScript@next using `settings.json/typescript.tsdk`: `1.9.0-dev.20160415`

**Comment by dbaeumer** [comment]
@unional thanks for the code test case. I am moving this to TS since the seems to be caused by the reexport in m.ts

**Comment by sandersn** [comment]
There is an error in this code, but it's not being reported at the right place. In m.ts, there should be a duplicate identifier error:

```ts
// m.ts
import { Foo } from './s';
declare namespace Foo { };
                  ^^^
                  Duplicate identifier 'Foo'.
```

This is because imported identifiers don't merge with anything else.

**Comment by sandersn** [comment]
@ahejlsberg pointed out offline that the compiler assumes that symbols are either aliases (imported/exported symbols) or local declarations -- never both. So as soon as `export = Foo` sees that `Foo` is locally declared, it exports only that. It never looks for the imported `class Foo` and never tries to merge them.

That means the code in `m.ts` is actually legal, but probably not what you wanted. Probably you want to use a module augmentation instead:

```ts
// s.ts
export class Foo {}

// m.ts
declare module './s' {
  namespace Foo { };
}
export var dummy = 1;

// c.ts
import { Foo } from './s'; // import from ./s instead of ./m
console.log(Foo);
```

**Comment by mhegazy** [comment]
@sandersn there are cases where the error is not reported. but the export behavior is not what is expected. we should raise these as errors .
