### ISSUE TITLE
Little bug in template jsdoc on param callback

### ISSUE THREAD

**Issue by Thaina** [Microsoft/TypeScript#8141]
I try to use template jsdoc on parameter which is callback function like this

``` JS
/**
 * @template T
 * @param {T[]} array
 * @param {function(T,number,function():void):void} action
 * @param {function():void} onFinish
 */
function ForEach(array,action,onFinish) {
    /** @type number */
    var i = arguments[3];
    if(!(i > 0))
        i = 0;

    if(i >= array.length)
        return onFinish();

    action(array[i],i,function() {
        setImmediate(asyncLib.ForEach,array,action,onFinish,i + 1);
    });
}
```

And it seem like it work, It put T type on action parameter p0

![image](https://cloud.githubusercontent.com/assets/1042507/14600232/c55eefd8-0585-11e6-86eb-85abec551cd5.png)

But when I try to use it like this.

``` JS
ForEach([0,1,2],function (n,i,done) {

},function () {

});
```

It just said everything is T, not the type of array I put in there

![image](https://cloud.githubusercontent.com/assets/1042507/14600587/a0510562-0587-11e6-9102-2180e7cb1a3f.png)

**Comment by billti** [comment]
I just tried this exact code on my local machine with `release-1.8` and `master` branches, and it's working fine (i.e. I see types of `number`, not `T`, for the signature help and intellisense). Which build are you using?

I would note that if the arguments to `ForEach` and the signature don't match, then we don't contextually type the arguments, and you will get the behavior you are experiencing. We could look at always contextually typing (esp. if there is only one signature) to be more helpful here. Marking this as a suggestion for that reason.

**Comment by Thaina** [comment]
@billti I use 1.9 and vscode 1.0.0

**Comment by Thaina** [comment]
Confirmed it work when I was uninstall and reinstall 1.8.10

Then it not work when I was uninstall 1.8.10 and install typescript@next (1.9.0-dev.20160420)
