### ISSUE TITLE
Visual Studio Project properties tab unusable on high DPI display

### ISSUE THREAD

**Issue by flcdrg** [Microsoft/TypeScript#8142]
**TypeScript Version: ** 

1.8.29

**Actual behavior:** 

Using Visual Studio 2015 with a UHD display (3840 x 2160) running at 250%

- You can't set the TypeScript version
- Output options are truncated (and no option to scroll down)
- Possibly other things missing altogether - hard to tell :-)

![typescript project properties](https://cloud.githubusercontent.com/assets/384747/14604278/dcd250fc-05b1-11e6-8c70-a5681c7de341.png)

**Comment by billti** [comment]
Looks like an issue we recently fixed in a minor update for VS. Can you try applying https://msdn.microsoft.com/en-us/library/mt695655.aspx and see if this resolves it (it's listed as issue 2 on that page).

**Comment by paulvanbrenk** [comment]
Yes, this is the issue we fixed in the update Bill pointed out.

**Comment by flcdrg** [comment]
Awesome. I hadn't noticed the update. At least this issue/resolution should now show up in search engines for other people who might encounter this problem.
