### ISSUE TITLE
TSC fails with "Out of Memory" when using rx.js Observable.empty() in a certain way

### ISSUE THREAD

**Issue by eyal453** [Microsoft/TypeScript#8143]
**TypeScript Version:** 

1.8.10 (haven't tested others)

**Reproduce**
To reproduce, download my sample app from here https://onedrive.live.com/redir?resid=D21E8187512929BF!618745&authkey=!AIy8PGTFM15HoiI&ithint=file%2czip
run 'npm install'
then 'typings install'
then 'tsc -w'

The problem is with line 19 in `app/src/app/api/ApiService.ts`. When commenting out this line `tsc` works as expected and transpiles it within a few short seconds. When uncommenting it, `tsc` will take more than 15 seconds to compile and sometime even crash with an "Out of Memory" exception.
The problem seems to be specifically with the `empty` method under `Observable` from rxjs. 
A workaround, as noted in line 18, is to use the generic form of the `empty` method and write 'Rx.Observable.empty<any>()' instead. Another thing to notice is if we use `Rx.Observable.empty()` in a different file in the project there seems to be no problem. I could only reproduce this crash with this specific structure.

**Expected behavior:**
`tsc` should compile as usual

**Actual behavior:** 
`tsc` hangs for 15-20 seconds (depends on the size of the app) and sometimes crashes with an "Out of Memory" exception.

**Comment by vladima** [comment]
this is a [known issue](https://github.com/Microsoft/TypeScript/issues/7344#issuecomment-198392320) with RxJs@5.0.0-beta2, on my box upgrading to beta-3 drops the compilation time from ~10s to ~1 s
