### ISSUE TITLE
No intellisense when object definition and declaration is splitted

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#8146]
_From @DenysYefimenko on April 18, 2016 13:17_

- VSCode Version: 1.0.0
- OS Version: Windows 10

Steps to Reproduce:

1 Having following code: 
```javascript
function constructorFunction () {
	this.otherFunction = function () {}
}

constructorFunction.prototype.method = function () {};

var x;
x = new constructorFunction();
x.method();
```
2 Try to get intellisense suggestions on `x.method()`. No suggestions provided (apart from generic ones).
3 Do the following change:
replace 
```javascript
var x;
x = new constructorFunction();
```
with
```javascript
var x = new constructorFunction();
```

4 Intellisense starts working on `x`. It suggests both `method `and `otherFunction`.

_Copied from original issue: Microsoft/vscode#5452_

**Comment by dbaeumer** [comment]
This is TS related. Moving...

**Comment by billti** [comment]
`x` is declared without a type above. We do not give it a new type based on later assignments. It needs to either be initialized at declaration with a value of the desired type, or given a JsDoc annotation to set the type explicitly.
