### ISSUE TITLE
`typeToString` discrepancy?

### ISSUE THREAD

**Issue by yinso** [Microsoft/TypeScript#8163]
**TypeScript Version:** 

1.8.9

**Code**

With the following function

```ts
function foo(a) {
  return a + 'hello';
}
```

I'd expect that `typeChecker.typeToString` of `foo`'s type should yield `(a: string) => string`.

Instead, it returns `(a: any) => string`.

Is this an issue of `typeToString`, or is the underlying Type object really marks `a` as `any`?

If it's the former, how can I walk the Type object to generate the right signature? A quick glance shows that a procedure type is "anonymous", and holds an opaque reference of `target` and `mapper`, which doesn't shed light on how to traverse the type objects. Is there a guide somewhere about the types?

I'm trying to generate the type signature for run time contract checking, so I need an accurate representation of the resolved type info.

**Comment by DanielRosenwasser** [comment]
This is actually by design - `a` implicitly gets the type `any` at that position. We don't do inference based on how you end up using your parameters.

**Comment by kitsonk** [comment]
And even at runtime, `a` isn't implicitly a string, because lots of other values could easily be coerced into a a `string` and provide no runtime issue:

```js
function foo(a) {
  return a + 'hello';
}

console.log(foo(true));
console.log(foo(5));
console.log(foo(undefined));
console.log(foo(null));
console.log(foo({}));
console.log(foo(/foo/));
console.log(foo(['foo', 'bar']));
```

All these produce valid results (a string) without throwing.

**Comment by basarat** [comment]
> And even at runtime, a isn't implicitly a string

Indeed. It is implicitly an `any`. If you want such *unsafe* cases to be an error turn on `--noImplicitAny` as @DanielRosenwasser pointed out. Then you can see the error and either add `:any` (to tell the next dev that its okay, I want it to be an `any`) or annotate with `:string` (which is what you want) :rose:

**Comment by yinso** [comment]
@kitsonk - not sure what you mean. JS runtime isn't exactly type sound, which provides the motivation for creating TypeScript in the first place, no?

@DanielRosenwasser & @basarat - thanks will give `--noImplicitAny` a try. I originally thought TypeScript's type inference is like OCaml. Should I instead think of it as a local inference system (i.e. all functions should be annotated) - instead?

**Comment by DanielRosenwasser** [comment]
@yinso it is somewhat closer to that. We have the idea of inferential typing and contextual typing. There are certain contexts in which we can figure out the types that an expression will flow to.

For instance, with

```ts
[1,2,3,4].map(x => x)
```

TypeScript can figure out that the type of `x` is `number` because it knows that you're calling `map` on a `number[]`. That's called *contextual typing*.

**Comment by kitsonk** [comment]
@yinso of course it isn't type safe, but by omitting any type annotation TypeScript has to assume the worse.  Mostly TypeScript without type annotations is just JavaScript and the compiler was offering up what it could given the context.

To further Daniel's explanation even then, TypeScript doesn't do that without some indication of how to extract those types out of the context.  From `lib.d.ts`:

```typescript
interface Array<T> {
    map<U>(callbackfn: (value: T, index: number, array: T[]) => U, thisArg?: any): U[];
}
```

So it infers the type of `number[]` which is then what it passes at `number` to `value` on the `callback` via the use of generics.  That means any callback function could have its types narrowed, depending on where and how it is used.  [For example](http://www.typescriptlang.org/play/#src=function%20cb1(value%2C%20index%2C%20array)%20%7B%20%2F%2F%20no%20context%2C%20so%20%60any%60%20is%20assumed%0A%20%20%20%20return%20value%3B%20%2F%2F%20return%20considered%20%60any%60%20because%20no%20context%0A%7D%0A%0Afunction%20cb2(value%3A%20string%2C%20index%3A%20number%2C%20array%3A%20string%5B%5D)%20%7B%20%2F%2F%20everything%20typed%0A%20%20%20%20return%20value%3B%20%2F%2F%20return%20type%20inferred%20to%20be%20string%3B%0A%7D%0A%0A%5B%201%2C%202%2C%203%20%5D.map(function%20(value%2C%20index%2C%20array)%20%7B%20%2F%2F%20context%2C%20so%20value%20is%20number%2C%20etc...%0A%20%20%20%20return%20value%3B%0A%7D)%3B%0A%0A%5B%201%2C%202%2C%203%20%5D.map(cb1)%3B%0A%5B%201%2C%202%2C%203%20%5D.map(cb2)%3B%0A):

```typescript
function cb1(value, index, array) { // no context, so `any` is assumed
    return value; // return considered `any` because no context
}

function cb2(value: string, index: number, array: string[]) { // everything typed
    return value; // return type inferred to be string;
}

[ 1, 2, 3 ].map(function (value, index, array) { // context, so value is number, etc...
    return value;
});

[ 1, 2, 3 ].map(cb1); // Works fine
[ 1, 2, 3 ].map(cb2); // Error, incompatible signatures
```

**Comment by yinso** [comment]
@DanielRosenwasser - thanks for the info on contextual typing. I will do more research on typescript's capability.

@kitsonk - thanks for the explanation and example. My take away is that typescript's design goal is to be compatible with Javascript (i.e. a proper superset), so it needs to be compatible with JS's runtime behavior when types are unspecified.

**Comment by kitsonk** [comment]
> so it needs to be compatible with JS's runtime behavior when types are unspecified

Or can't be contextually deduced. 😄
