### ISSUE TITLE
Suggestion: Show unused imports in VS Code  Editor as grayed

### ISSUE THREAD

**Issue by BBGONE** [Microsoft/TypeScript#8165]
I do a refactory of a large project. I split large modules into smaller ones.
So when i move imports to a new module i want to remove unused imports.
This can not be done easily as i click in context menu "Find All references" it  shows all the references in the current project - "it is very unuseful i admit".

_So, if it is by design, then this problem can be ameliorated by showing unused imports  as  grayed._

**Comment by s-panferov** [comment]
@BBGONE have you tried to use [tslint](https://github.com/palantir/tslint) and corresponding editor plugin? It can highlight unused imports.

**Comment by BBGONE** [comment]
@s-panferov Thanks, i did not try, yet. It will be very helpful in my case.

**Comment by donaldpipowitch** [comment]
I think this would be solved if `noUnusedParameters ` and `noUnusedLocals ` would be shown as warnings, not as errors. See for example https://github.com/Microsoft/TypeScript/issues/13408.

**Comment by BBGONE** [comment]
in fact _noUnusedParameters_ and _noUnusedLocals_ behave very rough.
For examle i have a code like this:
 ```
obj.addOnPropertyChange("*", function (s, a) {
            if (props.indexOf(a.property) > -1) {
                fn_onChange(a.property);
            }
        }, self.uniqueID);
```
where the s parameter is not used, but it's not an error. I can not remove it because it's the function's signature and is required, and it's not the last parameter which i can not simply ommit. 
Another problem when i declare an abstract class which members should be overriden. It's member functions have some parameters which is not used, but are used when overriden.
So these compiler options should account for the above situations.

**Comment by donaldpipowitch** [comment]
Regarding:

```
obj.addOnPropertyChange("*", function (s, a) {
           if (props.indexOf(a.property) > -1) {
               fn_onChange(a.property);
           }
       }, self.uniqueID);
```

Yeah, that's why it should be warning and not an error. (And maybe not even a warning in this case.)

By the way you can "fix" this by writing `_s` instead of `s`. Not TypeScript will just ignore it.

**Comment by demisx** [comment]
Though, version 1.19 underlines unused symbols in the imports now I wish the entire import was greyed out similar to other IDEs. That would make such imports easier to spot.

**Comment by mhegazy** [comment]
@andy-ms this is related to the non-error suggestions feature.

**Comment by vytautas-pranskunas-** [comment]
any progress on this?

**Comment by DavidVotrubec** [comment]
I am looking forward this feature too

**Comment by BBGONE** [comment]
now, for me it's all ok when unused imports is an error. If there's an error, i just remove the unused import.

**Comment by demisx** [comment]
We would rather have it as a grayed warning. Errors break the build.

**Comment by erzhtor** [comment]
Also waiting for this feature!

**Comment by tangooncash** [comment]
I need to see it

**Comment by marioteik** [comment]
+1

**Comment by mjbvz** [comment]
Just merged in support for this into VS Code: https://github.com/Microsoft/vscode/issues/15710

Should be in tomorrows VS Code insiders. It is controlled by the settings:

```json
"javascript.showUnused.enabled": true,
"typescript.showUnused.enabled": true,
```

**Comment by SerkanSipahi** [comment]
@mjbvz when it will be published for all?
