### ISSUE TITLE
VS 2015 code editor renames imports globally instead of only for a module

### ISSUE THREAD

**Issue by BBGONE** [Microsoft/TypeScript#8171]
This issue is in lieu of  the issue  #8118 (which was closed by @mhegazy , and according to his comment this should not happen as the alias is local)

**TypeScript Version:** 
1.8.9

**Code**
For example we have 3 modules: app.ts, module1.ts and module2.ts

in app.ts module we have:
```ts

export class Greeter {
}

```
in module1.ts module we have:
```ts

import { Greeter as ChitoGreetor } from "app";

let greeter = new ChitoGreetor();

```
in module2.ts module we have (**the same import alias as in module1**!):
```ts

import { Greeter as ChitoGreetor } from "app";

let greeter = new ChitoGreetor();

```
**Actual behavior:** 

If we rename in VS code editor module alias ChitoGreetor in module1 then it will be renamed
in module2 too. Besides, if we look for references using "Find all references" in module1 then
it finds references in module2 too.

**Expected behavior:**

Rename the alias only locally in one module which uses the import.
And find references locally either.

**Comment by andy-ms** [comment]
Successfully reproduced the issue in the current VSCode, but it appears to be fixed in the [next](https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Nightly%20Builds.md#visual-studio-code) version.
