### ISSUE TITLE
Find references on overloaded/abstract class method

### ISSUE THREAD

**Issue by use-strict** [Microsoft/TypeScript#8173]
It would be nice for "Find references" to also report usages of the overloads / implementations of the base method.

Example:
```ts
abstract class Base {
    abstract someMethod(): void; // <-- find references here should also find MyClass#someMethod
}

class MyClass extends Base {
    someMethod() {
        alert('test");
    }
}
```

EDIT: This is also a problem with refactoring (method rename) since it would rename the base class method, but not the overrides in the child classes.

**Comment by RyanCavanaugh** [comment]
Thanks for reporting this. Unfortunately, the code here isn't enough to reproduce the issue you're describing -- the rename and find references successfully find `someMethod` in both classes regardless of which one I start at.

Can you reduce this down to an isolated block that shows the bug? Either a sample that clearly shows the problem in the TypeScript Playground would be great.

**Comment by use-strict** [comment]
Somehow I assumed this feature wasn't implemented at all and I didn't bother to test my example. It looks like it only happens when generics are involved. See the modified example below:
```ts
abstract class Base<T> {
    abstract someMethod(): T; // <-- find references here should also find MyClass#someMethod
}

class MyClass<T> extends Base<T> {
    someMethod(): T {
        alert('test');
	    return; // funnily, this is also allowed without an explicit cast
    }
}
```

**Comment by RyanCavanaugh** [comment]
Re: your comment, see the `--noImplicitReturns` switch
