### ISSUE TITLE
tsc command inside npm scripts causes npm to error out

### ISSUE THREAD

**Issue by MarkPieszak** [Microsoft/TypeScript#8186]
**TypeScript Version:** 
1.7.5 && nightly (1.9.0-dev.20160217) either one

https://github.com/npm/npm/issues/12412

> Unsure if this is an Npm issue itself or something that `tsc` is doing that's causing npms lifecycle to crash and error out.

#### To reproduce, simply try to run `tsc` when inside an npm script on Windows.

In my example I have:

    "scripts" : {
        "build-ts" : "tsc"
    }
When running:

    npm run build-ts

It runs typescript compiler and all of that seems to work fine. After, it seems to error out (causing any further scripts to never run as well)
*Note: tsc alone when ran in the console works fine.*

**Comment by mhegazy** [comment]
> It runs typescript compiler and all of that seems to work fine. After, it seems to error out (causing any further scripts to never run as well)

not sure i understand. locally `npm run build-ts` seems to work fine for me. what are you seeing? what errors do you get?

**Comment by MarkPieszak** [comment]
Apologies, errors added above. (As well as here)

ELIFECYCLE
Exist status 1
Failed at ... build-ts script 'tsc'
Make sure you have the latest version of node.js and npm installed.

**Comment by mhegazy** [comment]
what version of npm are you using? searching around, this seems like an npm issue that ppl have been running into with other packages. https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=elifecycle%20npm

**Comment by MarkPieszak** [comment]
I'm using the latest Node 5.10.1 and npm 3.8.6

**Comment by mhegazy** [comment]
does setting `NODE_PATH` change anything, many issues seem to be suggesting that as a solution.

**Comment by maximedupre** [comment]
My npm script crashes when there are some typescript errors e.g. `error TS2307: Cannot find module '../models/User'.`, but as soon as I fix all the errors, everything works. Shouldn't the npm script still "succeed" even though typescript emits some errors?

**Comment by mhegazy** [comment]
if an error is reported, the return code is non-zero to indicate that the compilation failed. this is needed for other build tool chains.

**Comment by MarkPieszak** [comment]
@maximedupre Very strange, and I've noticed this is the same thing for me. `tsc` in the console will still get everything done, it also will when it's within `npm scripts`, but the scripts "flow" stops. (If you're chaining multiple scripts together with && for example)

@mhegazy The strange thing is, this actually works on any OS, but **Windows 7 is where this problem occurs**. I have a feeling this might be more of an `npm` issue than Typescript perhaps?

**Comment by mhegazy** [comment]
I tried to look into it yesterday and could not find any reasons on the TS side. it does seem to be a recurring npm issue in general, but i can not say for sure if it is.

**Comment by maximedupre** [comment]
@MarkPieszak I'm on OSX and it doesn't work :/.

**Comment by MarkPieszak** [comment]
Yeah I posted the issue there as well (linked these 2) but no response yet :(  Have a feeling it's something `npm` is doing, it shouldn't stop the lifecycle because of TS errors (that in this case are more "warnings" than errors.

Thank you so much for looking into it Mohamed.

**Comment by MarkPieszak** [comment]
@maximedupre What version of Node are you using?

**Comment by maximedupre** [comment]
`v5.10.1`

**Comment by basarat** [comment]
I use `tsc` / [`ntsc`](https://github.com/TypeStrong/ntypescript#npm-scripts) daily and [it works just fine](http://alm.tools/). Never had a problem. You might want to share the repro project on git :ros:

**Comment by jphustman** [comment]
I'm getting the same problem, its only if I have "tsc" in a script in "package.json" and run that script:

`"scripts" {
    "tsc": "tsc"
}`

Then run "npm tsc" or "npm run tsc" from the command line.  This is using the typescript installed with npm:  v1.8.10

**Comment by MarkPieszak** [comment]
@jphustman Yeah that's when the error seems to occur. If there's even 1 thing that isn't `declared` in the TS you are trying to run through, TSC is triggering a minor error (which on any other OS keeps going) but for Win7 it seems to stop `npm` dead in its tracks.

@mhegazy @basarat What error code is being thrown for something like this? Maybe there's some disconnect between npm on win7 and `tsc` that's making it thing it should stop the npm lifecycle at this point.

**Comment by mhegazy** [comment]
The compiler can return `0`, `1` or `2` as exit status. here are the definitions of what they mean: https://github.com/Microsoft/TypeScript/blob/master/src/compiler/types.ts#L1736-L1746

**Comment by hoetmaaiers** [comment]
I have the same issue. Exit status 2 when running tsc in `"prestart": "./node_modules/.bin/tsc"`.
The explanation for ExitStatusCode 2 is not saying much.

**Comment by MarkPieszak** [comment]
@mhegazy So to make the issue more specific. Basically when you have a few undeclared ts things such as Promise / require / anything really, things that actually don't "break" anything. When running them through npm TS throws that exist status 1 which causes npm lifecycle to completely stop, but it's fine on a MAC for example.

If you want to see it in action, pull down https://github.com/angular/universal and try to run an `npm i` on a Win7 machine. Very interesting...

**Comment by MasterKale** [comment]
`types.ts` has changed since @mhegazy posted his link so the line numbers don't match up anymore. Here's a copy-paste of those lines for sake of discussion:

    export enum ExitStatus {
        // Compiler ran successfully.  Either this was a simple do-nothing compilation (for example,
        // when -version or -help was provided, or this was a normal compilation, no diagnostics
        // were produced, and all outputs were generated successfully.
        Success = 0,

        // Diagnostics were produced and because of them no code was generated.
        DiagnosticsPresent_OutputsSkipped = 1,

        // Diagnostics were produced and outputs were generated in spite of them.
        DiagnosticsPresent_OutputsGenerated = 2,
    }

I'm experiencing a similar issue with the `tsc` command returning `2` but still outputting a transpiled Javascript file:

    node_modules/.bin/tsc -out /home/matthew/Repos/dpts/static/ts/main.js /home/matthew/Repos/dpts/static/ts/main.ts

This command causes `django-pipeline` to error out, even though a `.js` file is generated. No errors appear in the console, either - it's not until I try running this command via `django-pipeline` that the command supposedly errors out with `exit code 2`:

    pipeline.exceptions.CompilerError: ['node_modules/.bin/tsc', '', '-out', '/home/matthew/Repos/dpts/static/ts/main.js', '/home/matthew/Repos/dpts/static/ts/main.ts'] exit code 2
    b''

The code 2 is thrown but nothing is returned indicating what errors (if any) were detected in the TypeScript file being processed. How can I see whatever "diagnostics" the command is generating despite outputting a converted file?

**Comment by mhegazy** [comment]
> The code 2 is thrown but nothing is returned indicating what errors (if any) were detected in the TypeScript file being processed. How can I see whatever "diagnostics" the command is generating despite outputting a converted file?

what do you see running tsc directly? do you see any errors.

**Comment by MasterKale** [comment]
I don't see any errors when I copy-paste that command to call `tsc` manually. The file generates without issue and then the program exits with no additional output.

**Comment by MarkPieszak** [comment]
So we have redone the repo, now it doesn't chain installs for separate modules, the issue has gone away now because of that. 😕 this might of been a combination of things causing this. Now using 2.0beta and such, I've never seen it come up luckily !

When running tsc directly previously nothing would come up, but a small declaration error was coming up then, something that would of been more of a warning caused npm lifecycle to stop.

I'll close out for now unless there's some way I can replicate it again! Thanks again guys.

**Comment by bmingles** [comment]
I just got the same error on Ubuntu 16.04. Turned out to be caused by a missing .d.ts dependency. Once I added it the problem went away.

**Comment by CWSpear** [comment]
@mhegazy's link to the exit statuses no longer points to the right lines. Here's a permalink: https://github.com/Microsoft/TypeScript/blob/19aac12be9e73851dee3db4263105beaec20c14a/src/compiler/types.ts#L1916-L1927

(Pro Tip: press `y` while viewing a file and it will change the URL to reference the specific commit)

**Comment by deanrih** [comment]
I got this error too, I just wondered is there any arguments that ignore error and not returning non-zero exit code so I can use it on npm script without getting cancelled to next script because of tsc error, and I can use it like
`"prestart": "tsc --ignore-error @tscfiles"`

**Comment by MarkPieszak** [comment]
I think the easiest way is to just do "tsc || true" for your prestart script there @deanrih that'll let it continue

**Comment by deanrih** [comment]
@MarkPieszak thanks for the heads up, but what is `tsc || true` actually do ? because for some reason, `tsc || true` or `tsc || true @tscfiles.txt` in my case, will make the tsc print the content that can be seen through `tsc --help` or it simply unrecognized and resulting to not compiling the `.ts` files into `.js`.

My guess is, it can be my environment or my placing mistakes, but I can't place it like `tsc @tscfiles.txt || true` because it generate error `true is not recognized as an internal or external command`.
So maybe that is linux / mac terminal command ?

My development environtment is
Windows 10
Node v7.3.0
NPM 4.0.5
TypeScript Version 2.1.4

**Comment by bmingles** [comment]
Try
 tsc @tscfiles || echo done.

**Comment by deanrih** [comment]
@bmingles 
Thanks, it works, I thought that the `||` is not a part of the command line, or that just my laziness to explore.
Hope this will help anybody with same problem.

> `tsc @tscfiles || echo done.`

**Comment by MarkPieszak** [comment]
Ahh apologies, I was looking through old commits, `|| echo ` was what I was looking for :)
It just goes to the || (or) if it errors out and instead of stopping the entire process, just prints/echo's out something to keep it going. Good memory @bmingles 👍

**Comment by bmingles** [comment]
Goal is just to result in non-error code, so using || like a boolean OR and echo just happens to return non-error. You could use another "truthy" statement if you preferred.
