### ISSUE TITLE
Make variable declarations open ended

### ISSUE THREAD

**Issue by clark-stevenson** [microsoft/TypeScript#819]
This used to be on codeplex and I cannot find a reference here. 

https://typescript.codeplex.com/workitem/917

The problem is that I have project.d.ts and lets say that it has a Point class with simple {x,y} properties. 

project-plugin-coolvector.d.ts might come along tomorrow, and that Plugin JS might add a z property to the existing Point class. 

If project-plugin-coolvector.d.ts attempts to export a Point class with a z property. You get a duplicate error.  I looked at the JQuery plugins example on DT but project.d.ts must contain classes, since Point has a constructor. 

 I see no way of being able to support the direction of the project in this instance.

**Comment by basarat** [comment]
# Proposal

If the following is declared: 

```ts
declare class Foo  {
    static bar: any;
    bas():any;
}
```

It can be extended using another declaration: 

```ts
// Amend Foo
declare class Foo  {
    static anotherStatic: any;
    anotherMember():any;
}
```

# Issues 
@danquirk 
>  It would be helpful to understand why you need to have open ended classes and where open ended interfaces are insufficient.

Really for a convinient way to model classes. Currently one needs to *rewrite* the original definition to make it extensible. This is not *simple* to explain to someone brand new to TypeScript.

```ts
declare var Foo : FooStatic;
interface FooStatic { // Static properties
    new (): Foo;
    bar: any;
}
interface Foo{ // Instance properties
    bas():any;
}

// Amend Foo 
interface FooStatic  {
   anotherStatic: any;
}
interface Foo{
    anotherMember():any;
}
```

**Comment by NathanWalker** [comment]
+1 this is very frustrating to **not** have at the moment. Please please, need this.

**Comment by Pro** [comment]
:+1:

**Comment by adidahiya** [comment]
#2957 looks like it will cover the use case for open-ended classes

**Comment by lucax88x** [comment]
need!!!

**Comment by windperson** [comment]
+1

**Comment by JoeDuncko** [comment]
Been hitting my head up against this for a while. If we want the community to be able to share and depend on each others' d.ts files, then we will need to be able to extend them.

**Comment by JoeDuncko** [comment]
Looks like this was fixed with https://github.com/Microsoft/TypeScript/pull/3516 . I'm trying it now.

**Comment by niemyjski** [comment]
+1

**Comment by ravishivt** [comment]
+1

**Comment by nin-jin** [comment]
+100500

**Comment by DomiR** [comment]
+1

**Comment by delphinus35** [comment]
+1

**Comment by englercj** [comment]
+1

**Comment by istvan89** [comment]
+1

**Comment by suppayami** [comment]
+1

**Comment by garthk** [comment]
Required for `hapi`, where plugins such as `inert` can add members to `IRouteConfiguration.handler`, as DefinitelyTyped would have it. To work around it, I'd have to do something like:

```
    const routeConfig: IRouteConfiguration = {
        path: '/',
        method: 'GET',
        handler: {
            // will cheat below to assign file:
        }
    };
    
    assign(routeConfig.handler, {
        file: {
            path: indexFile
        }
    });
    
    server.route(routeConfig);
```
Too much of this will maim TypeScript's advantage over JavaScript for this project.

**Comment by jocull** [comment]
Please consider adding this. Extending external JavaScript packages is very painful. Adding new methods to existing prototypes seems impossible. Extending them into new definitions is not practical, as you must then override them in every other case to become a new type. They quickly conflict and become incompatible and awkward to use. This is especially true of objects that "chain" and return themselves.

http://stackoverflow.com/questions/37505881/extending-typescript-declaration-files

**Comment by mhegazy** [comment]
@jocull this can be achieved using module augmentation today. see my response in  http://stackoverflow.com/questions/37505881/extending-typescript-declaration-files?answertab=votes#tab-top

**Comment by JeroenNelen** [comment]
+1

**Comment by mertdeg** [comment]
+1

**Comment by simonbengtsson** [comment]
Another library where this would be helpful is [jspdf](https://github.com/MrRio/jsPDF). It exports a class `let doc = new jsPDF()`. Third party plugins can be added and would be called like this `doc.anExternalPlugin()`. One example plugin is [jspdf-autotable](https://github.com/simonbengtsson/jsPDF-AutoTable).

**Comment by John0x** [comment]
+1

**Comment by mhegazy** [comment]
> This sadly keeps me from using Typescript with VueJs

can you elaborate?

**Comment by John0x** [comment]
@mhegazy With Vue 2 you can access Vue plugins by the Vue class instance. For example the cookie plugin would be Vue.cookie

Therefore I would have to extend the type declaration for the Vue class, which I can currently not do (as far as I can see) since we can't merge class declarations.

**Comment by mhegazy** [comment]
```ts
import * as Vue from "vue";

declare module "vue" {
    export var plugin: any; // my new plugin
}

Vue.plugin; // OK
new Vue(); // OK
```

**Comment by John0x** [comment]
@mhegazy thanks, I'll try that out, once I'm home :)
Does it work if you have two different declaration files too?

Original (index.d.ts and my own declaration.d.ts)?

**Comment by mhegazy** [comment]
Vue declaration comes from the declaration file coming from the Vue npm package. i do not know what is the other one.

**Comment by John0x** [comment]
@mhegazy yeah, that's the one I meant with index.d.ts)

**Comment by icewind** [comment]
This is sad... Most of modules I'm using(typeorm as example) using class instead of interface in their declaration. I can extend them easily in JS but it is impossible in TS(keep type info + autocomplete).

**Comment by mhegazy** [comment]
classes are extensible through interfaces (instance side), and through namespaces (static side). not sure why is variable declarations merging or not is relevant here.

**Comment by maxlk** [comment]
@mhegazy Class (instance) may be extended through interface only if it's declared in global namespace. It doesn't work when class is defined in some namespace:
```typescript
declare namespace ns {
    declare class Foo { }
    declare function getFoo(): Foo;
}

namespace ns {
    interface Foo {
        bar(): number;
    }
}

let foo: ns.Foo = ns.getFoo();
foo.bar(); // Error: Property 'bar' does not exist on type 'Foo'
```
(the same works when removing `ns` namespace)

**Comment by manast** [comment]
It would be quite interesting to hear from the maintainers of typescript the reason why this issue has not been addressed. Is it there a theoretical standpoint that prevents this for being implemented? Is it that you believe this issue is not important, or easy workarounds are available? Some other reason? Why is this issue still open after 3 years?

**Comment by jocull** [comment]
I have worked around this in particular cases by extended a local interface definition. This is *not* ideal, but it works like this:

```
interface ResponseExt extends express.Response {
    myNewProperty: string;
}
```

Then you'd just declare usage of `ResponseExt` explicitly anywhere you use it, such as a function argument. Again, not my favorite thing, but it's the only workaround I could come up with.

**Comment by manast** [comment]
@jocull yes, but what about methods? I would like to extend a class with new methods as in aspect oriented programming...

**Comment by jocull** [comment]
@manast Would you mind putting an example here for clarity?

**Comment by nolakara** [comment]
+1

**Comment by RyanCavanaugh** [comment]
The OP is extremely old here and references a link that doesn't work anymore. In the interim we've added external module augmentation, additional forms of permitted declaration merging, and removed some error cases that made declaration merging less ergonomic.

With secure JS runtimes being more common (thus no arbitrary mutation to built-ins) and modules exporting immutable surface area in modern (thus you only can augment exposed endpoints, which are already eligible for declaration merging) I don't think there's any necessary work to do in this area. Open to new suggestions on more targeted areas but it's not clear that "make variable declarations open-ended" is a tractable description or the right path forward.
