### ISSUE TITLE
TS 1.8 resource files do not seem localized

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript#8194]
As part of investigating https://github.com/Microsoft/TypeScript/pull/8193, I have noticed that all the resource files are not localized.
See `C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.8\ja\diagnosticmessages.generated.json`, no strings seem to be localized there.

**Comment by paulvanbrenk** [comment]
Are you seeing the same in the LS?

**Comment by mhegazy** [comment]
nope. just the compiler.

**Comment by paulvanbrenk** [comment]
In the nightlies and next VS release.
