### ISSUE TITLE
onerror events should match addEventListener('error') event types

### ISSUE THREAD

**Issue by martine** [Microsoft/TypeScript#8202]
(From TypeScript 1.8.2 lib.d.ts as included with VSCode.)

E.g. I think these should be using `ErrorEvent`, not `Event`.  (Perhaps it's intentional?)

```
interface MSBaseReader {
    onerror: (ev: Event) => any;
    addEventListener(type: "error", listener: (ev: ErrorEvent) => any, useCapture?: boolean): void;
```

```
interface IDBDatabase extends EventTarget {
    onerror: (ev: Event) => any;
    addEventListener(type: "error", listener: (ev: ErrorEvent) => any, useCapture?: boolean): void;
```

There are others.

**Comment by martine** [comment]
Confirmed this still exists in 906ce18b1b5c45374d2bb317f9c707e448c17b55 (20 April 2016).

`TS.fsx` in TSJS-lib-generator 59dc04933ddd77ffdc81c5005673dc50c7973e47 (18 Apr 2016) has this:
```
        Pt.printl
            "%saddEventListener(type: \"%s\", listener: (ev: %s) => any, useCapture?: boolean): void;"
            prefix eHandler.EventName actualEventType
```
which appears to be the generator case where it gets the event type correct, so it's not clear to me why it's still wrong for onerror.  There's some code in the generator about inheriting stuff from some parent  so maybe that's related.  I will take this to the other repo.

**Comment by mhegazy** [comment]
PRs welcomed.

**Comment by mhegazy** [comment]
Cross reference: https://github.com/Microsoft/TSJS-lib-generator/issues/94
