### ISSUE TITLE
[Transforms] Where should comment after "{" in getter be placed when emitting down-level

### ISSUE THREAD

**Issue by yuit** [Microsoft/TypeScript#8205]
**Original**
```ts
    get X() { // ok
        return '';
    }
```
**Expected**
```js
    get: function() { // ok
        return '';
    }
```
**Result**
```js
        get: // error
        function () {
            return '';
        }
```

numericIndexerConstrainsPropertyDeclarations.js

**Comment by sandersn** [comment]
This is likely a duplicate of #8209 but I'll leave it open in case it's not.

**Comment by yuit** [comment]
There are related and share similar fix though at slightly different location
