### ISSUE TITLE
help: a module generated during compilation isn't resolved

### ISSUE THREAD

**Issue by alexeagle** [Microsoft/TypeScript#8211]
TS 1.9.0.dev-20160409

Working on the Angular 2 template compiler. I create a ts.CompilerHost and a ts.Program, and use them to do some static analysis on decorators, and produce extra .ts files in a generated directory.
One file in the source directory imports from one of the generated files, which works because it has the `rootDirs` option in tsconfig pointing both to the source and generated directories.

The code is here:
https://github.com/alexeagle/angular/blob/compiler_cli/tools/compiler_cli/index.ts#L126

After running the program to do codegen, then I can successfully run tsc on the command line. So I know that the generated code produces a working program.

For reference, here is the `traceResolution` from a successful compilation in that separate tsc process:
```
======== Resolving module './templates' from '/Users/alexeagle/Projects/angular/tools/compiler_cli/test/bootstrap.ts'. ========
Explicitly specified module resolution kind: 'NodeJs'.
'rootDirs' option is set, using it to resolve relative module name './templates'
Checking if '/Users/alexeagle/Projects/angular/tools/compiler_cli/test/' is the longest matching prefix for '/Users/alexeagle/Projects/angular/tools/compiler_cli/test/templates' - 'true'.
Checking if '/Users/alexeagle/Projects/angular/dist/tools/compiler_cli/test/gen/' is the longest matching prefix for '/Users/alexeagle/Projects/angular/tools/compiler_cli/test/templates' - 'false'.
Longest matching prefix for '/Users/alexeagle/Projects/angular/tools/compiler_cli/test/templates' is '/Users/alexeagle/Projects/angular/tools/compiler_cli/test/'
Loading 'templates' from the root dir '/Users/alexeagle/Projects/angular/tools/compiler_cli/test/', candidate location '/Users/alexeagle/Projects/angular/tools/compiler_cli/test/templates'
Loading module as file / folder, candidate module location '/Users/alexeagle/Projects/angular/tools/compiler_cli/test/templates'.
File '/Users/alexeagle/Projects/angular/tools/compiler_cli/test/templates.ts' does not exist.
Trying other entries in 'rootDirs'
Loading 'templates' from the root dir '/Users/alexeagle/Projects/angular/dist/tools/compiler_cli/test/gen', candidate location '/Users/alexeagle/Projects/angular/dist/tools/compiler_cli/test/gen/templates'
Loading module as file / folder, candidate module location '/Users/alexeagle/Projects/angular/dist/tools/compiler_cli/test/gen/templates'.
File '/Users/alexeagle/Projects/angular/dist/tools/compiler_cli/test/gen/templates.ts' exist - use it as a name resolution result.
======== Module name './templates' was successfully resolved to '/Users/alexeagle/Projects/angular/dist/tools/compiler_cli/test/gen/templates.ts'. ========
```

But instead, I want to emit the program in the same process, which requires the generated files be resolved. The file `/Users/alexeagle/Projects/angular/dist/tools/compiler_cli/test/gen/templates.ts` does exist, but the module resolution claims it does not:
```
======== Resolving module './templates' from '/Users/alexeagle/Projects/angular/tools/compiler_cli/test/bootstrap.ts'. ========
Explicitly specified module resolution kind: 'NodeJs'.
'rootDirs' option is set, using it to resolve relative module name './templates'
Checking if 'tools/compiler_cli/test/' is the longest matching prefix for '/Users/alexeagle/Projects/angular/tools/compiler_cli/test/templates' - 'false'.
Checking if 'dist/tools/compiler_cli/test/gen/' is the longest matching prefix for '/Users/alexeagle/Projects/angular/tools/compiler_cli/test/templates' - 'false'.
Loading module as file / folder, candidate module location '/Users/alexeagle/Projects/angular/tools/compiler_cli/test/templates'.
File '/Users/alexeagle/Projects/angular/tools/compiler_cli/test/templates.ts' does not exist.
...
======== Module name './templates' was not resolved. ========
```

I was able to clear up some problems by creating a new CompilerHost and Program at this point, but somehow the module resolution fails. Is there some global state retained by my original pass through the source files that isn't cleared by creating brand-new Program and CompilerHost?

(cc @billti we discussed earlier how the codegen sources would be found by the compiler)

**Comment by mhegazy** [comment]
Just to make sure i understand, fist file `/Users/alexeagle/Projects/angular/dist/tools/compiler_cli/test/gen/templates.ts` does not exist, then you create a program, and you generate the file, then you create a new program and that can not find `/Users/alexeagle/Projects/angular/dist/tools/compiler_cli/test/gen/templates.ts` ?

how can i reproduce this locally?

**Comment by billti** [comment]
Is the relative pathing correct in the code? In the first successful case I see it *is* finding `test/gen/templates.ts`, in the second it's *not* finding `test/templates.ts` (note the `gen` path part is missing).

**Comment by alexeagle** [comment]
minimal repro: https://github.com/alexeagle/repro_genfiles_not_resolved

**Comment by alexeagle** [comment]
@vladima helped me find the problem: `basePath` must be converted to absolute path

thanks!
