### ISSUE TITLE
Debugger partially broke after installing update 2 to VS2015

### ISSUE THREAD

**Issue by henrify** [Microsoft/TypeScript#8214]
After installing update 2 to Visual Studio 2015 Community Edition, TypeScript debugging broke partially.

When brakepoint is set in TS source and debugger started, IE (v11) launches and the breakpoint is hit / execution suspended as expected, BUT:

1. Instead of opening the TS source file containing the breakpoint, a copy of the source is opened with its tab on the right hand side of the editor tabs bar, and marked with [dynamic]. Editing of the [dynamic] version of the source does not reflect the changes to the real source.

2. Hovering cursor over variables does NOT display the normal popup/tooltip showing the variable's current value.

Stepping through the [dynamic] version of the source file does work correctly, and 'locals' window does display the local variables correctly, so it seems that Update 2 broke something about how the debugger handles sourcemaps?

This is a multi project solution with about 10 projects, build with browserify. The format of the sourcemap is absolute paths + inlined sources.

The exact same source and sourcemap continues to work correctly when debugging in VS2013 Ultimate with TS 1.8.5.

After detecting this issue I uninstalled VS2015 and did clean install of 'VS2015 with Update 2', but the problem persists. Trying to uninstall Update 2 from VS2015 resulted in VS not even starting, same after running windows recovery to a checkpoint before the evil Update 2.

**Comment by billti** [comment]
@paulvanbrenk can you comment on this? Sounds like the inline source related topic we've been discussing internally. I didn't think this changed with Update2 however.

**Comment by paulvanbrenk** [comment]
@henrify what kind of project is this exactly, ASP.NET, Cordova, something else? Which version of TypeScript did this work correctly with? And can you share a small sample project that shows the issue? 

Honestly I'm surprised this works in VS2013, since we haven't made any changes in the handling of sourcemaps in a while, and definitely don't support inline sources there.

**Comment by mhegazy** [comment]
@henrify can you share the project? we would be happy to sign any NDAs to get access to the sources. also feel free to send us directly a sample project the demonstrates the issue on mhegazy `at` microsoft `dot` com

**Comment by henrify** [comment]
I was able to simplify the repro to point where unmodified app.ts straight from "HTML Application with TypeScript" project template brakes the debugger in VS2015.2, but works fine in VS2013.5.

VS2013 debugger probably gets the sources using the absolute source paths from sourcemap, while VS2015 starting from Update 2 either gives priority to the inlined sources, or then fails to resolve the absolute paths and falls back to the inlined sources?

Please find the repro attached.

The source has been simplified to single file, but the build system has been left intact. The relevant browserify code is from line 240 of file gulpcommon.js.

To build:
- run 'npm install' on the solution root folder
- then 'npm install' in 'some-project' folder
- then 'gulp dev-build' in 'some-project' folder
- the output bundle will be in 'some-project/build/dev/' folder, and index.html has been already modified to load the bundle from there.

[VS2015DebuggerTest.zip](https://github.com/Microsoft/TypeScript/files/229327/VS2015DebuggerTest.zip)

**Comment by mhegazy** [comment]
@sheetalkamat can you take a look?

**Comment by henrify** [comment]
Just small additional note. I build a new Windows 8.1 VM with VS 2015 from scratch, and the bug reproes 100% in the virgin environment.

**Comment by Tamayi** [comment]
I am experiencing the same issues after upgrade to VS2015 Update 2. The debugging has broken. I cannot hover over variables that I could hover over before I applied the update this weekend. What's worse is even the watch window is complaining (Screenshot 2). My project is an ASP.NET 5 MVC 6 EF 7 project. The screenshots are from a ASP.NET Class Library project. I get an exception when I set a conditional breakpoint too (Screenshot 1).

Screenshot 1
![capture](https://cloud.githubusercontent.com/assets/6397813/14793333/79c6fd22-0b16-11e6-912e-865b480c0573.PNG)
Screenshot 2
![capture2](https://cloud.githubusercontent.com/assets/6397813/14793335/79ca7de4-0b16-11e6-8e8d-41cce96a8bf5.PNG)

**Comment by Tamayi** [comment]
I have just seen reference to a patch for this issue: http://go.microsoft.com/fwlink/?LinkID=785969

**Comment by mhegazy** [comment]
@Tamayi this is ASP.net debugging, and is not the Typescript debugger.

**Comment by henrify** [comment]
@sheetalkamat @mhegazy Continuing on the language theme:

Actually I only assumed that this would be strictly TypeScript related, because I found it hard to believe that Microsoft would have broken JS debugger entirely in general availability release, but I haven't verified that at all.

Just mentioning to make sure that I don't send you off to a wrong path of investigation.

**Comment by henrify** [comment]
Seeing that this issue still has "Needs more info" tag.. Do you need further additional info from me? Full repro solution is attached, and I wasn't planning to provide any more info, just waiting for your glorious resolution.

**Comment by sheetalkamat** [comment]
@henrify , I cant remove the tag but I have the information I need. 

I looked into this and found that there  are two issues going on here.

The source map presented has text for ```app.ts``` which starts with BOM. We aren't handling this correctly and use the whole contents as text of the file resulting in debugger thinking the disk file whose text starts with ```class Greeter``` but the document that we are trying to load has ```BOM followed by class Greeeter``` being differing in contents and hence the dynamic view. I am looking into handling this scenario and will let you know when I complete the changes for the same.

I also looked into issue with hovering over not showing evaluation result and my guess is it might be something in Roslyn language service and I am talking to the team to see what's going on there. I will keep you updated on it as well.

**Comment by sheetalkamat** [comment]
@henrify  Actually looking deeper into the source map with BOM we have come to conclusion that its a bug in build process you have. The source contents field shouldn't be containing BOM since they specify contents of the file and are suppose to be always UTF8 according to sourcemap spec. 

Still looking into why you aren't able to see evaluation data tip in the dynamic file.

**Comment by henrify** [comment]
This is just so horrible end-user experience.

To get basic build and debugging to work, we needed to have over 1000 lines of fragile build scripts, tying together no less than TWENTY ONE gulp plugins, mostly badly documented and buggy as hell, maintained by private people, when they have time.

Then you release Update 2 of Visual Studio 2015. The build / debugging brakes, and now it is us 'having bug in our build system'.

I have no idea what you mean that the 'sourcesContent' shouldn't contain BOM? As far as I can see the 'sourcesContent' property just has the sources as expected, and then we list the source files separately in 'sources'?

I'm not saying that you are wrong or that there isn't some 'bug in our build system', but in practice it is absurdly difficult to get TypeScript to transpile multiproject solution to bundles that can be debugged across different Browsers and IDEs, and you changing Update 2 to be stricter about acceptable sourcemap format made this now even more difficult.

Now we need to waste yet more time finding another fragile combination of sourcemap parameters that works with all browsers and IDEs, until somebody else decides to change something and we get another "bug in our build system".

**Comment by sheetalkamat** [comment]
@henrify The source contents field for the ```app.ts`` in the sourcemap contains the text has   in the generated map contain the string that starts with BOM character which is seen as below at the start of the source map in notepad++
```"ï»¿class Greeter {\r\n    element: HTMLElement;\r\n    span: HTMLElement;\r\n    timer```

It is either the bundler or sourcemap manipulator which consumes the sourcemaps generated by typescript compiler that is causing this.

**Comment by henrify** [comment]
Thank you for the explanation and your help.

This is a perfect example what I meant when I said that browserify-based build system requires ridiculous amount of plugins, and many of them are buggy us hell, resulting in extremely fragile builds and wasted time. This is about the tenth time that we are experiencing weird issues with browserify plugins.

Browserify based build is clearly not realistic alternative for us, and we'll be replacing it with something else ASAP. Feel free to close this issue.
