### ISSUE TITLE
Can someone port this to the PHP?

### ISSUE THREAD

**Issue by pedrourday** [Microsoft/TypeScript#8230]
Hello, This is not an issue but a suggestion to make. Can someone port this compiler to the PHP language? PHP language still remains the most widely used in web servers. I would appreciate this very much. Best regards.

**Comment by mhegazy** [comment]
No. The compiler is written in TypeScript.

**Comment by sandersn** [comment]
You might be able to use the [V8js extension](http://php.net/manual/en/book.v8js.php) to run the compiler.

**Comment by pedrourday** [comment]
ok! thank you sandersn. Another question. If i wish, can i make a compiler, on my own, written in PHP? Does the licence allow this?

**Comment by mhegazy** [comment]
The language and the tools are all open source. you can find the language spec at: https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md

**Comment by basarat** [comment]
TypeScript is a Typed superset of JavaScript. 

In a similar vein [Hack](http://hacklang.org/) is a typed superset of PHP by facebook that you might find interesting :rose:
