### ISSUE TITLE
Carriage return interpreted as newline despite LF newLine option

### ISSUE THREAD

**Issue by myitcv** [Microsoft/TypeScript#8239]
```
$ tsc --version
Version 1.9.0-dev.20160419
$ cat app/tsconfig.json
{
  "compilerOptions": {
    "declaration": false,
    "jsx": "react",
    "module": "system",
    "newLine": "LF",
    "noEmitOnError": true,
    "noImplicitAny": true,
    "noImplicitReturns": true,
    "noLib": true,
    "outDir": "../dist/js/app/",
    "removeComments": false,
    "rootDir": ".",
    "sourceMap": true,
    "target": "es5"
  }
}
```

## Actual behaviour

```bash
$ echo $BASH_VERSION
4.3.42(1)-release
$ echo -e '// \u000D ]]\nconsole.log("test");' > test.ts
$ tsc
test.ts(2,2): error TS1128: Declaration or statement expected.
test.ts(2,3): error TS1128: Declaration or statement expected.
```

## Expected behaviour

No errors from `tsc`.

**Comment by DanielRosenwasser** [comment]
`newLine` specifies the newlines used at *emit* time, it has nothing to do with how input is interpreted. Frankly Is there any reason you're trying to change the lexical meaning of a carriage return?

**Comment by myitcv** [comment]
> `newLine` specifies the newlines used at emit time

Thanks for clarifying.

> Is there any reason you're trying to change the lexical meaning of a carriage return

Not trying to change the lexical meaning; I just happened to have a Neovim macro definition included as a comment in my code. The macro definition included a carriage return in part of its definition. 

> how input is interpreted

I couldn't find anything in the spec on this, hence the question. Given the context for the error it's clearly low priority, so more for completeness than anything.

Is a line separator therefore defined as either `U+000A`, `U+000D` or `U+000DU+000A`?
