### ISSUE TITLE
can you provide a release package download url

### ISSUE THREAD

**Issue by uliian** [Microsoft/TypeScript#8247]
My company has limited network.So ,I can't download the package from the NPM,can you provide a release package download url?

**Comment by mhegazy** [comment]
If you are suing windows, the package is avialable at https://www.microsoft.com/en-us/download/details.aspx?id=48593 and thorugh Nuget: https://www.nuget.org/packages/Microsoft.TypeScript.Compiler/

for npm package contents, consider using `git clone --depth 1`

**Comment by zhengbli** [comment]
You mean using instead of suing? :wink:

**Comment by mhegazy** [comment]
:D thanks, updated.
