### ISSUE TITLE
TSLint: Change value of the semicolon option from boolean to array

### ISSUE THREAD

**Issue by YuichiNukiyama** [Microsoft/TypeScript#8248]
**TypeScript Version:** 

nightly (1.9.0-dev.20160422)

**Current code in tslint.json:**

```json
{
    "rules": {
        "semicolon": true
     }
}
```

**Desirable code:**
```json
{
    "rules": {
        "semicolon": [true,
            "always"
        ]
     }
}
```

**Description:** 
According to the [TSLint spec](http://palantir.github.io/tslint/rules/semicolon/) and their [json scheme](http://json.schemastore.org/tslint), value of semicolon option should be array. So, When I use [vscode-tslint](https://github.com/Microsoft/vscode-tslint), vscode show error message. this is noizy.
![semicolonoption](https://cloud.githubusercontent.com/assets/9623009/14736743/6e549c02-08b3-11e6-9bab-3564fea2b0aa.png)

**Comment by RyanCavanaugh** [comment]
Please log this at the https://github.com/palantir/tslint/ repo

**Comment by YuichiNukiyama** [comment]
My explanation it was difficult to understand. I said about https://github.com/Microsoft/TypeScript/blob/master/tslint.json#L19
