### ISSUE TITLE
tsc -w get compiles its own output again

### ISSUE THREAD

**Issue by jrieken** [Microsoft/TypeScript#8249]
**TypeScript Version:** 

1.8.10

**Code**

```json
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "ES6",
        "noLib": true,
        "outDir": "out"
    },
    "exclude": [
        "node_modules"
    ]
}
```

Have a file `extension.js` and run once `tsc -p jsconfig.json` which gives you a file `out/extension.js`. Start tsc in watch mode, make a change to `extension.js`

**Expected behavior:**

The compiler should auto-magically exclude the `outDir`.

**Actual behavior:** 

It recurses forever which make the terminal print funny patterns
![screen shot 2016-04-22 at 11 13 40](https://cloud.githubusercontent.com/assets/1794099/14737223/498e6890-087b-11e6-8272-43ed61e3bd12.png)

**Comment by basarat** [comment]
> The compiler should auto-magically exclude the outDir.

QQ if someone already knows: What is the current behavior of 

```
// foo.ts
console.log('hello');
```
With `allowJs` + no outDir. Is `foo.js` automagically excluded?

**Comment by mhegazy** [comment]
outDir is excluded by default if you do not specify `"exclude"` (`node_modules` behave similarly). the rational was, if we always include it, there is no way for you to disable this. with the current approach, you can not specify `"exclude"`, and get the automatic behavior or specify one, and disable the automatic behavior.

**Comment by jrieken** [comment]
@mhegazy So when exactly is the endless recursion a desired behaviour?

**Comment by mhegazy** [comment]
When you put it this way, the answer is never :)

the issue was, if we always added, some one will have a request to undo that, and there will be no way of doing this, unless we add a new flag --noImplicitOutDirExclusion (which is something we would rather not do). that is the same argument for node_modules as well.

**Comment by jrieken** [comment]
I understand that and I think it's a fair decision, tho I think it would be better if the compiler eventually stops. Like not be triggered by a file it emitted in the previous round

**Comment by mhegazy** [comment]
One thing we can do, is include it by default, and then let users override that using the include property (from https://github.com/Microsoft/TypeScript/pull/5980)

**Comment by basarat** [comment]
I've gone with : `outDir` is always excluded for [alm](http://alm.tools/)

Feeding the the output of the compiler back to the input of the *same* compiler seems wrong. And `outDir` is I guess the recommended way to support `allowJS` https://github.com/alm-tools/alm/issues/75 :rose:
