### ISSUE TITLE
Lose string union type through interface

### ISSUE THREAD

**Issue by danvk** [Microsoft/TypeScript#8254]
When I define the `props` of a `React.StatelessComponent` to be a union of strings, TS understands it:
![union props](https://cloud.githubusercontent.com/assets/98301/14754050/e8a78166-08a6-11e6-8f6d-8c9fddaacbd9.png)

However, if I attempt to pull this out into an `interface`, it resolves to `any`:
![interface props](https://cloud.githubusercontent.com/assets/98301/14754053/ebe39c7a-08a6-11e6-81e4-6d9573ca2d5d.png)

I also tried defining `Props` as an `interface` but got the same results.

I would have expected these to do the same thing.

**TypeScript Version:** 

1.8.9

**Code**

```ts
type Props = {
  page: ('od' | 'via' | 'hourly' | 'parking')
};

// const Navigation: React.StatelessComponent<{Props}> = (props) => {
const Navigation: React.StatelessComponent<{page: ('od' | 'via' | 'hourly' | 'parking')}> = (props) => {    
  const navItem = (key: string, message: string, url: string) => {
```

**Expected behavior:**

(see above)

**Actual behavior:** 

(see above)

**Comment by Arnavion** [comment]
I think you want `React.StatelessComponent<Props>` not `React.StatelessComponent<{ Props }>`

**Comment by DanielRosenwasser** [comment]
Thanks @Arnavion!

**Comment by danvk** [comment]
Doh! Thanks for the quick response :)
