### ISSUE TITLE
Tweak UMD global semantics

### ISSUE THREAD

**Issue by RyanCavanaugh** [Microsoft/TypeScript#8255]
Two good suggestions from @ahejlsberg 

* The globalness of a UMD *disappears* when the file is `import`ed, rather than *appearing* when `reference`d
* When the global is disappeared, replace it with a "poisoned" symbol that is illegal to use. e.g.

```ts
// file1.ts
import * as $ from "jquery";

// file2.ts
// Error, $ must be imported from "jquery"
$('foo').bar();
```

**Comment by basarat** [comment]
nice :rose: /cc @blakeembrey
