### ISSUE TITLE
`Promise.all` array types incorrect in ES6

### ISSUE THREAD

**Issue by blakeembrey** [Microsoft/TypeScript#8259]
**TypeScript Version:** 

1.8.10 (appears to be fixed in `1.9.0-dev.20160422` by removal of the final `Promise.all` fall through type)

**Code**

```ts
const foo: string[] = []

const value = Promise.all(foo.map(async (id) => {
  return Promise.resolve(id)
}))

function acceptsPromises (p: Promise<string[]>) {}

acceptsPromises(value)
```

```json
{
  "compilerOptions": {
    "target": "es6"
  }
}
```

**Expected behavior:**

`Promise.all<TAll>` should unwrap the array of promises to `Promise<string[]>`, instead the structures are incompatible under ES6 and you get `Promise<Promise<string>[]>`.

**Actual behavior:** 

```
index.ts(9,17): error TS2345: Argument of type 'Promise<Promise<string>[]>' is not assignable to parameter of type 'Promise<string[]>'.
  Type 'Promise<string>[]' is not assignable to type 'string[]'.
    Type 'Promise<string>' is not assignable to type 'string'.
```

**Comment by vladima** [comment]
looks like  dupe of https://github.com/Microsoft/TypeScript/issues/7566

**Comment by blakeembrey** [comment]
@vladima Thanks for that, I swear I tried to find it - using the wrong keywords I suppose. Cheers!
