### ISSUE TITLE
Class constructor type from instance

### ISSUE THREAD

**Issue by Mosho1** [Microsoft/TypeScript#8261]
**TypeScript Version:** 

1.8.10

**Code**

```ts
    class ClassWithStaticProp {
        static prop = {};
    }

    const instance = new ClassWithStaticProp();

    // instance.constructor has no type information

```

**Expected behavior:**

`instance.constructor` should have the same type as the `ClassWithStaticProp` constructor function.

**Actual behavior:** 

`instance.constructor` has no type information

**Comment by Arnavion** [comment]
Duplicate of #3841
