### ISSUE TITLE
Async arrow functions

### ISSUE THREAD

**Issue by 2426021684** [Microsoft/TypeScript#8262]
**TypeScript Version:** 

Typescript playground

**Code**

```ts
const x = async i => await someOtherFunction(i)

```

**Expected behavior:**
It works
**Actual behavior:** 
Cannot find name async

**Comment by Arnavion** [comment]
The parameter needs to be in parens.

```typescript
const x = async (i) => await someOtherFunction(i);
```

**Comment by bterlson** [comment]
Confirming that the parens should be optional per spec.
