### ISSUE TITLE
Typescript error TS2304: Cannot find name 'd3'. But App was able to run d3 when execute in browser.

### ISSUE THREAD

**Issue by trainrail** [Microsoft/TypeScript#8264]
**TypeScript Version:** 

1.8.7

**Code**

https://gist.github.com/trainrail/fc5871bb6fc1ebb422e4720b3e3e4264

Quick Description:

Here is a working version of typescript with angular2 and d3 in [plunker](https://plnkr.co/edit/hYuFcje1UVPi1XRmRD3e?p=preview)

Here is also a working version of typescript with angular2 and d3 in my [local](https://gist.github.com/trainrail/fc5871bb6fc1ebb422e4720b3e3e4264) , however even though the code is working, I am running into compiler error

    error TS2304: Cannot find name 'd3'.

**Expected behavior:**

No compiler error

**Actual behavior:** 

Compiler error 

        error TS2304: Cannot find name 'd3'.

even though browser could clearly render the d3 code.

**Comment by basarat** [comment]
TypeScript doesn't know about *ambient* types that aren't declared. You need to get `d3.d.ts`. 

More : https://basarat.gitbooks.io/typescript/content/docs/types/migrating.html :rose:

**Comment by achuthak1** [comment]
if anybody is still searching solution for this then its too damn simple.

just go to your typing.d.ts under your project (it can be found after index.html) (im using angular 5 and visual studio code)
and at the last line add "**declare var d3: any;**"

now it should work fine
