### ISSUE TITLE
[tsserver] Support for "Search Types"

### ISSUE THREAD

**Issue by angelozerr** [Microsoft/TypeScript#8265]
It should be very cool if tsserver could provide a new command "findAllTypes" which gives the capability to search types coming from ts files of the project.

To explain more my idea, I would like to implement inside typescript.java (Eclipse plugin for TypeScript) the same feature than we have with Java inside Eclipse.

See the following screenshot:

![javaopentype](https://cloud.githubusercontent.com/assets/1932211/14763607/c88decea-099a-11e6-9556-8ae409cc998e.png)

In this sample we have several classes MyServiceA,  MyServiceB and an inner class MyInnerServiceA in a Java project. We can open a dialog "Open Type" to search any types in the Java Project with a filter. It's very helpful when you wish to go at a definition of class but you don't know which files defines the class (in Java world, Java class name follow the same name than the file, but in TypeScript world, you can defines any classes in any files).

**Comment by basarat** [comment]
I used the language service modifying the *get navigation items* API endpoint to achieve a similar  "Symbol Search" in alm tools : https://basarat.gitbooks.io/alm/content/features/omni-search.html#symbol-search 

![](https://raw.githubusercontent.com/alm-tools/alm-tools.github.io/master/screens/symbolSearch.gif)

**Comment by angelozerr** [comment]
@basoarat very cool integration about search types. Hope tsserver will provide this command too.

**Comment by drake7707** [comment]
I use the `getNavigationBarItems()` method to build a treeview which I can filter (http://drake7707.github.io/Typescript-Editor/). Though this probably becomes a hassle (and not very efficient) if you have to call it for each ts file.

**Comment by angelozerr** [comment]
@drake7707 in my case I use too "navbar" tsserver command to fill outline. But it's only for a given file. My idea is to search types from the whole ts files of the project.

I think searching types from the whole ts files of the project can be interested for other issues like https://github.com/Microsoft/TypeScript/issues/7849

**Comment by mhegazy** [comment]
use NavigateTo instead of navbar (command: "navto"). this gives you all the names given a prefix. see https://github.com/Microsoft/TypeScript/blob/master/src/server/protocol.d.ts#L1066.

you can then filter on the kind, and keep the types, and remove the variables if you so choose.

**Comment by angelozerr** [comment]
@mhegcazy many thanks for your suggestion. 

I will try "navto" command, but if I understand your suggestion it means that it searchs in the whole of ts files of the project?

But I'm a little afraid with performance if I cannot filter on tsserver side type, because with large project, there are a lot of variables, etc although in my case I need just type.

**Comment by mhegazy** [comment]
> But I'm a little afraid with performance if I cannot filter on tsserver side type, because with large project, there are a lot of variables, etc although in my case I need just type.

The server does filtering on the production side limiting to the `searchValue`. do not expect you have that many entries with the same name but different kinds.

**Comment by angelozerr** [comment]
why do you close this issue?

I think a robust search types with complex criteria should be very usefull:

 * if I type '*' I would like to have the whole types.
 * I would like to search types which implement some interfaces to support https://github.com/Microsoft/TypeScript/issues/8268
 * support auto import https://github.com/Microsoft/TypeScript/issues/7849 and we could have an other service typedetail (like completionDetails) which gives the import to add.

But perhaps you find those features are too specific so we could do that in the future with a plugin once https://github.com/Microsoft/TypeScript/issues/6508 will be implemented.

**Comment by mhegazy** [comment]
> if I type '*' I would like to have the whole types.

we used to do this in the past. the size of the result was large that it caused perf issues both on th eserver and on the client serializing the result.

> I would like to search types which implement some interfaces to support #8268

And #8268 is tracking it. it is marked as `suggestion` and is open. do not think we need two issues for that. 
If you would like to generalize that proposal, feel free to update #8268

> support auto import #7849 and we could have an other service typedetail (like completionDetails) which gives the import to add.

This is a quick fix, not a search. we should be looking into these in TS 2.1

**Comment by angelozerr** [comment]
Many Thanks @mhegazy for having taken time to give me your great answer! Very exciting with TS 2.1 :)
