### ISSUE TITLE
[tsserver] Support for "Search Hierarchy Type"

### ISSUE THREAD

**Issue by angelozerr** [Microsoft/TypeScript#8268]
It should be cool if tsserver could provide a new command "findHierarchyType" to retrieve list of types  which implement an interface.

In other words I would like to provide te same feature than Eclipse plugins for Java inside typescript.java: open a popup which displays list of types (MyServiceA, MyServiceB etc) which implement an interface (IService):

![typehierarchy](https://cloud.githubusercontent.com/assets/1932211/14764578/3b90dc6c-09bd-11e6-83ba-722ffad94e11.png)

**Comment by DanielRosenwasser** [comment]
Are you asking about something like an "implement interface" command?

**Comment by sandersn** [comment]
Sounds more like a restricted "find all references" that only shows references for `I` that have `implements I`. I remember using this with C# too, and it's quite useful.

**Comment by DanielRosenwasser** [comment]
So find all implementations?

**Comment by angelozerr** [comment]
> So find all implementations?

Exactly!

**Comment by angelozerr** [comment]
It seems that https://github.com/Microsoft/TypeScript/pull/10482 should fix this issue?

**Comment by micaelgallego** [comment]
Maybe it can be implemented calling to this command several times (once per node in the hierarchy tree). But maybe it is too slow

**Comment by RyanCavanaugh** [comment]
Taking #10482 as the definitive fix
