### ISSUE TITLE
Error on flow analysis on outer scope variables

### ISSUE THREAD

**Issue by tinganho** [Microsoft/TypeScript#8269]
**TypeScript Version:** 

nightly (1.9.0-dev.20160217)

**Code**

```ts
let something: string | null;
function test(): string {
    something = '';
    return something; // error it can return null
}

```

**Expected behavior:**
Should not error.

**Actual behavior:** 
It errors. The return statements says it can return null.

**Comment by mquandalle** [comment]
Did you enable the `strictNullChecks` option? I believe that without it, types are still nullable by default and so your function can return `null` or `undefined`.

**Comment by basarat** [comment]
Works fine in alm *with* or *without* `strictNullChecks`. Demo: 

![memo](https://cloud.githubusercontent.com/assets/874898/14766837/2dfd54b0-0a5b-11e6-87a9-d3956da8f416.gif)

:rose:

**Comment by tinganho** [comment]
@mquandalle yes I enabled it.

**Comment by ahejlsberg** [comment]
@tinganho Looks like you have an old nightly build (from Feb 17). You example works fine with the latest nightly.

**Comment by tinganho** [comment]
Oh sorry, didn't configure my IDE correctly. You are correct it works fine now.

**Comment by tinganho** [comment]
Was a little bit confused. It actually didn't work.

```
$ tsc --strictNullChecks test.ts
test.ts(4,12): error TS2322: Type 'string | null' is not assignable to type 'string'.
  Type 'null' is not assignable to type 'string'.

tinganho at Tiens-MacBook-Pro in ~/Development/Mount on master [!?]
$ tsc --version
Version 1.9.0-dev.20160423

tinganho at Tiens-MacBook-Pro in ~/Development/Mount on master [!?]
$ cat test.ts
let something: string | null;
function test(): string {
    something = '';
    return something; // error it can return null
}
```

**Comment by RyanCavanaugh** [comment]
Compiles without error for me on `master`

**Comment by tinganho** [comment]
This issue was related to the issue with the nightly build not being updated.
