### ISSUE TITLE
`strictNullChecks` errors in `typescript.d.ts`

### ISSUE THREAD

**Issue by basarat** [Microsoft/TypeScript#8271]
If I enable `strictNullChecks` a bunch of stuff in `ntypescript.d.ts` highlights for me in [alm tools](http://alm.tools/) (in addition to the intentional one in `bas.tsx`) 

> I am testing with `ntypescript.d.ts`. Pretty sure `typescript.d.ts` would be the same as Its just output from the compiler.

![image](https://cloud.githubusercontent.com/assets/874898/14766876/f8c3d96c-0a5b-11e6-9eb6-767af5b23b97.png)

> Note: this is showing up for me because ntypescript is loaded as its a part of a `node_module` automatic resolution for the folder I am testing in. I would suspect it to be an error with `tsc` on the console as well ... but somehow its not loading `ntypescript.d.ts` < but that's a seperate possibly future concern :rose:

**Comment by basarat** [comment]
Verified. Thanks! :rose:
<img width="1417" alt="screen shot 2016-04-26 at 8 42 46 am" src="https://cloud.githubusercontent.com/assets/874898/14801226/17309d60-0b8b-11e6-995b-a16923907776.png">

**Comment by mhegazy** [comment]
thanks, i have also added tests to make sure we catch these before checking in.
