### ISSUE TITLE
The error "Object is possibly null or undefined" is ambiguous.

### ISSUE THREAD

**Issue by tinganho** [microsoft/TypeScript#8274]
I have problem distinguishing if the accessor `options` or `headers` or both is possibly undefined or null below.

<img width="415" alt="screen shot 2016-04-24 at 19 22 31" src="https://cloud.githubusercontent.com/assets/1324476/14767168/fc994d88-0a51-11e6-9dc9-a9d140643381.png">

Can it instead of using the text `Object is possibly...` output the accessor expression `'this.option.headers' is possibly ...`?

**Comment by mhegazy** [comment]
we can not write the full expression, this could be a function call, a function expression, a whole program .. the error span seems correct to me.

@sandersn and @DanielRosenwasser any ideas on making this error message better?

**Comment by DanielRosenwasser** [comment]
You could have a more helpful error message when the possibly null value is an identifier or property/element access, For more complex expressions, just default to the other one.

An alternative is to check for each of the possible forms and report the specifics.

* `Cannot access property '{0}' on a possibly null or undefined value.`
* `Cannot access element on a possibly null or undefined value.`
* `Cannot call a possibly null or undefined value.`
* `Cannot construct a possibly null or undefined value.`

**Comment by sandersn** [comment]
If you change the code so that it's `options` that could be undefined or null, then doesn't the error span shrink to `this.options`? That seems like it distinguishes well enough between `this.options` and `this.options.headers` as the source of the message.

**Comment by tinganho** [comment]
Though it is not every time I just look at my IDE. I some time look at the output of my terminal.

**Comment by DanielRosenwasser** [comment]
@tinganho the `--pretty` compiler option should give some context on what the error span refers to.

I generally agree with @sandersn though, I'd like to see if this is a problem a lot of people run into.

**Comment by gertcuykens** [comment]
Not sure if this is related but I have no idea why I get the same error when I try 

```js
    const l = document.querySelector('link[rel="import"]') as HTMLLinkElement                                                                    
    if (l == null || l == undefined) return;
    const t = l.import.querySelector('template')
```

![image](https://cloud.githubusercontent.com/assets/863731/19128234/cf1596a6-8b42-11e6-9aad-8cf5d0d40ec6.png)

**Comment by gertcuykens** [comment]
Doh! Sorry I needed to do `if (l.import == null ) return;`

**Comment by fcrespo82** [comment]
Is this issue still open? Can I go for it? Any pointers what file should I go for this fix?
