### ISSUE TITLE
[T] tuple type information is lost as T[]

### ISSUE THREAD

**Issue by nathancahill** [Microsoft/TypeScript#8276]
**TypeScript Version:** 

nightly (1.9.0-dev.20160213)

**Code**

```ts
interface Geo {
    latlng: [number, number]  // tuple
}

function world(geo: Geo) {}

world({ latlng: [35, -112] });  // works fine

let coordinates = { latlng: [35, -112] };
world(coordinates);  // errors

let coordinatesTyped: Geo = { latlng: [35, -112] };
world(coordinatesTyped);  // works fine
```

**Expected behavior:**

Compile without errors.

**Actual behavior:** 

Error, `[T]` tuple type information is lost as `T[]`:

> Type 'number[]' is not assignable to type '[number, number]'.

**Comment by aluanhaddad** [comment]
The type information is not being lost. 
In the line
```TypeScript
let coordinates = { latlng: [35, -112] };
```
the inferred type of the object literal is
```TypeScript
{ latlng: [35, -112]; };
```
not ```Geo```.
It is unrelated to the function call itself. When you define the object literal directly in the call as in
```TypeScript
world({ latlng: [35, -112] });
```
it is target typed based on the function's parameter type to that more specific type.

While it is not entirely clear what the type of ```coordinates``` should be, note that
```TypeScript
var t = [1, 2]; // t has type number[]
var [x, y] = [1, 2]; // x and y are of type number, there is no name for the tuple itself.
```
At any rate, neither the interface ```Geo``` nor the function ```world``` are taking part in type inference. They are red herrings.

**Comment by nathancahill** [comment]
My point is that `[35, -112]` could be `number[]` or `[number, number]`. The compiler is deciding that it's `number[]` and throwing an error when is used as `[number, number]`.

**Comment by aluanhaddad** [comment]
Which is why I said it's not entirely clear what the type should be. Either one will be incompatible with certain signatures or assignments.

**Comment by aluanhaddad** [comment]
I suppose it could be
```TypeScript
number[] & [number, number];
```
But that could get out of hand pretty quickly

**Comment by ahejlsberg** [comment]
This is by design. An array literal is considered a tuple only if it is *contextually typed* by a tuple type; for example, if it is assigned to a variable of a tuple type or passed as an argument for a parameter of a tuple type. In cases where the context provides no clear indication that it should be a tuple, we treat it as an array. It's not clear what else we would do, but we're certainly open to suggestions.

**Comment by aluanhaddad** [comment]
I think the current behavior matches the syntactic intuition that follows from the respective declaration forms for tuples and arrays.

**Comment by nathancahill** [comment]
Ok, thanks guys!
