### ISSUE TITLE
setting allowJS in jsconfig.json file breaks projectInfo

### ISSUE THREAD

**Issue by jrieken** [Microsoft/TypeScript#8279]
**TypeScript Version:** 

1.8.9

This is from https://github.com/Microsoft/vscode/issues/5699 but the essence is that setting `allowJS: true` in jsconfig.json breaks the `projectInfo` call in tsserver.

Steps and sources to repo can be found in https://github.com/Microsoft/vscode/issues/5699.

**Comment by mhegazy** [comment]
@zhengbli can you take a look.

**Comment by zhengbli** [comment]
This is because the correct name of this flag should be `allowJs`, the last `s` is a lower case letter. 
We do should give the user notices for config file errors. I didn't catch the difference here myself the first time.

**Comment by zhengbli** [comment]
Opened #8285 to track the progress in reporting config file in general. Closing this one.
