### ISSUE TITLE
Suggestion - nested imports

### ISSUE THREAD

**Issue by ca0v** [Microsoft/TypeScript#8283]
In my latest project I decided to write all my test code under a common "test" folder.  As a consequence I've been writing a lot of terrible import references:

```
import DojoUtil = require("../../../../../../tools/core/DojoUtil");
import common = require("../../../../../../tools/core/common");
import AttributeInspector = require("../../../../../../tools/annotations/AttributeInspector");
import MonikerDropDown = require("../../../../../../tools/annotations/AttributeInspector/MonikerDropDown");
```

It occurred to me that a "using" like syntax for imports would reduce my pain by setting the import context (a temporary baseUrl):

```
import "../../../../../../tools" {
	DojoUtil = require("./core/DojoUtil");
	common = require("./core/common");	
	AttributeInspector = require("./annotations/AttributeInspector");
	MonikerDropDown = require("./annotations/AttributeInspector/MonikerDropDown");
}
```

Taken a step further, these could be nested:

```
import "../../../../../../tools" {
	import "./core" {
		DojoUtil = require("./DojoUtil");
		common = require("./common");
	}
	import "./annotations" {	
		AttributeInspector = require("./AttributeInspector");
		MonikerDropDown = require("./AttributeInspector/MonikerDropDown");
	}
}
```

I realize this may be impracticality but wanted to put it out there to see if it resonated with others or to see if there might already be another way of doing this.  I think Typescript 2.0 path mappings will make this less painful via path mappings.

**Comment by mhegazy** [comment]
This should be solved by baseURL (i.e. set your module root to `..\..\..\..\..\` and just import as `toos/core/common`) or map `tools\*` to `..\..\..\..\..\..\tools\*`.

you can find more documentation at: https://github.com/Microsoft/TypeScript-Handbook/blob/release-2.0/pages/Module%20Resolution.md#additional-module-resolution-flags
