### ISSUE TITLE
Union doesn't merge objects properties' type

### ISSUE THREAD

**Issue by nicolo-ribaudo** [Microsoft/TypeScript#8289]
**TypeScript Version:** 

This is reproducible both in VSCode 1.0 and in the playground ([https://www.typescriptlang.org/play/#src=...](https://www.typescriptlang.org/play/#src=interface%20A%20%7B%0D%0A%09x%3A%20number%3B%0D%0A%7D%0D%0A%0D%0Ainterface%20B%20%7B%0D%0A%09x%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Aconst%20c%3A%20A%20%7C%20B%20%3D%20%7B%20x%3A%201%20%7C%7C%20%22a%22%20%7D%3B%0D%0A%0D%0Aconst%20d%3A%20A%20%7C%20B%20%3D%20%7B%20x%3A%201%20%7D%20%7C%7C%20%7B%20x%3A%20%22a%22%20%7D%3B%0D%0A))

**Code**

```ts
interface A {
	x: number;
}

interface B {
	x: string;
}

const c: A | B = { x: 1 || "a" };

const d: A | B = { x: 1 } || { x: "a" };

```

**Expected behavior:**
Both `c` and `d` should be fine

**Actual behavior:** 
TypeScript reports this error for the `const c: A | B = { x: 1 || "a" };` statement:
 ```
Type '{ x: number | string; }' is not assignable to type 'A | B'.
  Type '{ x: number | string; }' is not assignable to type 'B'.
    Types of property 'x' are incompatible.
      Type 'number | string' is not assignable to type 'string'.
        Type 'number' is not assignable to type 'string'.
```

**Comment by mhegazy** [comment]
`{ x: number | string };` is neither `A` nor `B`. it becomes easier to see that with more than one property, e.g.

```ts

interface A {
    x: number;
    y:  number;
}

interface B {
    x: string;
    y: string;
}

const c: A | B = { x: 1 || "a" , y :  2 || "b"};

````

**Comment by RyanCavanaugh** [comment]
I should add that we've gotten this request around single-property types a bunch. It turns out to be very difficult to detect all of these cases properly in the compiler.

**Comment by nicolo-ribaudo** [comment]
@mhegazy Thank you, now I see why the current behavior is correct
