### ISSUE TITLE
Don't enforce naming restrictions in ambient declarations

### ISSUE THREAD

**Issue by RyanCavanaugh** [Microsoft/TypeScript#8293]
There are some modules like this:

```ts
export declare namespace Foo {
  export var static: any;
}
```
We flag this as an error:

> ../../throwaway/clipboard.ts(2,14): error TS1214: Identifier expected. 'static' is a reserved word in strict mode. Modules are automatically in strict mode.

This is a mistake -- it's possible the actual library says something like e.g. `Foo["static"] = expr`, rather than actually making a literal `static` local; we should not treat this as an error. This is blocking some actual .d.ts files on DT.

**Comment by mhegazy** [comment]
is this blocking the definitelytyped work?

**Comment by RyanCavanaugh** [comment]
Yep. We can't convert some things to proper UMD because the definitions end up in a module.
