### ISSUE TITLE
Support real private static properties?

### ISSUE THREAD

**Issue by Treri** [Microsoft/TypeScript#8299]
**TypeScript Version:** 

1.8.7

**Code**

```ts
class A {
  private static names: string[] = [];

  public pushNames(name: string): void {
    A.names.push(name);
  }
}
```

**Expected behavior:**
have real private static properties `names`
```ts
var A = (function () {
    var names = [];
    function A() {
    }
    A.prototype.pushNames = function (name) {
        names.push(name);
    };
    return A;
}());
```

**Actual behavior:** 
does not have real private static properties. A.names is not private when compiled to javascript
```ts
var A = (function () {
    function A() {
    }
    A.prototype.pushNames = function (name) {
        A.names.push(name);
    };
    A.names = [];
    return A;
}());

```

---

We can only implement this for private static properties, and leave private instance properties as what it is now or add prefix underscore `_` or something else for private instance properties?

**Comment by DanielRosenwasser** [comment]
Hey @Treri, in the future we have an [FAQ](https://github.com/Microsoft/TypeScript/wiki/FAQ) that you can check out before filing suggestions/issues. The relevant suggestion is [You should emit classes like this so they have real private members](https://github.com/Microsoft/TypeScript/wiki/FAQ#you-should-emit-classes-like-this-so-they-have-real-private-members). As explained in the FAQ, your solution doesn't actually function correctly.

See also #684.

**Comment by Treri** [comment]
@DanielRosenwasser My meaning is **private static properties** not private properties(instance properties)

**Comment by Treri** [comment]
@DanielRosenwasser  Could you please give me a expansion for my suggestion for only **static** properties?

**Comment by Treri** [comment]
ping @DanielRosenwasser

**Comment by mhegazy** [comment]
I do not see why instance and static should behave differently. Please note that you can capture the variables if you want inside a closure and/or a namespace declaration

**Comment by sjohnsonaz** [comment]
@DanielRosenwasser, the FAQ explains why **private** variables should not be done outside the constructor, but inside the self executing function.  However, that is a valid implementation of **private static** variables, which is what I believe the @Treri is looking for.  I'm running into this problem in my own project, as I convert my classes from pure JavaScript into TypeScript.

**Comment by juanmendes** [comment]
@mhegazy They do behave differently already, one adds a property to the constructor, the other adds a property to the object.

@DanielRosenwasser  We're just saying that if it doesn't need to be access by the outside, why pollute the constructor object and get the benefit of being truly private, even in JS?
