### ISSUE TITLE
Better error message for invalid assignment of tuples to arrays

### ISSUE THREAD

**Issue by yuit** [Microsoft/TypeScript#830]
As suggested in PR #822, error messages for Tuple type is unclear in explaining why certain tuple can be assigned to array. It will be helpful for users to get messages which provide more directed information.

**Comment by begincalendar** [comment]
Could we please get some information on what exactly is needed with this issue?

`error TS2322: Type '[number, string]' is not assignable to type 'number[]'` seems adequate to me, but I also see that:
```
  Types of property 'pop' are incompatible.
    Type '() => string | number' is not assignable to type '() => number'.
      Type 'string | number' is not assignable to type 'number'.
        Type 'string' is not assignable to type 'number'.
```
...is not really helpful.

**Comment by mhegazy** [comment]
Looking at this again, i agree the error message we have today is good enough. closing as such.

The additional elaboration is the standard structural type comparison elaboration you would get elsewhere.
