### ISSUE TITLE
Continuous integration on cloudbees  

### ISSUE THREAD

**Issue by piyush-dholariya** [Microsoft/TypeScript#8300]
I have created one app in typescript, now I want to write some unit case for that app.
Q.1 : how can I write unit test cases for typescript.
Q.2 : I want to deploy that app on cloudbees for continuous integration purpose, but I want to run those unit test cases on cloudbees, so what should I need to do for that?

**Comment by weswigham** [comment]
TS presently runs tests on [travis](https://travis-ci.org/Microsoft/TypeScript).

You can run tests locally by downloading the repo, running `npm install`, `npm install -g jake`, and `jake runtests`. This runs a mix of end-to-end, integration, and unit tests.

Unit tests are typically just top-level `.ts` files in the `tests/cases/unittests` directory (with corresponding entries in the `Jakefile` to compile them). _Most_ tests are not in the `unittest` folder, but are in the `tests/cases` folder and subfolders - there are three automatically-loaded and managed styles of tests (in addition to the aforementioned unit tests):
- `projects` tests which are a kind of compiler-API/CLI end-to-end test
- `fourslash` tests (these use a special DSL and test the language service), and
- `compiler` or `conformance` tests (which are the same style - raw .ts files with some optional comments declaring compiler options). `compiler` tests generally test compiler flags and features, while `conformance` tests generally test language features. 
`projects`, `compiler`, and `conformance` tests are "baselined", meaning they generate a textual summary of their results, and if a dev determines those results are OK, they overwrite the prior results with them, and those are considered the new 'baseline' for future comparisons.

I couldn't help you with "cloudbees". Sorry. :stuck_out_tongue:

**Comment by kitsonk** [comment]
This is much better asked on StackOverflow or IRC or many of the other forums for supporting TypeScript.

**Comment by mhegazy** [comment]
As @kitsonk mentioned SO would be the right place for such questions; this issue tracker is mainly for the language and compiler bugs.

**Comment by mhegazy** [comment]
To answer your question, you would write tests in TypeScript jsut like you do with JavaScript, just remember to add a build step (from .ts to .js) for your tests just as for your sources.
There are few samples that use test frameworks in https://github.com/Microsoft/TypeScriptSamples
