### ISSUE TITLE
Type annotations for currying or function partial application style APIs

### ISSUE THREAD

**Issue by remojansen** [Microsoft/TypeScript#8303]
I'm trying to declare the typings of `IFactory<T>`. The factory APIs uses a “currying” or function partial application style:

```ts
interface IFactory<T> {
    (...args: any[]): (IFactory<T>|T);
}

class Engine {
    constructor(type: string, cc: number) {}
}

let engineFactory: IFactory<Engine> = (type: string) => (cc: number) => {
    return new Engine(type, cc);
};

let dieselEngineFactory = engineFactory("diesel");
let dieselEngine300cc = dieselEngineFactory(300);     // Error!
let petrolEngine300cc = engineFactory("petrol")(300); // Error!
```
@basarat helped me on stackoverflow with the following answer:
```ts
interface IFactory<T,C> {
    (type:string): (configuration:C) => T;
}

class Engine {
    constructor(type: string, cc: number) {}
}

let engineFactory: IFactory<Engine, number> = (type: string) => (cc: number) => {
    return new Engine(type, cc);
};

let dieselEngineFactory = engineFactory("diesel");
let dieselEngine300cc = dieselEngineFactory(300);     // OK
let petrolEngine300cc = engineFactory("petrol")(300); // OK
```
My problem is that I have a framework that uses factories and the factories are defined by the users so I can only have one unique generic implementation of `IFactory` that covers all the factories to be developed by the users.

I've been thinking and as far as I know this is not possible. I wonder if you could add support for a new operator it would not be an union type or intersection type. In set theory it would be the union of the intersection and the relative complement of the types. I would suggest to use the `||` operator:
```
interface IFactory<T> {
    (...args: any[]): (IFactory<T>||T);
}
```

This would mean that `(IFactory<T>||T)` can take only one of the following types:
- `(A ∩ B) ∪ (B ∖ A)` Union of the intersection and the relative complement (B ∖ A). 
- `(A ∩ B) ∪ (A ∖ B)` Union of the intersection and the relative complement (A ∖ B). 

This is probably something complex but I believe it would be useful.

Thanks!

**Comment by basarat** [comment]
QQ : What about

```ts
let petrolEngine300cc = engineFactory("petrol")(300)("too many");
```
Error or Okay? :rose:

**Comment by remojansen** [comment]
That would be a runtime error. I understand that compilation errors are better than runtime errors but this is making really complicated to use functional programming in TypeScript and I really believe that functional programming is becoming a big thing. 

Let's imagine that I want to create the type definitions for [ramdajs](http://ramdajs.com/0.21.0/docs/#curry):

```ts
interface R {
    curry: <T>(func: (...args: any[])=> T) => (((...args: any[])=> T)|T);
}

declare var R: R;

var addFourNumbers = (a, b, c, d) => a + b + c + d;

var curriedAddFourNumbers = R.curry<number>(addFourNumbers);
var f = curriedAddFourNumbers(1, 2); // Error!
var g = f(3);
g(4); //=> 10
```
As I said I I understand that compilation errors are better than runtime errors but If I have the freedom to choose to do the following I would:
```ts
interface R {
    curry: <T>(func: (...args: any[])=> T) => (((...args: any[])=> T)||T);
}

declare var R: R;

var addFourNumbers = (a, b, c, d) => a + b + c + d;

var curriedAddFourNumbers = R.curry<number>(addFourNumbers);
var f = curriedAddFourNumbers(1, 2);
var g = f(3);
var h = g(4); //=> 10
h(5); // Error! (runtime)
```
Maybe we could have a compilation setting to enable compilation warnings? So we get a compilation warning before the runtime error.

**Comment by kitsonk** [comment]
This is essentially a dupe/heavily related to #5453 which is currently being implemented.

**Comment by mhegazy** [comment]
indeed #5453 should address this request. until then the only way is to list the first n-signatures explicitly as mentioned in https://github.com/Microsoft/TypeScript/issues/8303#issuecomment-214699527

**Comment by remojansen** [comment]
Thanks for spending some time looking at this issue.
