### ISSUE TITLE
The navigator on documentation site is half-broken

### ISSUE THREAD

**Issue by x1a0** [Microsoft/TypeScript#8304]
When the navigator is collapsed, all items are gone but the first one. I got confused because I could not find other parts of the documentation until I set the zooming back to 100% so all menu items appeared on left side again...

![quick_start_ _typescript](https://cloud.githubusercontent.com/assets/205756/14817378/3e6a78f2-0bb7-11e6-96ba-27d1c544b508.png)

**Comment by mhegazy** [comment]
duplicate of https://github.com/Microsoft/TypeScript/issues/8119

**Comment by x1a0** [comment]
Ah sorry - I did search but couldn't found that one. Thanks.

**Comment by mhegazy** [comment]
should be fixed now, can you give http://www.typescriptlang.org/docs/tutorial.html another try.

**Comment by x1a0** [comment]
@mhegazy yep - works for me now.
