### ISSUE TITLE
Error definition abstract class when 'export default'

### ISSUE THREAD

**Issue by syuilo** [Microsoft/TypeScript#8307]
**TypeScript Version:** 

1.8.9

**Code**

```ts
export default abstract class Klass {
  // something
}
```

**Expected behavior:**
No error

**Actual behavior:** 
![image](https://cloud.githubusercontent.com/assets/4439005/14820850/5605c1be-0c03-11e6-9de4-bbab58ac9c7a.png)

but,
```ts
abstract class Klass {
  // something
}

export default Klass;
```
is ok.

---

Sorry my bad English. thanks!

**Comment by Gigabyte-Giant** [comment]
I do believe this error has already been reported, see https://github.com/Microsoft/TypeScript/issues/3792.

**Comment by syuilo** [comment]
Oh, Sorry!
