### ISSUE TITLE
allow type declarations inside objects

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#8308]
```typescript

interface W<X, Y, Z> { x: X; y: Y; z: Z; }

function toModule<X, Y, Z>()  {
     type $W = W<X, Y, Z>;
     return {
        W: $W // <-- wish could do that
     };
}

const m = toModule<string, number, boolean>();
const w : m.W = { // <-- wish could do that
   x: '',
   y: 0,
   z: false
};
```

**Comment by mhegazy** [comment]
so namespace expressions, a la class expressions?

**Comment by aleksey-bykov** [comment]
please do either of the following:

- either namespaces that can be parametrized with types and values https://github.com/Microsoft/TypeScript/issues/2625
- or allow types in the position of object properties (which is mostly equivalent) like in the example above

**Comment by mhegazy** [comment]
here is a sample:

```ts
function toModule<X, Y, Z>()  {
     return namespace {
        export interface W { x: X; y: Y; z: Z; }
    }
}

const m = toModule<string, number, boolean>();
const w : m.W = { // <-- wish could do that
   x: '',
   y: 0,
   z: false
};
```

**Comment by mhegazy** [comment]
both approach has issues with the current implementations that assumes an expression can only be a value, and not a namespace. we will need a proposal for this one.

**Comment by aleksey-bykov** [comment]
### Workaround

This is the workaround that I have to use now:

```typescript
interface W<X, Y, Z> { x: X; y: Y; z: Z; }

function toModule<X, Y, Z>()  {
     const $W : W<X, Y, Z>;
     return {
        W: $W //
}

const m = toModule<string, number, boolean>();
const w : typeof m.W = {
   x: '',
   y: 0,
   z: false
};
```

**Comment by aluanhaddad** [comment]
👍

**Comment by aleksey-bykov** [comment]
@mhegazy 

> here is a sample:

that would be super great

**Comment by aleksey-bykov** [comment]
I am afraid that alone returning a namespace isn't enough. It needs to be also passed as an argument and taken as a parameter. In order to declare it it has to have a type. Do namespaces have a type per se? Doubt so. Anyway, I believe that the difference between namespaces and objects is a made up. It would be great to see **namepaces unified with objects** because to JavaScript they are the same.

**Comment by aleksey-bykov** [comment]
closing in favor of #8358
