### ISSUE TITLE
Show imports in navigation bar

### ISSUE THREAD

**Issue by JsonFreeman** [Microsoft/TypeScript#831]
Followup on commit 01d93b22ba88bc06ff9026f0d94f0047c8576d23 of the Navigation Items feature by @DanielRosenwasser. I believe that imports should be shown in the navigation bar, even though they will have no children. It is possible to navigate to them by searching (navigate-to), so they should be featured in the navigation items as well.

**Comment by mhegazy** [comment]
This should be working correctly now.
