### ISSUE TITLE
Contextual this in prototype functions

### ISSUE THREAD

**Issue by pankleks** [Microsoft/TypeScript#8317]
Hi,

When adding new functions to object prototype, `this` could be hard-typed in below scenario:

```ts
interface Array<T> {
  first(): T;
}

Array.prototype.first = function() {
  return this.length > 0 ? this[0] : undefined;
}
```

`this` is of type `any`, why it can't be of type `Array` ?

typescript: 1.8.30

**Comment by RyanCavanaugh** [comment]
Duplicate of #8024 ?
