### ISSUE TITLE
Node.insertBefore() second parameter is not optional

### ISSUE THREAD

**Issue by ntrrgc** [Microsoft/TypeScript#8320]
This is in the definition of a DOM `Node`, from `lib.d.ts`:

    insertBefore(newChild: Node, refChild?: Node): Node;

According to it, `refChild` is optional, which is not true according to the [MDN documentation](https://developer.mozilla.org/en-US/docs/Web/API/Node/insertBefore) and certainly causes a runtime error in Google Chrome.

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.
