### ISSUE TITLE
Suggestion: use an 'is' operator for custom type guards rather than referring directly to user-defined function

### ISSUE THREAD

**Issue by mcdurdin** [Microsoft/TypeScript#8323]
I've found type guards to be very useful but the subtlety of how custom type guards restrict the type in the scope is troubling me, because as a developer we kinda have to know that `isFish()` is a type guard and not just a boring old function.

Suggestion: a self-documenting way of highlighting the use of a type guard would be to define an `is` operator which resolves to a user-defined type guard function:

```
function isFish(pet: Fish | Bird): pet is Fish {
  return (<Fish>pet).swim !== undefined;
}

if(pet is Fish) { // instead of isFish(pet)
  pet.swim();
}
else {
  pet.fly();
}
```

Would this be inferrable from the definition of `isFish()`? Using this pattern, I guess it would not be possible to define two custom type guards that have different implementations for the same type.

It would then also be logical to define, for all the primitive types:

```
if(v is String) {} // same as if(typeof v === 'string') {}
```

Benefits:

1. A consistent way of using type guards for primitive and complex types.
2. Clarity in when a custom type guard has been invoked when reading code.
3. Avoids multiple type guard definitions for a single type.
4. Avoids use of `typeof` for primitive types with the restrictions of argument order, `===` vs `==`, typos in the string content
5. Feels consistent with the use of the `is` predicate in the type guard function.

Costs:

1. The compiler would need to keep a tree of the custom type guards to map back to.

**Comment by mhegazy** [comment]
so is the compiler expected to grok all your sources to find a function with the annotation `function isFish(pet: Fish | Bird): pet is Fish` to use it in the emitted output? what happens if this method is in a different module? what if it is not accessible? shadowed? or aliased? how would this work for single file emit (i.e. when the compiler is transpilling a single file and is expected to write something in there)?

**Comment by mcdurdin** [comment]
Thanks for the comment. You are right. This probably means it can't work; so I'll close this as a non-starter.

**Comment by mcdurdin** [comment]
Wait a minute. I may have been a bit hasty closing this. In the existing implementation, doesn't the compiler already know about the function in order to infer the type for the new scope? Even if transpiling a single file you still need `<references/>` to definitions in other modules?

It's less obvious for scoped, shadowed or aliased types and I admit I haven't thought through the implications of those fully.

**Comment by basarat** [comment]
> In the existing implementation, doesn't the compiler already know about the function in order to infer the type for the new scope

The compiler doesn't drive any *emit* from global type information. The function `isFish` is explicitly called by user when they want to. 

Basically `if (isFish(foo))` vs. `if (foo is Fish)`. In the first case we know that `isFish` is the function to call and then see what it does to `foo`. Whereas in the second case we would have to search and find the `isFish` function (and there might be more than one).

**Comment by kitsonk** [comment]
Also, it works in the spirit of TypeScript being a superset of JavaScript.  `foo is Fish` introduces new language syntax that requires a transform, resolution and isn't erasable.  The beauty of the current solution is that in a lot of cases, existing JavaScript code can often be upgraded to intelligent type guards by just adding erasable type information to the return of a function.
