### ISSUE TITLE
Transform JSX to string

### ISSUE THREAD

**Issue by Longwelwind** [Microsoft/TypeScript#8326]
Hi !

Could it be possible to add a transformer for JSX that outputs a Javascript "normal" string ?
For example, this:

```ts
let foo = "Hello world !";
let bar = (
    <div>
        {foo}
    </div>
);
```

would be transformed to:

```ts
let foo = "Hello world";
let test = "<div>" +  foo + "</div>";
```
I'm not sure if it goes into the scope of the project, since one could use the `preserve` option and use an additional transpiler, but I think it could help users write components & templates for any library (Vuejs, Ractive, ...), instead of just React.

**Comment by basarat** [comment]
> Could it be possible to add a transformer for JSX that outputs a Javascript "normal" string

You could do it externally and only after the `[Transformer]` style emitter of the TypeScript is complete.

That said, why not just use a template string? : https://basarat.gitbooks.io/typescript/content/docs/template-strings.html

```ts
let bar = (
    `<div>
        ${foo}
    </div>`
);
```
Also `ReactServer.renderToString` has a similar outcome :rose:

**Comment by mikeyoon** [comment]
I wonder if a special transformer could be used for supporting strong typing in AngularJS templates.

**Comment by mhegazy** [comment]
see https://github.com/Microsoft/TypeScript/issues/5470

**Comment by developit** [comment]
@Longwelwind hate to resurrect this issue since it's fairly old now, but it seems like you're looking for [vhtml](https://git.io/vhtml).
