### ISSUE TITLE
TS5055: Cannot write file

### ISSUE THREAD

**Issue by Brakkar** [Microsoft/TypeScript#8329]
Hello,
got this error in 2 IDE: Webstorm and VScode.

tsc --v
Version 1.8.10

Mac OSX 10.11.4

> error TS5055: Cannot write file '/Users/ME/Documents/Apps_And_Sites/Js_Apps/projectname/apps/directory/directory_controller.js' because it would overwrite input file.
> error TS5055: Cannot write file 'apps/directory/directory_controller.js' because it would overwrite input file.
> error TS5056: Cannot write file 'apps/directory/directory_controller.js' because it would be overwritten by multiple input files.

Please find the attached culprit file

[directory_controller.ts.zip](https://github.com/Microsoft/TypeScript/files/238175/directory_controller.ts.zip)

**Comment by zhengbli** [comment]
Do you have a tsconfig file with `allowJs` set to `true`, or do you have a `jsconfig.json` file? The error happens when the JavaScript file was considered part of the project, and your compilation will override these files.

**Comment by Brakkar** [comment]
Indeed, I have a tsconfig with allowJs set to true.
Disabling it, fixed the issue. I'm not sure though it is coherent that it happens only with some files and not others.
