### ISSUE TITLE
Code fails noImplicitAny check under 1.1.0.0

### ISSUE THREAD

**Issue by paf31** [Microsoft/TypeScript#833]
This code used to compile without error under 1.0:

```typescript
module M {

        export interface T<A> {
            get(): A;
        }

        export function ap<A, B>(f: T<(a: A) => B>, x: T<A>): T<B> {
            return {
                get: () => f.get()(x.get())
            };
        }

        export function map<A, B>(f: (a: A) => B, x: T<A>): T<B> {
            return {
                get: () => f(x.get())
            };
        }

        var x: T<number> = {
            get: () => 0
        };

        var test = ap(ap(map((a: number) => (b: number) => (c: number) => {
                return { a: a, b: b, c: c };
            }, x), x), x);
}
```

However, under 1.1, I get the following error:

```
(23,37): error TS7024: Function implicitly has return type 'any' because it does not have a return type annotation and is referenced directly or indirectly in one of its return expressions.
```

I don't see any reason why any subexpression of `test` should have an inferred type of `any`.

**Comment by aleksey-bykov** [comment]
is this by design too?

```
function apply<a, r>(value: a, map: (value: a) => r): r {
	return map(value);
}
function id<a>(value: a) { return value; }
var yay = apply(() => ({ x: 0 }), id); // () => any <--- ????
```

**Comment by RyanCavanaugh** [comment]
I will let Fred Brooks know that developer time is completely fungible and that it would be plausible to take the intern off his summer project to redesign how generic type inference works.

**Comment by paf31** [comment]
> I will let Fred Brooks know that developer time is completely fungible and that it would be plausible to take the intern off his summer project to redesign how generic type inference works.

What is this in response to?

**Comment by RyanCavanaugh** [comment]
Aleksey's comment that we should change this instead of doing `abstract`

**Comment by aleksey-bykov** [comment]
sarcasm, i has it too

seriously, why do new controversial OOP features take precedence over not
working inference let alone anything that supports coding in functional
style?

**Comment by RyanCavanaugh** [comment]
It's not a matter of precedence.

Choosing not to do `abstract` will not a) make fixing this any easier or b) free up any resources that are capable of fixing this problem.

**Comment by danquirk** [comment]
@aleksey-bykov In addition to what's been covered, don't think we haven't spent _a lot_ of time talking about generic type inference over the years. It's not like where inference is now is as far as we thought about it and we just punted on thinking about going any deeper. We'll continually re-evaluate what is and isn't feasible in that part of the system over time, but as Ryan notes, it's not as simple as just choosing to do x instead of y.

**Comment by aleksey-bykov** [comment]
Good to know. Thank you
