### ISSUE TITLE
Typechecking for non-intrinsic elements in TSX

### ISSUE THREAD

**Issue by tinganho** [Microsoft/TypeScript#8330]
I'm using TSX without React. I'm just wondering how do I get type checking for a non-intrinsic element?

```ts
<ScrollableContent class='CommentsListContainer' type='vertical' maxHeight={300}/>
```

the attributes `class`, `type` and `maxHeight` is of type any. I have tried numerous ways to get type checking, but failed. I have also looked at `react.d.ts` to try to get the solution, but also failed.

The `ScrollableContent` class is an extension of a generic class:
```ts
interface Props {
    class: string;
    maxLength: number;
    type: 'vertical' | 'horizontal';
}

export class ScrollableContent extends Component<Props> {
```

And I guess just the right interfaces need to be defined in the JSX namespace in order for everything to kick in?

**Comment by RyanCavanaugh** [comment]
#3203 outlines how this works

**Comment by RyanCavanaugh** [comment]
#5478 as well

**Comment by tinganho** [comment]
Thanks!
