### ISSUE TITLE
Decorators should be applied before installing static members

### ISSUE THREAD

**Issue by bterlson** [Microsoft/TypeScript#8337]
Currently, given the following:

```ts

function sealed(constructor: Function) {
    Object.seal(constructor);
    Object.seal(constructor.prototype);
}

@sealed class MyDate {
	static EPOCH = new MyDate(0);
	private n;
		
	constructor(n) {
		this.n = n;
	}
}

Object.isSealed(MyDate.EPOCH); // false
```

I would expect by static member to be sealed but it is not. Ideally static members would be installed on the constructor after the class has been decorated.

**Comment by mhegazy** [comment]
The rational is to make sure that the class is "defined" before a decoration. and since a static property is part of final "shape" of the class, the decoration happens after it is defined.
also if the static member is decorated, i would expect this decoration to happen before the class decoration, the opposite would be fairly confusing.

**Comment by bterlson** [comment]
The outcome of this rationale is that you get the ability for a decorator to see the static "shape" of the class in exchange for giving up the ability to create a static member with an initializer that sees the decorated class. I don't believe this is a good tradeoff - the latter seems more useful to me.

Looking forward, I believe the final ECMAScript design for decorators will allow a decorator to see the shape of an object (as static members will be collected early and provided to the decorator with a mirror), but not the value (as the initializer is thunked and not run until the end of class definition evaluation for statics). This gets us pretty close to best of both worlds.

Agree that static member decoration should occur before the class is decorated. Note that applying the decorator and evaluating the initializer can be separate steps in the latest decorator proposal.

I think that the current design has some fairly confusing aspects as well. Eg. OP contains a very common pattern that I would expect to work. It is also strange that static initializers don't see the decorated class but instance initializers do.

**Comment by mhegazy** [comment]
closing in favor of https://github.com/Microsoft/TypeScript/issues/6285
