### ISSUE TITLE
In ES6, new RegExp should accept a regexp as the first parameter

### ISSUE THREAD

**Issue by nicolo-ribaudo** [Microsoft/TypeScript#8338]
**TypeScript Version:** 

1.8.10

**Code**

```ts
new RegExp(/a/, "g");
```

**Expected behavior:**
That code should be accepted by typescript

**Actual behavior:** 
`Argument of type 'RegExp' is not assignable to parameter of type 'string'.`

**Comment by mhegazy** [comment]
indeed. here is the reference to the spec: http://www.ecma-international.org/ecma-262/6.0/#sec-regexp-pattern-flags

**Comment by mhegazy** [comment]
PRs welcomed. the change should be done in https://github.com/Microsoft/TypeScript/blob/master/src/lib/es2015.core.d.ts#L346 by adding:

```ts
interface RegExpConstructor {
    new (pattern: RegExp, flags?: string): RegExp;
    (pattern: RegExp, flags?: string): RegExp;
}
```

**Comment by mhegazy** [comment]
@nicolo-ribaudo the fix should be in `typescript@next` tomorrow.
