### ISSUE TITLE
How to use typescript formatter options ?

### ISSUE THREAD

**Issue by Brakkar** [Microsoft/TypeScript#8348]
Hi,
on this page: https://code.visualstudio.com/Updates
It is mentioned that new formatter options are available for typescript, such as: 
"typescript.format.insertSpaceBeforeAndAfterBinaryOperators": boolean

Can these formatter options only be used in VSC ?
I use another ide (webstorm) and wish to use them.

I have tsc and tslint installed and working already.

**Comment by kitsonk** [comment]
These type of how-to questions are best asked on StackOverflow or the other help forums.

Other IDEs need to use the TypeScript language services.  How to set those sort of flags are up to the IDE and if the IDE respects and consumes those parts of the language services, so again, it is best to find support from your [IDE vendor](https://www.jetbrains.com/support/).
