### ISSUE TITLE
TSC allocates a lot of memory and crashes with an error

### ISSUE THREAD

**Issue by lexon0011** [Microsoft/TypeScript#8352]
I create a really small angular 2 app, where I can demonstrate that the TSC allocate a lot of memory. The command `tsc -w` crashes after a certain amount of time with the following error message:

**FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory**

You can reproduce it with [this repository](https://github.com/lexon0011/IssueDemonstrator)

- clone the repository: `git clone https://github.com/lexon0011/IssueDemonstrator`
- install the packages: `npm install`
- install typings: `typings install`
- star watching: `tsc -w ` or or start the application: `npm run start-dev`

I use the version 1.8.10. 

Is that a bug or a configuration error (e.g tsconfig.json)?? What goes wrong here?

![2016-04-28 16_44_46-windows task-manager](https://cloud.githubusercontent.com/assets/16290662/14889835/b7f9e41e-0d60-11e6-8237-b053e25dd695.png)

**Comment by mhegazy** [comment]
this looks like the same issue as https://github.com/Microsoft/TypeScript/issues/7344. updating to a newer RxJS (later than 5.0.0-beta.2) should address the issue.

**Comment by lexon0011** [comment]
Thanks, but the problem is, that angular 2 has RxJS beta.2 as dependency

**Comment by mhegazy** [comment]
@alexeagle what is the recommendation to get a newer version of RxJS?

**Comment by alexeagle** [comment]
current angular 2 releases use more recent rxjs (I believe we are on beta.6 now)

**Comment by mhegazy** [comment]
thanks @alexeagle!

**Comment by lexon0011** [comment]
Thanks. 
Today Angular 2 Beta 7 was published. The dependency was changed to RxJS Beta 6. Now TSC also looks better :)
