### ISSUE TITLE
unify namespaces and objects

### ISSUE THREAD

**Issue by zpdDG4gta8XKpMCd** [microsoft/TypeScript#8358]
Namespaces are objects that can hold types, but cannot be passed around because don't have a type themselves.
Objects are mostly namespaces which can be passed around because they are typed, but cannot hold types in them.

Looks like this difference is a made up thing.

**Consider unifying objects and namespaces.**

possible resolution of https://github.com/Microsoft/TypeScript/issues/8308

**Comment by mhegazy** [comment]
so what is the proposal? and how is it different from #8308?

**Comment by aleksey-bykov** [comment]
proposal goes: make namespaces first class citizens, which is

- make it possible to close them over types and values from current scope
- return from a function
- pass as a parameter

they are different in a scope of work, #8308 is less work and because of that might win over this request

**Comment by mhegazy** [comment]
> pass as a parameter

i am guessing you mean define a parameter as a namespace, you can pass them now just fine.

**Comment by aleksey-bykov** [comment]
not sure what you mean:

```typescript
namespace N {
	type T = string;
	
}

function f(n: typeof N) { // <-- ?
	return 
}
```

**Comment by mhegazy** [comment]
the value N (the object literal equivalent) does not exist. so `typeof N` is nothing. ` namespace N { export var x; }` has a type and it is `{ x: any }`.

**Comment by mhegazy** [comment]
I still do not see much difference and/or proposals than #8308. i would rather have one issue.

**Comment by aleksey-bykov** [comment]
which one is more likely to be implemented *this* or #8308 (adding types as properties of objects)?

**Comment by aleksey-bykov** [comment]
> ...does not exist. so typeof N is nothing

can you show an example of passing a namespace as an argument?

**Comment by mhegazy** [comment]
```ts

namespace N {
    export var x = 0;
}

function f(n: typeof N) {
    return
}

f(N) // OK
f({ x: 0 }); //OK


function f2(n: { x: number }) {
    return
}

f2(N) // OK
f2({ x: 0 }); //OK
```

**Comment by aleksey-bykov** [comment]
i am talking about this

![image](https://cloud.githubusercontent.com/assets/937933/14898968/c1a3c024-0d57-11e6-96f0-fdb7205e60e9.png)

**Comment by mhegazy** [comment]
OK, so there is a value, i.e. the entity that exists at runtime in JS, there is a type, i.e. the design time construct that is defined in a TS file, and there is a namespace, something that can contain, values, types and other namespaces.

a name can have 1, 2, or all 3 meanings based on its declaration. so a class is both a type and a value. an enum, is a value, a type, and a namespace, etc..

you can read more about this at: http://www.typescriptlang.org/docs/handbook/declaration-merging.html

`typeof value` returns the type of a value. a namespace can not have a type. just cause it does not make much sense. in the example above, `T` is a type, it is not a property on the value `N`, it is just another type that is accessed using the name `N.T`.

this is what i meant by askign for a proposal on how this would fit in the existing design in https://github.com/Microsoft/TypeScript/issues/8308#issuecomment-214798653

I think the two issues are the more or less the same issue, and a clear and detailed proposal is needed. marking this issue as a duplicate.

**Comment by aleksey-bykov** [comment]
i am closing the other one (#8308) then

**Comment by DanielRosenwasser** [comment]
#420 seems vaguely related for the record.

The thing is that there is no value side to non-instantiated namespaces. Something like

```ts
namespace n {
    export interface Foo { }
}
```

doesn't actually have any associated emit, so it's not clear what you'd pass in for a function like

```ts
function foo(x: typeof n) {
    // ...
}
```

Does

```ts
foo(n);
```

compile to the following?

```js
foo(undefined);
```

**Comment by aleksey-bykov** [comment]
*practically* (as far as i know it) i only pass types *and* values (never types alone), although it is a valid question, need to find a use case that does it

**Comment by aleksey-bykov** [comment]
side note, you don't need to pass types-only namespace, you can make it on site as you want:
```

    declare namespace HiThere<A, B, C> {
    }

    type NamepsceWithTypesThatINeed = HiThere<string, boolean, number>;

```
