### ISSUE TITLE
Exported variables are considered unassigned

### ISSUE THREAD

**Issue by ivogabe** [Microsoft/TypeScript#8359]
A variable that is exported, gives an error when it is used. When the `export` keyword is removed, everything works as expected.

**TypeScript Version:** 

nightly (1.9.0-dev.20160428)

**Code**

```ts
export const a = "";
a.substring;
```

**Expected behavior:**
This should compile without an error.

**Actual behavior:** 
This gives the following errors:
- Variable 'a' is used before being assigned.
- Property 'substring' does not exist on type '{}'.
- Object is possibly 'undefined'. (only with `strictNullChecks` enabled)

**Comment by ahejlsberg** [comment]
I can't reproduce this one with 1.9.0-dev.20160428. Are you sure that's the version of tsc you're using? I made fixes in this area a few days ago, but they're all in 1.9.0-dev.20160428.

**Comment by ivogabe** [comment]
Oops, you're correct. I had installed that version with npm, but I referenced the wrong version of TypeScript in the configuration of VSCode. Works good now.
