### ISSUE TITLE
Configuration setting need to have an option to disallow "any" in TypeScript source code

### ISSUE THREAD

**Issue by fletchsod-developer** [Microsoft/TypeScript#8360]
**TypeScript Version:** 

1.8.10

**Code**

var foo = 23;
var fee = "fff";

```

**Expected behavior:**
Somehow show that any is being used and strict data type need to be used.   The problem is JavaScript is too forgiving where "foo" can bee seen as either a number or string.

**Actual behavior:** 
Both foo and fee default to "any" because data type is not being specified.  Example "var foo: number = 23;" and "var fee: string = "fff";".

**Comment by thebanjomatic** [comment]
@fletchsod-developer, in typescript, the types of `foo` and `fee` will be deduced as `number` and `string` by the inferred type of the RHS of the assignment, and will not be deduced as `any`

However, had you written the following, `foo` _would_ be inferred as `any`:
```ts
var foo; // implicitly typed as any
foo = 23;
```

In that case, there is already a compiler option `noImplicitAny` that would produce compiler errors in this case, requiring you to either be explicit about the use of `any`:
```ts
var foo: any; // explicitly typed as any
foo = 23
```

or better by using the actual type (or union type) of the variable:
```ts
var foo: number|string; // explicitly typed
foo = 23
foo = "fff";
```

**Comment by fletchsod-developer** [comment]
I see.  It doesn't returned compiler error when 'noImplicitAny' is set to true.

**Comment by mhegazy** [comment]
there are no `any` types in this sample. they are `number` and `string`.

these two are identical.
```ts
var foo = 23;
var foo: number = 23;;
```

A variable is given the type `any`, if 1. it does not have a type annotation, and 2. a type could not be inferred from its initialization.

so:

```ts
var foo; /// this is of type any.
```

compiler that with `--noImplicitAny` and you will see an error.

**Comment by fletchsod-developer** [comment]
Shouldn't `--noImplicitAny` raise compiler error when this example below is missing `: number`

     var foo = 23;

because `foo: number` isn't being used.

**Comment by mhegazy** [comment]
you do **not** need to add a type annotation to every thing. the compiler can infer types on its own. if you forgot and did not give a variable a type at declaration site, `--noImplicitAny` will warn you about it.

**Comment by fletchsod-developer** [comment]
Okay.  We'll have to get used to it.  Thanks.

**Comment by mhegazy** [comment]
hover is your friend :)

![animation](https://cloud.githubusercontent.com/assets/8000722/14900113/e24f1666-0d43-11e6-963b-ac34d4884eb4.gif)
