### ISSUE TITLE
Early return instead of "else" causes compiler error.

### ISSUE THREAD

**Issue by radarsu** [Microsoft/TypeScript#8365]
**TypeScript Version:** 

nightly (1.9.0-dev.20160217)

**Code**

```ts
let greeting:string;
let x = (message: string | number) => {
		if (typeof message !== "string") {
			return;
		}
		// It's obvious, that message must be a string now. It works with "else statement" but not with early return.
		greeting = message;
    }
}
```

**Expected behavior:**
No raising error.

**Actual behavior:** 
Compiler raises an error that type string | number cannot be assigned to string variable.

**Comment by mhegazy** [comment]
This is working correctly in latest after https://github.com/Microsoft/TypeScript/pull/8010

**Comment by malibuzios** [comment]
I tried this in `1.9.0-dev.20160429` (the latest nightly) and it does perform the analysis.

I believe version `1.9.0-dev.20160217` (a nightly build from 17th of February 2016) may not yet include control flow based type analysis, that was only merged on the [23 of April](https://github.com/Microsoft/TypeScript/pull/8010#event-638259113).
