### ISSUE TITLE
Flow control resets guarded variables in sub function scope

### ISSUE THREAD

**Issue by kitsonk** [Microsoft/TypeScript#8367]
**TypeScript Version:** 

nightly (1.9.0-dev.20160429)

**Code**

```ts
function isFoo(value: any): value is Foo {
	return value && typeof value.foo === 'function';
}

interface Foo {
	foo(): string;
}

interface Bar {
	bar(): string;
}

function convertBar(input: Foo | Bar): () => string {
	return isFoo(input) ? function () {
		return input.foo(); // <-- Property 'foo' does not exist on type 'Foo | Bar'.
	} : input.bar;
}
```

**Expected behavior:**

Receive no errors ([as per 1.8](http://www.typescriptlang.org/play/#src=function%20isFoo(value%3A%20any)%3A%20value%20is%20Foo%20%7B%0A%09return%20value%20%26%26%20typeof%20value.foo%20%3D%3D%3D%20'function'%3B%0A%7D%0A%0Ainterface%20Foo%20%7B%0A%09foo()%3A%20string%3B%0A%7D%0A%0Ainterface%20Bar%20%7B%0A%09bar()%3A%20string%3B%0A%7D%0A%0Afunction%20convertBar(input%3A%20Foo%20%7C%20Bar)%3A%20()%20%3D%3E%20string%20%7B%0A%09return%20isFoo(input)%20%3F%20function%20()%20%7B%0A%09%09return%20input.foo()%3B%0A%09%7D%20%3A%20input.bar%3B%0A%7D%0A))

**Actual behavior:** 

Receive the error `Property 'foo' does not exist on type 'Foo | Bar'.`

**Comment by weswigham** [comment]
Technically, this dupes the first half of #8270 but since that was closed as the second issue the user in that thread mentioned was fixed (and he got a workaround for this issue), this issue may be appropriate.

@ahejlsberg 's prior comment on this:
> Regarding the first issue, control flow analysis doesn't consider a type guard to hold across a callback (because the callback could happen at any time, including outside the guarded block). This is different and more conservative from what we've previously done, and we're certainly open to feedback about whether it is too conservative. Meanwhile, you probably want to capture the guarded variable in a local and then reference that in the callback:

**Comment by kitsonk** [comment]
Thanks.  Since this is "clean" of the other issue, maybe it makes sense to keep this open, and for now I will feedback here.

From a feedback perspective it was surprising to me that the guard didn't hold (and a breaking change in behaviour).  While it is true that the callback can occur at any point, in the above use case, any conservatism is "wasted".  Also, technically input could be anything by the time the return function gets called, including not being type `Foo | Bar`.  The workaround based on the above would be something like (though obviously there are many ways):

```typescript
function convertBar(input: Foo | Bar): () => string {
    let foo: () => string;
    if isFoo(input) {
        foo = input.foo;
    }
    return foo ? function () {
        return foo();
    } : input.bar;
}
```

To me that just seems awkward and intent a whole lot less clear.  What I have done for now (which it always pains me to strong arm the compiler):

```typescript
function convertBar(input: Foo | Bar): () => string {
    return isFoo(input) ? function () {
        return (<Foo> input).foo(); // <-- I am sure I made a angel weep for doing this
    } : input.bar;
}
```

**Comment by mhegazy** [comment]
this is already covered in https://github.com/Microsoft/TypeScript/issues/7662.
