### ISSUE TITLE
Argument destructuring doesn't work with strictNullChecks

### ISSUE THREAD

**Issue by RReverser** [Microsoft/TypeScript#8376]
**TypeScript Version:** 

nightly (1.9.0-dev.20160429)

**Code**

```ts
[{ x: 1 }].map(
  ({ x }) => x
);
```

**Expected behavior:**
There should be no error in usage like this.

**Actual behavior:** 
Getting `Variable 'x' is used before being assigned.`

**Comment by ahejlsberg** [comment]
@RReverser Thanks for reporting. Fix is now in master.

**Comment by RReverser** [comment]
@ahejlsberg Awesome, thanks for such a quick response!
