### ISSUE TITLE
Contextually type class type arguments

### ISSUE THREAD

**Issue by tinganho** [Microsoft/TypeScript#8378]
I have problem of a non-DRY situation. I have `View` class that set a bunch of labels through a method. It must be a method because I need to give it some context.

```ts
interface Labels {
    label1: string;
    label2: string;
    label3: string;
    label4: string;
    label5: string;
    label6: string;
    label7: string;
    label8: string;
    label9: string;
    label10: string;
}
class FormView extends View {
    label: Labels;
    labels(l: (key: string) => string): Labels { // Some abstraction take the return of this and set it to 'this.label'.
        return {
             label1: l('hello_world_1'),
             label2: l('hello_world_2'),
             label3: l('hello_world_3'),
             label4: l('hello_world_4'),
             label5: l('hello_world_5'),
             label6: l('hello_world_6'),
             label7: l('hello_world_7'),
             label8: l('hello_world_8'),
             label9: l('hello_world_9'),
             label10: l('hello_world_10'),
        }
    }

    view() {
        return  <div>this.label.label1</div>;
    }
}
```

As you can see above there is a heavy repeating of properties one as an interface and one as a returning data structure. And I need to do this on every view class. And there is a bunch of them.

# Solution

Contextually type type argument.

```ts
abstract class A<T> {
	label: T;
	public labels(): T;
} 

class B extends A {
    labels() {
        return {
             label1: l('hello_world_1'),
             label2: l('hello_world_2'),
             label3: l('hello_world_3'),
             label4: l('hello_world_4'),
             label5: l('hello_world_5'),
             label6: l('hello_world_6'),
             label7: l('hello_world_7'),
             label8: l('hello_world_8'),
             label9: l('hello_world_9'),
             label10: l('hello_world_10'),
        }
    }

    view() {
        return  <div>this.label.label1</div>;
    }
}
```
There is no repetition of `label1, label2...` etc above.

**Comment by Thomas-P** [comment]
Hi,

wouldn't it be possible to use an array of labels instead of this interface? Otherwise you could use a Map if you compile to es6 to store your label information.

**Comment by tinganho** [comment]
I don't quite understand your suggestion. Can you provide a code example?

**Comment by mhegazy** [comment]
i do not think we should infer the generic type parameter in an extends clause. you are defining a shape of a new declaration, and silently inferring some type is not of much help.

**Comment by aleksey-bykov** [comment]
```
const toLabels = () => { /.../ }
const labels = undefined && toLabels();
new class B extends A<typeof labels> { labels: toLabels }
```

**Comment by tinganho** [comment]
@aleksey-bykov you can probably also do it in the future (when you can use typeof in an expression #6606):
```ts
class SomeView extends View {
    label: typeof this.labels();
    labels() {
        return {
             label1: l('hello_world_1'),
        }
    }
}
```
but the point is that. I want consumers of `View` already have everything magically stitched up, so everything they need to do is:
```ts
class SomeView extends View {
    labels() {
        return {
             label1: l('hello_world_1'),
        }
    }
}
```
after all the base class is an abstract class that should provide all the abstraction as possible.

>you are defining a shape of a new declaration, and silently inferring some type is not of much help.


@mhegazy I don't think I understand what you mean by silently? But it is giving me a lot of benefits of not having to duplicate the properties? And for my case I got 100 view classes like the one above and I must say it is quite a pain to have to duplicate the writing of the properties.

And except for a new declaration there is not a big difference from this example:

```ts
function test<T>(a: () => T, p1: T) {
}

test(() => 'hello world', 'hello world');
```
In the above example T is inferred to be a string, firstly from the callback.

**Comment by Thomas-P** [comment]
Hi, 

I mean in this case you should use a array structure to store your labels. 

```ts
interface ILabel {
    string;
}
class B {
    labels(): Array<ILabel> {
        return [
            l('hello_world_1'),
            l('hello_world_2'),
            l('hello_world_3'),
            l('hello_world_4'),
            l('hello_world_5'),
            l('hello_world_6'),
            l('hello_world_7'),
            l('hello_world_8'),
            l('hello_world_9'),
            l('hello_world_10'),
        ]
    }

    view() {
        return  <div>this.label[0]</div>;
    }
}

abstract class A<T> {
    constructor(labelInterface: T);
    label: T;
    public labels(): T;
}
```

It is more flexible and allows your to set more label or less label. Otherwise you could implement it as a Map.

```ts
class A {
    private $labelStore = new Map(); 
    
    setLabel(key: string, value: string): void {
        this.$labelStore.set(key, value);
    }
    
    getLabel(key: string): string {
        this.$labelStore.get(key);
    }
}

class B extends A{
    labels(): void {
        this.setLabel('label1', l('hello_world_1'));
    }

    view() {
        return  <div>this.getLabel('label1')</div>;
    }
}
```

Instead of Map you can also use an Object, because your label names are strings. I think it is a proper solution and you can also implement error handling in your view class A.

**Comment by tinganho** [comment]
I think I managed to get around my problem.
