### ISSUE TITLE
type assertions in object shortand properties

### ISSUE THREAD

**Issue by nicolo-ribaudo** [Microsoft/TypeScript#8379]
**TypeScript Version:** 

1.8.10

**Code**

```ts
let a;
let b = { a as string };
let c = { <string> a };
```

**Expected behavior:**
The type of `b` and `c` should be `{ a: string }` and the output should be this:
```ts
var a;
var b = { a: a };
var c = { a: a };
```

**Actual behavior:** 
```ts
var a;
var b = { a: as, string: string };
var c = {} < string > a;
;
```

**Comment by mhegazy** [comment]
Do not think this is a bug; this is an invalid syntax. there is no production in the language grammar that allows this code. compiling it results in syntax errors, and there are no guarantees about the output code in the face of invalid input syntax.

Now as a feature request; there is a chance of conflict with possible future ES syntax, so i would punt on this specially that the alternative is fairly easy to write, and i would argue is clearer to read:
```ts
var b = { a: <string> a };
var c = { a: a as string };
``
