### ISSUE TITLE
IIFEs incorrectly refine Maybe-values to Nothing

### ISSUE THREAD

**Issue by RReverser** [Microsoft/TypeScript#8381]
**TypeScript Version:** 

nightly (1.9.0-dev.20160429)

**Code**

```ts
let maybeNumber: number | undefined;
(function () {
    maybeNumber = 1;
})();
if (maybeNumber !== undefined) {
    maybeNumber++;
}
```

**Expected behavior:**
Everything works without errors, `maybeNumber` preserves type of `number | undefined` and refines to `number` in the `if` block.

```ts
let maybeNumber: number | undefined;
// Control flow figured that: maybeNumber === undefined
(function () {
    maybeNumber = 1;
})(); // --> oops, unknown side effects
// Revert maybeNumber to initial `number | undefined` to cover all possibilities
if (maybeNumber) {
    // Control flow: can refine to `number` again here
    maybeNumber++;
}
```

**Actual behavior:** 
Language service reports type `nothing` on `maybeNumber` after the call (even though it's `number | undefined` before the call), so statement inside of the `if` condition breaks.

**Comment by tinganho** [comment]
I just encountered something similar.
```ts
let test: string | undefined;
if (!test) {
	throw new Error('Test is not defined');
}
(() => {
	test.slice(1); // error possibly undefined...
})();
```

**Comment by aleksey-bykov** [comment]
@ahejlsberg would you consider additional knowledge of functions being pure to confidently do flow analysis for certain cases? #7770
