### ISSUE TITLE
control flow with instanceof not works properly

### ISSUE THREAD

**Issue by dashaus** [Microsoft/TypeScript#8383]
**TypeScript Version:** 

nightly (1.9.0-dev.20160429)

**Code**

```ts
class AAA {
    fieldA: string;
}

class BBB {
    fieldB: string;
}

class AA {
    data: AAA;
}

class BB {
    data: BBB;
}

class A {
    d: AA;
}

class B {
    d: BB;
}

function main(x: A | B) {
    for (let i of [1, 1]) {
        if (x instanceof A) {
            x.d.data.fieldA;
        } else if (x instanceof B) {
            x.d.data.fieldB; // Not compiles here. 
        }
    }
}

```

**Expected behavior:**

To access to the `fieldB` field of `BBB` class inside of block `} else if (x instanceof B) {`

**Actual behavior:** 

The compiler raises the follow error: `TS2339: Property 'fieldB' does not exist on type 'AAA'.`. 
The behavior in the version 1.8.10 is correct.

**Comment by malibuzios** [comment]
I tried to reduce the example to the simplest one possible, that still errored:

```ts
class A {
    prop: { a: string };
}

class B {
    prop: { b: string; }
}

declare let x: A | B;

while (true) {
	if (x instanceof A) {
		x.prop.a;
	} else if (x instanceof B) {
		x.prop.b; // property 'b' doesn't exist on type { a: string }
	}
}
```
If the `while` enclosure is removed the error doesn't occur (same with `for`, I only used `while` for simplicity).

**Comment by dashaus** [comment]
@malibuzios thanks!

**Comment by dashaus** [comment]
Apparently, only it occurs within iterators..

**Comment by malibuzios** [comment]
Interestingly, the type inferred within the guard is for `x` is `B` and the type inferred for `x.prop` is also correct:
```ts
    } else if (x instanceof B) {
        x; // has type B
        x.prop; // has type { b: string }
        x.prop.b; // property 'b' doesn't exist on type { a: string }
    }
```
