### ISSUE TITLE
Cannot specify array types as properties for React stateless components

### ISSUE THREAD

**Issue by pdeva** [Microsoft/TypeScript#8384]
**TypeScript Version:** 

1.8.10

**Code**

```ts
// A self-contained demonstration of the problem follows...

const ViolationsList = ({
	violations: IViolation[]
}) => (<div></div>);

```

**Expected behavior:**
This code should compile fine.

**Actual behavior:** 
Error msg printed on line containing `violations: IViolation[]`

```
error TS1005: '=' expected.
```

If i change the code to not take an array, it compiles fine:

```
const ViolationsList = ({
	violations: IViolation
}) => (<div></div>);
```

This is a serious bug in typescript.

**Comment by DanielRosenwasser** [comment]
Unfortunately colons in binding patterns rename the destructured property with the name on the left side as whatever you have on the right side.

I think you want something like

```ts
const ViolationsList = ({ violations }: { violations: IViolation[] }) => <div></div>
```
