### ISSUE TITLE
TypeScript to generate named registers rather than anonymous registers

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#8385]
_From @hanijizan on April 29, 2016 18:16_

I'm using Angular2 with SystemJS. I ran across a few issues which came down to the fact that TypeScript compiler generates anonymous registers rather than named registers:

```js
System.register([...deps...], ...); //Generated by TypeScript compiler
System.register('myModule', [...deps...], ...); //How to get the compiler to do this instead?
```

This is for purpose of bundling. I like to do what Angular2 does already for my own components. Put multiple System.register calls in one minified file then import the root component.

How to accomplish this?

tsconfig:

```json
{
  "compileOnSave": true,
  "compilerOptions": {
    "target": "es3",
    "module": "system",
    "moduleResolution": "node",
    "inlineSourceMap": true,
    "inlineSources": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": false
  }
}
```
_Copied from original issue: Microsoft/TypeScript-Handbook#265_

**Comment by mhegazy** [comment]
you can 1. specify `--out`, and automatically get names, or 2. use `/// <amd-module name="..." />` (see http://www.typescriptlang.org/docs/handbook/triple-slash-directives.html).

**Comment by hanijizan** [comment]
Only options is to use `--out` because as i understood, `/// <amd-module name="..." />` will result in `define('myModule', [...deps...], ...)` instead of `System.register('myModule, [...deps...], ...)`.

**Comment by mhegazy** [comment]
>  because as i understood, /// <amd-module name="..." /> will result in define('myModule', [...deps...], ...) instead of System.register('myModule, [...deps...], ...).

this not correct. the shape of the module is managed by `--module` argument. for instance

```ts
/// <amd-module name="mymod" />
export var x = 0;
```

compiled with `--module amd`:

```js
define("mymod", ["require", "exports"], function (require, exports) {
    "use strict";
    /// <amd-module name="mymod" />
    exports.x = 0;
});
```

compiled with `--module system`:

```js
System.register("mymod", [], function(exports_1, context_1) {
    "use strict";
    var __moduleName = context_1 && context_1.id;
    var x;
    return {
        setters:[],
        execute: function() {
            /// <amd-module name="mymod" />
            exports_1("x", x = 0);
        }
    }
});
```

**Comment by hanijizan** [comment]
OK this is great. Would it be more meaningful to rename `<amd-module>` to `<module>`?

**Comment by mhegazy** [comment]
we can not remove support for `amd-module` that would break user code. so we are stuck with this one, should we add another one, i am inclined to say 1 is better than 2.

**Comment by mindplay-dk** [comment]
I agree with @hanijizan, the `amd-` qualifier in the tag-name is misleading - I assumed this was amd-specific and had to find this thread to learn otherwise.

@mhegazy why not deprecate rather than remove? If anyone is using it now, they're likely using it for amd - they may be expecting it not to work with anything else. If they're targeting other module-types besides amd, it's confusing to see an `amd-module` tag in the file.
