### ISSUE TITLE
Update ASP.net documentation to use tsconfig.

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript#8402]
Here is the link: https://github.com/microsoft/TypeScript/wiki/Using-TypeScript-With-ASP.NET-5

courtesy of @deni35 in https://github.com/Microsoft/TypeScript/issues/4161#issuecomment-215984022

**Comment by deni35** [comment]
> for now here is a better tutorial for ASP.Net and TS: https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/quick-start/asp-net-core.md

Images is not loading.

I think example of Angular 2 is excess. 
Better leave only how to create and set up asp.net project for front-end development. And describe this in more detail because most front-end developers know nothing about asp.net and back-end.

**Comment by mhegazy** [comment]
images should be working correctly now. also the name of the file has changed, here is the link https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/tutorials/ASP.NET%20Core.md
