### ISSUE TITLE
static inheritence behavior

### ISSUE THREAD

**Issue by amirsaber** [Microsoft/TypeScript#8406]
Consider such a scenario:

```typescript
class A{
    public static foo(){
        console.log("A Foo"):
    }
   public static bar(){
        this.foo();
        console.log("A Bar");
   }
}

class B extends A{
    public static foo(){
        console.log("B Foo"):
        super.foo();
    }
   public static bar(){
        super.bar();
        this.foo();
        console.log("B Bar");
   }
}

B.bar();
```

I was expecting to get:

```
A Foo
A Bar
B Foo
A Foo
B Bar
```

but what I am actually getting is:

```
B Foo
A Foo
A Bar
B Foo
A Foo
B Bar
```

Is this an expected behavior and my assumptions are wrong or actually it's an issue??
[Playground link](http://www.typescriptlang.org/play/#src=class%20A%7B%0D%0A%20%20%20%20public%20static%20foo()%7B%0D%0A%20%20%20%20%20%20%20%20alert(%22A%20Foo%22)%3B%0D%0A%20%20%20%20%7D%0D%0A%20%20%20public%20static%20bar()%7B%0D%0A%20%20%20%20%20%20%20%20this.foo()%3B%0D%0A%20%20%20%20%20%20%20%20alert(%22A%20Bar%22)%3B%0D%0A%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Aclass%20B%20extends%20A%7B%0D%0A%20%20%20%20public%20static%20foo()%7B%0D%0A%20%20%20%20%20%20%20%20alert(%22B%20Foo%22)%3B%0D%0A%20%20%20%20%20%20%20%20super.foo()%3B%0D%0A%20%20%20%20%7D%0D%0A%20%20%20public%20static%20bar()%7B%0D%0A%20%20%20%20%20%20%20%20super.bar()%3B%0D%0A%20%20%20%20%20%20%20%20this.foo()%3B%0D%0A%20%20%20%20%20%20%20%20alert(%22B%20Bar%22)%3B%0D%0A%20%20%20%7D%0D%0A%7D%0D%0A%0D%0AB.bar())
Thanks in advance.

**Comment by kitsonk** [comment]
What you are getting is expected.  In JavaScript and ergo TypeScript, `this` will always refer to the instance at runtime, which in the case of a static class member, will be a reference to `B` and whenever `B` calls `A` via `super()`, `this` will still be `B`, which following your code is what is occurring.

**Comment by amirsaber** [comment]
Thanks @kitsonk for your reply. Just to make it clear for myself, so my best bet to achieve my desired behaviour I should call `class A` using it's name instead of `super`, right?

**Comment by mhegazy** [comment]
>  so my best bet to achieve my desired behaviour I should call class A using it's name instead of super, right?

if this is what you want then yes. if you want to allow your derived classes to override the implementation, use `this`.
