### ISSUE TITLE
using function signature in a generic type

### ISSUE THREAD

**Issue by mattiamanzati** [Microsoft/TypeScript#8409]
Hi all,
What I would like to achieve is to let the compiler know that the extend function will take in any function, and return a function with the same type signature and a little different output type (wrapped in another object); is that possibile in typescript?
Diving into the manual this is the most likely result I could achieve; but it is'nt what should be expected.

Thanks for any help,
Mattia Manzati. 

THE PROBLEM: https://www.typescriptlang.org/play/index.html#src=%2F%2F%20a%20sample%20function%0D%0Afunction%20create(id%3A%20string%2C%20a%3A%20string%2C%20c%3A%20string)%7B%0D%0A%09return%20%7B%0D%0A%09%09type%3A%20%22OK%22%2C%0D%0A%09%09id%2C%0D%0A%09%09a%0D%0A%09%7D%3B%0D%0A%7D%0D%0Afunction%20create2(id%3A%20string%2C%20a%3A%20boolean%2C%20c%3A%20number)%7B%0D%0A%09return%20%7B%0D%0A%09%09type%3A%20%22OK%22%2C%0D%0A%09%09id%2C%0D%0A%09%09a%0D%0A%09%7D%3B%0D%0A%7D%0D%0A%0D%0A%2F%2F%20takes%20in%20a%20function%20and%20returns%20it%20wrapped%20inside%20another%20object%0D%0Afunction%20extend%3CT%2C%20J%3E(fn%3A%20(...s%3A%20T%5B%5D)%20%3D%3E%20J%20)%7B%0D%0A%09return%20(...args%3A%20T%5B%5D)%20%3D%3E%20(%7B%0D%0A%09%09type%3A%20%22string%22%2C%0D%0A%09%09payload%3A%20fn(...args)%0D%0A%09%7D)%3B%0D%0A%7D%0D%0A%0D%0A%2F%2F%20works%20as%20long%20as%20the%20parameters%20are%20all%20of%20the%20same%20type%0D%0A%2F%2F%20but%20what%20about%20create(id%3A%20string%2C%20a%3A%20boolean%2C%20c%3A%20number)%20%3F%0D%0Avar%20a%20%3D%20extend(create)%3B%0D%0A%0D%0A%2F%2F%20this%20does'nt%20work%0D%0Avar%20b%20%3D%20extend(create2)%3B%0D%0A%0D%0A%2F%2F%20also%2C%20the%20type-hinter%20is'nt%20able%20to%20recognize%20that%20the%20signature%20is%20%0D%0A%2F%2F%20(id%3A%20string%2C%20a%3A%20string%2C%20c%3A%20string)%20and%20not%20(...args%3A%20string%5B%5D)

**Comment by kitsonk** [comment]
These how-to questions are best asked on StackOverflow or other support/discussion forums for TypeScript.

**Comment by mattiamanzati** [comment]
This is not an how-to question, this is mostly a "missing feature" question; could be this implemented in typescript? I see also other typings using strange solutions to this problem (like redux-saga)

**Comment by mhegazy** [comment]
the definition listed states that all the types are the same:
```ts
function extend<T, J>(fn: (...s: T[]) => J ) ..
```

in the case of `create2` there is not a `T` to infer, so you get the error. 

TypeScript has no way to define variadic types at the time being. issue https://github.com/Microsoft/TypeScript/issues/5453 tracks adding this support. 

for now your best bet to work around this is to define explicitly signatures for the first n overloads:

```ts
function extend<T1, J>(fn: (s1: T1) => J ) : (s1: T1) => { type:string, payload: J};
function extend<T1, T2, J>(fn: (s1: T1, s2: T2) => J ) : (s1: T1, s2: T2) => { type:string, payload: J};
function extend<T1, T2, T3, J>(fn: (s1: T1, s2: T2, s3: T3) => J ) : (s1: T1, s2: T2, s3:T3) => { type:string, payload: J};
....
function extend<J>(fn: (...s: any[]) => J ); // catch all
function extend<J>(fn: (...s: any[]) => J ){
	return (...args: any[]) => ({
		type: "string",
		payload: fn(...args)
	});
}
```

**Comment by mhegazy** [comment]
closing in favor of #5453

**Comment by mattiamanzati** [comment]
@mhegazy Thanks! I don't know that this thing was named variadic types! Thanks for pointing out!
