### ISSUE TITLE
VS Debugger broken with certain WebPack generated sourcemaps/bundles 

### ISSUE THREAD

**Issue by henrify** [Microsoft/TypeScript#8414]
Visual Studio 2013.5 and 2015.2 debugger doesn't work if bundle and sourcemap is generated with WebPack AND 'when' -library is included in the bundle. Debugging with anything else than VS works.

The original issue with full details and a ready to run repro solution is here: https://github.com/cujojs/when/issues/486

Would be great if you could at least determine why exactly Visual Studio debugger doesn't accept this sourcemap.

**Comment by mhegazy** [comment]
can you provide more details? a sample project would be great too.

**Comment by mhegazy** [comment]
//CC @sheetalkamat

**Comment by henrify** [comment]
@mhegazy hi, as mentioned, full repro solution as .zip and all details are in this issue: cujojs/when#486

**Comment by sheetalkamat** [comment]
@henrify I looked into the sourcemap and it seems the sourcemap contains sourcename as
```"file://ignored C:\\Users\\shkamat\\Desktop\\WebpackWhenSourcemapTest\\WebpackWhenSourcemapTest\\WebpackWhenSourcemapTest\\node_modules\\when\\lib vertx"```
Which is resulting in the error message in output window as 
```Error decoding sourcemap contents```

The url in the source contents is not a valid URL which is why decoder fails to go ahead further with it.

**Comment by henrify** [comment]
@sheetalkamat yes as discussed in the linked issue, I noticed that too, and built a custom version of the 'When' library which doesn't have that entry at all, but it still fails to debug.

Do you see anything else wrong in the sourcemap?

**Comment by henrify** [comment]
@sheetalkamat i made a ready to run repro solution for you.

This has pre-installed the custom built 'When' NPM module which eliminates the problem URL. Just run 'webpack' on the project's directory and then try to debug in VS.

[WebpackWhenSourcemapTest.zip](https://github.com/Microsoft/TypeScript/files/251314/WebpackWhenSourcemapTest.zip)

**Comment by sheetalkamat** [comment]
@henrify Looking into it and will let you know whats going on.

**Comment by sheetalkamat** [comment]
@henrify , I haven't heard from you but I have made change in debugger to load files with invalid url syntax if they have inline source.With that change I am able to load your project correctly and hit breakpoints. New version of debugger should fix this for you.

**Comment by henrify** [comment]
@sheetalkamat Ups sorry, I had missed your comment about the broken zip.

There must be more to the story than just the invalid url syntax though, as the (broken) zip with custom build of 'When' library without the invalid syntax stuff still didn't work..

**Comment by henrify** [comment]
@sheetalkamat So it appears that GitHub does not send notification when you edit a message, and thus I never got the 'Update I'm not able to open...' part.

I assume that you don't need retry of the broken zip, if my project from the linked issue is anyway working on your computer after the latest changes to debugger?

Anyway, thanks for your help on this issue, and I look forward to having a working debugger again :)
