### ISSUE TITLE
explicit public access modifier stripped from .d.ts generated by tsc --declaration 

### ISSUE THREAD

**Issue by rozzzly** [Microsoft/TypeScript#8417]
**TypeScript Version:** 1.8.10

So when I use the `--declaration` cli flag on `tsc`, or its corollary in `tsconfig.json`, I found that the definitions it produces have the **`public`** keyword stripped out. I couldn't find anything about why this might be on google, but did see that when there is no modifier present, **`public`** is assumed. Looking around at some popular type definitions, they also seem to lack the keyword. So, obviously its not needed. But, if I write it in my source, why not carry that over to the definition? It doesn't seem to affect the inference engines of the editors I quickly tested. So even if this is negligible, why not let it through? I like my code to be ~~statically~~ **_brutally_**-typed. I think it makes my intentions clearer as to what I would intend be exposed as an API to consuming developers. I see some potential for how this could be used by an IDE to rank symbols during autocomplete, and even more importantly, for auto generating documentation.

Is there some reason behind this? pragmatically/legacy/or otherwise? It seems like it would be a trivial fix. Interested to hear everyone's thoughts!

**Code**
_file:_    <kbd>Foo.ts</kbd>
```ts
class Foo {
    public memberPublic: string;
    public methodPublic(): number {
        // ...
    }
    private memberPrivate: string;
    private methodPrivate(): number {
        // ...
    }
    protected memberProtected: string;
    protected methodProtected(): number {
        // ...
    }
}
export default Foo;
```
_file:_    <kbd>tsconfig.json</kbd>
```json
{
  "compilerOptions": { /* same result when I use */
    "target": "es2015", /* es5 */
    "module": "es2015", /* commonjs */
    "moduleResolution": "node",
    "sourceMap": true,
    "declaration": true,
    "noImplicitAny": true,
    "noLib": false,
    "outDir": "lib",
    "allowSyntheticDefaultImports": true,
    "removeComments": false,
  },
  "exclude": [
    "typings/browser.d.ts",
    "typings/browser",
    "node_modules",
    "lib"
  ]
}

```

**Expected behavior:**
_file:_    <kbd>Foo.d.ts</kbd>
```ts
declare class Foo {
    public memberPublic: string;
    public methodPublic(): number;

    private memberPrivate: string;
    private methodPrivate(): number;

    protected memberProtected: string;
    protected methodProtected(): number;
}
export default Foo;
```
**Actual behavior:** 
_file:_    <kbd>Foo.d.ts</kbd>
```ts
declare class Foo {
    memberPublic: string;
    methodPublic(): number;

    private memberPrivate: string;
    private methodPrivate(): number;

    protected memberProtected: string;
    protected methodProtected(): number;
}
export default Foo;
```

**Comment by rozzzly** [comment]
As a side note... this might warrant its own issue, and probably has a larger potential for negative effects...

if my `target` and `module` are both set to `es2015` in `tsconfig.js`

_file:_    <kbd>Foo.ts</kbd>
```ts
class Foo {
    // ...
}
export default Foo;
```
_file:_    <kbd>Foo.d.ts</kbd>
```ts
declare class Foo {
    // ...
}
export default Foo;
```

but if I have `export default` directly in front of the `class`

_file:_    <kbd>Bar.ts</kbd>
```ts
export default class Foo {
    // ...
}
```
_file:_    <kbd>Bar.d.ts</kbd>
```ts
export default class Bar { // notice what's missing?
    // ...
}
```

in that case there's no `declare` keyword... I'd image that could have some complications for projects consuming such a definition. I just noticed this, haven't had time to experiment so I'm not sure, maybe this edgecase has already been considered? I did however find that `export class FooBar` --> `export declare class FooBar` so it sounds to me like `default` is the culprit.

I'm getting off now, but I'll play around tomorrow, see what consequences that has.

**Comment by kitsonk** [comment]
As far as the first, it is most likely that `public` is implicit anyways, and therefore redundant and the compiler probably just internally "ignores" it therefore it doesn't come out on the emit.  Because the presence or lack of the `public` keyword has no effect on someone consuming the typings, I suspect it will be considered more of a hygiene thing versus defect.

For the second, because the declared class only would have been in scope of the module's namespace, both emits are correct.  If the class had been declared without being exported, there would have been no way to reference the class from outside the module.

**Comment by mhegazy** [comment]
The rational here for stripping out `public` and `export` when implicitly known is to make the .d.ts look less cluttered and more readable. A .d.ts is for public API, so by default everything would read as `public`, no need to rewrite it in front of every declaration.

As for the `declare`, again it is implicitly known from the context (either in a .d.ts file or wrapped in a `declare module "mod" { ...}` declaration). again same reason, make the declaration file easier to read and less cluttered.

Also note that `declare` is not allowed within ambient declarations for the same reason.

**Comment by rozzzly** [comment]
Thanks for the response guys. While I don't necessarily agree with that rational, I do understand the thinking behind it. And thanks for clearing up my question about `declare`.
