### ISSUE TITLE
Regression: TypeScript no longer awaits custom Promises

### ISSUE THREAD

**Issue by RReverser** [Microsoft/TypeScript#8423]
**TypeScript Version:** 

1.9.0-dev.20160502

**Code**

```ts
declare namespace Windows.Foundation {
    interface IPromise<TResult> {
        then<U>(success?: (value: TResult) => IPromise<U>, error?: (error: any) => IPromise<U>, progress?: (progress: any) => void): IPromise<U>;
        then<U>(success?: (value: TResult) => IPromise<U>, error?: (error: any) => U, progress?: (progress: any) => void): IPromise<U>;
        then<U>(success?: (value: TResult) => U, error?: (error: any) => IPromise<U>, progress?: (progress: any) => void): IPromise<U>;
        then<U>(success?: (value: TResult) => U, error?: (error: any) => U, progress?: (progress: any) => void): IPromise<U>;
        done<U>(success?: (value: TResult) => any, error?: (error: any) => any, progress?: (progress: any) => void): void;

        cancel(): void;
    }
}

async function sample(promise: Windows.Foundation.IPromise<number>) {
    var number = await promise;
}
```

**Expected behavior:**
No error, as this is an await-compatible Promise definition; more concretely, those are definitions for UWP APIs and they worked well with a stable TypeScript.

**Actual behavior:** 
Compiler emits an error `Operand for 'await' does not have a valid callable 'then' member.`.

**Comment by mhegazy** [comment]
Please see https://github.com/Microsoft/TypeScript/issues/6068 for more details.

**Comment by RReverser** [comment]
@mhegazy Doesn't look like a duplicate - that issue seems to be describing setting global `Promise` to another value, while this one is about using custom implementation that exists under a custom name, while does fulfill thenable interface.

**Comment by mhegazy** [comment]
sorry about that. indeed the wrong reference.

**Comment by mhegazy** [comment]
but i do not get an error for this locally. looks like there is something else going on.. can you share more code?

**Comment by RReverser** [comment]
Well, I limited to this minimal example and I'm certainly seeing this error. Perhaps something in the config, let me try without one.
P.S. Please reconsider the `Duplicate` label :)

**Comment by RReverser** [comment]
Okay, this seems to be happening only when `strictNullChecks` is enabled.

**Comment by RReverser** [comment]
@mhegazy Please let me know if any other details are needed for this bug.

**Comment by vladima** [comment]
I can repro this.

**Comment by Arnavion** [comment]
While you're at it, could you also make that error list exactly how the `then` is not the expected signature in the general case? For example could you print out the types for both and how they disagree like the generic mismatching types error?

**Comment by RReverser** [comment]
@mhegazy Thank you! Fast as always, it's a pleasure to be beta-tester :)

**Comment by mhegazy** [comment]
> While you're at it, could you also make that error list exactly how the then is not the expected signature in the general case? For example could you print out the types for both and how they disagree (just like the error for mismatching types in general does)?

For this specific check, it actually passed. First we try to get the promised type from the `then` signatures if that failed, we want to make sure the type does not have a `then` property on it, or it might be used, and you can get an unexpected behavior at runtime. so we compare it to something that has a `then` in this case it passes.

the issue was a bit earlier than this specif check, during getting the promised type; now that undefined is added to optional arguments by default, we try to get the signature of a union type of first arg in all overloads and it fails as undefined does not have any signatures.

**Comment by mhegazy** [comment]
Thanks @RReverser! we do appreciate you feedback, keep the reports coming.
