### ISSUE TITLE
Typings for NPM Packages not working

### ISSUE THREAD

**Issue by tomitrescak** [Microsoft/TypeScript#8431]
According to instructions here: http://www.typescriptlang.org/docs/handbook/typings-for-npm-packages.html

Typescript should be able to resolve typings stored in NPM packages. Yet, even when I have all thing in place, the compilation fails.

I have a node module "kadira/storybook" in node_modules directory.

This module correctly references `typings: "./lib/typings.d.ts"` in package.json

Any ideas?

**Comment by kitsonk** [comment]
What version of TypeScript?

What compiler options are you using?

When you say compilation fails, what exactly do you get?

Some basic information would likely help provide a better answer.

**Comment by tomitrescak** [comment]
I apologise for the lack of detail.

* Typescript: 1.9.0-dev.20160302
* Error: `src/stories/message.tsx(2,35): error TS2307: Cannot find module '@kadira/storybook'.`
* tsconfig.json:
  ```
  "compileOnSave": true,
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "declaration": false,
    "noImplicitAny": true,
    "removeComments": false,
    "noLib": false,
    "preserveConstEnums": true,
    "outDir": "../dist",
    "suppressImplicitAnyIndexErrors": true,
    "jsx": "react",
    "experimentalDecorators": true,
    "sourceMap": false,
    "allowSyntheticDefaultImports": true
  },
  "filesGlob": [
    "src/**/*.ts",
    "src/**/*.tsx"
  ]
}
  ```

from what I can tell only manually adding the .d.ts file to the glob list helped the issue:

```
"filesGlob": [
    "src/**/*.ts",
    "src/**/*.tsx",
    "node_modules/@kadira/storybook/lib/*.d.ts"
  ],
```

While this is ok, it is not as automated as typescript make it look.

**Comment by kitsonk** [comment]
Everything in that case looks fine, but I wonder if the module resolution is challenged with the name spaced node module.  I am sure @vladima will be along in a bit to take a look.

**Comment by vladima** [comment]
can you try to compile with [traceResolution](https://github.com/Microsoft/TypeScript-Handbook/blob/release-2.0/pages/Module%20Resolution.md#tracing-module-resolution) option being enabled to see where compiler was looking for modules?

**Comment by tomitrescak** [comment]
@vladima thanks for that, my tsc was saying "unknown parameter" so I updated the typescript to latest and all problems were gone. Thanks for pointing out that parameter will be helpful in the future as well.
