### ISSUE TITLE
Tsuquyomi crashes frequently with latest nightly

### ISSUE THREAD

**Issue by myitcv** [Microsoft/TypeScript#8434]
_Raising here because I suspect this to be something related to `tsserver` as opposed to [Tsuquyomi](https://github.com/Quramy/tsuquyomi) itself given the relatively insignificant changes in the latter since December 2015_

cc @Quramy

This is something I've spotted over the last few days. I can't be sure when it started because it doesn't happen reliably, and indeed there aren't a specific set of steps that I can run to reproduce the issue.

```
TypeScript: 1.9.0-dev.20160429
Tsuquyomi:  9d93496 - https://github.com/Quramy/tsuquyomi/tree/9d93496c90e96ac75511ad59a93df9e2fd627f6f
Vim:        NVIM v0.1.5-83-g3dc8cdc
```

The follow error is triggered when I try to initiate a [completion](https://github.com/Quramy/tsuquyomi#completion):

```
Error detected while processing function tsuquyomi#complete:
line   38:
E716: Key not present in Dictionary: 0
Press ENTER or type command to continue
```

Once I have encountered this error, Tsuquyomi effectively "falls over" (although the `tsserver` process is still running) - i.e. I can't attempt any further completions. ~~The situation is only "reset" by me saving the file, at which point I can try again.~~

Anyone else seeing this? Perhaps not specifically with Tsuquyomi but with other `tsserver` clients (which would clearly result in different non-Tsuquyomi specific errors)?

**Comment by myitcv** [comment]
Correction to the above: sometimes saving the file does not "reset" Tsuquyomi.

Tsuquyomi will check for errors in a file on save (and show those errors in the quick fix window). Sometimes, much like the completions breaking randomly, this feature also does not work. i.e. assuming a file is known to have errors, after a `:w` no errors will show (again, almost like Tsuquyomi/`tsserver` has failed/fallen over in some way). When this happens, such a save does not "reset" Tsuquyomi as previously mentioned.

**Comment by Quramy** [comment]
I think it's because that there may be change in tsserver's `reload` command.

I took log of tsserver with 1.8.10 and 1.9.0-dev.20160429.

* with tsserver 1.8.10

```
Open file roots of inferred projects: 
Open files referenced by inferred or configured projects: 
Open file roots of configured projects: 
/Users/yosuke/workspaces/javascript/tsuquyomi-issue-ts8434/src/app.ts
Perf 6    Async elapsed time (in milliseconds): 758.7637
Info 7    request: {"seq":0,"arguments":{"file":"/Users/yosuke/workspaces/javascript/tsuquyomi-issue-ts8434/src/app.ts","tmpfile":"/var/folders/v_/3xh1qs_s56968pmj8qb4sx6jd8gp06/T/vMQc1HL/7"},"type":"request","command":"reload"}
Info 8    response: {"seq":0,"type":"response","command":"reload","request_seq":0,"success":true}
Perf 9    Async elapsed time (in milliseconds): 2.3352
Info 10   request: {"seq":1,"arguments":{"file":"/Users/yosuke/workspaces/javascript/tsuquyomi-issue-ts8434/src/app.ts","offset":1,"line":2,"prefix":""},"type":"request","command":"completions"}
Perf 11   Elapsed time (in milliseconds): 87.0473
```

* with tsserver 1.9.0-dev.20160429

```
Open file roots of inferred projects: 
Open files referenced by inferred or configured projects: 
Open file roots of configured projects: 
/Users/yosuke/workspaces/javascript/tsuquyomi-issue-ts8434/src/app.ts
Perf 6    Async elapsed time (in milliseconds): 751.0888
Info 7    request: {"seq":0,"arguments":{"file":"/Users/yosuke/workspaces/javascript/tsuquyomi-issue-ts8434/src/app.ts","tmpfile":"/var/folders/v_/3xh1qs_s56968pmj8qb4sx6jd8gp06/T/vGNkYVT/7"},"type":"request","command":"reload"}
Info 8    response: {"seq":0,"type":"response","command":"reload","request_seq":0,"success":true}
Perf 9    Elapsed time (in milliseconds): 4.4036
Info 10   response: {"seq":0,"type":"response","command":"reload","request_seq":0,"success":true,"body":{"reloadFinished":true}}
Info 11   request: {"seq":1,"arguments":{"file":"/Users/yosuke/workspaces/javascript/tsuquyomi-issue-ts8434/src/app.ts","offset":1,"line":2,"prefix":""},"type":"request","command":"completions"}
Perf 12   Elapsed time (in milliseconds): 112.7945
```

In 1.9.0-dev, there was one more response, `{"seq":0,"type":"response","command":"reload","request_seq":0,"success":true,"body":{"reloadFinished":true}}` (Info 10).

Tsuquyomi was mistaken the second `reload` response for the response of the `compeletions` command.

**Comment by Quramy** [comment]
I cannot find the `reloadFinished` key in the `protocol.d.ts`. I think that the 2nd response of the `reload` command was slipped in unexpectedly and I hope that it should be removed.

**Comment by vladima** [comment]
this is a deliberate change in protocol introduced in https://github.com/Microsoft/TypeScript/pull/8244 to address https://github.com/Microsoft/TypeScript/issues/4420, sorry for the break

**Comment by Quramy** [comment]
@vladima ok, i got it. I'll modify my plugin to suit this.

**Comment by myitcv** [comment]
@Quramy - thank you very much for your analysis, response and fantastic plugin!

**Comment by myitcv** [comment]
Thanks @vladima. I'll close this issue and open a corresponding issue in https://github.com/Quramy/tsuquyomi
