### ISSUE TITLE
Getters are not control flow analysed

### ISSUE THREAD

**Issue by tinganho** [Microsoft/TypeScript#8437]
```ts
class A {
    private something: string;
    
	public get id(): string | null {
        return null;
    }
    
    public doSomethingUseful() {
        if (this.id) {
            this.something = this.id; // Error can be null
        }
    }
}
```

**Comment by ahejlsberg** [comment]
I'm inclined to agree this is a bug, but obviously there's no guarantee that an accessor will return the same value the next time it is invoked. It's sort of akin to saying that if a function call `foo()` returns a truthy value, then we should assume it will also return a truthy value the next time it is called.

**Comment by mhegazy** [comment]
this is a bit too pedantic. For an interface property, there is no guarantee it was implemented as an accessor, so not sure why this would be any different.

**Comment by tinganho** [comment]
Sorry, I actually missed that it was being called 2 times. But I think I agree with @ahejlsberg then.

**Comment by ahejlsberg** [comment]
Well, @mhegazy has a point too. I'm inclined to fix it, so I'm going to reopen the issue.
