### ISSUE TITLE
Incorrect control flow type narrowing in a particular case

### ISSUE THREAD

**Issue by zhuravlikjb** [Microsoft/TypeScript#8438]
```ts
function s(a: string | number | boolean | symbol) {
    if ((typeof a === "string" || typeof a === "number" || typeof a === "boolean") && true) {
        return;
    }     
    a; // symbol, that's correct
}     
```

```ts
function s(a: string | number | boolean | symbol) {
    if ((typeof a === "string" || typeof a === "number" || typeof a === "boolean") && !false) {
        return;
    }     
    a; // string | number | boolean | symbol, but should be just symbol, too
}     
```

**Comment by tinganho** [comment]
@zhuravlikjb you can highlight the code example. Just append `ts` after the three first back ticks.

**Comment by RyanCavanaugh** [comment]
We generally don't do aggressive compile-time computation, so `!false` just looks like an arbitrary expression to us (this is often desirable behavior for times when you want to e.g. modify an expression for debugging purposes). What was the intent of writing this code?

**Comment by zhuravlikjb** [comment]
@tinganho Thanks! Will use this highlighting feature further times.

@RyanCavanaugh I wanted to know which kinds of expressions are treated as constant 'true' and 'false' in TS 2.0 type guards mechanism.
And it seems quite strange, that you correctly compute expressions like "true && true" while evaluating type guards, but you don't compute expressions like "!true". Sounds like a bug, rather than a feature.

The example I provided is a test case for my own type guard evaluation engine. I want to make it compatible with the TypeScript compiler behavior, and that's why such tiny differences pop up.

**Comment by RyanCavanaugh** [comment]
We have to give up on evaluation *somewhere*, right?

* `!false`
* `1 > 0`
* `1 + 1 === 2`
* `[1, 3][1] === 3`
* `Math.round(3.4) === 3)`

**Comment by mhegazy** [comment]
We can definitely have a more sophisticated constant expression evaluation logic, but does not seem that the value delivers would be worth the effort.
