### ISSUE TITLE
Using the compiler API to transpile jsx/tsx does not seem to work

### ISSUE THREAD

**Issue by rossipedia** [Microsoft/TypeScript#8441]
I'm trying to follow the instructions [here](https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API#transpiling-single-file), specifically this part:

> If file name is omitted then compiler will check if jsx options is specified - if it is set and is not JsxEmit.None then source text will be interpreted as '.tsx'.

However, I'm not getting the expected result.

**TypeScript Version:**  

1.8.10

**Code**

## index.js
```js
const ts = require('typescript');
const fs = require('fs');

const str = fs.readFileSync(__dirname + '/test.tsx', 'utf8');
const result = ts.transpileModule(str, { fileName: 'test.tsx', compilerOptions: { 'jsx': 'React' });

console.log(result.outputText);
```

## test.tsx
```ts
/// <reference path="./typings/react/react-global.d.ts" />
interface HelloProps {
  name: string;
};

const Hello = (props: HelloProps) => (
  <div>Hello, {props.name}</div>
);
```

**Expected behavior:**

The output I'm looking for is the same as what I get if I use `tsc`:

```
> tsc --jsx react test.tsx
> cat test.js
/// <reference path="./typings/react/react-global.d.ts" />
;
var Hello = function (props) { return (React.createElement("div", null, "Hello, ", props.name)); };
```

**Actual behavior:** 

However, the output I get is instead:

```sh
> node index.js
"use strict";
/// <reference path="./typings/react/react-global.d.ts" />
;
var Hello = function (props) { return (<div>Hello, {props.name}</div>); };
```

**Comment by vladima** [comment]
this issue has the same underlying reason with #7980: there are a bunch of places in compiler API that accept enum values. These places can be easily identified when API is consumed from the TypeScript however for JavaScript consumers it is common to pass just string values instead of enums.

To fix the problem `index.js` should look like this
```javascript
const ts = require('typescript');
const fs = require('fs');

const str = fs.readFileSync(__dirname + '/test.tsx', 'utf8');
const result = ts.transpileModule(str, { fileName: 'test.tsx', compilerOptions: { 'jsx': ts.JsxEmit.React }});

console.log(result.outputText); 
```

**Comment by rossipedia** [comment]
Awesome, thanks!
