### ISSUE TITLE
Destructured Function Parameters and String Literal Types don't mix

### ISSUE THREAD

**Issue by KeepItOneHundred** [Microsoft/TypeScript#8446]
**TypeScript Version:** 

Typescript 1.8.10 + VS Code 1.0.0

**Code**

```ts
interface xhrOptions {
  // this works:
  // method?: string;
  
  // this does not work:
  method?: "GET" | "POST";
}

function xhr(url: string, { method = "GET" }: xhrOptions = {}): Promise<any> {
  return new Promise((resolve, reject) => {
    // ...
  });
}
```

**Expected behavior:**
Either form of the "method" type should be valid.

**Actual behavior:** 
The string form works as expected, but the string literal form is rejected.

![untitled](https://cloud.githubusercontent.com/assets/17903394/14996155/7825b4bc-1170-11e6-8b05-be03c474adcf.png)

**Comment by sandersn** [comment]
Looks like it's fixed in master -- I can repro it on 1.8.10 but not on master. @KeepItOneHundred, can you try compiling with `typescript@next`?
