### ISSUE TITLE
Update playground so people can choose compiler options

### ISSUE THREAD

**Issue by tinganho** [Microsoft/TypeScript#8454]
Is it possible that you can update the playground http://www.typescriptlang.org/play/? So people can choose various compiler options?

**Comment by RReverser** [comment]
Also would be great to be able to switch between stable and next version in order to test some pieces of code and easily report issues with predefined code in the playground editor.

**Comment by kitsonk** [comment]
Related to #4866

**Comment by aluanhaddad** [comment]
Great idea!

**Comment by mhegazy** [comment]
Supporting different versions is tracked under https://github.com/Microsoft/TypeScript/issues/15662

Options are already added:
![image](https://cloud.githubusercontent.com/assets/8000722/25977046/8217af3e-366d-11e7-8340-9ee5ef9bac4d.png)
