### ISSUE TITLE
Unable to run test cases through npm test Node.js

### ISSUE THREAD

**Issue by aashishab** [Microsoft/TypeScript#8455]
Hi, I am unable to execute test cases as the npm test command throwing an error as:

**Node Version:** 

2.14.7

**Error**

```
tools\tasks\build.test.ts (2,46): Module '"C:/tools/config"' has no exported member 'TEST_SPEC_DEST'.

**Comment by mhegazy** [comment]
Do not think this is the correct repo. If this is a typescript issue please refile and provide enough information to reproduce.
