### ISSUE TITLE
Are there anyway we could use es6 in vscode without jsconfig.json?

### ISSUE THREAD

**Issue by Thaina** [Microsoft/TypeScript#8462]
I want to write html/js code in vscode with es6 support. But I don't want to create a file that not relate to actual work. I just want some triple slash comment or anything that could enable es6 syntax in vscode intellisense

Is it possible?

If not then I would like to request this feature

**Comment by mhegazy** [comment]
it is not possible. tsconfig.json/jsconfig.json is the only supported way to pass configurations to your editors. please note that the file needs to be in one of the parent directories of your sources, so it can be at a higher level and apply to all your projects for instance.

also see https://github.com/Microsoft/TypeScript/issues/6398 for relevant discussion

**Comment by mhegazy** [comment]
I should also note that there is no intention to add additional methods to set options at the time being. the reason tsconfig/jsconfig exist is to have one standard way of passing configurations to different editors.

**Comment by mhegazy** [comment]
Also consider putting tsconfig.json in your .gitignore file if you do not want to push it to your repo.
