### ISSUE TITLE
Remove restriction on external module augmentations introducing new top-level names

### ISSUE THREAD

**Issue by RyanCavanaugh** [Microsoft/TypeScript#8478]
> Module augmentation cannot introduce new names in the top level scope

This error is stopping us from accurately representing UMD-augmenting modules like `moment-range`. While it's a correct restriction for *ES6 values*, it's not correct for legacy modules, nor is it a correct restriction for types (e.g. you might want to write an `interface` in a module augment to provide a type of a new overload parameter)

**Comment by mhegazy** [comment]
@vladima any concerns here?

**Comment by kitsonk** [comment]
Just ran across this while trying to convert to UMD definitions, glad it is fixed. Just wanted to mention too, there is nothing preventing an ES6 module from grabbing a reference to global and augmenting it.  For example, this is completely valid:

```javascript
'use strict';
const global = Function('return this')();
global.foo = 'bar';
console.log(foo); // logs "bar"
```
