### ISSUE TITLE
[lib.d.ts]DataTransfer define error

### ISSUE THREAD

**Issue by twoeo** [Microsoft/TypeScript#8493]
**TypeScript Version:** 

1.8.9

**Code**
```ts
onDragStart(e){
  e.dataTransfer.setData('dragTarget', e.currentTarget)
}
```

**Expected behavior:**

Build Success

**Actual behavior:** 

error TS2345: Argument of type 'number' is not assignable to parameter of type 'string'.

**Reason**
In lib.d.ts

```
interface DataTransfer {
    //...
    getData(format: string): string;
    setData(format: string, data: string): boolean;
}
```

setData should be   setData(format:string, **data:any**):boolean
as getData should return **any**

**Comment by kitsonk** [comment]
The [specification is pretty clear](https://w3c.github.io/html/editing.html#ref-for-dom-datatransfer-setdata-1) that it is a DOMString.  Implicit coercion can be unsafe and is one of the big arguments for something like TypeScript.  So while it technically works at runtime, that doesn't mean it should be typed that way.  Typing it as `any` would open up people passing `setData('dragTarget', { foo: 'bar' })` which is clearly a defect.
