### ISSUE TITLE
target not support ES7 in jsconfig.json file

### ISSUE THREAD

**Issue by jrieken** [Microsoft/TypeScript#8495]
_From @welefen on November 20, 2015 5:48_

target not support ES7 in jsconfig.json file

_Copied from original issue: Microsoft/vscode#311_

**Comment by jrieken** [comment]
_From @scottaddie on November 21, 2015 2:54_

@welefen Not sure if you noticed or not, but there is experimental support for ES7 decorators. In your jsconfig.json file, use the `experimentalDecorators` option:

```json
{
	"compilerOptions": {
		"target": "ES6",
		"module": "commonjs",
		"experimentalDecorators": true
	}
}
```

That seems to be all the ES7 support you get at this time.

**Comment by jrieken** [comment]
_From @felixfbecker on November 21, 2015 17:45_

What about `async`/`await`?! See #408

**Comment by jrieken** [comment]
_From @warpdesign on May 5, 2016 9:17_

+1
Would love support for ES7 too.

Maybe it has changed since last year and there are new ES7-related options available ?

For example new function bind `::` operator would be great.

**Comment by jrieken** [comment]
moving this to TypeScript from which VS Code gets TS and JS smartness

**Comment by kitsonk** [comment]
Covered by #4692 which is committed but not aligned to a particular Milestone.

**Comment by mhegazy** [comment]
note that ES7 (aka ES 2016) is done. decorators, object literal spread rest, SIMD, async functions etc .. is not part of ES7/ES2016. 

ES7/ES2016 only has exponentiation operator and array.include. I think what you are look for is `ES  Next` target. this is tracked by https://github.com/Microsoft/TypeScript/issues/5361
