### ISSUE TITLE
Comma parsing oddity

### ISSUE THREAD

**Issue by mucaho** [Microsoft/TypeScript#8497]
**TypeScript Version:** 

Version 1.8.10

**Code**

```ts
console.log('Add a comma to the end of this statement!')
(<any>{})['key'] = (<any>{})['key'];
```

**Expected behavior:**
No error.
**Actual behavior:** 
`error TS2349: Cannot invoke an expression whose type lacks a call signature.`

**Comments**
Add a `;` to the end of the `console.log` statement and the error disappears.
Is this an error or by design?

**Comment by mucaho** [comment]
Hmm, seems like this is JS specific
```js
console.log('asd')
(function() {})()
```
also throws an error.

**Comment by basarat** [comment]
Just be sure to use semicolons before any of `[(` if the start of a line. e.g. 

`;[].forEach`
and 
`;(function(){})`

Or just use them everywhere https://basarat.gitbooks.io/typescript/content/docs/styleguide/styleguide.html#semicolons :rose:
