### ISSUE TITLE
interface optional methods not showing 

### ISSUE THREAD

**Issue by pankleks** [Microsoft/TypeScript#8498]
**TypeScript Version:** 

1.8.30

**Code**

```ts
interface ITest {
  init?();
}

class Test implements ITest {
  print() {
    if (typeof this.init == "function")
      this.init();
  }
}

class MyOwnTest extends Test {
  init() {
    // boo!  
  }
}
```

**Expected behavior:**
compiles without error

**Actual behavior:** 
Property 'init' does not exist in 'Test'

Why such construction? 
I would like to provide optional implementation of `init` in user derived type, and check in base class if it was really implemented.

today I have to use `this["init"]` - which is not strong type.

**Comment by malibuzios** [comment]
_(tested on `1.9.0-dev.20160506`)_

It is possible to work around this by declaring an uninitialized property having a a function type in the base class:
```ts
interface ITest {
    init?(): void;
}

class Test implements ITest {
    init: () => void; // when strict null checking is enabled,
                      // '() => void | undefined' is possible here as well
    
    print() {
        if (typeof this.init == "function")
            this.init();
    }
}

class MyOwnTest extends Test {
    init = () => {
        // boo!  
    }
}
```

**Comment by pankleks** [comment]
You right - thanks!

However for me it's workaround only as in derived class you MUST use arrow function to define - can't use "regular" method syntax anymore.

So still, IMO my original syntax should be possible.

**Comment by mhegazy** [comment]
you can use a class/interface pair to define optional properties on a calss, so 
```ts
interface Test {
    init?();
}

class Test {
    print() {
        if (typeof this.init == "function")
            this.init();  // OK
    }
}
```

**Comment by mhegazy** [comment]
the other option is to use abstract classes/methods. not sure if this fits your requirements though,

**Comment by pankleks** [comment]
Not obvious but works. 
Thanks - closing item.
