### ISSUE TITLE
Preventing a PropertyDecorator from being used as a MethodDecorator

### ISSUE THREAD

**Issue by remojansen** [Microsoft/TypeScript#8499]
I have a PropertyDecorator and I want to prevent users form applaying it to a method but the compilers seems to be not detecting the error:

```ts
let decPropTest: PropertyDecorator = function(
	target: Object, 
	propertyKey: string
): void {
	
}

let decMethTest: MethodDecorator = function (
	target: Object, 
	propertyKey: string,
	descriptor: any
): void {
	return descriptor
}

class SomeComponent {

	@decPropTest
	@decMethTest // Error (expected)
	public service: number;
	
	@decPropTest // Not Error ???
	@decMethTest
	public test() {}
}
```

Live demo is available [here](https://www.typescriptlang.org/play/#src=let%20decPropTest%3A%20PropertyDecorator%20%3D%20function(%0D%0A%09target%3A%20Object%2C%20%0D%0A%09propertyKey%3A%20string%0D%0A)%3A%20void%20%7B%0D%0A%09%0D%0A%7D%0D%0A%0D%0Alet%20decMethTest%3A%20MethodDecorator%20%3D%20function%20(%0D%0A%09target%3A%20Object%2C%20%0D%0A%09propertyKey%3A%20string%2C%0D%0A%09descriptor%3A%20any%0D%0A)%3A%20void%20%7B%0D%0A%09return%20descriptor%0D%0A%7D%0D%0A%0D%0Aclass%20SomeComponent%20%7B%0D%0A%0D%0A%09%40decPropTest%0D%0A%09%40decMethTest%20%2F%2F%20Error%20(expected)%0D%0A%09public%20service%3A%20number%3B%0D%0A%09%0D%0A%09%40decPropTest%20%2F%2F%20Error%20%3F%3F%3F%0D%0A%09%40decMethTest%0D%0A%09public%20test()%20%7B%7D%0D%0A%7D).

I have been looking to the [signatures of the decorators](https://github.com/Microsoft/TypeScript/blob/master/lib/lib.d.ts#L1269-L1272) but I don't see anything wrong. 

Is this a bug?

Thanks!

**Comment by mhegazy** [comment]
do not think there is much we can do. the signatures are assignable. they both have compatible types for arguments (it is OK to send more arguments to something that expects less), and the return type for both is void. so from the signatures there is nothing that says it can not work as a method decorator. 

that said, the decorator proposal is undergoing some significant changes, and the new proposal relies on mirrors that allows you to dynamically check the kind of the target, so the solution would be defensive coding inside the decorator to skip targets it does not know how to handle.
We are working with the proposal champion on finalizing the new proposal for TC39, and once we have a clear proposal that we know is finalized we will be sharing the plans for implementing it and what that means to user and library code, as well as how the transition would be managed.

**Comment by remojansen** [comment]
👍 thanks a lot, looking forward to the final proposal :)
