### ISSUE TITLE
Make `SharedArrayBuffer` type available to lib

### ISSUE THREAD

**Issue by clark-stevenson** [Microsoft/TypeScript#8505]
I am writing a definition file for a WebGL project One of the parameters looks like this  

`ArrayBuffer | SharedArrayBuffer | ArrayBufferView`

I can access `ArrayBuffer` and `ArrayBufferView` but not `SharedArrayBuffer`.  This is probably for reasons already known! I just could not find any good information.  I also do not know how to solve it and cannot issue a PR. Feel free to close if not relevant.

Thanks.

- https://www.chromestatus.com/feature/4570991992766464
- https://tc39.github.io/ecmascript_sharedmem/shmem.html

**Comment by mhegazy** [comment]
Shared memory is a proposal for TC39 and it is at stage 2 currently, see https://github.com/tc39/ecma262#current-proposals. Being a stage 2 function means that it will undergo some additional changes in the feature. 

having said that, we would be open to accepting a PR for this feature. the PR would including adding a new defintion file `es2017.sharedmemory.d.ts` in https://github.com/Microsoft/TypeScript/tree/master/src/lib, and addign support for a new `--lib` value for it, see https://github.com/Microsoft/TypeScript/blob/master/src/compiler/commandLineParser.ts#L367-L395

**Comment by mhegazy** [comment]
Should be available under `--lib es2017.sharedmemory`
