### ISSUE TITLE
Array.prototype.findIndex jsdoc is incorrect

### ISSUE THREAD

**Issue by basarat** [Microsoft/TypeScript#8506]
From https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/findIndex

> The findIndex() method returns an index in the array, if an element in the array satisfies the provided testing function. Otherwise -1 is returned.

^ this is what I experienced at runtime (i.e. `-1` return value). However the definition in `lib.d.ts` for *various* `Array<T>` interfaces has: 

> Returns the index of the first element in the array where predicate is true, and undefined otherwise.

e.g. https://github.com/Microsoft/TypeScript/blob/a715c45f2584c6d0e6c0069c7ebdf968d1a16909/lib/lib.es6.d.ts#L4141-L4150

To be honest I prefer *if it was `undefined`* cause it would be consistent with `.find` and you can do `.findIndex(something) || 0` for cases where you just want the index or first. But it is not the case. The JSDoc needs to be fixed :rose:

**Comment by basarat** [comment]
> various

There are others. Just search for `findIndex`. I am sure you guys know, but just wanted to be more explicit :rose:

**Comment by mhegazy** [comment]
A PR would be appreciated.

**Comment by Arnavion** [comment]
I guess I made it worse by adding `| undefined` to the return type, since I only looked at the description in the file, not the spec.

**Comment by sergey-shandar** [comment]
I've sent a PR #8965 to fix the documentation. I didn't run Jake. Firstly, I would like to confirm that the fix is correct.
