### ISSUE TITLE
Would "Hacks and workarounds" section in Wiki helpful?

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#8517]
There is a long list of requested features that may or may not ever be implemented. In the meanwhile developers need a way to go without them. There is quite a number of witty workarounds to missing features have been posted in separate issues. These workarounds get lost among other issues and sometimes closed which makes them hard to find. The developer's community might benefit from making a list of them and publish it at a well seen sight. A format of such list might be as follows:

#### Nominal types #202 (in investigation)

- https://github.com/Microsoft/TypeScript/issues/8510#issue-153574098
- https://github.com/Microsoft/TypeScript/issues/202#issuecomment-173143983, https://github.com/Microsoft/TypeScript/issues/202#issuecomment-184352626 together with https://github.com/Microsoft/TypeScript/issues/7267#issuecomment-190341185

**Comment by mhegazy** [comment]
I would rather have a section about nominal vs. structural type systems in the handbook, along with recommendations for emulating nominal types as suggested in #8510, #202 and #4895.

**Comment by DanielRosenwasser** [comment]
I agree with @mhegazy, I'm not so sure I want to endorse "hacks and workarounds". Promoting certain patterns to achieve things is a sure-fire way to paint us into a corner when we assume no real world code would be impacted by certain changes.

**Comment by basarat** [comment]
Hacks and workarounds : https://basarat.gitbooks.io/typescript/content/docs/tips/main.html Indeed some from people like @aleksey-bykov himself with my personal opinions mixed in (hacks are fundamentally personal) :rose:

**Comment by RyanCavanaugh** [comment]
I'm reminded of the `T|void` "workaround" people were using to emulate non-nullable types and how badly that code works with real nullable types. We should be careful here and only list things that we consider to be OK code to begin with (i.e. things we consider to be plausibly correct uses of the type system).

**Comment by falsandtru** [comment]
I don't like hacks.
