### ISSUE TITLE
same field name declared in constructor of derived class

### ISSUE THREAD

**Issue by pankleks** [Microsoft/TypeScript#8520]
**TypeScript Version:** 

1.8.30

**Code**

```ts
class A {
  constructor(protected loops: number[]) {
  }
}

class B extends A {
  constructor(protected loops: number[]) {
    super(loops);
 }
}
```

**Expected behavior:**
Error - loops already exists.
Class B should not allow protected/private/public for already existing fields.

**Actual behavior:** 
Compiles successfully

**Comment by RyanCavanaugh** [comment]
It's legal to redeclare fields. This is useful for when you want to provide a more specific type for a particular field (for example, a `PersonHolder` base class might have a `person` field of type `Person`, but the `EmployeeHolder` derived class specializes `person` to type `Employee`).

**Comment by pankleks** [comment]
I understand. Although it's confusing.

I would probably prefer to add precise typed getter `get Employee() Employee { return this.person as Employee; }` in derived class rather to allow this.
In my case field had completely different meaning, and it was coding mistake that could be found by compilation.
