### ISSUE TITLE
Unclear release numbers - where is 1.8.30.0?

### ISSUE THREAD

**Issue by 304NotModified** [Microsoft/TypeScript#8522]
We have installed TypeScript 1.8.30.0 in Visual Studio 2015, but it's unclear if this is the latest version. I can't be found on https://github.com/Microsoft/TypeScript/releases

 Is this TypeScript 1.8.10?

I would be nice if the release numbers would be more clear. E.g.
![image](https://cloud.githubusercontent.com/assets/5808377/15108879/b8ba9c56-15d8-11e6-8e3c-37db2424e3d5.png)

It's more clear if the release is called TypeScript 1.8.5/1.8.6/1.8.7, and also the tag should be 1.8.5_1.8.6_1.8.7? Or just create 3 tags/releases.

**Comment by mhegazy** [comment]
Please see my comment in https://github.com/Microsoft/TypeScript/issues/8030#issuecomment-210119939.

The language/Compiler version can be the same, i.e. no changes went into the compiler between different releases (1.8.9, 1.8.10, 1.8.29, 1.8.30). they are just updates to managed VS extension to react to API changes in VS between updates. 

We will try to simplify our version story going forward.

**Comment by 304NotModified** [comment]
This is again confusing :( 

One of the developers at work has version 1.8.31, but I cannot find if that's the latest version and where to download it (not on https://github.com/Microsoft/TypeScript/releases it seems? )
