### ISSUE TITLE
TSServer: Intellisense problems when project on network drive

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#8524]
_From @getglad on May 6, 2016 16:20_

- VSCode Version: 1.0.0
- OS Version: Win 7

When using a file on a Windows network drive, a lot of the Intellisense features are not working. Where I am at least feeling the most pain points is in using import/export ES6 statements, such that I am not able to see the components of my imported class. Peek/Find All References/Go to Definition, etc will not work.

On a desktop, this is fine. I remember Atom had this problem early on as well. A few are still open: https://github.com/atom/atom/issues/1766

Steps to Reproduce:

1. Put files on network drive
2. Try to use ES6 import/export statements; Peek feature; 'Go to Definition' feature

_Copied from original issue: Microsoft/vscode#6172_

**Comment by dbaeumer** [comment]
I will move this to the TS team which provide the tsserver.

**Comment by zhengbli** [comment]
Seems fixed for me after the recently changes that moving the file watching back to polling. Please reopen if it still exists.
