### ISSUE TITLE
Refactoring (rename symbol) is broken in certain cases

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#8526]
_From @DavidRigglemanININ on April 30, 2016 23:47_

- VSCode Version: 1.0.0
- OS Version: OS X Yosemite
- Language: TypeScript

Steps to Reproduce:

1. Paste the following code snippet into VS Code
```
export class Test {
    private static _meta = {
        foo: "string"
    };

    private p = Test._meta;

    private static test(me: Test) {
        var myTestVar = me.p.foo;
    }
}
```
2. Right click on foo on line 3 and select rename symbol
3. Change "foo" to "fooNew" and press enter
4. Expected: me.p.foo should be updated to me.p.fooNew
5. Actual: rename does not work leaving broken code that does not build

It may be worth mentioning that this code snippet is just a trivial example to highlight the problem. So in case you are wondering why anyone would want to do this, we do have a valid use case that's just too complex to put here. Also, Visual Studio handles the refactoring just fine.

_Copied from original issue: Microsoft/vscode#6021_

**Comment by dbaeumer** [comment]
_From @DavidRigglemanININ on May 1, 2016 0:6_

This may or may not be related but in case it is, I also have issues where the hover of the value of a property during debugging doesn't work. For example, hovering over "me" displays the value correctly, but hovering over "foo" in "me.p.foo" simply shows nothing. This is another thing that Visual Studio gets right.

**Comment by dbaeumer** [comment]
_From @stereokai on May 5, 2016 9:6_

I have another issue with renaming symbols. Trying to refactor a class name in a Typescript file across a project, VSCode fails and alerts "No result."

```
class MyClass extends AnotherClass {
  constructor() {
    super();
  }

  // ...
}
```

<img width="618" alt="screen shot 2016-05-05 at 12 05 36" src="https://cloud.githubusercontent.com/assets/2685357/15039988/ba5ab856-12b9-11e6-99d8-c1162bcc59ba.png">

Edit: nevermind, solved it by adding a `tsconfig.json` to root project directory. Didn't know it had to be done 😝

**Comment by mhegazy** [comment]
This is working correctly for me with latest. please reopen if still an issue.

![animation](https://cloud.githubusercontent.com/assets/8000722/15868923/b8b9e4b4-2c9e-11e6-9321-e4aa2c345443.gif)

**Comment by DavidRigglemanININ** [comment]
This is still not working for me. Running VS Code 1.2.1 and TS 1.8.10

![refactor fail](https://cloud.githubusercontent.com/assets/10616296/16151379/9dc3a8ec-346a-11e6-8431-89ca3cb28844.gif)

**Comment by mhegazy** [comment]
It is fixed in latest drop of typescript, that is typescript@next and not 1.8. It should be included in the next release.

**Comment by churtado** [comment]
I'm having the exact same issue.

- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: none
---
