### ISSUE TITLE
Javascript short circuit syntax not respected by syntax highlighting 

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#8530]
_From @bradbart on April 29, 2016 4:16_

- VSCode Version: 1.0.0 fa6d0
- OS Version: Windows 10 

Steps to Reproduce:

1. Write a function in a javascript function with the following definition: 
```javascript
function test(err) {
    err && return; 
    console.log('error'); 
}
```

Even though this syntax is valid, VS code underlines the return statement indicating that it expects an expression and that the console.log code is unreachable. 

_Copied from original issue: Microsoft/vscode#5968_

**Comment by RyanCavanaugh** [comment]
> Even though this syntax is valid

No, it isn't. `return` is a keyword that can only be used in a statement.
