### ISSUE TITLE
Compile on save hangs in Visual Studio after `tsconfig.json` is introduced.

### ISSUE THREAD

**Issue by NoelAbrahams** [Microsoft/TypeScript#8537]
Hi,

**Version:**  Visual Studio 2015 Update 2 / TS 1.8.9 (says 1.8.31.0 on the Visual Studio Help -> About page)

To reproduce:

* Create a new "HTML Application with TypeScript" project in Visual Studio.
* Make a change to `app.ts`, save it and observe that compile-on-save works correctly. The status bar should say "Outputs(s) generated successfully".
* Add a `tsconfig.json` file to the project.
 
```json
{
  "compileOnSave": true
}
 ```
* Now make a change to `app.ts` and save the file. 
* This can either work on the first go or fail. If it works try making a change and saving again.
* The status bar hangs with "Generation of 'myProject/app.ts' complete. Remaining files compiling'.

The actual `app.js` appears to generate correctly in this instance, but it's possible that that doesn't work either in other cases (I cannot seem to be able to reproduce that.)

Clearly, this is a very simple project and compilation should be instantaneous (as it was without the `tsconfig.json`).

**Comment by mhegazy** [comment]
@paulvanbrenk can you take a look.

**Comment by paulvanbrenk** [comment]
So to be clear the _only_ issue you see is that the status bar is not updated?

**Comment by NoelAbrahams** [comment]
Well it's difficult to tell without checking the output files every time.

Sent from my iPhone

On 9 May 2016, at 23:33, Paul van Brenk <notifications@github.com<mailto:notifications@github.com>> wrote:


So to be clear the only issue you see is that the status bar is not updated?

-

**Comment by paulvanbrenk** [comment]
Actually found a bug, fixing now.

**Comment by paulvanbrenk** [comment]
Should be in the next release of TypeScript

**Comment by AkosLukacs** [comment]
Do you have an Eta on the next release?
