### ISSUE TITLE
Proposal: Create classes for targets and modules

### ISSUE THREAD

**Issue by SetTrend** [Microsoft/TypeScript#8542]
TypeScript is able to transpile to a number of different JavaScript levels (targets) and a number of different loader frameworks (modules).

Basically, each target and each module are just a peculiar manifestation of the same task, having a common core for performing the basic task of transpilation.

Moreover, targets and modules may come and go over time.

To me - from an architectural perspective - this screams for a provider pattern, having a basic emmitter class utilizing a `Target` provider interface and a `Module` provider interface for dealing with the different peculiarities of a target and module, resp.

Looking at [`src/compiler/emitter.ts`](https://github.com/Microsoft/TypeScript/blob/master/src/compiler/emitter.ts), it's currently a huge dump bin for all of this code. The code in the file is hard to find, hard to maintain and it's hard to add new targets and modules.
<br/>
So I suggest to split `emitter.ts` into a class with no notion of targets or modules and into a number of `Target` and `Module` providers:

```
<src>

| -- <compiler>

  | -- <Modules>
    | -- IModule.ts
    | -- system.ts
    | -- amd.ts
    | -- commonjs.ts

  | -- <Targets>
    | -- ITarget.ts
    | -- es3.ts
    | -- es5.ts
    | -- es6.ts

  | -- emitter.ts
```
<br/>
`emitter.ts` might then look similar to this:
```ts
class emitter
{
  constructor(IModule module, ITarget target)  { ... }

  transpile(source) : string  {...}   // returns transpiled string
}
```

`emitter.ts` should contain all the boilerplate code that's not related to a target's or module's peculiarities. This boilerplate code should then call appropriate interface methods on the provided target/module providers to be able to create a target/module aware result.

Naming the target/module classes like the corresponding compiler option will make it easy to safely add/remove targets/modules to the compiler.

**Comment by mhegazy** [comment]
We are working on rewriting the emitter into a series of transformations on the tree. this should allow for adding extensibility points in the future to handle module transformations in a way that is not natively supported by the TS compiler today. Please see https://github.com/Microsoft/TypeScript/issues/5595 for more details.
and you can see the work done so far in https://github.com/Microsoft/TypeScript/tree/transforms

**Comment by mhegazy** [comment]
closing in favor of #5595

**Comment by SetTrend** [comment]
Excellent :clap:
