### ISSUE TITLE
When you change ts file folder will get the "Duplicate identifier" message

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#8543]
_From @wangyibu on April 29, 2016 9:34_

- VSCode Version:1.0.0
- OS Version:window7 sp1 build 7601
- VS2015: commuity 2015 update1
- system path:  C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.7;

Steps to Reproduce:

1.add two ts file and compile

![1](https://cloud.githubusercontent.com/assets/14134768/14912855/95bd0bde-0e31-11e6-8289-36e5e878e8f2.png)

![2](https://cloud.githubusercontent.com/assets/14134768/14912859/a0574316-0e31-11e6-94d4-174b19554a36.png)

2.add new folder
 
![3](https://cloud.githubusercontent.com/assets/14134768/14912898/e0a9252e-0e31-11e6-9908-e81c22dbb254.png)

3. move all ts file and js file to new folder 
![image](https://cloud.githubusercontent.com/assets/14134768/14912921/fc6fe90a-0e31-11e6-99eb-c106f8092e52.png)

_Copied from original issue: Microsoft/vscode#5980_

**Comment by dbaeumer** [comment]
_From @wangyibu on April 29, 2016 9:53_

supplement: when I change namespace  "Wd3.Test" -> "Wd3" is work
Steps to Reproduce:
1. 
![5](https://cloud.githubusercontent.com/assets/14134768/14913131/514af342-0e33-11e6-8f26-1483a2d20764.png)

2.
![6](https://cloud.githubusercontent.com/assets/14134768/14913133/556e8646-0e33-11e6-89c6-e8038cd64288.png)

**Comment by dbaeumer** [comment]
@wangyibu can you provide the content of the tsconfig.json file?

**Comment by dbaeumer** [comment]
_From @wangyibu on May 10, 2016 3:40_

not set config
tsconfig.json is empty

**Comment by dbaeumer** [comment]
Moving to TS since it looks like the tsserver doesn't honor the move of files correctly.

**Comment by mhegazy** [comment]
well.. you have two declarations for `Wd3.Test.IPerson`. each one of them defines `name` and `age`. so the duplicate definition error seems expected.

if you change the name of the containing module, you are now talking about two different declarations: `Wd3.Test.IPerson` and `Wd3.IPerson`, so not getting duplicate definition errors seems to be expected as well.
