### ISSUE TITLE
modules documentation doesn't have pattern for Node.js users

### ISSUE THREAD

**Issue by psnider** [Microsoft/TypeScript#855]
I find the module documentation page very confusing when I try to apply it to Node.js commonjs modules. I think my main difficulty understanding modules is that most documentation focuses on internal modules, with treatment of external modules as an option.

It seems to me that the two module types, internal and external, have little in common, and that they use different coding patterns. And I haven't figured out how to check my external module code in the [TypeScript Playground](http://www.typescriptlang.org/Playground). My guess is that a separate playground is required.

I would also like to see a separate best practices guide for node.js development.

Currently, my guidelines include:

- each module has an implementation file and a declaration file
- each implementation file has the following format:
  - references  
  There may only be references to native node packages and to commonjs packages.
  - module imports and alias imports  
  I use alias imports to avoid namespaced references in my code (e.g. module.interface_name), unless the namespace is clarifying.
  - interfaces and classes that are private to the module
  - the implementation, with only the minimum required exports
- declaration files go into a decl directory  
  And 3rd-party declarations going into decl/3rd_party  .
  I'm sure there's a better way to do this. It's cumbersome to manage with DefinitelyTyped.
  (BTW, I just starting investigating **tsd**) 

Here is a simplified example of a module:

```
/// <reference path='../../../decl/3rd_party/node.d.ts' />
/// <reference path='../../../decl/3rd_party/Q.d.ts' />
/// <reference path='../../../decl/appModule1.d.ts' />
/// <reference path='../../../decl/appModule2.d.ts' />

// native and 3rd-party modules and aliases
import http                             = require('http');
import Q                                = require('q');

// my app's modules and aliases
import AppModule1                       = require('appModule1');
import AppModule2                       = require('appModule2');
import Type1                            = appModule2.Type;
import some_var                         = appModule2.some_var;

// interfaces and classes that are private to this module
interface A {};
class B {}

// the implementation, with public element exported
var a;
export var b;
function c() {}
export function d() {}
```

And my declaration for the above module will look like:

```
// <reference path='../../../decl/3rd_party/Q.d.ts' />
/// <reference path='../../../decl/appModule3.d.ts' />

declare module "myApp" {

    // modules and aliases used by this declaration file
    import Q                                = require('q');
    import AppModule3                       = require('appModule3');
    import AM3Type                          = AppModule3.Type;

    // public interfaces and classes
    interface X {}
    class Y extends AM3Type {}

    // public variables and functions
    var b;
    function d() : Q.Promise<X> {}
}
```

Notice that the public interfaces aren't in the global namespace, they belong to the module, and must be referenced within its namespace. In some cases, I've been unable to figure out how to do this for 3rd-party libraries.

This is a fairly narrow set of guidelines.  If they seem reasonable, I'd be happy to work on them further to create a best practices guide for node.js development.

**Comment by mhegazy** [comment]
closing this issue for now, please reopen if there further details needed.
