### ISSUE TITLE
Automatically import module

### ISSUE THREAD

**Issue by 2426021684** [Microsoft/TypeScript#8550]
Automatically import modules.
A.ts:

```ts
export const a = 2
```

B.ts:
```ts
const b = a + 2
```

Module B would automatically import module A.

**Comment by DanielRosenwasser** [comment]
What do you mean exactly by *automatically*? Is this a language-service related quick-fix? Or is it something the compiler would automatically figure out on its own?

**Comment by 2426021684** [comment]
I mean the compiler

**Comment by mhegazy** [comment]
The compiler can not implicitly figure out your imports. what if you have a global called `a`, what if you have multiple modules called `a`, what if it is just an error.. 
Modules do have a clear syntax for importing names into their scope.

**Comment by 2426021684** [comment]
If there any way to avoid importing 10 files at the top of every file?
```ts
import X from "./X.ts"
import Y from "./Y.ts"
...
```
Or to import a file/library project wide?

**Comment by mhegazy** [comment]
you could reexport declarations.. e.g.:

```ts
// api.ts

// Things that every one needs
export * from "./x";
export * from "./y";
export * from "./z";
```

```ts
// module.ts

import { x, y, z} from "./api";
```

**Comment by 2426021684** [comment]
@mhegazy Thanks for your help. That work around will do. I was hoping for something like swift thought were imports happen automatically for the same project.

**Comment by 2426021684** [comment]
Is there a way to do `import * from "./file.ts"`?

**Comment by kitsonk** [comment]
`import * as file from "./file.ts";`

StackOverflow or [gitter](https://gitter.im/Microsoft/TypeScript) or ##typescript on IRC are really good places for these types of questions.

**Comment by mhegazy** [comment]
As @kitsonk noted, `import * as ns from "mod"` is the recommended pattern. You can find more about what `import * from "mod"` was not considered in https://github.com/Microsoft/TypeScript/issues/2956#issuecomment-97960188
