### ISSUE TITLE
Type Guards no longer work inside a nested closure.

### ISSUE THREAD

**Issue by david-driscoll** [Microsoft/TypeScript#8552]
**TypeScript Version:** 
nightly (1.9.0-dev.20160217)

**Code**

```ts
interface TypeGuard {
  guard: boolean;
}
function isTypeGuard(value: any): value is TypeGuard {
  return value.guard;
}

let a: { notGuard: boolean } | TypeGuard;
if (isTypeGuard(a)) {
  const b: TypeGuard = a;
  let c: TypeGuard
  (() => c = a)();
}
```

**Expected behavior:**
The guarded type should be guarded within any nested closures.

**Actual behavior:** 
The guarded type is not guarded in any nested closures.  This has previously been working correctly.

Example outputs...

![image](https://cloud.githubusercontent.com/assets/1269157/15180844/e26585fa-1751-11e6-961b-c432c4007ff9.png)

![image](https://cloud.githubusercontent.com/assets/1269157/15180848/e856b056-1751-11e6-87ed-a0bf1c17fa25.png)

This is impacting https://github.com/ReactiveX/rxjs/issues/1697

cc @alexeagle

**Comment by malibuzios** [comment]
Related: #7719, #7739, #8367, #8541

I believe this has been described as a breaking change in #7662

**Comment by david-driscoll** [comment]
Alright makes sense for a major rev.  Thanks!
