### ISSUE TITLE
Exception on getting quickinfo when having a comment with no code following it

### ISSUE THREAD

**Issue by zhuravlikjb** [Microsoft/TypeScript#8553]
If you have a comment node that has no other nodes following it, you get the following exception when positioning caret at that comment node.

```
/*
foo
*/
{caret}/*
moo
*/
```

![ts_exception](https://cloud.githubusercontent.com/assets/4499495/15185165/43211d82-1798-11e6-8fe8-8c909141e782.png)

p.s.: Compiler version - locally built today's checkout.

**Comment by andy-ms** [comment]
We're having trouble reproducing this error. What typescript settings are you using? Is the code you show here the entirety of the file that causes this error?

**Comment by zhuravlikjb** [comment]
By some reason it is reproducible only when the file has exported members. Managed to reproduce is stably with the following code:

```
export function f() {}

/*
foo
*/
/*
moo
*/
```

Just hover mouse pointer over "moo".
