### ISSUE TITLE
Unable to work `--lib` flag with dom

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#8557]
Note: v1.9.0-dev.20160407 works fine, but v1.9.0-dev.20160408 is broken.

**TypeScript Version:** 

master

**Code**

```ts
var a: HTMLAnchorElement;
var b: HTMLPhraseElement;
```

**Expected behavior:**

```
$ node built/local/tsc.js --lib es5,dom index.ts
```

**Actual behavior:** 

```
$ node built/local/tsc.js --lib es5,dom index.ts
index.ts(2,8): error TS2304: Cannot find name 'HTMLPhraseElement'.
```

**Comment by mhegazy** [comment]
`HTMLPhraseElement` is an IE specific definition, and does not exist in the standard. newer version of Edge stopped supporting it as well. It has been removed in https://github.com/Microsoft/TypeScript/pull/7619 as part of updating the DOM.

Please note this is not specific to `--lib`, it just does not exist in the DOM definitions any more. 

to keep using it, please add the definitions:

```ts
interface HTMLPhraseElement extends HTMLElement {
    /**
      * Sets or retrieves reference information about the object.
      */
    cite: string;
    /**
      * Sets or retrieves the date and time of a modification to the object.
      */
    dateTime: string;
}

declare var HTMLPhraseElement: {
    prototype: HTMLPhraseElement;
    new(): HTMLPhraseElement;
}
```

**Comment by falsandtru** [comment]
Thanks.
