### ISSUE TITLE
Math.log10 function is not included in lib.d.ts

### ISSUE THREAD

**Issue by jacalata** [Microsoft/TypeScript#8562]
**TypeScript Version:** 
1.8.9

**Code**
// A self-contained demonstration of the problem follows...
Math.log10(10)

**Expected behavior:**
typescript likes it, because it is part of the javascript language: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/log10

**Actual behavior:** 
Math.log10 is not present in the typescript lib.d.ts file and a typescript warning is produced

**Comment by jeffreymorlan** [comment]
`Math.log10` was introduced in ES6, so it's only in lib.es6.d.ts

**Comment by mhegazy** [comment]
Please note that you can use this with `--lib es2015` or `--lib es2015.core` if you are using `typescript@next`.
