### ISSUE TITLE
Importing a module with a different syntax should return the same reference in the SystemJS transpiled files

### ISSUE THREAD

**Issue by maximedupre** [Microsoft/TypeScript#8564]
I am transpiling my modules into the `system` format. Those two imports do not return the same reference:

    import _ from 'underscore';
    // when transpiled, _.where -> underscore_1.default.where

    import {when} from 'underscore';
    // when transpiled, where -> underscore_1.when

Since a module is imported only once and that each import share the same instance, I should be able to do

    import _ from 'underscore';
    _.where = null

in one module and

    import {where} from 'underscore';
    console.log(where) // null

in another module.

Typescript version is `1.8.10`.

**Comment by vladima** [comment]
these two imports are [not equivalent](https://tc39.github.io/ecma262/#table-40):
- `import _ from 'underscore'` imports name 'default' as local name '_'
- `import {when} from 'underscore'` imports name `when` and keeps the same local name.
In the former case `_` does not refer to a module namespace object bur rather to a particular name that was exported with `export default` export declaration.
If you need to get a module namespace object you can use `import * as ns from 'underscope'` however `[[Set]]` [operation](https://tc39.github.io/ecma262/#sec-module-namespace-exotic-objects-set-p-v-receiver) on such objects is not permitted so this code will fail at runtime in ES6 environment

```javascript
import * as ns from 'underscore';
ns.where = null;
```

**Comment by maximedupre** [comment]
@vladima Thanks for clearing that up for me. Is Chrome v50 an ES6 environment?

    import * as ns from 'underscore';
    ns.where = null;

This code is working with no errors.
