### ISSUE TITLE
[Suggestion] Is it possible for salsa jsdoc to document @param in function body

### ISSUE THREAD

**Issue by Thaina** [Microsoft/TypeScript#8567]
When we code things like this it hard to document

```js
DoSomeAsync(
    /** @param {{Items:number[]}} result */ function (result){
    }
);
```

It would be cleaner if we could mark `@param` in the function body

```js
DoSomeAsync(function (result){
    /** @param {{Items:number[]}} result */
});
```

Or maybe not `@param` but let `@type` able to document nearest things, not need var, and have scope after that `@type` tag

```js
/** @type {function(function(number):void):void} */
DoSomeAsync(function (result){
});
```

**Comment by mhegazy** [comment]
I am not aware of JSDoc rules that allows param to be inside the function. this also applies to `@type`, associating it with the function would be fairly arbitrary.
