### ISSUE TITLE
Confusing error message when using different prop type and casting from a type with private prop

### ISSUE THREAD

**Issue by donaldpipowitch** [Microsoft/TypeScript#8568]
Say I have two classes and I want to cast one type into the other like this:

```typescript
class Test {
  private foo: string = 'foo';
  bar: string = 'bar';
}

class MockedTest {
  bar: string = 'mocked-bar';
}

const myTest: Test = new Test();
const myTest2: Test = new MockedTest() as Test;
```

This works quite well. But if I change the property in `MockedTest` from `bar: string = 'mocked-bar';` to `  bar: number = 1;` I get a confusing error message.

```typescript
class Test {
  private foo: string = 'foo';
  bar: string = 'bar';
}

class MockedTest {
  bar: number = 1;
}

const myTest: Test = new Test();
const myTest2: Test = new MockedTest() as Test;
                      ~~~~~~~~~~~~~~~~~~~~~~~~
                      ^ Neither type 'MockedTest' nor type 'Test' is assignable to the other. Property 'foo' is missing in Type 'MockedTest'.
```

We actually had this error when we tried to mock our classes in unit tests and couldn't figure out why property `foo` throws the error until we noticed a different property had a wrong type.

A better error message would be that property `bar` should be a `string` and not a `number`.

**Comment by basarat** [comment]
Note : if you have a private member, that effectively makes the class nominal and you will have a hard time mocking it without assertions: 

```ts
class A {
	private foo: number;
}
class B {
	private foo: number;
}
let a:A, b:B;
a = b; // Error 
b = a; // Error
```
And of course [assertions can siliently ignore certain type incompatabilities that would result in runtime errors](https://basarat.gitbooks.io/typescript/content/docs/types/type-assertion.html) :rose:

**Comment by Arnavion** [comment]
I think this is just a consequence of the way the compiler generates error messages - it only puts the first reason. In this case it complains about the first difference between the two types.

**Comment by mhegazy** [comment]
There is not a clear way to define what error message is "better" than another. the compiler is checking `new MockedTest() as Test`, so either 1. `MockedTest` is assignable to `Test`, or 2. `Test` is assignable to `MockedTest`. neither were true, and as @Arnavion you get the first error.
I do not think there is much we can do about this behavior.
