### ISSUE TITLE
Inconsistency between compiler options in docs and actual options in tsconfig.json and VisualStudio.

### ISSUE THREAD

**Issue by mattmazzola** [Microsoft/TypeScript#8569]
**TypeScript Version:** 

1.8.10

### 1. The documentation for compiler options shows that you can set `module: "none"`
http://www.typescriptlang.org/docs/handbook/compiler-options.html

![image](https://cloud.githubusercontent.com/assets/2856501/15205118/7e691a12-17c9-11e6-823b-f2ea0b56ea4f.png)

This suggests that there should be an option to set `module: "none"` in a tsconfig.json file since it's equivalent to the `--module` flag.

### 2. When editing the tsconfig.json file from within VS Code `"none"` is not an option for "module".

![image](https://cloud.githubusercontent.com/assets/2856501/15205543/0e518e36-17cd-11e6-99b9-dfe6b1edbdbc.png)

This contradicts the documentation which says "none" is a valid option.

### 3. If you create a new Asp.Net MVC project and add a typescript file and check the project settings you will in fact see that "None" is an option for module output and it outputs the variables as globals using IIFE pattern.

![image](https://cloud.githubusercontent.com/assets/2856501/15205389/b1fcd1a0-17cb-11e6-8f5f-879495a9b4c8.png)

This is confusing because the if you try to set module to none from VS code the typescript compiler will actually give an error:
`error TS1148: Cannot compile modules unless the '--module' flag is provided with a valid module type. Consider setting the 'module' compiler option in a 'tsconfig.json' file.`

This makes you wonder how it can be possible to set modules as None when in Visual Studio.

## How to compile to equivalent of `module: "none"`
There might be a use case where someone wants to transpile to globals like visual studio does instead of being forced to use "amd", "commonjs", or "umd" and there isn't a clear way to do that in the `tsconfig.json` options.

Is it true that VS code and Visual Studio are both using same compiler and should have the same features? (I know they could target different versions, but assuming they're not)

I found that if you use a combination of:
```
target: "es5",
module: "es2015"
...
```
It will show an error saying:
`error TS1204: Cannot compile modules into 'es2015' when targeting 'ES5' or **lower.**`
but the output looks the closes to what `module: "none"` used to do.

### Resolution?
I would guess the easiest is to update tsconfig.json to allow `module: "none"` so it can be configured to behave the same as visual studio. Then it will also align with the documentation.

**Comment by DanielRosenwasser** [comment]
@paulvanbrenk is this just a bug with the schema?

**Comment by paulvanbrenk** [comment]
Isn't `module " none` the same as omitting `module` options, that's what VS does, doesn't that work you?

**Comment by mattmazzola** [comment]
If you omit module it defaults to commonjs, so as far as I can tell there is no way to do that unless you uses VisualStudio

**Comment by mhegazy** [comment]
`--module none` is a valid compiler flag and in a tsconfig.

not specifying the module is not the same as `none`. the default is `commonjs`.

we should update the schema.

**Comment by paulvanbrenk** [comment]
https://github.com/SchemaStore/schemastore/pull/149
