### ISSUE TITLE
Resolving modules in node_modules with broken typings.

### ISSUE THREAD

**Issue by tomitrescak** [Microsoft/TypeScript#8570]
I have a bit of technical question concerning the module resolution.
I am running the latest version of typescript from the @next branch.

I have several node modules in my project and most of them have typings (in package.json).
Yet, there is one project that also has typings "apollo-client", but these typings do not compile.

The reason for this is, that that project imports `graphql` and `Promise` from external modules and these are not found during the compilation. I am a bit lost in what can I do here.

I tried overriding the definition in my cusotm ambient defintion, but the resolved module has the preference. Specifying "noResolve" is not an option as I depend on typings from other modules.

My question is, how can I tell that imported module where to search for "graphql" and for "Promise"?

Thanks

**Comment by vladima** [comment]
you can use `baseUrl`, `paths` or `rootDirs` to customize module lookup - more details can be found [here](https://github.com/Microsoft/TypeScript-Handbook/blob/release-2.0/pages/Module%20Resolution.md#additional-module-resolution-flags)

**Comment by tomitrescak** [comment]
@vladima thank you kindly for your reply. While this solves my case and I could "replace" the path from where the definition is taken, this does not solve the problem systematically. I also had the same question from package developer asking how can they make it right?

So my question is, if I am a package developer and I provide typings, how do I provide typing from the external modules I use?

Example: I have a file that import graphql library such as `import { x } from "graphql"`. How do I distribute those graphql typings? 

I tried just adding the "graphql.d.ts" into the project but the compiler was not picking it up and was announcing `unknown module "graphql"`

Any help is greatly appreciated

**Comment by tomitrescak** [comment]
If you would have any time to test what I'm talking about, just check the "apollo-client" package from npm. These guys provide typings, but their typings break the project unforunatelly.

**Comment by PyDeq** [comment]
FYI, I've just [asked](https://github.com/typings/typings/issues/562) authors of `npm` to provide a recipe for this situation, IIUIC...

**Comment by mhegazy** [comment]
The original issue is an external issue, the fix should be done on the type definition producer side.

The other related issue is the user ability to override a set of external type definitions. with the new @types module, we should have this capability. a special folder named `types` at the root, would allow you to place some override definition files. I do not have documentation to point to at the moment. so keeping this issue open until we have more docs.

**Comment by aendrew** [comment]
Actually wait n/m it seems having a "types" folder in the root does absolutely nothing. 😒
