### ISSUE TITLE
Visual Studio 2015 TypeScript Language Services Not Working

### ISSUE THREAD

**Issue by jzabroski** [Microsoft/TypeScript#8573]
This issue is related to / almost identical to the one fixed in #6958. 

# *Actual Behavior*:
1. On my csproj's TypeScript Build tab, I get the error message: "An error occurred trying to load the page.
d4683cae-88c4-4b85-863d-ac8014f3ba36"
2. When I open a .ts file in Visual Studio 2015, there are no classical VS code navigation dropdowns at the top of the file for project, module and function.  Also, the text is completely black, there is no syntax highlighting for keywords, IntelliSense does not work, and Compile On Save does not work.
3. When I go to "File > New -> Project...", the "HTML Application for TypeScript" template does not show up.  No TypeScript project types appear in the tree view on the left of the New Project screen.
4. When I search Quick Launch for TypeScript, nothing comes up.
5. When I go to "Tools -> Extensions and Updates...", TypeScript 1.8.4 for Visual Studio 2015 appears as uninstalled.  When I then click Download, and run the installer, it asks me if I want to Repair the extension, indicating it thinks it is already installed. Further, when I go to "Control Panel -> Add or Remove Programs...", I can see the following are installed:
   - TypeScript Tools for Microsoft Visual Studio 2015 1.5.4.0 (Installed On: 8/10/2015, 73.7 MB, Version 1.5.23128.0)
   - TypeScript Tools for Microsoft Visual Studio 2015 1.6.3.0 (Installed On: 9/23/2015, 77.1 MB, Version 1.6.23313.0)
   - TypeScript Tools for Microsoft Visual Studio 2015 1.8.6.0 (Installed On: 5/11/2016, 16.1 MB, Version: 1.8.6.0)
6. Based on @mhegazy 's suggestions, I have attached my installation log from %temp%/dd_TypeScript* - see [dd_TypeScript_Dev14_20160511171729.zip](https://github.com/Microsoft/TypeScript/files/261360/dd_TypeScript_Dev14_20160511171729.zip)

Finally, I found this page on the wiki: https://github.com/Microsoft/TypeScript/wiki/Dev-Mode-in-Visual-Studio

Is this my missing problem?  If so, why doesn't the Visual Studio installer just handle this for me?

# *Additional Environment Details from Visual Studio Help/About - Copy Info button*:
> Microsoft Visual Studio Enterprise 2015
> Version 14.0.23107.0 D14REL
> Microsoft .NET Framework
> Version 4.6.01055
> 
> Installed Version: Enterprise
> 
> Architecture and Modeling Tools   00325-70002-17896-AA401
> Microsoft Architecture and Modeling Tools
>     
> UML® and Unified Modeling Language™ are trademarks or registered trademarks of the Object  Management Group, Inc. in the United States and other countries.
> 
> Visual Basic 2015   00325-70002-17896-AA401
> Microsoft Visual Basic 2015
> 
> Visual C# 2015   00325-70002-17896-AA401
> Microsoft Visual C# 2015
> 
> Visual C++ 2015   00325-70002-17896-AA401
> Microsoft Visual C++ 2015
> 
> Visual F# 2015 RC   00325-70002-17896-AA401
> Microsoft Visual F# 2015 RC
> 
> Application Insights Tools for Visual Studio Package   1.0
> Application Insights Tools for Visual Studio
> 
> ASP.NET and Web Tools 2015 (RC1 Update 1)   14.1.20203.0
> ASP.NET and Web Tools 2015 (RC1 Update 1)
> 
> ASP.NET Web Frameworks and Tools 2013   5.2.40204.0
> For additional information, visit http://www.asp.net/
> 
> Azure App Service Tools v2.7.1   14.0.11112.0
> Azure App Service Tools v2.7.1
> 
> Common Azure Tools   1.6
> Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.
> 
> GenerateUnitTest   1.0
> Generates unit test code for methods in classes under test.
> 
> GitHub.VisualStudio   1.0
> A Visual Studio Extension that brings the GitHub Flow into Visual Studio.
> 
> Microsoft Azure HDInsight HQL Service   2.0.2600.0
> Language service for Hive query
> 
> Microsoft Azure HDInsight Tools for Visual Studio   2.0.2600.0
> An integrated development environment for HDInsight application development.
> 
> Microsoft Azure Mobile Services Tools   1.4
> Microsoft Azure Mobile Services Tools
> 
> Microsoft Azure Tools   2.7
> Microsoft Azure Tools for Microsoft Visual Studio 2015 - v2.7.30818.1601
> 
> Microsoft Code Digger   0.9
> Microsoft Code Digger
> 
> Microsoft Team Foundation Server 2015 Power Tools   14.0
> Power Tools that extend the Team Foundation Server integration with Visual Studio.
> 
> Microsoft Visual Studio Process Editor   1.0
> Process Editor for Microsoft Visual Studio Team Foundation Server
> 
> Microsoft.Pex.VisualStudio   1.0
> Pex
> 
> NuGet Package Manager   3.0.0
> NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.
> 
> PreEmptive Analytics Visualizer   1.2
> Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.
> 
> SQL Server Data Tools   14.0.50730.0
> Microsoft SQL Server Data Tools
> 
> SQLPromptVsPackage   1.0
> Information about my package
> 
> Web Essentials 2015.2   2.0.214
> Adds many useful features to Visual Studio for web developers. Requires Visual Studio 2015
> 
> Workflow Manager Tools 1.0   1.0
> This package contains the necessary Visual Studio integration components for Workflow Manager.
> 
> XAML Spy   3.0.2
> XAML Spy for Visual Studio
> Copyright © First Floor Software. All rights reserved.
> 
> The visual runtime inspector for Android, iOS and Windows
> http://xamlspy.com

# *Additional Environment Details from Visual Studio Help/About - System Info button*
> OS Name	Microsoft Windows 7 Enterprise
> Version	6.1.7601 Service Pack 1 Build 7601

# *Expected Behavior*:
Essentially the opposite of the symptoms above.

**Comment by mhegazy** [comment]
> Finally, I found this page on the wiki: https://github.com/Microsoft/TypeScript/wiki/Dev-Mode-in-Visual-Studio
Is this my missing problem? If so, why doesn't the Visual Studio installer just handle this for me?

No.

Can you upgrade to VS 2015 Update2?

**Comment by paulvanbrenk** [comment]
TypeScript should show in `Help - About` if it's correctly installed, in your previous post you mentioned using `/noweb` that probably causes an issue. You're best bet is as @mhegazy suggested to install Update 2.

**Comment by jzabroski** [comment]
Thanks everyone.  Update 2 is what I suspected. :) Will make the case to my IT department to upgrade VS.  Would love Update 2...

**Comment by jzabroski** [comment]
I got Visual Studio Enterprise 2015 Update 2 installed and the problem went away.  Note, I had to install a different version of Update 2 than the one that comes in the Notifications window in Visual Studio - there is a special release for Enterprise that did the trick (I don't understand why).
