### ISSUE TITLE
Type Guards Not Recognised If typeof Is Used with Brackets

### ISSUE THREAD

**Issue by MrKWatkins** [Microsoft/TypeScript#8574]
**TypeScript Version:** 

1.8.9, used via the Visual Studio extension 1.8.31.0

**Code**

```ts
function something(value: string | number)
{
    if (typeof (value) === "string")
    {
        alert(value.length);
    }
}

```

**Expected behavior:**
I would expect the compiler to treat the if statement as a type guard and recognise that value is a string afterwards.
**Actual behavior:** 
I get the build error "Property 'length' does not exist on type 'string | number'". If I remove the brackets around value after the typeof, i.e.

```ts
function something(value: string | number)
{
    if (typeof value === "string")
    {
        alert(value.length);
    }
}

```

Then it compiles fine. I can therefore workaround this but it would be nice to not have to; I mainly write C# and as a result I automatically type brackets after typeof. :)

**Comment by mhegazy** [comment]
The compiler honors a certain forms of type guard expressions. there are other forms that are functionally equivalent, but are not supported, such as the one referenced in the OP. The recommendation would be to use the standard form instead.

**Comment by MrKWatkins** [comment]
Any chance you could reconsider please? It's quite difficult to work out what is happening here because, as you say the forms are functionally equivalent. And I naturally use brackets after typeof due to many years of C#... Took me ages to figure it out!

If you can't fix it could you maybe make it an error/warning to use brackets after typeof? Or at the very least put a big note in the handbook documentation telling people to use the standard form if they want type guards to work?

**Comment by mhegazy** [comment]
> Any chance you could reconsider please?

it is not about this pattern, there are other ones:
`typeof (v) === "string"`
`typeof v === ("string")`
`(typeof v) === "string"`
`typeof v === (foo(), "string")`

> If you can't fix it could you maybe make it an error/warning to use brackets after typeof? 

it is valid JS/TS code. it just does not narrow the type. a tslint rule would be a simple addition that can catch these.

**Comment by MrKWatkins** [comment]
No, fair enough, I can see how it would be complex to fix! If you could add a note to the handbook stating that type guards only work with the standard form that would be good though, might save others a bit of time working out what is going wrong.
