### ISSUE TITLE
Add Error.prototype.stack definition

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript#8582]
Most browsers support `Error.prototype.stack`. the property should be defined as optional in lib.d.ts as:

```ts
interface Error {
    stack?: string;
}
```
see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/Stack

**Comment by nojvek** [comment]
Does this need to be added to other .d.ts files which have error definitions? I wasn't very sure the distinction between lib and src/lib

**Comment by mhegazy** [comment]
`src\lib` is the place. the files in `lib\` are generated by the build.
