### ISSUE TITLE
[tsserver] Support for code generation of ES6 Import Declaration

### ISSUE THREAD

**Issue by Quramy** [Microsoft/TypeScript#8585]
I want a new tsserver's command to help generate "ES6 import declaration" code, which tells me locations where I can import the identifier from.

I've attempted to implement import declaration generation in my [Vim plugin](https://github.com/Quramy/tsuquyomi#create-es6-import-declaration), but it's highly limited. My plugin uses `navto` command to search where the identifier is exported. But essentially `navto` is a command for "keyword search". For example if my project has the following 2 files:

```ts
/* node_modules/@angular2/core/index.ts */
export * from './src/metadata';
```

```ts
/* node_modules/@angular2/core/src/metadata.ts */
export function Component() { ... }
```

the response `navto` with `{searchValue: 'Component'}` includes not 'angular2/core/index.ts' but 'angular2/core/src/metadata.ts'. Because not occurrence of 'Component' in 'index.ts'.

**Comment by mhegazy** [comment]
consider asking for definition locaiton (`"definition"`) on the module name instead. this should return you the target of the module import.
