### ISSUE TITLE
I am unable to install angular material -2 in Vs 2015 getting errors

### ISSUE THREAD

**Issue by Sanjaypbh** [Microsoft/TypeScript#8586]
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files
x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "@ng2-material/all"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code E404

npm ERR! 404 Not found : @ng2-material%2fall
npm ERR! 404
npm ERR! 404 '@ng2-material%2fall' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!

npm ERR! 404 It was specified as a dependency of 'angular2-quickstart'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     F:\AppTy\UIFrame\UIFrame\npm-debug.log

**Comment by DanielRosenwasser** [comment]
From a glance, this doesn't look like a TypeScript-specific problem at all. I think StackOverflow or an Angular-related site/chat might be a better place to ask about this.
