### ISSUE TITLE
Nightly version priority is broken by incorrect versioning

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#8589]
It makes impossible to use `npm i` with `npm i -D typescript@next`.

```
     '1.9.0-dev.20160428-1.0': '2016-04-28T21:40:32.410Z',
```

```
> semver.lt('1.9.0-dev.20160428', '1.9.0-dev.20160429')
true
> semver.lt('1.9.0-dev.20160428-1.0', '1.9.0-dev.20160429')
false
```

https://travis-ci.org/falsandtru/typed-dom/builds/129842035#L1146

Could you fix this incorrect versioning?

**Comment by mhegazy** [comment]
@yuit  can you take a look.

**Comment by yuit** [comment]
@falsandtru Sorry for the trouble here . On that day, 04/28, we make some changes in our npm publishing system and republish with "'1.9.0-dev.20160428-1.0" without realizing the implication it has with `semver`. It is too late for us to unpublish that particular package; would it be possible for you to skip this version for once?  We will make sure this won't happen again next time; we will be using ".1.0" instead of "-1.0" if we need to republish on the same day.

**Comment by falsandtru** [comment]
Unfortunately, npm still gives an old version `1.9.0-dev.20160428-1.0` in the popular workflow `npm i -D typescript@<'next' or version>`(on local) and `npm i`(on server). We cannot skip `-1.0` postfixed versions when using `@^x.y.z` formats. I think TypeScript need to increment the patch version as in `1.9.1-dev.20160429`.

Note: An instant solution is `npm i -DE typescript@next`. It uses an exact version `@x.y.z` and resolves problems with install. However, it does not resolve that with update, such as `npm update -S typescript`.

**Comment by yuit** [comment]
@falsandtru  gotcha. we will come up with the possible fix. One of the way we are considering is appending "-1.0" all the time. This will allow us to republish on the same day if necessary and it will not broke existng tool

**Comment by falsandtru** [comment]
> appending "-1.0" all the time.

Seems a nice solution :+1: . However, it will be good to change the postfix to `.1.0` after updating of standard version numbers `x.y.z`.

**Comment by falsandtru** [comment]
Oh, you removed your said about `.1.0` postfix. That postfix is not necessary if you have another convenience.

**Comment by yuit** [comment]
Yes. Sorry I don't want to cause confusiong. Also found out that it is not possible to do postfix `.1.0`

**Comment by falsandtru** [comment]
:+1:

**Comment by billti** [comment]
The issue (according to the semver spec) is in the language: "_identifiers consisting of only digits are compared numerically and identifiers with letters **or hyphens** are compared lexically in ASCII sort order. **Numeric identifiers always have lower precedence** than non-numeric identifiers_". Thus, just adding the dash makes "20160428-1" non-numeric, and always compare higher to "20160429", which is numeric.

Note also that dots are separators, (and dashes aren't), so dots won't work. We pretty much need to add the "-1.0" to the date part to make it non-numeric going forward. (Or bump the major.minor.patch to "1.9.1" for this set of releases).

**Comment by yuit** [comment]
@falsandtru I just install today nightly build. the new version has been in effect. Please let us know if there is still an issue
