### ISSUE TITLE
tsc reports incorrect column with error

### ISSUE THREAD

**Issue by MattijsKneppers** [Microsoft/TypeScript#8592]
In Webstorm, in case of a compile error like "Supplied parameters do not match any signature of call target." when using an incorrect number of arguments for a method, instead of highlighting/underlining the affected method, the first token of the call path is highlighted: 

![webstorm_2016-05-12_09-53-13](https://cloud.githubusercontent.com/assets/299714/15250496/5d4690be-1925-11e6-86fb-e179acbc3014.png)

In the this case, I would expect 'init' to be highlighted, not 'this'.

IntelliJ reports that this is due to a bug in tsc, which reports the incorrect column, see this thread:

https://intellij-support.jetbrains.com/hc/en-us/requests/684087?flash_digest=896873574cecdfd518b7719ac5197ff111ad6375

**TypeScript Version:** 

Webstorm built-in, supposedly latest?

**Code**
see screenshot

**Expected behavior:**
I expect tsc to report the correct column with the error

**Actual behavior:** 
tsc reports the incorrect column with an error, causing Webstorm to highlight the incorrect call path token.

**Comment by mhegazy** [comment]
This does not reproduce for me. can you share more code that shows this issue.

also an easy way to check, is to run the same code with `tsc --pretty` this should show you the error span.

**Comment by mhegazy** [comment]
Closing for now. please provide additional context to be able to reproduce and fix the issue.

**Comment by MattijsKneppers** [comment]
In the mean time, the folks at IntelliJ replied: https://intellij-support.jetbrains.com/hc/en-us/requests/684087, see the reply Elena made today.

Just passing it on, thanks for checking this out!
