### ISSUE TITLE
Do not transpile "async" and "await"

### ISSUE THREAD

**Issue by tomitrescak** [Microsoft/TypeScript#8593]
Is there any way to prohibit transpilation of "async" and "await" to the "_awaiter"? The transpiled code breaks the functionality of graphql. Seems like only babel transpiles this correctly.

I would like to maintain the async and await keywords.

Can it be done? Thanks.

**Comment by jods4** [comment]
This is not currently possible but has been requested several times. I think it's bound to happen at some point.

You can close this as a duplicate of #6747 (closed) and #5361 (open).

**Comment by tomitrescak** [comment]
Thanks. Not good news ;(
