### ISSUE TITLE
Avoid including 'index' (or equivalent) as part of module name during error reporting

### ISSUE THREAD

**Issue by RyanCavanaugh** [microsoft/TypeScript#8600]
When we resolve an external module to a folder index file like `index.d.ts` (or through the `typing` field of `package.json`), we should not consider that `index` part to be part of the filename for the purposes of error reporting.

For example, we currently display

> Module '"c:/github/DefinitelyTyped/react-router/index"' has no exported member 'LinkProps'.

Instead it should be:

> Module '"c:/github/DefinitelyTyped/react-router"' has no exported member 'LinkProps'.

**Comment by Andarist** [comment]
I think this is already solved:
```ts
// @filename: ./nested/index.d.ts
export type A = 'A'

// @filename: ./foo.ts
import { B } from './nested' // Module '"./nested"' has no exported member 'B'.ts(2305)
```

cc @jakebailey
