### ISSUE TITLE
[Docs] gulp handbook guide removes watchify when adding babel

### ISSUE THREAD

**Issue by marianoguerra** [Microsoft/TypeScript#8608]
The docs here: http://www.typescriptlang.org/docs/handbook/gulp.html adds features by steps, at some points it adds watchify to the browserify build task, then adds babel, and at doing so removes the watchify features added one step before. 

The final setup ends up not supporting watchify which was introduced in the same guide.

**Comment by marianoguerra** [comment]
The last step but with watchify included (could be a next step, like "adding back watchify" if only the changed required to have babel are left in the docs)

	var gulp = require('gulp');
	var browserify = require('browserify');
	var source = require('vinyl-source-stream');
	var watchify = require("watchify");
	var tsify = require('tsify');
	var gutil = require("gulp-util");
	var sourcemaps = require('gulp-sourcemaps');
	var buffer = require('vinyl-buffer');

	var paths = {
	    pages: ['src/*.html']
	};

	gulp.task('copyHtml', function () {
	    return gulp.src(paths.pages)
		.pipe(gulp.dest('dist'));
	});

	var watchedBrowserify = watchify(browserify({
	    basedir: '.',
	    debug: true,
	    entries: ['src/main.ts'],
	    cache: {},
	    packageCache: {}
	}).plugin(tsify));

	function bundle() {
	    return watchedBrowserify
		.transform("babelify")
		.bundle()
		.pipe(source('bundle.js'))
		.pipe(buffer())
		.pipe(sourcemaps.init({loadMaps: true}))
		.pipe(sourcemaps.write('./'))
		.pipe(gulp.dest('dist'));
	}

	gulp.task('default', ['copyHtml'], bundle);
	watchedBrowserify.on("update", bundle);
	watchedBrowserify.on("log", gutil.log);

**Comment by DanielRosenwasser** [comment]
This issue was moved to Microsoft/TypeScript-Handbook#278
