### ISSUE TITLE
stdout stream with --watch flag is broken

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#8610]
**TypeScript Version:** 

1.9.0-dev.20160514

**Code**

```ts
;
;
;
;
;
;
;
;
;
;
```

**Expected behavior:**

pass

**Actual behavior:** 

```
$(npm bin)/tsc -w --outFile /dev/stdout -t es5 -m amd index.ts | head
;
;
;
;
;
;
;
;
;
;
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at exports._errnoException (util.js:949:11)
    at WriteWrap.afterWrite (net.js:793:14)
```

**Comment by zhengbli** [comment]
It is not the watch issue though. `head` only reads the first few lines, while node throws exception when it could not produce outputs. Related question can be found at http://stackoverflow.com/questions/12329816/error-write-epipe-when-piping-node-output-to-head

FYI if you run without the `| head`, it works fine on my mac mini.
