### ISSUE TITLE
static name:"test" does not give compiler error

### ISSUE THREAD

**Issue by rekna1** [Microsoft/TypeScript#8613]
When I define a class with a static field, and I by accident write 

`static myVariable : 'test';` 

instead of 

`static myVariable = 'test';`

typescript compiler does not display an error for this. 
in javascript the code just goes away.

**Comment by Arnavion** [comment]
Just like `static myVariable: string` declares a static property of type `string`, `static myVariable: 'test'` declares a static property of the [string literal type](https://www.typescriptlang.org/docs/handbook/advanced-types.html#string-literal-types) `"test"`.
