### ISSUE TITLE
noImplicitPublic flag

### ISSUE THREAD

**Issue by Jameskmonger** [Microsoft/TypeScript#8617]
Are there any plans to implement a `noImplicitPublic` compiler flag?

This would throw a compilation error on code such as this:

```
export class SomeClass {

    someFunction(): void {

    }

}
```

As it would need to be written like this:
```
export class SomeClass {

    public someFunction(): void {

    }

}
```

**Comment by sandersn** [comment]
We don't have any plans for this. And tslint [has a rule](https://github.com/palantir/tslint#core-rules) `member-access` that enforces the use of visibility keywords. The strictness flags the compiler has are ones that involve difficult analysis, like `--noImplicitReturns`, or nearly everybody will want, like `--noImplicitAny`. 

(With some exceptions ... `--noFallthroughCasesInSwitch` should probably just be a lint rule)

**Comment by Jameskmonger** [comment]
Thanks for the response @sandersn
