### ISSUE TITLE
Exhausting enum values in switch statements without default case.

### ISSUE THREAD

**Issue by tinganho** [Microsoft/TypeScript#8618]
For expressivity I don't always include a default case in my switch statements. But I know that variable `abc` below cannot be any value other than `a`, `b` and `c`. Thus, I think the below code should not error, because I return the correct type for all branches it can take.
```ts
let abc: 'a' | 'b' | 'c';
function test(): string {// function lacks ending return statement and return type does not include 'undefined'.
    switch(abc) {
        case 'a':
            return '';
        case 'b':
            return '';
        case 'c':
            return '';
    }
}
```
And for enums:
```ts
enum ABC {
  a,
  b,
  c,
}
let abc: ABC
function test(): string {// function lacks ending return statement and return type does not include 'undefined'.
    switch(abc) {
        case ABC.a:
            return '';
        case ABC.b:
            return '';
        case ABC.c:
            return '';
    }
}
```

**Comment by kitsonk** [comment]
Dupe of #2214? Currently planned for TS 2.1...

**Comment by tinganho** [comment]
@kitsonk IMO little bit different. That one is about types. My OP is about exhausting enum values. But anyway changed title and the content of my OP to reflect my intent.

**Comment by DanielRosenwasser** [comment]
Hm, looks closer to #8602 actually.

**Comment by aleksey-bykov** [comment]
might be related #6155

**Comment by tinganho** [comment]
Yes, dupe of #6155.
