### ISSUE TITLE
Add private class fields

### ISSUE THREAD

**Issue by uMaxmaxmaximus** [Microsoft/TypeScript#8623]
You private props is not private:

1) The code is not written on the typescript (which accordingly is not subject to static analysis) can access them.

2) there is a naming conflict in the child classes (child classes can not use the same private properties of the parent class name, even though the conflict of names should not be)

![image](https://cloud.githubusercontent.com/assets/19378179/15293758/328b9fda-1b92-11e6-87d1-a61665278c1e.png)
	
SOLUTION:

compile this code
````typescript
class Animal {
    private handlers = []
}

class Rebbit extends Animal {
    private handlers = []
}
````

to ES6:
```javascript

class Animal {
    let _private_handlers = Symbol('Animal.handlers')

    constructor(){
        this[_private_handlers] = []
    }
}

class Rebbit extends Animal {
    let _private_handlers = Symbol('Rebbit.handlers')

   constructor(){
        this[_private_handlers] = []
    }
}
```

Simplified Symbol es5 pollyfill:
```javascript
function Symbol(name){ return name + Math.random()  }
```

Yes, this is not in the semantics of the javascript, but then your private property modificator too is not in the semantics of the javascript, but you've added them as a convenience.

protected props 
```typescript
class Animal {
    protected handlers = []
}

class Rebbit extends Animal {
    protected handlers = []
}
```

compile to ES6:

```javascript
class Animal {
    constructor(){
       this._handlers = []
    }
}

class Rebbit extends Animal {
    constructor(){
       this._handlers = []
    }
}
```

the only way it will not work, expressions like ```this[propName]``` because we need to know the name of the property to which the access, in advance at compile time, so if it is a private or protected, then replace it with the proper structure: private to ```this[symbol]```, protected to ```this._prop```

**Comment by uMaxmaxmaximus** [comment]
protected props 
```typescript
class Animal {
    protected handlers = []
}

class Rebbit extends Animal {
    protected handlers = []
}
```

compile to ES6:

```javascript
class Animal {
    constructor(){
       this._handlers = []
    }
}

class Rebbit extends Animal {
    constructor(){
       this._handlers = []
    }
}
```

**Comment by uMaxmaxmaximus** [comment]
the only way it will not work, expressions like ```this[propName]```

**Comment by DanielRosenwasser** [comment]
Hey @uMaxmaxmaximus 

1. That ES6 code isn't valid - you can't declare a `let` inside of a class. Perhaps you meant something like [this entry in our FAQ](https://github.com/Microsoft/TypeScript/wiki/FAQ#you-should-emit-classes-like-this-so-they-have-real-private-members).
2. We've looked into using `Symbol`s for `private`s in #685 but it didn't turn out well.

In general this comes up every once in a while, but treating `private` members as members on the object itself seems to still be the best approach to use.

**Comment by uMaxmaxmaximus** [comment]
ok, i write coffeescript mod to (typescript and es6) and impliment private props, since you can not
