### ISSUE TITLE
Playground is not supporting for "wrong order" classes

### ISSUE THREAD

**Issue by xsetion** [Microsoft/TypeScript#8633]
**Actual behavior:**

I write two classes in the playground and when I run the code I get an error in the console which land on the extend function.

class Snake extends Greeter {
    constructor() {
		super();
	}
	skip(){}
}
class Greeter {
    constructor() {}
	
	skip(){
		console.log('nothig to skip');
		this.preEnd();
		console.log('so just ended');
	}
	preEnd(){}
}

**Expected behavior:**

The order of the class should not matter.

**Comment by jeffreymorlan** [comment]
Unlike `function`s, classes aren't actually created until the class declaration is reached, so they can't be forward referenced.

**Comment by DanielRosenwasser** [comment]
This is correct. Classes need to be declared before they are referenced on their value side.

**Comment by RyanCavanaugh** [comment]
This will now issue an error in cases where we can tell it's guaranteed not to work
