### ISSUE TITLE
Doc comments for a file module

### ISSUE THREAD

**Issue by basarat** [microsoft/TypeScript#8638]
If I want to write doc comments for a file module how would I do it? One way: 

``` ts
/**
 * Source file level JSDoc comment
 */

/** Some foo */
export var foo = 123;
```

Each `node` has `jsDocComment` however the `SourceFile` `jsDocComment` doesn't contain this comment. It is actually considered as a part of the `foo` identifier node.  TypeDoc tries to use the first jsdoc comment in a file as the file comment (http://typedoc.io/guides/doccomments.html see dynamic modules). Can this be the standard way or will this stay specific to TypeDoc. Is there any standard way? 

:rose: 

> refs https://github.com/alm-tools/alm/issues/78#issue-154976324

**Comment by mhegazy** [comment]
files sometimes have headers that are not intended to be module documentation, e.g. copyright notices, triple slash references, etc.. 
I do not think this would be specifically helpful by itself. might be possible if we look for `"@module"` tag, http://usejsdoc.org/howto-es2015-modules.html

**Comment by basarat** [comment]
> might be possible if we look for "@module" tag

Thanks. That's the kind of consensus I wanted. You can close this issue if you want I have it in my head :rose:

**Comment by mhegazy** [comment]
I think it should be done in the TS API. specifically in `Symbol.getDocumentationComment`, i.e. in https://github.com/Microsoft/TypeScript/blob/master/src/services/services.ts#L39

**Comment by RyanCavanaugh** [comment]
Closing due to low feedback volume
