### ISSUE TITLE
TypeScript MSBuild Offical NuGet not working

### ISSUE THREAD

**Issue by squadwuschel** [Microsoft/TypeScript#8643]
**TypeScript Version:** 
I Try to use the TypeScript MSBuild NuGet for my My VS 2013/2015

https://www.nuget.org/packages/Microsoft.TypeScript.MSBuild/

My csProj looks fine and when I try to start my project, the typeScript files get compiled to js, but the resulting js files are invalide, there I can find "class" or "static" identifier in my javaScript files and so the project is not running.

When I copy my local 1.8 TypeScript installtion from

C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.8

to the 
<MyLocalProjectPath>\packages\Microsoft.TypeScript.MSBuild.1.8.11\tools\tsc\

then the resulting js files work.

A second Problem is, compile on save is not working with MSBuild Package, bevor I've installed the package this was working fine on VS 2013/2015 I am using a ASP.NET 4 Project with csproj settings for TypeScript --> this works for the compile on save: https://github.com/Microsoft/TypeScript/issues/7210

**Expected behavior:**

- valid js files with current offical NuGet Package

**Actual behavior:** 
- current js files created from the NuGet Package are not valid.

**Comment by mhegazy** [comment]
You can get a `class` keyword in the output if you are compiling with `--target es6`.

Do you have a `tsconfig.json` in your project? can you share the project?

**Comment by squadwuschel** [comment]
Sry I need to close the Issue - I've tried it several times this afternoon and it never works. 

Now I tried to reproduce the problem and it allways works fine :-/ sorry.
