### ISSUE TITLE
Inference lost in functions with executed methods as default values

### ISSUE THREAD

**Issue by xLama** [Microsoft/TypeScript#8647]
Sorry for description but I don´t know how describe it.

**TypeScript Version:** 

nightly (1.9.0-dev.20160217)

**Code**

tsconfig.json
```ts
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es5",
        "sourceMap": true,
        "inlineSourceMap": true
        
    },
    "exclude": [
        "node_modules",
        "typings/main",
        "typings/main.d.ts"
    ]
}

```

```ts
class A {

    getFoo() {
        return {
            "foo": "foo"
        }
    }

    getBaz() {
        return {
            "baz": "baz"
        }
    }


    getAll(a = this.getFoo(), b = this.getBaz()): typeof a & typeof b {
        return {
            "foo": "foo",
            "baz": "baz"
        }
    }

}

```
getAll inference: 
![prtscr capture_3](https://cloud.githubusercontent.com/assets/8139881/15330457/303ecace-1c5d-11e6-9b50-f37dd058644c.jpg)

But if we remove return type annotation

![prtscr capture_4](https://cloud.githubusercontent.com/assets/8139881/15330476/49f3827a-1c5d-11e6-9b16-6fd74801b73b.jpg)

But if a default parameter is not a method and rewrite return type annotation:

```ts
function out(){
    return {
        "out" : 
    }
}

class A {

    getFoo() {
        return {
            "foo": "foo"
        }
    }

    getBaz() {
        return {
            "baz": "baz"
        }
    }


    getAll(a = out(), b = this.getBaz()): typeof a & typeof b {
        return {
            "out": "out",
            "baz": "baz"
        }
    }

}


```

![prtscr capture_5](https://cloud.githubusercontent.com/assets/8139881/15330517/7c6ac1dc-1c5d-11e6-826e-8446a908eb62.jpg)

**Comment by malibuzios** [comment]
(tested on `1.9.0-dev.20160517-1.0`, with `noImplicitAny` and `strictNullChecks` enabled)

Simplified example:
```ts
class Example {
    getNumber() {
        return 1;
    }

    doSomething(a = this.getNumber()): typeof a { // <-- errors with noImplicitAny enabled
		return a;
    }
}
```
The error is:
```
'a' implicitly has type 'any' because it does not have a type annotation 
and is referenced directly or indirectly in its own initializer.
```
Compare to:
```ts
function getNumber() {
	return 1;
}

function doSomething(a = getNumber()): typeof a { // <-- works with noImplicitAny enabled
	return a;
}
```
Which doesn't error.

**Comment by xLama** [comment]
@malibuzios Thanks for Simplified example.

**Comment by mhegazy** [comment]
This behaves as i would expect. as the error message states, 
> 'a' implicitly has type 'any' **because it does not have a type annotation 
and is referenced directly or indirectly in its own initializer.**

The compiler tries to know the shape of they type `Example` in  @malibuzios's example, to know that, it needs to know the type of the parameters of the method `doSomething`. it does not have a type annotation, so it tries to infer it from the initializer. the initalizer however refers to `this`. which is the same type it was resolving. Cycles are broken in the TS compiler by giving the type `any`. with `--noImplicitAny` flag on, you get the error message.

this can be solved by adding an explicit type annotation, e.g.:
```ts
    doSomething(a: number = this.getNumber()): typeof a { // <-- errors with noImplicitAny enabled
        return a;
    }
```

**Comment by RyanCavanaugh** [comment]
@mhegazy We shouldn't be resolving the type of every member of `this` during the checking of the initializer. Also, this works in the Playground?

![image](https://cloud.githubusercontent.com/assets/6685088/15333923/9e3d8444-1c20-11e6-9798-f93b0663a30a.png)

**Comment by xLama** [comment]
@RyanCavanaugh  I can confirm that

```ts

class Example {
    getNumber(): number {
        return 1;
    }

    doSomething(a = this.getNumber()): typeof a { // <-- errors with noImplicitAny enabled
        return a;
    }
}

```

wotks fine in 1.8.10 but it does not in nightly (1.9.0-dev.20160217)

**Comment by sandersn** [comment]
The compiler incorrectly thinks that `this.getNumber` refers to the method's `this` in the new this-function-type code. It needs to resolve `this` as the classes' `this` instead.
