### ISSUE TITLE
class extends null error

### ISSUE THREAD

**Issue by uMaxmaxmaximus** [Microsoft/TypeScript#8649]
```typescript
class Class extends null {
  constructor(name:string){
    this.name = name
  }
}
```

Error: this awalible only after call `super()`

```typescript
class Class extends null {
  constructor(name:string){
    super()
    this.name = name
  }
}
```

If i compile TypeScript with target ES6, then compile es6 with Babel,
Babel throw error: Error: you cant call `super()`, cuz null parent class hasnt constructor

Solution:

Typescript must not be throw error if we access to `this` without `super()` if parent class is null.
Null parent class hasn't constructor, an obvious logical fallacy.

Temporary hack:
```typescript
class NullClass extends null {

}

class Class extends NullClass {
    constructor(name:string) {
        super()
        this.name = name
    }
}
```

**Comment by uMaxmaxmaximus** [comment]
Inheritance from null very important, because I like doing AJAX API where the prototype should not be exposed to unnecessary methods

**Comment by mhegazy** [comment]
what version of TS are you using? here is what i get:

```ts
c:\test>type c:\test\file1.ts
∩╗┐class Class extends null {
    public name: string;
    constructor(name: string) {
        this.name = name
    }
}
c:\test>tsc --v
Version 1.9.0-dev.20160513

c:\test>tsc c:\test\file1.ts --t es6

c:\test>echo %ERRORLEVEL%
0

c:\test>type c:\test\file1.js
class Class extends null {
    constructor(name) {
        this.name = name;
    }
}
```
