### ISSUE TITLE
TypeScript MSBuild NuGet not compiling on Build Server

### ISSUE THREAD

**Issue by squadwuschel** [Microsoft/TypeScript#8651]
I am using the current version 1.8.11 of MSBuild.TypeScript from NuGet.

My local installation works fine I can start and when I remove my js files they are created and working.

But when I try to build the project on the BuildServer 2013 (TFS 2013) (with C++ Restributables 2015 installed) then the created build outbut contains no compiled js files, the folder is completly empty.

**Code**

some lines of my csproj. and the relative path are right.

    <TypeScriptToolsVersion>1.8</TypeScriptToolsVersion>
    ...
     <PropertyGroup Condition="'$(Configuration)' == 'DevMvc'">
         <TypeScriptModuleKind>
         </TypeScriptModuleKind>
         <TypeScriptNoEmitOnError>false</TypeScriptNoEmitOnError>
         <TypeScriptTarget>ES5</TypeScriptTarget>
         <TypeScriptJSXEmit>None</TypeScriptJSXEmit>
         <TypeScriptCompileOnSaveEnabled>True</TypeScriptCompileOnSaveEnabled>
         <TypeScriptNoImplicitAny>False</TypeScriptNoImplicitAny>
         <TypeScriptRemoveComments>False</TypeScriptRemoveComments>
         <TypeScriptOutFile />
         <TypeScriptOutDir />
         <TypeScriptGeneratesDeclarations>False</TypeScriptGeneratesDeclarations>
         <TypeScriptSourceMap>True</TypeScriptSourceMap>
         <TypeScriptMapRoot />
         <TypeScriptSourceRoot />
      </PropertyGroup>
      <Import Project="..\..\95_ProjectFiles\packages\Microsoft.TypeScript.MSBuild.1.8.11\tools\Microsoft.TypeScript.targets" Condition="Exists('..\..\95_ProjectFiles\packages\Microsoft.TypeScript.MSBuild.1.8.11\tools\Microsoft.TypeScript.targets')" />
        <Import Project="$(VSToolsPath)\WebApplications\Microsoft.WebApplication.targets" Condition="'$(VSToolsPath)' != ''" />
        <Import Project="$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v10.0\WebApplications\Microsoft.WebApplication.targets" Condition="false" />
        <Target Name="MvcBuildViews" AfterTargets="AfterBuild" Condition="'$(MvcBuildViews)'=='true'">
            <AspNetCompiler VirtualPath="temp" PhysicalPath="$(WebProjectOutputDir)" />
        </Target>

If you need more please tell me what you need. I can't find any TypeScript compile errors in the deployment protocol. When I am looking at the source dir on the TFS there are all NuGet Packetes restored and all files are downloaded, but in the compiled project all js files from TypeScript compilation are missing.

**Expected behavior:**

TypeScript file compilation on BuildServer with MSBuild NuGet Package for TypeScript

**Actual behavior:** 

No Output js files are created on the BuildServer - local compilation works fine.

**Comment by mhegazy** [comment]
what do you see in the build log?

**Comment by squadwuschel** [comment]
what should I see in the build log. e.g. I've a file named "main.app.ts" when I search the Build log I can't finde anything for "main.app"

**Comment by mhegazy** [comment]
do you see a call to `TypeScriptCompile` task? if not, do you have the targets imported? if so do the targets you are importing exist on the build machine in the expected place?

**Comment by squadwuschel** [comment]
when I search in the Log for "TypeScriptCompile" I can't find anything. 

Sorry don't know which targets you mean, I am following the Wiki instructions for this NuGet

https://github.com/Microsoft/TypeScript/wiki/Configuring-MSBuild-projects-to-use-NuGet

the only target to the "Microsoft.TypeScript.targets" in my csproj is the following, it was added from the NuGet and the Path to the Package is right.

    <Import Project="..\..\95_ProjectFiles\packages\Microsoft.TypeScript.MSBuild.1.8.11\tools\Microsoft.TypeScript.targets" Condition="Exists('..\..\95_ProjectFiles\packages\Microsoft.TypeScript.MSBuild.1.8.11\tools\Microsoft.TypeScript.targets')" />

**Comment by mhegazy** [comment]
if you remove the condition, do you see an error for the missing target?

i.e.:

`<Import Project="..\..\95_ProjectFiles\packages\Microsoft.TypeScript.MSBuild.1.8.11\tools\Microsoft.TypeScript.targets" />`

without `Condition="Exists('..\..\95_ProjectFiles\packages\Microsoft.TypeScript.MSBuild.1.8.11\tools\Microsoft.TypeScript.targets')"`

**Comment by squadwuschel** [comment]
thanks for your help, removing the condition helped me a lot.

The Problem was, that we use tfs 2013 which was upgraded from TFS 2010 and we use old Buildproccesstemplates and our own Build Scripts and there are some problems we need to fix.

When I choose the sln as build Target and not our own Build Script and the new Buildprocesstemplates from 2013 then the TypeScript MSBuild Nuget Package works fine. 

Thx much for your Help.
