### ISSUE TITLE
Add observable in typescript and support

### ISSUE THREAD

**Issue by rajeevkumarsharma** [Microsoft/TypeScript#8658]
**TypeScript Version:** 

1.7.5 / 1.8.0-beta / nightly (1.9.0-dev.20160217)

**Code**

```ts
// A self-contained demonstration of the problem follows...

```

**Expected behavior:**

**Actual behavior:**

**Comment by kitsonk** [comment]
I assume you mean the [Stage 1 ES Observable](https://github.com/zenparsing/es-observable) proposal.

Much like many other functional aspects of ECMASCript (Promise, Set, Map, WeakMap, WeakSet, Symbol, Array extras, Object extras, etc...), TypeScript does not "shim" functionality and you need external libraries to provide the functionality.  As stated in the proposal, there are currently two implementations of this:

* [RxJS 5](https://github.com/ReactiveX/RxJS)
* [zen-observable](https://github.com/zenparsing/zen-observable)

In particular, RxJS is actually written in TypeScript.

**Comment by rajeevkumarsharma** [comment]
Typescript has add  **Stage 1 ES Decorators**.

So, We should also add **Observable** into it or simply target 'ES7' feature in typescript.

**Comment by kitsonk** [comment]
Decorators are syntactic features which cannot be functionally polyfilled.

[TypeScript design non-goal](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals#non-goals):

> 6) Provide additional runtime functionality or libraries. Instead, use TypeScript to describe existing libraries.

**Comment by mhegazy** [comment]
As noted by @kitsonk typescript does not provide any polyfills. you can use any polyfill library that you choose.
