### ISSUE TITLE
tsconfig.json detection detect config files in other projects

### ISSUE THREAD

**Issue by Solethia** [Microsoft/TypeScript#8659]
**TypeScript Version:** 

1.8.30.0

**Issue**
We have a solution with a number of web projects. We recently made a new project which used a tsconfig.json file. 

This affected other projects to believe they had a tsconfig.json file, overriding our project typescript settings for those projects.

"One or more tsconfig.json files detected. Project properties are disabled."

I've checked and the project file itself does not contain any reference to any tsconfig.json files nor does the project folder contain a tsconfig file.

**Reproduce**

1. Create two new Web Api projects in same solution.
2. Add a typescript file to each project and accept that they are converted into a typescript project.
3. Add a tsconfig.json to the second project.
4. Open properties for the first project and go to the TypeScript Build Tab. Observe "One or more tsconfig.json files detected. Project properties are disabled."

**Code**

```ts

// None

```

**Expected behavior:**

tsconfig.json detection to only work within project folder or files defined in the project file.

**Actual behavior:** 

tsconfig,json detection aparently appears on a solution level or at least a project will detect tsconfig files that are in other projects folders.

**Comment by mhegazy** [comment]
I can reproduce the same behavior locally as well. @paulvanbrenk can you take a look.

**Comment by paulvanbrenk** [comment]
@Solethia Can you share a repro project on GitHub?

**Comment by mhegazy** [comment]
here you go.
[WebApplication5.zip](https://github.com/Microsoft/TypeScript/files/273319/WebApplication5.zip)

**Comment by paulvanbrenk** [comment]
Fix in Code review

**Comment by Solethia** [comment]
When will we be seeing this in Visual Studio? This issue is currently preventing our Visual Studio Online releases from compiling, essentielle preventing us from getting our nightly updates published, without dooing it manually. Could see it was added to the 2.0 Milestone, but since we have a fix I'm honning soner.

**Comment by paulvanbrenk** [comment]
@Solethia how is this blocking your build? This only affects how the 'Project Properties' are rendered in VS, and you can always edit the project file manually.
