### ISSUE TITLE
JSX formatting

### ISSUE THREAD

**Issue by asvetliakov** [Microsoft/TypeScript#8663]
Not sure if it has been reported yet, tried to find similar issues but didn't find anything.

**TypeScript Version:** 

1.9.0-dev.20160518-1.0

**Code**

``` ts
// A self-contained demonstration of the problem follows...
<div name="test"
     data="test"
     onClick={() => { }}
>
  <div>test</div>
</div>
```

**Expected behavior:**
Same as in example

**Actual behavior:** 

``` ts
<div name="test"
    onClick={() => { } }
    data="test"
    >
    <div>test</div>
</div>

```
1. Attributes need to aligned and take indentation from top attribute (name)
2. Closing tag indentation is a bit strange - any way to make it have same indentation level as opening one?

**Comment by evansb** [comment]
I think 1. is a little bit too opinionated, there are people who wants to keep indentation consistent across lines. +1 to your second point though.

**Comment by Vadorequest** [comment]
I think the same. The first point is oponionated, but the second is valid, IMO.

I also happened to have the same issue using VS Code (itself relying on TS), see http://stackoverflow.com/questions/41428375/vs-code-how-to-align-tag-end-and-tag-opening-when-formatting-jsx/41557692#41557692
