### ISSUE TITLE
Bad TS2346

### ISSUE THREAD

**Issue by wwanghee** [Microsoft/TypeScript#8664]
when I use ...args in ES6 with typescript:

```javascript
function f(x, y, z) {
    // ...
}
var args = [0, 1, 2];
f(...args);
```

it show me the following: 

![image](https://cloud.githubusercontent.com/assets/4279668/15362296/62e60df8-1d47-11e6-9c71-b10a7a6ad6b4.png)

what's wrong? thx~~~

**Comment by mhegazy** [comment]
you can only spread into something that accepts a rest argument. i.e.

```ts
function f(...args) {
    // ...
}
f(...args);
```
