### ISSUE TITLE
Suggestion:Validation on defined types

### ISSUE THREAD

**Issue by rylphs** [Microsoft/TypeScript#8665]
It would be nice if we could write some kind of validation on user defined types. Something like:

```Javascript
type Integer(n:number) => String(n).macth(/^[0-9]+$/)
let x:Integer = 3 //OK
let y:Integer = 3.6 //wrong

type ColorLevel(n:number) => n>0 && n<= 255
type RGB = {red:ColorLevel, green:ColorLevel, blue:ColorLevel};
let redColor:RGB = {red:255, green:0, blue:0}   //OK
let wrongColor:RGB = {red:255, green:900, blue:0} //wrong

type Hex(n:string) => n.match(/^([0-9]|[A-F])+$/)
let hexValue:Hex = "F6A5" //OK
let wrongHexValue:Hex = "F6AZ5" //wrong
```
The value that the type can accept would be determined by the function parameter type and by the function evaluation itself. That would solve other issues like #6902, #6579 or #7982

**Comment by mhegazy** [comment]
Looks like the same thing as #6579. i would add implementation suggestions in that issue instead of creating a new one.

**Comment by rylphs** [comment]
Sorry, I thought that should be in a different issue because the other was just about allow regex patterns in types and I'm asking for a more general feature, but I will suggest there.

Thank you!

**Comment by zspitz** [comment]
@mhegazy If I understand you correctly, the OP provides three examples: `Integer`, duplicated in #4639; `ColorLevel` which could be covered by a combination of #15480 and #4639; and `Hex` which is covered by #6579.

Are there no other possible type validations possible with this?
```
type Even (n: number) => n % 2 == 0;
type Past (dte: Date) => dte < Date.now();
```

**Comment by zspitz** [comment]
@mhegazy Considering that the [OP's comment on #6579](https://github.com/Microsoft/TypeScript/issues/6579#issuecomment-220180091) has (as of this writing) garnered 67 +1s, and this proposal is broader than any of the other more limited special case proposals, can this be reopened?

**Comment by stephen-zhao** [comment]
These are called Dependent Types: https://en.wikipedia.org/wiki/Dependent_type

A very powerful feature indeed, especially if done generically as opposed to case-by-case (regex, range types, etc). If pursued in this form, we would need to be wary of what is or is not allowed in such type predicates (e.g. no type system within the type predicate), since this could lead to undecidable type checking...
