### ISSUE TITLE
Destructuring parameters allows implicit any even with noImplicitAny: true

### ISSUE THREAD

**Issue by OliverJAsh** [Microsoft/TypeScript#8667]
With `noImplicitAny: true` set, the following should fail, but it doesn't:

``` ts
const x = ({ f }) => 1;
```

TS 1.8.7

**Comment by Arnavion** [comment]
Duplicate of #6935

**Comment by mhegazy** [comment]
In deed a duplicate. Should be fixed in typescript@next.
