### ISSUE TITLE
Suggestion: Only create global variable for module if something tangible is exported

### ISSUE THREAD

**Issue by zolem** [Microsoft/TypeScript#8668]
I think it would be great if when creating a module it would only create a global variable for that module if something tangible is exported. Whenever I use Typescript with angular I have no need for the global variable.

```typescript
module a{
    export interface IController{
    }
    angular.module("module").controller("controller", Controller);
    class Controller{
    }
}
```

Nothing tangible is exported here so there is no need to create a global variable of "a".

The nice thing is I can still use the interfaces at design time because of the module and interface. But at runtime there is no need for the javascript variable to exist as it will just be an empty object anyway.

**Comment by RyanCavanaugh** [comment]
Discussed; this would complicate the emitter quite a bit and in the majority of cases there's going to be a global anyway. Workaround of using an IIFE seems acceptable now that local types are supported. #206 is related so if we get more use cases like this we can reconsider that one.

**Comment by zolem** [comment]
@ryancavanaugh so can I still access the local classes/interfaces outside of an IIFE? With angular you still need the type hinting.

**Comment by RyanCavanaugh** [comment]
You'd write e.g.:
```ts
module a{
    export interface IController{
    }
}
(() => {
    angular.module("module").controller("controller", Controller);
    class Controller implements a.IController {
    }
})();
```

**Comment by zolem** [comment]
@RyanCavanaugh Well at this point there is no need to make both a module and an IIFE. I might as well just use the module that is being created empty anyway as in the above comment. There would not be any benefit to your example over mine above that I can tell.
