### ISSUE TITLE
Duplicate Identifier between node.d.ts and lib.d.ts

### ISSUE THREAD

**Issue by yuit** [Microsoft/TypeScript#8675]
**TypeScript Version:** 

nightly with "node.d.ts" from typings

We recently add [this](https://github.com/Microsoft/TypeScript/blob/master/src/lib/es5.d.ts#L867)in to es5.d.ts
**Expected behavior:**
No error
**Actual behavior:** 
Duplicate Identifier with the same property defined in "node.d.ts"

**Comment by mhegazy** [comment]
//CC @RyanCavanaugh who was mentioning this earlier this week.

**Comment by mhegazy** [comment]
The proposed fix is to relax the duplicate definition error for interface members if they have the same type.

**Comment by kitsonk** [comment]
👍 that will make lots of things easier!
