### ISSUE TITLE
Namespace-type merging fails silently across module boundaries

### ISSUE THREAD

**Issue by kourge** [Microsoft/TypeScript#8679]
**TypeScript Version:** 

1.9.0-dev.20160518-1.0

**Code**

`bar/index.ts`:
```ts
export interface Bar {}
```

`foo/index.ts`:
```ts
import {Bar} from '../bar';

namespace Bar {
  export const foo = 3;
}

export const foo = Bar.foo;
```

**Expected behavior:**

`foo/index.js`:
```js
"use strict";
var bar_1 = require('../bar');
var Bar;
(function (Bar) {
    Bar.foo = 3;
})(Bar || (Bar = {}));
exports.foo = Bar.foo;
```

**Actual behavior:** 

`foo/index.js`:
```js
"use strict";
var bar_1 = require('../bar');
var Bar;
(function (Bar) {
    Bar.foo = 3;
})(Bar || (Bar = {}));
exports.foo = bar_1.Bar.foo;
```

**Notes:**
This currently fails silently. At runtime `foo/index.js` will export `{foo: undefined}`. If merging a namespace declaration into a type name imported from another module is not allowed, then this should result in a compilation error. The issue I could find closest to this was #8288.

This issue does not occur if `bar/index.ts` additionally exports a namespace named `Bar`; `tsc` reports `error TS2440: Import declaration conflicts with local declaration of 'Bar'` in such a scenario.

**Comment by kourge** [comment]
Upon further searching, it looks like this issue is nearly identical to #7368.

**Comment by mhegazy** [comment]
Yup, indeed a duplicate.
