### ISSUE TITLE
Detection of duplicate javascript function names !!

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#8684]
_From @ikourfaln on May 18, 2016 11:4_

- VSCode Version: 1.1.1
- OS Version: Windows 10

Steps to Reproduce:

if we have two or more functions with the same name, there is no syntax highlighting error !!

![sans titre](https://cloud.githubusercontent.com/assets/9744226/15356433/8dca48ce-1cf0-11e6-83d7-a099d7e9839f.png)

is this feature not yet available in the language services or I miss samething here ?

_Copied from original issue: Microsoft/vscode#6479_

**Comment by kitsonk** [comment]
I am afraid re-declaration of functions (just like variables) is completely valid JavaScript, even in strict mode:

```js
'use strict';

var a = 'foo';

function foo() {
	console.log(a);
}

var a = 'bar';

function foo() {
	console.log(a);
}

foo(); // logs 'bar' with no errors
```

This would be the domain of a linter versus a syntactical language service.

**Comment by ikourfaln** [comment]
hmmm, thanx for replay @kitsonk but I think that its usefull tu prevent that on Typescript, because there no situation where we can use functions with the same name in same scope.

**Comment by kitsonk** [comment]
It is prevented on TypeScript:

<img width="464" alt="test_ts_-_widgets" src="https://cloud.githubusercontent.com/assets/1282577/15392705/d11492e4-1dc0-11e6-810b-af2dcc481dca.png">

Just not JavaScript:

<img width="464" alt="test_js_-_widgets" src="https://cloud.githubusercontent.com/assets/1282577/15392739/0eb13c60-1dc1-11e6-865b-93bf3d83e6bc.png">

In JavaScript it is a linting issue.  There are a lot of silly things in JavaScript which are disallowed in TypeScript.

**Comment by ikourfaln** [comment]
Good, thanx  @kitsonk  for clarifying that.
