### ISSUE TITLE
making IE specific declarations optional on XMLHttpRequest interface

### ISSUE THREAD

**Issue by ilgooz** [Microsoft/TypeScript#8688]
_XMLHttpRequest_ interface has IE only fields like _msCaching_ but they are not declared as optional with _msCaching?_ syntax. Is there any reason behind of it? I believe they should be declared as optional.
refer https://github.com/Microsoft/TypeScript/commit/1dacb54fbde2c2af772326981e6d753f76b1955a#diff-b32ebd70e111503a0b6d629131e5acdbR775

thank you.

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.
