### ISSUE TITLE
Default tsserver behaviour cannot be changed

### ISSUE THREAD

**Issue by anstarovoyt** [Microsoft/TypeScript#8692]
Hi. I am working on an integration with tsserver and there is a little problem: I need to override a default behaviour for IOSession but I cannot do it because:
1) IOSession and ioSession are private
2) a listening session is always started ([see here](https://github.com/Microsoft/TypeScript/blob/a09b001c6180b39155832b2f18be708ea92da263/src/server/server.ts#L278-L278))

I have to use my own tsserver implementation as a workaround.

Possible solution: check an environment flag before running ioSession.listen().

**Comment by mhegazy** [comment]
For a while we had a different target that packages the server as a library (i.e. without the IO/node pieces), see https://github.com/Microsoft/TypeScript/blob/master/Jakefile.js#L528-L539.

no one was using it, so we stopped building it. we can refresh that if you need it.

**Comment by anstarovoyt** [comment]
It's definitely what I need

**Comment by mhegazy** [comment]
tsserverlibrary should be available in typescript@next starting tomorrow.
