### ISSUE TITLE
Multiple function definitions: if no valid signature is found, error checking is done against the last defined signature.

### ISSUE THREAD

**Issue by schittler** [microsoft/TypeScript#8693]
When multiple overloads of a function are specified and a function call does not match any signature, typescript will iterate through the last defined signature to find the error, even if another signature matches partially.

When a call does not match any signature on the second argument, the first argument is different in the last signature and the calls first argument type matches the any other signature, the error will refer to the first argument type of the later-defined signature instead of the mismatched second argument.

Reduced test case (thanks @Arnavion)

``` ts
    interface Dictionary<T> {
        [index: string]: T;
    }

    interface MemoIterator<T, TResult> {
        (prev: TResult, curr: T, indexOrKey?: any, list?: T[]): TResult;
    }

    declare var _: {
        reduce<T, TResult>(
            collection: Array<T>,
            callback: MemoIterator<T, TResult>,
            accumulator: TResult): TResult;

        reduce<T, TResult>(
            collection: Dictionary<T>,
            callback: MemoIterator<T, TResult>,
            accumulator: TResult): TResult;
    };

    interface IPackageReference {
        name: string;
        version: string;
    }

    interface IPackage {
        dependencies?: IPackageReference[];
    }

    declare var pkg: IPackage;

    _.reduce<IPackageReference, boolean>(pkg.dependencies, function(ref: IPackageReference, state: boolean) {
        return true;
    }, true);

```

**Comment by Arnavion** [comment]
To clarify, the error is reported on `pkg.dependencies`

```
foo.ts(32,38): error TS2345: Argument of type 'IPackageReference[]' is not assignable to parameter of type 'Dictionary<IPackageReference>'.
  Index signature is missing in type 'IPackageReference[]'.
```

whereas the real error is that the arguments of the `function(ref: IPackageReference, state: boolean)` are in the wrong order. Deleting the `Dictionary<T>` overload of `reduce` allows TS to give the correct error.

@DamonGant is using the lodash v3.10 typings. I do not see this issue with the `master` version on DT which is for v4 and has different overloads for `reduce`; with the latter the error is reported correctly. Compare https://gist.githubusercontent.com/DamonGant/5c50a77e17ea201bfe8118f12e0c029a/raw/93e93f0f92ebf99eff57e76282653f6111c7b057/gistfile1.txt with https://gist.githubusercontent.com/Arnavion/5ddbe2b49240c5ce0a8fb6e25325717c/raw/dea335a00e7bf47ace26248bfafa6591201b1a3e/test.ts in the playground.

**Comment by aluanhaddad** [comment]
I've also experienced this issue many times. IIRC it has been around since long before 1.8.10, but I'm not positive. I would very much like to see it fixed as it would make both consuming and authoring `.d.ts` files much easier.

**Comment by RyanCavanaugh** [comment]
We now report on each overload
