### ISSUE TITLE
CommonJS vs UMD vs moduleResolution..

### ISSUE THREAD

**Issue by electricessence** [Microsoft/TypeScript#8695]
```
    "module": "commonjs",
    "target": "es5"
```
or
```
    "module": "umd",
    "target": "es5",
    "moduleResolution": "node"
```
Works perfectly to resolve my ```/node_modules/typscript-dotnet``` library.
But ...
```
    "module": "umd",
    "target": "es5",
```
Does not... :(  (TS2307 for everything including relative references) Can someone explain why?  I'm fine with using commonjs as a module type for subsequent projects.  Just curious why this is.

**Comment by vladima** [comment]
by default if value of `moduleResolution` is not specified we use `node` module resolution if module is `commonjs` and `classic` otherwise. `classic` module resolution does not look into `node_modules` folder
