### ISSUE TITLE
Add closest method of Element

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#8699]
https://dom.spec.whatwg.org/#interface-element

```diff
 interface Element {
+    closest(selector: string): Element;
 }
```

**Comment by glen-84** [comment]
```ts
element.querySelectorAll("button")
```

... is typed as `NodeListOf<HtmlButtonElement>`, could:

```ts
element.closest("form")
```

... be typed as an `HTMLFormElement`?

Or does it require the generics?
