### ISSUE TITLE
Customize formatting with formatOptions inside tsconfig.json

### ISSUE THREAD

**Issue by angelozerr** [Microsoft/TypeScript#8709]
I tell me if it could customize the formatiing inside tsconfig.json like this:

```json
{
  "formatOptions": {
    "insertSpaceAfterCommaDelimiter": true,
    ...
 },
 "compilerOptions": {
   ...
  }
}
```

The benefit with this feature is that:

 * you can customize formation options inside tsconfig.json so your configuration will work with an IDE
 * you can have several formatting configuration in your project (like editorconfig) if you have several tsconfig.json files in your project

What do you think about this idea?

**Comment by mhegazy** [comment]
We have discussed this before; the conclusion was that different editors already have configuration  support in `.editorconfig`files, in project property pages (VS), settings.json (VSCode), etc.. so we should not add yet another one. 

The TSServer today has support of passing format options from the host. where does the host get these configuration is not up to the server.

Since tsconfig.json is a json file, you are welcome to store formatOptions in it, and load them from your  editor and pass them to tsserver, but tsserver will not load them automatically for you.

**Comment by angelozerr** [comment]
Thanks @mhegazy for having taken time to give me an answer.

> The TSServer today has support of passing format options from the host. where does the host get these configuration is not up to the server.

Yes I have seen that but is it possible to post configuration to tsserver for a given file (and not for the project)?

> Since tsconfig.json is a json file, you are welcome to store formatOptions in it, and load them from your editor and pass them to tsserver, but tsserver will not load them automatically for you.

Ok I understand, but do you think it should be possible to update the tsconfig.json schema to define "formatOption" like you have done for "compileOnSave". 

Thanks!

**Comment by mhegazy** [comment]
> Yes I have seen that but is it possible to post configuration to tsserver for a given file (and not for the project)?

yes. the config arguments has an optional file, see: https://github.com/Microsoft/TypeScript/blob/master/src/server/protocol.d.ts#L486-L489

**Comment by angelozerr** [comment]
It seems that Atom provides the capability to define format inside tsconfig.json https://github.com/TypeStrong/atom-typescript/blob/master/docs/tsconfig.md#formatcodeoptions

@mhegazy  @basarat perhaps it should be a good idea to update the tsconfig.json schema with formatCodeOptions like compileOnSave. What do you think about that?

**Comment by basarat** [comment]
@angelozerr Just a note that for [alm.tools](http://alm.tools/) I went with with a combination

* Editorconfig : https://basarat.gitbooks.io/alm/content/config/editorconfig.html
* AND tsconfig : https://basarat.gitbooks.io/alm/content/config/tsconfig.html#formatcodeoptions

:rose:
