### ISSUE TITLE
tsserver is not supporting module declaration overrides.

### ISSUE THREAD

**Issue by michalvankodev** [Microsoft/TypeScript#8710]
Hi!

I'm consuming declaration files from the node packages in my project so I'm not able to modify them.
Therefore I opted to override module definition.

I use redux and redux-thunk. Without this override of Dispatch type all my uses of dispatch will complain about wrong type (Correct behaviour). What redux-thunk does that it allows to dispatch to not dispatch object but also functions that can dispatch multiple objects.

**TypeScript Version:** 

1.8.10

**Code**
// redux-dispatch-override.d.ts
```ts
import * as redux from 'redux';

declare module 'redux' {
    export interface Dispatch<S> {
        <R>(asyncAction: (dispatch: Dispatch<S>, getState: () => S) => R): R;
    }
}
```

**Expected behavior:**
Typescript compiler actually does accept this and will no longer throw errors which is very nice.

**Actual behavior:** 
On the other hand there is a problem with tsserver.
In Webstorm tsserver will no longer consume definitions defined in redux node package. Instead it will try to find all definitions in this overriden declaration.

**Comment by mhegazy** [comment]
As far as i know webstorm does not use tsserver. what makes you believe it is a tsserver issue? do you see the same behavior on VSCode? what version of tsserver are you using?

**Comment by michalvankodev** [comment]
Wow ! :)
It turns out you are right. VSCode behaves as expected!

I didn't know that WS is not using tsserver. Seems like a good default choice to use it.
Thanks for your reply!
