### ISSUE TITLE
Assign module imports to locals (when emitting)

### ISSUE THREAD

**Issue by robinei** [Microsoft/TypeScript#8725]
When the following is compiled to `es5` / `amd` for example:
`import { foo } from './module';`

Is there any reason why usages of `foo` become `module.foo`. Can't the compiler emit code which assigns `foo` to a local variable? The ES6 module syntax doesn't imply that post-import changes to `foo` inside `module` will be reflected. Can this be enabled by a compiler option at least?

Also, related to this (still assuming `es5` / `amd` since I tested that): If I prefix `export` to each item instead of using a separate `export` block, then usages of the exported items will be emitted as `exports.foo` inside their own module. Is there any reason why they are not assigned to, and used through locals (and separately assigned to `exports`) when not using an `export` block?

I tested this using TypeScript 1.8.

**Comment by DanielRosenwasser** [comment]
The indirection is necessary to reflect any changes that might occur across module boundaries. Assigning to a local would not keep the values in sync.

Consider the following module `foo.ts`

```ts
export var thing;

export function assignToThing(newThing) {
    thing = newThing;
}
```

Now imagine a consumer:

```ts
import { thing, assignToThing } from "./foo";

console.log(thing); // prints "undefined"
assignToThing(100);
console.log(thing); // prints "100"
assignToThing(200);
console.log(thing); // prints "200"
```

Assigning `thing` to a local would have it stick with the value `undefined` and never get updated upon calling `assignToThing`.

**Comment by robinei** [comment]
OK reading the ES6 module spec I see that this is the intended behavior there as well. I assumed it would be so "static" as to export values, not bindings.
