### ISSUE TITLE
JSON.stringify without replacer with --strictNullChecks is not available

### ISSUE THREAD

**Issue by dchest** [Microsoft/TypeScript#8729]
**TypeScript Version:** 

nightly (1.9.0-dev.20160521.01)

**Code**

Currently `JSON.stringify` is defined as:

```ts
stringify(value: any): string;
stringify(value: any, replacer: (key: string, value: any) => any): string;
stringify(value: any, replacer: any[]): string;
stringify(value: any, replacer: (key: string, value: any) => any, space: string | number): string;
stringify(value: any, replacer: any[], space: string | number): string;
```

which makes it impossible to provide `space` argument without `replacer` if strictNullChecks is on:
```ts
JSON.stringify(value, undefined, 2)
```

Perhaps, another signature can be added or replacer can be made `| undefined`?

**Comment by mhegazy** [comment]
I believe this was defined before union types. a better signature would be
```ts
stringify(value: any, replacer?: any[] | ((key: string, value:any) => any), space?: string | number): string
```

**Comment by mhegazy** [comment]
looking at the spec: http://www.ecma-international.org/ecma-262/6.0/#sec-json.stringify, 1. null is also allowed for replacer, and 2. array can only be number or string so it should be:

```ts
stringify(value: any, replacer?: null | (number|string)[] | ((key: string, value:any) => any), space?: string | number): string
```

**Comment by basarat** [comment]
Minor Curiousity. Should the `fixed` issues be closed? https://github.com/Microsoft/TypeScript/labels/Fixed :rose:

**Comment by mhegazy** [comment]
PR still not merged, hopefully I will get a :+1: soon on it.

**Comment by DanielRosenwasser** [comment]
I gave it a :+1+.

**Comment by dchest** [comment]
Thank you!
