### ISSUE TITLE
re-exported value is not correct

### ISSUE THREAD

**Issue by wilfrem** [Microsoft/TypeScript#8738]
re-exporting result is not correct.

**TypeScript Version:** 

1.8.10

**Code**

```ts
let foo = "bar";
foo = "baz";
export {
	foo
}
```

**Expected behavior:**
```ts
import * as that from "./code"; // import that ts code
that.foo === "baz"
```

**Actual behavior:** 
`that.foo === "bar"`

http://www.typescriptlang.org/play/index.html#src=let%20foo%20%3D%20%22bar%22%3B%0D%0Afoo%20%3D%20%22baz%22%3B%0D%0Aexport%20%7B%0D%0A%09foo%0D%0A%7D%0D%0A%0D%0A

**Appendix*
https://babeljs.io/repl/#?evaluate=true&lineWrap=false&presets=es2015%2Creact%2Cstage-2&experimental=false&loose=false&spec=false&code=let%20foo%20%3D%20%22bar%22%3B%0D%0Afoo%20%3D%20%22baz%22%3B%0D%0Aexport%20%7B%0D%0A%09foo%0D%0A%7D%0D%0A

**Comment by evansb** [comment]
```typescript
var foo = "bar";
export.foo = foo;

foo = "baz"; // should be export.foo = "baz";
```

**Comment by basarat** [comment]
Verified bug. 


# Note 

For 

```ts
export let foo = "bar";
foo = "baz";
```
we have 
```js
var foo = "bar";
export.foo = "baz";
```
So for 
```ts
let foo = "bar";
foo = "baz";
export {
    foo
}
```
I would expect
```js
var foo = "bar";
export.foo = foo;
export.foo = "baz";
```
But instead we get (the wrong one): 
```js
var foo = "bar";
exports.foo = foo;
foo = "baz"; // note the missing `export.` prefix. 
```

**Comment by evansb** [comment]
It should be `export.foo = foo = "baz";` so that the side effect is visible on local `foo`.

Anyway, my PR already fix this, waiting for merging/further feedback now.

**Comment by basarat** [comment]
Typescript rewrites all local foo to exports.foo ( I think ) 🌹

-- 
Cheers,
BAS (*BAS*arat *A*li *S*yed)
0422 888 669
http://basarat.com

**Comment by mhegazy** [comment]
thanks @evansb!
