### ISSUE TITLE
rootDirs need duplicates?

### ISSUE THREAD

**Issue by ManuelDeLeon** [Microsoft/TypeScript#8741]
**TypeScript Version:** 

nightly (1.9.0-dev.20160522-1.0)

**Description**

I'm trying to add a reference from the root:

```
import {Hero} from "/models/hero";
```

But it only works if I add both `models` and `/models` to the rootDirs array:

tsconfig.json
```
    "rootDirs": [
      "models",
      "/models"
    ]

```

If I only use one (either one) I get `error TS2307: Cannot find module '/models/hero'`

Seems odd that I need both for it to work.

**Comment by vladima** [comment]
can you please provide a repro for this issue? Also `rootDirs` are intended to be used when compiler needs to resolve a relative name that is absent in design time but will exist in runtime. It looks a bit strange (though definitely legal) that import uses  rooted path as a module specifier.

**Comment by ManuelDeLeon** [comment]
https://github.com/ManuelDeLeon/tsrootdirs

I was cleaning it up for the repro and then started getting the annoying ` error TS2300: Duplicate identifier` errors. I couldn't get rid of them completely but the original problem is there nonetheless.

To reproduce it remove either `"models"` or  `"/models"` from the rootDirs and you'll get `error TS2307: Cannot find module '/models/hero'` when you run `tsc`

btw, I'm resorting to `rootDirs` so I can import from the root instead of doing `..\..\..\..\..\..\..\models\hero`. Is there another/better way to accomplish this? (`"moduleResolution": "classic"` made Angular2 barf a whole bunch of errors so I assumed that wasn't the way to go)

**Comment by mhegazy** [comment]
> btw, I'm resorting to rootDirs so I can import from the root instead of doing ..\..\..\..\..\..\..\models\hero

@ManuelDeLeon you should be using `baseUrl` instead of `rootDirs`, you can see more documentation at https://github.com/Microsoft/TypeScript-Handbook/blob/release-2.0/pages/Module%20Resolution.md#base-url
