### ISSUE TITLE
Block scoped variables must not be accessible during its assignment

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#8743]
A ReferenceError is thrown at runtime.

**TypeScript Version:** 

master

**Code**

```ts
let a = ((_ = a) => a)();
//            ^     ^
```

**Expected behavior:**

error

**Actual behavior:** 

pass

**Comment by yortus** [comment]
Can this even be statically analysed in general? `a` can't be referenced in it's *temporal* dead zone. This means it *can* be legal for `a` to be referenced on the RHS of it's own declaration, if say the reference is nested inside a function called on the next tick. E.g. the following would be not be an error (however meaningless):

```ts
let a = setTimeout((_ = a) => a, 0);
```

For the compiler to be able to determine that the OP example is invalid but the above example is valid, it would have to statically understand the temporal behaviour of the RHS, in this case how `setTimeout` works. That's probably up there with the halting problem.

**Comment by falsandtru** [comment]
Right. Your example code should be valid. Thanks.
