### ISSUE TITLE
Submodules?

### ISSUE THREAD

**Issue by AlecTaylor** [Microsoft/TypeScript#8745]
**TypeScript Version:** 

1.9.0-dev.20160522-1.0

**Code**

Here's what I want to do:
```ts
import {isEmail} from 'marker.validators'
```

**Expected behavior:**
For it to just work

**Actual behavior:** 
Submodules don't work that way

---

So currently I do this:

```ts
import {validators} from 'marker';

validators.isEmail('foo@bar.com');
// I want the `isEmail` symbol, without having to `const isEmail = validators.isEmail`
```

#### marker.d.ts
```ts
declare var marker: marker.marker;

declare module marker {
    export interface marker {
        validators: IValidators;
    }

    export interface IValidators {
        isEmail(input: string): boolean;
    }
}

export = marker;
```

#### index.ts
```ts
import * as vs from './validators'

export const validators = vs;
```

#### validators.ts
```ts
export function isEmail(input: string): boolean { return true }
```

---

How am I meant to do this, e.g.: `namespace`s?

BTW: Asked on [StackOverlfow](http://stackoverflow.com/q/37370601) also

**Comment by basarat** [comment]
You should cheat. But you can make that cheating prettier using further destructuring (more https://basarat.gitbooks.io/typescript/content/docs/destructuring.html). Instead of 

    const isEmail = validators.isEmail;

You can 

    const {isEmail} = validators;

:rose:

**Comment by AlecTaylor** [comment]
@basarat Okay, that's slightly nicer, but is there no general solution?

The only other thing I can think of is to iterate over all the objects in `validators`, expose them in `marker`, and inherit the interfaces so `marker` has all validators on it.

But that removes the modularity advantage (and namespacing) :(

**Comment by mhegazy** [comment]
My recommendation is to change `marker` to be split into multiple files, so you can do `import {isEmail} from "marker\validators"`.

**Comment by mhegazy** [comment]
Note that the current behavior matches the ES6 module spec, there is no reference to submodules or using dots to destructure module exports.

**Comment by AlecTaylor** [comment]
Thanks @mhegazy ,

How do I reference it in my d.ts file?

After moving validator.ts to a validators subdirectory, I tried:
```
declare module "marker/validators" {
}
```

But that gave me:
> Error:(6, 16) TS2664: Invalid module name in augmentation, module 'marker/validators' cannot be found.

**Comment by mhegazy** [comment]
do you have a module named `"marker/validators"`? or is it a file `"marker/validators.ts"`?

if it is a file, then the augmentation should be:

```ts
declare module "./marker/validators" {
}
```

it is basically whatever you would have written in `import * as ns from "<mod>"` to import this module.

**Comment by AlecTaylor** [comment]
Just chucked the test-case onto Github, note that usually I have a -dist suffixed project for the .js files:
https://github.com/AlecTaylor/marker

Nothing seems to be working. Note that my typings.json was created with `typings install github:AlecTaylor/marker/marker.d.ts --save`, as an example of how I would use this project elsewhere.

**Comment by mhegazy** [comment]
I am a bit lost. i do not understand what `marker.d.ts` is supposed to represent. The transformation that typings does on the .d.ts is not correct though, but this is a https://github.com/typings/typings bug.

or your import. in `/index.ts` you should just write:
```ts
import {isEmail} from './validators'
```

which means import `isEmial` from `./validators/index.ts`
