### ISSUE TITLE
Module resolution on Visual Studio 2015 is too slow and it shows incorrect errors after the failure of that resolving

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#8746]
**TypeScript Version:** 

1.8.30

When I give a correct path with es6 module syntax after failed by an incorrect path(e.g. `'../../a'` -> `'../../../a'`), VS2015 shows an error of module resolution with a **correct** path _after a few second_ via Error list tab. About **30 seconds** later, module resolution is succeeded and erases errors automatically.

**Comment by mhegazy** [comment]
error reporting is intentionally delayed for a second to avoid feeling too pushy. depending on hte size of your project, there might be some propping on disk that needs to be done.  but it should not keep you waiting. 

can you share some information on the project? files? can you share `tsc --diagnostics`?

**Comment by falsandtru** [comment]
Sorry, now I overwrote the slow code. But incorrect paths are still remained(However, it will be removed by resolving in a few second.). This behavior of VS seems a normal behavior. VS shouldn't display those incorrect errors before really resolving paths.

**Comment by mhegazy** [comment]
> This behavior of VS seems a normal behavior. VS shouldn't display those incorrect errors before really resolving paths.

not sure i understand what you mean.  the errors are not removed until the next time we update the errors for the file. if you wrote an invalid import, and got an error for it, changing it would not remove the error instantaneously. but within a second or so it should. if it is taking longer than that, then it is an bug we need to look into.

**Comment by falsandtru** [comment]
I'll take a gif movie. Can you also review #8830?

**Comment by falsandtru** [comment]
@mhegazy can you take a look?

![path](https://cloud.githubusercontent.com/assets/3143368/15965296/e8566358-2f57-11e6-86f1-bdcfe8ea2086.gif)

**Comment by DanielRosenwasser** [comment]
The sample @falsandtru is working with is https://github.com/falsandtru/localsocket

**Comment by falsandtru** [comment]
What should i do?

**Comment by mhegazy** [comment]
this looks fairly fast to me. is this the normal speed you see?

**Comment by falsandtru** [comment]
This movie speed is adjusted. The normal speed is about 2-10 seconds on my desktop. So I cannot know "This error is correct? or incorrect?". Please don't display incorrect errors.
