### ISSUE TITLE
Async/await wont work properly with nodejs

### ISSUE THREAD

**Issue by NikosEfthias** [Microsoft/TypeScript#8747]
**TypeScript Version:** 

1.8.10

**Code**

```ts
// A self-contained demonstration of the problem follows...
async function dbsave(connect: Promise<Db>, col: string, where: string, obj: update): Promise<void> {
	const db = await connect;
	const coll = db.collection(col);
	const total = db.collection("total");
	const date: Date = new Date();
	total.update({ date: new Date(date.getFullYear(), date.getMonth(), date.getDate()) },
		{
			$inc: {
				count: 1
			}
		}, {
			upsert: true
		});
	/*
	**experimental
	*/
	coll.update({}, {
		$pull: {
			pages: {
				date: {
					$lte: new Date(date.getTime() - (1000 * 60 * 60 * 24))
				}
			}
		}
	}, {
			multi: true
		});
	/*
	***experimental
	*/
	console.log(await coll.update({ _id: where }, obj, { upsert: true }));
	return db.close();
}

```
and at the bottom of page i call the function 
```ts
dbsave(mongodb.connect(options.db), options.collection, addr, doc)
		.catch(e => {
			console.error(e);
		})
```
i have no error during compilation . And after compilation the program is actually running but after first await program newer re-enters the function. and as expected no db operation is done.
**Expected behavior:**
update db and log the object returned from db operation
**Actual behavior:** 
nothing happens res.end() method works but the save db function wont work and no error or log .

**Comment by yortus** [comment]
Are those `.update(...)` method calls returning promises? If so you need to `await` them too. They may be throwing an error, which you'll not see at all with the above code because they are neither `await`ed nor have any catch handers attached to them.

**Comment by aluanhaddad** [comment]
@NikosEfthias I think @yortus is right. In one place you await coll.update and in another you do not. You can await something that isn't a promise but this looks suspect.

**Comment by NikosEfthias** [comment]
i figured the issue out @aluanhaddad  @yortus  when the async function definition is in the scope of its caller  it works but when its defined in global it wont enter back but still it makes no sense to me i guess its something to do with yield in es6
