### ISSUE TITLE
Generic return type of function in Typescript

### ISSUE THREAD

**Issue by paramsinghvc** [Microsoft/TypeScript#8748]
http://stackoverflow.com/questions/37386265/generic-return-type-of-function-in-typescript

**TypeScript Version:** 

1.7.5 / 1.8.0-beta / nightly (1.9.0-dev.20160217)

**Code**

```ts
// A self-contained demonstration of the problem follows...

```

**Expected behavior:**

**Actual behavior:**

**Comment by mhegazy** [comment]
Already answered on SO, let's keep questions to SO and use this tracker for language and compiler bugs.
