### ISSUE TITLE
exported variable do not return correct type

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#8750]
_From @FalloutPL on May 23, 2016 2:11_

**TypeScript Version:** 

1.8.10 Win10, VSCode 1.1.1

TS config:

```ts
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es5",
        "noImplicitAny": false,
        "outDir": "dist",
        "rootDir": "src",
        "sourceMap": true
    },
    "exclude": [
        "node_modules"
    ]
}
```

**Code**

```ts

export interface IDeviceIdentsAttributes {
    id_device: number
    id_ident_type: number
    ident_value: string
}

export interface IDeviceIdentsInstance extends sequelize.Instance<IDeviceIdentsAttributes> { }
export var DeviceIdents = db.connection.define<IDeviceIdentsInstance, IDeviceIdentsAttributes>('device_idents', {model definition}, {options) 
```

**Expected behavior:**

exported DeviceIdents should return type: **sequelize.Model<IDeviceIdentsInstance, IDeviceIdentsAttributes>**

![image](https://cloud.githubusercontent.com/assets/5012042/15458511/8bc0a4ca-209b-11e6-95b0-96f00d7ad72f.png)

**Actual behavior:** 

exported DeviceIdents returns **any**

![image](https://cloud.githubusercontent.com/assets/5012042/15458506/72171158-209b-11e6-944f-9464baec7b42.png)

![image](https://cloud.githubusercontent.com/assets/5012042/15458498/5f8f23e0-209b-11e6-85a4-e7d43c106636.png)

_Copied from original issue: Microsoft/vscode#6643_

**Comment by mhegazy** [comment]
Can you provide more context. i can piece together the repro from the screenshots above.

**Comment by FalloutPL** [comment]
what you need in specific? i think this is problem with intellisense.
i will try post more code later when i can access repo.

**Comment by mhegazy** [comment]
i need a self contained sample that shows the issue.

**Comment by mhegazy** [comment]
closing for now. please reopen with a project.
