### ISSUE TITLE
LanguageService API request : Flattened navigation bar items

### ISSUE THREAD

**Issue by basarat** [Microsoft/TypeScript#8755]
I've added a semantic view to TypeScript [alm.tools](http://alm.tools/): 

![image](https://cloud.githubusercontent.com/assets/874898/15471500/994e9fe0-2139-11e6-8be2-3c913c337fc4.png)

I just used (abused) the `getNavigationBarItems` entry point. Would like to consider get the results flattened using some other API endpoint. Something like 

```
global 
  foo 
  ts.NavigationBar 
    getNavigationBarItems
        createTopLevelItem
```

`getFileOutline`? Just a thought :rose:

**Comment by mhegazy** [comment]
This is should be covered by https://github.com/Microsoft/TypeScript/issues/7523.
