### ISSUE TITLE
An easier way to create new records from existing records that have readonly properties

### ISSUE THREAD

**Issue by zhengbli** [microsoft/TypeScript#8769]
I have the following type:

``` ts
interface IPerson {
    readonly name: string
    readonly gender?: string
    ... // a bunch of other readonly properties
}
var p1: IPerson = { name: "zhengbli", gender: "male", ... };
```

Now I want to create another object from the `p1` variable, that only changes the `name` property. So I imagine the ideal function would look like this:

``` ts
var p2 = cloneWithEdits(p1, { name: "trump" }) { };
```

However, I couldn't figure how the implementation of `cloneWithEdits` should be without losing type safety. 

@DanielRosenwasser has suggested that if all the properties are not optional, I can use type constraints:

``` ts
function cloneWithEdits<T extends U, U>(originalObj: T, edits: U): T {
     ....
}
```

But that doesn't work well with optional properties.

F# has the `with` keyword that does similar thing:

``` fsharp
let p1 = { name: "zhengbli", ... }
let p2 = { p1 with name = "trump" }
```

**Comment by aluanhaddad** [comment]
Am I incorrect In thinking if it would be covered by #2103 ?

**Comment by RyanCavanaugh** [comment]
This is possible with conditional types now
