### ISSUE TITLE
Code completion proposes ___foo although symbol is __foo

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#8778]
**TypeScript Version:**  1.8.10
**VS Code version:** alpha

- create js file with content
```js
__foo;

<cursor>
```
- request code complete
- observe: the first entry returned from code complete tsserver request is:
```json
    {
        "name": "___foo",
        "kind": "warning",
        "kindModifiers": "",
        "sortText": "1"
    }
```
where foo has 3 _ in front although the foo in the file has only two __ in front.

**Comment by DanielRosenwasser** [comment]
Identifier escaping strikes again.
