### ISSUE TITLE
Microsoft.TypeScript.MSBuild 1.9.0 does not support any target frameworks.

### ISSUE THREAD

**Issue by deni35** [Microsoft/TypeScript#8781]
I'm trying to install the last 1.9.0-beta-20160524-1 version, but package can't be restored because of error: 
```Package Microsoft.TypeScript.MSBuild 1.9.0-beta-20160524-1 does not support any target frameworks.```

I got this error in Asp.Net Core rc1 and rc2.

Version 1.8 works normally.

**Comment by mhegazy** [comment]
@paulvanbrenk thoughts?

**Comment by paulvanbrenk** [comment]
@deni35 Can you share your `packages.config` or `project.json`. And which version of `nuget` are you using?

According to the [spec](http://docs.nuget.org/Create/Enforced-Package-Conventions) I could find, we're not doing something weird.

**Comment by deni35** [comment]
I created a new project, so I have the default package.json.

[project.zip](https://github.com/Microsoft/TypeScript/files/280455/project.zip)

**Comment by deni35** [comment]
1.8 has bug, 1.9 has bug (: I will wait for 2.0 (: I hope 2.0 will be soon.
I wonder there is no 1.9 in Roadmap?

**Comment by mhegazy** [comment]
TS 2.0 is the next release. 1.9 is just the tag for the nightly builds, it should switch to 2.0 once we ship that one out.

**Comment by paulvanbrenk** [comment]
@deni35 Which version of Nuget are you using? Do you restore from the command-line or from VS?

**Comment by deni35** [comment]
![default](https://cloud.githubusercontent.com/assets/7755015/15552892/3fae28a6-22c5-11e6-8de7-1033372a2a41.png)
Strangely, command-line doesn't write errors. But VS throws error.
Version of nuget 3.4.3.855.

**Comment by paulvanbrenk** [comment]
@deni35 A second problem is that the way TypeScript targets are currently referenced in ASP.NET Core projects is through the `Microsoft.DotNet.Web.targets`, so we aren't actually able to replace them... this means even if you could install the package, it probably won't work.

I'm working with the ASP.NET team to get this to work, and I'll talk to the NuGet team to try and figure out what's happening.

**Comment by deni35** [comment]
What is there? 
Is it not a bug of TypeScript?

**Comment by paulvanbrenk** [comment]
@deni35 No, this is not a bug specific to TypeScript, but to NuGet.

**Comment by deni35** [comment]
Hm. Then why version 1.8 works normally?
Where can I track this NuGet bug?
