### ISSUE TITLE
Assignability error

### ISSUE THREAD

**Issue by atyapin** [Microsoft/TypeScript#8782]
**TypeScript Version:** 

typescript@1.9.0-dev.20160409

**Code**

```ts
export enum SMTypeEnum { // расположены в порядке возрастания приоритета
  S, I
}
type SMItemType = { messageType: SMTypeEnum, description: string, cssClassSuffix: string}
export var S_M_TYPES: SMItemType[] = [
  {messageType: SMTypeEnum.S, description: "Success", cssClassSuffix: "success"}, // type: "S"
  {messageType: SMTypeEnum.I, description: "Info", cssClassSuffix: "info"}, // type: "I"
];

.....

for (var apm of this.afterPostMessages) {
  this.maxMessageType = Math.max(this.maxMessageType, SMTypeEnum[apm.msgType]);
}

```

**Expected behavior:**
no error
**Actual behavior:** 

error TS2345: Argument of type 'string' is not assignable to parameter of type 'number'.

**Comment by sandersn** [comment]
Can you make this repro standalone? And can you show where the error is located in the code?

**Comment by sandersn** [comment]
Here's what I got from altering the code slightly:

```ts
export enum SMTypeEnum { // расположены в порядке возрастания приоритета
  S, I
}
type SMItemType = { messageType: SMTypeEnum, description: string, cssClassSuffix: string}
export var S_M_TYPES: SMItemType[] = [
  {messageType: SMTypeEnum.S, description: "Success", cssClassSuffix: "success"}, // type: "S"
  {messageType: SMTypeEnum.I, description: "Info", cssClassSuffix: "info"}, // type: "I"
];
let afterPostMessages: SMItemType[];
let maxMessageType: number;
for (var apm of afterPostMessages) {
  maxMessageType = Math.max(maxMessageType, SMTypeEnum[apm.messageType]);
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                            Argument of type 'string' is not assignable to parameter of type 'number'
}
```

This is correct. When you index into an enum with an enum value, which is a number, you get a string. And `Math.max` requires its arguments to be numbers.

In other words, `SMTypeEnum[0] === SMTypeEnum[SMTypeEnum.S] === "S"`. And `Math.max(0, "S")` is a compile error.

**Comment by atyapin** [comment]
Dear Nathan,

thank you for a quick reply.

here is the example
http://plnkr.co/edit/QLLho93zeWWlgd5tjjCx?p=preview

you can see that *typeof SMTypeEnum[apm.msgType]* is *number*


*[image: Встроенное изображение 1]*


With best regards,
Alexander Tyapin

2016-05-24 18:44 GMT+03:00 Nathan Shively-Sanders <notifications@github.com>
:

**Comment by sandersn** [comment]
The example from plnkr is different from the repro at the top of the bug. The original repro has `messageType: SMTypeEnum.S` while the plnkr repro has `msgType: "S"`. So you will find that your plnkr example no longer has a compile error.

Confusingly, at runtime, `SMTypeEnum["S"] === 0` (plnkr), so `typeof` gives you *number*. But `SMTypeEnum[0] === "S"` (original), meaning that `typeof` gives you *string*.

**Comment by atyapin** [comment]
Dear Nathan

I am sorry of confusing you by the initial topic. But still if you look at
the code you can see that problem with types persists.

As you mentioned, SMTypeEnum["S"] === 0 (plnkr), so typeof gives you
*number*
[image: Встроенное изображение 2]

[image: Встроенное изображение 2]


Compiler considers *SMessageTypeEnum[apm.msgType]* as *string*, but you can
see at my plunk that typeof is *number*

[image: Встроенное изображение 3]

Alexander Tyapin

2016-05-25 0:40 GMT+03:00 Nathan Shively-Sanders <notifications@github.com>:

**Comment by sandersn** [comment]
Now I am very confused. I pasted the plunk [into the typescript playground](http://www.typescriptlang.org/play/index.html#src=%0Aexport%20enum%20SMessageTypeEnum%20%7B%20%2F%2F%20%D1%80%D0%B0%D1%81%D0%BF%D0%BE%D0%BB%D0%BE%D0%B6%D0%B5%D0%BD%D1%8B%20%D0%B2%20%D0%BF%D0%BE%D1%80%D1%8F%D0%B4%D0%BA%D0%B5%20%D0%B2%D0%BE%D0%B7%D1%80%D0%B0%D1%81%D1%82%D0%B0%D0%BD%D0%B8%D1%8F%20%D0%BF%D1%80%D0%B8%D0%BE%D1%80%D0%B8%D1%82%D0%B5%D1%82%D0%B0%0A%20%20S%2C%20I%0A%7D%0Atype%20SMItemType%20%3D%20%7B%20messageType%3A%20SMessageTypeEnum%2C%20description%3A%20string%2C%20cssClassSuffix%3A%20string%7D%0A%0Aexport%20class%20App%20%7B%0A%20%20constructor()%20%7B%0A%0A%20%20%20%20let%20afterPostMessages%20%3D%20%5B%0A%20%20%20%20%20%20%7BmsgType%3A%20%22S%22%2C%20id%3A%20%22%22%2C%20number%3A%20%22%22%2C%20message%3A%20%22success.%20code%20no%201%22%7D%2C%0A%20%20%20%20%20%20%7BmsgType%3A%20%22I%22%2C%20id%3A%20%22%22%2C%20number%3A%20%22%22%2C%20message%3A%20%22info.%20code%20no%202%22%7D%2C%0A%20%20%20%20%5D%3B%0A%20%20%20%20let%20maxMessageType%3A%20number%20%3D%200%3B%0A%20%20%20%20for%20(var%20apm%20of%20afterPostMessages)%20%7B%0A%20%20%20%20%20%20maxMessageType%20%3D%20Math.max(maxMessageType%2C%20SMessageTypeEnum%5Bapm.msgType%5D)%3B%0A%20%20%20%20%20%20console.log(%22typeof%20maxMessageType%20is%22%2C%20typeof%20maxMessageType%2C%20maxMessageType)%3B%0A%20%20%20%20%20%20console.log(%22typeof%20apm.msgType%20is%22%2C%20typeof%20apm.msgType%2C%20apm.msgType)%3B%0A%20%20%20%20%20%20console.log(%22typeof%20SMessageTypeEnum%5Bapm.msgType%5D%20is%22%2C%20typeof%20SMessageTypeEnum%5Bapm.msgType%5D%2C%20SMessageTypeEnum%5Bapm.msgType%5D)%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D) (and removed the Angular stuff that isn't available there), and got no errors.

In fact, if you add an extra line `let x = SMessageType[apm.msgType];`, you'll see that the compiler actually considers the type to be `any`, not `string`. I'm not sure why it's not `number`, but I suspect the spec explains why.

Could this be a problem with Webstorm? Their language service does not use our compiler for type checking as far as I know.

**Comment by atyapin** [comment]
Nathan,
please, clarify. Do you think such behaviour is ok and the problem is in on my side and I should use type casting or the problem is on TypeScript side?

I simplified the example. If you put in a playground

```
enum Directions {
    Up, Down, Left, Right
}
export class App {
  constructor() {
	let s = "Up";
// enum
	let d = Directions["Up"]; // let d: Directions
	let dd = Directions[s]; // let d: any

  }
}
```
you can see that for enum `typeof Enum["string literal"]` is `number` while `typeof Enum[string]` is `any`, not `string`.

I changed typescript version to 1.8.10 but error is still here. For compilation I use webpack. The error message is generated after

> ts-loader: Using typescript@1.8.10 and ...workspace-as\as\tsconfig.json

**Comment by sandersn** [comment]
It's a design limitation of enums -- it's an unavoidable consequence of string indexers. String indexers assert that *all* properties have a single type. So, in an enum, the expected string indexer type would conflict with the number indexer type. Here's what you get if you try to build an enum out of an interface:

```ts
interface Enum {
  A: number;
  B: number;
  [s: string]: number; // <-- all properties are of type number
  [n: number]: string; // <-- properties '0', '1', ... are of type string
  // error: '0' of type 'string' is not assignable to 'number'
}
```

One of the indexers has to be of type `any` to get the the double-indexing behaviour we want. So in your example, you'll have to cast `Directions[s]` back to string.
