### ISSUE TITLE
LanguageServiceHost->getScriptSnapshot should allow "undefined" returns with strictNullChecks

### ISSUE THREAD

**Issue by christyharagan** [Microsoft/TypeScript#8783]
Hi all,

Trying out the new strictNullChecks, and I get an error with my implementation of ```getScriptSnapshot``` for ```LanguageServiceHost```

As per the example on the ```Using the Compiler API``` wiki page, this looks like:

```ts
getScriptSnapshot: (fileName) => {
  if (!fs.existsSync(fileName)) {
    return undefined;
  }

  return ts.ScriptSnapshot.fromString(fs.readFileSync(fileName).toString());
}
```

But this now throws an error saying ```IScriptSnapshot | undefined is not compatible with IScriptSnapshot```.

**Comment by mhegazy** [comment]
I did fix this a while back (https://github.com/Microsoft/TypeScript/commit/743fa3c32dc494d1e3c3c0aa1cee657424846eb5). what version of TS are you using?

**Comment by christyharagan** [comment]
I'm sorry, I hadn't updated my typescript.d.ts. My bad!
