### ISSUE TITLE
Optional constructor arguments with accessors are being added to .d.ts as optional class members

### ISSUE THREAD

**Issue by dustinhorne** [Microsoft/TypeScript#8788]
**TypeScript Version:** 
nightly (1.9.0-beta-20160521-3)

When creating a class, if a parameter is added to the constructor as optional and given an accessor (such as private), the compiler generates it as an optional class member in the .d.ts file which then throws a syntax error.

**Expected Behavior**
Either field would be added to the class and set with the optional parameter, meaning it could be null or undefined or a syntax error is displayed at compile time.

**Actual behavior:**
Parameter is added as an optional class field resulting in an error.

**Example class declaration:**
```typescript
export class Foo {
    constructor(private someValue?: any) { }
}
```

**What The Compiler Produces in the Resulting .d.ts:**
```typescript
class Foo {
    private someValue?;
}
```

and the following error:
_Error TS1112 A class member cannot be declared optional._

**Comment by RyanCavanaugh** [comment]
Optional class members are allowed now (#8625). Are you generating the file with one version of the compiler and consuming it with an older version? The provided generated snippet compiles without error in master.

**Comment by dustinhorne** [comment]
We are using it within Visual Studio so technically we're using tools version 1.8.  Is there an updated version of the Visual Studio tooling?  It compiles fine, just shows as an error in the Visual Studio Error List after compilation because it's in the generated .d.ts file.

**Comment by mhegazy** [comment]
you can setup VS to use the latest nightly builds, see https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Nightly%20Builds.md

**Comment by dustinhorne** [comment]
Thanks, I'll check it out.  We're not currently using npm so we will just avoid the error for now and wait for the tooling installer.

**Comment by mhegazy** [comment]
i think we have to fix this issue anyways. https://github.com/Microsoft/TypeScript/issues/8795 provides a compelling example of why `?` should not bind to the property.

**Comment by mhegazy** [comment]
closing in favor of https://github.com/Microsoft/TypeScript/issues/8795
