### ISSUE TITLE
The API for the TypeScript Node Module

### ISSUE THREAD

**Issue by EisenbergEffect** [Microsoft/TypeScript#8799]
I need to use the TypeScript compiler API directly in NodeJS. Where can I find the documentation on the API for compiling code?

**Comment by DanielRosenwasser** [comment]
Hey Rob, we've got some documentation on our wiki. Check out

* [Using the Compiler API](https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API)
* [Using the Language Service API](https://github.com/Microsoft/TypeScript/wiki/Using-the-Language-Service-API).

**Comment by EisenbergEffect** [comment]
Excellent. Thanks!
