### ISSUE TITLE
Generic type inference and intersection types in function parameters

### ISSUE THREAD

**Issue by tmcl** [Microsoft/TypeScript#8801]
**TypeScript Version:** 

$ ./node_modules/.bin/tsc --version
Version 1.8.7

**Code**

```ts
// A self-contained demonstration of the problem follows...
const parameterFn = (props:{store:string}) => alert(props.store)
const brokenFunction = <OwnProps>(f: (p: {dispatch: number} & OwnProps) => void) => (o: OwnProps) => o
export const Form3 = brokenFunction(parameterFn)({store: "hello"})
```

**Expected behavior:**

`OwnProps` is inferred as `{store: string}`. Therefore, the code compiles; `parameterFn` asks for less information than it's given.

**Actual behavior:** 
```
testing.ts(4,37): error TS2345: Argument of type '(props: { store: string; }) => void' is not assignable to parameter of type '(p: { dispatch: number; } & {}) => void'.
  Types of parameters 'props' and 'p' are incompatible.
    Type '{ store: string; }' is not assignable to type '{ dispatch: number; } & {}'.
      Type '{ store: string; }' is not assignable to type '{ dispatch: number; }'.
        Property 'dispatch' is missing in type '{ store: string; }'.
```

**Discussion**
I encountered the error while trying to correct the types for the `redux-react` module; consequently, `brokenFunction` represents a radically simplified version of that package's `connect` function.

The actual error message seems weird; the is no obvious requirement for the function passed in to expect to have `dispatch`.

**Comment by ahejlsberg** [comment]
Yes, it would seem reasonable to infer `{ store: string }` here. The reason we don't currently is that it never really is meaningful in a co-variant location such as a regular parameter. But it actually makes sense in a contra-variant location, as is the case in your example.

**Comment by tmcl** [comment]
Thanks
