### ISSUE TITLE
Find all references doesn't show default export

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#8805]
_From @khoomeister on May 25, 2016 1:5_

- VSCode Version: 1.1.1
- OS Version: Mac 10.11.5
(latest as of May 24 2016)

Steps to Reproduce:

1. Create file `blah.ts` with a default export (e.g. `export default whatever = 123`)
2. In another file, `import someDefault from './blah'`.
3. If you right click on `someDefault` and select "Find all References", should it show the reference to the default export in `blah.ts`?  Right now, it doesn't.

_Copied from original issue: Microsoft/vscode#6851_

**Comment by mhegazy** [comment]
This is the same underlying issue as https://github.com/Microsoft/TypeScript/issues/5513. find all references today does not handle aliases.

closing in favor of https://github.com/Microsoft/TypeScript/issues/5513.
