### ISSUE TITLE
Cannot find module from ./node_modules

### ISSUE THREAD

**Issue by c9s** [Microsoft/TypeScript#8807]
Don't know if this is a expected bahaviour ? I thought loading node modules should be OK?

**TypeScript Version:** 

1.8.0, 1.8.0-beta, also in 1.9.0-dev.20160217

**Install**

     npm install object-assign

so we will have `node_modules/object-assign/index.js` installed.

**Config**

```
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "allowJs": true
  },
  "files": ["entry.ts"]
}
```

**Code**

```ts
import * as assign from "object-assign";
```

**Expected behavior:**

should load the module from `node_modules/object-assign`

**Actual behavior:** 

    error TS2307: Cannot find module 'object-assign'.

**Comment by c9s** [comment]
```
typins install object-assign
```

And change import statement to

```js
import assign from "object-assign";
```

solves this problem.

**Comment by tutok** [comment]
Is there any way to ignore `error TS2307` in case where typings were not available for package installed from npm?

**Comment by RyanCavanaugh** [comment]
```ts
declare module "the-module-name";
```

Which package is missing type definitions? I'm working on a tool to generate these quasi-automatically and am interested to try it out

**Comment by tutok** [comment]
Thanks for quick response!

Should I declare it in `typings\globals\[the-module-name].d.ts` ?
For sure, your one line solution produce `error TS1005: '{' expected.`. I assuem that  your answer a shortcut for writing whole typings for this module, am I right?

I am searching for quick solution for situation where I can not find typings, writing them from scratch is not what I expect.

**Comment by RyanCavanaugh** [comment]
Sorry, that syntax is specific to TS2.0.

It doesn't matter where you place the file as long as it's part of your compilation.

In pre-2.0 you can write the equivalent
```ts
declare module "react-cookie" { 
  var x: any;
  export = x;
}
```
