### ISSUE TITLE
Don't make function parameters required by default

### ISSUE THREAD

**Issue by linvi** [Microsoft/TypeScript#8818]
After installing to Visual Studio 2015 Update 2, the functions parameters are now enforced.

Meaning that if I have a function like

``` c# 
var myFunc = function (hello) {};
```

I must specify the hello value. The solution is to put a `?` character at the end of the variable name (e.g. `hello?`).
But why would you do that? This is so painful and not compatible with javascript standards.

Is there an option to remove this default behaviour?

**Comment by ahejlsberg** [comment]
That's been the behavior in TypeScript all along, it is not new in the latest VS update. TypeScript's purpose is to catch mistakes, such as passing the wrong number of arguments to a function (a very common one). I'm not quite sure what you're proposing here?

**Comment by linvi** [comment]
You are correct. I was used to call function from anonymous objects but it apparently does not work the same if the function is a variable.

``` ts
var t : any = {};
t.funct = function(param) {
                
}
t(); // Works
```

I would personally prefer that the user that a parameter is required instead of the opposite (specifying that  a parameter is optional). But I guess one of the typescript goal is to catch mistakes.

Thank you for your help.
