### ISSUE TITLE
Can't re-use exported variable in object literal shorthand (ES6/CommonJS)

### ISSUE THREAD

**Issue by blakeembrey** [Microsoft/TypeScript#8826]
**TypeScript Version:** 

Version 1.9.0-dev.20160525-1.0

**Code**

```ts
export const test = 'test'

export function foo () {
  run({ test })
}
```

```
tsc index.ts --target es6 --module commonjs
```

**Expected behavior:** Output using `exports.test` alias, or create a local `test` variable.

```ts
"use strict";
exports.test = 'test';
function foo() {
    run({ test: exports.test });
}
exports.foo = foo;
```

**Actual behavior:** Test is `undefined`.

```ts
"use strict";
exports.test = 'test';
function foo() {
    run({ test });
}
exports.foo = foo;
```

**Comment by yuit** [comment]
@DanielRosenwasser @mhegazy considering moving this to 2.1 as this is an emitter bug which will then have to be redo in again in "transforms" branch
