### ISSUE TITLE
type inferrence with structurally identical classes

### ISSUE THREAD

**Issue by rkirov** [Microsoft/TypeScript#8831]
**TypeScript Version:** 

nightly (1.9.0-dev.20160217)

**Code**

```ts
class A {
  foo: string;
}
class B {
  foo: string;
}

function f(a: A | B) {
  if (a instanceof A) {
    // a is inferred to be A here
  } else if (a instanceof B) {
    // a is inferred to be 'never' here
  }
}
```

**Expected behavior:**
`a` should be inferred to be an instance of `B` in the B branch. That is what happens when the program is exectured with `f(new B())`.

**Actual behavior:** 
`a` in inferred to be `never` in the B-branch, because `A | B` was unified to be just `A` structurally.

**Comment by falsandtru** [comment]
See #7271 and #8503.

**Comment by rkirov** [comment]
indeed, exactly the same issue.
