### ISSUE TITLE
Have to import all of React into every file that uses JSX

### ISSUE THREAD

**Issue by bcherny** [Microsoft/TypeScript#8833]
This syntax works:

```ts
import * as React from 'react'

export class MyComponent extends React.Component<{}, {}> {
  render() {
    return <div></div>
  }
}
```

This is the syntax I want to use (with the error thrown by TS):

```ts
import {Component} from 'react'

export class MyComponent extends Component<{}, {}> {
  render() {
    return <div></div>  // [ts] Cannot find name 'React'.
  }                     // (property) JSX.IntrinsicElements.div: __React.HTMLProps<HTMLDivElement>
}
```

Is this expected behavior? Is there a workaround?

**Comment by DanielRosenwasser** [comment]
The way default property imports for CommonJS are looking, the workaround would be

```ts
import React, { Component } from "react";
```

However CommonJS interop for ES modules is still very much in flux, so we're holding off on that.

That said, you could run this through with `--allowSyntheticDefaultImports` and chain it through a tool that will generate the default import for you (e.g. SystemJS, Babel).

**Comment by bcherny** [comment]
@DanielRosenwasser That makes sense, I think, but my question is why does TypeScript need me to import `React` in the first place? The only value I'm using explicitly is `Component` - I'm not using any other React members.

**Comment by DanielRosenwasser** [comment]
When you actually compile `<div></div>`, you actually are using `React` because it compiles down to `React.createElement("div", null)`. If we didn't give you an error, you'd be referring to something that doesn't exist in certain environments. In short, we need something named `React` to exist in the current context.

**Comment by bcherny** [comment]
That makes sense - is there a way to silence the errors? `React` is already defined ambiently, so expecting an explicit import might be overly strict.

**Comment by DanielRosenwasser** [comment]
If you're using modules, I would strongly suggest not doing this since the general direction JS and the broader community is taking is moving away from using global variables. Your dependencies become less explicit (i.e. harder to analyse), and it also removes opportunities for things like asynchronous loading.

But if you're really sure you want to do that, you can use `react-global.d.ts` from https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/react.

**Comment by bcherny** [comment]
I also like explicit imports better, but was unable to find a non-ambient typing for React. This is more of a community/Typings issue, but the command I used was:

```sh
typings install dt~react dt~react-dom --global --save
```

Without the `--global` I get `ERR! Attempted to compile "react" as an external module, but it looks like a global module.`. So it seems like either the typing is ambient, or Typings inferred that it is a global typing (I'm not familiar enough with Typings to know which!).

It also seems that the [React typing](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/7ad4e09016898d9c4837e250121fef2aedbecaaa/react/react.d.ts#L2318) avoid exposing `React` ambiently, which explains the issue I'm having - even though I installed the typing using Typing's `--global` flag, the typing is not actually global and still requires explicitly importing `"react"`.

cc @blakeembrey

**Comment by DanielRosenwasser** [comment]
@bcherny did you figure everything here out?

**Comment by bcherny** [comment]
I did - closing.

**Comment by DanielRosenwasser** [comment]
Would you be able to comment on the specific workaround just so I have an idea of what might've been going wrong? Hopefully we can avoid other users going through the same issues. :smiley:

**Comment by alexeypetrushin** [comment]
UP. Any way to escape `import * as React from 'react'` in every file?

I don't buy this argument about avoiding global, there are tons of globals in JS that aren't going to go anywhere. Like window, etc.
