### ISSUE TITLE
Visual Studio compiles on save only one file and not all changed *.ts files when tsconfig.json exists

### ISSUE THREAD

**Issue by Oblomoff** [Microsoft/TypeScript#8835]
Visual Studio compiles on save only one file and not all changed *.ts files when tsconfig.json exists

Configuration:
Microsoft Visual Studio Enterprise 2015 Version 14.0.25123.00 Update 2
Microsoft .NET Framework Version 4.6.01038
ASP.NET and Web Tools 2015.1   14.1.20512.0
ASP.NET Web Frameworks and Tools 2012.2 4.1.41102.0
ASP.NET Web Frameworks and Tools 2013 5.2.40314.0
TypeScript   1.8.29.0

Create new ASP.NET Core Web Application (.NET Framework)

app/main.ts
```typescript
import {other} from "./other";
alert(other());
```
app/other.ts
```typescript
export function other() {  
    return "other";  
}
```

- Rebuild solution
- Open only other.ts file, press F2 and refactor name of function `other()` to any other name.
- Press `Ctrl+S`

Both *.ts files changed and compiled, everything is ok.

- Add new file
tsconfig.json
```json
{
  "compileOnSave": true
}
```

- Repeat previous steps

Only file other.ts compiled, file main.js leaves intact.

Visual Studio should compile all changed files (not only saved by Ctrl+S in IDE) but

Visual Studio compiles only saved file when tsconfig.json exists.

**Comment by qbunia** [comment]
+1 
Got same problem with project that doesnt contain tsconfig.
Also sometimes visual studio doesnt show me typescript errors in files that are not opened in IDE.

**Comment by mhegazy** [comment]
I can repro this issue locally following the steps outlined by @Oblomoff

**Comment by paulvanbrenk** [comment]
This is fixed in VS 2015 Update 3 **RTM** (_Note_: it's still broken in RC, which was released today).
