### ISSUE TITLE
Disable compile on build

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [Microsoft/TypeScript#8839]
Hello,

I am using TypeScript 1.8.6 and vs2015

`{
	"filesGlob": [
		"App/**/*.ts",
		"typings/tsd.d.ts",
		"!node_modules/**"
	],
	"compileOnSave": false,
	"compilerOptions": {
		"noImplicitAny": false,
		"noEmitOnError": true,
		"removeComments": false,
		"sourceMap": true,
		"target": "es5",
		"module": "commonjs"
	},
	"exclude": [
		"node_modules"
	]
}`

but when building project .js and .maps are generated. Is there any way to disable this action except to hack .csproj file manually?

**Comment by mhegazy** [comment]
set `<TypeScriptCompileBlocked>true</TypeScriptCompileBlocked>` in your project. see http://www.typescriptlang.org/docs/handbook/compiler-options-in-msbuild.html#TypeScriptCompileBlocked for more details.
