### ISSUE TITLE
Missing default when re-exporting with `export =`

### ISSUE THREAD

**Issue by demurgos** [Microsoft/TypeScript#8840]
**TypeScript Version:** 

nightly (`1.9.0-dev.20160518-1.0`)

**Code**

````ts
// export-default.ts
export let foo = "bar";
export default foo;

// re-export.ts
import alias = require("./export-default");
export = alias;

// main.ts
import foo from "./re-export";
console.log(foo);
````

**Expected behavior:**
This project should compile and executing `main.ts` should output `"bar"`.

**Actual behavior:** 
The following compilation error occurs:
````txt
main.ts(1,8): error TS1192: Module '"D:/projects/expor-default/re-export"' has no default export.
````

**Comment**
This issue prevents [typings](https://github.com/typings/typings) from exposing default exports ( [original `typings` issue](https://github.com/typings/typings/issues/525)).

The syntax in `re-export.ts` is used as a workaround for TS preventing the augmentation of module-definitions re-exported with `export * from "export-default"` ([see this issue](https://github.com/typings/registry/pull/270) and [this comment](https://github.com/typings/registry/pull/270#issuecomment-208094474)).

**Comment by blakeembrey** [comment]
@mhegazy this is breaking a few people using default exports with Typings (see https://github.com/typings/typings/issues/525).

**Comment by weswigham** [comment]
If I remember correctly, this is currently because we treat `export = importedNamespace` exactly as `export * from "imported-module";` which, per spec, doesn't reexport default. This would be another point where the two syntaxes would diverge.

**Comment by blakeembrey** [comment]
Thanks @weswigham. In that case, I switched to the `import = export =` syntax because of a different TypeScript issue - originally I used `export *` here which is perfectly fine, except you can't augment things from `export *`. It seems like an odd limitation, since can't you realistically augment `export *` properties in JavaScript? (More information in https://github.com/typings/registry/pull/270).

**Comment by mhegazy** [comment]
I highly recommend not mixing up `export =` patterns in this way. you should be using `export default` and `export * from "mod"` instead.
as @weswigham noted, this is currently working as intended. the module `re-export.ts` really does not have a `default` export.

**Comment by blakeembrey** [comment]
@mhegazy That means Typings does not work and will never work.

**Comment by blakeembrey** [comment]
If you look at the message above, that's how it used to work - but it broke people who wanted to augment modules.

**Comment by unional** [comment]
@mhegazy , IMO, I agree that the interop between ES2015/commonjs is hairy. Until a standard spec is derived we (the consumer) should avoid doing interop and use the module as it intended to be.

But currently it is a necessity as more and more people adapt to ES2015 thanks to Babel and TypeScript. I think we all appreciate the effort the team put in to make this a reality.

As for the interop, it has to be complete. As now commonjs -> ES2015 works (except #7398), and ES2015 -> commonjs also possible:

```ts
import alias = require("./export-default");
export = alias;
```

the solution has to be complete and cannot leave out the `export default` part.
Currently this is a blocking issue. Please reconsider.
