### ISSUE TITLE
Property assignments in constructor should show up in intellisense

### ISSUE THREAD

**Issue by sandersn** [Microsoft/TypeScript#8846]
If you request completion at the `/**/` below...

``` ts
class C {
  constructor() {
    this.x = 'foo';
  }
}
let c = new C();
c./**/;
```

**Expected behavior:**

Completion list should contain `x`.

**Actual behavior:** 

Completion list does not contain `x`.

Currently there is an error at `this.x = 'foo'`, "Property 'x' does not exist in 'C'". That error should stay.

**Comment by DanielRosenwasser** [comment]
Is this a JS language service bug? We explicitly said TypeScript shouldn't recognize this back in October.

https://github.com/Microsoft/TypeScript/issues/5196#issue-110735956

Though I wouldn't be opposed to changing it.

**Comment by mhegazy** [comment]
We should understand the property assignments but still give you an error. This way js and TS work the same way, and we can have better quick fix support.

**Comment by RyanCavanaugh** [comment]
I think this is as fixed as it needs to be
