### ISSUE TITLE
Strict null checks fail on common RegExp pattern

### ISSUE THREAD

**Issue by blakeembrey** [Microsoft/TypeScript#8851]
**TypeScript Version:** 

Nightly

**Code**

```ts
const re = /./g
let match: RegExpExecArray | null

while ((match = re.exec(value)) != null) {
  const length = match[1].length + match[2].length
}
```

**Expected behavior:** Successful compilation.

**Actual behavior:** 

```
error TS2531: Object is possibly 'null'.
```

**Comment by basarat** [comment]
Think its got something to do with `while` as the following works: 

```ts
const re = /./g
let match: RegExpExecArray | null
match = re.exec("somestring")
if (match != null) {
  const length = match[1].length + match[2].length
}
```
:rose:

**Comment by basarat** [comment]
Actually its the compiler not understanding that `==` happens *after* the assignment: 

```ts
const re = /./g
let match: RegExpExecArray | null
if ((match = re.exec("somestring")) != null) {
  const length = match[1].length + match[2].length // Error
}
```

**Comment by basarat** [comment]
### Workaround :rose:

```ts
const re = /./g
let match: RegExpExecArray | null
const value = "some value";
match = re.exec(value);
while (match != null) {
  const length = match[1].length + match[2].length
  match = re.exec(value);
}
```

**Comment by basarat** [comment]
Now I understand what you meant with `fail on common RegExp pattern`. You meant a common coding pattern used with regexes. Sorry about the noise :rose:

**Comment by blakeembrey** [comment]
Correct, yes 👍 Sorry, should maybe have said coding pattern inside statements. For now I worked around it by coercing the type to non-null using `as RegExpExecArray`.

**Comment by ahejlsberg** [comment]
The control flow analyzer isn't currently picking up on the pattern `(x = expr) != null` as a type guard. Shouldn't be too hard to fix. Meanwhile, a workaround is to use the comma operator:

```typescript
const re = /./g
let match: RegExpExecArray | null

while (match = re.exec("abc"), match != null) {
  const length = match[1].length + match[2].length
}
```
