### ISSUE TITLE
Typescript not installing on visual studio 2015

### ISSUE THREAD

**Issue by Vikaskumargd** [Microsoft/TypeScript#8852]
**TypeScript Version:** 

1.7.5 / 1.8.0-beta / nightly (1.9.0-dev.20160217)

**Code**

```ts
// A self-contained demonstration of the problem follows...

```

**Expected behavior:**

**Actual behavior:**

**Comment by mhegazy** [comment]
what version of TS? where did you get it from? what version of VS 2015? what is the error? what are the symptoms? was it working before? do you have setup logs?.....

**Comment by mhegazy** [comment]
closing for now. please provide more information, as noted earlier, to make this issue actionable.
