### ISSUE TITLE
extends dynamic Base class with generic throw an error

### ISSUE THREAD

**Issue by cevek** [Microsoft/TypeScript#8853]
Throw error: `Base constructor return type 'T' is not a class or interface type`
```ts
interface BaseClass<T> {
	new (): T
}
function generateUserClass<T>(baseClass: BaseClass<T>){
	return class extends baseClass {
		name: string;
	}
}
```

Error: `Type any is not constructor function type`
```ts
function generateUserClass<T>(baseClass: any){
	return class extends baseClass {
		name: string;
	}
}
```

But if we specify generic it's work
```ts
function generateUserClass(baseClass: BaseClass<Foo>){
	return class extends baseClass {
		name: string;
	}
}
```
Throw error: `Base constructor return type 'IUser & Base' is not a class or interface type`
```ts
interface IUser {
    name: string;
}
interface IUserClass<T>{
    new (): IUser & T;
}
function genUserCls<T>(base: new ()=>T): IUserClass<T> {
    return null;
}
class Base{
    foo(){}
}
class User extends genUserCls(Base) {}
```
TS version: 1.8

**Comment by sandersn** [comment]
For the first example, on master, I get a different error:

```ts
interface I<T> {
    new(): T
}

function gen<T>(base: I<T>) {
    return class extends base {
                         ^^^^ Base constructor return type 'T' is not a class or interface type
        name: string;
    }
}
```

This error seems correct to me -- T is just a type variable, so we can't know if it's a class or not. However, adding a constraint doesn't make the error go away:

```ts
class Foo { }
function gen<T extends Foo>(base: I<T>) {
  return class extends base {
                       ^^^^ same error here
    name: string
  }
}
```

**Comment by mhegazy** [comment]
this is behaving as i would expect. you can only extend object types, in other words something that of a known structure. type arguments are not. the extend relationship involves checking that the structure of the derived class matches that of the base. without knowing what is the shape of the base, the compiler can not report these errors.

The request to allow classes to extend generic type arguments is tracked by https://github.com/Microsoft/TypeScript/issues/4890

**Comment by cevek** [comment]
Thanks, ahejlsberg example is working
```ts
interface Base{}
interface BaseClass<T> {
    new (): T
}

function generateUserClass<T extends Base>(baseClass: BaseClass<T>){
    class User extends (baseClass as BaseClass<Base>) {
        name: string;
    }
	return User as BaseClass<T & User>;
}

class Model{
	id: number;
}
var User = generateUserClass(Model);
var user = new User();
user.id;
```

**Comment by hszhsh** [comment]
'new User()' is ok, but you cannot create a class that extends User.
