### ISSUE TITLE
Modularize polyfills 

### ISSUE THREAD

**Issue by nippur72** [Microsoft/TypeScript#8854]
As far as I know, polyfill functions are repeated in each file they are needed, resulting in lot of duplicate code.

I suggest to optionally emit them as a module, so that they appear once in a bundled project.

E.g. instead of: 
```js
var __extends = (this && this.__extends) || function (d, b) {
    for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];
    function __() { this.constructor = d; }
    d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
};

var myclass= (function (_super) {
    __extends(myclass, _super);
    // ...
```
emit this:
```js
var __extends = require("typescript-polyfills").extends;

var myclass= (function (_super) {
    __extends(myclass, _super);
    // ...
```

**Comment by kitsonk** [comment]
> ```js
> var __extends = require("typescript-polyfills").extends;
> ```

This assumes everyone is using the Common JS module loader.  What about those using an AMD loader, a SystemJS loader, etc?

**Comment by nippur72** [comment]
oh that was just an example, I guess we could actually use the existing TypeScript capability of turning any import code into the chosen module loader. E.g. a sort of intermediate compilation with:
```
import { extends as __extends } from "typescript-polyfills";

var myclass= (function (_super) {
    __extends(myclass, _super);
    // ...
```
The basic idea here is to put polyfills into modules to save space. But perhaps that work might be delegated to the bundlers (webpack/browserify/etc...) by the use of a specific plugin.

**Comment by kitsonk** [comment]
Still doesn't deal with how the module will be resolvable...

Anyways a quick search shows that this is a dupe of #1350 which was discussed and the solution was #2901 (`noEmitHelpers`) flag.

**Comment by nippur72** [comment]
thanks and sorry for the dupe--I always check but sometimes you don't know what terms to look for.

**Comment by kitsonk** [comment]
Also, for completeness, #3364 is delivering the helpers as a module for TS2.0 as per the roadmap.
