### ISSUE TITLE
Object map notation and classical read access

### ISSUE THREAD

**Issue by AlexGalays** [Microsoft/TypeScript#8859]
If I want to declare an object where all the values are of the same type, I HAVE to declare it like so:

`[s: string]: SomeType;`

Unfortunately, I then can't access its properties using the normal key notation:

`obj.prop`

Why shouldn't this compile? It's what everyone use and is less cumbersome to type than `obj['prop']`

**Comment by sandersn** [comment]
The point of TypeScript is to catch unintentional errors. So it doesn't have anything that allows you to declare arbitrary properties that all have the same type -- basically we believe that people either use an object like a map or like a typed object.

The syntax should reflect that difference -- arbitrary strings with index syntax for maps versus known identifiers with property syntax for objects.

**Comment by AlexGalays** [comment]
Oh well, I see where you're coming from, but since pretty much everything else is 100% compatible with JS I didn't expect this to be any different.
