### ISSUE TITLE
Type inference and noImplicitAny checks don't work

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#8864]
**TypeScript Version:** 

master

**Code**

```ts
const g = f(() => (
  void g(),
  (): void => null));
function f(cb: () => any): () => void {
  return;
}
```

**Expected behavior:**

pass

**Actual behavior:** 

```
$ node built/local/tsc.js --noImplicitAny index.ts
index.ts(1,7): error TS7022: 'g' implicitly has type 'any' because it does not h
ave a type annotation and is referenced directly or indirectly in its own initia
lizer.
```

**Comment by Arnavion** [comment]
It seems the compiler can't deal with `g` being referenced as part of its declaration, so it falls back to `any`. A simpler repro:

```typescript
const f = (func: () => number) => func(); // f: (func: () => number) => number

const g = f(() => 5); // g: number

const h = f(() => (h + 1, 5)); // h: any
```

**Comment by falsandtru** [comment]
It is not a same case. In my case, type inference for `g` should be ignored. expr `(0, 1, 2)` returns `2`.

**Comment by Arnavion** [comment]
Correct, and it's the same in my reduced case. `(h + 1, 5)` is just `5`

**Comment by falsandtru** [comment]
Sorry, it is my fault. I was dead tired XD. TypeScript should refer a type of parentheses by right to left, and shouldn't refer unnecessary expressions. This optimization will improve the performance of tsc. Another, function `f` in my example code is already typed. TypeScript should use that type. For example, type of `g` should be `() => void` because `f` declared return type `() => void`.

**Comment by mhegazy** [comment]
While i agree this is a bug, I do not see us fixing it any time soon. we currently just use `checkExpression` to get the return type of a function, but to address this issue, we will have to do a special pass that excludes the left operand of the comma operator to get to the type without checking references to other declarations that does not contribute to the return type.
Getting this done is not trivial, and i do not think it is worth the value.
