### ISSUE TITLE
Blob property is missing on Window interface

### ISSUE THREAD

**Issue by zuzusik** [Microsoft/TypeScript#8866]
**TypeScript Version:**  

1.8.10

**Code**

```ts
new window.Blob();
```

**Expected behavior:**
compiled

**Actual behavior:** 
error TS2339: Property 'Blob' does not exist on type 'Window'.

**PS**: `new Blob()` works as expected, but I want to access it from `window` in order to be able to mock this method in Angular unit tests by mocking `$window` service.

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.
