### ISSUE TITLE
API for acquiring types

### ISSUE THREAD

**Issue by bowdenk7** [Microsoft/TypeScript#8868]
We should provide a way for others to ask for types that Salsa will fetch. 

We use `bower.json` and `package.json` as sources for fetching types, but Cordova projects have an additional source `config.xml` which lists plugins that also need types. We don't want to check `config.xml` for all projects, nor be dependant on the structure of `config.xml` going forward. But we should allow Cordova to parse it themselves and send us a list of libs that they want types for.

**Comment by mhegazy** [comment]
This looks like an extensibility point for discoverTypings. Related to https://github.com/Microsoft/TypeScript/issues/6508

**Comment by mhegazy** [comment]
//cc:@weswigham
