### ISSUE TITLE
Type definition for Object.create 

### ISSUE THREAD

**Issue by thorn0** [Microsoft/TypeScript#8872]
Is there a reason why in `lib.d.ts`, `Object.create` is defined as following:
```typescript
create(o: any, properties?: PropertyDescriptorMap): any;
```
and not as following
```typescript
create<T>(o: T): T;
create(o: any, properties: PropertyDescriptorMap): any;
```
?

**Comment by basarat** [comment]
Generally one does `const someDict:{[key:string]:Something} = Object.create(null)` :rose:

**Comment by thorn0** [comment]
The return type of `Object.create(null)` still would be `any` with my definition. Also it'd possible to write like this: `Object.create<{[key:string]:Something}>(null)`.

**Comment by mhegazy** [comment]
both these proposals will be an error with `--strictNullChecks` as `null` is not part of the domain of any type, except the type `null`.

i would say a better definition would be:
```ts
create(o: null): any;
create<T>(o: T): T;
create(o: any, properties: PropertyDescriptorMap): any;
```
