### ISSUE TITLE
Sharing documents between projects in tsserver

### ISSUE THREAD

**Issue by vladima** [Microsoft/TypeScript#8874]
Currently we create `DocumentRegistry` [once per project](https://github.com/Microsoft/TypeScript/blob/master/src/server/editorServices.ts#L1358) which means that we don't share anything between multiple open projects (because of that we can end up with multiple copies of i.e. `lib.d.ts`). We should consider using one instance of `DocumentRegistry` that will be utilized for all projects to remove this duplication.

**Comment by mhegazy** [comment]
@vladima is this already fixed in release-2.0.5?

**Comment by vladima** [comment]
Yes, it can be closed
