### ISSUE TITLE
class extends interface generates bad code (possibly only with "Node" name?), no errors

### ISSUE THREAD

**Issue by xHuike** [Microsoft/TypeScript#8875]
**TypeScript Version:** 

1.7.5 / 1.8.0-beta / nightly (1.9.0-dev.20160217)

**Code**
```ts
interface Node
{
   asd:number;
}
class y extends Node
{
   asd2:number;
}
```
```ts
// A self-contained demonstration of the problem follows...
This seems to only happen with the name "Node".
It generates the code with a reference to "Node" function even though none exists. No errors in console. The JS throws.
```

**Expected behavior:**
I get an error "cannot find name "Node"" since a class Node dos not exist (rename Node to something else and you should see the correct behavior).
**Actual behavior:** 
No errors are in console and bad code is generated.

**Comment by kitsonk** [comment]
`Node` is a built-in class in a [browser](https://developer.mozilla.org/en/docs/Web/API/Node).  Therefore TypeScript is correctly assuming you are trying to subclass this built in.  If you are running the code in the browser, you get no errors.  If you are running the code in NodeJS, the base class isn't present to extend, therefore you get an error.

If you did what is better to do with interfaces, and done this:

```
interface Node {
  asd:number;
}
class y implements Node {
  asd2:number;
}
```

You would have gotten an error that says `y does not correctly implement Node`, letting you know that you were trying to extend a built in.
