### ISSUE TITLE
Infer bottom type for type argument when passing empty array

### ISSUE THREAD

**Issue by ivogabe** [Microsoft/TypeScript#8878]
I think the bottom type, `never`, could be used for this case: when passing an empty array to an argument of type `T[]`, where `T` is a type argument.

@ahejlsberg What do you think?

**TypeScript Version:** 

1.7.5 / 1.8.0-beta / nightly (1.9.0-dev.20160528-1.0)

**Code**

```ts
function a<T>(xs: T[]) {
	return xs;
}
const x = a([]);
function b<T extends Node>(xs: T[]) {
	return xs;
}
const y = b([]);
```

**Expected behavior:**
Type of `x` would be `never[]`, `y` would be `Node[]`

**Actual behavior:** 
Type of `x` is `any[]`, `y` is `any[]`.

**Comment by kitsonk** [comment]
Wouldn't `any` be better, with an error if `noImplicitAny` is used?

There was also a lot of discussion of why `{}` gets inferred for generics.  Any change here would cause all sorts of carnage.

**Comment by ivogabe** [comment]
`any` is sound here, but the inference should ideally find the most specific type that is sound. `any` is the least specific type (top type). `never` is more specific than every other type (bottom type). In the body of these functions, there will *never* be a value with the type of the type argument, so `never` is a sound type for the type argument.

`never` is very useful when used with union, as it then just disappears. Taking a union with `any` resolves in `any` and quickly everything is `any`. In this example, `z` is currently inferred as `any` but with this change, it would be `undefined` ( = `never | undefined`).
```typescript
function first<T>(xs: T[]): T | undefined {
	return xs[0];
}
const z = first([]);
```

**Comment by Arnavion** [comment]
```typescript
var x = [];
x.push(5);
```

needs to continue to work, so `x` needs to continue to be `any[]` in this case.

**Comment by ivogabe** [comment]
@Arnavion Agree, but I only wanted this for values of a parameter with a type argument.

**Comment by Arnavion** [comment]
I thought the value of the generic parameter is derived from the type of the expression, so the fact that `[]` is  `any[]` is used to refine `T` to `any`. Even if this isn't actually how the typechecker/binder actually works, it's a simple mental model for TS users. It would be confusing for `[]` to be inferred as `any[]` when assigning to a variable and `never[]` when assigning to a function parameter.

**Comment by ivogabe** [comment]
> I thought the value of the generic parameter is derived from the type of the expression, so the fact that `[]` is `any[]` is used to refine `T` to `any`.

In general, that's true. Though with contextual typing, these types of the arguments will be inferred differently. For instance, the type of `[1, ""]` is `(number | string)[]`. But with contextual typing this could be inferred as a tuple type, `[number, string]`. For instance when `foo<T, V>(a: [T, V])` is called with `foo([1, ""])`. I think that contextual typing could be used to infer the type of `[]` to `never[]`.

**Comment by kitsonk** [comment]
> think that contextual typing could be used to infer the type of `[]` to `never[]`.

It could, but I can't see that being the intent in most cases. Almost every contextual type is as wide as can be inferred.  You are suggesting this one of case (because you have a further widening challenge) to totally narrow down this one case to nothing.  So far every use of `never` is when it is clear that all other types have been eliminated and the type can be no-longer narrowed.  That would never be the case with an `[]` unless of core is it a frozen empty array.

**Comment by ivogabe** [comment]
The type `never` means that that code is not reachable. Currently that happens for instance with type guards (`typeof x === "string" && typeof x === "number"`) and with a function that always throws (`function a() { throw new Error(); }`). When you pass `[]` to a function, and that argument is the only reference to a type argument, the body of that function can never have a value of that type. Thus that type is 'unreachable' in the body and `never` is thus valid here.

I also found out that the following code doesn't work as expected. `y` is inferred as `(string | undefined)[]`, whereas it should be `string[]`. I think that this is related to this issue as well.
```typescript
function concat<T>(xs: T[], ys: T[]): T[] {
	return [...xs, ...ys];
}
const y = concat([], ["a"]);
```

**Comment by ahejlsberg** [comment]
Starting with your last example, it is definitely a bug that `y` is inferred as `(string | undefined)[]` in this example:

```typescript
function concat<T>(xs: T[], ys: T[]): T[] {
    return [...xs, ...ys];
}
const y = concat([], ["a"]);
```

It should be `string[]`. The issue only shows up with `--strictNullChecks` and has to do with the fact that we still infer `undefined[]` for an empty array literal. We need to infer a true bottom type, so in strict null checking mode we should infer `never[]`.

Now, regarding the original proposal to infer `never[]` for this example:

```typescript
function a<T>(xs: T[]) {
    return xs;
}
const x = a([]);  // Could we infer never[]?
```

We actually do infer `never[]` for the array literal, but then we widen then result of the call to `a([])` so we end up with `any[]`. There is a proposal not to do this in #241. The core issue is that we need to modify the widening algorithm and it is not trivial to do. See my comment [here](https://github.com/Microsoft/TypeScript/issues/1436#issuecomment-66855469).

However, even if we stopped widening function results, it isn't clear that we shouldn't widen when we're inferring a type for `x` above. It would be reasonable to keep the `never[]` type only in situations where the type is deeply immutable (a concept we don't currently have), but a `const` is only shallowly immutable. As @Arnavion points out, it would be odd if the following didn't work:

```typescript
const a = [];
a.push(5);  // Don't want an error here
```

Contextual typing was also mentioned in the thread above, but that really doesn't have anything to do with widening.

**Comment by ahejlsberg** [comment]
I did some edits to the comment above to fix some inaccuracies. It should be good now.
