### ISSUE TITLE
Missing implicit any error for inferring an "any" implicitly as a type argument

### ISSUE THREAD

**Issue by JsonFreeman** [Microsoft/TypeScript#888]
```TS
class C<T> {
    constructor(x: T);
    constructor(x: T, y: T);
    constructor(public x: T, public y?: T) { }
}

var constructC: <T>(CConstructorFunction: new (x: T, y: T) => C<T>) => C<T>;
var x = constructC(C).x;
```

The way the type argument inference rules work, we end up inferring to the T's in `CConstructorFunction` from the T's in C's constructor. But because C is generic, it gets instantiated with `any` for that process. We don't give an implicit any error in this case. Is this something we want to do?

**Comment by DanielRosenwasser** [comment]
Any reason `any` is inferred in this process instead of `{}`?

**Comment by JsonFreeman** [comment]
It says this in Section 3.10.6 (Type Inference) in the spec. We are making inferences from S to T (in this case `C` to `new (x: T, y: T) => C<T>`. We hit the following bullet, which causes us to instantiate C with any.
> If M is a construct signature and a corresponding construct signature N exists in S, N is instantiated with the Any type as an argument for each type parameter (if any) and inferences are made from parameter types in N to the corresponding parameter types in M for positions that are present in both signatures, and from the return type of N to the return type of M.

**Comment by mhegazy** [comment]
Should this be a bug instead?

**Comment by JsonFreeman** [comment]
I guess. I'm not sure how we'd detect the implicit any here. We may have to have a different type to track the implicit any introduced by generic signature erasure, and then change it to a regular any at the end of the inference process, or when inferentially typing a parameter. I'm worried that the type would leak though.

**Comment by mhegazy** [comment]
I am inclined to punt on this one. it is rather complicated, we get the right type, but we miss the noImplicitAny warning.

**Comment by JsonFreeman** [comment]
That is fine with me
