### ISSUE TITLE
tsserver should support compileOnSave

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#8884]
**TypeScript Version:** 1.8.x

The tsconfig.json can list compileOnSave which is nicely supported in VS. To make that work on VS Code as well the necessary support should come from the tsserver. We could either send the tsserver and event when a file is saved or the tsserver could make use of its file eventing to detect the case.

**Comment by frogcjn** [comment]
Any Progress? Thanks!

**Comment by mmc41** [comment]
Most wanted feature

**Comment by aleksey-bykov** [comment]
Merged https://github.com/Microsoft/TypeScript/pull/9837

**Comment by zhengbli** [comment]
Note the PR #9837 is not merged in `master` branch, instead it is merged in a recent tsserver re-write branch `tsserverVS-WIP`. Therefore the APIs wouldn't be available in the nightly builds for now.
