### ISSUE TITLE
Type-check a JavaScript file with definition

### ISSUE THREAD

**Issue by andyshuxin** [Microsoft/TypeScript#8887]
Can I type-check a JavaScript file against a `.d.ts`?

Let's say `Print.js` is
```js
function print(s) {
  console.log(s)
}
```

And `Print.d.ts` is 
```typescript
export function print(s: string): void
```

Can I somehow get a warning when I call `print` with the wrong parameter (in JavaScript), say, 
```js
print({hello: 1024})
```
?

**Comment by basarat** [comment]
> Can I somehow get a warning when I call print with the wrong parameter (in JavaScript),

Use `jsdoc` `@param` annotation with types `@param {string}`. See https://developers.google.com/closure/compiler/docs/js-for-compiler#tags :rose:

**Comment by mhegazy** [comment]
this should be covered by https://github.com/Microsoft/TypeScript/issues/6802
