### ISSUE TITLE
Language Service : How to use the `cancellationToken`

### ISSUE THREAD

**Issue by basarat** [Microsoft/TypeScript#8888]
With [alm.tools](http://alm.tools/) I do a whole program analysis in the background if no file has been editing for a while (some seconds). 

The code to get the whole program errors is:

```ts
public getDiagnostics() {
        const program = this.languageService.getProgram();

        return program.getGlobalDiagnostics()
            .concat(program.getSemanticDiagnostics())
            .concat(program.getSyntacticDiagnostics());
}
```

With a simple cancellation token implementation:
```ts
/**
 * Cancellation token
 */
export type CancellationToken = ts.CancellationToken & { cancel: () => void };
export const cancellationToken = (): CancellationToken => {
    let cancelled = false;
    return {
        isCancellationRequested(): boolean {
            return cancelled;
        },
        cancel: () => cancelled = true,
        /** @throws OperationCanceledException if isCancellationRequested is true */
        throwIfCancellationRequested() {
            // Aint throwing nothin
        }
    }
}
```

Converted the said function in my code to: 

```ts
public getDiagnostics(cancellationToken: utils.CancellationToken = utils.cancellationToken()) {
        const program = this.languageService.getProgram();
        return program.getGlobalDiagnostics(cancellationToken)
            .concat(program.getSemanticDiagnostics(undefined, cancellationToken))
            .concat(program.getSyntacticDiagnostics(undefined, cancellationToken));
    }
```
Of course I am very wrong here as the `setTimeout` isn't really called till `getDiagnostics` returns in the below call:

```ts
        // Get all the errors from the project files:
        const cancellationToken = utils.cancellationToken();
        let diagnostics = currentProject.getDiagnostics(cancellationToken);
        // We never get to this setTimeout
        setTimeout(()=>{
            cancellationToken.cancel();
            console.log('cancelled');
        },100)
```

Can someone point me to an example using cancellation token please :rose:

**Comment by basarat** [comment]
I had a deeper look, I see that I definitely need to throw from 

```ts
/** @throws OperationCanceledException if isCancellationRequested is true */
        throwIfCancellationRequested() {
            // Aint throwing nothin
        }
```

However, the thread is completely busy after a call to `program.getSemanticDiagnostics` has left the :gun: so can't really mark for cancellation, or am I mistaken?

**Comment by mhegazy** [comment]
Well, JS is single threaded. and the LS APIs are synchronous, so there is not much we can do here. The only place you have the chance to execute would be in the `isCancellationRequested`. The way cancellation token works now is the host is multi threaded (e.g. VS), so asking the host isCancellationRequested checks on a flag set by another thread.

**Comment by basarat** [comment]
> Well, JS is single threaded. and the LS APIs are synchronous, so there is not much we can do here.

Cool. I'll add the delays in my code, just wanted to be sure I'm not creating stuff that's already there :rose:

> the way cancellation token works now is the host is multi threaded (e.g. VS), so asking the host isCancellationRequested checks on a flag set by another thread

Just curious : So there is *sync* RPC channel from JS (language service) to VS?

**Comment by mhegazy** [comment]
VS hosts the LS in proc in a background thread. Each call to isCancellationRequested goes back to the host, the code there checks the task TPL cancelation token status. Since the host is multithreaded, the cancelation token can be flagged while the js engine is executing, so the next time it checks it gets the notification to cancel. If the host is js as well there is no way to do this without suspending the LS execution.

**Comment by basarat** [comment]
Thanks for the explanations. I'll figure out how to do this in my own code :rose:
