### ISSUE TITLE
Question: Disallow toString / cast to String

### ISSUE THREAD

**Issue by 304NotModified** [Microsoft/TypeScript#8891]
Hi,

I like to disallow (=compiler error) the toString / cast to string for a object. Is this possible? 

**TypeScript Version:** 

1.8

**Code**

I have the following class:
```ts
class Person
{
   private toString(): string {
            return "not allowed";
    }
}
var person1 = new Person();

```

This is now disallowed
```ts
person1.toString();
```

But can I also disallow this?

```ts
var text = person1 + "";
```

**Comment by basarat** [comment]
> Is this possible

Just quick info : Not at the moment :rose:

**Comment by kitsonk** [comment]
You could throw in the `toString()` method if you are really that desperate to keep people from using implicit coercion on your instances.

**Comment by 304NotModified** [comment]
> You could throw in the toString() method if you are really that desperate to keep people from using implicit coercion on your instances.

Yes, we're doing it now, but I was hoping for a better solution. 

Thanks for the replies!
