### ISSUE TITLE
[Errors] wrong identifier in errors that reference indexers

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript#89]
```TypeScript
var a1: { [a: string]: string };
var b1: { [b: string]: number }; 

var r1a1 = a1 < b1;    
```

Expected: 

    !!! Operator '<' cannot be applied to types '{ [a: string]: string; }' and '{ [b: string]: number; }'.

Actual: indexer variable is always 'x'

    !!! Operator '<' cannot be applied to types '{ [x: string]: string; }' and '{ [x: string]: number; }'.

**Comment by DickvdBrink** [comment]
Seems to be fixed
Baseline here: https://github.com/Microsoft/TypeScript/blob/master/tests/baselines/reference/comparisonOperatorWithNoRelationshipObjectsOnIndexSignature.errors.txt#L93
