### ISSUE TITLE
Support wildcards in the new 2.0 Path declaration 

### ISSUE THREAD

**Issue by born2net** [Microsoft/TypeScript#8909]
As far as I can tell this is not possible:

```
  "compilerOptions": {
    "paths": {
      "angular2-redux-util": [
        "npm/angular2-redux-util@*"
      ],
    ...
```
which forces us to hard code versions into tsconfig
```
"npm/angular2-redux-util@0.8.64"
```
is there a way around this?

tx

Sean

**Comment by mhegazy** [comment]
the wildcard is already used for substitution. e.g.
```ts
  "compilerOptions": {
    "paths": {
      "angular2/*": [
        "modules/angular2/*"
      ],
```

this maps `angular2/MyModule` to `modules/angualr2/MyModule`. 

having the wildcard means two different things is ambiguous.


is this for jspm module resolution? if so, then that is tracked by https://github.com/Microsoft/TypeScript/issues/6012

**Comment by born2net** [comment]
got it, TX!!
