### ISSUE TITLE
Add support for JSDoc's @inheritDoc for TypeScript

### ISSUE THREAD

**Issue by jrieken** [Microsoft/TypeScript#8912]
_From @kohzihan on May 31, 2016 22:43_
- VSCode Version: 1.2.0-insider
- OS Version: Win 10

For TypeScript, for instance when a class implements an interface, it would be good if the IntelliSense would recognize JSDoc's `@inheritDoc` and display the JSDoc declared at the parent/interface level instead.

http://usejsdoc.org/tags-inheritdoc.html

_Copied from original issue: Microsoft/vscode#7084_

**Comment by raijinsetsu** [comment]
Any way to get MS to look at this? It seems like it should be simple for VSCode to do.

**Comment by mhegazy** [comment]
PRs are welcomed.

**Comment by cliffkoh** [comment]
Thank you @sjbarag, this is awesome!
