### ISSUE TITLE
Same amd module with different names

### ISSUE THREAD

**Issue by unlight** [Microsoft/TypeScript#8914]
Part of `tsconfig`
```
"target": "es5",
"module": "amd",
"moduleResolution": "node",
```
**TypeScript Version:** 1.8.10
**Code**
```ts
import {provide, enableProdMode} from '@angular/core';
import {APP_ID} from '@angular/core/index';
```

**Expected behavior:**
This supposed to be the same modules. 
```
define(["require", "exports", '@angular/core', ...
```
or
```
define(["require", "exports", '@angular/core/index', ...
```

**Actual behavior:** 
Generated code is:
```
define(["require", "exports", '@angular/core', '@angular/core/index', ...
```
This can be an issue for bundlers.

**Comment by kitsonk** [comment]
How do you expect TypeScript to know that those are the same module?  If they are the same module, use the same MID.  TypeScript is trusting that you know what you are doing and there must be a good reason why you are doing that, as its module resolution logic is only enough to determine what the potential types are for the import.

Also, while you can configure your AMD loader to resolve `@angular/core` to `@angular/core/index.js`, that is not the default behaviour of an AMD loader...  Only `package/main` is equivalent to `package` ([reference](https://github.com/amdjs/amdjs-api/blob/master/CommonConfig.md#packages-)).
