### ISSUE TITLE
New Website Logo: Sky

### ISSUE THREAD

**Issue by davidbohunek** [Microsoft/TypeScript#8915]
Please fill the following out:

- Name: Sky
- Homepage url: http://developers.sky.com
- Brand Guidelines/Licensing: Please can you contact brandteam@bskyb.com, they would like to work with you on that.
- Logo: https://onedrive.live.com/redir?resid=1EC5326F8AD7B1EF!4428&authkey=!AEpYJhZzcsoBoek&v=3&ithint=photo%2cpng

**Comment by davidbohunek** [comment]
Hi, this issue is closed but the logo is still not there? Will it only be updated with release of 2.0?

**Comment by RyanCavanaugh** [comment]
Website logos are batched up and new ones will appear the next time we republish the website, which should happen around the same time as 2.0.

**Comment by davidbohunek** [comment]
Thanks Ryan!
