### ISSUE TITLE
Simple Bundling

### ISSUE THREAD

**Issue by NogginBox** [Microsoft/TypeScript#8918]
I have a web project that consists of several single page apps. I would like each to have a single JS file for each page. Each page uses several small modules. Several small modules are shared, but they're so small I'd rather include them in each page's js file than module load them all. I also do not want to include them all in one master JS file, particularly as some are admin related and should not be accessible to all users.

I would like to be able to include a module in a typescript file and know that the code would be included inline. Something like:

`include('smallmodule');`

This [question on StackOverflow](http://stackoverflow.com/questions/31747366) asks about it, but it doesn't seem to be possible with TypeScript.

**Comment by Arnavion** [comment]
It sounds like you want to take some files a.ts, b.ts, c.ts, ... and compile a subset into foo.js, another subset into bar.js, and so on? If so you can do exactly that by running the subset through tsc with the appropriate `--outFile` and `-m` option. Equivalently you could create foo.tsconfig.json, bar.tsconfig.json and use `tsc -p` with each.

**Comment by NogginBox** [comment]
@Arnavion that would work, but I'd like it to be simple to use, be part of my normal Visual Studio work process and be easy to manage dependencies. I imagined TypeScript would do this in a similar way to SASS for CSS, which lets me break up my CSS files and makes it very easy to combine them into multiple master files.

For now I'm going to add the bundling to Grunt and manage the dependencies manually. This will make me try and limit the number of files I break things down into, to make managing those dependencies easier. I don't think the build system should influence how I structure my program in this way.

Someone has also suggested WebPack, which looks promising, but will require some research. The learning curve for TypeScript has been quite nice till now, and this feels like a wall on that curve.

**Comment by DanielRosenwasser** [comment]
@NogginBox modules tend to be confusing because the JS community in general is still converging on workflows. It's not necessarily a TS-related issue.

Webpack has some great support for multiple entry points and/or listing files as externals. Like @Arnavion mentioned, having several different projects that rely on different parts would also work pretty well.

**Comment by NogginBox** [comment]
@DanielRosenwasser thanks for considering.

I started using TypeScript because I thought it would solve two issues I had with JS. Firstly the type system, which I've been pleased with and secondly the composability of medium sized web apps.

It doesn't really seem to solve the second for me, or there is just more to learn. The books really skim over modules. It seemed really simple when I was reading about it, but in practice I'm missing something.

**Comment by mhegazy** [comment]
If this is a single page app, with no module dependencies, you could use namespaces.. portion your app into files, all within the same namespace, then use `--outFile`. this will give you a single executable that you can include in your app. see how the typescript compiler is authored and put together in https://github.com/Microsoft/TypeScript/blob/master/src/compiler/tsconfig.json

**Comment by aluanhaddad** [comment]
> Someone has also suggested WebPack, which looks promising, but will require some research.

You should also consider [jspm](jspm.io) which has the concept of module arithmetic which allows you to create very specific bundles.
