### ISSUE TITLE
Colorize <any> variable names in Visual Studio

### ISSUE THREAD

**Issue by nippur72** [Microsoft/TypeScript#8919]
I propose to colorize variable names of type `any` with a dedicated color (for example 20% darker or lighter depending on the theme), so that it's easier to differentiate them from typed variables. It would be an additional visual feedback providing useful information on the source code. 

The option could be turned off by simply making the "any" color be the same of "normal text" color.

**Comment by mhegazy** [comment]
identifiers are not colorized based on their types. they are colorized based on their kind, i.e. class vs. interface, vs. variable.
colorizing them based on their types would be a significant amount of work (memory and CPU), and i do not think the value gained by this distinction is worth the cost.
I would recommend using --noImplicitAny to ensure only valid any's can show up in your code.
