### ISSUE TITLE
Cannot import modules with "absolute" path when `module` set to `commonjs`

### ISSUE THREAD

**Issue by unindented** [Microsoft/TypeScript#8920]
**TypeScript Version:** 

1.8.0.10 & nightly (1.9.0-dev.20160601)

**Code**

Small example project here: https://github.com/unindented/ts-webpack-example

Project has the following layout:

```
.
├── app
│   ├── index.css
│   ├── index.html
│   └── index.ts
├── components
│   ├── button
│   │   ├── index.css
│   │   ├── index.html
│   │   └── index.ts
│   └── counter
│       ├── index.css
│       ├── index.html
│       └── index.ts
├── package.json
├── shared
│   ├── backbone_base_view.ts
│   ├── backbone_with_default_render.ts
│   └── backbone_with_subviews.ts
└── tsconfig.json
```

`tsconfig.json` has the following options:

```json
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "noImplicitAny": false,
    "removeComments": false,
    "preserveConstEnums": true,
    "sourceMap": true,
    "outDir": "dist"
  },
  "exclude": [
    "dist",
    "node_modules"
  ]
}
```

**Expected behavior:**

I'd expect `import`s like this one to work:

```typescript
import Counter from 'components/counter/index';
```

**Actual behavior:** 

I get `TS2307` errors:

```
app/index.ts(1,21): error TS2307: Cannot find module 'components/counter/index'.
components/button/index.ts(2,22): error TS2307: Cannot find module 'shared/backbone_base_view'.
components/button/index.ts(3,25): error TS2307: Cannot find module 'shared/backbone_with_default_render'.
components/counter/index.ts(2,22): error TS2307: Cannot find module 'shared/backbone_base_view'.
components/counter/index.ts(3,25): error TS2307: Cannot find module 'shared/backbone_with_default_render'.
components/counter/index.ts(4,27): error TS2307: Cannot find module 'shared/backbone_with_subviews'.
components/counter/index.ts(5,20): error TS2307: Cannot find module 'components/button/index'.
```

However, if I change `module` to `amd`, things do work.

If this is intentional, is there a way to have `commonjs` be able to resolve these kinds of *"absolute"* paths?

**Comment by vladima** [comment]
The way how compiler resolves modules is controlled by `moduleResolution` option that can be either `node` or `classic` (more details can be found [here](https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Module%20Resolution.md)). If this setting is omitted the compiler treats this setting to be `node` if `module` is `commonjs` and `classic` - otherwise.

**Comment by unindented** [comment]
That makes sense. Thank you very much!
