### ISSUE TITLE
Error adding new TypeScript file, issue in template manifest.

### ISSUE THREAD

**Issue by alanpurple** [Microsoft/TypeScript#8928]
![image](https://cloud.githubusercontent.com/assets/4515120/15732236/7bdb9858-28b6-11e6-9fe5-df9028b483a1.png)

Visual Studio 15 Preview2 error with generating ts file
with TypeScript 1.9.0.0 contained in Visual Studio

**Comment by mhegazy** [comment]
@alanpurple, Are other features working correctly?

**Comment by paulvanbrenk** [comment]
Which TypeScript file in the add new item dialog did you select?

**Comment by alanpurple** [comment]
@paulvanbrenk 
add New Item -> Client-side->TypeScript File

.Net Core ->TypeScript works fine

![image](https://cloud.githubusercontent.com/assets/4515120/15918903/c1124ef4-2e46-11e6-956d-217545b07763.png)

**Comment by paulvanbrenk** [comment]
Thanks, those should be going away.. you can search for the correct template, I believe the are in .NET Core / Client-side.

**Comment by paulvanbrenk** [comment]
Checked in a fix for VS "15", but this will be post Preview 4.
