### ISSUE TITLE
Proposal: { myObject.property } as sugar for { property: myObject.property }

### ISSUE THREAD

**Issue by osi-oswald** [Microsoft/TypeScript#8932]
I don't know how this feature is called in C#, but it is quite comfortable in situations where you have to pass certain properties from one object to a new object (or to a function with a single object parameter like react stateless components).

In TypeScript there is already some "implicit" property naming:
```ts
let greeting = 'hello', name = 'world';
let hello = { greeting, name }; // results in hello = { greeting: greeting, name: name };
HelloComponent({ greeting, name });
```

This proposal suggest to bring the previous example one step further:
```ts
let props = { greeting: 'hello', name: 'world' };
let hello = { props.greeting, props.name }; // should results in hello = { greeting: props.greeting, name: props.name };
HelloComponent({ props.greeting, props.name });
```

**Comment by Arnavion** [comment]
TS is just implementing the ES6 shorthand object literals.

Your idea was brought up [here](https://mail.mozilla.org/pipermail/es-discuss/2015-March/042197.html) (see the previous and next posts as well). As mentioned there, while it's possible to convert `{ o.a }` to `{ a: o.a }`, it's not easy to do this for more complicated expressions than `o.a` like computed properties. It seems nothing happened with the discussion after that.

**Comment by osi-oswald** [comment]
Hm, from my perspective the "logic" would simply be "use the last member identifier as property name in the new object". And the current "shorthand object literal " logic is just a special case of this rule. 

I don't get the argument for computed properties, since the "shorthand object literal" feature is not available for computed properties anyways. 

And it is not destructuring either, it is simply "initializing a new object with some property names and their respective values".

How does C# do it? But then again, I guess it is not up to TS to discuss this, sadly :(

**Comment by mhegazy** [comment]
This specific use-case would be better addressed by the object spread operator as noted earlier by @Arnavion, `let hello = { ...props }`. this is currently tracked by https://github.com/Microsoft/TypeScript/issues/2103.

As for the general proposal. expanding shorthand properties past identifiers is a bit ambiguous, for instance, i could thing of at least 3 legitimate meanings for { a.prop }
- `{ "prop" : a.prop }`
- `{ "a.prop" : a.prop }`
- `{ [a.prop] : a.prop }`

Should it be extended to index expressions as well, so would `{ a["prop"] }` be allowed? what about expressions in the indexer position, `{ a["prop" + str + getUniquieName(12)] }`? what about call expressions `{ a.prop() }`? 

Whereas we could agree on answers for all these questions, I would be concerned about TC39 (the JS standardization body) picking a different one, and then we have syntactic ambiguities between TS and JS.

We would like to keep TS as a super-set of JS. We have shied away from adding new syntactic features to TS that may conflict with future features added in JS. 

I would suggest proposing this as a new JS feature first, and as consensuses builds in the committee, TS can easily support the proposal.
