### ISSUE TITLE
Editor Action Format hotkey not working on some jsx markup

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#8933]
_From @CrazyRyDmi on June 1, 2016 16:46_

- VSCode Version:1.1.1
- OS Version:Windows 8.1

Steps to Reproduce:

1. Create .tsx file with simple jsx template (one div element).
2. Add a text with double quotes and put inside it a some substitution (with braces).
3. Press shift+alt+f to perform a format action.

After that formatting will not work on any file of project until vsc restarted.

My example.tsx:
![image](https://cloud.githubusercontent.com/assets/8034149/15717614/d62dbcec-2838-11e6-8b07-81779741b6a0.png)

_Copied from original issue: Microsoft/vscode#7102_

**Comment by oshalygin** [comment]
Having the same issue lately!

**Comment by zhengbli** [comment]
Does not seem to happen using the re-wrote version tsserver. I think this issue was addressed there.
