### ISSUE TITLE
Why "Use undefined, do not use null."?

### ISSUE THREAD

**Issue by lnaie** [Microsoft/TypeScript#8940]
Can someone explain this prescription?

Undefined is a type, used heavily by the JS engine, while null is a value that only the developer can control. I would rather go for null than undefined, because I'm managing it.

**Comment by kitsonk** [comment]
That guide is for those developing the TypeScript compiler, not a general statement about using `null` with TypeScript.  Projects should adopt usage rules around usage of `undefined` and `null` and be consistent in their usage.

**Comment by mhegazy** [comment]
the rational is JavaScript has two concepts to refer to the empty sentinel value, most other programming languages just have one. Moreover, `undefined` is always present, as all uninitialized values have the value `undefined` at run time. `null` on the other hand is avoidable, specially if you are not using any APIs that produce it, e.g. DOM, which the TypeScript compiler does not use.
