### ISSUE TITLE
Namespace-style outputs?

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [Microsoft/TypeScript#8943]
For older browser-based projects that use the `namespace` keyword (or `module` still), it can be inconvenient to interact with AMD/CommonJS/etc. style code.

It would be great if TypeScript could natively compile modern-style modules into the traditional namespaces. This would allow these older projects to interact near-natively with newer code without having to add an additional compilation step or including requirejs.

Here's a proposal for how it would look for a single-file output, where `src/Base.ts` and `src/Children/Child.ts` are written in the import style and compiled to a single file `dist/Compiled.js`:

### src/base.ts

*Original Import Style:*

```typescript
export const Base = true;
```

*Equivalent Namespace Style:*

```typescript
namespace MyProject {
    export const Base = true;
}
```

### src/Children/Child.ts

*Original Import Style:*

```typescript
import { Base } from "../Base";

export const Child = Base.toString();
```

*Equivalent Namespace Style:*

```typescript
/// <reference path="../Base.ts" />

namespace MyProject.Children {
    // Optionally:
    // import Base = MyProject.Base;
    export const Child = Base.toString();
}
```

### dist/Compiled.js

*Output JS in Namespace Style:*

```javascript
var MyProject;
(function (MyProject) {
    MyProject.Base = true;
    var Children;
    (function (Children) {
        Children.Child = MyProject.Base.toString();
    })(Children || (Children = {}));
})(MyProject || (MyProject = {}));
```

*Equivalent Namespace Style:*

```typescript
namespace MyProject {
    export const Base = true;

    namespace Children {
        export const Child = Base.toString();
    }
}
```

#### Errata

* This system assumes that file system directory path === namespace name & path.
* You could make the argument that this would encourage users to stay with this old namespace approach. I would make the counter-point that this would help spread TS adoption, and the benefits of moving to a require-style usage (more modular code, asynchronous loading, etc.) still hold true.
* The motivation for this is the pain of making browser-style distribution versions of a project that both work with requirejs and can be embedded in namespace-y sites.

**Comment by mhegazy** [comment]
this example is rather simple and has no external dependencies. you can not remove all the dependencies on module system and emit all code as global.

We have recently added support for UMD module declaration using `export as namespace`. see https://github.com/Microsoft/TypeScript/issues/7125. i would say this allows you to write modules and chose to expose them as globals if you so choose.

**Comment by DanielRosenwasser** [comment]
I'll add that you can add a module that tacks on a property to whatever the runtime considers the global object, export it to a single AMD file, and then synchronously call `require` on that global module. That's what I would think to do in conjunction with the `export as namespace foo` syntax.

I'm going to close this because I think the transform would be too complex and I think we are moving away from that model of JS development anyway.

**Comment by JoshuaKGoldberg** [comment]
FWIW, I started this as a project here: https://github.com/JoshuaKGoldberg/Typespace

It is useful in very specific scenarios, but I agree with the decision to not include it as a part of TypeScript.
