### ISSUE TITLE
[Salsa] Disable semantic diagnostics checking in javascript projects

### ISSUE THREAD

**Issue by zhengbli** [Microsoft/TypeScript#8947]
As we are not reporting semantic diagnostics in javascript projects anyways, having the semantic diagnostics checking (for both javascript files and .d.ts files) running seems a waste of memory and time. We should at least provide a flag to disable the feature.

**Comment by billti** [comment]
I thought that's what this code did:

https://github.com/Microsoft/TypeScript/blob/master/src/compiler/program.ts#L1434

**Comment by mhegazy** [comment]
> I thought that's what this code did:

this is true for JS files. but a JS project can have non-js files, i.e. definition files. as a mater of fact, we know each project will have at least one (lib.d.ts).

so the proposal here is for `jsconfig.json` to have an implicit `"skipLibCheck": true`.

**Comment by mhegazy** [comment]
This also needs to be done in VS today, as it builds the JS project.

**Comment by mhegazy** [comment]
We need to do this for:
- configured projects with jsconfig.json
- inferred projects with only .js and .d.ts files
- external projects with only .js and .d.ts files

**Comment by zhengbli** [comment]
> - inferred projects with only .js and .d.ts files
> - external projects with only .js and .d.ts files

This does not sound right to me. For example, this means you cannot get diagnostics when editing a stand-along .d.ts file. I would say it is more reasonable to turn it on for inferred projects / external projects with **only** .js file as root files.

**Comment by zhengbli** [comment]
After some offline discussion, turn on the `skipLibCheck` for the following scenarios would make more sense for now:
- Configured projects with jsconfig.json
- External projects with one or more .js files and no .ts or .tsx files
- Inferred projects with one or more .js files and no .ts or .tsx files
