### ISSUE TITLE
Help truncated on Node 6.2

### ISSUE THREAD

**Issue by garthk** [Microsoft/TypeScript#8948]
… because nodejs/node#6456, I'd wager.

See also: #4990

**TypeScript Version:** 1.8.10

**Code**

`tsc --help`

**Expected behavior:**

See full help text, ending:

```
 -w, --watch                         Watch input files.
 @<file>                             Insert command line options and files from a file.
```

**Actual behavior:** 

See partial help text, ending:

```
 --init                              Initializes a TypeScript project and creates a tsconfig.json file.
 --jsx KIND                          Specify JSX code generation: 'preserve' or 'reg
```

**Comment by garthk** [comment]
I figure the fix will be something along the lines of:

```
process.stdout._handle.setBlocking(true);
// output help
process.exit(0)
```

**Comment by DanielRosenwasser** [comment]
This is a bug in Node 6 on Macs as far as we can tell.

**Comment by mhegazy** [comment]
same issue as https://github.com/Microsoft/TypeScript/issues/8793 and almost sure it is caused by nodejs/node#6456 since this code has not changed in a while and it works fine on previous versions of node

**Comment by garthk** [comment]
Closing as duplicate of #8793 per @mhegazy.
