### ISSUE TITLE
Debugging UWP apps is broken in Visual Studio 15

### ISSUE THREAD

**Issue by lilred** [Microsoft/TypeScript#8951]
Copied from [this SO question](http://stackoverflow.com/posts/37604906).

Minimal reproduction (in VS 15):

1. Create a new project using the "JavaScript -> Windows -> Universal -> Blank App (Universal Windows)" template.
2. Rename `main.js` to `main.ts`.
3. Add a `tsconfig.json` file to your project (see [here](http://stackoverflow.com/questions/37493863/how-can-i-create-a-universal-windows-application-using-typescript-in-visual-stud) for why).
4. Enter the following code in `main.ts`:  
```declare var foo: any;
foo();```
5. Go to "Debug -> Windows -> Exception Settings" and check "JavaScript Runtime Exceptions".
6. Click the green "Run on Local Machine" button.

An error message appears:

>Unable to activate Windows Store app [...]. The wwahost.exe process started, but the activation request failed with error 'Windows was unable to communicate with the target application. This usually indicates that the target application's process aborted. More information may be available in the Debug pane of the Output window (Debug->Window->Output)'.

Expected behavior: the IDE should break on `foo();`.

**Comment by mhegazy** [comment]
As noted in https://github.com/Microsoft/TypeScript/issues/8950, UWP is not currently supported. 
This should be covered by https://github.com/Microsoft/TypeScript/issues/8950.
