### ISSUE TITLE
[Transforms] Wrong emit for "for..of" loop for Map instance

### ISSUE THREAD

**Issue by Vizer** [Microsoft/TypeScript#8954]
Hi gyus,
I could not find duplicate so I am posting here.

**TypeScript Version:** `1.8.9`
Target: `es5`

**Code:**

```ts
var myMap = new Map();
myMap.set(0, "zero");
myMap.set(1, "one");
for (var [key, value] of myMap) {
  console.log(key + " = " + value);
}
```
**Actual emit:** 
```js
var myMap = new Map();
myMap.set(0, "zero");
myMap.set(1, "one");
for (var _i = 0, myMap_1 = myMap; _i < myMap_1.length; _i++) {
    var _a = myMap_1[_i], key = _a[0], value = _a[1];
    console.log(key + " = " + value);
}
```
The problem is that `Map`(and `Set` too) instance does not have `length` property, instead it has `size` property. As result loop does not traverse

[Playground](http://www.typescriptlang.org/play/index.html#src=var%20myMap%20%3D%20new%20Map()%3B%0D%0AmyMap.set(0%2C%20%22zero%22)%3B%0D%0AmyMap.set(1%2C%20%22one%22)%3B%0D%0Afor%20(var%20%5Bkey%2C%20value%5D%20of%20myMap)%20%7B%0D%0A%20%20console.log(key%20%2B%20%22%20%3D%20%22%20%2B%20value)%3B%0D%0A%7D)

**Comment by kitsonk** [comment]
ES5 does not have Maps or Sets or iterators.  How are you polyfilling these?  The Playground example complains `Map` is not found.

When targeting ES5, TypeScript will on allow a down emit of Arrays or Strings using the `for...of` construct.

When targeting ES5 with polyfilled iterators, you would have to use some [functional replacement](https://github.com/dojo/core/blob/fe595b1f415106698aa7af7e49cbec36ac958421/src/iterator.ts#L101) that replicates the `for...of` construct that deals with the polyfilled iterator interface.

TypeScript will still emit on error by default.  If you aren't getting errors at design time, then your polyfill is incorrectly extending Array.

**Comment by Vizer** [comment]
Currently I am targeting browsers that provides native support for Map (IE11+)

I have workaround, so it is not critical for me. I am just curious to use for..of loop.

**Comment by kitsonk** [comment]
The partial implementation in IE11 does not support the iterator interface.  It isn't part of ES5 nor part of ES6.  The is no reliable way of TypeScript to down emit that when targeting ES5.
