### ISSUE TITLE
Subresource Integrity for HTMLScriptElement and HTMLLinkElement

### ISSUE THREAD

**Issue by DamonGant** [Microsoft/TypeScript#8955]
Subresource Integrity (SRI) is currently a [W3 Proposed Recommendation](https://www.w3.org/TR/SRI/#). [It ships with current versions of Firefox and Chrome.](https://www.chromestatus.com/features/6183089948590080)

Setting the `integrity` property should not hurt other browsers, it is a progressive enhancement.

**TypeScript Version:** 

nightly (1.9.0-dev.20160603)

**Code**

```ts
// A self-contained demonstration of the problem follows...
let script = document.createElement('script');
script.integrity = "sha-256-some-hash"
```

**Expected behavior:**

`integrity` property is defined

**Actual behavior:** 

`integrity` property is not defined

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.

**Comment by haskellcamargo** [comment]
I've edited the `TSJS-lib-generator` to support this property. Reference: https://github.com/Microsoft/TSJS-lib-generator/pull/113
