### ISSUE TITLE
Provide documentation for compiler

### ISSUE THREAD

**Issue by raDiesle** [Microsoft/TypeScript#896]
Provide documentation for compiler

would be great, as well as documenting version changes.

**Comment by mhegazy** [comment]
just for reference, i have added a few doc pages:
- [compiler options](https://github.com/Microsoft/TypeScript/wiki/Compiler%20Options)
- [tsconfig](https://github.com/Microsoft/TypeScript/wiki/tsconfig.json)
- [Setting compiler options through MSBuild](https://github.com/Microsoft/TypeScript/wiki/Setting-Compiler-Options-in-MSBuild-projects)
- [Architecture](https://github.com/Microsoft/TypeScript/wiki/Architectural-Overview), [API documentation](https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API) and [Dev Mode](https://github.com/Microsoft/TypeScript/wiki/Dev-Mode-in-Visual-Studio)

The handbook has moved to its own repo as well: https://github.com/Microsoft/TypeScript-Handbook
The wiki for this repo is also accepting PRs at: https://github.com/Microsoft/TypeScript-wiki

I still need to write something about ordering files using --out.

As always, suggestions welcomed!
