### ISSUE TITLE
Internal typescript error with no useful information

### ISSUE THREAD

**Issue by anstosa** [Microsoft/TypeScript#8961]
I'm trying to compile an existing codebase and getting an error message with no useful context at all and which doesn't reference any of my code. Any pointers here?

```
Using tsc v1.8.10
/usr/lib64/extrahop_node_modules/node_modules/typescript/lib/tsc.js:33078
                throw e;
                      ^
TypeError: Cannot read property 'id' of undefined
    at getNodeId (/usr/lib64/extrahop_node_modules/node_modules/typescript/lib/tsc.js:11646:18)
    at getNodeLinks (/usr/lib64/extrahop_node_modules/node_modules/typescript/lib/tsc.js:12007:26)
    at checkExpressionCached (/usr/lib64/extrahop_node_modules/node_modules/typescript/lib/tsc.js:20308:25)
    at /usr/lib64/extrahop_node_modules/node_modules/typescript/lib/tsc.js:13842:107
    at Object.map (/usr/lib64/extrahop_node_modules/node_modules/typescript/lib/tsc.js:163:29)
    at getTypeOfVariableOrParameterOrProperty (/usr/lib64/extrahop_node_modules/node_modules/typescript/lib/tsc.js:13842:57)
    at getTypeOfSymbol (/usr/lib64/extrahop_node_modules/node_modules/typescript/lib/tsc.js:13958:24)
    at writeLiteralType (/usr/lib64/extrahop_node_modules/node_modules/typescript/lib/tsc.js:13281:33)
    at writeAnonymousType (/usr/lib64/extrahop_node_modules/node_modules/typescript/lib/tsc.js:13176:25)
    at writeType (/usr/lib64/extrahop_node_modules/node_modules/typescript/lib/tsc.js:13064:25)
```

**Comment by vladima** [comment]
can you share the repro scenario for this issue?

**Comment by anstosa** [comment]
Unfortunately, no. I can't narrow down what's causing this in a repo of several hundred files. I'm hoping someone has tips on what might be causing this or troubleshooting steps so I don't have to just poke blindly... every similar error I saw while researching this error referenced the user's code above the stack trace... it seems like this is being thrown by TS from TS.

**Comment by mhegazy** [comment]
can you try using node-inspector to debug the tsc.js process:

```ts
npm install -g node-inspector
node-inspector

node --debug-brk <path to your tsc.js>
```

somewhere on the stack, there should be a call to `getDiagnosticsWorker`. the argument `sourceFile.fileName` will tell you which file is causing the issue. hopefully this helps to narrow down the repro.

**Comment by mhegazy** [comment]
also a longer stack trace would be helpful. for that try:
> node --stack-trace-limit=1000 tsc.js ...

**Comment by anstosa** [comment]
Thanks @mhegazy! I was never able to get an isolated repro for this but I did narrow it down to 3 problem files and it seemed to be related to binding functions in the constructor? `this.foo = this.foo.bind(this);`.

Removed those and now it all compiles. ¯\_(ツ)_/¯

**Comment by mhegazy** [comment]
was this a .js or a .ts file? we would love to figure out the issue and fix so you do not have to change your code.

**Comment by anstosa** [comment]
It was a `.js` file with `--allowJs`. I was compiling via [grunt-ts](https://github.com/TypeStrong/grunt-ts).

**Comment by mhegazy** [comment]
is there any chance you can share a sample? we would be happy to sign any NDA to get access to the code.

**Comment by anstosa** [comment]
Let me check with my manager. I'll also try to revisit this by the end of the week and try to figure out what actually happened. I'm in a bit of a rush right now because I'm blocking people.

**Comment by DataTables** [comment]
I'm encountering this error at the moment as well (found this issue via Google). It sounds a lot like [this issue](https://github.com/Microsoft/TypeScript/issues/9527) which was fixed in 2.0.2 (although 2.0.0 hasn't been released yet which I've got to admit I'm totally confused about :-) ).

**Comment by DataTables** [comment]
Yup - installed 2.0.2 via npm and it made this error "go away" for me. Assuming that it is the same error (it sure sounds like it) I think this is resolved.

**Comment by tibbus** [comment]
This happened to me as well, there is no details to error just `Error: length < 0   node_modules\typescript\lib\tsc.js:53737  throw e;`  

In my case it was because I left git conflict unresolved with `<<<<<<<<<<` code
Relate to : https://github.com/Microsoft/TypeScript/issues/12952
