### ISSUE TITLE
Compiler forces call super() even if it could be done automatically

### ISSUE THREAD

**Issue by kemsky** [Microsoft/TypeScript#8963]
**TypeScript Version:** 
1.8.10

**Code**

```ts
class Base {
    constructor(name?:string){
         console.log(name);
    }
}

class Child1 extends Base {
      constructor(){
            super(); //wont compile without super call
            console.log('do not need name');
      }
}

class Child2 extends Base {
      //this code is ok...
}
```

**Expected behavior:**
It should be possible to skip `super()` call if there are no required parameters (just like Java does).
**Actual behavior:** 
Will not compile without `super()` call.

**Comment by Arnavion** [comment]
It's according to the ES spec. If an explicit constructor is present, then it must include a `super()` call.

**Comment by kemsky** [comment]
`super()` could be added to generated code automatically by compiler,  es spec would not be violated.

**Comment by kitsonk** [comment]
While access `this` is prohibited before the `super()` call, other actions can take place.  Auto-magic features are dangerous for little value, cause confusion and aren't in the spirit of TypeScript as a superset of ECMAScript.

**Comment by kemsky** [comment]
This issue has nothing about `this` access. Any valid ECMAScript code would still be valid TypeScript code. Seriously, blindly typing `super()` for each inherited class does not add any value to the application code.  I still do not see any reason against generating `super()` call.

**Comment by kitsonk** [comment]
> Seriously, blindly typing `super()` for each inherited class does not add any value to the application code.

What if you want to do something before `super()`?  What if you want to pass arguments to `super()`?  You might then argue that is `super()` is in the body of the constructor then don't emit the `super()` but that becomes auto-magical then, which is surprising.  You are correct, it is blindly emitting, which blindly emitting anything will cause issues.

**Comment by Arnavion** [comment]
It's not unreasonable to ask for an implicit `super()` call at the beginning of derived class constructor if it's not explicitly called anywhere in the body (and, in the case of TS, if a no-arg constructor actually exists on the base class). If the user wants explicit control over its placement they would call it explicitly. If the user wants to call it with arguments they would call it explicitly.

But this decision should come from TC39.

**Comment by kemsky** [comment]
> It's not unreasonable to ask for an implicit super() call at the beginning of derived class constructor if it's not explicitly called anywhere in the body (and, in the case of TS, if a no-arg constructor actually exists on the base class). If the user wants explicit control over its placement they would call it explicitly. If the user wants to call it with arguments they would call it explicitly.

Exactly.

> But this decision should come from TC39.

So it will not happen any time soon.

**Comment by RyanCavanaugh** [comment]
This really comes down to preserving the ES6 class semantics. ES6 could have said there was an implicit `super` call in constructor bodies that did not contain a `super` call, but they didn't. We can agree or disagree with that decision but it's basically immaterial in a language that isn't intentionally diverging from the ES6 behavior.

**Comment by kemsky** [comment]
Obviously, i'm not going to argue. Just want to know, what is the scope for new features in TypeScript? Is it limited to type system?

**Comment by RyanCavanaugh** [comment]
https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals is a good overview of what we generally consider to be in scope.

In general things that aren't related to the type system have to clear a much higher bar. Changing the runtime behavior of TS relative to its "vanilla" JS counterpart is something we will not do, even if the behavior would be broadly preferable. For example, we could easily decide to have more sane behavior runtime around `this`, but haven't because maintaining JS compatibility is an absolute constraint.
