### ISSUE TITLE
() => T | void with strictNullCheck should waive noImplicitReturns

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#8968]
nightly build
```typescript
// --noImplicitReturns --strictNullCheck 

function fn(callback: () => string | void): void {}

fn(() => {
    if (Math.random() > 0.5) {
        return 'hey';
    }
});
```
![image](https://cloud.githubusercontent.com/assets/937933/15800992/ff511564-2a55-11e6-9f53-c20363abaf25.png)

what exactly does it want me to return if i say void is ok?

UPDATE:
interestingly this works no problem
```typescript
function fn(): string | void {
    if (Math.random() > 0.5) {
        return 'hey';
    }
}

```

**Comment by iignatov** [comment]
IMHO having a function that both returns a value in one case and doesn't return anything in another is very *very* bad practice. I would recommend you to always return a value and in the case with invalid input parameter _(or another condition)_ to return `null` or throw an exception. Moreover this seems like a TypeScript limitation and not a Ionic issue, so it would be better to [open an issue](https://github.com/Microsoft/TypeScript/issues/new) in the TypeScript repository _(although it's debatable if this is a real issue or an edge case in result of a language abuse)_.

**Comment by aleksey-bykov** [comment]
got it, cap, thank you for sharing you best practices

**Comment by RyanCavanaugh** [comment]
I'm inclined to say the second snippet is a bug and the first one is working as intended. You said no implicit returns, but implicitly returned on one codepath and explicitly returned on another. Thoughts?

**Comment by aleksey-bykov** [comment]
well, you might be interested to read this answer https://github.com/Microsoft/TypeScript/pull/7140#issuecomment-192908646

**Comment by aleksey-bykov** [comment]
![image](https://cloud.githubusercontent.com/assets/937933/15802722/53e8e8c0-2a8a-11e6-9261-77a6381c6201.png)


![image](https://cloud.githubusercontent.com/assets/937933/15802723/60d57bca-2a8a-11e6-8249-ab4e9f685a0a.png)

![image](https://cloud.githubusercontent.com/assets/937933/15802725/6bfc5a50-2a8a-11e6-8449-4c01a2eae08e.png)

![image](https://cloud.githubusercontent.com/assets/937933/15802726/7a5b6cd0-2a8a-11e6-9270-32b683b698c0.png)

**Comment by Arnavion** [comment]
Is it that the lambda is not getting the `string | void` return type inferred? Explicitly annotating it removes the error.

```typescript
function fn(callback: () => string | void): void {}

fn((): string | void => {
    if (Math.random() > 0.5) {
        return 'hey';
    }
});
```

That's perhaps also why @aleksey-bykov 's second example works?

**Comment by mhegazy** [comment]
this behaves as intended. the explicit type annotation allows you to shut off this check when this is what you really want, but get notified when this is not the intention.

**Comment by aleksey-bykov** [comment]
this is a very subtle feature that looks like a bug, certainly needs to be documented
