### ISSUE TITLE
can "this" type for callbacks be used yet?

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#8969]
nightly build 
the roadmap says it's there and a pull request merged
however although the declaration syntax works, the callsite doesn't seem to be aware of it

```typescript
function testme(callback: (this: { blackjack: string; otherStuff: number }) => void) {
}

testme(() => {
    this. // <-- expected to be of the type specified in the callback declaration, actual any
});
```
![image](https://cloud.githubusercontent.com/assets/937933/15801412/b765b410-2a61-11e6-86f9-a5140f46e667.png)

**Comment by mhegazy** [comment]
lambdas inherit their containers `this` binding. they do not introduce a new `this`; so regardless of how `testme` calls it, it will always use `this` from the global scope in this example.

use function expressions instead:
```ts
testme(function() {
    this.blackjack = 0; // Error: blackjack is not  number
});
```

**Comment by aleksey-bykov** [comment]
ah, silly me
