### ISSUE TITLE
Syntactic Classifications fails for `ntypescript.js` (suspect also `typeScriptService.js`)

### ISSUE THREAD

**Issue by basarat** [Microsoft/TypeScript#8973]
**TypeScript Version:** 

Latest from master

**Main issue report**

If you call `getEncodedSyntacticClassifications`  for this source file: https://github.com/TypeStrong/ntypescript/blob/master/bin/ntypescript.js it crashes at line `1077`

![image](https://cloud.githubusercontent.com/assets/874898/15804453/fe09418a-2b4b-11e6-8059-cb873cc50180.png)

**Background** 

I am in the process of migrating alm tools to monaco : https://github.com/alm-tools/alm/pull/121 Since the sample grammar for `.js` uses the lexical classifier (sample https://github.com/Microsoft/vscode/blob/a89447cca9ef71b5a4c0f974ad61b09cf46fa6f2/src/vs/languages/typescript/common/tokenization.ts) its fairly limited in presence of jsx / ES6 template strings. 

So migrating it to to use `syntacticClassifer` for `.js` files similar to what I did for `.ts` files :rose:

**Comment by mhegazy** [comment]
can you share the input that caused the crash? does it always happen? what is the node.kind when it crashes?

**Comment by basarat** [comment]
> can you share the input that caused the crash

Eventual point of crash: 

![image](https://cloud.githubusercontent.com/assets/874898/15841112/f911e924-2c91-11e6-926e-7110d1990191.png)

The root level call:

![image](https://cloud.githubusercontent.com/assets/874898/15841116/feeb92d2-2c91-11e6-98ba-8a6b9a0af4d3.png)


> does it always happen

Yes.



> what is the node.kind when it crashes?

`node.kind` is `0` (visible in the first screenshot). Here is more info about `node` (shows that something bad has happened ... we are tokenizing stuff inside jsdoc ` ¯\_(ツ)_/¯`)

![image](https://cloud.githubusercontent.com/assets/874898/15841167/6dae3cc4-2c92-11e6-9227-6288ec3ef881.png)


Thanks for looking into this :rose:

**Comment by DanielRosenwasser** [comment]
@basarat do you have a smaller repro? Or a file that this specifically occurs at?

**Comment by basarat** [comment]
> do you have a smaller repro

Unfortunately not. I imagined there would be some tests here for syntactic classifier that we could pipe this file to https://raw.githubusercontent.com/TypeStrong/ntypescript/master/bin/ntypescript.js with arguments `span: {start:63928,length:7}`

**Comment by mhegazy** [comment]
@basarat is this still an issue?

**Comment by basarat** [comment]
> @basarat is this still an issue?

Nope. Seems fixed :rose: The whole typescript.js (and typescriptServices.js) file tokenized with zero errors 👍 

![image](https://cloud.githubusercontent.com/assets/874898/18700474/d0ac249a-801a-11e6-98f0-5a4489fbd857.png)
