### ISSUE TITLE
Request Feature: Paths mapping support in TypeScript (Intellisense, Errors and Warnings, Go to Definition)

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#8977]
_From @davidgabrichidze on June 5, 2016 14:7_

This RF is related to TypeScript's **Path mappings based module resolution [#5039 ](https://github.com/Microsoft/TypeScript/issues/5039)**.  The link describes all details how Path mapping works. Please review it.

So here is copy of Example 1 from Microsoft/TypeScript#5039

```
projectRoot
├── folder1
│   └── file1.ts (imports 'folder2/file2')
├── folder2
│   ├── file2.ts (imports './file3')
│   └── file3.ts
└── tsconfig.json
```

Expected behavior is to support 'folder2/file' imports without Errors & Warnings, list classes of module and support Intellisense - in short: normal behavior, as it would be, if imported using relative paths.

![image](https://cloud.githubusercontent.com/assets/12189125/15805862/23ed829e-2b47-11e6-902e-8816f443064f.png)

```
export class LocalModuleClass
{
  public title: string = "Title from local-module!!!";
}
```

TypeScript itself, compiles and builds everything as expected, application works.

Here is [demo rep](https://github.com/davidgabrichidze/vscode-paths-example). It uses [angular-cli](https://github.com/angular/angular-cli). Instructions to run app:
`npm install angular-cli -g`
`npm install`
`ng build`
`ng serve`

_Copied from original issue: Microsoft/vscode#7226_

**Comment by dbaeumer** [comment]
Moving to TS since VS Code relies on the tsserver provided by the TS team. Quickly looking at it I think this is caused by the fact that the tsconfig states moduleResolution node and to my knowledge node would not resolve 'folder2/file2' either since it has not the concept of a base path. But I leave the final answer up to the TS team.

**Comment by mhegazy** [comment]
This is a TS2.0 feature. i am assuming you have not updated your VSCode to use the prerelease version of TS you are using to build. to do this, you need to set your `"typescript.tsdk"` in your user settings. see https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Nightly%20Builds.md#visual-studio-code

**Comment by davidgabrichidze** [comment]
Can confirm. After installing typescript@1.9.0-dev.20160606-1.0 and configuring VS Code's `"typescript.tsdk"` it worked.

Thanks!

**Comment by dodyg** [comment]
I am trying to use '2.0.0-dev.20160707' on Visual Studio code (Windows) and I use an absolute path for ```typescript.tsdk``` but I cannot make it to work

```
    "typescript.tsdk": "H:/InnoLabs/Everest/everest_app/src/node_modules/typescript/lib"
```

I test whether VS Code using the nightly by using ```noUsedParameters```. It generates

```
error TS5023: Unknown compiler option 'noUnusedParameters'.
```

**Comment by mhegazy** [comment]
@dodyg, i can not get a repro for this. working for me. does tsc work correctly on the commandline?

**Comment by dodyg** [comment]
```
H:\InnoLabs\Everest\everest_app\src\node_modules\typescript\lib
λ node tsc.js --version
Version 2.0.0-dev.20160707
H:\InnoLabs\Everest\everest_app\src\node_modules\typescript\lib
λ
```

I am using Version 1.4.0-insider if that makes any difference (I tried on my stable VSCode, same problem)

My tsconfig.json 
```
{
    "compileOnSave": true,
    "compilerOptions": {
        "target": "es5",
        "sourceMap": false,
        "noImplicitAny": false,
        "allowUnreachableCode": false,
        "allowUnusedLabels": false,
        "preserveConstEnums": true,
        "noImplicitReturns": true,
        "noFallthroughCasesInSwitch": true,
        "allowJs": false,
        "module": "commonjs",
        "moduleResolution": "node",
        "noUnusedParameters": true
    },
     "exclude": [
        "node_modules",
        "typings"
    ]
}
```

**Comment by dodyg** [comment]
I got this message today (with my other computer) with the latest insider when the path is wrong.

```
The path H:\InnoLabs\Everest\everest_app\src\node_modules\typescript\lib doesn't point to a valid tsserver install. TypeScript language features will be disabled
```
I fixed the path and the warning goes away. However the issues with ```noUsedParameters``` remains

**Comment by mhegazy** [comment]
still no luck. here is my setup.

**Comment by dodyg** [comment]
How do you do your "typescript.tsdk" path?

**Comment by mhegazy** [comment]
'typescript@next'

**Comment by dodyg** [comment]
I don't think that will work. I mean do you use absolute path or relative path. I am installing typescript@next locally so I need to refer to it at ```typescript.tsdk```

**Comment by dodyg** [comment]
Well typescript@beta is out now and I just install it on global so the options are now available. ```typescript.tsdk``` is still not working but that's a worry for another day I guess.

**Comment by rfarina** [comment]
@dodyg, I used your snippet here and it worked well for me.
"typescript.tsdk": "./node_modules/typescript/lib"

**Comment by jlanza** [comment]
I use this in my settings.json and it's still getting the system tsc which is an old version. Why is it not getting the locally installed for the project?

**Comment by fruitjs** [comment]
@rfarina Thanks, after restarting vscode it works for me as well.
