### ISSUE TITLE
Need help with latest typescript and npm package type definition resolution visual studio 2015

### ISSUE THREAD

**Issue by squaretabledev** [Microsoft/TypeScript#8978]
Hi

Not sure if this is the right place to ask but I am going through the latest release notes for typescript and found the following [typings-for-npm-packages](http://www.typescriptlang.org/docs/handbook/typings-for-npm-packages.html) and I am trying to get this to work in visual studio 2015.

I have installed version 1.8.6.0 from the installer TS1.8.6-TS-release-1.8-nightly.20160229.1\TypeScript_Dev14Full.exe

I have checked the packages install from NPM and it looks to me like all the configuration is correct. 

My tsconfig.json is set up as per below

```json
"compilerOptions": {
   "target": "es2015",
   "sourceMap": true,
   "jsx": "react",
   "allowSyntheticDefaultImports": true,
   "experimentalDecorators": true,
   "noImplicitAny": false,
   "suppressImplicitAnyIndexErrors": true,
   "moduleResolution": "node"
},
"exclude": [
   "node_modules"
]
```

For some reason visual studio 2015 is not picking up the definitions from the packages in node_modules.

I tried the same code in atom and it picked everything up correctly. Any help would be appreciated.

**Comment by mhegazy** [comment]
I can not reproduce this issue on VS 2015 update 2.

I would try installing VS 2015 Update2, https://www.visualstudio.com/en-us/news/vs2015-update2-vs.aspx and trying again.

**Comment by mhegazy** [comment]
closing for now, please reopen if it still an issue.
