### ISSUE TITLE
Update spec: ambient module declarations

### ISSUE THREAD

**Issue by andy-ms** [microsoft/TypeScript#8980]
See #8945 (issue: #6615)

**Comment by MartinJohns** [comment]
The issue is in milestone 2.0, but the spec update is in milestone 2.1?

**Comment by mhegazy** [comment]
We do not attache milestones to spec issues. sorry about that.

**Comment by RyanCavanaugh** [comment]
The spec is now an "archived" artifact and we won't be tracking defects against it anymore.
