### ISSUE TITLE
Problem with arr.entries()

### ISSUE THREAD

**Issue by Brakkar** [Microsoft/TypeScript#8984]
**TypeScript Version:** 

1.8.10

```
{
  "compilerOptions": {
    "module": "commonjs",
    "moduleResolution": "node",
    "removeComments": true,
    "sourceMap": true,
    "pretty": true,
    //"noImplicitAny": true,
    "target": "es5"
    //"allowJs": true
  },
  "exclude": [
    "node_modules",
    "typings/globals",
    "typings/modules"
  ]

}
```
Using with vscode 111 on mac osx.

This code:

```
  let languagesList: string[] = new directory_models.LanguagesList().languageArray()
      
  let languagesListArray = function() {
            for ( let [ index, value ] of languagesList.entries() ) {
                console.log(index, value)
            }
        }

```

Produces this error:  TS2339: Property 'entries' does not exist on type 'string[]'.

Which is weird because entries() is a valid es6 code:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/entries

**Comment by RyanCavanaugh** [comment]
If you're targeting ES6, set `target` to `es6`, not `es5`

**Comment by Brakkar** [comment]
Please correct me if i'm wrong but i was thinking that typescript would transpile es6 syntax to target es version, even es5.

**Comment by RyanCavanaugh** [comment]
It does transform syntax, but functions on built-in prototypes are not syntax (they're just functions). You can use a polyfill library if you want to target ES5 for syntax but still use ES6 functions.

**Comment by DanielRosenwasser** [comment]
To give some more detail on Ryan's answer, TypeScript compiles ES2015+ syntax down to ES3/5, but does not supply runtime features that are part of the execution environment (such as new methods like `entries` and whatnot). Polyfills like core-js and es6-shim are typically used to fill in this functionality.

One thing I'll note is that in TypeScript 2.0, you'll be able to acknowledge that your runtime has the functionality (or a shim) for additional methods like `entries`, but that you still want to compile down to ES5. You'll be able to use the `--lib` flag for this.

Hope that helps!
