### ISSUE TITLE
Unable to export an interface as a default export in one line

### ISSUE THREAD

**Issue by raybooysen** [Microsoft/TypeScript#8985]
This is valid typescript
```ts
interface Bar {
	name: string;
}

export default Bar;

```

However, the compiler complains if I do this:
```ts
export default interface Bar {
	name: string;
}

```

I would have expected this to work in both cases as if I substitute `interface` with `class` it works fine.

Reading the spec here, https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#11.3.4, shows that interfaces cannot be part of a default export, but why?

Thanks!

**Comment by RyanCavanaugh** [comment]
Duplicate of #3792. Please use the GitHub search feature before logging new issues.

![image](https://cloud.githubusercontent.com/assets/6685088/15829815/413996a2-2bca-11e6-8c5f-de81a8991ab3.png)

**Comment by raybooysen** [comment]
Apologies. I didn't search
