### ISSUE TITLE
Error in compiler option docs. `traceResolution` is listed as valid option but it is not.

### ISSUE THREAD

**Issue by mattmazzola** [Microsoft/TypeScript#8986]
**TypeScript Version:** 

Version 1.8.9

The documentation here:
http://www.typescriptlang.org/docs/handbook/compiler-options.html
Lists `--traceResolution` as a compiler option to which I intended to use to help diagnose errors; however, it appears this was removed or changed names.

**Code**

```
 tsc -p . --traceResolution
```

**Expected behavior:**
I expected this to tell me why my module cannot be found even though it is in the node_modules folder and has package.json with main and typings paths setup correctly.

**Actual behavior:** 
`error TS5023: Unknown compiler option 'traceresolution'.`

**Comment by mattmazzola** [comment]
Maybe this docs page can be auto generated from the `tsc -h` ?

**Comment by mhegazy** [comment]
looks like a doc bug. it is a new flag added in TS 2.0. so it is valid if you are using `typescript@next` and should list the set of steps the compiler took to resolve a module.

**Comment by mhegazy** [comment]
removed in https://github.com/Microsoft/TypeScript-Handbook/commit/86fa56d4f9fddb1be86e9d822d78f12c89eabe83

**Comment by sethlivingston** [comment]
It's still there:

https://www.typescriptlang.org/docs/handbook/compiler-options.html

**Comment by bennyn** [comment]
I also got tricked by the availability of `--traceResolution`. It's not present in TypeScript Version 1.8.10.

**Comment by ajxs** [comment]
It's still very much there as of June 2018...
https://www.typescriptlang.org/docs/handbook/compiler-options.html

**Comment by mbovel** [comment]
This option is also mentioned on this page: https://www.typescriptlang.org/docs/handbook/module-resolution.html#tracing-module-resolution.

**Comment by TheOpenDevProject** [comment]
Why was this closed, its 2020 and still not resolved..
