### ISSUE TITLE
d.ts file not included in if tsconfig.json present without files specified, and d.ts file is in a sub-directory and has another non-d.ts named file present

### ISSUE THREAD

**Issue by adamcarr** [Microsoft/TypeScript#8987]
This has been found in 1.8.10. Not tested in other versions. 

Issue can be found in the following shared repository.

[tsconfig-test](https://github.com/adamcarr/tsconfig-test)

- If you rename models.ts to something else, models.IPerson in test.ts will resolve. 
- If you keep models.ts the same but uncomment the lines in models.interfaces.d.ts, models.IPerson in test.ts will resolve. 
- If you specify the files to compile explicitly to the tsc compiler, it will compile. 
- If you move models.d.ts and models.ts to the root folder as a sibling of tsconfig.json, models.IPerson in test.ts will resolve.

This seems to be a problem with how tsc handles the automatic search for files when a tsconfig.json is present and doesn't explicitly define the files to include.

**Comment by mhegazy** [comment]
The compiler avoids including files that it thinks are outputs for ones it found earlier. it sees model.ts, and then model.d.ts and thinks this is probably the output of model.ts, so it ignores it.
in general having a ts and .d.ts with the same name in the same location is not a recommended practice, as it messes up module resolution as well. but for this case, the recommendation is to use "files" property and list all the files you want to import, or use `/// <reference path=...>` directive to include model.d.ts.
