### ISSUE TITLE
Update diagnostic messages to ES2015 instead of ES6

### ISSUE THREAD

**Issue by AppShipIt** [Microsoft/TypeScript#8996]
Also the messages for `generator` and `async` have slightly different wording:

> **1220:** Generators are only available when targeting ECMAScript 6 _or_ higher.
> **1311:** Async functions are only available when targeting ECMAScript 6 _and_ higher.

I only noticed trying to search the phrase <q>EcmaScript 6 or higher</q>.

**Comment by mhegazy** [comment]
sigh... ES6 is much easier to read than ES 2015.

PRs are welcomed. changes should be mainly in https://github.com/Microsoft/TypeScript/blob/master/src/compiler/diagnosticMessages.json and places in the code the report the errors.

**Comment by AppShipIt** [comment]
> sigh... ES6 is much easier to read than ES 2015.

I agree but I noticed the configs were updated already. I'll PR momentarily.
