### ISSUE TITLE
need an complier api, to add a new ModuleKind export

### ISSUE THREAD

**Issue by gastrodia** [Microsoft/TypeScript#8999]
maybe just export moduleEmitDelegates( in src\compiler\emitter.ts) , so I can rewrite it ,to export some modules  such as [Unreal.js](https://github.com/ncsoft/Unreal.js) (it's module loader is not same to es6 amd system umd commonjs)

**Comment by DanielRosenwasser** [comment]
#5595 will help support this, but we won't necessarily have an extension point when we initially publish it.

**Comment by basarat** [comment]
> it's module loader is not same to es6 amd system umd commonjs

You are probably right and I have no experience from it but their readme says `(Full) access to existing javascript libraries via npm, bower,` so I think `commonjs` might just work :rose:

![image](https://cloud.githubusercontent.com/assets/874898/15846145/b931d3b0-2cbd-11e6-828a-9dd1077d2de5.png)

**Comment by DanielRosenwasser** [comment]
@gastrodia does @basarat's post more or less solve your issue? I think several other issues might better cover the suggestion here.

**Comment by gastrodia** [comment]
yep I have solve it by commonjs ,thanks a lot @basarat  and I also expect an complier api to custom ModuleKind export in typescript 2.1
