### ISSUE TITLE
super.method "this" return type

### ISSUE THREAD

**Issue by nicolo-ribaudo** [Microsoft/TypeScript#9005]
*Tested in VSCode 1.2 and in the playground*

```ts
class A {
	method(): this {
		return this;
	}
}

class B extends A {}

const c = new B().method();
```

`c`'s type is `B` (correctly). However, if I call super.method() from B, its return type is A instead of B:

```ts
class A {
	method(): this {
		return this;
	}
}

class B extends A {
	method(): this {
		return super.method(); // Type 'A' is not assignable to type 'this'.
	}
}
```

**Comment by jeffreymorlan** [comment]
https://github.com/Microsoft/TypeScript/issues/7728 - already fixed in master branch

**Comment by DanielRosenwasser** [comment]
Thanks for filing @nicolo-ribaudo. Feel free to use our nightly builds if you need with `npm install -g typescript@next`.

**Comment by DanielRosenwasser** [comment]
Also thanks for digging that up @jeffreymorlan!
