### ISSUE TITLE
Named parameters and properties

### ISSUE THREAD

**Issue by yjaaidi** [Microsoft/TypeScript#9007]
Hi!

I'm using TypeScript with named parameters massively like this.
```
class User {
  public firstName: string;
  public lastName: string;
  constructor({firstName, lastName}: {firstName: string, lastName: string}) {
    this.firstName = firstName;
    this.lastName = lastName;
  }
}

new User({firstName: 'Foo', lastName: 'BAR'});
```

And I would love to be able to generate the properties automatically like this.

```
class User {
  constructor({public firstName, public lastName}: {firstName: string, lastName: string}) {}
}

new User({firstName: 'Foo', lastName: 'BAR'});
```

I think that this feature can be really interesting and would encourage more developers to use named parameters which I think is one of the most important best practices in TypeScript and any other language by the way.

Thank you in advance.

**Comment by RyanCavanaugh** [comment]
Duplicate of #5326 ?

**Comment by yjaaidi** [comment]
Oups! In fact, couldn't find it, so sorry!
