### ISSUE TITLE
Comment classification initially only colorizes identifiers, causes flashing

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#902]
Consider the following code

```TypeScript
function checkObjectLiteral(node: ObjectLiteral, contextualMapper?: TypeMapper): Type {
    // ...snip ...
}
```

If you open up a multiline comment on the line above, only `checkObjectLiteral`, `node`, and `contextualMapper` are colorized.

**Comment by paulvanbrenk** [comment]
This is fixed in the Visual Studio component
