### ISSUE TITLE
JS quick outline - support to navigate to more symbols

### ISSUE THREAD

**Issue by egamma** [Microsoft/TypeScript#9021]
From https://twitter.com/alvinsight/status/705152030147485696

![image](https://cloud.githubusercontent.com/assets/172399/15892896/c78792f0-2d7c-11e6-8d89-c9c78ccfe4a9.png)

![image](https://cloud.githubusercontent.com/assets/172399/15892905/d5c3078c-2d7c-11e6-8777-ad387ecbe101.png)

**Comment by mhegazy** [comment]
duplicate of https://github.com/Microsoft/TypeScript/issues/6145?
