### ISSUE TITLE
What is wrong with root var name=123?

### ISSUE THREAD

**Issue by cevek** [Microsoft/TypeScript#9022]
```ts
var name = 123;
//Subsequent variable declarations must have the same type.  Variable 'name' must be of type 'string', but here has type 'number'
```

**Comment by RyanCavanaugh** [comment]
Because `window.name` is going to coerce this to a string. Try it: 
![image](https://cloud.githubusercontent.com/assets/6685088/15902236/caebbe38-2d5b-11e6-809f-8fd429f45e8d.png)
