### ISSUE TITLE
Unreachable code for const variables

### ISSUE THREAD

**Issue by Thomas-P** [Microsoft/TypeScript#9024]
**TypeScript Version:** 

1.8.10

**Code**

```ts
const a=false;
if  (a) {
    console.log('should be unreachable');
}
```
[TypeScript Play](http://www.typescriptlang.org/play/#src=const%20a%3Dfalse%3B%0D%0Aif%20%20(a)%20%7B%0D%0A%09console.log('should%20be%20unreachable')%3B%0D%0A%7D%0D%0A)
**Expected behavior:**
The code should be unreachable in fact that a is immutable. A warning should be placed
**Actual behavior:** 
No unreachable warning.

# Proposal

I know that it could be a little bit difficult to check if we check a property of an object. But for primititves it should work. the compiler already knows if it is a constant and did not allow them to assign twice.

**Comment by mhegazy** [comment]
This is the same request as in https://github.com/Microsoft/TypeScript/issues/8438. narrowing does not do constant propagation nor constant expression evaluation. it is not clear there is much value to be gained by doing these aggressive operations compared to the complexity of the solution on the compiler side.

**Comment by RyanCavanaugh** [comment]
This seems more burdensome than useful. Presumably that variable exists for a *reason*; if you always knew it was false you wouldn't have written the code in the first place. I find myself in this state fairly often:

```ts
// debugging, revert later
// const a = getValueFromServer();
const a = false;
if (a) {
  console.log('should be unreachable');
} else {
  // code I need to check
}
```
