### ISSUE TITLE
List of syntactic definition file errors we could detect

### ISSUE THREAD

**Issue by RyanCavanaugh** [Microsoft/TypeScript#9027]
# Signatures that differ only by a single parameter type

``` ts
declare function fn2(x: number): void;
// Error, write one signature taking string|number
declare function fn2(x: string): void;
```
# Signatures that differ only by omitting by a parameter

``` ts
declare function fn6(): void;
// Error, write one signature with one optional parameter
declare function fn6(s: string): void;
```
# Use of the non-primitive names anywhere

(except in a `interface Number {` declaration)

``` ts
declare var var1: Number; // Error, use 'number'
```
# Optional parameters in callback positions:

``` ts
declare function fn5(callback: (key: string, value?: number) => void): void;
```

**Comment by isiahmeadows** [comment]
Just an opinion, but this sounds more like a linter error than a syntax error. Not saying it's a bad idea to warn, but I would disagree about it being something that should be completely rejected.

**Comment by mhegazy** [comment]
@isiahmeadows the intention here is to implement these as tslint rules and suggest them for definition authors, and may be run them on definitelytyped CI.

**Comment by isiahmeadows** [comment]
@mhegazy Oh. Okay. I get what you mean.

**Comment by RyanCavanaugh** [comment]
Non-consecutive function overloads in the same block:
```ts
interface Foo {
  x(): void;
  y(): void;
  x(s: string): number; // <-- error, all 'x' signatures should be adjacent
}
```

**Comment by mhegazy** [comment]
@rakatyal can we mark this as completed?

**Comment by rakatyal** [comment]
@mhegazy: There are a couple of Open PRs on the tslint repo regarding this. One of them has been merged. Also we decided to wait to implement the primitive names till [this](https://github.com/Microsoft/TypeScript/issues/9879) gets in. 
So let's keep it open for now.

**Comment by mhegazy** [comment]
These should all be addressed now in https://github.com/Microsoft/dtslint
