### ISSUE TITLE
use "export" inside functions

### ISSUE THREAD

**Issue by twelve-monkeys** [Microsoft/TypeScript#9028]
Echo the module exporting semantics into functions as a means of defining complex return values.
Why? The same reasons that modules use them. 

eg:
```ts
function getSomething() {
   export const size = 10;
   ...
   export let name = "";
   name = ...;
}
```
could have a signature of `getSomething() : {size:number,name:string}`
and might emit:
```ts
function getSomething() {
   var size = 10;
   ...
   var name = "";
   name = ...;
   return {size, name}
}
```
The exported variables would have to be at the root scope of the function.
"export default" makes sense as well as the normal return value.
The function can still specify a return type explicitly as well, which can be validated.
Only empty return statements would be permitted if there are export modifiers in the function.
No return Statements would be permitted before the last export modifier to avoid ambiguity.

**Comment by vladima** [comment]
how it is different from just writing:
```ts
function getSomething() {
    const size = 10;
    let name = "";
    ///...
    name = ...
    return { size, name }
}
```
?

**Comment by twelve-monkeys** [comment]
The same difference as export keyword provides for modules - it removes the need to maintain the:
module.eports = {exportedMethodOne, exportedVariable2};
which corresponds to the return of a method.

It deduplicates and makes return statements automatically consistent with each other.

It is one less line of code.

I'm playing devil's advocate. It's more of a "why not..." idea.

**Comment by mhegazy** [comment]
One of the main reasons for using exports in modules is making modules statically analyzable. this is not the same case in functions.

I am not sure there is much value added by introducing a new syntax compared to the cognitive loaded added on language users.

Moreover, this is an area of possible conflict with future JS syntax. We have maintained TypeScript as a super set of JavaScript, and such syntactic proposals should go to https://github.com/tc39/ecma262#ecmascript
