### ISSUE TITLE
Array.from should also permit `IterableIterator` in addition to `ArrayLike`

### ISSUE THREAD

**Issue by NoelAbrahams** [Microsoft/TypeScript#9030]
The [Array Constructor declaration in lib.d.ts](https://github.com/Microsoft/TypeScript/blob/master/lib/lib.es6.d.ts#L4158) should also have the following overload:

```ts
        /**
         * Creates an array from an iterable object.
         * @param iterable An iterable object to convert to an array.
         */
        from<T>(iterable: IterableIterator<T>): Array<T>;
```

[See MDN:](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/from)

> The Array.from() method creates a new Array instance from an array-like or ***iterable object***.

**Comment by jeffreymorlan** [comment]
It's already there: https://github.com/Microsoft/TypeScript/blob/master/lib/lib.es6.d.ts#L4729

**Comment by mhegazy** [comment]
as noted by @jeffreymorlan, this is already defined in es6 lib. if you are using `typescript@next` you can get the definition through `--lib es2015` or `--lib es2015.iterable`.

**Comment by tzachshabtay** [comment]
Hi, I'm using es6 and I don't see this overload in the type definition?
The link @jeffreymorlan provided seems to point to a wrong line now (no permalink?), but that overload is not in the file.

I tried to use it in my code but I'm getting the error:

`error TS2345: Argument of type '() => IterableIterator<MyType>' is not assignable to parameter of type 'ArrayLike<{}>'.
  Index signature is missing in type '() => IterableIterator<MyType>'.`

My code:

```

public MyMap: Map<string, MyType>;
...
Array.from(this.MyMap.values);

```

@mhegazy any ideas?
Thanks.

**Comment by mhegazy** [comment]
did you mean `Array.from(this.MyMap.values());` ?

**Comment by tzachshabtay** [comment]
Ah, silly me, thanks.
