### ISSUE TITLE
Latest NTypeScript build broken

### ISSUE THREAD

**Issue by basarat** [Microsoft/TypeScript#9039]
Similar to some previous error reports where a new endpoint is exported but its types aren't 

```
../src/services/signatureHelp.ts(175,15): error TS4033: Property 'kind' of exported interface has or is using private name 'ArgumentListKind'.
```

Build : https://travis-ci.org/TypeStrong/ntypescript/builds/136283530#L326 :rose:

**Comment by mhegazy** [comment]
well it is internal for a reason :)

**Comment by basarat** [comment]
Thanks for the PR :heart:

**Comment by mhegazy** [comment]
give it another try now.

**Comment by basarat** [comment]
Passed https://travis-ci.org/TypeStrong/ntypescript Thanks!:rose:
