### ISSUE TITLE
Add options to choose JSX file extension .js or .jsx

### ISSUE THREAD

**Issue by frogcjn** [Microsoft/TypeScript#9044]
I want to keep jsx in the file content, so I choose:

```
        "jsx": "preserve"
```

but the generated file has `jsx` extension and ReactNative refuse to recognize this extension.

So there needs an option to let JSX format file using `js` extension.

**Comment by mindnova** [comment]
Yeah I met the same problem. 
I would like to see the compiled file with jsx expression because that's clear but I do not want the .jsx extension. React Native just does not recognize them.

**Comment by RyanCavanaugh** [comment]
I'd propose an option `preserveJs` that retains JSX expressions but computes the filename as `.js`. This should be a fairly easy change if someone wants to send a PR for it

**Comment by jbaxleyiii** [comment]
@RyanCavanaugh I'd love to take this! Can you give me any other direction?

**Comment by jbaxleyiii** [comment]
Actually it looks like https://github.com/Microsoft/TypeScript/pull/9864/files targets this?

**Comment by basarat** [comment]
I'm a big fan of keeping `jsx` out of `.js` files :) but [thats just my opinion](https://medium.com/@basarat/typescript-vs-flowlang-caee1386b4fc#.vxygajv6k) and I haven't done react native :rose:

**Comment by ivogabe** [comment]
I think this can be closed, implemented in #13636.
