### ISSUE TITLE
Better parsing experience for TSX

### ISSUE THREAD

**Issue by tinganho** [microsoft/TypeScript#9045]
I have noticed when I type an incomplete JSX element. It sometimes breaks the whole file. Red squiggles are showing up everywhere:

``` tsx
class View extends Component<{}> {
    view() {
       return <div/>
    }
}
class Something extends Component<{}> {
    view() {
         return <div> 
            <V> // Breaks whole file
        </div>
    }
}
```

It would be great if the red squiggles is only localized to where the syntax is incomplete. It doesn't break downwards but also upwards.

If you take a coffee when you are in the middle of typing something, you end up not finding where you left off sometimes.

**Comment by chicoxyzzy** [comment]
I want to fix this. Can you give me some hints?

**Comment by RyanCavanaugh** [comment]
This is supposed to work, so it's just a matter of figuring out what's going wrong. In parser.ts around line 3667 there's this code:
```ts
                else if (token === SyntaxKind.EndOfFileToken) {
                    // If we hit EOF, issue the error at the tag that lacks the closing element
                    // rather than at the end of the file (which is useless)
                    parseErrorAtPosition(openingTagName.pos, openingTagName.end - openingTagName.pos, Diagnostics.JSX_element_0_has_no_corresponding_closing_tag, getTextOfNodeFromSourceText(sourceText, openingTagName));
                    break;
                }
```
which is supposed to give a localized error message. Stepping through the surrounding code in `parseJsxChildren` and seeing why this isn't happening should give you the information needed to make a fix

**Comment by chicoxyzzy** [comment]
@RyanCavanaugh thank you.
Now I need to figure out how to debug TypeScrip sources.

**Comment by RyanCavanaugh** [comment]
`jake runtests-browser tests=theNameOfYourTest` and debugging in-browser usually works pretty well.

**Comment by chicoxyzzy** [comment]
Is `theNameOfYourTest` here is the path to my file?

my `index.tsx`
```
import React, { Component } from 'react';

class Something extends Component<{}> {
  render() {
    return <div>
      <V> // Breaks whole file
    </div>
  }
}
```

how I run `jake`:
```
node_modules/.bin/jake runtests-browser browser=chrome tests=mytest/index.tsx
```

I have all necessary `node_modules` in my `mytest` directory.

I can't find `index.tsx` in sources tab of Chrome DevTools :(

**Comment by RyanCavanaugh** [comment]
Look at e.g. `tests/cases/conformance/jsx/jsxParsingError2.tsx` to see how to write a compiler test. Using that as an example, you would run `jake runtests-browser browser=chrome tests=jsxParsingError2`

**Comment by jakebailey** [comment]
This has been working for a while; there's special code intended to recover from unclosed tags (and it is tested in our suite): [Playground Link](https://www.typescriptlang.org/play?ts=5.1.3#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgIilQ3wG4BYAKCoBMk0AbFIuRlAZ3bgDU4kAPGEgB2NLsnQwAdAGFckYSPgBvAL4VqlOmxbCUIJOzDokcAFIBlABpxlVOA7jBhQqJhNwAki6jP2wNABRBiQDFy5lOBpgADcALltVOFUqFM02Th5gJAB3PkERMURiaTlwCEUXAB41AD5be0cY7JyACgBKBspHHqIYAFcoYTgq6JiAelrGhzS0jK4LXCQYAAtnAHN8oVFxEtl5CqUa1Xq7bqaWjq6em77B4dHY+umbnqruevHxuAAhIhQANZcHIrCAhOCYYAhF5vcZjKbnGapKhUTD9YQYYAVOAAIyYKyuZx6qSAA)
