### ISSUE TITLE
ES6 getter property does not exist when using union types

### ISSUE THREAD

**Issue by bradleyayers** [Microsoft/TypeScript#9050]
**TypeScript Version:** 

nightly (1.9.0-dev.20160217)

**Code**

```ts
class Example {
  get foo() {
    return true;
  }

  baz(example: Example) {
    example.foo;
  }

  bar(example: Example | Object) {
    example.foo; // error TS2339: Property 'foo' does not exist on type 'Example | Object'.
  }
}
```

**Expected behavior:**

`example.foo` would not throw an error in either method.

**Actual behavior:** 

`example.foo` when `example` is `Example | Object` throws:

    error TS2339: Property 'foo' does not exist on type 'Example | Object'.

**Comment by kitsonk** [comment]
That is the normal behaviour of TypeScript as it is guarding you against something that might not have a `.foo`.

If you want this to work, you need to [narrow the type down to something that contains `.foo`](http://www.typescriptlang.org/play/#src=class%20Example%20%7B%0D%0A%20%20get%20foo()%20%7B%0D%0A%20%20%20%20return%20true%3B%0D%0A%20%20%7D%0D%0A%0D%0A%20%20baz(example%3A%20Example)%20%7B%0D%0A%20%20%20%20example.foo%3B%0D%0A%20%20%7D%0D%0A%0D%0A%20%20bar(example%3A%20Example%20%7C%20Object)%20%7B%0D%0A%09if%20(example%20instanceof%20Example)%20%7B%0D%0A%09%20%20example.foo%3B%0D%0A%09%7D%0D%0A%20%20%7D%0D%0A%7D%0D%0A):

```typescript
class Example {
  get foo() {
    return true;
  }

  baz(example: Example) {
    example.foo;
  }

  bar(example: Example | Object) {
	if (example instanceof Example) {
	  example.foo;
	}
  }
}
```
