### ISSUE TITLE
erratic output structure if one of the folder is empty

### ISSUE THREAD

**Issue by thakurarun** [Microsoft/TypeScript#9051]
**TypeScript Version:** 

1.8.10 

**Code**

```ts
// A self-contained demonstration of the problem follows...

Tool: VS Code
I have two folders under src folder like

-src
 --ClientTypings **//empty folder**
 --ServerTypings
  ---Repositories
   ----classs1.ts
   ----classs2.ts
  ---Routes
   ----route1.ts
   ----route2.ts

tsconfig.json
{
  "compilerOptions": {
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "module": "commonjs",
    "noEmitOnError": true,
    "noImplicitAny": false,
    "outDir": "app/src",
    "removeComments": false,
    "sourceMap": true,
    "target": "es6",
    "watch": true,
    "allowJs": false
  },
  "exclude": [
    "node_modules"
  ]
}
```

**Expected behavior:**

output directory should be

-app
 --src
 ---ServerTypings
  ----Repositories
    -----classs1.js
    -----classs2.js
   ----Routes
    -----route1.js
    -----route2.js

ClientTypings can be skipped as it is empty folder

**Actual behavior:** 

in output directory **"ServerTypings"** is not considered, which make erratic levels of code files.

-app
 --src
  ---Repositories
    ----classs1.js
    ----classs2.js
   ---Routes
    ----route1.js
    ----route2.js

**Comment by mhegazy** [comment]
use `--rootDir` to fix the root of your project. see https://github.com/Microsoft/TypeScript/wiki/FAQ#why-does---outdir-moves-output-after-adding-a-new-file for more information.
