### ISSUE TITLE
Code completion for optional properties in sub classes

### ISSUE THREAD

**Issue by Lenne231** [Microsoft/TypeScript#9058]
Is there a way to have code completion for optional properties in sub classes? This would be really helpful when using ReactJS.

![image](https://cloud.githubusercontent.com/assets/2046557/15942446/b3a4533c-2e84-11e6-86ef-7e1a88c26c0a.png)

**Comment by mhegazy** [comment]
Duplicate of https://github.com/Microsoft/TypeScript/issues/7158
