### ISSUE TITLE
Type 'this'???

### ISSUE THREAD

**Issue by electricessence** [Microsoft/TypeScript#9063]
Is there any magic (without insane generics) to define a type that matches 'this'?

For example...
```typescript
class A {
  me():A {
     return this;
  }
}

class B extends A {
  otherThing():void{}
  me():B {
    return this;
  }
}
```

Instead of overriding ```me()``` can I define a type without adding another generic declaration that simply solves the type of ```me()```?

**Comment by mhegazy** [comment]
`this`?

```ts
class A {
  me(): this {
     return this;
  }
}

```

**Comment by electricessence** [comment]
So I tried that and it started to unravel when I got into sub classes...
I want 'this' as a type to reflect the current type... Is that what ```: this``` is doing?

**Comment by mhegazy** [comment]
What do you mean by "current type"; and what happened with subclasses when you used this?

**Comment by basarat** [comment]
> I want 'this' as a type to reflect the current type... Is that what : this is doing?

Yes. 

```ts
class A {
  me():this {
     return this;
  }
}

class B extends A {
  otherThing():void{}
  me():this {
    return this;
  }
}

let a = new A, b= new B();
let foo = a.me(); // foo:A
let bar = b.me(); // bar:B
```
You can hover over  `foo` / `bar` in your IDE to see the inferred type :rose:

**Comment by basarat** [comment]
Also, you don't need to override it i.e. the base case `me` function is enough :rose: 

```ts
class A {
  me():this {
     return this;
  }
}

class B extends A {
  otherThing():void{}  
}

let a = new A, b= new B();
let foo = a.me(); // foo:A
let bar = b.me(); // bar:B
```

**Comment by mhegazy** [comment]
also, `this` types are infered automatically for you:

```ts
class A {
  me() {
     return this; // infers type this
  }
}
```

**Comment by DanielRosenwasser** [comment]
https://www.typescriptlang.org/docs/handbook/advanced-types.html#polymorphic-this-types

**Comment by electricessence** [comment]
Hey thanks guys!  I'm gonna check this out.  It may make a huge difference in some of my class structures.  I did try and do this out of instinct, but it didn't work right on my first try.  I'll get back to you. ;)

**Comment by electricessence** [comment]
Ok so here's where it get's sticky...
```typescript
class A<T> {
  me():this {
     return this;
  }
}

class B<T> extends A<T> {
  otherThing():void{}  
}

class C<T> extends B<T> {
  map<TResult>(t:(v:T)=>TResult):this<TResult> {}
}
```
Anything that will make this work? :/

**Comment by basarat** [comment]
Minor simplification of your code (that still errors): 

```ts
class A<T> {
	map<TResult>(mapper: (v: T) => TResult): this<TResult>{

	}
}
```

However `this` really is *whatever calls the function*  **generics and all**, so I don't see a way to declare what you want :rose:

**Comment by electricessence** [comment]
Yes, you get it.
Ok so it means that I have to override the function.

So lastly is there any consequences to doing something like:
```
class A<T> {
    clone():this {
       return new A<T>();
    }
}
```

**Comment by basarat** [comment]
> So lastly is there any consequences to doing something like:

If a child class `B` fails to override it then the compiler will think `new B().clone()` to be `B` but it will really be `A` :rose:

**Comment by electricessence** [comment]
Ok so assuming that it the type returned always matches correctly, then ok right?
Because right now, for the above sample I have to force the return like this (to get it to work):
```typescript
class A<T> {
    clone():this {
       return <any> new A<T>();
    }
}
```

**Comment by electricessence** [comment]
So I got everything to compile.
