### ISSUE TITLE
Compile on save stopped working after VS2015 Update 3 installation

### ISSUE THREAD

**Issue by rmtew** [Microsoft/TypeScript#9064]
**TypeScript Version:** 

1.8.6 (1.8.32 in Help / About).

typescript has been working wonderfully for me since I started using it, and compile on save has been working fine.  However, I updated VS2015 to the update 3 release the other day, and now returning to  my solution, nothing happens when I save a tsx file.

Building the solution will result in compiling the tsx files, but it is very slow as a solution.

My tsconfig.json had, and still has, the compileOnSave option set to true.

**Comment by mhegazy** [comment]
Looks like the same issue as https://github.com/Microsoft/TypeScript/issues/8835. we have a fix ready, and should be shipped out in the final Update 3 drop.
