### ISSUE TITLE
Code format stopped working

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#9072]
_From @Sampo123 on May 24, 2016 13:32_

- VSCode Version: 1.0.0
- OS Version: Debian Jessie

Steps to Reproduce:

Really hard to say once again. Everything was fine for a week or so but then the code format just does nothing. Which is a bitch. Also seems to start with random indentation time to times when for example { is added and enter pressed. 

Only error I got from the developer console is this:

/usr/share/code/resources/app/node_modules/vscode-textmate/release/main.js:1232
Grammar is in an endless loop - case 1

I know that these reports without real "how to reproduce" are sometimes a bit useless but just reporting so that somebody could help or take a note.

_Copied from original issue: Microsoft/vscode#6801_

**Comment by dbaeumer** [comment]
_From @aeschli on May 24, 2016 14:29_

With what languages are you see this?
When format stops working, are other features still doing fine? E.g. Code completion, hovers....

**Comment by dbaeumer** [comment]
_From @Sampo123 on May 24, 2016 17:23_

I'm using it with JavaScript. Intellisense and everything else are pretty much fine and even error checking works at normal level. Just the format stopped working. Only other noteworthy thing  is that VS Code seems to be bit off with indentation also at some points. Like when adding a curly bracket at the end of the line and then the cursor is between the curly brackets and I press enter it indents the bracket even though it kind of should not. But this does not seem to happen always. 

Is the error message any related? Could there be some debug flag or something that I could enable and see some explanation why nothing is happening when I try to format the code?

**Comment by dbaeumer** [comment]
_From @aeschli on May 25, 2016 7:10_

The error message is likely not related, but also very interesting. To find out more about it we would need the content of the file at that time.

**Comment by dbaeumer** [comment]
@Sampo123 can you reproduce the formatting problem locally. If so can you please do the following.
- enable TS/JS logging via the setting:
```json
{
	"typescript.tsserver.trace": "messages"
}
```
- open the JS showing the behavior
- Bring Output view to front
- switch to channel typescript
- format the file
- attach the output to this issue.

**Comment by dbaeumer** [comment]
_From @Sampo123 on May 25, 2016 7:54_

Hey, 

Thanks for your replies. I'll do that and get back to you this evening. I'm on other projects today so I'll need to do this when I get off so I'll try to get back to you later today, like in 7 hours or so :)

**Comment by dbaeumer** [comment]
_From @OldrichDlouhy on May 25, 2016 10:33_

I am getting the same issue with editing typescript ts and tsx files. Restarting the VS Code helps in some cases.

This is the text from the Output view:

Sending request: quickinfo (5255). Response expected: yes. Current queue length: 0
Response received: quickinfo (5255). Request took 26 ms. Success: false . Message: No content available.
Sending request: definition (5256). Response expected: yes. Current queue length: 0
Response received: definition (5256). Request took 27 ms. Success: false . Message: No content available.
Sending request: format (5257). Response expected: yes. Current queue length: 0
Response received: format (5257). Request took 4 ms. Success: false . Message: Error processing request. Debug Failure. False expression:

**Comment by dbaeumer** [comment]
Actually I looks like the tsserver 'lost' the content of the file.

**Comment by dbaeumer** [comment]
_From @Sampo123 on May 27, 2016 7:5_

Same kind of behavior here as OldrichDlouhy said. It seems to have gone away for now. I'll get back when it comes back as it seems to be recurring problem.

**Comment by dbaeumer** [comment]
@Sampo123 when you see the bahaviour could you please provide a trace as well to ensure it is the same root cause.

**Comment by dbaeumer** [comment]
_From @leegee on June 9, 2016 10:12_

`Format Code` often stops working here, on JavaScript.

Version info attached (would be nice if that dialog had text that could be clipboarded).

Doesn't work at all on the Insiders build (at least yesterday): says the extension is out of date, so I no longer use Insiders.

![image](https://cloud.githubusercontent.com/assets/512816/15926263/f6ace506-2e32-11e6-8a66-5cd3a522f735.png)

**Comment by dbaeumer** [comment]
According to the trace this is a problem in the tsserver. Moving to the TS team.

@Sampo123 could you still provide the trace so that we can ensure your behaviour is caused by the same root cause

**Comment by leegee** [comment]
Please ping me if you need more details/testing [UTC+0200).

**Comment by zhengbli** [comment]
@leegee do you have a repro procedure / sample code that can help me find the source of the issue quickly? As this issue seems to be happening occasionally.

**Comment by leegee** [comment]
Sorry, not really, or I would have posted it.
I've just had another look using both Insiders and ...outsiders... and both work and don't work.
They both work when I open a directory with less content, and both fail on a directory with lots more content.
Whether or not that is the only difference, or even related, I do not know.
Both directories use a `jsconfig.json` like this:
```
{
	// See http://go.microsoft.com/fwlink/?LinkId=759670
	// for the documentation about the jsconfig.json format
	"compilerOptions": {
		"target": "es6"
	},
	"exclude": [
		"node_modules",
		"tmp",
		"temp",
        "src/bower_components",
        "gulp-tasks",
        "reports",
        ".git",
        "system-menu"
	]
}
```
The directory with less files, where code-formatting works, in is a sub-directory of the other directory, where code-formatting fails. Removing the sub-dirs config makes no difference to formatting.
Please let me know if there is something you'd like me to try.

**Comment by leegee** [comment]
When code formatting stops, IntelliSense also stops.

**Comment by zhengbli** [comment]
@leegee @Sampo123 Can you try using the nightly version of typescript with VSCode? Because recently we start to print the stack if the server crashes. And keep "typescript.tsserver.trace" as "messages" or "verbose", then if the issue occurs, paste the output panel content (would really help if it contains the stack trace info). 

Also, did you see that happen when adding / removing files to the project folder? Or git switch branches that adds / removes files?

**Comment by titonobre** [comment]
I had the same problem but it disapeared after I exclude `node_modules` dir in `.vscode/settings.json` and `jsconfig.json`.

**Comment by zhengbli** [comment]
@titonobre That case is be design, because otherwise too many .js files would be included in the project implicitly. A recent change added a default upper limit of 20 MB for the non-ts file size in a project for that case. In VSCode you should see a light bulb tip in the bottom left that hinting on excluding the `node_modules` folder.

**Comment by leegee** [comment]
I've always limited my code the correct way, I think.

I've not seen this bug for the past few days, but I'm a bit tied up in some
refactoring atm, but after than I will test a little more and report back.

**Comment by leegee** [comment]
I am no longer having any issues with js formatting. Thank you!

**Comment by mhegazy** [comment]
This looks fixed in latest. @Sampo123 please reopen if this issue still occurs.

**Comment by leegee** [comment]
I thought it was working, but should it not format the below?
```
$scope.enterPressed = function() {
if((!$scope.inputText) || ($scope.inputText.length === 0)) return;
var found = false;
for(var i = 0, length = $scope.mainMenuItems.length; i < length; ++i) {
var item = $scope.mainMenuItems[i];
if($scope.inputText.toLowerCase() === item.text.toLowerCase()) {
monitor.openMonitorById(item.value);
found = true;
break;
}
}
if(!found) {
monitor.openMonitor($scope.msg.openMonitor.toUpperCase(), $scope.inputText);
}
};
```

![image](https://cloud.githubusercontent.com/assets/512816/16451250/c58b0300-3df9-11e6-8600-1c1f671970a2.png)

**Comment by zhengbli** [comment]
Hmmm. @leegee  This is what I got using your code:
![gif](https://cloud.githubusercontent.com/assets/1171301/16461578/0e6b2784-3de2-11e6-93fb-c06ef6a82312.gif)
I am using the same commit of VSCode as you, and I'm using the typescript version that comes with it as well.

**Comment by leegee** [comment]
What can I say?

How did you record the animation?

**Comment by zhengbli** [comment]
I used [GifCam](http://blog.bahraniapps.com/gifcam/).

If you set the settings to
```
"typescript.tsserver.trace": "verbose"
```
Would you see exception & trace information in your output panel, TypeScript channel?
