### ISSUE TITLE
More Recursive Type Declarations

### ISSUE THREAD

**Issue by opensrcken** [Microsoft/TypeScript#9074]
**TypeScript Version:** 

nightly

**Code**

```ts
// A self-contained demonstration of the problem follows...
type Json = string | number | boolean | null | JsonObject | JsonArray;
type JsonObject = { [key:string]: Json };
type JsonArray = Array<Json>;
```

**Expected behavior:**
Compiles.

**Actual behavior:** 
Type alias 'Json' circularly references itself.
Type alias 'JsonArray' circularly references itself.

As a workaround, I'm using the more verbose:

```ts
declare type Json = JsonObject | number | string | JsonArray;
declare type JsonArray = IMaybeRecursiveArray<JsonObject | number | string>;
interface IMaybeRecursiveArray<T> {
  [i: number]: T | IMaybeRecursiveArray<T>;
}
interface JsonObject {
  [paramKey: string]: Json
}
```

But FlowType can compile the more "direct" type declarations. It would be nice if Typescript could support this as well.

**Comment by mhegazy** [comment]
please see https://github.com/Microsoft/TypeScript/issues/3496#issuecomment-128553540

**Comment by opensrcken** [comment]
I definitely never saw that comment. My apologies.
