### ISSUE TITLE
A duplicate declaration of Node.prototype.contains

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#9075]
**TypeScript Version:** 

master

**Code**

https://github.com/Microsoft/TypeScript/blob/master/lib/lib.dom.d.ts#L8754
https://github.com/Microsoft/TypeScript/blob/master/lib/lib.dom.d.ts#L8766

@zhengbli can you remove one of them?

**Comment by mhegazy** [comment]
caused by https://github.com/Microsoft/TSJS-lib-generator/blob/master/inputfiles/addedTypes.json#L301-L303

**Comment by mhegazy** [comment]
PRs welcomed.
