### ISSUE TITLE
Goto declaration for default import behaves differently

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#9078]
```
// x.ts
export default 0;
export const x = 0;
export const y = 0;

// index.ts
import df, {x, y as z} from "./x";
[df, x, z];
```

Starting from the last line of `index.ts`, goto-declaration on `x` and `z` each go directly to `x.ts`. But for `df` it goes to the import first, and one must goto-declaration again to get to `x.ts`.

**Comment by rozzzly** [comment]
+1 This has been bugging me for a while, but it seemed intermittent. Nice observation that it was only on default imports.
