### ISSUE TITLE
Find all references for default export does not include alternate names

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#9079]
// x.ts
    export default function x() {};

    // index.ts
    import x from "./x";

    // other.ts
    import y from "./x";

Goto-definition for "y" correctly goes to `x.ts`.
But find-all-references for "x" in `x.ts` only finds itself and the usage in `index.ts`.

**Comment by mhegazy** [comment]
duplicate of https://github.com/Microsoft/TypeScript/issues/5513
