### ISSUE TITLE
Find all references does not work for default export of ambient module

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#9081]
```
// declarations.d.ts
declare module "x" {
    const df: number;
    export default df;
}

// index.ts
import df from "x";
```

Goto-declaration works for `df` in `index.ts`, but find-all-references for `df` in `declarations.d.ts` only finds the two uses in that file.

**Comment by OliverJAsh** [comment]
I believe this is not restricted to ambient modules not all modules.

**Comment by mhegazy** [comment]
Seems to be working in latest.
