### ISSUE TITLE
Give an error on using '--module' with a non-module input file

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#9082]
Currently, if a user doesn't have an import/export statement, output usually messed up and users are left wondering how to fix them. We should give an error on using '--module' with a non-module input file.

Then give users an option like `--allowScriptInputs` or `--allowGlobalInputs` if they really know what they're doing.

One thing to keep in mind is that you don't want to create errors in the file itself, as it would be incredibly annoying to constantly see this error while typing. I would think you would only see it at emit time.

**Comment by RyanCavanaugh** [comment]
This is `--isolatedModules`
