### ISSUE TITLE
Improve test baseline handling

### ISSUE THREAD

**Issue by RyanCavanaugh** [Microsoft/TypeScript#9093]
We should be able to improve test execution speed by making some very simple changes to how baselines work to drastically reduce the amount of disk I/O we have to do. This would also have the side effect of making `jake baseline-accept[soft]` obsolete.

Instead of writing a bunch of files to `tests/baselines/local`, the only files that should written to disk are _different_ files. Additionally we'll need a folder `tests/baselines/local/missing` with zero-byte files to represent a file that exists in `reference` but was not created by a test.

The test runner will also need to keep track of whether or not it's running in a not-all-tests filter mode and, if so, keep track of which files in `reference` never got possibly-generated and make `missing` entries for them.

All of this happens in `runBaseline` so it should be relatively isolated work.

`jake baseline-accept` then just needs to copy whatever's in `local` on top of `reference`, and delete the files whose names match what's in `missing`.

**Comment by RyanCavanaugh** [comment]
Throwing in the community milestone but I'll take this up at some point if no one else does

**Comment by deyshin** [comment]
Seems like this issue is closed by @RyanCavanaugh's commit.
[Make baselines faster by not writing out unneeded files](https://github.com/Microsoft/TypeScript/commit/53d54c2b282d7bc4808941292fd91c1d41f5e4cc)

I don't think there is a change regarding `tests/baselines/local/missing` though. Am I correct?

**Comment by RyanCavanaugh** [comment]
Yep, this has been done.

**Comment by RyanCavanaugh** [comment]
Missing files were handled with a .delete file rather than a missing folder

**Comment by deyshin** [comment]
Gotcha. Thanks for the clarification!
