### ISSUE TITLE
Possibility of publishing installer on a nightly basis

### ISSUE THREAD

**Issue by naveedahmed1** [microsoft/TypeScript#9101]
Is there any possibility of publishing installer on a nightly basis? This will make it easy to install latest version of TypeScript for those who wants to try latest features.

**Comment by basarat** [comment]
> Is there any possibility of publishing installer on a nightly basis

there is already `npm install typescript@next` which is great for command line users / [IDE authors](http://alm.tools/) / VSCode ... but I suspect you want a visual studio installer :rose:

**Comment by naveedahmed1** [comment]
You are right Basarat, I am referring to visual studio installer.

**Comment by mhegazy** [comment]
We do produce nightly builds for VS, but we do not currently have the infrastructure to publish them to the Download Center, or any other public facing CDN. This is something on our radar, and we have been waiting for the internal infrastructure teams to enable this automatic publishing.

Also worth noting, the MSBuild/Build tools are available on nightly bases as a the nuget package on myget.org, see https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Nightly%20Builds.md#using-nuget-with-msbuild.

**Comment by naveedahmed1** [comment]
@mhegazy thank you for your reply, glad to know that its already on your radar. I tried those nuget packages but receive the below error:

```
PM> Install-Package Microsoft.TypeScript.MSBuild -Version 1.9.0-beta-20160613-2
Attempting to gather dependency information for package 'Microsoft.TypeScript.MSBuild.1.9.0-beta-20160613-2' with respect to project 'MyProject', targeting '.NETFramework,Version=v4.5.2'
Install-Package : Package 'Microsoft.TypeScript.MSBuild,1.9.0-beta-20160613-2' is not found in the following primary source(s): 
'https://api.nuget.org/v3/index.json,https://www.nuget.org/api/v2/curated-feeds/microsoftdotnet/,C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\'. Please verify all your online 
package sources are available (OR) package id, version are specified correctly.
At line:1 char:1
+ Install-Package Microsoft.TypeScript.MSBuild -Version 1.9.0-beta-2016 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
```

**Comment by paulvanbrenk** [comment]
You need to add `https://www.myget.org/F/typescript-preview/ ` as a source to your `nuget.config`, though I'm not 100% sure how that works with the powershell tools.

**Comment by mhegazy** [comment]
i would like to keep this open to track this request.

**Comment by RyanCavanaugh** [comment]
We can use TS from node_modules now, so basically unneeded
