### ISSUE TITLE
Deriving namespace of types

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#9102]
A `extends` keyword derives only namespace of variables.

**TypeScript Version:** 

master

**Code**

```ts
class B {
}
namespace B {
	export type M = number;
	export var m = 0;
}
class D extends B {}
var m: D.M = D.m;
```

**Expected behavior:**

```
$ node built/local/tsc.js index.ts
```

**Actual behavior:** 

```
$ node built/local/tsc.js index.ts
index.ts(8,8): error TS2503: Cannot find namespace 'D'.
```

**Comment by falsandtru** [comment]
If TypeScript derives namespace of types, I can use partial classes using mixins. https://github.com/Microsoft/TypeScript/issues/563#issuecomment-225400463

cc @RyanCavanaugh

**Comment by mhegazy** [comment]
This is working as intend. initially in 0.8.* extends would get you all the declarations but that seemed a lot like statics.

So the recommendation is to use statics if you want your declarations to be inherited, and use namespaces for augmentation to the current symbol.

**Comment by falsandtru** [comment]
Is your comment a deciding of design for this proposal?

**Comment by mhegazy** [comment]
I do not think there is new information to warrant a design reconsideration.

**Comment by falsandtru** [comment]
My description has a diff of behaviors. Or, what formats for proposals do you need?

**Comment by mhegazy** [comment]
> My description has a diff of behaviors. Or, what formats for proposals do you need?

A use-case description that is not possible today because of this issue.

**Comment by falsandtru** [comment]
So I'll create this proposal.
