### ISSUE TITLE
A token is not highlighted correctly

### ISSUE THREAD

**Issue by plantain-00** [Microsoft/TypeScript#9105]
**TypeScript Version:** 

1.8.10

**Code**

```ts
const from = 1;
const to = 1;
const of = 1;
const foo = { from, to, of };
```

**Expected behavior:**
The `from` should be highlighted the same as `to`.
**Actual behavior:** 
The `from` should be highlighted the same as `const`.

Can get it from playground and VSCode.

**Comment by plantain-00** [comment]
'''
const from = 1;
const to = 1;
const foo = { from, to };
'''

**Comment by mhegazy** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#185
