### ISSUE TITLE
can i use import module in nodejs ,and avoid reltive path

### ISSUE THREAD

**Issue by gastrodia** [Microsoft/TypeScript#9106]
I don't wan't import a module write a lot reltive path such as 

`
import {myFunction} from '../../../../../myModule'; 
`

is any solution?

**Comment by aluanhaddad** [comment]
Try importing it relative to the root directory of your application. You shouldn't need that many `../`s unless the desired module is actually located 4 levels above your app folder. If that's the case, you may want to create a local package.json, restructure your app, or maybe even use npm link.

Generally I find myself rarely writing parent relative imports, and when I do they're usually just one level up. 

That said, I mainly right client-side TypeScript, but that kind of import pattern may indicate an overall structuring inneficiency. 

On the other hand if it's a helper library that you use all over the place, consider installing or locating it at the top level of your application directory and then simply importing it directly.

Also consider using the re-export pattern.
