### ISSUE TITLE
Unsound enforcement of generic type constriants.

### ISSUE THREAD

**Issue by zv** [Microsoft/TypeScript#9111]
**TypeScript Version:** 

1.8.0-beta

**Code**

```ts
// A self-contained demonstration of the problem follows...
interface Bar {
    fn: <T>(t: T) => void;
}
interface Foo {
    x: number;
}
function toBar<T extends Foo>() : Bar {
    return {
        // This type constraint couldn't be enforced anyway.
        fn: (t: T) => {
            console.error(t);
        }
    };
}

// Succeeds without any errors
function constraintValidation(bar: Bar): void {
    bar.fn({}); 
}

constraintValidation(toBar<Foo>()); // displays "undefined"

```

**Expected behavior:**
This constraint should be enforced -- I can't find any evidence in the documentation that this is intended behaviour, so I'll chalk it up to a specific error with the enforcement machinery. 

**Actual behavior:** 
Succeeds without any errors.

**Comment by Arnavion** [comment]
The `T` of `Bar.fn<T>` and of `toBar<T>` are separate. Thus the call to `bar.fn({});` is free to specialize `Bar.fn<T>` to `Bar.fn<{}>` independent of what `toBar<Foo>()` returns.

Sounds like you want

```typescript
interface Bar<T> {
    fn(t: T): void;
}
```

instead.
