### ISSUE TITLE
Sourcemap debugging in Safari

### ISSUE THREAD

**Issue by galsch** [Microsoft/TypeScript#9114]
TypeScript Version: 1.8.0

**Expected behavior:**

When debugging my application (Angular2) I'm able to see the source map and debug the TypeScript files only in Google Chrome. However, I'm unable to debug the TypeScript files in Safari(Version 9.1.1 Mac OS).

Is it possible to debug the original TypeScript files in Safari? I need this to debug my iOS Cordova  apps  only from Safari, and I couldn't find an answer on the Web.

Actual behaivour:

I can only see the bundled javascript files - not the TypeScript files.

**Comment by RyanCavanaugh** [comment]
If the source maps work in Chrome then presumably they were generated correctly. What points to this being a TypeScript issue rather than a Safari issue?

**Comment by justme1** [comment]
Hi Ryan,

I'm not suggesting this is TypeScript issue; I'm intersted to know if there is support for this in Safari.
I'm assuming this is basic feature that is used by anyone who has to debug their apps on Safari(e.g. iOS apps).

**Comment by RyanCavanaugh** [comment]
Please only log TypeScript issues on the TypeScript issue tracker. This isn't a general discussion forum.
