### ISSUE TITLE
Rename Symbol goes to undesired places

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#9119]
_From @Spown on June 9, 2016 14:18_

- VSCode Version: 1.2.0
- OS Version: Win10x64

``Rename Symbol`` can wander off into files, that are undesired to change. Just now I had several lines using ``__dirname`` global variable, I decided to use an another user defined variable ``settings.paths.root`` and used ``Rename Symbol`` it worked fine, except it also went into ``.\typings\node\node.d.ts`` and changed it there as well... This happens even if I exclude the ``typings`` dir in ``.vscode\settings.json``

_Copied from original issue: Microsoft/vscode#7478_

**Comment by dbaeumer** [comment]
Rename operation is provided by the TS server. Moving...

**Comment by mhegazy** [comment]
closing in favor of https://github.com/Microsoft/TypeScript/issues/8227
