### ISSUE TITLE
Please add more Format Code options.

### ISSUE THREAD

**Issue by heroboy** [microsoft/TypeScript#9124]
Especially for open brace, for example:
- open brace position for namespace.
- open brace position for method.
- open brace position for lambda.
- open brace position for function.
- open brace position for control block
- ... (above are from VS2015 C# formatting options)

all above can be set to 'new line','same line' or 'don't automatically reposition' (from VS2015 C++ formatting options)

**Comment by mhegazy** [comment]
We already have `PlaceOpenBraceOnNewLineForFunctions`, this covers functions, methods, lambdas, function expression, classes, namespaces, interfaces, and enums. and `    PlaceOpenBraceOnNewLineForControlBlocks`, this covers if, for, while, and do statements.

**Comment by mhegazy** [comment]
in VS code these can be set through: 
```ts
    // Defines whether an open brace is put onto a new line for functions or not
    "typescript.format.placeOpenBraceOnNewLineForFunctions": false,

    // Defines whether an open brace is put onto a new line for control blocks or not
    "typescript.format.placeOpenBraceOnNewLineForControlBlocks": false,
```

In VS 2015/VS2013, these can be set through tools\options

![image](https://cloud.githubusercontent.com/assets/8000722/16016761/7222ed54-3151-11e6-9c05-4b5469e9edb3.png)

**Comment by heroboy** [comment]
Actually, I really want is to make different settings for function statement,function expression and arrow function. Or adding 'don't automatically reposition' is better.

**Comment by aluanhaddad** [comment]
Not really an issue, but I have always been frustrated by the following formatting behavior.

before formatting:
```TypeScript
(function () {
}());

var f = function () {
}();
```
after formatting:
```TypeScript
(function () {
} ());

var f = function () {
} ();
```

I find the whitespace inserted between the function expression and its invocation to be unseemly and would like to be able to disable it. I know I'm nitpicking but as no whitespace is inserted when the invoked expression is itself wrapped in parentheses, it doesn't seem consistent. That, I'm a jslint style die-hard... :grinning:

**Comment by RyanCavanaugh** [comment]
Closing due to lack of additional feedback
