### ISSUE TITLE
Typescript 1.8.4 / 1.8.6 installation issues for VS 2015 Update 2

### ISSUE THREAD

**Issue by stefan505** [Microsoft/TypeScript#9128]
I'm having trouble installing TypeScript 1.8.4 or 1.8.6 for VS 2015 Update 2. I tried following the steps on this issue without any luck: https://github.com/Microsoft/TypeScript/issues/7519

I have installed:

1) `TypeScript Tools for Microsoft Visual Studio 2015 1.8.4.0`
then
2) `TypeScript Tools for Microsoft Visual Studio 2015 1.8.6.0`

Windows shows that it installed:
![image](https://cloud.githubusercontent.com/assets/10812446/16004416/cae30bd0-3161-11e6-949d-da7c60a46c04.png)

My VS 2015 doesn't show TypeScript as being installed:
![image](https://cloud.githubusercontent.com/assets/10812446/16004330/5e0b79ac-3161-11e6-94e2-4fa366152579.png)

As a result, TS syntax highlighting doesn't work:
![image](https://cloud.githubusercontent.com/assets/10812446/16004448/f0d9121c-3161-11e6-8adb-ee835b844601.png)

Also, Text Editor options doesn't detect TypeScript at all:
![image](https://cloud.githubusercontent.com/assets/10812446/16004460/0daa5a2c-3162-11e6-947b-2682a123b5b4.png)

Installer logs:
[installer logs.zip](https://github.com/Microsoft/TypeScript/files/311613/installer.logs.zip)

**Comment by stefan505** [comment]
Noticed that this folder doesn't contain a `TypeScript` folder: C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft

**Comment by mhegazy** [comment]
TypeScript is already bundled with VS 2015 Update 2. you should get TS 1.8.30 out of the box. TS 1.8.4 and TS 1.8.6 are not compatible with VS 2015 Update 2. If you want to downgrade, you need to uninstall Update 2.

what is the reason for downgrading, if i may ask?

**Comment by stefan505** [comment]
The missing folder in my last comment was the issue in the end. I tried using Update 3 RC with TS 1.8.6. Due to bugs (compile on save for example)  I tried downgrading to Update 2, which proved disastrous. The fresh install did not install TS 1.8.3 correctly, which I assume ships with Update 2. All in all, I got it working in the end.
