### ISSUE TITLE
Strange behavior on overloaded signatures with user-defined type-guards

### ISSUE THREAD

**Issue by Artazor** [Microsoft/TypeScript#9130]
**TypeScript Version:** 

1.8.10 (Playground)

**Code**

```ts
type Tree = string | Many
interface Many extends Array<Tree> {};

function isMany(target: Tree): target is Many {
    return Array.isArray(target);
}

// CASE 1
function f1(target: string): string
function f1(target: Many): Many
function f1<T extends Tree>(target: T): T {
	return isMany(target) 
		? target.map(node => f1(node)) //  Property 'map' does not exist on type 'T'
		: target
	;
}

// CASE 2
function f2(target: string): string
function f2(target: Many): Many
function f2(target: Tree): Tree {
	return isMany(target) 
		? target.map(node => f2(node))  // Argument of type 'string | Many'
		: target                        // is not assignable to type 'Many'
	;
}

```

**Expected behavior:**

* Both cases should compile without error;

**Actual behavior:** 

* CASE 1: there was no type-narrowing applied to the target - should be `T & Many`;
* CASE 2: the function was overbound by the type narrowing, and lost its polymorpism on recursion.

**Comment by mhegazy** [comment]
generic type arguments were not narrowed down in TS 1.8, now they are. so at least the narrowing part is fixed.

**Comment by Artazor** [comment]
@mhegazy and what about CASE 2?

**Comment by mhegazy** [comment]
both should be narrowed correctly. i am getting errors now for the use of node, which seems right to me.

```txt
15         ? target.map(node => f1(node)) //  Property 'map' does not exist on type 'T'
                                   ~~~~

c.ts(15,33): error TS2345: Argument of type 'string | Many' is not assignable to parameter of type 'Many'.
  Type 'string' is not assignable to type 'Many'.


25         ? target.map(node => f2(node))  // Argument of type 'string | Many'
                                   ~~~~

c.ts(25,33): error TS2345: Argument of type 'string | Many' is not assignable to parameter of type 'Many'.
  Type 'string' is not assignable to type 'Many'.
```

**Comment by Artazor** [comment]
Yes, now they, at least, behave in the same. And the first issue is fixed.

But I still think this is incorrect:
*  the type 'string | Many' is correctly assigned to `node`
```ts
function f2(target: string): string
function f2(target: Many): Many
function f2(target: Tree): Tree {
    return isMany(target) 
        ? target.map(node => f2(node)) 
        : target  //         ^------------- why f2 signature here is bound to Many => Many??? 
                  //   it's completely other call and it should have it's own type inference
    ;
}
```

It looks like that together with narrowing of `target` we've narrowed the whole context of parametricaly-polymorphic function `f2`. The error is emitted because the compiler thinks that in that context `f2` can accept only `Many`. It is wrong. That is true, that the current (surrounding) call of `f2` is bound to `Many` by the `target`,  but it should not affect the recursive call of `f2` whose binding should be *inferred separately by its own parameter* (namely `node`). Shouldn't it?

**Comment by mhegazy** [comment]
target in this branch is `Many`, as it has been narrowed from `Tree` (i.e. `string` | `Many`) by virtue of `isMany` call. Since `Many` is jsut an array of `Tree`,  `node` in the call is of type `Tree` (i.e. `string` | `Many`). There are no call signatures for `f2` that accept `string | Many`, there is one that accept `string` and not that accept `Many`, but the compiler does not coalesce them. now the compiler id not find an overload matching your call, so it gave you the error on what it considered the best match so far.
