### ISSUE TITLE
strictNullChecks and undefined values in class

### ISSUE THREAD

**Issue by nicolashenry** [Microsoft/TypeScript#9131]
**TypeScript Version:** 

1.9.0-dev.20160613-1.0

**Code**

```ts
class Greeter {
	greeting: string;
	constructor(message: string) {
		// do nothing
	}
	greet() {
		return 'Hello, ' + this.greeting;
	}
}

export let greeting: string = new Greeter('world').greeting;

// greeting is undefined
console.log(greeting);
```

**Expected behavior:**

I would expect the compiler to complain about greeting not being assigned at least once in constructor with strictNullChecks flag activated.

**Actual behavior:** 

The code run without error.

**Comment by RyanCavanaugh** [comment]
See #8476
