### ISSUE TITLE
TSServer should warn about supicious project setups

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#9133]
**TypeScript Version:** 

1.8.x

The tsserver should warn when a file ends up in a virtual project although inside the workspace there is a tsconfig.json file that would cover the file but doesn't include it. This points very likely to a misconfigured project. The diagnostic maker is best generated on a file opened from the virtual project.

**Comment by mjbvz** [comment]
Closing as I have not seen recent reports of this causing confusion
