### ISSUE TITLE
lib.es2015.iterable.d.ts includes Promise<T>

### ISSUE THREAD

**Issue by alexeagle** [Microsoft/TypeScript#9139]
This means that 
`tsc --lib es2015.iterable @types/es6-promise/es6-promise.d.ts`
fails with 
Generic type 'Promise<T, R>' requires 2 type argument(s).

because lib.es2015.iterable.d.ts chose a different name for the free template variable than the es6-promise typing everyone uses from DT.

**Comment by mhegazy** [comment]
so what is the proposal? iterable adds some functions that return a `Promise`.

**Comment by alexeagle** [comment]
Maybe it used to, but doesn't at head: search Promise in https://github.com/Microsoft/TypeScript/blob/master/lib/lib.es2015.iterable.d.ts

proposal is to remove Promise and PromiseConstructor declarations in that file.

**Comment by mhegazy** [comment]
That means that Promise will reference iterables. Are you saying that this is less common?

**Comment by alexeagle** [comment]
es2015.promise.d.ts doesn't mention Iterable. Why should there be a dependency between the two at all?

**Comment by mhegazy** [comment]
So in https://github.com/Microsoft/TypeScript/blob/master/lib/lib.es2015.iterable.d.ts#L123-L139, we have some iterable references, e.g.:
```ts
interface PromiseConstructor {
  ...
  race<T>(values: Iterable<T | PromiseLike<T>>): Promise<T>;
}
```
this is why we have PromiseConstructor in this file, to augment it with the iterable overload.

we could move this out to `es2015.promise.d.ts`. but that means that `es2015.promise.d.ts` will need to have a declaration for `Iterable<T>`. hence my question; if we believe more ppl will be using itrables with es6-promise-shims, then we should be putting it in promise.

**Comment by alexeagle** [comment]
Ah, I see now. What we really want is for that one line in `lib.es2015.iterable` to declare "there's an interface named Promise that takes one generic parameter, but I don't know what name it has". No such syntax, right?

`interface Promise<?> {}`

That would make the file compatible with `es6-promise.d.ts` from DT.

cc @rkirov

**Comment by alexeagle** [comment]
I tried just a bit harder, and found that our `Promise<R>` is just old - it was already fixed on DT:
https://github.com/DefinitelyTyped/DefinitelyTyped/commit/830e8ebd9ef137d039d5c7ede24a421f08595f83#diff-f53514e542177d42bff33f6076b1fea9
