### ISSUE TITLE
No tsconfig support for strictNullChecks

### ISSUE THREAD

**Issue by ddivecs** [Microsoft/TypeScript#9141]
**TypeScript Version:** 

1.8.10

**Code**

```json
{
    "compilerOptions": {
        "strictNullChecks": true
    }
}
```

**Expected behavior:**
compile with strictNullChecks.

**Actual behavior:** 
This is a valid compiler option in https://www.typescriptlang.org/docs/handbook/compiler-options.html but does not exist in the schema http://json.schemastore.org/tsconfig and thus results in `error TS5023: Unknown compiler option 'strictNullChecks'.`

**Comment by Arnavion** [comment]
The handbook is jumping the gun, I think. That option is not in the current released version (1.8.10).

**Comment by mhegazy** [comment]
We should have the documentation covered by the time TS 2.0 ships out. see https://github.com/Microsoft/TypeScript-Handbook/issues/294

**Comment by mhegazy** [comment]
I will remove this option for now.

**Comment by mhegazy** [comment]
see https://github.com/Microsoft/TypeScript-Handbook/commit/86fa56d4f9fddb1be86e9d822d78f12c89eabe83

**Comment by szarouski** [comment]
@mhegazy, https://www.typescriptlang.org/docs/handbook/compiler-options.html still have strictNullChecks option.

**Comment by spencerturkel** [comment]
This is still an issue.

**Comment by RyanCavanaugh** [comment]
2.0 is still not released.

**Comment by mhegazy** [comment]
We update the sire in bulk. so we are waiting on the TS final release to move all docs to the 2.0 version (latest from https://github.com/Microsoft/TypeScript-Handbook). sorry for the delay.

**Comment by mspoulsen** [comment]
I still get this error in version 2.0.3: 

Error: Parse tsconfig error [{"messageText":"Unknown compiler option 'strictNullChecks'.","category":1,"code":5023}]

This is my tsconfig:

{
  "compilerOptions": {
    "module": "commonjs",
    "target": "es5",
    "sourceMap": true,
    "strictNullChecks": true
  },
  "exclude": [
    "node_modules"
  ],
  "files": [
    "test.ts"
  ]
}

**Comment by mhegazy** [comment]
should be updated now.
