### ISSUE TITLE
Improve error message when trying to use decorators with ES3 target

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#9143]
Given this code:
    
    declare const MyMethodDecorator: MethodDecorator;
    class A {
        @MyMethodDecorator
        method() {}
    }

    src/index.ts(3,5): error TS1241: Unable to resolve signature of method decorator when called as an expression.
      Supplied parameters do not match any signature of call target.

The error goes away when I add `"target": "ES5"` to my `tsConfig.json`. Given that this is the solution to the problem, the error message should say something about targeting ES5.

**Comment by rbuckton** [comment]
It should work if you write:

```
declare function MyMethodDecorator(target: any, key: any);
class A {
  @MyMethodDecorator
  method() { }
}
```

For `--target ES3` we don't provide a descriptor for decorators. Since we type check the decorator as a call, it is failing because `MethodDecorator` specifies too many arguments.
