### ISSUE TITLE
Using `typeof` to check for a function fails to narrow union types

### ISSUE THREAD

**Issue by LPGhatguy** [Microsoft/TypeScript#9150]
**Versions**: 1.8.10, 1.9.0-dev.20160613-1.0

Given a variable with a type that could resolve to a function or an object:

```ts
interface Stringable {
	toString(): string;
}

export type StringFunction = () => Stringable;

declare const x: StringFunction | Stringable;
```

Attempting to narrow the variable with a `typeof` type guard results in no call signature being found:

```ts
if (typeof x === "function") {
	x(); // Error: Cannot invoke an expression whose type lacks a call signature
}
```

The type here, when inspected via an IDE using the 1.8.10 language services is `(() => Stringable) | Stringable`, but we already asserted that it was a function, so it should have a call signature!

Defining a user type guard, like:

```ts
function isFunction(f: any): f is { (...args: any[]): any } {
	return typeof f === "function";
}
```

Allows usage that correctly narrows the type:

```ts
if (isFunction(x)) {
	x();
}
```

The type of `x` inside the type guard is `() => Stringable`, which is what I expected with the initial type guard.

Is this a bug?

**Comment by RyanCavanaugh** [comment]
This compiles without error for me in `master`. Can you double-check your compilation against `typescript@next` ?

**Comment by LPGhatguy** [comment]
Looks like I probably botched the install of TS 1.9-dev, it does appear to be working in `master`.

Thanks!
