### ISSUE TITLE
transpileModule() fails when lib option was given

### ISSUE THREAD

**Issue by asvetliakov** [Microsoft/TypeScript#9173]
**TypeScript Version:** 

Version 1.9.0-dev.20160614-1.0

**Code**

```js
const typescript = require("typescript");
const input = `export class Test { }`;
const output = typescript.transpileModule(input,
    {
        compilerOptions: {
            target: "es5",
            lib: ["es2015", "dom"],
            module: "commonjs",
        },
        reportDiagnostics: true
    }
);
console.log(output.diagnostics[0].messageText);
```

**Expected behavior:**
Compiles without error

**Actual behavior:** 
```
Option 'lib' cannot be specified with option 'noLib'.
```

Since transpileModule() forces ```noLib``` flag i'd expect it doesn't take account into ```lib``` option

**Comment by asvetliakov** [comment]
Also ```noEmitOnError``` option fails because ```isolatedModules``` was set

**Comment by mhegazy** [comment]
#9176 should handle all the remaining options.

**Comment by asvetliakov** [comment]
Thanks!
