### ISSUE TITLE
Peek definition for import {} in TypeScript

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#9177]
_From @wallverb on June 14, 2016 13:18_

Imagine this code

def.ts:
```
export interface Message {
  name: string
}
```

code.ts: 
```
import {Message} from './def'
import * as def from './def'

let test1:Message
let test2:def.Message
```

When I peek definition of `Message` in `let test1:Message` i only get `import {Message} from './def'` - it would be awesome if it was smart enough to determine that i'm importing interface `Message` and give me definition of that interface. Works fine for `let test2:def.Message` case

_Copied from original issue: Microsoft/vscode#7657_

**Comment by dbaeumer** [comment]
Moving to TS since the feature is provided there.

**Comment by mhegazy** [comment]
should be fixed in latest.
