### ISSUE TITLE
Feature suggestion: Compile-time reflection of string literal unions and enums

### ISSUE THREAD

**Issue by XorgonTheTypesafe** [Microsoft/TypeScript#9182]
say we have

```
type Fish = "one" | "two" | "red" | "blue";
```

or 

```
enum Fish
{
   one,
   two,
   red,
   blue
}
```

It would be useful to have a way to refer to the possible values at runtime:
something like `__valuesof(Fish)` would transpile to 
`["one" , "two" , "red", "blue"]` in both cases.

Also consider __enummap(Fish) that would transpile to 

```
{
	"one":1,
	"two":2,
	"red":3,
	"blue":4	
}
```
or explicit enum values if specified. This would allow C#'s Enum.Parse functionality

**Comment by mhegazy** [comment]
The issue of type serialization/"reflection" has been discussed multiple times (https://github.com/Microsoft/TypeScript/issues/2902, https://github.com/Microsoft/TypeScript/issues/2577, https://github.com/Microsoft/TypeScript/issues/3060). we already have https://github.com/Microsoft/TypeScript/issues/3628 to track this discussion; so i suggest moving this proposal to that issue.
