### ISSUE TITLE
Feature suggestion: allow overwrite read-only output files.

### ISSUE THREAD

**Issue by mvockerodt** [Microsoft/TypeScript#9183]
Hi. 

Would it be possible to add a simple boolean compiler option to tsconfig.json that allows one to select to overwrite read-only output file(s)? Currently if the output file is read-only the compiler will not build.

Our specific use case is that we need the .js file to be marked as an embedded resource. That means it gets placed under source control (which is actually not necessary but I can't prevent it even using .tfignore) and therefore gets marked as read-only. I've tried prebuild events to change the read-only flag but it appears the TypeScript compiler runs before this prebuild event does so it has no effect.

A simple opt-in flag to overwrite the output file(s) would solve this issue trivially yet not break existing installations that depend on the current functioning.

Thanks,
Martin

**Comment by RyanCavanaugh** [comment]
My general take is that programs should not overwrite read-only files. We're not going to violate that constraint because of a nonconfigurable build system. Is there no other solution for your scenario? Source control systems that mark their files as read-only are increasingly rare.

**Comment by mhegazy** [comment]
Consider adding a prebuild step that will check out the files. i am assuming you are using tfs, there are multiple discussions on this issue already in:
http://stackoverflow.com/questions/892195/checking-a-file-out-tfs-for-a-pre-build-action and 
https://blogs.msdn.microsoft.com/nikhilsi/2008/06/12/how-to-autoincrement-version-with-each-build-using-team-foundation-server-build-with-a-little-help-from-assemblyinfotask/

**Comment by mvockerodt** [comment]
Noted, that is why I didn't suggest it being the default. 

This is a TFS setup with exclusive checkouts and server workspaces (it sets all files to be read-only when you get-latest etc). There was a reason a while back for us not using local workspaces (which don't set read-only) but I forget what that was (probably issues with developers messing up when resolving conflicts on project files manually).

I have already tried the prebuild events, and checking it out doesn't help because of the exclusive checkout policy.

Thanks for at least considering it though.

**Comment by mhegazy** [comment]
As noted by @RyanCavanaugh, this would better fall in the realm of build tools, and not the TS compiler.

**Comment by StingyJack** [comment]
Every other compiler overwrites the output it created previously. 

Having just lost a half hour of my life to this unexpected behavior, I do not understand the position of compiling something that then becomes immutable to that compiler in a development time context..
