### ISSUE TITLE
Find all references for computed property

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#9187]
Given:

```
let o = { ["foo"]: 12 };
let y = o.foo;
let z = o["foo"];
```

We can currently find-all-references for the first `"foo"` but not for the 2 uses. (We _can_ goto-definition for the uses).

The test `getOccurrencesIsDefinitionOfComputedProperty.ts` should be updated when this is done.

**Comment by RyanCavanaugh** [comment]
Works today
