### ISSUE TITLE
Incorrect return types for Promise#catch and 0- and 2- arg forms of Promise#then

### ISSUE THREAD

**Issue by jeffreymorlan** [Microsoft/TypeScript#9193]
Expression (p: Promise\<boolean\>) | Correct type | Current type
--- | --- | --- | ---
p.then() | Promise\<boolean\> | Promise\<{}\>
p.then(b => 1) | Promise\<number\> | Promise\<number\>
p.then(b => 1, e => 'error') | Promise\<number \| string\> | Promise\<number\>
p.then(b => 1, e => {}) | Promise\<number \| void\> | Promise\<number\>
p.then(b => 1, e => {throw Error()}) | Promise\<number\> | Promise\<number\>
p.then(b => 1, e => Promise.reject(Error())) | Promise\<number\> | Promise\<number\>
p.catch(e => 'error') | Promise\<boolean \| string\> | Promise\<boolean\>
p.catch(e => {}) | Promise\<boolean \| void\> | Promise\<boolean\>
p.catch(e => {throw Error()}) | Promise\<boolean\> | Promise\<boolean\>
p.catch(e => Promise.reject(Error())) | Promise\<boolean\> | Promise\<boolean\>

Using overloading and the new `never` type, PromiseLike/Promise could be typed to handle all these cases correctly:

```ts
interface PromiseLike<T> {
    then(): PromiseLike<T>;
    then<R1>(onfulfilled: (value: T) => R1 | PromiseLike<R1>): PromiseLike<R1>;
    then<R1, R2>(onfulfilled: (value: T) => R1 | PromiseLike<R1>,
                 onrejected: (reason: any) => R2 | PromiseLike<R2>): PromiseLike<R1 | R2>;
}

interface Promise<T> {
    then(): Promise<T>;
    then<R1>(onfulfilled: (value: T) => R1 | PromiseLike<R1>): Promise<R1>;
    then<R1, R2>(onfulfilled: (value: T) => R1 | PromiseLike<R1>,
                 onrejected: (reason: any) => R2 | PromiseLike<R2>): Promise<R1 | R2>;
    catch<R2>(onrejected: (reason: any) => R2 | PromiseLike<R2>): Promise<T | R2>;
}

declare var Promise: {
    reject(reason: any): Promise<never>; // Returned promise is never fulfilled
};
```

**Comment by mhegazy** [comment]
//cc: @rbuckton

**Comment by rbuckton** [comment]
There are a few things we need to fix in the checker for properly handling `never` in these cases with async functions, and there's a breaking change in the definition for `PromiseLike` and `Promise` that needs to be resolved, but this seems like the right direction.
