### ISSUE TITLE
`this` in function paramter list not classified as a keyword

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript#9197]
![image](https://cloud.githubusercontent.com/assets/8000722/16094735/742245fe-32f6-11e6-8072-8e9b9f8f5f9e.png)

I would expect the `this` in the parameter list to be blue.

**Comment by weswigham** [comment]
@sandersn is already working on things related to this in #9171 and #9037 - it may be more correct for him to finish this.
