### ISSUE TITLE
Find all refs and goto def do not work on `this` in function parameter position

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript#9198]
```ts
function f(this:any) {
    this;// find all ref/ goto def here
}
```

I expect this should show the two references of `this`.

**Comment by RyanCavanaugh** [comment]
Is this fixed?

**Comment by andy-ms** [comment]
This is working for me in vscode pointed at a checkout of master.

**Comment by RyanCavanaugh** [comment]
Please add the `Fixed` label to closed fixed bugs. Thanks!
