### ISSUE TITLE
comments are not preserved

### ISSUE THREAD

**Issue by Kflash** [Microsoft/TypeScript#9201]
**TypeScript Version:**  1.9.0-dev.20160217

**Code**

```ts
class Foo {

    // This comment will disappear
    public bar: string | number;
     constructor(abc: string | number) {
this.bar = abc;
}
}
```

**Expected behavior:**
This comments should still be there after the code have been transpilled down to ES6 / ES5 

**Actual behavior:** 
Comments are removed even if `"removeComments": false`, in `tsconfig.js.`.

**Comment by DanielRosenwasser** [comment]
The `bar` property is not initialized anywhere, so where exactly would you want the comment to appear?

**Comment by DanielRosenwasser** [comment]
For the record, [we do emit the comment](http://www.typescriptlang.org/play/#src=class%20Foo%20%7B%0D%0A%0D%0A%20%20%20%20%2F**%20This%20comment%20will%20disappear*%2F%0D%0A%20%20%20%20bar%20%3D%2010%3B%0D%0A%20%20%20%20%0D%0A%20%20%20%20constructor(abc%3A%20string%20%7C%20number)%20%7B%20%7D%0D%0A%20%20%20%20%7D%0D%0A%7D) if you have an initializer.

Input:
```ts
class Foo {

    /** This comment will disappear*/
    bar = 10;
    
    constructor(abc: string | number) { }
    }
}
```

Output:
```js
var Foo = (function () {
    function Foo(abc) {
        /** This comment will disappear*/
        this.bar = 10;
    }
    return Foo;
}());
```
