### ISSUE TITLE
Returned values from functions cause type inference with optional parameters to fail

### ISSUE THREAD

**Issue by yeerkkiller1** [Microsoft/TypeScript#9205]
**TypeScript Version:** 
1.7.5 / 1.8.0-beta / nightly (1.9.0-dev.20160217)

I tested this in 1.7.5 and 1.9.0-dev.20160217

**Code**

```ts
interface IProps {
	prop1?: number;
	prop2?: string;
}

declare function inferFromFnc<P>(p: P, fnc: () => P);

inferFromFnc(
	{} as IProps,
	function() {
		return { prop1: 5 };
	}
);
```

**Expected behavior:**
The inferFromFnc call succeeds.

**Actual behavior:** 
The inferFromFnc call fails:

```
Type argument candidate 'IProps' is not a valid type argument because it is not a supertype of candidate '{ prop1: number; }'. Property 'prop2 is missing in type '{ prop1: number; }'.
```

However it works in some unexpected cases:

prop1 is NOT optional
```ts
interface IProps {
	prop1: number;
	prop2?: string;
}
```

The passed function specifies its return parameters as optional:
```ts
function(): {prop1?: number} {
	return { prop1: 5 };
}
```

inferFromFnc uses a union:
```ts
declare function inferFromFnc<P>(p: P, fnc: () => P|{});
```

If we were using an object instead of a function:
```ts
declare function inferFromFnc<P>(p: P, p2: P);
inferFromFnc({} as IProps, {prop1: 5});
```

From what I can tell from the related spec (https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#3113-subtypes-and-supertypes) the reason the expected case fails is because when looking for a supertype to infer the generic type:
- {prop1?: number, prop2?: number} cannot be a subtype of {prop1: number} because it has excess properties
- Using it as the return value from a function causes different logic to be run, causing "the result type of M is Void, or the result type of N is a **subtype** of that of M" instead of "for parameter positions that are present in both signatures, each parameter type in N is a **subtype or supertype** of the corresponding parameter type in M, and"

Is there a reason "the result type of M is Void, or the result type of N is a **subtype** of that of M." is not worded as "the result type of M is Void, or the result type of N is a **subtype or supertype** of that of M."?

I apologize if this question is unclear, it seems like the return type of a function should be inferred just like an object would be, but there could be a very good reason it can't be that way.

**Comment by RyanCavanaugh** [comment]
The problem here is that we have two equally good types (`IProps` and `{ prop1: string }`) to choose from. Neither is perfectly substitutable for the other. We could potentially have some kind of "betterness" ranking but it's not obvious that there's any real ordering that would make everyone happy.
