### ISSUE TITLE
keypress e.code is not valid TypeScript, but is valid JavaScript

### ISSUE THREAD

**Issue by ChicagoDave** [Microsoft/TypeScript#9206]
**TypeScript Version:** 

1.8.10

**Code**

```ts
// A self-contained demonstration of the problem follows...

Grrr - I don't have time for this

in an input element onkeypress, you can't touch e.code. You have to create a plain JS function to read that totally legitimate property on the event argument.

```

**Expected behavior:**

(e.code == "Enter") is valid

**Actual behavior:** 

(e.code == "Enter") is not valid because .code is not recognized as a legit property

**Comment by kitsonk** [comment]
`.code` is relatively new with [only support in Firefox 32+](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code).  Things like this take a while to flow through the libraries (and may not be considered until there is wider browser support).  These additions [can be contributed](https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes).

Interfaces though are open ended, and if you are writing code that only works in Firefox, you can quite easily [add it yourself](http://www.typescriptlang.org/play/#src=interface%20KeyboardEvent%20%7B%0D%0A%09code%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Afunction%20listener(e%3A%20KeyboardEvent)%20%7B%0D%0A%09if%20(e.code%20%3D%3D%3D%20'Enter')%20%7B%0D%0A%09%09%2F%2F%0D%0A%09%7D%0D%0A%7D%0D%0A):

```typescript
interface KeyboardEvent {
	code: string;
}

function listener(e: KeyboardEvent) {
	if (e.code === 'Enter') {
		//
	}
}
```

It would be best though to place the extension in a custom `.d.ts` file which you maintain and include in projects where this valid at runtime (Firefox 32+ only).

**Comment by mhegazy** [comment]
should be addressed by https://github.com/Microsoft/TSJS-lib-generator/pull/138
