### ISSUE TITLE
Consider using union types for function return expressions

### ISSUE THREAD

**Issue by RyanCavanaugh** [Microsoft/TypeScript#921]
Via #919 

Even with union types, we still require that a best common type can be selected from the types of the return expressions in a function:
```ts
function fn() { // Error, return expressions do not have a BCT
  if(x) {
    return 'foo';
  } else {
    return 42;
  }
}
```

If this is the desired behavior, the user must write
```ts
function fn(): number|string {
```

This is inconsistent with how we're treating other cases, e.g. `var x = [1, 'foo'];` produces an` Array<number|string>`.

Is the desired behavior here that we infer a more complex union type return type for a function, or that we enforce a consistent set of return expression types when no other information is given?

**Comment by RyanCavanaugh** [comment]
Everyone seems to like the current behavior.

**Comment by JsonFreeman** [comment]
Perhaps we should reconsider this in the context of `yield` expressions in a generator. Ideally `yield` expressions should be subject to the same rules as return expressions, with respect to common type / union type. For someone using generators to model async/coroutine style programming, it is quite common to yield several unrelated types from a generator. For context, see https://github.com/Microsoft/TypeScript/issues/2873#issuecomment-97624632 and https://github.com/Microsoft/TypeScript/issues/2873#issuecomment-97084410.

Our three options are:
1. Infer union types for both return and yield expressions
2. Do not infer union types
3. Infer union types for yield expressions, but not return expressions.
