### ISSUE TITLE
Commenting out in tsx file

### ISSUE THREAD

**Issue by sandy081** [Microsoft/TypeScript#9210]
_From @wallverb on June 14, 2016 13:22_

Right now when I use `cmd+/` in tsx file in jsx part of the file:

eg. on second line of:

```
<div>
  <div>...</div>
</div>
```

then it will convert it to

```
<div>
  // <div>...</div>
</div>
```

It would be awesome if it could turn it into 

```
<div>
{/* <div>...</div> */}
</div>
```

_Copied from original issue: Microsoft/vscode#7658_

**Comment by mhegazy** [comment]
I guess we never thought of this one. the assumption now that a comment in TS is always adding `//`. we will need to make it based on syntactic context. so we will need a new API on the LS side to do that, possibly `getCommentEdits` and `getUncommentEdits` to do the two operations based on context.

**Comment by radix** [comment]
vscode now comments with the right syntax inside of tsx, so I guess this should be closed.

**Comment by priezz** [comment]
@radix, for me it does not... VScode 1.13.1

**Comment by cettoana** [comment]
Still have JSX comment problem in VSCode 1.14.2, any updates?

**Comment by cytryn** [comment]
also have this issue... did anyone find a solution?

**Comment by mjbvz** [comment]
This should be fixed in VS Code 1.19:

![dec-21-2017 16-19-18](https://user-images.githubusercontent.com/12821956/34280167-bb8e2af6-e66a-11e7-9203-e4579b913d0d.gif)

Please report any additional issues around jsx commenting against VS Code: https://github.com/Microsoft/vscode/issues/new

**Comment by rosieks** [comment]
What about regular Visual Studio?

**Comment by dhruvdutt** [comment]
I'm still facing this issue in latest VSCode.

**Comment by saostad** [comment]
same problem with 1.23.1

Version 1.23.1
Commit d0182c3417d225529c6d5ad24b7572815d0de9ac
Date 2018-05-10T17:11:17.614Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

**Comment by mhegazy** [comment]
Since this is a VS-specific feature i would add a comment on the VS issue tracking that under https://developercommunity.visualstudio.com/content/problem/50528/jsx-comment-syntax-is-incorrect.html
