### ISSUE TITLE
Inference of [a,b] to union type array is missing index signature [0]:A and [1]:B

### ISSUE THREAD

**Issue by hansmaad** [Microsoft/TypeScript#9216]
When calling a method declared as `all<T1, T2>(values: [T1, T2]);` I cannot use a union type array.

**TypeScript Version:** 

1.8.10

**Code**
OK:
```ts
$q.all([a, b]).then(/*...*/);
```
Error:
```ts
var promises = [a, b];
$q.all(promises).then(/*...*/);

> TS2329 Index signature is missing in type '(IPromise<A> | IPromise<B>)[]'
```

**Expected behavior:**
It would be nice if both versions work, without explicitly reference types A and B. I think the problem is, that `[a, b]` infers to `(A|B)[]` instead of `[A,B]`, which should prevent me from `[a,b].push(new C())` (Is this the intension?). The problem is, that `(A|B)[]` looses the indexers `[0]: A` and `[1]: B`. I think that's what the error message wants to say? 
Would it be possible to infer `[a, b]` to something like `(A|B)[A, B]` which is compatible to 

```ts
interface IAB {
    [i:number]: A|B;
    [0]:A;
    [1]:B;
}
```
Btw. the error message is rather confusing, since `(A|B)[]` actually has an index signature.

**Comment by aleksey-bykov** [comment]
it's a well known annoying problem with tuples among many others,
it doesn't work the way you expect because *array literals are inferred being array-types* not tuple-types

a workaround i use: 

```
function of2<a, b>(one: a, two: b) : [a, b] {
   return [one, two];
}
...
$q.all(of2(a, b)).then(/*.. here comes tuple ..*/);
```

**Comment by mhegazy** [comment]
As noted by @aleksey-bykov, the compiler can not infer any array literal as a tuple, as this would be a massive breaking change. so by the time we get to the call, `promises` is just an array or variable length.

**Comment by iskiselev** [comment]
Could it infer type to `(A|B)[] & [A,B]` which should not be a breaking change? Or have I missed something?

**Comment by kitsonk** [comment]
Seems to [be effective](http://www.typescriptlang.org/play/#src=const%20a%20%3D%201%3B%0D%0Aconst%20b%20%3D%20'string'%3B%0D%0A%0D%0Aconst%20p%3A%20(number%20%7C%20string)%5B%5D%20%26%20%5B%20number%2C%20string%20%5D%20%3D%20%5Ba%2C%20b%5D%3B%0D%0A%0D%0Afunction%20all%3CT1%2C%20T2%3E(values%3A%20%5BT1%2C%20T2%5D)%3A%20%5BT1%2C%20T2%5D%20%7B%0D%0A%09return%3B%0D%0A%7D%0D%0A%0D%0Afunction%20some%3CT%3E(values%3A%20T%5B%5D)%3A%20T%20%7B%0D%0A%09return%3B%0D%0A%7D%0D%0A%0D%0Aconst%20r1%20%3D%20all(p)%3B%0D%0Aconst%20r2%20%3D%20some(p)%3B%0D%0A):

```typescript
const a = 1;
const b = 'string';

const p: (number | string)[] & [ number, string ] = [a, b];

function all<T1, T2>(values: [T1, T2]): [T1, T2] {
	return;
}

function some<T>(values: T[]): T {
	return;
}

const r1 = all(p);
const r2 = some(p);
```

**Comment by DanielRosenwasser** [comment]
If you inferred that, you wouldn't be able to assign a `string` to `p[0]`, which `(number | string)[]` does allow.
