### ISSUE TITLE
1.8.9 - Parameter or Constructor parameter not recognized for template string

### ISSUE THREAD

**Issue by rcollette** [Microsoft/TypeScript#9219]
**TypeScript Version:** 

1.8.9
target ES5

**Code**

```
    constructor(x:string) {
      this.url = `y/{$x}`;
    }
```

**Expected behavior:**
The generated code should be `this.url="y/"+x;`

**Actual behavior:** 
The generated code is like `this.url="y/{$x}"`

It seems that template strings does not recognize parameters or constructor parameters.

Doing the following as a workaround does not work either:
```
    constructor(x:string) {
      x;
      this.url = `y/{$x}`;
    }
```

**Comment by mhegazy** [comment]
The `$` should be before the `{`. so it should be ``y/${x}`;`

**Comment by mhegazy** [comment]
see http://www.typescriptlang.org/docs/handbook/basic-types.html#string for documentation

**Comment by rcollette** [comment]
FacePalm.  Ugh.  So sorry.
