### ISSUE TITLE
ES5 Compile On Save does not always generate var _this = this; for closures.

### ISSUE THREAD

**Issue by Merenwen** [Microsoft/TypeScript#9222]
**TypeScript Version:** 
VS TS 1.8.31

**Project Information**
Targeting: ES5
Module System: None
TypeScript Files: Around 200

**Code**

```ts
// Test Code
namespace TypeScript.Test {

    export interface Observation {
        Identifier: string
        Time: Date | string
        MeasuredValue: number
    }

    export interface IObservationManager {
        observations: Observation[];
        addObservation(obs: Observation);
    }

    export interface IServices {
        getObservations(start: Date, end: Date): Observation[];
        logger<T>(item: (arr: T[]) => void): string;    
    }

    export class MeasurementData {

        constructor(private services: IServices, private manager: IObservationManager) { }

        public updateView() {
            //Do something
        }

        public updateGroups() {
            //Do something else
        }

        public queryObservations(start: Date, end: Date) {
            const justForATest = "";

            return this.services.logger(obs => {
                //Function closure...
                const data = this.services.getObservations(start, end);
                this.updateManager(this.manager, data);
                this.updateGroups();
                this.updateView();
            })
        }

        private updateManager(manager: IObservationManager, observations: Observation[]) {
            if (manager) {
                manager.observations.length = 0;
                observations.forEach(o => manager.addObservation(o));
            }
        }
    }
}
```

**Expected behavior:**

Using Visual Studio's _Compile On Save_ feature should generate a combined JavaScript file ES5 compatibility.

In a function with closures within a class member, var _this = this is expected at the function root, and all instances of 'this' should be replaced with '_this'. 

```ts
//Correct Code
var TypeScript;
(function (TypeScript) {
    var Test;
    (function (Test) {
        var MeasurementData = (function () {
            function MeasurementData(services, manager) {
                this.services = services;
                this.manager = manager;
            }
            MeasurementData.prototype.updateView = function () {
                //Do something
            };
            MeasurementData.prototype.updateGroups = function () {
                //Do something else
            };
            MeasurementData.prototype.queryObservations = function (start, end) {
                var _this = this;
                var justForATest = "";
                return this.services.logger(function (obs) {
                    //Function closure...
                    var data = _this.services.getObservations(start, end);
                    _this.updateManager(_this.manager, data);
                    _this.updateGroups();
                    _this.updateView();
                });
            };
            MeasurementData.prototype.updateManager = function (manager, observations) {
                if (manager) {
                    manager.observations.length = 0;
                    observations.forEach(function (o) { return manager.addObservation(o); });
                }
            };
            return MeasurementData;
        }());
        Test.MeasurementData = MeasurementData;
    })(Test = TypeScript.Test || (TypeScript.Test = {}));
})(TypeScript || (TypeScript = {}));
```

**Actual behavior:** 
The file is generated, however some of the time the generated JavaScript does not generate var _this = this, nor do the replacements for closures.

```ts
//Incorrect Code
var TypeScript;
(function (TypeScript) {
    var Test;
    (function (Test) {
        var MeasurementData = (function () {
            function MeasurementData(services, manager) {
                this.services = services;
                this.manager = manager;
            }
            MeasurementData.prototype.updateView = function () {
                //Do something
            };
            MeasurementData.prototype.updateGroups = function () {
                //Do something else
            };
            MeasurementData.prototype.queryObservations = function (start, end) {
                var justForATest = "";
                return this.services.logger(function (obs) {
                    //Function closure...
                    var data = this.services.getObservations(start, end);
                    this.updateManager(this.manager, data);
                    this.updateGroups();
                    this.updateView();
                });
            };
            MeasurementData.prototype.updateManager = function (manager, observations) {
                if (manager) {
                    manager.observations.length = 0;
                    observations.forEach(function (o) { return manager.addObservation(o); });
                }
            };
            return MeasurementData;
        }());
        Test.MeasurementData = MeasurementData;
    })(Test = TypeScript.Test || (TypeScript.Test = {}));
})(TypeScript || (TypeScript = {}));
```

**Workaround:**
Using the command line tsc compiler directly seems to always generate the expected JavaScript.
For now our team will go forward with utilizing this directly, but the _Compile On Save_ feature in Visual Studio was very nice to use. Up until 1.8 we experienced no problems with the _Compile On Save_ feature.

**Comment by mhegazy** [comment]
@sandersn can you take a look.

**Comment by sandersn** [comment]
@Merenwen, I tried a simple repro but couldn't get anything -- not surprising since this looks like a multi-file bug. Can you provide some detail about your project? In order, here's the best way to help:

1. A minified repro.
2. Your entire project; I could sign an NDA if needed. 
3. Your tsconfig.json and/or file full of triple-slash references.

The best hypothesis that @vladima and I came up with was that checking starts in some other file based on some edits, then touches this file. Later you invoke compile-on-save on this file and it emits with incomplete information from the checker.

I'll try to synthesise a repro from scratch starting from your single-file example but I'm not sure how much success I'll have.

**Comment by mhegazy** [comment]
@Merenwen any updates about steps to reproduce this issue locally?

**Comment by Merenwen** [comment]
@mhegazy Sorry for the delay. After talking with our manager we won't be able to give out the repo, though I might still be able to give you some metadata on how many files we have / directory structure if that would help. We currently have 215 typescript files (including external d.ts files) in our project.

At this point the Compile on Save functionality generates any combined file about half the time. I think this could be related to the large amount of typescript files we have. 
However, when using the compiler outside of Visual Studio, it always generates the combined file correctly.

**Comment by mhegazy** [comment]
Unfortunately meta data would not be sufficient. the behavior described is dependent on your code. the compiler takes a code path that does not mark the function to capture the `this` binding at emit time. to identify this code path we need to debug through the compiler using your project, or any other code sample that demonstrates the issue. unless we have that, i am afraid this issue is actionable for us.

**Comment by mhegazy** [comment]
We have changed the emitter logic to emit this capture. this should not be an issue any more. please give `typescript@next` a try.
