### ISSUE TITLE
unexpected TS2342

### ISSUE THREAD

**Issue by lucap86** [Microsoft/TypeScript#9227]
i have 3 static function

```ts
Util.isString(value:any):boolean{
return typeof value === 'string'
}

Util.isFunction(value:any):boolean{
return typeof value === 'function'
}

Util.noop():void{}
```
Than
```ts
foo(fn:Function|string, context:Object){
    fn = Utils.isFunction(fn) ? fn : (Util.isString(fn) && Util.isFunction(context[fn]) ? context[fn] : Util.noop);
    fn.apply(this);
}
```
This produce an unexpected TS2342 An index expression argument must be of type 'string', 'number', 'symbol', or 'any'
But Util.isString(fn) ====> typeof fn === 'string'

**Comment by yortus** [comment]
Try annotating your `isString` and `isFunction` return types as follows:

```ts
function isString(value:any): value is string {
    return typeof value === 'string'
}

function isFunction(value:any): value is Function {
    return typeof value === 'function'
}
```

Then the `TS2342` error should go away.

Type guard functions need these special `x is Type` return type annotations for the compiler to recognise them as type guards and use them to narrow types. They still return a boolean value of course.
