### ISSUE TITLE
Indenter should indent binary operands more than their parent

### ISSUE THREAD

**Issue by JsonFreeman** [Microsoft/TypeScript#923]
Indenter gives the following for binary expressions:
```TS
a = a &&
b;
c = c
&& d;
```

But it would be much nicer to have
```TS
a = a &&
    b;
c = c
    && d;
```

The previous indenter does not do this correctly either, but the Visual Studio JavaScript indenter does.

**Comment by mhegazy** [comment]
should work as expected now.
