### ISSUE TITLE
Prevent access to abstract properties in the constructor

### ISSUE THREAD

**Issue by sandersn** [Microsoft/TypeScript#9230]
**TypeScript Version:** 

nightly (and earlier)

**Code**

``` ts
abstract class AbstractClass {
    constructor(s: string) {
        this.m(parseInt(s));
        console.log(this.n);
        this.n = 12;
    }

    abstract n: number;

    abstract m(n: number): void;
    m2() {
        console.log(this.n);
    }
}
```

**Expected behavior:**

Errors for each access and assignment of `this.n` in the constructor of the abstract property.

**Actual behavior:** 
No errors

**Comment by charlespierce** [comment]
PR #19005 opened to resolve this issue.
