### ISSUE TITLE
Compiler doesn't understand type restrictions in function declaration

### ISSUE THREAD

**Issue by OlegTsyba** [Microsoft/TypeScript#9231]
**TypeScript Version:** 

1.8.10

**Code**

```ts
function map<T>(list:   Array<T>,
                fn:     (T) => any): Array<any>
{
    let res = [];
    for(let i = 0; i < list.length; i++)
        res.push(fn(list[i]));
    return res;

}

console.log(map<string>(['fuck', 'the', 'police'], (x: number) => x.toFixed()));
```

**Expected behavior:**
I expected the typechecker rejected `(x: number) => x.toFixed()`, since it doesn't fit to the type declaration.

**Actual behavior:** 
Typechecker didn't reject this code. So, I have runtime error instead of compile error

**Comment by sandersn** [comment]
The syntax for functions is different than what you expected, probably:
```ts
                fn:     (T) => any): Array<any>
```

should be
```ts
                fn:     (t:T) => any): Array<any>
```

You have to give the parameter a name. Otherwise, it uses `T` as the name and `any` as the type.
