### ISSUE TITLE
Enum index signature to get enum value by string representation

### ISSUE THREAD

**Issue by Strate** [Microsoft/TypeScript#9234]
As for now, in TS 1.9, enums has implicit index signature `[index: number]: string`, which could be used to get string representation of enum value, but there is no "reverse" index signature: `[index: string]: T` where `T` is enum.

```typescript
enum Enum {
  One,
  Two
}
let a: Enum
let b: string
b = Enum[a]
a = Enum[b] // error "Element implicitly has an 'any' type because index expression is not of type 'number'
```

It would be great, if enums has index signature `[index: string]: Enum | void`, which could be used for getting enum value by string representation.

I suggest to use `Enum | void`, not just `Enum` for `[index: string]: Enum | void` signature to force developer check typeof expression:

```typescript
enum Enum {
  One,
  Two
}
let a: Enum
let b: string
let c: Enum | string
b = Enum[a]
a = Enum[b] // error "type 'Enum | void' is not assignable to type 'Enum'"
c = Enum[b] // no error
if (typeof c !== "undefined") {
  a = c // no error
}
```

P.S. tsconfig.json:
```json
{
    "compilerOptions": {
        "noImplicitAny": true,
        "suppressImplicitAnyIndexErrors": false
    },
}
```

**Comment by RyanCavanaugh** [comment]
The reality is that indexing an enum by a string sometimes produces a number and sometimes produces a string (e.g. indexing by `"0"` produces `"One"`). If you have a key that you *truly know* is the name of one of the members, that's the appropriate time to use a type assertion to tell the type system about the extra information you have.
