### ISSUE TITLE
a class cannot extend events node module

### ISSUE THREAD

**Issue by NikosEfthias** [Microsoft/TypeScript#9243]
**TypeScript Version:** 

1.8.10

**Code**

```ts
/// <reference path="./../../../typings/index.d.ts" />
import {EventEmitter} from "events";
class _req extends EventEmitter {
	constructor() {
		super();
	}
	emit() {
		super.emit("test")
	}
}
const a = new _req();
a.on("test", _ => {
	console.log("test was called");
})
a.emit();
```

**Expected behavior:**
compile with no errors 
**Actual behavior:** 
i got the error telling me 
```
ts/core/request/index.ts(3,7): error TS2415: Class '_req' incorrectly extends base class 'EventEmitter'.
  Types of property 'emit' are incompatible.
    Type '() => void' is not assignable to type '(event: string, ...args: any[]) => boolean'.
      Type 'void' is not assignable to type 'boolean'.
```

**Comment by kitsonk** [comment]
This isn't an issue with TypeScript.  This is basic stuff.  You should read the error and fix it.

The method you are extending does not match the contract of the underlying class.  As the error says, your extended `emit` is of type `() => void`, but the method you are extending is of type `(event: string, ...args: any[]) => boolean` and the need to be compatible, so at the very least `emit` need to return a boolean value.

For basic questions like these, StackOverflow, Gitter or IRC are better places to ask.

**Comment by NikosEfthias** [comment]
ah now it makes sense i am sorry for opening this i just didnt pay attention to my own emit method
