### ISSUE TITLE
Cannot set property 'xyz' of undefined

### ISSUE THREAD

**Issue by benmillhouse** [Microsoft/TypeScript#9247]
It would seem like this is a (common?) bug that the compiler could catch for us.

Given this example class:
```javascript
class Foo {
    bar: number;
}
let a: Foo;
a.bar = 1;
```

At runtime I will get an error 'Cannot set property 'bar' of undefined because I never actually initialized the object. (i.e. `let a: Foo = new Foo();` or `let a = new Foo();`)
This seems to me like it could probably be a pretty common developer mistake given the ability to provide types (: Foo), especially since editors will give you full Intellisense on the object just by naming the type of it without initialization.  I'm curious if it's something that the Compiler could catch?  (variable a is undefined; declared, but never initialized)

**Comment by yortus** [comment]
If you use the `--strictNullChecks` compiler option, you'll get a compiler error stating `Variable 'a' is used before being assigned`. Is that what you are after?

**Comment by benmillhouse** [comment]
That probably would do it. Sorry, didn't see that in the tsconfig options. I'll give it a try.

**Comment by yortus** [comment]
@benmillhouse it's only in the nightly version, so might not be documented yet. See #7140.
