### ISSUE TITLE
Go-to-definition doesn't work on path in calls to 'require'

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#9251]
./foo.js:

```js
module.exports = {};
```

./bar.js:

```js
var x = require(/*$*/"./foo");
```

1. Go to definition on `/*$*/`

Expected: Navigate to `foo.js`.
Actual: Nada.

**Comment by mhegazy** [comment]
@riknoll has been looking at similar issues with completions in require call. moving to his plate.
