### ISSUE TITLE
Completion info shows declared type, not narrowed type

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#9256]
```ts
interface AddTodo {
    type: "ADD_TODO";
    text: string;
}

interface DeleteTodo {
    type: "DELETE_TODO";
    id: number;
} 

type TodoAction = AddTodo | DeleteTodo;

function dispatchOrSomething(action: TodoAction) {
    switch (action.type) {
        case "ADD_TODO":
            actio/*$*/
            break;
        case "DELETE_TODO":
            break;
    }
}
```

![image](https://cloud.githubusercontent.com/assets/972891/16179572/96276e88-361e-11e6-8f3f-0350495ecf8d.png)

**Comment by ahejlsberg** [comment]
I don't think this is a bug. We don't know if you're going to assign to `action` (in which case we want to show the full type) or whether you're just reading the value. Once you type `action.` (i.e. a property access) the type actually narrows because we know it is a read.
