### ISSUE TITLE
Can anyone tell me the difference about module?

### ISSUE THREAD

**Issue by phevose** [Microsoft/TypeScript#9261]
I recently was planning to convert javascript to typescript in my nodejs project,there are many "module.exports" "export.myfunction" in javascript code,i need use "exports class"、"export defaule"、"export let"、"import from ..."、"import <name> from ....." instead them.
by example:
javascript code
exportA.js
```
var Item = {
      'a':'100',
      'funcA':function(v){
               return v++;
       }
};
module.exports=Item;
```
importB.js
```
var item = require('./exportA');
console.log(item.funcA(item.a));
```
use typescript
exportA.ts
`exports default Item;`
or
`exports let Item={.....};`
or
```
exports class item{
    ......
}
```
importB.ts
`let item = require('./exportA');`
or
`import item './exportA';`
or
`import item from './exportA';`

**Comment by basarat** [comment]
> use typescript

First off its all `export` (not `exports`). That said I believe you are struggling with :

```ts
// import / require
import item = require('./foo');

// vs ES6 import
import * as item from "./foo";
```

# Difference 

import / require is legacy. It allowed TypeScript to support existing models like amd / commonjs in a type checked manner. Please use ES6 module format for new code :rose:

**Comment by basarat** [comment]
Also I recommend against `export default` : https://basarat.gitbooks.io/typescript/content/docs/tips/defaultIsBad.html :rose:

**Comment by phevose** [comment]
@basarat  Thanks for your reply!
I changed my code:
exportA.ts
```
let Item = {
      'a':'100',
      'funcA':function(v){
               return v++;
       }
};
**export** = Item;
```
importB.ts
```
import * as item from './exportA';
console.log(item.funcA(item.a));
```
