### ISSUE TITLE
About design patterns(typescript)

### ISSUE THREAD

**Issue by phevose** [Microsoft/TypeScript#9262]
Scene:
**init.js**
```
//because connectionPool should singleton,so i save it in nodejs global.
if(!global.connectionPool) global.connectionPool=createPool();
```
**module(A...X).js**(multiple)
```
reruire(./init.js);
global.connectionPool.execSQL('select * from tableA');
```

If use java,i could define 'abstract parent class' then initial 'connectionPool' in constructor,the next all module(A...X) extend 'abstract parent class',but in typescript.what Is Best Practice?

**Comment by kitsonk** [comment]
StockOverflow, Gitter or IRC are better places to discuss best practices and design questions...

**Comment by DanielRosenwasser** [comment]
Agreed with @kitsonk - though you should be able to do something similar with abstract classes in TypeScript anyhow.
