### ISSUE TITLE
Typescript with amd (requirejs) import(include/load) custom jquery plugin into mudule

### ISSUE THREAD

**Issue by Kwirirai** [Microsoft/TypeScript#9272]
How do you make the compiled typescript file include a jquery plugin amd module in the final compiled js file in the defines list of the module requiring the plugin eg currently output is  define(["require", "exports", "jquery"]... instead of 
 define(["require", "exports", "jquery" ,**"myplugin"**],.... which will allow the plugin to work.

I have the following greenify.js a Jquery plugin

       define(["jquery"], function($){
          $.fn.greenify = function() {
          this.css( "color", "green" );
         return this;
        };
     });
**greenify.d.ts**

    interface JQuery
    {
       greenify():JQuery;
    }

 **app.ts**

    import * as $ from "jquery";

    var hide = true;
    $("button").click(function(){
    if(hide){
      $("p").greenify();
      hide = false;      
     }else{
       $("p").css( "color", "black" );
       hide = true;
      }        
     });
With the usual typescript config ,typings config and jquery d.ts files.this compiles to app.js which does not include greenify in the ["require", "exports", "jquery"] list

      define(["require", "exports", "jquery"], function (require, exports, $) {
      "use strict";
      var hide = true;
       $("button").click(function () {
       if (hide) {
           $("p").greenify();
           hide = false;
       }
       else {
           $("p").css("color", "black");
           hide = true;
       }
        });
     });

Now using requirejs the greenify module will not be loaded.How can one make the compiled file include the greenify module to avoid the TypeError: $(...).greenify is not a function

**Comment by aluanhaddad** [comment]
**greenify.d.ts**
```TypeScript
interface JQuery
{
   greenify():JQuery;
}
declare module "greenify" { }
```
**app.ts**
```TypeScript
import * as $ from "jquery";
import "greenify";

var hide = true;
$("button").click(function(){
if(hide){
  $("p").greenify();
  hide = false;      
 }else{
   $("p").css( "color", "black" );
   hide = true;
  }        
 });
```

**Comment by rybolt** [comment]
@aluanhaddad  out of the (way too many) versions of import statements, I've never seen this one before:
`import "mod_name"` .  However, I think the key for me to get this working, is I have learned the hard way  , typescript wants everything to be a module, even though all I ever wanted to do is mandate requireJS style syntax to download a (js only , no .ts equivalent) dependency . Thanks

**Comment by mhegazy** [comment]
More documentation about modules can be found at http://www.typescriptlang.org/docs/handbook/modules.html

**Comment by civalin** [comment]
I got a problem about `import "mod_name"` operation.

If not `import` the plugin, but access **plugin related** interface, `tsc` will not raise any errors. It is really strange and not good.

# Reproducing

## pre-install

```sh
mkdir test
cd test
npm install @types/jquery@2 @types/bootstrap@3  # bootstrap is a jquery plugin
```

## create a file: `test.ts`

```javascript
import * as $ from "jquery";
// import "bootstrap";

$(`[data-toggle="tooltip"]`).tooltip(); // `.tooltip()` defined in bootstrap.
```

## run

```sh
tsc test.ts  # no error
 
rm -r node_modules/@types/bootstrap/  # remove plugins from filesystem...
tsc test.ts  #print:  test.ts(4,30): error TS2339: Property 'tooltip' does not exist on type 'JQuery'.
```

Both `tsc` `2.0.3` and `2.1.0-dev.20161005` has the same behavior. (System is ubuntu 16.04 and nodejs == `v4.2.6`)

Is it a bug or I miss something?
