### ISSUE TITLE
Regression: ES6 & TypeScript "go to definition" jumps to import

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#9274]
_From @jahewson on June 20, 2016 5:36_

- VSCode Version: 1.2.1
- OS Version: OS X 10.11.5

I the past week (or two?) the "go to definition" feature for ES6 and TypeScript has changed from jumping to the original definition to jumping to the import at the top of the current file. That's the old broken behaviour which was reported in #263 (and despite that issue being open still, was actually fixed and has worked nicely for several months).

"Peek definition" also suffers from the same problem.

I've opened this as a new issue to report it as regression and not as a feature request 😄 

_Copied from original issue: Microsoft/vscode#7878_

**Comment by dbaeumer** [comment]
This is actually a problem in the tsserver. Moving to the TS team.

**Comment by jahewson** [comment]
Just to be clear `#263` refers to [vscode/#263](https://github.com/Microsoft/vscode/issues/263), not TypeScript #263.

**Comment by mhegazy** [comment]
@jahewson this is working fine for me on the [nightly builds](https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Nightly%20Builds.md#visual-studio-code). can you share your sample?

**Comment by jahewson** [comment]
Ok, I figured this one out, I didn't have "settings.json" in source control, so moving to a a new branch didn't bring my "typescript.tsdk" setting with it. Everything works now!

**Comment by mhegazy** [comment]
thanks for getting back on this. closing.
