### ISSUE TITLE
Allow custom object types in JSDoc

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#9276]
_From @GRIM2D on June 18, 2016 10:11_

I'm using "vanilla" javascript for development. If I write custom object type in JSDoc, it appears as `any` or `void` . It will be more helpful, if one can type custom types.

- VSCode Version: 1.1.1 (1.1.1)
- OS Version: OSX (10.11.4)

Steps to Reproduce:

1. 
```javascript
/**
 * @param document {Object}
 * @returns {Object}
 */
function addDocument(document) {
	
}
```
![screen shot 2016-06-18 at 3 07 53 pm](https://cloud.githubusercontent.com/assets/6705445/16170266/b3f9bf6e-3566-11e6-9661-3868cf13210d.png)

2. 
```javascript
/**
 * @param document {ProductProjection}
 * @returns {ObjectId}
 */
function addDocument(document) {
	
}
```
![screen shot 2016-06-18 at 3 07 15 pm](https://cloud.githubusercontent.com/assets/6705445/16170276/d1ce4d16-3566-11e6-9d6e-2d9ca559aa68.png)

_Copied from original issue: Microsoft/vscode#7847_

**Comment by dbaeumer** [comment]
Moving to TS team.

**Comment by zhengbli** [comment]
With nightly you can defined customized type using the `@typedef` tag, for example
```
/**
 * @typedef { {name: string, age: number} } People
 */
```
Then use it elsewhere.

**Comment by GRIM2D** [comment]
Trying to write type definitions according [this](https://github.com/Microsoft/TypeScript/pull/8103).

Format 3 doesn't work

```javascript
/**
 * @typedef {Object} Product
 * @property {String} name
 */

/**
 * Creates a product instance
 * @return {Product}
 */
function makeProduct() {}
```
![screen shot 2016-07-10 at 9 14 20 pm](https://cloud.githubusercontent.com/assets/6705445/16714680/164c7d6c-46e4-11e6-96cd-0c887bdac331.png)

------------

However format 1 works

```javascript
/**
 * @typedef {{name: String}} Product
 */

/**
 * Creates a product instance
 * @return {Product}
 */
function makeProduct() {}
```
![screen shot 2016-07-10 at 9 14 48 pm](https://cloud.githubusercontent.com/assets/6705445/16714688/37178488-46e4-11e6-9493-9edde57b63a6.png)

-------------
```
$ tsc -v
Version 2.0.0-dev.20160707
```

**Comment by GRIM2D** [comment]
Also, function declarations are required.

Something like:
```javascript
/**
 * @typedef {{name: String, workClosure: () => (Error, Date) => void}} Product
 */

**Comment by zhengbli** [comment]
@GRIM2D That's a bug, I'll send a fix soon, it should have worked.

Regarding the function type, we use the popular jsdoc notation instead, so to achieve what you want you can do:
```
/**
 * @typedef { {name: String, workClosure: function(): function(Error, Date): void} } Product
 */
```

Reference for the type expression pattern:
https://developers.google.com/closure/compiler/docs/js-for-compiler#types
