### ISSUE TITLE
when i do alt-sht-f to format code it adds a semicolon to places with a starting parentheses and a starting curly bracket!! 

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#9277]
_From @shpleef on June 17, 2016 15:22_

- VSCode Version:
- OS Version:

Steps to Reproduce:
![screen shot 2016-06-17 at 17 21 59](https://cloud.githubusercontent.com/assets/16339855/16155497/0a6efac4-34b0-11e6-89ca-899de54e44bc.png)

1. vscode 1.20
2. MacOsX El Captain 

_Copied from original issue: Microsoft/vscode#7820_

**Comment by dbaeumer** [comment]
_From @tills13 on June 17, 2016 15:54_

Fill out the OS version/vscode version as well - it really helps the devs out.

**Comment by dbaeumer** [comment]
Moving to the TS team which own the formatter.

**Comment by mhegazy** [comment]
The typescript formatter does not add semicolons. this seems to be a different component. please reopen if you believe otherwise, and provide additional information to enable us to reproduce the issue locally.
