### ISSUE TITLE
Provide API for faster incremental compilers

### ISSUE THREAD

**Issue by alexeagle** [Microsoft/TypeScript#9282]
In https://github.com/Microsoft/TypeScript/issues/9017#issuecomment-225751262
@mhegazy suggested the possibility that TS could include an API that makes it easy to build incremental compilers, similar to the `--watch` behavior of TSC.

Given a `ts.Program` object, and a `string[]` of files that were modified, re-read and parse only the changed files, `getPreEmitDiagnostics` only for the changed files, emit only the changed files, and give the updated Program.

Right now it's too much work for us to write our own `tsc` that has the `--watch` behavior.

cc @IgorMinar

**Comment by TheLarkInn** [comment]
+1 😏

**Comment by TheLarkInn** [comment]
Tagging @ahejlsberg per conversation we had today about this issue. This is the number one problem we have reported from those who are going from Babel to TypeScript and looking for fast incremental builds. Related issue #9017 for more context Anders.

**Comment by mhegazy** [comment]
Should be fixed by https://github.com/Microsoft/TypeScript/pull/20234
