### ISSUE TITLE
Tests is not discoverable when using JavaScript output to directory

### ISSUE THREAD

**Issue by lostfields** [Microsoft/TypeScript#9287]
**TypeScript Version:** 
1.8.29.0

**Prerequisite**
"TypeScript Build" properties in Visual Studio 2015 (14.0.25123.00 Update 2) has to have "Redirect JavaScript output to directory" to eg. "build\"

**Expected behavior:**
Tests is discovered and runnable

**Actual behavior:** 
Tests is not discovered and runnable.

**Comment by lostfields** [comment]
when I reflect about this it is probably a NTVS (Node Tools) problem.

**Comment by mhegazy** [comment]
I do not see anything that TS does here to cause these issues. please reopen if you believe otherwise.
