### ISSUE TITLE
Externalize `collectExternalModuleReferences`

### ISSUE THREAD

**Issue by s-panferov** [Microsoft/TypeScript#9289]
Refs #9017 

Right now there is no way to extract external dependencies from SourceFile. This is useful for tools like [awesome-typescript-loader](https://github.com/s-panferov/awesome-typescript-loader) to track files dependencies and trigger rebuils on changed files.

I propose to make [`collectExternalModuleReferences`](https://github.com/Microsoft/TypeScript/blob/3fe546b9eaac9afff44251d2434c21a47c41cd99/src/compiler/program.ts#L1725) function from `program.ts` to became public for external users or add overload to `preProcessFile` to take existing `SourceFile`.

**Comment by RyanCavanaugh** [comment]
You can already simply walk the source tree (see here https://github.com/Microsoft/types-publisher/blob/master/src/lib/definition-parser.ts#L240 ) to collect the import statements. Is there extra information only the TS compiler itself could provide?
