### ISSUE TITLE
Type inference does not propagate properly across try/catch/finally blocks

### ISSUE THREAD

**Issue by dingfengquek** [Microsoft/TypeScript#9291]
"typescript": "1.9.0-dev.20160620-1.0"

```
function foo () {
  let maybe_connection : number | null; 
  try {
    maybe_connection = 1;
  } finally {
    return maybe_connection;
  }
}
```
Compile error: "Variable 'maybe_connection' is used before being assigned."
Expected outcome: 'maybe_connection' is properly inferred as being assigned and usable

```
finally { if (maybe_connection instanceof number) { ... } }
```
gives a compile error as well.

Use case: To initialise a database connection, use it in a try-catch-finally, and then, if the connection was acquired, to terminate/return-to-pool the connection

Urgency: Not urgent, workarounds exist, e.g. casting to "any" type

**Comment by ahejlsberg** [comment]
This works as intended. We can't know for certain that the assignment has happened in the `finally` clause because an exception *might* happen anytime in the `try` block.
