### ISSUE TITLE
toLowerCase == static string with upper case values?

### ISSUE THREAD

**Issue by wildert** [Microsoft/TypeScript#9297]
i've done this a few times

if(someVariable.toLowerCase() == 'thisThing'){
}

and this is obvious nonsense, can this create a compiler warning?

**Comment by DanielRosenwasser** [comment]
TypeScript does't treat any individual methods specially. All `toLowerCase` tells the compiler is that the method returns a `string`, which doesn't carry any information about what kinds of characters are in the resulting string.

This seems more in the domain of a lint rule which you could write up.
