### ISSUE TITLE
typescript doesn't check callback signatures

### ISSUE THREAD

**Issue by fernandezpablo85** [Microsoft/TypeScript#9300]
**TypeScript Version:** 

1.7.5

**Code**

```ts
type cb = (a:number, b:number) => number;

function foo(callback: cb): void {
	callback(1,2);
}

foo(function(a, b){return 1;}); // this is OK.
foo(function(a){return 1;}); // this should fail.
foo(function(){return 1;}); // this should fail.
```

**Expected behavior:**

First call should compile. The rest shouldn't.

**Actual behavior:** 

All calls compile cleanly.

**Additional note**
This is what happens, for example, with `Array.prototype.sort`

**Comment by Vitucho** [comment]
I also had the same problem...

**Comment by RyanCavanaugh** [comment]
https://github.com/Microsoft/TypeScript/wiki/FAQ#why-are-functions-with-fewer-parameters-assignable-to-functions-that-take-more-parameters

**Comment by kitsonk** [comment]
And the fourth one [does fail properly](http://www.typescriptlang.org/play/#src=function%20foo(callback%3A%20(a%3A%20string%2C%20b%3A%20string)%20%3D%3E%20number)%3A%20void%20%7B%0D%0A%09%0D%0A%7D%0D%0A%0D%0Afoo(function(a%2C%20b%2C%20c)%7Breturn%201%3B%7D)%3B%0D%0A).

**Comment by fernandezpablo85** [comment]
@kitsonk indeed, my bad. Just edited the code and removed that sample.

**Comment by fernandezpablo85** [comment]
@RyanCavanaugh thanks Ryan. I understand that it's impossible to even use union types to define a function that takes either a 3 argument or zero argument callback like this:

```ts
type noargs = () => number;
type args<T> = (a: T, b: T, c: T) => number;
type cb<T> =  args<T> | noargs;

function sort<T>(callback: cb<T>): void {}
```

because `sort(1,2)` would be a valid invocation. Right?

**Comment by RyanCavanaugh** [comment]
One way to think of it is that the invoker of the callback can only set a *maximum* arity of the callback, not a minimum. If the callee decides it doesn't care about the 2nd argument, it's not going to be forced to declare a dummy parameter.
