### ISSUE TITLE
Error when setting property of union type

### ISSUE THREAD

**Issue by SomeKittens** [Microsoft/TypeScript#9301]
**TypeScript Version:** 

```
$ tsc --version
Version 1.8.10
```

**Code**

```ts
interface IHello {
	prop: string | HTMLImageElement;
}

let x: IHello = {
	prop: new Image()
};

x.prop.src = 'http://i.imgur.com/CcydwKs.gif';
```

https://www.typescriptlang.org/play/#src=interface%20IHello%20%7B%0D%0A%09prop%3A%20string%20%7C%20HTMLImageElement%3B%0D%0A%7D%0D%0A%0D%0Alet%20x%3A%20IHello%20%3D%20%7B%0D%0A%09prop%3A%20new%20Image()%0D%0A%7D%3B%0D%0A%0D%0Ax.prop.src%20%3D%20'http%3A%2F%2Fi.imgur.com%2FCcydwKs.gif'%3B

**Expected behavior:**

No error when setting `x.prop.src`

**Actual behavior:** 

`Property 'src' does not exist on type 'string | HTMLImageElement'.`

**Comment by RyanCavanaugh** [comment]
Are you expecting that you should be able to set a `src` property on any value of type `string | HTMLImageElement`, or that the compiler should use the initializer of the `let` to infer a different type for `x` than what you explicitly declared?

**Comment by SomeKittens** [comment]
Specifically, I was expecting the compiler to figure out that, of the two types I had, that in this scenario, `x.prop` was of type `HTMLImageElement`.  I also tried to be more explicit about this with:

`x.prop = <HTMLImageElement> new Image();`

**Comment by RyanCavanaugh** [comment]
It's not sound for the compiler to allow that. Consider this code:
```ts
function fn(x: IHello) {
	x.prop = 'hello';
}

interface IHello {
    prop: string | HTMLImageElement;
}

let x: IHello = {
    prop: new Image()
};
fn(x); // harmless?
x.prop.src = 'http://i.imgur.com/CcydwKs.gif'; // fails
```

In your case (not seeing the unsimplified example), I would just remove the type annotation from `x` and let its type be inferred.

Alternatively, you can write
```ts
(x.prop as HTMLImageElement).src = '...';
```
if you're sure the property hasn't changed.

In the `master` branch, we'll detect type guard on properties as well:
```ts
// OK in master
if (x.prop instanceof HTMLImageElement) {
  x.prop.src = '...';
}
```
