### ISSUE TITLE
Support for shorthand `module/module` resolution?

### ISSUE THREAD

**Issue by adambuczynski** [Microsoft/TypeScript#9307]
As my applications grow in size I start placing components in sub folders. Simplified:

```
app
  |_ components
    |_  app
      |_ header
        |_ header.ts
        |_ header.html
      |_ sidebar
        |_ sidebar.ts
        |_ sidebar.html
      |_ app.ts
      |_ app.html
```

If I want to import the `sidebar` or `header` components from the `app` component, I currently have to do:

```ts
import { HeaderComponent } from './header/header';
import { SidebarComponent } from './sidebar/sidebar';
```

As you can see this gets a bit repetitive, and I'd prefer to simply use:

```ts
import { HeaderComponent } from './header';
import { SidebarComponent } from './sidebar';
```

If the typescript module resolver is smart enough to look for an `index.ts` file in the `header` subfolder in these cases, could we add a rule to also have it look for a file which is the same name as the folder, or would that conflict with other resolve rules?

The reason I don't want to rename my files to `index.ts` within the subfolders is because it makes jumping to those files and keeping track of which one is which when you have several `index.ts` files open a hassle.

Alternatively, would it possible to accomplish this by using the new `paths` and `baseDir` resolution scheme?

**Comment by DanielRosenwasser** [comment]
If you're using Node-style resolution (e.g. CommonJS), then you should be able to rename each of those `index.ts` at the top level and import them the way you'd like. Does that solve your problem?

**Comment by adambuczynski** [comment]
Hi @DanielRosenwasser , thanks for the quick reply.

I am using `"moduleResolution": "node",`, but it doesn't seem to be working as I get errors `Cannot find module app/header`

**Comment by aluanhaddad** [comment]
@adambuczynski I usually use the re-export pattern to solve this particular problem. So my `components` folder would contain a file with the contents
```TypeScript
export * from './app';
export * from 'app/header';
export * from 'app/sidebar';
```

**Comment by adambuczynski** [comment]
@aluanhaddad thanks for the suggestion. That would work well for nested shared components, I'll give that approach a try.

However, for my particular usecase where I only need the header and sidebar components from within the app component it seems like overkill.

**Comment by mhegazy** [comment]
Consider using path mapping for module resolution added in TS 2.0, see https://github.com/Microsoft/TypeScript/wiki/What%27s-new-in-TypeScript#path-mapping for more details.
