### ISSUE TITLE
throwing error while using nodejs packages

### ISSUE THREAD

**Issue by NikosEfthias** [Microsoft/TypeScript#9308]
**TypeScript Version:** 

1.8.10
```ts
import {params} from "scrypt";
```
**Expected  behavior:**
since scrypt is already in node_modules compile with no error
**Actual behavior:** 
throws error saying cannot find module seems like i cannot use typescript for nodejs development
![](http://i.imgur.com/TBiOPeO.png)
![](http://i.imgur.com/n3vRyrW.png)

**Comment by kitsonk** [comment]
By default, TypeScript does not magically understand random NodeJS packages.  [It needs information to describe it so you can consume it](http://www.typescriptlang.org/docs/handbook/typings-for-npm-packages.html).  `scrypt` does not provide that information in its package.  Either you have to provide it yourself, or you have to obtain it from somewhere (potentially using a tool like [`typings/typings`](https://github.com/typings/typings/) or on [DefinitelyTyped](http://definitelytyped.org/)).

**Comment by NikosEfthias** [comment]
@kitsonk i tried to export an interface from a file called scrypt.d.ts and referenced it but still the same problem its behaving like the interface is not referenced 
the scrypt.d.ts file content is as follows
```ts
//scrypt.d.ts
	export interface paramsObject extends Object{
		n: number;
		r: number;
		p: number;
	}
export interface scrypt{
	params(maxtime: number, maxmem?: number, maxmemfrac?: number):Promise<paramsObject>;
	paramsSync(maxtime: number, maxmem?: number, maxmemfrac?: number):paramsObject;
	kdf(key:string,paramsObject):Promise<Buffer>;
	kdf(key:Buffer,paramsObject):Promise<Buffer>;
	kdfSync(key:Buffer,paramsObject):Buffer;
	kdfSync(key:Buffer,paramsObject):Buffer;
	verifyKdf(encryptedPass:Buffer,password:string):Promise<Boolean>;
	verifyKdfSync(encryptedPass:Buffer,password:string):Boolean;
}
```
and in my actual file that i use scrypt i reference it by using tripple slash 
`/// <reference path="./scrypt/scrypt.d.ts" />`
but no use it still says module is not found

**Comment by mhegazy** [comment]
This would work if you imported it using relative path, e.g. `import d from "./scrypt"`, which is not the case.  you want to put the module name, "scrypt" in the global. so:

```ts
//scrypt.d.ts
declare module "scrypt" {
	export interface paramsObject extends Object {
		n: number;
		r: number;
		p: number;
	}
	export function params(maxtime: number, maxmem?: number, maxmemfrac?: number): Promise<paramsObject>;
	export function paramsSync(maxtime: number, maxmem?: number, maxmemfrac?: number): paramsObject;
	export function kdf(key: string, paramsObject): Promise<Buffer>;
	export function kdf(key: Buffer, paramsObject): Promise<Buffer>;
	export function kdfSync(key: Buffer, paramsObject): Buffer;
	export function kdfSync(key: Buffer, paramsObject): Buffer;
	export function verifyKdf(encryptedPass: Buffer, password: string): Promise<Boolean>;
	export function verifyKdfSync(encryptedPass: Buffer, password: string): Boolean;
}
```

also consider submitting a PR to definitely typed for this library: https://github.com/DefinitelyTyped/DefinitelyTyped/

**Comment by NikosEfthias** [comment]
@mhegazy thank you for help it clarifies everything :)
