### ISSUE TITLE
Should syntax like `+someVariable` be allowed by itself?

### ISSUE THREAD

**Issue by chrismbarr** [Microsoft/TypeScript#9311]
**TypeScript Version:**  1.8.10

I've seen some developers at my organization do something like the following *(usually a typo)*

```ts
var num = 4;
var demo = +num;
console.log(demo); //4
```

Writing `+num` seems like it should not be valid syntax by itself, although it is allowed in plain JavaScript.  Either way it really does nothing except look strange as far as I can tell.

I can't really think of a valid reason why syntax like this should be allowed, but I'd be curious to hear if anyone knows reasons why it should.

**Comment by kitsonk** [comment]
It is a form of *valid* implicit coercion:

```javascript
const four = 4;
const a = +four;
const b = +false;
const c = +'4';
console.log(a, b, c); // 4, 0, 4
console.log(typeof a, typeof b, typeof c); // number, number, number
```

So not in all cases would it be an error.  This sort of thing is usually addressed best by a linter (e.g. `tslint`) instead of "breaking" the JavaScript compatibility in TypeScript.

**Comment by chrismbarr** [comment]
ah ok, I was not aware of that. I suppose I've only seen it used "improperly" then
