### ISSUE TITLE
Importing a module to reference in a d.ts silently fails a declaration

### ISSUE THREAD

**Issue by nevir** [Microsoft/TypeScript#9313]
**TypeScript Version:** nightly (1.9.0-dev.20160217), also 1.8.10

**Code**

`tsconfig.json`:
```json
{
  "compilerOptions": {
    "charset": "utf-8",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": [
      "es5"
    ],
    "module": "commonjs",
    "newLine": "LF",
    "outDir": "dist",
    "pretty": true,
    "sourceMap": true,
    "target": "es2015"
  },
  "include": [
    "src/**/*.ts",
    "typings/**/*.ts"
  ]
}
```

I am attempting to declare Bluebird as my global promise implementation.  I have typings for the bluebird _module_ installed via `typings`.

`typings/custom/global-bluebird.d.ts`:
```ts
import Bluebird = require('bluebird');
declare var Promise:typeof Bluebird;
```

`src/test.ts`:
```ts
Promise.resolve();
```

When compiling, I have no errors on `global-bluebird.d.ts`, but I see `TS2304: Cannot find name 'Promise'.` when referencing `Promise`.

---

Interestingly, it seems to be the `import` statement that blows it up.  The following compiles as expected:

`typings/custom/global-bluebird.d.ts`:
```ts
declare class Promise {
  static resolve():void;
}
```

However, if I import bluebird (and do nothing with it!):

`typings/custom/global-bluebird.d.ts`:
```ts
import Bluebird = require('bluebird');

declare class Promise {
  static resolve():void;
}
```

It fails again with `error TS2304: Cannot find name 'Promise'.`  This seems to be true no matter what I import.

It also occurs if I explicitly add a reference to the Bluebird typings via `/// <reference path="../modules/bluebird/index.d.ts" />`

**Comment by vladima** [comment]
`import` statement makes the file an external module which means that `Promise` is declared and visible only inside this module
```ts
import Bluebird = require('bluebird');
declare var Promise:typeof Bluebird;
```

If you want to declare that module changes the global scope you can use [global augmentations](https://github.com/Microsoft/TypeScript/wiki/What%27s-new-in-TypeScript#augmenting-globalmodule-scope-from-modules):
```ts
import Bluebird = require('bluebird');
declare global {
    var Promise:typeof Bluebird;
}
```

**Comment by nevir** [comment]
Aha, thanks!
