### ISSUE TITLE
Not sure how to contact @types people - But `express-serve-static-core` is broken and breaking builds

### ISSUE THREAD

**Issue by dsifford** [Microsoft/TypeScript#9315]
Sorry for this, but I've attempted to troubleshoot for the last 2 hours without any luck.

**TypeScript Version:** 

1.7.5 / 1.8.0-beta / nightly (1.9.0-dev.20160217)

**Expected behavior:**
`@types/express-serve-static-core` to work correctly.

**Actual behavior:** 
`@types/express-serve-static-core` does not work.

Message: `[....]express-serve-static-core/index.d.ts is not a module. Please contact blah blah blah...`

**Comment by DanielRosenwasser** [comment]
That is an old nightly. Can you try a more up-to-date one?

**Comment by dsifford** [comment]
Of note, it works perfectly fine using `typings`.

@DanielRosenwasser Sorry, figured the prefilled version was the latest one. This is the version I'm currently using: `^1.9.0-dev.20160622-1.0`

**Comment by mhegazy** [comment]
@RyanCavanaugh can you take a look.

**Comment by dsifford** [comment]
@DanielRosenwasser @mhegazy Hold off on prioritizing this for a sec.. I think I have an idea why this might be happening. Let me try and report back.

**Comment by dsifford** [comment]
@DanielRosenwasser Disregard -- Mistake on my end. 

Using `atom-typescript` and I just assumed the built-in compiler used the globally installed typescript version I have installed (it doesn't). Changed the options to use the latest build and voila!

Sorry for stirring this up for no reason! I appreciate the help either way 👍 Thanks again.
