### ISSUE TITLE
importing JavaScript containing JsDoc comments

### ISSUE THREAD

**Issue by tamird** [Microsoft/TypeScript#9317]
I've been trawling the repository and wiki for information regarding how to import commonjs modules (specifically, those generated by [`protoc`'s javascript code generator](https://github.com/google/protobuf/tree/master/js)) into a typescript file.

In particular, these generated files have JsDoc comments such as:
```javascript
/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.cockroach.server.serverpb.ClusterFreezeResponse.prototype.serializeBinary = function() {
...
}
```

As you might imagine, typescript definitions are not generated. Here's where things get confusing: the wiki page https://github.com/Microsoft/TypeScript/wiki/JsDoc-support-in-JavaScript claims that typescript supports gathering type information from some forms of JsDoc comments, but it seems to be impossible to import these commonjs modules without first writing some definitions for them (which ISTM would trample the JsDoc type information).

Does anyone have an example (or even instructions) on how this is meant to work? @RyanCavanaugh you seem to have worked on some of this - do you have an insights?

**Comment by mhegazy** [comment]
this should be handled by https://github.com/Microsoft/TypeScript/pull/7075

**Comment by tamird** [comment]
@mhegazy now that #7075 is in, how does it handle this? In other words, what's the expected syntax to make this work?

**Comment by mhegazy** [comment]
Fixed by https://github.com/Microsoft/TypeScript/pull/7075

**Comment by tamird** [comment]
@mhegazy can you respond to my previous comment? Simply closing the issue isn't helpful.

**Comment by mhegazy** [comment]
I am assuming you are using this file as a module and importing it into a different file and you are not seeing the type information, correct? if so, then #7075 fixes this by loading the .js files from a node package. previously only .d.ts files are loaded, and if none is provided no type information is loaded from a node package.
