### ISSUE TITLE
Visual Studio 2015 Update 2 stops compiling TS files if tsconfig.json (not resolved by fixes in #3949)

### ISSUE THREAD

**Issue by sumitkm** [Microsoft/TypeScript#9318]
**TypeScript Version:** 

1.8.x

**Steps**
1. Create new TypeScript HTML project
2. Make changes to app.ts, save, js file generated as expected
3. Add tsconfig.json
```
{
  "compilerOptions": {
    "module": "amd",
    "target": "es5",
    "noImplicitAny": false,
    "sourceMap": false
  },
  "exclude": [
    "node_modules"
  ]
}
```
4. Make changes to app.ts no JS file generated
5. Open command prompt at Project folder, run ```tsc``` (installed via npm), JS is generated again.
6. Run ```tsc -w``` on command prompt, make changes to app.ts and save, works!

Visual Studio Options
![vs-2015-version-details](https://cloud.githubusercontent.com/assets/578882/16285584/efb03ce8-38ce-11e6-87db-5058610c65f5.png)
![vs-2015-options](https://cloud.githubusercontent.com/assets/578882/16285583/efabaeda-38ce-11e6-986f-9628689ecd39.png)

**Comment by mhegazy** [comment]
You need to set `"compileOnSave"` in your tsconfig.json, see http://www.typescriptlang.org/docs/handbook/tsconfig-json.html#compileonsave

**Comment by sumitkm** [comment]
No dice with the version of TypeScript + Visual Studio I have!

```
{
  "compileOnSave": true,
  "compilerOptions": {
    "module": "amd",
    "target": "es5",
    "noImplicitAny": false,
    "sourceMap": false
  },
  "exclude": [
    "node_modules"
  ]
}

```

How can I tell if Visual Studio 2015 has version 1.8.4 ? Node JS says it is 1.8.1 and the above dialog says TypeScript tools version, 1.8.31.0 (?). This machine was setup last week.

**Comment by mhegazy** [comment]
`tsc --v` will tell you the version of the compiler. in this case it is `1.8.10`.

the version of the VS plugin can be different, as we ship multiple VS plugins, e.g. 1.8.10 for VS Update 1, and 1.8.10 for VS Update 2, and ow VS Update 3. no changes to the compiler or the language, but there are changes to the plugin. 1.8.31 is what i would expect. so you have the latest.

**Comment by yuit** [comment]
@sumitkm confirmed with @paulvanbrenk  this is a bug. We fixed this in Update3

**Comment by sumitkm** [comment]
@yuit Thanks for confirming. Is it in the current RC? I'll usually wait for RTMs to stabilize before I get to updates, but might make an exception for this one...

**Comment by mhegazy** [comment]
RC still has this issue. it should be fixed in the RTM though.

**Comment by vsanat** [comment]
just add new .ts file to your project and save. This will start it working again. This did for me.
