### ISSUE TITLE
Suggestion: generic default

### ISSUE THREAD

**Issue by unional** [Microsoft/TypeScript#9321]
Currently when using a generic and the type cannot be inferred, it fallbacks to `{}`. It would be nice if we can specify it. e.g.:

```ts
interface generic<T extends Anything default any> { ... }
interface generic<T extends Anything default {}> { ... }
interface generic<T extends Anything default SubClassOfAnything> { ... }
```

🌷 

EDIT: I recall there is an issue that complaint about it fallback to `<{}>` but I can't find it.

**Comment by mhegazy** [comment]
Duplicate of https://github.com/Microsoft/TypeScript/issues/2175
