### ISSUE TITLE
Property Math is missing on Window interface

### ISSUE THREAD

**Issue by zuzusik** [Microsoft/TypeScript#9325]
**TypeScript Version:**  

1.8.10

**Code**

```ts
window.Math.round(1.35);
```

**Expected behavior:**
compiled

**Actual behavior:** 
error TS2339: Property 'Math' does not exist on type 'Window'

**PS**: `Math.round(1.35)` works as expected, but I want to access it from `window` in order to be able to mock this method in Angular unit tests by mocking `$window` service.

**Comment by mhegazy** [comment]
The standard library does not support using Window as the global polluter. i.e. adding members on Window are not reflected on the global and adding members on the global are not reflected on Window. The rational is to limit the ways a construct is accessible, and generally accessing global through window is not recommended.

if you want to expose `Math`, or any other declaration on `window`, you can augment the `Window` interface:

```ts
interface Window {
    Math: typeof Math;
}
```
