### ISSUE TITLE
Equivalent of babel-plugin-react-html-attrs

### ISSUE THREAD

**Issue by tkrotoff** [Microsoft/TypeScript#9327]
When using React and .tsx, keywords [`class` and `for` should be replaced by `className` and `htmlFor`](https://facebook.github.io/react/docs/jsx-in-depth.html#html-tags-vs.-react-components).

Babel features a [plugin](https://github.com/insin/babel-plugin-react-html-attrs) that allows the keywords `class` and `for`. Advantages:
- shorter and proper syntax
- make it easy to copy-paste HTML from documentation or examples

Would be nice to have the same feature with TypeScript.

Note: currently when writing `class` instead of `className`, no error is given: the resulting HTML silently remove any `class` attribute.

Related to #6843, #5595

**Comment by aluanhaddad** [comment]
Seems like this should be a static error.

**Comment by RyanCavanaugh** [comment]
We're not really in the "I guess you really meant `x`" business. Someone can write a gulp-ts plugin or whatnot.
