### ISSUE TITLE
Generic constraints are not transitive with polymorphic this

### ISSUE THREAD

**Issue by Christoph-D** [Microsoft/TypeScript#9328]
**TypeScript Version:** 

1.8.9

**Code**

```ts
class A { foo() { return this; } }
class B extends A {}
class C<T extends A> {}
class D<T extends B> extends C<T> {}
```

**Expected behavior:**
No errors.

**Actual behavior:** 
Error on the line defining class D:
```
error TS2344: Type 'T' does not satisfy the constraint 'A'.
  Type 'B' is not assignable to type 'A'.
    Types of property 'foo' are incompatible.
      Type '() => B' is not assignable to type '() => T'.
        Type 'B' is not assignable to type 'T'.
```
It seems to me that T should satisfy the constraint 'A' by transitivity because T extends B and B extends A.

**Comment by aluanhaddad** [comment]
This is not in that version. You need to use a dev build.
`npm i -g typescript@next`

**Comment by sandersn** [comment]
Yep, this is fixed in `typescript@next`.
