### ISSUE TITLE
Select .options attribute should be an HTMLOptionsCollection

### ISSUE THREAD

**Issue by jasongrout** [Microsoft/TypeScript#9334]
**TypeScript Version:** 

1.9.0-dev (commit be6c34f1c79ec998c56ae127e572ffa9d7794b51)

**Description**

In https://github.com/Microsoft/TypeScript/blob/be6c34f1c79ec998c56ae127e572ffa9d7794b51/lib/lib.dom.d.ts#L6797, `.options` should be an HTMLOptionsCollection, which would have typed add/remove methods. We have an HTMLOptionsCollection defined at https://github.com/Microsoft/TypeScript/blob/be6c34f1c79ec998c56ae127e572ffa9d7794b51/lib/lib.dom.d.ts#L6633, but I think it should probably inherit from `HTMLCollectionOf<HTMLOptionElement>` (possibly unioned with an optgroup type too) for the typed index accessors, etc.

Also, HTMLOptionsCollection shouldn't have a `selectedIndex: number;` attribute according to the spec at https://www.w3.org/TR/2011/WD-html5-20110525/common-dom-interfaces.html#htmloptionscollection-0

**Code**

``` ts
// A self-contained demonstration of the problem follows...
document.createElement('select').options
```

cf. https://github.com/Microsoft/TypeScript/issues/8220

**Comment by mhegazy** [comment]
I am not sure i understand why this changed but, https://github.com/Microsoft/TypeScript/commit/9a55facfe3c1dce852e4192c37d54739e2524638 should show the fixed definition.

**Comment by mhegazy** [comment]
should be in typescript@next later tonight.

**Comment by mhegazy** [comment]
> Also, HTMLOptionsCollection shouldn't have a selectedIndex: number; attribute according to the spec at https://www.w3.org/TR/2011/WD-html5-20110525/common-dom-interfaces.html#htmloptionscollection-0

I am a bit confused:

from https://www.w3.org/TR/2011/WD-html5-20110525/common-dom-interfaces.html#htmloptionscollection-0

```idl
interface HTMLOptionsCollection : HTMLCollection {
  // inherits item()
  attribute unsigned long length; // overrides inherited length
  caller getter object namedItem(in DOMString name); // overrides inherited namedItem()
  void add(in HTMLElement element, in optional HTMLElement before);
  void add(in HTMLElement element, in long before);
  void remove(in long index);
  attribute long selectedIndex;
};
```

from lib.d.ts:

```ts
interface HTMLOptionsCollection extends HTMLCollectionOf<HTMLOptionElement> {
    length: number;
    selectedIndex: number;
    add(element: HTMLOptionElement | HTMLOptGroupElement, before?: HTMLElement | number): void;
    remove(index: number): void;
}
```

and both has `selectedIndex`.

**Comment by jasongrout** [comment]
> and both has selectedIndex.

You're right! My mistake.

Should HTMLOptionsCollection extend `HTMLCollectionOf<HTMLOptionElement | HTMLOptGroupElement>` to account for optgroup elements? (I'm not sure if `.options` will list option group elements alongside option elements).

**Comment by jasongrout** [comment]
Thanks for the fast response on this!

**Comment by mhegazy** [comment]
Can you explain why you think it should be a union?

**Comment by aluanhaddad** [comment]
I suppose it is because both types are valid elements in the collection, but neither is declared as a subtype of the other. Actually, the instance side of both types is identical, but this is not clear from reading their definitions. 
```TypeScript
var x: HTMLOptGroupElement;
var y: HTMLOptionElement = x;
x = y;
```
is perfectly valid, but they are not explicitly related. A union would be clearer, but it would not affect typing.
