### ISSUE TITLE
String Literal Types  and inference

### ISSUE THREAD

**Issue by wallverb** [Microsoft/TypeScript#9336]
Sorry if duplicate - couldn't find it.

**TypeScript Version:** 

1.8

**Code**

```ts
interface TextStyle {
	align: 'center' | 'left'
}

function test(style:TextStyle) {
	
}

// works fine
test({align: 'center'})

let style = {
	align: 'center'
}

// does not work: 'string' not assignable to 'center' | 'left'
test(style)
```

**Expected behavior:**

Second call `test(style)` should work

**Actual behavior:** 

Error: Type string is not assignable to type 'center' | 'left'

Maybe typescript when seeing `let style = {align: 'center'}` should infer type as `{align: string } | {align: 'center'}`

**Comment by mhegazy** [comment]
String literal types are not inferred by default. you have to give a hint to the compiler that you want one of them inferred. so 

```ts
let style : TextStyle = {
    align: 'center'
}
```

the type annotation would tell the compiler that `center` should be of type `center` and not the more general type `string`.

inferring the literal string all the time would be a breaking change, for instance:
```ts
cosnt defaultAlignement = "center";
let alignement = defaultAlighment;
if (condition) {
    alignement = "left"; 
}
```

**Comment by wallverb** [comment]
Right, that's what I thought, although I was hoping that maybe it could be done on that declaration level only. like `const defaultAlignement = "center";` and `alignement` would become `string | 'center'` and then the condition assignement would still work and my case would be handled.

The use case I'm looking for is for example using styles with React Native,

their default example:
```
const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: "center",
    margin: 10,
  });

// ....

    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>
//...
```

will not work because it will scream that `textAlign` (inferred as string) but declared with `'center'` cannot be assigned to `'center' | 'left' | 'right'`.   I would need to cast each style class object with proper type definition eg.
```
const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  } as ReactNative.ViewStyle,
  welcome: {
    fontSize: 20,
    textAlign: "center",
    margin: 10,
  } as ReactNative.TextStyle,

```

of course possible to do - but pretty painful to do it every time :)

**Comment by DanielRosenwasser** [comment]
We've discussed elsewhere that a syntax that triggers more specific types to be inferred would be ideal, but we try to avoid new expression-level syntax.

**Comment by moglodek** [comment]
I understand, thanks for the info

**Comment by wallverb** [comment]
Understood, thanks for the info.
Tried to find that discussion but no luck.

That's probably not a new syntax but would it be breaking change if `let a = 'center'` would be inferred as `'center'` string literal while `let b = "center"` would be inferred as string (`'` vs `"`). Seems like it wouldn't break existing code but maybe I'm missing something.
