### ISSUE TITLE
Error with strictNullChecks when nested function

### ISSUE THREAD

**Issue by horiuchi** [Microsoft/TypeScript#9345]
**TypeScript Version:** 

Version 1.9.0-dev.20160624-1.0

**Code**

`test.ts`
```ts
function g(cb: () => Promise<boolean>): Promise<boolean> {
    return cb();
}
function f(a: string | null): Promise<boolean> {
    if (a === null) {
        return Promise.resolve(false);
    }
    return g(() => {
        console.log(a.substr(1));
        return Promise.resolve(true);
    });
}
```

execute the command `tsc --target es2015 --module commonjs --strictNullChecks test.ts`.

**Expected behavior:**

There is no compile error.

**Actual behavior:** 

`test.ts(9,21): error TS2531: Object is possibly 'null'.`

**Comment by kitsonk** [comment]
Essentially duplicate of #9263 and #7662 as narrowing is reset across function boundaries as explained in [#7718 (comment)](https://github.com/Microsoft/TypeScript/issues/7719#issuecomment-202684512).

**Comment by horiuchi** [comment]
OK, I understand 👍
