### ISSUE TITLE
Pattern for define type of class extends an abstract class.

### ISSUE THREAD

**Issue by Thomas-P** [Microsoft/TypeScript#9347]
Hi,

I am looking for a pattern that allows me to create a command pattern object from an classes that extends from an abstract class. The abstract class have some helper method and implement the default values for the properties defined in an interface. 
This type of ATest (see below) should the base element, because the getValue method will declared in the classes that extends ATest.
So the question is if there is a proper sollution or a way to define an interface, contain a bunch of classes, that extends an abstract?
```TypeScript
// a base interface that spec the properties
interface ITest {
	value: string;
	getValue(): string;
}

// abstract class that implements helper methods
abstract class ATest implements ITest {
	value: string = 'new String';
	abstract getValue(): string;
	constructor() {
		// create default value pattern
	}
	
	protected helper(num: number): string {
		return String(num);
	}
}

// implementing class
class Test extends ATest {
	constructor() {
		super();
	}
	
	getValue(): string {
		return this.value;
	}
	
	getNumVal(num: number) {
		return this.helper(num);
	}
}

// this should implement the command pattern
// how can this a class that extends from the abstract class ATest?
interface ICommandTest {
	[name: string]: typeof ATest;
}



var commandObject: ICommandTest = {};
commandObject['test'] = Test;
// Does not work
//let Cmd: typeof Test = commandObject['test'];
let Cmd = commandObject['test'];
let test = new Cmd();
```

**Comment by aluanhaddad** [comment]
I think you are looking for 
```TypeScript
interface ICommandTest {
    [name: string]: ATest;
}
```
when you write `typeof ATest`, you are getting the class from whence an instance was created (more or less).

**Comment by aluanhaddad** [comment]
Consider
```TypeScript
type T = typeof Date;
```
T is the type `DateConstructor`.

**Comment by Thomas-P** [comment]
Hi, 
I want to get the class explicitly passed and call the constructor in the method. Otherwise I head to use the factory way.

**Comment by aluanhaddad** [comment]
OK, I missed that requirement. This can still be done by declaring the type returned by the index signature to be a constructor function which returns a type derived from `ATest` 
```TypeScript
    [name: string]: new () => ATest;
```

**Comment by RyanCavanaugh** [comment]
`[name: string]: new () => ATest;` indeed looks like the right declaration here.
