### ISSUE TITLE
Signature help for optional members uses superfluous bracketing

### ISSUE THREAD

**Issue by danquirk** [microsoft/TypeScript#935]
The new signature help is showing optional arguments with [x?: string] rather than just using the question mark like in the past. The brackets are entirely superfluous, it's just visual noise.

**Comment by Andarist** [comment]
This is rather an ancient issue, can't repro it in the oldest TS version that is available in the TS playground ([TS 3.3 playground](https://www.typescriptlang.org/play?ts=3.3.3#code/GYVwdgxgLglg9mABFApgZygCgIYC5FggC2ARigE4A0iJA-PhuTGAOYCUiA3gL4BQvqDDmpsgA)), cc @jakebailey
