### ISSUE TITLE
nullability of getAttribute / setAttribute APIs in lib.d.ts

### ISSUE THREAD

**Issue by rkirov** [Microsoft/TypeScript#9350]
**TypeScript Version:** 

nightly (1.9.0-dev.20160217)

**Code**
The following code does not typecheck
```ts
el1.setAttribute('foo', el2.getAttribute('foo'));
```
because `getAttribute` returns `string | null`, and setAttribute expects `string`. If would be convenient if lib.d.ts has a matching signature on the get/set pair, to avoid users having to write an explicit null check.

The two options are both types being `string | null` or both being `string`. I can see arguments for either.

According to https://www.w3.org/TR/2004/REC-DOM-Level-3-Core-20040407/core.html#ID-666EE0F9 correctly getAttribute returns empty string for missing attrs, which is a strong argument for `string`. 

The spec does not talk about nullabilty in setAttribute, but my tests a few browsers show that also `null` is an accepted value by the runtime. This would be an argument in favor of `string | null`.

**Comment by aluanhaddad** [comment]
I think it needs to be the former since `getAttribute` will return null if there is no matching attribute.

**Comment by rkirov** [comment]
Indeed, the spec says

> The Attr value as a string, or the empty string if that attribute does not have a specified or default value.

but of course looks like all browsers just return `null`.

**Comment by aluanhaddad** [comment]
Interesting. It looks like the spec needs to be brought in line with reality.

**Comment by mhegazy** [comment]
PRs would be appreciated. i would make make them both accept `null`. seems conservative but still convenient.

**Comment by mhegazy** [comment]
You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.

**Comment by YuichiNukiyama** [comment]
According to [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Element/setAttribute#Notes), `setAttribute` method accept `null`. But, this isn't remove attribute. whereas this will coerce the null value to the string `"null"`.  Isn't this confused developers?

**Comment by weswigham** [comment]
@YuichiNukiyama It falls out from the string coercion rules as `'' + null === 'null'`.

**Comment by rkirov** [comment]
pretty good argument for keeping it as is. Setting attributes to `'null'` is probably not what developers want.
