### ISSUE TITLE
PropertyAccessExpression changed its structure

### ISSUE THREAD

**Issue by basarat** [Microsoft/TypeScript#9354]
It no longer has `dotToken` member. No biggie. I'm using the internal API (so there is no guarantee) + using it with TypeScript (so compile fails reliably :rose:). Was using this in *assert* style quick fixes e.g. https://github.com/TypeStrong/atom-typescript/blob/1163e05b11c42269623e11e7dcc3d4f32b68deae/lib/main/lang/fixmyts/quickFixes/typeAssertPropertyAccessToAny.ts#L30 

Just curious why it was changed :)

**Comment by RyanCavanaugh** [comment]
We're trying to reduce our memory consumption; not storing any tokens we could synthesize later saves a few bytes per expression

**Comment by mhegazy** [comment]
`Node.getChildern()` should still generate you the token, it is just not going to be a property on the tree by default.
