### ISSUE TITLE
TS2345 Argument of type A is not assignable to parameter of type A

### ISSUE THREAD

**Issue by CarsonF** [Microsoft/TypeScript#9358]
**TypeScript Version:** 

1.8.0

**Code**

```ts
declare function decorate<T>(): (component: T) => T;

class Foo {
  derp () {}
}

decorate<Foo>()(Foo);
```
```
error TS2345: Argument of type 'typeof Foo' is not assignable to parameter of type 'Foo'.
  Property 'derp' is missing in type 'typeof Foo'.
```
How can there be a type mismatch if it's the same type? 😖

**Comment by yortus** [comment]
Your `decorate<Foo>()` call returns a function that accepts and returns an *instance* of `Foo`, but then you pass it the *constructor function* `Foo`, which is not the same type, hence the error.

I'm not sure whether you mean to work with `Foo` instances or `Foo` constructors, but the following variants both pass type checks:

```ts
decorate<typeof Foo>()(Foo);  // Foo constructor
decorate<Foo>()(new Foo);  // Foo instance
```

**Comment by CarsonF** [comment]
@yortus Ahh thank you, that's what I was missing. 

Thank you @blakeembrey as well :)
