### ISSUE TITLE
Suggestion: preserve both static and instance sides of class types when class is used in value position

### ISSUE THREAD

**Issue by jwbay** [Microsoft/TypeScript#9359]
Following up on #9358 and #6543. It hasn't stopped bothering me that generic identity functions don't exactly return their incoming types when it comes to classes.

```ts
declare function decorate<T>(Class: T): T;

class Foo {
	static bar = 42;
	baz () {}
}

//full type information seems present...
const DecoratedFoo = decorate(Foo);
DecoratedFoo.bar === 42; //ok
new DecoratedFoo().baz(); //ok

//but the instance side has been dropped from the DecoratedFoo type
let fooConstructor: typeof Foo; //ok
let foo: Foo; //ok
let decoratedFooConstructor: typeof DecoratedFoo; //ok
let decoratedFoo: DecoratedFoo; //error: cannot find name 'DecoratedFoo'
```

Would it be possible for `decorate(Foo)`'s return type to be `class Foo`, or something equivalent, instead of `typeof Foo`? It's an identity function; I'm trying to tell TypeScript that whatever I'm doing to the class, if anything, is invisible to the caller. The workaround in #6543 is a bit unfortunate in that it places the burden of the aliasing/merging on each and every caller instead of in the function that's doing the work.

**Edit**: Simpler repro, looks like it has nothing to do with identity functions and everything to do with a class  being assigned to a value, whether via local alias or passed as argument. Would just like a class to stay a class everywhere it goes :)

```ts
class Foo { }
const Bar = Foo;
let bar: Bar; //error: cannot find name 'Bar'
```

**Comment by aluanhaddad** [comment]
```TypeScript
let decoratedFoo: DecoratedFoo; //error: cannot find name 'DecoratedFoo'
```
Because `DecoratedFoo` is just a value. you need to obtain it's type to use it in type position.

**Comment by jwbay** [comment]
> Because DecoratedFoo is just a value. you need to obtain it's type to use it in type position.
Right, that's the current limitation. You can't get to or preserve the instance type of a class once it enters a function as an argument; it's a bit of a black hole. I'd like to see that limitation lifted somehow.

**Comment by aluanhaddad** [comment]
@jwbay I see, and I've since read the linked issues. It's not clear what the best way to do this would be because implicitly introducing a name into the type space is problematic. Mixing the static and instance types into a single parameter type is kind of complicated because classes represent multiple types. 

I recently trying to write a better declaration for dojo/lang/mixin and had a very frustrating experience. Because the function takes a single argument which is an object literal which represents a class was static and instance members using member names as conventions for what should go where. I realize that is the slightly off topic.

**Comment by aleksey-bykov** [comment]
by the definition of the identity function the result is always of the type of its argument, if so then you don't need to call it to get the type, because you got the type already before you called it

problem is that it is not and identity function, it's a transformation from T to another U, but then why is it called identity?

**Comment by aluanhaddad** [comment]
@jwbay I don't see why one would expect
```typescript
const DecoratedFoo = decorate(Foo);
```
to create a new manifest type. It doesn't make sense.

@aleksey-bykov I'm not entirely sure what you mean but I think you're saying the identity operation is lossy when applied to a class. Classes have a weird asymmetry.

**Comment by jwbay** [comment]
@aleksey-bykov I'm very likely using the term 'identity function' incorrectly, sorry for the confusion. What I was trying to say, very poorly, was this

>I'm trying to tell TypeScript that whatever I'm doing to the class, if anything, is invisible to the caller

@aluanhaddad I would disagree. If Foo has a type meaning attached to it, then it seems to me that applying X => X to it should carry the type to the result.

It might come down to the `class` keyword being painfully special since it creates both a value and a type.

**Comment by aluanhaddad** [comment]
@jwbay binding to a variable binds a value and a type but the variable does _not_ itself represent the type in the same way that it represents the value. We say that the variable refers to a value of a type but it does not exist in type space as an identifier and it does not represent the type itself.

Part of the confusion is indeed the special nature of the `class` keyword. It actually declares a value and _two_ types. The type having the name of the class is the type of the instances which result from instantiating it, while the type of the class itself is the type of the implicit variable to which it is bound.
I think it also comes from the notion that in most other languages, the object of the `new` operator is a type but in JavaScript it is a value.

**Comment by jwbay** [comment]
@aluanhaddad Right, I suppose what I'm asking for is essentially for types to follow values around into new bindings. I feel like the behavior of the simpler repro in the OP is especially counter-intuitive (to anyone like myself who's not familiar with the intricacies of the type system :sweat_smile:). It's a local alias, so I would expect to be able to use Bar in exactly the same way I use Foo.

(Obviously the fix for the small repro is to add `type Bar = Foo`, but that breaks down a bit at scale as noted right above it)

**Comment by aluanhaddad** [comment]
@jwbay that does make sense laundry clay, but I can't see it making sense syntactically without a new kind of declaration. Something along the lines of
```TypeScript
class Bar = decorate(Foo);
```
But there are conceptual problems with this beyond the simple introduction of an additional declarator, and I'm not convinced the use cases are sufficiently broad given all of the available workarounds. That said, something like this would be reasonable.

**Comment by benjamin-hg** [comment]
I recently was wondering about this:

~~~ .ts
class A {}

var B = A;

class C extends B {} // OK

var c:C; // OK
var b:B; // Error: cannot find name 'B'
~~~

Does this make any sense?

**Comment by aleksey-bykov** [comment]
@benjamin-hg 

yes once you did this:
```
var B = A;
```
you lost type-side of `A` and left alone with a value-side of it only

**Comment by benjamin-hg** [comment]
@aleksey-bykov 
But successfully using `C extends B ` doesn't make B look like it has lost its type-side.

Let's extend the example:

~~~ .ts
class A {
	propOfA:string;
}

var B = A;

class C extends B { // OK
	propOfC:string;
} 

var c:C; // OK
c.propOfC; // OK
c.propOfA; // OK! The type information must have been transferred through variable B
var b:B; // Error: cannot find name 'B'
~~~

Maybe I don't understand the concept of type-side and value-side, but I didn't find so much on it on the internet so far. Can you point me to a resource where this is explained?

**Comment by aleksey-bykov** [comment]
@benjamin-hg I might be wrong myself, this is how I understand this problem:

TypeScript has 2 lookups for a given scope:
- for values: name <-> value and its type
- for types: name <-> type only

Classes in TypeScript a hybrids of a value-side and a type-side so they are registered in both lookups.

When you do `var B = A;` it gets gets saved to a values-lookup (because of `var`), but not into types-lookup. Note that it is saved with its type information.

Now, later when you declare 

```
var b: B;
```

we only check the type-lookup and we don't find an entry for `B` there

Now, when you do `class C extends B`, since `B` is a class (type + value) we go to the values lookup and this is where we find `B` and everything works.

Not saying it is right, just it is what it is.

**Comment by aleksey-bykov** [comment]
in order to pull the type information from a value-lookup you use the `typeof`operator:
```
var b: typeof B;
```

**Comment by aluanhaddad** [comment]
@aleksey-bykov that is a good explanation. I think what confuses people is that the _value_ side of a class is used in places where most other languages expect a _type_. Some examples are with `new`, with `instanceof`, and with `extends`. When the object of an `extends` clause is a class it looks like a _type_ is being extended when in fact it is a _value_. That the clause can be part of a class declaration which introduces a new type is incidental. I think a good way to illustrate this is with anonymous class expressions.

**Comment by benjamin-hg** [comment]
What got clear to me at least (and it took me some time): 
~~~ .ts
var B = A;
~~~
is the same as 
~~~ .ts
var B: typeof A;
~~~
(Assuming `A` is the name of a class)

**Comment by aleksey-bykov** [comment]
it's not the same:
```
var B = A; // transfers the type and the value of A to a value B, registring B in values
```

```
var B: typeof A // declares an uninitialized value B using only the type of A, also registring B in values
```

difference is that, although the following compiles, it won't run:
```
var B: typeof A;
class C extends B {}; // <-- unitialized value is used
```

whereas this one will:
```
var B = A;
class C extends B {}
```

**Comment by benjamin-hg** [comment]
@aleksey-bykov 
Right, that was not very precise. From an execution point of view, the statements are different. But I'm still pretty sure that form a typing point of view (which I had) `b` looks the same for the compiler in both cases. 
![image](https://cloud.githubusercontent.com/assets/10807766/16622596/fb700d84-439a-11e6-8a25-cb0a91c48e87.png)
(Tooltip for 'B' in the TypeScript Playground)

**Comment by aluanhaddad** [comment]
@benjamin-hg that is not correct
```TypeScript
var B = A;
```
 creates a mutable reference to the value `A`, which has the inferred type `typeof A`.
```TypeScript
var B: typeof A;
```
creates a mutable reference explicitly of the type `typeof A` with the value `undefined`.

Consider
```TypeScript
const B : typeof A; // error
```

**Comment by mhegazy** [comment]
Looks like the request here is a way to access the return type of a function and/or a constructor. If so, then this should be covered by the request in https://github.com/Microsoft/TypeScript/issues/6606

**Comment by jwbay** [comment]
@mhegazy I don't think it quite fits. The linked proposal would indeed let you get at the instance type with something like `typeof new A()`, but how would that then be joined with the static side type? I don't think there's a way to "reconstruct" what the class keyword gives you (value + static type + instance type) from its disparate pieces.

**Comment by DanielRosenwasser** [comment]
@jwbay weren't you already able to get the static side with `typeof A`?

**Comment by mhegazy** [comment]
But that is what a class is; a constructor function and an inststance type. That is how a lot of the built ins and Dom classes are defined anyways.

**Comment by aluanhaddad** [comment]
@mhegazy in the original example this fragment
```TypeScript
//full type information seems present...
const DecoratedFoo = decorate(Foo);
DecoratedFoo.bar === 42; //ok
new DecoratedFoo().baz(); //ok

//but the instance side has been dropped from the DecoratedFoo type
let fooConstructor: typeof Foo; //ok
let foo: Foo; //ok
let decoratedFooConstructor: typeof DecoratedFoo; //ok
let decoratedFoo: DecoratedFoo; //error: cannot find name 'DecoratedFoo'
```
The expectation was that the declaration, 
`const DecoratedFoo = decorate(Foo);` 
would introduce a new type, namely `DecoratedFoo` into the type space. Basically the expectation was that a class stored in a variable of a different name with introduce that variable's name itself into the type space as the instance type of invoking the variable with new.

**Comment by aluanhaddad** [comment]
The only assignment Target that I believe has this property is a module export. We have type assignments, and value level assignments, namespace level assignments, but no assignment target that combines all of their meanings outside of an export. Basically this is what it would allow for:
```typescript
var C = class {
    static staticMember;
    
    instanceMember;
};
var i :C;
if (blah) i = new C();
```

**Comment by mhegazy** [comment]
That is 'typeof new DecoratedFoo()'

**Comment by mhegazy** [comment]
Variables are not valid type names. Values are not types.

**Comment by aluanhaddad** [comment]
That was what I said in comment https://github.com/Microsoft/TypeScript/issues/9359#issuecomment-228604574 but that is what @jwbay is expecting.

**Comment by jwbay** [comment]
@mhegazy But a class name is a valid type name, and once a class passed somewhere as a value, it stops being a type. That's the stumbling block.

On a second look the enhanced typeof operator would be a suitable workaround for my use case, so I'll close.
