### ISSUE TITLE
Spell-checking of identifiers

### ISSUE THREAD

**Issue by robertknight** [Microsoft/TypeScript#936]
The [clang](http://clang.llvm.org/) C++ compiler has a useful feature where if an identifier is unknown, it will try to determine which identifier the user may have intended to use instead and then for the rest of the compile, assumes that the user did intend to use that identifier.

This often avoids the cascade of errors that happen when an identifier is misspelt, especially in scenarios where type inference means that the types of many other identifiers depend on the original.

For example:

````
var aPromise = getAPromies(); // oops, meant getAPromise()
aPromise.then((result) => { // cascading error because type of 'result' is unknown here
...
});
````

The clang output is something along the lines of:

````
Unknown method 'getAPromies()', did you mean 'getAPromise()'?
// remainder of errors are on the basis that the user did mean 'getAPromise()'
````

**Comment by mhegazy** [comment]
This is a linter feature and is out of scope of the TypeScript project.
