### ISSUE TITLE
Type assertion not working with string literal union types in classes

### ISSUE THREAD

**Issue by mirow** [Microsoft/TypeScript#9369]
If a class member is defined as a string literal union type, type assertion fails. If I change the type of `orgType` to `string` instead, the type assertion works as expected.
Any ideas how to circumvent this bug?

**TypeScript Version:** 
1.8.10

**Code**
```ts
declare class Organization {
  id: number;
  orgType: "school"|"company"|"branch";
  // lots of other properties here which are not optional
}
let org: Organization;
org = <Organization>{
  orgType: 'company'
};
```

**Expected behavior:**
No errors.
**Actual behavior:** 
`error TS2352: Neither type '{ orgType: "company"; }' nor type 'Organization' is assignable to the other. Property 'id' is missing in type '{ orgType: "company"; }'.`

**Comment by RyanCavanaugh** [comment]
Type asserting to `<any>` always works.

This has been changed in `master` on account of #6167
