### ISSUE TITLE
Allow empty return statements on setters

### ISSUE THREAD

**Issue by gjuchault** [Microsoft/TypeScript#9370]
**TypeScript Version:** 
1.8.10

**Code**

```ts
class Foo {
  private _value: string = '';
  set value(newV: string): void {
    if (newV === this._value) {
      return;
    }

    // ...
  }
}
```

**Expected behavior:**

No errors.

**Actual behavior:** 

`A 'set' accessor cannot have a return type annotation.`.

Thanks :)

**Comment by aluanhaddad** [comment]
Is the issue of the Void annotation, or the return statement I believe it's the former.

**Comment by gjuchault** [comment]
The error is that TypeScript puts an error when there is a return statement on a setter; when it can makes sense to stop the setter becasue of validation or whatever

**Comment by RyanCavanaugh** [comment]
The issue is the return type annotation, not the return statement. Expressionless return statements are legal. Return type annotations are not.

**Comment by gjuchault** [comment]
@RyanCavanaugh Ok I'm not really sure what's the difference between the two. Is the `: void` non-sense on a setter ?

**Comment by RyanCavanaugh** [comment]
Yes. The returned value of a setter is unobservable, so it doesn't make any sense to talk about its return type.
