### ISSUE TITLE
async function error: TypeError: Generator is already running 

### ISSUE THREAD

**Issue by phiresky** [Microsoft/TypeScript#9372]
**TypeScript Version:** Version 1.8.10 and Version 1.9.0-dev.20160626-1.0

**Chromium Version:** Version 51.0.2704.103 (64-bit)

**Code**

```ts
"use strict";

function count(): number {
    return 42;
}
async function countAsync(): Promise<number> {
    return count();
}
countAsync()

```

**html**:
```html
<script src="bin/main.js"></script>
```

**Expected behavior:** print 42

**Actual behavior:** 

```
main.ts:2 Uncaught (in promise) TypeError: Generator is already running
    at next (native)
    at fulfilled (http://localhost:8000/bin/main.js:4:58)
```

**Emitted Javascript (ES6):**

```js
"use strict";
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator.throw(value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : new P(function (resolve) { resolve(result.value); }).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments)).next());
    });
};
function count() {
    return 42;
}
function countAsync() {
    return __awaiter(this, void 0, Promise, function* () {
        return count();
    });
}
countAsync().then(x => console.log(x));
//# sourceMappingURL=main.js.map
```

Same code works fine in node v6.2.2

**Comment by Anjmao** [comment]
It works fine for me on Chrome: 51.0.2704.106 v :)

**Comment by phiresky** [comment]
Same issue appears here: https://phiresky.github.io/qalc-react/ for me.

**Comment by Arnavion** [comment]
This is a Chrome bug (testing on dev version v53).

```javascript
"use strict";

function count() { return 42; }
var generator = function* () { return count(); }
var g = generator.apply(undefined, undefined);
console.log(g.next());
```

incorrectly logs `42`.

Inlining the result of `count()`

```javascript
"use strict";

function count() { return 42; }
var generator = function* () { return 42; }
var g = generator.apply(undefined, undefined);
console.log(g.next());
```

correctly logs `Object {value: 42, done: true}`

The former is the bug. In the original emit, `step` gets a bad value `42` because of it.

**Comment by RyanCavanaugh** [comment]
Please log this in the V8 issue tracker. We don't have any way to account for broken runtimes.

**Comment by phiresky** [comment]
Okay, I apparently had the `enable-javascript-harmony` flag enabled in chrome://flags . Disabling that solves this problem for chrome stable.

**Comment by Kovensky** [comment]
Is there a tracking bug for this? This is now affecting Canary, even without the harmony flag.

**Comment by Arnavion** [comment]
I didn't find an existing bug, so I've created https://bugs.chromium.org/p/v8/issues/detail?id=5322
