### ISSUE TITLE
tsc -w vs visual studio compile on save

### ISSUE THREAD

**Issue by Anjmao** [Microsoft/TypeScript#9373]
I'm using Typescript 1.8.10 and Karma in watch mode.
1) If I run `tsc -w` and change any file, karma detects that all my source files was changed (**bad**)
2) I have big solution with more what 1000 files and get a lot of annoying`INFO [watcher]: Changed file "...file.js"` output messages in karma console (**bad**).
3) Usually I use fdescribe or fit jasmine methods to run only related tests for code changes. This makes tests run much faster, but I still should white up to 10 seconds because I get 1000 File changed messages in console. I tried to set karma logLevel to config.LOG_ERROR, but delay is still the same. (**bad**)
4) If use Visual Studio 2015 it works fine and karma notify only about one file changes which I'm editing (**good**)

Maybe we can emit only changed file, like in Visual Studio?

**Comment by mhegazy** [comment]
https://github.com/Microsoft/TypeScript/pull/6937 should fix this. a file is only modified if it has changed.
