### ISSUE TITLE
Autocomplete undeclared references

### ISSUE THREAD

**Issue by tinganho** [microsoft/TypeScript#9385]
I think it is quite common for people to write a reference to an undeclared property or variable first and then write the declaration of it. And not the other way around.

Given the below code:

``` ts
class View {
  bind() {
    this.data.on('change:title', this.renderTitle);
  }

  renderTitle() {
    // ...
  }
}
```

If I would have written the above code from scratch, I would often write the reference `this.renderTitle` first before the declaration of `renderTitle`:

``` ts
    this.data.on('change:title', this.renderTitle);
```

So it would be good if it could autocomplete `renderTitle` when I am about to write the declaration for it:

``` ts
  renderTitle() {
    // ...
  }
```

**Comment by DanielRosenwasser** [comment]
The actual suggestion here is somewhat difficult from a technical perspective. I wonder if an "add missing member" code-fix would possibly help alleviate some of the pain of the current experience.

**Comment by tinganho** [comment]
>I wonder if an "add missing member" code-fix would possibly help alleviate some of the pain of the current experience.

Yes that would also be preferrable.

**Comment by RyanCavanaugh** [comment]
Closing due to lack of feedback
