### ISSUE TITLE
Resolving absolute import path

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#9386]
_From @vuhrmeister on June 27, 2016 10:28_

- VSCode Version: 1.2.1
- OS Version: OSX

Only relative import paths are resolved. So jumping to the file that's imported works only with relative paths.

```javascript
// resolves
import '../some-file.js';
// does not resolve
import '/modules/some-file.js';
```

Where `/` is the very root of the project. 

Also it would be nice if automatically resolving index files would work:

```javascript
// imports '../some-module/index.js'
import '../some-module';
```

_Copied from original issue: Microsoft/vscode#8183_

**Comment by DanielRosenwasser** [comment]
On a Unix system (like Mac OS X), that path might have nothing to do with your project. Instead, it is the root of the file-system. I don't think we could change that behavior.

Automatically resolving import paths *should* work though, but I'd file a separate issue if that's not actually the case.
