### ISSUE TITLE
jsconfig & tsconfig schemas: Description improvements

### ISSUE THREAD

**Issue by aeschli** [Microsoft/TypeScript#9387]
http://json.schemastore.org/tsconfig contains the JSON schema of the tsconfig.json file. I assume it is maintained by the TS team, that's why I thought I directly file the issue here.

VSCode fetches the tsconfig schema from that URL and uses it for completion and hovers.
Now that there's also a public schema for [jsconfig](http://json.schemastore.org/jsconfig), we also plan to do the same for the jsconfig schema. Currently we have our own local version as none was available before. 

In our own version of the jsconfig schema we changed the description of all options that only apply when downlevel compile.
e.g.
"outFile": "When down-level compiling, concatenate and emit output to single file.",
"outDir": "When down-level compiling, redirect output structure to the directory."
...

We did this following consultations with @billti and @mhegazy in order for us to understand which properties work when, which is quite tricky unless you are an insider. We think the additional information is valuable and it would be great if it could be applied in the schemastore as well.
See https://github.com/Microsoft/vscode/blob/master/extensions/javascript/schemas/jsconfig.schema.json for our version.

Also, for new options, can you mention in which TS version it is supported?
Recently new options such as 'exclude' and 'include' have been added. It would be nice if the description can mention that these options require TypeScript 2.0

**Comment by aluanhaddad** [comment]
@aeschli The schema for `tsconfig.json` was recently updated, so you may want to update you current custom versions. Regardless there is definitely room for improvement here. As you say, descriptions of various items, especially with respect to versioning, could be dramatically improved.

With regard to versioning, I would actually like this to be taken a step further. Once a version of the language is officially released, it would be great if the subset of `tsconfig` and `jsconfig` settings it supports were captured in a versioned release of the `schema.json`. Then a reliable version, supporting the settings understood by the version of TypeScript detected, could be picked up and retrieved accordingly. 

This has three main advantages:

1. It removes the need for "requires TypeScript >= 2.0" to be included in the setting description, saving valuable space for explanatory text.
2. Tooling could detect deprecated/superseded settings as well as settings requiring a new versions and issue warnings or upgrade path suggestions accordingly
2. Tooling could detect deprecated/superseded settings as well as settings requiring a new versions and issue warnings or upgrade path suggestions accordingly
3. It preserves previous sets of settings for posterity.

That said, I love `tsconfig` it's an awesome feature, it is wonderfully cross IDE and cross platform, I just think these scenarios are important.

**Comment by mhegazy** [comment]
@yui can you update the files, since you last touched them, and add the missing documentation from  https://github.com/Microsoft/vscode/blob/master/extensions/javascript/schemas/jsconfig.schema.json

**Comment by aluanhaddad** [comment]
Awesome work. Very helpful

**Comment by yuit** [comment]
if anyone of you will be interested in the update, let me know what you think or whether it is good to be merged. Here is the PR in schema store: [here](https://github.com/SchemaStore/schemastore/pull/198)
