### ISSUE TITLE
Move scrollIntoView method to Element from HTMLElement

### ISSUE THREAD

**Issue by SaschaNaz** [Microsoft/TypeScript#9388]
This prevents [scrollIntoView extension](http://www.w3.org/TR/2016/WD-cssom-view-1-20160317/#extension-to-the-element-interface) to Element.

```webidl
// CSSOM View Module: http://www.w3.org/TR/2016/WD-cssom-view-1-20160317/
partial interface Element {
  ...
  void scrollIntoView();
  void scrollIntoView((boolean or object) arg);
  ...
};
```

```ts
interface Element {
    // Always overridden by HTMLElement
    scrollIntoView(arg?: boolean | ScrollIntoViewOptions): void;
    scroll(options?: ScrollToOptions): void;
    scrollTo(options?: ScrollToOptions): void;
    scrollBy(options?: ScrollToOptions): void;
}
```

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.

**Comment by YuichiNukiyama** [comment]
This is fixed in TSJS repo. [#128](https://github.com/Microsoft/TSJS-lib-generator/pull/128/files)

**Comment by mhegazy** [comment]
thanks @YuichiNukiyama
