### ISSUE TITLE
Add VarDate interface and Date constructor overload for VT_DATE to lib.d.ts

### ISSUE THREAD

**Issue by zspitz** [Microsoft/TypeScript#9392]
**TypeScript Version:**  1.8.0 / nightly (2.0.0-dev.201xxxxx)

Automation host objects pass dates into Javascript as `VarDate` per the specification ([copy found here](http://jibbering.com/faq/res/[MS-ES3EX].pdf)) (section 2.2.2). These need to be wrapped in a `Date` constructor before they can be used in Javascript.  
Such properties therefore cannot be typed as `Date` in declarations.

**Code**
```ts
namespace Scripting {
    interface File {
        DateCreated: Date;
    }
    interface FileSystemObject {
        GetFile(FilePath: string): File
    }
}
interface ActiveXObject {
    new (s: 'Scripting.FileSystemObject'): Scripting.FileSystemObject;
}

// Under WSH
var fso = new ActiveXObject('Scripting.FileSystemObject');
var file = fso.GetFile('C:\\test.txt');
var varDate = file.DateCreated;

//the following fails with "'varDate' is null or not an object"
//WScript.Echo(varDate.getYear()); 

//outputs the year
WScript.Echo(new Date(varDate).getYear());
```

**Proposal**

Add the following to [scripthost.d.ts](https://github.com/Microsoft/TypeScript/blob/master/src/lib/scripthost.d.ts):

```ts
interface VarDate { }

interface DateConstructor {
    new (vd: VarDate): Date;
    getVarDate: () => VarDate;
}
```

and such date properties could use `VarDate` instead of `Date`.

**Comment by mhegazy** [comment]
`ActiveXObject` is defined as:

```ts
interface ActiveXObject {
    new (s: string): any;
}
```

so from the compiler perspective `fso` is of type `any`. 

Contributions for better definitions for the WSH are always welcomed. the definitions should go in https://github.com/Microsoft/TypeScript/blob/master/src/lib/scripthost.d.ts

**Comment by zspitz** [comment]
> Contributions for better definitions for the WSH are always welcomed.

@mhegazy I thought I was the last one using WSH (with or without Typescript)...

**Comment by mhegazy** [comment]
> I thought I was the last one using WSH (with or without Typescript)

:D i think there still a few more out there. the TS compiler uses them internally as well to support running on cscript.

**Comment by zspitz** [comment]
@mhegazy See [here](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/9868). I've written a tool that uses tlbinf32.dll to generate Typescript definitions from type libraries.

**Comment by zspitz** [comment]
@mhegazy The tool is now on [Github](https://github.com/zspitz/ts-activex-gen);

**Comment by zspitz** [comment]
> the TS compiler uses them internally as well to support running on cscript.
Are there any specific libraries that should be added?

**Comment by mhegazy** [comment]
see `getWScriptSystem` in https://github.com/Microsoft/TypeScript/blob/master/src/compiler/sys.ts#L88-L232
