### ISSUE TITLE
tsc.exe exited with error code 1 - Exclude not working

### ISSUE THREAD

**Issue by MCKRUZ** [Microsoft/TypeScript#9398]
**TypeScript Version:**  1.8.10
**TypeScript Tools Version:** 1.8.6

I'm using Visual Studio 2015 sp3.  Here is my project
https://github.com/MCKRUZ/TestCode

I'm getting issues where I will get an error tsc.exe exited with code 1 no matter what I do.

It seems like the "exclude" attribute isn't working at all in tsconfig.json.  Can someone please try this and help me?

**Expected behavior:**
The project should build

**Actual behavior:** 
The project errors out

**Comment by GeorgDangl** [comment]
Your project should build when you change `watch` in tsconfig.json to `false`. I got the error described [here](https://github.com/Microsoft/TypeScript/issues/7362).

However, it seems that some *.cs files are missing in your repository (Momentum.ASPCoreNg2.Template.Services namespace is referenced in `AccountController` but not present in the repository), so it still won't compile. But all the errors are .Net compiler errors now.

**Comment by mhegazy** [comment]
as noted by @GeorgDangl `--watch` is not supported in `tsc.exe` using node to build should do the trick. my recommendation is to remove that from the tsconfig.json, along with the other not needed flags like `diagnostics`, `listFiles`, `pretty`, `locale`..

in general, i would remove all the properties that has the default, i.e. "false".

**Comment by MCKRUZ** [comment]
Thank you so much guys that did it!
