### ISSUE TITLE
Can not specify an empty list of `--types`

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript#9409]
> tsc a.ts --types ,
> error TS2688: Cannot find type definition file for ''.

**Comment by mhegazy** [comment]
@weswigham can you take a look.

**Comment by weswigham** [comment]
I [removed](https://github.com/Microsoft/TypeScript/pull/9090/commits/d20459607b96b17dacfd018eb6f8e29a97805dfc) the bare comma option after discussion around the PR in the office - people found it confusing. You need to just supply a following command line argument (like `--sourcemaps`), or supply an empty following parameter (if calling using some shelling out API).

If we do actually want the bare comma form back, we can just revert that commit.

**Comment by falsandtru** [comment]
Help messages should have a `types` option's parameter such as `--types TYPES`.

```
$ node built/local/tsc.js -h | grep types
 --types                             Type declaration files to be included in compilation.
```

**Comment by mhegazy** [comment]
closing as won't fix for now. let's see how users will react to it.

**Comment by mhegazy** [comment]
@falsandtru a PR would be welcomed for the documentation change.

**Comment by petrkoutnysw** [comment]
IMO, as a developer I'd like the "--types" flag to behave the same way as it does in tsconfig.json.
