### ISSUE TITLE
Visual Studio 2015 Update 3: compileOnSave from tsconfig.json no longer works

### ISSUE THREAD

**Issue by GeorgDangl** [Microsoft/TypeScript#9416]
**TypeScript Version:**  1.8.34.0 / 1.8.6.0

Since I've upgraded to Visual Studio 2015 Update 3 with the .Net Core 1.0 SDK and the Visual Studio Tooling Preview 2 for .Net Core, the `compileOnSave` entry from `tsconfig.json` is no longer being honored by Visual Studio. I've followed the [advice given here](https://github.com/Microsoft/TypeScript/issues/8518#issuecomment-223156931) to be able to compile Angular2 by manually updating `C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TypeScript\typescriptServices.js`.

I've tried uninstalling [Web Essentialls](https://visualstudiogallery.msdn.microsoft.com/ee6e6d8c-c837-41fb-886a-6b50ae2d06a2) as well as [Web Extension Pack](https://visualstudiogallery.msdn.microsoft.com/f3b504c6-0095-42f1-a989-51d5fc2a8459) in Visual Studio without any change. 

`C:\Program Files (x86)\Microsoft SDKs\TypeScript` has folders for `1.0`, `1.7` and `1.8` present. The PATH variable points to `1.8` and the output from `tsc -v` is `1.8.34`. I've not installed any additonal TypeScript tools, so Windows' _Programs and Features_ does only list `Microsoft TypeScript for Visual Studio` with version `1.8.6.0`.

The behaviour is consistent amoung two Laptops that I use, both are on Windows 10.

Compilation on project build works fine in Visual Studio, but no automatic changes are detected and acted upon. Here's [a small sample repository](https://github.com/GeorgDangl/NetCoreHeroes) that worked fine before upgrading the Visual Studio Extension.

**tsconfig.json**

```json
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": false
  },
  "compileOnSave": true,
  "exclude": [
    "node_modules",
    "wwwroot/lib",
    "bin",
    "obj"
  ]
}
```

**Expected behavior:**
*.ts files are automatically compiled to *.js after being saved.

**Actual behavior:** 
No action at all.

**Comment by paulvanbrenk** [comment]
@GeorgDangl did it work without updating `typescriptServices.js'?

**Comment by GeorgDangl** [comment]
I can't check that today since I don't have access to the backed up typescriptServices.js file until tomorrow, I'll report asap. But Angular2 wouldn't compile with the fresh installation of VS Update 3.

I found out, however, that compile on save _does_ work in either a TypeScriptHtmlProject (so no .Net Core) or alternatively if I remove the tsconfig.json file from the .Net Core project. It also works on a fresh .Net Core project (Web Application Template).

So looks like it might be the same as #9318, presence of tsconfig.json somehow blocks compileOnSave?

**Comment by paulvanbrenk** [comment]
@GeorgDangl The `typescriptservices.js` file referenced here https://github.com/Microsoft/TypeScript/issues/8518#issuecomment-223156931 doesn't return the state of `compileOnSave` in the `tsconfig.json` to VS, so we don't enable it. @mhegazy should update that to point to the right `typescriptservices.js` to work with both angular and compile on save.

**Comment by mhegazy** [comment]
I have updated the workaround for 8518, see https://github.com/Microsoft/TypeScript/issues/8518#issuecomment-229506507

**Comment by pksorensen** [comment]
This is the same problem for me, the compileOnSave do not work and cant get it working from any of the suggested fixes

**Comment by elemental21** [comment]
@mhegazy  I'm confused by your comment.  Are you saying that the Update 3 update for the workaround  should have taken care of the compileOnSave issue?  It isn't for me.  I'm on 1.8.36 as per the VS2015 about screen (although the command line says 1.8.34).  Is the suggested solution to upgrade to Typescript 2?

**Comment by mhegazy** [comment]
TypeScript 2.0 beta should have fix for both issues. 

if you are applying my workaround for #8518 and then running into this issue, then please look at my updated comment.

if you have not ran into #8518 and did not make any changes to typescriptservices.js, but you are still running into this issue, then this is a different bug. please file a new issue to track it and provide some details to be able to reproduce it locally.

**Comment by elemental21** [comment]
@mhegazy I applied your updated comment (for Update 3) and while it has fixed the errors it seems to have broken my compileOnSave in Typescript.  When I undo the typescriptservices.js fix then compileOnSave works.

However I seem to have a fix for both of these issues (compiler errors and compileOnSave). One of the developers in our group has an environment that was working properly with compileOnSave and no build errors.  While looking for differences I realized that he did *not* have Typescript set in his PATH environmental variable.  So I removed Typescript from my PATH variable and everything works now.  No typescriptservices.js patch necessary.  Could this be because of the differing Typescript versions between VS2015 about and "tsc -v" (1.8.36 vs 1.8.34)?  Are there ramifications of doing this? I assume something like gulp-typescript wouldn't work.

**Comment by mhegazy** [comment]
> So I removed Typescript from my PATH variable and everything works now

CompileOnSave and any other VS features do not use the PATH at all. so not sure why you are seeing a different behavior here.

> and no build errors. 

my comment in #8518 was not about build errors. looks like you were running into other things.

**Comment by elemental21** [comment]
@mhegazy Maybe I'm saying it wrong, but VS "Error List" had 111 typescript errors flagged when I do a build (such as Invalid module name in augmentation, module '../../Observable' cannot be found).  I can still run/debug the application but they are flagged as errors.  These errors are the same that are originally referenced in #8518 by the OP.  Your typescriptservices.js patch fixed these errors but appears to have broken my saveOnCompile.

Unfortunately you are correct about the PATH settings.  The errors are still there without your typescriptservices.js patch, it just took a while for them to appear.

**Comment by mhegazy** [comment]
i would recommend moving to TS 2.0 at this point. it should contain fixes for both issues.

**Comment by SergeyBarskiy** [comment]
I just installed 2.0, and compileOnSave does not work again.  I had to install the workaround mentioned above.  The TS 2.0 installer did not overwrite any files in C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TypeScript folder.  Any suggestions to address the issue?  Thanks.
