### ISSUE TITLE
Output test files don't delete/rename themselves after doing the same operation in src files

### ISSUE THREAD

**Issue by HarshdeepGupta** [Microsoft/TypeScript#9418]
**TypeScript Version:**  1.8.5
**VSCode Version:** 1.2.1
**OS Version:** Windows 10

I am building a VS Code extension, and on writing test cases for it, I noticed that files in out/test get created automatically upon creation in /test but don't get renamed or deleted.

**Steps to Reproduce:**

1. Start Yo Code and scaffold a TS extension (Yo code)
2. open the extension in VS Code and build once (by pressing F5 ) to get typescript compiler running on watch mode (need to select "Launch Extension" from debug pane)
3. go to /test and create main.test.ts. See that the file is generated in out/test folder.
4. Delete (or rename) main.test.ts .
5. In /out/test , you will see that the old files are still there.

**Expected behavior:**
main.test.ts should get deleted
**Actual behavior:** 
Files don't get updated

I raised this issue to VS Code team, they directed me here.
[8495](https://github.com/Microsoft/vscode/issues/8495)

**Comment by mhegazy** [comment]
The compiler does not delete files. if you have renamed a source file, you need to delete the generated files as well. I do not think we have any intentions to change this behavior.
