### ISSUE TITLE
Feature Request: switch tuple

### ISSUE THREAD

**Issue by frogcjn** [Microsoft/TypeScript#9419]
for example:
```typescript
const tuple: [number, number] = [f0.length, f1.length]

switch (tuple) {
    case [3,3]: return ...
    case [3,4]: return ...
    case [4,3]: return ...
    case [4,4]: return ...
    default: throw Error("Invalid Case")
}
```

currently, tuple will not match any case, though its value is [3, 3]

**Comment by mortb** [comment]
If you can't wait for the team to answer, here is a workaround:
```
switch (tuple.join(",")) {
    case "3,3": return ...
    case "3,4": return ...
    case "4,3": return ...
    case "4,4": return ...
    default: throw Error("Invalid Case")
}
```

**Comment by sandersn** [comment]
I don't think TypeScript can help in this case because `switch` working with arrays would be quite different from JavaScript's behaviour. You probably should support [the ECMAScript pattern matching proposal](https://gist.github.com/bterlson/da8f02b95b484cd4f8d9). If that's accepted into the standard, you will get tuple matching and more.

**Comment by frogcjn** [comment]
@sandersn 
does ECMAScript has tuple?

**Comment by sandersn** [comment]
You just need array matching to get the semantics you want. Tuples are just a type to make sure that you aren't matching against nonsensical patterns.

Of course if ES20xx adds support for pattern matching, then TypeScript will allow you to type arrays as tuple in a matching context.

**Comment by frogcjn** [comment]
@martb, thanks. I solved it what as you writes.
But as I suggest, typescript has a "tuple" concept, then it should has an ability to match tuple in switch.

**Comment by frogcjn** [comment]
@sandersn OK. I'll proposal ECMASCript has all type features like typescript. And then I wait until 2019.

**Comment by sandersn** [comment]
Pattern matching isn't really a type-system concept. There are plenty of languages with pattern matching but no compile-time types. (Erlang, Clojure, Common Lisp and Scheme come to mind immediately.)

**Comment by kitsonk** [comment]
> But as I suggest, typescript has a "tuple" concept, then it should has an ability to match tuple in switch.

JavaScript does not `switch` on non-primatives (references).  You cannot `switch` on Objects, Arrays, etc..

While a tuple type is a TypeScript concept, it is still a non-primative concept.  As tuples stand at the moment, they are a design time only concept, with their typing information fully erasable by using Array literals at run-time. Implementing this feature it would break several of the TypeScript Design Goals:

> 3) Impose no runtime overhead on emitted programs.
> 7) Preserve runtime behavior of all JavaScript code.

And would be an anti-goal:

> 5) Add or rely on run-time type information in programs, or emit different code based on the results of the type system. Instead, encourage programming patterns that do not require run-time metadata.
