### ISSUE TITLE
Can not access name of `export default async function`

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#9423]
**TypeScript Version:**  next

**Code**

(with `--target ES6`)

```ts
export default async function foo() {}
foo();
```

**Expected behavior:**
`foo` can be accessed

**Actual behavior:** 
`src/index.ts(2,1): error TS2304: Cannot find name 'foo'.`

**Comment by DanielRosenwasser** [comment]
This may just be a matter of us parsing that as a function expression instead of a function declaration.
