### ISSUE TITLE
Right paren is not a completion commit character

### ISSUE THREAD

**Issue by Peter-Juhasz** [Microsoft/TypeScript#9424]
**Visual Studio 2015 Update 3**
**TypeScript Version:**  1.8.34

**Code**
![image](https://cloud.githubusercontent.com/assets/9047283/16461397/a5e7fe44-3e2c-11e6-95ae-4eb91c3e1808.png)

**Expected behavior:**
I type the next character ')' without fully typing the word or explicitly committing the selected completion item by Enter; the completion item gets committed and the character I typed gets inserted at the next position.
![image](https://cloud.githubusercontent.com/assets/9047283/16461437/cf59a958-3e2c-11e6-83ab-f03a43a7a35c.png)

**Actual behavior:** 
Completion does not happen, the completion session gets dismissed but the character gets typed, so I end up in an incorrect state.
![image](https://cloud.githubusercontent.com/assets/9047283/16461500/28bbf6a4-3e2d-11e6-91a5-6ed0009b8513.png)

This behavior is really frustrating, because almost every time I start typing a word then write the next character fluently ('.', ',' '(', ...), the code gets messed up.

**Comment by Peter-Juhasz** [comment]
Hey @DanielRosenwasser the title you changed the bug to is wrong. Not only "right paren" but **all** completion characters do not work. So please change it back, because the overall behavior of commiting on specific characters does not work.

**Comment by Peter-Juhasz** [comment]
@DanielRosenwasser did you read the issue definition completely? Because it not applies only to right parenthesis but all characters which you can write next right after completion, like dot, space and so on.

**Comment by paulvanbrenk** [comment]
I have a fix for this, and it should be part of the final 2.0 release.

**Comment by dudeNumber4** [comment]
Very confused.  Using 2.1.6 and this is still an issue.  Should it not be?
