### ISSUE TITLE
Typescript LS is preferring .js to @types .d.ts when loading types

### ISSUE THREAD

**Issue by weswigham** [Microsoft/TypeScript#9427]
**TypeScript Version:**  nightly (2.0.0-dev.201xxxxx)

**Code**
`npm install --save-dev gulp`
`npm install --save-dev @types/gulp`

```ts
import gulp = require("gulp");
```

**Expected behavior:**

Right click -> Go to definition on `gulp` -> Opens `@types/gulp/index.d.ts`

**Actual behavior:** 

Right click -> Go to definition on `gulp` -> Opens `gulp/index.js`

Using the imported `gulp` also makes it obvious that all the types are being loaded from the located `.js` and not the `@types` `.d.ts`. This causes serious editor usability issues as your included type definitions are overridden by the required js!

**Comment by weswigham** [comment]
@billti I think this has something to do with #9384. I think it's taking priority over #8670 and #9095 - which are headlining features for 2.0!

**Comment by billti** [comment]
Doh! Yeah, makes sense. I'll need to somehow locate the .js file, but defer using it until other type resolution from other search locations fail. Will take a look a bit later, but will revert in the meantime.

**Comment by weswigham** [comment]
@billti I think I can make a PR fixing it - one of my other PRs already alters that area a bit, so I'm familiar with it.

**Comment by billti** [comment]
We'll need to add a project test covering a realistic NPM file layout with @types definitions installed too. That would have caught this.

**Comment by billti** [comment]
Fixed with the above merges.
