### ISSUE TITLE
Microsoft.TypeScript.targets(156,5): error MSB4018: The "FindConfigFiles" task failed unexpectedly.

### ISSUE THREAD

**Issue by ludakuca** [Microsoft/TypeScript#9435]
**TypeScript Version:**  1.8.34 (build server 1.8.6 and 1.7.5

**Code**
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\TypeScript\Microsoft.TypeScript.targets(156,5): error MSB4018: The "FindConfigFiles" task failed unexpectedly. [D:\Builds\TFSBuild.proj]
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\TypeScript\Microsoft.TypeScript.targets(156,5): error MSB4018: System.ArgumentNullException: Value cannot be null. [D:\Builds\TFSBuild.proj]
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\TypeScript\Microsoft.TypeScript.targets(156,5): error MSB4018: Parameter name: path [D:\Builds\TFSBuild.proj]

// A *self-contained* demonstration of the problem follows...
I have installed the 1.8.34 version on my Visual studio 2015 and I have changed the build project to import the 

**
  <Import Project="$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\TypeScript\Microsoft.TypeScript.Default.props" Condition="Exists('$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\TypeScript\Microsoft.TypeScript.Default.props')" />

etc....

**

Build servers had installed version 1.7.5 

Everything worked fine (meaning build completed fine, but the js files were never generated).

I went onto build server and tried upgrading the latest version of typescript for vs2015 from the site, and ever since I have been getting this error.  There is nothing much online to show what is going on.

I have tried uninstalling/repairing the installation, repairing the old one, but nothing seems to work.   My tsconfig.json looks like this

** 
{
  "compilerOptions": {
    "noImplicitAny": false,
    "noEmitOnError": true,
    "removeComments": false,
    "sourceMap": true,
    "target": "es5",
    "outDir": "./Scripts"
  },
  "compileOnSave": false,
  "exclude": [
    "node_modules",
    "wwwroot"
  ]
}
**

Everything builds fine locally, its just when I push it on build server when this error is happening and I cannot find any solution to it.

**Expected behavior:**

**Actual behavior:**

**Comment by mhegazy** [comment]
@paulvanbrenk can you take a look.

**Comment by ludakuca** [comment]
I realized after installing the newer version of TypeScript as well that neither my build servers or my local has any entry in the Parh for the environmental variables.  Is this something we should add manually if we want to be able to access the typescript compiler from anywhere other then TS folder?

**Comment by mhegazy** [comment]
correct. since TS 1.1, the installer does not add any thing to the path.

**Comment by ludakuca** [comment]
Cool, thanks.

I uninstalled 1.8.6 from the build server, and have only 1.7.5.  I did a repair on the 1.7.5 and still getting the same error.  Not sure what changed and how was this working prior to me trying to upgrade to 1.8.6

Also I have VS2015 on build servers, and when I installed the 1.8.6 it was telling me in the version that its actually 1.8.5 (which should be the version for VS2013).  Kind of confused here.  What would be the best way to uninstall everything and install latest on the build server.

My dev computer has VS2015 with 1.8.34 installed.  I tried downloading the new version and installing from 

[https://www.microsoft.com/en-us/download/details.aspx?id=48593](url)

but it is still showing that its 1.8.34

Any input on these.  And what is the meaning of the error message above?  Does it have to do with my using tsconfig.json file?  Would removing the file and using the project properties work?

**Comment by ludakuca** [comment]
got update 3 of visual studio on the build server, the version is showing as 1.8.34 (same as what I have locally)

When I build again getting the same error.

**Comment by paulvanbrenk** [comment]
@ludakuca Can you share your project file?

**Comment by ludakuca** [comment]
Project file within solution has this code at the top added for typescript:
`<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="12.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\TypeScript\Microsoft.TypeScript.Default.props" Condition="Exists('$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\TypeScript\Microsoft.TypeScript.Default.props')" />
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" Condition="Exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props')" />
 ,,,`

Then this entry for typescript:
`    <TypeScriptToolsVersion>1.8</TypeScriptToolsVersion>
`

at the end it has this:

` <ItemGroup>
    <TypeScriptCompile Include="Scripts\typeScript\my-custom-fields.ts" />
    <TypeScriptCompile Include="Scripts\typeScript\types\jquery.d.ts" />
    <TypeScriptCompile Include="Scripts\typeScript\types\kendo-ui.d.ts" />
  </ItemGroup>

<PropertyGroup>
    <VisualStudioVersion Condition="'$(VisualStudioVersion)' == ''">10.0</VisualStudioVersion>
    <VSToolsPath Condition="'$(VSToolsPath)' == ''">$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)</VSToolsPath>
  </PropertyGroup>
  <Import Project="$(MSBuildBinPath)\Microsoft.CSharp.targets" />
  <Import Project="$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\TypeScript\Microsoft.TypeScript.targets" Condition="Exists('$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\TypeScript\Microsoft.TypeScript.targets')" />
  <Import Project="$(VSToolsPath)\WebApplications\Microsoft.WebApplication.targets" Condition="'$(VSToolsPath)' != ''" />
  <Import Project="$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v10.0\WebApplications\Microsoft.WebApplication.targets" Condition="false" />
 `

everything builds and works fine locally.

These are the MSBuild project file entries.


at the top I added:

`<Project DefaultTargets="DesktopBuild" xmlns="http://schemas.microsoft.com/developer/msbuild/2003" ToolsVersion="14.0">

  
  <Import Project="$(MSBuildExtensionsPath)\Microsoft\VisualStudio\TeamBuild\Microsoft.TeamFoundation.Build.targets" />
  <Import Project="$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\TypeScript\Microsoft.TypeScript.Default.props"
      Condition="Exists('$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\TypeScript\Microsoft.TypeScript.Default.props')" />
  `

Then in the middle of the project I have this part:

```
<PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <TypeScriptRemoveComments>false</TypeScriptRemoveComments>
    <TypeScriptSourceMap>true</TypeScriptSourceMap>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <TypeScriptRemoveComments>true</TypeScriptRemoveComments>
    <TypeScriptSourceMap>false</TypeScriptSourceMap>
  </PropertyGroup>

```

and then at the end I added follwoing lines:

```
<Import
      Project="$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\TypeScript\Microsoft.TypeScript.targets"
      Condition="Exists('$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\TypeScript\Microsoft.TypeScript.targets')" />
```

These are identical and unchanged entries recommended on the typescript site to use for msbuild.

It worked as I said originally, but upon trying to get the version on server to update from 1.7.5 to 1.8 this started happening...and I tried uninstalling and everuything and nothing brings it back.


Thanks,

**Comment by paulvanbrenk** [comment]
@ludakuca Can you share your whole project file, there may be some subtle things going on. Does this work on your local machine? Further can you share the log file when you build with the following options `msbuild /fl /flp:verbosity=diagnostic`

**Comment by ludakuca** [comment]
@paulvanbrenk 

everything works fine on my local machine.  What project file are you talking about, the msBuild, or the project file within my solution?

**Comment by paulvanbrenk** [comment]
@ludakuca The project file that contains the typescript files, so probably the one in your solution.

**Comment by ludakuca** [comment]
@paulvanbrenk but everything builds fine in my local computer and even other coworkers when getting latest can build and work with it.  

Only time this fails is when I am trying to push code to the build server to build

**Comment by paulvanbrenk** [comment]
@ludakuca How about the log file from the server build?

**Comment by ludakuca** [comment]
@paulvanbrenk 

This is pretty much it in the log file.  its the first thing that fails.

```
Build started 6/30/2016 12:27:41 PM.
Project "d:\Builds\15\BuildType\TFSBuild.proj" on node 1 (EndToEndIteration target(s)).
InitializeBuildProperties:
  GetBuildProperties TeamFoundationServerUrl="http://localhost:8080/tfs/mycollection" BuildUri="vstfs:///Build/Build/44865"
InitializeEndToEndIteration:
  UpdateBuildNumberDropLocation TeamFoundationServerUrl="http://localhost:8080/tfs/mycollection" BuildUri="vstfs:///Build/Build/44865" BuildNumber="20160630.3" DropLocation="\\{Myserver}\Builds\20160630.3"
CoreInitializeWorkspace:
  DeleteWorkspaceTask TeamFoundationServerUrl="http://localhost:8080/tfs/mycollection" BuildUri="vstfs:///Build/Build/44865" Name="SERVER_103_15" DeleteLocalItems=True
  CreateWorkspaceTask TeamFoundationServerUrl="http://localhost:8080/tfs/mycollection" BuildUri="vstfs:///Build/Build/44865" Name="SERVER_103_15" BuildDirectory="d:\Builds\15\" SourcesDirectory="d:\Builds\15\src" Comment="Workspace created by Team Build"
InitializeBuild:
  Creating directory "d:\Builds\15\src".
CoreGet:
  Get TeamFoundationServerUrl="http://localhost:8080/tfs/mycollection" BuildUri="vstfs:///Build/Build/44865" AllowUnmapped=True AutoMerge=True BuildDirectory="d:\Builds\15\" Force=True NoCIOption=True Overwrite=False PopulateOutput=False Preview=False Recursive=True Version="C66837" Workspace="SERVER_103_15"
  11919 file(s) were downloaded with a total size of 490.00 MB.
CoreLabel:
  Label TeamFoundationServerUrl="http://localhost:8080/tfs/mycollection" BuildUri="vstfs:///Build/Build/44865" Name="20160630.3" Scope="$/MyApp" Recursive=True Comments="Label created by Team Build" Version="WSERVER_103_15" Child="Replace" Files="$/"
  Label 20160630.3@$/MyApp (version WSERVER_103_15) was successfully created.
  SetBuildProperties TeamFoundationServerUrl="http://localhost:8080/tfs/mycollection" BuildUri="vstfs:///Build/Build/44865" CompilationStatus="Unknown" LabelName="20160630.3@$/MyApp" Status="None" TestStatus="Unknown"
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\TypeScript\Microsoft.TypeScript.targets(156,5): error MSB4018: The "FindConfigFiles" task failed unexpectedly. [d:\Builds\15\BuildType\TFSBuild.proj]
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\TypeScript\Microsoft.TypeScript.targets(156,5): error MSB4018: System.ArgumentNullException: Value cannot be null. [d:\Builds\15\BuildType\TFSBuild.proj]
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\TypeScript\Microsoft.TypeScript.targets(156,5): error MSB4018: Parameter name: path [d:\Builds\15\BuildType\TFSBuild.proj]
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\TypeScript\Microsoft.TypeScript.targets(156,5): error MSB4018:    at System.IO.Directory.EnumerateFiles(String path) [d:\Builds\15\BuildType\TFSBuild.proj]
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\TypeScript\Microsoft.TypeScript.targets(156,5): error MSB4018:    at TypeScript.Tasks.FileHelpers.RecursiveGatherFiles(String directoryPath, String projectPath, Func`2 filter) [d:\Builds\15\BuildType\TFSBuild.proj]
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\TypeScript\Microsoft.TypeScript.targets(156,5): error MSB4018:    at TypeScript.Tasks.FindConfigFiles.FindConfigFilesOnDisk() [d:\Builds\15\BuildType\TFSBuild.proj]
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\TypeScript\Microsoft.TypeScript.targets(156,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [d:\Builds\15\BuildType\TFSBuild.proj]
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\TypeScript\Microsoft.TypeScript.targets(156,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext() [d:\Builds\15\BuildType\TFSBuild.proj]
Done Building Project "d:\Builds\15\BuildType\TFSBuild.proj" (EndToEndIteration target(s)) -- FAILED.

Build FAILED.

"d:\Builds\15\BuildType\TFSBuild.proj" (EndToEndIteration target) (1) ->
(FindConfigFiles target) -> 
  C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\TypeScript\Microsoft.TypeScript.targets(156,5): error MSB4018: The "FindConfigFiles" task failed unexpectedly. [d:\Builds\15\BuildType\TFSBuild.proj]
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\TypeScript\Microsoft.TypeScript.targets(156,5): error MSB4018: System.ArgumentNullException: Value cannot be null. [d:\Builds\15\BuildType\TFSBuild.proj]
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\TypeScript\Microsoft.TypeScript.targets(156,5): error MSB4018: Parameter name: path [d:\Builds\15\BuildType\TFSBuild.proj]
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\TypeScript\Microsoft.TypeScript.targets(156,5): error MSB4018:    at System.IO.Directory.EnumerateFiles(String path) [d:\Builds\15\BuildType\TFSBuild.proj]
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\TypeScript\Microsoft.TypeScript.targets(156,5): error MSB4018:    at TypeScript.Tasks.FileHelpers.RecursiveGatherFiles(String directoryPath, String projectPath, Func`2 filter) [d:\Builds\15\BuildType\TFSBuild.proj]
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\TypeScript\Microsoft.TypeScript.targets(156,5): error MSB4018:    at TypeScript.Tasks.FindConfigFiles.FindConfigFilesOnDisk() [d:\Builds\15\BuildType\TFSBuild.proj]
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\TypeScript\Microsoft.TypeScript.targets(156,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [d:\Builds\15\BuildType\TFSBuild.proj]
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\TypeScript\Microsoft.TypeScript.targets(156,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext() [d:\Builds\15\BuildType\TFSBuild.proj]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:58.41
```


i removed the names of the servers, etc.  for privacy concerns.

**Comment by paulvanbrenk** [comment]
@ludakuca Can you post the*while* log file with the verbosity set to `diagnostic` I need to know all the variables that are being set by msbuild in one way or another.

**Comment by ludakuca** [comment]
this is pretty much it with the logging verbosity set to diagnostic.  Do I have to run the build from the command prompt?

**Comment by paulvanbrenk** [comment]
@ludakuca Yes, you probably do. If I compile a tiny project with diagnostic logging enabled I get a 200KB log, that starts with a bunch of variables being setup like this:

```
Build started 6/30/2016 1:43:20 PM.
Environment at start of build:
ALLUSERSPROFILE = C:\ProgramData
APPDATA = C:\Users\pvanbren\AppData\Roaming
CommonProgramFiles = C:\Program Files (x86)\Common Files
CommonProgramFiles(x86) = C:\Program Files (x86)\Common Files
CommonProgramW6432 = C:\Program Files\Common Files
ComSpec = C:\WINDOWS\system32\cmd.exe
DevEnvDir = C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\
DNX_HOME = %USERPROFILE%\.dnx
ExtensionSdkDir = C:\Program Files (x86)\Microsoft SDKs\Windows Kits\10\ExtensionSDKs
FPS_BROWSER_APP_PROFILE_STRING = Internet Explorer
FPS_BROWSER_USER_PROFILE_STRING = Default
Framework40Version = v4.0
FrameworkDir = C:\WINDOWS\Microsoft.NET\Framework\
FrameworkDIR32 = C:\WINDOWS\Microsoft.NET\Framework\
FrameworkVersion = v4.0.30319
FrameworkVersion32 = v4.0.30319
HOMEDRIVE = C:
INCLUDE = C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE;C:\Program Files (x86)\Windows Kits\10\include\10.0.10586.0\ucrt;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.10586.0\shared;C:\Program Files (x86)\Windows Kits\10\include\10.0.10586.0\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.10586.0\winrt;
LIB = C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\LIB;C:\Program Files (x86)\Windows Kits\10\lib\10.0.10586.0\ucrt\x86;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\lib\um\x86;C:\Program Files (x86)\Windows Kits\10\lib\10.0.10586.0\um\x86;
LIBPATH = C:\WINDOWS\Microsoft.NET\Framework\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\LIB;C:\Program Files (x86)\Windows Kits\10\UnionMetadata;C:\Program Files (x86)\Windows Kits\10\References;C:\Program Files (x86)\Microsoft SDKs\Windows Kits\10\ExtensionSDKs\Microsoft.VCLibs\14.0\References\CommonConfiguration\neutral;
LOCALAPPDATA = C:\Users\pvanbren\AppData\Local
MSBuildLoadMicrosoftTargetsReadOnly = true
NETFXSDKDir = C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\
NugetMachineInstallRoot = D:\NugetCache
NUMBER_OF_PROCESSORS = 4
OS = Windows_NT
```

**Comment by ludakuca** [comment]
@paulvanbrenk I do not have Teambuild on my local box and cant run this locally.  On the server I do not have the files to build it on the server.

we first copy all the files to the build server and then build things.

**Comment by paulvanbrenk** [comment]
Can't you set the verbosity of the msbuild step to `diagnostic` either direct or via a command-line parameter (I can on the version we use here).

**Comment by paulvanbrenk** [comment]
It looks like a variable `projectdir` isn't set as expected in your server build... I need those logs to figure out why.

**Comment by ludakuca** [comment]
Initial Property Values
BinariesSubdirectory = 
BuildDirectory = D:\Builds\12\myproject
CommandLineArguments = 
ConfigurationFolderPath = $/(myproject)/Build
DoNotDownloadBuildType = False
LogFilePerProject = True
MaxProcesses = 1
NodeReuse = False
RecursionType = Full
SourcesSubdirectory = 
TargetsNotLogged = 
TestResultsSubdirectory = 
ToolPath = 
ToolPlatform = Auto
Verbosity = Diagnostic

![afsfa](https://cloud.githubusercontent.com/assets/20220724/16505897/ddd69f78-3ee4-11e6-848a-10c01d61be36.PNG)

**Comment by paulvanbrenk** [comment]
@ludakuca Can you share the whole log?

**Comment by ludakuca** [comment]
that was the whole log above.

Can the log you are looking for be generated by changing the build defitions and running the build from there.  The way this is set up I cannot run the builds using the cmd.

**Comment by paulvanbrenk** [comment]
On my build server I can get detailed logs from the step that builds the proj file... you should be able to set those to diagnostic and grab those. Or log on the machine after the build is completed and grab them there.. without those logs I'm not able to tell you what's happening.

![image](https://cloud.githubusercontent.com/assets/5273975/16506456/582ec83a-3ed7-11e6-8f47-56a3ca015963.png)

**Comment by ludakuca** [comment]
This is all i get as options....
![screenss](https://cloud.githubusercontent.com/assets/20220724/16506717/ebea8732-3ee9-11e6-9520-72d3d2a03b97.PNG)

**Comment by paulvanbrenk** [comment]
What do you get when you 'download all logs as zip'

**Comment by ludakuca** [comment]
I get the file that I posted above.BuildLog.txt.

ah this is giving me too many headaches :) I wish I can get you more information, I know you would know lots more if I had more detailed log, but its just not possible it seems like.

This error seems to be happening even before my project is being built.

**Comment by paulvanbrenk** [comment]
Ok, I can see in the screenshot that the call to msbuild doesn't set the verbosity of the log to `diagnostic` in the build step in your definition there should be an option to set `MSBuild Arguments` can you try setting `/verbosity=diagnostic` there.. the error you're seeing is part of the TypeScript build.

**Comment by ludakuca** [comment]
Trying now..

**Comment by paulvanbrenk** [comment]
What's the error you're getting?

**Comment by ludakuca** [comment]
ah it seems like you gave me the wrong switch :)

should be `/verbosity:diagnostic`

**Comment by paulvanbrenk** [comment]
Aah, yeah `:` vs. `=` is a common issue

**Comment by ludakuca** [comment]
so is a copy paste :)

**Comment by ludakuca** [comment]
is this good log?

**Comment by paulvanbrenk** [comment]
Ok, looks like we want to set this option ` /flp:verbosity=normal` to `diagnostic` as well..

**Comment by ludakuca** [comment]
I think thats it.. getting the file ready to upload

**Comment by paulvanbrenk** [comment]
Please don't post it here, but either zip it or email it directly to me. I assume it's pretty big.

**Comment by ludakuca** [comment]
I removed bunch of stuff

**Comment by ludakuca** [comment]
Thanks for helping me out over the email.  TThe build completed but no javascript files were generated on the build server.

**Comment by ludakuca** [comment]
@paulvanbrenk I did put some error logging in that file and I am seeing that both ProjectDir and Content parameters are null.  Am I not passing those properly?

**Comment by paulvanbrenk** [comment]
@ludakuca is this an ASP.NET v5/Core project... ? Is the ConfigFiles collection empty?

Since you have a `tsconfig.json` file, the Content parameter is ignored, but we should be able to find the `tsconfig.json` file if that's inside the cone of the project (i.e. in the same dir as the proj file being build, or one of the sub-directories)

**Comment by ludakuca** [comment]
this is legacy / MVC 5 type project.  I have tsconfig inside the root of the web project.  its just the basic config file that generates when add new typescript file is added and I just added option compileOnSave = true

**Comment by ludakuca** [comment]
@paulvanbrenk I have sent you the email.

It seems like the changing the ProjectDir in the Typescript.targets file to point to the $SolutionRoot, which is TFS reserved word fixed the issue and now everything works as intended.  Please let me know what is the plan for the 2.0 version so that it does not overwrite for me.  Otherwise I will have to pass the ProjectDir variable from the build config.

**Comment by mhegazy** [comment]
We should have a fix for this in the next release. the official targets will not use `ProjectDir` at all.
