### ISSUE TITLE
Property 'fill' does not exist on type 'any[]'

### ISSUE THREAD

**Issue by rajeevkumarsharma** [Microsoft/TypeScript#9436]
**TypeScript Version:**  1.8.0 / nightly (2.0.0-dev.201xxxxx)

**var arr = new Array(10).fill(1);**

```ts
// A *self-contained* demonstration of the problem follows...

```

**Expected behavior:**

**Actual behavior:**

**Comment by kitsonk** [comment]
I assume you are targeting ES5 though you have not provided that information... If you change the target to ES6 those will go away, but TypeScript does not polyfill functionality, so that could would only work in an ES6+ environment.

**Comment by yuit** [comment]
as @kitsonk  mentioned, `fill` function is ES6 specific and if you have `target` ES5 in your tsconfig (or project setting in VS), the editor will load default library which is ES5 library and therefore will not show you `fill` function. if you want to use ES6 library you can use our new compiler flag, `lib` which is available in nightly build

If our understanding is not correct, please complete the information.

**Comment by rajeevkumarsharma** [comment]
Thanks u
