### ISSUE TITLE
How to judge class type?

### ISSUE THREAD

**Issue by keyiis** [Microsoft/TypeScript#9438]
Hi all,I have a question that how to  judge the class type in typescript? pseudo-code as below:
```
function isComponent(ipt:any){
     if(ipt==Component) return true;
     return false;
}
function isAaComponent(ipt:any){
     if(ipt==AaComponent) return true;
     return false;
}
```

**Comment by kitsonk** [comment]
General questions should be filed on StackOverflow or discussed on Gitter or IRC.  The TypeScript issues are for issues (potential bugs) for TypeScript.

This is basic JavaScript and little to nothing to do with TypeScript, if you want to know if an instance is an instance of a class, you use the `instanceof` operator.  For example:

```typescript
function isComponent(ipt: any) {
  return ipt instanceof Component;
}
```

At a technical level it determines if the prototype of `Component` is contained in the prototype chain of the subject of the operator.
