### ISSUE TITLE
insertAdjacent* methods should be part of the Element interface

### ISSUE THREAD

**Issue by davidkmenta** [Microsoft/TypeScript#9440]
**TypeScript Version:**  1.8.10

**Expected behavior:** According to the MDN (https://developer.mozilla.org/en-US/docs/Web/API/Element), insertAdjacent* methods should be part of the Element interface.

**Actual behavior:** insertAdjacent* methods are part of the HTMLElement interface.

**Comment by kitsonk** [comment]
As you have done, filing the issue in TSJS-lib-generator is the proper place, you should/could close this issue here.

**Comment by davidkmenta** [comment]
Oh, I'm sorry. README in TSJS-lib-generator mentions creating issue in this repo.. closing ;)
