### ISSUE TITLE
typescript dependency on typescript@next

### ISSUE THREAD

**Issue by tp** [Microsoft/TypeScript#9441]
**TypeScript Version:**  1.9.0-dev.20160627-1.0

I tried to install typescript only once using https://github.com/mariocasciaro/npm-workspace in a project with many small components, each of whom depend on TypeScript as a dev dependency.

When evaluating the output I saw that the typescript/node_modules folder contained a link pointing to itself again.

After some investigation I found out that this is due to the dependency of TypeScript on `typescript@next` in `package.json`.

Is there a real requirement on this, or this is an oversight that has not yet caused problems?

(I have no issue with that, but some code toolings follow this dependency again and again causing problems. (see also https://github.com/mariocasciaro/npm-workspace/issues/18))

**Comment by yuit** [comment]
We have dependency on typescript@next is used in out build system, `gulp` and `tslint`.

**Comment by tp** [comment]
Interesting, I assumed there was some more sophisticated bootstrapping.

I can resolve this issue on my end by installing in "production" mode (i.e. ignoring the devDependencies).
