### ISSUE TITLE
Allow to run TypeScript (Compiler, Services) in strict mode

### ISSUE THREAD

**Issue by T917820981726** [Microsoft/TypeScript#9449]
**TypeScript Version:**  master

Currently, `tsc.js`, `typescriptServices.js` and `tsserver.js` cannot be run in a strict mode environment due to using the identifier [`static` in `checker.ts`](https://github.com/Microsoft/TypeScript/commit/675d176cef2bfed298ab0250398e905ba76ef58a?diff=unified#diff-c3ed224e4daa84352f7f1abcd23e8ccaR12971).

`static` is a reserved identifier in strict mode, so if you run tsc.js with Node in strict mode, it will fail:
```
C:\Users\VPC\Desktop\TypeScriptOrg\built\local>node --use_strict tsc.js
C:\Users\VPC\Desktop\TypeScriptOrg\built\local\tsc.js:24019
                    var static = ts.forEach(member.modifiers, function (m) { return m.kind === 113; });
                        ^^^^^^
SyntaxError: Unexpected strict mode reserved word
```
 
I think it is reasonable to allow TypeScript to be run in a strict mode environment, by changing the name of the variable.

PS: Is there a reason why the TypeScript sources don't use strict mode in general?
Thanks!

**Comment by HerringtonDarkholme** [comment]
I also encounter this when trying to compress typescript services using Closure compiler.

@mhegazy can I submit a pull request for this? Or you prefer to do it yourself?

**Comment by mhegazy** [comment]
thanks @HerringtonDarkholme.
