### ISSUE TITLE
Relax the rule that ‘super’ call must be the first statement

### ISSUE THREAD

**Issue by jbaron** [microsoft/TypeScript#945]
Right now the compiler always checks if a super call is made, it is indeed the first statement in the constructor. This is even true if the statements before the super call don’t access anything of the object just being constructed. 

It would be nice to not allow access to object variables and methods but allow for other kind of statements. For example the  following gives an warning:

```
constructor(name) {
    var filePath = someGlobalFunction(name); 
    super(filePath);
}
```

while the following is ok:

```
constructor(name) {
    super(someGlobalFunction(name));
}
```

Of course the sequence of commands in the above two example is the same (and one might argue that the second example is the less maintainable/debuggable code). So would be great if the first example wouldn't throw a compiler warning.

I guess the tricky part is to determine which statements are ok to be used before the super call. But I would assume if the statements don’t include this or super keywords, they should be ok.

**Comment by pdfernhout** [comment]
I suggest this issue be reopened based on discussion here: https://github.com/Microsoft/TypeScript-Handbook/pull/214

While it is reasonable in TypeScript to not permit <code>this</code> to be referenced in a constructor before calling super when there are initialized properties or constructor parameter properties, broader restrictions on calling other code don't seem that helpful and can be worked around anyway, like by function calls inside a super call such as <code>super(logThisName(name));</code> where the called function refers to <code>this</code>. As show by an example in the above linked discussion, ES6 permits other code in a constructor before a super call (although accessing <code>this</code> in called code would generate a runtime error before super was called), so in that sense, TypeScript is being more strict than what ES6 permits.

**Comment by pdfernhout** [comment]
As requested by @mhegazy, I have made a new issue for a fresh discussion on this topic (issue #8277).
