### ISSUE TITLE
Dont require declaration files after compile

### ISSUE THREAD

**Issue by laskos** [Microsoft/TypeScript#9456]
I use `import` instead of `<reference ..` to import my `d.ts` files. But after I'd compiled this:

```ts
import 'tests/interfaces/mocha.d.ts';
```

I've got:

```js
"use strict";
require('tests/interfaces/mocha.d.ts');
```

My config file:
```json
{
    "compilerOptions": {
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "module": "commonjs",
        "moduleResolution": "classic",
        "noImplicitAny": false,
        "outDir": "dist",
        "rootDir": ".",
        "sourceMap": true,
        "target": "es5"
    }
}
```

Can i change this behaviour by config?

**Comment by mhegazy** [comment]
do not put the file extension in the require statement. use the module name. so:

```ts
import 'tests/interfaces/mocha';
```

**Comment by laskos** [comment]
@mhegazy I use version `1.8.10`

```ts 
import 'tests/interfaces/mocha';```

works same.

**Comment by mhegazy** [comment]
> Can i change this behavior by config?

no. module names are resource identifiers, they are written in the output the same way they are read. the compiler will not change the import name or extension.
