### ISSUE TITLE
Supporting the narrow type inference assertion operator

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#9457]
## Motivation

String literal types and tuple types require type assertion. Our key typing for its assertion is WET. The narrow type inference assertion operator facilitates assertions of string literal types and tuple types, and makes DRY code.

## String literal types

```ts
<!>'abc'; // 'abc'
```

## Tuple types

```ts
<!>[]; // error, an empty tuple type does not exist.
<!>[0]; // [number]
<!>[0, '']; // [number, string]
```

**Comment by aleksey-bykov** [comment]
related #9217

**Comment by mhegazy** [comment]
you can see the discussion in https://github.com/Microsoft/TypeScript/issues/9217. this has been one of the earlier proposals too. the issue in all of these are 1. undiscovered (you have to be told what it does, you will not figure that on your own), and 2. fairly un-ergonomic, and frankly not so pretty to look at.

**Comment by mhegazy** [comment]
Let's leave one issue with all these suggestions. #9217 has more details. so closing this in favor of #9217.

**Comment by aleksey-bykov** [comment]
pardon my ignorance, but any new syntax is "undiscovered", isn't it?

**Comment by kitsonk** [comment]
Not really... There are several examples where syntax changes are discoverable:

```typescript
const foo = 'bar';
const a = {
    foo: foo
};
const b = {
    foo
};
const c = {
    bar: function () {
        return '';
    }
};
const d = {
    bar() {
        return '';
    }
};
```

Of course some new semantics are initially undiscoverable, like introducing a erasable type system, but once that pattern is established, additional enhancements to it can be discoverable:

```typescript
interface Foo<A, B> { }
interface Foo<A, B extends A> { }
```

**Comment by aleksey-bykov** [comment]
can you elaborate on what exactly in this example demonstrates discoverable syntax? (and to who)

**Comment by kitsonk** [comment]
Prior to ES6, object literals had to be described this way:

```typescript
const foo = 'bar';
const a = {
    foo: foo
};
```

As of ES6, the shorthand syntax was permitted:

```typescript
const b = {
    foo
};
```

That is a "discoverable" change to the syntax.  There is no need to explain what is going on here, it would be largely considered obvious to anyone familiar with the previous syntax and it is likely not to confuse anyone.  The only thing that typically needs to be done is let people know they can use it.

The same for the method shorthand in ES6:

```typescript
/* before ES6 */
const c = {
    bar: function () {
        return '';
    }
};

/* post ES6 */
const d = {
    bar() {
        return '';
    }
};
```

Other than know the syntax is available, there is little else to know, nor can it be easily confused.

The same can be applied.  Prior to TypeScript 1.8, we couldn't use generics as arguments for other generics, but the functionality was added, the syntax supported, and was done in a way that requires no education of the developer expect to let them know it is available:

```typescript
interface Foo<A, B extends A> { }
```

So to the assertion:

> but any new syntax is "undiscovered", isn't it?

The answer is: No,not all new syntax is undiscovered.
