### ISSUE TITLE
Suggestion: show system notification when `tsc --watch` is used

### ISSUE THREAD

**Issue by Knagis** [Microsoft/TypeScript#9467]
We are currently using Visual Studio to develop our library with compileOnSave - whenever the compilation completes, the status bar displays "Output generated successfully.". It is a very small notification but still useful.

However, due to the issue described in #9417 we now have to move away from compileOnSave. One option is to use explicit build however that requires at least me to change my habits :smile: 

The other option is to use `tsc --watch`. This would be preferred however the problem is the notification of when the compilation completes. I must have the console window open at top at all times to see the status of the compilation.

For our project I made a simple improvement to `tsc.js` using [node-notifier](https://www.npmjs.com/package/node-notifier) package:

```
    function reportWatchDiagnostic(diagnostic) {
        // the original code goes here...
        //
        const notifier = require('node-notifier');
        notifier.notify({ title: "TypeScript compiler", message: output.substr(0, output.indexOf(ts.sys.newLine)) });
    }
```

In my opinion this makes the watch mode significantly easier to use.

**Comment by unional** [comment]
It would be better if it provides a hook to add the next action if compile is successful.

Use case:

`ava` to run tests in watch mode:
```js
// package.json
{
  "scripts": {
    "test": "tsc && ava" // currently working
    "watch": "tsc -w && ava" // something similar to this would be nice.
  }
}
```

**Comment by mfour-merickson** [comment]
Wonder if this was ever implemented, cant find anything else on google :-)

**Comment by RyanCavanaugh** [comment]
Doesn't seem to be a lot of demand for this and we'd like to keep the TypeScript package dependency-free as much as possible

**Comment by LaurensRietveld** [comment]
For future reference, you can use this snippet if you want to be notified on errors.

```
tsc -p ./tsconfig.json --watch --preserveWatchOutput |  tee >(while read ln; do if echo "${ln}" | grep -q "Found [^0][0-9]* error"; then notify-send "${ln}"; fi  ; done)
```

Notes: 
- This only notifies on errors 
- If the error message changes, this breaks
- Working on linux (ubuntu)
