### ISSUE TITLE
Visual Studio: unexistent file causes ambiguous error

### ISSUE THREAD

**Issue by SaschaNaz** [Microsoft/TypeScript#9471]
**TypeScript Version:**  master branch

**Repro:**

1. Make a new empty JS project
2. Add any two new TS files on VS
3. Remove one of the TS file outside of VS (via File Explorer, PowerShell, or anything)
4. Build

**Expected behavior:**

An error with "File not found" message

**Actual behavior:** 

Code: MSB6006	
Description: "tsc.exe" exited with code 1.
Project: App1
File: C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\TypeScript\Microsoft.TypeScript.targets
Line: 242

**Comment by jwbay** [comment]
This bit me really badly last week. Took me forever to figure out what was going on.

**Comment by mhegazy** [comment]
Running tsc.exe directly issues two messages:

```txt
Cannot open file 'c:\users\mhegazy\documents\visual studio 2015\Projects\TypeScriptHTMLApp45\TypeScriptHTMLApp45\file1.ts'.
error TS6053: File 'c:/users/mhegazy/documents/visual studio 2015/Projects/TypeScriptHTMLApp45/TypeScriptHTMLApp45/file1.ts' not found.
```

only one should be issues, the second. the first is not well formatted, and that throws off msbuild.
