### ISSUE TITLE
ignoreFileNamePattern apply to non project context path(absolute) with default tsconfig.include section

### ISSUE THREAD

**Issue by agaricus** [Microsoft/TypeScript#9472]
**TypeScript Version:**  nightly (2.0.0-dev.20160701)

**Code**
```ts    
// Skip over any minified JavaScript files (ending in ".min.js")
// Skip over dotted files and folders as well
const ignoreFileNamePattern = /(\.min\.js$)|([\\/]\.[\w.])/;
```
[https://github.com/Microsoft/TypeScript/blob/master/src/compiler/commandLineParser.ts#L692-L694](url)

but this _file_ is absolute and ignored this file
[https://github.com/Microsoft/TypeScript/blob/master/src/compiler/commandLineParser.ts#L991](url)
and 

.outer
└─ project
...├─ test.ts
...└─ tsconfig.json

**Expected behavior:**
project scope file match
emit .outer/project/test
**Actual behavior:**
absolute scope file match
 ignore .outer/project/test

**Comment by agaricus** [comment]
#9451 bad ignoreFileNamePattern RegExp

**Comment by mhegazy** [comment]
@riknoll can you take a look. if a dotted file or minifided file path is listed explicitly in the include list it should always be included regardless of the check.

**Comment by agaricus** [comment]
this solved, thq @riknoll
