### ISSUE TITLE
Block comments don't get created as a "block" and don't continue on new lines

### ISSUE THREAD

**Issue by josh-endries** [microsoft/TypeScript#9480]
**TypeScript Version:**  1.8.30

**Code**

``` ts
/*
```

Or:

``` ts
/**
```

**Expected behavior:**

``` ts
/*
 * <cursor>
 */
```

The `/**` variant works correctly here, but not with the next step.

And, after pressing Enter:

``` ts
/*
 *
 * <cursor>
 */
```

**Actual behavior:** 

``` ts
/*
<cursor>
```

(Your template has no "description" section, which seems valuable. I'm adding one. Here it comes!)

**Description:**

I'm not really sure if this belongs here or [maybe here](https://github.com/dotnet/roslyn/issues/2077), but this doesn't work in VS "14.0.25123.00 Update 2" with TS or TSX or JSX files. It's impressively annoying. It _does_ work with JS.

When initially adding a block comment, it doesn't fill in the "blank" line with just a `<indent> *` prefix (note the space), and upon pressing enter, it doesn't insert the `<indent> *` for the new line as a continuation of the comment.

The "doc" code block format (`/**`) starts out correctly, adding a single `*` line and closing `*/` line and placing the cursor on the single `*` line, however when adding a new line it doesn't prefix the line with `<indent> *` as I would expect. Virtually every other editor I've used (that I can remember) does block comments this way, so I don't think my expectation is unwarranted, but maybe so...

**Comment by DanielRosenwasser** [comment]
We do auto-fill for the second star on `/**` if the following thing can be JSDoc'd (see some of the checklist on #4447). That said, I don't remember if there's a good reason why we don't always fill in the comment.

Adding a new `*` when pressing enter in a multi-line comment is something we were looking at but I can't find the issue tracking it.

**Comment by RyanCavanaugh** [comment]
This has been fixed
