### ISSUE TITLE
Incompatible between ES6-promise thenable and recent PromiseLike change in lib.d.ts 

### ISSUE THREAD

**Issue by yuit** [Microsoft/TypeScript#9481]
Our Angular2 code-base of RWC uses es6-promise for defining Promise interface as well as PromiseLike definition from our lib.d.ts. With our recent change, `Thenable` and `PromiseLike` is no longer compatible.

**Comment by mhegazy** [comment]
@rbuckton can you see if reverting the changes to PromiseLike would do?

**Comment by rbuckton** [comment]
I reviewed this with @yuit, reverting the change to PromiseLike fixes the issue, and does not impact the improved typing for Promise.

**Comment by mhegazy** [comment]
Fixed by https://github.com/Microsoft/TypeScript/pull/9484#issuecomment-230081306
