### ISSUE TITLE
Build failed with npm install not working

### ISSUE THREAD

**Issue by basarat** [Microsoft/TypeScript#9487]
Today's NTypeScript build failed : https://travis-ci.org/TypeStrong/ntypescript/builds/141776988#L207

Something wrong with `@types` automation? :rose:

**Comment by mhegazy** [comment]
Should be fixed by https://github.com/Microsoft/types-publisher/pull/44. publishing now.

**Comment by basarat** [comment]
Yup, passed https://travis-ci.org/TypeStrong/ntypescript/builds/141816682 :rose: :heart:
