### ISSUE TITLE
`npm install @types/react-router` 

### ISSUE THREAD

**Issue by basarat** [Microsoft/TypeScript#9488]
There is a bug in `typings` http://stackoverflow.com/questions/38157103/dtreact-router-error-ts2503-cannot-find-namespace-historymodule so I thought I'd give `@types` a go. However that didn't do a stellar job either. 

```
npm install @types/react-router
tsc --init
tsc -p .
```

Errors: 

```ts
node_modules/@types/react-router/index.d.ts(10,20): error TS2307: Cannot find module './lib/Router'.
node_modules/@types/react-router/index.d.ts(11,18): error TS2307: Cannot find module './lib/Link'.
node_modules/@types/react-router/index.d.ts(12,23): error TS2307: Cannot find module './lib/IndexLink'.
node_modules/@types/react-router/index.d.ts(13,27): error TS2307: Cannot find module './lib/IndexRedirect'.
node_modules/@types/react-router/index.d.ts(14,24): error TS2307: Cannot find module './lib/IndexRoute'.
node_modules/@types/react-router/index.d.ts(15,22): error TS2307: Cannot find module './lib/Redirect'.
node_modules/@types/react-router/index.d.ts(16,19): error TS2307: Cannot find module './lib/Route'.
node_modules/@types/react-router/index.d.ts(17,26): error TS2307: Cannot find module './lib/History'.
node_modules/@types/react-router/index.d.ts(18,23): error TS2307: Cannot find module './lib/Lifecycle'.
node_modules/@types/react-router/index.d.ts(19,26): error TS2307: Cannot find module './lib/RouteContext'.
node_modules/@types/react-router/index.d.ts(20,28): error TS2307: Cannot find module './lib/browserHistory'.
node_modules/@types/react-router/index.d.ts(21,25): error TS2307: Cannot find module './lib/hashHistory'.
node_modules/@types/react-router/index.d.ts(22,23): error TS2307: Cannot find module './lib/useRoutes'.
node_modules/@types/react-router/index.d.ts(23,30): error TS2307: Cannot find module './lib/RouteUtils'.
node_modules/@types/react-router/index.d.ts(24,31): error TS2307: Cannot find module './lib/PatternUtils'.
node_modules/@types/react-router/index.d.ts(25,27): error TS2307: Cannot find module './lib/RouterContext'.
node_modules/@types/react-router/index.d.ts(26,23): error TS2307: Cannot find module './lib/PropTypes'.
node_modules/@types/react-router/index.d.ts(27,19): error TS2307: Cannot find module './lib/match'.
node_modules/@types/react-router/index.d.ts(28,30): error TS2307: Cannot find module './lib/useRouterHistory'.
node_modules/@types/react-router/index.d.ts(29,33): error TS2307: Cannot find module './lib/createMemoryHistory'.
```

Where should people put `@types` issues? :rose:

**Comment by JabX** [comment]
I have the same issue with the `history` module. It looks like the problem is that `npm install @types/**` only takes the `index.d.ts` file and ignores the `lib` directory.

**Comment by rhmoller** [comment]
I don't think the problem is with `npm install`. It is more likely the tool that has moved the typings from DefinitelyTyped to @types that is the problem

**Comment by JabX** [comment]
The `types 2.0` branch of DefinetelyTyped has all the files, and I assumed it was published to NPM from there.

**Comment by rhmoller** [comment]
Looks like the types-publisher does not scan for .d.ts in subfolders.
https://github.com/Microsoft/types-publisher/blob/master/src/lib/definition-parser.ts#L74

**Comment by dalgard** [comment]
How can I get this fix? I've installed `@types/react-router` today and the error still occurs.

**Comment by Zyphrax** [comment]
I am having the same problem, how can we fix this?

**Comment by RyanCavanaugh** [comment]
@andy-ms can you see what's going on?

**Comment by matthew-rister** [comment]
This is marked as fixed, but I still get these compilation errors with using the latest react-router typescript definitions when using npm install @types/react-router --save

**Comment by matthew-rister** [comment]
Also looks like there is another open issue detailing this exact experience #10686

**Comment by mhegazy** [comment]
> This is marked as fixed, but I still get these compilation errors with using the latest react-router typescript definitions when using npm install @types/react-router --save


```sh
c:\test\9488>npm install @types/react-router
test@1.0.0 c:\test\9488
`-- @types/react-router@2.0.41
  +-- @types/history@2.0.41
  `-- @types/react@0.14.55

c:\test\9488>echo import { History } from 'react-router'; > index.ts

c:\test\9488>tsc --v
Version 2.1.4

c:\test\9488>tsc --init

c:\test\9488>tsc

c:\test\9488>echo %ERRORLEVEL%
0
```

**Comment by matthew-rister** [comment]
As detailed by this post, it only works if module resolution is set to node in tsconfig. https://github.com/DefinitelyTyped/DefinitelyTyped/issues/10686. I was able to get around this by manually changing the imports of "history" to the relative path of the @types/history index definition

**Comment by mhegazy** [comment]
the resolution of these packages assumes a node-style resolution. so you need to use `"moduleResolution": "node"`

**Comment by matthew-rister** [comment]
We use AMD and therefore cannot use node module resolution. TypeScript definitions should be robust enough to handle all module types. Can we re-open this?

**Comment by andy-ms** [comment]
The other issue that you linked to is still open and we're planning to fix it.

**Comment by mhegazy** [comment]
i miss spoke. thanks @andy-ms for the correction. the AMD should work. this issue seems to be caused by the @types package authoring. @andy-ms is fixing it on Definitely Typed.
