### ISSUE TITLE
ImageData.data should be a Uint8ClampedArray, not a number[]

### ISSUE THREAD

**Issue by tomtung** [Microsoft/TypeScript#949]
In version 1.0.1, ImageData.data was a Uint8Array. In version 1.1 it becomes a number[]. Seems like it should be a Uint8ClampedArray.

Reference:
https://developer.mozilla.org/en-US/docs/Web/API/ImageData#Browser_compatibility

**Comment by darrylring** [comment]
Other than simply leaving an ImageData object untyped, is there a workaround for this?

A complication here is that Firefox 38 already uses an ES6 `Uint8ClampedArray` for `ImageData.data` but doesn't support ES6's `class`. Maybe this is a separate issue, but is it possible to use es6.d.ts while still emitting ES5 JavaScript?

**Comment by mhegazy** [comment]
> is it possible to use es6.d.ts while still emitting ES5 JavaScript?

@darrylring, yes. just add a reference to lib.es6.d.ts either on the commandline or using a /// reference.

**Comment by mhegazy** [comment]
@zhengbli can we get this in soon?

**Comment by zhengbli** [comment]
Sure I'll send a PR soon.
