### ISSUE TITLE
compile in browser ? 

### ISSUE THREAD

**Issue by gbaumgart** [Microsoft/TypeScript#9490]
Hi,

i found a few repos doing that but they seem all outdated. I found also posts about webpack but still I am not sure that's the official way to compile TS in the browser (I am accepting the potential problems). 

Your official web-page has an editor. Is there the source code for this somewhere ? 

thanks a lot.

**Comment by kitsonk** [comment]
The website's editor is based on [Monaco Editor](https://github.com/Microsoft/monaco-editor).

**Comment by gbaumgart** [comment]
Whoa, Kitsonk to the rescue, again. thanks man.
g

**Comment by basarat** [comment]
> compile in browser 

Don't recommend it. But makes for a good demo : https://github.com/basarat/typescript-script ;) `script` tag in TypeScript :rose:

**Comment by gbaumgart** [comment]
yup, confirmed, TS in Browser renders the whole consumer app useless, FPS down to 5-10, and on low-spec machines its pretty unusable.
g

**Comment by aluanhaddad** [comment]
@gbaumgart this is a very nice development workflow. Just don't use it in production. Try https://github.com/frankwallis/plugin-typescript it is awesome!

**Comment by gbaumgart** [comment]
@aluanhaddad thanks a lot. i dropped the whole idea. just way too much deps/ballast at the end.
