### ISSUE TITLE
Add JSX spread children

### ISSUE THREAD

**Issue by calebmer** [Microsoft/TypeScript#9495]
The JSX specification was just updated (here: https://github.com/facebook/jsx/pull/59) to add for JSX spread children. See the rationale here: https://github.com/facebook/jsx/issues/57

What would be involved in adding support for this new feature of the JSX specification to the TypeScript parser?

**Comment by mhegazy** [comment]
the change should not be that big to the parser, there are changes needs to the checker, and the emitter as well.
PRs are welcomed

**Comment by sandersn** [comment]
#11591 adds this feature.
