### ISSUE TITLE
`lib` es6 loses window and other dom stuff

### ISSUE THREAD

**Issue by basarat** [Microsoft/TypeScript#9500]
ts: 

```ts
console.log(window);
```
tsconfig.json: 
```json
{
  "compilerOptions": {
    "lib": [
      "es6"
    ]
  }
}

```

compile: 
```
tsc -p .
```

**Expected behavior:**
Works!

**Actual behavior:** 
Error cannot find name `window`. 

refs https://github.com/Microsoft/TypeScript/issues/6974 :rose:

**Comment by mhegazy** [comment]
you have to choose it. so 
```json
{
  "compilerOptions": {
    "lib": [
      "es6",
      "dom"
    ]
  }
}
```

here are more details:
- es6/es5/es2015/es2016/es2017 -- built in JS definitions.
- dom -- DOM definitions
- webworkers -- Web worker definitions
- scripthost -- widows Script Host


complete list is in https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#including-built-in-type-declarations-with---lib

**Comment by basarat** [comment]
Thanks for that. I've fixed up my understanding / code etc. Also mentioned it here : https://basarat.gitbooks.io/typescript/content/docs/types/lib.d.ts.html#lib-option

Minor: the link https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#including-built-in-type-declarations-with---lib mentions `DOM if you are working on a node project using --lib es5,es6`. Having a look at the code `es6` automatically references `es5` ([as seen here](https://github.com/Microsoft/TypeScript/blob/c2730ce659733b89b8599440837a3046ca734a75/lib/lib.es2015.d.ts#L26)) so really it should be just `--lib es6`. 

That said I'd PR but it seems its not linked to the page here : https://github.com/Microsoft/TypeScript-wiki/blob/master/What's-new-in-TypeScript.md :rose:
