### ISSUE TITLE
Duplicate Identifier 

### ISSUE THREAD

**Issue by zeeshanjan82** [Microsoft/TypeScript#9501]
I am using Typescript with typings, and everything for me was working fine until I decided to use async/await instead of Promises in Node.js. When I replaced the 'es5' to 'es6' inside the tsconfig.json file then I started getting 'Duplicate Identifier' errors. I have attached the screenshot of the errors as well
![error](https://cloud.githubusercontent.com/assets/8342604/16550401/bb678a52-41c7-11e6-9f1a-10139b71c7db.png)

**Comment by mhegazy** [comment]
with target ES6, the ES6 definitions are included in your compilation. Promises are part of the ES6 spec, so the es6 library has that. you probably are using es6-promise through typings, you can remove this.
