### ISSUE TITLE
should not remove decorator tag in emitted declaration files

### ISSUE THREAD

**Issue by WanderWang** [Microsoft/TypeScript#9502]
use case : 

We are developing a Visual IDE . Developer can setup properties in a property panel

```
class Data {

    @ide
    public key1:string;

    @ide
    public key2:string;

    public key3_do_not_in_ide:string;
}

```

 developer can setup properties in IDE panel such as this

Properties | Value 
------------ | -------------
 key1 | value1
 key2 | value2

we create a tss instance to analysis decorator and generate a data grid in our IDE . It works fine now .

But it can only works well on typescript source file , not in typescript  declaration files because of  d.ts file remove decorator tag .

please consider this design : 

```

class Data {

    @ide
    public key1:string;

    @ide
    public key2:string;

    public key3_do_not_in_ide:string;
}

```

generate to 

```

declare class Data {

    // do not remove "ide" decorator
    @ide
    public key1:string;

    @ide
    public key2:string;

    public key3_do_not_in_ide:string;
}

```

**Comment by zcxp** [comment]
Need it too!

**Comment by aluanhaddad** [comment]
I think you are looking for ambient decorators #2900 which are slated for release in TypeScript 2.1

**Comment by mhegazy** [comment]
decorators are expressions, expressions can not be preserved in the declaration file. consider this example:

```ts
@foo(a + b);
export class C {}
```

as noted by @aluanhaddad, #2900 is tracking ambient decorators.
