### ISSUE TITLE
Typeof comparison expression should check right hand side value

### ISSUE THREAD

**Issue by tinganho** [Microsoft/TypeScript#9506]
As I understood `typeof` operator can only return `undefined`, `object`, `boolean`, `number`, `string`, `symbol`, `function.`

If the RHS is a string literal, I think it should check against the above values and throw an error on:
```ts
const str = 'str';
if (typeof str === 'd') {// error right hand side can only be `undefined`, `object`, ...
}
```

**Comment by mhegazy** [comment]
There are two parts here, first type of the return type of `typeof` operators to be `"undefined" | "object" | "boolean" | "number" | "string" | "symbol" | "function"` instead of `string` which sounds safe.

and two is to make a comparison between two a string literal type and a string literal an error, which would be a breaking change and prevent defensive coding patterns.

**Comment by DanielRosenwasser** [comment]
> There are two parts here, first type of the return type of `typeof` operators to be `"undefined" | "object" | "boolean" | "number" | "string" | "symbol" | "function"` instead of `string` which sounds safe.

For the record, in the spec's section on [The `typeof` Operator](https://tc39.github.io/ecma262/#sec-typeof-operator):

> Type of `val` | Result
> ----|----
Undefined | "undefined"
Null | "object"
Boolean | "boolean"
Number | "number"
String | "string"
Symbol | "symbol"
Object (ordinary and does not implement [[Call]]) | "object"
Object (standard exotic and does not implement [[Call]]) | "object"
Object (implements [[Call]]) | "function"
Object (non-standard exotic and does not implement [[Call]]) | Implementation-defined. Must not be "undefined", "boolean", "function", "number", "symbol", or "string".

> NOTE
Implementations are discouraged from defining new typeof result values for non-standard exotic objects. If possible "object" should be used for such objects.

**Comment by RyanCavanaugh** [comment]
Good comments from Brian in #10594

**Comment by RyanCavanaugh** [comment]
Until this is normatively specified we don't want to encode this into the type system. A TSLint rule would be very easy to write.

**Comment by RyanCavanaugh** [comment]
We did do this! 🎉
