### ISSUE TITLE
Autocomplete for String Union Types

### ISSUE THREAD

**Issue by Meligy** [Microsoft/TypeScript#9512]
Let's say I have the following type:

```typescript
 type Cars = 'Ferrari' | 'Volvo' | 'Porsche';
```

It will be awesome if I can treat it like an enum, meaning I can write `Cars.      ` and get intellisense for `Ferari`, `Volve`, and `Porsche`.

Today, you do not get that.

You can have funky workarounds to make the number based enum become a string

Like this ([runnable sample](http://www.typescriptlang.org/play/index.html#src=enum%20Cars%20%7B%0A%09Ferrari%20%3D%20%3Cany%3E%20%22Ferrari%22%2C%0A%09Volvo%20%3D%20%3Cany%3E%20%22Volvo%22%2C%0A%09Porsche%20%3D%20%3Cany%3E%20%22Porsche%22%0A%7D%0A%0A%0A%2F%2F%20Delete%20the%20%60.Ferrari%3B%60%20piece%2C%20%0A%2F%2F%09%09then%20write%20a%20%60.%60%2C%20and%20see%20the%20autocomplete%0Avar%20car%20%3A%20Cars%20%3D%20Cars.Ferrari%3B%0A%0A)):
```typescript
enum Cars {
	Ferrari = <any> "Ferrari",
	Volvo = <any> "Volvo",
	Porsche = <any> "Porsche"
}
```
But that's hacking, even though it opens the question why not make this a core feature.

Or, you can use namespaces, like ([runnable sample](http://www.typescriptlang.org/play/index.html#src=type%20Cars%20%3D%20'Ferrari'%20%7C%20'Volvo'%20%7C%20'Porsche'%3B%0Anamespace%20Cars%20%7B%0A%09export%20const%20Ferrari%20%3A%20Cars%20%3D%20%22Ferrari%22%3B%0A%09export%20const%20Volvo%20%3A%20Cars%20%3D%20%22Volvo%22%3B%0A%09export%20const%20Porsche%20%3A%20Cars%20%3D%20%22Porsche%22%3B%0A%7D%0A%0A%0A%2F%2F%20Delete%20the%20%60.Ferrari%3B%60%20piece%2C%20%0A%2F%2F%09%09then%20write%20a%20%60.%60%2C%20and%20see%20the%20autocomplete%0Avar%20car%20%3A%20Cars%20%3D%20Cars.Ferrari%3B%0A%0A)):
```typescript
type Cars = 'Ferrari' | 'Volvo' | 'Porsche';
namespace Cars {
	export const Ferrari : Cars = "Ferrari";
	export const Volvo : Cars = "Volvo";
	export const Porsche : Cars = "Porsche";
}
```
But obviously, this way you can get into errors, with both the type and namespace potentially going out of sync due to human error.

Ideally, the very first line should in itself allow you to have autocomplete, similar to what enum does. Or alternatively of course support `string` `enum` types.

**Comment by mhegazy** [comment]
> But that's hacking, even though it opens the question why not make this a core feature.

that is the plan. we need to come up with a detailed proposal. we have talked about this in the past in https://github.com/Microsoft/TypeScript/issues/5740 and https://github.com/Microsoft/TypeScript/issues/5943.

the feature is tracked by https://github.com/Microsoft/TypeScript/issues/1206



For auto completions in IDE's this already coverd by https://github.com/Microsoft/TypeScript/issues/8428

![image](https://cloud.githubusercontent.com/assets/8000722/16599267/6b35f484-42b6-11e6-8bee-bd9c52991b5d.png)

**Comment by mhegazy** [comment]
unless this is more to this request that allowing string enums, i would close this in favor of https://github.com/Microsoft/TypeScript/issues/1206.
