### ISSUE TITLE
Better JavaScript completion thru JSDOC

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#9518]
_From @slowmove on July 5, 2016 6:28_

It would be very interesting to make the intellisense, completion and documentation popup (for a method for instace) better thru the ability of VSCode to better understand standard jsdoc like ```@description``` and such to give some text description to how to use a function, not only ```@param``` and parameter typing.

_Copied from original issue: Microsoft/vscode#8747_

**Comment by dbaeumer** [comment]
_From @joaomoreno on July 5, 2016 9:9_

@dbaeumer Is there already a feature request for this?

**Comment by dbaeumer** [comment]
If so then in the TS land. I will move the issue since the feature request needs to be implemented there.

**Comment by mhegazy** [comment]
@slowmove what do you have in mind? we already have support for JSDoc today, see https://github.com/Microsoft/TypeScript/wiki/JsDoc-support-in-JavaScript

**Comment by slowmove** [comment]
@mhegazy I am not able to get the description fetched neither as plain text or with the ```@description``` tag.
![skarmavbild 2016-07-06 kl 07 37 05](https://cloud.githubusercontent.com/assets/624182/16608483/9f8ed4da-434c-11e6-8016-8789d1876e9d.png)

**Comment by mhegazy** [comment]
I see the issue now. this is a bug, the comments are read correectlly, they are not sent to in the signature info though.

![image](https://cloud.githubusercontent.com/assets/8000722/16628662/7dcedf78-4367-11e6-8458-55ce4b8d9089.png)

**Comment by mhegazy** [comment]
@zhengbli can you take a look.

**Comment by zhengbli** [comment]
I am getting these when I try to repro the case:
![1](https://cloud.githubusercontent.com/assets/1171301/17766358/9ff010f6-64df-11e6-9c7a-10eb01170c13.PNG)
![screenshot 1](https://cloud.githubusercontent.com/assets/1171301/17766363/a39492cc-64df-11e6-80c6-b6c29144b2dc.png)

Are these the desired results?

**Comment by slowmove** [comment]
@zhengbli It works when in the same file, though not when exporting and use it in another file. See image 1 vs 2 below.

![skarmavbild 2016-08-18 kl 10 17 09](https://cloud.githubusercontent.com/assets/624182/17766766/ff92d032-652c-11e6-9cfd-055ea13e1f19.png)

![skarmavbild 2016-08-18 kl 10 18 40](https://cloud.githubusercontent.com/assets/624182/17766807/2e67bd1e-652d-11e6-9777-c98a5da94e8d.png)

**Comment by slowmove** [comment]
Though I do understand this is correct per se (module exports is a object with properties) I'll see this as a quite usual way of exporting methods public in Node.
