### ISSUE TITLE
tsc works, tsc $file doesnt

### ISSUE THREAD

**Issue by a93ushakov** [Microsoft/TypeScript#9521]
**TypeScript Version:**   1.8.10

I am study `angular 2` now. Here is demo repo: [link](https://github.com/a93ushakov/angular2-quickstart).

`tsc` command works well from any subdirectory, but if specify files `tsc file.ts` it shows usual for `typings` problem error:
```sh
...
../../node_modules/@angular/core/src/linker/dynamic_component_loader.d.ts(108,135): error TS2304: Cannot find name 'Promise'.
../../node_modules/@angular/core/src/linker/systemjs_component_resolver.d.ts(18,53): error TS2304: Cannot find name 'Promise'.
../../node_modules/@angular/core/src/linker/systemjs_component_resolver.d.ts(26,53): error TS2304: Cannot find name 'Promise'.
../../node_modules/@angular/platform-browser-dynamic/index.d.ts(81,90): error TS2304: Cannot find name 'Promise'.
../../node_modules/@angular/platform-browser-dynamic/index.d.ts(85,99): error TS2304: Cannot find name 'Promise'.
../../node_modules/@angular/platform-browser-dynamic/index.d.ts(89,99): error TS2304: Cannot find name 'Promise'.
../../node_modules/rxjs/Observable.d.ts(10,66): error TS2304: Cannot find name 'Promise'.
../../node_modules/rxjs/Observable.d.ts(66,60): error TS2304: Cannot find name 'Promise'.
../../node_modules/rxjs/Observable.d.ts(66,70): error TS2304: Cannot find name 'Promise'.

```

`typings` directory place is irrelevant.

**Comment by mhegazy** [comment]
if no arguments specified to `tsc` it picks up the configuration file from the containing folder. if you specify a file argument, then the config file will not be picked up. the errors you are getting is because some configurations (as specified in your config file) are not passed on the commandline.

**Comment by mhegazy** [comment]
see http://www.typescriptlang.org/docs/handbook/tsconfig-json.html for more details.

**Comment by mhegazy** [comment]
` tsc file.ts`  =>  **does not** use `tsconfig.json`

`tsc`   => uses `tsconfig.json`

**Comment by a93ushakov** [comment]
Is there any way to specify config?

**Comment by mhegazy** [comment]
```cmd
tsc --p path\to\tscofig.json
```

all what i mentioned above is listed in http://www.typescriptlang.org/docs/handbook/tsconfig-json.html. please check it out.

**Comment by a93ushakov** [comment]
So, there is no way to archive incremental build via `make` by specifying list of files for compilation?

**Comment by mhegazy** [comment]
you can, but you have to pass the arguments on the commandline along with the files.

**Comment by a93ushakov** [comment]
```sh
a93ushakov@venom:~/lab/angular2_boilerplate/app/custom$ tsc -p tsconfig.json main.ts 
error TS5042: Option 'project' cannot be mixed with source files on a command line.
```

**Comment by mhegazy** [comment]
you can, **but you have to pass the arguments on the commandline** along with the files.

**Comment by a93ushakov** [comment]
I had tried to replace this config 
```json
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "sourceMap": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": false
  }
}
```

with this command
```sh
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "sourceMap": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": false
  }
}
```

But error still here.

**Comment by mhegazy** [comment]
when you use tsconfig.json all files in this directory will be included. so from the error i am guessing there is a definition file for es6-promise or es6-shims that was not included in the compilation.

one easy way to know what files were picked up using `tsconfig.json` is `--listFiles`.

```cmd
tsc --p path/to/tsconfig.json --listFiles
```
