### ISSUE TITLE
Visual Studio 2015 Crash when debugging IE (no TypeScript in project)

### ISSUE THREAD

**Issue by jonstelly** [Microsoft/TypeScript#9524]
**TypeScript Version:**  1.8.34.0

**VS2015:**
Update 3
ReSharper 2016.1.2
Node.js Tools 1.2
TypeScript 1.8.34.0

**Expected behavior:**
Configure VS2015 to debug web application using Internet Explorer.  TypeScript 1.8.34.0 extension for VS2015 but project does not contain any TypeScript or TypeScript source maps.  Expect IE to launch and debugger to attach

**Actual behavior:** 
VS2015 crashes after browser launches with the following error in event log:

```
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at TypeScriptDebugEngine.SymbolProvider.SourceMapManager.UnloadSourceMap(Microsoft.VisualStudio.Debugger.DkmModuleInstance)
   at TypeScriptDebugEngine.SymbolProvider.SourceMapManager.Microsoft.VisualStudio.Debugger.ComponentInterfaces.IDkmModuleInstanceUnloadNotification.OnModuleInstanceUnload(Microsoft.VisualStudio.Debugger.DkmModuleInstance, Microsoft.VisualStudio.Debugger.DkmWorkList, Microsoft.VisualStudio.Debugger.DkmEventDescriptor)
   at Microsoft.VisualStudio.Debugger.EntryPoint.IDkmModuleInstanceUnloadNotification_OnModuleInstanceUnload(IntPtr, IntPtr, IntPtr, IntPtr)

```

**Comment by mhegazy** [comment]
This should be fixed in the next release.

**Comment by mhegazy** [comment]
We are looking into shipping it as a VS update as well. will post back once we have an ETA.

**Comment by kkohler2** [comment]
Same error when doing remote debugging a JavaScript / UWP app that DOES have TypeScript files and source maps.  I tried remote debugging same project on two different computers with same result - Visual Studio crashes with remote debugging.  Same error in EventLog.

**Comment by mhegazy** [comment]
Should be available in the next TS release, as well as the next VS 2015 update.

**Comment by hem19** [comment]
I can see the label 'Fixed' mentioned for this bug, is this issue fixed?
 I have VS2015 update 3 with latest patch installed, still while debugging typescript it keeps on crashing. 
Is there any specific patch I need to apply in my machine to make it work?

**Comment by mhegazy** [comment]
Can you give TS 2.0 beta a try (https://www.microsoft.com/en-us/download/details.aspx?id=48593)
