### ISSUE TITLE
Errors are output to stdout

### ISSUE THREAD

**Issue by sebastien** [Microsoft/TypeScript#9526]
**TypeScript Version:**   2.0.0-dev.20160705

I have a module that compiles correctly but where an import contains an error/warning. When compiling this module `viewer.ts`, both code and error got output to *stdout*:

```
$ tsc --module amd --outFile /dev/stdout lib/ts/viewer.ts 
/// <reference path="../../node_modules/@types/d3/index.d.ts" />
/// <reference path="../../node_modules/@types/three/index.d.ts" />
define("viewer", ["require", "exports"], function (require, exports) {
    "use strict";
    console.log("Hello, world!");
    var viewer;
    (function (viewer) {
        var Viewer = (function () {
            function Viewer() {
            }
            return Viewer;
        }());
    })(viewer || (viewer = {}));
});
lib/ts/viewer.ts(1,21): error TS2306: File 'lib/ts/d3.ts' is not a module.
```

as you can see, the trailing line below should be output on *stderr*, not as part of *stdout*.

```
lib/ts/viewer.ts(1,21): error TS2306: File 'lib/ts/d3.ts' is not a module.
```

See also #1226

**Comment by DanielRosenwasser** [comment]
See #615 for a previous discussion. To quote @mhegazy:

> This is actually by design. writing errors to standard error was a wrong choice in the first place, as the errors are not errors from the compiler (e.g. crashes) but rather user errors, and the user would expect them as part of the normal output of the compiler.

The new behavior is consistent with other compilers as well.

**Comment by sebastien** [comment]
OK, I checked and `tsc` returns an exit status of `2` in that case, so at least we can disambiguate.
