### ISSUE TITLE
Duplicate identifier error on `bind` usage 

### ISSUE THREAD

**Issue by basarat** [Microsoft/TypeScript#9533]
Migrating a JS project to TS. With TypeScript latest: 

The following *js* file errors: `Duplicate Identifier`. 

```js
class Foo {
  constructor(){
    this.foo = this.foo.bind(this);
  }
  foo(){}
}
```

Note : this does not happen in TypeScript stable :rose:
PSPS: using ` = ()=>` will error with "property initializer not allowed in js"

**Comment by sandersn** [comment]
This is probably related to @andy-ms' recent changes to allow renaming and find-all-definition of `this` expressions.

**Comment by mhegazy** [comment]
looks fixed in latest.
