### ISSUE TITLE
String literal type widened to string in return value of async function

### ISSUE THREAD

**Issue by wmrowan** [Microsoft/TypeScript#9535]
**TypeScript Version:**  1.8.10

**Code**

```ts
interface Result {
  type: 'error' | 'result';
}

function synchronous(): Result {
  return {
    type: 'result',
  };
}

async function asynchronous(): Promise<Result> {
  return {
    type: 'result',
  };
}
```

**Expected behavior:**

No compilation errors.

**Actual behavior:** 

```bash
$ tsc -t es6 example.ts
example.ts(12,10): error TS2322: Type '{ type: string; }' is not assignable to type 'Result'.
  Types of property 'type' are incompatible.
    Type 'string' is not assignable to type '"error" | "result"'.
      Type 'string' is not assignable to type '"result"'.
```

Field `result` in the return value in the function `synchronous` is correctly narrowed to the type `"result"` and type checking passes. In the function `asynchronous`, however, the field `result` is widened to `string`, resulting in a compilation error.

I can fix this example by introducing a seemingly redundant type cast on the field `result`.

```ts
async function asynchronous(): Promise<Result> {
  return {
    type: 'result' as 'result',
  };
}
```

**Comment by mhegazy** [comment]
This is the same issue as https://github.com/Microsoft/TypeScript/issues/5165. it should be fixed in `typescript@next`, and will be in the next release (TS 2.0).
