### ISSUE TITLE
Autoformat multiple exports

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#9540]
_From @ayoubdev on July 5, 2016 10:10_

- VSCode Version: 1.3.0-insider (2016-07-04)
- OS Version: Windows 10

Hello everyone,

I wonder if it's possible to change indentation behavior for javascript multiple exports (like multiple imports one). Indeed, autoformat feature currently outputs following:
```jsx
import {
	InjectEventEmitter,
	ProvideEventEmitter
} from "./decorator.js";

export {
Helper,
CustomPropTypes
};
```

Desired output:
```jsx
import {
	InjectEventEmitter,
	ProvideEventEmitter
} from "./decorator.js";

export {
	Helper,
	CustomPropTypes
};
```

_Copied from original issue: Microsoft/vscode#8755_

**Comment by dbaeumer** [comment]
Moving to TS.

**Comment by mhegazy** [comment]
This should be working correctly in latest.
