### ISSUE TITLE
error TS2347: Untyped function calls may not accept type arguments

### ISSUE THREAD

**Issue by RichardJECooke** [Microsoft/TypeScript#9547]
**TypeScript Version:**  1.8.0

**Code**

This class with a generic function

```ts
class ResponseHelper {
  getSuccessResponse<T>(dataToReturn : T, newEncryptedAuthToken : string) : string {
    const result : IResponse<T> =
    {     
      'errorMessage': null,
      'data': dataToReturn
    }
    return JSON.stringify(result);
  }
}
export = new ResponseHelper();
```

when called like this:
```ts
resolve(responseHelper.getSuccessResponse<string>(externalPaymentId, newJwt));
```

gives this error incorrectly:
`error TS2347: Untyped function calls may not accept type arguments`

In both the Typescript compiler and the Atom plugin.

Is it something that is part of the 1.9 fixes, like the resolve promise required bug?

**Comment by aluanhaddad** [comment]
How are you importing the file? What does your `tsconfig.json` looklike?

**Comment by RichardJECooke** [comment]
`const responseHelper = require('../../logic/responseHelper');`

```json
{
	"buildOnSave": false,
	"compileOnSave": false,
	"compilerOptions":
	{
		"allowJs": true,
		"jsx": "react",
		"noImplicitAny": true,
		"noImplicitReturns": true,
		"noImplicitUseStrict": false,
		"module": "commonjs",
		"outDir": "../dist/server/app",
		"rootDir": "..",
		"removeComments": false,
		"sourceMap": false,
		"target": "es6",
		"experimentalDecorators": true,
		"emitDecoratorMetadata": true
	},
	"exclude":
	[
		"build_scripts",
		"node_modules",
		"typings"
	]
}

```

**Comment by aluanhaddad** [comment]
this line is the problem
```TypeScript
const responseHelper = require('../../logic/responseHelper');
```
When you use a `const` or `var` or `let` require, type information is not imported. The function will just have type any. It certainly can't be called with type arguments.
use
```TypeScript
Import responseHelper = require('../../logic/responseHelper');
```

**Comment by RichardJECooke** [comment]
Oh wow, that affects our **entire** project.  I'll change every file, thanks.

It would be cool if Typescript compiler or plugin gave you a warning about that. Because there about 8 different syntaxes to import a module in Javascript.

**Comment by aluanhaddad** [comment]
@RichardJECooke the problem is people use the var requires to get around importing things like static assets or things that don't even exist, so it has its valis use cases (TypeScript 2.0 introduces a better way to handle these).
My advice would be to use tslint. It has an option called `no-var-requires`.

**Comment by jaumard** [comment]
I have the same error but not causing by the `var-require`, I create a stackoverflow question for my case http://stackoverflow.com/questions/40634038/angular-2-dynamic-component-generation-ts-compilation-error

**Comment by luillyfe** [comment]
Apparently when you are using `@Inject` parameter decorator to specify a dependency on a Service' constructor, type information is not imported.

```
@Injectable()
export class MyService {
    constructor(@Inject(HttpClient) private _http) { }
}
```

Throws this error, error `TS2347: Untyped function calls may not accept type arguments`. But **it works on perfectly** using the **Typescript shortcut** for initialises parameters an create private class property.

```
@Injectable()
export class MyService {
    constructor(private _http: HttpClient) { }
}
```
