### ISSUE TITLE
'noUnusedParameters' compiler options warn the specified 'this' type as 'never used' parameter

### ISSUE THREAD

**Issue by saneyuki** [Microsoft/TypeScript#9550]
## Environment

- TypeScript Version 2.0.0-dev.20160707

## Step to Reproduce

compile the following code with `tsc test.ts --noUnusedParameters`

```typescript
// test.ts
class A {
    constructor(private a: number) {}

    b(this: A): number {
        return this.a;
    }
}

function bar(this: Window): string {
    return window.location.href;
}
```

## Expected behavior

There is not any compile error.

## Actual behavior

`tsc` reports following compilation errors

```sh
test.ts(4,7): error TS6133: 'this' is declared but never used.
test.ts(10,14): error TS6133: 'this' is declared but never used.
```

```typescript
// test.ts
class A {
    constructor(private a: number) {}

    b(this: A): number { // error TS6133: 'this' is declared but never used.
        return this.a;
    }
}

function bar(this: Window): string { //  error TS6133: 'this' is declared but never used.
    return window.location.href;
}
```

**Comment by saneyuki** [comment]
@mhegazy 

Sorry, I missed that you assigned this to you and I opened the pull request #9557 to fix this bug.
How should I treat #9557?

**Comment by mhegazy** [comment]
thanks @saneyuki. waiting on the CI server, then will merge it.

**Comment by falsandtru** [comment]
@mhegazy This bug is not fixed in Visual Studio 2015 with TS2.0 (typescript@2.0.0 installed by npm works correctly). Can you reopen this issue?

**Comment by andy-ms** [comment]
Why is the second example (`this: Window` but `this` is not used) not an error? Why do you need to declare the type of `this` if you never use it?
