### ISSUE TITLE
Missing Math bindings

### ISSUE THREAD

**Issue by danslocombe** [Microsoft/TypeScript#9555]
**TypeScript Version:**  Version 2.0.0-dev.20160707

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
// test.ts
class A{
  constructor(){
    console.log(Math.cosh(1));
    console.log(Math.sinh(1));
  }
}

let a = new A();

```

**Expected behavior:**
No compilation errors
 
**Actual behavior:** 

On compilation with tsc:
```
test.ts(3,22): error TS2339: Property 'cosh' does not exist on type 'Math'.
test.ts(4,22): error TS2339: Property 'sinh' does not exist on type 'Math'.
```

We can, however, still run the output to get the expected
```
1.5430806348152437
1.1752011936438014
```

**Comment by mhegazy** [comment]
`cosh` and `sinh` are added in ES2015. the declarations live in the ES2015/ES6 library. use `--lib` and include `es2015.core` to get to them.

so for instance:

```ts
// tsconfig.json
{
    "compilerOptions": {
        "lib": ["es5", "dom", "es2015.core"]
    }
}

```
