### ISSUE TITLE
React Native tag Image with Typescript.

### ISSUE THREAD

**Issue by nschurmann** [Microsoft/TypeScript#9559]
I have the following component written in Typescript:
```Typescript
const Welcome = (p: any) => 
  <View>
    <Image source={require('../assets/welcome-background.png')} />
  </View>

const styles = StyleSheet.create({
  container: {
    flex: 1,
    width: null,
    height: null
  }
})
```
which compiles to this:
```javascript
const Welcome = (p) => React.createElement(View, null, React.createElement(Image, {source: require('../assets/welcome-background.png')}));
const styles = StyleSheet.create({
    container: {
        flex: 1,
        width: null,
        height: null
    }
});
```

Thus is throwing me this error:
<img width="319" alt="screen shot 2016-07-07 at 2 06 08 pm" src="https://cloud.githubusercontent.com/assets/5099344/16663915/018e7870-444c-11e6-9388-7cb5ef6a145f.png">
Is there a flag in tsconfig.json or an alternative way to load the images in the source tag? (the image is in where it says to be)

**Comment by DanielRosenwasser** [comment]
I believe this is related to React Native, not a TypeScript one. StackOverflow is probably a better venue for questions like this.

For what it's worth, according to [this answer on SO](http://stackoverflow.com/a/30467637/4386952), you can prefix your path with `image!` to load it this way.

**Comment by sintylapse** [comment]
@nschurmann, @DanielRosenwasser, this is definitely the problem of typescript. You just need to install
`npm install @types/node`
This question is: Why do you, @DanielRosenwasser, close an issue, without providing a reasonable answer???

**Comment by DanielRosenwasser** [comment]
Sorry, I'll defer to your answer if it works. It was (and sort of is) kind of a pain from our end to get a full React Native setup together to test. If others still run into the problem, we'll take a look.

**Comment by oferRounds** [comment]
Hi @nschurmann and @sintylapse 

Facing the same issue. I installed `@types/node` but the situation did not change - still unable to resolve. Any idea?

**Comment by oferRounds** [comment]
@DanielRosenwasser - maybe you’d have an idea?

**Comment by Klabauterman** [comment]
I also have a problem with react-native, typescript and including images. As far as I see it, the problem is that typescript does not copy resources into the build folder. But I have no solution yet.

**Comment by eassymo** [comment]
any update?

**Comment by adamconservis** [comment]
Here is a node module that helps RN work with Typescript, this solved the issue for me.  https://github.com/ds300/react-native-typescript-transformer

**Comment by petekp** [comment]
@adamconservis I'm still having an issue copying over static resources to `/artifacts` even while using `react-native-typescript-transformer` — was there any additional config you may have done to enable this? I don't see static resources mentioned in the docs. Thanks!

**Comment by oferRounds** [comment]
For me the solution was to move the `images` folder out of the `src` folder, placing at the same level.

**Comment by eassymo** [comment]
I'm ussing "copyfiles" package to copy assets folder into transpiled code:

package.json
```
"scripts": {
    ... etc
    "build": "npm run tsc && npm run add-assets",
    "add-assets": "copyfiles -u 1 src/assets/**/* out-dir/"
    ... etc
  },
```

Error of "module not found" gone, but image is not shown.

**Comment by AleskiWeb** [comment]
@petekp when I do this, it works fine but tsc complains at me that it cant find module `assets`. I named my package.json `{ "name": "assets"}`. Any idea on a workaround for that?

**Comment by petekp** [comment]
@AleskiWeb Have you tried changing the `baseUrl` in `tsconfig.json`? Mine is `"baseUrl": "."`. If that doesn't work, then I'm not sure, but it is likely related to your `tsconfig` configuration.

**Comment by MichelDiz** [comment]
I have the same issue, I'll try (right now) this https://github.com/expo/expo-asset-utils

**Comment by jdeanwaite** [comment]
I created an answer on SO for this issue outlining two options: [https://stackoverflow.com/a/49715468/4216035](https://stackoverflow.com/a/49715468/4216035)
