### ISSUE TITLE
Add "indexed properties"

### ISSUE THREAD

**Issue by dmitryDemchenko** [microsoft/TypeScript#956]
In our project we use ActiveX objects accessible from JavaScript. I have .d.ts of COM library.
One of the external types has "indexed properties". As for now, it's TS declaration loks like

``` javascript
interface axType {
  Values(index:string):string;
}
```

JS code like

``` javascript
axObject.Values('F1') = 'test'
```

works just fine in runtime, but TS compiler shows the message:  "Invalid left-hand side of assignment expression".

 I can't see the way how to define that interface in  .d.ts.

As I can imagine, it should be something like 

``` typescript
class axType { 
  get Values(index:string): string 
  {
  //....
  }

  set Values(index:string, value: string)
  {
  // ...
  }
}
```

**Comment by zspitz** [comment]
@RyanCavanaugh Can I define a signature with multiple parameters? Or with types other than `number` or `string`?

**Comment by zspitz** [comment]
@RyanCavanaugh  Also, won't defining the indexers this way require the use of square brackets:

    axObject.Values['F1'] = 'test';

but the Javascript call is using invocation:

    axObject.Values('F1') = 'test'

**Comment by dmitryDemchenko** [comment]
@zspitz as far as I can see JScript indexer is something not supported in ECMA; also TypeScript is intended to compile to JavaScript (ecma). That's why this kind of indexes definitely will not be supported in TypeScript.

In my project I ended up rewriting all calls like 

`d.Item("a") = "Athens"` 

into 

`AssignIndexedProperty(d, "a", " "Athens"") `

and defining function 

`AssignIndexedProperty = new Function (d, name, value, "d(name) = value")`

That trick worked good in JScript interpreter, but had terrible readability ((((

**Comment by zspitz** [comment]
@dmitryDemchenko You may be interested to know that I've written a tool to convert type libraries to Typescript definition files. https://github.com/zspitz/ts-activex-gen

**Comment by dmitryDemchenko** [comment]
@zspitz Nice job! I did the almost same for our ActiveX libraries, or, to be more accurate, for .NET "interop" libraries. It was very similar, but I suppose a little bit easier thanks to "reflection" mechanism.

**Comment by zspitz** [comment]
@dmitryDemchenko I originally was using .NET reflection, but there were too many mismatches between the .NET reflection model and the COM object model. I am currently using tlbinf32.dll.
