### ISSUE TITLE
Getting Error MSB6006 in v1.8.34.0

### ISSUE THREAD

**Issue by kabua** [Microsoft/TypeScript#9563]
**VS Version** VS2015 update 3 (Community Ed.)
**TypeScript Version:**  1.8.34.0 from VS2015 update 3
**Extension** TypeScript for Microsoft Visual Studio 1.8.34.0

**Installed Apps**
TypeScript Tools for Microsoft Visual Studio 2015 1.8.6.0
TypeScript Tools for Microsoft Visual Studio 2015 1.7.6.0

**Steps**
1) Start VS2015 and created a new TypeScript project; using 'Html Application with TypeScript'
1.1)  Rebuild Solution - Build succeeded.

2) Added the following ```tsconfig.json``` file to the project.

    {
        "compilerOptions": {
            "target": "es5",
            "module": "amd",
            "moduleResolution": "classic",

            "declaration": false,
            "diagnostics": true,
            "removeComments": false,
            "sourceMap": true
        },

        "compileOnSave": true
    }
2.1)  Rebuild Solution - Build succeeded.

3) Changed the ```tsconfig.json``` file to:

    {
        "compilerOptions": {
            "target": "es5",
            "module": "amd",
            "moduleResolution": "classic",

            "declaration": false,
            "diagnostics": true,
            "removeComments": false,
            "sourceMap": true,

            "baseUrl": ".",
            "paths": {
                "*": "*"
            }
        },

        "compileOnSave": true
    }
3.1) Rebuild Solution - Build FAILED.
3.2) Build Output

    1>------ Build started: Project: TypeScriptHTMLApp1, Configuration: Debug Any CPU ------
    1>Build started 7/7/2016 3:36:41 PM.
    1>PreComputeCompileTypeScriptWithTSConfig:
    1>  C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.8\tsc.exe --project "C:\SandBox\Ts\TypeScriptHTMLApp1\TypeScriptHTMLApp1\tsconfig.json" 
    1>CompileTypeScriptWithTSConfig:
    1>  C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.8\tsc.exe --project "C:\SandBox\Ts\TypeScriptHTMLApp1\TypeScriptHTMLApp1\tsconfig.json" 
    1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\TypeScript\Microsoft.TypeScript.targets(214,5): error MSB6006: "tsc.exe" exited with code 1.
    1>
    1>Build FAILED.
    1>
    1>Time Elapsed 00:00:00.14
    ========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

3.3) It appears that when adding baseUrl and/or paths will case it to fail.

**Comment by mhegazy** [comment]
` "paths"` is a TS 2.0 feature and is not supported by the TS 1.8.* compiler. So you can wait for the TS 2.0 release, or you can update to the nightlly following https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Nightly%20Builds.md#visual-studio-2013-and-2015.

if you chose to update VS to the nightly using DevMode, please remember to switch it off on your next install.

**Comment by kabua** [comment]
Okay, but what I really don't understand is where I first saw the issue. I have a VS solution (with 10 projects; but only two are TS/JS based). Our WebUtilities project builds just fine with the following ```tsconfig.json``` file.

    {
        "compilerOptions": {
            "target": "es5",
            "module": "amd",
            "moduleResolution": "Classic",

            "declaration": false,
            "diagnostics": true,
            "removeComments": false,
            "sourceMap": true,

            "baseUrl": ".",
            "paths": {
                "Base64":  "/Lib/Base64/0.3/*", 
                "BitSet":  "/Lib/BitSet/3.1/*", 
                "angular": "/Lib/angular/1.3/*",
                "WebUtilities/*": "/Lib/*"
            }
        },

        "exclude": [
            "Lib"
        ],

        "compileOnSave": true
    }

Yet, our TestApp.Spa fails with this ```tsconfig.json``` file

    {
        "compilerOptions": {
            "target": "es5",
            "module": "amd",
            "moduleResolution": "classic",

            "declaration": false,
            "diagnostics": true,
            "removeComments": false,
            "sourceMap": true,

            "baseUrl": ".",
            "paths": {
                "Base64": "."
            }
        },

        "compileOnSave": true
    }

The interesting thing is, in the WebUtilities the ```tsc.exe``` command line looks like this:

    1>  C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.8\tsc.exe  --declaration --module AMD --sourcemap --target ES5 --noEmitOnError --locale en-US "D:\M\S\WebUtilities\Lib\Base64\0.3\Base64.d.ts" "D:\M\S\WebUtilities\Lib\BitSet\3.1\bitset.d.ts" "D:\M\S\WebUtilities\S\C\AR.ts" "D:\M\S\WebUtilities\S\H\A.ts" "D:\M\S\WebUtilities\S\CIP.ts" "D:\M\S\WebUtilities\S\Does.ts" "D:\M\S\WebUtilities\S\H\CIT.ts" "D:\M\S\WebUtilities\S\ISI.ts" "D:\M\S\WebUtilities\S\P.ts" "D:\M\S\WebUtilities\S\S.d.ts"

but the TestApp.Spa version looks like this

    5>  C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.8\tsc.exe --project "D:\M\S\TestApp\TestApp.Spa\tsconfig.json" 

It appears that the WebUtilities version isn't using the ```tsconfig.json``` file but when I open up the project's properties and view TypeScript Build settings they are grayed out, stating 'one or more tsconfig.json files detected...'

Note: both projects are web site projects.

**Comment by mhegazy** [comment]
If i were to guess, in the first case, the tsconfig.json is not part of your project, or its content type is not "Content". the build targets will only pick up a tsconfig.json file and pass it as `tsc --project ...` if the two conditions above are satisfied.

**Comment by kabua** [comment]
The file is part of the solution but the Build Action is set to None. Mystery solved, thanks.

However, after thinking about this issue some more last night, I realized that a better user experience could be achieved by:

- Giving a better error message when the TSC.exe came across a ill-formed config property, or
- Ignore any config settings it doesn't recognize, or perhaps a better approach
- Log a warning about ill-formed or unrecognized configuration properties but keep going, that way new configuration settings will not break the compiler or the build process.

What do you think?

**Comment by mhegazy** [comment]
A project could include tsconfig.json but not intend them to be used. the support for tsconfig.json in VS and build came in after the file was around. so to avoid breaking changes for users' build configuration, we opted to pick up only included files. this way nothing changes unless you include the file in the project. adding a new tsconfig.json file will include it as "Content". so it is set to "None" if some one manually changes it.
