### ISSUE TITLE
lib.webworker.d.ts missing definitions for IDBObjectStoreParameters and IDBIndexParameters

### ISSUE THREAD

**Issue by lilred** [Microsoft/TypeScript#9564]
**TypeScript Version:**  1.9.0

In Visual Studio 2015 Update 3, I've created a brand new TypeScript project, cleaned out `app.ts`, and used this as the `tsconfig.json`:

```json
{
  "compilerOptions": {
    "lib": [ "es2015", "webworker" ]
  }
}
```

The result is a pair of build errors:

```
Error		Build:Cannot find name 'IDBIndexParameters'.           TypeScriptHTMLApp1	c:\Program Files (x86)\Microsoft SDKs\TypeScript\1.9\lib.webworker.d.ts	404	
Error		Build:Cannot find name 'IDBObjectStoreParameters'.     TypeScriptHTMLApp1	c:\Program Files (x86)\Microsoft SDKs\TypeScript\1.9\lib.webworker.d.ts	336	
```

Bonus bug: Visual Studio 2015.3 doesn't recognize the `readonly` keyword in TypeScript, so once you open `lib.webworker.d.ts` everything goes to hell.

**Comment by mhegazy** [comment]
This should be resolved with latest `typescript@beta`
