### ISSUE TITLE
Type interference fails for generics in multiple levels

### ISSUE THREAD

**Issue by jeremyhallden** [Microsoft/TypeScript#9571]
TypeScript Version: 1.8.0

Considering the code below, the line in the foo method does not compile:

```        

export class Dummy{
   public static foo<T extends  IEquatable<T>>(graphEdges: Array<GraphEdge<T>>) {
           const dummy = graphEdges.map(edge => edge.endNodeId);
           (...)
   }
}

export interface IEquatable<T> {
        equals(other: T): boolean;
    }

export class GraphEdge<T extends IEquatable<T>> implements IEquatable<GraphEdge<T>> {
        constructor(
            public startNodeId: T,
            public endNodeId: T) {
        }

        public equals(other: GraphEdge<T>): boolean {
            if (other == null) {
                return false;
            }
            return this.startNodeId.equals(other.startNodeId) && this.endNodeId.equals(other.endNodeId);
        }
    }
```

This should give me an array of type Array[T], but gives a compile error:
"Supplied parameters do not match any signature of call target: parameter type mismatch. Parameter 'callbackfn' should have type assignable to '{(value: GraphEdge[T], index: number, array: GraphEdge[T][]):any}

**Comment by aluanhaddad** [comment]
@jeremyhallden There is an error in your code.
```TypeScript
const foo = new Array<GraphEdge<T>>().map(edge => edge.endNodeId);
```
You need to instantiate the generic parameter `T`. as in
```TypeScript
const foo = new Array<GraphEdge<number>>().map(edge => edge.endNodeId); // number[]
```

**Comment by jeremyhallden** [comment]
@aluanhaddad Thanks for the response, but I (over)simplified the code to show the error. I'll edit my initial post right now :)

**Comment by aluanhaddad** [comment]
@jeremyhallden I see, I'll try to take a look at the revised code later

**Comment by sandersn** [comment]
@jeremyhallden I tried your example with my compiler built from master and I don't see an error (although I had to convert `foo` from `public static` to `function`). Can you try this code with `typescript@next`? That is, by saying `npm install -g `typescript@next` and using that typescript compiler.

**Comment by jeremyhallden** [comment]
Thanks for trying it out on 2.0 - I can try to do the same soon.
This is to be used in a huge app that is in production right now, which
runs 1.8 though.
Could you confirm that this bug exists in 1.8.x?

**Comment by sandersn** [comment]
I went back to 1.8.34 and also couldn't reproduce the error. Here's precisely what I have in my VSCode buffer:

```ts
function foo<T extends  IEquatable<T>>(graphEdges: Array<GraphEdge<T>>) {
        const dummy = graphEdges.map(edge => edge.endNodeId);
        //(...)
}

export interface IEquatable<T> {
        equals(other: T): boolean;
    }

export class GraphEdge<T extends IEquatable<T>> implements IEquatable<GraphEdge<T>> {
    constructor(
        public startNodeId: T,
        public endNodeId: T) {
    }

    public equals(other: GraphEdge<T>): boolean {
        if (other == null) {
            return false;
        }
        return this.startNodeId.equals(other.startNodeId) && this.endNodeId.equals(other.endNodeId);
    }
}
```

**Comment by mhegazy** [comment]
Without more information we can be sure we identified the issue. please try `typescript@next` and reopen if it is still an issue. also please provide more information to be able to diagnose and track the issue.
