### ISSUE TITLE
Visual Studio 15 Preview3 Error

### ISSUE THREAD

**Issue by alanpurple** [Microsoft/TypeScript#9572]
<entry>
    <record>571</record>
    <time>2016/07/08 13:36:28.031</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.DllNotFoundException: Unable to load DLL &apos;ChakraCore.dll&apos;: The specified module could not be found. (Exception from HRESULT: 0x8007007E)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Editor.TypeScript.ScriptServices.Hosting.ChakraCoreEngine.JsCreateRuntime(JavaScriptRuntimeAttributes attributes, JavaScriptThreadServiceCallback threadService, JavaScriptRuntime&amp; runtime)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Editor.TypeScript.ScriptServices.Hosting.ChakraCoreEngine.CreateRuntime(JavaScriptRuntimeAttributes attributes, JavaScriptThreadServiceCallback threadService, JavaScriptRuntime&amp; runtime)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Editor.TypeScript.ScriptServices.Hosting.JavaScriptEngine..ctor(String text, String url, INativeEngine nativeEngine)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Editor.TypeScript.ScriptServices.ShimFactory.ShimFactory.Factory.ReinitializeEngineAndFactoryIfNeeded()&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Editor.TypeScript.ScriptServices.ShimFactory.ShimFactory.Factory.CreateOrUpdateShim(String createShimFunction, Object host, ShimAndServicesFileVersion&amp; shimInfo)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Editor.TypeScript.ScriptServices.ShimFactory.ShimFactory.CreateOrUpdateShim(String caption, String createShimFunction, Object host, ShimAndServicesFileVersion&amp; shimInfo)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Editor.TypeScript.ScriptServices.Proxies.AbstractProxy`1.InvokeShimMethod[T](String methodName, Object[] arguments)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Editor.TypeScript.ScriptServices.Proxies.ClassifierProxy.TryAddLexicalClassifications(String lineText, Int32 lexState, Int32 offset, TypeScriptLexicalClassificationMap classificationMap, ITextSnapshot snapshot, List`1 tagSpans, Int32&amp; newEndOfLineState)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Editor.TypeScript.Features.Classifier.LexicalClassificationTaggerProvider.Tagger.AddLexicalClassifications(ClassifierProxy classifier, String text, Int32 lineNum, Int32 offset, ITextSnapshot snapshot, List`1 tagSpans)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Editor.TypeScript.Features.Classifier.LexicalClassificationTaggerProvider.Tagger.GetClassifications(NormalizedSnapshotSpanCollection spans, List`1 result)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Editor.TypeScript.Features.Classifier.LexicalClassificationTaggerProvider.Tagger.GetTags(NormalizedSnapshotSpanCollection spans)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.&lt;GetTagsForBuffer&gt;d__38.MoveNext()</description>
  </entry>

TypeScript Module error in VS 15 Enterprise Preview3

**Comment by derth** [comment]
Same problem, it's very slow, both javascript and typescript files are shown like plain text. I can debug but no intellisense or anything shown.

**Comment by aluanhaddad** [comment]
Turns out that, for me at least, _chakracore.dll_ was not present in _C:\Program Files (x86)\Microsoft Visual Studio 15.0\Common7\IDE\CommonExtensions\Microsoft\TypeScript_ i copied the version from my VS 2015 install and everything seems to be working fine.

**Comment by vladima** [comment]
// cc @paulvanbrenk

**Comment by alanpurple** [comment]
@aluanhaddad  thx, it works

**Comment by paulvanbrenk** [comment]
This should be fixed in the next preview of Dev15

**Comment by yaananth** [comment]
P.S: look for chakracore.dll in C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.0 or whatever version...
