### ISSUE TITLE
Allow not fully applied generic types in constraints

### ISSUE THREAD

**Issue by shockone** [Microsoft/TypeScript#9573]
Consider the following function:

```typescript
type Functor<A> = Array<A> | (<P>(param: P) => A);

function fmap<A, B>(mapper: (p: A) => B, functor: Functor<A>): Functor<B> {
    if (Array.isArray(functor)) {
        return functor.map(mapper);
    }

    return compose(functor, mapper);
}
```

It compiles, but we lose information about which part of the union was passed as `functor`.

```typescript
const mapped = fmap([1, 2], square); // mapped is a Functor<number>, not Array<number>.
```

In order to keep this information I'd need to rewrite it as

```typescript
type Functor<A> = Array<A> | (<P>(param: P) => A);

function fmap<A, B, F extends Functor>(mapper: (p: A) => B, functor: F<A>): F<B> {
    if (Array.isArray(functor)) {
        return functor.map(mapper);
    }

    return compose(functor, mapper);
}
```

But this one fails with `error TS2314: Generic type 'Functor' requires 1 type argument(s).` Note that I can't describe the type parameter as `F extends Functor<A>` because then I wouldn't be able to return `F<B>`.

That said, maybe there is a better way to handle this use case than allowing not fully applied generic types.

**Comment by DanielRosenwasser** [comment]
Hey @shockone, #1213 is probably a good place to discuss this, so I'm going to mark this as a duplicate.
