### ISSUE TITLE
unknown compiler options should not stop parsing of tsconfig.json

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript#9577]
If a tsconfig.json has an unknown option, the whole tsconfig.json is thrown away. This is too drastic. instead, only unknown properties should be ignored, and other properties kept.

**Comment by Arnavion** [comment]
But please warn about them to help catch typos.

**Comment by DanielRosenwasser** [comment]
`--wranAbuotUknownOptionss`

**Comment by basarat** [comment]
> If a tsconfig.json has an unknown option

I think an valid compile output but with a error message + code (just like a type failure) would be nice :rose:
