### ISSUE TITLE
Support Custom JSX Pragma

### ISSUE THREAD

**Issue by developit** [Microsoft/TypeScript#9582]
Hi. I've searched through the various issues (as well as other places this has been discussed) and I don't see a current open issue to address the lack of custom JSX pragma support.

As discussed elsewhere, other transpilers allow specifying any function name to insert when producing hyperscript from JSX.  It's worth noting that hyperscript predates React, and is a format shared by a large number of libraries entirely separate from the React project.  Currently, TypeScript only allows configuration of an Object on which to invoke `.createElement()`, however the [original implementations](https://github.com/dominictarr/hyperscript) and many descendants thereof simply use `h()`.  You can read my attempt to document some of the context and background [here](http://www.jasonformat.com/wtf-is-jsx/).

The configuration would presumably look something like this:

``` js
{
    "compilerOptions": {
        "jsx": "react",
        "jsxPragma": "h"
    }
}
```

... and the output would look like:

``` js
// input:
<div id="foo">hello</div>

// output:
h('div', { id:'foo' }, 'hello');
```

Has this been bypassed for feasibility reasons?  If not, I think it would be a valuable addition.

**Comment by WanderWang** [comment]
I have a different view

consider this proposal  
[Proposal: Replace emitter with syntax tree transformations and a simplified node emitter.](https://github.com/Microsoft/TypeScript/issues/5595)

Your requirement can be implements via " custom syntax tree transformations " . So I don't think it's necessary for us to increase tsconfig 's complexity.

**Comment by PaulBGD** [comment]
And I think that's a great idea, however the tsconfig already has an option for JSX (that only supports React.) I don't see why we'd support just the first half of the function call.

**Comment by developit** [comment]
@WanderWang this is very much a userland feature. Most users of TypeScript would not be compelled to extend TypeScript itself simply to account for a common use-case. 

My suggestion could replace the existing `"jsxNamespace"` config property, since `jsxPragma` enables a superset of use-cases, while still allowing the default to remain `"React.createElement"`.

Currently, TypeScript forces users to build shims for non-React JSX use-cases, which is significantly more cumbersome than needing to know about another (or a different) configuration property.

**Comment by basarat** [comment]
workaround: 

```ts
import * as h from "someplace";
const hyper = {createElement: h}
```

**Comment by developit** [comment]
@basarat yes, this is what people currently do. However, this is a second-class experience and difficult to explain in documentation.

**Comment by eshansingh** [comment]
@basarat that is exactly that - a workaround. It seems that there should be a better way of doing this.

**Comment by eshansingh** [comment]
No discussion, no nothing. Sad.

**Comment by bradleyayers** [comment]
My use-case is to support JSX within [skate.js](https://github.com/skatejs/skatejs). skatejs has a hyperscript compliant API `import { h } from 'skatejs';`, so all that's missing is JSX pragma support or something equivalent.

**Comment by RyanCavanaugh** [comment]
Accepting PRs for a flag `jsxFactory` which accepts a string, like `"h"` or `"React.createElement"`

* No explicit validation of this parameter occurs; users are assumed to have provided a correct string
* If this flag is specified, JSX elements in `react` emit mode no longer require the `React` identifier to be present
* It is an error to specify both this and the "React namespace" setting

**Comment by developit** [comment]
Sweet, someone submit a PR

**Comment by RyanCavanaugh** [comment]
Be the PR you want to see in the world :wink:

**Comment by developit** [comment]
I would, but I've never used TypeScript and already have tons to maintain 😛

**Comment by bradleyayers** [comment]
I'll raise a PR.

**Comment by bradleyayers** [comment]
> If this flag is specified, JSX elements in react emit mode no longer require the React identifier to be present.

In the case of `// @jsxFactory: a`, we *should* require the `a` identifier to be present right? Following on that `// @jsxFactory: a.b` would still require just `a` to be present.

**Comment by mhegazy** [comment]
sounds reasonable.

**Comment by bradleyayers** [comment]
I've raised the PR — https://github.com/Microsoft/TypeScript/pull/11267.

**Comment by tusharmath** [comment]
For future readers —
```json
{
    "compilerOptions": {
        "jsx": "react",
        "reactNamespace": "h"
    }
}

```

The above configuration will get you going.

**Comment by mhegazy** [comment]
Edit: updated the jsxFactory property name in comment above.

**Comment by tusharmath** [comment]
@mhegazy I get this error — ` Unknown compiler option 'jsxFactory'`
```
tsc --version
Version 2.1.1
```

**Comment by mhegazy** [comment]
Use `typescript@next`.

**Comment by nojvek** [comment]
This is awesome. Kudos for baking this as a compiler param.

**Comment by streamich** [comment]
```jsx
<div>Hello</div>
```

should compile to:

```js
({h}) => h('div', {}, 'Hello');
```

and them React could do:

```js
(({h}) => h('div', {}, 'Hello');)({
  h: React.createElement,
});
```
