### ISSUE TITLE
refer self-defined class in d.ts to extend Express.Request

### ISSUE THREAD

**Issue by frogcjn** [Microsoft/TypeScript#9586]
for example:
`my-express-extend.d.ts`
```typescript
declare namespace Express {
    export interface Request {
        payload: string
    }
}
```
This works fine, req.payload is a string type.

but when I import the User class, the extension will have no effect on other files.
```typescript
import { User } from "./model"
 declare namespace Express {
    export interface Request {
        payload: string
        myUser: User
    }
}
```
req.payload will be invalid. req.myUser is also invalid.

**Comment by frogcjn** [comment]
I found the solution:
in `./model`
just declare the User type in global
```ts
declare global {
    interface User {
          id: string
          name: string
          ...
    }
}
```

**Comment by 19majkel94** [comment]
Did you add new interface? It's not very usefull when you have both class and interface describing it - hard to refactor and easy to miss changes.
