### ISSUE TITLE
Continuous rebuild in Visual Studio when touching .js files

### ISSUE THREAD

**Issue by rendmath** [Microsoft/TypeScript#9588]
Possibly since VS2015 Update 3, the watch on TypeScript project seems to have become more aggressive in Visual Studio. Now, adding or removing any .js file within the scope of the TypeScript project triggers a rebuild. Therefore, removing the build output is now impossible since the project is rebuilt in a matter of seconds.

**TypeScript Version:**  1.8.34
**Visual Studio Version:**  2015 Update 3

**Reproduction steps**
1. Create a new ASP.NET Core project from an "Empty" template.
2. Add a dummy TS file to the root of the application.
3. Delete the generated .js file.

**Expected behavior:**
Uncertain.

**Actual behavior:** 
The .js file reappears within seconds (that is frustrating).

**Remarks:**
Also work with any addition or removal of any .js file in the project.
compileOnSave: false doesn't alter the behavior.

**Workaround**
If you don't need Visual Studio to build your TypeScript (built with Gulp, Grunt, NPM, etc.), you can disable Visual Studio build with &lt;TypeScriptCompileBlocked>true&lt;/TypeScriptCompileBlocked> (see: http://rostacik.net/2015/08/14/how-to-disable-building-of-typescript-files-in-visual-studio-2015/ for more info).

**Comment by mhegazy** [comment]
I can not get this behavior to reproduce locally. the only thing in the TypeScript plugin that writes files is CompileOnSave, and that is triggered by saving, so i do not know what is going on here.

**Comment by mhegazy** [comment]
I am going to close this for now. please reopen if you have more information.
