### ISSUE TITLE
Type guards do not work on member expressions

### ISSUE THREAD

**Issue by arciisine** [Microsoft/TypeScript#9589]
**TypeScript Version:**  2.0.0-dev.20160707

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
function isString(x:any):x is String {
  return typeof x === 'string';
}

let obj:{age:string|number} = { age : "10" };

if (isString(obj.age)) {
  obj.age.toUpperCase();
}

if (typeof obj.age === 'string') {
  obj.age.toUpperCase();
}
```

**Expected behavior:**
`obj.age` should be identified as a `string`, and compilation should succeed.

**Actual behavior:** 
`obj.age` is treated as `string|number` as if the type guard wasn't applied, and the expression is invalid.

**Work around**
The following works, but requires creating extra local variables.
```ts
// A *self-contained* demonstration of the problem follows...
function isString(x:any):x is String {
  return typeof x === 'string';
}

let obj:{age:string|number} = { age : "10" };

let age = obj.age;
if (isString(age)) {
  age.toUpperCase();
}
```

**Comment by arciisine** [comment]
And as a follow up, the use case for this is that I'm working with an AST (all interfaces) and the children are typed as a base type.  I am hoping to be able to discriminate using type guards.

**Comment by aleksey-bykov** [comment]
use `sting | a` in your type guard instead of `any`

```typescript
function isString <a>(value: string | a): value is string {
   // ...
}
```

**Comment by aleksey-bykov** [comment]
also mind the case in `value is string`

**Comment by aleksey-bykov** [comment]
until recently you could not narrow `any` at all, then narrowing was allowed for primitive values:

- https://github.com/Microsoft/TypeScript/pull/5011
- https://github.com/Microsoft/TypeScript/issues/4432
- https://github.com/Microsoft/TypeScript/pull/1621

@ahejlsberg, PR https://github.com/Microsoft/TypeScript/pull/1621 doesn't consider properties, does it?

**Comment by mhegazy** [comment]
This sample is working as expected for me. i believe there is something missing from the initial report:

```cmd
c:\test\sandbox7>tsc --v
Version 2.0.0-dev.20160707

c:\test\sandbox7>type a.ts
// A *self-contained* demonstration of the problem follows...
function isString(x:any):x is String {
  return typeof x === 'string';
}

let obj:{age:string|number} = { age : "10" };

if (isString(obj.age)) {
  obj.age.toUpperCase();
}

if (typeof obj.age === 'string') {
  obj.age.toUpperCase();
}

c:\test\sandbox7>tsc a.ts

c:\test\sandbox7>echo %ERRORLEVEL%
0
```

**Comment by arciisine** [comment]
I just checked again, and it does seem to be working from command line compilation, but VSCode was reporting it as an error.  It appears VSCode was not picking up the version of TypeScript from `node_modules`, but the one bundled with the editor.  Forcing `typescript.tsdk` to `node_modules/typescript/lib` now allows for guards on expressions.
