### ISSUE TITLE
Some breakpoints not hit in VS since VS2015 Update 3

### ISSUE THREAD

**Issue by rendmath** [Microsoft/TypeScript#9591]
Visual Studio integrated debugging with Internet Explorer suffers from source mappings problems with TypeScript, apparently since Visual Studio 2015 Update 3. Some breakpoints are not hit, others are opened in the .js file instead of the .ts one, and VS often crashes. 

**TypeScript Version:**  1.8.34
**Visual Studio Version:**  2015 Update 3

**Reproduction steps**

1. Create a new ASP.NET Core project with an "Empty template" and app.UseFileServer().
2. Add a simple TypeScript file (see file.ts below) to the root of the application.
3. Add a tsconfig with an outFile pointing to wwwroot/file.js (see tsconfig.ts below).
4. Add an index.html file loading the JS output.
5. Add breakpoints to all lines of the TS file.
6. Launch debugging.

***file.ts***
```ts
console.log("a");
console.log("b");
console.log("c");
```

***Project structure***
![image](https://cloud.githubusercontent.com/assets/8426590/16708583/7e9a95e8-45f9-11e6-9f79-5428d1d44185.png)

***tsconfig.json***
```json
{
  "compilerOptions": {
    "noImplicitAny": false,
    "noEmitOnError": true,
    "removeComments": false,
    "sourceMap": true,
    "target": "es5",
    "outFile": "wwwroot/file.js"
  },
  "exclude": [
    "node_modules",
    "wwwroot"
  ]
}
```

**Expected behavior:**
All three beakpoints are hit.

**Actual behavior:** 
Only first two breapoints are hit. Result may vary unexpectedly with small changes in the source TS file.

![image](https://cloud.githubusercontent.com/assets/8426590/16708553/5c762546-45f8-11e6-8184-c4d556fb240d.png)

**Comment by mhegazy** [comment]
@sheetalkamat just checked in a fix for this. should be available in the next release.

**Comment by rendmath** [comment]
Is it contained in KB3165756 that was issued on tuesday?

**Comment by mhegazy** [comment]
no. this will be releases in the next release of TS 2.0
