### ISSUE TITLE
Suggestion: Different access modifiers in overloads

### ISSUE THREAD

**Issue by buola** [Microsoft/TypeScript#9592]
Currently, all overloads of a method must have the same access modifier.
This seems an unnecessary restriction, and removing it would allow to have extra parameters in methods that are internal to the implementation of a class

**For example**

```ts
class SomeClass {
   private play(a: string, b: number); // the 'b' parameter is private to the class
   public play(a: string); 
   //no access modifier needed here, since access to this should never be checked
   play(a: string, b: number = 0) { //when called from outside the class, 'b' must be 0
   }
}
```

**Comment by RyanCavanaugh** [comment]
Our type system doesn't have a way to represent this. Members have exactly one visibility, and there's only one member of a given name. It'd be a major refactoring to allow anything different, which doesn't seem worth it given how rarely this is needed in practice.
