### ISSUE TITLE
Changes to compileOnSave require closing and reopening the solution in VS

### ISSUE THREAD

**Issue by rendmath** [microsoft/TypeScript#9593]
**TypeScript Version:**  1.8.34
**Visual Studio Version:**  2015 Update 3

**Reproduction steps**
1. Create new ASP.NET Core Web Application with an "Empty" template.
2. Add a new file.ts TypeScript file at the root of the project.
3. Add some dummy code inside the file. [The code compiles and is updated on save, that seems right].
4. Add a defaut tsconfig.json file at the root of the project, add compileOnSave: true and save.
5. Change the code in the source file. [The code is not updated any more, that seems wrong].

**Additional steps**
1. Rebuild the project. [The code is updated for the rebuild but still not recompiled on save]
2. Unload and reload the project. [The code is still not recompiled on save]
3. Close and reopen the solution. [Now it works]

**Expected behavior:**
Changes to compileOnSave should be taken into account immediately.

**Actual behavior:** 
Changes to compileOnSave require to close and reopen the solution to be taken into account.

**Comment by mhegazy** [comment]
@paulvanbrenk can you take a look.

**Comment by paulvanbrenk** [comment]
This seems a problem in Roslyn, which I have to investigate.

**Comment by mhegazy** [comment]
Does not look like a Roslyn issue. other configurations are working correctly. it is just compile on save. we need to investigate.

**Comment by RyanCavanaugh** [comment]
Closing due to lack of additional reports of this
