### ISSUE TITLE
Type inference: inferring generic parameter from lambda arg default parameter value.

### ISSUE THREAD

**Issue by blacktaxi** [Microsoft/TypeScript#9594]
Generic parameter inference from lambda argument parameter type doesn't work for anonymous lambda with default parameter value.

**TypeScript Version:**  nightly (2.0.0-dev.20160704)

**Code**

```ts
function thing<T>(fn: (x: T) => string) {
  return undefined as T;
}

const a = thing((x: number) => 'test');

const b = thing((x = 5) => 'test');

const named = (x = 5) => 'test';
const c = thing(named);
```

**Expected behavior:**

Types of all `a`, `b` and `c` should be `number`.

**Actual behavior:** 

Type of `a` and `c` is `number`, type of `b` is `{}`.

**Comment by sandersn** [comment]
This has to do with the way that contextual typing and type inference interact. If there is no default and no type annotation:

```ts
const d = thing(x => 'test');
```

Then it is not surprising that `d: {}` because there's no way to tell what type `x` is supposed to be and therefore what type `thing` will return.

Unfortunately, as far as I remember, the default doesn't actually help in the contextual typing case, so it's ignored. This means that `b` is treated as if it were `d`.

I need to confirm whether this is the case by checking the code. If it is, it means that a fix may be difficult.

**Comment by sandersn** [comment]
My initial reading of the code makes it look like the initializer should be used -- if execution gets to that case. I'll debug through it to see whether that's actually happening.

**Comment by sandersn** [comment]
I poked around the code but couldn't get a simple change working. Then I checked [the spec section on contextual typing](https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#4.23) and confirmed that my initial guess was correct: initialisers are contextually typed by their parameter's contextual type, and not the other way around. And our contextual typing system doesn't have a good way to resolve circularity in the direction of contextual typing. @ahejlsberg would be able to comment on the difficulty of changing this architecture.

Here's an example of where circular contextual typing would go wrong. The initializer is itself a function with contextually typed parameters:

```ts
declare function fun<T>(f: (x: T) => string): T;
let g = fun((x = (y => y + 1)) => 'circular!')
```

**Comment by blacktaxi** [comment]
Thanks for the response!

Could you please give a little bit more explanation on the circularity? I don't think I quite understand where the `y` parameter is supposed to get it's contextual type in this case.

**Comment by sandersn** [comment]
Actually, the circular example doesn't work today either. Here's an example that does work:

```ts
declare function fun(f: (g:(n: number) => number) => number): string;
fun((x = (y => y + 1)) => x(1));
```
Notice that contextual typing works for both `x` and `y` here:

1. `x ... => x(1)` is contextually typed by the call to `fun`, which has an instantiated type for its first parameter `f: (g: (n: number) => number) => number`. So `x` gets the type of `f`'s first parameter: `(n: number) => number`.
2. `y => y  + 1` is contextually typed by the parameter it initialises. So `y` gets the type of `x`'s first parameter: `number`.

Now let's go back to the generic version of `fun`. Contextual typing works the same way but breaks down pretty quickly:

1. `x ... => x(1)` is contextually typed by the call to `fun`, which has a *generic* type for its first parameter `f: T => number`. So `x` gets the type of `f`'s first parameter: `T`. This has two bad effects: we can't guess a type for `T`, so we default to `{}`. And `{}` becomes the value of `T`, causing the error that you noticed to begin with.
2. `y => y + 1` is contextually typed by the parameter it initialises. But `x` is `{}`, which has no call signatures, so `y` DOESN'T get the type of `x`'s first parameter (no call signature means no parameters). It just gets `any`.

Now let's try to fix things by having parameters contextually typed by their initialisers as a fallback.

In `x ... => x(1)`, `x` falls back to its initialiser for its contextual type: `x = (y => y + 1)`. So what's the type of `y => y + 1`? Well, we first look at the contextual type of its parameter `x` ... and now we're stuck in a loop.

Of course we might be able put in some loop detection and abort contextual typing in case of circularity. In that case we'll be able to get cases like `x = 5 => x + 1` but will still end up with `any` for `x = (y => y + 1) => x + 1`.

However, this is a significant architectural (and spec) change, so I'll defer to @ahejlsberg whether it's something worth considering.

**Comment by blacktaxi** [comment]
Got it, thanks for the explanation.

I hope this can be sorted out somehow, at least for a limited set of use cases like I presented.
