### ISSUE TITLE
Intellisense doesn't show base Object methods on classes

### ISSUE THREAD

**Issue by GlitchEnzo** [Microsoft/TypeScript#9596]
**TypeScript Version:**  1.8.34 inside Visual Studio 2015 Community Update 3

**Code**

```ts
var obj = new Object();
obj.toString(); // intellisense properly lists methods
```

```ts
class Test {
    Foo() {
    }
}

var test = new Test();
test.toString(); //intellisense does NOT list methods, but code compiles and runs
```

**Expected behavior:**
Intellisense should show the base Object methods for any class

**Actual behavior:** 
Methods show up on Object:
![object](https://cloud.githubusercontent.com/assets/3473293/16709816/6215ad6e-45d0-11e6-9e82-82b5d00f0520.gif)

But methods don't show up on Test:
![test](https://cloud.githubusercontent.com/assets/3473293/16709817/68688204-45d0-11e6-8b51-412687d2cc9a.gif)

**Comment by mhegazy** [comment]
this is the intended design. the object methods are filtered out from the completion list to avoid noise by always showing the default object properties. our experiments showed that most of the time these functions are not used.

**Comment by GlitchEnzo** [comment]
Thanks for the response.

Unfortunately, filtering out Object methods causes a side-effect where new methods defined on Object are also hidden from Intellisense.

For example:
```ts
interface Object {
    foo(): void;
}

Object.prototype.foo = () => {
    console.log("Object.foo()");
}

class Test {
}

window.onload = () => {
    var test = new Test();
    test.foo(); // no Intellisense, but it compiles and runs
};
``` 

Is there any workaround or process for defining new methods on primitive types?

**Comment by mhegazy** [comment]
> Is there any workaround or process for defining new methods on primitive types?

No. please note that they do not show in the list, but they are allowed, and go-to-def, etc, works.

**Comment by GlitchEnzo** [comment]
> please note that they do not show in the list, but they are allowed, and go-to-def, etc, works.

Yeah, the fact that it compiles and runs is great!  However, I'm trying to write a library that would be used by many people and I'm trying to add a method to Object (think System.Object.GetHashCode() in C#), and it would burdensome for other devs to commit to memory the method name and not rely on Intellisense or Autocomplete.

**Comment by mhegazy** [comment]
The system does not differentiate between something like toString and something like GetHashCode. they are all declarations on the `Object` interface, which is just a normal TS interface.

**Comment by GlitchEnzo** [comment]
Are you saying that I should create a feature request to add support for a decorator (or something similar) that tags methods as "exposed" to Intellisense?

Something like so:
```ts
interface Object {
    @exposeToIntellisense
    foo(): void;
}
```

**Comment by mhegazy** [comment]
> Are you saying that I should create a feature request to add support for a decorator (or something similar) that tags methods as "exposed" to Intellisense?

No, i am not saying that :) augmentation to the global Object is fairly uncommon. this is the first request i have seen in the past 4 years. so i would be inclined to punt on this one unless there is more requests.

**Comment by GlitchEnzo** [comment]
Okay.  Thanks for the dialog.  

I'll try to come up with my own solution for this issue.  :-)
