### ISSUE TITLE
Better error recovery after `.` followed by `return`

### ISSUE THREAD

**Issue by sant123** [microsoft/TypeScript#9597]
**TypeScript Version:**  1.8.10

Hi, I'm trying to make a generic function that include an **Array&lt;T&gt;** and a callback with a parameter **T** that returns an **OptionElement** interface.

**Code**

``` ts
interface OptionElement {
    text : string;
    value : string
}

function someFunction<T>(options : Array<T>, mapper : (data : T) => OptionElement){

}
```

The problem comes with the inference of the compiler when I pass my **Array&lt;SomeFakeElement&gt;** to `someFunction`

``` ts
interface SomeFakeElement{
    someText : string;
    someValue : string;
}

var a : SomeFakeElement[] = [{
    someText : "Text to show",
    someValue : "Text to eval"
}];

someFunction(a, function(someData){

    return {
        text : "Fake 1",
        value : "Fake 2"
    }
})

```

**Expected behavior:**

Show the right intellisense on object **someData** in the callback.

**Actual behavior:** 

The compiler says **T** is of type **SomeFakeElement**, but it does not offer completion:

![image](https://cloud.githubusercontent.com/assets/7959437/16711627/076beff8-462b-11e6-8cbd-9e1ba8712eda.png)

![image](https://cloud.githubusercontent.com/assets/7959437/16711632/175f2916-462b-11e6-8fa5-caa3078f0833.png)

Although, if I specify the type of someData it works!

![image](https://cloud.githubusercontent.com/assets/7959437/16711638/34da6dd4-462b-11e6-9bcf-8277e9516b54.png)

It's strange, isn't it?

Thank you for reading :smile:  

The whole code is:

``` ts
interface SomeFakeElement{
    someText : string;
    someValue : string;
}

interface OptionElement {
    text : string;
    value : string
}

var a : SomeFakeElement[] = [{
    someText : "Text to show",
    someValue : "Text to eval"
}]

function someFunction<T>(options : Array<T>, mapper : (data : T) => OptionElement){

}

someFunction(a, function(someData){
    return {
        text : "Fake 1",
        value : "Fake 2"
    }
})

```

**Comment by yortus** [comment]
I think it's just getting confused after you insert the `.`, when it tries to parse `someData. <whitespace> return...` and treats `return` as a property of `someData`. If you hover over the `return` keyword, the error states 'Property return does not exist on type 'SomeFakeElement'.

Try inserting a semicolon before you insert the `.` and everything works as expected:

![vscode9597](https://cloud.githubusercontent.com/assets/1252361/16712937/7c72dfa2-46c9-11e6-8bd8-1444417a73a2.png)

**Comment by sant123** [comment]
Thank you @yortus for your answer, yes I could notice that but; if you explicitly specify the type of someData like this:

```ts
someFunction(a, function(someData:SomeFakeElement){
	return {
		text : "Fake 1",
		value : "Fake 2"
	}
})
```
 You will notice Typescript does not get confuse.

**Comment by sant123** [comment]
Also there is something regarding with intellisense from the example above:

Here works as expected, I need to provide an object of type **Person** and offers intellisense.
![image](https://cloud.githubusercontent.com/assets/7959437/16715671/4aeb1fa2-46ac-11e6-93bc-6d3abd9581ae.png)

But here says that and empty object is not assignable to object **Person** but does not offer intellisense.
![image](https://cloud.githubusercontent.com/assets/7959437/16715659/f5fa522e-46ab-11e6-88df-252b036d18f3.png)

**Comment by DanielRosenwasser** [comment]
Yes, I think that the intermediate parse throws the type checker off, and makes the current call an error. Somehow this means that we won't try to infer the type of `someData`. We can possibly do better here, but it may be difficult.

**Comment by sant123** [comment]
I see @DanielRosenwasser, I think this is another case of the issue above..

![image](https://cloud.githubusercontent.com/assets/7959437/18524489/3084e98a-7a7e-11e6-8474-3956e3b47c23.png)

**Comment by Andarist** [comment]
It's worth noting that this is essentially the first issue that I could find about this problem, some newer ones can be found [here](https://github.com/microsoft/TypeScript/issues/54970) and [here](https://github.com/microsoft/TypeScript/issues/53124)

**Comment by DanielRosenwasser** [comment]
It does appear that the original issue is fixed though.
