### ISSUE TITLE
ES6 class member not showing in Intellisense

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#9599]
_From @jdforsythe on July 7, 2016 18:15_

- VSCode Version: 1.2.1
- OS Version: Windows 10

Steps to Reproduce:

1. Create a new `test.js` file

```js
'use strict';

class TestClass {
  constructor(prop) {
    this.property = prop;
  }

  GetLowerCase() {
    return this.property.toLowerCase();
  }
}

let a = new TestClass('ABC');
```

2. Type `a.` and check the Intellisense - it picks up class methods but not the property, even though a `console.log(a.property)` prints `"ABC"`

![js-intelli](https://cloud.githubusercontent.com/assets/286972/16664215/2182b852-444d-11e6-919e-fdc35034ebe6.PNG)

Contrast this with the same Typescript class.

```ts
class TestClass {
  property: string;

  constructor(prop: string) {
    this.property = prop;
  }

  GetLowerCase() {
    return this.property.toLowerCase();
  }
}

let a = new TestClass('ABC');
```

In TypeScript the Intellisense shows both the class method and the property.

![ts-intelli](https://cloud.githubusercontent.com/assets/286972/16664223/27603862-444d-11e6-87aa-440f3092acff.PNG)

Also, it works properly with the prototypical declaration.

```js
function TestClass(prop) {
  this.property = prop;
}

TestClass.prototype.GetLowerCase = function() {
  return this.property.toLowerCase();
};

let a = new TestClass('ABC');
```

![js-proto-intelli](https://cloud.githubusercontent.com/assets/286972/16664411/e701c8de-444d-11e6-9a62-686e5dc2929e.PNG)

_Copied from original issue: Microsoft/vscode#8849_

**Comment by dbaeumer** [comment]
Moving to TS team.

**Comment by mhegazy** [comment]
should be fixed in latest TS release.

![animation](https://cloud.githubusercontent.com/assets/8000722/16746729/9123bd20-4770-11e6-8bc4-2a3a00d6a072.gif)

**Comment by albertkim** [comment]
This is not working for me right now.

VSCode 1.5.2

jsconfig.json
```
{
  "compilerOptions": {
    "target": "es6",
    "module": "es6",
    "allowSyntheticDefaultImports": true
  },
  "excludes": [
    "node_modules",
    "build"
  ]
}
```

I do not get the instantiated class's properties showing like it does in the above gif.

**Comment by mhegazy** [comment]
Should be working correctly in latest drop of TypeSript (TS 2.0.2 or later). VSCode ships with an older version of TypeScript. Please see [Using Newer TypeScript Versions](https://code.visualstudio.com/docs/languages/typescript#_using-newer-typescript-versions) documentation for more details on updating your VSCode to use a different version of TypeScript.

**Comment by albertkim** [comment]
^ Thank you, that was it.

**Comment by mhegazy** [comment]
how are you exporting it?

**Comment by albertkim** [comment]
`export default class User {...}`

I have also tried with

`module.exports = class User {...}`

**Comment by mhegazy** [comment]
seems working to me using latest, and `typescript@next`. 
![animation](https://cloud.githubusercontent.com/assets/8000722/18720129/3a6860e2-7fdf-11e6-9294-abf6c5d53473.gif)
