### ISSUE TITLE
[Errors] empty/implements extends list

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript#96]
```TypeScript
class C extends {    }
```
 
Expected: !!! 'extends' list cannot be empty.

Actual: !!! Identifier expected.

See also:

tests/cases/conformance/parser/ecmascript5/ErrorRecovery/ExtendsOrImplementsClauses/parserErrorRecovery_ExtendsOrImplementsClause3.ts

for how error recovery is negatively impacted.

tests/cases/conformance/parser/ecmascript5/ErrorRecovery/ExtendsOrImplementsClauses/parserErrorRecovery_ExtendsOrImplementsClause4.ts

**Comment by DickvdBrink** [comment]
Fixed on Playground and baseline is here: https://github.com/Microsoft/TypeScript/blob/master/tests/baselines/reference/parserErrorRecovery_ExtendsOrImplementsClause1.errors.txt

**Comment by danquirk** [comment]
@DickvdBrink is a triage machine today, thanks again.
