### ISSUE TITLE
Unclear intent in error message for unused parameter property

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#9601]
nightly build

![image](https://cloud.githubusercontent.com/assets/937933/16715443/870e5430-46ad-11e6-83dc-489debdda181.png)

```typescript
class A {
	constructor(
		private used: string
	) {
		alert(used);
	}
}

new A('');
```

**Comment by mhegazy** [comment]
The private used is never used :). The error is for the property not the parameter.

**Comment by aleksey-bykov** [comment]
needs a clearer message doesn't it?

**Comment by DanielRosenwasser** [comment]
Fair enough. We should consider giving more distinct errors between the two for this reason.

**Comment by YuichiNukiyama** [comment]
👍 
What message are you think it is the best?

**Comment by aleksey-bykov** [comment]
my vote for at least: `Property 'used' is declared but never used.`
