### ISSUE TITLE
Function of return type void in interface can return anything

### ISSUE THREAD

**Issue by sant123** [Microsoft/TypeScript#9603]
**TypeScript Version:**  1.8.10

Hi, I have this code and as you can see the function greet has a return type of **void**.

**Code**

```ts
interface Person {
	name : string;
	lastName : string;
	greet : (person : this) => void;
}

declare var some : Person;

var obj : Person = {
	name : "Santi",
	lastName : "Aguilar",
	greet : function(person) {
		return "some string";
	}
}
```

**Expected behavior:**

Type **string** is not assignable to type **void**.

**Actual behavior:** 

No error.

However, if you explicitly specify the return type **void** in the implementation; it works!

```ts
var obj : Person = {
	name : "Santi",
	lastName : "Aguilar",
	greet : function(person) : void {
		return "some string"; //Type string is not assignable to type void.
	}
}
```

**Comment by aleksey-bykov** [comment]
cpnsider your vote to fix: https://github.com/Microsoft/TypeScript/issues/8584

**Comment by aleksey-bykov** [comment]
@RyanCavanaugh, this what rationale applies here? (doesn't seem to be the case of https://github.com/Microsoft/TypeScript/issues/8581#issuecomment-218877349)

**Comment by kitsonk** [comment]
There is no bottom type until TypeScript 2.0.  Therefore `void` in an interface is essentially saying "you should ignore a return value from a function.  But just like excess parameters, TypeScript evaluates if the resulting object can be conformed to the shape of the interface.  So the below is valid (although a bit surprising):

```typescript
interface Foo {
    foo(a: string, b: number): void;
}

const foo: Foo = {
    foo() {
        return 'bar';
    }
};
```

But then of course if you were to depend upon the [return type](http://www.typescriptlang.org/play/#src=interface%20Foo%20%7B%0D%0A%20%20%20%20foo(a%3A%20string%2C%20b%3A%20number)%3A%20void%3B%0D%0A%7D%0D%0A%0D%0Aconst%20foo%3A%20Foo%20%3D%20%7B%0D%0A%20%20%20%20foo()%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20'bar'%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%3B%0D%0A%0D%0Afunction%20bar(c%3A%20string)%20%7B%0D%0A%09console.log(c)%3B%0D%0A%7D%0D%0A%0D%0Abar(foo.foo())%3B%0D%0A) TypeScript would get upset:

```typescript
function bar(c: string) {
	console.log(c);
}

bar(foo.foo()); // error here
```

In TypeScript 2.0 we get the bottom type `never`, which is a hard "this will NEVER return a value" versus a soft "don't depend upon any returned value" and some more strictness around unused parameters which will allow us to enforce these contracts more specifically.
