### ISSUE TITLE
NPM package out-of-sync to NuGet myget package

### ISSUE THREAD

**Issue by pocesar** [Microsoft/TypeScript#9605]
**TypeScript Version:**  nightly (v2.0.0-beta-20160711-1)

**Expected behavior:**

Expected that NPM had the same version v2.0.0-beta-20160711-1

**Actual behavior:** 

Latest available on NPM is v2.0.0-beta-20160707

**Comment by mhegazy** [comment]
looks like we had an issue with the nighlty publish.

@paulvanbrenk can you take a look.

**Comment by yuit** [comment]
@pocesar we have some unexpected failure on our publishing machine. I just fixed it this morning and republish our nightly npm package. The version now should be `typescript@2.0.0-dev.20160711` let me know if your issue is fixed

**Comment by DanielRosenwasser** [comment]
Looks good to me! Feel free to reopen if you still see any issues @pocesar, and thanks for reporting this!

**Comment by pocesar** [comment]
it did thanks!
