### ISSUE TITLE
Partial interface "import" unexpected behavior

### ISSUE THREAD

**Issue by pocesar** [Microsoft/TypeScript#9606]
**TypeScript Version:**  nightly

**Code**

```ts
// some/file.ts
import * as mongoose from 'mongoose';

export interface ISomeInterface {
  id: string; 
  email: string;
  user: string;
}

export interface IDocument extends mongoose.Document, ISomeInterface {
}

export interface IModel extends mongoose.Model<IDocument> {
}

// app.ts
import { ISomeInterface } from './some/file';

export default function(m: ISomeInterface) {
  if (m.email) {
    return m.user;
  }
  return m.id;
}
```

**Expected behavior:**

Don't include the './some/file' when doing a `tsc -p`. I'm using the "system" and "es5" output, `outFile` to `public/app.js`

**Actual behavior:** 

The whole `./some/file` is being included in the output, which is a server-side model. it wasn't being included in Typescript 1.8, was only using the interfaces to do static checking

**Comment by mhegazy** [comment]
what do you mean included? are you using `--out`/`--outFile`?

**Comment by mhegazy** [comment]
nevermind. you are. looking again.

**Comment by mhegazy** [comment]
I just tried with TS 1.8, and it shows the same behavior. i do not think this ever changed. `--out`/`--outfile` will contain **all** the files in your compilation. `some/file` is pulled into your compilation by virtue of the `import`. if you do not want it, then use a .d.ts instead.

**Comment by pocesar** [comment]
hmm yes, the behavior using `tsc -p` isn't the same as using `grunt-ts`. using a `.d.ts` is the only way to do this?
