### ISSUE TITLE
TypeScript 2: implicit readonly vs mongoose

### ISSUE THREAD

**Issue by frogcjn** [Microsoft/TypeScript#9609]
As What's new in TypeScript [writes](https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#read-only-properties-and-index-signatures):

> An entity accessed through an ES2015 namespace import is considered read-only (e.g. foo.x is read-only when foo is declared as import \* as foo from "foo").

How about mongoose.Promise? It should be set by developer, as mongoose v4.10 [asks developer](http://mongoosejs.com/docs/promises.html) to set Promise:

``` ts
mongoose.Promise = global.Promise
```

my d.ts is edited for this purpose:

``` ts
declare module "mongoose" {
  let Promise: Function;
...
```

but it will trigger error, since it is implicit readonly.

So how about to add some other keywords like `mutable` to this Promise?

``` ts
declare module "mongoose" {
  mutable let Promise: Function;
...
```

**Comment by mhegazy** [comment]
This matches the [ES6 spec](http://www.ecma-international.org/ecma-262/6.0/#sec-module-environment-records), for libraries like these, consider using `default` export instead. e.g.:
```ts
import mongoose from "mongoose";
mongoose.Promise = ....;
```
off course this depends on the library and how it is crafted.

the other alternative is to use `import ... = require("..")` which does not enforce these semantics.
