### ISSUE TITLE
formatting does not work for newly created JavaScript file

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#9610]
_From @misaxi on July 7, 2016 11:49_

- VSCode Version: 1.2.1
- OS Version: Win/Mac

Steps to Reproduce:

1. open VSCode with project folder
2. create new file, with some code
3. format code via shortcut or command
4. nothing happens
5. switch to previous created file and change some thing
6. it works

_Copied from original issue: Microsoft/vscode#8833_

**Comment by dbaeumer** [comment]
Works for me. See Attachement. Do you have any additional steps?

![cast](https://cloud.githubusercontent.com/assets/1931590/16713140/12696214-469e-11e6-8ed3-2ab8b04ed3a2.gif)

**Comment by dbaeumer** [comment]
_From @misaxi on July 10, 2016 12:16_

@dbaeumer I don't know if you are using a beta version. My VSCode icon is in blue :)

But I've upload my gif to show what exactly happened.

Highlights
- open a folder with files. Code formatting works.
- create a new file, formatting does not work.
- close folder, and reopen the folder, it works again.

![2016-07-10_22-14-57](https://cloud.githubusercontent.com/assets/767799/16713465/ce37a4f4-46eb-11e6-8a67-d9ba3ba9a5c0.gif)

**Comment by dbaeumer** [comment]
Thanks for the steps. The difference to what I do is I create the new file in the explorer whereas you create a new empty file and then save. Need to see what differences in code paths that results in.

**Comment by dbaeumer** [comment]
The error occurs in the tsserver. The trace is:

```
Sending request: format (197). Response expected: yes. Current queue length: 0
Arguments: {
    "file": "p:/mseng/VSCode/Playgrounds/javascript/abc.js",
    "line": 1,
    "offset": 1,
    "endLine": 1,
    "endOffset": 60
}

Response received: format (197). Request took 3 ms. Success: false . Message: Error processing request. Cannot read property 'lineNumberToInfo' of undefined
```

**Comment by dbaeumer** [comment]
Some more tracing. This only happens if there is already a js in the workspace. If a first js file is created that way, no problem occurs. The full trace from the open of the test.js file for which formatting fails is:
```
Sending request: open (3). Response expected: no. Current queue length: 0
Arguments: {
    "file": "p:/mseng/VSCode/Playgrounds/bugs/8833/test.js",
    "fileContent": ""
}

Sending request: change (4). Response expected: no. Current queue length: 0
Arguments: {
    "file": "p:/mseng/VSCode/Playgrounds/bugs/8833/test.js",
    "line": 1,
    "offset": 1,
    "endLine": 1,
    "endOffset": 1,
    "insertString": ""
}

Sending request: geterr (5). Response expected: no. Current queue length: 0
Arguments: {
    "delay": 0,
    "files": [
        "p:/mseng/VSCode/Playgrounds/bugs/8833/test.js",
        "p:/mseng/VSCode/Playgrounds/bugs/8833/abc.js"
    ]
}

Event received: syntaxDiag (0).
Data: {
    "file": "p:/mseng/VSCode/Playgrounds/bugs/8833/test.js",
    "diagnostics": []
}

Event received: semanticDiag (0).
Data: {
    "file": "p:/mseng/VSCode/Playgrounds/bugs/8833/test.js",
    "diagnostics": []
}

Event received: syntaxDiag (0).
Data: {
    "file": "p:/mseng/VSCode/Playgrounds/bugs/8833/abc.js",
    "diagnostics": []
}

Event received: semanticDiag (0).
Data: {
    "file": "p:/mseng/VSCode/Playgrounds/bugs/8833/abc.js",
    "diagnostics": []
}

Sending request: projectInfo (6). Response expected: yes. Current queue length: 0
Arguments: {
    "file": "p:/mseng/VSCode/Playgrounds/bugs/8833/test.js",
    "needFileNameList": true
}

Response received: projectInfo (6). Request took 4 ms. Success: true 
Result: {
    "fileNames": [
        "p:/mseng/VSCode/vscode/extensions/typescript/server/typescript/lib/lib.d.ts",
        "p:/mseng/VSCode/Playgrounds/bugs/8833/test.js"
    ]
}

Sending request: change (7). Response expected: no. Current queue length: 0
Arguments: {
    "file": "p:/mseng/VSCode/Playgrounds/bugs/8833/test.js",
    "line": 1,
    "offset": 1,
    "endLine": 1,
    "endOffset": 1,
    "insertString": "console.log( \"Hello World \")                   ; // Comment"
}

Sending request: geterr (8). Response expected: no. Current queue length: 0
Arguments: {
    "delay": 0,
    "files": [
        "p:/mseng/VSCode/Playgrounds/bugs/8833/test.js",
        "p:/mseng/VSCode/Playgrounds/bugs/8833/abc.js"
    ]
}

Event received: syntaxDiag (0).
Data: {
    "file": "p:/mseng/VSCode/Playgrounds/bugs/8833/test.js",
    "diagnostics": []
}

Event received: semanticDiag (0).
Data: {
    "file": "p:/mseng/VSCode/Playgrounds/bugs/8833/test.js",
    "diagnostics": []
}

Event received: syntaxDiag (0).
Data: {
    "file": "p:/mseng/VSCode/Playgrounds/bugs/8833/abc.js",
    "diagnostics": []
}

Event received: semanticDiag (0).
Data: {
    "file": "p:/mseng/VSCode/Playgrounds/bugs/8833/abc.js",
    "diagnostics": []
}

Sending request: configure (9). Response expected: yes. Current queue length: 0
Arguments: {
    "file": "p:/mseng/VSCode/Playgrounds/bugs/8833/test.js",
    "formatOptions": {
        "tabSize": 4,
        "indentSize": 4,
        "convertTabsToSpaces": true,
        "newLineCharacter": "\n",
        "insertSpaceAfterCommaDelimiter": true,
        "insertSpaceAfterSemicolonInForStatements": true,
        "insertSpaceBeforeAndAfterBinaryOperators": true,
        "insertSpaceAfterKeywordsInControlFlowStatements": true,
        "insertSpaceAfterFunctionKeywordForAnonymousFunctions": true,
        "insertSpaceAfterOpeningAndBeforeClosingNonemptyParenthesis": false,
        "insertSpaceAfterOpeningAndBeforeClosingNonemptyBrackets": false,
        "placeOpenBraceOnNewLineForFunctions": false,
        "placeOpenBraceOnNewLineForControlBlocks": false
    }
}

Response received: configure (9). Request took 5 ms. Success: true 
Sending request: format (10). Response expected: yes. Current queue length: 0
Arguments: {
    "file": "p:/mseng/VSCode/Playgrounds/bugs/8833/test.js",
    "line": 1,
    "offset": 1,
    "endLine": 1,
    "endOffset": 60
}

Response received: format (10). Request took 3 ms. Success: false . Message: Error processing request. Cannot read property 'lineNumberToInfo' of undefined
```

Moving to the TS team since this looks like a project setup , ScriptVersion problem.

**Comment by robsonrosa** [comment]
@dbaeumer Are you using the [EditorConfig for VS Code](https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig) plugin?

@mhegazy I don't think it is a Typescript bug. It seems more a bug from the EditorConfig plugin. Let me explain what I mean.

I've had a similar problem: the intellisense didn't work when I created new files. After some tests, and removing all my plugins, I've realized that the problems stopped. After reinstalling my plugins one by one I could identify the guilty one: `EditorConfig for VS Code`.

I can reproduce this problem  as many times I install and uninstall the plugin. So, after some researches, I found this issue and [another one](https://github.com/editorconfig/editorconfig-vscode/issues/68). Last is a EditorConfig's issue and its related with autocomplete/intellisense. 

When I've got here and have noticed the exactly same error message (`Message: Error processing request. Cannot read property 'lineNumberToInfo' of undefined`) I knew these issues should be related. So, again, I reproduce the tests installing and uninstalling the plugin, but, this time, not only checking the autocomplete, but also the formatter. 

And guest what? Both problem occurs only when EditorConfig plugin is installed.

_Plugin **installed**:_
![with-plugin](https://cloud.githubusercontent.com/assets/2868031/18601485/76d9d848-7c39-11e6-98d2-74376289fc7f.gif)

_Plugin **uninstalled**:_
![without-plugin](https://cloud.githubusercontent.com/assets/2868031/18601497/85db2acc-7c39-11e6-9af1-1743f5f01bc9.gif)

**Comment by dbaeumer** [comment]
No

**Comment by robsonrosa** [comment]
I didn't expect this answer, @dbaeumer.  😕 
Do you have any installed plugin? Could you reproduce the bug with no installed plugin?

**Comment by zhengbli** [comment]
I don't think it is another plugin's problem, as I can repro on a clean installed vscode. Investigating.
