### ISSUE TITLE
inter-modules namespace merging not working?

### ISSUE THREAD

**Issue by nahuel** [Microsoft/TypeScript#9611]
I have two files:

```ts
// a.ts file
export namespace N {
    export interface A {}
}
```

```ts
// b.ts file
import {N} from "./a"

export namespace N {
    export interface B{}
}

var x : N.A   // ok
var y : N.B   // ERROR: Module '"./a".N' has no exported member 'B'
```

Note there is no error about B.N conflicting with A.N. 

**TypeScript Version:**  2.0.0-dev.20160630

**Comment by sandersn** [comment]
https://github.com/Microsoft/TypeScript/wiki/FAQ#why-dont-namespaces-merge-across-different-module-files

**Comment by sandersn** [comment]
Actually, that just redirects to http://stackoverflow.com/questions/30357634/how-do-i-use-namespaces-with-typescript-external-modules. Briefly, the answer is that modules don't allow merging, so the namespaces don't merge.

**Comment by nahuel** [comment]
ok, thanks @sandersn
