### ISSUE TITLE
Intellisense not working when creating new typescript file and referencing another ts file

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#9612]
_From @alverLopez on July 10, 2016 18:49_

- VSCode Version: 1.3.0
- OS Version: windows 10

Hello, it seems when i create a new ts file, intellisense doesn't recognize it when i reference it.
![vs_code_bug](https://cloud.githubusercontent.com/assets/8460975/16715418/69db472e-46df-11e6-8d78-54c0792253e4.png)

As you can see, intellisense doesn't show me Phaser options, when i restart vs code it starts to work

_Copied from original issue: Microsoft/vscode#9035_

**Comment by dbaeumer** [comment]
Moving to TS team

@alverLopez can you share the project. having steps or code to verify always helps to fix the problem.

**Comment by alverLopez** [comment]
Alright it's very simple.

Steps:

1.- Make any .ts file and define some class in it.
2.- Make a new .ts file and reference your first .ts file, define a new class and try to extend it with your first class, you will notice intellisense won't recognize the class in that first file.

Base.ts

`namespace example {
  export class BaseClass {
    constructor(public att1: number, public att2: number) { }
  }
}`


Child.ts
`/// < reference path="base.ts" />
namespace example {
export class ChildClass extends BaseClass { // At this point intellisense doesn't recognize BaseClass
}
}` 


Both files are in the same directory. You should notice the problem solves just when i restart VS Code.

**Comment by mhegazy** [comment]
on 1.4.0-insider, this is why i see.

![animation](https://cloud.githubusercontent.com/assets/8000722/16742341/222754b8-475c-11e6-9e1c-cf7a1f4cacbd.gif)

**Comment by alverLopez** [comment]
Effectively, i've tested Insiders and it recognices my classes when referencing their respective .ts file without needing to restart, maybe it's something fix that will come with new stable version.

P.D.: I don't know whether it should be tagged as SOLVED or ..., i'll let admins decide that.

**Comment by mhegazy** [comment]
the version of TS in the insider drop is the same as that in stable. if you see different behavior then this is a VSCode issue.

**Comment by alverLopez** [comment]
stable version is 1.3.0
insider version is 1.4.0

**Comment by mhegazy** [comment]
> the version of TS in the insider drop is the same as that in stable.

**Comment by alverLopez** [comment]
Mmm sorry, my mistake, i misread

**Comment by lostfields** [comment]
I got the same problem both in VS Code and VS2015 (NTVS) where I import classes, interface, enums to my new Extended Class, and when I export that along with the exposed interfaces and classes to my library code it shows only "import <name of interface>" and nothing more. It does not tell whether it is a class, an interface, enum or whatever - only import.

**Comment by mhegazy** [comment]
Should be working correctly in latest drop of TypeSript (TS 2.0.2 or later). VSCode ships with an older version of TypeScript. Please see [Using Newer TypeScript Versions](https://code.visualstudio.com/docs/languages/typescript#_using-newer-typescript-versions) documentation for more details on updating your VSCode to use a different version of TypeScript.
