### ISSUE TITLE
Visual Studio Intellisense not updated to 2.0.0

### ISSUE THREAD

**Issue by olmobrutall** [Microsoft/TypeScript#9623]
**TypeScript Version:**  2.0.0 beta

I've just installed TS 2.0.0 and while it compiles correctly, VS is not able to understand the new syntax.

![image](https://cloud.githubusercontent.com/assets/720953/16745757/a36be894-47b7-11e6-8f98-8b8d93157337.png)

Also in about looks like is still using the old version. 

![image](https://cloud.githubusercontent.com/assets/720953/16745752/9a4e0102-47b7-11e6-8cdb-fbbe29f9df4c.png)

I've updated the project file 

```XML
    <TypeScriptToolsVersion>2.0</TypeScriptToolsVersion>
```

And this is my tsconfig.json

````JSON
{
  "compilerOptions": {
    "target": "es5",
    "sourceMap": true,
    "module": "commonjs",
    "jsx": "react",
    "noEmit": true
  },
  "exclude": [ "node_modules" ]
}
````

**Comment by mhegazy** [comment]
The TS 2.0-beta installer needs [VS 2015 Update 3](https://www.visualstudio.com/en-us/news/releasenotes/vs2015-update3-vs). Please install the update first and then repair the installer.

**Comment by mhegazy** [comment]
Will update the blog post to make this clear as well. sorry about the confusion.

**Comment by olmobrutall** [comment]
Thanks, works now
