### ISSUE TITLE
VSCode (1.3) highlights nullable type as error in --strictNullChecks option (typescript@beta)

### ISSUE THREAD

**Issue by dodyg** [Microsoft/TypeScript#9626]
![funny-behaviour](https://cloud.githubusercontent.com/assets/1761249/16747973/c6d047c6-47c1-11e6-9a8f-9b0cf9ef62e2.png)

The VSCode is running on Windows 10. 

The code compiles just fine but the language service highlights nullable types as errors.

**Comment by mhegazy** [comment]
that is not using the latest. you need to set your ` "typescript.tsdk"`. but i guess that is not working for you correctly for some reason.

**Comment by dodyg** [comment]
I installed ```typescript@beta``` globally and  uses the following tsconfig.json

```
{
    "compileOnSave": true,
    "compilerOptions": {
        "target": "es5",
        "sourceMap": false,
        "noImplicitAny": false,
        "allowUnreachableCode": false,
        "allowUnusedLabels": false,
        "preserveConstEnums": true,
        "noImplicitReturns": true,
        "noFallthroughCasesInSwitch": true,
        "allowJs": false,
        "module": "commonjs",
        "moduleResolution": "node",
        "noUnusedLocals": true,
        "noUnusedParameters": true,
        "strictNullChecks": true
    },
     "exclude": [
        "node_modules",
        "typings"
    ]
}
```

```noUnusedLocals``` and ```noUnusedParameters``` are working fine so it is using TypeScript 2 at least for the compilation.

**Comment by mhegazy** [comment]
There is the compilation on the commandline, i.e. `tsc`, this will use your latest node package. and there is the VSCode experience, i.e. completion, errors in the editor, etc.. this uses `typescript.tssdk`. you need both to get both working.

**Comment by dodyg** [comment]
Ah got it. Thanks. It's working now.

```
    "typescript.tsdk": "C:\\Users\\xxxx\\AppData\\Roaming\\npm\\node_modules\\typescript\\lib"
```
