### ISSUE TITLE
@types/ioredis and the definition file from definitelytyped are not same

### ISSUE THREAD

**Issue by plantain-00** [Microsoft/TypeScript#9629]
**TypeScript Version:**  2.0.0 beta

**Code**
install @types/ioredis
```ts
import * as Redis from "ioredis";

let client: IORedis;
function init() {
    client = new Redis();
}
```

**Expected behavior:**
no error, same with tsd or typings
**Actual behavior:** 
error TS2503: cannot find namespace IORedis

**Comment by mhegazy** [comment]
use `Rediis.IORedis` instead. the file has been converted to a module. this ensures that it does not pollute the global namespace, and does not cause conflicts when multiple versions of it are loaded in the same compilation.

**Comment by plantain-00** [comment]
@mhegazy `Rediis.IORedis`?I tried:
```
let client: Redis.IORedis;
```
the error is TS2503: cannot find name Redis.

Current structure of ioredis is like socket.io, but @types/socket.io works.
I will change the structure later, make it more like express.js, hope this works.

**Comment by mhegazy** [comment]
Queued up a fix in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/10085/files. should be available in @types after it is merged and published.
