### ISSUE TITLE
Transpiling mess up the lexical scoping of arrow function

### ISSUE THREAD

**Issue by smangalath** [Microsoft/TypeScript#9630]
**TypeScript Version:**  1.8.0 / nightly (2.0.0-dev.201xxxxx)

**Code**
```ts
var CounterES6 = ()=>{
    console.log('Inside CounterES6')
    this.seconds = 0;
    setInterval(()=>{
        console.log('setInterval ' + this.seconds);
        this.seconds++;

    },1000)
}

var counterB = new CounterES6();
setTimeout(()=>{
    console.log('setTimeout '+ counterB.seconds);
},1000);
```
// A *self-contained* demonstration of the problem follows...

Result
Inside CounterES6
setInterval 0
setTimeout undefined
setInterval 1
setInterval 2
setInterval 3
setInterval 4
setInterval 5

Reason
Transpiled code doesn't store 'this' properly
```js
//ES6
var CounterES6 = function () {
    console.log('Inside CounterES6');
    _this.seconds = 0;
    setInterval(function () {
        console.log('setInterval ' + _this.seconds);
        _this.seconds++;
    }, 1000);
};
var counterB = new CounterES6();
setTimeout(function () {
    console.log('setTimeout ' + counterB.seconds);
}, 1000);
```
**Expected behavior:**
```js
var _this = this; // to be there
```
**Actual behavior:**

**Comment by mhegazy** [comment]
I do not get this output. there is something else going on that is not clear from this snippit.

here is the output i get:
```js
var _this = this;
var CounterES6 = function () {
    console.log('Inside CounterES6');
    _this.seconds = 0;
    setInterval(function () {
        console.log('setInterval ' + _this.seconds);
        _this.seconds++;
    }, 1000);
};
var counterB = new CounterES6();
setTimeout(function () {
    console.log('setTimeout ' + counterB.seconds);
}, 1000);

```

**Comment by smangalath** [comment]
Thanks for looking into this.
I am also getting the same output, however the transpiler puts   '_this' globally

Ideally, it should have been as shown below

`//ES6
//var _this = this;
var _global = 'Me';
var CounterES6 = function () {
    var _this = this;
    console.log('Inside CounterES6');
    _this.seconds = 0;
    setInterval(function () {
        console.log('setInterval ' + _this.seconds);
        console.log(_this._global); // should be undefined
        _this.seconds++;
    }, 1000);
};
var counterB = new CounterES6();
setTimeout(function () {
    console.log('setTimeout ' + counterB.seconds);
}, 1000);`

**Comment by smangalath** [comment]
It looks like the issue with arrow function being used as constructor function. If we change to normal function - like  the one provided below puts the var _this = this; inside the constructor function

`var CounterES6 = function(){
    console.log('Inside CounterES6')
    this.seconds = 0;
    setInterval(()=>{
        console.log('setInterval ' + this.seconds);
        console.log(this._global);
        this.seconds++;

    },1000)
}

var counterB = new CounterES6();
setTimeout(()=>{
    console.log('setTimeout '+ counterB.seconds);
},1000);`

**Comment by mhegazy** [comment]
this is not correct. as per the ES6 spec, lambda's do not have their own `this` binding. and inherit that of the containing  scope. in this case the scope is the global, and there is not much the compiler can do for that.

**Comment by smangalath** [comment]
Understood. Arrow function is not there with ES5 hence when transpiler see a lambda function being used for constructor function  then it could bind  the 'this' properly. Not remembering any use cases that should prevent a transpiler from doing that.

**Comment by mhegazy** [comment]
The transpiler emulates the semantics of ES6. The ES6 spec brhaviour is not what you are proposing.

**Comment by smangalath** [comment]
That is correct, I am referring to transpiling into ES5. Current behavior of the transpiler to ES6 is absolutely no issues.

**Comment by RyanCavanaugh** [comment]
I don't understand what would be desirable about having different behavior when targeting ES5 vs ES6. The goal of a transpiling language is to mask the differences between runtime feature levels, not magnify them.

**Comment by smangalath** [comment]
In ES6 , this.seconds stays bound to its container where as the transpiled  code into ES5 bind 'this' to the global space.
Expectation is to have same behavior between ES6 and ES5 but transpiler should be able to handle this appropriately by containing 'this' value with in the construction function ( in ES5 transpiled code).

**Comment by mhegazy** [comment]
> In ES6 , this.seconds stays bound to its container where as the transpiled code into ES5 bind 'this' to the global space.

The container in both cases is the global. this is the ES6 semantics. if you do not trust me, run it in chrome:

![image](https://cloud.githubusercontent.com/assets/8000722/16791937/5aceb65e-4878-11e6-88ee-e85ff9128305.png)

**Comment by smangalath** [comment]
I agree. My point is in ES6 form - an outer lambda used as function constructor will be stopped in both chrome as well as node  when an attempt is made to create an instance of it. Where  as in  ES5 transpiled form, it lets to create an instance but leaky to the global  'this'

**Comment by mhegazy** [comment]
The constructor issue is tracked by https://github.com/Microsoft/TypeScript/issues/1761
