### ISSUE TITLE
Visual studio 2015 with TS 2.0 braces auto complication are not working 

### ISSUE THREAD

**Issue by Anjmao** [Microsoft/TypeScript#9634]
I installed vs 2015 update 3 and typescript 2.0
![vs-version](https://cloud.githubusercontent.com/assets/3028012/16761609/8df44002-4829-11e6-81c5-37f57e8ef9c0.png)

I have braces complition enabled
![autocomplete-enabled](https://cloud.githubusercontent.com/assets/3028012/16761640/b3c6be72-4829-11e6-9164-eb38d697edb6.png)

But int ts files braces complition still not working. I see this issue is closed #1484.

**Comment by paulvanbrenk** [comment]
Can you confirm that you haven't enabled [dev mode in Visual Studio](https://github.com/Microsoft/TypeScript/wiki/Dev-Mode-in-Visual-Studio), and what's the date modified of this file: `C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TypeScript\typescriptServices.js`

**Comment by paulvanbrenk** [comment]
Checked in a fix

**Comment by Anjmao** [comment]
@paulvanbrenk Cool :) Is it typescriptServices.js fix or visual studio itself? How I can get this update :) ?

**Comment by paulvanbrenk** [comment]
@Anjmao This will be in the next release of TypeScript, it unfortunately required changes in the VS side of the code.
