### ISSUE TITLE
for of problem with Set

### ISSUE THREAD

**Issue by bbotond90** [Microsoft/TypeScript#9635]
I am following the handbook on this link
http://www.typescriptlang.org/docs/handbook/iterators-and-generators.html

When you run this code it generates a custom for statement that does not log anything.

**TypeScript Version:**  1.8.0 / nightly (2.0.0-dev.201xxxxx)

**Code**

```ts
let pets = new Set(["Cat", "Dog", "Hamster"]);
pets["species"] = "mammals";

for (let pet in pets) {
   console.log(pet); // "species"
}

for (let pet of pets) {
    console.log(pet); // "Cat", "Dog", "Hamster"
}

```
Here is the generated code
```js
var pets = new Set(["Cat", "Dog", "Hamster"]);
pets["species"] = "mammals";
for (var pet in pets) {
    console.log(pet); // "species"
}
for (var _i = 0, pets_1 = pets; _i < pets_1.length; _i++) {
    var pet = pets_1[_i];
    console.log(pet); // "Cat", "Dog", "Hamster"
}
```

**Expected behavior:**
The for of statement should log the values.

This js code captures though the expected values. (Expected js code)
```js
for(pet of pets){console.log(pet)}
```

**Actual behavior:** 
The ts script generates a for statement that has not capture any values

**Comment by kitsonk** [comment]
You need to target ES6 when using `for...of` with iterators.  The only down-emitting when targeting for ES5 that TypeScript does for `for...of` is arrays.

As per the documentation:

> When targeting an ES5 or ES3, iterators are only allowed on values of `Array` type. It is an error to use `for..of` loops on non-Array values, even if these non-Array values implement the `Symbol.iterator` property.

and:

> When targeting an ECMAScipt 2015-compliant engine, the compiler will generate `for..of` loops to target the built-in iterator implementation in the engine.

However you are polyfilling `Set` when targeting ES6 is confusing `tsc` making it think `Set` is an array, when it isn't (or you are ignoring the compiler errors).

**Comment by bbotond90** [comment]
OK. I see. I was just confused with the Playground's result and didn't realize this bit. I would expect a warning sign and a note above the example to know that it should not be tried in the Playground editor. (I think most of us (or just me) use this one when first reading the Handbook)
But you are right it is mentioned in the next section just below the example.

Thank you for your answer. :)
