### ISSUE TITLE
Publish pre-release versions of TypeScript via npm

### ISSUE THREAD

**Issue by robertknight** [Microsoft/TypeScript#964]
TypeScript in master contains many new and interesting features. It would be great if pre-release versions could be installed via npm. This would hopefully help get more testing and exposure for these features for downstreams who can tolerate the risks.

eg. via
````
npm install typescript@future
````

**Comment by vvakame** [comment]
closed by #3875 ?

**Comment by DanielRosenwasser** [comment]
Not just yet; I need to ensure that the nightly build script actually works when it gets triggered before closing.

**Comment by DanielRosenwasser** [comment]
Pretty confident it works so far. The command is

```shell
npm install -g typescript@next
```

**Comment by Arnavion** [comment]
@DanielRosenwasser How often are you guys going to publish? Then I can retire my repo :)

**Comment by DanielRosenwasser** [comment]
@Arnavion Nightly :D

Check around midnightish to see the end-of-day build.

**Comment by dsebastien** [comment]
Awesome news :)

**Comment by robertknight** [comment]
Indeed. Thanks so much!
