### ISSUE TITLE
Give possibility to cast JSX component

### ISSUE THREAD

**Issue by Strato** [microsoft/TypeScript#9643]
Hello,

I've been finding myself in the following situation multiple times since I started to use the combo React/TypeScript: I need to be able to cast a React component to any, since for technical reasons I cannot match the props the component expect (or thinks he expects).

I ended up doing this:

```
const ComponentAsAny = Component as any;

return (
    <ComponentAsAny someAttribute='foobar' />
);
```

I wish I could write this more inlined version instead:

```
return (
    <(Component as any) someAttribute='foobar' />
);
```

...or any other syntax you see fit. Maybe it's already possible and I missed something?

**Comment by mhegazy** [comment]
There does not seem to be a good solution. Expressions are not allowed in the JSX tag names, changing that is a diversion of the spec, and does look fairly foreign. Even with that in place, the closing tag, would it be the target of the expression`<(Component as any)...> </Component>`, or would it be another cast, `<(Component as any)...> </(Component as any)>`, what if you have more than one expression `<(Namespace as any).(Component as MyComponent)...> </?>`.... Moreover, the work around of using a declaration up top as in the OP does not feel totally hideous.

leaving it open to see if we get more user input on this.

**Comment by RyanCavanaugh** [comment]
Closing due to lack of feedback - this doesn't seem to come up enough to warrant us deviating from the JSX spec so severely. It's also very confusing as to what the closing tag would have to look like if this were allowed.
