### ISSUE TITLE
Suggestion: disallow for-in with Array types

### ISSUE THREAD

**Issue by danvk** [Microsoft/TypeScript#9645]
Here's a function I just wrote:

```ts
/**
 * Read a property from a nested object, e.g.
 * getIn({a: {b: 2}}, ['a', 'b']) --> 2.
 */
export function getIn(o: Object, path: string[]): any {
  for (const property in path) {
    o = o[property];
    if (!o) return o;
  }
  return o;
}
```

It type checks fine, but it has a bug! The `for .. in` should really be `for .. of`.

If a variable is known to have an array type, then using `for .. in` to iterate over it is a very strange thing to do. It will iterate over the indices, converting them to strings, and skip over any holes in the array.

I'd propose that `for .. in` with an Array be an error. You probably want `for .. of`. Or `array.forEach`. If you really want `for .. in` for some reason, you could always use `Object.keys(array).forEach`.

This might be better implemented as a lint rule. See https://github.com/palantir/tslint/issues/1380

**Comment by mhegazy** [comment]
I agree this is in the realm of linting. I would recommend writing a tslint rule for this.
