### ISSUE TITLE
Issue informative error message when calling function with too many arguments

### ISSUE THREAD

**Issue by bryanerayner** [Microsoft/TypeScript#965]
When invoking a function with more arguments than are declared, the error we give is basically "code is wrong." with no elaboration:
```ts
interface Foo {
    (x: number): void;
}

var n: Foo;
// Useful error: Argument of type 'string' is not assignable to parameter of type 'number'. 
n("");
// Useless error: Supplied parameters do not match any signature of call target.
n(1, 2);
```

We should issue a more descriptive error, e.g. "No call signature takes 2 arguments".

Comments from OP below

---
I'm working on a side project, implementing some Graph computations in Typescript.

I'm encountering a strange error with it being unable to implement a function that was overridden in a derived class.

I've included the source in a gist, it depends on lodash.d.ts from DefinitelyTyped.
https://gist.github.com/bryanerayner/269480242eaf461632a2

The error is on line 200 and 291. I'm really at a loss for how this could be an invalid invocation of the function.

Can this error message be improved to perhaps reveal to a programmer, the reason why their invocation is invalid?

**Comment by mhegazy** [comment]
closing in favor of #6045
