### ISSUE TITLE
ArrayLike should not have a readonly index signature

### ISSUE THREAD

**Issue by dasa** [Microsoft/TypeScript#9652]
**TypeScript Version:**  2.0.0

**Code**

```ts
// from lib.d.ts
interface ArrayLike<T> {
    readonly length: number;
    readonly [n: number]: T;
}
```

**Expected code:**

```ts
// from lib.d.ts
interface ArrayLike<T> {
    readonly length: number;
    [n: number]: T;
}
```

The change to `ArrayLike` to be read-only breaks lots of existing code.

**Comment by mhegazy** [comment]
Can you share a sample of what breaks? `ArrayLike` is mostly used in argument position, and not return type position in the library, so the change in this context is benign.

**Comment by RyanCavanaugh** [comment]
This would be problematic for other people because if `ArrayLike` demands write access, many functions that don't perform mutation on the array will now fail to accept `ReadOnlyArray` parameters. It seems much more likely that anyone accepting an `ArrayLike` *isn't* mutating the array than *is*.

**Comment by mhegazy** [comment]
I would recommend having another type that has the desired shape under a different namespace, e.g `glMatrix.ArrayLike` that would be writable. your type will be assignable to the global `ArrayLike` but not the opposite.
