### ISSUE TITLE
Compile error for generic type declaration: 'T' is declared but never used.

### ISSUE THREAD

**Issue by Jagged** [Microsoft/TypeScript#9656]
**TypeScript Version:**  2.0.0 beta

**Code**

```ts
interface XXX<T> {
    yyy(callback: (value: T | any) => any): XXX<T>;
}
```

**Expected behavior:** Compile without errors.

**Actual behavior:** Error on Line 1: Build:'T' is declared but never used.

This occurs when `<TypeScriptNoUnusedLocals>True</TypeScriptNoUnusedLocals>` is set within the csproj file.

**Comment by mhegazy** [comment]
There are really two `T`'s in this sample, there is the type parameter for `XXX` and there is the type parameter for `yyy`. they are not the same type parameter. the inner one shadows the outer one. in this case, the compiler did indeed catch a case of an unused type parameter.

**Comment by Jagged** [comment]
When I remove the T on line 2 it still errors.  I've amended the sample code.

**Comment by mhegazy** [comment]
```cmd
c:\test\9656>type a.ts
interface XXX<T> {
    yyy(callback: (value: T | any) => any): XXX<T>;
}
c:\test\9656>tsc --v
Version 2.0.0

c:\test\9656>tsc a.ts --noUnusedLocals

c:\test\9656>echo %ERRORLEVEL%
0
```

**Comment by ItGacky** [comment]
The bug is not fixed in @beta (2.0.0), but fixed in @next(2.1.0-dev.20160728).

**Comment by MortenChristiansen** [comment]
There is still an issue in v2.1.4.

The following code does not compile:

``````

**Comment by RyanCavanaugh** [comment]
> The following code does not compile since T is not used.

The error is correct. `T` is not used. It shouldn't exist. It does literally nothing. See https://github.com/Microsoft/TypeScript/wiki/FAQ#why-is-astring-assignable-to-anumber-for-interface-at--

**Comment by MortenChristiansen** [comment]
I get your point - this is just me coming from C# where interfaces are sometimes used for marking intent but I guess that does not make sense in TypeScript.

**Comment by seepel** [comment]
I believe I have a use case for a generic parameter that is not used in the interface itself. I'm essentially writing a sql builder and it is useful to type expressions even though they may not use the type directly in the interface, but rather in external functions/classes. For example:
```typescript
export interface Expression<T> {
    sql(): string;
    bindings?(): any[];
}

export class Bind<T extends boolean | string | number> {
    value: T;
    sql() {
        return "?";
    }
    bindings() {
        if (typeof value === "boolean") {
            return value ? 1 : 0;
        }
        return [ value ];
    }
}

export class Column<T extends string | number> implements Expression<T> {
     name: string;
     sql() {
        return this.name;
     }
}

export class Update<T> {
    constructor(public table: string; public column: Column<any>; public value: Expression<T>) {
    }
    sql() {
        return `UPDATE ${table} SET ${column.sql()} = ${value.sql()}`;
    }
    bindings() {
        return value.bindings ? value.bindings() : [];
    } 
}

export function update<T extends string | number>(table: string, column: Column<T>, value: Expression<T> | T) {
     return new Update(
        table, 
        column, 
        typeof value === "number" || typeof value === "string"
            ? new Bind(value)
            : value
    );
}
```

So you can then do the following:
```typescript
const column = new Column<number>("number_column");
const convenientUpdate = update("table_name", column, 1);
const explicitlyUpdate = update("table_name", column, new Bind(1));
```

So even though the `Expression` interface doesn't directly use the type, it is helpful in building type safe functions. I can't seem to find any other way to get the same effect.
