### ISSUE TITLE
Generic type argument cannot be inferred by nested callback return type

### ISSUE THREAD

**Issue by Igorbek** [Microsoft/TypeScript#9660]
**TypeScript Version:**  1.8.10

**Code**

```ts
declare function a<T>(f: (x: T) => ((y: T) => T)): T;

a<number>(x => y => 1);	// works
a(x => y => 1);			// infers T as { }
a<string>(x => y => 1); // error, as expected
```

**Expected behavior:**
In `a(x => y => 1)`, `T` is inferred as `number` based on nested callback return type.
As shows `a<string>(x => y => 1)` example, the just cannot be anything else.

**Actual behavior:** 
In `a(x => y => 1)`, `T` is inferred as `{ }`.

**Comment by thorn0** [comment]
A similar (but not the same) situation: http://stackoverflow.com/questions/35613446/type-inference-for-functions-passed-to-generic-function-wrappers-like-debounce

**Comment by thorn0** [comment]
You can simplify your issue:
```ts
declare function a<T>(f: (x: T) => T): T;

a<number>(x => 1); // works
a(x => 1); // infers T as { }
```

Return values just are not used in type argument inference.

**Comment by Igorbek** [comment]
Thanks, then it's dup of #9659. Closing this.
