### ISSUE TITLE
Autocomplete Informed by String-Restricted Interface Set

### ISSUE THREAD

**Issue by M-Pixel** [microsoft/TypeScript#9661]
**TypeScript Version:**  1.8.0

Currently, given the following code,

``` ts
type SerTypeName = "Color" | "Number";
interface ISerDefBase {
    Type:SerTypeName;
    Required?:boolean;
    ReadOnly?:boolean;
}
interface ISerDefColor extends ISerDefBase {
    Type: "Color";
    Format: "RGB" | "HSL";
}
interface ISerDefNumber extends ISerDefBase {
    Type: "Number";
    Step?:number;
}
interface ISerDefNumberRestricted extends ISerDefNumber {
    Min:number;
    Max:number;
}
type ISerDefType
```

No autocomplete for possible Type values:
![image](https://cloud.githubusercontent.com/assets/4174312/16793971/bb967948-4889-11e6-963b-7441bc565d9d.png)
(Expected behavior: Intellisense suggests "Color" and "Number")

And autocomplete for possible property names is unaffected by Type value choice
![image](https://cloud.githubusercontent.com/assets/4174312/16793999/e2387100-4889-11e6-949a-4db8a71a2fbd.png)
(Expected behavior: Intellisense also suggests "Format")

As a reference of what behavior could be, see IntelliJ/WebStorm:
![image](https://cloud.githubusercontent.com/assets/4174312/16794017/1505ad3c-488a-11e6-9d85-bece75da62c0.png)

However, even that IDE's implementation does not suggest "Format" when "Color" is Type:
![image](https://cloud.githubusercontent.com/assets/4174312/16794046/4007026a-488a-11e6-9548-35e5584f138e.png)

The transpiler does a great job at following these type restrictions. By adding a Min, for example, I can't transpile without adding a Max. It only allows "Color" and "Number", and only allows for the proper sister fields. The Visual Studio half, however, does not properly inform Intellisense.

This sort of setup is necessary for libraries that assume fields in an object based on some type indicator field on that same object.

**Comment by RyanCavanaugh** [comment]
This has been fixed for the great majority of cases
