### ISSUE TITLE
--strictNullChecks doesn't recongnize error that throw from nested method

### ISSUE THREAD

**Issue by xujihui1985** [Microsoft/TypeScript#9664]
**TypeScript Version:**  1.8.0 / nightly (2.0.0-dev.201xxxxx)
2.0.0
**Code**

```ts
// A *self-contained* demonstration of the problem follows...
with --strictNullChecks options, 
always complain `function lack ending return`, I throw the error in another method instead of throw it right awary. doesn't recongnize method that throw error in another method.

```
![image](https://cloud.githubusercontent.com/assets/1619030/16798769/3a039a18-4920-11e6-801c-3801b40e691c.png)

![image](https://cloud.githubusercontent.com/assets/1619030/16798804/63607be2-4920-11e6-87f1-f5095a4ba981.png)

**Expected behavior:**
should compile success
**Actual behavior:** 
can not be compiled

**Comment by RyanCavanaugh** [comment]
Same root cause as #9655

**Comment by xujihui1985** [comment]
@RyanCavanaugh thanks for reply
