### ISSUE TITLE
TS 2.0 beta breaks VS2015U3

### ISSUE THREAD

**Issue by SaschaNaz** [Microsoft/TypeScript#9665]
**TypeScript Version:** 2.0 beta

**Repro**

1. Create a new JS Windows app project (or make sure `<TypeScriptToolsVersion>2.0</TypeScriptToolsVersion>` in existing .jsproj file)
2. Add a TS file (file.ts here)
3. Build

**Expected behavior:**

App should be built.

**Actual behavior:** 

APPX070: Payload file '(some directory)/file.js' does not exist.

**Comment by mhegazy** [comment]
@paulvanbrenk can you take a look

**Comment by paulvanbrenk** [comment]
Can you share the diagnostic build logs?

**Comment by SaschaNaz** [comment]
Sorry for late response.

This is the build output:

```
1>------ Build started: Project: App2, Configuration: Debug Any CPU ------
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\AppxPackage\Microsoft.AppXPackage.Targets(2151,5): error APPX0702: Payload file 'C:\Users\sasch\Documents\GitHub\App2\App2\App2\js\file.js' does not exist.
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\AppxPackage\Microsoft.AppXPackage.Targets(2151,5): error APPX0702: Payload file 'C:\Users\sasch\Documents\GitHub\App2\App2\App2\js\file.js.map' does not exist.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
========== Deploy: 0 succeeded, 0 failed, 0 skipped ==========
```

Deploy works if I insert that TypeScriptProjectDir tag.

**Comment by paulvanbrenk** [comment]
@SaschaNaz  thanks for confirming the tag fixes it.. closing it since the fix will be in the next release of TypeScript 2.0
