### ISSUE TITLE
TypeScript Intellisense sometimes lose track of project definitions.

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#9666]
_From @thomthom on July 12, 2016 12:29_
- VSCode Version: 1.3.0
- OS Version: Windows 10

I don't have a way to reliably reproduce when I observe this, but I wanted to describe it:

I have a project where I use typings to manage definitions for third party libs. (https://github.com/typings/typings)

This saves me from having to use reference comments in every file - instead I rely on `import` statements entirely. 

This works well in VSC - at least when I initially open the project folder. Then after some while I start to get complains from Intellisense that objects and/or properties doesn't exists. These are stem from the definitions from `typings`. But by just restarting VSC the intellisense works fine again - for a while.

I've yet not been able to determine what trigger the intellisense to stop using the `typings` definitions during a session.

The compiler never run into issues - it's just the intellisense that fail after a while in a running session.

Anyone else experienced this? Or have any suggestions to what I can try to debug or create a reliable repro case?

Here is a screen capture that shows the bug in action - intellisense fails to pick up on my third party references. Then I close and reopen the project - and everything works again:

![visualstudiocodeintellisensebug](https://cloud.githubusercontent.com/assets/192418/16766845/adac8f40-483c-11e6-8713-717c01f4ce62.gif)

_Copied from original issue: Microsoft/vscode#9124_

**Comment by dbaeumer** [comment]
Moving to the TS team.

**Comment by thomthom** [comment]
I still experience this in 1.5.2. Anything I can try to provide a reproducible case?

**Comment by mhegazy** [comment]
a sample that we can use to debug locally would be great.

also can you try this on latest [TS drop](https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Nightly%20Builds.md#visual-studio-code). VSCode 1.5 ships with TS 1.8.

**Comment by thomthom** [comment]
The trouble is that I haven't found a reliable way to reproduce it. It happen after some time of use.

That link to the latest TS drop - will changing that also affect the Intellisense? (Because everything compile fine - it's just Intellisense that get confused eventually.)

**Comment by thomthom** [comment]
I finally got around to test this. I set the workspace's `typescript.tsdk` to use TS 2.0.3. Restarted VSC, and the IDE still highlight these as missing. 

What seem to have changed now is that I get the squiggly lines right away now. Not sure when that changed, maybe with VSC 1.6?

So while my `tsconfig.json` lists the definitions to use - which the compiler handles fine, the intellisense doesn't pick this up.

**Comment by mhegazy** [comment]
Can you share a project we can debug against?

**Comment by thomthom** [comment]
I don't have a project I can share publicly. I might be able to share it privately if there is a facility for that.

**Comment by thomthom** [comment]
It seems that a file was missing in `tsconfig.json`. I used `gulp` to build and it used a separate list of files to compile - hence the discrepancy of what compiled.

This issue can be closed.
