### ISSUE TITLE
@types for sources outside of DefinitelyTyped (previously grabbed through typings)

### ISSUE THREAD

**Issue by MarkPieszak** [Microsoft/TypeScript#9672]
**TypeScript Version:**  (2.0.0-dev.20160706)

Now that `@types/` is replacing typings, how can we handle *types* that were coming from things besides DefinitelyTyped, **like Github let's say**.

Previously in typings this was done by:
`"xhr2": "github:gdi2290/typed-xhr2#86ebfa644796b3a6553d22e62bb5e77fcae1eb8d"`

xhr2 isn't in @types (https://www.npmjs.com/~types)

How can this be achieved now, is this future functionality that will come in upcoming releases perhaps?

For now I'm still using typings for those definitions that aren't part of @types yet, which isn't the end of the world, just wanted to see if anyone else has been running into this!

**Comment by RyanCavanaugh** [comment]
Tracking this at the types-publisher repo: https://github.com/Microsoft/types-publisher/issues/4

**Comment by MarkPieszak** [comment]
Oh okay great thanks Ryan! Apologies.
