### ISSUE TITLE
Loose typing for ES6 Map/Set

### ISSUE THREAD

**Issue by use-strict** [Microsoft/TypeScript#9674]
**TypeScript Version:**  2.0.0

**Code**

```ts
// In lib.es2015.collection
interface MapConstructor {
    new (): Map<any, any>;
    // ...
}
```

Map, Set, WeakMap and WeakSet have unsafe constructor signatures. This leads to implicit unwanted behavior. They should be removed, in favor of their generic counterparts. Users who want unsafe code should use explicit casts, like this: `new Map<any, any>()`

**Comment by mhegazy** [comment]
We originally got feedback that users can not just write `new Map()`. this will break this experience.

**Comment by mhegazy** [comment]
here is the relevant discussion https://github.com/Microsoft/TypeScript/pull/3547

**Comment by use-strict** [comment]
Seems my memory doesn't serve me well :(. At that time, I worked around the problem by duplicating the lib, removing the offending definition and adding "noLib" flag, so it didn't bother me in my project, until I upgraded to 2.0.

Nonetheless, it makes little sense to allow untyped maps by default. It's also a hidden behavior and a source for design mishaps and they don't even count as implicit any. Being cumbersome to migrate shouldn't be a valid argument. On the same page, with a little exaggeration, it's also cumbersome to add type annotation to every single variable, now isn't it?

Some possible solutions, not in the standard library, but in the offending projects:
1. Add type parameters on usage: new Map`<any, any>`(); This should almost be second nature to beginners.
2. Augment the Map interface, in the scope of the project: `interface MapConstructor { new (): Map<any, any>; }`. This is for die-hards and most people will most probably not even bother, because it would be simpler to just fix the maps usages.
3. Most beginners add an `any` type annotation by default when something doesn't work. Let them f**k up their own project instead of pushing unsafe typings on the entire community.

@mhegazy , please pardon my effervescence, but I've struggled with these kinds of "easy way out" typings all over DefinitelyTyped. This is **Type**Script and the standard ts lib is no place for them IMHO. It just kills quality.

**Comment by kitsonk** [comment]
I think the argument is that it is consistent with `Array` and `ArrayConstructor`.  If you make the argument for `Map` you have to also argue that `ArrayConstructor` is unsafe, which I don't think you have.

Lots of parts of TypeScript use contextual inference as to "not get in the way".  If someone `new`s up something, I don't think it defaulting it's generics to `any` is overly surprising or unsafe.  Actually, by default, sometimes the defaulting to `{}` in many situations is surprising.

There is a little bit of inconsistency though in TS2.0:

```typescript
const a = Array(); // any[]
const b = new Array(); // any[]
const c = []; // never[]
```

Also to point out, there is no barrier to being explicit:

```typescript
const m = new Map(); // Map<any, any>
const n = new Map<string, number>(); // Map<string, number>
const d = Array<string>(); // string[]
```

I guess the argument though is that while we can disallow implicit `any` and even implicit `this` we cannot disallow these higher-order implicit values in other positions.  For example while we are really tight about no implicit `any` and making sure we are explicit, the change to inferring `never[]` for an empty array literal flagged up a few situations where we were being "lazy" that we were previously unaware of.

**Comment by use-strict** [comment]
> If you make the argument for Map you have to also argue that ArrayConstructor is unsafe, which I don't think you have.

Seems that I have actually: https://github.com/Microsoft/TypeScript/pull/3547#commitcomment-14191046

> I don't think it defaulting it's generics to any is overly surprising or unsafe

The statement is a contradiction by itself. Defaulting to any *IS* unsafe. Also, I didn't mean that generics should default to any. The default `{}` makes perfect sense, even if it's surprising for some. `{}` is an interface with no properties, so you will get errors the instant you try to access something, instead of silently swallowing them. The solution is to provide type parameters when instantiating.

> There is a little bit of inconsistency though in TS2.0:

Yes. `c` looks right. The other two are caused by the loose typings. I'm not sure though how `c` behaves with 'noImplicitAny'. Looks like a change from pre-2.0.

> Also to point out, there is no barrier to being explicit:

Being explicit is a conscious decision to override implicit behavior. This means you have to know and be aware of the implicit behavior. Since it's *cough* implicit, I think you can see where I'm going with this. 
```typescript
let x = new Map();
x.set(2, true);
x.set('2', false); // yaaaay everything works.
```

**Comment by kitsonk** [comment]
In < 2.0, `const c = [];` was inferred as `any[]` and did not flag up even with `noImplicitAny` set to `true`.

**Comment by use-strict** [comment]
Yes, but it would be a compile error with `noImplicitAny`.

**Comment by kitsonk** [comment]
> Yes, but it would be a compile error with `noImplicitAny`.

Sorry, I didn't think it was, but it is.
