### ISSUE TITLE
allow "export as namespace" in non-declaration files

### ISSUE THREAD

**Issue by nippur72** [Microsoft/TypeScript#9678]
According to #7125, the new `export as namespace`

> [...] is only legal as a top-level declaration a .d.ts file containing other top-level export declarations

Now this is a nuisance for library authors that are generating declarations via the `--declaration` flag, because everytime there's a recompile, `.d.ts` are rewritten and the `export as namespace` typed previously is gone. 

What about if `export as namespace` could be written in the actual code and exported in the generated `.d.ts` file? E.g.:

`myreact.ts`:
```ts
export function createElement() { /* ... */ };
export as namespace React;
```
(generated) `myreact.d.ts`:
```ts
export declare function createElement() {};
export as namespace React;
```

**Comment by mhegazy** [comment]
so what would the emitted code be?

**Comment by nippur72** [comment]
the emitted code would be none: `export as namespace` would be ignored in `.ts` but written into `.d.ts`.

**Comment by mhegazy** [comment]
mmm.. that is not what i would expect from a declaration like that in a .ts file. for instance `export =` does emit code, and do not expect you to assign the output to `module.exports` yourself. so why would this be any different.

**Comment by nippur72** [comment]
what about if the emitted code is a publishing into globals as per your suggestion in #8436 ?

**Comment by mhegazy** [comment]
yup. that is what i had in mind, though i forgot about that other comment :)

**Comment by mhegazy** [comment]
https://github.com/Microsoft/TypeScript/issues/8436 seems to have more details. would you mind moving this suggestion to https://github.com/Microsoft/TypeScript/issues/8436.

**Comment by nippur72** [comment]
closing as discussion merges with #8436
