### ISSUE TITLE
VisualStudio 2015 Community Edition TS code highlighting and compilation errors

### ISSUE THREAD

**Issue by Dimous** [Microsoft/TypeScript#9679]
I installed TypeScript Tools for Microsoft Visual Studio 2015 2.0.0.0 Beta and this is how VS started to behave:
![](http://i.imgur.com/5aW9WlB.png?1)
I completely uninstalled VS, then installed again with stable TS tools (1.8.6.), but no luck.
Now I can't compile my old projects. It stops with errors. Something wrong with lib.d.ts

**Comment by Dimous** [comment]
This is f'd up.

**Comment by paulvanbrenk** [comment]
Can you try deleting the component model cache `%localappdata%\Microsoft\VisualStudio\14.0\ComponentModelCache` and running `devenv /setup` from a `Developer Command Prompt for Dev 15` as an admin.

**Comment by Dimous** [comment]
it didn't help
![](http://i.imgur.com/UrHDGZj.png)

**Comment by Dimous** [comment]
Microsoft Visual Studio Community 2015
Version 14.0.25422.01 Update 3
Microsoft .NET Framework
Version 4.6.01038

Installed Version: Community

Visual Basic 2015   00322-20000-00000-AA383
Microsoft Visual Basic 2015

Visual C# 2015   00322-20000-00000-AA383
Microsoft Visual C# 2015

Visual C++ 2015   00322-20000-00000-AA383
Microsoft Visual C++ 2015

Application Insights Tools for Visual Studio Package   7.0.20622.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2015.1   14.1.20624.0
ASP.NET and Web Tools 2015.1

ASP.NET Web Frameworks and Tools 2012.2   4.1.41102.0
For additional information, visit http://go.microsoft.com/fwlink/?LinkID=309563

ASP.NET Web Frameworks and Tools 2013   5.2.40314.0
For additional information, visit http://www.asp.net/

Azure App Service Tools v2.9   14.0.20316.0
Azure App Service Tools v2.9

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.0.6000.0
Microsoft Azure Data Lake Tools for Visual Studio

Common Azure Tools   1.8
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

DataFactoryProject   1.0
Microsoft Data Factory Package

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

Microsoft .NET Core Tools (Preview 2)   14.1.20624.0
Microsoft .NET Core Tools (Preview 2)

Microsoft Azure Data Factory Node Node   1.0
Azure Data Factory extension for Visual Studio Server Explorer.

Microsoft Azure HDInsight HQL Service   2.0.6000.0
Language service for Hive query

Microsoft Azure HDInsight Tools for Visual Studio   2.0.6000.0
An integrated development environment for HDInsight application development.

Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Mobile Services Tools

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2015 - v2.9.40323.3

Microsoft Azure Tools   2.8
Microsoft Azure Tools for Microsoft Visual Studio 2015 - v2.8.40211.2

NuGet Package Manager   3.5.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

SQL Server Data Tools   14.0.60525.0
Microsoft SQL Server Data Tools

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript   2.0.0.0
TypeScript tools for Visual Studio

**Comment by paulvanbrenk** [comment]
Does this happen with each new project?

Can you delete `C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.0` and `C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TypeScript` and repair TypeScript 2.0 in add remove programs. If that doesn't help can you send the setup logs for TypeScript from `%temp%`, anything that starts with `dd_TypeScript_Dev14` and is from that repair attempt.

**Comment by Dimous** [comment]
Yes, with each new (and old).
I switched to VisualStudio Code, so this issue is not relevant for me anymore.

I uploaded dd_TypeScript_Dev14 logs - https://github.com/Dimous/dimous.github.com/tree/master/ts-issue-9679
