### ISSUE TITLE
Unable to enforce the interface type

### ISSUE THREAD

**Issue by smangalath** [Microsoft/TypeScript#9683]
Please note the following code snippet

'use strict';

interface Add{
    (a:number,b:number):number;
}

let addThis:Add = (a:number,b?:number)=>a+b;

console.log(addThis(1));

Observation : I have created an interface contract where I am able to make a variable optional which is in a way overriding what is stated in the contract. Not able to see any documentation support on this. Is it normal to override a contract like this ?
It is stopping at the time of addThis(3) only. Ideally the error should have been shown in the addThis function implementation itself. right ?

**Comment by RyanCavanaugh** [comment]
Your provided initializer can accept *at least* the same arguments as the interface requires, so it is substitutable and thus this code is valid. There's no reason to reject the provided expression as a valid `Add`.

See also the FAQ: https://github.com/Microsoft/TypeScript/wiki/FAQ
