### ISSUE TITLE
Allow Emitting Async Await Directly

### ISSUE THREAD

**Issue by saulshanabrook** [Microsoft/TypeScript#9691]
It would be helpful to turn off the transformation of async await code, to allow it to be emitted directly. The Typescript implementation has some bugs (like #4367) so I would prefer just letting [Babel handle this for me](https://babeljs.io/docs/plugins/transform-async-to-generator/).

**Comment by Arnavion** [comment]
Duplicate of #4692

**Comment by saulshanabrook** [comment]
Closed then as duplicate
