### ISSUE TITLE
Interface + Class of same name causes problems

### ISSUE THREAD

**Issue by jbrownson** [Microsoft/TypeScript#9699]
**TypeScript Version:**  1.8.0 / nightly (2.0.0-dev.201xxxxx)

2.0.0 beta

**Code**

1. 
```ts
interface Foo { doFoo(): void }
class Foo implements Foo {}
```

2.
```ts
interface Fooasdf { doFoo(): void }
class Foo implements Fooasdf {}
```

**Expected behavior:**

neither 1 nor 2 typecheck

**Actual behavior:** 

1 typechecks, but 2 doesn't

**Comment by RyanCavanaugh** [comment]
This is the intended behavior. Declaring an interface with the same name as a class is how you add methods to the class without implementing them (this is an important feature for some mix-in scenarios and other cases where non-TS code adds methods to classes).

**Comment by jbrownson** [comment]
wow mind blown w/ the response time, thanks for clarifying
