### ISSUE TITLE
`src/compiler/core.ts(903,50): error TS2304: Cannot find name 'endsWith'.`

### ISSUE THREAD

**Issue by basarat** [Microsoft/TypeScript#9711]
NTypeScript build failed : https://travis-ci.org/TypeStrong/ntypescript/builds/144606184#L864

This is the line : https://github.com/Microsoft/TypeScript/commit/8e679b7021ba0b1b078826647dc86fe5b676b322#diff-66cec844e251a1918deb897eabca206bR903

I think it should be fine, might be the way I am building ntypescript (my automation is starting to show its age ... is it still jake in ts official?). I just wanted to double check if maybe it is an error even here (and not just in my build tool chain) :rose:

**Comment by mhegazy** [comment]
should be in the last lines of checker.ts

**Comment by vladima** [comment]
can repro this, will submit the fix shortly
