### ISSUE TITLE
new --lib option errors on compiling angular2 app

### ISSUE THREAD

**Issue by cebor** [Microsoft/TypeScript#9721]
**TypeScript Version:**  2.0.0-beta

Im trying to compile a basic Angular2-app with the new `--lib` option and getting following error:

```
node_modules/@angular/core/src/testability/testability.d.ts(29,33): error TS2304: Cannot find name 'Node'.
```

**tsconfig.json**
```json
{
  "compilerOptions": {
    "target": "es5",
    "lib": ["es5", "es2015.promise", "es2015.collection"],
    "module": "commonjs",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "sourceMap": true
  },
  "exclude": [
    "node_modules"
  ],
  "compileOnSave": false,
  "buildOnSave": false,
  "atom": { "rewriteTsconfig": false }
}
```

When using the core-js typings or target "es6" without `--lib` option it works fine.

Seems the conflict is in `typescript/lib/es6.d.ts` line 14402, but i include only `es5`, `es2015.promise` and  `es2015.collection` as specified above.

AngularApp: https://github.com/cebor/ng2-start/tree/master/src

**Comment by jods4** [comment]
I think you need to include the `"dom"` lib if you want to use HTML DOM, which `Node` is part of.

**Comment by cebor** [comment]
thats it, thanks ...

**Comment by mailmrmanoj** [comment]
Please let me know where actually the `"dom"` should fit in?
