### ISSUE TITLE
How to extend a property by method

### ISSUE THREAD

**Issue by popomore** [Microsoft/TypeScript#9722]
**TypeScript Version:**  ~2.0.0

**Code**

``` ts
interface FuncType {
  (key: any): Object;
}

class A {
  prop: FuncType;
}

class B extends A {
  prop() {}
}
```

**Expected behavior:**

I want to define a method with a `FuncType`, and implement it in extended class.

**Actual behavior:** 

Got an error

Class 'A' defines instance member property 'prop', but extended class 'B' defines it as instance member function.

**Comment by aluanhaddad** [comment]
This is intentional because the semantics are very different. If you're looking at the type described by the base class, it suggests that `prop` does not require exicit binding of `this`, meaning that it can be referenced independently.

To implement the interface correctly write
```typescript
class B extends A {
  prop = () => {};
}
```

**Comment by RyanCavanaugh** [comment]
The fundamental restriction here is that `prop() { }` declares a prototype member, whereas `prop: Functype` declares an instance member. It's not possible for a prototype member to 'hide' an instance member, so any implementation declared this way would never be called.

It sounds like you might want to make `A` `abstract` based on your setup.
