### ISSUE TITLE
Spread operator with async & await feature caused the wrong compiled result

### ISSUE THREAD

**Issue by jumperchen** [Microsoft/TypeScript#9723]
**TypeScript Version:**  1.8.10

**Code**

```ts
class Foo {
    public async test(bar: any, ...baz: any[]): Promise<any> {
        const flag: boolean = await baz[0].test(bar);
        if (flag) {
            return baz[1];
        } else {
            return vals[2];
        }
    }
}
```

The compiled result in ES5 target with System module
```js
System.register([], function(exports_1, context_1) {
    "use strict";
    var __moduleName = context_1 && context_1.id;
    var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
        return new (P || (P = Promise))(function (resolve, reject) {
            function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
            function rejected(value) { try { step(generator.throw(value)); } catch (e) { reject(e); } }
            function step(result) { result.done ? resolve(result.value) : new P(function (resolve) { resolve(result.value); }).then(fulfilled, rejected); }
            step((generator = generator.apply(thisArg, _arguments)).next());
        });
    };
    var Foo;
    return {
        setters:[],
        execute: function() {
            var Foo = (function () {
                function Foo() {
                }
                Foo.prototype.test = function (bar) {
                    return __awaiter(this, void 0, Promise, function* () {
                        var baz = [];
                        for (var _i = 1; _i < arguments.length; _i++) { //<-- this arguments is in wrong scope
                            baz[_i - 1] = arguments[_i];
                        }
                        var flag = yield baz[0].test(bar);
                        if (flag) {
                            return baz[1];
                        }
                        else {
                            return vals[2];
                        }
                    });
                };
                return Foo;
            }());
        }
    }
});
```

**Expected behavior:**
the **arguments** should be a scope of the Foo.prototype.test
**Actual behavior:** 
the **arguments** is in a scope of the __awaiter's function generator.

**Comment by Arnavion** [comment]
`async` is not supported for ES5 target. You'll notice the compiler output `error TS1311: Async functions are only available when targeting ECMAScript 6 and higher.` and had non-zero exit code.

**Comment by jumperchen** [comment]
No, if we call this [function](https://github.com/Microsoft/TypeScript/blob/master/lib/typescript.d.ts#L2554), it won't throw any exception, which is the same as called by using [SystemJS](https://github.com/systemjs/systemjs/blob/master/lib/legacy-transpiler.js#L82)

**Comment by RyanCavanaugh** [comment]
`transpile` assumes you're not passing an invalid set of options. If a program and settings combination doesn't work in a regular compile, you can't assume `transpile` will produce valid output.

**Comment by jumperchen** [comment]
so, you mean this's a bug in [SystemJS](https://github.com/systemjs/systemjs) rather than TS?
because we use it as the build tool.

**Comment by mhegazy** [comment]
> so, you mean this's a bug in SystemJS rather than TS? because we use it as the build tool.

All we are saying is that this feature is not supported at the moment. so the fact that the output is invalid is not really a bug.

**Comment by mhegazy** [comment]
the full support for async..await for ES5 should be available in the nightly releases in the next few weeks.
