### ISSUE TITLE
Proposal: Allow initializers for literals/expressions in ambient declarations, as inlined values/expressions

### ISSUE THREAD

**Issue by zspitz** [Microsoft/TypeScript#9729]
The following:
```ts
declare namespace WIA.CommandID {
    var wiaFormatBMP = "'{B96B3CAB-0728-11D3-9D7B-0000F81EF32E}'";
    var wiaFormatGIF = "'{B96B3CB0-0728-11D3-9D7B-0000F81EF32E}'";
}
```
is currently invalid, because 
> Initializers are not allowed in ambient contexts

## Proposal
Where it is possible to inline the value/expression, the initializer should be allowed in the declaration, and the value/expression should be inlined at the call site. The following
```ts
var y = WIA.CommandID.wiaFormatBMP;
```
should emit:
```js
var y = "'{B96B3CAB-0728-11D3-9D7B-0000F81EF32E}'"; /*WIA.CommandID.wiaFormatGIF*/
```

This will allow for special values to be documented even if they are not available as static values from the library's global objects. For example:
```ts
declare namespace WIA {
    interface CommonDialog {
        ShowTransfer: (Item: any, FormatID?: string, CancelError?: boolean) => any;
    }
}
var cd: WIA.CommonDialog;
var item: any;
cd.ShowTransfer(item, WIA.CommandID.wiaFormatGIF)
```
`WIA.CommandID.wiaFormatGIF` is clearer than the magic value it represents, and can be used even though the shape of the library doesn't contain an actual implementation of `WIA.CommandID.wiaFormatGIF`.

## Specific use case
My specific case for this issue, is that Javascript code cannot read static methods on ActiveX libraries, because the only available entry point is the ```new ActiveXObject(`Namespace.Class');``` function, which returns an instance. This includes values of enums, which are usually numeric, but sometimes other types.
For numeric enums, this can be resolved by using `const enum` in the declaration, which inlines the values at the call site. But the issue still remains for string enums and enums of other types, and static constants declared in modules.

## Discussion - How far to inline?
a. Simple literals -- string, number, boolean etc.
b. Expressions composed of literals -- expressions whose sub-expressions are all simple literals.

    //declaration
    declare namespace LibConstants {
        var objectWithOnlyPrimitiveLiterals = {
            A: 1,
            B: true
        };
        var unixEpoch = new Date(1970,1,1);
    }
    //code
    var x = LibConstants.objectWithOnlyPrimitiveLiterals;

inlines to:

    //Javascript
    var x = {A:1, B: true} /* LibConstants.objectWithOnlyPrimitiveLiterals */;

c. Expressions referencing other inlinable expressions

    ```ts
    declare namespace LibConstants {
        var inlineableObject = {
            A: 1,
            B: {c: A},
            D: [A, B]
        };
    }
    //code
    var x = LibConstants.inlineableObject;
    ```

could inline to:

    //Javascript
    var x = {A:1, B: {c: 1}, D: [1, {c: 1}]} /* MyConstants.objectWithOnlyPrimitiveLiterals */;

My own feeling is that my specific use case doesn't require more than (a), and the others would add complexity to declaration parsing.

## Discussion - Inlining non-equal objects
Named values could be used in two ways:

  * to set properties or pass as function arguments
  * to compare against returned values of properties/functions

The second usage is only possible on types which have value equality, such as `string` or `number`:

    declare namespace LibConstants {
        var uneqalObject = {};
    }
    //code
    var result = someFunction();
    if (result == LibConstants.unequalObject) {
        //never gets here, because {} !== {}
    }

---
cc @basarat

**Comment by basarat** [comment]
@zspitz Thanks for the `@` mention :heart: 💯 but I am not a member of the TypeScript team, just a community guy :rose: Someone from the team will have a look / discuss with you further 👍

**Comment by zspitz** [comment]
@basarat It was in response to [your answer on SO](http://stackoverflow.com/a/38364029/111794).

**Comment by basarat** [comment]
> I thought you might be interested.

Thanks. Appreciate it 🌹

**Comment by kitsonk** [comment]
The whole purpose of ambient declarations is that they describe the environment around them and are fully erasable and have no run-time code.

If you want run-time code, why not use run-time constructs?

**Comment by RyanCavanaugh** [comment]
If we had `const` enums that allowed string values, would that be sufficient to handle this scenario?

**Comment by zspitz** [comment]
@kitsonk The rationale is the same as for allowing `const enums` in ambient declarations - instead of having to write code that uses literal magic values (like the GUIDs in the example), we can write code that is self-descriptive.
It's not quite runtime code; it's the introduction of names that will get erased afterwards, much like the type annotations themselves.

@RyanCavanaugh That would be useful in some scenarios, but sometimes there are modules with static constants, and each constant could have a different type.
```ts
namespace FAXCOMEXLib {
    namespace FaxConstants {
        var bstrGROUPNAME_ALLDEVICES =  '<All Devices>';
        var lDEFAULT_PREFETCH_SIZE = 100;
    }
}
Enums serve a dual purpose - they limit values to a certain set within the parent type (number, or string, or whatever), and they also help code be more self-documenting by assigning names to those values. Even where the first purpose is not relevant, I think there is still value in the name assignment..

**Comment by RyanCavanaugh** [comment]
I don't understand this fully then. If there *is* a `FAXCOMEXLib.FaxConstants.bstrGROUPNAME_ALLDEVICES`, why does it need to be inlined? If not, why not just place this in a `.ts` file and let it be resolved at runtime?

Or is it that you want ``FAXCOMEXLib.FaxConstants` to *appear* as it if has a `bstrGROUPNAME_ALLDEVICES` property, but in reality have that be inlined during compilation?

**Comment by zspitz** [comment]
@RyanCavanaugh The second option.
The library itself doesn't expose* `FAXCOMEXLib.FaxConstants.bstrGROUPNAME_ALLDEVICES` or even FAXCOMEXLib.FaxConstants.; if I were to try to use it in Javascript directly:
```js
var x = FAXCOMEXLib.FaxConstants.bstrGROUPNAME_ALLDEVICES;
```
I would get an error.

---
* Technically, in this case the library does expose these values; there is just no way to access them via Javascript.

**Comment by zspitz** [comment]
@RyanCavanaugh 
> I don't understand this fully then. If there is a `FAXCOMEXLib.FaxConstants.bstrGROUPNAME_ALLDEVICES`, why does it need to be inlined? If not, why not just place this in a .ts file and let it be resolved at runtime?
The same question could be asked of a `const enum` initialized in a declaration context:
```ts
declare const enum MyEnum {
    First = 1,
    Second = 2
}
```
If this Javascript:
```js
var x = MyEnum.First;
```
will not cause an error, then there is no need for inlining. If it will cause an error, then what is the whole enum doing in the declaration?
My understanding is this allows the declaration to describe special values _above_ the actual shape of the API.

**Comment by mhegazy** [comment]
with https://github.com/Microsoft/TypeScript/pull/9407, I am not sure we need this proposal. values mentioned in the OP can now be represented in the type space.

**Comment by zspitz** [comment]
@mhegazy With this proposal I can pass in the named value, even in a context which expects only a primitive type:
```
//declaration
declare namespace FAXCOMEXLib {
    var bstrGROUPNAME_ALLDEVICES =  '<All Devices>';
    var APICall: (s: string) => void;
}
//code
FAXCOMEXLib.APICall("an arbitrary string");
FAXCOMEXLib,APICall(FAXCOMEXLib.bstrGROUPNAME_ALLDEVICES);
```
Modelling this using literal types:
```
declare namespace FAXCOMEXLib {
    type APICallConstant = '<All Devices>' | string;
    var APICall: (arg: APICallConstant) => void;
    var LastAppliedDevice: APICallConstant;
}
```
means that calling code must use the special value:
```
FAXCOMEXLib,APICall('<All Devices>');
if (FAXCOMEXLib,.LastAppliedDevice == '<All Devices>') { //do something }
```
instead of using the name, in which the intent is clearer (if a little more long-winded):
```
FAXCOMEXLib,APICall(FAXCOMEXLib.bstrGROUPNAME_ALLDEVICES);
if (FAXCOMEXLib,.LastAppliedDevice == FAXCOMEXLib.bstrGROUPNAME_ALLDEVICES) {
    //do something
}
```

**Comment by mhegazy** [comment]
you would wirte this as:

```ts
//declaration
declare namespace FAXCOMEXLib {
    var bstrGROUPNAME_ALLDEVICES:  '<All Devices>';
    var APICall: (s: string) => void;
}
```

**Comment by zspitz** [comment]
Closed pending #9407.

**Comment by zspitz** [comment]
@mhegazy Will it be possible to simulate string enums using #9407?

**Comment by mhegazy** [comment]
You can do it today using a namespace and a union type.

**Comment by zspitz** [comment]
@mhegazy How can I attach a name to a specific value using a namespace and union type? This:
```
declare namespace WIA {
    type CommandID = 
        "'{B96B3CAB-0728-11D3-9D7B-0000F81EF32E}'"
        | "'{B96B3CB0-0728-11D3-9D7B-0000F81EF32E}'";
}
```
will not let me refer to the values by name; I have to write in the actual values.

**Comment by mhegazy** [comment]
I meant:
```ts
namespace CommandID {
  export type CommandID_1 = "'{B96B3CAB-0728-11D3-9D7B-0000F81EF32E}'";
  export const CommandID_1: CommandID_1 = "'{B96B3CAB-0728-11D3-9D7B-0000F81EF32E}'";

  export type CommandID_2 = "'{B96B3CB0-0728-11D3-9D7B-0000F81EF32E}'";
  export const CommandID_2: CommandID_1 = "'{B96B3CAB-0728-11D3-9D7B-0000F81EF32E}'";
}

type CommandID = CommandID.CommandID_1 | CommandID.CommandID_2;
```

**Comment by zspitz** [comment]
@mhegazy But can I do this in a declaration context?

**Comment by mhegazy** [comment]
here you go:

```ts
declare namespace CommandID {
  export type CommandID_1 = "'{B96B3CAB-0728-11D3-9D7B-0000F81EF32E}'";
  export const CommandID_1: CommandID_1;

  export type CommandID_2 = "'{B96B3CB0-0728-11D3-9D7B-0000F81EF32E}'";
  export const CommandID_2: CommandID_1;
}

declare type CommandID = CommandID.CommandID_1 | CommandID.CommandID_2;
```

**Comment by zspitz** [comment]
@mhegazy Is `CommandID.CommandID_1` inlined?
```
//Javascript
var x = "'{B96B3CB0-0728-11D3-9D7B-0000F81EF32E}'"; //CommandID.CommandID_2
```

**Comment by mhegazy** [comment]
No.

**Comment by zspitz** [comment]
@mhegazy The whole point of this proposal is to inline values declared in an ambient context. I understand that after #9407 this:
```
declare namespace FAXCOMEXLib {
    var bstrGROUPNAME_ALLDEVICES:  '<All Devices>';
}
var x = FAXCOMEXLib.bstrGROUPNAME_ALLDEVICES;
```
will inline to this:
```
var x = '<All Devices>'; //FAXCOMEXLib.bstrGROUPNAME_ALLDEVICES
```
(which is not currently happening with string literal types).
Am I missing something?

**Comment by mhegazy** [comment]
This is const string enums, which is not available right now.

**Comment by zspitz** [comment]
@mhegazy Is there any hope for const string enums?

**Comment by mhegazy** [comment]
The issue (#1206) is still open, so I would not rule it out.
