### ISSUE TITLE
Protected constructors should be accessible on subclasses's static methods

### ISSUE THREAD

**Issue by tinganho** [Microsoft/TypeScript#9734]
I think the below should be allowed. 

```ts
class A {
    protected constructor() {

    }
}

class B extends A {
    static create() {
        new B(); // ERROR, but should not error.
    }
}
```
I wanted to override a static factory and customise it a bit. But it seems like I wasn't allowed to do it.

And my motivation is that private constructors are accessible on a class's static methods.
```ts
class A {
    static create() {
        new this();
    }
    protected constructor() {

    }
}
```
And a natural extension of the private case is to allow protected constructors on subclasses's static methods.

**Comment by RyanCavanaugh** [comment]
Definitely a bug; this should be equivalent to the allowed
```ts
class A {
    protected constructor() {

    }
}

class B extends A {
	protected constructor() { super(); }
    static create() {
        new B(); // OK
    }
}
```
