### ISSUE TITLE
Salsa Feature Request: Support 'fuzzy' go to definition when not using commonJS

### ISSUE THREAD

**Issue by egamma** [microsoft/TypeScript#9737]
When a JS project doesn't use CommonJS as the module system then there is no support for 'go to definition'. Similar as is done for Intellisense where Salsa proposes global symbols that match, Salsa should provide some 'fuzzy' definition locations of a symbol.

This [extension](https://marketplace.visualstudio.com/items?itemName=jrieken.fuzzy-definitions) is an attempt to fill this gap. However, it is limited and it uses a full text search with some regular expression matching for location. Salsa could do much better than this.

**Comment by RyanCavanaugh** [comment]
Haven't seen other feedback on this; I think this has been addressed by a change in the default module settings of inferred projects. Closing since there's no repro to validate with.
