### ISSUE TITLE
The typescript language service in VS doesn't consider tsconfig's types entry

### ISSUE THREAD

**Issue by Tragetaschen** [Microsoft/TypeScript#9740]
**TypeScript Version:**  2.0.0-beta / "2.0.0.0" in Help -> About

**Code**

```json
"devDependencies": {
  "@types/jquery": "1.10.27",
  "typescript": "2.0.0"
}
```
```json
{
    "compilerOptions": {
        "types": ["jquery"]
    }
}
```
```ts
var a: JQuery;
```
Running `tsc` on the command line works as expected. When I remove for example the "jquery" entry from the `types` array in `tsconfig.json` I get the appropriate error for `a`.

**Expected behavior:**
Opening the ts file in Visual Studio 2015 with 2.0.0-beta installed should show no errors.

**Actual behavior:** 
VS complains about the type `JQuery` not known. When I manually add a
```ts
/// <reference types="jquery" />
```
VS stops complaining.

**Comment by mhegazy** [comment]
typeRoots does not seem to be honored either.
