### ISSUE TITLE
[typing]Cannot get type 'Request' from outside of @types/multer

### ISSUE THREAD

**Issue by plantain-00** [Microsoft/TypeScript#9751]
**TypeScript Version:**  2.0.0 beta

**Code**

installed @types/express and @types/multer .

``` ts
import * as express from "express";
import * as multer from "multer";

type Request = express.Request & multer.Request;
```

**Expected behavior:**
no error
**Actual behavior:** 
error

**Comment by RyanCavanaugh** [comment]
What's the error?

**Comment by plantain-00** [comment]
error TS2305 module multer has no exported nember Request.

**Comment by plantain-00** [comment]
Seems I can use Express.Request
strange

**Comment by plantain-00** [comment]
but the Express.Request is from express, not multer. through the Request in multer is declared in namespace Express
