### ISSUE TITLE
Proposal for functions with single callback

### ISSUE THREAD

**Issue by LexRiver** [Microsoft/TypeScript#9752]
With **async** and **await** keywords coding becomes a real joy.

I have a proposal for calling function with single callback that can be used in browsers also. And it is easy to implement.

Let's say we have two functions from some library:
```ts
function functionOne(param1, next){
    // some action
    next(param1);
}
function functionTwo(param1, param2, next){
    next(param1, param2);    
}
```

**Current usage**
```ts
functionOne(1, (x) => {
    functionTwo(x, 2, (a,b) => {
        console.log(x,a,b);
    });
});
```

**Proposal usage**
```ts
let x = await functionOne(1, waitfor next);
let [a,b] = await functionTwo(x, 2, waitfor next);
console.log(x,a,b);
```
which will be compiled to the code above.
There can be only one **waitfor** keyword per function. So if function have two callbacks that will not be possible.

**Comment by kitsonk** [comment]
Anti the [TypeScript design goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals):

> 6) Align with current and future ECMAScript proposals.
> 8) Avoid adding expression-level syntax.

If you feel your features are valid, you should consider championing them with the ECMAScript standards body via [ESDiscuss](https://esdiscuss.org/).

**Comment by basarat** [comment]
@LexRiver just curious which library you are trying to emulate / migrate / make easy to work with? :rose:

**Comment by RyanCavanaugh** [comment]
ESDiscuss is the appropriate channel for this. We really don't want to spec new async features -- it's important the runtime is on board and these kinds of features need to start there.
