### ISSUE TITLE
Control flow type analysis doesn't flow to a callback closure

### ISSUE THREAD

**Issue by zakjan** [Microsoft/TypeScript#9753]
**TypeScript Version:** 2.0.0 (installed today with `npm install typescript@beta`) with strictNullChecks enabled

**Code**

```ts
function plusOne(x: number): number {
    return x + 1;
}

function test(x?: number): Promise<number> {
    if (!x) {
        return Promise.resolve(0);
    }

    return Promise.resolve().then(() => plusOne(x));
}
```

**Expected behavior:**
no type error

**Actual behavior:**
error TS2345: Argument of type 'number | undefined' is not assignable to parameter of type 'number'.
  Type 'undefined' is not assignable to type 'number'.

**Comment by zakjan** [comment]
However when used outside of Promise, it is ok.
```ts
function test2(x?: number): number {
    if (!x) {
        return 0;
    }

    return (() => plusOne(x))();
}
```
This emits no error. What the difference? I believe it shouldn't be affected by Promise typings.

**Comment by kitsonk** [comment]
Essentially a dupe of #9263, #7719, #8541, #8552, #9491 (and many more...).  The root reason is discussed [here](https://github.com/Microsoft/TypeScript/issues/7719#issuecomment-202684512).

**Comment by zakjan** [comment]
Ah, ok, thanks a lot.
