### ISSUE TITLE
can't fully uninstall TS 2.0 beta tooling from VS 2015 Update 3

### ISSUE THREAD

**Issue by rostacik** [Microsoft/TypeScript#9758]
**TypeScript Version:**  TypeScript Tools for Microsoft Visual Studio 2015 2.0.0.0 Beta - 2016 07 08 nightly

Hello gents.
I am experiencing problem with TS 2.0 tooling. I am not able to uninstall TypeScript tools for Visual Studio that came with 2.0 beta package. I removed last stable version 1.8.6 and installed TS beta 2.0 from this URL : [TS 2.0.0.0](http://download.microsoft.com/download/6/D/8/6D8381B0-03C1-4BD2-AE65-30FF0A4C62DA/TS2.0.0-TS-release20-nightly-20160708.1/TypeScript_Dev14Full.exe). 
Now I want to remove TS 2.0 and return to 1.8.6 but I can't. I removed TS 2.0 from `Add or remove programs` but still I see TS tooling in Help, About.
![vs](https://cloud.githubusercontent.com/assets/429190/16874626/b60de3a4-4a9a-11e6-99a2-3db27dc26d16.png)

Information from about dialog about my VS 2015:
Microsoft Visual Studio Enterprise 2015
Version 14.0.25422.01 Update 3
Microsoft .NET Framework
Version 4.6.01055

Installed Version: Enterprise

Architecture and Modeling Tools   00322-80000-00000-AA186
Microsoft Architecture and Modeling Tools
    
UML® and Unified Modeling Language™ are trademarks or registered trademarks of the Object Management Group, Inc. in the United States and other countries.

Visual Basic 2015   00322-80000-00000-AA186
Microsoft Visual Basic 2015

Visual C# 2015   00322-80000-00000-AA186
Microsoft Visual C# 2015

Visual C++ 2015   00322-80000-00000-AA186
Microsoft Visual C++ 2015

Visual F# 2015   00322-80000-00000-AA186
Microsoft Visual F# 2015

.NET Portability Analyzer   1.1.10808.0
API portability analyzer.

Add Empty File   1.9
Gives the ability to add an empty file with any extension and starting with a dot

ASP.NET and Web Tools 2015.1   14.1.20624.0
ASP.NET and Web Tools 2015.1

ASP.NET Web Frameworks and Tools 2012.2   4.1.41102.0
For additional information, visit http://go.microsoft.com/fwlink/?LinkID=309563

ASP.NET Web Frameworks and Tools 2013   5.2.40314.0
For additional information, visit http://www.asp.net/

Azure App Service Tools v2.9   14.0.20316.0
Azure App Service Tools v2.9

Bundler & Minifier   2.1.258
Adds support for bundling and minifying JavaScript, CSS and HTML files in any project.

Chutzpah Context Menu   4.2.3
Enables you to run JavaScript unit tests via Chutzpah from the context menu

Chutzpah Test Adapter for Visual Studio 2012   4.2.3
Chutzpah adapter for the Visual Studio 2012 Unit Test Explorer. Chutzpah is an open source JavaScript test runner which enables you to run JavaScript unit tests from the command line and from inside of Visual Studio.

CodeMaid   10.1.93
CodeMaid is an open source Visual Studio extension to cleanup and simplify our C#, C++, F#, VB, PHP, PowerShell, R, JSON, XAML, XML, ASP, HTML, CSS, LESS, SCSS, JavaScript and TypeScript coding.

Command Task Runner   1.2.28
Adds support for command line batch files in Visual Studio 2015's Task Runner Explorer. Supports .cmd, .bat, .ps1 and .psm1 files.

Common Azure Tools   1.8
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

CssLint   1.0
Information about my package

DataFactoryProject   1.0
Microsoft Data Factory Package

File Nesting   1.0
Automatically nest files based on file name and enables developers to nest and unnest any file manually

Flatten Packages   1.1.14
Flattens the node_modules folder hierarchy by using the "flatten-packages" npm package behind the scenes. Works with long paths

GitHub.VisualStudio   1.0
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

GruntLauncher   1.1
Right click extension to launch Grunt commands

Image Optimizer   3.6.89
Uses industry standard tools to optimize any JPEG, PNG and Gifs - including animated Gifs. Can do both lossy and lossless optimization.

Image Sprites   1.2.36
Boost your website's performance by creating image sprites to reduce the amount of HTTP requests needed.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

JSLint.NET for Visual Studio   2.2.2
JSLint.NET for Visual Studio allows JavaScript files to be validated by JSLint.

Markdown Editor   1.5.110
A full featured Markdown editor with live preview and syntax highligting. Supports GitHub flavored Markdown.

Mexedge.Web.Extensions   1.0
Information about my package

Microsoft .NET Core Tools (Preview 2)   14.1.20624.0
Microsoft .NET Core Tools (Preview 2)

Microsoft Azure Data Factory Node Node   1.0
Azure Data Factory extension for Visual Studio Server Explorer.

Microsoft Azure HDInsight HQL Service   2.0.6000.0
Language service for Hive query

Microsoft Azure HDInsight Tools for Visual Studio   2.0.6000.0
An integrated development environment for HDInsight application development.

Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Mobile Services Tools

Microsoft Azure Tools   2.8
Microsoft Azure Tools for Microsoft Visual Studio 2015 - v2.8.40114.1

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2015 - v2.9.40323.3

Microsoft Azure Tools   2.7
Microsoft Azure Tools for Microsoft Visual Studio 2015 - v2.7.30818.1601

Mindscape Web Workbench   1.0
Accelerate and simplify your Web development experience with Visual Studio integrated Sass, Less and CoffeeScript support

MuleSoft.RAML.MuleSoft_RAML_ToolsPackage   1.0
RAML.NET Tools

Multilingual App Toolkit   4.0.1605.0
Multilingual App Toolkit helps you localize your Windows Store app by providing file management, pseudo and machine translation, translation editor, and build integration. http://aka.ms/matinstallv4

Node.js Tools   1.1.31117.00
Adds support for developing and debugging Node.js apps in Visual Studio

Node.js Tools - Profiling   1.1.31117.00
Profiling support for Node.js projects.

NuGet Package Manager   3.5.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

Open Command Line   2.1.175
Opens a command line at the root of the project. Support for all consoles such as CMD, PowerShell, Bash etc. Provides syntax highlighting, Intellisense and execution of .cmd and .bat files.

Open From Azure Websites   1.2.44
Open any Azure hosted web application as a Website Project.

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

Sassy Studio   0.2.0.0
Provides some support for sass / scss in visual studio

SQL Server Data Tools   14.0.60525.0
Microsoft SQL Server Data Tools

tangible T4 Editor   2.3.0
tangible engineering GmbH

TechTalk SpecFlow   2015.1
TechTalk SpecFlow - Binding business requirements to .NET code, http://www.specflow.org
Copyright © 2009–2013 TechTalk

ToolOptions Extension   1.0
ToolOptions Visual Stuido Extension Detailed Info

TypeScript   2.0.0.0
TypeScript tools for Visual Studio

Typewriter   1.0
Provides automatic TypeScript Template generation from C# source files

Visual F# Power Tools   2.5.0
A collection of additional commands for F# in Visual Studio

WakaTime   1.0

Web Analyzer   1.7.77
Provides static analysis directly in Visual Studio for JavaScript, TypeScript, JSX, CSS and more

Web Compiler   1.11.315
Compiler for LESS, Sass and CoffeeScript files

Web Essentials 2015.3   3.0.230
Adds many useful features to Visual Studio for web developers. Requires Visual Studio 2015

WebPack Task Runner   1.4.59
Adds support for WebPack in Visual Studio 2015's Task Runner Explorer.

**Expected behavior:**
`TypeScript tools for Visual Studio` to uninstall from VS 2015 with package from `Add or remove programs`.

**Actual behavior:** 
I don't see any package that I can uninstall from Windows of from VS 2015 but I still have support for TypeScript inside VS 2015.
Folder where VS 2015 stores it's TS package : `c:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TypeScript\`, 
extension.vsixmanifest states it's `<Identity Id="Microsoft.TypeScript.3D12078A-1A3F-4AFF-8B70-0037C0F580CD" Version="2.0.0.0" Language="en-US" Publisher="Microsoft" />`

**Comment by paulvanbrenk** [comment]
You should be able to remove this by uninstalling the MSI directly.. you can find it here:

`C:\ProgramData\Package Cache\{0B7B689E-5030-490F-99C4-4155F045C267}v2.0.0.0\packages\TypeScript_VS`

Note: I'm not sure if the GUID is unique for the package or the system, so if this exact folder doesn't exist search for `TypeScript_Dev14.msi` in the `ProgramData` folder and uninstall the most recent one.

**Comment by paulvanbrenk** [comment]
I checked in a fix to make this work for RC

**Comment by pksorensen** [comment]
When will we see RC ? I just vent over this also (repairing vs now, hoping it solves the problem). 

Another thing, you should consider having a repair option to restore typescript sdks, in `C:\Program Files (x86)\Microsoft SDKs\Typescript` as the visual studio repair do not restore them. I had to pick up 1.8 from another pc.

**Comment by pksorensen** [comment]
Small update, I have not uninstall visual studio totally and all related packages. Installed visual studio again and in the help dialog of visual studio, it still is writing typescript 2.0.0.0
