### ISSUE TITLE
getSourceFilePathInNewDir broken by recent commits

### ISSUE THREAD

**Issue by cartant** [Microsoft/TypeScript#9768]
**TypeScript Version:**  2.0.0-beta

@zhengbli The following commit appears to have broken the `getSourceFilePathInNewDir` implementation in certain circumstances:

[Use getCanonicalFileName](https://github.com/Microsoft/TypeScript/commit/d9bd31fc5288577100718c2d2278705b12dd0342)

The use of `getCanonicalFileName` breaks the implementation if the common directory is a parent of the current directory.

For example, with these files:

    C:/Users/Nicholas/example/a/a.ts
    C:/Users/Nicholas/example/b/b.ts

The common directory is `C:/Users/Nicholas/example`.

If the current directory is `C:/Users/Nicholas/example/b`, for the `a.ts` source file:

    cannonical source = ../a/a.ts
    cannonical common = ..

So `isSourceFileInCommonSourceDirectory` will be `true`.

However, for the `b.ts` source file:

    cannonical source = b.ts
    cannonical common = ..

So `isSourceFileInCommonSourceDirectory` will be `false` - which will result in the absolute path to the source file - `C:/Users/Nicholas/example/b/b.ts` - being returned.

Specifically, this change to the implementation breaks my [tsify-based](https://github.com/TypeStrong/tsify) builds.

**Comment by zhengbli** [comment]
I don't quite understand. The `sourceFilePath` is always an absolute path returned by `getNormalizedAbsolutePath`, and `getCanonicalFileName` only changes casing, so why does the cannonical source file path of `C:/Users/Nicholas/example/b/b.ts` become `b.ts`?

**Comment by cartant** [comment]
`getCanonicalFileName` does more than change the case; it returns a relative path. And if `C:/Users/Nicholas/example/b` is the current directory, `b.ts` is the cannonical path. The examples I gave were from console outputs I placed in the source - with some upper directory levels removed.

**Comment by cartant** [comment]
I think I see the problem.

`getCanonicalFileName` is implemented in the host, so it's `tsify`'s implementation that's being called. It's not calling the TypeScript implementation of [`getCanonicalFileName`](https://github.com/Microsoft/TypeScript/blob/master/src/compiler/program.ts#L851-L855) - which, as you've said, just changes the case.

Thanks. I guess I have something to fix in `tsify`.
