### ISSUE TITLE
Proposal - Class property helper

### ISSUE THREAD

**Issue by kitsonk** [Microsoft/TypeScript#9769]
# Scenario

Inspired by a conversation in #9733, it is a continual "shock" to many that `private` doesn't mean `private` at run-time and is nothing more than a design time only convention.  Most of the proposed solutions though require using a closure per instance to make these variables not visible.  While I personally prefer a `WeakMap` to not expose such variables, for those using `class` constructs and wanting to constrain the visibility of the properties on the class, using the keyword `private` is obviously far more comfortable.

While TC39 are considering [Class Property Declaration](https://github.com/jeffmo/es-class-fields-and-static-properties) there is no current proposal around visibility of properties.  That means at run-time `private` will still be a convention for a long long time.

I would say though one of the most surprising thing though is the enumerability of the `private` properties, as class instances could cause challenges at run-time when enumerating of the properties.
# Proposal

When emitting `private` members, add them to the instance using a helper which would define them as non-enumerable.  By using a new helper function, it would allow others to potentially change the way the properties are defined and potentially "future proof" TypeScript as the proposals of class properties are further refined.

There are no semantic changes with this proposal.  The only changes would be in the emit.

For example:

``` typescript
class Foo {
  private a: string;
  private b = 12;
  protected c: number;
  protected d = false;
  e: string;
  f = 'foo';
}
```

Currently results in a ES5 emit of:

``` js
var Foo = (function () {
    function Foo() {
        this.b = 12;
        this.d = false;
        this.f = 'foo';
    }
    return Foo;
}());
```

But would instead result in something like:

``` js
function __defineClassProperties(i, d) {
    var e, pd = {};
    for (var k in d) {
        e = !!(d[k].private || d[k].protected || false);
        pd[k] = { writable: true, configurable: true, enumerable: e };
        if ('value' in d[k]) {
          pd[k].value = d[k].value;
        }
    }
    Object.defineProperties(i, pd);
}

var Foo = (function () {
    function Foo() {
        __defineClassProperties(this, {
            a: { private: true },
            b: { private: true, value: 12 },
            c: { protected: true },
            d: { protected: true, value: false },
            e: { },
            f: { value: 'foo' }
    }
    return Foo;
}());
```

The above does not account for getter and setter properties, only because I have spent too much of my morning writing this, but I think the pattern of offloading the definition of class instance properties to a helper function could provide a better level of abstraction for something that may change in the future, allow protected and private members to be non-enumerable and potentially allow other developers to change the behaviour if they want to.

**Comment by aciccarello** [comment]
@kitsonk I understand the confusion that private variables can cause but I'm afraid that this proposal will cause TypeScript to deviate from the JavaScript it is meant to augment. Additionally, if someone wanted to migrate to vanilla JS by taking the ES2015 output their classes would be significantly mangled.

I did not understand well how the TC39 Class Property Declaration proposal factored into your motivation. Could you explain that more?

**Comment by kitsonk** [comment]
> but I'm afraid that this proposal will cause TypeScript to deviate from the JavaScript it is meant to augment.

How so?

> Additionally, if someone wanted to migrate to vanilla JS by taking the ES2015 output their classes would be significantly mangled.

I don't see how this differs from `__extend` in TypeScript for ES5...

> I did not understand well how the TC39 Class Property Declaration proposal factored into your motivation. Could you explain that more?

That is currently proposing a single level of visibility that any properties declared in the `class` are defined as own properties on the instance as `{ writable: true, enumerable: true, configurable: false }`.  (Note in the above, I should have set `configurable: false` to align with the proposal. There is no concept of a visibility keyword in the proposal.

That does mean, if and when this gets ratified, the current implementation will not be compatible with this proposal.  Since a) properties without values are still set on the instance and b) direct assignment results in a `configurable: true` versus `configurable: false`.  Therefore it is logical that considering offloading this to a helper now would make it easier to preserve forward compatibility, but also continue to allow support for the visibility keywords which are not part of the proposal (nor any current future proposal).  That would mean changes are less disruptive.

Once TC39 has ratified the proposal, the emit would simply change to preserving the public properties without a down emit and only utilise a helper for the non-public visibility ones, and then in maybe some point in the future, when visibility keywords are adopted, that could be dropped as well.

**Comment by aciccarello** [comment]
@kitsonk Thanks for the explanation. If that proposal goes through I could see the merit of this change but I am still hesitant to support abstracting class implementations with a factory function. Even while the `__extends` helper adds another function to the output, a class's methods/properties are still being outputted in classic ES5 style.

It's a solid proposal though :rose:

**Comment by RyanCavanaugh** [comment]
I don't think this would be the default, but we could imagine an emit pipeline transform plugin (coming in 2.1) that would allow for this to happen. Certainly enough people have asked for it that it'd be nice to have some solution, even if that solution has side effects.

Meta-feedback: if you're going to :-1: someone's proposal, please post a brief comment about why.

**Comment by kitsonk** [comment]
There is a correction to this, there is now an active proposal for private fields that is at Stage 1 with TC39: https://github.com/tc39/proposal-private-fields

This differs greatly from the current TypeScript syntax.  It appears to be trying to solve the problem where descendent classes having to deal with visibility issues by "baking" the visibility directly into the property name, and obviously having to choose a different semantic from the standard convention of prefixing with `_`.  I am sure it will be going through a rather bumpy road.

**Comment by endel** [comment]
I believe there are only advantages in making `private` properties non-enumerable by default. 

Take this simple class as an example. 

```ts
// default TypeScript behavior when emitting private properties
class Enumerable {
    public a = 10;
    private b = 10;
}

// explicitly setting the private property as enumerable: false
function NonEnumerable () {
    this.a = 10;
    Object.defineProperty(this, 'b', {
        enumerable: false,
        value: 10
    });
}
```

**JSON.stringify()**

You usually don't want private properties to appear in your JSON.

```ts
console.log( JSON.stringify(new Enumerable()) )
// => {"a":10,"b":10}
```

```ts
console.log( JSON.stringify(new NonEnumerable()) )
// => {"a":10}
```

**for..in**

You shouldn't be allowed to loop through private properties like this. `enumerable.b` results in `Property 'b' is private and only accessible within a class 'MyClass`. But within a `for..in` loop it's fine.

```ts
let enumerable = new Enumerable();
for (let k in enumerable) {
    console.log(k, enumerable[k]);
}
// => a 10
// => b 10
```

```ts
let nonEnumerable = new NonEnumerable();
for (let k in nonEnumerable) {
    console.log(k, nonEnumerable[k]);
}
// => a 10
```

I understand that ES3 doesn't have the possibility to use `enumerable` , as discussed in https://github.com/Microsoft/TypeScript/issues/782, but the necessity to target ES5+ is much higher IMO.

Cheers!

**Comment by kitsonk** [comment]
Ultimately, I suspect the implementation of private fields as part of the ES fields proposal would make this redundant, and I don't have a personal interest in advancing this proposal.
