### ISSUE TITLE
VS2015 can't place breakpoint on last statement

### ISSUE THREAD

**Issue by nippur72** [Microsoft/TypeScript#9770]
**TypeScript Version:**  2.0.0 beta
**VS Community 2015:** v14.0.25422.01 Update 3
**Webpack:** 1.13.10 (not using `ts-loader`)

![screens](https://cloud.githubusercontent.com/assets/2598443/16894733/ebeaaa50-4b5f-11e6-968a-9f045a5a6eb0.png)

Can't place a breakpoint on a line if it's the last line of the file. 

In the above image `a=a+2;` is the last statement of the file (but there are various `\n` after). The tooltip says breakpoint can't be counted because there is no corresponding code due to compiler optimizations etc... (exact message is in localized so I am not reporting it).

But oddly, adding a line of comment makes it work:

![screen2](https://cloud.githubusercontent.com/assets/2598443/16894764/3a89ac32-4b61-11e6-965b-d8f85c587413.png)

**Comment by mhegazy** [comment]
@sheetalkamat has pushed a fix for this issue early last week. it should be in the next TS release.
