### ISSUE TITLE
[TS 2.0] Typescript does not assert/throw/error when an empty array is path mapping value

### ISSUE THREAD

**Issue by TheLarkInn** [Microsoft/TypeScript#9772]
**TypeScript Versions:** 
*Beta:* _Version 2.0.0-dev.20160707_
*Nightly:* _Version 2.1.0-dev.20160716_

**Code**
My tsconfig.json
```json
{
    "compilerOptions": {
    	"baseUrl": "",
        "module": "es6",
        "target": "es5",
        "noImplicitAny": false,
        "sourceMap": false,
        "paths": {
        	"foo": []
        }
    },
    "exclude": [
        "node_modules"
    ]
}
```

**Expected behavior:**
The expected behavior after talking with @mhegazy would be that typescript errors because the path value is an empty array.

**Actual behavior:** 
Nothing happens.

**Asside**
However an error does happen when someone tries to use that mapped path (which makes sense because it maps to nothing.

**Comment by mhegazy** [comment]
PRs are welcomed.
