### ISSUE TITLE
code completion with "." and "(" broken again

### ISSUE THREAD

**Issue by nippur72** [Microsoft/TypeScript#9777]
this was fixed a year ago (see #3202), but after updating to TS 2.0 beta + VS2015 Community Update 3 the issue is back.

Eg: 
1) you have `JSO` but typing `.` does not autocomplete to `JSON`
2) you have `JSON.par` but typing `(` does not autocomplete to `JSON.parse(`

This in VS2015 Community Edition Update 3. 

In VSCode there is a slight different behaviour: 1) works but 2) doesn't

**Comment by mhegazy** [comment]
@paulvanbrenk thoughts?

**Comment by paulvanbrenk** [comment]
I checked in a fix on Thursday, after this was reported as #9424
