### ISSUE TITLE
ASI not working in this case

### ISSUE THREAD

**Issue by IOAyman** [Microsoft/TypeScript#9779]
**TypeScript Version:**  1.8.10

**Code**
```ts
const l = [2, 3, 4]
let head:any, tail:any

[ head, ...tail ] = l
console.log(head, tail)  // no semicolon here

[ head, tail ] = [ tail, head ]
console.log(head, tail)
```

**Expected behavior:**
Expected to compile to something like
```js
var l = [2, 3, 4];
var head, tail;

head = l[0], tail = l.slice(1);
console.log(head, tail);   // ASI should insert ; here

_a = [tail, head], head = _a[0], tail = _a[1];
console.log(head, tail);
var _a;
```
Expected to output
```
2 [ 3, 4 ]
[ 3, 4 ] 2
```

**Actual behavior:** 
But it compile to this
```js
var l = [2, 3, 4];
var head, tail;
head = l[0], tail = l.slice(1);
console.log(head, tail)[head, tail] = [tail, head];  // semicolon missing
console.log(head, tail);
```

**Here is a [demo in playground](http://www.typescriptlang.org/play/#src=const%20l%20%3D%20%5B2%2C%203%2C%204%5D%0D%0Alet%20head%3Aany%2C%20tail%3Aany%0D%0A%0D%0A%5B%20head%2C%20...tail%20%5D%20%3D%20l%0D%0Aconsole.log(head%2C%20tail)%09%09%2F%2F%20%3B%20should%20be%20inserted%20here%0D%0A%0D%0A%5B%20head%2C%20tail%20%5D%20%3D%20%5B%20tail%2C%20head%20%5D%20%20%2F%2F%20here%20as%20well%0D%0A%0D%0A%5B%20head%2C%20tail%20%5D%20%3D%20%5B%20tail%2C%20head%20%5D%0D%0A)**

**Comment by mhegazy** [comment]
unfortunately this valid JS grammar. The [JS ASI rules](http://www.ecma-international.org/ecma-262/6.0/#sec-rules-of-automatic-semicolon-insertion) do not list `[` as a location to add one. without a semi-colon this reads as:

`console.log(head, tail)` -> call express  
`[ head, tail ]` -> index into the result of the call express
`head , tail` -> this is a comma expression
` = [ tail, head ]` -> assignment
`[ tail, head ]`  -> array literal


So this is a valid JS production, and the TS parser is parsing it correctly.

**Comment by IOAyman** [comment]
I see. Thanks!
