### ISSUE TITLE
Types of property 'xxx' are incompatible

### ISSUE THREAD

**Issue by ruslanmogilevskiy** [Microsoft/TypeScript#978]
I`m switching from TS 0.9.5 to 1.1 CTP and have this simplified .d.ts:

```ts
interface FooArray<T> extends Foo<T[]> {
    subscribeTo(transform?: (val: any) => T): FooArray<T>;
}
interface Foo<T> {
    subscribeTo(transform?: (val: any) => T): Foo<T>;
}
```

Compilation has failed failed with:
 error TS2429: Interface 'FooArray<T>' incorrectly extends interface 'Foo<T[]>':
    Types of property 'subscribeTo' are incompatible:
      Type '(transform?: (val: any) => T) => Foo<T>' is not assignable to type '(transform?: (val: any) => T[]) => Foo<T[]>':
        Types of parameters 'transform' and 'transform' are incompatible:
          Type '(val: any) => T' is not assignable to type '(val: any) => T[]':
            Type 'T' is not assignable to type 'T[]':
              Property 'length' is missing in type '{}'.

Note that the TS 0.9.5 compiles the below code while 1.0/1.1-CTP does not.

Questions:
1) Shouldn't FooArray.subscribeTo should be treated as an overload and added to the FooArray`s contract? I.e. FooArray will have two subscribeTo methods.
2) How to fix it?

**Comment by diegovilar** [comment]
@RyanCavanaugh Any specific reason for that? Makes it a copy/paste job to extend+overload interface members...

**Comment by mhegazy** [comment]
resolving overloads is order dependent, not merging results in a more predictable system.
