### ISSUE TITLE
Use a TypeScript-specific option to enable/disable global solution analysis instead of C#'s

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript#9780]
Starting with VS 2015 Update 3, disabling full-solution-analysis under the C# tab in `Tools` -> `Options` -> `Text Editor` -> `C#` -> `Advanced` disables the TypeScript full-solution-analysis. the check should be specific to a language, or the check should be in a non-language specific page.

**Comment by mhegazy** [comment]
// CC: @CyrusNajmabadi

**Comment by mhegazy** [comment]
// CC: @vladima

**Comment by CyrusNajmabadi** [comment]
Tagging @hechang .  Heejae, do you know why setting the option for C# would affect TS?  This is obviously not good for their users :(

**Comment by paulvanbrenk** [comment]
The check no longer affects TypeScript. So moving to 2.1, since this is a little more involved than expected.

**Comment by daryllabar** [comment]
Any update on this?

**Comment by mhegazy** [comment]
Should be fixed in 15.7, we now have two options to disable checking for closed files, and disable loading of projects with no open files:

![image](https://user-images.githubusercontent.com/8000722/38143244-7ae9cc08-33f4-11e8-964c-d98ec34e4522.png)
