### ISSUE TITLE
Inconsistent behavior with @types when using tsc with a tsconfig

### ISSUE THREAD

**Issue by poke** [Microsoft/TypeScript#9785]
When using TypeScript 2, I get an inconsistent behavior for importing type definitions from `@types` when using `tsc` with an explicit `tsconfig.json` path versus not specifying one.

I have the following setup:

> **`package.json`**
```json
{
  "name": "typings-test",
  "devDependencies": {
    "@types/es6-shim": "*",
    "typescript": "^2.0.0"
  }
}
```

> **`tsconfig.json`**
```json
{}
```

> **`test.ts`**
```typescript
let x = new Set<string>();
```

After installing all dependencies with `npm install`, I call `tsc` once without arguments and once with `-p .`:
```
$ typings-test> tsc
$ typings-test> tsc -p .
test.ts(1,13): error TS2304: Cannot find name 'Set'.
```

As you can see, the latter fails because it cannot find a definition for `Set`. So the types that are located in `node_modules/@types/es6-shim/index.d.ts` are not loaded in this case.

**Comment by mhegazy** [comment]
@RyanCavanaugh can you take a look.

**Comment by RyanCavanaugh** [comment]
I can't repro this behavior with current sources (compilation succeeds either way). Can you set up a repo I can clone if you're seeing this with the current nightly build?

**Comment by Gekkio** [comment]
I'm not the original reporter of this issue, but here's a minimal example as a gist that can be easily cloned:

https://gist.github.com/Gekkio/720511fa701e7903ef48adc6e4898e39

I ran into this issue myself with 2.0.0 beta, but this example project reproduces the issue with the latest nightly build. Here's an example run on my machine:

```
$ git clone https://gist.github.com/720511fa701e7903ef48adc6e4898e39.git
Cloning into '720511fa701e7903ef48adc6e4898e39'...
remote: Counting objects: 5, done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 5 (delta 0), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (5/5), done.
Checking connectivity... done.
$ cd 720511fa701e7903ef48adc6e4898e39
$ npm i
ts-9785@0.0.0 /home/joonas/720511fa701e7903ef48adc6e4898e39
├── @types/node@4.0.29
└── typescript@2.1.0-dev.20160718
$ tsc
$ tsc -p .
main.ts(1,23): error TS2307: Cannot find module 'path'.
```

**Comment by RyanCavanaugh** [comment]
Odd, that repro also compiles both ways for me. I'll try on a Linux machine

**Comment by Gekkio** [comment]
The actual project I'm working on uses `@types/node`, `@types/react` and `@types/react-dom`, but only the node typing dependency has this issue. For example, `import * as fs from 'fs'` doesn't work, but `import * as React from 'react'` works.

**Comment by RyanCavanaugh** [comment]
Fix should be visible in next nightly build. Thanks!

**Comment by Gekkio** [comment]
Sweet! Thanks for the quick response and fix, Ryan :smile:

**Comment by poke** [comment]
That was indeed quick, thanks a lot!

For the record, I was seeing this on Windows machines (both the examples in this issue were broken for me on two different machines).
