### ISSUE TITLE
Visual Studio, Project with multiple tsconfig's with path mappings generates extra output's

### ISSUE THREAD

**Issue by Saulzi** [Microsoft/TypeScript#9786]
**TypeScript Version:**  (2.0.0.0)

I have a project which contains two adjacent folders one which contains source and one which contains tests, both have there own tsconfig.json and are set to output elsewhere on the filesystem

**Source tsconfig.json**
```
{
  "compilerOptions": {
    "baseUrl": "./",
    "sourceRoot": "./",
    "sourceMap": true,
    "outDir": "../scripts/Application",
    "target": "es3", 
    "module": "amd",
    "noImplicitUseStrict": true, 
    "noImplicitAny": false       
  },
  "compileOnSave": true
}
```

This outputs to the correct location.

**Tests tsconfig.json**
```
{
  "compilerOptions": {
    "baseUrl": "./",
    "sourceRoot": "./",
    "sourceMap": true,
    "outDir": "../scripts/Tests/",
    "paths": {
      "Application/*": [ "../Source/*" ]
    },
    "target": "es3",
    "module": "amd",
    "noImplicitUseStrict": true, 
    "noImplicitAny": false
  }
}

```

This outputs to the correct location but not as I would expect, I get the following

```
scripts/application/ - from other project 
scripts/tests/source/ - contents of source compiled
scripts/tests/tests/ - compiled tests
```

**I expect the following**
```
scripts/application
scripts/tests
```

**Comment by mhegazy** [comment]
all `.ts` files included in a compilation will be written to the output. in this case, i am assuming you have an import or a `/// reference` to the sources. so this will cause them to be written to the output as well.

if you do not want the test tsconfig.json to build the sources, then include the sources build .d.ts files instead of the .ts files.

**Comment by Saulzi** [comment]
So I have made some changes to my configuration and I now get the output I would expect. Although this still has some issues.

** Source tsconfig.json **
```
{
  "compilerOptions": {
    "baseUrl": "./",
    "sourceRoot": "./",
    "sourceMap": true,
    "declaration": true,
    "declarationDir": "../Typings/Application/",
    "outDir": "../scripts/Application",
    "target": "es3", 
    "module": "amd",
    "noImplicitUseStrict": true, 
    "noImplicitAny": false       
  },
  "compileOnSave": true
}

```

** Tests tsconfig.json **
```
{
  "compilerOptions": {
    "baseUrl": "./",
    "sourceRoot": "./",
    "sourceMap": true,
    "outDir": "../scripts/Tests/",
    "paths": {
      "Application/*": [ "../Typings/Application/*" ]
    },
    "target": "es3",
    "module": "amd",
    "noImplicitUseStrict": true, 
    "noImplicitAny": false
  }
}
```

The tests typescript project does not know that it depends on the application project so it would not build until I built the application project first and is not built in the correct order.
I could create another project in Visual Studio with build order etc as a workaround. It would be nice to be able to reference a typescript 'module project'. i.e I have a project with multiple source files which gets referenced via a alias i.e. 

**Application tsconfig.json**
`no changes`

**Tests**
```
{
      "referencedModules": {
             "application": "../Application/"
       }
}

```

I had no reference but files which live outside the root path.
