### ISSUE TITLE
digits not supporting in declaration filename (d.ts)

### ISSUE THREAD

**Issue by kalokamgit** [Microsoft/TypeScript#9790]
**Numeric value in the file name is changing the expected behaviour**

**Ex: Test123.d.ts**

```
declare namespace koti.sample.test {
    interface IModel123{
        property1: koti.another.type;  //issue here
    }
}
```

It is not resolving **koti.another.type**

** numeric value at the end of file should not impact the actual behaviour **

Koti

**Comment by RyanCavanaugh** [comment]
Please provide a complete repro.

**Comment by mhegazy** [comment]
The sample provided works fine. closing. please reopen if it is still an issue and provide more information.
