### ISSUE TITLE
uninitialized class properties allowed in strictNullChecks 

### ISSUE THREAD

**Issue by nippur72** [Microsoft/TypeScript#9797]
in `strictNullChecks`:
```ts
class Foo {
   someprop: string;
}
var a = new Foo();
a.someprop === undefined;
```

**Expected behavior:**
Do not allow to have `someprop` uninitialized, by requiring explicit initialization either directly or on the constructor.

**Actual behavior:** 
no errors

**Comment by RyanCavanaugh** [comment]
Duplicate of #8476
