### ISSUE TITLE
Compilation fails on Azure, even with 1.8.11 Nuget package installed

### ISSUE THREAD

**Issue by sheam** [Microsoft/TypeScript#9803]
TS Version: 1.8.11 nuget package

My TS compiles and runs fine locally, but build fails on Azure (using continuous deployment from git).

An example of offending code is:

        let numbers: number[] = getNumberList();
        for (let i = 0; i < numbers.length; i++)
        {
            let n = numbers[i];
            setTimeout(() => console.log(`number is ${n}`))
        }

**Expected behavior:**
Should compile and run fine even with output: "es5".

**Actual behavior:** 
When deployed to azure:
Loop contains block-scoped variable 'n' referenced by a function in the loop. This is only supported in ECMAScript 6 or higher.

My project is of the .csproj format, if that matters.

**Comment by mhegazy** [comment]
the error suggests a TS version of 1.6 possibly. and not TS 1.8. can you share your build log?

**Comment by sheam** [comment]
I added some code to force the error:

    private loop(): void
    {
        let data: number[] = [];
        for (let i = 0; i < 10; i++)
        {
            let n = Math.random();
            setTimeout(() => {
                data[i] = n;
            });
        }
    }

Here is the build log from Azure:

    Command: "D:\home\site\deployments\tools\deploy.cmd"
    Handling .NET Web Application deployment.
    MSBuild auto-detection: using msbuild version '14.0' from 'D:\Program Files (x86)\MSBuild\14.0\bin'.
    All packages listed in packages.config are already installed.
      StrangeBrew.Common -> D:\home\site\repository\StrangeBrewWeb\StrangeBrew.Common\bin\Release\StrangeBrew.Common.dll
      StrangeBrew.Data -> D:\home\site\repository\StrangeBrewWeb\StrangeBrew.Data\bin\Release\StrangeBrew.Data.dll
      StrangeBrew.Service -> D:\home\site\repository\StrangeBrewWeb\StrangeBrew.Service\bin\Release\StrangeBrew.Service.dll
      StrangeBrew.QuickBooksIntegration -> D:\home\site\repository\StrangeBrewWeb\StrangeBrew.QuickbooksIntegration\bin\Release\StrangeBrew.QuickbooksIntegration.dll
      StrangeBrew.Bootstrapper -> D:\home\site\repository\StrangeBrewWeb\StrangeBrew.Bootstrapper\bin\Release\StrangeBrew.Bootstrapper.dll
    D:\home\site\repository\StrangeBrewWeb\StrangeBrew.Web\ClientApp\Controllers\RecipeImportController.ts(311,9): error TS4091: Build: Loop contains block-scoped variable 'i' referenced by a function in the loop. This is only supported in ECMAScript 6 or higher. [D:\home\site\repository\StrangeBrewWeb\StrangeBrew.Web\StrangeBrew.Web.csproj]
    D:\home\site\repository\StrangeBrewWeb\StrangeBrew.Web\ClientApp\Controllers\RecipeImportController.ts(311,9): error TS4091: Build: Loop contains block-scoped variable 'n' referenced by a function in the loop. This is only supported in ECMAScript 6 or higher. [D:\home\site\repository\StrangeBrewWeb\StrangeBrew.Web\StrangeBrew.Web.csproj]
    Failed exitCode=1, command="D:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe" "D:\home\site\repository\StrangeBrewWeb\StrangeBrew.Web\StrangeBrew.Web.csproj" /nologo /verbosity:m /t:Build /t:pipelinePreDeployCopyAllFilesToOneFolder /p:_PackageTempDir="D:\local\Temp\8d3af8760634edb";AutoParameterizationWebConfigConnectionStrings=false;Configuration=Release;UseSharedCompilation=false /p:SolutionDir="D:\home\site\repository\StrangeBrewWeb\\"
    An error has occurred during web site deployment.
    \r\nC:\Program Files (x86)\SiteExtensions\Kudu\56.50706.2317\bin\Scripts\starter.cmd "D:\home\site\deployments\tools\deploy.cmd"

**Comment by sheam** [comment]
My .csproj this in it:     

    <TypeScriptToolsVersion>1.8</TypeScriptToolsVersion>

And I have the Microsoft.TypeScript.Compiler nuget package version 1.8.11 package installed. Is there something I have to do to tell msbuild to use this compiler instead of the default tsc?

**Comment by mhegazy** [comment]
Can you share your MSBuild log with /verbosity:detailed

**Comment by sheam** [comment]
This project builds fine locally. 

I only get this error when azure builds directly from git repository. So I really don't much about how azure builds. I will try setting my build to detailed, and see if that causes azure to build that way.

I guess what I am saying, is I don't know how to pass that switch to msbuild on azure.

**Comment by sheam** [comment]
Yeah, it appears that changing the build verbosity in VS only affects local builds, as it doesn't seem to change anything in azure build log

**Comment by sheam** [comment]
Solved, the problem was that I only had the typescript compiler package installed. I also need the typescript msbuild package installed.
