### ISSUE TITLE
VS2015 MSBuild settings not obeyed by IDE

### ISSUE THREAD

**Issue by PleasantD** [Microsoft/TypeScript#9804]
**TypeScript Version:**  1.8.11 (via Microsoft.TypeScript.MSBuild)
Visual Studio 2015 - TypeScript Extension v1.8.35.0

I'm using the MSBuild properties to set the TypeScript compiler options, partly because I like that I can easily set different options for release vs debug and partly because I started with (and need to support) VS2013 which didn't (doesn't?) have support for `tsconfig.json`. But to make the options more portable and easier to edit, I placed them in a separate `Project.TypeScript.props` file which I imported into my `csproj` file. The import for the custom settings is after the TypeScript props at the top of the file and before the TypeScript targets near the bottom.

**Expected behavior:**
The TypeScript compiler uses my custom settings.

**Actual behavior:** 
In VS2015 the TypeScript compiler uses my custom settings only when built using F5. The IDE reports errors that it shouldn't (like experimental decorators) and emits the wrong JS when recompiling on save.

Things seem to work correctly in VS2013.

**Comment by mhegazy** [comment]
Unfortunately the MSBuild APIs we use in VS to query these properties do not get us the values defined in other files. My recommendation would be to use tsconfig.json when possible, or include the properties in the project file directly.

**Comment by PleasantD** [comment]
It's disappointing that the compatibility and compilation story for this tool, and JS development in general, is so fractured. I shouldn't need to spend this much time figuring out how to make the tools do the same thing in three different build environments.
