### ISSUE TITLE
the poly-fills of 'Symbol', 'Set' etc.

### ISSUE THREAD

**Issue by imbubble** [Microsoft/TypeScript#9807]
**TypeScript Version:**  1.8.0 / nightly (2.0.0-dev.201xxxxx)

**Expected behavior:**

*target: es5*

Typescript implemented the poly-fills of `class` and `extends`.

wondering if it is possible to add poly-fills of the others, like `Symbol`, `Set` etc.

it seems reasonable.

**Comment by kitsonk** [comment]
TypeScript expressly does not provide polyfills.  It is an [anti-goal of the project](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals):

> 6) Provide additional runtime functionality or libraries. Instead, use TypeScript to describe existing libraries.

`class` and `extends` are not "polyfills" (functionality), they are syntax.  Just like the arrow function, async/await, generators, exponentiation, etc...

Using something like [core.js](https://github.com/zloirock/core-js) or other libraries is how this is accomplished.

Also this has been covered numerous times in this issue tracker.  We should really search the issues before opening new issues. 😢
