### ISSUE TITLE
Cannot define declared variable with the same property

### ISSUE THREAD

**Issue by NN---** [Microsoft/TypeScript#9811]
**TypeScript Version:**  1.8.0 / nightly (2.0.0-dev.201xxxxx)

**Code**

```ts
interface A {	
}

declare var A: {
    x: number;
}

class AShim implements A {
    x: number;
}

var A: {
     x: number;
} = AShim;
```

**Expected behavior:**
I expect this to compile successfully.

**Actual behavior:** 
```
a.ts(12,5): error TS2322: Type 'typeof AShim' is not assignable to type '{ x: number; }'.
  Property 'x' is missing in type 'typeof AShim'.
```

**Comment by kitsonk** [comment]
Classes have two interfaces, the instance interface and the static interface of the constructor function.  You are trying to assign something that is a class to something that is a simple object interface.  The static interface can be referenced as `typeof AShim` and `new AShim()` would produce something that is assignable to `A`.

To describe an interface that `AShim` could be assigned to, it would look like this:

```typescript
interface AConstructor {
    new (): A;
    prototype: A;
}

var A: AConstructor = AShim;
```

**Comment by NN---** [comment]
Why it works for other cases like this:

```ts

interface Blob {
    size: number;
    type: string;
    msClose(): void;
    msDetachStream(): any;
    slice(start?: number, end?: number, contentType?: string): Blob;
}

declare var Blob: {
    prototype: Blob;
    new (blobParts?: any[], options?: BlobPropertyBag): Blob;
}

class BlobShim implements Blob {
	constructor(blobParts?: any[], options?: BlobPropertyBag) { }
	msDetachStream(): any {}
	slice(start?: number, end?: number, contentType?: string): Blob {
		return null;
	}
	msClose(): void {}
	type: string;
	size: number;
}

// OK
var Blob: {
	prototype: Blob;
	new(blobParts?: any[], options?: BlobPropertyBag): Blob;
} = BlobShim;
```

**Comment by kitsonk** [comment]
Because BlobShim's interface matches the interface for `var Blob`.  Above, you were trying to put assign a constructor function/class to an instance interface, as I explained.  Here, you are assigning `BlobShim` to a constructor interface, which works.

**Comment by NN---** [comment]
@kitsonk Your example doesn't compile.

```ts
interface A {   
}

declare var A: {
    x: number;
}

class AShim implements A {
    x: number;
}

interface AInterface {
	x: number;
}

var A: AInterface = AShim;
```

**Comment by mhegazy** [comment]
@NN--- can you explain what is the original issue behind the OP?

**Comment by NN---** [comment]
@mhegazy I am writing tests with PhantomJS runner.
It doesn't have window.URL object, so I want to create my own.
The code worked well in TS 1.8 and stopped working in TS 2.0.
After some investigations I got to this minimal code sample.

I don't understand why it doesn't work while having the exact same types on both sides.

**Comment by wallverb** [comment]
@NN---  

Seems like you did not understand @kitsonk explanation

Here is your last full example adjusted to compile

```ts
interface A {   
}

declare var A: {
    x: number;
}

class AShim implements A {
    x: number;
}

interface AInterface {
    x: number;
}

var A: AInterface = AShim.prototype;
var A: AInterface = new AShim();

interface AInterface2 {
    new (): AInterface;
    prototype: AInterface;
}

var A2: AInterface2 = AShim;
```

**Comment by NN---** [comment]
@wallverb The only problem that I want to it without A2.

I want to define a variable of URL with my implementation.
How I do it ?
Thank you.

```ts
interface URL {
    hash: string;
    host: string;
    hostname: string;
    href: string;
    readonly origin: string;
    password: string;
    pathname: string;
    port: string;
    protocol: string;
    search: string;
    username: string;
    toString(): string;
}

declare var URL: {
    prototype: URL;
    new(url: string, base?: string): URL;
    createObjectURL(object: any, options?: ObjectURLOptions): string;
    revokeObjectURL(url: string): void;
}
```

**Comment by mhegazy** [comment]
all you need is somehting that has the shape of the the URL constructor, i.e. the type of the `var` `URL`.

so:
```ts
class URLShim {
    // instace side, i.e. interface URL
    hash: string;
    host: string;
    hostname: string;
    href: string;
    readonly origin: string;
    password: string;
    pathname: string;
    port: string;
    protocol: string;
    search: string;
    username: string;

    // Static side, i,e. typeof var URL
    constructor(url: string, base?: string) { }
    static createObjectURL(object: any, options?: ObjectURLOptions): string { }
    static revokeObjectURL(url: string): void { }
}

URL = URLShim;

```

**Comment by NN---** [comment]
@mhegazy **static createObjectURL** 
This does the trick :+1: 

Didn't think that 'static' affects on type matching, while it is logical though.
