### ISSUE TITLE
Compiler API compile errors

### ISSUE THREAD

**Issue by hriss95** [Microsoft/TypeScript#9814]
**TypeScript Version:**  1.8.10 

I am using the compiler API developing a project on my own. So far, I have not had any major problems in using the exported interfaces that it provides, but for some reason the compiler complains about the usage of the IndexInfo interface:

```
import * as ts from "typescript";
let x : ts.IndexInfo;
```
**Expected behavior:**
Should compile.

**Actual behavior:** 
Compile-time error: error TS2305: Module 'ts' has no exported member 'IndexInfo'.

As I said, I've had no problems so far trying to use exported interfaces. I've also had a problem with using NodeFlags: 

`ts.NodeFlags.Readonly` 

Compiler complains that NodeFlags has no exported member "Readonly", but there is no problem if I use other flags from the NodeFlags enum.
I am working with [https://github.com/Microsoft/TypeScript/blob/master/src/compiler/types.ts](url) to check what exported interfaces/enums/etc. are available to me.

**Comment by DanielRosenwasser** [comment]
`readonly` and the like were only added in TypeScript 2.0. Try using the beta and reopen the issue if you experience the same problem.
