### ISSUE TITLE
Compound assignments and narrowing

### ISSUE THREAD

**Issue by zhuravlikjb** [microsoft/TypeScript#9815]
Noticed a very strange behaviour with compound assignments and narrowing.

This works fine with a normal assignment:

``` ts
function moooo12() {
    var x: string | number = 5;
    x = x + "a";  // RHS "x" is narrowed, LHS "x" is not, everything right
    x;
}
```

This doesn't work, though:

``` ts
function moooo12() {
    var x: string | number = 5;
    x += "a"; // the compiler thinks that "x" is "number" here, and states that "string" is not assignable to it
    x;
}
```

Seems that in the last case the compiler shouldn't narrow the LHS "x" anyways, but rather it should specially calculate the result type of "+=" assignment taking into account the narrowed version of "x".

**Comment by DanielRosenwasser** [comment]
@ahejlsberg and I have actually discussed this: https://github.com/Microsoft/TypeScript/pull/9013#discussion_r66197725

Is there a use case you had in mind @zhuravlikjb?

**Comment by zhuravlikjb** [comment]
@DanielRosenwasser No particular use cases. I was supporting some corner cases in my own type guards mechanism, and stumbled upon the fact that the TypeScript compiler behaves strangely with compound assignments. I'm always a source of theoretical questions, sorry. :)

**Comment by DanielRosenwasser** [comment]
No worries! Looks like we have that in common. 😄

**Comment by RyanCavanaugh** [comment]
Closing due to lack of additional interest. The behavior here seems at least sometimes desirable.
