### ISSUE TITLE
Assignments in (user defined) type guards

### ISSUE THREAD

**Issue by ivogabe** [Microsoft/TypeScript#9818]
**TypeScript Version:**  2.0 beta

**Code**

```ts
let x: string | number = undefined as any;
function isString(x: any, y: any): x is string {
	return typeof x === "string";
}

if (isString(x, x = 4)) {
	x;
}
```

**Expected behavior:**
The type of `x` in the then-block should be `number` and the type guard `isString` should not be applied.

**Actual behavior:** 
The type guard `isString` is applied to `x`, resulting in `number & string`.

This could be fixed by blocking narrowing if an argument after the variable (that should be narrowed) contains an assignment. I think (and hope) that this only applies to user defined type guards, since other type guards are too restrictive in their syntax for these strange cases.

**Comment by ivogabe** [comment]
This applies to `instanceof` checks too:
```ts
let y: {} | number = undefined as any;
if (y instanceof (y = 1, Object)) {
	y;
}
```
The narrowed type of `y` is `Object`, should be `number`.

**Comment by aleksey-bykov** [comment]
(curious to see a real code fragment illustrated by the examples, hurts my eyes as written)

**Comment by mhegazy** [comment]
these examples, though illustrate a valid bug, do not seem common. I am inclined to mark this as won't fix.

**Comment by ivogabe** [comment]
This was luckily not real code. I think that the only possible situation in which this could happen, would be when passing a minified JavaScript file with allowJs. Though that sounds still very hypothetical.
