### ISSUE TITLE
Disable window typings

### ISSUE THREAD

**Issue by OliverJAsh** [Microsoft/TypeScript#9820]
I've noticed that all my TypeScript files have implicit typings for `window`, regardless of my configuration and where the files will be used (e.g. Node).

Is there a way to notify the compiler of the target environment (e.g. `browser: true/false`), and thus disable the `window` typings where possible?

**Comment by weswigham** [comment]
You should be able to achieve this by listing the specific lib parts you want to include using the `--lib` command and not including "dom" in this list.

**Comment by mhegazy** [comment]
specifically `--lib es5` would get you the ES5 APIs like `Math`, `JSON` but not any DOM declarations. similarly `--lib es2015` gets you ES6/ES2015 APIs like `Promise` and `Proxy`. see https://github.com/Microsoft/TypeScript/wiki/What%27s-new-in-TypeScript#including-built-in-type-declarations-with---lib for more details.
