### ISSUE TITLE
Use lowercase module name when looking up `@types` packages

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript#9824]
New NPM packages can not have uppercase letters in their names. the original package has been shipped already. May be we can make the package lookup in the compiler always look for the lower case name of the type package..

See https://github.com/DefinitelyTyped/DefinitelyTyped/issues/9716#issuecomment-233519331

**Comment by andy-ms** [comment]
It appears to already work this way, even with `--forceConsistentCasingInFileNames`.

My setup:

`src/tsconfig.json`:

    {
      "compilerOptions": {
        "forceConsistentCasingInFileNames": true,
        "outDir": "../out"
      }
    }

`node_modules/@types/foo/index.d.ts`:

    declare const x: number;
    export default x;

`node_modules/@types/bar/index.d.ts`:

    declare namespace Bar {
        const x: number;
    }

`src/index.ts`:

    import foo from 'FoO';
    foo + 1;

`src/foo-user.ts`:
    
    import foo from 'FoO';
    foo + 1;

`src/bar-user.ts`:

    /// <reference types='BaR'/>
    Bar.x;

`src/CAPS.ts`:

    export default 0;

`src/caps-user.ts`:

    // This one really does fail.
    import c from 'caps';
    c + 1;

There's still a chance that this won't work on a real case-insensitive OS.

**Comment by DanielRosenwasser** [comment]
The thing that flag does is yell at you if you use uppercase in one place and lowercase in another, so it's unrelated to this AFAIK.

**Comment by andy-ms** [comment]
My bad. I guess I'll have to test this out on my linux box.
