### ISSUE TITLE
2.0.0: Array destructure on promise callback not compiles correctly

### ISSUE THREAD

**Issue by unional** [Microsoft/TypeScript#9828]
**TypeScript Version:**  2.0.0

**Code**

I cannot create a stand-alone code that show case the problem.
You can try it out here:
https://github.com/unional/jspm-config/blob/array-spread/src/readProjectConfig.ts#L18

When you compile it (`npm run build`), you will see the resulting JS code as follow:

```js
// dist/readProjectConfig.js
// ...
const Promise = require('any-promise');
// ...
function readProjectConfig(options) {
    return readJspmPackageJson(options)
        .then((jspmPackageJson) => {
        return Promise.all([
            readJspmConfigs(jspmPackageJson.directories.baseURL, jspmPackageJson.configFiles, options),
            readDependenciesJson(jspmPackageJson.directories.packages, options)
        ])
            .then(([jspmConfigs, dependenciesJson]) => {  // <----- here
            return {
                jspmPackageJson,
                jspmConfigs,
                dependenciesJson
            };
        });
    });
}
```

When I create a stand-alone code, it compiles correctly:

```ts
import Promise = require('any-promise');

Promise.all([
  'abc', 'def'
]).then(([a, b]) => {
  return a + b;
});
```

compiles to:

```js
"use strict";
var Promise = require('any-promise');
Promise.all([
    'abc', 'def'
]).then(function (_a) {
    var a = _a[0], b = _a[1];
    return a + b;
});
```

**Comment by mhegazy** [comment]
@yuit can you take a look?

**Comment by unional** [comment]
Thanks. @yuit , The `array-spread` branch is created just to show case this problem. So remember to checkout that branch when you are testing instead of using `master`. 🌷

**Comment by httpdigest** [comment]
I experience the same problem using async/await. The following node program has a typecheck error although it behaves correctly when executed:
```Typescript
import * as request from 'request-promise';
async function test(): Promise<void> {
  try {
    const resp = await Promise.all([request.get('http://github.com')]);
    console.log(resp[0].length);
  } catch (err) {
    console.log(err);
  }
}
test();
```
The error is on the `resp[0].length`. Even though at runtime `resp[0]` is a string (containing the response body) the typechecker thinks it is a `RequestPromise` (from request-promise) which has no length property.
It seems to be irrelevant whether array destructuring is used or not. The following program has the same type error:
```Typescript
import * as request from 'request-promise';
async function test(): Promise<void> {
  try {
    const [resp] = await Promise.all([request.get('http://github.com')]);
    console.log(resp.length);
  } catch (err) {
    console.log(err);
  }
}
test();
```
I have another program that uses RxJS toPromise() methods and the return type of an `await Promise.all()` is reported as `Promise<Promise<any>>` whereas I expected it to be `Promise<any>`.

Strangely, when I use an empty array as argument to `Promise.all()`, then the type of `await Promise.all([])` is correctly inferred to `any`.

Requirements to run the above program:
```
npm install request request-promise --save
typings install dt~request dt~request-promise dt~node dt~form-data --save --global
```

**Comment by mhegazy** [comment]
@httpdigest the promise.all issue is the issue described in https://github.com/Microsoft/TypeScript/issues/7566. this should be fixed in TypeScript@2.0.0, and do not think it is related to the issue in the OP.

**Comment by httpdigest** [comment]
Thanks a lot for the link to the actual issue I was referring to! I will remove my comment now.

**Comment by mhegazy** [comment]
thanks. no need to remove the comment, unless you want to.

**Comment by yuit** [comment]
@unional I am starting to investigating the issue. I have check out your repo/branch and I notice the `tsconfig.build.json` uses by `npm run build` is targeting "es2015". Array-destructuring is es2015 features so it won't be down level; when I compile your small sample through `npm run buld` they both produce same result
```javascript
import Promise = require('any-promise');

Promise.all([
  'abc', 'def'
]).then(([a, b]) => { // here
  return a + b;
});
```

However, when I change the target to "es5" then both are down level
```javascript
function readProjectConfig(options) {
    return readJspmPackageJson(options)
        .then(function (jspmPackageJson) {
        return Promise.all([
            readJspmConfigs(jspmPackageJson.directories.baseURL, jspmPackageJson.configFiles, options),
            readDependenciesJson(jspmPackageJson.directories.packages, options)
        ])
            .then(function (_a) {
            var jspmConfigs = _a[0], dependenciesJson = _a[1];
            return {
                jspmPackageJson: jspmPackageJson,
                jspmConfigs: jspmConfigs,
                dependenciesJson: dependenciesJson
            };
        });
    });
}
```
Let me know if you still have an issue

**Comment by unional** [comment]
Thanks! I probably need to further down compile to es5 using babel.

That explain why I couldn't re-po it in the first place. 🌷

**Comment by yuit** [comment]
@unional no problem. Would targeting "es5" in tsconfig.json not solved your problem ? Just wonder as you mention you would have to use babel to compile to es5.

**Comment by unional** [comment]
It wouldn't work in this case because `ava/index.d.ts` relies on some es2015 feature (e.g. `Iterator`)

**Comment by yuit** [comment]
@unional If I understand your situation correctly, you want to use `es6` library while targeting `es5`. If that is the case we have a new compiler flag call `lib` [here](https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Compiler%20Options.md) for more details.

essentially your tsconfig.json will look something like.
```
... // other options
"lib": ["es2015", "dom", "webworker", "scripthost"] 
```

Note: you can drop `"dom", "webworker", "scripthost"` if you are targeting node environment. I just include them here as this configuration will be exactly the same ad default library files when targeting `es6`
let me know if you misunderstand anything or not be clear anywhere

**Comment by unional** [comment]
Excellent! Thanks a lot in following through this. Learn something new and very useful! 

Cheers. 🍻
