### ISSUE TITLE
Get file path of a extended class in TypeScript (amd/requireJs)

### ISSUE THREAD

**Issue by vanuatu** [Microsoft/TypeScript#9833]
**TypeScript Version:**  1.8.10

I have two classes in my TypeScript project (ClassA and ClassB), ClassB extends ClassA and I want to get the file path of ClassA, but I'm getting the path of ClassB, see my code below:

/my/folder/ClassA.ts;
```ts
    export class ClassA{
        
    }
```

/my/folder/sub/ClassB.ts
```ts
    import { ClassA } from "../ClassA";

    export class ClassB extends ClassA{
        constructor(){
            console.log(document._currentScript.src);
        }
    }
```
/my/main.ts
```ts
    import { ClassB } from "./my/folder/sub/ClassB";

    new ClassB();
```
I expected output: "/my/folder/sub/ClassB.ts", but I'm getting "/my/folder/ClassA.ts"

I'm using AMD with requirejs in this project.

Anyone can help me?

**Comment by mhegazy** [comment]
I am not sure i understand the issue. what is the expected output? and what do you get instead?

**Comment by vanuatu** [comment]
I would like to receive "http://127.0.0.1:8080/my/folder/sub/ClassB.js",
but instead I'm getting  "http://127.0.0.1:8080/my/folder/sub/ClassA.js"

**Comment by mhegazy** [comment]
what do you mean "receive"?

please note that TS is not a module loader. at runtime your module loader is the one doing the actual loading of files.

**Comment by vanuatu** [comment]
the problem really was not in the typescript, I decided changing the way that RequireJS imports the JS files.

Thank you for your help!
