### ISSUE TITLE
Loading custom Language Service from VS Code

### ISSUE THREAD

**Issue by winding-lines** [Microsoft/TypeScript#9834]
**TypeScript Version:**  beta (2.0.0)

**Code**

I have a custom resolver that I successfully use to build a typescript-enabled ember application. 
https://github.com/winding-lines/broccoli-typify/blob/master/src/broccoli-typescript.ts#L306

The broccoli plugin that I use implements a LanguageServiceHost with the following resolveModuleName(). This allows tsc to find type descriptions without having to use any triple slash annotations.

```ts
  resolveModuleNames(moduleNames: string[], containingFile: string): ts.ResolvedModule[] {
    return moduleNames.map(name => {
      // first try the default resolution
      let result = ts.resolveModuleName(name, containingFile, this.compilerOptions, { fileExists, readFile });
      if (result.resolvedModule) {
        return result.resolvedModule;
      }
      let candidatePaths: string[] = [];

      if (name === 'ember') {
        // custom repo for ember resolution while we stabilize the type definition
        candidatePaths.push(`${this.currentDirectory}/node_modules/at-types-ember/index.d.ts`);
      }
      if (name.match(/\/config\/environment$/)) {
        candidatePaths.push(`${this.localTypesFolder}/ember-config-environment.d.ts`);
      } else {
        // resolve npm: modules as loaded with ember-browserify.
        // the end goal is to have all the types coming from npm @types,
        // however we support a local-types for development.
        const module = (name.indexOf('npm:') === 0) ? name.split(':')[1] : name;
        candidatePaths.push(`${this.localTypesFolder}/${module}/index.d.ts`);
        candidatePaths.push(`${this.currentDirectory}/node_modules/@types/${module}/index.d.ts`);
      }
      for (let i = 0; i < candidatePaths.length; i++) {
        if (fs.existsSync(candidatePaths[i])) {
          return {
            resolvedFileName: candidatePaths[i],
            isExternalLibraryImport: true
          }
        }
      }
      return undefined;
    });

```

Everything works fine in the broccoli-based build pipeline. I am trying to take this integration to the next level and make it available to the IDE. Both VS Code and Intellij Idea allow a custom version of typescript to be configured. I see a couple of options:

1. write a wrapper to typescript which adds this custom resolver

2. move the local-types behaviour in Typescript itself, basically:
  1.1 look for types for module FOO under local-types/FOO in addition to node_modules/@types/FOO.
  1.2 allow for browserify type imports npm:FOO

3. allow Typescript to load plugins at run-time

**Expected behavior:**

VS Code uses the custom resolver.

**Actual behavior:** 

VS Code cannot locate the type definitions provided by the custom resolver.

**Comment by mhegazy** [comment]
VSCode loads a tsserver.js. you will have to produce a whole build of tsserver. the compiler (and the server) does not load extensions at the moment.

it also seems to me that most, if not all, these conditions can be coded as a [path mapping](https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Module%20Resolution.md#path-mapping) rules in your tsconfig.json.

**Comment by winding-lines** [comment]
Thanks for the fast reply. I need to load only d.ts files from the new locations. I was under the impression that path mappings are for the actual code as opposed to type files. Trying now.

**Comment by mhegazy** [comment]
not sure what you mean by code vs types. The whole module resoluton business is about finding the shape of a module looking at something like `import ember from "ember"`. 
```json
{
  "compilerOptions": {
    "paths": {
        "ember" : ["./node_modules/at-types-ember/index.d.ts"],
        "*/config/environment" : ["localTypes/ember-config-environment.d.ts"],
        "npm:*" : ["*", "localTypes/*/index.d.ts", "./node_modules/@types/*/index.d.ts"]
    }
  }
}
```

**Comment by winding-lines** [comment]
Yeah this approach is very promising, thanks for pointing me to it. I still have a couple of use cases to solve but setting baseUrl and the right paths mapping may work for my use case.

**Comment by winding-lines** [comment]
I was able to get this to work as desired, thanks a lot for your fast feedback!
