### ISSUE TITLE
Circular reference problem when using decorators in circular referenced classes 

### ISSUE THREAD

**Issue by pleerock** [Microsoft/TypeScript#9840]
I'm tired. I hate circular reference problems.
We have migrated a huge codebase to Typescript a few month ago, and now there is a problem that totally blocks us. I think this is a huge problem that prevent people to write a large scale apps.

**TypeScript Version:**  `@next`

**Code:**

I can't describe a problem clearly, its really better to see it. I created a basic project a with same models I have. They all are plain classes + one file that bootstrap the app + one empty decorator that brings a problem. I can't post a code here, to clearly show a problem you need to checkout repo and run the app. It is a real-world app.

1. git pull [git@github.com:pleerock/typescript-circual-reference-problem.git](https://github.com/pleerock/typescript-circual-reference-problem)
2. npm i
4. npm start

**Actual behavior:** 

Application is not running because of circular reference problem. It throws an error.

**Expected behavior:**

It should run without errors.

-------

How to fix this error:

* open ./src/modules/general/concept/entity/Concept.ts
* on line 68 change `attachedPhoto: AttachedPhoto` to `attachedPhoto: any`
* run app again and you'll not see error anymore

-------

If you remove a decorator - everything will work. I think the problem in emitted code:

```javascript
const AttachedPhoto_1 = require("../../../widget/attached-photo/entity/AttachedPhoto");

/// .......................................

__decorate([
    Decorated_1.Decorated(), 
    __metadata('design:type', AttachedPhoto_1.AttachedPhoto)
], Concept.prototype, "attachedPhoto", void 0);
```

And I even have no idea how to at least monkey patch it

**Comment by aluanhaddad** [comment]
Not that this is related to your problem, as changing it didn't resolve anything, but why is Decorated a decorator factory and not a decorator? Also, why are you using the same decorator, that has no behavior on class properties and on classes? Why apply the same decorator to multiple times to the same property (one of them had three Decorated annotations). Also, it looks like a lot of this code was generated by a template which has some odd notions.

**Comment by pleerock** [comment]
> Also, it looks like a lot of this code was generated by a template which has some odd notions.

no, this code is from a real project

> Why apply the same decorator to multiple times to the same property

Its because I have bulk changed all its different decorators to a single decorator, to simplify an example. But decorator can be applied multiple times without problems, right

>  Also, why are you using the same decorator, that has no behavior on class properties and on classes

Again, because its the simplest example of reproduction of the problem. I simply removed all behaviour because its unrelated to the problem

> why is Decorated a decorator factory and not a decorator?

I need decorator factory. [Here are a real decorators](https://github.com/pleerock/typeorm/tree/master/src/decorator/relations) I used

> Not that this is related to your problem, 

I don't think so, because I have a very simple project but with many relations and it simply should work without an issue. There is no my logic that breaks everything. Only references between objects.

> as changing it didn't resolve anything

what do you mean? If you change it the way I described and recompile the project - it should resolve the issue

**Comment by aluanhaddad** [comment]
> what do you mean? If you change it the way I described and recompile the project - it should resolve the issue

I mean that I changed the decorator factory to a decorator and removed multiple applications of the decorator and that did not help. I was just trying to understand the issue. 

Upon further reflection, I think it has to do with how node handles circular references https://nodejs.org/api/modules.html#modules_cycles

**Comment by pleerock** [comment]
> Upon further reflection, I think it has to do with how node handles circular references https://nodejs.org/api/modules.html#modules_cycles

Yes its most probably related to this issue, but I also think if in my situation everything is working as expected, then maybe typescript can emit/handle differently such situations

> I mean that I changed the decorator factory to a decorator and removed multiple applications of the decorator and that did not help. I was just trying to understand the issue.

Did you try to do what I described without changing everything else?: 

*  open ./src/modules/general/concept/entity/Concept.ts
*  on line 68 change attachedPhoto: AttachedPhoto to attachedPhoto: any
*  run app again and you'll not see error anymore

**Comment by aluanhaddad** [comment]
Yes I did, and it fails just as you describe under TypeScript 2.1.0-dev.20160723, Node 6.2.2. I do believe the issue is in the runtime. I'm not sure how TypeScript could resolve runtime issues like this without introducing other problems and making overly broad assumptions about current and future runtimes. It is also not a design goal of TypeScript to provide runtime support of any kind. Proper circular references are supported by module loaders such as SystemJS, so it may be worth investigating alternatives.

You may find this interesting https://github.com/ModuleLoader/es6-module-loader/blob/v0.17.0/docs/circular-references-bindings.md

**Comment by RyanCavanaugh** [comment]
We can't really look at repros with dozens of files. Please pare this down to a minimal example and we can figure out whether there's something we can do on our side vs in the codebase itself.

**Comment by pleerock** [comment]
@RyanCavanaugh its minimal example. There is NO logic in the codebase. Only dummy classes with dummy properties and decorated with dummy decorator set. That's it. It was a hard work for me to left only models and remove everything else. I tried to reproduce in small codebase (with only few models), but I could not reproduce it the same way. I tried to make installation process as minimal as possible.

**Comment by RyanCavanaugh** [comment]
Forgive the directness, but I'm extremely skeptical that whatever you're seeing can't be reproduced in three or four files. You're saying if you remove even one file from this repo, you know longer see the problem?

**Comment by pleerock** [comment]
after few days of experiments I have resolved my issue by manually settings the order in which files are being imported (now importing all abstract classes at last). But I still feel very uncomfortable with this issue. I'll reopen this if this issue again reproduce. Btw [here](https://blogs.msdn.microsoft.com/laurieatkinson/2016/04/27/file-order-matters-with-typescript-inheritance/) somebody describe very similar problem
