### ISSUE TITLE
Narrowing union types with array's indexOf

### ISSUE THREAD

**Issue by wallverb** [Microsoft/TypeScript#9842]
It would be great if TS could handle this:

```ts
                if (typeof reply == 'string') {

                }
                else if (~['input', 'button'].indexOf(reply.typeName)) {
                    const test = reply // Input or Button - currently everything
                }
```

**Comment by DanielRosenwasser** [comment]
There's a lot going on there that would need to be formalized. Specifically:

1. The expression of a property access becomes a literal type location.
2. An array literal becomes a literal type location if its parent is a literal type location.
3. `indexOf` would need to have a way of expressing that any value `>=` 0 implies that its type is related to its array's numeric index signature.

(1) and (2) are very easy to implement, but I think that (3) is too complex to express right now. While we have type predicate functions, we'd need a more powerful mechanism for expressing relationships between produced values and their arguments.
