### ISSUE TITLE
Allow quoted names in ambient contexts

### ISSUE THREAD

**Issue by RyanCavanaugh** [Microsoft/TypeScript#9846]
The node module `yargs` is callable (`typeof require('yargs') === 'function'`). It also has a property named `default` that is a function.

This makes writing a definition file very difficult. You'd be inclined to write
```ts
declare function yargs(): void;
declare namespace yargs {
  /* dozens of other things */
  function default(): void; // syntax error
}
export = yargs;
```
There's not an obvious workaround that doesn't have bad side effects (e.g. rewriting the whole mess as a `var` doesn't really work in the case where there's a nested class), possibly requiring a massive restructuring of the entire file.

Wherever an identifier appears in an *ambient* context where it could have been initialized as a property, it should be allowed to be quoted. For example
```ts
export const "default": string;
declare namespace foo {
  function "with"(): string;
}
```

**Comment by RyanCavanaugh** [comment]
This actually prevents some objects from being correctly represented. Consider if you had some object `foo` that was legal to use as
```ts
class d extends foo.var { }
let d = new foo.var();
let e = foo.default;
```

**Comment by RyanCavanaugh** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/17985/files#diff-ca41bc5f580b39365289711693a2ac6cR19

**Comment by BendingBender** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/18309/files#diff-c892b71507d5d1f0e96637ae3684df9eR60

**Comment by RyanCavanaugh** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/21749

**Comment by mhegazy** [comment]
Note that `export { x as y}` is legal in a `namespace` in an ambient context. so the issue in the OP can be written as:

```ts
declare function yargs(): void;
declare namespace yargs {
    function _default(): void; 
    export { _default as _default };
}
export = yargs;
```
