### ISSUE TITLE
Jsx format code bug

### ISSUE THREAD

**Issue by aeschli** [Microsoft/TypeScript#9856]
_From @thhoang99 on July 19, 2016 13:52_
- VSCode Version: 1.3.1
- OS Version: Windows 10

Steps to Reproduce:
1. in return of jsx file, put `<div>(or <h2>,<h3>,<a>, ...)"(enter)"</div>` anywhere.
   
   ex: 

```
<h3>"
     "</h3>
```
1. format code (alt + shift + f)
2. format code will stop working till reset vscode.

_Copied from original issue: Microsoft/vscode#9489_

**Comment by RyanCavanaugh** [comment]
@SaschaNaz any interest in taking a look?

**Comment by SaschaNaz** [comment]
Not really familiar with this type of issue, but definitely interested.

BTW, I'm also experiencing several formatter crash on TS 2.0 beta that I haven't make a minimal repro yet...

**Comment by SaschaNaz** [comment]
This seems fixed now.
