### ISSUE TITLE
JSX formatter removes space between sentences in component plain text content.

### ISSUE THREAD

**Issue by aeschli** [Microsoft/TypeScript#9857]
_From @joseph-iussa on July 19, 2016 13:37_

- VSCode Version: Code 1.3.1 (e6b4afa53e9c0f54edef1673de9001e9f0f547ae, 2016-07-12T13:35:06.227Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:

1. Open a new file and save it somewhere as test.jsx.
2. Add the following content to the file: `<div>Sentence one. Sentence two. Sentence three.</div>`
3. Format the file.
4. The file will be altered to: `<div>Sentence one.Sentence two.Sentence three.</div>`

This also happens with question marks and exclamation points at the end of sentences.

_Copied from original issue: Microsoft/vscode#9486_

**Comment by RyanCavanaugh** [comment]
The TypeScript formatter doesn't do this (or at least doesn't anymore). Maybe there's another formatter in play?

**Comment by dbaeumer** [comment]
@RyanCavanaugh I was able to reproduce this with a 1.8.10 tsserver. Is this fixed in 2.0?
