### ISSUE TITLE
Formalize AtScript-TypeScript alignment

### ISSUE THREAD

**Issue by JeroMiya** [Microsoft/TypeScript#986]
It seems like teams from MS and Google are keen on keeping alignment and syntax compatibility between AtScript and TypeScript. Right now AtScript is billed as a superset of the TypeScript syntax, adding an optional runtime type system and annotations/metadata capabilities. This was always something I thought should have been on the TypeScript roadmap even before AtScript was announced.

Let's take this rare opportunity and more formally align the two projects on at least a language spec level. Let's fold in Google's extensions to the TypeScript syntax into a draft language specification proposal that the two teams can agree on, and add the implementation of those extensions in the TypeScript compiler to the official roadmap.

If Google is serious about its long term plans to propose AtScript/TypeScript language extensions to the ECMAScript standards body, then it would greatly benefit both teams to stay in close alignment from an early stage.

**Comment by RyanCavanaugh** [comment]
AtScript now *is* TypeScript :smile:

![image](https://cloud.githubusercontent.com/assets/6685088/6509357/a928468a-c313-11e4-992d-5571618eb137.png)

**Comment by johnnyreilly** [comment]
Wow!

**Comment by JeroMiya** [comment]
*does a happy dance* Awesome job on the collaboration front guys! Good news for all involved!

**Comment by DickvdBrink** [comment]
This sounds really good! Good job team!

**Comment by Dignifiedquire** [comment]
Great news!

![66b](https://cloud.githubusercontent.com/assets/790842/6510360/df14f958-c365-11e4-8467-ac594033e43f.jpg)

**Comment by derekcicerone** [comment]
So awesome!

**Comment by NoelAbrahams** [comment]
> New TypeScript has all the features that Angluar needs

@RyanCavanaugh, are you able to clarify?

(thumbs up, of course)

**Comment by RyanCavanaugh** [comment]
The big thing was the @-style annotations.

**Comment by basarat** [comment]
Great job with the secrecy. On both teams part. Couldn't have been easy ❤️ this is great news

**Comment by vvakame** [comment]
:+1:
