### ISSUE TITLE
--noUnusedParameters does not work good enough

### ISSUE THREAD

**Issue by KnisterPeter** [Microsoft/TypeScript#9860]
**TypeScript Version:**  2.0.0

**Code**

```ts
function fn(p1: any, p2: any): void {
  return p2;
}
```

**Expected behavior:**
This should compile even with --noUnusedParameters

**Actual behavior:** 
Fails when p1 is unused.

Since this is method signature and callside may not be possible to fix this, the compiler should only flag unused from the end.

**Comment by mhegazy** [comment]
Change the name of p1 to start with _. Parameters with underscores are exempt from error reporting.

**Comment by KnisterPeter** [comment]
Interesting hidden feature. :laughing: 
Did you mean with 'working as intended' that this is not subject to change and this is not a bug?
Then I would say 'noUnusedParameters' is unusable, because developers need to know the hidden '_' prefix feature. This does not lead to clean and readable code (IMHO).

**Comment by yortus** [comment]
This is a duplicate of #9458

**Comment by mhegazy** [comment]
>Interesting hidden feature

Please see documentation at https://github.com/Microsoft/TypeScript/wiki/What%27s-new-in-TypeScript#flag-unused-declarations-with---nounusedparameters-and---nounusedlocals
