### ISSUE TITLE
Type guard failures with negative condition

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#9861]
**TypeScript Version:**  2.0.0

**Code**

```ts
class A<T> {
  private _: T;
}
class B<T> {
  private _: T;
}
function f() {
  var o: A<void> | B<void> = new B<void>();
  if (!(o instanceof B)) return o; // B<void>, should be A<void>
  o; // B<any>, should be B<boid>
}
```

**Expected behavior:**

A type of `o` narrowed by type guard inside if statement is `A<void>`.
A type of `o` narrowed by type guard after if statement is `B<void>`.

**Actual behavior:** 

A type of `o` narrowed by type guard inside if statement is `A<void>`.
A type of `o` narrowed by type guard after if statement is `B<any>`.

**Comment by yortus** [comment]
I think the 'problem' here is that you assigned a `new B<void>` instance in the declaration of `o`. TypeScript has accordingly narrowed `o` to `B<void>` for the rest of the function body.

To see the behaviour you are expecting, you can add an `<any>` cast to prevent the initial narrowing:

```ts
class A<T> {
  private _: T;
}
class B<T> {
  private _: T;
}
function f() {
  var o: A<void> | B<void> = <any> new B<void>();            // <=====
  if (!(o instanceof B)) return o; // A<void>, should be A<void>
  o; // B<void>, should be B<boid>
}}
```

**Comment by mhegazy** [comment]
@falsandtru i would appreciate it if you can limit the discussion to https://github.com/Microsoft/TypeScript/issues/9859 and avoid creating much noise.

**Comment by mhegazy** [comment]
This is the same topic discussed in https://github.com/Microsoft/TypeScript/issues/9859. closing in favor of https://github.com/Microsoft/TypeScript/issues/9859
