### ISSUE TITLE
Class decorator incorrectly runs after class constructor in a static context

### ISSUE THREAD

**Issue by KeithWoods** [microsoft/TypeScript#9868]
**TypeScript Version:**   1.8.10  

**Code**

``` ts
function myClassDecorators(constructor: Function) {
    console.log('decorator running');
}


@myClassDecorators
class Foo {

    constructor() {
         console.log('ctor running');
    }

    static MyFoo = new Foo();
}
```

**Expected behavior:**
console should log this:

```
decorator running
ctor running
```

**Actual behavior:** 
Console logs 

```
ctor running
decorator running
```

It appears that when a class instantiates an instance of itself in a static context the class constructor runs before any decorator declared on the class. The decorator should run first to allow any custom configuration of the class/type.

[run it on the playground](https://www.typescriptlang.org/play/index.html#src=function%20myClassDecorators%28constructor%3A%20Function%29%20%7B%0D%0A%20%20%20%20console.log%28'decorator%20running'%29%3B%0D%0A%7D%0D%0A%0D%0A%0D%0A%40myClassDecorators%0D%0Aclass%20Foo%20%7B%0D%0A%20%20%20%20%0D%0A%20%20%20%20constructor%28%29%20%7B%0D%0A%20%20%20%20%20%20%20%20%20console.log%28'ctor%20running'%29%3B%0D%0A%20%20%20%20%7D%0D%0A%09%0D%0A%09static%20MyFoo%20%3D%20new%20Foo%28%29%3B%0D%0A%7D%0D%0A%0D%0A%2F%2F%20running%20this%20produces%20this%20output%20%28which%20looks%20incorrectly%20ordered%2C%20decorator%20should%20run%20first%29%3A%0D%0A%2F%2F%20ctor%20running%0D%0A%2F%2F%20decorator%20running)

**Comment by RyanCavanaugh** [comment]
@rbuckton comments?

**Comment by rbuckton** [comment]
This is a known issue with the current implementation of decorators and is unlikely to change until the official decorators proposal is closer to standardization.

**Comment by RyanCavanaugh** [comment]
This would be a pretty invasive break to incur now, so I think we're sticking with the current behavior until the new decorators proposal makes progress.
