### ISSUE TITLE
Mutually exclusive guard constraints and 'never'

### ISSUE THREAD

**Issue by zhuravlikjb** [Microsoft/TypeScript#9869]
Applying two mutually exclusive guard constraints doesn't lead to 'never' type in the following case:
```ts
function ololo() {
    let stringOrNumber: string | number = 3 > 5 ? "a" : 7;

    if (typeof stringOrNumber === "number") {
        if (typeof stringOrNumber !== "number") {
            stringOrNumber; // shouldn't this be 'never'?
        }
    } 
```

Seems that it should.

**Comment by yahiko00** [comment]
Intellisense (TS 2.0.0) tells the innermost `stringOrNumber` is a `string`.

**Comment by kitsonk** [comment]
I mean you could argue that, but at the same time when the code is illogical and unreachable at run-time, why would you expect the control flow to work?  What benefit would there be in coding for that?

**Comment by ahejlsberg** [comment]
This is working as intended as per #8548. There are a number of subtle issues interacting here and we haven't come up with a better place to land yet.
