### ISSUE TITLE
Typinging missing for WebCrypto API generateKey function

### ISSUE THREAD

**Issue by jo-wil** [Microsoft/TypeScript#9872]
**TypeScript Version:**  2.00 beta

I tried this with no typings added as most of the WebCryptoAPI seemed to be fine by default and that being the case I would like to see this work by default as well.

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
 const key =  await crypto.generateKey({
   name: 'ECDH',
   namedCurve: 'P-256'
}, true, ['deriveBits']);
```

**Expected behavior:**

This should compile cleanly. It appears from the error message that there is no ECDHKeyGenParams type. The spec for this can be found here https://www.w3.org/TR/WebCryptoAPI/#ecdh.

A super basic type could be 
```ts
interace ECDHKeyGenParams {
   name: string,
   namedCurve: string
   // ... other types that I don't know about
} 
```
as this type seems to be for the algo section passed into generateKey

**Actual behavior:** 

src/jwcl.ts(166,16): error TS2345: Argument of type '{ name: string; namedCurve: string; }' is not assignable to parameter of type 'AesKeyGenParams | HmacKeyGenParams | Pbkdf2Params'.
  Object literal may only specify known properties, and 'namedCurve' does not exist in type 'AesKeyGenParams | HmacKeyGenParams | Pbkdf2Params'.

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.

**Comment by jo-wil** [comment]
Awesome thank you, will submit a PR.

**Comment by mhegazy** [comment]
let's keep this issue open to track the change.

**Comment by Fluf22** [comment]
I support this PR. I encountered the same problem with the ECDSA algorithm today.

**Comment by YuichiNukiyama** [comment]
[changed EcKeyGenParams from typedCurve to namedCurve to fix issue #135](https://github.com/Microsoft/TSJS-lib-generator/pull/135)

**Comment by jo-wil** [comment]
Since this pull request was accepted https://github.com/Microsoft/TSJS-lib-generator/pull/135 I think we can close this issue.

**Comment by vladikoff** [comment]
Somehow this issue is still within the ECDH deriveKey: 

![image](https://cloud.githubusercontent.com/assets/128755/26660666/7069d110-4647-11e7-9610-d370dae60efd.png)

What's a workaround to force it to ignore it?

**Comment by jo-wil** [comment]
@vladikoff that error message seems strange as the pull request I filled fixed this issue for me. What version of Typescript are you using and could you post the code snippet of how you are calling deriveKey as well as your tsconfig options?

**Comment by vladikoff** [comment]
`"typescript": "2.3.3"`

code: 

```js

  return window.crypto.subtle.deriveKey(
    {
      name: "ECDH",
      namedCurve: "P-256",
      public: APP_PUBLIC_KEY, 
    },
    RELIER_PRIVATE_KEY, 
    { 
      name: "AES-GCM", 
      length: 256, 
    },
    true,
    ["encrypt", "decrypt"] 
  )
```

**Comment by jo-wil** [comment]
You don't need namedCurve in the options for deriveKey. It already knows the curve used because you are passing in the CryptoKey instance. The function I was using in the original instance was generateKey, a subtle but important difference. 

You can find the types here for reference. https://github.com/Microsoft/TypeScript/blob/master/src/lib/dom.generated.d.ts

**Comment by vladikoff** [comment]
@jo-wil oh good to know, seems like a bug in https://github.com/diafygi/webcrypto-examples/#ecdh---derivekey I should PR a fix 👍
