### ISSUE TITLE
No comment preservation for parenthesized expressions

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#9873]
@evmar ran into issues where generating a JSDoc comment for a type assertion for Closure did not get preserved.

Neither

``` ts
var x = (/** @type {Foo.Bar} */ y);
```

nor

``` ts
var x = /** @type {Foo.Bar} */ (y);
```

have their comments preserved, though I'm not sure which is more common.

**Comment by weswigham** [comment]
@DanielRosenwasser
```ts
var x = /** @type {Foo.Bar} */y;
```
is also unpreserved. It's no unique to parenthesized expressions.

**Comment by mprobst** [comment]
Also happens for dotted expressions:

```ts
let x = /** @type {string} */ foo.bar;
```

**Comment by olemartinorg** [comment]
Not sure if related, but it also happens for regular comments when they appear before a }:

```Typescript
// Comment
let a = 5;
// Another comment
if (a === 5) { 
    alert('hello world');
    // Third comment
}
```
Compiles to:
```Javascript
// Comment
var a = 5;
// Another comment
if (a === 5) {
    alert('hello world');
}
```
