### ISSUE TITLE
Assigning values from tuple.

### ISSUE THREAD

**Issue by yulianovdey** [Microsoft/TypeScript#9874]
**TypeScript Version:**  1.8.10

**Code**

[playground link](https://www.typescriptlang.org/play/#src=const%20someTuple%3A%20%5Bstring%2C%20number%5D%20%3D%20%5B'someString'%2C%201%5D%3B%0D%0A%0D%0Aconst%20first%3A%20string%20%3D%20someTuple.shift()%3B%0D%0A)

```ts
const someTuple: [string, number] = ['someString', 1];

const first: string = someTuple.shift();
```

**Expected behavior:**

TypeScript lets me assign the result of `shift()` to `first: string`, or assign the result of `pop()` to `first: number`.

**Actual behavior:** 

> error TS2322: Type 'string | number' is not assignable to type 'string'.

If I hint first as `any`, or access someTuple[0], both of those work.

**Comment by yulianovdey** [comment]
I guess the problem is I'm not supposed to be modifying my "immutable" tuple ;).

**Comment by DanielRosenwasser** [comment]
The type system doesn't have a way to track the relationship between the first numeric property of a tuple and the behavior of `shift` (especially when `shift` changes the contents of the containing array), and I don't think doing so is very realistic.

**Comment by yulianovdey** [comment]
@DanielRosenwasser understood, thanks. What about making `slice` work, since it copies and you could infer types based on each resulting index?
