### ISSUE TITLE
different type between the type declared in jsDoc and the actual type

### ISSUE THREAD

**Issue by plantain-00** [Microsoft/TypeScript#9882]
**TypeScript Version:**  2.0.0 beta

**Code**

```ts
/**
 * @type {{ [name: string]: string; }} variables
 */
const variables = {};
```

**Expected behavior:**
from VSCode(hover the variable), the type of the `variables` is `{ [name: string]: string; }`
**Actual behavior:** 
from VSCode(hover the variable), the type of the `variables` is `{}[]`

Seems the feature is powered bu salsa from typescript, so commit this here.

**Comment by mhegazy** [comment]
the issue is the index signature is not really part of the JSDoc schema. so it is not really expected here. probaly the correct syntax, which is not supported either, is `{Object.<string, number>}` as per http://usejsdoc.org/tags-type.html
