### ISSUE TITLE
Error when is named a variable

### ISSUE THREAD

**Issue by andru255** [Microsoft/TypeScript#9887]
**TypeScript Version:**  1.8.0 / nightly (2.0.0-dev.201xxxxx)

**Code**

```ts

`let name: string = "hi!";` 

```

**Expected behavior:**

`var name = "hi!";` 

**Actual behavior:** 
I have an error when declare a variable with name `name`,
When compile with gulpjs shows me:

`error TS2451: Cannot redeclare block-scoped variable 'name'.`

`__lib.d.ts(16757,13): error TS2451: Cannot redeclare block-scoped variable 'name'.`

It's a single file, but how work's the reserved word "name"?

**Comment by DanielRosenwasser** [comment]
[`name` is actually a global in browser environments](https://developer.mozilla.org/en-US/docs/Web/API/Window/name), and re-declaration of `name` is a continuous source of problems for users.

If you're not in a browser environment, TypeScript 2.0 will support the `--lib` flag where you can select portions of what you want in your standard declarations.

**Comment by andru255** [comment]
@DanielRosenwasser thanks a lot! for the guides and explanation.
