### ISSUE TITLE
Visual Studio 2015 - Update 3 - .ts files not compiling with tsconfig.json present

### ISSUE THREAD

**Issue by PEsteves8** [Microsoft/TypeScript#9892]
**TypeScript Version:**  1.8.35

For some reason, the .ts files aren't being compiled to .js on save using Visual Studio Professional 2015 Update 3

If I remove the tsconfig.json file (or rename it) the compilation runs properly.

Here's my tsconfig.json:

``` 
{
  "compilerOptions": {
    "target": "es5",
    "module": "system",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": true
  },
  "compileOnSave": true,
  "exclude": [
    "node_modules",
    "typings/main",
    "typings/main.d.ts",
    "wwwroot"
  ]
}
```

If the file is present in the root folder, when I save a .ts file, nothing happens. No error. It just doesn't compile.

The automatically compile TypeScript files that are not part of a project is unchecked.

**Comment by PEsteves8** [comment]
Described here as well: https://github.com/Microsoft/TypeScript/issues/5995

**Comment by yuit** [comment]
I have tried your `tsconfig.json` then added a ts file into the same folder as `tsconfig.json` and the file seems to be compiled just file. I am currently used TypeScript 2.0.0 Beta on Update3, could you give 2.0.0 Beta a try?

**Comment by PEsteves8** [comment]
Thanks for the response. I tried installing TypeScript 2.0.0 Beta. It shows up in the VS about windows as expected, but the behavior seems to be the same. VS Code, works but slowly and Atom with the Typescript plugin works without any problem.

**Comment by mhegazy** [comment]
can you share a project that exhibits the issue?

**Comment by PEsteves8** [comment]
I'm using .NET Core 1.0, but I tried following this tutorial, using .NET 4.x: https://www.typescriptlang.org/docs/handbook/asp-net-4.html

It only compiles .ts if I build. Before I algo did try follow the tutorial for Typescript tutorial for .NET Core, adapting from RC1 to 1.0. Neither work as expected, since it shouldn't really matter which version of .NET Core is being used as long as there are typescript files and a tsconfig.json. Anyway, those are two projects where it didn't work.

**Comment by mhegazy** [comment]
Can you share the project?

**Comment by PEsteves8** [comment]
It's the most basic project possible. Everything works fine with VS Code and Atom with the typescript plugin. It's specifically VS2015. I tried repairing it with no luck. Is there anyway to delete some Typescript cache definitions or something that may reset the integration between VS2015 and typescript?

**Comment by PEsteves8** [comment]
By the way, it also seems to be ignoring the tsconfig.json options, since it complains gives the "experimental support for decorators is a feature..." message. If I switch it to false, the message shows up in VS Code, otherwise it doesn't. 

I'm also getting 90000 errors from lib.d.ts and all the modules from @angular and rxjs are said to be "not found". Again, only in VS2015.

After a suggestion here, I installed Typescript 2.0beta, which didn't help. In the about page that's the only version that shows up and I'm unable to install it, although I supposedly uninstalled it by running it's installer.

After uninstalling VS2015 and installing it again, everything stayed the same, including the "2.0" Typescript version in the about window.

**Comment by PEsteves8** [comment]
Anyway after multiple reinstalls and repairs and deleting chache and temp folders and registry entries and more repairs and some more random stuff, I once again installed Typescript 2.0 beta (which did nothing) and then repaired it aaaaaand now it works.

So for anyone with the same problem, just follow those steps :P

**Comment by dudih** [comment]
I had the same problem.
Solved it by checking version:
\>tsc -v

make sure the value is > 1.7.

If not, update it using this tutorial:
http://stackoverflow.com/questions/31750964/typescript-compile-on-save-feature-not-working-in-visual-studio-2015/35258446#35258446

**Comment by vaibahv88sharma** [comment]
Hi,
I may be very late to answer but you can follow the steps mentioned in the following, it worked for me.

http://sharepointpals.com/post/Creating-a-SharePoint-App-with-TypeScript-and-Angular-Js-Step-by-Step

**Comment by amitkprajapati** [comment]
-typescript file option is not getting in **add new file option** in vs2105 of angularJs application , although all the dependencies have been installed.
-the typescript file option is getting other application type.
