### ISSUE TITLE
[Errors] incorrect array creation syntax

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript#99]
```TypeScript
new Foo[];!!! 'new T[]' cannot be used to create an array. Use 'new Array<T>()' instead. 
```

Expected: errors above

Actual: 

!!! Expression expected.!!! Cannot find name 'Foo'.!!! Cannot use 'new' with an expression whose type lacks a signature.

High priority error quality bug.

**Comment by DickvdBrink** [comment]
Looks fixed on master and playground.
Also, there is already a test for this. https://github.com/Microsoft/TypeScript/blob/master/tests/baselines/reference/badArraySyntax.errors.txt

**Comment by mhegazy** [comment]
thanks @DickvdBrink
