### ISSUE TITLE
Support for “export default from” and “export ns from” proposals

### ISSUE THREAD

**Issue by calebmer** [Microsoft/TypeScript#9906]
Is it on the TypeScript roadmap to support the [export default from](https://github.com/leebyron/ecmascript-export-default-from) and [export namespace from](https://github.com/leebyron/ecmascript-export-ns-from) proposals? This makes working with default exports much easier. Currently this needs to be done to export a bunch of defaults as named exports:

```js
import a from 'a'
import b from 'b'
import c from 'c'

export {
  a,
  b,
  c,
}
```

By implementing these proposals the above goes to:

```js
export a from 'a'
export b from 'b'
export c from 'c'
```

These proposals make import/export semantics symmetrical.

**Comment by mhegazy** [comment]
should be covered by the proposal in https://github.com/Microsoft/TypeScript/issues/4813
