### ISSUE TITLE
Path mapping should relative path ?

### ISSUE THREAD

**Issue by GreanMaster** [Microsoft/TypeScript#9910]
**TypeScript Version:** nightly (2.1.0-dev.20160722)

**Code**

```ts
// src/views/foo.ts
import foo from 'view/bar';

console.log('Hi ', foo);

```
```ts
// generated/templates/views/bar.ts
let foo = 'foo'

export default foo;

```
```json
// tsconfig.json
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
    	"view/*": ["generated/templates/views/*"]
    },
    "outDir": "dist"
  }
}
```

**Expected behavior:**
the `import foo from 'views/bar';` in `src/views/foo.ts` should generate 'var bar_1 = require('../../../view/bar');' because I've already define it with path mapping, It should relative path or not ?
**Actual behavior:** 
the `import foo from 'views/bar'; in `src/views/foo.ts`  generate 'var bar_1 = require('view/bar');`

if you don't understand my english you should try by yourself [ts-path-mapping](https://github.com/GreanMaster/ts-path-mapping)

Sorry for my bad eng, Thank you :)

**Comment by mhegazy** [comment]
Reposting my answer from https://github.com/Microsoft/TypeScript/issues/5039#issuecomment-232470330

The compiler does not rewrite module names. module names are considered resource identifiers, and are mapped to the output as they appear in the source

The module names you write are not going to change in the output. the "paths" and "baseURL" are there to tell the compiler where they are going to be at runtime.

**Comment by GreanMaster** [comment]
Thank you @mhegazy, I've understood :+1:

**Comment by papercuptech** [comment]
Appreciating TS's position, here's a simple solution to the 90% use case for those of us using node, but wanting the convenience of using `baseUrl` relative `require()` calls without any fuss.

This solution hooks node's `require()` call, and resolves requests using the dirname of "main" to mimic `baseUrl`. It therefore assumes the `baseUrl` compiler option was also set to the same directory where the source "main.ts" was located.

To use, paste this tiny chunk of code at the top of your "main.ts".

```typescript
import * as path from 'path'
import * as fs from 'fs'
const CH_PERIOD = 46
const baseUrl = path.dirname(process['mainModule'].filename)
const moduleProto = Object.getPrototypeOf(module)
const origRequire = moduleProto.require
moduleProto.require = function(request) {
  if(!path.isAbsolute(request)) {
    if(request.charCodeAt(0) !== CH_PERIOD) {
      const ext = path.extname(request)
      const hasJsExt = ext.length > 0 && ext.toLowerCase() === '.js'
      const basedRequest = path.join(baseUrl, hasJsExt ? request : request + '.js')
      if(fs.existsSync(basedRequest)) request = basedRequest
    }
  }
  return origRequire.call(this, request)
}
```
