### ISSUE TITLE
default value of `declarationDir` and `mapRoot`

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#9913]
https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Compiler%20Options.md
says that the default value of `declarationDir`  and `mapRoot` is `null`

** Should it be `undefined` instead? **

**Comment by mhegazy** [comment]
Fixed in https://github.com/Microsoft/TypeScript-Handbook/commit/d654783d0b7ef8ecf49d0f2f2bd20cd97490c0f7
