### ISSUE TITLE
Typing through interfaces is duck-typed rather than strict

### ISSUE THREAD

**Issue by Jameskmonger** [Microsoft/TypeScript#9915]
**TypeScript Version:**  1.8.7

**Code**

```ts
interface IModel {

    // this is a marker interface

}

interface IGenericRepository <TModel extends IModel> {

    getById(id: number): TModel;

}

class BrandModel {

    public id: number;
    public name: string;

}

class AnotherModel {

    public id: number;
    public name: string;

}

interface IBrandRepository extends IGenericRepository <BrandModel> {

    // the only property on this interface is:
    //     getById(id: number): BrandModel

    // inherited from IGenericRepository

}

class BrandRepository implements IBrandRepository {

    // this should return BrandModel because of IBrandRepository. But it doesn't have to
    public getById(id: number): AnotherModel {
        return undefined;
    }

}
```

**Expected behavior:**
A compilation error to be thrown, as getById returns AnotherModel not BrandModel.

**Actual behavior:** 
The program compiles.

**Comment by mhegazy** [comment]
The type system in typescript is structural, and not nominal. Please see some related explanation in:
https://github.com/Microsoft/TypeScript/wiki/FAQ#what-is-structural-typing And 
https://github.com/Microsoft/TypeScript/wiki/FAQ#why-is-astring-assignable-to-anumber-for-interface-at--

**Comment by basarat** [comment]
Having a great duck type experience is fundamental to providing a great JavaScript **upgrade to ->** TypeScript experience : https://basarat.gitbooks.io/typescript/content/docs/why-typescript.html
