### ISSUE TITLE
Cannot build TypeScript: "gulp local" hangs

### ISSUE THREAD

**Issue by kpreisser** [Microsoft/TypeScript#9918]
Hi,
since yesterday, I seem to not be able to build TypeScript on a Windows machine because "gulp local" hangs after printing "Requiring external module ts-node/register".

I just run the following steps on a clean Windows 10 x64 Version 1511 machine:
1) Install Git for Windows 2.9.2 (x64), TortoiseGit 2.2.0.0 (x64), Node.js v4.4.7 LTS (x64).
2) Clone `https://github.com/Microsoft/TypeScript.git`.
3) In the TypeScript directory, run `npm install -g gulp` and `npm install` as written in the readme.
4) In the TypeScript directory, run `gulp local`.

However,  the console window now looks like this since 10 mins, and there is no harddisk or network activity (however there is 100% usage for 1 CPU core):
![](https://cloud.githubusercontent.com/assets/13289184/17082867/e68d8b30-518c-11e6-9526-c77c048fd3a7.png)

Any idea what could be causing this?
Thanks!

**Comment by Artazor** [comment]
Exactly the same!

**Comment by Artazor** [comment]
Even `gulp clean` hangs with the same symptoms

**Comment by Artazor** [comment]
Looks that it is not a Windows specific problem - I'm on OSX 10.11.5

**Comment by Artazor** [comment]
Something strange happens, when loading tsconfig (which is absent for the TypeScript project itself, ts-node scans all the files in TypeScript/tests/baselines/reference/project and does it extremely slow. Investigating further.

**Comment by Artazor** [comment]
getFileMatcherPatterns produces extremely inefficient RegEx for includeFilePattern.
It hangs (actually take very long time) on long file names.
the culprit: 
```
/^((\/Users\/aar\/type\-type\/TypeScript(\/[^\/.][^\/]*)*?\/([^.\/]([^.\/]*(\.(?!min\.js$))?)*)?))$/.test(
"/Users/Artazor/repo/TypeScript/tests/baselines/reference/project/declarationsImportedUseInFunction/amd/useModule.d.ts")
``` 
Will investigate further and probably make a PR with fix

**Comment by mhegazy** [comment]
@weswigham can u take a look

**Comment by Artazor** [comment]
/^(((\/[^\/.][^\/]*)*?\/([^.\/]([^.\/]*(\.(?!min\.js$))?)*)?))$/  - has a catastrophic backtracking

**Comment by Artazor** [comment]
The problematic regexp is built right here: https://github.com/Microsoft/TypeScript/blob/8b2ea398ffc54f96018e40091d1827cb81d5ee39/src/compiler/core.ts#L944

**Comment by Artazor** [comment]
The problem was introduced (I suspect) by the commit https://github.com/Microsoft/TypeScript/commit/8325565f0ac8783895b0f1b5a16273526326ae4a

**Comment by Artazor** [comment]
the problem is not caught by tests because fileName values used in tests are too short. performance problems start to be observable starting from 130 characters (on my machine) and quickly grow with the length.

**Comment by Artazor** [comment]
All tests are passed

**Comment by Artazor** [comment]
```ts
 const singleAsteriskRegexFragmentFiles = "([^./]*(\\.(?!min\\.js$))?)*";   // BEFORE
 const singleAsteriskRegexFragmentFiles = "([^./]|(\\.(?!min\\.js$))?)*";    // AFTER
```
I've changed '*' to '|' because all the group is repeated as '*' and the (\\.(?!min\\.js$)) is optional.
It keeps the semantics.

**Comment by Artazor** [comment]
@mhegazy maybe it would be worth to create another issue, related to the unacceptable regexp in `core.ts` ?

**Comment by weswigham** [comment]
[This change](https://github.com/TypeStrong/ts-node/commit/84fcf198a4779aecb6d8efbdd29eb3efa91115b0) in `ts-node` (which reads our Gulpfile.ts and compiles it) is what triggered the exposure of this bug. (And so is also likely the cause of the following errors once the RegExp DOS issue is fixed)

**Comment by weswigham** [comment]
I've merged the RegExp DOS fix and opened an issue on `ts-node` about the behavioral change. While that is getting looked at, I've locked out `package.json` to version `1.1` of `ts-node`.
