### ISSUE TITLE
Awaiting a non-promise doesn't error

### ISSUE THREAD

**Issue by tinganho** [Microsoft/TypeScript#9921]
I'm kind of expecting this to throw an error:
```ts
async function test() {
    await []; // no error
}
```
I did a mistake of not using `Promise.all()`:
```ts
async function test() {
    let promises: Promise<any>[] = [];
    // ...
    await Promise.all(promises); // no error
}
```
And it would be helpful if TS could help me catch those mistakes.

**Comment by yortus** [comment]
I agree this is annoying as I've also occasionally put the wrong thing after `await` and didn't get any compiler errors.

Having said that, awaiting a non-promise is valid under the spec (although it comes under the heading 'debatable syntax'), and it has [well-defined semantics](https://github.com/tc39/ecmascript-asyncawait#awaiting-non-promise). It is actually convenient in some cases (eg awaiting a value of type `T|Promise<T>`).

I agree it's annoying but I would not wish something that's currently valid in the ECMA proposal, and that is useful at times, to become an error in TypeScript.

If someone could think up a 'best of both worlds' approach, I'd be all for that.

**Comment by yortus** [comment]
Also, this is a duplicate of #8310, and there's a lot more discussion there.

**Comment by tinganho** [comment]
Yes duplicate of #8310.
