### ISSUE TITLE
Go to definition from an argument structure

### ISSUE THREAD

**Issue by tinganho** [Microsoft/TypeScript#9922]
I was expecting go to def should work on arguments:

``` ts
interface A {
    a/*to here*/: string;
}
function test(p: A) { }
test({ a/*from here*/: ''});
```

**Comment by mhegazy** [comment]
This is not the definition; the defindion is where something is defined, and this an object literal, so it is a definition itself. This is the same as a class peppery, go to def does not take you to the interface. 

Find all references should get it for you though.

**Comment by tinganho** [comment]
Could the current goto-def be augmented to include this? Even though it technically is not a definition. I think people want this feature to help understand and debug code.

**Comment by RyanCavanaugh** [comment]
Odd that this doesn't work given that we would rename both instances of `a` here due to contextual typing. Seems like something we should do. Thoughts @mhegazy ?

**Comment by mhegazy** [comment]
Find all references finds definition, usage, and contextual types with same name. So rename works. The question is what is definition and what is not. Is an object literal a definition or is it a use site. I have always intrepreted it as a definition.

**Comment by RyanCavanaugh** [comment]
I think the *intent* of Go-to-Def at that location is pretty clear. Surely no one is invoking F12 at the property key just to go to the property key again.
