### ISSUE TITLE
Property 'MAX_SAFE_INTEGER' does not exist on type 'NumberConstructor'

### ISSUE THREAD

**Issue by hckr** [Microsoft/TypeScript#9937]
**TypeScript Version:**  1.8.10

**Code**

```ts
let smallestDistance = Number.MAX_SAFE_INTEGER;
```

**Expected behavior:** `smallestDistance` equals the biggest possible integer value.

**Actual behavior:** Compiler error:
> Property 'MAX_SAFE_INTEGER' does not exist on type 'NumberConstructor'

I discovered that there exists `Number.MAX_VALUE` but should not TS be backwards compatible with JS?

**Comment by RyanCavanaugh** [comment]
This should be in the ES6 lib

**Comment by YuichiNukiyama** [comment]
`Number.MAX_SAFE_INTEGER` had been implimented in **ts2.0.0 beta** (see [here](https://github.com/Microsoft/TypeScript/blob/master/src/lib/es2015.core.d.ts#L231)).
If you want to use this, upgrade ts version and set `"lib": ["es2015"]` for compilerOptions.
Or make .d.ts file, and write following code:

`
interface NumberConstructor {
    readonly MAX_SAFE_INTEGER: number;
}
`

**Comment by DanielRosenwasser** [comment]
Thanks for the heads up @YuichiNukiyama!

**Comment by NateMay** [comment]
Use `MAX_VALUE` or `POSITIVE_INFINITY` instead of `MAX_SAFE_INTEGER`

lib.es5.d.ts

```
interface NumberConstructor {
    new (value?: any): Number;
    (value?: any): number;
    readonly prototype: Number;
    readonly MAX_VALUE: number;
    readonly MIN_VALUE: number;
    readonly NaN: number;
    readonly NEGATIVE_INFINITY: number;
    readonly POSITIVE_INFINITY: number;
}
```
