### ISSUE TITLE
Undeclared variable allowed

### ISSUE THREAD

**Issue by asakusuma** [Microsoft/TypeScript#9938]
**TypeScript Version:**  1.8.10

**Code**
```JavaScript
this.name = name;
```
`name` was never declared. [entire file](https://github.com/asakusuma/ventana/tree/9346a621727b9434554a2e4bf1932326270e51b7/lib/streams/stream.ts#L8).

**Expected behavior:** Running `tsc` should fail

**Actual behavior:** Running `tsc` passes

I believe this is either a bug or I'm missing something in my `tsconfig`

**Comment by RyanCavanaugh** [comment]
`name` is a property of the `window` interface and is available at the global level. You could use the "Go to definition" feature of your editor to discover this.

**Comment by asakusuma** [comment]
Ah, thank you for the quick reply @RyanCavanaugh, closing.

**Comment by asakusuma** [comment]
@RyanCavanaugh do you happen to know of any linters that force explicitly doing `window.name` instead of `name`?

**Comment by RyanCavanaugh** [comment]
Looks like it's being discussed at https://github.com/palantir/tslint/issues/327
