### ISSUE TITLE
Compile on save in Visual Studio 2013 does not emit reference tags in declaration output when saving

### ISSUE THREAD

**Issue by jasonscharf** [Microsoft/TypeScript#994]
I'm using Visual Studio 2013 Update 3 with TypeScript 1.1 on Windows 8.1.

I have a solution with multiple projects that use declaration files to reference each other. A core project emits a declaration file, and a single JavaScript output. Each dependent project copies these into their own hierarchy. The core definition file references a number of other definition files.

When I do a rebuild, the output definition file contains the references at the top of the file. This is correct behaviour, in my case. However, when I save any of the files in the project, the declaration file is emitted again, but with no references at the top. Comments are still preserved in the declarations (and obey the setting for comment preservation), but references are gone. This breaks my entire project.

Replication is simple:
1) Create a new project in VS 2013 from the "**HTML Application with TypeScript**" template.
2) Using the **Project Properties** screen, ensure that "**Compile on save**" and "**Keep comments in JavaScript output**" are *enabled*, and define an output file.
3) Create a `test.d.ts` file with something valid in it.
4) Reference `test.d.ts` from your generated `app.ts`.
5) Make a change in `app.ts`.
6) Do a rebuild of the project.
7) Examine `app.d.ts`. It will contain the reference to `test.d.ts`
8) Save `app.ts` (even without modifying it).
9) Examine `app.d.ts`. The references are gone.
10) Do a rebuild and examine `app.d.ts`. The references are back.

A workaround for this is to disable **Compile on save** in projects that generate definition files that require reference emission.

**Comment by mhegazy** [comment]
I can not reproduce this any more. please reopen if still an issue.
