### ISSUE TITLE
process.exitCode doesn't work or exist in node.d.ts file

### ISSUE THREAD

**Issue by trixlerjs** [Microsoft/TypeScript#9940]
**TypeScript Version:**  nightly (2.0.0-dev.201xxxxx)

**Code** ,,,

```ts
process.exitCode doesn't work or exist in node.d.ts file

```

**Expected behavior:** process.exitCode should work

**Actual behavior:**  process.exitCode doesn't work

**Comment by RyanCavanaugh** [comment]
Please send a pull request to https://github.com/DefinitelyTyped/DefinitelyTyped
