### ISSUE TITLE
Suggestion: explicit type narrowing

### ISSUE THREAD

**Issue by saschanaz** [Microsoft/TypeScript#9946]
To fix #5930 and #6474:
### Syntax and use cases

``` ts
let anything: any;
if (isFoo(anything)) {
  declare anything: Foo;
  anything.foo // valid and type-checkable
}

interface Foo {
  foo: number;
}

function isFoo(something: any): something is Foo {
    return typeof something.foo === "number"; 
}
```

``` ts
let node: Node
if (node.nodeType === 1) {
   declare node: Element;
   node.addEventListener // valid
}
```

``` ts
// Added on August 2, 2016
// Dog|House case from #9999
function fn(x: any) {
  if (x instanceof Animal) {
    declare x: Dog; // User knows better than the type system, so let it go explicitly
    x.woof(); // type-checked
  } else {
    declare x: House;
    // handle House case
  }
}
```

``` ts
// Added on August 8, 2016
try {
  foo();
}
catch (err) {
  // when I'm absolutely sure that my error object will always be an instance of Error
  declare err: Error;
  console.error(err.messge) // compiler warns
}
```
### Behavior

``` ts
{
  declare anything: Foo;
  // `anything` is Foo in this block.
  // if type of `anything` is not narrow-able into Foo, it should be an error.
}
```
### Why not existing type guards?
1. `any` type cannot be narrowed by type guards. (#5930)
2. Defining a new super-small function only for a single or two uses is not always preferable. (#6474)
### Workaround

Declare a new variable. `var element = node as Element`

**Comment by vilic** [comment]
+1 for this feature. I was also thinking of another way to have "type assertion type" assertion work in `if` statement:

```ts
interface Yo {
    type: 'yo';
}

let foo: any;

if ((foo.type === 'yo') as foo is Yo) {
    // Now `foo` has type `Yo`.
}
```

**Comment by aleksey-bykov** [comment]
the example with `Node` to `Element` is exactly what type guards were designed for
```typescript
function isElement(node: Node): node is Element { return node.nodeType === 1; }
```
what is wrong with defining a super-small function for it?

i think that using `declare node: Element;` undermines:
- type-safety: `node.nodeType === 1` and `declared node: Element` not bound together and can easily go out of sync during refactoring
- the purpose of type guards

**Comment by SaschaNaz** [comment]
>type-safety: `node.nodeType === 1` and `declared node: Element` not bound together and can easily go out of sync during refactoring

I think the unboundedness can help sometimes with its flexibility. What about this:

```ts
// jQuery ajax
$.ajax({
  url: "http://example.com/foo.xml",
  dataType: "xml"
}).then(data => {
  // data is any
  declare data: XMLDocument; // I know better than the type system!
});
```

**Comment by aleksey-bykov** [comment]
first: narrowing from `any` is one of my favorite dreams to dream of, so i am with you on that

the `ajax` problem isn't a problem as long as you develop a contract between input and output:

```typescript
interface Request<Data> {
   url: string;
   dataType: string;
}

function fetchData<Data>(request: Request<Data>) : Promise<Data> {
   return $ajax(request);
}

const request: Request<XMLDocument> = {
   url: "http://example.com/foo.xml",
   dataType: "xml"
};

fetchData(request).then(xml => { /* xml is XMLDocument */ })

```

**Comment by yortus** [comment]
> I posted this suggestion because I had to catch an error and get error type.

@SaschaNaz see also #8677

> narrowing from `any` is one of my favorite dreams to dream of

@aleksey-bykov amen, same here. The compiler treats `any` annotations as meaning *"I don't* want *any type checking on this variable"*. But what I often wish to convey to the compiler is *"this variable could be anything at this point. I can't make assumptions until I narrow it"*, for which `any` also *seems* like the clearest and most readable annotation, but isn't right. I think `{}` works best in this case but I find it has unclear intent when I later re-read the code.

For me the best of both world would be that `any` still means *"don't type-check this"*, but if I explicitly put it through a type guard then I'm saying *"please do narrow this now since I'm explicitly asking you to"*. This is also more consistent with runtime semantics.

After all, an explicit type cast *does* work on `any`, so why not an explicit type guard?

But it's not going to happen because it's too much of a breaking change to make people change the annotation of `x` in the [following example](https://github.com/Microsoft/TypeScript/issues/5930#issuecomment-162135447) from `any` to `Dog|House`, which would make it work perfectly.

```ts
// By contract, this function accepts only a Dog or a House
function fn(x: any) {
  // For whatever reason, user is checking against a base class rather
  // than the most-specific class. Happens a lot with e.g. HTMLElement
  if (x instanceof Animal) {
    x.woof(); // Disallowed if x: Animal
  } else {
    // handle House case
  }
}
```

If TypeScript accepted a breaking change here with the advice to use a union type annotation rather than `any` in examples like this, I not sure if there would be any other objection to narrowing from `any`.

> we want type guards to allow you to do more, not less.

...then let them work with `any`

> `any` can already do everything

...except be narrowed even when explicitly requested

**Comment by SaschaNaz** [comment]
>so why not an explicit type guard?

Ryan has said in https://github.com/Microsoft/TypeScript/issues/5930#issuecomment-163817104:

>I'm serious about the number of breakages we found in real-world code. It was very large, and feedback from people trying early builds said they didn't want this.

...which seems reasonable to me.

**Comment by aleksey-bykov** [comment]
@yortus i've ranted a bit right past that example you mentioned, i have a strong opinion about the shady business that is going on there

**Comment by yortus** [comment]
@aleksey-bykov your rant is spot on. I'm pretty sure it's a conspiracy by those flow or babel people to hurt TypeScript's credibility...

**Comment by aleksey-bykov** [comment]
related #9999

**Comment by rozzzly** [comment]
I've always wanted something like 

```typescript
function foo(x: any) { 
  // type of x is `any`
  if (someCondition) { // doesn't matter what this is
    // type of x is still `any`
    x is number[];
    // now type of x is `number[]`
    x.push (7);
  }
  // type of x is `any`
}
```

**Comment by SaschaNaz** [comment]
```ts
function foo(x: any) { 
  // type of x is `any`
  if (someCondition): x is number[] { // doesn't matter what this is
    // now type of x is `number[]`
    x.push (7);
  }
  // type of x is `any`
}
```

Great, and I think this can be better for boundedness sake.

**Comment by rozzzly** [comment]
@SaschaNaz ooh that's nice too, definitely helps by defining the scope within which that type has been narrowed. But, I think adding it to an if could be somewhat restrictive because it has to be accompanied by an if. I can't think of any practical examples off the top of my head though :/

**Comment by SaschaNaz** [comment]
>oh and what about this...

That problem also occurs with type guard functions.

```ts
function isString(something: any): something is string {
  return true === false && _.isString(x)); // ???
}
```

**Comment by RyanCavanaugh** [comment]
Let's track this at #10421
