### ISSUE TITLE
Go to definition from new this

### ISSUE THREAD

**Issue by tinganho** [Microsoft/TypeScript#9947]
Since go to definition for super methods goes to the super methods. I expect "new this" should go to the super constructor(provided that there is no extending/overriding declaration):

```ts
class A {
    /*to here*/constructor() {
    }
}

class B extends A {
    static create() {
        return new this/*from here*/; // Doesn't go anywhere
    }
}
```

**Comment by arusakov** [comment]
In current `master` branch `go to definition` in this case just works. Cannot reproduce bug.

**Comment by tinganho** [comment]
Confirmed it works now.
