### ISSUE TITLE
Properties implemented in a class are not determined correctly

### ISSUE THREAD

**Issue by vascofernandes** [Microsoft/TypeScript#9952]
**TypeScript Version:**  1.8.10

**Code**

```ts
    interface IOptions {
        id: string;
    }
    export function test<T>(func: () => IOptions & T) {
        return {
            do() {
                let result = func();
            }
        };
    };


    interface A<T> {
        propA1: '1';
        propA2: C<T>
    }

    interface B {
        propB1: number;
    }

    interface C<T> {
        propC1: () => T;
    }

    let result = test<A<B>>(() => ({
        id: '123',
        propA1: '1',
        propA2: MyClass
    }));


    class MyClass implements C<B> {
        propC1: () => B;
    }
```

**Expected behavior:**
I expected that in `propA2: MyClass` it would be inferred that `MyClass` implments `C<B>`.

**Actual behavior:** 

Type '{ id: string; propA1: "1"; propA2: typeof MyClass; }' is not assignable to type 'IOptions & A<B>'.
Type '{ id: string; propA1: "1"; propA2: typeof MyClass; }' is not assignable to type 'A<B>'.
Types of property 'propA2' are incompatible.
Type 'typeof MyClass' is not assignable to type 'C<B>'.
Property 'propC1' is missing in type 'typeof MyClass'.

**Comment by RyanCavanaugh** [comment]
The expression you'd need to write here
```ts
    let result = test<A<B>>(() => ({
        id: '123',
        propA1: '1',
        propA2: MyClass
    }));
```
Is
```ts
    let result = test<A<B>>(() => ({
        id: '123',
        propA1: '1',
        propA2: new MyClass()
    }));
```

If you meant to provide a constructor function rather than a class instance, you should change your interface to be
```ts
    interface A<T> {
        propA1: '1';
        propA2: new() => C<T>
    }
```

**Comment by vascofernandes** [comment]
Thanks. 

I did not know about new () => C<T>.
That is what I want.

Again, thank you.
