### ISSUE TITLE
Auto emit types 

### ISSUE THREAD

**Issue by DominicBoettger** [Microsoft/TypeScript#9955]
Is it planned to emit the type metadata for every attribute on class level. Especially when defining a data model this would be very helpful. It would be great to be able to add something like a decorator @emitAllMetadata to the class and then the metadata for every attribute will be emitted.

``` js
@emitAllMetadata
class Myclass {
  public color: string;
}

let test = new Myclass();

console.log(Reflect.getMetatdata('design:type', test,'color'));
// output: string
```

I know it will create a lot of overhead when doing this for every class but especially in the backend where its's needed to verify data before storing in the database it could be very helpful.

**Comment by mhegazy** [comment]
We have no plans in changing or increasing the scope of the metadata emit feature.
