### ISSUE TITLE
Returning a new constructor from a class decorator does not type check.

### ISSUE THREAD

**Issue by fluffywaffles** [Microsoft/TypeScript#9961]
**TypeScript Version:**  2.0.0

**Code**

``` ts
function ReplaceConstructor (target: Function) : Function {
  return class Replacement {
    constructor (public a: string) { }
  }
}

@ReplaceConstructor
class A { }

console.log((new A('hello')).a)
```

**Expected behavior:**

Should type-check.

**Actual behavior:** 

Gives the following errors:

```
main.ts(7,1): error TS1238: Unable to resolve signature of class decorator when called as an expression.
  Type 'Function' is not assignable to type 'void'.
main.ts(10,14): error TS2346: Supplied parameters do not match any signature of call target.
```

The first error goes away with the following adjustment:

``` ts
function ReplaceConstructor () : ClassDecorator {
  return (target: Function) => class Replacement {
    constructor (public a: string) { }
  } 
}

@ReplaceConstructor()
class A { }

console.log((new A('hello')).a)
```

Both source files, when compiled and run in node.js, correctly output the string "hello".

**Comment by mhegazy** [comment]
Cause `Function` is not the same as `A` that you are decorating. a class decorator can not change the type of what it decorates.

I think you are looking for something like https://github.com/Microsoft/TypeScript-Handbook/blob/792592c8f7d36a45f3eb5d1f68fce655aa5c7f5d/pages/Decorators.md#class-decorators
