### ISSUE TITLE
`gulp lssl` needs more dependencies

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#9964]
Running `gulp clean; gulp lssl` results in compiler errors. (`jake clean; jake lssl` doesn't work either.)
The specific errors are:

    C:/Users/andy/work/typescript/src/services/utilities.ts(839,77): error TS2304: Cannot find name 'LanguageServiceShimHost'.
    C:/Users/andy/work/typescript/src/services/utilities.ts(839,77): error TS2304: Cannot find name 'LanguageServiceShimHost'.

**Comment by weswigham** [comment]
We don't run this as part of our CI (though we probably should, since it's part of our LKG), so it's easy for us to break this target without realizing it.
