### ISSUE TITLE
[Suggestion] tslib.es6.js and module bundlers

### ISSUE THREAD

**Issue by dmitrage** [Microsoft/TypeScript#9980]
**tslib Version:**  1.0.0

Now tslib.es6.js ([tslib](https://github.com/Microsoft/tslib) project) contains only ES6+ helpers. Including all helpers would allow using this file with module bundlers and benefit from tree-shaking while targeting ES5. 

Also, this file should probably be referenced in package.json _module_ field ([proposal](https://github.com/nodejs/node-eps/blob/master/002-es6-modules.md#51-determining-if-source-is-an-es-module), already supported at least by webpack).

**Comment by mhegazy** [comment]
Fixed by https://github.com/Microsoft/tslib/pull/5
