### ISSUE TITLE
Inconsistent behaviour of string union type with single element

### ISSUE THREAD

**Issue by federico-lox** [Microsoft/TypeScript#9986]
There is an inconsistency in the way the compiler treats string union types with a  single element:

**TypeScript Version:**  1.8.10

**Code**

```ts
declare class test {
    foo(val: "asd") // ERROR: Specialized overload signature is not assignable to any non-specialized signature.
}

declare class test2 {
    foo(val: "asd" | "dfg") // valid
}

declare class test3 {
    foo(val: string)
    foo(val: "asd") //valid
}

var n: "asd"; //valid
```

**Expected behavior:**
All the 4 cases should compile without error.

**Actual behavior:** 
The first case results in a compilation error.

**Comment by RyanCavanaugh** [comment]
This is no longer an error (`npm install typescript@next` if you'd like to verify)
