### ISSUE TITLE
Don't use environment variables for command line options

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#9988]
Jakefile and Gulpfile use `process.env` to store command line options. These can become confused when a real environment variable is defined that happens to share a name with one of our options.

**Comment by weswigham** [comment]
This was a feature that, AFAIK, people actually used. I'd poll the rest of the team to see if they actually use it or not. Also, it can't be removed from Jake, its part of its builtin argument parsing infrastructure. It can be removed from gulp, however, as it was only added to mimic Jake's functionality.

**Comment by andy-ms** [comment]
Since we don't have a `port` option any more (#9985), this is no longer an issue for me. Closing.
