### ISSUE TITLE
Errors in lib.d.ts with Visual Studio 2015 Update 3

### ISSUE THREAD

**Issue by kingua** [Microsoft/TypeScript#9989]
I have an application that was originally built on TypeScript 0.9.1. I have installed Visual Studio 2015 Update 3, updated my Windows PATH variable to C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.8 and added TypeScriptToolsVersion 1.8 to the .csproj.

The correct version of typescript is stored for intellisense at C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TypeScript

I receive the following errors in lib.d.ts:
![capture](https://cloud.githubusercontent.com/assets/1474053/17182179/45f3ab6a-53e8-11e6-9524-9060626e3dcf.PNG)

When running tsc -v globally as well as from C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.8 and C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.8, I get 1.8.34. When using the Visual Studio -> Help -> About, I get version 1.8.35.  This version mis-match seems like a red herring.

Any help or pointing in the right direction would be greatly appreciated as I've been unable to find this problem reported anywhere else and, as far as I can see, everything is installed correctly and pointed at the correct compiler.

Thanks.

**Comment by kingua** [comment]
The problem seems to have 'fixeditself' by deleting the .suo file in the solution directory, at least in terms of the build errors.  Sometimes the intellisense errors still pop up.

**Comment by mhegazy** [comment]
This happens when one of your files declare new properties on one of the DOM interfaces.
