### ISSUE TITLE
Error TS8014: 'property declaratons can only be used in a .ts file. ---- however, code is emitting correctly

### ISSUE THREAD

**Issue by saosebastiao** [Microsoft/TypeScript#9992]
**TypeScript Version:**  typescript@beta (2.0)

**Code**

```ts
// foobar.js
class Foobar {
    static foo = (x) => console.log(x);
    bar = "bar";
    print(){
        console.log(this.bar);
    }

}
let x = new Foobar();
Foobar.foo(x.bar);

```

output:
```ts
class Foobar {
    constructor() {
        this.bar = "bar";
    }
    print() {
        console.log(this.bar);
        console.log("haha");
    }
}
Foobar.foo = (x) => console.log(x);
let x = new Foobar();
Foobar.foo(x.bar);
//# sourceMappingURL=jstest.js.map
```

**Expected behavior:**

No error messages

**Actual behavior:** 
compiler output:
```
lib/jstest.js(3,5): error TS8014: 'property declarations' can only be used in a .ts file.
```

Should this error message be removed if the compiler is emitting correct output?

**Comment by andy-ms** [comment]
This looks similar to #6997 which should have been fixed. 

Try this:

    mkdir repro; cd repro
    npm install typescript@next
    echo "class Foo { static x = 1; y = 2; }" > foo.js
    node node_modules/typescript/bin/tsc foo.js --allowJs --out foo.compiled.js

Can you still reproduce the error?

**Comment by saosebastiao** [comment]
es5 output:
```
var Foo = (function () {
    function Foo() {
        this.y = 2;
    }
    Foo.x = 1;
    return Foo;
}());
```

es6 output:
class Foo {
    constructor() {
        this.y = 2;
    }
}
Foo.x = 1;
```

no compiler errors
