### ISSUE TITLE
ellipses for ...rest argument is not removed during compilation

### ISSUE THREAD

**Issue by webdori882** [Microsoft/TypeScript#9993]
**TypeScript Version:**  1.8.10

**Code**

```ts
  static start(...argumentArray: string[]) {

```

**Expected behavior:**
after the compilation:
static start(argumentArray) {

**Actual behavior:** 
static start(...argumentArray) {

which results in an error:
SyntaxError: Unexpected token ...

**Comment by sandersn** [comment]
Can you give a more complete example? When I paste the following into the Playground,

```ts
class C {
	static start(...args: string[]) {
		return 12;
	}
}
```

I then get the correct output: 

```js
var C = (function () {
    function C() {
    }
    C.start = function () {
        var args = [];
        for (var _i = 0; _i < arguments.length; _i++) {
            args[_i - 0] = arguments[_i];
        }
        return 12;
    };
    return C;
}());
```

Maybe you are targeting ES2015 instead of ES3 or ES5?

**Comment by mhegazy** [comment]
This sample seems to work fine. Please try `typescript@next` first, and if this still an issue, reopen and provide more context to be able to piece together a consistent repro.
